code/modules/projectiles/gun_system.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9352
:cl:
fix: Fix spawned shotgun not able to shoot
/:cl:

Fix spawned shotgun not able to shoot

---

code/game/objects/structures.dm

oops
:cl:
fix: Fix climbing
/:cl:

Fix climbing

---

code/modules/projectiles/ammo_datums.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9592
:cl:
fix: Fix bonus projectile not having IFF
/:cl:

Fix bonus projectile not having IFF

---

code/game/objects/machinery/doors/poddoor.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10666
:cl:
fix: Fix tadpole able to crush shutters
/:cl:

Fix tadpole able to crush shutters

---

code/modules/projectiles/gun_system.dm

Fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10635
You should not be able to shoot in a tarp
:cl:
fix: Fix being able to shoot in a tarp
/:cl:

Fix being able to shoot in a tarp

---

code/game/objects/machinery/doors/airlock_types.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/sentries.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10590
allow windup gun to shoot as a turret in general
:cl:
fix: Fix sadar turret not shooting
/:cl:

Fix sadar turret not shooting

---

code/datums/components/attachment_handler.dm

Title
2nd most costly proc ever, called tens of thousand time every round
:cl:
code: Attachment icon no longer update every icon change
/:cl:

Attachment icon no longer update every icon change

---

code/modules/projectiles/projectile.dm

Some dumb nerd put in an early return before the projectile starts actually processing, imagine that.
Projectiles actually travelling is fairly useful
:cl:
fix: fixed ghost projectiles
/:cl:

Fix ghost bullets

---

code/__DEFINES/mecha.dm
code/modules/vehicles/mecha/_mecha.dm
code/modules/vehicles/mecha/combat/marauder.dm

Remove mech mmi flag

---

code/modules/projectiles/gun_attachables.dm

Title
also fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10026
:cl:
fix: Fix wrong flag on shouldermount, causing gun to cycle too much
fix: Prevent shoulder-mount duel weapon firing
/:cl:

Fix wrong flag on shouldermount, causing gun to cycle too much

---

code/modules/mob/dead/observer/observer.dm

Reverts tgstation/TerraGov-Marine-Corps#10662
Caused https://github.com/tgstation/TerraGov-Marine-Corps/issues/10724

Revert "Turns lengthy else-if chain in /mob/dead/observer/Topic(href, href_list) into a switch"

---

code/controllers/subsystem/aura.dm
code/game/data_huds.dm
code/game/objects/machinery/overwatch.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_defines.dm

Just a followup to the refactor.
Optimizes some bits, makes mob emitter overlays update properly for external sources. Adds in requested default values for auras.
:cl:
code: Cleanup from aura refactor
/:cl:

Aura cleanup

---

config/config.txt

Wide screen on local

---

code/modules/mob/living/carbon/xenomorph/death.dm

They'd just go forever
fugbix
:cl:
fix: Dead xenos stop emitting pheromones
/:cl:

Stop pheromones on death

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

I played AI and I noticed a bunch of issues, so I took to StrongDMM and fixed them. And more that I found as I went on.
It makes things look more polished, and more logical. No more weird dark spots, or missing tiles under some doors.
:cl: Targeting Computer 9.6
fix: fixed some missing or misplaced cameras, firelocks, lights, apcs, holopads and wires on POS.
/:cl:

Updates Pillar of Spring map to fix some issues with misplaced or missing cameras, firelocks, lights & APC's.

---

code/modules/clothing/shoes/marine_shoes.dm

In some situations, SOM shoe sprites would go invisible. This probably fixes it, by making the loaded shoe consistant with how the loaded marine shoe works.
Barefoot bandits are gross.
:cl:
fix: fixed SOM shoes sometimes going invisible
/:cl:

SOM shoe fix

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm

Hunter's disguise description tells you how to select a disguise target.
I can't see anywhere in-game that says how to use it, and I regularly saw people asking how to use it. So, it's in the description now.
:cl:
fix: Hunter's Disguise description tells you how to select a target.
/:cl:

Clarifies description on Hunter's disguise

---

code/game/objects/machinery/squad_supply/supply_console.dm

Text was wrong. Said 1 minute, but it is 30s in game.
Fixes are great.
:cl:
fix: fixed a wrong line about time regarding drops.
/:cl:

Correct bit of wrong text with supply drop console

---

code/datums/gamemodes/game_mode.dm
code/datums/round_statistics.dm
code/game/objects/machinery/mortar.dm

Mortar & Howitzers go boom. It would be nice to know if there has been like, 5 shots or 50 during a particular round.
Stats good. Not a huge performance impact given we track bullets fired.
:cl:
add: Added mortar & howitzers shots to end round.
/:cl:

Add mortar & howitzer shots to end game stats

---

code/datums/quick_load_outfits.dm

As my boy Xander pointed out, some of the loadout descriptions in Combat Patrol are a bit vague if you're not already familiar with what guns are what.
Updated loadout descriptions to describe what kind of weapon all guns are, and added some more useful description to explain certain weapon features, such as the V-31's rail launcher not detonating under 3 tiles, and the V-21 having a variable rate of fire.
:cl:
qol: Combat Patrol: Made some loadout descriptions clearer
/:cl:

Combat patrol: Loadout description improvements

---

code/__DEFINES/obj_flags.dm
code/_onclick/hud/screen_objects/screen_objects.dm
code/datums/elements/riding.dm
code/game/atoms.dm
code/game/objects/effects/effect.dm
code/game/objects/items.dm
code/game/objects/objs.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm
code/modules/mob/mob_defines.dm
code/modules/projectiles/projectile.dm

Could make projectile systems less expansive
:cl:
code: Made projectile maybe less expansive performance wise
/:cl:

Projectile performance improvement

---

code/game/objects/structures.dm

Reverts tgstation/TerraGov-Marine-Corps#10665
I don't have sprites for toggle, reverting until I get them

Revert "Add auto climbing"

---

_maps/map_files/Sulaco/Sulaco.dmm

After more AI playing, and fixing some stuff on the POS, i went on a quick tour of the sulaco.
This pr : 
- Fixes some missing firelocks & orientation,
- Missing firealarms
- Missing lights
- Weirdly packed together things spots.
Pain
:cl:
fix: fixed map oddities on the sulaco regarding firelocks, lights, apc's and fire alarms. Again
/:cl:

More sulaco fixes & patches.

---

code/datums/components/attachment_handler.dm

Wrong list index
fixes #10783 
:cl:
fix: Prevented replacing unremovable attachments
/:cl:

Fixes unremovable attachments

---

code/modules/mob/living/silicon/ai/say.dm

This PR makes it so the AI gets a little message of what it sent in the vox system.
It follows the convention of other communication options, from speech to announcements : You can read what you sent
:cl:
qol: made the AI able to read what it sent into the vox system
/:cl:

Give the AI a recap of vox messages

---

code/controllers/subsystem/persistence.dm

Adds SOM ballistics as seasonal weapons. I have no idea if these will be balanced, but 🤷 they should be fun at least.
More seasonals
:cl:
add: Added SOM ballistic weapons to the seasonal rotation
/:cl:

SOM seasonals

---

_maps/map_files/Minerva/TGS_Minerva.dmm

Minerva needs some love and detailing. 
- Better cameras placement is one. Many of them were floating in the air. I removed bathroom cameras.
- I added some more holopads for the AI coverage.
- I redid some of the preps because it wasn't symetrical. 
- I also added more catwalks for disposal pipes. 
Prettier map.
:cl:
fix: fixed some floating and other nonsensical cameras on minerva
/:cl:

Various minerva fixes

---

.gitignore
tools/hyperscale_converter/ReadMe.txt
tools/hyperscale_converter/converter.py

Adds a python script to /tools that will convert greyscale sprites to hyperscale ones.
the output folder was added to .gitignore
This will help spriters to make hyperscale since converting greyscale to hyperscale will no longer be manual.

Adds a tool for converting greyscale sprites into hyperscale sprites.

---

code/game/objects/items/scanners.dm

I didn't know this stuff was still in the codebase, honestly. Not usually available but they spawn in on a couple maps.
Minor cleanup so you don't get reagent paths spat at you.
:cl:
code: Cleaned up reagent scanner/mass spectrometers.
/:cl:

Mass spectrometer/reagent scanner cleanup

---

code/datums/jobs/squads.dm

Fixes SOM squad preferences.
Some people mentioned some funny errors they were getting related to squads when joining combat patrol, so this may fix that also.
Bug fix good
:cl:
fix: SOM squad preferences actually work
/:cl:

SOM squad preferences actually work

---

code/modules/mob/living/blood.dm

I thought I put this in the last pr but apparently I neglected to commit it.
path displaying ingame bad
no changelog

Spectrometers again

---

code/datums/quick_load_outfits.dm
code/game/objects/machinery/vending/quick_vendor.dm
code/modules/clothing/modular_armor/modular.dm
code/modules/projectiles/guns/rifles.dm

Some new loadouts plus tweaks.
As always, let me know if you have any ideas/suggestions.
- Adds an AR-18 scout loadout to TMGC (light armour/shield)
- Adds MPI loadouts to SOM veterans and SL's
- Buffs the SH-15 shocktrooper loadout with Tyr II for slightly better armour and mobility
- The two machinegun loadouts for TGMC now have half of their sandbags filled roundstart
- Increased the quantity and tweaked the types of grenades over a whole bunch of different TGMC loadouts (usually at the expense of a box of ammo)
- Some more C4 on certain marine SL loadouts
- Shield loadout gets a single extended SMG-25 mag
- SOM engie and medic MPI loadouts no longer have a UGL (MPI is actually rather good as it turns out), the medic also gets an extinguisher
- The engies that have razorburn grenades …

Combat Patrol: The loadouts just keep coming

---

code/datums/quick_load_outfits.dm
code/game/objects/items/storage/holsters.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/specialist.dm
code/modules/projectiles/magazines/specialist.dm

Edit: Made a new shell instead of changing the light shell.
Added the low impact shell, similar to the light explosive shell.
Reduced pen from 50 to 15, so it has less ggnore potential.
Reduced blind range from 5 to 3, for less AOE ggnore potential.
Additionally changed the RR loadout in Combat Patrol to only contain low impact RR shells... to remove the ggnore potential of HE shells.
Also just cleaned up some duplicate vars.
Less ggnore
:cl:
add: Added a low impact shell for the RR, with less direct hit damage and blind range
balance: Combat Patrol: RR loadout only has low impact RR shells
/:cl:

New RR shell for Combat Patrol

---

_maps/shuttles/minidropship.dmm

This add a camera to the tadpole. It should be decently out of the way, looking like a dashcam
Fewer moments of wondering WHERE THE HELL IT IS.
:cl:
qol: Added a camera to the tadpole, like alamo. 
/:cl:

Add a camera to the tadpole

---

code/modules/projectiles/guns/mounted.dm
code/modules/projectiles/magazines/mounted.dm

Fixes #10857
No ingame impact.
Bug fix good.
:cl:
fix: MG-27 actually uses 10x27mm rounds as described
/:cl:

MG-27 actually uses 10x27mm

---

code/modules/projectiles/projectile.dm

Title. Based on projectile perf improvment.
closes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10791
:cl:
fix: Fix piercing projectile hitting the same atom multiple times
/:cl:

Fix piercing projectile hitting the same atom multiple times

---

tools/WebhookProcessor/github_webhook_processor.php

Update webhook to tg

---

strings/tips/HvH.txt

Adds some tips that are relevant to HvH. Leave comments if you have any more ideas.
I assume keyholders need to do some config thing to actually use this new file, I couldn't see anything in code.
More useful tips.
:cl:
add: Adds some tips of the round for HvH
/:cl:

Combat Patrol tips of the round

---

code/__HELPERS/global_lists.dm

Funni brave misclick merge.
Makes the new HvH tips actually show up.
Tips are useful when they are visible

HvH tips actually load

---

code/modules/mining/remote_fob/remote_fob_computer.dm

Pretty self-explanatory, the AI can now use the FOB building console.
This adds a single line of code.
It was a thing before and I don't see any reason as for why the AI shouldn't be able to do this. It's great when the server is lowpop. (This is a bugfix anyways.)
fixes #10803
:cl:
fix: AI can now use the FOB building console again
/:cl:

AI can now build the FOB again

---

code/modules/mob/dead/observer/observer.dm

- This PR makes it so vallhalla copies your prefs when you spawn in, in other words you are your character in valhalla
I think it's nicer to be your character rather than some random gen with pink hair and a cyan beard. 
:cl:
qol: You are now your character when spawned into vallhalla
/:cl:

You are now your character when spawned into vallhalla

---

code/modules/mob/dead/observer/observer.dm

- Fixes the valhalla loadout vendor not working
- I am dumb
Half the point of valhalla is setting up the loadout vendor, bleh.
:cl:
fix: Fixed the valhalla loadout vendor not working
/:cl:

Fixes the valhalla loadout vendor not working

---

code/__HELPERS/unsorted.dm
code/game/atoms.dm
code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/guns/flamer.dm

Edit: I have no reduced the flame duration of the wide nozzle by 20%, which means the wide nozzle will no longer be able to kill walls in a single click. You can still just click twice in a row to kill them, but it means you'll absolutely blast through fuel like nothing else.
I think making any flamer be able to kill walls in one click was a questionable change, but I'll reserve changing overall flamer behavior to another pr as that's out of scope.
So this was a rabbit hole of code to rework, guh.
Changed the way the wide nozzle calculates the turfs to burn, giving it more of a natural icecream cone sort of shape instead of a wide pyramid.
https://user-images.githubusercontent.com/7869430/187071890-a785afd5-f6ee-426f-9cbc-9da550b455fa.mp4
This should hopefully be actually useful, compared …

Improves the  wide flamer nozzle and related refactor

---

code/modules/projectiles/ammo_datums.dm

Slight buff to GL-54 airburst grenade slow/stagger, removed it from incend entirely, and made it actually work properly.
Reduced the pointless accuracy variance.
Makes regular airburst actually ok at support compared to incendiary.
:cl:
balance: Improved GL-54 airburst stagger and slow slightly, removed it entirely from incendiary
/:cl:

GL-54 tweaks

---

code/game/objects/items/marine_gear.dm

There was a typo. It is gone now.
Good spelling is nice.
:cl:
spellcheck: fixed a typo on the mint protein bars
/:cl:

Fixes a small typo with the mint protein bar

---

code/modules/projectiles/gun_attachables.dm

I forgot to push a commit, whoops.
Fix my mistake.
:cl:
/:cl:

Fixes standard flamer nozzle

---

code/game/objects/items/weapons/shields.dm

You can now bash your shield with any weapon, not just batons.
This sickening, game breaking issue needs to be fixed ASAP, speed merge pls.
~Bash bash bash~
Not being able to bang your shield with a gun is dumb.
:cl:
add: You can now bash your shield with any weapon, not just batons
/:cl:

Shields can be bashed with any weapon instead of just batons

---

code/modules/factory/machines.dm

Just a little wrenching noise.
Sounds good.
:cl:
qol: Wrenching noise for wrenching req factory machines
/:cl:

Wrenching noise for wrenching req factory machines

---

code/datums/components/riding/riding_mob.dm
code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm

Larva could not ride crushers before, with this PR they can.
https://imgur.com/a/ltI9BR6 (low quality imgur gif)
Larva on da crusher, what he gonna do?
:cl:
expansion: Xeno larva are now able to ride crushers.
/:cl:

Makes larva able to ride crushers

---

code/modules/projectiles/sentries.dm

Sorry guys, party is over.
You can no longer disassemble, remove the ammo from, or use the interface of a hostile turret.
If the turret IFF matches your own, or it doesn't have IFF, you can interact with them normally.
Funny turret theft is probably not the greatest.
:cl:
fix: You can no longer disassemble, remove the ammo from, or use the interface of a hostile turret.
/:cl:

Sentry fixes

---

code/controllers/subsystem/pathfinder.dm
code/datums/components/ai.dm
code/modules/ai/ai_behaviors/ai_behavior.dm
code/modules/mob/living/living.dm

Prevent the weird movement when a lot of ais are escorting an atom. They were bumping into each other so it looks like some of them were teleporting
Also fix a bug with escorting atom. Affect hunter and widow
Also fix some dead ai moving (if the player logs out)
Bugfix
:cl:
fix: Fix ais seemingly teleporting
fix: Dead ai moving too much
/:cl:

Fix some weird ai movements

---

code/datums/components/_component.dm

https://github.com/tgstation/tgstation/pull/69638/files

Registersignal microopts

---

code/datums/looping_sounds/_looping_sound.dm

Funni bug meant this var didn't ever work, and when I ported the refactor, it turns out this var has never worked on TG either.
Max_loops will now actually work as intended, instead of stopping the sounds from playing at all.
Bug fix good.
:cl:
code: minor looping_sounds bugfix
/:cl:

looping_sounds maxloops fix

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

The POS has no fireaxe locker.
This PR adds it.
🪓 
:cl:
add: Added the Fire Axe to Pillar of Spring
/:cl:

Give the POS a fireaxe locker

---

code/_onclick/hud/rendering/plane_master.dm

https://github.com/tgstation/tgstation/pull/69778

Fix a bug that popped up on newer byond vers

---

code/__DEFINES/misc.dm
code/game/turfs/space.dm

Did not benchmark used https://github.com/tgstation/tgstation/pull/69079/files for some of these, removed update icon on top of that
:cl:
code: Optimised some loading
/:cl:

Space load optimisations

---

code/game/objects/structures/droppod.dm

The AI gets a small notice about where a drop pod is going, with who. 
Deadchat gets it, so why not the AI?
:cl:
qol: Gave the AI a notification for drop pod usage. 
/:cl:

Add pods to the list of notifications the AI get

---

code/datums/jobs/job/shipside.dm

Fix copy paste woopsie

---

code/modules/admin/panels/player_panel.dm
code/modules/admin/topic.dm

Title
Consistency good.
:cl:
admin: adds Gorger to the admin player panel tab
/:cl:

Adds Gorger tab to Admin Player Panel

---

code/modules/admin/panels/player_panel.dm
code/modules/admin/topic.dm

Title
Consistency good.
:cl:
admin: adds Combat Robot to admin player panel
/:cl:

Adds Combat Robot to admin panel

---

code/datums/components/ai.dm

Title
:cl:
fix: Fix ai not stopping when controlled by a player
/:cl:

Fix ai not stopping when controlled by a player

---

code/modules/admin/admin_verbs.dm

web edit fix, cleaning up message log for #10681
:cl:
admin: Set-Xeno-Buffs verb percentage logging now accurate.
/:cl:

Fix Set-Xeno-Buffs Logging

---

code/game/atoms_movable.dm
code/modules/mob/camera/camera.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/mob/living/living.dm
code/modules/shuttle/on_move.dm
code/modules/vehicles/mecha/_mecha.dm

We had no way to give push priority (Which mechs need) because for some reason we only have a half-implemented move_resist
Idk why the safe throw was commented out it's only used for shuttles so whats the worst
:cl:
code: Added push priorities
/:cl:

(Re?)adds move_force

---

code/modules/projectiles/guns/shotguns.dm

Reverts tgstation/TerraGov-Marine-Corps#10990
Tye was going to close this PR, but forgot to do it before it got merged.
For the record I don't think giving the V-51 burst mode to ggnore people is a good idea for a HvH weapon.

Revert "buff the som shotgun"

---

code/modules/ai/ai_behaviors/ai_behavior.dm

Fix overriding signals warning

Fix overriding signals

---

code/game/objects/items/reagent_containers/hypospray.dm
code/game/objects/machinery/vending/new_marine_vendors.dm
code/game/objects/machinery/vending/vending.dm

Title
:cl:
fix: Fix some items map text overflowing on the right
/:cl:

Fix some items map text overflowing on the right

---

code/__DEFINES/skills.dm
code/datums/jobs/job/clf.dm
code/datums/skills.dm

Gave CLF leaders a skill set, which is slightly worse than normal SL's, but they can at least give orders now.
Also updates some leader define comments.
Leader having leader skills is good.
:cl:
balance: CLF team leaders have been put through a leadership course and can now issue orders
/:cl:

CLF SL skills

---

code/game/objects/items/weapons/shields.dm

So I'm a dumb dumb and didn't realise that the default coverage of shield items against all projectiles is... 100%
i.e. until your shield gets degraded, it absorbs all incoming projectile damage.
Changed it to instead block 60% of bullet, laser and energy damage, and reduced fire block from 80 to 70.
This should have very little impact on HvX but is rather needed for HvH.
Full damage invulnerability is not ideal.
:cl:
balance: Reduced the percentage of damage absorbed by shields for bullet, lasers, energy and fire
/:cl:

Shield rebalance

---

code/game/objects/structures/droppod.dm

It was saying dirt or snow. Now it should say Cargo or something.
Fix silly code. 
:cl:
fix: Fix the AI not having correct locations for drop pods
/:cl:

Give the AI correct area for drop pod landing

---

code/__DEFINES/construction.dm
code/game/objects/machinery/computer/camera_advanced.dm
code/modules/mining/remote_fob/remote_fob_actions_misc.dm
code/modules/mining/remote_fob/remote_fob_computer.dm
code/modules/mining/remote_fob/remote_fob_fobdrone.dm

Rewrites remote AI eye movement code so i have finer control over it (and it doesn't skip tiles anymore at high acceleration)
FOB Drone now uses bubble alerts , and is slower because its way too fast.
Draft because i still have to figure out how to make the drone face an atom the controller clicks on , as an extra qol.
Edit : figured out.
More QoL, easier life for engies.
:cl:
qol: Slowed down the FOB Drone, gave it bubble alerts and fixed double .remaining messages
qol: Drones now face the direction of any turf you click.
code: Rewrote the remote AI eye code to support more configurable move_delays
code: Rewrote the remote AI eye acceleration , it now gets removed on direction change.
/:cl:

Rewrites remote AI eye movement code , general FOB Drone QOL

---

code/game/objects/items/reagent_containers/glass/bottle.dm

Title
Same reasoning as https://github.com/tgstation/TerraGov-Marine-Corps/pull/10019. With infini restock, this just makes things tedious, and is relic from where chems were limited.
:cl:
qol: Oxycodone bottle capacity changed to 60u
/:cl:

Changes oxycodone bottle capacity to 60u

---

code/datums/skills.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm

Adds mech skill requirement

---

code/_compile_options.dm

Bump byond ver

---

code/datums/jobs/job/shipside.dm

Now with Tivi approval.
Mech Pilot scales with Squad Engineer/Corp ranks, but takes a bit more time.
Spawn in blurb changed from the field commander one.
Mech pilot rank being so high makes little sense in the setting overview, and gameplay wise this makes more sense.
:cl:
spellcheck: MPs have a unique spawn in blurb.
tweak: MPs have Squad Engineer/Medic rank scaling. (E3->E4->E5)
/:cl:

MPs rank and spawn in blurb changes.

---

code/controllers/subsystem/persistence.dm
code/game/objects/machinery/vending/marine_vending.dm

Adds the two holsters for the mp and seasonal smg
Drip, i guess, and in the case of the smg25 something to carry it and make it worth it over the p90, which is generally better all around.
:cl:
add: added holsters for the mp19 and smg-25
/:cl:

Mp holster in clothing vensor, smg25 holster in seasonal

---

_maps/shuttles/minidropship.dmm

tadpole now has 3 tiles of cades on all sides
more space for tadpole
:cl:
balance: slightly more space for tadpole
/:cl:

tadpole 3 tile cade all sides

---

code/modules/projectiles/sentries.dm

Fixes an oversight, due to there being multiple ways to unload a turret. Guh.
Bug fix good
:cl:
fix: fixed a bug that let you remove the ammo from hostile turrets
/:cl:

Bug fix for removing ammo from hostile turrets

---

code/modules/vehicles/mecha/_mecha.dm
code/modules/vehicles/mecha/mecha_defense.dm

https://github.com/tgstation/tgstation/pull/69038/files

Mech destruction fixes

---

code/modules/vehicles/mecha/equipment/weapons/mecha_ammo.dm
code/modules/vehicles/mecha/mecha_defense.dm

https://github.com/tgstation/tgstation/pull/69807/files

mech ammo fix and desc

---

code/__HELPERS/pronouns.dm
code/modules/vehicles/mecha/equipment/mecha_equipment.dm
code/modules/vehicles/mecha/mecha_defense.dm
code/modules/vehicles/mecha/mecha_mob_interaction.dm

https://github.com/tgstation/tgstation/pull/67411/files

Some mech damage fixes

---

tgui/packages/tgui/interfaces/Mecha/UtilityModulesPane.tsx
tgui/packages/tgui/interfaces/Mecha/data.ts
tgui/packages/tgui/styles/interfaces/UtilityModulesPane.scss
tgui/packages/tgui/styles/main.scss

https://github.com/tgstation/tgstation/pull/68167/files#

mech utility panel changes

---

code/game/objects/structures/prop.dm

Adds mech props

---

code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/gun_system.dm

replaces some stat with incapacitated
:cl:
fix: Fixes being able to shoot while stunned/unconcious
/:cl:

Fixes being able to shoot while stunned/unconcious

---

code/controllers/configuration/entries/general.dm
code/game/world.dm
config/config.txt

Game update chat config

---

code/modules/vehicles/vehicle_actions.dm

https://github.com/tgstation/tgstation/pull/70151

Destroy mech abilities port

---

code/modules/vehicles/mecha/_mecha.dm

Xenos can hit mechs

---

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm

Fixes mech accuracy

---

code/modules/vehicles/atv.dm
code/modules/vehicles/mecha/mecha_defense.dm

https://github.com/tgstation/tgstation/pull/68786/files
https://github.com/tgstation/tgstation/pull/70167/files

Mech takes time to repair

---

_maps/map_files/combat_patrol_base/combat_patrol_base.dmm
code/game/objects/structures/prop.dm

mech prop for tgmc patrol base
mech hype i guess
:cl:
add: mech prop to patrol base
/:cl:

tgmc patrol base mech prop [MDB Ignore]

---

code/game/objects/items/explosives/grenades/flashbang.dm

Makes flashbangs use hearers() instead of get_hear() to be a little more efficient, and cleans up some comments.
Makes the max range a var instead of a hardcoded number.
No functional changes.
Slightly better code.
:cl:
code: cleaned up a bit of flashbang code
/:cl:

Minor flashbang code cleanup

---

code/game/turfs/walls/wall_types.dm

Just some lobby art.
Someone can probably do the writing less shittily but eh
More art gud
:cl:
imageadd: added a new lobby artwork
/:cl:

More lobby art

---

code/game/atoms_movable.dm
code/modules/lighting/lighting_atom.dm

Concatonate into 1 proc and add vis_locs = null

Movable destroy improvements

---

code/modules/mob/mob_helpers.dm

Title
Stutter removing a random letter just makes it look like other people can't type rather than actually looking like stuttering and is generally annoying
:cl:
qol: stutter no longer removes a random consonant sometimes
/:cl:

Stutter no longer removes random letters

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/mob/living/carbon/xenomorph/charge_crush.dm
code/modules/vehicles/_vehicle.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm
code/modules/xenomorph/xeno_structures.dm

Mechs
Mechs
:cl:
balance: All vehicles can now be crushered, punched by warrior, and hit by acid smoke
/:cl:

More xeno abilities usable on vehicles

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

https://github.com/tgstation/TerraGov-Marine-Corps/pull/11133#issuecomment-1266778159
:cl:
fix: wraith will now properly send mobs inside objects that are banished instead of just dumping them out
/:cl:

Wraith's banksh will now properly handle mobs in objects

---

code/datums/skills.dm

haha woops, forgot to remove this

Synths no longer have mech skill

---

code/modules/ai/ai_behaviors/xeno/xeno.dm

AI can directly slash inside mechs/closets etc if you're inside, now it just gets the topmost and attacks that
:cl:
fix: AI will no longer attack inside of objects, instead it will aim for the outermost container of it's target
/:cl:

AI will no longer attack inside of objects

---

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm

Nani has said admins are now banned from spawning mechs outside of the dome and im basically done so it's time to remove this

Remove mech admin blocker

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

That ain't it, chief.
This is it, chief.
:cl:
fix: MP computer in MP room in PoS
/:cl:

Fix MP's computer in PoS

---

code/__DEFINES/_click.dm
code/modules/vehicles/mecha/_mecha.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm

this needs to be widened out to most click code but i cant be assed to do everything rn
https://github.com/tgstation/tgstation/pull/70369/files

Simultaneous click fix

---

code/__HELPERS/unsorted.dm
code/datums/chatmessage.dm

ported from tg cant find the pr anymore
Runechat works even in mechs, droppods or closets!!
:cl:
add: runechat now works when you are inside something
/:cl:

Runechat shows on top of whatever you're in

---

_maps/map_files/Theseus/TGS_Theseus.dmm
code/game/objects/machinery/door_control.dm
code/game/objects/machinery/doors/poddoor.dm

Prepare for the MP
Soon mech is here
:cl:
expansion: add MP room in Theseus
/:cl:

MP is back in Theseus

---

code/modules/vehicles/mecha/mecha_movement.dm

Kuro pointed out this mitigated a lot of the direction based mechanics
Now instead they will randomly pick right or left and then face the direction you were moving towards

Makes mechs unable to immediately flip around

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

Code was kinda bad
:cl:
code:  Ravager will now ravage all items it can slash
/:cl:

Ravager ravage refactor

---

code/modules/admin/topic.dm

"Force Event" was nonfunctional due to a typo, I fixed it since I needed to test events.
Fixes good, if we merge more events it might be nice to verify they actually work.
:cl:
fix: The force event verb is now functional
/:cl:

Fixes a bug in the "force event" verb

---

code/modules/events/stock_uptick.dm

It's a new event, Tivi wants more of them and I sat down and made some.
Stock uptick is a random boost to supply points, it's tied to population and capped at 125 max points.
More events good.
:cl:
add: Added a new event, stock uptick
/:cl:

Adds a new event, stock uptick

---

code/game/objects/machinery/doors/poddoor.dm

From what I can tell this should cover all future cases instead of having to manually fix bumpopen every time we add something using it
:cl:
fix: fixed shutters being bump-openable sometimes
/:cl:

Should fix being able to bump open shutters

---

code/modules/projectiles/ammo_datums.dm
code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm

Various nerfs to different mech guns, and a fix to GL
Some mech guns are way too oppresive, this should remedy that
:cl:
balance: Some mech guns nerfed
/:cl:

Mech gun nerfs

---

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm

Fix mech armor having doubled values
Immortal mechs bad
:cl:
fix: Mechs are no longer immortal
/:cl:

Mech Armor fix

---

code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm

It had the flag, for AI use, I removed it
:cl:
fix: AI can no longer touch the mech console
/:cl:

AI no longer can touch mech console

---

code/modules/mob/living/carbon/human/human_defines.dm

very ez fix
:cl:
fix: fixed ravage not working on humans
/:cl:

Fix ravage

---

.github/workflows/ci_suite.yml
.github/workflows/generate_documentation.yml
.github/workflows/update_tgs_dmapi.yml

https://github.com/tgstation/tgstation/pull/70463

Updates ci

---

code/modules/vehicles/mecha/combat/gygax.dm

Now doesnt layer over things it shouldnt

Fix mech ability module layering

---

code/modules/vehicles/mecha/equipment/weapons/weapons.dm

Mech launchers such as GL will now respect cooldowns, power use & will update HUD/play sound

Mech launcher fix

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Mech will now use the short banish duration

---

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm

heavily nerfs chance and only lets consequential ones happen

Mech Internal damage nerf

---

code/modules/projectiles/gun_system.dm

Fixes an issue causing some guns not to display their mob sprites.
The revert to hyperscale reverted changes made to guns since hyperscale was first introduced.
This broke mob sprites for the majority of SOM weapons.
Invisible guns bad
:cl:
fix: fixed certain guns not displaying their mob sprites
/:cl:

Gun mobsprite fixes

---

code/game/objects/structures/sensor_tower.dm
code/modules/projectiles/gun_system.dm

A couple of balloon alerts are broadcast to all human viewers, but the wording says you are doing something. Changed it to be more genericly descriptive of what's happening.
Clear alerts
:cl:
fix: Some minor balloon alert fixes for sensor cap
/:cl:

Sensor cap balloon alert tweaks

---

code/_compile_options.dm
code/modules/client/client_procs.dm

These should be fine, dunno about latest
:cl:
code: changed recomended versions
/:cl:

Update byond max versions

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Title.
Map corruption did this, so time to fix that.
:cl:
fix: missing keeper missle in PoS
/:cl:

Fix missing keeper missle in PoS

---

code/game/turfs/walls/wall_types.dm

Awesome new lobby art by Lich.
Art good
:cl:
imageadd: New lobby art
/:cl:

Droppod lobby art

---

code/modules/reqs/supplypacks.dm

I uh, didn't actually test the req side of loot boxes. I forgot to put it in an actual category, honk.
Loot boxes will now be actually orderable.
Working code good.
:cl:
fix: Loot boxes are now actually orderable
/:cl:

makes loot boxes actually available in req

---

code/modules/clothing/head/helmet.dm

Cleans up helmet vars a little

---

code/modules/vehicles/mecha/_mecha.dm
code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm

Rebalances some mech energy numbers
liguana
:cl:
balance: Mech's no longer use all of their energy using the actuator overload, efficiency module now does what it says, laser burst rifle uses less energy per shot
/:cl:

Energy rebalance

---

code/modules/clothing/suits/marine_armor.dm

Revive #11309.
It's a good PR.
:cl:
qol: Combat robot armors can now store instruments and other things that the modular armors can. Some things have been axed from being put on the suit-storage slot, however, like oxygen tanks.
/:cl:

Makes suit storage consistent with armors 2.0

---

CONTRIBUTING.md

Some instructions on how to compile for Linux

Update contributing md with rust instructions

---

code/modules/clothing/modular_armor/attachments/modules.dm

Removes the slowdown off Arrowhead, the energy shield module.
Its currently pretty bad, it drops you down 2 armor levels and has slowdown making it difficult to use at all other than tanking spits and mimir is better at that.
:cl:
balance: Arrowhead no longer has slowdown.
/:cl:

Arrowhead no longer has slowdown.

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm

- Preweeds the not snowy parts of ice colony
Most played maps start preweeded, with a few outliers (which I'll get to, probably). Being consistent about that is nice.
:cl:
expansion: The non-snowy parts of ice colony now start weeded
/:cl:

Preweed Ice Colony

---

code/controllers/subsystem/vote.dm

Fixed a vote bug where the server would restart to load the correct whitelisted ship (or ground) map, when it was already on that map.
Honk.
Bug fix good.
:cl:
fix: Fixed a voting bug with whitelisted maps
/:cl:

Whitelist map vote bugfix

---

code/datums/gamemodes/civil_war.dm
code/datums/gamemodes/combat_patrol.dm
config/shipmaps.txt

I accidentally deleted a couple of changes when I removed some debugging changes that I didn't mean to.
Changing gamemode between combat patrol and sensor cap pregame will no longer incorrectly trigger a restart.
Also changed the placeholder shipmap config, as these are the settings those ships have on the live server (and actually need to function properly) and I was scratching my head for a minute before I remembered this, when trying to debug. 
Not an actual config change, again the live server already has these settings.
Funni vote bug bad
:cl:
fix: fixed another minor vote bug
/:cl:

Fix another vote issue

---

code/modules/vehicles/mecha/mecha_defense.dm

~750 seconds to full repair isnt walance

Mech repair up to 150 from 10

---

code/modules/vehicles/mecha/combat/gygax.dm

https://github.com/tgstation/tgstation/pull/70683

Fix leg overload movespeed resetting

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Researcher's zone. They have dedicated chem lab, they get their own stuff.
:cl:
add: add grinder in PoS'  research lab
/:cl:

add grinder in research

---

code/modules/reqs/supplypacks.dm

Dispenser can now be ordered. 40 points.
Allows for a way to get replacement rather than ghosting out of the round because you got 80% of your items deleted by some unga not realizing it can catch bullets. Price high enough that it's not a roundstart concern other than funny FCs hoarding all the points.
:cl:
add: Dispenser can now be ordered from req. 40 points.
/:cl:

Adds dispenser to req

---

code/controllers/subsystem/processing/processing.dm
code/game/objects/effects/aliens.dm
code/modules/vehicles/mecha/equipment/tools/other_tools.dm

Spooky didnt implement it properly now it is

Fix deltatime

---

code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm

Fixes spiderlings going to sleep after killing robots.
No time to sleep.
:cl:
fix: fixed spiderling AI turning off after killing combat robots
/:cl:

Fixes spiderling AI bug

---

code/datums/jobs/job/other.dm

Makes the Pizza ERT and job actually spawn with Pizza in hand.
Imagine my surprise when the Pizza ERT didn't even spawn with pizzas. This should fix that.
:cl:
add: Gives the Pizza Delivery people Pizza.
/:cl:

It's Pizza time.

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

Bit copy-pasty but it'll do the trick.
This is unintended.
:cl:
fix: Fixes ravage being able to move dead bodies
/:cl:

Fixes ravage being able to move dead bodies

---

code/modules/vehicles/mecha/equipment/weapons/weapons.dm

makes mecha weapons automatically reload if the mecha is standing still
tivi say zaro do
:cl:
qol: mech now auto reloads once you have 0 bullets in magazine and are standing still
/:cl:

auto-reload for mech

---

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm

It was a bit too punishing
:cl:
balance: mech no longer gets control loss
/:cl:

Mech no longer gets control loss

---

_maps/map_files/Theseus/TGS_Theseus.dmm
code/game/objects/machinery/door_control.dm

Fix a rogue light.
Expand dorms to make room for a BIGGER req.
Change req a bit to make it appealing to my eyes and inspired by psykzz's work.
Put vendors near Alamo. The future is now.
Fix mech blast doors.
Theseus needs a little loving. Also, this little loving comes with fixing doors.
:cl:
fix: Fix a rogue light in Theseus req.
fix: Fix mech blast doors.
expansion: Expand Theseus dorms to make room for a BIGGER req.
expansion: Change req a bit to make it appealing to my eyes and inspired by psykzz's work.
add: Put vendors near Alamo. The future is now.
/:cl:

Theseus polish and fix

---

code/modules/vehicles/mecha/equipment/weapons/mecha_ammo.dm

Tittle
Having to click 10548 times to reload my mech when the ammo is infinite is ???
:cl:
qol: Mech ammo boxes now hold more ammo so you need less clicks to refill your mech
/:cl:

Buffs the ammount of ammo mecha ammo boxes have

---

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm

title, fixes #11406 
It isn't.
:cl:
fix: unmeltable walls removed from Warden Office for Prison Station.
/:cl:

Prison Station East LZ heavy reinforced walls removed

---

code/modules/vehicles/mecha/mecha_defense.dm

Mech's healing nerf from 150 to 100.
Tivi's request and not cheesing mech's healing.
:cl:
balance: Mech's healing nerf from 150 to 100.
/:cl:

Nerf Mech healing

---

code/modules/projectiles/guns/specialist.dm

Scope added to acceptable attachments for railgun, and offset for railgun attachments fixed.
The Railgun is in such a sorry state, a supposed railgun but couldnt even fire in long range. This will fix that, making the railgun more viable than the sad state it is in now.
:cl:
add: Railgun can now use a railscope.
fix: Railgun rail attachment offset fixed.
/:cl:

Railgun now has Scope (and offset fix)

---

code/modules/vehicles/mecha/mecha_defense.dm

Mech Repairs now have a skill check, failing it leads to fumble.
I am an undercover agent dispatched by the xeno mains to nerf all fun marines have, I will now be making it so the private can't repair the mech as easily as the synth. 
:cl:
balance: Fumble added to mech repairs.
/:cl:

Mech Repair Now Fumbles

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/projectiles/guns/specialist.dm
code/modules/projectiles/magazines/specialist.dm
code/modules/reqs/supplypacks.dm

Fixes Pepperball gun not being buyable in req, first and foremost.
Makes magazines infinite in the marine vendor instead of there only being 40 of them, no real reason to force you to shred threw these things, and if I did add a req only variant I'd readd the old Tanglefoot SAN balls.
Aim mode has no slowdown now and I reduced aim mode fire delay to .2 from .25 total, and basically serves as a timed IFF to stop people from having .1 fire rate aim mode and instead have rifle firerate.
Upped the guns magazine size to 100, and added rail light as an attachable if you want it over mag harness.
The Forgotten weapon, the Pepperball gun.
It was outdated on release as I never gave it a followup and this should atleast give it an identity now as a good support tool, if its still poopy I'll give it …

Pepperball magazine, aim mode buff, infinite magazines, added to req and rail light addition

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Remove the second APC in CIC because it was screwing up power.
Put a second mech console in mech bay in case if round spawns with two MP.
Move mech button because I couldn't find it at first.
Put two full sheets of phoron in mech bay.
CIC has a recurring issue with power that can be fixed with deleting one APC. Also, help mech pilot out with phoron along with not having to wrestle with one console. I will do the same with other maps.
:cl:
del: Remove the second APC in CIC because it was screwing up power.
add: Put a second mech console in mech bay in case if round spawns with two MP.
fix: Move mech button because I couldn't find it at first.
add: Put two full sheets of phoron in mech bay.
/:cl:

Pillar of Spring's Winter Edition part 1: fix CIC APC and help MP

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/TGS_Sulaco.dmm

Title.
Doing it for PoS, Sulaco deserves the same.
:cl:
add: Add stack of phoron and another mech console in Sulaco
/:cl:

Add stack of phoron and another mech console in Sulaco

---

_maps/map_files/Minerva/TGS_Minerva.dmm

Title.
Also, fix an issue in ERT where there were two starboards.
Standardization across shipside maps is good.
:cl:
add: Add phoron stack and another mech console in Minerva
fix: issue where there were two starboard landing zones for ERT
/:cl:

Add phoron stack and another mech console in Minerva

---

code/game/objects/items/storage/dispenser.dm

Adds the missing throwpass var, so they can be fired past/used as cover.
Corrected the integ to 250, I did actually mean this in the old pr, whoops.
Fix good.
:cl:
fix: dispensers can be fired past like other objects, and integrity is correctly set to 250
/:cl:

dispenser fixes

---

code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm

Raises Queen leader slots from 2/3/3/4 at young/mature/elder/ancient to 2/3/4/5.
Makes more sense, spreads xenos pheremones a bit more, rewards maturing for Queen.
:cl:
balance: Queen leader slots adjusted.
/:cl:

Raises Queen Leader Slots

---

_maps/map_files/generic/Admin_Level.dmm
code/datums/jobs/job/fallen.dm

Mech Pilot added to Valhalla ghost roles, as well as a mech computer 
Allows for people to test how the mech works outside of the round, should appease those who like to experiment and want to see how to refine their mech loadouts.
:cl:
add: Valhalla given Mech Pilot role.
expansion: Mech Computers added to Valhalla for MP
/:cl:

Valhalla Mech Pilot

---

.github/workflows/auto_changelog.yml
.github/workflows/compile_changelogs.yml
.github/workflows/generate_documentation.yml
.github/workflows/remove_guide_comments.yml
.github/workflows/update_tgs_dmapi.yml

:cl:
code: test changelog
/:cl:

Git actions changes

---

config/config.txt

:cl:
config: test message
/:cl:

[s] test pr

---

code/game/objects/machinery/mortar.dm
code/modules/projectiles/ammo_datums.dm

add impact tablet to mlrs and make mlrs rockets do the explosion animation since it didn't do it before
didn't have them before and explosions are cool
:cl:
add: hud impact tablet to mlrs and explosions to the mlrs rockets
/:cl:

mlrs impact tablet and explosion animation

---

code/game/objects/items/stacks/stack.dm
code/game/objects/structures/barricade.dm
code/modules/projectiles/gun_helpers.dm

Just another balloon alerting batch
:cl:
qol: a bunch of barricade and a few gun verbs use balloon alerts now
/:cl:

Balloon alerts barricades and some gun stuff

---

code/controllers/subsystem/job.dm
code/datums/gamemodes/distress.dm
code/datums/gamemodes/extended.dm
code/datums/jobs/job/job.dm
code/datums/jobs/job/shipside.dm

First MP slot unlocks at 25 marines, then another every 40
Robot too stronk for 5man game.
:cl:
balance: First mech slot at 25 marines, second at 65, up from 0/40.
/:cl:

No mechs in lowpop

---

code/game/objects/items/flashlight.dm

Flashlight uses update icon properly

---

code/game/objects/items/explosives/bombvest.dm

Added missing spans
Added better admin logging
changed from ctrl click to the existing rclick framework
Changed the admin OB to have a little more fluff
multiple do_afters will no longer be queued
:cl:
qol: bomb vest can no longer spam progress bars
qol: bomb vest warcry is set with right click instead of ctrl click
admin: improvced bomb vest logging
/:cl:

Misc bombvest code improvements

---

code/game/objects/items/loot_box.dm
code/modules/reqs/supplypacks.dm

Spend 100 points, get 150 to 200 points of value back in return, basically.
Some items (Mainly legendary stuff) can't be acquired anywhere else but here, like NVGs and PMTL rifles.
There's only four packs right now since my 1am raddled brain can't make any more up.
Weight list unchanged, 10% for legendary, 20% for Rare, 30 and 40 for uncommon and common respectively.
Legendaries are made to absolutely tear up the round if used well, rares much less so, being more so round spinners like two TL-102s or double howitzers and five mortars which will wack up the round but not really define it.
Uncommon and Commons are just made to be variety packs, giving you some random assortment of stuff.
Hopefully leads to more variety in what people use in rounds considering the amount of wacky stuff …

Adds TGMC pack boxes

---

code/__DEFINES/mobs.dm
code/modules/reagents/reagents/medical.dm

Oxy has 100 pain resist over 50.
Oxycodone is super mediocre, and barely worth carrying in its current state, it doesn't give you enough pain resist to wobble away from whatever just beat the crap out of you unless you double dose on tramadol as well.
:cl:
balance: Oxycodone gives 100 pain resistance instead of 50 now.
/:cl:

oxycodone now gives 100 pain resistance over 50.

---

code/datums/skills.dm

Wayward copypaste
:cl:
fix: fixed MP having lead skill by accident
/:cl:

Fix MP having lead skill

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

<!-- ***STOP!***  Read this: If this is not a PR ready for review and merge or WIP, open it as a draft PR, using the arrow next to 'Create Pull Request'>
oversight when adding mech ability impacts
:cl:
fix: warrior can punch vehicles as intended
/:cl:

Woyer can punch vehicles properly

---

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm

Tittle
Stop funny pepperball man from deleting mechs, also idk why stamina damage does regular damage to objects but I'm gonna assume that stamina code fuckery, aka way beyond me, and in theory mech should probably have 100 bio armor but meh
:cl:
balance: Mechs have been upgraded with pepperball proof armor platings, they now have 75 bio armor
/:cl:

Mech actually has bio armor now

---

code/modules/vehicles/mecha/equipment/tools/work_tools.dm

<!-- ***STOP!***  Read this: If this is not a PR ready for review and merge or WIP, open it as a draft PR, using the arrow next to 'Create Pull Request'>
oversight when adding non filler modules
:cl:
fix: fixed broken mech extinguisher being selectable on accident
/:cl:

Mech extinguisher not selectable

---

code/modules/projectiles/guns/rifles.dm

Changes new sound of MG42 (Halo AR) back to old T42 sounds
:cl:
soundadd: replaced sound for the MG42
/:cl:

Changes MG42 gun sound back to old T42 gun sound.

---

code/modules/vehicles/mecha/_mecha.dm
code/modules/vehicles/mecha/combat/gygax.dm

https://github.com/tgstation/tgstation/pull/71113/files
:cl:
fix: fixed mech speed exploit
/:cl:

Fix actuator exploit

---

code/modules/shuttle/marine_dropship.dm

:cl:
add: change name of marine platoon for distress and nuclear
/:cl:

change name of marine platoon

---

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm

Removes starting melee and acid armor values, nerfs mech hp overall by 300
Immortal mech man bad
:cl:
balance: Nerfed mech HP and Armor values
/:cl:

Nerfs mech armor and HP

---

code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm

Looks like it was just a bad merge commit deleting code by accident.
h
:cl:
fix: Drone enhancement can actually be activated
/:cl:

Fixes drone enhancement

---

code/modules/projectiles/ammo_datums.dm
code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm

Nerfs light cannon and minigun, buff pistol and  rebalance shotgun
Lightcannon and minigun are way too good, this should bring them into line, the pistol isnt bad but it's not that desirable compared to the other light weapons so I'm buffing it to make it a better choice, and the shotgun is overall whack, now it has buckshot like CC and less spread, but does less damage as well, also higher fire delay to account for the new CC it got
:cl:
balance: Mech lightcannon and minigun nerfed, pistol buffed, shotgun now stuns but does less damage and fires slower
/:cl:

Some mech weapon balance changes

---

code/game/objects/structures/stool_bed_chair_nest/bed.dm

fixes #11533
Exploit bad.
:cl:
fix: Fixed a rollerbed bug
/:cl:

Rollerbed fix

---

code/modules/reqs/supplypacks.dm

Typo fixed for MLRS Rocket Pack
Whoever was the absolute dumbass who did #11517 forgot to update the req name for the order.

Rocket Pack Typo

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm

Spiderlings will now avenge widow when she dies, pursuing any nearby marines and mauling them. This only lasts 10 seconds or untill they die from other causes.
Currently spiderlings just kinda.. look at their dead mother.
Unless widow got gibbed, in which case they would just run around stupidly.
Now however, they will attack any marine in sight, if there are none, they get brazil'd.
:cl:
add: widow spiderlings will avenge widow
/:cl:

Spiderlings ain't no bitches

---

code/game/objects/structures/dropship_equipment.dm

Wow, what kind of huge nerd broke attachment points amirite?
Fixes attachment points getting blocked by dense object, that are themselves built into a dense object.
CAS being able to work is good.
:cl:
fix: fixed some attachment points not working
/:cl:

Fix hardpoint issue

---

code/modules/projectiles/ammo_datums.dm

TP44 changes
Damage 30->40
Penetration 20->15
Sunder 1,5->1
Slowdown removed entirely. It now only knockbacks.
Makes the TP44 more useable as a sidearm and primary as right now its difficult to use at all in my opinion, TP-14 can put out more damage with less skill required due to having more in a magazine. Removing the slowdown as a tradeoff for more damage and slightly less pen seems like a good change to me.
:cl:
balance: Revolver now does no slowdown. It now does more damage, and slightly less pen and sunder.
/:cl:

Revolver changes

---

code/__DEFINES/mobs.dm
code/game/objects/effects/landmarks/corpsespawner.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/update_icons.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/living_health_procs.dm

Remove some headbite remnants

---

code/game/objects/machinery/vending/vending_types.dm

Title
Better consistency, medbay won't run out of food in the long run. Bartenders are more useful.
Shouldn't affect balance as Xenos can melt groundside vendor variants.
:cl:
balance: Hoot foods and drink vendors now have infinite contents.
/:cl:

Hot Foods and Drink vendors now have an infinite supply of foods and drinks.

---

code/game/turfs/walls/wall_types.dm

It's times for the feels.
Even if this person is known in TGMC, it has a tone I like that isn't explored in TGMC: loss.
:cl: novaepee, lich, zaha, relevation
add: New Title Art: Grief of a loved one
/:cl:

New Title Art: Grief of a loved one

---

code/datums/components/chem_booster.dm

Bugfix good
instant necro not fun :(
:cl: Credit TiviPlus & Slotbot
fix: fixed vali instant necro bug
/:cl:

Vali bugfix

---

code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/guns/rifles.dm

What is this ? so, this is basically a scatter increase per shot mechanic, guns now have a min scatter, max scatter, scatter increase and scatter decay values
minimum scatter and maximum scatter is pretty obvious.
scatter increase is how much scatter increases per shot of a gun.
scatter decay is how much scatter decreases per 1/10 of a second not shooting.
attachments are also able to modify those so that should also take account into balance, certain attachments instead of modifying only the static scatter guns had, they can now modify increase, decay, maximum and minimum.
Currently i dind't actually make any gun use this system other than testing it, balancing and numbers need to be done, also, the default values means no gun is actually affected by this system(i also need to check if …

Scatter increase per shot mechanics.

---

code/game/objects/items.dm
code/game/objects/items/storage/belt.dm
code/game/objects/items/storage/dispenser.dm
code/game/objects/items/storage/holsters.dm
code/game/objects/items/storage/storage.dm
code/modules/clothing/under/under.dm
code/modules/mob/mob.dm

Fixes quick equip bypassing access delays, and bypassing the draw restriction on dispenser.
Bug fix good
:cl:
fix: fixed quick equip bypassing access delays and dispenser restrictions
/:cl:

Fixes quick equip not respecting access delays

---

code/game/objects/machinery/vending/marine_vending.dm

mor evaeli knieves :)
people called me fat and stinky because there were only 6 vali knives, now they might stop
:cl:
balance: Amount of harvester knives in the marine vendor increased
/:cl:

more vali knives

---

code/modules/projectiles/ammo_datums.dm

Some nerfs to laser weapons, and a buff to the burst rifle
Makes laser guns less of a obvious choice compared to their ballistic counterparts
:cl:
balance: Laser smg and projector nerfed, ballistic burst rifle buffed
/:cl:

Some more mech weapon balance changes

---

code/modules/admin/panels/player_panel.dm
code/modules/admin/topic.dm

Title
Consistency good.
:cl:
add: Adds Warlock to admin player panel tab.
/:cl:

Adds Warlock tab to Admin Player panel

---

code/controllers/master.dm

https://github.com/tgstation/tgstation/pull/68490

SS prio sort fix port

---

code/modules/mob/mob_verbs.dm

:cl:
fix: fixed use-inhand keybind bypassing restrainment
/:cl:

Fix use-inhand keybind bypassing restrainment

---

.gitignore
code/_compile_options.dm
code/game/world.dm

https://github.com/tgstation/tgstation/pull/70931/files

Byond tracy support port

---

code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/xenomorph/damage_procs.dm

Title
:cl:
fix: fixes xenos not receiving burn damage
fix: fixes humans runtiming on getting attacked in melee by another human
/:cl:

fix bugs on damage refactor

---

_maps/modularmaps/big_red/barracks.dmm

title
wack
Also, there were two APC for one area, which is not good mapping practice. I removed the APC in canteen since marines need the APC for green.
:cl:
del: remove two r walls and useless apc in Big Red's admin
/:cl:

remove two r walls and useless apc in Big Red's admin

---

code/game/objects/structures/grille.dm

fixes #11694 
grilles are not hunter
:cl:
fix: abolition of invisigrillity
/:cl:

Destealths grilles

---

code/modules/mob/living/living_health_procs.dm

Fix the base version of this proc which I forgot in my original pr. No change in game as only the human version of this is actually used.
Code fix good.
:cl:
code: Minor proc fix
/:cl:

Overall damage proc code fix

---

CONTRIBUTING.md
code/__HELPERS/game.dm
code/controllers/subsystem/greyscale.dm
code/controllers/subsystem/input.dm
code/datums/components/_component.dm
code/datums/elements/light_blocking.dm
code/datums/greyscale/_greyscale_config.dm
code/game/atoms_movable.dm
code/game/turfs/turf.dm
code/modules/lighting/lighting_static/static_lighting_corner.dm
code/modules/lighting/lighting_static/static_lighting_source.dm
code/modules/mob/living/silicon/ai/freelook/chunk.dm
code/modules/tgui/external.dm
code/modules/vehicles/mecha/_mecha.dm
code/modules/vehicles/mecha/mecha_movement.dm
code/modules/vehicles/mecha/mecha_ui.dm

TGMC has a macro AS for more byond version support, however I noticed it wasn't always used, so I standardized it to use the macro.
This isn't really affecting the game but if you have a macro you might as well use it, get the more byond version support it seems to give.
No player-facing changes, I dunno if I need a changelog.

Replaces 'as anything' with AS macro

---

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm

Removes a var that is no longer needed, and makes a couple of damage calculations use the new modify by armour method for calculating resists.
Consistant code good.
:cl:
code: Clean up some warlock code
/:cl:

Minor warlock code improvement

---

code/modules/projectiles/gun_helpers.dm
code/modules/projectiles/gun_system.dm
code/modules/reagents/machinery/chem_dispenser.dm
code/modules/reagents/machinery/chem_master.dm

Fixes the ability to bypass certain skill fumble times by giving yourself enough brain damage. Yes you can currently be some dumb you become able to do some things faster.
A few skill checks were written to only check if a skill value was present, which was probably fine before the brain damage rework.
After the rework, brain damage can cause your skills to go into the negative, which means you have a value for that skill, so the fumble is not performed.
Brain damage exploit bad.
:cl:
fix: fixed brain damage making you better at certain things
/:cl:

Skill check fixes

---

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm

fix for deevolve deleting xenos if they are not at full plasma or health
fix
:cl:
fix: fix for deevolve deleting xenos if they are not at full plasma or health
/:cl:

fix for deevolve deleting xenos

---

code/game/objects/items/bodybag.dm

Fix some exploits with bodybags and their child types.
Exploits bad.
:cl:
fix: fixed some exploits
/:cl:

Bodybag exploits

---

code/game/objects/items/storage/pouch.dm
code/modules/clothing/modular_armor/modular.dm

Adds them to modular armor suit storage ~~and lets them fit unfolded into construction pouches (but only one)~~
Means they actually work with new belt harness. ~~The pouch thing is just a personal grievance.~~
:cl:
balance: Shovels fit in suit storage
/:cl:

Improves shovel storage options

---

code/modules/admin/fun_verbs.dm
code/modules/tgui_input/alert.dm

Wrong arguments are preventing admins from playing music via the Play-Internet-Sound verb since last tgui update
fix #11544
:cl:
fix: Admin can't play music via the Play-Internet-Sound verb
/:cl:

Wrong arguments are preventing admins from playing music via the Play-Internet-Sound verb

---

code/modules/vehicles/mecha/mecha_defense.dm

Refactors mech reloading, fixing ammo with direct_load that is currently bugged and will only refill the current mag, not the reserve ammo cache.
Being able to load more than one round is good.
:cl:
fix: fixed some mech guns not being properly reloadable

Fixed mech reloads

---

code/modules/vehicles/mecha/equipment/weapons/weapons.dm

fixes inability to reload mech via UI
fix
:cl:
fix: fixed inability to reload mech via UI
/:cl:

mech UI reload fix

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

If you observe, the direction of reinforced window are wack. Some vendors are unaccesible by marines due to where reinforced window are orienated.
What they ought to look like.
yeah my bad
For mappers and nonmappers, this is terrible. I shall fix my mistakes.
:cl:
fix: the wack reinforced window frame orietation in PoS prep
/:cl:

PoS Prep Window Cleanup and Fix

---

code/modules/clothing/suits/marine_armor.dm

Harness (and thus stuff like cowboy jacket) has 6 light range.
You have 0 armor. This is basically baldur range so.
:cl:
balance: harness and unarmored leather jackets have 6 light range.
/:cl:

harnesses and harness type stuff have 6 light range

---

code/datums/jobs/squads.dm

SL's no longer lose leadership skill from the trauma of demotion.
Bug fix good
:cl:
fix: SL's no longer lose leadership skill from the trauma of demotion
/:cl:

SL demotion/promotion fix

---

code/modules/vehicles/mecha/_mecha.dm

Title
No more qdelete. Self destruct button would be based.
:cl:
fix: Mech can't be plasmacut
/:cl:

Mech can't be Plasmacut

---

code/game/turfs/walls/wall_types.dm

Title.
I made it to 608x480, then realized that I could make PR real fast if I had art already.
It's really good art. Made by Shinji (no really). Shinji Nomura for full name.
:cl: novaepee, Shinji Nomura
imageadd: New Title Painting: MP is Depressed
/:cl:

New Title Painting: MP is Depressed

---

code/modules/projectiles/gun_system.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm

title
this is mainly to fix quick-fire shotguns applying sunder too fast.
:cl:
balance: damage_mult applies to sunder
/:cl:

damage_mult applies to sunder

---

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm

No.
Map maintainer and many people say it's bad taste.
:cl:
del: Remove suicide vest in Magmoor's mosque
/:cl:

Remove suicide vest in Magmoor's mosque

---

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm

Fixed lance being unable to hit certain objects, like barricades.
Honk.
Bug fix good.
:cl:
fix: fixed warlock lance not hitting targetted objects
/:cl:

Warlock lance fix

---

code/modules/requisitions/supply_export.dm

fixes #11875
mjp forgot
:cl:
fix: Pizza profit margin has been fixed for RO Papa John to feed marines more pizza
/:cl:

Adjust factorio pizza selling to inflation

---

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm

Funny maintainer pressed merge before I pushed this last commit.
No gameplay changes, just some missing autodoc and cleaner code.
good code is good
:cl:
/:cl:

Minor king code improvement

---

code/modules/language/language_holder.dm
code/modules/mob/living/carbon/human/species.dm

Combat robots can speak machine
Combat robots (synths and AI too) have their own sikrit language now.
:cl:
add: Combat robots can speak machine
/:cl:

Combat robots can speak machine

---

_maps/modularmaps/EORG/basketball.dmm
_maps/modularmaps/EORG/cs_mansion.dmm
_maps/modularmaps/EORG/cs_militia.dmm
_maps/modularmaps/EORG/cs_office.dmm
_maps/modularmaps/EORG/de_dust2.dmm
_maps/modularmaps/EORG/de_inferno.dmm
_maps/modularmaps/EORG/de_nuke.dmm
_maps/modularmaps/EORG/old.dmm
_maps/modularmaps/EORG/original.dmm

title
becuase i want to box more in eord
ooc: novaepee: boxing fight rn
:cl:
add: ADD BOXING RINGS TO ALL EORD ARENA
/:cl:

ADD BOXING RINGS TO ALL EORD ARENA

---

strings/tips/marine.txt
strings/tips/meme.txt
strings/tips/xeno.txt

Time to add, delete, and update tips!
TGMC always changes every year, and tips ought to reflect that. It's a community effort at best to ensure that other new or vet players (if they read tips) can gain a tidpit or two about TGMC.
:cl: novaepee, Al-1ce
spellcheck: 2023 tips update
/:cl:

2023 tips update

---

code/modules/mob/living/carbon/human/human.dm
code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/gun_system.dm

Fixed gun underbarrel lights not working as expected, or when you have two separate lights on them.
MJP lied, bad.
Lights work properly is good.
:cl:
fix: fixed some gun light bugs
/:cl:

Gun light fix

---

code/game/objects/machinery/mortar.dm

Make offsets work properly.
A funny typo meant that the X offset change both X AND Y coordinates, while the Y offset just did nothing.
Also cleaned up some unneeded code.
Bug fix good.
:cl:
fix: fixed mortar offsets
/:cl:

Mortar offset fix

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

fixes #11962, which is space area in starboard maint.
fix missing wire in starboard maint
remove black table next to alamo
space area where xenos and marines walk in is bad
:cl:
fix: space area in starboard maint
fix: missing wire in starboard maint
fix: remove black table next to alamo
/:cl:

PoS minor fixes

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
_maps/map_files/desertdam/desertdam.dmm
_maps/modularmaps/big_red/bigredatmosvar1.dmm
_maps/modularmaps/big_red/bigredatmosvar2.dmm
_maps/modularmaps/big_red/bigredatmosvar3.dmm
_maps/modularmaps/big_red/bigredatmosvar4.dmm
_maps/modularmaps/big_red/bigredatmosvar5.dmm
_maps/modularmaps/big_red/bigredatmosvar6.dmm
_maps/modularmaps/lv624/southsandtemple1.dmm

Removes some misplaced hull windows on BR, removes an oversight on Chigusa where you could pod into a storage tank and be invulnerable.
Fixes good, people are chilling out in the tanks on Chigusa like it's some kind of giant sauna.
:cl:
fix: Removed some misplaced hull windows on Big Red.
fix: Fixed an oversight with podding on Chigusa.
/:cl:

Minor map fixes

---

code/modules/factory/parts.dm

Reqtorio part 2 electric boogaloo
Fixes surt recipe making violins
Another bad recipe squashed, reqtorio players in awe
:cl:
fix: Creating surt modules through reqtorio should no longer disappoint you with 10 violins
/:cl:

Fixes Reqtorio surt module printing violins 

---

code/game/objects/effects/spawners/random.dm

Fixes a couple of minor bugs causing random map spawners to not function correctly.
Bug fix good.
:cl:
fix: fixed random map spawners
/:cl:

Random spawner fix

---

code/datums/emergency_calls/sonsofmars.dm
code/datums/jobs/job/sonsofmars.dm
code/datums/status_effects/debuffs.dm
code/game/objects/items/storage/holsters.dm
code/modules/clothing/modular_armor/attachments/modules.dm
code/modules/projectiles/guns/shotguns.dm

Adds a few more loadouts to SOM erts, for some extra variety.
Also fixes a funny bug with sentinel toxin and the resistance trait.
Apply mimir to armour gives the trait to the user, putting on the armour is not required. I've changed it to bio armour since that's what it's for.
Spicy ERT good.
Bug fix good.
:cl:
balance: Added some more loadouts to SOM ERTs
fix: Fixed a bug with mimir traits
/:cl:

SOM ert update

---

code/__DEFINES/status_effects.dm
code/datums/status_effects/debuffs.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
code/modules/mob/living/status_procs.dm

Adds god mode checks to debuff status effects, defiler's defile ability and rouny snatch.
No more funny intox or stealing guns from petrified marines.
Getting your guns stolen while frozen is guh.
:cl:
fix: Added god mode checks to debuff status effects, snatch and defile
/:cl:

Godmode fixes

---

code/modules/projectiles/mounted.dm

Fixes #12004
As far as I am aware this flag serves no purpose for mounted guns.
bug fix good.
:cl:
fix: fixed an exploit with mounted weapons
/:cl:

Fixes a mounted weapon bug

---

code/modules/projectiles/guns/pistols.dm

Title
14->21
I guess the desc isn't wrong.
:cl:
spellcheck: P-14 no longer lies to you in the description about the mag size.
/:cl:

P-14 desc no longer lies to you about mag size

---

code/game/objects/structures/sensor_tower.dm

Fixed another bug with sensor tower interactions, and broke up interactions into multiple procs because it was kinda horrible to look at.
Fixed a runtime with minimap updates.
Towers are also no longer snowflake tied to factions, meaning any two factions can fight over towers if admins wish it, and makes it easier to add other factions to HvH in the future.
Bug fix good, code readability good, snowflake bad.
:cl:
fix: fixed a couple of sensor tower bugs
code: Updated sensor tower code, are no longer coded to the TGMC faction specifically.
/:cl:

Sensor tower update

---

code/_onclick/hud/screen_objects/screen_objects.dm
code/datums/atom_hud.dm

Battle day 2145 in the war against lag.
Fixes some harddels like this:
There's a number of hud icons that are not properly set to be removed from hud when qdel'd, the worst offendor being CAS lines.
I may or may not actually know what I'm doing though.
Harddel is one of the most consistant causes of high overtime and therefore tidi, so this should help to some degree.
:cl:
code: Fixed some harddel failures
/:cl:

Fixes some harddel issues

---

code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm

When widow gets resin jellied her spiderlings do too.
Loosing all of your precious spiderlings or having to resist away 6 firestacks can be pain.
Also 1 flame tile denying you any gameplay isnt nice either
:cl:
qol: spiderlings get coated in jelly too :)
/:cl:

spiderlings now get coated in resin jelly too :)

---

code/modules/reqs/supply.dm

removes supply manifest paper from orders
useless since computer already logs purchases, and is clutter
:cl:
del: removed supply manifest from orders
/:cl:

remove supply manifest

---

code/game/objects/machinery/vending/marine_vending.dm
code/game/objects/machinery/vending/vending.dm
code/game/objects/machinery/vending/vending_types.dm

Removes vending delay from marine vendors
Bro this shit is painful. Why. All it does is slow shit down. Even CM doesn't have this
:cl:
qol: Removes vending delay from marine vendors
/:cl:

Removes vending delay from marine vendors

---

code/game/objects/items/weapons/blades.dm

Funny throwing knives out DPS most guns in the game currently.
This isn't directly due to the autofire PR, but it did serve to highlight the issue.
Throwing a knife shouldn't be better than shooting a gun.
:cl:
balance: Reduced throwing knife throwforce to 25 from 45
/:cl:

Nerfs throwing knives

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Adds a light, it was causing a weird dark spot where the vendors are.
:cl:
fix: Fixes a dark spot on the pillar of spring.
/:cl:

Adds a light on the pillar of spring where the vendors are.

---

code/modules/factory/parts.dm

Title and as per Tivi's request.
Consistent formatting good.
:cl:
fix: fixes reqtorio formatting.
/:cl:

Fixes Reqtorio formatting

---

code/modules/mob/living/carbon/xenomorph/evolution.dm

Um, I forgot to re-implement the actual checking for the death timers, which is like, the whole point of it. Anyway, here you go, It's there, now.
:cl:
fix: Caste death timers now work, whoops.
/:cl:

Fixes Caste death timers not working

---

code/game/objects/items/portable_vendor.dm

Fixes a bug and replace some chat messages with balloon alerts for portable vendors.
Also made them faster to fabricate things.
Fixes good.
:cl:
fix: fixed a bug with portable vendors
/:cl:

Portable vendor fix

---

code/modules/mob/living/carbon/xenomorph/evolution.dm

Probs TM first.
Fixed a few checks that were getting missed when evolving which can lead to multiple of the same leader caste, and other issues like that.
Also reorganised evo code a bit more, as it was still a huge ass single proc, now split into 4 procs.
Added balloon alerts where appropriate, and removed an unneeded child proc.
Bug fixes good
Neater code good
:cl:
fix: fixed some evolution bugs
/:cl:

Xeno evolution fixes

---

code/game/objects/items/storage/belt.dm
code/game/objects/items/storage/holsters.dm
code/game/objects/items/storage/storage.dm

Fixed a bug where quick equip bug out when spammed with storage that has access delays, causing various other issues.
Bug fix good.
:cl:
fix: fixed an issue with spamming quick equip for storage with an access delay
/:cl:

Fix some quick equip bugs

---

code/__DEFINES/cooldowns.dm
code/game/atoms.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
code/modules/mob/living/carbon/xenomorph/damage_procs.dm
code/modules/mob/living/living_defense.dm
code/modules/projectiles/guns/flamer.dm

Makes the rav fire proc the right thing. I am smoothbrain, but also firecode sucks.
Also added a 1 second CD so you can't just move back and forth mega fast for quick plasma.
Organised some fire procs a bit more so they're not all just stuffed in the flamerthrower gun dm for whatever reason.
Fix my own mistakes
Cooldown is good
Slightly better organised code
:cl:
fix: Fixed ravager fire interaction and added a one second cooldown
/:cl:

More fire cleanup and rav fire act actually working edition

---

code/game/objects/items/weapons/energy.dm

Eswords now bumpslash when toggled on.
Also made it use the actual esword hit sword when on.
Bumpslash on sword good.
:cl:
qol: Eswords now have bumpslash when activated
/:cl:

Adds bumpslash to esword

---

code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/mob_helpers.dm
code/modules/surgery/surgery.dm

Removes 2 stupid procs

---

code/game/objects/items/weapons/twohanded.dm

bay relic? idk the check is stupid
:cl:
qol: Monkeys can now wield two-handed weapons
/:cl:

Monkeys can now wield two-handed weapons

---

code/game/objects/items/cocoon.dm

fixes #11975 
:cl:
fix: cocoons are no longer meltable
/:cl:

Cocoons are no longer meltable

---

code/datums/actions/action.dm
tgui/packages/tgui/interfaces/HiveStatus.tsx

Kinda a stinky issue but this is good enough (tm)
:cl:
qol: the blessings button in hive status ui has a little store icon now
fix: the blessings button in the hive UI works again
/:cl:

Fix hivestatus blessings button

---

code/__HELPERS/icons.dm

Remove resolved todo

---

code/game/objects/structures/stool_bed_chair_nest/janicart.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/projectiles/projectile.dm
code/modules/vehicles/multitile/cm_armored.dm

Theres a signal
:cl:
fix: animals now take damage from bullets properly
/:cl:

bullet_act now calls parent

---

code/_onclick/click.dm
code/game/say.dm
code/modules/mob/camera/imaginary_friend.dm
code/modules/mob/death.dm
code/modules/mob/new_player/new_player.dm

Makes more things parentcall that should have

---

code/datums/elements/deployable_item.dm
code/modules/projectiles/gun_attachables.dm

Fixes only one of each deployable item being deployable.
I did a whoops because I didn't realise the deployable element has a instance per item type, not per item.
Also fixes a couple other minor bugs/runtimes
Bug fix good
:cl:
fix: fixed a bug with deployable items not deploying and some other minor bugs
/:cl:

Fixes deployable bug

---

code/game/objects/machinery/vending/marine_vending.dm

Adds shoulder mount
Moves RR to its OG position in the vendor and adds heat, cloak, smoke and tfoot shells.
Adds cloak implant
Adds blood implant
Adds Garand and ammo
Adds MBX and its shell types
More testing, more fun.
:cl:
add: Adds shoulder mount, cloak and blood implant and RR heat, smoke, cloak and tfoot shells to Valhalla.
add: Adds Garand and MBX and its shell types to Valhalla.
qol: Moves RR shells to the same position in the normal vendor along with its ammo.
qol: Moves tracker shells from valhalla req vendor to seasonals vendor for the MBX.
/:cl:

Adds more stuff to Valhalla

---

code/datums/actions/action.dm
code/datums/actions/xeno_action.dm
code/datums/components/bump_attack.dm
code/modules/mob/living/carbon/carbon_defines.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/mob_defines.dm

Just fixes a bit of code. Mostly things that should be /// but are currently //
I hate old coders. Why are you like this.
:cl:
code: more gooder code. :)
/:cl:

Fixes some code

---

code/modules/shuttle/marine_dropship.dm

Adds admin anounce and writes log on who called dropship
I was very supprised to learn it was not the case yet. we are survaliance state more logging is nice
:cl:
admin: Dropship calls are logged now
/:cl:

Logs who calls the dropship

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Yet another thing I noticed that was somewhat broken by me.
:cl:
fix: The queen dying will no longer mute hivemind for the full queen evolve delay
/:cl:

Fixed the hivemind muting lasting longer than half the queen's timer

---

code/datums/keybinding/xeno.dm

:cl:
qol: Added hunter keybind defaults
/:cl:

Adds sensible hunter keybind defaults

---

code/datums/keybinding/xeno.dm

:cl:
qol: Added defender keybind defaults
/:cl:

Adds sensible defender keybind defaults

---

code/datums/keybinding/xeno.dm

:cl:
qol: Added sentinel keybind defaults
/:cl:

Adds sensible sentinel keybind defaults

---

code/datums/keybinding/xeno.dm

:cl:
qol: Added hivelord keybind defaults
/:cl:

Adds sensible hivelord default keybinds

---

code/datums/keybinding/xeno.dm

:cl:
qol: Added runner keybind defaults
/:cl:

Adds sensible runner keybind defaults

---

code/datums/keybinding/xeno.dm

:cl:
qol: Added boiler keybind defaults
/:cl:

Adds sensible boiler keybind defaults

---

code/datums/keybinding/xeno.dm

:cl:
qol: Added ravager keybind defaults
/:cl:

Adds sensible ravager keybind defaults

---

code/datums/keybinding/xeno.dm

:cl:
qol: Added carrier keybind defaults
/:cl:

Adds sensible carrier keybind defaults

---

code/modules/projectiles/ammo_datums.dm
code/modules/reqs/supplypacks.dm

Fixed an ugly oversight with ammo in req.
no bug
:cl:
fix: fixed autocannon ammo in req
/:cl:

Autocannon oversight fix

---

code/controllers/subsystem/vote.dm

Basically forces the automatic vote screen on everyone's screens once the vote starts. Also admins can force it to pop up in custom votes as well.
I'm not sorry, EORDers. The vote for what we're gonna be playing for the next hour or so is more important.
Main point is to address the issue of 80% of the server not voting.
Should prevent wasting of time sitting in lobby after that one person who remembered the gamemode vote exists decided to vote for HvH for shits and giggles so now everyone has to waste extra time in the next round's lobby voting on gamemode again.
:cl:
add: The vote screen for the automatic votes now pops up when they start
admin: Admins can now make the voting panel pop up for everyone for their custom votes
/:cl:

The vote screen for the automatic votes now pops up when they start

---

code/modules/power/fusion_engine.dm

Title
CSE and STs are the masters of engineering and the masters of ship maintenance. Makes sense for them to do the job more efficiently. Synth too but that's if they're shipside.
:cl:
qol: Makes repairing shipside gens and removing fuel cells scale with engineering skill.
/:cl:

Repairing shipside gens and removing fuel cells now scales with engi skill

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Title.
forgot
:cl:
fix: Pillar of Spring's SMES not being connected
/:cl:

fix Pillar of Spring's SMES not being connected [MDB Ignore]

---

code/datums/jobs/job/sonsofmars.dm

Couple of minor SOM fixes.
Veterans are no longer marked as SGers on comms, and fixed the default paygrades for some jobs (only relevant for admin assigned roles).
Fixes good.
:cl:
fix: fixed a couple of minor SOM paygrade and radio rank issues
/:cl:

SOM radio rank fixes

---

code/_globalvars/lists/flavor_misc.dm
code/modules/mob/new_player/new_player.dm
code/modules/projectiles/gun_attachables.dm

Title
Fix good
:cl:
spellcheck: fixed 'sports bra' typo.
spellcheck: fixed the grammar of the lack of xeno message alert.
spellcheck: fixed BAS desc grammar.
/:cl:

Typo fixes

---

code/modules/projectiles/gun_attachables.dm

Fixes some exploits with bipods. Also cleans up foldable attachment code a bit.
Nicer code, kill bugs.
:cl:
fix: fixed some bipod exploits
/:cl:

Bipod fixes

---

code/controllers/subsystem/minimaps.dm

The workaround for [this bug](http://www.byond.com/forum/post/2661309) is no longer necesarry.
Unnecesarry vars are unnecesarry therefore not good.
:cl:
code: Updates SSminimaps to account for BYOND error being fixed
/:cl:

Updates SSminimaps to account for BYOND error being fixed

---

code/modules/projectiles/gun_system.dm

Garands have a 1% chance to deal 1 brute to the hand the gun is in.
Muh realism.
Meh gacha mechanic but interesting and funny implementation.
Feel the PVT in you come out with the 1% chance to smack your thumb.
:cl:
add: Added Garand thumb mechanic. (1% chance to deal 1 brute when reloading a Garand)
/:cl:

Garands have a 1% chance to give you Garand thumb.

---

code/datums/jobs/job/other.dm
code/game/objects/items/reagent_containers/food/snacks.dm

#11377 gave the Pizza ERT actual Pizza boxes.
This gives them a chance to spawn with more varieties of pizzas.
More Pizzas, more fun.
:cl:
add: Adds more options of pizzas to spawn with the pizza ERT.
/:cl:

Pizza time 2.0

---

code/controllers/subsystem/aura.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/xenomorph/xeno_structures.dm

Fixes non-normal hive pheros not working
Pheros being hardcoded to only work for one hive is stinky.
:cl:
fix: Fixed non-normal hive pheros not working
/:cl:

Fixes non-normal hive pheros not working

---

code/controllers/subsystem/minimaps.dm

Observe as I hit this code with a brick and make it run twice as fast

Minimaps fire() optimization

---

code/datums/jobs/job/job_exp.dm

Fix valhalla playtime exploit

---

code/game/sound.dm

Moves the ?? list assignments into sound define 
get_sfx now only called when needed
TM before merge might affect some stuff

Some playsound local changes

---

code/modules/projectiles/guns/specialist.dm

backblast particles for rocket launchers
https://user-images.githubusercontent.com/98577688/224560364-205ea63e-25f7-4d88-a34b-da9a75227912.mp4
looks nice
:cl:
add: particles for rl backblast
/:cl:

backblast particles

---

code/modules/projectiles/ammo_datums.dm

Purely code
Gooder code
:cl:
code: cleans up ammo_datum.dm
/:cl:

Cleans up doc on ammo_datum

---

code/modules/clothing/suits/labcoat.dm

I forgot to update an icon_state, whoops. Also removed some code which wasn't needed.
Bug fix good.
:cl:
fix: fixed the icon of basic lab coats
/:cl:

Massive labcoat fix

---

code/datums/loadout/loadout.dm
code/datums/loadout/loadout_manager.dm
code/modules/tgui_input/alert.dm
tgui/packages/tgui/interfaces/LoadoutViewer/index.tsx

Ports https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/35
It's just better loadout management.
:cl:
add: "Overwrite loadout" button in Loadout Vendor
/:cl:

Adds "Rewrite Loadout" button to the loadout vendor.

---

code/game/turfs/floor.dm

Yeah. Stupid forgot a line again.
Closes #12463
Floors being slippery forever isn't.
:cl:
fix: Fixes slippery floors being slippery forever
/:cl:

Fixes slippery floors being slippery forever

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
code/__DEFINES/minimap.dm
code/game/area/areas/shuttles.dm
code/game/area/general.dm
code/game/area/mainship.dm
code/game/turfs/closed.dm

Adds minimap colours to shipside.
Clearer map is good.
:cl:
qol: Added colours to the shipside minimap
/:cl:

Ship map colors

---

code/modules/clothing/under/marine_uniform.dm

Title.
Naked marines guh.
:cl:
fix: Fixed charlie turtleneck missing a sprite
/:cl:

Fixes charlie turtleneck missing a sprite

---

code/modules/projectiles/projectile.dm

Yeah. Don't assume they'll have a client.
Runtime bad.
:cl:
fix: Fixes runtime from clientless mobs behind hit with projectiles
/:cl:

Fixes runtime from clientless mobs being hit with projectiles

---

code/game/objects/items/defibrillator.dm

Defib no longer fails entirely at 0 damage
Defibbing a robot at 100 total damage (0 health) is no longer a full heal
bugfix
:cl:
fix: Defibbing robots is more reliable
/:cl:

Fixes low damage robot defibs

---

code/modules/clothing/suits/marine_armor.dm

Fixes PMC armour not showing up on mob, whoops.
Bug fix good.
:cl:
fix: PMC armor is no longer invisible
/:cl:

Fixes some ert suit sprites

---

code/__DEFINES/skills.dm
code/datums/skills.dm

Title
The chief is and should be the best at their craft.
:cl:
balance: changes CMO surgery and medical skill to Master.
fix: fixes some descriptions in code to be more accurate
/:cl:

Gives CMO Master Surgery and Medical skill

---

code/game/objects/machinery/overwatch.dm

Overwatch consoles sometimes try to do some really wacky stuff that leads to bad things. This attempts to improve safeties to prevent that from happening.
Bug man bad.
:cl:
fix: Hopefully patches up some vulnerable parts of overwatch console code.
/:cl:

Attempts to resolve some wacky overwatch stuff

---

code/controllers/subsystem/weeds.dm
code/game/objects/effects/weeds.dm
code/game/objects/structures/window.dm
code/game/objects/structures/window_frame.dm

Clicks on weeds get transferred to the frame always now. Also cleans up copypasta.
Pixel hunt bad.
:cl:
fix: Fixes window and window frame weeds transferring the click to the frame/window below
code: Removed some weed window frame copypasta
/:cl:

Fixes window and window frame weeds transfering the click to the frame/window below

---

code/datums/jobs/job/sonsofmars.dm

Adds missing helmet items to a couple of SOM ERT loadouts.
While testing the quick equip fix I noticed a couple had missing bits.
Also swapped out a stray marine pouch for its SOM version.
Bug fix good
:cl:
fix: Added a few missing items on a couple of SOM ERT loadouts
/:cl:

Minor SOM ERT fix

---

code/datums/jobs/job/icc.dm

Fixes the ICC medic, probably. Which will allow them to spawn not butt naked.
It was already approved with MJP's implementation, this fixes minor bugs with it.
:cl: Skye
fix: fixes the ICC medic spawn. It's Space...Somewhere, not 1940s Russia.
/:cl:

Updates the ICC medic, potentially allows for them to spawn with an outfit.

---

code/datums/components/attachment_handler.dm

Partial revert of #12383 due to an exploit.
Spooky is fine with the speed merge.
Exploit bad.
:cl:
/:cl:

Exploit fix

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

Changes this to "xeno_name_here's skin begins to glow!"
Weird grammar bad.
:cl:
fix: Fixes the 3rd person ravager endure message
/:cl:

Fixes the 3rd person ravager endure message

---

code/game/objects/machinery/computer/nuke_disk_generator.dm
tgui/packages/tgui/interfaces/NukeDiskGenerator.js

Please note this is my first time dabbling in TGUI properly.
The overall progress bar is based on disk color. 
Also fixes a bug with the nuke disk console just never processing again after being depowered once.
Html stinky, tgui good 8)
:cl:
add: Gave the nuke disk generator a new TGUI interface
fix: Fixed a bug related to the disk console never being processed again if turned off once
refactor: Refactored a bit of the nuke disk generator code and added autodocs
/:cl:

Gives the nuke disk generator a TGUI interface

---

code/controllers/master.dm

Ports https://github.com/tgstation/tgstation/pull/64498
See original pr
:cl:
code: The mc now detects if its priority budget gets out of sync with reality and soft resets
/:cl:

The mc now detects if its priority budget gets out of sync with reality and soft resets

---

code/__DEFINES/spaceman_dmm.dm
code/_debugger.dm
code/controllers/failsafe.dm
code/controllers/master.dm
code/controllers/subsystem.dm
code/controllers/subsystem/air.dm
code/controllers/subsystem/assets.dm
code/controllers/subsystem/garbage.dm
code/controllers/subsystem/mapping.dm
code/controllers/subsystem/shuttle.dm
code/controllers/subsystem/ticker.dm
code/controllers/subsystem/timer.dm
code/game/world.dm
code/modules/tgchat/to_chat.dm
tgmc.dme

Ports https://github.com/tgstation/tgstation/pull/60846
I was checking some stuff and saw we never ported this.
Delete the MC. Laugh with impunity. But probably don't.
better failsafe good
:cl:
code: Updated the failsafe to recover from a deleted MC
/:cl:

The Failsafe can now recover from an deleted MC

---

code/modules/mob/living/carbon/human/human_attackhand.dm

Shows up on self click under the wounds check.
Also included an absolutely critical grammar fix.
Makes it more apparent that germs actually exist. Didn't add a way to check them on someone else because that should never matter.
:cl:
add: When you check yourself for wounds, you can see the dirt you've accumulated. Mostly only matters for surgeons.
/:cl:

Adds self germ check

---

code/controllers/subsystem/vote.dm

Fix largest hard del (prolly)

---

code/game/objects/items/weapons/twohanded.dm

sword hits slower :)
whats the point
:cl:
balance: Claymore now hits slower 
/:cl:

claymore balances

---

code/controllers/subsystem/minimaps.dm

Basically remove what i assume is the expensive part with the assoc lookup in a large list

Optimize minimap location updating

---

code/game/objects/items/reagent_containers/food/snacks.dm

Increases the nutrients in the food that a MRE contains.
Currently a MRE takes up the equivalent space of 2 protein bars, but it only has 12 total nutriment. which is worse than just carrying 2 protein bars.
This will make carrying MREs more worthwhile, as you actually get more than 1 nutriment per bite.
:cl:
balance: MREs contain a lot more nutriment.
/:cl:

MREs are much more nutrient dense.

---

code/__DEFINES/equipment.dm
code/game/objects/items/storage/secure.dm
code/game/objects/machinery/squad_supply/supply_beacon.dm
code/game/objects/structures/dummy_mapping_objects.dm
code/modules/projectiles/gun_system.dm
code/modules/vehicles/multitile/hardpoints.dm

Defines better.
Everything with weight class 7 or up has been moved to 6
No player facing changes.
c*ders
:cl:
code: w_class code cleanup 2nd try.
/:cl:

Moves everything weight class 7 and + down to 6.

---

code/modules/power/groundmap_geothermal.dm

I put length for some reason. Pain.
Psi working good.
:cl:
fix: Fixes the psi gen fix
/:cl:

Fixes psi gen, again.

---

code/_onclick/item_attack.dm
code/game/objects/items.dm
code/game/objects/structures/inflatable.dm

Combined duplicate attack_self procs (this probably fixes the squeak component, what a game changer).
Couple of minor code tidy ups on inflatables.
Working code good.
:cl:
code: Some minor code cleanup
/:cl:

Minor code fixes

---

_maps/map_files/Theseus/TGS_Theseus.dmm

Yeah. Theseus is the only shipmap without them. Most of these changes are automatic by strongdmm.
Brings theseus up to par with the other shipmaps in that regard at least.
:cl:
add: Adds 2 AI droids to Theseus
/:cl:

Adds 2 AI droids to Theseus

---

code/game/objects/machinery/vending/loadout_vendor.dm
code/game/objects/machinery/vending/marine_vending.dm
code/modules/projectiles/guns/rifles.dm
code/modules/projectiles/guns/shotguns.dm

Title
Fix and consistency good.
:cl:
spellcheck: added improper tag to some guns missing it.
/:cl:

Fixes some grammar checks.

---

code/__DEFINES/factions.dm
code/datums/jobs/job/special_forces.dm
code/game/objects/items/cards_ids.dm
code/modules/projectiles/guns/sentries.dm
code/modules/projectiles/sentries.dm

Original pr, donutsteel.
Remake of #12669 after Xander's unfortunate demise.
Adds a bunch of missing faction and IFF related stuff, so everyone can actually use IFF with their own or friendly factions.
Not shooting your friend in the back of the head (accidentally) is good.
:cl:
fix: fixed some IFF issues with various minor factions
/:cl:

Updates Factions

---

code/datums/loadout/loadout_manager.dm
tgui/packages/tgui/interfaces/LoadoutManager/Types.tsx
tgui/packages/tgui/interfaces/LoadoutManager/index.tsx

https://user-images.githubusercontent.com/66163761/231069688-4825fb9b-13fb-4406-85b2-b47897bbf4dd.mp4
Better UI
:cl:
qol: Loadouts are re-organizable.
/:cl:

Loadouts can be reorganized.

---

code/game/objects/machinery/camera/camera_assembly.dm

Fixes an oversight with infinite camera assemblies
Exploit bad.

Camera assembly fix

---

code/modules/mob/living/carbon/human/human.dm

Whole bunch of 8 year old indent hell and single letter non descriptive vars. Replaced with early returns and better vars.
Yes, this is mostly outdated code for MP and stuff. Suffer.
Cleaner code is better.
:cl:
refactor: Cleaned up the human topic proc
/:cl:

Human topic cleanup

---

code/__DEFINES/dcs/flags.dm
code/__DEFINES/map_switch.dm
code/controllers/subsystem/dcs.dm
code/datums/elements/_element.dm
code/datums/elements/attachment.dm
code/datums/elements/connect_loc.dm
code/datums/elements/deployable_item.dm
code/datums/elements/egrill_element.dm
code/datums/elements/gestures.dm
code/datums/elements/light_blocking.dm
code/datums/elements/limb_support.dm
code/datums/elements/plasma_on_attack.dm
code/datums/elements/plasma_on_attacked.dm
code/datums/elements/riding.dm
code/datums/elements/shrapnel_removal.dm
code/datums/elements/special_clothing_overlay.dm
code/datums/elements/undertile.dm
code/datums/elements/wall_speedup.dm
code/modules/unit_tests/bespoke_id.dm
code/modules/unit_tests/dcs_get_id_from_elements.dm
tgmc.dme

literally just updates our element system by porting a newer version from tgstation
also adds MAP_SWITCH macro
part of an atomized PR, needed for it
probably TM this but i saw no issues in my 19 seconds of testing
(yeah TM this)
ports elements up to PR https://github.com/tgstation/tgstation/pull/72188
ports MAP_SWITCH macro, with the latest PR being https://github.com/tgstation/tgstation/pull/71007
old bad new good
none

updates the element system from /tg/station

---

code/game/objects/items/reagent_containers/hypospray.dm

Makes the pill remove_from_storage(pill) so that it actually goes through all the proper procs.
Bugfix
:cl:
fix: Pill packet/bottle numbers update when you click it with a hypo
/:cl:

Pill packet/bottle overlay updates when you refill a hypo

---

code/game/objects/items/circuitboards/circuitboard.dm
code/game/objects/items/stacks/medical.dm
code/game/objects/items/tools/maintenance_tools.dm

Adds desc to 
- weldingtool 
- medical splint
- airlock electronics
Fixes this:
:cl:
spellcheck: Weldingtool, airlock electronics and medical splints have a description now
/:cl:

Adds desc to weldingtool and medical splint

---

_maps/shuttles/tgs_canterbury.dmm

My bad, I forgot to tell Naani to merge a PR in his branch that would've put it back earlier. Sorry!
Drip is good.
:cl:
fix: Readds the IV drip to the small Canterbury variant.
/:cl:

Re-adds the IV drip to the Canterbury

---

code/datums/keybinding/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm

:cl:
fix: fixed missing call burrowed description
/:cl:

Missing call burrow desc fix

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

bloat
:cl:
qol: Removes X spits at y message
/:cl:

Remove X spits at y message

---

code/modules/client/client_procs.dm

https://github.com/tgstation/tgstation/pull/74373/files

[s]Fix admin topic exploit

---

code/modules/client/client_procs.dm

https://github.com/tgstation/tgstation/pull/74373/files

First connect responsiveness improvement

---

code/game/objects/machinery/doors/railing.dm

Title. Kinda tired of people being thrown in then needing admins to get out.
Bug bad,
:cl:
fix: Fixes req railings not being invunerable and fixes mobs being able to be thrown over them
/:cl:

Fixes req railings not being invunerable and fixes mobs being able to be thrown over them

---

code/game/objects/items/scanners.dm

adds feedback to healthscan RMB
so that you (and people close by) can see that you've shown a patient their healthscan.
Simply a bit of useful feedback to know it worked.
:cl:
qol: Balloon alert tells you that you've shown your patient their healthscan.
/:cl:

adds feedback to healthscan RMB

---

code/game/objects/machinery/doors/railing.dm

Fuck. Should've put that check last. 
Bug bad.
:cl:
fix: Fixed req railings not having collision
/:cl:

Fixes req railings not having collision

---

code/game/objects/structures/droppod.dm

Fixes a couple of drop pod bugs related to unbuckling from them without choosing a target, causing the pod to be unusable etc.
Bug fix good.
:cl:
fix: fixed some bugs with drop pods
/:cl:

droppod fix

---

code/modules/mob/living/living.dm

**Before fixes:**
https://user-images.githubusercontent.com/22431091/234931942-25735e97-5ac5-4c01-a657-b9630c3f4532.mp4
https://user-images.githubusercontent.com/22431091/234930729-39e6268d-df6f-4eea-b30c-0efd0b73bdc3.mp4
With the fixes in this PR:
https://user-images.githubusercontent.com/22431091/234930819-71656dcf-c58a-49ad-bf56-dd9a70a080ff.mp4
https://user-images.githubusercontent.com/22431091/234931133-385d4823-78d1-4ca0-8fc9-34b7254bea6d.mp4
I really suggest a testmerge for this instead of a yolomerge.
Diagonals being janky isn't good for the game. Also exploits that allow you to phase thru cades are bad.
:cl:
fix: Fixed diagonal shuffling
fix: Fixed exploit that allowed you to phase through cades
/:cl:

Fixes up diagonals and diagonal shuffling

---

code/datums/components/companion.dm

rountime
Runtime bad
:cl:
fix: Fixes the companion component runtiming upon deletion
/:cl:

Fixes the companion component runtiming upon deletion

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Fixes some issues with some xeno abilities.
Exploit bad
:cl:
fix: fixed a maturity issues with some xeno abilities
/:cl:

Xeno ability fix

---

code/game/objects/items/devices/minimap_tablet.dm

Yes.
Bug bad.
:cl:
fix: Fixed the filter error
/:cl:

Fixes the filter error

---

code/game/objects/items/stacks/sheets/sheet_types.dm

4 metal, 5 second construction time, same fumble as cades.
Kinda weird they aren't constructable.
:cl:
add: Let window frames be made from metal
/:cl:

Let window frames be made from metal

---

code/modules/projectiles/ammo_datums.dm

Fixes boiler shooting through shutters and the like.
Also AGLS nades.
Bug fix good.
:cl:
fix: fixed boilers shooting through shutters and other dense objects
/:cl:

boiler fix

---

code/game/objects/machinery/mortar.dm

also cleaned some punctuation 
:cl:
qol: linking binoc to arty uses a balloon alert
/:cl:

Arty link ballon

---

code/game/objects/machinery/mortar.dm

Videos coming in a sec
looks cool
:cl:
qol: added some howitzer visual effects when firing
/:cl:

Make howitzer kick up dust when it's fired

---

_maps/map_files/Sulaco/TGS_Sulaco.dmm

Puts a med vendor in sulaco prep.
Marine med in marine prep 👍 
:cl:
add: MarineMed in Sulaco prep.
/:cl:

Puts a med vendor in sulaco prep.

---

code/game/turfs/liquid_turfs.dm

Quick hotfix. Two prs were merged that both touched the same file causing a conflict with var names getting changed.
Compiling is pretty useful.

hotfix for incorrect var name

---

code/game/objects/items/defibrillator.dm

when paddles are being set up it pulls the ghost if not DNR into the body
ghost can still leave to cancel
so PVT dinglefart doesnt have to realize they have to reenter their body to get revived
:cl:
add: Defibrillation pulls the ghost into the body during the process
/:cl:

makes defibrillation grab ghost

---

code/controllers/subsystem/minimaps.dm
code/datums/jobs/job/xenomorph.dm
code/game/objects/effects/landmarks/excavation_site_spawner.dm
code/game/objects/effects/temporary_visuals/miscellaneous.dm
code/game/objects/items/devices/minimap_tablet.dm
code/game/objects/items/radio/headset.dm
code/game/objects/machinery/computer/nuke_disk_generator.dm
code/game/objects/machinery/miner.dm
code/game/objects/machinery/nuclearbomb.dm
code/game/objects/machinery/sellingpad.dm
code/game/objects/machinery/squad_supply/supply_beacon.dm
code/game/objects/structures/sensor_tower.dm
code/game/objects/structures/teleporter.dm
code/modules/events/intel_computer.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/power/groundmap_geothermal.dm
code/modules/projectiles/sentries.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm
code/modules/xenomorph/xeno_structures.dm

Boilerplate Zlevel arg
appearances just rolled into a blip arg
other misc changes with useless arg by names and such

Minimap addmarker refactor

---

code/game/objects/items/weapons/twohanded.dm

bugfix
bugfix
:cl:
fix: Vali Claymore is no longer immune to acid.
/:cl:

Makes Claymore not acid immune.

---

code/game/objects/effects/temporary_visuals/miscellaneous.dm
code/game/objects/structures/orbital_cannon.dm

https://cdn.discordapp.com/attachments/500801682058379265/1103265616330244106/Change_Me_-_Debugdalus_2023-05-03_11-29-45.mp4
:cl:
qol: OB cannon impact now has a visual animation
/:cl:

OB cannon impact is now animated

---

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

acid spray now deletes razorwire again
lumi said so
:cl:
fix: fixed acid spray not deleting razorwire
/:cl:

acid spray now deletes razorwire again

---

code/game/objects/structures/tables_racks.dm
code/modules/admin/IsBanned.dm
code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm

Yeah. Why was this valid syntax.
515 syntax compat good
:cl:
code: Addressed more 515 compat stuff the regex missed
/:cl:

Yet more TYPE_PROC_REF the regex missed

---

code/game/objects/structures/droppod.dm

For some reason I removed this bit in #12859, bleh
Unintended bad
:cl:
fix: Pods fit in the pod launchers again
/:cl:

Fixes pods

---

code/__DEFINES/callbacks.dm
code/controllers/subsystem/garbage.dm
code/datums/callback.dm
code/modules/projectiles/gun_system.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm
tools/build/build.js

https://github.com/tgstation/tgstation/pull/73264/files
and fixes from
https://github.com/tgstation/tgstation/pull/73788/files

Async optimization port

---

code/game/objects/structures/stool_bed_chair_nest/bed.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm
code/modules/projectiles/projectile.dm

Removes:
-line spray message
-bullet miss message
-hugger dying message
- picking up beds message
Doesnt give any useful info you cant already see visually
:cl:
qol: Removed some unneeded tochats
/:cl:

Unneeded tochat removals

---

code/modules/projectiles/guns/specialist.dm

thermo backblast particles wouldnt delete and slightly adjusts backblast particles
fix good
:cl:
fix: thermo backblast not removing
/:cl:

fix thermo backblast and slight adjustment

---

code/datums/jobs/squads.dm

Removes unused squad vars

---

code/game/verbs/ooc.dm

1984
:cl:
admin: LOOC/MOOC/XOOC is now filtered
/:cl:

Fixes LOOC/MOOC/XOOC filter

---

code/game/buckling.dm
code/game/objects/items/bodybag.dm
code/game/objects/items/embedding.dm
code/game/objects/items/explosives/bombvest.dm
code/game/objects/items/explosives/grenades/grenade.dm
code/game/objects/items/frames/frame.dm
code/game/objects/items/gift_wrappaper.dm
code/game/objects/items/jetpack.dm
code/game/objects/items/megaphone.dm
code/game/objects/items/pinpointer.dm
code/game/objects/items/quickdeploy_cade.dm
code/game/objects/items/radio/headset.dm
code/game/objects/items/reagent_containers/dropper.dm
code/game/objects/items/reagent_containers/food/snacks.dm
code/game/objects/items/tools/cleaning_tools.dm
code/game/objects/items/tools/extinguisher.dm
code/game/objects/items/tools/maintenance_tools.dm
code/game/objects/items/tools/mining_tools.dm
code/game/objects/items/tools/research_tools.dm
code/game/objects/items/tools/shovel_tools.dm
code/game/objects/items/toys/crayons.dm
code/game/objects/machinery/kitchen/microwave.dm
code/game/objects/structures/barricade.dm
code/game/objects/structures/crates_lockers/closets.dm
code/modules/power/apc.dm
code/modules/power/fusion_engine.dm
code/modules/reagents/machinery/chem_dispenser.dm
code/modules/reagents/machinery/chem_master.dm
html/changelogs/AutoChangeLog-pr-12967.yml

Title.
About a year ago I created a PR that added balloon_alerts to almost everything in the game, https://github.com/tgstation/TerraGov-Marine-Corps/pull/9901. Unfortunately it was too large and died under its own weight. I have decided to revive the PR in pieces, this being my first one.
Read the original PR. tl:dr visual feedback is better than searching through the chat boxes looking for things that have happened.
:cl:
qol: Added balloon_alerts to many things and objects
/:cl:

Adds some more balloon alerts

---

code/game/objects/machinery/vending/marine_vending.dm

Forgot
Yes
:cl:
qol: Recharger lascells in valhalla req vendor
/:cl:

Adds recharger lascells to Valhalla vendor

---

code/game/objects/items/storage/boxes.dm

misc harddel

---

code/game/objects/items/tools/maintenance_tools.dm

They shouldn't eat power cells anymore.
Closes #13041
Bug bad.
:cl:
fix: Fixed handheld cell chargers
/:cl:

Fixes handheld cell chargers

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Twin_Pillars/Twin_Pillars.dmm
_maps/modularmaps/big_red/bigredetavar2.dmm

fixes ert engine dirs in other maps
wacky dirs bad
:cl:
fix: ert engines in maps
/:cl:

mapside ert engines fix

---

code/__HELPERS/unsorted.dm
code/game/objects/machinery/computer/computer.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
code/modules/vehicles/mecha/combat/savannah_ivanov.dm

Port of https://github.com/tgstation/tgstation/pull/73480
https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/5c5eea53-0427-466a-9c5b-684643599f66
Features working good.
:cl:
fix: Fixed atom shaking
/:cl:

Fixes atom shaking

---

code/modules/mob/living/say.dm

Completely untested
:cl:
fix: Maybe fix radio keys being filtered
/:cl:

Maybe fix radio keys being filtered

---

code/controllers/subsystem/vote.dm

Title.
Stops goobers interrupting the automatic votes.
:cl:
fix: Automatic votes cancel any ongoing voting when they start
/:cl:

Automatic votes cancel any ongoing voting when they start

---

_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/TGS_Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
_maps/map_files/Twin_Pillars/Twin_Pillars.dmm
_maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
_maps/map_files/debugdalus/tgs_debugdalus.dmm
_maps/map_files/gelida_iv/gelida_iv.dmm
_maps/map_files/generic/Admin_Level.dmm
_maps/modularmaps/big_red/bigredofficevar2.dmm
_maps/shuttles/tgs_bigbury.dmm
_maps/shuttles/tgs_canterbury.dmm
code/game/objects/effects/spawners/random/engineering.dm
code/game/objects/machinery/fuelcell_recycler.dm
code/modules/power/fusion_engine.dm

Readds a line the balloon alert PR removed for some reason, refactors the procs to call parent and utilizes early returns in them. Murders fuel cell camel case. 
Stuff working as it should good.
:cl:
fix: The shipside generators work again
code: Cleaned up engine code and added docs
/:cl:

Fixes the shipside engines + docs + cleanup

---

code/datums/jobs/job/fallen.dm
code/datums/jobs/job/terragov.dm
code/modules/mob/dead/observer/observer.dm

You will now spawn as a race depending on game prefs, same as normal roles (so you can spawn as vatborn too).
Robros get to do stuff in valhalla
:cl:
add: Robots and vatborn have now been accepted in valhalla
/:cl:

Valhalla now accepts robots

---

code/game/objects/items/reagent_containers/hypospray.dm

Switches a lot of chat notices like injecting someone and drawing from a container to balloon notices. [only hypospray related]
Balloons show you that you did a thing.
:cl:
code: unnecessary proc/label
code: replace to_chat with balloons
/:cl:

Balloonening ft. hyposprays + old proc inline

---

code/datums/components/attachment_handler.dm

Fix funny attachment exploit.
Fixes #13086
Exploit bad.
:cl:
fix: fixed an exploit with attachments
/:cl:

Fix attachment exploit

---

code/modules/projectiles/projectile.dm

ricochet vars that aren't used anywhere
this is unused
:cl:
code: remove unused ricochet vars
/:cl:

remove unused projectile ricochet vars

---

code/game/objects/machinery/roomba.dm

Not actually tested, same voice settings as vending machines
Funny
:cl:
add: Roomba gets TTS
/:cl:

Roomba gets a voice

---

code/__HELPERS/time.dm

stationTimestamp tweak

---

code/_onclick/click.dm

Did not test
:cl:
code: Improved some clicking code
/:cl:

Low hanging click code optimization fruit

---

code/__DEFINES/_tick.dm
code/__DEFINES/text.dm
code/controllers/subsystem/runechat.dm
code/datums/chatmessage.dm
code/modules/balloon_alert/balloon_alert.dm

https://github.com/tgstation/tgstation/pull/69137/files
https://github.com/tgstation/tgstation/pull/74428/files
:cl:
code: optimized runechat
/:cl:

Optimized runechat

---

code/game/objects/items/tools/shovel_tools.dm

Just an overreach from the .? find/replace a while back.
Fixes #13087 
:cl:
fix: You can dump snow off shovels again
/:cl:

Fixes a shovel runtime

---

code/modules/power/pipecleaners.dm
code/modules/vehicles/mecha/mecha_mob_interaction.dm

Not supplying a message yields a runtime.
Runtime bad.
:cl:
fix: Fixed an add_fingerprint runtime
/:cl:

Fixes `add_fingerprint` runtime

---

code/game/objects/structures/misc.dm

Fixes a runtime. 515 spaceman dmm when?
Also just makes the code a bit better.
Runtime bad.
:cl:
fix: fixed an issue with facehugger cryo tanks
/:cl:

Cryotank improvement and fix

---

code/datums/gamemodes/_game_mode.dm
code/datums/round_statistics.dm
code/game/objects/structures/benchpress.dm

CL
:cl:
add: Xenos may now lift on the benchpress
qol: Which faction lifted how much is now logged as an end of round stat
fix: fixed breaking an arm not stopping the lift animation of the benchpress
/:cl:

Benchpress updates

---

code/datums/components/_component.dm

Drag and drop TG proc, safer & no more callasync

Updates _sendsignal to TG

---

code/datums/datacore.dm
code/game/objects/items/stacks/stack.dm
code/game/objects/machinery.dm
code/game/objects/machinery/computer/marines_consoles.dm
code/game/objects/machinery/computer/medical.dm
code/game/objects/machinery/computer/security.dm
code/game/objects/machinery/computer/skills.dm
code/game/objects/machinery/doors/airlock.dm
code/game/objects/machinery/sleeper.dm
code/modules/mining/money_bag.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/mob_helpers.dm
code/modules/paperwork/paper.dm
code/modules/paperwork/paper_bundle.dm
code/modules/paperwork/photography.dm

funny error in tgs, testing fix

compile test

---

code/game/objects/structures/crates_lockers/closets.dm

Yes.
Causes some undesirable behavior with dead bodies and it's a useless feature anyways.
:cl:
del: Removed crate stuffing
/:cl:

Removes crate stuffing

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/mining/remote_fob/remote_fob_actions_misc.dm
code/modules/mining/remote_fob/remote_fob_computer.dm

By default cades now will be placed wired
Comments out fob drone sentry code
Less hassle making fob is good
Removing not used code and icons for players is good
:cl:
qol: By default, cades are wired
/:cl:

Fob Construction Improvements

---

code/datums/quick_load_outfits.dm
code/game/objects/items/storage/pouch.dm
code/modules/clothing/modular_armor/som.dm
code/modules/clothing/modular_armor/xenonauten.dm

Minor HvH tweaks.
TGMC and SOM medics have  general storage for extinguisher and defib, and some extra stuff in their backpacks instead.
Normal firstaid pouches can now take hyposprays.
Minor QOL/fixes good
:cl:
balance: Some minor tweaks to medic and SL loadouts
/:cl:

Hvh loadout tweaks

---

code/game/objects/items/weapons/misc.dm

Exploit bad.
:cl:
fix: fixed an exploit with powerfists
/:cl:

fixes a power fist exploit

---

code/datums/jobs/job/job.dm

Fixes variant outfits.
I missed a couple of dumb things because 515 has no break points so I didn't see any runtimes. I have no idea how it magically worked without initial to begin with though.
Bug fix good, Lumi bad.
:cl:
fix: fixed an issue with variant outfits
/:cl:

Fix variants

---

code/datums/keybinding/carbon.dm
code/datums/keybinding/mob.dm

I love byond syntax
515 compliance
:cl:
code: Addressed more stuff that should be TYPE_PROC_REF
/:cl:

More type proc ref that was missed

---

code/modules/projectiles/gun_system.dm

attachments now rotate with the gun when thrown
fix good
:cl:
fix: gun attachments now rotate with the gun
/:cl:

gun appearance flags

---

code/datums/progressbar.dm
code/modules/tgui_input/say_modal/typing.dm

Fixes speech bubbles and do_after icons getting filter effects from their mob applied to them.

filter fixes

---

code/__HELPERS/text.dm
code/__HELPERS/type2type.dm
code/game/objects/effects/manifest.dm
code/game/objects/items/cards_ids.dm
code/game/objects/items/implants/implantcase.dm
code/game/objects/items/stacks/stack.dm
code/game/objects/items/storage/secure.dm
code/game/objects/machinery.dm
code/game/objects/machinery/air_alarm.dm
code/game/objects/machinery/autodoc.dm
code/game/objects/machinery/camera/camera.dm
code/game/objects/machinery/camera/tracking.dm
code/game/objects/machinery/computer/medical.dm
code/game/objects/machinery/computer/security.dm
code/game/objects/machinery/computer/skills.dm
code/game/objects/machinery/computer/station_alert.dm
code/game/objects/machinery/fire_alarm.dm
code/game/objects/machinery/igniter.dm
code/game/objects/machinery/sleeper.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/fireaxe.dm
code/modules/buildmode/submodes/boom.dm
code/modules/instruments/songs/editor.dm

Legacy proc that should never be used
https://www.byond.com/forum/post/2872285
Legacy procs bad.
:cl:
code: Murdered all instances of the text byond proc
/:cl:

Murders `text()`

---

code/modules/projectiles/projectile.dm

https://github.com/tgstation/TerraGov-Marine-Corps/pull/12893 reverted this fnr
Runtime bad
:cl:
fix: Fixed hard armor getter proc
/:cl:

Fixes hard armor getter proc

---

code/modules/mob/living/say.dm

Bird doesn't have a job.
Runtime bad.
:cl:
fix: Fixed poly tts runtime
/:cl:

Fixes poly TTS runtime

---

code/modules/mob/living/carbon/xenomorph/evolution.dm

Closing the window would count as a yes
Bug bad
:cl:
fix: Fixed slight issue in hivemind prompt
/:cl:

Fixes slight issue in hivemind prompt

---

code/_onclick/hud/screen_objects/screen_objects.dm

Don't assume they'll still have a client at this point
Runtime bad
:cl:
fix: Fixed hive tracker no client runtime
/:cl:

Fixes hive tracker no client runtime

---

code/game/objects/structures/dropship_equipment.dm

We don't wanna continue the proc if there isn't anything loaded in the clamp.
Runtime bad.
:cl:
fix: Fixed clamp dropship attach point runtime
/:cl:

Fixes clamp dropship attach point runtime

---

code/modules/mob/living/carbon/xenomorph/attack_alien.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

Turns out I broke hunter AP on sneak attack 6 months ago, but no one noticed/reported it, honk.
Curse of mass editing stuff.
Bug fix good.
:cl:
fix: Hunter sneak attack correctly applies AP again
/:cl:

hunter AP fix

---

code/game/objects/items/blink_drive.dm

Adds a codex entry for the blink drive. Explains all the mechanics, as well as some fluff.
Explaining how things works is good.
:cl:
qol: added a codex entry for the blink drive
/:cl:

Adds a codex entry for the blink drive

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

title
:cl:
add: hivemind core can be tracked on the hive status
/:cl:

Make hivemind core hive status trackable

---

code/datums/components/shield.dm

It's a wonder this ever worked in the first place honestly.
Bug bad.
:cl:
fix: Fixed a shield bug
/:cl:

Fixes a shield bug

---

_maps/map_files/gelida_iv/gelida_iv.dmm
code/game/objects/structures/platforms.dm

AIs and other clientless stuff don't have a client, duh.
`Runtime in code/game/objects/structures/platforms.dm, line 125: Cannot read null.move_delay`
`Runtime in code/game/objects/structures/platforms.dm, line 111: Cannot read null.move_delay`
Runtime bad.
:cl:
fix: Fixed a platform runtime
/:cl:

Fixes platform runtime

---

code/datums/weather/weather.dm
code/datums/weather/weather_types/acid_rain.dm
code/datums/weather/weather_types/ash_storm.dm

I kinda fucked up and made only humans hear weather before. Whoops.
Weather pref fully working good.
:cl:
fix: Weather sounds should work properly for everyone now
/:cl:

Fixes weather not working for non humans + micro optimizations

---

code/modules/projectiles/mounted.dm

Fixes the exploit of getting onto dense objects via deployable weapons, which is bad for a number of reasons.
Fixes #13278 
Fixes #11693
Exploit bad.
:cl:
fix: fixed a deployable gun exploit
/:cl:

fix deployable exploits

---

code/datums/weather/weather.dm

I mindlessly made all the loops equal with the goal of making them performant completely glossing over this.
Bug bad.
:cl:
fix: Fixed weather messages not appearing if you have weather sounds off
/:cl:

Fixes weather messages

---

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm

Change defiler's tentacle plasma cost to 175 plasma.
Ancient defiler's plasma max is 575. When you use emit gas, reagent slash, and defile, you have 175 plasma to use left, and this PR allows primo defiler to use tentacle without buffing defiler's plasma max.
defile = 100
gas = 200
slash = 100
From other PR, #13221,
"Gives the defiler more ability to combo all the way by letting high-skill players the ability to use all the castes abilities when they go all in due to the high cost of tentacle. Now they should be able to use all frontline abilities ONCE each before needing to run away."
:cl:
balance: Buff defiler's tentacle by decreasing plasma cost; a primo defiler with full plasma can use emit gas, reagent slash, tentacle, and defile in one full plasma
/:cl:

Buff defiler's tentacle by decreasing plasma cost

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/projectile.dm
code/modules/projectiles/tracer.dm

also fixes pistol disabler being invisible
https://github.com/tgstation/TerraGov-Marine-Corps/assets/98577688/464cd0f3-55ce-4834-816b-b01634163aae
looks cool
:cl:
add: light to hitscan lasers
fix: disabler shots being invisible
/:cl:

hitscan lasers now produce light

---

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm

sleep bad
fix good
:cl:
refactor: refactored defiler emit gas code
/:cl:

Defiler code fix

---

code/datums/elements/jump.dm

Very minor visual issue with jumping where mixing different changes to your Y position would look weird.
Fix good.
:cl:
fix: Minor jumping visual fix in some situations
/:cl:

fixes a small jump visual bug

---

code/modules/clothing/shoes/marine_shoes.dm

Yes. Back when I made slipping a component I apparently forgot this.
This is the same behavior as before.
:cl:
fix: Marine boots have noslip again
/:cl:

Marine boots have noslip again

---

code/game/objects/items/frames/alarms.dm
code/game/objects/items/frames/frame.dm
code/game/objects/items/frames/light_fixtures.dm
code/game/objects/machinery/camera/camera_assembly.dm
code/game/objects/structures/crates_lockers/closets.dm
code/game/turfs/walls/walls.dm

Some random balloon alert fixes/additions.
I noticed popping out of a locker caused a runtime due to usr instead of user.
Fixes good.
Balloon alert good.
:cl:
fix: fixed a locker runtime
qol: Added a few balloon alerts for some construction steps
/:cl:

Misc balloon alert fixes

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
code/game/objects/machinery/vending/marine_vending.dm

Expand morgue and medical supply room in Medbay. Make room for robotic cradle. Remove triage room.
Adjust requisition to have marines make orders right after they leave prep.
Add crates nearby vendors and engineering vendors close to Alamo.
Add MarineMed in all the specialized roles.
Add more easter eggs in PoS!
TGMC meta is always changing, and with that, important additions to the PoS comes with the meta.
:cl:
add: Expand morgue and medical supply room in Pillar of Spring Medbay.
add: Adjust Pillar of Spring requisition to have marines make orders right after they leave prep.
add: Add crates nearby vendors close to Pillar of Spring Alamo landing zone.
add: Add more easter eggs in PoS, making a total of eight easter eggs!
/:cl:

Pillar of Spring Summer 2023 Remodel

---

code/game/objects/items/embedding.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/projectiles/gun_attachables.dm

Byond interprets this as a new type definition because of course.
Bad syntax bad.
:cl:
code: Fixed more type definitions in params
/:cl:

Fixes more type definitions in params

---

code/__HELPERS/spatial_info.dm
code/game/objects/items/reagent_containers/food/snacks/grown.dm
code/game/objects/items/taperecorder.dm
code/game/objects/machinery/computer/security.dm
code/game/objects/machinery/computer/skills.dm
code/modules/mob/inventory.dm
code/modules/reagents/holder.dm
code/modules/reagents/reactions.dm
code/modules/reagents/reagents/other.dm

Old syntax.
It's better list inits are consistent.
:cl:
code: Converted instances of new/list to the list wrapper
/:cl:

new/list => list()

---

code/game/objects/structures/barricade.dm

Yea. This might be intentional actually so I'll slap a balance.
Exploit bad.
:cl:
balance: Fixed stacking repairs on cades if they were low hp enough to get them to full hp in a short time
/:cl:

Fixes insta repairing cades if they were low hp enough

---

code/modules/atmospherics/machinery/pipes/manifold.dm
code/modules/mapping/mapping_helpers.dm

fixes it runtiming when you use it for mapping
fixes ported from this pr https://github.com/BeeStation/BeeStation-Hornet/pull/9220
you can now use it for mapping
:cl:
fix: smart pipe mapping helper runtiming
/:cl:

fix smart pipe mapping helper runtiming

---

code/datums/jobs/job/job.dm
code/modules/admin/topic.dm
code/modules/mob/living/carbon/human/human.dm

Fixed equipping a mob not properly equipping in some cases. This was actually the most cursed way of doing it that I could possibly imagine, jesus.
Fixed all of the ID related options not working. This also incidentally fixes ID's themselves. If you've ever examined one and seen that it has a weird [blank] thing? Yeah there's supposed to be stuff there, like your blood type.
Bug fix good.
:cl:
fix: fixed ID's not correctly showing info such as blood type
admin: Fixed some issues with the rank and equip button
/:cl:

Fixes admin Rank and Equipment bugs

---

code/game/objects/structures/cas_plane_parts.dm
code/game/turfs/closed.dm

These types shouldn't be acidable.
Bug.
:cl:
fix: Fixed some rock walls and cas parts being acidable
/:cl:

Fixes some rock walls and cas parts being acidable

---

code/datums/components/jump.dm

Messing with gravity settings no longer bugs out robots pass flags.
Bug fix good.
:cl:
fix: fixed an issue with the adjust gravity button
/:cl:

Grav button fix

---

code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm

Title.
Grammar good
:cl:
spellcheck: fix grammar on defender's desc
/:cl:

fix grammar on defender's desc

---

code/game/objects/items/radio/headset.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/living.dm

Why would you set a non dead mob to be undefinable? 
Bug bad.
:cl:
fix: Fixes ghosting humans being set to undefibbable and not processing
/:cl:

Fixes ghosting humans getting taken out of ssmobs

---

code/modules/clothing/modular_armor/attachments/arm_plates.dm
code/modules/clothing/modular_armor/attachments/leg_plates.dm

Title.
QV requested it.
:cl:
code: add in mk1 arm and leg plates description that they have the same armor and slowdown to tell players that only changing chestplate influence armor and slowdown
/:cl:

add in mk1 arm and leg plates desc that they have the same armor

---

code/modules/admin/panels/ban_panel.dm
code/modules/mob/say.dm

Requested by admins. 
People get a bit upset sometimes.
:cl:
admin: Added a deadchat specific ban
/:cl:

Adds a deadchat specific ban

---

_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/TGS_Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
_maps/map_files/debugdalus/tgs_debugdalus.dmm
code/game/objects/structures/dropship_equipment.dm
code/modules/reqs/supplypacks.dm

God I hate copypasta.
Also makes the minigun one + it's ammo buyable in req since that was accidentally taken out apparently.
Bug bad and copypasta bad. Working good.
:cl:
add: Readded the mounted nest minigun back to req
fix: Fixed mounted nest dropship equipment not letting you mount it
code: Refactored mounted nest dropship equipment to use inheritance
/:cl:

Fixes mounted nest dropship equipment not letting you mount it + free refactor of the mountables

---

code/datums/jobs/job/marines.dm

Title.
Make TGMC marine players play a total of 5,000 hours to get new ranks
:cl:
add: engineer, corpsman, SG, & SL have 1,000 hours rank
/:cl:

engineer, corpsman, SG, & SL have 1,000 hours rank

---

code/datums/status_effects/debuffs.dm
code/modules/mob/living/carbon/human/dummy.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/species.dm

Also changed repair mode to a fake blind instead of a normal one to circumvent potential immunities.
Makes it easier and cleaner to add species specific actions in future.
:cl:
code: Species can have a list of inherent actions
/:cl:

General cases species actions

---

code/modules/projectiles/gun_system.dm

Runtimes.
Runtime bad.
:cl:
fix: Fixed a sentry runtime
/:cl:

Fixes sentry guns

---

code/datums/jobs/job/shipside.dm

Fixes it trying to equip the robot variant onto humans. I forgor
closes #13427
Bug bad.
:cl:
fix: Fixed MD outfit trying to give humans the robot variant
/:cl:

Fixes missing line in md outfit

---

code/modules/orbits/spaceship.dm

Title. 
Log spam bad.
:cl:
admin: Orbit changes only message admins if successful
/:cl:

Fixes orbit change spam messaging admins even if unsuccessful

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
_maps/map_files/Sulaco/TGS_Sulaco.dmm
_maps/map_files/gelida_iv/gelida_iv.dmm

Turns out my solution to creating shallower areas might have broken a couple area APCs, this (should) fix it.
Bugs bad fixes good.
:cl:
fix: Fixed a couple broken area APCs
/:cl:

Fixes broken area APCs

---

code/modules/reqs/supplypacks.dm

Title
:cl:
add: You can get more money from req
/:cl:

You can get more money from req

---

code/game/objects/items/radio/radio.dm

Fixes handheld radios not being in the hearable list when broadcasting.
We uh, having fucking ancient CM/bay era code, someone should totally port from TG or something.
Fix good.
:cl:
fix: fixed handheld radios not actually hearing things
/:cl:

Handheld radio fix

---

code/game/atoms_movable.dm

I uh, forgot a commit.
bug fix good
random test comments bad

fixed funny throw bug

---

code/game/atoms_movable.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
code/modules/mob/living/living.dm
code/modules/mob/mob_movement.dm

Fixes jump throws going over mobs but not objects that can normally be thrown over.
So throw code is extremely old and shitty and makes no sense. Made some changes to try make it more sane.
Bug fix good.
Slightly better code slightly better.
:cl:
fix: fixed jump throws not going over objects that they should
/:cl:

Throw fixes and improvements

---

code/datums/components/chem_booster.dm

Fixes #9083
:cl:
fix: Fix vali necro overlay not disappearing
/:cl:

Fix vali necro overlay not disappearing

---

code/datums/gamemodes/nuclear_war.dm

nucler.
Unintended bad.
:cl:
fix: Fixed xeno jobs needing more points than intended
/:cl:

Fixes xeno jobs needing more points than intended

---

code/modules/projectiles/guns/energy.dm

Minor update to the laser weapons that changed in the rework, as they still referenced outdated firemodes.
Accurate descriptions are good.
:cl:
qol: Removed description references to old firemodes for laser weapons
/:cl:

Laser description update

---

code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm

see title and **QUEEN DOESNT LAY EGGS!!!!!!!!!!!!!!!!!!**
stops the spread of misinformation and lies
:cl:
fix: fixed queen's description still mentioning that she lays eggs.
/:cl:

removes mention of egg laying in the queen's description

---

_maps/shuttles/minidropship_umbilical.dmm
code/datums/gamemodes/combat_patrol.dm

People complained, I forgor to add it in the original.
Less falling out of shuttle mid transit...
:cl:
add: Added new side shutters to Umbilical Tad.
/:cl:

Gives the Umbilical Tad shutters on side windows.

---

code/datums/elements/limb_support.dm
code/modules/clothing/modular_armor/attachments/modules.dm

Fixes this element not having a proper detach proc, leading to signals not being unregistered when detached.
Fixes #13493
Bug fix good
:cl:
fix: fixed a bug with the valkyrie module
/:cl:

limb support element bugfix

---

code/modules/admin/panels/ban_panel.dm
code/modules/mob/camera/imaginary_friend.dm
code/modules/mob/living/say.dm

Admin request, untested btw
:cl:
admin: Adds TTS and IC bans
/:cl:

Adds TTS and IC bans

---

code/modules/mob/say.dm

Admin request
:cl:
admin: Deadchat now uses the OOC chat filter
/:cl:

Dchat uses OOC filter

---

code/__HELPERS/_lists.dm

These can be null so we need to make sure they aren't.
Runtime bad.
:cl:
fix: Fixed listclearnulls on 515
/:cl:

Fixes `listclearnulls` on 515

---

code/__DEFINES/speech_channels.dm
code/datums/keybinding/admin.dm
code/modules/client/client_procs.dm
code/modules/tgui_input/say_modal/modal.dm
code/modules/tgui_input/say_modal/speech.dm
tgui/packages/tgui-say/ChannelIterator.ts
tgui/packages/tgui-say/styles/colors.scss

cd6ff02a3c222917bcfbf5070744bf589236f1eb but for msay
:cl:
add: msay is tgui. rebind your msay key
/:cl:

Hook msay into tgui

---

code/controllers/subsystem/minimaps.dm

Fixes #13171. This was missed in #13506
:cl:
fix: iguana is on minimap after being spawned
/:cl:

Fix markers not working on objs made inside closets

---

code/modules/reqs/supply.dm

Fixes #13040
:cl:
fix: req lift can move only when idle
/:cl:

Req lift can move only when idle

---

code/__HELPERS/pencode.dm
code/modules/admin/verbs/faxes.dm
code/modules/asset_cache/asset_list_items.dm
code/modules/paperwork/paper.dm

Fixes #5516. tgui paper when
:cl:
fix: writing [logo] and [ntlogo] on paper works now
/:cl:

Fix pencode [logo] and [ntlogo]

---

_maps/map_files/Orion_Military_Outpost/orionoutpost.dmm

title
RipGrayson have blesssed us with tunnels that I couldn't have code otherwise. It's time for other maps to prespawn tunnels.
:cl:
add: xenomorphs tunnel landmarks in Orion to help with xenomorphs create manuever around maps
/:cl:

add xenomorph tunnel landmarks in Orion

---

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
_maps/map_files/gelida_iv/gelida_iv.dmm

title
RipGrayson have blesssed us with tunnels that I couldn't have code otherwise. It's time for other maps to prespawn tunnels.
:cl:
add: xenomorphs tunnel landmarks in Magmoor to help with xenomorphs create manuever around maps
/:cl:

add xenomorph tunnel landmarks in Magmoor

---

_maps/map_files/Theseus/TGS_Theseus.dmm

Title
stinky; go take a bath, theseus
:cl:
balance: Theseus' SD walls are not Outer Hull anymore
/:cl:

Theseus' SD walls are not Outer Hull anymore

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm

Title.
RipGrayson have blesssed us with tunnel landmarks that I couldn't have code otherwise. It's time for other maps to tunnel landmarks.
:cl:
add: xenomorphs tunnel landmarks in Ice Colony to help with xenomorphs create manuever around maps
/:cl:

add xenomorph tunnel landmarks in Ice Colony

---

code/controllers/subsystem/job.dm
config/config.txt

Still need to enable these in the server config for it to actually work.
Exp requirements working is good.
:cl:
fix: Fixed readying up bypassing exp requirements 
config: Added the missing exp flags to the default config
/:cl:

Fixes readying up bypassing exp requirements + adds the missing exp flags to the default config

---

code/modules/surgery/surgery.dm

Fix surgery on robots always failing due to them being in pain
:cl:
fix: fixed robot surgery
/:cl:

Fix robot surgery

---

_maps/map_files/Sulaco/TGS_Sulaco.dmm

Fixes #13573. #13446 broke it
:cl:
fix: fixed the medbay exit button on sulaco
/:cl:

Fix medbay exit on Sulaco

---

code/game/objects/items/weapons/blades.dm
code/game/objects/items/weapons/twohanded.dm

its not actually super controversial and bad balance changes towards vali it just updates the codex information to make it not wrong
I feel like nobody will be mad about replacing some misinformation with actual information
:cl:
add: New vali codex information
/:cl:

super controversial and bad balance changes towards vali

---

code/game/atoms.dm
code/game/atoms_movable.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

More throw code shitty cleanup
Fixes a bug with xeno throws still getting stuck on things.
Removes some dead code/tidies up some proc usage.
Throwcode go home.
Fixes/code improvement
:cl:
fix: fixed another issue with xeno throws getting stuck on things
/:cl:

Xeno throw cleanup

---

code/game/turfs/walls/wall_types.dm

This is WORTHY of being a title art!
:cl: novaepee and Pqüax
add: title art of an epic battle between mech vs queen
/:cl:

add an awesome painting

---

code/_globalvars/lists/mobs.dm
code/controllers/subsystem/server_maint.dm
code/game/sound.dm
code/modules/mob/dead/observer/login.dm
code/modules/mob/dead/observer/logout.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/say.dm

humans_by_zlevel works now and replace another one i added
TTS should no longer cross z for ghosts, tm would be good
:cl:
fix: fixed  TTS for ghosts going across zlevels
/:cl:

Likely fix for cross-z tts and misc sendspeech improvements

---

code/game/turfs/floor_types.dm

I seem to have undone some alt wood floor type paths before the pr got merged.
No in game changes, just makes a few more types of wood floor actually usable for mappers.

Fix wood floor type paths

---

code/game/atoms_movable.dm

Latejoins or readyups are in nullspace for a brief moment so yeah.
Runtime bad
:cl:
fix: Gravity fixed for real this time
/:cl:

Gravity fix 2

---

code/_onclick/hud/screen_objects/screen_objects.dm

Tracker can be gone by this point.
Runtime bad.
:cl:
fix: Fixed tracker runtime 2
/:cl:

Fixes tracker no client runtime 2

---

code/datums/jobs/job/fallen.dm

Skills can't be outfits
Causes runtimes and runtime bad.
:cl:
fix: Synth skills should work properly in valhalla now
/:cl:

Fixes synth valhalla skills

---

code/game/objects/items/stacks/sheets/glass.dm
code/game/objects/items/stacks/sheets/sheet_types.dm
code/game/objects/items/stacks/stack.dm

Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/13599
Fixes good
:cl:
fix: Crafting for anything other than plasteel/metal works again
/:cl:

Crafting menus for wood, glass, etc. work again

---

code/game/objects/machinery/vending/marine_vending.dm

hey you forgot these
Serpenta moment
:cl:
add: Valhalla vendor now has volkite small cells (Serpenta ammo)
/:cl:

Adds volkite small cells to the valhalla vendor

---

code/modules/client/client_procs.dm

https://github.com/tgstation/tgstation/pull/77316
Fixes #6864
:cl:
fix: fixed clickdrag aimbot
/:cl:

Update client click handling for 514

---

code/game/objects/items/scanners.dm

Title. 
It being accurate is good.
:cl:
fix: Health scanner doesn't tell you you're pregnant if you hold an alien embryo in your hand anymore
/:cl:

Health scanner doesn't tell you you're pregnant if you hold an alien embryo in your hand

---

code/game/objects/items/cocoon.dm

Ew bug.
Ew bug.
:cl:
fix: Landing on cocoons actually gibs the person inside it now
/:cl:

Landing on cocoons actually gibs the person inside it now

---

code/__HELPERS/ai.dm

These lists can have nulls in them (due to harddels or otherwise) and it's not wise to feed nulls to this because it causes runtimes. This might fix motion sensor bricking at random and it fixes motion sensor not working if you get inside a locker.
Bug bad.
:cl:
fix: Motion sensor should keep working when inside a locker now
code: cheap_get_human/xenos_near shouldn't return nulls anymore
/:cl:

Fixes some motion sensor (and probably other) bugs

---

code/modules/mob/living/carbon/human/species.dm

Fixes #13701
:cl:
fix: Remove nutrition icon from robot hud
/:cl:

Remove nutrition icon from robot hud

---

TGS3.json

You are free my children. Be rid of this foul pox upon your soul

---

code/modules/reagents/reagents/medical.dm

Yeah. One letter mistake.
Runtime bad.
:cl:
fix: Fixed crit OD peri+ runtime
/:cl:

Fixes crit OD peri+ runtime

---

.gitattributes

Removed the duplicate dmm and dmi lines that borked the custom merge drivers. If you install them they'll actually work now

Clean up gitattributes

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Don't assume you'll be jabbing a human..
Runtime bad.
:cl:
fix: Fixed warrior punch trying to blind inanimate objects
/:cl:

Fixes warrior punch trying to blind inanimate objects

---

code/modules/events/hive_threat.dm

Yeah you can't `SEND_SOUND` directly to a list, byond doesn't like.
Runtime bad.
:cl:
fix: Fixed a hive threat runtime
/:cl:

Fixes hive threat runtime

---

code/game/objects/structures/barricade.dm

title
:cl:
fix: Fix jetpack not working over wired cades
/:cl:

Fix jetpack not working over wired cades

---

code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm

Bug bad. Bug go squish.
Bluespace prae is bad.
:cl:
fix: fixed a bug with praetorian acid dash
/:cl:

Fix funny prae bug

---

code/datums/jobs/access.dm
code/game/objects/items/binoculars.dm
code/game/say.dm

When you took your ID off your name would be `PVT  John`
:cl:
fix: Fix double leading space in paygrades
/:cl:

Fix double leading space in paygrades

---

code/datums/jobs/access.dm
code/modules/security_levels/keycard_authentication.dm

Awful
Awful proc bad
:cl:
code: Deleted old shitcode access proc
/:cl:

Deletes old shitcode access proc

---

code/modules/shuttle/mini_dropship.dm

Apparently forcing the action and the camera view on people who have the ui open can cause issues.
Bug bad.
:cl:
fix: Fixed people getting stuck in tad camera view
/:cl:

Fixes people getting stuck in tad camera view

---

code/modules/mob/living/carbon/human/human_defense.dm

Line in the wrong spot led to funny repeated throw impacts.
Giga throw bad.
:cl:
fix: fixed an issue with throwing some mobs not stopping correctly
/:cl:

Another throw fix

---

code/datums/jobs/job/fallen.dm
strings/tips/marine.txt
strings/tips/meta.txt
strings/tips/xeno.txt

does some edits on the roundstart tips for syntax + grammar; removes a few that are no longer true, as far as I can tell.
adds a space to the long message you get when entering valhalla about how rules still apply, etc.
keeps them kind of useful and fun for people; there may be some worthwhile stuff in here that people can learn things from and i'd hate to have just downright outdated and untrue things mixed in still
that missing space really bothered me!!!
:cl:
spellcheck: updates the roundstart tips
/:cl:

grammatical and info fixes on roundstart tips + adds a single space to the valhalla mobspawn message

---

code/datums/gamemodes/infestation.dm

Title.
Spam bad, this is my fault,
This is bad and my fault, needs fixed
:cl:
fix: Fixed being able to spam AI bioscans
/:cl:

Probably fixes AI biospam

---

code/datums/gamemodes/nuclear_war.dm
code/datums/jobs/job/shipside.dm

Read title.
Having 6 MD slots is a bit silly considering 3 is the **maximum** amount of doctors you would want in the Medbay (including CMO); anymore and it gets crowded and you have to fight over patients more than you already would have to.
:cl:
balance: Medical Doctor slots reduced to 2 from 6.
/:cl:

Reduces MD slots to four

---

code/_onclick/click.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_verbs.dm
code/modules/mob/mob.dm
code/modules/mob/mob_verbs.dm
code/modules/mob/new_player/new_player.dm

title
:cl:
add: Ghosts can point
/:cl:

Ghosts can point

---

code/game/objects/effects/overlays.dm

We had this define but it was unused
:cl:
fix: Pointing arrows are no longer hidden under things
/:cl:

Move points to the point layer

---

code/game/objects/machinery/vending/vending_types.dm

add station-bounced radio to engi-vend
I forgor (This was in autolathe)
:cl:
add: station bounced radio in engi-vend
/:cl:

add station-bounced radio to engi-vend

---

_maps/map_files/debugdalus/tgs_debugdalus.dmm

The debug ship can get a little confusing in prep sometimes. The markings should help with that. 
I think tagging is great and we should support our tagger artists
:cl:
qol: added some markings to the debugdalus 
/:cl:

Add some markings to the debugdalus squad prep

---

code/game/objects/items/stacks/tiles/tile_types.dm
code/game/turfs/floor.dm

Title.
This was being abused, so off it goes.
:cl:
balance: Welding floor tiles no longer generate metal
/:cl:

Removes ability to weld floor tiles into metal

---

code/controllers/subsystem/minimaps.dm
tgmc.dme

You aren't supposed to tick templates. CI does it in https://github.com/tgstation/TerraGov-Marine-Corps/blob/e2a5b6a3ec3e105f55124110fc824d71a8df352d/_maps/_basemap.dm#L25-L27
:cl:
fix: fixed maps
/:cl:

Fix map loading

---

code/game/objects/effects/aliens.dm
code/game/objects/structures/barricade.dm

Fixes acid spray getting blocked by things it shouldn't.
Fixes #13860
:cl:
fix: fixed acid sprays getting blocked by things that weren't supposed to
/:cl:

Acid spray fix

---

code/modules/mob/living/silicon/ai/ai.dm

When the AI spawns, it gets a random core icon. It helps people see the less common ones. 
I'll probably add a set preference for the icon in the future, but not tonight. 
More icon variety good. 
:cl:
add: AI core display is now random at spawn
/:cl:

The AI icon is now random at roundstart

---

code/modules/reqs/supplypacks.dm

Someone was begging so I did it.
Seems fine for it to be on order just like the others?
:cl:
add: Added the ALF to req imports
/:cl:

Adds the alf to req because someone asked

---

code/modules/projectiles/ammo_datums.dm

Fixes psyblast's AOE damaged potentially happening multiple times depending on how a victim is thrown.
Funny extra damage bad.
:cl:
fix: fixed Psyblast dealing more damage than intended in some cases
/:cl:

Psyblast fix

---

.github/workflows/update_tgs_dmapi.yml

yes this is the only one that was still using this token

Fix the update_tgs_dmapi action

---

.gitignore

https://github.com/tgstation/TerraGov-Marine-Corps/pull/13626/files added this to the gitignore, whew please just download vsc.
Random gitignore bad.
:cl:
config: Reverted random addition to gitignore
/:cl:

Revert random addition to gitignore

---

code/modules/clothing/modular_armor/modular.dm

title
lego good; git fudged up
:cl:
fix: fix lego hotaru so that you can actually put it on exoskeleton
/:cl:

fix lego hotaru

---

_maps/map_files/deltastation/deltastation.dmm
_maps/map_files/generic/Admin_Level.dmm

Fixed some space turfs that I accidentally put in
:cl:
fix: Fix some space turfs
/:cl:

Fix some space turfs

---

code/datums/components/admin_popup.dm

Use RegisterSignals where applicable

---

code/datums/jobs/job/shipside.dm

Read title.
People with 3 hours playing PO is probably not a good thing. Hopefully it works now.
:cl:
fix: PO timelock should work now.
/:cl:

Fixes PO timelock missing a var

---

code/datums/jobs/job/deathsquad.dm
code/game/objects/items/explosives/grenades/flashbang.dm
code/game/objects/items/portable_vendor.dm
code/game/objects/items/reagent_containers/autoinjectors.dm
code/game/objects/items/storage/pouch.dm
code/game/objects/items/weapons/energy.dm
code/game/objects/items/weapons/shields.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/marine_armor.dm

Adds to and updates the capabilities of Deathsquad members.
- Upgrades night vision goggles to current in game best
- Gives Deathsquad armor the grenade storage module, and packs the additional storage with specialty grenades.
- Updates the Medical kit and Elite Injector, ~~now about as strong as i can make it without using Adminorazine, or pushing the kidneys past their organ threshold. (Considered nerfing Ultrazine and putting it in as well, but seems like that'd be removing the primary weakness of Deathsquad.~~ (Also nobody needs the kits, you should be done killing everyone by the time kits would come into play.)
- Adds Binoculars, because you may as well scope out the place if you're going to fat run everywhere.
- Gives the leader a Xeno Structure pinpointer, just in case.
- Made …

Death squad amped

---

code/game/atoms.dm

title
More feedback good. Knowing you can't move because someone accidentally clickdragged you to a chair good
:cl:
add: Add a balloon alert for moving while buckled
/:cl:

Add a balloon alert for moving while buckled

---

code/__DEFINES/loadout.dm
code/modules/reqs/supplypacks.dm

Corrects all missed instances of SR-153 after the SG-153 prefix change in #13948 
Consistency and making up for missed info on the last PR.
:cl:
fix: Fixes references to SR-153 in the requisitions list and loadout files.
/:cl:

Fixes missed SR-153 Instances

---

code/game/objects/machinery/vending/marine_vending.dm

see title
:cl:
add: Adds the FAMAS and M412L1 HPR to valhalla. Go play with 'em.
/:cl:

adds the FAMAS and m412l1 HPR to valhalla

---

code/modules/unit_tests/spawn_xenos.dm

Fix spawn_xenos unit test evolving to primo three times

---

code/controllers/subsystem/monitor.dm
code/modules/mob/living/carbon/xenomorph/castes/king/king.dm

no player-facing changes. This should've gone with #13971

Remove SSmonitor deadcode

---

code/game/objects/structures/dropship_ammo.dm

Yes. Revert of https://github.com/tgstation/TerraGov-Marine-Corps/pull/13735, but I add a qdeleted check instead.
Eh this wasn't really intented, plus gau is already kinda bad so halving its damage makes it sad.
:cl:
balance: Gau hits twice again
/:cl:

Gau hits twice again

---

code/game/objects/structures/dropship_ammo.dm
code/modules/condor/cas_chair.dm
code/modules/condor/cas_shuttle.dm
tgui/packages/tgui/interfaces/MarineCasship.tsx

Redoes the CAS UI since I wasn't very good at UI 3 years ago and I've gone beyond spamming section and box to spamming stack
Same functionality with the exception of the deselect button which was removed
:cl:
qol: Redid the CAS plane UI
/:cl:

Mostly redoes the CAS UI

---

code/modules/admin/view_variables/reference_tracking.dm

Ports https://github.com/tgstation/tgstation/pull/78574/files
Better hard del tracking

Del unit test ref tracking port

---

code/datums/jobs/job/sons_of_mars_shipside.dm

fix shipside outfits

---

code/controllers/subsystem/minimaps.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm

Fucking guh. Fixes the funny hard del.
Please someone suggest a less rediculous way to do this.

Somewhat cursed lateload z-level minimap hard del fix

---

code/modules/projectiles/guns/rifles.dm

Fixes attachment visual offsets so it's not as fugly as sin.
visual bugs begone good
🆑 
fix: Fixed attachment offset of storm rifle
/:cl:

StormRifle Attachment Offsets Fix

---

code/modules/client/preferences_ui.dm

broken since #7000
:cl:
fix: Fix "Spawn as undefined" in job prefs, where the overflow job should have been
/:cl:

Fix "Spawn as undefined" in job prefs

---

code/modules/admin/callproc.dm

https://github.com/tgstation/tgstation/pull/61642/files
good
:cl:
admin: Fix runtime on init
/:cl:

Admin proccall followup fix PR port

---

code/game/objects/items/devices/minimap_tablet.dm

Fixes #14011
:cl:
fix: Fix drawing on minimap tablets
/:cl:

Fix drawing on minimap tablets

---

code/modules/projectiles/guns/energy.dm

There's some *issues* with shots not resetting. 
Bug bad.
:cl:
fix: Fixed an issue with quick laser swap
/:cl:

Quick laser swap fix

---

code/game/objects/effects/spawners/modularmappingspawner.dm
code/modules/mapping/modular_mapping.dm

Don't know why it was 29x25 when it's actually 29x24 in reality, seems to work fine ingame though
no player-facing changes

Fix a Big Red modular with incorrect height

---

code/game/objects/items/weapons/weaponry.dm

What it says on the tin. They're not really balanced in HvH, and serve no purpose in HvX.
Less funny stun memes in HvH
:cl:
del: Stunprods are no longer craftable
/:cl:

Uncraftable stunprods

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/projectiles/guns/rifles.dm

Fixes aug export mags not fitting, and vallhalla
bug bad, and camyrn says they would eat me raw if I didn't do this
:cl:
qol: EF-88/L-88 added to Valhalla
fix: EF-88 mags now fit inside EF-88 rifles.
/:cl:

AUG mag fix+vallhalla

---

code/game/objects/machinery/vending/marine_vending.dm

completely untested. yyzsong for valhalla maintainer 2024. The next motherfucker who adds a gun without putting it in valhalla I will hunt down and eat raw.
duplicate removal + missing add
:cl:
add: Adds russian red autoinjectors to the valhalla medical vcendor
fix: removes a duplicate item from the valhalla medical vendor
/:cl:

adds RR injectors to valhalla

---

code/modules/admin/debug_verbs.dm
code/modules/admin/holder.dm

Wanted to debug a SS but statpanel was down so I couldn't
:cl:
admin: Add Debug Controller verb
/:cl:

Add Debug Controller verb

---

code/game/objects/items/stacks/barbed_wire.dm
code/game/objects/items/stacks/sheets/mineral.dm

title
:cl:
fix: Fix some missing stack singular names
/:cl:

Fix some missing stack singular names

---

code/_onclick/click.dm
code/modules/mob/dead/observer/observer.dm

If you CTRL+SHIFT click yourself, it turns a ghost into a human.
Admin tools
:cl:
admin: CTRL+Shift click self to spawn as a human
/:cl:

Ports CTRL+SHIFT Click from TG for admins

---

code/modules/screen_alert/_screen_alert.dm

Fixed some errors due to a duplicate line of code in screen alerts.

screentext fix

---

code/datums/quick_load_outfits.dm
code/game/objects/machinery/vending/quick_vendor.dm
code/modules/projectiles/guns/rifles.dm

Spotting rifle for that plink plink on SOM domes.
More SG loadouts
:cl:
add: HvH: SG62 loadout added
/:cl:

SG62 hvh loadout

---

code/game/objects/machinery/vending/marine_vending.dm

mjp you stupid pipeworker your flesh is mine
shoot people
:cl:
add: Adds the two new ICC guns to valhalla 
/:cl:

adds the two new icc guns to valhalla

---

code/game/objects/items/reagent_containers/autoinjectors.dm
code/game/objects/items/reagent_containers/glass/bottle.dm
code/game/objects/items/reagent_containers/hypospray.dm
code/game/objects/items/reagent_containers/reagent_container.dm

Spellcheck dexaline -> dexalin
three doses -> 3 doses (same standard)
Deletes commented code
un-hardcodes possible_transfer_amounts 
plus autodoc
Better code, better UI, better autodoc
:cl:
spellcheck: Dexaline -> Dexalin. three doses -> 3 doses
code: un-hardcodes possible_transfer_amounts 
/:cl:

Atomization of #14116

---

code/game/objects/items/storage/holsters.dm
code/game/objects/items/weapons/blades.dm

Small buff to the FC's sword.
FC sword is literally just a worse machete currently, which is kinda sad.
- Has a strap and bump slash like machete
- Has a small amount of AP
- Has very slightly better attack speed
It's still objectively worse than using a spear, but at least it shouldn't be worse than a common machete anymore.
FC sord be gud.
:cl:
balance: FC's sword has a strap and bumpslash
balance: FC's sword has slightly improved attack speed and AP
/:cl:

giga FC buff

---

code/game/objects/items/explosives/plastique.dm

:cl:
fix: you can no longer make C4 instant
/:cl:

Fix an exploit allowing you to make C4 instant.

---

code/game/objects/structures/droppod.dm

:cl:
fix: Fix a missing trailing space before pod dchat announcement
/:cl:

Fix a missing trailing space before pod dchat announcement

---

code/modules/vehicles/mecha/_mecha.dm

Mechs can now crush mobs under foot.
Currently only works on human sized or lower. Hooman has to be already on the floor.
https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/bc3f4009-cec2-4fa1-9784-417007e869e7
Mechs are now 200% more enjoyable.
Adds more DYNAMIC PLAYER INTERACTION when mechs and little people are working together, or against each other.
:cl:
add: Mechs will now crush human sized mobs underfoot
/:cl:

Mech stomp

---

code/datums/gamemodes/campaign/faction_stats.dm

Should be less laggy for some people.
:cl:
code: campaign status screen uses static data
/:cl:

Campaign status uses static data

---

code/game/objects/machinery/bots/bots.dm

:cl:
spellcheck: Spellchecked some bot messages
/:cl:

Spellchecked some bot messages

---

code/modules/mob/new_player/new_player.dm

Added a little background info for the SOM in the lobby background tab that probably no one actually reads.
More fluff is good. Gives you an idea of what the SOM's deal is.
:cl:
add: Added some background info for the SOM in the lobby menu
/:cl:

SOM background fluff info

---

code/datums/gamemodes/campaign/faction_stats.dm
tgui/packages/tgui/interfaces/CampaignMenu/CampaignAssets.tsx
tgui/packages/tgui/interfaces/CampaignMenu/CampaignMissions.tsx
tgui/packages/tgui/interfaces/CampaignMenu/CampaignOverview.tsx
tgui/packages/tgui/interfaces/CampaignMenu/CampaignPurchase.tsx
tgui/packages/tgui/interfaces/CampaignMenu/index.tsx

Fixes a BSOD on the mission tab if you run out of missions.
The mission tab will properly close the confirmation screen when pressing yes.
UI is a bit prettier with icons.
Better UI stuff
:cl:
qol: Some general campaign UI improvements
fix: fixed a BSOD on the campaign UI if no missions were available
/:cl:

Campaign UI improvements

---

code/modules/projectiles/guns/shotguns.dm

Per title.
Very powerful shotgun, shouldn't be something you can one hand.
:cl: Lewdcifer
balance: Sawn off shotgun must now be wielded to fire.
/:cl:

Sawn-off shotgun must now be wielded to fire

---

code/datums/skills.dm

synth deals doctor damage on melee (so like less)
combat synth deserves a nerf
:cl:
balance: Synths deal less damage on melee now.
/:cl:

synth has a melee damage malus

---

code/game/objects/items/marine_gear.dm

cement
mmm... cement...
:cl: Lewdcifer
add: Cement protein bar. Mmm... cement...
/:cl:

Adds the cement protein bar

---

tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx

Forgot to add the new officer roles to job prefs.
Selectable preround jobs is good.
:cl:
fix: SOM officers are properly in job preferences
/:cl:

SOM officer prefs

---

code/modules/projectiles/guns/energy.dm

If you change a lasguns mode, it makes the gun invisible. I fixed it
Fixes
:cl:
fix: Fixes lasguns becoming invisible after changing modes.
/:cl:

Fixes Lasguns inhands

---

code/__byond_version_compat.dm
code/modules/client/client_procs.dm
code/modules/mob/living/silicon/ai/freelook/eye.dm

not very significant but should be done for completeness

VERB_REF for 515

---

code/modules/shuttle/marine_dropship.dm

Fix a unsanitized log message

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm

adds psychic whisper to hivemind abilities
flavor for the omni-caste
:cl:
add: gives hiveminds psychic whisper
/:cl:

give hivemind psychic whisper

---

code/modules/condor/cas_chair.dm
code/modules/condor/cas_shuttle.dm
tgui/packages/tgui/interfaces/MarineCasship.tsx

I somewhat recently got to play around with CAS again after a long long while of not having used the Condor, and immediately noticed several questionable oversights in it.
One allows you to begin firemissions while still in your hangar, which I have not been able to precisely pin down when it was caused (years ago probably), but some people have confirmed sharing my memory you did in fact need to be in space to use CAS guns before.
Another allowed you to begin fire missions while on return flights, which given it boots you out of all fire missions when you hit "return" seems inappropriate.
A third is also fixed, however I will not elaborate on its exact nature due to it being less-known and potentially more exploitable than the others.
If I'm able to play like two rounds of CAS, and …

Fixes some CAS oversights

---

code/game/objects/structures/crates_lockers/largecrate_supplies.dm

#13969
:cl:
fix: Fix x8 DRPG crate containing only one DRPG
/:cl:

Fix x8 DRPG crate containing only one DRPG

---

code/__DEFINES/loadout.dm

see title
efficient cat herding
:cl:
add: SLs may buy megaphones from their vendor
/:cl:

SLs may now buy megaphones

---

code/modules/mob/living/carbon/xenomorph/evolution.dm

fixing my own mistake
fix
:cl:
fix: Evolution overlay runtime error fix
/:cl:

Evolution overlay runtime error fix

---

code/modules/clothing/masks/breath.dm

Updated some old code, also made it so it longer hides facial hair, it is already rendered over it, there is no point in hiding it, it only causes funny moment when your whiskers vanish because of it.
Also made it so switching between bandana modes actually makes logical sense in terms of stats.
More visual clarity - good.
:cl:
del: bandana no longer hides facial hair
/:cl:

Bandana no longer hides facial hair

---

code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Fixes a hugger sprite issue, that caused it to stay on the throw icon for a second longer than it should.
This had no game impact however, it was purely visual.
Visual fix.
:cl:
fix: fixed a minor visual issue with throwing huggers
/:cl:

hugger sprite fix

---

code/modules/clothing/modular_armor/modular.dm

Fixed an issue where headwear with an emissive visor would display when in hand, but not when worn.
Bug fix good.
:cl: Lewdcifer
fix: Fixed an issue where headwear with an emissive visor would display when in hand, but not when worn.
/:cl:

Fixes an issue with headwear visor behavior

---

tgui/public/tgui.html

this is a problem as of https://github.com/tgstation/tgstation/issues/79215

Fix a reference to tgstation's issue tracker in tgui

---

code/game/objects/items/weapons/blades.dm
code/game/objects/items/weapons/misc.dm

Original pr wasn't meant to be merged.
Fixed some code guh, and brick is no longer comically strong. Bricks no longer magically transmute into stone.
You're lucky I didn't just revert it.
:cl:
balance: Reduced brick damage somewhat
/:cl:

Bricks the brick

---

code/game/objects/items/stacks/barbed_wire.dm
code/game/objects/items/stacks/rods.dm

Currently dismantling 2 razorwire structures returns 8 rods and 2 barbed wires.
The creation of 2 razorwire structures  requires 8 rods and 1 barbed wire.
Infinite barbed wire bad.
changes recipe from 8 rods 1 barbed to 8 rods 2 barbed.
infinite barbed wire bad.
:cl:
balance: razor wires cost 8 iron rods 2 barbed to make
fix: fixes infinite barbed duplication
/:cl:

Fixes razorwires from producing infinite barbed wires.

---

code/game/objects/items/reagent_containers/hypospray.dm

Changes imialk mix:
1u Alk, 4u Imi, injection set to 5u
Gives you 20 chem cycles of imialky
Totals out to 12 uses (up from 6)
Better hypo mix
:cl:
balance: improves imialk hypo
/:cl:

Adjust imialky hypo

---

code/modules/reqs/supply.dm

Updates the description of the radio backpack to clarify it has access to a supply request console.
Current description makes it seem like it's just a re-skin of the normal backpack, this makes it's differences more apparent.
:cl:
spellcheck: Updated the description of the radio backpack to clarify it's access to a supply request console.
/:cl:

Updates Desc Of Radio Backpack

---

code/game/objects/machinery/cic_maptable.dm

So the checks worked fine, I just forgot one word so the tools were given to the ghost anyway. Aylmao.
Working fix
:cl:
fix: fixed ghosts drawing on maptables for reals
/:cl:

Fix drawing ghosts5real

---

code/game/objects/machinery/vending/marine_vending.dm

Kinda weird the tool vendor is missing one tool.
:cl:
add: Youtool vendor stocks multitools
/:cl:

Multitool in tool vendor

---

_maps/map_files/generic/Admin_Level.dmm

Grayson told me to move these carps
:cl:
fix: moves 2 carps
/:cl:

Moves props on admin level

---

code/modules/projectiles/guns/mounted.dm

Per title.
I'm not trying to balance this I just want to be able to hear what's sundering the ever living shit out of me so I can react to it.
:cl: Lewdcifer
balance: MG-27 no longer accepts suppressors.
/:cl:

MG-27 no longer accepts suppressors

---

code/__DEFINES/__game.dm

:cl:
code: Delete unused chigusa define
/:cl:

Deletes unused define

---

code/modules/power/power_monitor.dm

Fixes power monitor sprites.
Its another pretend computer that got missed.
Working sprite good.
:cl:
fix: fixed power monitor sprites
/:cl:

Power monitor sprite

---

code/game/objects/machinery/vending/vending_types.dm

Forgot to add to valhalla when put in base NTMED
:cl:
add: Syringe Case in Valhalla NTMED
/:cl:

Syringe Case Valhalla NTMED

---

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm

:cl:
fix: Deleted stacking pipes on Prison Station.
/:cl:

Deletes stacking pipes on Prison Station.

---

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm

Also deleted duplicate ai_node.
:cl:
fix: Deleted stacking pipes on Magmoor.
/:cl:

Deletes stacking pipes on Magmoor.

---

_maps/map_files/Iteron/Iteron.dmm

Less runtimes during setup
:cl:
fix: Deleted stacking pipes on Iteron.
/:cl:

Deletes stacking pipes on Iteron.

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm

:cl:
fix: Deleted stacking pipes on Ice Colony.
/:cl:

Deletes stacking pipes on Ice Colony.

---

code/game/objects/machinery/cic_maptable.dm
code/game/objects/machinery/squad_selector.dm
code/modules/vehicles/mecha/mech_bay.dm

title
:cl:
fix: Fix invisible squad selection console
fix: Fix invisible mech bay power console screen
fix: Fix tacmap console emissive
/:cl:

Fix some broken emissives

---

code/game/objects/items/weapons/twohanded.dm

Apparently it has been broken since some rework that changed stun values.
Also updated description to inform the user that they can change attack modes.
fix
:cl:
fix: fixed rocket sledgehammer having incorrect stun values
/:cl:

Rocket Sledgehammer Fix

---

code/modules/mob/mob_helpers.dm

People were using this to cheat SG skill
:cl:
fix: Fix recoil not working properly with a scope
/:cl:

Fix recoil not working properly with a scope

---

code/game/objects/items/portable_vendor.dm
code/game/objects/machinery/vending/new_marine_vendors.dm
code/game/objects/machinery/vending/vending.dm
code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
code/modules/reagents/machinery/chem_dispenser.dm

Removed all calls to updateUsrDialog from tgui as it doesn't need this to update
:cl:
fix: Fix cryo pod and some other UIs opening their window when they shouldn't
/:cl:

Remove useless uses of updateUsrDialog

---

code/game/objects/items/explosives/grenades/marines.dm

Fixes flares not extinguishing on nodes when you throw them.
Fixes #14350
Fix good.
:cl:
fix: fixed flares not hitting weed nodes
/:cl:

flare throw fix

---

code/_onclick/click.dm
code/game/objects/items/reagent_containers/pill.dm

Removes the delay on eating pills.
Makes it so you can use a pill in-hand to eat it.
Makes pill munching so much more fluid. 
:cl:
balance: pills no longer input-lock you
qol: You can use a pill in-hand to eat it.
/:cl:

Makes eating pills more fluid

---

code/game/objects/machinery/camera/tracking.dm
code/game/objects/machinery/computer/medical.dm
code/game/objects/machinery/computer/security.dm
code/modules/mob/living/carbon/human/human.dm

deprecated and harder to read than `[]`

Kill text()

---

code/modules/screen_alert/command_alert.dm

It was previously only being shown for whoever sent the order
:cl:
fix: Fix orders not being shown in chat
/:cl:

Fix orders not being shown in chat

---

code/modules/ai/ai_behaviors/ai_behavior.dm

Per title.
Bug fix good.
:cl: Lewdcifer
fix: Fixes a runtime related to AI movement.
/:cl:

Fixes a runtime related to AI movement

---

code/__HELPERS/math.dm
code/datums/datacore.dm
code/game/objects/items.dm
code/game/objects/items/explosives/grenades/marines.dm
code/game/objects/structures/prop.dm
code/modules/hydroponics/hydro_tools.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
code/modules/reagents/reagents/medical.dm
code/modules/shuttle/on_move.dm
code/modules/vehicles/multitile/cm_armored.dm

so... like....
`rand()`
it's a proc right?
 
to give you random numbers?
between two numbers?
 
 
what are numbers in byond?
floats, right?
so, rand() should work with floats, right?
 
 
right?
 
...right?
.........RIGHT?
 
**no.**
 
**_it doesn't._**
 
 
 
 
contribute to opendream today
 
 
 
code ported from goonstation ([pali](https://github.com/pali6)), not really copyrightable but they gave permission
byond just never fails to disappoint doesn't it
fixes spiderlings being shit and runtiming
admins begging yet no coders fix
sad
:cl:
fix: Spiderlings and some assorted damage rolls should now actually work instead of being super weird
/:cl:

this language purports to only use floats but then doesn't (spiderling runtime fix)

---

code/__DEFINES/machines.dm
code/game/objects/effects/acid_hole.dm
code/game/objects/items.dm
code/game/objects/obj_defense.dm
code/game/turfs/closed.dm
code/modules/atmospherics/machinery/components/binary_devices/binary_devices.dm
code/modules/atmospherics/machinery/components/trinary_devices/trinary_devices.dm
code/modules/atmospherics/machinery/components/unary_devices/heat_exchanger.dm
code/modules/atmospherics/machinery/pipes/heat_exchange/junction.dm
code/modules/atmospherics/machinery/pipes/layermanifold.dm
code/modules/lighting/lighting_static/static_lighting_corner.dm
code/modules/mapping/space_management/space_transition.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
code/modules/power/cable.dm
code/modules/power/pipecleaners.dm
code/modules/power/smes.dm
code/modules/recycling/conveyor2.dm
code/modules/recycling/disposal-construction.dm
code/modules/recycling/disposal.dm
code/modules/shuttle/docking.dm
code/modules/vehicles/multitile/cm_armored.dm

microop and makes use of a define

Use REVERSE_DIR instead of `turn(x, 180)`

---

code/_globalvars/lists/mobs.dm
code/controllers/master.dm
code/controllers/subsystem/server_maint.dm
code/datums/emergency_calls/sons_of_mars_breachers.dm
code/game/objects/items/explosives/mine.dm
code/game/objects/machinery/overwatch.dm
code/game/objects/structures/dropship_equipment.dm
code/game/turfs/floor_ground.dm
code/modules/mob/living/carbon/xenomorph/castes/puppet/abilities_puppet.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/projectiles/ammo_datums.dm

These were mostly typos and procs that were missed during repaths. No player-facing changes other than what's in changelog
:cl:
fix: Fix SOM breacher ERT scaling the amount of specs incorrectly
fix: Fix player-controlled puppets being able to feed on non-adjacent humans
/:cl:

Fix SDMM lints

---

code/modules/projectiles/gun_helpers.dm

So guns with a long wield time (e.g. SVD) can be aim moded during the do_after
:cl:
qol: You can now toggle auto aim mode while trying to wield a gun
/:cl:

You can now toggle auto aim mode while trying to wield a gun

---

_maps/map_files/icy_caves/icy_caves.dmm

TLDR; icy caves now passes the unit tests.
Re-areas one part of Icy Caves to use the Morgue area (because it wasn't used previously?), to ensure all areas have one APC. Also made sure those APC's had wires leading to them (they didn't before!)
`[2023-11-14 05:47:07.952] Starting up round ID .
- -------------------------
[2023-11-14 05:47:59.831] PASS: /datum/unit_test/area_apc_sanity 0s
[2023-11-14 05:48:00.017] PASS: /datum/unit_test/bespoke_id 0s
[2023-11-14 05:48:00.037] PASS: /datum/unit_test/binary_insert 0s
[2023-11-14 05:48:00.058] PASS: /datum/unit_test/chat_filter_sanity 0s
[2023-11-14 05:48:00.081] PASS: /datum/unit_test/component_duping 0s
[2023-11-14 05:48:00.102] PASS: /datum/unit_test/connect_loc_basic 0s
[2023-11-14 05:48:00.135] PASS: …

Fixes Icy Caves APCs

---

code/modules/factory/parts.dm
code/modules/factory/unboxer.dm
code/modules/reqs/supplypacks.dm

see title
a completely untested pr
RO mains rejoice
:cl:
add: adds refills for unguided sadar rockets and SG-62 magazines to req
/:cl:

adds unguided sadar and sg 62 reqtorio

---

code/game/objects/structures/xeno.dm
code/game/turfs/walls/resin.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/evo_datum.dm
code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm

Xenos can spawn in valhalla before the game starts, so assuming it started is bad
:cl:
fix: Fix evolving when the game hasn't started
/:cl:

Fix pre-game xeno runtimes

---

code/datums/datacore.dm

title
:cl:
fix: Fix custom squad members not showing in manifest
/:cl:

Fix custom squad members not showing in manifest

---

code/__DEFINES/rust_g.dm
code/datums/helper_datums/getrev.dm
dependencies.sh

Needed for #14376. rust_g.dll from https://github.com/vvvv-vvvv/rust-g/actions/runs/6756473831

Bump rust-g to 3.0.0

---

code/game/objects/items/storage/pill_packets.dm
code/game/objects/items/storage/pouch.dm
code/game/objects/machinery/vending/marine_vending.dm

The maintainers are furiously throwing dice at each other and we rolled double six's. According to the wheel that means you get pill bottles back.
Replaced packets entirely with pill bottles for marine use.
Unga gets to gobble more pills.
:cl:
balance: Replaced packets with pill bottles for all marine use
/:cl:

Pill bottles for all

---

code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Fixed huggers not jumping on people if they're on the same tile, or prone people at all.
I'm not entirely sure what change broke this, but it would have been me either with as throw change or hugger change so eh.
Fix good
:cl:
fix: fixed huggers not hugging people in some cases
/:cl:

Hugger fix

---

code/datums/gamemodes/campaign.dm
code/datums/gamemodes/campaign/missions/base_rescue.dm
code/game/objects/machinery/computer/nt_access.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm

**Base rescue mission specific**
- Fixes the ghost role not being able to free itself properly
- Fixed it not properly despawning at mission end
- Fixed the disk computers being incorrectly flagged as objectives
**General**
- Neutral faction can now respawn freely between missions (i.e. you're not locked out for 30 minutes if you went valhalla)
Fixes good.
:cl:
fix: fixed a few campaign bugs
qol: 3rd party faction are not locked behind the 30 min respawn timer in campaign, when between missions
/:cl:

Campaign fixes

---

code/modules/projectiles/projectile.dm

Fixes #12799
Fixes #14505
:cl:
fix: Fix lascarbine spread pointblanks shooting past the target
/:cl:

Fix lascarbine spread pointblanks shooting past the target

---

code/modules/mob/living/say.dm

Don't blindly port stuff from tg. We can have non mask types in the mouth slot here.
runtime bad
:cl:
fix: TTS mask runtime fix
/:cl:

TTS mask runtime fix

---

code/controllers/subsystem/ping.dm
code/controllers/subsystem/processing/resinshaping.dm

title
this makes it cbt to debug them, you have to go through sdql to select them
:cl:
fix: Fixed SSresinshaping and ping not returning their stat panel entry
/:cl:

Fix SSresinshaping and ping not returning their stat panel entry

---

code/game/objects/items/reagent_containers/autoinjectors.dm
code/game/objects/items/reagent_containers/hypospray.dm
code/game/objects/items/reagent_containers/pill.dm
code/game/objects/items/storage/firstaid.dm
code/modules/reagents/reagents/medical.dm

title
to further reinforce that alkysine heals brain and ear damage
:cl:
add: update alky meds' desc to include healing ear damage
/:cl:

update alky meds' desc to include healing ears

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/map_files/slumbridge/slumbridge.dmm

github desktop moment
tiny, dense, movable, unslashable objects 🤮 
:cl:
balance: kills portaflashers
/:cl:

Kills portaflashes for real this time

---

code/game/objects/machinery/camera/camera.dm

DESACTIVED 
:cl:
spellcheck: fixed desactived to deactivated in camera code
/:cl:

fix spelling on camera

---

code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/mob/living/init_signals.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_defines.dm

Tiny cleanup, we have a sig register proc for init, so we should be consistant with using it.
Code improvement
:cl:
code: some code clean up for living mob init
/:cl:

init sig register stuff

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

I honest to god have no idea how nobody noticed this epic logic error and how it's been unreported so long.
Added a safety net in case this somehow happens again.
closes #14522
bug bad
:cl:
fix: Xenos should no longer have quickbuild outside of prep
/:cl:

Fixes a quickbuild bug

---

code/game/objects/machinery/computer/nuke_disk_generator.dm

title
:cl:
fix: Fix tadpole being able to land on disks
/:cl:

Fix tadpole being able to land on disks

---

code/game/objects/machinery/computer/general_air_control.dm
code/game/objects/machinery/teleporter.dm

title
:cl:
fix: Fix some computer emissives
/:cl:

Fix some computer emissives

---

code/__DEFINES/loadout.dm
code/game/objects/machinery/vending/marine_vending.dm

Title, they couldn't pull from non existant vendors.
Valhalla working good
:cl:
fix: Fixed valhalla loadout vendor not working in hvh
/:cl:

Fixes valhalla loadout vendor not working in hvh

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

Autoweed was bypassing a check.
Exploit bad.
:cl:
fix: fixed an exploit with autoweeding
/:cl:

Autoweed exploit fix

---

code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/projectiles/gun_system.dm

closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14006
closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/13541
This is prob shitcode, im tired
bug bad
:cl:
fix: Synth actually can DNR properly now
fix: Unrevivable people shouldnt show up as revivable anymore
/:cl:

Fixes some minimap dnr issues

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

I think the action refactor broke this since they were merged at the same time.
Fixed a bug, removed an extra check since can_use_ability calls it anyway.
:cl:
fix: fixed an issue with autoweed
/:cl:

Autoweed fix

---

code/modules/mob/living/carbon/human/examine.dm

title
:cl:
fix: Fix grammar in human examine text
/:cl:

Fix grammar in human examine text

---

code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm

Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14580
exploit bad
:cl:
fix: Fixed widow being able to go over the spider limit
/:cl:

Fix a funny widow exploit

---

code/game/objects/machinery/vending/marine_vending.dm

Namely the clothing, armor, mech and youtool vendor.
These should not be something you should be able to bring groundside ever, they bring shipside level supply groundside at no cost.
:cl:
balance: Makes standard marine vendors unwrenchable
/:cl:

Makes standard marine vendors unwrenchable

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm

admins if you see someone doing this youre free to nuke them from existance
bug bad
:cl:
fix: Fixed defender being able to move dead bodies
/:cl:

Fix defender being able to move dead bodies

---

code/modules/vehicles/sealed.dm

Fixes entering a mech.
During the do after update I mistook where an arg was, whoops.
Unenterable mechs bad
:cl:
fix: fixed mechs being impossible to enter
/:cl:

Mech entry fix

---

code/modules/admin/debug_verbs.dm
code/modules/admin/topic.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_defense.dm

Stinky legacy initial commit proc which we have a better actually working version of
bad proc bad
:cl:
code: Killed get_contents
/:cl:

Kill get_contents

---

code/__DEFINES/chat.dm
code/controllers/subsystem/chat.dm
code/datums/chat_payload.dm
code/modules/tgchat/README.md
code/modules/tgchat/to_chat.dm
code/modules/tgui/tgui_window.dm
tgmc.dme
tgui/packages/tgui-panel/chat/middleware.js

Add a chat reliability layer

---

code/modules/clothing/modular_armor/attachments/modules.dm

Original PR had a typo that made the intended functionality not properly apply, which neither I nor maints spotted. I did some mildly cursed things to be able to debug me seeing it not work, and found this.
Should actually really work this time, now even with actual testing
Fix man good.
:cl:
fix: The antenna module now actually does what it says it does.
/:cl:

Fixes antenna

---

code/modules/requisitions/supply_export.dm

not cool exploit 
this shouldnt be happening
:cl:
del: Pizza doesn't net cas points anymore
/:cl:

Pizza doesn't net cas points anymore

---

code/__HELPERS/unsorted.dm

HOW IS THIS VALID SYNTAX
:cl:
code: Fix more 515 regex fuckup
/:cl:

Fix wrong 515 regex

---

code/datums/personal_statistics.dm

haha silly me
bad
:cl:
fix: Fixed export denied personal stat
/:cl:

Fix export denied personal stat

---

code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm

Minor tweaks.
Updated jetpack to heavy jetpack.
Gave the MG loadout a deployable shield.
Removed some unneeded lines.
Minor improvements/cleanup
:cl:
balance: Small changes to combat robot loadouts in campaign
/:cl:

Campaign combat robo tweaks

---

code/modules/projectiles/guns/energy.dm

Fixes some eguns that have the wrong skill associated with them.
Shouldn't be any player facing changes since no one has these skills anyway.
Clean up before future changes
:cl:
fix: Corrected the type of gun skill associated with some energy weapons
/:cl:

Misc gun skilltype changes

---

code/game/objects/structures/xeno.dm

funy
i hate accidentally melting this instead of something on top of it
:cl:
fix: You cannot melt sticky resin anymore
/:cl:

Makes sticky resin unacidable

---

_maps/map_files/icy_caves/icy_caves.dmm

What it says on the tin. Deleted pipes that had its copy below it.
Less errors while Initializing.
Not player facing.

Deletes stacking pipes on Ice Caves.

---

code/controllers/subsystem/advanced_pathfinding.dm
code/controllers/subsystem/autofire.dm
code/controllers/subsystem/modularmapping.dm

so that there is some sort of pattern in these names

Change some SS names to be nicer to read

---

code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm

salt pr
it isn't but it bothers me
:cl:
code: shrike code comment now says 3x3 instead of 2x3
/:cl:

updates this stupid shrike comment

---

code/modules/reqs/supplypacks.dm

see title
whoops
:cl:
fix: SG-62 reqtorio should work properly now.
/:cl:

Fixes SG-62 reqtorio

---

code/modules/organs/limbs.dm

title
:cl:
fix: Fix emote spam when losing grasp of NODROP items
/:cl:

Fix emote spam when losing grasp of NODROP items
