code/modules/projectiles/gun_attachables.dm, code/modules/projectiles/gun_system.dm
Barrel chargers now slightly reduce projectile damage falloff.
Barrel chargers are kinda useless currently. They increase projectile speed but reduce accuracy, where as an EB increases projectile speed, accuracy and scatter. This should give it some niche benefit for longer range shooting, especially with lower damage projectiles.
BC has a very small niche instead being basically trash.
:cl:
balance: Barrel chargers reduce projectile damage falloff slightly
/:cl:
=> Barrel charger improvement

_maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm, code/game/objects/machinery/floodlight.dm, code/modules/reqs/supplypacks.dm
The following changes have been made to Combat Floodlights:
- Fixed a typepath issue.
- No longer acidable, but can now be damaged by slashes.
- Floodlights have a maximum integrity of 500.
- Can now be repaired using welders. Each welder use will restore 100 integrity.
- Remaining integrity is visible by examining the floodlight.
- Reduced their cost in requisitions from 100 to 30 points.
Further enhances marine visibility and makes Combat Floodlights worth a damn.
As discussed with @TiviPlus, floodlights should be complicated to deal with, but scarce in amount.
:cl: Lewdcifer
balance: Combat Floodlights are no longer acidable, but can now be damaged by slashes.
balance: Combat Floodlights can now be repaired using welders. Examine the Floodlight to see its remaining integrity.
balance: …
=> Buffs Combat Floodlights

code/modules/projectiles/ammo_datums.dm
0 sunder, nada.
These are free, roundstart and on an incredibly tough piece to kill, they shouldn't really sunder at all considering their high damage and penetration.
:cl:
balance: Mech Heavy Cannon and sniper no longer have sunder.
/:cl:
=> mech APFDS (Heavy cannon) and sniper no longer sunder

code/modules/clothing/clothing.dm, code/modules/clothing/shoes/marine_shoes.dm
Per title. Looking at you, western boots.
- There's many off cases where shoes have no armor values despite being supposed to.
- Just because your shoes weren't in the standard clothing vendor doesn't mean you should have 0 armor. #Justice4ERTs.
- Hardly part of my actual argument, but... c'mon. Even in real life the most poor of materials in a shoe can at least provide _some_ form of protection.
:cl: Lewdcifer
balance: All shoes now have the same armor unless specified otherwise.
/:cl:
=> All shoes now have the same armor unless specified otherwise

code/datums/gamemodes/combat_patrol.dm, code/datums/gamemodes/sensor_capture.dm
Fixed an issue where SC rounds could suddenly end while there is still time on the clock.
Cleaned up the code a little as well.
SC was setting the game timer in addition to the base code for combat patrol already doing this. Although there was a check to see if an existing timer was present, that's not the best way to do it, and after I made towers pause the timer, it meant if a tower was contested at the 5 minute mark, a phantom game timer would be set.
Gamemode working properly is good.
:cl:
fix: Sensor Capture: Fixed an issue where the game could end unexpectedly
/:cl:
=> Fix sensor capture timer bug

code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
This fixes mecha smoke module having the wrong smoke path
A fixed module is a better module
GrayRachnid
:cl:
fix: fixed mecha tactical smoke, now properly launches cloaking smoke.
/:cl:
=> Fixes mecha tactical smoke

code/modules/vehicles/mecha/mecha_defense.dm
Changes mech repair speed to 4 seconds instead of 2 seconds. Fumble time is also 4 seconds.
This is still fairly low all things considered however.
Currently you can repair mechs giga fast, which tends to make xenos cope as the time to repair a mech vs the time to cause that damage is pretty wack.
Makes severely damaging mechs (slightly) more rewarding for xenos.
:cl:
balance: Increased mech repair and fumble time to 4 seconds
/:cl:
=> Mech repair speed reduction

code/_onclick/hud/human.dm, code/_onclick/hud/screen_objects/screen_objects.dm
removes these things
noob bait to use, all of these things are keybindable and can be used by actions on the top left
:cl:
del: Removed old cm gun actions
/:cl:
=> remove old cm actions for guns

code/datums/skills.dm
The CSE had the same leadership level as the Captain/FC.
I've changed his leadership to reflect his rank shipside, earning him the same leadership level as a Squad Leader/Staff Officer
The CSE no longer has a higher leadership than squad leaders and staff officers.
GrayRachnid
:cl:
balance: The CSE should not be having Captain/FC level leadership
/:cl:
=> Brings the CSE's leadership down to a more reasonable level

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Fixed a bug with summon where dead/qdel'd xenos could get summoned.
Bug fix good.
:cl:
fix: fixed a bug with King's summon
/:cl:
=> King summon fix

_maps/map_files/Minerva/TGS_Minerva.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm
title
Part of Lewd's light REBALANCE after he removed imager. He noted that combat floodlights are not used as much, so he made them cheaper to buy from req. Since the buff was not enough, he wanted to allow engineers to have a taste of what floodlights can do by making them free.
:cl:
add: 4 floodlights to all shipside maps
balance: xenomorphs will have a harder time engaging marine fixed positions due to more lights
/:cl:
=> add 4 floodlights to all shipside maps

code/modules/mob/living/carbon/human/human_defense.dm
Currently the chance to stun a human is based off raw damage, not damage done after armour is taken into account.
Edit: PR not only effects stun chance, no change to stun durations.
stuns ignoring armour is bad.
:cl:
balance: Melee stuns now respect armour when calculating probability
/:cl:
=> Melee stun chance now factor in armour

code/modules/projectiles/ammo_datums.dm
So it turns out bean bag rounds stun for like 12 seconds or something hilarious. This is not ideal.
Giga stun bad.
:cl:
balance: Beanbag slugs no longer has a comically long stun duration
/:cl:
=> Beanbag nerf

code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
OLD HP Scaling
450->500->600->700
New
575->600->625->650
King HP scaling right now is absurd, the difference is insane between levels, the EHP is insane at 700HP, this should help alleviate that atleast a bit, while making younger levels of kings more consistent between themselves.
:cl:
balance: King HP scaling changed from 450->500->600->700 to 575->600->625->650.
/:cl:
=> King HP nerf and scaling change

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Slightly decreases recon mech part health by 100 total, greatly decreases assault and vanguard mech part health by 550 total and 1100 total respectively. 
Using the ancient ravager and praetorian index (each does 30 damage a hit), a full recon mech needs 34 hits, the assault mech needs 64 hits, and the vanguard needs 97. This does not include the resistance modules. Mechs are simply too tanky right now, capable of absorbing so much damage that even a full swarm struggles to take one down unless the MP is very far out of position and away from support. 
Needless to say mechs aren't particularly fun to fight, and they have king syndrome of surviving situations they really shouldn't be surviving. This makes it so on that same index, full recon needs 30 hits, assault 45, and vanguard 60. …
=> Makes mechs (mostly assault and vanguard) substantially less tanky.

code/game/objects/machinery/cloning/cloning.dm
From "You can't get to the beaker while the machine growing a clone"
to "You can't get to the beaker while the machine is growing a clone."
No more popped blood vessels from seeing a grammar issue in 2023.
:cl:
fix: added a missing "is" to clone vat's error message when removing a beaker
/:cl:
=> Misspelling fix when trying to remove cloning vat beaker

code/game/objects/items/tools/surgery_tools.dm
Y'all can't behave so yet another infinite material exploit is being patched.
Fixes #12012 
:cl:
balance: Surgery tool cost reduced by 99% to prevent quick infinite free metal by vending pouches.
/:cl:
=> Reduces surgery tool material costs

code/modules/projectiles/ammo_datums.dm
Title.
2 heavy, 4 light to 5 light.
Free HE sadar roundstart is goofy, this should be better considering its closer to RR LE than anything else.
:cl:
balance: Mech Rocket launcher no longer has heavy explosion, it now has 1 more tile of light explosive range.
/:cl:
=> Mech Rocket nerf removes heavy explosion, +1 Light explosion

_maps/map_files/Sulaco/TGS_Sulaco.dmm
Title
Sulaco has a comm issue that can be fixed by replacing extra comm with FC dorms. From the void from FC dorm, SOs have dorms for themselves.
:cl:
add: new FC and SO dorms
fix: extra tcomm in Sulaco, which annihilate comm issues in Sulaco
/:cl:
=> annihilate extra tcomm in Sulaco w/ dorm changes

code/modules/mob/living/carbon/xenomorph/evolution.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm
The king PR is turns out was merged before a final change was pushed, so the death timer wasn't working. Honk.
King death timer is 7 minutes (queen is 5 minutes for comparison).
Bug fix good
:cl:
fix: fixed the King death timer
/:cl:
=> king death timer fix

code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm, code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Having a base bomb armour of 100 or more no longer makes a xeno entirely immune to explosions.
Xeno gib threshold now takes sunder into account and changed to 5 (this still only applies to devastate level explosions).
Crusher and defender's fortify bomb armour slightly increased.
Currently, if something like a crusher is sundered by 50% (i.e. it only has 50 bomb armour currently) it is still entirely immune to explosions due to the check occuring prior to sunder being taken into account. Now, it will check armour after sunder and pheromones are taken into account.
This isn't as dramatic as it might seem at first glance. Explosion damage, slowdown and stagger are all modified by bomb armour anyway, so unless you're severely sundered, mr crusher is still not really going to care much. …
=> Xeno Ex_act fix

code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Fixed xenos getting gibbed by OB's when they shouldn't.
I did a funny and forgot to update a thing.
Every xeno getting gibbed by OB is not ideal
:cl:
fix: fixed xenos getting gibbed by devestating explosions when they shouldn't have
/:cl:
=> Fix xeno bomb checks

code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
A year and a half ago, the mechanics of climbing into the ventilation were reworked. Larvae and hunters had to get into the ventilation quickly and silently. And it is. BUT ONLY IF YOU USE THE ALIEN TAB.
If you use alt-click speedup doesn't work. This pr fixes this bug.
Fix bugs good. Larva buff double good
:cl:
fix: Larva and hunter now crawl into the ventilation faster (as it should have been for like a year and a half)
/:cl:
=> Fix vent crawl 

code/modules/mob/living/carbon/human/species.dm
Aged vatborn have 1.05 species slowdown. This would be pretty minor, were it not for the default species slowdown being 0 and not 1. Oops.
I went slow once.
It was honestly alright but this is excessive.
:cl:
fix: Vatborn have been given permission to take off their training weights.
/:cl:
=> Fixes vatborn having way too much slowdown

_maps/map_files/icy_caves/icy_caves.dmm
lel
I gamer too hard with mosin in Sensor Capture and Combat Patrol.
:cl:
del: Remove Mosin from Icy Cave due to HvH balance
/:cl:
=> Remove Mosin from Icy Cave

code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm, code/modules/projectiles/guns/flamer.dm
Ravagers now gain 50 rage every tick while on fire.
Currently, they completely refill their rage AND reset their charge cooldown every time a fire turf ticks while they are standing on it.
This is extremely powerful when abused, but also super unintuitive as you can move on and off fireturfs and never get the buff, or get it for touching a turf for 0.1 second.
Fire is no longer giga for rav, and provides a more modest, consistant bonus.
:cl:
balance: Ravagers now gain rage every tick when on fire, instead of refilling rage entirely when on a flame turf
/:cl:
=> Unjanks rav fire interation

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Warlock shield hotkey now selects the shield ability instead of instant casts it.
This should A: help with people accidentally using it while moving and instantly cancelling it
and B: make it far easier to directionally cast.
This does mean both casting it initially and detonating the shield now require middle click (or whatever you have it bound to) but this should be a significant QOL boost.
Easier to control warlock shield
:cl:
qol: Warlock shield hotkey not selects the ability instead of casting it
/:cl:
=> Warlock shield control change

code/datums/jobs/job/sonsofmars.dm, code/datums/quick_load_outfits.dm, code/game/objects/items/blink_drive.dm, code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/gun_attachables.dm, code/modules/projectiles/guns/energy.dm, code/modules/projectiles/guns/mounted.dm, code/modules/projectiles/guns/shotguns.dm
A few general tweaks for HvH.
Updated volkite falloff slightly. Charger in partiuclar had pretty high falloff which combo'd with its lower projectile damage quite hard. Also cut down the wield time on the serpenta, since pistols are supposed to be fast wield.
Cleaned up deflagrate code a little. tidied up and improved it slightly, no in game change other than calculating falloff a bit more accurately, and a small visual effect when deflagrate triggers.
Removed tacsensors from shotgun loadouts for both sides. Tacsensor shotties make it a little too easy to spam smoke and do the funni while the other guy is blind, or to hide around blind corners. Shotguns from supply drops retain their tacsensors however.
Removed damage malus from V-51B. It wasn't supposed to have the 0.8 damage modifier, I …
=> HvH tweaks

code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/living_defense.dm
Title. 
https://user-images.githubusercontent.com/22431091/217038012-1d857e05-9799-4fe5-a298-64d951b0e3be.mp4
Xenos don't roll when they resist fire (at least not visually), so there's no point. Plus they kept spinning way after they were done rolling which was annoying. 
:cl:
qol: Only humans spin when stop drop and rolling
/:cl:
=> Only humans spin when stop drop and rolling

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/magazines/rifles.dm
Reduced MG-60 bullet damage to 25 from 27.5. AP and sunder unchanged.
Also reduced capacity to 200 because the damage per mag is still hugely better than what it was previously.
The MG-60 buff pushed the gun to a level of DPS exceeding anything else in the game (except the two bigger MG's) which is not particularly ideal considering it is usable in hand, and viable on the move.
It will still be better DPS that any other portable gun by a fair margin, but slightly less guh to fight.
Giga MG-60 bad.
:cl:
balance: Reduced MG-60 damage to 25 from 27.5, and reduced magazine capacity to 200 from 250
/:cl:
=> MG-60 reduction

code/modules/projectiles/guns/rifles.dm
~~T~~MG-42 now has copy pasted T-12 burst fire.
It also gained 
I can't even remember the original reason it has no burst fire, this just mades it a true T-12 sidegrade. More magazine capacity in exchange for more slowdown+wield delay, meanwhile in the MGsphere its the only burst fire MG.
:cl:
balance: MG-42 now has AR-12 burst fire. As in completely the same.
balance: MG-42 now has BFA and tactical sensor.
/:cl:
=> MG-42 now has T-12 burst fire and tac sensor+BFA

code/modules/reagents/reagents/medical.dm
I realised that oxy's OD functionally does nothing, which is extremely lame for a very strong pain killer.
Oxy OD now causes some stam loss and confusion.
No penalty for ODing on oxy is lame.
:cl:
balance: Oxycodone OD now causes stam loss and confusion
/:cl:
=> Actual oxycodone OD

code/game/objects/items/weapons/misc.dm
Power fist uses 33% less power and pushes "large" mobs ie most T2+ 1*setting more tiles away
Power fist is kinda in a meh spit this should hopefully make it a little more usable
:cl:
balance: power fist uses a little less power and pushes large xenos a little further away
/:cl:
=> Buffs power fist a little

code/modules/reqs/supplypacks.dm
Somehow forgot to change the name of the AGLS WP ammo order in req, which made the normal frag ammo not able to be bought
fix
:cl:
fix: fixed AGLS WP magazine in req console
/:cl:
=> Fix AGLS req oversight

code/game/objects/items/storage/bible.dm
Bible can only hold 1 thing inside it, down from 7
Booze bible can still hold 7 but only cans and cash.
Book having as much storage as a pouch while fitting inside plenty of other containers is bad.
:cl:
balance: The bible is no longer in and of itself a miracle
/:cl:
=> Nerfs the bible

code/game/objects/structures/orbital_cannon.dm
Fixs Plasma OB going off in the OB room
this solution works when i test it on a local server, but i have no idea why it works, if someone who know how this stuff works could check it that would be great
also can someone explain to me why this works?
being able to use the plasma OB and not having it blow up in the OB room and basically waste fuel is nice.
:cl:
fix: Plasma OB will now hit the lased position instead of going off in the OB room
/:cl:
=> Fix Plasma OB detonating in OB room

code/modules/factory/parts.dm
currently if you place the MLRS factory refill into an unboxer it just outputs the final product right away, turns out this is because of a small typo, this should fix it and make it have to go through all its required machines
makes it so the MLRS ammo boxs cannot be fabricated by just unboxing them
:cl:
fix: MLRS reqtorio refils will now work properly and not just pop out the final product from the unboxer
/:cl:
=> Fix MLRS reqtorio

code/game/objects/items/explosives/grenades/flashbang.dm, code/game/objects/items/explosives/grenades/grenade.dm, code/game/objects/items/explosives/grenades/marines.dm
HvH: Reduced stun grenade det time to 2 seconds (same as smoke grenades).
Also makes det time use SECONDS consistantly, and clears out unneeded impropers.
Shorter det time makes it easier to use stun grenades more defensively.
:cl:
balance: HvH: Stun grenade detonation time reduced to 2 seconds from 4 seconds
/:cl:
=> Reduce Stun grenade detonation time

code/modules/projectiles/gun_attachables.dm
Reduced the flame duration for the spray nozzle to 30%, down from 80%.
This makes the spray nozzle significantly less practical for burning down walls, and reduces its area denial ability.
Also made the funny admeme nozzle actually do something more than the normal one.
Less oppressive spray nozzle.
:cl:
balance: Reduces the duration of fire produced by spray nozzles to 30% of normal
/:cl:
=> Spray nozzle nerf

code/game/objects/machinery/mortar.dm, code/modules/projectiles/ammo_datums.dm
Mortar/Howitzer unified to .75 shell speed from 1.10 and 1.25 respectively.
Howitzer has 10 seconds of cooloff, rather than 4.
Mortar-type rounds are all yellow in general.
Artillery is incredibly fast for how damaging it is, it has high damage due to the difficulty it has landing hits, making the shell speed lower in general should make it less frustrating to play against.
Howitzer could use a slight nerf in how spammable it is, this should be better than nerfing reload speed from a player facing perspective, even if it doesn't make much sense from a realism perspective.
The white light it gave off was hard to see, this should be easier to perceive in general.
:cl:
balance: Mortar/Howitzer have lost shell speed, so they have higher travel times. They also emit a different color of light …
=> Mortar/Howitzer shell speed nerf, howitzer cooloff nerf, arty bullet color change to yellow

code/__DEFINES/loadout.dm
Title.
Teleporters are insanely strong for what are basically free move across the map tools for little cost, if I made them take up all your engi points they would *still* be insanely overpowered. Them costing some points (500/50) is fine in my book because that costs your team cost opportunity cost.
:cl:
balance: Engineers can no longer buy teleporters
/:cl:
=> Engineers can no longer buy teleporters

code/game/objects/items/weapons/shields.dm, code/game/objects/machinery/vending/marine_vending.dm
Non-Deployable shields now have 10% less melee and 5% less acid resist.
Dropped melee coverage from 80 to 50.
Shields give you an absurd amount of effective HP in their current state, I think reducing their resist is a good change. 10% melee reduction and 50% melee absorption is a noticeable amount, but should still keep the shield as a viable option.
:cl:
balance: Shields have lost 10 melee armor, and 5 acid armor. As well as dropping melee coverage from 80 to 50.
/:cl:
=> Nerfs Shields melee/acid resistances and shield melee coverage overall

_maps/map_files/Research_Outpost/Research_Outpost.dmm
Title
Lumi can't find them all.
Funny enough, when sensor capture happened in Research Outpost, I searched up mosin in Visual Studio Code during lobby to find if there was one. Funny enough, there was, and I used it to my heart's content.
Time to delete.
:cl:
del: Remove mosin from Research Outpost
/:cl:
=> Remove mosin from Research Outpost

code/game/objects/items/reagent_containers/food/drinks/bottle.dm
Bottle stuns were missing an armour check, so always stunned when it should only stun against unarmoured heads.
Also reduced the stun duration from a mighty 20 seconds to 4.
Bug fix good.
20 sec stun bad
:cl:
fix: Fixed bottles stunning armoured heads
balance: bottle stuns last 4 seconds instead of 20
/:cl:
=> Fix bottle stuns

code/__DEFINES/mode.dm
Reduced the extra time put on the clock for capturing a tower to 3 minutes instead of 5.
The time is a little too generous now that the clock pauses during activation.
Bit less tilted towards marines.
:cl:
balance: HvH: Capturing a sensor tower now adds 3 minutes to the clock instead of 5
/:cl:
=> Reduces bonus time for capturing a sensor tower

dependencies.sh, tools/bootstrap/node.bat, tools/bootstrap/node_.ps1
This ports https://github.com/tgstation/tgstation/pull/64461
and https://github.com/tgstation/tgstation/pull/64513
Fixes the nodeJS Error::0308010C:digital envelope routines::unsupported, and possibly other errors as well
:cl:
code: Jukebuild will now only vendored nodeJS as the latest version is prone to issues.
/:cl:
This does add some bloat in the form of the vendored nodeJS executable, but it's probably worthwhile to have this as the latest version of nodeJS doesn't work without a specific flag, and stylemistake clearly didn't add that on purpose. Make sure to run bin/clean.cmd after this PR is merged, as I've noticed issues cropping up without doing so, somehow.
=> Brings node.bat to what TG has, to fix several jukebuild problems

code/game/objects/items/storage/firstaid.dm
Deletes:
balloon_alert(user, "You take out a pill")
You take out a pill
You take out a pill
You take out a pill
You take out a pill
You take out a pill
You take out a pill
After a while this gets annoying.
:cl:
del: No longer spammed with balloon alerts from taking out a pill
/:cl:
=> Deletes balloon alert from taking out a pill

code/modules/mob/living/carbon/human/life/handle_organs.dm, code/modules/organs/limbs.dm
A kitted limb will regen for 2 total damage split appropriately between burn and brute, up from 0.5 of each with a 75% chance.
This amount reduces with multiple damaged limbs, but you'll still heal faster with multiple damaged and treated limbs in total.
Specifically, per limb regen is divided by the square root of the damaged limb count. Four total will halve the per-limit amount and so on.
Makes kitting more valuable even when the limb stays treated for a shorter period.
:cl:
balance: Kitted limbs passively heal faster
/:cl:
=> Increases passive regeneration on kitted limbs

code/__DEFINES/status_effects.dm, code/datums/status_effects/debuffs.dm, code/modules/mob/living/carbon/human/species.dm, code/modules/mob/living/status_procs.dm
Robots get an action button they can press to stun and blind themselves for 5 seconds while healing up to 20 total brute and burn damage.
Essentially a very light, robotic version of surgery/sleep. Commit to disabling yourself for a period and you can heal more/for free.
:cl:
add: Maintenance mode for robots: disable yourself for five seconds to heal up to 20 damage.
fix: Fixed blindness not clearing properly if you tried to remove it a certain way.
/:cl:
=> Adds maintenance activation to robots

code/modules/mob/living/carbon/xenomorph/evolution.dm
Makes evolution consider the caste tier of what they're trying to evolve to, instead of checking their own caste when considering blocking evolution due to lack of tiered slots.
It fixes drones being unable to evolve into T4 caste (shrikes, queen, king) if they lack t2 slots, as the slot checking used to be completely bypassed for shrike before my previous PR, the issue was neither noticed during the testmerges.
:cl:
fix: Evolution doesn't check the evolving xeno's tier when checking if there are enough tier slots, instead it checks the tier of the  caste the xeno is evolving to.
/:cl:
=> Fixes xenos being unable to evolve to t4 from t1 due to missing t2 slots

code/modules/power/cable.dm
Changes cable autolathe material cost from 50 to 5. 
Makes it more tedious to try and abuse autolathe for materials. I would like to remove the ability to make metal from thin air from autolathe all together, but that is for later. With this material cost, it only takes two thirty stacks to make, for example, mass produced crates; so it is not totally inconvenient for the lesser items.
:cl:
balance: cable mat cost changed to 5
/:cl:
=> Reduces cable coil material cost

code/modules/reagents/machinery/chem_dispenser.dm, code/modules/reagents/machinery/chem_master.dm
Ungas lack the double digits neurons to use chemistry machines. Fixed this bizarre unimmersive oversight.
Also powergaming chem is bad, and just punishes people for not choosing to power game every round.
Powergaming chem is lame.
:cl:
balance: Chemistry machines now require skill to operate
/:cl:
=> Skill locks chemistry

code/modules/admin/holder.dm
Per title. Due to a recent change in admin observer perms, they no longer appear on staffwho and are unable to use MSAY. This is because they recently acquired `+ADMINTICKET`.
This PR aims to fix that. I have no way to test this on local due to a lack of config and the likes, but I'm pretty sure these two lines of code are the culprits.
Would appreciate this being (test)merged as soon as possible since it does mess with their abilities and complicates the learning process.
Fix good.
:cl: Lewdcifer
admin: Admin Observers should now appear on staffwho and be able to use msay now that they have +ADMINTICKET.
/:cl:
=> (Hopefully) fixes Admin Observers not appearing on staffwho and being unable to use MSAY

code/game/objects/machinery/vending/new_marine_vendors.dm
Simply adds a roller bed to the vendor
As the job that is expected to perform field surgery, alongside researcher or potential deployed doctors, it's frustrating to find out that all the roller beds are gone/taken. 
:cl:
add: a roller bed to the synth essentials kit
/:cl:
=> Adds a roller bed to the Synth Essential Set.

code/modules/clothing/modular_armor/attachments/uniform.dm
These guys probably want ammo
3 empty slots looks ugly when you spawn as an ERT.
:cl:
add: fills the slots of the recently buffed shoulder holster webbing for ERTs.
/:cl:
=> ERT Shoulder holster empty slots.

code/datums/loadout/item_representation/_item_representation.dm, code/datums/loadout/item_representation/armor_representation.dm
Fixes quick equip not working is some cases for items obtained from a loadout vendor.
This is a bug that has always existed in loadout code as far as I am aware. Thanks to Xander for bringing it up.
Currently loadouts create the internal storage item for storage armour modules and fills them with whatever is saved in the loadout. However the armour modules already create this storage item when initialised. This means there is a second, hidden storage item in loadout vended items.
This only really causes a problem from the quick equip hotkey, which checks the first (empty) storage item, and so assumes its empty and fails.
This includes all storage attachments (i.e. helmet storage, armour modules etc).
Also fixed a loadout vendor runtime with boot storage that I noticed.
Bug fix good.
:cl: …
=> Loadout fixes

code/datums/elements/deployable_item.dm
Dispensers will no longer teleport across time and space into your hand when they finish undeploying.
This applies to all deployables, in case you somehow get similar situations in the future.
Teleporting bag of holding bad.
:cl:
fix: fixed dispensers teleporting into your hand when undeploying regardless of distance
/:cl:
=> Fixes a dispenser bug

code/datums/status_effects/debuffs.dm
The default range of 25 for the robo repair was intended, so my bad for overriding it.
Unintended change bad.
:cl:
fix: Combat robot maintenance mode is audible from the correct range again.
/:cl:
=> Revert an unintended sound change

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Time Shift description now says that it will not save you from being dead or in crit when it's effect ends.
Prevents stupid deaths of new wraith players
:cl:
qol: Time Shift description now says that it wouldn't save the target from death or from being in crit
/:cl:
=> Specifies that time shift doesnt save you from death or from crit

code/game/objects/items/jetpack.dm
Why is jetpack code so ass, I've cleaned it up just a bit.
Wasting fuel because of double-jetpacking bug is awful, a simple do_actions fixes that.
Also, you are no longer forced to waste fuel every time you want to open an inventory with alt right click, simply turn off the jetpack.
:cl:
fix: You no longer spend 2 uses of jetpack when you spam the activation.
fix: You can no longer use jetpack if it isnt toggled on.
/:cl:
=> Cleans up jetpack code

_maps/map_files/Minerva/TGS_Minerva.dmm
Adds a missing loadout vendor next to the clone vat on minerva
Every other map has a loadout vendor for recently awakened clones. Minerva lacks this.
:cl:
add: Loadout vendor in minerva medbay
/:cl:
=> Adds a missing loadout vendor next to the clone vat on minerva

code/datums/gamemodes/_game_mode.dm, code/datums/gamemodes/civil_war.dm, code/datums/gamemodes/combat_patrol.dm, code/datums/jobs/job/terragov.dm, code/modules/mob/living/carbon/human/species.dm
So it turns out robots spawning in HvH has been broken since robots were first added, because the proc where the restriction is added happens... after the game starts, meaning anyone readied up could spawn as a robot.
It now directly checks the gamemode flag instead of the glob var (I didn't see any reason to keep it).
Bug fix good.
:cl:
fix: fixed combat robots being able to spawn in HvH
/:cl:
=> Fixes robots being able to spawn in HvH

_maps/map_files/Twin_Pillars/Twin_Pillars.dmm, _maps/map_files/gelida_iv/gelida_iv.dmm, _maps/map_files/oscar_outpost/oscar_outpost.dmm, _maps/modularmaps/big_red/bigredsecornervar6.dmm, _maps/modularmaps/oscaroutpost/oscarsouthvar1.dmm, _maps/modularmaps/oscaroutpost/oscarsouthvar2.dmm, _maps/modularmaps/oscaroutpost/oscarsouthvar3.dmm, _maps/modularmaps/oscaroutpost/oscarsouthvar5.dmm, _maps/shuttles/minidropship.dmm, code/game/objects/structures/window.dm, code/game/turfs/closed.dm, code/game/turfs/floor_ground.dm, code/game/turfs/walls/wall_types.dm, code/modules/shuttle/marine_dropship.dm
Just a small PR that fixes some minor smoothing and map issues, formerly part of the round end PR before it was atomized.
Check the changelog for details.
Fixes good, bugs bad.
:cl:
balance: Removed some plasma cutters from Gelida and one modular of Big Red.
fix: Fixed Oscar Outpost runtiming on load due to bad vars.
fix: Fixed lava basalt incorrectly smoothing with regular floors.
fix: Fixed Tadpole shutters smoothing with walls.
fix: Fixed Canterbury smoothing issues with walls and windows.
fix: Fixed Tadpole windows allowing bullets through them.
/:cl:
=> Minor smoothing and map fixes

code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
- Fixes prae primo giving the person it was used on the PASSMOB flag because of a runtime
- Which in human terms means anyone who the prae used the ability on could walk through any mob in the game
Bug bad.
:cl:
fix: Fixes prae primo giving the person it was used on the PASSMOB flag
/:cl:
=> Fixes prae primo giving the person it was used on the PASSMOB flag

code/modules/projectiles/ammo_datums.dm
Incendiary RPG radius increased to 5 from 3.
HEAT RPG increased mech damage mult to 3 from 2.
Incendiary RPG's are pretty bad, as they have a tiny AOE and no explosive damage. They're still worse than RR rockets in HvH, but should now be good area denial.
Mechs have a lot of health, and especially from the front are hard to kill, so this helps for mech HvH events (or the rare SOM ert vs mech).
:cl:
balance: Increased Incendiary RPG radius to 5 from 3
balance: Increased HEAT RPG mech damage multiplier to 3 from 2
/:cl:
=> RPG tweaks

code/game/objects/effects/spawners/random.dm, code/modules/projectiles/guns/rifles.dm
All SR-127 that spawn in planetside shall be scopeless due to HvH.
Some players noticed that they could get a scope weapon in HvH, especially the SR-127. I have seen this in HvH round, and in fact I have it recorded.
No scope weapons in HvH.
:cl:
add: SR-127 now spawn scopeless in planetside due to HvH balance
/:cl:
=> Scopeless SR-127 randomly spawns in planetside due to HvH

code/__DEFINES/loadout.dm, code/game/objects/machinery/vending/vending_types.dm
Remove paracetamol pill bottles from the corpsman point vendor, adds 6 bottles to the medplus
No corpsman in the existence of TGMC has spent 8 points on a pill bottle of paracetamol. Moving it over to the nanotrasen medplus is a better idea.
:cl:
add: Added paracetamol pill bottle to the medplus
del: corpsmen can no longer buy paracetamol pill bottle for 8 points.
/:cl:
=> Corpsmen can no longer buy paracetamol bottles.

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm, _maps/map_files/Twin_Pillars/Twin_Pillars.dmm, code/game/objects/machinery/vending/marine_vending.dm
Adds infinite paracetamol pill packets to the vendor.
With the chemistry skill lock, you can no longer pour tramadol, water and sugar into a beaker to make worse-than-tram painkillers. This adds infinite paracetamol packets to the marine vendor.
:cl:
add: paracetamol pill packets in the marine vendor.
del: Removed paracetamol pill packets from map spawns
/:cl:
=> Adds paracetamol pill packets to the vendor.

code/modules/projectiles/guns/rifles.dm
Removes the suppressor from the MG60.
It's kinda weird that it has it to start with, and all it serves to do is make BAS turrets difficult to be aware of/tell that its the highest dps gun in the game on it.
:cl:
balance: MG-60 can no longer take a suppressor
/:cl:
=> no silenced GPMG

code/game/objects/items/explosives/grenades/grenade.dm, code/game/objects/items/explosives/grenades/marines.dm, code/modules/mob/living/carbon/carbon.dm, strings/tips/marine.txt
WE HAVE THE TECHNOLOGY, WE CAN MAKE HIM BETTER.
This makes it so that grenades throw on /afterattack , instead of just enabling throw mode.
Throw mode is janky, being able to avoid it (while still supporting it) is a better way.
:cl:
add: Primed grenades throw on click regardless of intent.
/:cl:
=> Grenades no longer require throw mode to throw

code/modules/projectiles/gun_system.dm
This makes it so that the underbarrel attachment no longer fires when you middle click.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/8182
https://user-images.githubusercontent.com/66163761/221994838-c41cd79e-af35-4ec4-9e7a-8b4fffc3f83c.mp4
This ^^ was stupid.
:cl:
del: You can no longer fire underbarrel attachments with middle click.
/:cl:
=> Underbarrel attachments no longer fire on middle click.

code/modules/projectiles/guns/revolvers.dm
RO revolver wasn't allowed to use their speedloaders. This is a fix.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/12086
Bugfix good.
:cl:
fix: RO SAA Revolver can use the 2 special speedloaders.
/:cl:
=> Fix RO revolver

code/datums/components/riding/riding_mob.dm, code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
At last, we have done it. A 2 line fix to 6+ month old issue
Bugfix good
:cl:
fix: fixed spiderlings controlling widow movement
/:cl:
=> Spiderlings no longer control widow movement

code/datums/elements/deployable_item.dm, code/modules/projectiles/gun_system.dm
Specifically, prevents loading a gun with a worn magazine (back tanks, minigun power packs) while you aren't carrying both the gun and the mag.
Causes flamethrowers to disconnect from a backtank when deployed as a sentry, they weren't leaving mob inventory correctly.
Fixes #12294 
Fixes #12097 
:cl:
fix: You can only attach a back-worn mag to a gun while you're carrying both
fix: Flamers will disconnect from a backtank when deployed as a sentry
/:cl:
=> Fixes backtanks staying attached when they shouldn't

code/datums/components/chem_booster.dm
As title. You can still disable it whenever, because automatic full necrosis if you get knocked out with it active would be too much
Wasn't sure between this option and checking incapacitated, but I thought starting it while stunned was probably alright.
Mostly because being able to self-apply crit heal chems is excessive, but in general being in crit should by and large disable you.
:cl:
balance: Vali boosting can't be toggled on while you're in crit
/:cl:
=> Prevents starting vali boosting while not awake

code/modules/projectiles/gun_system.dm
You can no longer shoot gun with MMB
Left click to shoot gun, right click to shoot attachment. Middle click should not be doing either of these things.
:cl:
del: Middle click no longer shoots gun.
/:cl:
=> Can't shoot main gun with MMB.

code/modules/mob/living/brain/brain.dm, code/modules/organs/limb_objects.dm
Lets synth heads ghost without it counting as suicide, although it'll still kill them.
Heads inherit languages from the origin mobs (applies to nonsynths too, but they don't tend to have heads that can speak)
Fixes #12230 
Fixes #11732 
Fixes #11504 
:cl:
fix: Beheaded synths can ghost and return to their head later
fix: Beheaded mobs keep their old known languages
/:cl:
=> Two synth head fixes

code/game/objects/items/explosives/grenades/chem_grenade.dm
Chem grenade production from scratch was disabled, but you could still take out the contents of available finished ones (engineering, janitorial) and replace it with your own mix.
Arbitrary chem grenades grotesquely OP.
:cl:
del: Removed repurposing existing chem grenades with a new payload.
/:cl:
=> Kills chem grenade disassembly

code/modules/projectiles/guns/revolvers.dm
Mateba now has 1 additional delay rather than .5, making akimbo basically just give you extra capacity.
Mateba getting any DPS increase from akimbo is insane, mostly because it stuns, staggers and does high enough damage that is mostly balanced by the format it comes out of which is well.. A six round revolver. Akimbo solves the capacity issue with a hefty DPS increase, so remove the DPS increase and it should be fine.
:cl:
balance: Mateba has much more fire delay in akimbo.
/:cl:
=> Mateba akimbo nerf (Additional delay)

code/modules/clothing/modular_armor/attachments.dm, code/modules/clothing/modular_armor/attachments/arm_plates.dm, code/modules/clothing/modular_armor/attachments/chest_plates.dm, code/modules/clothing/modular_armor/attachments/leg_plates.dm
Jaeger Mk.I had some extremely advanced active urban camo, rendering it entirely invisible on prison station.
Marines have lost access to this amazing camo as they blew their budget on rainbow crayons.
Also cleaned up armour plate code a bit.
Bug fix good
:cl:
fix: fixed Jaeger Mk.I being invisible on prison station
/:cl:
=> Fix prison camo being too effective for Jaeger Mk.I

code/game/objects/machinery/vending/marine_vending.dm
Title
Every other RR shell has a free amount round start. Colour me surprised when I found out Tfoot shells (that are never bought) wasn't.
More fun for our demo boys that'll either wipe the hive or the marines.
:cl:
add: Adds RR Tfoot shells to normal vendor
/:cl:
=> RR Tfoot shells to normal vendor

code/modules/clothing/suits/miscellaneous.dm
Makes white dress able to carry something. It holds less than real armor, but instruments and blades are fine I would say.
:cl:
balance: white dress jacket can now hold instruments, swords+sword holsters.
/:cl:
=> white dress jacket can now carry instruments and sword/sword holsters

code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Fixes facehugger layer being under helmet, which makes them impossible to spot.
Fix good, less confusing situations.
Before :
After : 
:cl:
add: facehugger above helmet layer rendering
/:cl:
=> Hugger overlay fix

code/modules/projectiles/guns/rifles.dm
Slightly tweaks the Garand's reciever code, removing a flag that didn't do anything, as it's intertwined with another define that the Garand lacks and replacing it with a flag that makes it's clip eject after the final round is fired.
This does, however mean you can't +1 the rifle.
I mean, it is a tad bit awkward to get the Garand Ping before it's actually empty. Though the PR isn't perfect, as you can't +1 it any more. But hey, if it doesn't get merged, at the very least attention will be brought to it!
:cl: Skye
fix: Removed a flag that doesn't do anything from the C1 Garand
fix: The Garand's clip now pings out after it's empty!
balance: ...And by extension the Garand cannot be +1ed. Sorry!
/:cl:
=> Tweaks the Garand's reciever to eject clips after the final shot is fired.

code/modules/shuttle/marine_dropship.dm
Can no longer spam "hijack dropship"
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/10866
:cl:
fix: Hive leaders can no longer spam "Hijack Dropship"
/:cl:
=> Xenos can no longer spam hijack dropship to spam ARES scan.

code/modules/client/preferences_ui.dm
Fixes the radial preferences for construction stacks and medical stuff. Medical stuff worked purely due to jank, but the construction stack visually did not show if you had it toggled on.
Bug fix good.
:cl:
fix: fixed the preference for radial construction not actually showing when it was enabled
/:cl:
=> Radial preference fix

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Fixed stagger not applying against king in some instances where it should be.
King is vulnerable to projectile based stagger when channeling abilities, but the way it was actually checking for stagger was inconsistant.
Also increases the penalty cooldowns for getting interrupted, to make it a bit more beneficial outside of cancel itself.
Bug fix good.
Interrupt more rewarding
:cl:
fix: King is now consistantly vulnerable to stagger when channeling abilities
balance: Interrupting a king while channeling now put the ability on cooldown for 10 seconds instead of 5
/:cl:
=> Fixed king stagger interaction

code/datums/gamemodes/_game_mode.dm, code/datums/round_statistics.dm, code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
Adds Sentinel drain sting to round stats.
I like stats.
:cl:
add: Sentinel Drain Sting shows up in post-round stats.
/:cl:
=> Sentinel Drain sting shows up in end-round stats.

code/game/objects/effects/aliens.dm
- Makes it so that if you melt a container the things inside the container melt too, with the exception of mobs
- So, if you melt a medibelt you don't have to melt all the pill bottles inside then all the pills inside said bottles (guh)
(this is tehnically a partial revert of #11334)
Xenos having to babysit containers til they're full melted then babysit the contents to melt them as well (while having to spend absurd amounts of plasma to melt all the items inside as well, which makes it take even longer) is not fun!
:cl:
balance: If you melt a container the things inside the container melt too, with the exception of mobs
/:cl:
=> Acid now melts everything in the container that has gotten melted minus mobs

code/game/objects/items/reagent_containers/glass/bottle.dm
Updates polyhexanide bottle to have 60 units of reagent.
Every other bottle in the Nanotrasen Medplus has 60 units, except polyhex. This looks like an oversight so I'm updating it to the match the other reagent bottles. This is hardly a balance change anyways since you can always just restock the bottles, this just aims at making it less tedious when transferring to pills.
:cl:
balance: Polyhexanide reagent bottles in the medplus contain 60 units like the other bottles in the vendor.
/:cl:
=> Polyhexanide bottle has 60 units

code/datums/gamemodes/_game_mode.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm
Makes the amount of Ozelomelyn stings be tracked in the end-round screen.
I like stats.
:cl:
add: Ozelomelyn Sting is now a tallied ability.
/:cl:
=> Ozelomelyn Sting is now a tracked ability in stats.

code/datums/jobs/job/shipside.dm, code/game/objects/machinery/vending/new_marine_vendors.dm, code/modules/projectiles/guns/pistols.dm
FC pistol is now snowflake cracked rather than bad sidegrade, it does 30% more damage.
FC no longer spawns with a mateba.
I don't know whoever gave FC a mateba, but the 1911 is their snowflake sidearm, Captain is the one with the Mateba and should probably start being that way again.
I haven't seen anyone use the custom pistol in ages, this should give it the snowflake power it needs to be good considering it has no autoeject.
:cl:
balance: FC no longer spawns with a Mateba belt, they instead spawn with their custom 1911.
balance: 1911 custom buffed,  it now does much more damage.
/:cl:
=> FC Pistol buff, removes Mateba from FC loadout

code/modules/clothing/modular_armor/style_line.dm
I was told to atomize this into parts, so style hats have helmet armor now.
Suffering for your drip is sadge, and style in general is about form and function.
:cl:
balance: Style hats now have helmet-level armor.
/:cl:
=> Style hats have helmet-level armor

code/modules/mob/living/carbon/xenomorph/charge_crush.dm
240->375 mutliplier for damage, makes mechs take much more damage from getting hit by a crusher.
The damage is piddly considering the average mech has around 1400~ hp. This makes charges at lower speeds more dangerous while making high speed charges very lethal.
:cl:
balance: Mechs take much more damage from crusher charges, now.
/:cl:
=> crusher multiplier against mech is now 375 rather than 240

code/modules/organs/limbs.dm
Increases the chance per tick to drop the thing youre holding from 5% to 20% if you have a robotic limb.
(For reference the chance for a normal arm to drop is 15%)
Robot arms cannot fracture, which is a big upside, so they shouldn't get less impact from their arm being hurt on top of that. This also makes robotic limbs have some sort of tradeoff for their unbreakability.
:cl:
balance: Increased the chance for robotic arms to drop stuff if their arm is malfunctioning
/:cl:
=> Increased the chance for robotic arms to drop stuff if their arm is malfunctioning

code/datums/jobs/job/shipside.dm, code/datums/skills.dm
Drops MP engi skill to 1 from 3, gives them construction 1, making them fumble and take longer to repair their ride.
Larva strength upped from shipside strength to regular strength.
Mech pilots are far too self sufficent, and should look for engineers to repair them in the frontlines rather than doing it themselves, the construction part is because it'd be weird for them to know how to repair cades but not make them as well as encouraging more emergent use of your skillset outside the mech.
Larva strength is just an oversight fix..
:cl:
balance; Mech pilots are equal larva strength to a Squad Marine, previously they were worth the same as a Shipside role, so less.
balance; Mech pilot engineering skill nerfed to 1 from 3, added 1 construction skill.
/:cl:
=> Mech pilot skill and larva strength changes

code/modules/projectiles/ammo_datums.dm
Boiler globs/lances have a seven times multiplier against mecha targets on direct hit like SoM HEAT (which is 3x), which causes them to do much more damage against mechs on direct hits, however this doesn't account for armor so the actual damage is much lower.
Boilers doing measly damage on direct hits to mechs makes no sense considering the difficulty of landing a shot on a mech directly, but this also adds a soft counter.
:cl:
balance: Mech takes much more damage from direct hits by boiler acid globs and lances.
/:cl:
=> Boiler globs do significantly more damage to mechs.

code/modules/projectiles/ammo_datums.dm
I'm sure you know this, a boiler glob splats you (or your target if you are the boiler), but the gas appears multiple tiles away from it. This is because /mob hits for boiler globs are the only type of target where it does not trigger gas on the target's turf, but on the projectile's, as opposed to turfs / objects / etc, which is sometimes unreliable, more so when TD is high.
This resolves that and should make direct hits always create the gas on the hit target's tile, especially when at high TD.
Fix man good.
:cl:
fix: boiler glob direct hits should more reliably deposit their gas on the target's tile
/:cl:
=> Fixes some questionable boiler glob behavior

code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/magazines/rifles.dm
Improved ALF performance, reduced extra burst delay to 0.2 from 0.5 (for reference T18 has an extra delay of 0.1)
Changed the projectile to the SOM MG bullet. This has the same damage, slightly more AP, less sunder, but does 0.5 slowdown on hit.
The ALF has a triple damage falloff multiplier, or 6 times higher than almost all rifles, which means its damage becomes utterly terrible after just a few tiles. The very long burst delay also made it somewhat punishing to use on top of having a rather low rate of fire, so both of these things combined to make the ALF an extremely terrible gun in terms of damage (some like less than half the dps of a T12 even at close range). 
This is in addition to having a 1 second reload time and no underbarrel weapon options. So it being called a CQC king is …
=> ALF improvements

code/game/objects/items/weapons/misc.dm
You no longer need a screwdriver to unload the powerfist. Click it with off-hand while holding it or right click it.
Powerfist no longer sends you flying if you accidentally (or intentionally) punch yourself.
Powerfist can now use up the entire cell worth of charge (So you can punch 10x on level 3 instead of 9 times which was a bug)
Powerfist description is better:
Makes powerfist less janky to unload (why screwdriver???).
:cl:
add: Powerfist cell is easier to remove.
add: Powerfist description is better.
del: You can no send yourself flying with your own powerfist.
fix: powerfist cell can properly reach 0 charge.
/:cl:
=> Powerfist is easier to unload. No longer sends the user flying.

code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/machinery/vending/vending.dm, code/modules/projectiles/guns/specialist.dm
RL72 no longer vends empty from the vendor.
RL72 ammo removed (You can't reload this thing)
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/12019
:cl:
fix: RL72 is no longer broken in valhalla
/:cl:
=> RL72 no longer vends empty in valhalla.

code/__DEFINES/dcs/signals.dm, code/datums/actions/item_action.dm, code/datums/keybinding/human.dm, code/modules/clothing/modular_armor/attachments.dm, code/modules/clothing/modular_armor/attachments/modules.dm
Adds hotkeys for helmet modules and for suit lights (this includes the suicide vest toggle).
It should be straight forwards to add hotkeys to toggleable armour modules in the future if they get added.
Hotkeys good.
:cl:
qol: Added hotkeys for helmet modules and suit lights
/:cl:
=> Helmet module and suit light hotkeys

code/datums/gamemodes/_game_mode.dm
Currently if you're not a human, you won't see the victory results in your panel at the end of a round. This PR fixes that.
Bugs bad, xenos should probably be able to see if they won or lost without scrolling through chat.
:cl:
fix: Fixed end round status not displaying correctly to nonhumans.
/:cl:
=> Fixes round results not displaying correctly for nonhumans

code/datums/gamemodes/objective_items.dm
When I PR'ed the objectives the steal items were kind of a placeholder, so there were only 3 of them. This adds a bunch more.
To admins: **most of these items do not spawn naturally** you will have to place them somewhere if you want it to be completable by whoever you assigned the objective.
If/when objectives are assigned to regular players, I'll do some extra work and make sure that non-existent items won't be the target of a steal objective. Until then it's up to admins to make sure the item is actually present.
More items are good, should mean more ideas for an admin who just wants to quickly give somebody an objective to carry something away.
:cl:
add: Added some more possible items for the steal objective.
/:cl:
=> Adds more steal items for objectives

code/__DEFINES/loadout.dm
Changes the tank the vendor sells from FL-240 to FL-84.
This matches the flamethrower that SLs can buy.
:cl:
fix: SL Vendor vends the proper flamethrower tanks now.
/:cl:
=> SL Vendor sells tanks for the FL-84, not the FL-240

code/datums/gamemodes/objective.dm
Currently to receive greentext for an escape objective, you have to be in the shuttle during the evac process and escape. This check does not work, so I fixed it.
In the process I added an extra option for admins, it loosens the restrictions on escaping and allows for completion of the goal as long as the person is just in an escape shuttle/pod/ert ship and not on mainship level. This is probably better than forcing admins to force all the escape procedures for the sake of an event.
Bugs bad. QOL improvements so admins don't have to initiate SD and force escape pods every time they assign escape objectives good.
:cl:
qol: Created an option for admins to loosen the success requirements for the escape objective.
fix: Fixed the escape objective not completing successfully.
/:cl:
=> Fixes and enhances escape objectives

code/game/objects/items/weapons/misc.dm
I made a mistake
Powerfist can't be taken out of an inventory if you have an item in your offhand.
Changes if(!user.get_inactive_held_item(src)) to if(!(user.get_inactive_held_item() == src))
Fixes the mistake
:cl:
fix: You can pull out a powerfist while holding something in your off-hand (oops)
/:cl:
=> unfucks powerfist.

code/modules/surgery/generic.dm
Both cauterizing and opening incisions with lasers (nobody does this one)
Honestly I could've sworn this flag was already set on cauterizing but I guess it wasn't because it zeroes germs anyway?
:cl:
qol: Cauteries can't infect you. They already couldn't, but now they extra can't.
/:cl:
=> Laser surgery can't infect you

code/modules/organs/limbs.dm
As title, only polyhex works once you're in the right germ threshold. Spaceacillin still helps avoid getting there, of course.
Necrosis is a major kind of long term damage which either arises from long term negligence or a major misplay. Spaceacillin is a basic chem with high availability and no real drawbacks for ODing. The later granting immunity to the former isn't great. Alternatives and why I don't like them:
Make spaceacillin less available - basic chems should be available, and making chems unavailable never actually lasts anyway.
Make ODing on spacea less absolutely nothing - it's a basic chem, akin to bica/kelo, and misusing it shouldn't be any more than a gentle reminder not to do that.
:cl:
balance: Spaceacillin OD doesn't prevent necrosis from forming
/:cl:
=> Spaceacillin doesn't protect against necrosis

code/controllers/subsystem/weeds.dm, code/game/objects/effects/weeds.dm, code/game/turfs/turf.dm
Disables weeds crawling up resin walls after being planted.
Also makes your clicks with weapons, ctrl clicks and xeno attacks on the weed transfer directly to the window frame it's on so you don't have to pixel hunt.
The weeds cause issues with visibility.
Also pixel hunting is not fun.
:cl:
del: Disabled wall weeds
/:cl:
=> Disables resin wall weeds

code/_onclick/hud/parallax.dm
Fixes a runtime related to not having any parallax layers because the preference, thus resulting in a 0 second timer.
Runtime bad.
:cl:
fix: Fixes a runtime related to parallax
/:cl:
=> Fixes a parallax runtime

code/modules/reqs/supplypacks.dm
Adds Jerrycan to req for 100 points.
There are no ways to obtain these outside of looting the few that spawn on ship.
This adds a reasonably priced way to get cans.
:cl:
add: Jerrycans are now in the vehicles category in req for 100 points.
/:cl:
=> Adds Jerrycan to req for 100 points.

code/game/objects/items/storage/belt.dm
Adds 3 more slots to the hypospray belt.
Hypospray belt has 42 storage, but only holds w_class 2 and 18 slots, meaning it can only reach 36 weight held. This makes it objectively the worst medical belt in the game. This rectifies that.
:cl:
balance: Hypospray belt can hold 3 more slots. 
/:cl:
=> Adds 3 more slots to hypospray belt.

code/modules/projectiles/projectile.dm
Removes the "Jim Pfc is hit by the high-velocity bullet in the chest" messages
Does not affect "You are hit by the high-velocity bullet in the chest"
This is marginally useful imo since the info it provides is on-map and it creates a bunch of unnecessary messages in chat and spends unneeded time iterating over nearby objects
:cl:
del: Removed you being notified of nearby players being hit by bullets
/:cl:
=> Remove bullet impact messages

code/game/objects/items/reagent_containers/autoinjectors.dm, code/game/objects/items/reagent_containers/glass.dm, code/game/objects/items/reagent_containers/pill.dm, code/modules/reagents/reactions/medical.dm, code/modules/reagents/reagents/medical.dm, code/modules/reagents/reagents/other.dm
Changes isotonic from restoring nutrition, to purely restoring blood volume. Don't forget your MRE!
Removes iron regenerating blood.
Adds new chem saline glucose, restores 1.2 units of blood.
Recipe is salt, water and sugar.
Blood restore pills restore blood, not food.
This makes it so isotonics no longer invalidate MRE in every way.
:cl:
add: New chem, saline glucose, restores blood at a rate of 1.2 units (QC is 0.2, Nano is 2.4)
del: Iron no longer regens blood.
add: Saline-Glucose has replaced iron in the cryomix.
refactor: Isotonics are now just 15u of saline-glucose. Pills hold 1 dose, injectors hold 2 doses.
/:cl:
=> New chem, saline-glucose. Adjusts isotonic mix.

code/datums/gamemodes/_game_mode.dm, code/datums/round_statistics.dm, code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Adds bull stats: Marines Crushed, Gored and Headbutted.
I like stats.
:cl:
add: Bull abilities have their stats in the end-round popup. Marines Crushed, gored and headbutted.
/:cl:
=> Adds statistics to end-round for Bull

code/__DEFINES/dcs/signals.dm, code/datums/keybinding/human.dm, code/modules/mob/living/carbon/human/species.dm
title.
https://user-images.githubusercontent.com/6610922/226139268-481dfa3b-7c19-411e-b55a-798e1d7bfd0d.mp4
Having keybinds for this action is good for combat robots that don't want to click action button. QoL, essentially.
:cl:
add: Add keybind for activate autorepair for combat robots
/:cl:
=> Add keybind for activate autorepair for combat robots

_maps/map_files/generic/Admin_Level.dmm, code/game/objects/machinery/buttons.dm
Fixes valhalla buttons spawning xenos in nullspace and adds a check to prevent future bugs like this.
Thank you Blundir from pointing out how to reproduce this.
Bugs not good. Xenos are spawning in nullspace and taking up slots.
:cl:
fix: Fixed valhalla buttons
/:cl:
=> Fixes valhalla buttons

code/datums/components/chem_booster.dm
Right now vali just sets the limb germs to above the threshold to cause necrosis. This changes it to setting the limb flag directly and not touching germs.
I'm of two minds about this. The core reason for opening it is actually lore (yeah, I know). It's conceptually weird that vali would add germs to the limb, given that the idea is you've burning out your body via boosting too long.
In terms of balance, there's benefits both directions. If it is germs, you can use polyhex to become immune to the kickback, but that's not a super strong option these days since a: availability and b: poly downsides means you really don't want to use that in combat. If there isn't, it's easier to clear up (if my other prs get merged, since otherwise it's the same surgery either way and nothing else), and you …
=> Vali withers limbs directly instead of adding germs

code/game/objects/machinery/vending/new_marine_vendors.dm
Bugfix.
Bugfix
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/12453
:cl:
fix: Fixes xenonauten light armor not vending in GHMME.
/:cl:
=> Fix xenonauten_light not vending properly

code/datums/jobs/job/shipside.dm
You now need 80 MP job points to an MP rather than 40, this makes mech pilots only really appear on super high pop, as everyone in the marine team is worth 1 point.
Job points also now start at 0.
Makes mech pilots more rare rather than something that occurs basically every midpop round.
:cl:
tweak: MPs now require double the amount of marine spawns to be acquired, as well as starting out at 0 job points rather than 15.
/:cl:
=> Mech pilot job worth required doubled to 80 from 40, job points start at 0

code/modules/projectiles/mounted.dm, code/modules/projectiles/projectile.dm
Fixes a couple of issues caused by the turret rework a couple of months ago.
COPE's were going dense after using manual override, and they were hilariously hard to actually shoot.
Generally made sure if you specifically click a turret (whether its being manned or not) you actually hit it.
Also cleaned up the turret hit code so its a little neater and not doing stuff needlessly.
Fixes good.
:cl:
fix: Fixed an issue with targeting mounted guns when manned
fix: Fixed a couple of minor  COPE sentry issues
/:cl:
=> Turret fixes

code/__DEFINES/is_helpers.dm, code/__DEFINES/loadout.dm, code/datums/loadout/item_representation/_item_representation.dm, code/datums/loadout/item_representation/helmet_representation.dm, code/datums/loadout/loadout_helper.dm, code/datums/loadout/loadout_manager.dm, code/datums/loadout/old_typepaths.dm, code/game/objects/items.dm, code/modules/clothing/clothing.dm, code/modules/clothing/head/head.dm, code/modules/clothing/head/helmet.dm, code/modules/clothing/modular_armor/attachments/storage.dm, code/modules/clothing/modular_armor/modular.dm, code/modules/clothing/shoes/marine_shoes.dm, code/modules/mob/living/carbon/human/inventory.dm
Kills the pocket var on boots and hats, and fixes the loadout screen BSOD from the previous change.
Pushes loadout version to 11 to cover the changes.
Contains a few related changes/
Snowflake var bad, attachment good.
Bug fix good.
:cl:
fix: fixed a loadout screen BSOD
code: removed the pocket var from boots and some hats, replacing them with irremovable attachments.
code: Loadout version progressed to 11.
/:cl:
=> Kills pocket var for good + loadout fix

code/game/objects/effects/effect_system/smoke.dm
Someone probably just forgot these when making smoke prevent huggers from jumping.
I'm 99% sure huggers being able to jump through opaque smoke is unintended. Otherwise being unable to even shoot/react to the hugger is bad.
:cl:
balance: Made defiler smoke (and neuro) pacify huggers
/:cl:
=> Makes defiler smoke (and neuro) pacify huggers

code/game/objects/machinery/vending/vending_types.dm
Valhalla hypospray things were limited like the normal medplus, I've made them unlimited.
Toxin was weirdly 1, I assume the - was forgotten.
Missing isotonic and paracetamol pill bottles are added.
Valhalla vendor is unlimited.
:cl:
fix: Added missing things to the valhalla medplus.
/:cl:
=> Valhalla medplus vendor limit fix.

code/game/objects/machinery/cloning/cloning.dm, code/modules/reagents/reactions/medical.dm, code/modules/reagents/reagents/other.dm
Removes unobtainable reagent xeno_blood.
This misleads people into thinking it's actually a possibility to get expanded biomass, when in reality there exists 0 ways to harvest xeno blood.
This is purely code bloat.
:cl:
del: Deletes the unobtainable chem xeno_blood
/:cl:
=> Removes unobtainable reagent xeno_blood

code/modules/shuttle/cas_plane.dm
Makes cas' starting point be a point the PO selects on the minimap.
The screen being all static after you begin your firemission is rather confusing and looks like cas is broken rather than there just being nobody on your screen. Should hopefully clear this up.
:cl:
qol: Made cas' eye starting position selectable via minimap
/:cl:
=> Makes cas' eye starting position selectable via minimap

code/modules/shuttle/ripple.dm
Yeah. Funny.
Currently you can't interact with anything under the shadow minus using alt click to get to it. This causes funnies with drains or generally trying to save something from under tad.
:cl:
fix: Shuttle landing shadow doesn't block clicks anymore
/:cl:
=> Stop the shuttle shadow from blocking clicks

code/game/objects/effects/effect_system/smoke.dm
Makes normal smoke nades (i.e. the one that completely blocks vision) extinguish fire.
Smoke extinguishing fire is a super niche mechanic, as it only exists with boiler neuro smoke and more recently sentinel primo nades.
This is basically only relevant for HvH, but its a handy and interesting mechanic if you remember it.
Adds more counterplay/interesting interactions for HvH
:cl:
balance: Standard smoke grenades now extinguish fire
/:cl:
=> Normal smoke extinguishes fire

_maps/map_files/LV624/LV624.dmm
Moves green disk across the river to engineering on LV.
I really hate how LV is being played right now. 
Every round is the exact same pointless marine push to engi followed by them just sitting there until the xenos attrition them enough. This should make that push a bit less pointless and give marines a timer to gtfo out of engi once the disk is done instead of sitting there eternally.
On the other hand this should also help with how marine sided the disks (and LV as a whole) are if the marines actually go for disks because it's harder to get compared to green being in hydro which is essentially free as it stands right now.
:cl:
balance: Moved green disk to engineering on LV
/:cl:
=> Moves green disk to engineering on LV

code/game/objects/machinery/squad_supply/supply_beacon.dm
Says Orbital Strike beacon instead of supply.
Don't know why its still a thing but might as well make it accurate.
:cl:
spellcheck: updated beacon admin log to say 'supply' instead of 'orbital strike'
/:cl:
=> Fix beacon admin log message

_maps/shuttles/tgs_bigbury.dmm
A simple one-line change I did by opening the .dmm in notepad, CTRL+F'ing the id and rewriting it to a proper one.
Right now the left button controls the right shutters instead of the left ones, leaving the left side to be unable to be opened by ungas. This PR fixes that
Bug fix good, not being able to ever open left door on big canter was a meme
:cl:
fix: fixed big canterbury left button opening right shutters instead
/:cl:
=> FIX: Big Canterbury Left Button

code/game/objects/items/scanners.dm
Moves the health scan function of the health analyzer over to a new proc analyze_vitals().
Fixes runtime error on health scan.
New functionality, RMB can be used to show the patient you are scanning their health scan.
I agree, thanks for the idea @Losenis 
:cl:
add: RMB with health analyzer will show the patient their health.
add: Health scanner balloon alerts.
fix: Runtime involved when health scanning non-carbons.
/:cl:
=> You can show patients their health scan with RMB.

code/__DEFINES/equipment.dm, code/modules/mob/living/carbon/human/inventory.dm
I am exhausted.
Adds SLOT_IN_BELT to the required areas so I can finally make it a quick equip that works.
There was always this option in prefs, it just DIDNT WORK. 
There was always Belt, and then Belt (2)
What the fuck is belt 2, idk, but I changed it to "Belt inside"
It's basically your health scanner if you use a lifesaver belt, or ammo inside ammo belts, etc.
Quick equip Belt, is if you have a gun directly on your belt. (Or whatever else you can wear on belt that isnt a storage)
Bugfix good? 
If this is considered a bug, probably is.
:cl:
fix: "Belt (2") in quick equip prefs is now "Belt Inside"
/:cl:
=> Changes "Belt (2)" to be "Belt Inside"

code/__DEFINES/dcs/signals.dm, code/datums/keybinding/xeno.dm, code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Somewhat recently, Warlock's shield got changed to be a selected ability, requiring you to select it before being able to use it.
This, in some cases, is useful for targetting a specific target, but in others, can also be hindering in reactive or quick use of the ability, as not only does it require two clicks to execute, but also adds an additional click to any other action you'd maybe prefer stayed selected (e.g. your psychic shot). As this is purely a matter of preference, I have added a keybind that triggers the ability immediately without selecting it, towards your current direction, as before the initial change. It starts unbound, but is there for anyone who preferred the original behavior.
Ability use behaving like players prefer tends to be a good thing.
:cl:
qol: Readds the …
=> Warlock's Psychic Shield gets a trigger bind (again)

code/datums/gamemodes/crash.dm
T1 Xenos get the maturity points for evolving in crash.
Since maturity points carry on when evolving, crash has the issue of giving T1s Elder but starting off with 0 maturity points and makes T2s mature by default, also not giving them the points, but T3s take a massive amount of time to reach ancient since maturity changes.
This should rectify that issue and give the missing points when the first evolve is done.
This should help reintroduce the previous interaction without making Xenos too powerful whilst also being a bit of a slight buff when Xenos evolve instantly.
:cl:
balance: T1 Xenos get the maturity points for evolving.
/:cl:
=> Slight Xeno crash buffs (fix)

code/modules/clothing/modular_armor/attachments/storage.dm
You can click on boot to insta draw your item again.
Fixes #12503 
Altered all storage attachment behavior so this applies to any storage with draw_mode enabled, while alt right click always opens storage.
Restore original functionality.
:cl:
fix: left click draws items out of boots again, alt right click will open storage instead
/:cl:
=> Fixes boot knife click draw

code/__DEFINES/dcs/signals.dm, code/controllers/subsystem/minimaps.dm, code/datums/components/remote_control.dm, code/datums/keybinding/mob.dm, code/game/objects/machinery/miner.dm, code/game/objects/machinery/overwatch.dm, code/game/objects/structures/droppod.dm, code/modules/mob/living/silicon/ai/ai.dm, code/modules/mob/living/silicon/ai/freelook/eye.dm, code/modules/shuttle/cas_plane.dm
This PR adds a minimap to CIC's consoles while in the overwatch camera view, which updates its z to the one currently viewed (or none if the z is minimapless).
Similarly, the AI minimap is now improved to track whichever z the AI's eye is on currently.
CAS also gets a minimap while running strike missions, and this might allow it to give it laze locations on the minimap at a later time (would be out of scope for this PR and I'm already doing enough here)
The locator also tracks the eyes and not the user in CIC / wherever, for all of these added / modified minimaps.
Minimap code may contain a little bit of signal sorcery to achieve this but it should work fine. Please do testmerge this before fullmerging, as there may nonetheless be things I missed or oopsied.
Also fixes two minor minimap …
=> CIC-Overwatch and CAS missions get minimaps, improves AIs minimap

code/game/turfs/open.dm, code/game/turfs/open_ground.dm, code/game/turfs/snow.dm, code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
I forgot to remove the slowdown on snow for xenos and lumi forgot to make water have water slowdown instead of snow slowdown. Fighting in river is once again a very very bad idea.
Unintended changes aren't.
:cl:
balance: River slows the amount its supposed to again
fix: Snow actually doesn't slow xenos down
/:cl:
=> Removes the snow slowdown var and puts the water slowdown var where it's supposed to be

code/modules/projectiles/guns/pistols.dm, code/modules/projectiles/magazines/pistols.dm
Does a pass over smartpistol.
tl;dr makes it go from normal pistol ammo to AP, adds full auto. Makes it more light SMG-esque than full pistol.
Detailed changes below
<details>
Left(old)|Right(New)
Damage:20|20
AP:5|12.5
Sunder:1|2 [Swapped over from /pistol to /pistol/ap. in order to make it simmilar to other SGs with their higher penetration, I don't think a damage malus is necessary considering it fires at rifle fire rate.]
Mag Capacity: 25|30 [Heightens ammo count a tiny bit to make it more viable on its own.
Added Full auto [Makes sense considering this is dollar store fire support pistol, and 88mod has it which is its closest comparison statwise.]
Gun handling is unchanged, I do not believe this thing needs any nerfs in that regard, considering you need to buy it or have a Captain …
=> Smartpistol restatting

code/modules/mob/living/living.dm
Before:  (I am trying to diagonal shuffle very hard)
After: 
Closes #10916 and reverts #9534. Priorities, brave.
I've seen countless, countless xenos die to being just stuck because there was another xeno standing on the tile cardinal to them and the destination (that was diagonal of them) and they just stand there and die. The shuffle destination being slightly off is not as big of an issue as xenos getting punished for trying to use diagonal movement to get away.
:cl:
fix: Fixed mobs getting stuck on eachother and other mobs when moving diagonally
/:cl:
=> Fixes mobs getting stuck on eachother and other mobs when moving diagonally

code/controllers/subsystem/monitor.dm
While checking some code I noticed a funny typo.
Presumable BM did not mean to have autobalance be influenced by whether the SS was in SS_IDLE or not.
Bug fix good.
:cl:
fix: Minor fix to the anti-stalemate system
/:cl:
=> Minor stalement fix

_maps/map_files/generic/Admin_Level.dmm, code/datums/jobs/job/pmc.dm, code/modules/clothing/suits/marine_armor.dm
PMC SG armor is no longer invisible.
PMC SG armor is the child of CM era SG specific armor which no longer exists, repathed it to be the same as other PMC armor.
Also fixed imperial guard suits.
Bug fix good.
:cl:
fix: fixed some invisible ERT armor
/:cl:
=> PMC SG armour fix

code/game/objects/machinery/computer/camera_advanced.dm
Overwatch consoles can get a little uppity if their camera eye gets deleted, especially when tracking.
This adds an additional layer of safety that should ensure the overwatch console always has its eye reference and user removed.
Fixes #11977 
Fix man good.
:cl:
fix: Overwatch consoles should no longer brick under certain eye-deletion related conditions.
/:cl:
=> Resolves overwatch consoles bricking in some scenarios

code/modules/shuttle/mini_dropship.dm
Title.
This was requested on my previous minimap-adding PR and I don't feel like it's too much of a big change.
Nonetheless labeled "balance" as the Tad being somewhat blind to the events on the ground while in flight could be considered a feature.
Should make tracking the groundside happenings and potential landing opportunies easier while in camview, however this could also be used as a negative. I'm pretty impartial to this and am mainly doing this at request.
:cl:
balance: Tad's landing cam view has minimap access.
/:cl:
=> Tad landing camview also gets a minimap

code/modules/surgery/necrosis.dm
Necrosis surgery requires necrosis to be performed. I moved the necrosis removal to the first step for flavor reasons (that's the step at which you're cutting it out, with the step after being healing damage tissue). This made the second step impossible to perform, since you no longer have necrosis for it. This also made it impossible* to perform necrosis removal surgery on the same limb twice, since you couldn't perform the first step again.
This pr moves the removal back to the second step.
bugfix
Also makes it more clear to the surgeon that the procedure is actually finished.
:cl:
fix: Moved the actual necrosis removal of surgery back to the second step, rendering it possible to perform once again
/:cl:
=> Fixes one necrosis surgery step being impossible

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm, code/game/turfs/floor_types.dm, code/game/turfs/plating.dm
Currently explosions break both carpet and catwalk due to an oversight with how their parents handle explosions, this fixes that.
Bugs bad fixes good.
:cl:
fix: Fixed carpets and catwalks becoming blank voids after explosions.
/:cl:
=> Fixes carpet and catwalk breaking

code/__DEFINES/loadout.dm
You can import loadouts from the current version again.
Forgot to update a list.
Feature working is good.
:cl:
fix: Importing loadouts works again with the current version
/:cl:
=> Fixes loadout imports

code/modules/clothing/modular_armor/attachments/storage.dm
Makes the default starting boot knife the M5 survival knife.
The difference between the two is the M5 has higher damage, at the tradeoff of being unattachable (unless you have 5 cable coil).
Generally as far as I know most people would prefer being able to 2 shot weed sacs with their boot knife rather than have the bootknife be attachable to their gun (because you can just dispense a bayonet and attach that in prep if you want to run a bayonet)
Should help new people who don't know better just use the better knife by default.
:cl:
balance: Makes the default starting boot knife the M5 survival knife
/:cl:
=> Makes the default starting boot knife the M5 survival knife

code/controllers/master.dm, code/controllers/subsystem.dm
Ports https://github.com/tgstation/tgstation/pull/72324
When I found the issue with the silo SS going to sleep I wondered "is this logged?" The answer was no, but turns out TG did.
Also some autodoc because funny comments
Logging MC issues good.
:cl:
code: The mc now keeps track of how many times a subsystem has slept in fire()
/:cl:
=> The mc now keeps track of how many times a subsystem has slept in fire()

code/__DEFINES/qdel.dm, code/controllers/subsystem/garbage.dm
Ports https://github.com/tgstation/tgstation/pull/72401
Keeps gc_destroyed from getting updated on every step thru the gc queue.
Fixes logic that assumed gc_destroyed is the time the object first qdel'ed. it used to get updated on each stage of the garbage controller and there are 3 stages.
Added list index defines for the inner gc item list.
=> Keeps gc_destroyed from getting updated on every step thru the gc queue

code/_globalvars/admin.dm, code/datums/actions/observer_action.dm, code/modules/admin/server_verbs.dm
Also makes the valhalla disable verb actually have a toggle verb.
People ruining PVE events isn't funny.
:cl:
add: Admins can disable players taking over ssd mobs now
fix: Admins can now actually toggle the var to disable valhalla joining
/:cl:
=> Adds an admin verb to disable taking over mindless/SSD mobs

code/game/objects/items/storage/dispenser.dm
Dispenser can only hold items of w_class 3, no more bulky items fitting in the dispenser.
Dispenser reduced to 36 storage capacity, 1.5x the size of a backpack.
Carrying bulky items allows degenerate strategies and bypasses how items are balanced:
- Multiple plasma cutters in a dispenser means you will  never run out of charge (Intended downtime that xenos can play around)
- Multiple sentries means that any xeno that even thinks of approaching will just get gunned down by auto-targetting turrets.
- Allowing things like infinite welding kits to enable permanent flamethrowing is unreasonable (no downtime for xenos to exploit when you have infinite fuel without reliance on fob/req)
Carrying a huge amount of items, is not as bad as carrying bulky items, but it is still problematic:
The game …
=> Nerfs the dispenser storage, can no longer hold bulky items.

code/game/objects/structures/droppod.dm
Fixes the targetting map getting stuck open if you launch while it is open.
Fixes #12567 
Bug fix good
:cl:
fix: The droppod deployment map can no longer get stuck if you deploy with it open
/:cl:
=> Fix stuck droppod targetting map

code/game/atoms.dm, code/game/blood.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/human_defines.dm, code/modules/mob/living/carbon/human/human_movement.dm, code/modules/mob/living/carbon/human/life/handle_status_effects.dm, code/modules/reagents/reagents/other.dm, code/modules/surgery/surgery.dm
Strictly the only times germ_level matters is on humans and gloves, and I've folded the glove effects into human.
Also standardizes surgery gear-based germ transfer - proper gear is 10% from surgeon, improper is 20%, none is 33%. There was a weird case where having non-specialized gloves was better sometimes, that's dead now.
Humans pop out of cryosleep clean instead of moderately dirty.
One less var on almost every single atom in the game.
:cl:
code: germ_level moved from atom to human, no major player-facing changes
/:cl:
=> Moves germs to human from atom

code/modules/events/ion_storm.dm
What is says on the tin.
A callback was doing a global instead of src, which only broke with the 515 changes.
Also there was an unused proc which I've combined into the start proc in how I assume it was intended to function. (i.e. randomised blackout time, not always one minute)
Bug fix good
:cl:
fix: Comms blackouts no longer last forever
fix: Comms blackouts now correctly apply for a randomised period of time
/:cl:
=> Fixes comms blackout event

code/game/objects/machinery/vending/marine_vending.dm, code/modules/projectiles/ammunition.dm
Adds a large ammo box for loose 10x26mm caseless that holds 2400 rounds and can be infinitely vended from the req supplies vendor like all other large ammo boxes.
I thought it was kind of silly that you can sling large boxes of rifle and SMG ammo over your back, but no such thing existed for the quintessential machinegun caliber. You know, the caliber designed to be spammed in large volumes in the general direction of the enemy. The one that would be most useful in a large, bulk format such as a big box of loose rounds. it holds the same amount as the rifle ammo box because a backpack full of 10x26 packets is about 1200 rounds, half of 2400.
:cl:
add: Added big 10x26mm caseless ammo box to req operational vendor
/:cl:
=> Adds large 10x26mm caseless box

code/game/objects/items/storage/belt.dm, code/game/objects/items/storage/pouch.dm, code/modules/projectiles/guns/specialist.dm, code/modules/projectiles/magazines/specialist.dm, code/modules/reqs/supplypacks.dm
Railgun now holds 3 in a canister, price in req upped from 3(0)->5(0) to compensate
Railgun, since it now has an actual magazine holding more than 1 round now has 3 fire delay.
Railgun currently has terrible ammo economy, this should assist it in acquiring some real ammo economy so it isn't awful to use. I don't personally think this is too OP outside of maybe HVAP should stay at 1 and 3 points.
:cl:
balance: Railgun now holds 3 shots in a canister rather than 1, has 3 seconds of fire delay inbetween shots. Railgun ammo now costs 50 points rather than 30 to accommodate for the larger magazine size.
/:cl:
=> Railgun changes

_maps/shuttles/tgs_bigbury.dmm, _maps/shuttles/tgs_canterbury.dmm
It does exactly as it says on the tin. To be more specific, these changes have been made, indicated by sharpie.
Well...It kinda sucks that one version of the Cant has cryo while the other doesn't, especially with certain clone loss causing meds. 
In an ideal world, I'd like both versions to have chemistry too, but uh...I can't be bothered to figure out how to fit chem into SmallBury
:cl: Skye
qol: Adds cryogenics to the TGS Smallbury, used in the Crash game mode. (Also moves a table.)
balance: Adds a cryomix beaker to both Canterbury variants.
/:cl:
=> Adds cryo to small Cant, adds cryo beakers to both variants

code/game/objects/machinery/mortar.dm
Mortar shells once again land at subsonic speeds, with their sound effect playing before landing.
I'm not entirely sure how this broke, or if just the old speed coincidentally made it just work due to the minus 1 second, but it is now actually tied to how often the projectile SS fires.
Being able to hear a mortar coming is good.
:cl:
fix: Fixed mortar sounds playing after they've already landed
/:cl:
=> Mortar sound fix

code/game/objects/structures/barricade.dm
Two changes. Cade repair time and fuel use cut in half (2.5 seconds from 5 seconds, and 1 fuel from 2).
Repair amount reduced to slightly above 50% (85hp from 150).
This should make it easier to do minor repairs, especially if it's difficult to stand there for a prolonged period of time due to boiler acid etc.
There's more ways of damaging cades, in particular damaging multiple cades for xenos, and no more multirepair, so I buffed the repair/second very slightly to make it less guh to try hold cades.
Repair QOL, make cade repairing slightly more effective against modern xeno cade murdering options.
:cl:
balance: Barricade repair time and fuel use cut in half. Repair amount reduced from 150 to 85
/:cl:
=> Cade repair improvements

code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
They go the normal distance like all the other spits now. Also removes an unused var.
Closes #12621
Unintended. This was kept from when it had neuro spit.
:cl:
fix: Sentinel spit now travels properly instead of stopping at the tile you aimed
/:cl:
=> Sentinel spit now travels properly instead of stopping at the tile you aimed

code/modules/clothing/suits/marine_armor.dm
Lumi didn't iconpath these properly, they're properly iconpathed now.
Icons being seeable is pretty important I'd say.
:cl:
fix: ICC and some SoM armors not having their onmobs show up properly.
/:cl:
=> Fix ICC/old SOM armor sprites

code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Fixed a simple typo in the primo warrior's caste_desc
_vastly_ improved immersion
:cl:
Fixed a typo in the primo warrior's description
/:cl:
=> fixed typo in the warrior's caste_desc

code/modules/mob/living/carbon/human/human_defense.dm
You're supposed to pass the zone, not the limb itself.
Runtime bad.
:cl:
fix: Fixed a behead runtime
/:cl:
=> Fixes a behead runtime

code/modules/reqs/supplypacks.dm
Because everyone needs a friend.
Adds each plushie to requisitions, a games crate, and a box with each color of therapy doll.
Plushies are neat and so are games. Frankly, if requisition wants to spend their points on 50 rouny plushies, I don't see why they shouldn't be able to. Marine morale will be boosted tenfold by giving each unga a battle buddy.
:cl: dopamiin
add: The TGMC has approved several morale-boosting supply options to be added to requisitions. 
/:cl:
=> Adds toys and plushies to requisitions.

_maps/modularmaps/big_red/bigredlz2var1.dmm, _maps/modularmaps/big_red/bigredlz2var2.dmm
shifts the landing pad in LZ2 one tile to the left. Currently the east side of the LZ is 3 tiles wide, and even has the dropship computer clogging the way reducing it down to 2 wide.
This makes the LZ pretty unpleasant to move around in, let alone defend.
Slightly less painful LZ is good.
:cl:
balance: Big Red LZ2 is slightly wider on the right hand side
/:cl:
=> Minor Big red LZ2 tweak

code/game/objects/items/reagent_containers/hypospray.dm
Makes new proc draw_reagent(). Afterattack_alternate just calls this proc after some checks.
The UI is clunky and slow, this goes around the problem in a TG-esque way. Being able to draw reagents with right click instead of having to open the UI, set it to draw mode and then left click your container.
I HAVE NOT TOUCHED THE UI OR DRAW MODE, just added draw mode innately to right click.
:cl:
add: Hyposprays can now draw reagent with right click (Autoinjectors are also hyposprays fyi).
/:cl:
=> Hyposprays can draw reagent with right click.

code/_globalvars/lists/objects.dm, code/game/objects/items/stacks/sheets/sheet_types.dm, code/game/objects/machinery/squad_supply/supply_packer.dm, code/game/objects/structures/crates_lockers/largecrate.dm, tgmc.dme
For 1 wood, you can craft a crate which will store all the stuff your currently standing on into big crate
https://user-images.githubusercontent.com/36102060/228908965-94d596ca-08dc-447a-b5f7-3b10b79a9d84.mp4
RO's can send supplys to muhreens without using crates, these look color imo
:cl:
add: You can now craft supply crates with wood
/:cl:
=> Adds craftable supply crates

code/modules/projectiles/gun_attachables.dm
BAS attachment now has a size increase of 1.
Sholdn't do anything right now after the dispenser nerf, but should make it more difficult to carry 50 BAS T60s in the future if something that fits normal guns comes along.
:cl:
balance: Buildasentry attachment increases object (gun) size by 1.
/:cl:
=> BAS attachment increases gun size

code/__DEFINES/mobs.dm, code/datums/status_effects/debuffs.dm, code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
You may have noticed that you can spam resist to immediately rid yourself of the intoxication debuff. I talked about it with Lewd and Ivan and we came to the conclusion that making the resist itself stronger but removing the stacking would be the best way to go.
This PR ups the resist time from 3 seconds to 5 seconds and ups the amount removed from 3 stacks to 8 stacks. This makes the resist 1.6 times stronger than previously. (3 / 3 = 1 and 8 / 5 = 1.6)
The resist timer now also repeats itself on it's own, similarly to repairing things.
This PR also adds messages to the sting since I noticed it lacks them unlike most other abilities, making you unable to see the sting in chat log unless you got buffed by it, which has it's own message.
Resist spam is unintuitive and can be affected by …
=> Adjusts some things on drain sting, fixes do_after stacking

code/game/objects/structures/stool_bed_chair_nest/chairs.dm
They just kept standing after dying. Stinky. Call your parents.
Bug bad. Standing corpses bad.
:cl:
fix: Fixed people who get killed while buckled in the alamo chairs standing up even while dead
/:cl:
=> Fixes people who get killed while buckled in the alamo chairs standing up even while dead

code/modules/projectiles/gun_system.dm, code/modules/projectiles/magazines/sentries.dm
Weight clast = 3 -> WEIGHT_CLASS_NORMAL
Sentry ammo set to WEIGHT_CLASS_NORMAL
It makes no sense for the ammo to be heavier than the sentry.
:cl:
balance: Sentry ammo is now sentry sized (Normal)
/:cl:
=> Sentry ammo is now the same weight as the sentry.

code/controllers/subsystem/persistence.dm
Yeah, you get 2 mag types but not the gun itself. Funny.
Not intended.
:cl:
fix: Adds the ak47 to the proper seasonal instead of 2 mag types
/:cl:
=> Adds the ak47 to the proper seasonal instead of 2 mag types

code/__DEFINES/misc.dm, code/_globalvars/lists/objects.dm, code/modules/power/groundmap_geothermal.dm
Fix the number of gens being universal, sigh. Also only counts marines for the calculations not all humans in existance.  Also fixes being able to recorrupt an already corrupted gen.
Psi gen being correct is good.
:cl:
fix: Fixed psi point gen calculations being wrong. Also you cant corrupt an already corrupted gen anymore.
/:cl:
=> Fixes psi point gen

code/modules/projectiles/ammo_datums.dm
Small fix to rockets, most notably incendiary ones. They will no longer detonate on the turf of an object they hit, as this causes various issues like going through windows/stopping most of the spread.
Bug fix good.
:cl:
fix: fixed some odd behavior when firing rockets at dense objects like windows or airlocks
/:cl:
=> Rocket fix

code/modules/vehicles/unmanned/unmanned_vehicle.dm
Destroying an unmanned vehicle (+ droids because subtype) leaves behind gibs and sparks instead of being banished to the shadow realm
looks cool
:cl:
add: robot gibs for unmanned vehicles
/:cl:
=> Unmanned Vehicles now leave behind robot gibs when destroyed

code/game/objects/items/storage/belt.dm
Swaps the dexaline pill bottle in lifesaver belt for an isotonic solution pill bottle
Dexaline's use is redundant in most cases when you have inaprovaline. As it is, the default loadout has no real blood replenishing options so a corpsman has to go out of their way to get one. Shouldn't be too big a change given both are available from vendors anyway, so more of a qol change than balance.
:cl:
balance: Dexaline pill bottle in lifesaver belts replaced with Isotonic Solution pill bottle
/:cl:
=> Swaps dexaline for isotonic in lifesaver belt

code/game/objects/items/defibrillator.dm, code/game/objects/items/scanners.dm
Bugfix.
Currently, you keep the defib/healthscan gloves effect if you get delimbed because unregister only gets called on equip.
Bugfix
:cl:
fix: You can no longer magically health scan/defib after being delimbed while wearing scan/defib gloves.
/:cl:
=> You no longer keep healthscan/defib gloves after being delimbed.

code/game/turfs/turf.dm
To not have acid floating even after the wall is gone. (from it being destroyed from a charge or explosion, etc)
Bug.
:cl:
fix: Acid on walls gets deleted if the wall gets deleted
/:cl:
=> Acid on walls gets deleted if the wall gets deleted

code/__DEFINES/loadout.dm, code/game/objects/items/reagent_containers/hypospray.dm
Literally just the injectors stuffed into basic hyposprays.
Less busywork for whoever wants to vend the injectors and put them in hypos. QC+ is same cost as 4 injectors. Peri+ is the same cost as 7 injectors, since even if you have some leftover in an injector you still need to spend 7 to get them. Zero balance impact, the vendors even have empty hyposprays to vend to say nothing of the rest of vendable hypos to empty and refill.
:cl:
qol: Corpsman vendor now has hypospray option for QC+ and Peri+
/:cl:
=> Corpsman vendor has QC+ and Peri+ hypos

code/game/objects/items/storage/belt.dm
pistol belt can hold 1 gun + 6 mag. not 1 + 2
:cl:
spellcheck: pistol belt has 7 slots total, not 3
/:cl:
=> Updates Pistol belt description

code/modules/projectiles/ammo_datums.dm
Fixes spit chem transfer not respecting armour penetration. This means a neuro lance to the face WILL fill even a mimir 2 user with a bucket of neuro.
At the moment armour is taken into account, but not AP. So Mimir II just hard block even neurolance.
Bug fix good.
:cl:
fix:Xeno spit chem transfer now correctly respects armor penetration
/:cl:
=> Spit chem fix

code/modules/projectiles/gun_helpers.dm
If both one hand and parent gun are empty, you could tac reload even when you aren't actually holding the gun.
bugfix
:cl:
fix: You need to be holding a gun to tac reload it
/:cl:
=> Fixes out of hand tac reloads

code/game/objects/items/stacks/barbed_wire.dm, code/game/objects/items/stacks/rods.dm, code/game/objects/items/stacks/sheets/sheet_types.dm, code/game/objects/structures/razorwire.dm
1 units of razorwire now costs 2 metal. This will change how much stuff engineers can build and reinforce. This does not affect razorBURN grenades. Only handbuild razorwire.
Compared to razorburn, razorwire is very expensive. I believe this should make it so that razorwire is good for prepared positions, and razorburn remains good for quick plans. This does not change the actual damage, effects, or the fact crushers can delete razorwire at 50 integrity. Only the cost. 
:cl:
balance: razorwire construction options now makes 2 razorwire instead of 1 for 4 metal.
fix: Changed a min to a max to allow deconstructing razorwire
/:cl:
=> razorwire construction option changed to a ratio of 2 metal for 1 razorwire, with 2 razorwire being made with 4 metal

code/game/objects/machinery/mortar.dm
This PR fixes arty pieces not being able to see where the shots land on the impact cam 
This will add back the dopamine from using artillery for multiple pieces
:cl:
fix: Artillery pieces now each have their own camera on tablets, and they work again
/:cl:
=> fixes only the first arty piece having a cam

code/modules/projectiles/gun_system.dm
Guns that are in-hand are opaque. 
This makes it easier to click on them when you are trying to insert/remove a magazine.
This makes it easier to click drag a magazine onto the sprite when attempting to do a tactical reload.
:cl:
qol: Equipped guns are easier to click on
/:cl:
=> Tac-reloadable guns are opaque (so when in hands)

_maps/map_files/Orion_Military_Outpost/orionoutpost.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/generic/Admin_Level.dmm, _maps/modularmaps/EORG/cs_office.dmm, _maps/modularmaps/EORG/de_dust2.dmm
Title.
Entertainment monitors in a couple of maps got broken by the status_display changes. This PR fixes them by replacing them entirely.
Big bad error icon bad, fix good.
:cl:
fix: Fixed entertainment monitors erroring out.
/:cl:
=> Fixes broken entertainment monitors

code/game/objects/obj_defense.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Does wizard magic with signals so it no longer breaks stealth when staring at weeds.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/12457
:cl:
fix:Hunter no longer breaks stealth while staring at weeds cluelessly  
/:cl:
=> Hunter no longer breaks stealth when staring at weeds.

code/game/objects/machinery/cryopod.dm, code/modules/shuttle/escape_pod.dm
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/12371
bugfix
:cl:
fix: Cancelling the channel to enter a cryo pod on the evac shuttle will no longer ghost you.
/:cl:
=> Fixes Evac cryo pod ghosting you immediately if you start getting into it.

code/__DEFINES/mode.dm, code/_globalvars/lists/objects.dm, code/modules/power/groundmap_geothermal.dm
Makes the psi output based off the ratio of currently corrupted generators and generators on the ground. Why wasn't it like this? I have no idea. 
If you manage to corrupt the gens shipside you get extra psi, wow.
Psi gen math being sane is neat.
:cl:
fix: Fixes the psi gen fix fix by making the math actually not stupid. Psi is based off ratio of generators corrupted to uncorrupted.
/:cl:
=> Fixes the psi gen fix fix by making the math actually not stupid

code/_onclick/hud/screen_objects/screen_objects.dm, code/modules/projectiles/gun_system.dm
Guns are no longer opaque
Makes it so clicking on a UI box will relay your click to click on whatever item is inside the box.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/pull/12758
- Guns are no longer opaque: No more gun64 causing backpacks/pockets to become unclickable
- Things are easier to click on, clicking on the UI box will return whatever you have inside the box.
:cl:
add: Clicking on a UI box will click on whatever is inside the box.
del: Guns are no longer opaque
/:cl:
=> Clicking a UI Slot will return the item inside the slot

code/modules/clothing/modular_armor/attachments/uniform.dm
This removes MP19 from fitting inside the shoulder holster webbing.
MP19 is not a pistol, it doesn't fit in pistol belt, it should not fit in pistol holster webbing.
:cl:
balance: MP19 no longer fits in pistol webbing.
/:cl:
=> Shoulder holster can no longer carry mp19

code/game/objects/items/defibrillator.dm, code/modules/mob/living/carbon/human/life.dm
Because synths do not go cold!
Bug bad. 
:cl:
fix: Fixes synth erroneously being marked as "cold" on both minimap and examine
/:cl:
=> Fixes synth erroneously being marked as "cold" on both minimap and examine

code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/machinery/vending/vending_types.dm
This PR removes the new Medscanner gloves from the normal MarineMed, as really it shouldn't make sense that a common marine can get their hands on it.
[updating the pic, please stand by]
It's more of a balancing stuff, since it's pretty much a flat upgrade from the default marine gloves as it is right now.
:cl:
removed: Removed the Medscanner gloves from the Marinemed
/:cl:
=> Removes the medscanner gloves from the Marinemed

code/modules/projectiles/gun_attachables.dm, code/modules/projectiles/gun_system.dm, code/modules/projectiles/guns/mounted.dm, code/modules/projectiles/guns/smgs.dm
Changes the Burst Fire Assembly to decrease burst scatter and accuracy specifically.
Currently the BFA reduces scatter and accuracy generally, so even if you fire it on semi/auto, it still penalises you which is kinda wack.
The stats will be more or less the same, although the scatter may be very slightly higher for guns with large bursts (like BFA t18).
Also fixes a bug with MP19. I accidentally left out a minus, so it was MORE accurate instead of less, when burstfiring. Whoops.
BFA specifically effecting burst is good.
Bug fix good.
:cl:
balance: BFA now only penalises burst accuracy and scatter, not semiauto or autofire stats
fix: fixed MP19 being more accurate than it should be burstfiring
/:cl:
=> BFA change

_maps/map_files/Minerva/TGS_Minerva.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm, _maps/map_files/debugdalus/tgs_debugdalus.dmm, _maps/modularmaps/big_red/bigredcargoareavar3.dmm, _maps/modularmaps/big_red/bigredcargoareavar4.dmm, _maps/modularmaps/big_red/bigredcargoareavar5.dmm, _maps/modularmaps/big_red/bigredcargoareavar6.dmm, _maps/modularmaps/big_red/bigredsecornervar3.dmm, _maps/modularmaps/big_red/bigredsecornervar6.dmm
Apparently a number of BR modulars (specifically the ones created by vilereaver41) have huge amounts of loot in them. I have opted to remove the loot.
How much loot I hear you ask?
400 metal,
200 sandbags,
60 plasteel 
100 flares
500 mines (!!!)
30ish guns of random quality
2 sentries 
No free loot groundside, not in that quantity anyway.
:cl:
balance: Removed a bunch of free loot from BR
fix: Fixed a couple of broken spawner typepaths
/:cl:
=> BR modular loot removal

code/modules/clothing/modular_armor/attachments/storage.dm, code/modules/clothing/modular_armor/attachments/uniform.dm
Makes the list of the can_hold organized in the same order.
Adds a couple things to webbing/module
Webbing:
- Added advanced/autoinjector hypos
- Added latex gloves
Medical module:
- Added a whistle
- Added a beaker
- Added a health hud.
I think these are reasonable asks.
Holding beakers are also just inferior to holding more pill packets so I don't think this is game breaking in any way.
:cl:
refactor: White webbing/Medical armor module have some small things added to their whitelist.
/:cl:
=> Reorganizes white webbing/medical module

code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
`/datum/gas_mixture` doesn't exist in the code. This var is also unused. 
Unused vars of unknown type aren't.
:cl:
fix: Removed portable atmospherics machinery's var of non existant type
/:cl:
=> Removes portable atmospherics machinery's var of non existant type

code/datums/components/squeak.dm
Uh oh, how will the proc know which we're referring to!
Found via opendream:tm:
Arg ambiguity isn't.
:cl:
fix: Fixes two args having the same name in the squeak component
/:cl:
=> Fixes two args having the same name in the squeak component

code/modules/mob/living/carbon/human/species.dm
Robots now suffer from stagger and slowdown when below -25 health.
Repair mode is now 10 seconds instead of 5.
Robots have been powercrept repeatedly since they were added, and while they still have the very important drawback of no sprint, they have a significant number of strong advantages over humans, that makes them superior in many instances.
The staggerslow change is a fairly mild change mainly in response to robots:
A: Not having a crit at all meaning they effectively have 33% more hp than humans.
B: Cannot be crit dragged so are significantly harder to perma.
C: Being immune to pain and therefore the staggerslow associated with high pain
D: Being a one click revive regardless of damage, and having no permenant damage from death or draining.
The maintenance mode change is because 5 …
=> A couple of combat robot balance changes

code/modules/vehicles/mecha/_mecha.dm
`/obj/item/mecha_parts/mecha_equipment/thrusters` doesn't exist. This var is unused.
Found with opendream:tm:
Unused vars of nonexistant type aren't.
:cl:
fix: Removes unused mech var with nonexistant type
/:cl:
=> Removes unused mech var with nonexistant type

code/game/objects/items/storage/belt.dm, code/game/objects/items/storage/pouch.dm
Makes tool belt and tool pouch have the same can_hold list.
buffs toolbelt to max_w_class normal (same as tool pouch)
It's a bit weird that the pouch variant of the tool storage is better than the belt variant.
It's also weird that they dont hold the same things.
This normalizes it.
:cl:
refactor: Toolbelt and tool pouch can hold the same items.
/:cl:
=> Toolbelt and tool pouch can now hold the exact same things

code/modules/antagonists/_common/antag_datum.dm
`/datum/team` isn't a type that exists. The `Topic()` proc was defined twice. The var was unusued so I commented it out because I assume we'll want teams.
Unused vars of non existant type are bad.
:cl:
fix: Deleted duplicate proc def and unused var of nonexistant type on the antagonist datum
/:cl:
=> Deletes duplicate proc def and unused var of nonexistant type on the antagonist datum

code/game/objects/machinery/cell_charger.dm
Wrenchable = TRUE
^ For the codex to add the description
typo fix
:cl:
spellcheck: Cell charger properly indicates that it can be unwrenched.
/:cl:
=> Fix typo for cell charger

_maps/map_files/Theseus/TGS_Theseus.dmm
Instead of having it be HIDDEN BEHIND AN AIR ALARM, it is now actually visible
Oh and also you can't lock yourself inside tcomms as easily anymore, i guess
Hidden buttons bad, visibility good.
:cl:
fix: made Theseus's tcomms button easier to spot instead of being hidden behind an air alarm
/:cl:
=> Moves the button for Tcomms in Theseus

code/game/objects/items/storage/belt.dm
Medical Rig belt has isotonic instead of dexalin
Isotonic > Dex
Also, same reasoning as https://github.com/tgstation/TerraGov-Marine-Corps/pull/12695
"Dexaline's use is redundant in most cases when you have inaprovaline. As it is, the default loadout has no real blood replenishing options so a corpsman has to go out of their way to get one. Shouldn't be too big a change given both are available from vendors anyway, so more of a qol change than balance."
I feel like this also applies to doctors (or corpsman who opt to take the medrig belt instead of lifesaver)
:cl:
balance: Medical rig belt has isotonic instead of dexalin.
/:cl:
=> Medical Rig belt has isotonic instead of dexalin

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
I read someone complain about the Fortify Charge combo being "buggy" in Discord. Not being able to immediately charge out of Fortify is intentional (#7523), it's just that the way it works right now can lead to players thinking the behavior is buggy like I think it's the same problem #11972 is talking of. 
Instead of checking if Fortify is on cooldown, it just adds a cooldown to charge after fortifying. 
How it works right now:
[old.webm](https://user-images.githubusercontent.com/94504089/233837397-5ec6e0ed-6fbb-48ba-a631-fd1a9965e0b3.webm)
This PR:
[new.webm](https://user-images.githubusercontent.com/94504089/233837404-9524873a-6d6b-4d17-9f6f-79961c3343b7.webm)
QoL. Personally, I think it feels better to use.
:cl:
qol: defender's fortify charge combo should feel smoother to use
/:cl:
=> Makes Defender's Fortify Charge feel smoother to use

code/modules/mob/living/carbon/xenomorph/abilities.dm
Removes bloat ability since it's now in the hive status menu for free screen real estate
:cl:
del: Blessings menu action button removed. Button in hive status is unchanged
/:cl:
=> Blessings menu action button removal

code/modules/mob/living/carbon/xenomorph/abilities.dm
Annoying when testing
:cl:
qol: Makes xenos have all abilities if spawned prior to game start
/:cl:
=> Make xenos have all abilities if spawned prior to game start

_maps/map_files/icy_caves/icy_caves.dmm
Icy Cave is under maintained, therefore it produces rounds where marines benefit more from taking a walk to miners from landing zone. We've done this with other maps for the same reason.
Xander notes that xenomorphs cannot weed these area until marines open shutters, making these miners easy to capture and gain req points faster than any planetside maps.
:cl:
del: Remove three miners close to landing zone in Icy Cave
balance: Remove three miners close to landing zone in Icy Cave
/:cl:
=> Remove three miners close to landing zone in Icy Cave redux

code/game/objects/items/stacks/stack.dm
This runtimes if (for example) a roomba moves on its own and qdels a stack of metal. There is no usr (or rather it is 0, somehow) so it runtimes and fails to delete. Not good.
Failed dels bad.
:cl:
fix: Fixed stack Destroy() runtime
/:cl:
=> Fixes stack Destroy() runtime

code/game/objects/structures/misc.dm
Minor ground map fluff change.
Those decorative little cryo tank things you see on maps with huggers/larva in them are lorewise responsible for most if not all the xeno outbreaks that the marines have to deal with. Gameplay wise though, they do nothing.
Now they can actually be broken to release the living huggers inside (or dead larva).
Muh immersion
:cl:
add: hugger tanks found groundside can now be broken to release the living hugger inside
/:cl:
=> Improves xeno tanks

code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm, code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm, code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
making more space on queen ability bar
:cl:
qol: Toggling minion aggressivity is now the right click ability of command/rally minions
balance: Removes rally minions from queen since they have command minions
/:cl:
=> Rolls minion agressivity ability into rally/command

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Shows the carrier a balloon alert when they pick a hugger type.
balloon alert is good.
:cl:
qol: Balloon alert when carrier selects a hugger type.
/:cl:
=> carrier balloon alerts when switching huggers

_maps/modularmaps/big_red/bigredlzvar1.dmm, _maps/modularmaps/big_red/bigredlzvar2.dmm, _maps/modularmaps/big_red/bigredlzvar3.dmm, _maps/modularmaps/big_red/bigredlzvar4.dmm, _maps/modularmaps/big_red/bigredlzvar5.dmm, _maps/modularmaps/big_red/bigredlzvar6.dmm, _maps/modularmaps/big_red/bigredlzvar7.dmm
All Big Red LZ1 shall have 4 or 3 flanks as par standard of landing zones NOT to exceed or equal to 5 flanks. 
Some of Big Red LZ1 map modules have either 4 or 3 flanks, reduced from 5 flanks.
Annihilate this potential breach to FOB from all Big Red LZ1 map modules.
Change part of northern cave tunneling to LZ1 in light of reducing flank.
Allow xenomorphs to have an easier time making a funny hole from marshal to caves linking to LZ1.
No LZ with the exception of Big Red have more than 4 flanks. RipGrayson noted that Shiryu added an additional flank for some reason.
Due to the reduced flank, I ensure that xenomorphs can still contest against marines' FOB.
:cl:
balance: Some of Big Red LZ1 map modules have either 4 or 3 flanks, reduced from 5 flanks. This means that there are less fronts …
=> Big Red LZ1 Changes

code/game/objects/structures/inflatable.dm
Just so they're always transparent.
Closed doors being opaque when the walls aren't doesn't make sense.
:cl:
fix: Fixed inflatable door opacity
/:cl:
=> Fixes inflatable door opacity

code/game/objects/structures/tables_racks.dm
Tables flipping can move decals (along with anything `atom/movable`) currently. Not cool.
Bug bad.
:cl:
fix: Fixed tables flipping being able to move things it shouldn't
/:cl:
=> Fixes tables flipping being able to move things it shouldn't

code/modules/mob/living/carbon/xenomorph/abilities.dm
This is a bugfix, building isn't meant to trigger on left click.
Not randomly placing a wall while destroying stuff is rather neat for sanity's sake.
:cl:
fix: Quickbuild no longer triggers on left click.
/:cl:
=> Quickbuild no longer triggers on left click

code/datums/quick_load_outfits.dm, code/game/objects/items/reagent_containers/hypospray.dm, code/game/objects/items/storage/pouch.dm, code/modules/clothing/modular_armor/som.dm, code/modules/clothing/modular_armor/xenonauten.dm
A variety of loadout adjustments.
All squad marines (both sides) SG's, SL's and veterans now have medical suit storage.
This storage has gauze, ointment, dylo injector, QC injector and iso injector.
After gauze and ointment got buffed, they actual heal a significant amount if you can take the time to use it.
Because of this there have been a variety of loadout shuffling, most notably for SL's of both varieties to fit everything they need.
Better med QOL for HvH.
:cl:
balance: HvH: Variety of loadout tweaks, mainly aimmed at giving combat roles gauze, ointment and some other misc meds
qol: Inaprov hypos inject 15u by default instead of 10
/:cl:
=> HvH loadout adjustments

_maps/map_files/Minerva/TGS_Minerva.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm
Wrong typepaths led to wrenchable nanomeds
idk walance or something. At the very least, consistency
:cl:
fix: All shipside med vendors are properly the unwrenchable variant
/:cl:
=> Shipside medvendors are now shipside

code/modules/mob/living/carbon/xenomorph/abilities.dm
Negation logic is hard and so is doing even the most basic test.
Bug bad.
:cl:
fix: Fixed quickbuild drag not working
/:cl:
=> Fixes quickbuild drag not working

_maps/map_files/Minerva/TGS_Minerva.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm, _maps/map_files/Twin_Pillars/Twin_Pillars.dmm, code/game/objects/structures/droppod.dm, code/modules/reqs/supplypacks.dm
Allows droppods to be bought in req. 50 points each, 100 points for leader pod. You can move them with a powerloader and they will only launch on a pod launch bay.
Most even semi highpop rounds tend to run out of pods relatively quickly with no way to restock them. This PR rectifies that.
:cl:
balance: Allowed droppods to be bought in req, 50 points for a normal pod and 100 for a leader pod. Move them with a powerloader.
/:cl:
=> Allows droppods to be bought in req

code/controllers/subsystem/advanced_pathfinding.dm, code/game/objects/structures/supplypod.dm, code/modules/ai/presets/zombie_presets.dm, code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm, code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm, code/modules/organs/limb_objects.dm, code/modules/projectiles/projectile.dm, code/modules/projectiles/tracer.dm, code/modules/xenomorph/xeno_structures.dm
Removes the location param from Initialize defs due to it going completely unused in all cases and only causing issues, like args that were meant to be other args being passed into it with mapload being a thing now.
Fixes xeno structure lists not updating, warlock shields, laser weapon tracers being invisible and probably like 20 more.
Bugs bad.
:cl:
fix: Removes location params from Initialize defs, this fixes things like laser weapon tracers being invisible and structures not breaking on alamo departure during hijack
/:cl:
=> Removes location params from Initialize defs

code/game/objects/items/explosives/grenades/marines.dm, code/modules/projectiles/guns/grenade_launchers.dm
Make it not explode, make it not make fire when thrown regardless of primed/not primed, make it not runtime on cleaning refs.
Bugs and unintended behaviour bad.
:cl:
fix: Fixes up trailblazer runtimes and unintended behaviour like it exploding at the end
balance: Trailblazer fits in the nade launchers now
/:cl:
=> Fixes up trailblazer runtimes and unintended behaviour

code/modules/factory/unboxer.dm
Unboxer will turn on when refilled, and will turn off when empty.
It's weird having to click 3 times after you put a refill in a unboxer, this solves that by making the machine turn off when it empties, and turn on when you put a refill. 
You can still manually turn it on/off outside of that.
:cl:
qol: Unboxer no longer requires 3 clicks when you put a new refill
/:cl:
=> Makes Unboxer require less clicks.

_maps/map_files/Sulaco/TGS_Sulaco.dmm
Okie-dokie, originally this was going to be something that fixed the Sulaco having two sets of shutters stacked for some reason.
Found out the reason why and we've made a slight compromise, adds a tiny sub-armory in the Sulaco's CIC with all the basics, while allowing the SD variant to open when it's supposed to.
Allows the most basic stuff from the usual CIC armories to be accessed roundstart.
:cl: Skye
qol: Allows the basic armory goods to be accessed on the Sulaco ship map.
/:cl:
=> Adjusts the Sulaco's armories to allow for basic use at roundstart.

code/game/atoms.dm, code/game/objects/items/radio/headset.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/tables_racks.dm, code/game/turfs/floor_types.dm, code/modules/factory/parts.dm
Pointless param that never gets passed as an arg anywhere, only causes confusion as it is right now and there's no reason for it to exist anyhow.
Unused params bad.
:cl:
fix: Lockers shouldn't spill in contents that were mapped in after
code: Removed mapload as a param from LateInitialize
/:cl:
=> Removes `mapload` as a param from `LateInitialize()`

code/modules/projectiles/guns/energy.dm
Changes laspistol wield time from 0.6 to 0.2 seconds.
Brings laspistol wield time in line with all other pistols. I don't know why this pistol specifically has one this long given its designation as a pistol. Ironically it has a longer wield time than the lasrifle. Additionally, laspistol has worse unwielded accuracy than its ballistic counterparts, so I think that this would make wielding more rewarding and realistic as a quick defense option.
:cl:
balance: TE Laser Pistol wield time reduced from 0.6 to 0.2 seconds.
/:cl:
=> Reduce Laspistol Wield Time

code/game/objects/structures/droppod.dm
Fixes droppods facing you west and not unbuckling mobs once the pod gets picked up by a powerloader.
No, `DIRLOCK` didn't work. :(
Bugs bad.
:cl:
fix: Fixes droppods facing you west and not unbuckling mobs once the pod gets picked up by a powerloader
/:cl:
=> Fixes droppods facing you west and not unbuckling mobs once the pod gets picked up by a powerloader

code/modules/projectiles/magazines/energy.dm
Max charge reduced to 3000 from 4800.
Charge rate increased to 100 from 32 per 2 seconds.
Slowdown decreased to 0.2 from 0.3.
The power pack has a pretty comically low charge rate considering how fast you fire (a culverin can only fire 0.5 times per second instead of its actual 6.6 times per second, if you're running on empty), which can easily lead to prolonged downtime where you can't really use your bullet hose.
This change reduces the single burst fire time (20 seconds from full to empty instead of 26 seconds), but significantly increases the charge rate.
This should allow the culverin to still perform as originally intended, while being a bit less frustrating to use at times.
Reduces the slowdown since no other backpack has slowdown, and both guns that use it already have high …
=> Volkite power pack tweaks

code/modules/projectiles/magazines/shotguns.dm
This variant instead gives the Mosin clips the bog standard loose bullets mini_sprite. I thought they looked neater, should be more distinct too, so may as-well see what sticks. Either way, both PRs give a mini_sprite.
Notably this shouldn't be merged along with PR #12797  because it does the same thing.
Red X is still bad. But this time...More boolets!
:cl: Skye
fix: Gives the mosin clips a different already existing mini_sprite
/:cl:
=> Chooses an alternative In_Ammo_Box sprite for the Mosin clips. (Loose bullets)

code/modules/vehicles/unmanned/unmanned_turrets.dm
This is your fault, Jazzy.
Something with a superior damage and armor penetration model to the AR-21 should not have the fire rate of a SMG. Fire rate is now 4 times a second instead of close to 7.
:cl:
balance: Combat droid energetic cannon fire rate down to 0.25 from 0.15.
/:cl:
=> Nerfs combat droid fire rate

code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
If an obj has already been hit by acid spray once in a tile check, it will not be hit again by the atom/moveable acid spray check below.
This bug has made praetorian acid spray 2x as effective on all defensive structures and objs that are also moveable, which is unintended. 
:cl:
fix: prae acid spray no longer deals double damage to all objects that are also atom/moveables
/:cl:
=> fixed acid spray dealing double damage to all objects

code/game/turfs/liquid_turfs.dm
Fixes the water overlay getting stuck if you are teleported out of the water (such as medivac).
Bug fix.
:cl:
fix: fixed water overlays getting stuck if you are teleported out of the liquid turf
/:cl:
=> fixes aqua ghosts

code/__DEFINES/mobs.dm, code/game/turfs/liquid_turfs.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm, code/modules/mob/living/carbon/xenomorph/castes/warlock/warlock.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm, code/modules/mob/mob_helpers.dm
Some minor rework of how water slowdown is applied.
Slowdown is now define based via a proc.
All liquid turfs apply slowdown, and have a multiplier var to adjust slowdown.
This means you can no longer swim through lava faster than ankle deep water.
Lava and deep water have  a x1.5 modifier.
Killed the water slowdown xeno caste var.
Removed the weird negative slowdown boilers have (yes, they currently go through water FASTER than dry land), and make it just 0. I guess they float or whatever.
Make liquid turf effects apply to all mobs instead of just carbons.
Better code good.
More adjustable stuff good too.
:cl:
balance: Boilers no longer travel on water faster than land (just equal speed)
balance: Lava now applies slowdown similar to water
refactor: Tiny refactor of how water slowdown …
=> Water slowdown refactor

code/__DEFINES/loadout.dm
Removes 2 noob trap options from the synth vendor, IMP and satchel.
You spawn with a satchel as a synth so there is no reason to have it in the vendor.
The IMP backpack is a noob trap when it's infinitely vendable in the clothes vendor.
I only left the industrial backpack because I dont think it's vendable elsewhere despite being only a slight reskin.
:cl:
del: Synth vendor no longer has satchel or IMP backpack.
/:cl:
=> Synth vendor no longer has the base satchel and IMP pack

code/game/objects/machinery/miner.dm
Repaired miners not processing is bad.
Fixes #12914 
:cl:
fix: Uninstalling autominer mod doesn't break the miner
/:cl:
=> Autominer mod uninstall fix

code/game/objects/items/weapons/twohanded.dm, code/game/objects/structures.dm, code/game/objects/structures/window.dm, code/modules/clothing/glasses/glasses.dm, code/modules/clothing/head/misc.dm, code/modules/mob/living/carbon/human/life/life_helpers.dm, code/modules/mob/living/simple_animal/hostile/shade.dm, code/modules/mob/living/simple_animal/hostile/syndicate.dm, code/modules/vehicles/multitile/hardpoints.dm
Because `resistance_flags = 10` isn't as easy to read.
Clearer code good.
:cl:
code: Replaces some flags defined with ints with defines
/:cl:
=> Replaces some flags defined with ints with defines

code/modules/shuttle/navigation_computer.dm
Tadpole can land in water again.
Turns out there is a funny whitelist of turfs it can land on, honk.
Bug fix good.
:cl:
fix: fixed tadpole being unable to land in water
/:cl:
=> Tadpole water landing fix

code/modules/shuttle/marine_dropship.dm
Addresses the issue of the alamo controls being locked and unable to move for 6 minutes if you touch the console while it is in the process of taking off.
Bug bad.
:cl:
fix: Fixed alamo being unable to be called down if you touch the console as it is taking off
/:cl:
=> Fixes alamo being unable to be called down if you touch the console as it is taking off

code/datums/looping_sounds/weather_sounds.dm, code/datums/weather/weather_types/acid_rain.dm, code/datums/weather/weather_types/ash_storm.dm
Combines the ash/sandstorm looping sounds into two (active/weak). This means they won't exactly always be appropriate, but not like there's much difference between the outside/inside variations at all.
Accomplishes this by making the sounds play directly to mobs instead of to areas based on preferences.
The weather sound preference actually working is nice. Not everyone wants the weather sfx to make it hard to hear anything.
:cl:
fix: Made the weather sound preference actually work
/:cl:
=> Makes the weather sound preference actually work

code/modules/projectiles/gun_attachables.dm
So time ago someone decided to give gyroscopic stabilizer a 10% damage debuff per marine the bullet went over in aim mode. Problem is it's fucking impossible to tell unless you explicitly get told about it by a codediver or were around for the PR. Gyroscopic stabilizer's aim mode speed buff already competes with vgrip's speed buff that even applies outside of aim mode so it's not a braindead choice to need that debuff anyway.
Hard to convey mechanics bad
:cl:
balance: Gyroscopic stabilizer no longer has a 10% damage penalty per marine the bullet on aim mode goes through.
/:cl:
=> Gets rid of gyroscopic stabilizer's damage debuff

code/game/objects/items/explosives/grenades/marines.dm, code/modules/xenomorph/xeno_structures.dm
Acid wells now clear stickies from both marines and xenos. Minor changes to grenade code
Gives an active way for xenos to avoid death if prepared or near acid wells. Takes two charges to clear stickies.
:cl:
add: Acid wells remove sticky grenades
code: Changes to grenade code, specifically clear_refs
/:cl:
=> acid well changes and minor grenade code

code/modules/mob/living/carbon/human/species.dm
Title.
Currently, due for some reason happening in updatehealth() (???), robots will only get staggerslowed anytime their health is updated, means, damage, repairs, a bunch of other random procs called by a variety of things.
This is very inconsistant and very much not a stable "you are staggerslowed below -25 health", instead varying between "no effect" and "staggerstacked into next year"
This PR improves that behavior by moving the staggerslow adjustment into Life(), which is called consistantly, aswell as establishes a cap on stagger stack buildup (slow overlaps instead of stacking) to avoid being permanently staggered after going out of crit.
Fix man good?
:cl:
fix: Combat robot crit staggerslow now behaves consistently.
/:cl:
=> Fixes robot crit stagger

code/modules/clothing/modular_armor/mark_one.dm
**_Should_** fix the Surt module not being able to be placed on the MK.I Jaeger helmets
less bug good?
me no like bug
also fixes #12953
:cl:
fix: Surt Helm now can be placed on MK.I Jaeger Helm
/:cl:
=> Fix Surt module unable to be placed on MK1 Helm

_maps/map_files/desparity/desparity.dmm, code/game/area/lv624.dm
Super tiny fixes.
Removed some floating hydro signs, made marines unable to CAS the crashed ship in caves.
Bugs bad.
:cl:
fix: Fixed some floating signs in Desparity.
fix: Made CAS unable to bombard xenos in Desparity's crashed ship area.
/:cl:
=> Tiny Desparity fixes

code/game/objects/machinery/self_destruct.dm, tgui/packages/tgui/interfaces/SelfDestruct.js
#12888 broke the self destruct interface, making it display error when all rods are armed.
This fixes that glaring issue.
Additionally, the timer was also just broken in the first place. This makes the timer actually work instead of resetting for each rod, and also adjusts it to display in 1 second intervals instead of rounding down to the next 10 (feels more tense to have every single second tick down individually)
Also adds a very small note to the control part informing the user it is "offline", instead of elifing into the emergency case and displaying error when looking at it while disabled.
Fix man good.
:cl:
fix: The self destruct core no longer requires admin intervention to finish / blow up the ship.
fix: The time display on the self destruct UI should be more sane now.
/:cl:
=> Fixes the self destruct

code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Hey all, Dagger the Defiler main here. 
I've been on a mission to make sure all the info that you can find on Defiler is correct, to avoid misinformation. Since Defiler can tend to be a pretty complex caste for some. I love Defiler, and you should too. (But not enough to, yknow, get it nerfed 😅 )
Just a small quick change to a feature that has been left deprecated since Afflictor became a part of Defiler, and the Reagent Sight feature was never updated. Hopefully shouldn't break anything.
All this does is update the descriptions displayed when examining a human with any of the toxins present in them. Certainly not a massive gamechanger but very convenient to have.
Also updates the ability description for Select Reagent, which seemingly also had deprecated info. (Yes I know that it is …
=> Updates Xeno Toxin Hud Desc

code/modules/mob/living/carbon/xenomorph/damage_procs.dm, code/modules/projectiles/projectile.dm
Sunder scaling on applied sunder excessively hit weapons that have high firerate and low sunder. As an example:
A projectile that does 100 sunder will bring a xeno's armor% down from 100% to 0%.
A projectile that does 50 sunder and is shot twice will first bring down the armor% from 100% to 50%, and then for the second shot have the sunder value multiplied by 0.5 to do 25 and leave the xeno with 25% armor remaining rather than 0.
This pattern keeps going for guns that have lower sunder per shot.
:cl:
balance: Projectile sunder is no longer multiplied by the % of remaining armor of the struck xeno
/:cl:
=> New sunder no longer scales on existing sunder

code/game/objects/items/explosives/grenades/grenade.dm
Yes. Tested by putting a nade into a GL and taking it out, usually this makes it appear like it's about to go off (with the flashing !)
Bug bad.
:cl:
fix: Fixed nades erroniously appearing primed when they aren't
/:cl:
=> Fixes nades erroniously appearing primed when they aren't

code/game/objects/machinery/squad_supply/supply_beacon.dm, code/game/objects/machinery/squad_supply/supply_console.dm, code/modules/clothing/modular_armor/attachments/modules.dm, code/modules/reqs/supply.dm, code/modules/vehicles/unmanned/unmanned_droid.dm
Comes with a bonus signal override fix for the console.
Bugs bad.
:cl:
balance: Supply beacons now lose their signal when the source of the signal is destoryed
fix: Fixed the req console keeping dead signals in the list
fix: Fixed a signal override in the req console
/:cl:
=> All supply beacons lose their signal when destroyed + fixes dead signals in the supply console

tgui/packages/tgui-panel/styles/goon/chat-light.scss
Before:
After:
Whoever thought gray on white background was a good idea should be shot.
More readable.
:cl:
qol: Changed the light mode common radio color to green
/:cl:
=> Changes the light mode common radio color to green

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Title. With the way it's currently done the evasion only gets interrupted on the first life tick, which can be a bit (relatively). Seems like an oversight.
Bug bad.
:cl:
fix: Fixed runner being able to start evasion while on fire
/:cl:
=> Runner can't begin evasion if on fire

code/modules/xenomorph/xeno_structures.dm
Title
Fixes/Prevents wraith portal transportation cheese.
:cl:
fix: Turrets can no longer be portalled to bypass the range restriction.
/:cl:
=> Acid turrets are portal immune.

code/game/objects/machinery/dropship_part_fabricator.dm
be playing cas po
someone lets a xeno through and it melts the fab
you cannot fix it or replace it
now your entire job of playing cas is useless
cas po should be able to play the entire purpose of their job 
:cl:
balance: dropship fabricator is indestructible
/:cl:
=> Dropship Fabricator is Indestructible

code/modules/xenomorph/xeno_structures.dm
Reworks acid well sticky interactions to drop the grenades instead of Q-del, also fixes bugs
Qdel bad, easier to use but still allows the grenades to explode so not an instant get out of jail free card. bug squished.
:cl:
feature: acid wells cause stickies to drop instead of Qdel
fix: fixes acid wells triggering on their own
/:cl:
=> Acid well change rework plus bug squish

code/game/objects/structures/benchpress.dm, code/modules/mob/living/carbon/human/species.dm
Makes it so that the Weight Bench no longer gets banished to the shadowrealm if you dont wish to change the weights.
The TGMC can now stop having to buy a new weight bench everytime someone changes their mind and banishes the Weight bench
Also fixes #12949
:cl:
fix: Weight Benches no longer disappear when unselecting the radial wheel.
/:cl:
=> Stops the Weight Bench from being deleted when select wheel is closed

code/modules/clothing/modular_armor/attachments/cape.dm
Code fix. I saw this during kama code, and I went, "That's weird".
Cleaner code.
:cl:
code: remove unneeded override in cape highlight
/:cl:
=> Remove override on cape highlight

code/modules/clothing/modular_armor/attachments.dm, code/modules/clothing/modular_armor/attachments/cape.dm
Fixes some attachments going fully black.
I added the flag for capes instead of all greyscale for some reason.
Bug fix good. closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/13025
:cl:
fix: fixed some greyscale attachments showing entirely black
/:cl:
=> Greyscale fixes

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Stun turned into stagger. About the same amount of stagger the warlock crush does.
As it is, the tentacle kinda breaks the whole balance of defiler in my eyes. It's a caste that isn't meant to have a stun, so it getting it's hands on one makes it incredibly unfair to fight because defile exists. Using tentacle on someone basically guarantees that you'll get a defile off, which leads to unfun 100-0 combos which the target can't do anything to avoid. Stagger at least allows you to fight back to some extent. 
Note: due to the 0.1 stun it still has tentacle still works as a disarm.
:cl:
balance: Defiler's tentacle now staggers instead of a stun
/:cl:
=> Replaces the defiler tentacle stun with stagger

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Old PR was never finished.
King can no longer summon across z-levels.
Its dumb, and mechanically loses the game for the xenos... if the marines choose to just afk the disks for the next 40 minutes.
:cl:
balance: King can no longer summon across z-levels
/:cl:
=> king tele fix

code/game/objects/items/storage/holsters.dm
Fixes flares sometimes having full tile opacity.
Fixes #12051 
It turns out this was happening when a flare was right click loaded into a flaregun from a flarepouch, as the item wasn't being correctly removed from storage.
Also adds a check so you don't try reload the flaregun when its already loaded.
Being able to click a tile is good.
:cl:
fix: fixed flares sometimes having full tile opacity
/:cl:
=> Fixes flare opacity

code/modules/projectiles/ammo_datums.dm
Muh Mope etc.
Psylance no longer does bonus damage to objects hit (it still has a  large bonus against mechs specifically however).
Less able to insta murder turrets behind cades.
:cl:
balance: Psylance no longer does bonus damage to objects other than mechs
/:cl:
=> Warlock nerf

code/game/objects/effects/effect_system/smoke.dm
All forms of Tanglefoot smoke now reduces the lifetime of any xeno type smoke found on the same tile.
This means xeno smoke can still spread through tangle, but will rapidly get removed.
Also technically applies to WP smoke since that has the same anti plasma properties.
Adds a limited counter measure to smoke spam.
:cl:
balance: Tanglefoot gas now quickly removes xeno smoke occupying the same space
/:cl:
=> Tfoot smoke eats xeno smoke

code/modules/mining/remote_fob/remote_fob_computer.dm
Per title.
- Not a lot of people want to build FOB even when SLs _do_ want to. Giving SLs the ability to build FOB sounds good, so that there's statistically more chances for FOB to be built.
- Squad Leaders are, y'know, leaders. Building FOBs sounds like something a leader would do.
:cl: Lewdcifer
add: Squad Leaders can now use the FOB construction drone.
/:cl:
=> Squad Leaders can now use the FOB Construction Drone

_maps/modularmaps/prison/civresgym.dmm, code/game/turfs/liquid_turfs.dm
Fixes a prison pool not loading due to an old typepath somehow getting missed.
Space pool of death bad.
:cl:
fix: Prison station no longer has a pool leading directly to deep space
/:cl:
=> Prison pool fix

code/datums/jobs/job/marines.dm
They didn't scale, the number was flat from the start. Need 5 marines to unlock 1 corpsman/engi, seems like a good ratio. Unable to test because no clue how to fake population and also check remaining available slots.
You ever played deadpop and everyone was either engi, SGnr, or corpsman without a single squad marine? Yeah
You ever played highpop and had 100 marines and 1 or 2 corpsmen and engis that survived the 2 earlier hours? Yeah
:cl:
balance: Engi and corpsman slot now scales on pop of marines
/:cl:
=> Engineer and corpsman slots scale on squad marines

_maps/map_files/gelida_iv/gelida_iv.dmm, code/game/area/gelida_iv.dm
Makes a bunch of Gelida changes in hopes of making it less awful.
Here's the new version of Gelida in screenshot form
The changes are as follows;
-Revamps LZ2 to be less of a straight shot into caves while also making the area around it slightly more open
-Revamps LZ1 to actually be somewhat viable compared to LZ2
-Changes the cave power generators to be in the center of caves instead of the side
-Extends no build zones near the LZs somewhat
-Gives underground power generator room some lights
-Fixes mismatched LZ zones
Gelida isn't in a good place currently, it's always the same push from LZ2 into caves (which is usually ruined by a combination of overextension and the larva generation giving the xenos 15+ new bodies by the time marines make it to power gen). This is unfun and most of the …
=> Gelida changes 2023 edition

code/modules/projectiles/guns/sentries.dm
Ditto
Fixes #12919
Less typo good
:cl:
spellcheck: PD sentry description says accurate max ammo
/:cl:
=> Fixes typo in PD sentry description

_maps/map_files/Theseus/TGS_Theseus.dmm
Remapped Theseus' req operating area to not be a 1-tile corridor??? All consoles are now in a nice little overwatch corner, and all the vendors are grouped along the wall for easy access. The rest of the space is left open for reqtorio  or whatever else you wanna do with the space.
I HATE THESEUS REQ WHY DO I HAVE A 1X1 DOORWAY? WHY DO I HAVE A WALL SEPARATING THE SUPPLY CONSOLE FROM ALL THE VENDORS?
:cl:
balance: Theseus RO area is now more open and less cringe to navigate and use
/:cl:
=> Minor theseus req remap

strings/tips/xeno.txt
Behold, the solution to all of our tier based woes. A tip!
"As a xeno, a Tier 3 unit takes up both a Tier 3 and Tier 2 slot." - Sun Tzu, probably.
Er...Look, coding an actual thing isn't my forte. Fortunately, we have roundstart tips.
:cl: Skye
qol: Adds a single tip to the xeno section, regarding tier slots.
/:cl:
=> Adds a tip about tiers to the Xeno tip section. It's very tippy.

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
It adds an APC to an area that didn't have it. There's not much besides that.
On more practical terms, this means the disk generator isn't permanently powered.
Well...I mean....Bugs bad and all that?
:cl:
fix: Gives an APC to a area that didn't have it on Ice Colony
/:cl:
=> Fixes underground power station nuke disk location on the hit map Ice Colony.

_maps/map_files/LV624/LV624.dmm
Title.
**This is just an emergency measure until I can build enough modulars to have proper alternate locations for disks to spawn in.**
I'm being deluged with complaints about disk RNG placing all disks in the colony, this ruins the point of LV and makes winning the game nearly impossible for xenos.
:cl:
balance: Removed colony disk generators again.
/:cl:
=> Removes extra disk location in LV

code/game/objects/structures/droppod.dm
Prevents this 
https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/6e869a7e-a6f4-4c83-81ef-9bad2e24cdc4
Bug bad.
:cl:
fix: Fixed pod deleting you if they get shot out before you land
/:cl:
=> Fixes pod deleting you if they get shot out before you land

code/game/objects/items/tools/maintenance_tools.dm, code/modules/clothing/modular_armor/attachments/uniform.dm
Bulky sized cells no longer fit in webbings or small cell chargers.
Magic storage bad.
:cl:
fix: Large cells no longer fit in small cell chargers
/:cl:
=> Fixes unintended cell magic

code/game/objects/machinery/computer/nuke_disk_generator.dm
Makes base computers indestructable, so they can't be destroyed by xenos before nuke disk machines are actually spawned.
Bug fix good
:cl:
fix: fixed nuke disk gens being destructable before the ship crashes
/:cl:
=> Nuke disk fix

code/game/objects/items/storage/boxes.dm
When you take packaged or unpackaged MRE meal out of MRE, you can put it back in.
muy immersion
It never made sense to me why you can't put the MRE food back into the MRE. I have eaten MRE before (source: it was revealed to me in my dream about FX, for which I have never went to), and the MRE can definitely hold its stuff back.
Can also be balance since marines were forced to put the unpackaged MRE meal inside a backpack | satchel, so this PR is also a storage balance.
:cl:
add: Allow marines to put packaged or unpackaged MRE meal back inside of MRE
balance: Permit marines to have more storage by not forcing marines to use backpack | satchel space for MRE food
/:cl:
=> Allow MRE to hold its food

config/config.txt
Causes a runtime currently if you don't have TTS set up on your local, tivi forgor
Runtime bad
:cl:
config: Commented out TTS in default config
/:cl:
=> Comments out TTS in default config

code/modules/mob/living/carbon/human/species.dm
DO NOT PUT SPECIES CODE ON THE MOBS!!!
NEVER DO IT
THE DATUMS MUST BE HANDLING EVERYTHING
:cl:
fix: fixed not being an explicitly spawned species not giving robots a damage screen overlay
/:cl:
=> Removes combat robot code on the mob

code/controllers/subsystem/minimaps.dm
Minimap fire() is about 6-7 times faster when testing with ~150 AIs
Makes minimap fire scale better by moving the fire list operations into less often called add and z move procs
:cl:
code: Minimap has been heavily optimized
/:cl:
=> Heavy minimap fire() optimization

code/modules/reagents/holder.dm
Because this codebase doesn't have suppressants, there's no case where removing a reagent would cause a reaction to be possible when it wasn't previously. 
Mostly important because this was bunch of iteration being called every single time any chem metabolized.
:cl:
code: Chemicals don't try to react when some of them are removed.
/:cl:
=> Reactions aren't checked on reagent removal

code/modules/projectiles/gun_attachables.dm, code/modules/projectiles/gun_system.dm
One line to allow it and another to make sure it disconnects if the parent gun leaves inventory.
Fixes #12517 
:cl:
fix: Attached guns can be loaded with worn magazines
/:cl:
=> Reenables loading worn mags into attached guns

code/modules/projectiles/guns/energy.dm
Xray rifle standard shot firerate is now 0.25. Piercing mode unchanged.
Gives it an actual reason to be used over piercing given it had AR12 stats for OVER TWICE the firedelay, giving it the same reasons to not be used as heat mode from the laspistol and lassniper. The firestacks don't even do enough damage to make up for it, funnily enough, and the low firerate makes it unwieldy against fast xenos like rouny that on paper it'd be supposed to be ok against. Assuming you didn't just set the 5 marines around you on fire with ff.
Final stats still deliberatedly worse than AR12.
:cl:
balance: xray rifle standard shot firerate now 0.25 (Comparison: AR12 has 0.2)
/:cl:
=> Xray rifle std firerate increase

_maps/map_files/Minerva/TGS_Minerva.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm
Starting off, deletes a rogue APC from the Minerva's mech bay and moves a mech prop that was covering the actual one.
Additionally, adds some wires to Minerva and Thesseus' engineering zones, this connects the power monitoring consoles to the grid. (Minerva image not included. It's one piece of wire, check the checks section.)
**11:06PM :** Moves a wall chair from the maints of the Pillar of Spring, along with fixing a wire in one of the surgical rooms.
Hiccups being fixed is good, I guess. That and not having to fix the wires each round.
:cl: Skye
qol: A secret has been revealed! You can now find the mech bay's APC on the Thesseus map.
fix: Added wires to the power monitoring computers in Thesseus and Minerva's engineering zones.
/:cl:
=> Slight Thesseus changes and a piece of wire on Minerva. (And the Pillar of Spring)

code/__DEFINES/obj_flags.dm, code/game/turfs/closed.dm
Title.
I have merged PLASMACUTTER_IMMUNE into RESIST_ALL as it didn't make sense that our all purpose indestructible flag was allowing things to be destroyed via plasma cutter.
It's more logically consistent, also fixes a nasty bug with https://github.com/tgstation/TerraGov-Marine-Corps/pull/12893 preventing mineral walls from being cut.
:cl:
fix: Fixed walls with the UNACIDABLE flags being also immune to plasma cutters
code: Added PLASMACUTTER_IMMUNE to RESIST_ALL
/:cl:
=> Fixes an oversight with a resistance_flag

code/__DEFINES/mobs.dm, code/datums/jobs/job/job.dm, code/datums/jobs/job/shipside.dm, code/datums/outfit.dm, code/modules/mob/living/carbon/human/species.dm
Fixes #12941 more or less
Robo FC spawns with robot uniform and armour instead of being naked. This means he actually gets his binos and such.
Adds the support more generally for species specific outfits, but I didn't add any to the other ship roles because A: We have no non combat gear for robots, and B: They're expendable **combat** robots, why are they staff officers and doctors to begin with?
If someone adds gear they can add them though. Same goes for if we add some other snowflake race in the futre.
Not spawning with important gear due to a game pref is bad.
:cl:
fix: Field Commander robots now spawn with robot equipment
code: Adds support for species specific outfits
/:cl:
=> Robo FC spawns with gear

code/game/objects/structures.dm
This fixes #13120. Apparently when sending the signal it had to wait for the climbing `do_after` to return which made the whole `ClickOn` proc sleep.
Bug bad.
:cl:
fix: Fixed `COMSIG_MOB_CLICKON` sleeping when climbing, this should fix crate climbing/pulling
/:cl:
=> Fixes `COMSIG_MOB_CLICKON` sleeping when climbing

_maps/map_files/desparity/desparity.dmm
Removes a total of 6 invisible objects from both LZ's which I don't even know how they wound up there
You got blocked by this, not even sure how this happened
:cl:
fix: you should no longer bump into invisible objects on Desparity
/:cl:
=> Fixes invisible blocking objects on both LZ's on Desparity

code/modules/projectiles/gun_system.dm
Was checking whether it should or not in the wrong part of the chain, so signal calls in bypassed it
Fixes #13124 
Fixes #13119 
:cl:
fix: Dropping a gun won't make all the ammo fall out of attachments
/:cl:
=> Fixes attachments unloading on drop

code/modules/projectiles/ammo_datums.dm
Reduces mech bonus damage from 200-400 to just flat 200.
The bonus damage was added before several nerfs that reduced mech survivability. Its now kinda too strong for mechs as they currently are, although they'll still be extremely good against them.
:cl:
balance: Reduced Psylance effectiveness against mechs slightly
/:cl:
=> Psylance vs mech tweak

code/__DEFINES/conflict.dm, code/modules/projectiles/projectile.dm
- Removes the slowdown inflicted when an AMR bullet hits a xenomorph.
- Removes the bullet penetration bonus associated with an active laser.
The AMR is a bit too oppressive as it stands right now, and has been for the longest time.
About damn time someone gave it the heavy hand.
:cl: Lewdcifer
balance: AMR slowdown removed, bullet penetration bonus from laser removed.
/:cl:
=> Removes AMR bullet slowdown and laser penetration bonus

code/modules/mob/living/carbon/xenomorph/death.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
The reward from hive threat was failing sometimes, it turns out due to the order in which stuff happens during xeno init was leaving null entries in the normal hive list due to admeme/valhalla xenos.
Bug fix good.
:cl:
fix: fixed hive threat rewards not working some times
/:cl:
=> Fixes hive threat reward

code/modules/projectiles/gun_system.dm
Turns out some magazines aren't magazine and so need their flags checked differently.
bugfix
:cl:
fix: Power pouches disconnect from guns properly when one is dropped
/:cl:
=> Fixes power packs not disconnecting on drop

code/game/objects/items.dm
Being blind prevented you from unzooming so you'd stay with supervision even after you dropped the gun
Fixes #13148 
:cl:
fix: Dropping your gun while blind resets any active scope
/:cl:
=> Fixes blinds permazooming you

code/modules/reqs/supplypacks.dm
Its named wrong
Not being named wrong is neat
:cl:
fix: The GL54 razor nade magazines have the correct name in req now
/:cl:
=> Fixes GL54 razor nade name in req

code/game/turfs/turf.dm, code/modules/shuttle/marine_dropship.dm
Basically alamo straight up deleting people who are outside the doors can be kinda lame. AI nodes are abstract and shouldn't be getting influenced.
Getting deleted upon crash isn't exactly engaging. If it's meant to be punishing to be caught near alamo when it crashes then have the xenos do a punishing instead of a mechanic designed to make sure xenos can leave alamo. 
:cl:
balance: Alamo shouldn't delete you if you stand near the doors when it crashes
fix: Fixed AI nodes being deleted when turfs get emptied
/:cl:
=> Prevents alamo crashing from deleting mobs and AI nodes

code/datums/jobs/job/clf.dm, code/game/objects/items/explosives/bombvest.dm, code/game/objects/machinery/vending/marine_vending.dm
gives the boom vest the correct stats and repaths it
the harness got removed in the purge, and the boom vest inherited its stats from it. i fix.
:cl:
fix: tactical explosive vest now has the correct armour and slowdown stats
/:cl:
=> Boomvest fix2

_maps/map_files/Sulaco/TGS_Sulaco.dmm
Due to Rosa Borden (whatever their discord tag is.) having troubles, I made this as closely as possible to their version.
It adds a map table to the main lobby, next to the crew computer.
And a shower in the hypersleep room. (Though I don't think it'll help with germs much there.)
I guess it'll be more in line with the PoS and it's map table? Maybe?
:cl:
add: Adds a shower and map table to the Sulaco medbay. Stop stinking.
/:cl:
=> Gives the Sulaco Medbay a map table and a shower.

_maps/map_files/Theseus/TGS_Theseus.dmm
Theseus' OB and railgun armaments are closer to CIC.
Some CIC players HATE Theseus because reloading OB is far. The second Theseus designer, me because I will hope that Alterist consents to my changes, decides to give a new reason for Theseus to be chosen.
:cl:
add: move Theseus' ship armaments closer to CIC
/:cl:
=> move Theseus' ship armaments

tgui/packages/tgui/interfaces/PlayerPreferences/GearCustomisation.tsx
Couldn't select glasses and such. 
Bug bad.
:cl:
fix: Fixed gear preferences not showing everything
/:cl:
=> Fix gear preferences not showing the right slots

code/datums/status_effects/debuffs.dm, code/game/objects/structures/crates_lockers/closets.dm, code/modules/mob/living/carbon/human/human_defense.dm
All of these are because of an improper first arg being supplied.
Runtime bad.
:cl:
fix: Fixed some runtiming balloon alerts
/:cl:
=> Fix some runtiming balloon alerts

code/game/turfs/closed.dm
Seems like https://github.com/tgstation/TerraGov-Marine-Corps/pull/12893 made it so you could acid jungle walls, I saw a few people using this. So I've come and fixed it.
Being able to acid walls placed to stop you from aciding or accessing tiles is probably not the best thing to leave in the game.
:cl:
fix: Jungle walls are now unacidable again.
/:cl:
=> Jungle walls are now unacidable.

code/modules/mob/living/carbon/human/species.dm
This is in effect a redo of the species changes in https://github.com/tgstation/TerraGov-Marine-Corps/pull/10149
Early synth is *much* tankier, at the expensive of being a very, very slow boy.
Max HP is doubled to 200 from 125.
Brute/Burn mod is .6 from .7.
Inherient Slowdown of 1.15.
Early/Late synth should have noticeable gameplay differences beyond their skill set and this accomplishes that in a nice and simple way that is clearly noticeable to the player.
:cl:
balance: Early synth is now properly slower and tankier than late synth.
/:cl:
=> Early synth health stats differentation

code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
The qdel nulls were causing double deletions, `remove_status_effect` handles their deletions, we don't need to do it again.
Double del bad.
:cl:
fix: Fixed drone link double del
/:cl:
=> Fixes drone link double del

code/modules/mob/living/carbon/xenomorph/facehuggers.dm
This instance didn't have `TIMER_STOPPABLE`
Runtime bad
:cl:
fix: Fixed a hugger timer runtime
/:cl:
=> Fixes a hugger timer runtime

code/modules/projectiles/gun_system.dm
`Runtime in code/modules/projectiles/gun_system.dm, line 1189: undefined variable /obj/item/weapon/combat_knife/var/flags_magazine`
Tested GLs and normal guns.
Runtime bad.
:cl:
fix: Fixed reloading runtiming if you try to load a non magazine into a gun
/:cl:
=> Fixes reloading runtiming if you try to load a non magazine into a gun

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/energy.dm
Restored carbine sunder back to 1 per shot instead of 1.5 (that should only apply to the rifle).
I somehow deleted this out of the main laser rework PR.
Unintended change bad.
:cl:
fix: Laser carbine does 1 sunder per shot on autoburst instead of 1.5
/:cl:
=> laser carbine sunder fix

code/game/turfs/walls/resin.dm
Makes the delay 1s instead of 4s.
To avoid people accidentally tearing things down during combat, I couldn't make it instant, so 1s it is.
A bug was found in #13173 that made deconstruction instant.
As it turns out, this improved xeno game flow, at least from my perspective.
Less stupid sabotage, faster gameplay, very good.
:cl:
balance: Deconstructing xeno structures as a xeno now takes 1s instead of 4s.
/:cl:
=> Makes deconstructing xeno structures as a xeno faster

code/modules/admin/holder.dm
Rooba got no client.
Cannot read 0.client
Runtime bad
:cl:
fix: Fixed roomba no client tts runtime
/:cl:
=> Rooba adv proc call

code/controllers/subsystem/silo.dm
Makes silo larva gen scale based off the ratio of active marines to xenos.
In what has become much more apparent due to our more regular very high pop numbers, xenos can often get into a situation where they have somewhat absurd larva regen, making it extremely difficult for marines to actually reduce their numbers in any meaningful way.
This is caused by a few factors, but most important to understand is that:
1. Larva gen scales off the number of active marines on the z-level, but has **no scaling for the number of xenos**
2. Xenos directly get more larva for killing and draining/cocooning marines which **does not scale with pop**
These two points means growing xenos numbers snowballs much easier at high pop compared to lowpop.
This PR uses an 'ideal' ratio which is based on the number …
=> Silo scaling

code/game/objects/machinery/computer/crew.dm
`undefined variable list/var/gc_destroyed`
Don't pass lists to `RegisterSignal`
Runtime bad.
:cl:
fix: Fixed crew monitor signal runtime
/:cl:
=> Fixes crew monitor signal runtime

code/datums/components/chem_booster.dm, code/datums/components/harvester.dm, code/game/objects/items/reagent_containers/pill.dm
Applies to both harvester weapons and the armor module. The full pill is always consumed, even when there's only space for part of it.
Restricting chem gear from using the chem form marines are generally supplied with the most is kinda weird.
:cl:
balance: Vali armor and weapons can load reagents from pills
/:cl:
=> Vali can load from pills

code/game/objects/effects/countdown.dm, code/game/objects/machinery/nuclearbomb.dm, tgui/packages/tgui/interfaces/NuclearBomb.tsx
Refactors the nuke to use timers, it shouldn't take twice the time set to explode anymore (i think)
:cl:
refactor: nuke uses timers
/:cl:
=> Refactor nuke to use timers

code/modules/xenomorph/xeno_structures.dm
I dunno why this stuns for 4 whole seconds but uh, chain stunning is generally bad.
Infinite brazil memes bad.
:cl:
balance: Resin holes can no longer chain stun
/:cl:
=> Fixes resin hole chain stun

code/game/objects/machinery/vending/marine_vending.dm
title
1) Niche medicine in autoinjectors like imidazoline, alkysine, quick clog, and hypervene are accessible to any marines but not spaceacillin
2) For the marine that really want to ensure that when he gets infection, he can deal with it himself
3) Permit corpsmen to have the chance to choose a tiny med item to deal with infection
:cl:
add: add spaceacillin autoinjector to marinemed
balance: squad marine can have easier access to spaceacillin, which makes it easier for them to deal with infection
/:cl:
=> add spaceacillin autoinjector to marinemed

code/game/objects/items/reagent_containers/hypospray.dm, code/game/objects/items/storage/firstaid.dm
When items like pill packets and bottles, hyposprays, and autoinjectors are vended into storage the icon is not updated. This PR makes it update on enter storage.
No one wants to take an item out and back into storage just so you can see the content and how much is in it.
Before:
After:
Some more things:
1. There are probably other items where this is broken and I just forgot/don't know
2. This is probably a horrible way to fix it, this is my first TGMC PR
:cl:
fix: Medical items show overlays when vended into storage
/:cl:
=> Fixes medical item overlays not appearing when vended into storage

code/game/objects/items/reagent_containers/autoinjectors.dm, code/game/objects/machinery/vending/marine_vending.dm
Puts 30 RR autoinjectors into the marinemed vendor. 
RR is available in relatively large quantities because of the 6 RR pill bottles in Medplus vendor and 1 RR pill bottle in tadpole medical vendor. The squad marine only vendor also lets you choose injector pouch with your 2 options of pouches, which contains an RR injector. It contains 10u of RR and 5u of ryet, 15u dose setting by default. 
As per QV's request, I have made the RR injectors unable to be restocked to prevent people from farming RR and ryet. 
:cl:
add: Added 30 RR autoinjectors to Marinemed vendor, which cannot be restocked. 
/:cl:
=> Adds Russian Red autoinjectors to Marinemed Vendor

code/game/objects/structures/xeno.dm
Title, as it turns out they use a different attack_alien proc.
Consistency and also this is a bug lol.
:cl:
fix: Doors are now destroyed in 1 second just like everything else.
/:cl:
=> Resin doors are destroyed in 1 second

code/game/turfs/walls/walls.dm, code/modules/mob/living/carbon/human/human_damage.dm, code/modules/mob/living/damage_procs.dm, code/modules/projectiles/projectile.dm
Fixes a couple of outstanding issues with turf armour. Yes, turfs (i.e. all walls) have armour.
Fixes hard armour being used as a flat modifier (no change as unused entirely)
Fixes projectile penetration doing precisely nothing against walls.
This will translate into a notable balance change, as high AP projectiles will melt walls (both human and xeno made) notably faster.
For example an HMG/HSG will do **80% more damage** against walls with this fix. Although thats a more extreme example.
Also moved the get soft/hard armour procs out of the projectile dm as they didn't really belong there.
Bug fix good.
:cl:
fix: fixed projectile penetration not working against walls
/:cl:
=> fixed turf armour

code/game/objects/items.dm, code/modules/mob/living/carbon/human/human_damage.dm
`Runtime in code/modules/projectiles/projectile.dm, line 1203: Cannot read null.hard_armor`
Runtime bad.
:cl:
fix: Made get_limb just return the limb if its passed one, this fixes a hard armor runtime
/:cl:
=> Fixes `get_limb` getting a limb passed

code/datums/weather/weather_types/acid_rain.dm
Title.
Since sand storm and acid rain cause damage to both xenomorphs and marines, both sand storm and acid rain ought to sound an alarm. Also, since colonists previously lived in these two locations, it made sense that leadership wanted colonists to not die due to not hearing warning and get in shealter.
:cl:
add: give acid rain a siren warning like sand storm
/:cl:
=> give acid rain a siren warning like sand storm

code/game/objects/machinery/nuclearbomb.dm
milliseconds werent being converted to seconds in the ghost notification. also round all the unit conversions
:cl:
fix: the ghost notification for the nuke prints seconds correctly
/:cl:
=> Fix nuke timer ghost notification

code/modules/projectiles/magazines/misc.dm
556->5.56
762->7.62
dumb cat accosting me
:cl:
spellcheck: 5.56 and 7.62 boxes now have their dots in their name and description.
/:cl:
=> adds a dot to 7.62x39 and 5.56 ammo boxes

_maps/map_files/gelida_iv/gelida_iv.dmm
Too easy for engineers to gamer.
:cl:
del: remove easy plat miner in Gelida IV
balance: remove easy plat miner in Gelida IV
/:cl:
=> remove easy plat miner in Gelida IV

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Applies the roar effects in a 2 tile wide band instead of 1 while tracking victims to make sure they are not hit more than once, so that simply moving towards the King does not negate what should be one of its most effective abilities.
Fix good.
:cl:
fix: King's roar no longer misses things moving towards the King,
/:cl:
=> Fix King roar reliability

code/modules/mob/living/carbon/human/human_damage.dm, code/modules/mob/living/damage_procs.dm
Makes armour getters for humans actually work properly.
So human armour getters were kinda fucked in 2 ways.
1: Hard armour simply had no code to retrieve a number if no limb was specified.
2: Soft armour did this bizarre calculation to get some weighted average armour value when no limb was specified.
But the correct overall armour is already calculated... it's what the mob's soft/hard armour value is.
The procs will now just call parent if no limb is specified, meaning they get the actual, accurate figure. This means in some cases the value will be slightly different from what you'd get currently.
For example on my SOM test guy, melee soft armour is 61, but currently the proc returns a value of 63.
Better code.
:cl:
fix: fixed a couple of issues with human total armour calculations …
=> Fix human armour checks

code/game/objects/machinery/vending/marine_vending.dm
Adds medium general pouch to white clothing vendor in unlimited quantities. It is a pouch with 2 slots of storage that can hold normal sized items. 
My understanding is that the medium general pouch was replaced by current general pouch, which was supposed to be a straight upgrade to the medium general pouch. So medium general pouch was mostly removed because it was thought to be bloat. I don't know if this was an unintended change at some point, but the current general pouch cannot hold normal sized items except for ammo boxes (ex. 10x24 ammo box to refill T12 magazines). 
There is a niche for being able to carry normal sized items in a pouch slot. Weapons with normal sized magazines like the T29 (SG-29), T60 (MG-60), T42 (MG-42), HMG-08 for the 250 round drums, and large flamerthrower …
=> Adds Medium General Pouch to White Clothing Vendor

code/game/objects/structures/dropship_ammo.dm
this also fixes illum flares not lighting up
this is the only explosion that does it and its breaking illum flares
:cl:
del: smoke effect from minirockets
/:cl:
=> remove smoke effect from mini rocket impacts

code/datums/elements/debris.dm
AddElement gets called in the parents of all closed turfs, then on the children which overrides it. The element itself is highlander, the signal might as well be too.
Runtime bad.
:cl:
fix: Fixed a debris runtime
/:cl:
=> Fixes debris runtime

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Warlock's shield now changes visually depending on the amount of integrity left
100% port of https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/53
More visuals = good
:cl:
add: warlock's shield changes transparency depending on integrity
/:cl:
=> Warlock shield transparency port from RU

code/game/objects/machinery/autodoc.dm
It caused runtimes.
Runtime bad.
:cl:
fix: You can't put dogs or other nonhumans into the autodoc anymore. Stop it.
/:cl:
=> Non humans don't fit in autodoc anymore

code/modules/mob/living/carbon/xenomorph/embryo.dm
SSD larva that bursts out grounside, will automatically burrow, instead of being non controlled and dying instantly.
Does not work shipside.
Basically 100% port of this <https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/15>
Ssd larva that cannot do anything isn't really useful, this fixes the issue.
:cl:
add: if burst groundside larva has no player, it'd automatically burrow and give a larva point
/:cl:
=> No mind burst larva auto burrow

_maps/pillar_of_spring.json
removes the limitation on pillar of spring generating only two squads
allows for four teams. in the rare event that someone actually assigns teams to do things, there'll now be more teams to cover various parts of the operation.
mostly this is to allow for selecting four Squad Leader roles on join/roundstart like sulaco, or to allow for assigning up to four Squad Leader roles. Pillar of Spring gets played decently often enough on high pop that i think having four SLs is justified.
:cl:
balance: Pillar of Spring can now support up to 4 squads roundstart
/:cl:
=> allows for more than 2 squads when Pillar of Spring is the ship map

_maps/theseus.json
removes the limitation on theseus generating only two squads
allows for four teams. in the rare event that someone actually assigns teams to do things, there'll now be more teams to cover various parts of the operation.
mostly this is to allow for selecting four Squad Leader roles on join/roundstart like sulaco, or to allow for assigning up to four Squad Leader roles.
theseus is even thematically designed to support four squads, so i dunno why you never get to see all of them in action (i want to bully the alpha squaddies who don't follow the red tile pathway and come to the wrong prep room)
:cl:
balance:  Theseus can now support up to 4 squads roundstart
/:cl:
=> allows for more than 2 squads when theseus is the ship map

code/datums/looping_sounds/weather_sounds.dm, code/datums/weather/weather.dm, code/datums/weather/weather_types/acid_rain.dm
- Sandstorm actually uses all variations of the looping sound now.
- Acid rain telegraph and start and end sounds are properly separate now.
- You don't get the flavor messages if you aren't on the impacted z levels anymore.
Bugs bad.
:cl:
fix: Sandstorm actually uses all the sound variations
fix: Acid rain telegraph and start/end messages work properly
fix: You don't get the weather messages if you aren't on the weather's Z level anymore
/:cl:
=> More weather fixes

code/__DEFINES/dcs/signals.dm, code/datums/components/squeak.dm, code/datums/elements/jump.dm
Adds a new turf signal for jump landings.
Hooked up to the squeak component because I want things to squeak when I jump on them in place.
More jump interaction possibilities.
:cl:
add: Added a signal for jump landings on turfs, and implemented for squeak toys.
/:cl:
=> Fix squeak toys not squeaking when jumped on w/ new turf jump ended signal

code/modules/reqs/supplypacks.dm
#13202 made a mistake and overwritten the original MLRS rockets, making it so only gas rockets can be used, this makes it so both can be ordered as intended.
It isnt
:cl:
fix: TA-40L standard rockets are orderable from requisitions again.
/:cl:
=> Fixes MLRS Rockets being unavailable

code/datums/jobs/job/marines.dm, code/game/objects/items/storage/boxes.dm, code/game/objects/machinery/overwatch.dm, code/game/objects/machinery/vending/loadout_vendor.dm, code/game/objects/structures/prop.dm, code/modules/reqs/supply.dm
Title.
My lore and immersion.
For the non-military players that don't understand why the correction is made so that we make reference to marines instead of soldiers:
1) This is the TerraGov Marine Corps, not TerraGov Army.
2) Junior enlisted ranks reflect Marine Corps junior enlisted ranks, not Army junior enlisted ranks, so it would be absurd to call an E3 lance corporal (or terminal lance for people who know) a soldier when in the Army there is E3 private first class. Don't get me started on Army E4.
3) E7 in Marine Corps is Gunnery Sergeant, E7 in the Army is Sergeant First Class. We have gunny.
4) Marine Corps has corpsmen, Army has combat medics.
Realism is not the focus, it is consistency. You can go call a marine a soldier, but see what happen.
Still waiting on IRL Army to make a …
=> Changing soldiers to marines in some item and description

code/modules/mob/living/silicon/ai/ai.dm
Currently the AI targetting beacon for artillery breaks if you try to link another deployable after the first one, this makes it so the code doesnt break and can transition to the newest linked deloyable
Why should it be good for the game?
:cl:
fix: Attempting to link multiple deployables to AI no longer breaks the system.
/:cl:
=> Fixes targetting breaking when another module inserted

_maps/map_files/Minerva/TGS_Minerva.dmm
removes erroneous engine in minerva's ob room
it's in the way, also bug bad
:cl:
fix: removed misplaced engine in Minerva's OB room
/:cl:
=> removes engine in minerva OB room

code/modules/projectiles/mounted.dm
`Runtime in code/modules/projectiles/gun_system.dm, line 1426: undefined proc or verb /obj/item/weapon/gun/heavymachinegun/put in any hand if possible(). `
Funny. Can be reproduced by right clicking a deployed gun (08 for example)
Runtime bad.
:cl:
fix: Fixed a mounted gun runtime
/:cl:
=> Fixes a mounted gun runtime

code/datums/elements/shrapnel_removal.dm
`Runtime in code/datums/elements/shrapnel_removal.dm, line 53: Cannot read null.implants`
Can be reproduced by tweezering someone and not selecting a bodypart.
Runtime bad.
:cl:
fix: Fixed a tweezer runtime
/:cl:
=> Fixes a tweezer runtime

code/controllers/subsystem/monitor.dm
`Runtime in code/controllers/subsystem/monitor.dm, line 83: type mismatch: cannot compare /list (/list) to 30`
Runtime bad.
:cl:
fix: Fixed a ssmonitor runtime
/:cl:
=> Fixes a ssmonitor runtime

code/game/turfs/space.dm
Space now always does damage by applying debuff on every step, no longer can you do weird damage evasion in space, which allowed some xenos to do abuses outside the ship. (wraith doing portals to space and xenos building a silo there)
Fix = good
:cl:
fix: fixed cases when damage from space turfs could've been negated
/:cl:
=> Fix space dealing inconsistent damage

code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Addresses inconsistencies between the bind and the action, clicking the action would get blocked in cases where pressing the bind wouldn't.
Prevents unintended behaviour like resting while rooted and other cases.
:cl:
fix: Resting via bind as a xeno now respects the use flags of the rest action
/:cl:
=> Resting via bind as a xeno now respects the use flags of the rest action

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Enables evolution points collecting even when there is no client/soul.
100% port of this https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/174
Good thing for cases when a client crashes and has to reload, or during any other unforseen disconnecting issues, which compensates the time client wasn't connected, additionally, would lower the damage to the hive by having ssd xeno ready to evolve if a ghost takes it, without any need to wait for evolution.
:cl:
add: evolution points tick even if xeno has no client/soul
/:cl:
=> evolution without client

code/modules/mob/living/carbon/xenomorph/damage_procs.dm, code/modules/mob/living/status_procs.dm
Unfugs ex_act for xenos.
It had some real wack numbers that were confusing, overly complicated and in some cases simply not working.
Simplifies it and tweaks some numbers marginally.
Working/sane code is good
:cl:
code: Reworked some code in xeno explosion code
fix: Xenos should correctly get staggered by explosions
/:cl:
=> xeno ex_act sanity

code/game/objects/items/reagent_containers/autoinjectors.dm
Old RR autoinjector:
-15u total capacity
-15u dose
-10u RR and 5u ryetalyn
New RR autoinjector:
-30u total capacity
-15u dose
-20u RR and 10u oxycodone
-10u RR and 5u oxycodone per dose
Ryetalyn being in the RR autoinjectors didn't really make sense. RR is an emergency chem to heal you quickly but at a cost, then ryet is a slow metabolism anti toxin chem. It just doesn't fit the injector's role well. Also, 150u of free ryet from the injectors is a bit weird, considering it is supposed to be lemolocked. 
Oxycodone meanwhile is a strong painkiller that lowers shock and recovers some stamina on addition to body. The "downside" of it is that it metabolizes fast and is generally hard to rely on as your main painkiller. But for an emergency pick me up, it fits the role perfectly. Advanced …
=> Changes Russian Red Autoinjector Mix

code/modules/projectiles/ammo_datums.dm
Apparently this broke ages ago and nobody noticed, sticky spits now spit thin sticky resin rather than sticky resin.
Thin sticky resin mostly existed to be spit out, so its kinda weird it got changed by accident by BM.
:cl:
fix: Sticky resin now spits out thin sticky resin again rather than normal sticky resin.
/:cl:
=> Sticky spit now spits thin sticky resin again

code/modules/projectiles/guns/specialist.dm
Smart minigun now has superior handing statistics than before.
The windup has been made the same as the req minigun at .4 rather than .7.
It now has had its slowdown reduced by like, 20%~ from 1.5 to 1.2. at 1.5 it was incredibly awful. 1.2 is the same as the GPMG.
SG-85 damage on paper is fine, but the handling stats for it are all incredibly bad for it, this ideally should make it a more viable choice as a support weapon.
:cl:
balance: SG-85 now has 20%~ less slowdown when wielded, and has identical windup to req minigun.
/:cl:
=> Smart minigun now has reduced windup/slowdown

code/modules/mob/living/carbon/xenomorph/update_icons.dm
Basically it gets deleted in the xeno's `Destroy`, but then when the mob is taken out of ssmobs processing further up the call stack it calls `ExtinguishMob` which calls this which causes a runtime.
`Runtime in code/modules/mob/living/carbon/xenomorph/update_icons.dm, line 97: Cannot modify null.icon_state.`
Runtime uncool.
:cl:
fix: Fixed a fire overlay runtime
/:cl:
=> Fix a fire overlay runtime

code/game/objects/machinery/mortar.dm
MLRS can now be loaded directly from box of rockets
This makes reloading much easier for MLRS operators who would normally need to manually remove and load all 16 rockets.
https://streamable.com/6tavll
:cl:
qol: MLRS now can be loaded directly from it's respective rocket storage boxes by interacting with it with the box in hand.
/:cl:
=> MLRS Box QOL

code/game/objects/structures/xeno.dm
Recent quickbuild PR completely removed this check.
Var may be dirty but it's probably the best way here since I can't really typecache refundable structures due to the way attack_alien works.
Unintended bad.
:cl:
fix: Thin sticky resin once more doesn't refund points
/:cl:
=> Thin sticky resin doesn't refund build points

code/game/objects/items/explosives/bombvest.dm
Updates description of tactical explosive vest in that it cannot be used with riot shields from the marine vendor. This should be reflected in the item description.
This is not as the explosive vest is a shitpost item. But neither is obfuscation of features.
:cl:
fix: Added the part that the description of the explosive vest that says you cannot use strapped on shields. 
/:cl:
Tested locally.
=> Explosive Vest description update in regards to riot shields

code/datums/status_effects/debuffs.dm
If you started the do_after and the debuff ran out in the meantime it'd end up a runtime. Not cool.
`Runtime in code/datums/status_effects/debuffs.dm, line 528: Cannot execute null.balloon alert().`
Runtime bad.
:cl:
fix: Fixed an intoxication status effect runtime
/:cl:
=> Fixes an intoxication status effect runtime

code/modules/projectiles/gun_attachables.dm
Turns out you could exploit to have an unslashable, invisible flashlight attached to your gun. Not cool.
Exploit bad.
:cl:
fix: Fixed ghost rail flashlight
/:cl:
=> Fixes ghost rail flashlight

code/modules/mob/living/carbon/human/species.dm
Okay so this is a doozy. Apparently the `/datum/species/old_species` counted as a brand new species definition, so when the global list of all species did `subtypesof(/datum/species)` this "species" got added to the list which then didn't have a name, so the key in the assoc list was null, so when you made a new character and it looked for an entry under the null key it picked this and you'd end up with an invalid species selected in your prefs which fucked character editing because it's not a real species datum. Guh. 
Fixes #13343
Bug bad.
:cl:
fix: Fixed new character slots/characters being uneditable in prefs
/:cl:
=> Fixes new character slots being uneditable (minus species)

code/modules/shuttle/marine_dropship.dm
Basically if you did the manual hijack from all sides locked and the alamo was igniting when you finished the alamo would end up hijack locked shipside, meaning you'd be unable to call it down for the duration. Made it so it only unlocks doors and disables AI door control instead (if the alamo is igniting when you finish the do_after).
Added disabling AI door control to touching the console too.
Bug bad.
:cl:
balance: AI loses door control of alamo when xenos touch the alamo console
fix: Alamo should no longer get locked shipside if your manual hijack ends just as the alamo is taking off
/:cl:
=> The alamo doesn't get locked as it is taking off if manually hijacked

code/modules/clothing/modular_armor/attachments/storage.dm
Fixes a grammar mistake.
It isn't, this is actually the start of a power creep for the general storage module (SOM) that would eventually allow you to store the nuke inside the module. 
:cl:
spellcheck: Fix grammar mistake in SOM general armor storage module
/:cl:
=> SOM General Storage Grammar

code/modules/mob/living/say.dm
So basically hivemind and silicon/holopad chats are now auto capitalized and have a dot at the end like radio.
This being standard with all the channels is good because standardization. Might also make people stop treating these slightly less like OOC channels hopefully.
:cl:
add: Hivemind and silicon chat now have automatic capitalization and end of dot punctuation
/:cl:
=> Gives non speech channels first letter uppercase + automatic dot

code/modules/projectiles/gun_helpers.dm
Fix some aimmode issues with deployable weapons.
You can no longer stack multiple aim mode toggles to curse yourself with stacked penalties for the rest of the game.
You can no longer move off the gun and still toggle aim mode to also curse yourself forever.
Cleaned up some bitfield checks because CHECK_BITFIELD is lame and just takes up more space.
Bug fixes good.
:cl:
fix: fixed some deployable weapon bugs that could curse you to eternal aim mode penalties
/:cl:
=> fix deployable aim mode bugs

code/game/objects/items/stacks/tiles/tile_types.dm, code/game/turfs/floor_types.dm
Couple of flooring fixes.
Fixes incorrect damaged wood tile states and carpet.
Fixes welding floor tiles having a couple of checks in the wrong order and not doing an eye check.
Fixes #13028
Fixes good.
:cl:
fix: fixed damaged wood or carpet tiles not showing up correctly
fix: Fixed welding floor tiles not doing eye damage to the unprotected
/:cl:
=> flooring fixes

code/datums/weather/weather_types/acid_rain.dm
Title.
Players expect siren to play in acid rain when they are in LV-624, but they do not expect siren to play in normal rain.
Pavlov approves.
:cl:
fix: siren playing in normal rain in LV-624
/:cl:
=> fix siren playing in normal rain

code/__DEFINES/xeno.dm, code/datums/actions/observer_action.dm, code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Smart Minions is enabled for by default.  
From my experience, Smart Minions is almost never purchased, and minion spawners are not always purchased. Even when Smart Minions is purchased, it may be ignored or overlooked in favor of spawning a larva, potentially wasting its purchase. I don't think it is such a huge advantage over AI-controlled minions, since they are slightly robust, and even if it is better than some of the AI's shortcomings, such as getting stuck, these aren't intended anyway.
:cl: Tanker
balance: Smart Minions is now enabled by default.
/:cl:
=> Smart Minions by default

tools/tts/tts/Dockerfile
It just kept erroring out with this because it was missing `pydub`
The tts docker working for local testing is nice.
:cl:
fix: Fixed the TTS docker not working properly
/:cl:
=> Adds missing dependency to TTS docker

code/game/objects/machinery/mortar.dm
Partically fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/12972 by extending the time before impact hud returns camera to deployable
:cl:
add: Impact Hud now stays at the impact site for slightly longer.
/:cl:
=> Impact Hud lingers longer

code/game/objects/items/binoculars.dm, code/game/objects/machinery/deployable.dm, code/game/objects/machinery/mortar.dm
Mortars now automatically link to saved binoculars and keep track of them in item state as well as structure state
Massive QOL, plus bug fix, plus I need street credit with the engineers
:cl:
qol: mortars now automatically set save binoculars to them, linking with saved binoculars, and keeping track of them, no more need to use a binocular on a mortar before firing.
/:cl:
=> mortars now automatically link and save deployed binoculars

code/modules/projectiles/gun_helpers.dm, code/modules/projectiles/gun_system.dm
Focus order now reduces the aimmode fire rate penalty by 50%, the same as a RDS or bipod. (This is still limited to 0, you can't have all 3 and shoot faster!)
The focus order is pretty bad currently. It currently boosts your accurate which is a pretty limited benefit, and removes the delay to toggling aim mode. This is compared to a 20% or 30% damage damage reduction from hold order, or speed boost from move order, which are both extremely powerful.
This change means you're actively making aimmode stronger for your team. Still worse than the other two orders? Yeah almost certainly, but at least it has some more actual use now.
:cl:
balance: The focus order now reduces the fire rate penalty of aimmode
/:cl:
=> Focus order buff

code/__DEFINES/modular_armor.dm
Four new armor colors.
GREYISH_TURQUOISE
STORM
SILVER
WOOD
Three new visor colors.
With the power of hyperscale, we can have more colors!
:cl:
add: 4 new armor color and 3 new visor colors
/:cl:
=> more armor and visor colors & make visor in color organization

code/datums/mind.dm, code/game/objects/items/radio/headset.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/living.dm
Ghosting out of a living body not show as DNR.
Going DNR after death properly shows this.
Fixed taking over a living body still being marked as DNR in some cases
At some point mind.current was changed so that ghosts would get set as current instead of the actual former body, so the body is only connected via weakref.
I'm not entirely sure if its better for current to be typecast as just mob instead of mob/living or not (there are procs that assume its living, and other code that assumes it can be a ghost), but that's out of scope of this PR.
Bug fixes good.
:cl:
fix: fixed some DNR bugs
/:cl:
=> Fix some DNR bugs

code/modules/projectiles/guns/smgs.dm
Changes -
- Has gained all the unbarreled gun attachments (masterkey/PP/masterkey/mini/UGL)
- Has rifle level akimbo maluses.
- Has carbine-level falloff damage multiplier. (0.9)
- Has .4 akimbo fire delay multiplier.
Makes the SMG-25 more unique in its class, its basically a rifle with the damage profile and handling of an SMG now.
:cl:
balance: SMG-25 can now fit underbarreled guns.
balance: SMG-25 and its elite version now have higher akimbo maluses, and have less damage falloff over distance.
/:cl:
=> SMG-25 changes

code/datums/jobs/job/fallen.dm, code/modules/mob/dead/observer/observer.dm
First one addresses various runtimes where it'd try to read the reagents of the deleting mob, which wouldn't exist because it's being deleted. No good.
Other issue is closing the valhalla join menu would open the marine job choice menu, no good.
Runtime bad and unintended behaviour bad.
:cl:
fix: Fixes various ghostize runtimes
fix: Fixed closing the valhalla join menu opening the marine job choice menu
/:cl:
=> Fixes various valhalla/ghostize runtimes + valhalla menu being janky

code/modules/power/fusion_engine.dm
Examine procs should always return a list, no TRUE/FALSE
Runtime bad.
:cl:
fix: Fixed fusion engine examine runtime
/:cl:
=> Fixes fusion engine examine runtime

code/controllers/subsystem/tts.dm
Would runtime because this SS wouldn't have these vars because it didn't init if we didn't have this config entry.
Runtime bad.
:cl:
fix: Fixed TTS stat panel runtime
/:cl:
=> Fixes TTS stat panel runtime

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Remove 5 miners that are near LZ in Prison Station.
Too close to FOB. While marines fight in 3 tiles corridors, some good engineers can secure easy miners near the safety of FOB. 
:cl:
balance: Remove 5 miners that are near LZ in Prison Station.
/:cl:
=> remove easy miners near LZ in prison station

code/__DEFINES/mode.dm, code/_globalvars/admin.dm, code/datums/gamemodes/_game_mode.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm
\+ unused define deletion
Not using the other enter_allowed global because it get's set to true/false depending on if SD is on which is very unreliable.
Latejoin larvas spawned groundside which wasn't ideal on hijack
:cl:
fix: Fixed larvas being able to spawn groundside via latejoin post hijack
/:cl:
=> Disallow xenos from latejoining post hijack

code/modules/screen_alert/command_alert.dm
https://github.com/tgstation/TerraGov-Marine-Corps/assets/6610922/c45c2276-7868-40db-ba72-cce144cd43ca
Xenomorph's hive message appears in the visual UI and the text UI, but the marine's send order only appear in the visual UI. This PR adds that marines receiving sent order can read it in their text UI for better coordination and utilization of the highlight function.
:cl:
add: Send order is added in text ui so that marines can read
/:cl:
=> Marines can read send order in text ui

code/game/objects/items/cocoon.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm
This PR adds cloneloss while you stay inside the cocoon. For the duration of the cocoon you get a total of 40, Double of psydrain.
Finally adds cloneloss to cocoon which I was originally gonna do last year or so when I added it to psydrain but I couldn't wrap my head around process()
Now cocoon isn't just straight up a worse option than psydrain unless the marine is garuanteed to never be rescued, now it _might_ be worth it to cocoon someone relatively close to the front lines. A freshly rescued marine might not have any impactful cloneloss, While a fully cocooned but still rescued marine (cocoon resets defib timer if you didn't know) has 40 cloneloss, or double that of psydrain.
:cl:
add: Adds cloneloss to cocoon.
/:cl:
=> Adds cloneloss to marines over time while they are cocooned

code/__DEFINES/dcs/signals.dm, code/datums/components/anti_juggling.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/projectiles/gun_system.dm, tgmc.dme
Adds a component to prevent the juggling of weapons to bypass firing rate limitations. Yes this is extremely silly and a mob var could just do the trick but hey ho :)
Juggling bad.
:cl:
balance: Added a component that prevents the juggling of weapons to bypass firing rate limitations
/:cl:
=> Anti-juggling component

config/maps.txt, config/shipmaps.txt
These are old and shouldn't exist anymore. Causes warnings.
Warnings not cool.
:cl:
config: Removed old map definitions in default config
/:cl:
=> Removes old map definitions in default config

code/game/say.dm
If a role has no paygrade, it leaves behind a space in chat before a character's name when sending a message. This PR just appends the space after a rank on the condition that a character actually has one.
It is quite annoying.
:cl:
fix: Remove empty space before character name if they don't have a rank.
/:cl:
=> Fix leading space in chat when no paygrade

code/modules/projectiles/gun_system.dm
Apparently I am the only one who uses chambering messages so no one noticed this oopsie.
Display the proper message.
:cl:
fix: Chamber closing message instead of the opening message is shown when closing the reciever.
/:cl:
=> Fix reciever closing message

code/controllers/subsystem/vote.dm, tgui/packages/tgui/interfaces/Vote.js
https://github.com/tgstation/TerraGov-Marine-Corps/assets/64715958/63851e51-4d43-4780-8c79-2a2512e1cf05
Eliminate indiscriminate voters blindly bandwagoning for what ever map happens to be listed first in the shared shuffled choice list. Looking at you Gelida.
:cl:
add: Added per client vote choice randomization.
/:cl:
=> Add per client vote choice randomization 

code/game/objects/structures/girders.dm
Yet another funny modular/turf bug.
Building walls will no longer mess with the baseturfs in odd ways.
This also in general means building walls will no longer delete what's under them. i.e. a wall on sand will still have sand under it.
Bug fix good.
:cl:
fix: fixed a bug with human built walls in modular map errors
/:cl:
=> Wall fix for modulars

code/modules/projectiles/guns/smgs.dm, code/modules/projectiles/magazines/smgs.dm
Changes
- Fire delay dropped to .1 (+)
- Drum magazine maluses for wield delay removed, reduced slowdown from .3 to .2 (+)
- Removed autoburst entirely. (-)
- Reworked to use scatter buildup. It scatters a lot even on short bursts, though.
Gives the PPsh a gimmick beyond being a trolling autoburst gun which is an OLD holdover from long ago when we had no full auto. The gun is now a dedicated shock weapon meant for CQC engagements, its high scatter makes it really bad beyond mid range...
..I mean, you could also bipod it and use it as a dollar store MG, I guess?? I don't know why you would.. but the option is there.
:cl:
balance: PPsh rebalanced, removed autoburst, fires faster, it now builds up scatter as it fires.
/:cl:
=> PPsh changes

code/game/objects/structures/barricade.dm
Fix a funny with barbed wire blocking movement even if the cade is open.
Bug fix good.
:cl:
fix: Barb wired plasteel cades are no longer one way doors
/:cl:
=> Plasteel cade fix

code/modules/power/groundmap_geothermal.dm
Xeno valhalla has corrupted generators which cause thousands of runtimes if a groundside map has no thermal generators. This adds a check where if the groundside generators list is empty, just stop the processing of corrupted generators. Also moves the addition of the generator to the list above the corruption proc in initialization otherwise corrupted generators at roundstart would shut themselves down before adding themselves to the list.
Annoying runtime spam bad, bug fix good.
:cl:
fix: Corrupted thermal generators check if there actually are any groundside for psy point generation.
/:cl:
=> Fix division by 0 in process() of corrupted thermal generators

code/game/objects/items/stacks/tiles/tile_types.dm
Fixes tad tiles getting left behind when plating is retiled.
Another reason why changeturf is lame.
Fix good.
:cl:
fix: fixed an issue with tad leaving behind turfs
/:cl:
=> Tad tile fix

code/__DEFINES/supply.dm, code/modules/reqs/supplypacks.dm
Disposable RPGs now cost 10(0) points rather than 5(0) points.
SADAR has been slashed from 1200 to 800 points, for reference B18 is 1200 and minigun is 800.
All sadar rockets are 10 points cheaper.
SADAR has lost a lot of its luster since losing miniscope and requiring full wielding, it can no longer really offscreen kill people reliabily and so its pointcost is very unwarranted.
DRPGs have needed a pointcost nerf for literally years by this point, they're incredibly efficient point for payload.
:cl:
balance: Disposable RPGs are now 100 points from 50.
balance: SADAR now costs 400 points less, SADAR rockets cost 10 points less across the board.
/:cl:
=> SADAR and its rockets are now cheaper across the board, disposables cost more

code/game/objects/machinery/overwatch.dm, code/modules/shuttle/cas_plane.dm, code/modules/shuttle/navigation_computer.dm
So it turns out caves (not deep caves) allowed CAS/tad/OB (but not railgun because :^)
This is uh, not ideal.
Tad half way into caves is bad.
:cl:
fix: Shallow caves are no longer enterable by air support or OB
/:cl:
=> Cave fixes

code/modules/projectiles/gun_system.dm
Funny bug. Gun would keep shooting even when in your hands and while undeploying.
Bug bad.
:cl:
fix: Fixed BAS (and probably other sentries) not losing target when undeployed
/:cl:
=> Fixes BAS (and probably other sentries) not losing target when undeployed

code/game/objects/machinery/nuclearbomb.dm
Title. Marines could just reenable the nuke.
Bug bad.
:cl:
fix: Fixed nuke being activable post hijack
/:cl:
=> Fix nuke being activable post hijack

code/__DEFINES/loadout.dm, code/game/objects/machinery/vending/new_marine_vendors.dm, code/modules/projectiles/guns/pistols.dm
Allows SG's to get a free holster and SP-13 smart pistol with two mags as a sidearm. Any further ammo is 2 points per or from req. 
Also allows the smart pistol to be one handed, stats adjusted to make it cause recoil even with gryo. adjusted scatter as well.
it's a smart pistol, smart gunners should have access to a specific side arm for them to use, provides a good sidearm to go with their main guns while not being overpowering.
Adjustments to the gun itself will out it to be whipped out in emergency's, but still scatters and recoils. 
:cl:
add: SP-13 and ammo to smartgunner prep vendor
balance: SP-13 can be one handed, recoil of 2 and scatter of 7 when wielded.
/:cl:
=> smart pistol now avaliable to smartgunners plus balance changes

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/shotguns.dm
Reworks Martini from a meme with no purpose beyond FF and triple juggle memes to something resembling a gun with a gimmick
- Ammo no longer has minimum range
- Sundering and staggerstun are entirely removed from the ammo.
- It now does 10 seconds of Shatter on hit.
- It now has aim mode, with an incredibly fast aiming time.
Martini now has some level of niche in the marine arsenal, it breaks through a large chunk of armor to allow teammates to follow up.
I removed the minimum range since it doesn't really feel like it fits here.
:cl:
balance: Martini rework, no longer has staggerstun nor minimum range. It now deals the shattering effect on hit instead.
/:cl:
=> Martini Rework MK.IV - Revenge of the Tea

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/specialist.dm
Muh xope etc.
100 sunder weapons are dumb, they'll all go in the bin eventually.
Reduced sunder of HVAP from 100 to 50, and for the IFF one 50 to 20 (but increased its damage)
This is still very significant sunder, it just means a p90 won't completely delete you after the fact.
Also made it fully wielded fire only.
100 to 0 sunder is bad gameplay.
:cl:
balance: reduced sunder of HVAP and IFF railgun rounds
balance: railgun must be fully wielded to fire
/:cl:
=> Railgun nerfs

code/game/atoms_movable.dm
Changes throw to use get_dist_euclide instead of turfs crossed.
This means throwing diagonally will no longer comically reduce your effective range.
For a 7 throw range nade, we go from this:
To this:
Diagonal throwing less jank.
:cl:
balance: Made throwing perform more accurately in diagonal directions
/:cl:
=> Diagonal throw improvement

code/datums/gamemodes/infestation.dm
Makes the nuke setFireLoss instead of adjusting, setFireLoss cares about armor, and that causes marines to often survive the nuke, which is no good at all.
If fucking monsters that are 2 times or more size of a marine get obliterated by the nuke, why can marines barely just survive it?
Tempting also to make it gib, but that's far more performance intensive for humans than xenos methinks.
:cl:
fix: Marines will no longer survive nuke by the sheer strength of their unga.
/:cl:
=> Fixes marines surviving nuke

code/modules/projectiles/guns/shotguns.dm
Juggling is dead. One handed combat shotgun is back.
Juggling is dead, and the TGMC bought better stocks for the combat shotguns again.
:cl:
balance: You can now fire combat shotguns one handed again.
/:cl:
=> Combat shotgun can fire one handed again

code/datums/components/anti_juggling.dm
Underbarrel weapons no longer get caught by the anti-juggle component.
This was making underbarrels next tro unusable on low rate of fire weapons (most notably the flamer).
floride staring the burning man for 2 seconds before you can extinguish them is bad.
:cl:
fix: Underbarrel weapons no longer get delayed by the anti-juggle component
/:cl:
=> Underbarrel weapon fix

code/__DEFINES/loadout.dm
You can only have one essential item from a vendor, that is bad, so I put it in non essential so if SG's want the pistol they don't delete their goggles.
SG's having their funky goggles is kinda the point along with their gun, unintentional so here's a fix
:cl:
fix: SG pistol no longer locks you out of your goggles
/:cl:
=> loadout fix

code/__HELPERS/spatial_info.dm
Ports:
- https://github.com/DaedalusDock/daedalusdock/pull/421
One of the hottest procs in the game. The way it works is it uses the spatial grid to grab all hearers in a given range. Then, it assigns mobs called ears to every turf that contains a hearer. Then, it uses view() to determine who should actually hear the message based on sight. 
There's a pretty simple optimization here, given to us by Dantom back in the dark ages. `hearers()`. `hearers()` is a *very* fast proc that returns all mobs in view, ignoring darkness. We can't replace Ears with this entirely, because SS13/TGMC have objects that need to be aware of hearing, like Radios. But this is still a massive improvement.
Benchmarked using Lohikar's closed-source benchmarking tools. Left-to-right:  Average Iterations, Harmonic …
=> [should probably TM] Macro optimizes get_hearers_in_view()

code/game/objects/machinery/mortar.dm
Adds barricade level armor to mortars. 
Oh my lord I have never wanted to murder a marine as much as when they destroy my mortar. This PR would make it so mortars are harder for marines to kill, but that they still take damage. Also Lumi approved.
:cl:
balance: TA-50 mortar now has 400 effective health against marines, because it has 50 laser, bullet, and energy armor plus other ones on 200 health, with the howitzer and MLRS also having 2x increases against marines. 
/:cl:
=> adds barricade level armor to mortars

code/datums/gamemodes/infestation.dm
Please don't be dumb like me and be too lazy to test your 1 liner PR.
Makes the nuke call death so you *definetely* cannot survive the nuke
How does one revive from a literal nuclear explosion, or simply survive it's blast with one's mortal body?
:cl:
fix: The nuclear explosion will actually, properly, goddamn, kill you, instead of just singing you slightly
/:cl:
=> Makes the nuke call death() and deal more damage

code/__DEFINES/loadout.dm, code/game/objects/machinery/vending/new_marine_vendors.dm
I did a dumb on the last fix and instead broke it further. this will add the KTLD goggles to the bundle so you choose to just get the goggles or the pistol with goggles instead of one or the other
infinite SG pistols is bad
:cl:
fix: no more infinite SG pistols, now you can get goggles with them
/:cl:
=> SG_pistol fix for real this time

code/modules/clothing/suits/storage.dm
Some suits are normal sized items, which meant they can fit inside their own storage.
Exploit bad
:cl:
fix: fixed a storage bug with some misc suits
/:cl:
=> Storage exploit fix

code/datums/quick_load_outfits.dm, code/modules/projectiles/guns/mounted.dm, code/modules/projectiles/magazines/mounted.dm
Decreased MMG aimmode penalty from 0.1 to 0.05 seconds
Increased mag size from 100 to 150 rounds.
Decreased damage falloff from 0.5 to 0.25.
Can fit a railscope
Some minor improvements to make the MMG have a bit more use in light of current MG-60 performance.
Also related, added a BC to the MMG HvH loadout, so it can just rip people apart at long range with very fast projectiles and essentially no falloff.
When the MG-60 was buffed, the MMG was made somewhat obsolete due to being extremely similar in performance but requiring deployment to use.
These changes make a scoped MMG a better aim mode gun than a scoped MG-60, have a more notable advantage at long range, and have generally better ammo economy.
:cl:
balance: Improved MG-27 aimmode penalty, ammo per mag, and damage falloff. Can now …
=> MG-27 improvements

_maps/shuttles/tgs_bigbury.dmm, _maps/shuttles/tgs_canterbury.dmm, code/__DEFINES/factions.dm, code/__DEFINES/loadout.dm, code/game/objects/machinery/vending/loadout_vendor.dm, code/game/objects/machinery/vending/marine_vending.dm
Title. 
So you can't get stuff the crash weapons vendor doesn't have thru the loadout vendor.
:cl:
fix: Crash vendor doesn't pull from shipside weapons vendor anymore
/:cl:
=> Crash vendor doesn't pull from shipside weapons vendor

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
This adds a screen effect for endure if you fall below 0 HP while it's active. The effect is copied from gorger's feast ability.
The HP bar has very poor clarity and you can't spare the time to look at chat to see if you're in crit yet.
:cl:
add: Ravager's Endure now has a screen effect when you have below critical HP in endure.
/:cl:
=> Ravager endure crit effect

code/__HELPERS/_lists.dm, code/controllers/subsystem/server_maint.dm
\+ deletes an unused helper and makes `listclearnulls` actually return TRUE/FALSE so nulls in global lists actually get logged.
Nulls in this list cause issues like completely breaking emotes. It's not really feasible to track down why there are nulls since they are most likely the results of harddels.
:cl:
fix: Fixed emotes breaking at random
/:cl:
=> Adds the dead mob list to the server maint SS

code/controllers/subsystem/minimaps.dm
Basically going inside lockers, pipes, etc was fucky because your xyz vars would all get set to 0 which would result on you disappearing on the map. (it also caused runtimes)
Solved this by just `get_turf`ing the target, so the turf is tracked instead.
Runtime bad, more accurate minimap good.
:cl:
fix: You don't disappear on minimap anymore if you go inside an object like a locker or ventcrawl
/:cl:
=> Fixes minimap not tracking mobs inside objects properly

code/__HELPERS/unsorted.dm, code/modules/projectiles/ammo_datums.dm
Made SOM cluster nades and psyblast properly hit things as intended.
Not sure if the proc they used changed due to the spatial port, or if I just incorrectly used it a year ago.
They now use the cone proc to accurately find turfs they can actually hit.
Also made bomblets hit objects again.
Psylance now correctly staggerslows NON xenos instead of ONLY xenos. Whoops.
Finally, made the cone proc include the central turf by default (due to the mysteries of get_dist, this is interpreted as a distance of -1 however, as added to the autodoc).
Working code good.
:cl:
fix: SOM cluster grenades and warlock psyblast has more accurate code for what their AOE's will hit
fix: Psylance no longer staggerslows xenos instead of humans
balance: SOM cluster grenades hit objects again, instead of just mobs
=> Ammo fixes

code/datums/status_effects/status_effect.dm
Fixes an issue that could cause certain status effects to get stuck on mobs.
In particular this fixes it for the shatter effect, but also fixes it for dead mobs getting particles stuck.
Also removes some dead code and puts in some proper autodoc where it used to be comments.
Fix good.
Autodoc good.
??? code ???
:cl:
fix: Fixed status effects sometimes getting stuck on living or dead mobs
/:cl:
=> Status effect fix

code/modules/mob/living/carbon/human/human_defense.dm
Head stuns correctly apply a longer stun than chest stuns.
Head stuns (when humans donk humans) are supposed to be longer lasting than chest stuns, at the cost of being harder to land.
It used a different proc from chest stuns however, which due to shittery relies on a multiplier, meaning it was actually significantly shorter than chest stuns, so simply worse.
Reduced it down to 10 as 16 would be giga high, but again keep in mind the duration is modified by armour, and does not consider AP, unlike stun CHANCE.
Looks like I inadvertantly nerfed this back when I refactored armour.
Bug fix
:cl:
fix: HvH - Fixed melee head stuns being far shorter than intended
/:cl:
=> Fix head stuns

code/modules/projectiles/guns/mounted.dm, code/modules/projectiles/mounted.dm
What is says on the tin.
Mounted guns are no longer magically nondense when mounted.
This had the incredibly negative outcome of making crushers (previously the strongest counter to a mounted gun) not only entirely ineffective against mounted weapons, but it was actually almost guaranteed suicide to charge one as they'd act as one way doors.
Guns are normal objects to they have coverage like everything else. So being dense still means you can shoot the gunner (although TAT/AA gun have good coverage due to their shields), but now you can once again more easily destroy the guns 
themselves.
Closes #12762
Crushers can actually crush mounted guns again instead of just suiciding.
Easier to actually shoot a mounted gun.
:cl:
balance: Mounted guns are dense when mounted again. Crushers rejoice …
=> Mounted guns are dense again

code/game/atoms_movable.dm
Removes a bunch of dead code bloating up throw_at.
From testing I am 99.99% sure it literally never does anything under any circumstance other than some edge cases where it does bad things like trigger multiple throw impacts, as all the stuff this supposedly does is handled in bump.
Dead/buggy code bad.
:cl:
code: Removed some dead code out of throw code
/:cl:
=> Purges some dead throw code

code/modules/projectiles/guns/mounted.dm
Mounted guns had bullet armour but no laser or energy armour.
Also a few had 100 bullet armour because ???
Consistant stats.
:cl:
balance: Mounted guns have normalised bullet, laser and energy armor
/:cl:
=> Normalise mounted gun armour

code/__DEFINES/dcs/signals.dm, code/datums/keybinding/xeno.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Ability that opens up a minimap, then polls for a click on the map and attempts to teleport you there. All standard hivemind teleport restrictions apply, so you need weeds to be able to teleport still. Same delay to the teleport as with double clicking somewhere normally as a hivemind.
Hivemind needs more stuff. This should help the recon side of it.
:cl:
add: Added a teleport to location on map ability for hivemind
/:cl:
=> Adds an ability to hivemind that lets it select a location to teleport to on minimap

code/modules/mob/mob_movement.dm
Proper fix for the mob throw bug.
Throwing past mobs has different checks from throwing past other stuff, which meant not dense items would go through mobs.
Throws working properly is good.
:cl:
fix: fixed an issue with throwing past mobs
/:cl:
=> Proper mob throw fix

code/game/objects/machinery/vending/marine_vending.dm
Read title.
Seems like an oversight given all the other harvester weapons are in Valhalla and Crash. If I need to remove them from crash for whatever reason (I really don't see why I would need to), then I'll make the necessary edits.
:cl:
add: Harvester Knives are now in your local Valhalla and Crash vendors.
/:cl:
=> Adds the Harvester Knife to Valhalla and Crash

code/_onclick/item_attack.dm
:cl:
fix: fixed "You grab the HE orbital warhead with the HE orbital warhead."
/:cl:
=> Fix inaccurate powerloader message

code/game/objects/machinery/vending/vending.dm, code/game/objects/objs.dm, code/game/objects/structures/barricade.dm, code/game/objects/structures/window_frame.dm
Mainly targetted at HvH.
Improved the quality of cover of several objects.
**Barricades**
Both metal and plasteel barricades now have starting bullet/laser/energy armour now, and the melee armour addon now boosts laser and energy armour (it already buffed bullet armour). Normalised the deployable shield armour.
**Windowframes**
Have good armour against bullet/laser/energy, as they're basically just short walls. Unchanged against melee/acid.
Windowframes used to be much stronger overall, but were nerfed to make them easier to clear for xeno movement. Now we have jumping, that's really not an issue anymore, so this makes them into durable but less reliable cover compared to barricades.
**Vending machines**
Vending machines have low armour and slightly higher coverage, making them more …
=> Cover buffs

_maps/map_files/generic/Admin_Level.dmm, code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/machinery/vending/vending_types.dm, code/modules/reagents/machinery/chem_master.dm, code/modules/reagents/machinery/reagentgrinder.dm
Makes the engi-vend, youtool, chem master and chem grinder in valhalla have the INDESTRUCTIBLE flag.
So that vendors in the ghost-testing area don't die to explosives.
:cl:
qol: Valhalla vendors are more robust.
/:cl:
=> Makes a few things in valhalla indestructible

code/__DEFINES/loadout.dm
Fixes #13495
:cl:
fix: synth surgical pouch is in the correct vendor category
/:cl:
=> Place the surgical pouch in synth vendor in the correct category

code/game/atoms_movable.dm
Fixes certain throws like defender or ravager charge stopping after hitting one person.
There was a set of breaks that should have been purged in the original pr, as the stop is handled by bump/throw_impact in all cases.
Bug fix good.
:cl:
fix: fixed defender and rav charge stopping after one hit
/:cl:
=> Probably final throw fix

code/modules/projectiles/gun_attachables.dm
Okay, so, way back when, the bipod had a melee malus, which meant it was less effective at bashing.
Once it became foldable, it doesn't actually do that unless it's deployed. So, for the sake of clarity I think removing it would be the right step. Until someone gets a better idea and has the know-how to do it, atleast.
It's misleading, doesn't do a whole lot and even if there was the 'ideal' scenario of being able to PB something while it's deployed. You can still get bump slashed and returned to your normal melee damage.
:cl:
del: Removes the damage malus from the bipod.
/:cl:
=> Removes the melee malus from the bipod.

code/modules/projectiles/gun_attachables.dm
Fixes #12898. This was checking the wrong bitfield and it happened to pass for lasguns because 1<<12 is GUN_AMMO_COUNT_BY_SHOTS_REMAINING
:cl:
fix: Fix scopes not changing direction on lasguns
/:cl:
=> Fix scopes not changing direction on lasguns

_maps/map_files/BigRed_v2/BigRed_v2.dmm, _maps/modularmaps/big_red/bigredatmosvar1.dmm, _maps/modularmaps/big_red/bigredatmosvar2.dmm, _maps/modularmaps/big_red/bigredatmosvar3.dmm, _maps/modularmaps/big_red/bigredatmosvar4.dmm, _maps/modularmaps/big_red/bigredatmosvar5.dmm, _maps/modularmaps/big_red/bigredatmosvar6.dmm, _maps/modularmaps/big_red/bigredcaveswvar1.dmm, _maps/modularmaps/big_red/bigredcaveswvar2.dmm, _maps/modularmaps/big_red/bigredcaveswvar3.dmm, _maps/modularmaps/big_red/bigredcaveswvar4.dmm, _maps/modularmaps/big_red/bigredcaveswvar5.dmm, _maps/modularmaps/big_red/bigredcavevar1.dmm, _maps/modularmaps/big_red/bigredcavevar2.dmm, _maps/modularmaps/big_red/bigredcavevar4.dmm, _maps/modularmaps/big_red/bigredcavevar5.dmm
Title.
RipGrayson have blesssed us with tunnels that I couldn't have code otherwise. It's time for other maps to prespawn tunnels.
:cl:
add: xenomorphs tunnel landmarks in Big Red to help with xenomorphs create manuever around maps
/:cl:
=> add xenomorph tunnel landmarks in Big Red

_maps/map_files/gelida_iv/gelida_iv.dmm
title.
RipGrayson have blesssed us with tunnels that I couldn't have code otherwise. It's time for other maps to prespawn tunnels.
:cl:
add: xenomorphs tunnel landmarks in Gelida to help with xenomorphs create manuever around maps
/:cl:
=> add xenomorph tunnel landmarks in Gelida IV

code/modules/mob/living/carbon/carbon.dm
Our cold, tireless beep boop friends can no longer sleep to magically repair integrity damage.
Unintended mechanic, they're not supposed to be able to sleep off integrity damage.
Also immersion I guess
:cl:
fix: Robots (and synths) no longer sleep
/:cl:
=> Robots can no longer sleep

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
POS has some new areas with strangely bad camera coverage. This PR fixes it
It also moves the hangar shutters button off to somewhere not covered by a sign.
Consistency pass.
:cl:
fix: fixed some areas strangely lacking camera coverage on POS.
/:cl:
=> Fix missing cameras issue, move buttons to POS

code/modules/projectiles/gun_system.dm
Fixed autoburst not properly resetting shots fired between bursts.
Causes a bug or two.
:cl:
fix: Fixed autoburst not correctly resetting shots fired between bursts
/:cl:
=> Minor autoburst bug fix

code/modules/mob/living/carbon/life.dm, code/modules/mob/living/carbon/xenomorph/life.dm
Fixes stagger and slowdown.
So for the last couple of years, humans have recovered from stagger twice as fast as they should.
Xenos on the other hand have recovered from stagger THREE times as fast as they should, on top of recovering from slowdown twice as fast as they should.
Funny copy proc calls.
Yes this means stagger and slow in general will be a lot better, but if they need adjustments thats out of scope of this pr.
Copy paste code when it calls to parent is bad.
soft stuns not working correctly is also not ideal.
:cl:
fix: fixed humans recovering from stagger twice as fast as they should
fix: fixed xenos recovering from stagger three times as fast as they should, and recovering from slowdown twice as fast as they should
/:cl:
=> Fixes stagger and slowdown recovery

code/modules/shuttle/marine_dropship.dm
Fixed being able to throw through certain solid parts of the alamo.
For mysterious, probably CM reasons, the alamo is arbitrarily made out both turfs and structures, with zero way to tell which is which.
The little tail wing flaps at the back can still be thrown over, but the actual chunky tail section/engines/front corners are now impassable to throws.
Unintended behavior
:cl:
fix: You can no longer throw past certain dense parts of the alamo
/:cl:
=> Alamo fixes

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/shuttles/tgs_bigbury.dmm, _maps/shuttles/tgs_canterbury.dmm
adds a robotic cradle to the canterbury
(MO loses their seat but i believe it's fair since the ST north of them also has no seat; nanomed is still present, just on the wall above the table so it's hidden under all the Stuff in the map viewer)
adds a robotic cradle to the bigbury
switches a tile in the PoS medbay out from full color green to side green to retain the cross pattern in the center of the medbay
way for robots to heal cloneloss on crash gamemode
Fixes #13562
:cl:
fix: added the missing robotic cradle to the canterbury and bigbury for robots to heal cloneloss on the crash gamemode
fix: changed a tile out in the PoS medbay to fix the tile design
/:cl:
=> adds cradle to canterbury and bigbury; fixes a tile in PoS medbay

code/game/objects/items/stacks/tiles/tile_types.dm
Fixes #13590. If there were only 4 tiles in the stack it would get qdel'd and get_turf(src) would be null
:cl:
fix: fixed floor tile welding
/:cl:
=> Fix floor tile welding

code/modules/projectiles/guns/shotguns.dm
Slightly increases fire delay on the DB, by 0.15 seconds.
Removes gyro as an attachment.
Reduces recoil to 1 instead of 2 while wielded.
DB as it currently stands is the best vendor weapon due to it's frankly insane DPS with no downside due to it not being hit with the juggle nerf, and the ability to be reloaded very quickly with good keybinds. This keeps it as a burst weapon, but with less accuracy on the farther ranges if you are not running vgrip (which has a tradeoff of wield time) and overall less DPS.
:cl:
balance: Reduces the Double Barrel's firerate, removes gyro as an attachment, reduce base recoil.
/:cl:
=> SH34 (DB) Nerf

code/game/objects/items/storage/storage.dm, code/modules/clothing/modular_armor/attachments/storage.dm, code/modules/clothing/suits/labcoat.dm, code/modules/clothing/suits/storage.dm
Originally this was just going to set the storage name to the armor name but my brain 2 cells continued rubbing. Made a new proc to handle displaying the message so there wouldn't be the headache of maintaining a large copy-pasted proc just so it could have a different message. Pockets are also now their own thing instead of just being a child of the general storage object. Found it weird that it was tied to it since internal suit pockets should not be handled as if they were your normal storage module. They can be balanced separately and such.
It bothered me how if you put an item into your normal looking coat it would say you put it into a "General Purpose Storage module" instead. Less jank is good.
:cl:
code: Suit pockets no longer appear as if they are just bolted-on storage modules. …
=> Remove awkwardness of suit pockets

code/modules/projectiles/sentries.dm
This fixes #13471
This bug makes it possible to cheese sentries by having them target you while you are behind a wall.
:cl:
fix: fixed sentries targeting mobs when they cant actually see and shoot them
/:cl:
=> sentries now need line of sight to actually acquire a target 

code/modules/client/client_procs.dm
Clients will now be marked QDELING while in the process of deleting
It'll fix some runtimes with runechat mainly. Plus it's good to let the gc handle it properly.
:cl:
fix: Client is marked as QDELING properly now
/:cl:
=> Mark client as QDELING

code/game/objects/items/pinpointer.dm
title
:cl:
fix: fixed pinpointer not turning itself off after target is destroyed
/:cl:
=> Fix pinpointer not turning itself off after target is destroyed

code/modules/projectiles/guns/mounted.dm, code/modules/projectiles/guns/rifles.dm
What it says on the tin. They're now both relegated to miniscope.
I added to the MG27 purely because the MG60 had it as well and they're directly comparable. However MG's having sniper tier scopes in general is kinda not ideal.
A: They become better than the higher tier MG's at long range due to the simple fact they can see
B: They kinda invalidate actual sniper rifles (which are already pretty bad).
Also added some missing bayonet options for certain guns.
MG's are more consistant in how they can be used, and don't encroach entirely on sniper rifles.
:cl:
balance: MG27 and MG60 can no longer use rail scopes
/:cl:
=> Kills scope on MG27 and MG60

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm, _maps/map_files/LV624/LV624.dmm, _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm, _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm, _maps/map_files/Research_Outpost/Research_Outpost.dmm, _maps/map_files/icy_caves/icy_caves.dmm, code/game/objects/effects/landmarks/landmarks.dm
Forgot to get this in the civil war pr.
Unused bad.
:cl:
del: fob sentry landmark is gone
/:cl:
=> Fob sentry landmark del

code/game/atoms_movable.dm
Never rely on the z var for anything ever. It's unreliable as fuck because byond nulls it if you're inside an object, it sucks.
Bug bad.
:cl:
fix: Fixed gravity giving infinite stamina
/:cl:
=> Fixes gravity giving infinite stamina

_maps/map_files/Theseus/TGS_Theseus.dmm
Fixes #13597. Moved the crash target y down by 1
:cl:
fix: cic crash doesn't expose space on theseus
/:cl:
=> Fix CIC crash target exposing space on Theseus

code/datums/jobs/job/shipside.dm
Read title.
In the original PR for adding timelock, it was stated:
"These hours are not much too ask if you compare to the griefing power these roles have."
I believe that Bravemole severely underestimated, in this case, the griefing power of PO. This is a grievance as admin due to the amount of ahelps I get about under 10 hour living PO's, throwing entire op's due to the low timelock and not understanding the game properly. This will not solve all of the issue with new PO, it is a game after all, but hopefully new PO's can have more experience.
:cl:
admin:  Gives PO the same timelock as Captain
/:cl:
=> Gives PO the same timelock as Captain

code/modules/projectiles/gun_attachables.dm
Brings the mounted guns' "miniscope" to actual miniscope levels (3 -> 5) and increases by +1 the tadpole mounted/tat scope to keep a significant difference between the two (7 -> 8)
Lumi approved (at least the miniscope one). The issue is, the miniscope and the mounted gun scopes were the same and intended to be: 3 tile zoom range. However, the miniscope got buffed to 5, but the mounted variant got left behind cause no one cares. This means that the MG27, a "lower tier" mounted gun, can outrange the higher tier mounted guns (HSG and MG08 notably) because it can mount the 5-range miniscope instead of using a 3-range legacy scope. Nevermind the other handheld guns that don't have the disadvantage of being fixed in place and being able to be destroyed.
The +1 range to the long scope is so …
=> Mounted gun scope range increase 

code/modules/mob/living/say.dm
Again, `z` is very unreliable. This would give a bad index runtime if the mob speaking was in an object
Runtime bad
:cl:
fix: Fixed say runtime, you should be able to talk from within objects again
/:cl:
=> Fixes say runtime

code/game/objects/items/tools/shovel_tools.dm, code/modules/mob/living/say.dm
Per title. This fixes an issue where null.max_amount would be read instead.
Bug fix good.
:cl: Lewdcifer
fix: Fixed a runtime where shovel tools would read NULL.max_amount.
/:cl:
=> Fixes a runtime associated to shovel tools

code/datums/keybinding/mob.dm, code/modules/mob/mob_defines.dm
See title.
More often than not you want self harm to be off rather than on (looking at melee users), adds an easy keybind if you want it on though. If you already have keybinds set, this won't change it.
:cl:
qol: Adds default keybind for toggling self harms, turns self harm off by default.
/:cl:
=> Self harm toggled off by default, default keybind for self harm toggle

code/game/objects/machinery/vending/marine_vending.dm, code/modules/clothing/modular_armor/modular.dm
cleans up the rownin description
**new:**
```A light armor, if you can even call it that, for marines that want to have agility in exchange for protection. Alt-Click to remove attached items. Use it to toggle the built-in flashlight.```
**old:**
```A light armor, if you can even called it that, for dedicated marines that want to travel light and have agility in exchange of protection. Alt-Click to remove attached items. Use it to toggle the built-in flashlight.```
removes a space before one of the blood vendor phrases
me spell real good
consistency. maybe clarity on the rownin armor.
:cl:
spellcheck: fixed rownin armor description; extra space on one of the blood vendor slogans
/:cl:
=> rownin skeleton desc fixes; remove space in blood vendor phrase

code/game/objects/items/toys/cards.dm
Card hands will no longer runtime and work once more. Problem was caused by .len() conversions a few months back
Fixes good, fun good. I love the fun RP items like cards we have
:cl:
fix: Fixes a runtime regarding cards that was causing them to become invisible, playing cards work once more!
/:cl:
=> Stops playing card hands from magically disappearing

code/modules/mob/living/living.dm
Yeah. Not doing this means status effects keep trying to process despite the owner not existing anymore. Means we get a lot of runtimes.
Runtime bad.
:cl:
code: Status effects get deleted along with their owners
/:cl:
=> Status effects get deleted along with their owners

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Add vents and scrubber in operation room.
Add cryo console near Alamo.
Add where jaeger vendor will be. Keep your eyes out for the future!
All shipside maps have OR with vent and scrubber, and I forgot to add that in PoS.
Cryo console is near Alamo so that marines who want to see what is inside before deployment don't have to run far.
Computer console frame will be replaced by jaeger vendor. It's a nice visual narrative.
:cl:
add: vents and scrubber in PoS operation room.
add: cryo console near PoS Alamo.
add: where jaeger vendor will be for PoS. Keep your eyes out for the future!
/:cl:
=> Small Pillar of Spring Update

code/controllers/subsystem/persistence.dm
Read title.
When about everyone changes from the normal sniper to the SVD when its in seasonal, ya know something is up. It is everything the TL127 wants to be, but better.
:cl:
balance: Removed SVD from the Cold War seasonals.
/:cl:
=> Removes SVD from the Cold War seasonal

code/datums/actions/order_action.dm, code/modules/screen_alert/command_alert.dm
Not sure feedback messages are needed for this, they spam your chat 4x when you re-enter your corpse as well. Could've added a silent argument to /datum/action/innate like /datum/action/xeno_action does but this is the only innate action that has feedback anyway
:cl:
del: removed chat feedback from order actions
/:cl:
=> Remove chat spam from order actions

code/datums/keybinding/mob.dm, code/game/objects/items.dm, code/modules/clothing/modular_armor/attachments/storage.dm
Ghosts can examine with shift+click and open armor storage
:cl:
fix: Fix observers being unable to examine
fix: Fix observers being unable to open armor storage
/:cl:
=> Observe improvements

_maps/map_files/LV624/LV624.dmm, _maps/modularmaps/big_red/bigredofficevar1.dmm, _maps/modularmaps/lv624/newcavevar10.dmm
Read title.
This is what (minus the x'd) LV caves look like, for the most part because muh modulars. I say most because I might have missed a modular, tell me if I did.
Also does a minor fix on the Research Lab area east of LV 2 as there was an unroofed area.
Muh xope. In all seriousness,
With LV already being focused on the cave fight as Xenos cannot contest colony, these miners just enable the Marines to cave fight much easier with less attrition.
:cl:
del: Removed some Platinum Miners on LV.
fix: Fixes LV research lab area not being entirely roofed.
/:cl:
=> Removes (most) easy plats on LV

_maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm, code/game/area/lawankaoutpost.dm
Removes nexus disk spawn
Makes engineering underground
Minor SMES changes (Zack yelled at me that they didn't work, they should now?)
There was a potential of the disks spawns to be a literal straight line to the nuke, this makes it so marines will have to go to the underground lab in order to get all disks; which is a tad ride away from nuke anywho. Breaks up the straight line flow that Lawanka can currently have. Nexus will still be a very good spot for xenos to stage flanks, as it is in the literal center of the map. In addition, tadpole landing in engineering was a bit too funny as it could control all the chokepoints leading into it.
:cl:
balance: Lawanka Outpost; 3 disk spawns, engineering is now underground
/:cl:
=> Lawanka Changes (Version 1)

code/game/objects/items/storage/pouch.dm, code/game/objects/machinery/vending/marine_vending.dm
The field utility pouch had an inaccurate description of what items it can contain, such as map tablets, compasses, and deployable cameras.
This adds several items to the can_hold list, including a compass, Undeployed "Huginn" ROC-58 Observer, hud tablet, minimap tablet, ASRS tablet, megaphone, hand labeller, and deck of cards, as well as papers and clipboard which was in can_hold list of document pouch. This also removes the document pouch from the marine vending machine.
The field utility pouch had a limited amount of can_hold which did not have even items that would not grant any advantage in combat, therefore limiting the viability of using it even as a meme loadout or for roleplay purposes.
I deem the document pouch to have a too niche purpose and bloated the vending machine menu, …
=> More can_hold items for field utility pouch

code/game/objects/machinery/miner.dm
Xenos can no longer left click spam a miner to break it in < half the required time.
I'd call this a bugfix, if miners are intended to be destroyed at the faster rate (of left click spam), then the amount of time it takes to slash it should be reduced.
:cl:
fix: Xenos can no longer spam left click miners to break them faster than normally.
/:cl:
=> Xenos can no longer spam click miners to break them faster

code/game/objects/machinery/miner.dm
Now you can no longer bypass the while loop, slashing miners takes notably longer.
Halves the time to make it a bit quicker, also in particular means its possible to do hit and run attacks on miners to chip it down.
walance
:cl:
balance: Miner slash time reduced to 1.5 seconds per cycle
/:cl:
=> Reduced miner slash time

code/modules/projectiles/ammo_datums.dm
This ammo has a drop_flame() proc which seems to want to drop fire on tiles it hits, but it is never called anywhere.
I'm just gonna copy the flamer code for this so that it actually flames things as intended.
Bugfix
:cl:
fix: AGLS Incendiary ammo drops fire now.
/:cl:
=> Fixes AGLS Incendiary ammo not making fire.

code/game/objects/items/weapons/blades.dm, code/game/objects/items/weapons/twohanded.dm
Vali has the funny strap.
Normal melee weapons have strap now too.
Dropping your unga stick when you take a tumble is bad.
:cl:
balance: Machete and spear now have straps
/:cl:
=> Sword and spear straps

code/datums/quick_load_outfits.dm
Minor tweak giving the minigun man 2 spare ammo boxes so they can brrrt for twice as long.
Also removed some duplicate stuff that snuck into one of the SL loadouts.
More dakka
:cl:
balance: HvH: SG-85 loadout comes with extra ammo
/:cl:
=> SG-85 HvH loadout tweak

code/datums/jobs/job/sectoid.dm, code/modules/projectiles/guns/rifles.dm
Gives sectoid gun innate mag harness.
Fills the sectoid belt with another magazine (It has an empty slot usually)
Sectoids have ammo issues and "oh no I lost my gun and now I'm useless" issues, I feel like this is a reasonable buff.
:cl:
balance: Sectoids have 1 more magazine and innate mag harness for their gun.
/:cl:
=> Small sectoid buff

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
For some reason shaking a lot of tiles in a wide radius causes severe clientside lag in certain cases. Smaller radius seems to work alright though.
Adds checks to the callback procs to make sure owner didn't get deleted (read: gibbed) in the meantime.
Also makes the for loop that makes the nearby people get the funny screenoverlay from super rage use `cheap_get_[humans/xenos]_near`.
Toning down potential clientside lag should be good.
:cl:
fix: Toned down super rage shake radius to help with potential clientside lag
/:cl:
=> Tones down super rage shake radius + tiny refactor

code/datums/emotes.dm
There can be nulls in this list and we should account for that.
Runtime that borks emotes for a time is bad.
:cl:
fix: Fixed a small emote runtime
/:cl:
=> Fixes a small emote runtime

code/modules/mob/living/living_defense.dm
This causes runtimes.
Runtime bad.
:cl:
fix: Fixed adjust_fire_stacks trying to affect qdeleted mobs
/:cl:
=> Fixes `adjust_fire_stacks` trying to affect qdeleted mobs

code/game/objects/machinery/vending/new_marine_vendors.dm
Ghost looking at the UI of these caused runtimes.
Runtime bad.
:cl:
fix: Fixed ghosts causing runtimes by having the specialized vendor UI open
/:cl:
=> Fixes ghosts causing runtimes by having the specialized vendor UI open

code/game/objects/items/bodybag.dm
A tarp being flamered or exploded would cause runtimes because the occupant would be null before the ex and fire acts would kick in.
Runtime bad.
:cl:
fix: Fixed multiple bodybag/tarp runtimes
/:cl:
=> Fixes multiple bodybag/tarp runtimes

code/game/objects/structures/dropship_ammo.dm
Causes deleted objects to try to take damage which causes runtimes.
Runtime bad.
:cl:
fix: Fixed cas gau exploding contents of turfs twice
/:cl:
=> Fixes cas gau exploding contents of turfs twice

code/modules/mob/dead/observer/observer.dm, code/modules/mob/dead/observer/orbit.dm
The signal never got unregistered, so orbiting the same person twice in a row would override the signal with an error.
Also it'd runtime if you pressed the auto observe button without orbiting anyone.
Runtime bad.
:cl:
fix: Fixed some auto observe runtimes
/:cl:
=> Fixes some auto observe runtimes

code/modules/clothing/modular_armor/attachments/storage.dm
Yepo. Overrides unfunny.
Runtime bad.
:cl:
fix: Fixed ghost observing armor not unregistering signals
/:cl:
=> Fixes ghost observing armor not unregistering signals

code/game/objects/machinery/computer/computer.dm
"It is broken" instead of "It is broken and needs to be rebuilt."
You can't rebuild tad computer, this is misleading.
:cl:
spellcheck: change broken computer warning to be a bit less misleading.
/:cl:
=> change broken computer warning to be a bit less misleading.

code/modules/mob/living/living.dm
Makes it so when you press your switch hands button, it will unwield whatever you are holding instead of blocking your input.
Feels smoother, which is a much better player experience.
:cl:
qol: Switching hands unwields.
/:cl:
=> Switching hands while wielding automatically unwields.

code/datums/gamemodes/_game_mode.dm, code/datums/gamemodes/combat_patrol.dm, code/datums/gamemodes/crash.dm, code/datums/gamemodes/infestation.dm, code/datums/gamemodes/nuclear_war.dm
Makes them actually need 5 marines per, so there won't be 14 corpsmen and engi slots on 30 marines.
This is the intended way I'm pretty sure when https://github.com/tgstation/TerraGov-Marine-Corps/pull/13050 was made.
:cl:
fix: Engineer and corpsman slots actually scale properly now
/:cl:
=> Engineer and corpsman slots actually scale properly now

code/modules/ai/ai_behaviors/xeno/xeno_illusion.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Bugfix good and very much overdue.
Mirage illusions now always follow hunter until they find a marine within range ( 5 tiles as of now ).
When that happens, they will stick to them and attack until they die.
bugfix good
:cl:
fix: hunter mirage now works as intended
/:cl:
=> Hunter illusions now work as intended

code/game/objects/items/storage/pouch.dm
This will fix the SOM and ICC pouches going invisible when they are empty.
SOM operatives would appreciate a stealth camouflage but not if it is only applied to their pouches.
:cl:
fix: Fixed SOM and ICC pouches going invisible when they are empty
/:cl:
=> Dynamic sprite revert for SOM and ICC pouches

_maps/map_files/Minerva/TGS_Minerva.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm, code/game/objects/machinery/doors/windowdoor.dm
Read title.
Here is what chem looks like now on the shipmaps:
Since there are still req lines (on PoS, for example), if we ever need chemical request lines they are there; smartfridge only is sort of sad.
:cl:
add: Added chemistry request lines to most shipmaps.
/:cl:
=> Adds chemistry request lines to (most) shipmaps

code/datums/gamemodes/_game_mode.dm, code/datums/gamemodes/extended.dm, code/datums/shuttles.dm, code/game/objects/machinery/computer/dropship_picker.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/holder.dm
Alternative to https://github.com/tgstation/TerraGov-Marine-Corps/pull/13650
This PR allows admins to toggle gimmick tadpoles on and off via a verb in the fun panel.
By default I've only added the restriction to the food tad. The extended game mode by default allows all tadpoles unless the admins manually toggle gimmick tads off again.
This option allows for fun tads without messing up normal rounds. Instead of outright denying or removing gimmick tads, they can stay locked away until admins need or want them for an event.
:cl:
add: Added the ability for admins to toggle gimmick tads
balance: The food tad is now classified as a gimmick tad
balance: Gimmick tads now require admin intervention before they can be selected
/:cl:
=> Allows toggling of gimmick tads

code/game/objects/structures/xeno.dm
In https://github.com/tgstation/TerraGov-Marine-Corps/pull/12642 I kinda messed up the math. This should make the doors have the same amount of effective hp against melee as before.
Yeah this was a mistake on my part.
:cl:
balance: Bring resin door melee armor back down to previous values
/:cl:
=> Bring resin door melee armor back down to previous values

code/datums/jobs/job/marines.dm, code/datums/jobs/job/shipside.dm, code/datums/jobs/job/xenomorph.dm
Changes the description for a job's gamemode on multiple jobs from distress to nuclear war. First time making a pr for this codebase, so let me know if I missed something.
Asked and apparently distress signal isn't in rotation atm, as nuclear war has replaced it. This reflects that in the job descriptions.
:cl:
fix: Fixed jobs listing an unused gamemode in their description as the gamemode they are in.
/:cl:
=> Swaps The Gamemode On Job Descriptions From Distress To Nuclear War

code/controllers/subsystem/job.dm, code/datums/gamemodes/_game_mode.dm, code/datums/gamemodes/crash.dm, code/datums/gamemodes/nuclear_war.dm, code/datums/jobs/job/marines.dm
- Fixed the job scaling check, thanks istype
- Engineers contribute to corpsman slots and vice versa
- Fixed jobs not scaling if nobody readies up
- Fixes engi/corps taking twice as many points as intended
Bug bad. I forgor istype is more strict when comparing types.
:cl:
fix: Fixed jobs not scaling if nobody readies up
fix: Fixed jobs not being scaled properly
/:cl:
=> Fixes jobs not scaling if nobody readies up + fix a thing I broke

code/game/objects/machinery/vending/vending_types.dm
Adds sterilizing spray (100u spray bottle) and ***limited*** amounts of Soap to the vendor.
Nice to keep the Medbay clean, and I made sure the soap is limited to limit grief by slipping people. Good on the conscious to not have to take from Medbay when you want to clean yourself for field surgery, too; even if there is usually some spray bottles there. Soap is already available on the shipmap, just making it more easily accessible to doctors who don't memorize the spawns.
:cl:
add: Added soap and sterilizing spray bottles to the NanotrasenMed Plus
/:cl:
=> Adds cleaning supplies to the NanotrasenMed Plus

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
fixes a single tile's area on magmoor
it had fullbright; which was weird.
:cl:
fix: fixed the area for a single tile in magmoor's security building
/:cl:
=> fixes a tile area on magmoor

code/modules/mob/living/blood.dm
This pr moves blood regen from just happening very slowly (0.5) when you'd lost blood to now regen based on how much nutrition you have.
at 450 nutrition and up (fat) you regen 1 whole blood per life tick (or whatever blood works in).
250 to 450 nutrition (The green zone) You regen 0.5 per blood tick.
0 to 250 (starve zone) You regen 0.1 blood per blood tick.
It made no sense to ALWAYS regen 0.5 blood per tick no matter how much blood you have lost and randomly lose a LOT of nutrition for no tradeoff.
Now you regen blood based on how much food you have in you, which I believe is how it works on all other servers and lets regenning blood not SOLELY rely on a medic shoving iso and nano in you.
:cl:
balance: Natural blood regen now regens in tiers based on how much nutrition you have.
/:cl:
=> Blood regen changes

code/game/objects/structures/xeno.dm
Resin doors will no longer appear closed after being created, when they are actually open.
Bug bad.
:cl:
fix: fixed resin doors appearing closed when they are actuall open, after creation
/:cl:
=> Fix resin door bug

_maps/map_files/Minerva/TGS_Minerva.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm
Ensures all medbays have a map table inside of them
Ensures all medbays have a blood vendor in the main lobby
PoS rechargers now have their own tables
Watching marines is nice for downtime in Medbay, and having the supplies in the lobby when you need them is good as well. Rechargers being under a bunch of stuff in PoS medbay was not ideal, either.
:cl:
qol: All shipside medbays now have a map table.
qol: All shipside medbays now have a blood vendor in the main lobby.
qol: Rechargers in medbay on Pillar of Spring are now more visible.
/:cl:
=> Minor shipside medbay additions

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
stops trailblazers from being taken back to hivemind core
unintended and bug fix
:cl:
fix: Trailblazers no longer teleport to hivemind core with them
/:cl:
=> hivemind fix

code/modules/shuttle/marine_dropship.dm
The front window inherited some funny flags so you could shoot through it/flame through it.
Fixes #13797
P.S. Please someone reorganise tad and alamo structures/turfs, its the most cursed organisation possible with absolutely no rhyme or reason.
bug bad.
:cl:
fix: fixed the front tad window allow fire and projectiles through
/:cl:
=> Fix tad window

_maps/map_files/BigRed_v2/BigRed_v2.dmm
:cl:
del: Remove a bad crash site from Big Red
/:cl:
=> Remove a bad crash site from Big Red

code/modules/projectiles/magazines/rifles.dm
Makes garand ammo weight class small
The garand ammo is fucking massive, despite having like 8 boolet.
This is misery.
:cl:
balance: Garand clips are smaller
/:cl:
=> makes garand clips smaller

code/modules/factory/parts.dm, code/modules/factory/unboxer.dm, code/modules/reqs/supplypacks.dm
This PR did the following, and yes, it is my commit message : 
- Added smoke shells to the factory
- Added some flavor text to make things easier to handle
- Reduced the price of refills from 150 to 120 for HE and INC
- Reduced the price of refills for flare from 150 to 100
- Fixed the flare refills being called HE in the supply computer
Here is the math for HE, flares, and incendiary shells : 
For 10 pts, you get 2 in the req elevator. That's 5 pts per shell. 
For 150 pts, you can get a refill that becomes 30 shells. 150/30 = 5pts per shell. 
The new math for refills is that you start with 120 for HE and INC, meaning you get shells for 4 points each, roughly 20% of discount, without counting possible factory machines, and the bother to actually set it up. Given that tanglefoot shells …
=> Increased Mortar Factory Viability 

code/modules/projectiles/ammo_datums.dm
Probably TM this first.
Scout ammo no longer has a minimum accurate range. It's had this for 6 years but it didn't even work until I fixed the mechanic, and I'm not entirely sure why the scout has it when its explicitly described as a gun that 'can be used at any range'.
Incendiary ammo now pierces mobs. Currently is completely over shadowed by base ammo in general usefulness, and completely overshadowed in terms of fire application by funny rapid fire incend xray laser.
High impact rounds no longer pierce mobs. They have slightly higher damage, lower AP and better sunder, but most significantly do knockback on top of the current slowdown. This makes it quite a strong soft CC tool against smaller xenos, but it'll need a TM to see if it's too much.
Also removed the 0% shrap chance. No real …
=> Scout ammo changes

code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/machinery/vending/vending_types.dm, code/modules/clothing/under/jobs/medsci.dm
Adds the MD's clothes into the vendor. In addition, fixes the medical scrub names as the different colors were the same name.
Being able to get these from loadout vendors is nice, and they are not gamebreaking in any fashion; they can help you with surgery but you can already find them on the map either way.
:cl:
add: Added Medical Doctor clothing to the Clothing Vendor in a new section called "Medical Clothing"
fix: Medical scrubs now have their respective color on their name.
/:cl:
=> Adds Medical Clothing into the Clothing Vendor

code/game/objects/machinery/mortar.dm
this wasn't even supposed to be in the game it was a test bed i made for mortar features also removes my unused rocket arty typepath
no more rapid firing 4 mortar shells in a second
:cl:
del: unused rocket arty typepath
balance: db mortar reload time to 2 seconds
balance: db mortar max rounds to 2
balance: db mortar now has cooloff time of 6s
balance: db mortar now has base spread of 2 tiles
/:cl:
=> nerf the mortar db also remove useless rocket arty typepath

code/game/objects/machinery/buttons.dm
Title. There were some AIs opening shutters before 12:10 even apparently.
Limiting (mainly) AI grief capacity good.
:cl:
fix: You can't open the shutters before the alamo can even take off anymore
/:cl:
=> Prevents shutter open button from working before the shuttles can even take off

code/controllers/subsystem/processing/resinshaping.dm, code/game/objects/structures/xeno.dm, code/game/turfs/walls/resin.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm
Title. Valhalla xenos being able to drain quick build is not pog.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/13818
Bug bad.
:cl:
fix: Fixed all xeno hives sharing the same point pool
/:cl:
=> Fixes all xeno hives sharing the same point pool

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/pistols.dm
Per title.
Sunder per bullet reduced from 2 to 0.5.
Burst fire now has an additional delay of 0.3 seconds between bursts.
This is option 2 of two PRs I intend to put out for the 88M4 (see: #13815). This thing is allegedly meant to be an ERT-only sidearm that somehow became common access. It currently is hands down one of the best weapons in the game, and xenos aren't having a fun time fighting it in its current state... if they even get the chance to, considering how fast this kills.
:cl: Lewdcifer
balance: MK88 Mod 4 Combat Pistol nerfed. Sunder reduced from 2 > 0.5, burst fire now has a 0.3s delay between bursts.
/:cl:
=> Nerfs the MK88 Mod 4 Combat Pistol

_maps/templates/unit_tests.dmm, code/game/area/general.dm, code/game/objects/effects/landmarks/landmarks.dm, code/game/world.dm, code/modules/unit_tests/connect_loc.dm, code/modules/unit_tests/unit_test.dm, code/modules/unit_tests/weed_ability.dm, code/modules/unit_tests/weed_spread.dm, tgmc.dme
https://github.com/tgstation/tgstation/pull/57408/files
Required for some other more important ports. Also made it so gamemode start checks get bypassed in case your mode was set to nuclear war when running tests locally.
Required for some other more important ports
:cl:
code: Unit tests are done in a box now instead of space
/:cl:
=> Ports the tg unit test box

code/modules/projectiles/guns/pistols.dm
Also adjusts the unwielded scatter of 1911 and tp23 since they could be potentially problematic.
Pistols are kinda neglected right now, you see basically none carried. I think this is because of the harsh click gate they're locked behind, meaning you have to click for every shot, which isn't enjoyable to use. I tested out the feel and most pistols are still not more powerful than rifles even with full auto so the balance shouldn't be questionable. This doesn't affect revolvers. 
:cl:
balance: Pistols now have full auto! No more spam clicking
balance: Increased the unwielded scatter of the P23 and 1911
/:cl:
=> Gives pistols full auto

code/modules/mob/living/carbon/xenomorph/death.dm
I have no idea how they weren't gibbing before honestly. These lines of code are 3 years old.
Not intended afaik. Minions should leave a corpse.
:cl:
balance: AI xenos no longer gib on death every time
/:cl:
=> AI xenos no longer gib on death every time

_maps/map_files/BigRed_v2/BigRed_v2.dmm, _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
some silos i looked at on ice colony and big red didn't have complete fog coverage. one on ice colony just didn't have fog, period.
safe spots for xenos to spawn
:cl:
fix: added some missing fog tiles around silos on ice colony and big red for crash games
/:cl:
=> crash silo fog fixes

code/modules/mob/living/blood.dm
Makes some adjustments to blood regen by making it 3 tiered based on your levels of blood.
The previous iteration made you starve when you went below 90% to regen your blood and players reported that it wasn't very fun. This aims to make the regen better when you are near full blood. It also makes blood regen better when you are close to death but with small amounts of tox.
:cl:
balance: Rebalances blood regen to be more player friendly above 90%
balance: Adds a tier below 50% blood to quickly bring you above 50%
/:cl:
=> Un-unfuns blood regen and adds more to it

code/game/objects/items/tools/extinguisher.dm, code/game/objects/machinery/doors/firedoor.dm, code/game/objects/structures/watercloset.dm
Title.
Firedoors are no longer insta-weld, handwashing code has been cleaned up some and no longer uses sleep().
~~Also kills some unintended interactions with handwashing, like being able to literally anything as long as you're adjacent to the sink by the end of the handwashing check~~
Better code is better, also firedoors shouldn't be instant weld, they should take a couple seconds for consistency sake.
:cl:
balance: Firedoors now take a few seconds to weld and unweld
refactor: Cleaned handwashing code up somewhat
fix: Fixed an incorrect balloon alert when operating a fire extinguisher 
/:cl:
=> Firedoors now have a delay when welding, minorly refactors hand washing

code/__DEFINES/admin.dm, code/modules/admin/admin_verbs.dm, code/modules/client/client_procs.dm
This PR makes the private messages of mentors bypass the spam filter. This applies to both adminpms aswell as mentorpms, as both use the same framework after what tg did to them and I have not seen any way to clearly distinguish the two.
Done via private messages sending another arg to the spam filter check, which checks for it. Also done for admins, however admins generally bypass the filter anyways. I did do it nonetheless to ensure better futureproofing if someone for some reason removes general admin spam filter bypassing.
Any mentor will tell you how annoying it is to be writing up a long response, only for "Automute triggered, muted from adminpms / adminhelp". Please actually let people write long responses for things that warrant one instead of having to artificially truncate out …
=> Mentors no longer get automuted by using private message

code/__DEFINES/loadout.dm, code/game/objects/machinery/mortar.dm, code/game/objects/machinery/vending/new_marine_vendors.dm
This PR allows corpsmen to buy a bundle of a bed, and a beacon for the low low price of their entire budget. 
I also added a space in some mortar code, because it was bothering me.
I always wanted to have two beds to chuck people up faster. I am absolutely willing to skimp on the other gear for that
It also gives more work to doctors shipside, which is good. While it is effectively a teleporter, and you could sooort of make a discount telepad with them, I do not think the cooldown makes it any viable for any substantial effect.  
:cl:
add: Added medivac beds to corpsmen vendor for their entire budget
code: Added a space to the mortar code :)
/:cl:
=> Add Medivac beds to Corpsmen vendors for all of their points.

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
adds missing the wire that connects the APC terminal to the power grid.
bug bad
:cl:
fix: adds a missing wire to the pillar of spring medbay store room
/:cl:
=> adds a missing wire to the pillar's medbay store room

code/modules/projectiles/guns/pistols.dm
Reverts some dubious pistol changes.
P-23 no longer has a unwield scatter var that does nothing.
1911 no longer has a LOWER unwield scatter than other pistols (the value for both of these guns was intended as a nerf from the autofire pr).
Mod4 no longer has a 0.3 extra delay on bursts. This made it HUGELY worse than either the P-14 or P-23. It still has trash sunder now though.
Funny number changes.
:cl:
fix: fixed 1911 having lower scatter than it should
balance: Mod4 no longer has an extra delay when burst firing
balance: Slight akimbo nerfs to the P-23, 1911 and Mod4
/:cl:
=> pistol tweaks

code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
Alt activation doesn't respect can use restrictions by default, so a quick fix to check manually.
Also fixes the can use check spamming constantly on button icon update due to not respecting silence.
bugfix
:cl:
fix: Cannibalise doesn't let widow have too many spiderlings
/:cl:
=> Cannibalise respects spiderling cap

code/datums/gamemodes/infestation.dm
Title
Xeno buff of the year
> open hive tunnels screen
> An old tunnel dug by a former member of the hive prior to our awakening at An old tunnel dug by a former member of the hive prior to our awakening at An old tunnel dug by a former member of the hive prior to our awakening at An old tunnel dug by a former member of the hive prior to our awakening at
> close hive tunnels screen
There's no reason to name it like this. It clogs up the hive tunnels screen and chat whenever it dies.
:cl:
qol: Prebuilt tunnels are no longer named as obtusely
/:cl:
=> Renames automatically generated tunnels

code/modules/mob/dead/observer/observer.dm
Title. 
Because being able to observe people in lobby and click buttons for them is funny.
:cl:
fix: You can only observe living mobs
/:cl:
=> You can only observe living mobs

code/game/objects/items/storage/belt.dm
Changes the G8 General utility pouches storage behavior from 3 slots to 9 storage space, same functional space, just divisible into smaller pieces.
Makes the G8 General utility pouch storage behave like the normal general pouches, just bigger and can hold normal weight class items. Good because one injector shouldn't fill the same amount of space as a GPMG ammo box.
G8 General utility pouch storage
:cl:
balance: G8 belt is no longer slot based, so can hold more smaller items
/:cl:
=> G8 from storage_slots=3 to max_storage_space=9

code/game/objects/items/weapons/twohanded.dm
Basically the behaviour we have pre wield fix. Inhand appears wielded the moment you start wielding instead of updating after you're finished wielding.
People preferred the old behaviour.
:cl:
fix: Fixed inhand wielding sprites
/:cl:
=> Fixes inhands when wielding

code/_globalvars/admin.dm
It was working only half the time because /g and findtext don't work together. Fixes #13871, you were never meant to be sending emojis
```dm
world.log << NON_ASCII_REGEX("😀") // 1
world.log << NON_ASCII_REGEX("😀") // 0
```
:cl:
fix: You can no longer use non-ASCII characters in OOC
/:cl:
=> Fix non ASCII regex

code/game/objects/machinery/vending/marine_vending.dm
It currently only holds chaplain outfits, because I severely lack drip judgement, and I do not know what would look good on marines. Or be useful. 
A little more drippyness for us. 
:cl:
qol: Added chaplain clothes to the clothing vendor
/:cl:
=> Add a category for spare civilian clothing in the clothing vendor

_maps/map_files/Sulaco/TGS_Sulaco.dmm
The current sulaco drop pod bay is not lined up well with the alamo landing south of it, which is most displeasing. This PR fixes that, and makes it more pleasing.  It also increased the number of drop pods by about 10%
It seriously looks better.
:cl:
qol: Made the sulaco drop pod bay line up with the nose of the alamo :)
balance: Increased the number of drop pods in the sulaco by 11%
/:cl:
=> Makes the sulaco drop pod bay look better

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
This PR adds a couple firelocks to places which were missing them, re-adds the medical shutter button and more firelocks to redesigned places that were lacking them. Also a sprinkle of AI holopads, because lots of place lacked coverage. 
Consistency good, random lack of coverage bad. 
:cl:
qol: Added more AI holopads to POS
fix: re-fixed missing firelocks and shutters buttons to POS.
/:cl:
=> Add firelocks and AI pads to POS again

code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Xenos can once again throw mobs past other xenos.
Fixed a bug with throwing mobs past warriors.
Bug fixes.
:cl:
fix: Xenos can throw mobs past xenos once again
fix: Fixed an issue with throwing mobs past warriors specifically
/:cl:
=> Xeno throw fixes

code/game/objects/structures/benchpress.dm
If you bench press you become not fat.
Credit akimomi on discord:
"Fat slowdown isn't a good mechanic, it's not enjoyable for marines and doesn't add anything to the game except as a way to punish new players for eating food and people taking advantage of the ability to have infinite nutrition.
It doesn't fit for TGMC."
Someone then said lifting should remove fat so here we go.
:cl:
add: Bench press is a great way to lose weight
/:cl:
=> Bench pressing makes you not fat anymore.

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Read title. This is what it looks like fixed.
I am sick of getting ahelps for this. Bug bad.
:cl:
fix: Fixed PoS CAS ammo storage not having a button to open it.
/:cl:
=> Fixes PoS CAS ammo storage lacking a button

code/datums/keybinding/xeno.dm
Reorganises the xeno keybindings so that multi-caste abilities are at the top, then single caste abilities all in alphabetical order. Also adds some default keybindings for Drone, Queen and multi-caste abilities which didn't have any before. 
The ordering before was pretty arbitrary (mixing in multi-caste abilities in the middle of single caste abilities, not alphabetical or tier order, etc) so this makes it easier for players and coders to edit. And having more default keybinds is helpful for new players, as well as if a veteran has to reset their bindings for whatever reason. 
:cl:
add: Added some default keybinds for Drone, Queen and multi-caste abilities
refactor: Reordered xeno keybindings so it's now in alphabetical caste order
/:cl:
=> Reorganised xeno keybindings and added a few new default ones 

code/modules/surgery/surgery.dm
Currently, regardless of where you do surgery, the time is randomized between the minimum and maximum time of how long a surgery step can take. This PR makes it so if you are on an operating table, it will always take the minimum.
P.S this is probably fairly shitcode, if there is a better way to do it please tell me
This aims to do two things:
1) Make it less frustrating for the person doing surgery to get used to step times. RNG while doing medical can be fun (see bone cracks when opening rib) but for the most part just adds tedium. However, this keeps another penalty to rollerbed and normal table surgery as those have the benefit of being *portable*, while already having some RNG with them as well (see: slip chance outside of synth, synth is a funny snowflake).
2) In a small way …
=> De-randomizes surgery step time on an operating table

_maps/map_files/Minerva/TGS_Minerva.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm
Each chem bay has their stack(s) of phoron increased/decreased to 4 pieces each using PoS as a standard. Shouldn't be gamebreaking since phoron is (mostly) a catalyst.
Consistency between shipside medbays is a good thing.
:cl:
balance: Each shipside chemistry now has 4 pieces of phoron per stack.
/:cl:
=> Gives every shipside chemistry bay the same amount of phoron

code/__DEFINES/dcs/signals.dm, code/datums/keybinding/xeno.dm, code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm, code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
- Fixed "Hivemind: Change Form" keybinding not being available.
- Added "Carrier: Build Hugger Turret" and "Widow: Birth Spiderling using Cannibalise charges" keybinds.
- A lot of default hotkeys were added for ones which didn't already have them, so now almost all abilities have one if they're frequently used. Some existing hotkeys were changed also to eliminate conflicts across all castes, and so that similar abilities from different castes use the same hotkey. Focus was on minimising unassigned hotkeys, eliminating hotkey conflicts, and having similar abilities from different castes use the same keys (e.g. Healing Infusion and Psychic Cure, Essence Link and Psychic Link, etc)
- Swapped the newly added default hotkeys for Frenzy and Recovery pheromones so that it matches the sequential …
=> Added many defaults for xeno keybinds, and three new ones available

code/modules/client/preferences_ui.dm
The "This is my voice" preview in prefs was always robotic because in python `bool('0') == True`. This could be fixed on the tts-api.py side too but I'm not sure anyone will update that in a meaningful amount of time
:cl:
fix: Fix TTS preview voice being always robotic
/:cl:
=> Fix TTS preview voice being always robotic

code/game/objects/items/reagent_containers/autoinjectors.dm, code/modules/reagents/reactions/medical.dm
changes the medical nanites recipe from: 
10 parts nanites (not medical, razorburn for whatever reason), 100 parts iron, 5 parts radium and 5 parts lemoline = 1u of nanites
to: 
1 part medical nanites catalyst, 10 part iron and 1 part lemoline = 9u of nanites
nanites are already free in the vendor, this recipe is a just a QOL feature incase you want bigger quantities of nanites but don't want to be sitting at the vendor injecting beaker, restocking, vending and repeat while also keeping the small cost of lemo
:cl:
add: Added an actual recipe for medical nanites
/:cl:
=> Adds a recipe to medical nanites

_maps/shuttles/minidropship_mobile_bar.dmm, _maps/shuttles/minidropship_standard.dmm, _maps/shuttles/minidropship_umbilical.dmm
Adds barbed wire on the ground to the tadpoles on the title.
With the metal from floortile removal, good to allow the PO to barb their cades easily. 3 hardpoint tad gets none because it is unbalanced as is, and the big tadpole already has metal in it.
:cl:
add: Adds barbed wire to the Standard, Bar and Umbilical tadpole.
/:cl:
=> Adds barbed wire to standard, bar and umbilical tadpole

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm, _maps/map_files/deltastation/deltastation.dmm, code/modules/recycling/recycler.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/10652
The issue was that recyclers only have sprites for 1 direction, and they point north by default, instead of west. I made the default point west and fixed minerva's one by forcing it to point north. Avoids us having to redo it. 
Working gear is good!
:cl:
fix: fixed some recyclers not working properly.
/:cl:
=> Makes recyclers point in their relevant direction. 

code/datums/components/chem_booster.dm, code/modules/atmospherics/machinery/components/unary_devices/cryo.dm, code/modules/reagents/reagents/medical.dm
Changes chem related brute and burn healing to carry over additional health to another damaged limb when the randomly targeted limb has less damage than the chem is supposed to heal. This is most notable with big ticket healing chems, such as Russian red, Neuraline, Somolent, Clonexedone, and Cyroxadone (not that it matters much with cyropods)
Good because it makes all chems heal their specified amount, regardless of randomly selected limb.
:cl:
balance: Chem healing on some chemicals is now overall instead of per limb
/:cl:
=> Changes chem related brute/burn healing behavior

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm, _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm, _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm, _maps/map_files/desparity/desparity.dmm, _maps/map_files/gelida_iv/gelida_iv.dmm, _maps/map_files/generic/Admin_Level.dmm, _maps/map_files/icy_caves/icy_caves.dmm, code/game/objects/effects/spawners/random/weaponry.dm
Title.
I've replaced all the removed boxes with random grenade spawns, but I can change that if needed,
Flashbangs invalidate deathsquads and ruin HvH, I thought I had removed all the flashbangs earlier but apparently didn't.
:cl:
balance: Removed all the flashbang boxes from the ground.
/:cl:
=> Removes groundside flashbang boxes

_maps/map_files/Minerva/TGS_Minerva.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm, _maps/map_files/combat_patrol_base/combat_patrol_base.dmm, _maps/map_files/debugdalus/tgs_debugdalus.dmm, _maps/modularmaps/big_red/bigredsecornervar6.dmm, code/game/objects/machinery/computer/dropship_weapons.dm, code/game/objects/machinery/dropship_part_fabricator.dm, code/game/objects/structures/cas_plane_parts.dm, code/game/objects/structures/dropship_ammo.dm, code/game/objects/structures/dropship_equipment.dm, code/modules/condor/cas_shuttle.dm, code/modules/projectiles/guns/sentries.dm, code/modules/reqs/supplypacks.dm
This pr separates the dropship fabricator items into 3 categories, Condor Equipment, Dropship Equipment, and Condor Ammo. Also repaths condor equipment into /obj/structure/dropship_equipment/CAS, dropship equipment into /obj/structure/dropship_equipment/shuttle, and most dropship ammo into /obj/structure/ship_ammo/CAS (exception being the railgun ammo)
Currently all printable items are under "Dropship", meaning it can be rather confusing for new players whether something can be used on the Condor or the Tad/Alamo. This helps to clarify this.
:cl:
qol: The dropship fabricator has had it's items separated into more distinct categories.
code: Repathed dropship/condor equipment, dropship/condor weapons, and condor ammo.
/:cl:
=> Separates the Dropship Fabricator Into Dropship/Condor Categories. Repaths Dropship Equipment/Ammo

code/game/objects/machinery/vending/marine_vending.dm
This reverts commit 405b1ad475d06d4ea7542e410681c10c4b5d95a2.
we added an entire other tab with ONE item
why do we need an entire tab for 1 item, just merge surplus headgear into surplus clothing or something
:cl:
del: surplus clothing
/:cl:
=> Revert "Add a category for spare civilian clothing (#13881)"

code/__DEFINES/dcs/signals.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/crates.dm
Deletes comsig closet dumped because why does it exist? It just causes issues with unregistration. Instead an exited signal gets registered to whatever mob enters the closet so we can do something when the mob gets forceMoved or such and call the open proc, which helps with tarps making people perma invis if teleported out a tarp for example. This gets unregistered on open.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/13833
Closets are a bit weird code wise and exploits aren't cool. This addresses both.
:cl:
fix: Fixed tarping before eord making you invisible
refactor: Made lockers not use signals where they aren't necessary. Should help with signals not unregistering properly in some cases
/:cl:
=> Closets no longer use signals for no reason + fixes weird behaviour with forceMove and closets

code/__DEFINES/mode.dm, code/_globalvars/misc.dm, code/datums/actions/observer_action.dm, code/datums/gamemodes/_game_mode.dm, code/datums/gamemodes/crash.dm, code/datums/gamemodes/extended.dm, code/datums/gamemodes/nuclear_war.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/xenomorph/death.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm
ONLY supposed to be paired up with https://github.com/tgstation/TerraGov-Marine-Corps/pull/13615
Adds a xeno respawn timer as an alternative to the silo rework and nerfs Nuclear War larva generation, to keep a punishment for dying with the maturity rework.
Current time is 5 minutes, 3 for crash. Silo scaling down from 2x to 1.5x.
It applies if you die as a xeno or ghost as a xeno, but not if you are a minion to not punish players for taking minions while waiting
Keeps a punishment for dying as Xeno while keeping it user friendly (i.e larva generation being x number per minute)
:cl:
balance: Added a xeno respawn timer on xeno death and ghosting, does not apply if you took a minion
/:cl:
=> Adds a xeno respawn timer, nerfs silo scaling

_maps/map_files/Theseus/TGS_Theseus.dmm
The Theseus Requisitions department is a little weird. This should help.
Theseus' requisitions department currently has a lot of clutter in the central zone, with outdated components, mismatched tiles, and other items that generally feel out of place, or in some cases block movement paths to doorways. This moves things around, should look a little nicer while doing so.
:cl:
qol: Adjusted Theseus requisitions to be more ergonomic.
/:cl:
=> Adjustments to Theseus Requisitions

code/controllers/subsystem/monitor.dm
Read title. Currently at 5 minutes between each check; moving down to 3 minutes.
A common occurrence when autobalance happens is when xenos join in at the start of the check, which *would* disable autobalance, but because they joined after the check is doesn't change. This leads to 3-4 minutes of autobalanced xenos when they really shouldn't be. This hopes to reduce that. If it is fine to move down to two minutes, please tell me; this is just being on the cautious side.
:cl:
balance: Autobalance check now occurs every 3 minutes instead of every 5
/:cl:
=> Decreases time between autobalance checks

code/__DEFINES/monitor.dm, code/controllers/subsystem/monitor.dm
King had special autobalance weight since the caste used to work mechanically as a "game ender" that cost a lot of psy points, now instead it's just another T4 that is pop-locked so it has the same weight as other T4s.
King used to weigh up to 350% of a Queen for autobalance calculations, this hasn't been updated since King got reworked into a much weaker pop-locked T4 caste.
:cl:
del: King no longer has additional special autobalance weight.
/:cl:
=> King no longer has additional special autobalance weight

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/pistols.dm
Super heavy pistol ammo now deals knockback and has slightly less sunder/slowdown. It's effectively nearly the same as non TP-44 revolver ammo, also reduced falloff slightly.
Deagle
Fire delay 0.7->0.3
Better base handling overall.
Hipower
Fire delay 1->0.35
These guns suck complete doodoo, they don't work as pocket stunners because their damage and handling is trash, M-44s generally just handle better despite being stuck as single action, and their ammo economy is equally as bad. If the fire delay is too low I'd probably just make it .35 and .4 respectively and they'd be fine forever, since getting rid of the stagger would just make them worse heavy pistols.
:cl:
balance: Superheavy pistols like the Deagle and Hipower have significantly less fire delay, deal a bit less sunder, deal …
=> Superheavy pistol changes

code/modules/reqs/supplypacks.dm
This renames the module orders in the req buylist to remove the "Jaeger" before each of em, and puts "armor" in the name for orders that only give modules for the chest piece. Also adds "set" to an order that is a module set.
Less confusing for new players, considering these modules are not Jaeger only.
:cl:
spellcheck: Removed "Jaeger" from req module buy orders' names, adds "armor" and "set" to module orders that are chest piece only or a set.
/:cl:
=> Renames armor modules in req buylist

code/modules/mob/living/carbon/xenomorph/evolution.dm, code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
These were being decremented but never incremented so xeno deaths were actually counting *towards* turning autobalance on
:cl:
fix: Fix xeno spawns not counting towards autobalance
/:cl:
=> Fix xeno spawns not counting towards autobalance

code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm
I spent like 10 hours on this debugging, removing/adding code, debugging
You should be able to queue now and not have to requeue to spawn in if you queued with your xeno respawn timer active
The skipping past queue if your timer is off should work now, too
Ghosting as a Valhalla xeno shouldn't reset your timer
Side note: I had to remove the XENODEATHTIME_CHECK from attempt_to_spawn_larva, so far I haven't found any ways to bypass the check regardless but keep that in mind when reviewing
Bugs aren't very good for the game.
:cl:
fix: Xeno queue should (hopefully) work as intended now
fix: If you ghost as a Valhalla xeno, your xeno respawn timer shouldn't reset
/:cl:
=> (Hopefully) fixes some queue bugs

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/shotguns.dm
Derringer buffs
Fire delay 0.5->0.2 SECONDS
Scatter 2->0
Recoil (Both Wielded/Unwielded) 1->0
Wield Delay 0.5->0.1
Derringer deals slowdown on hit, no longer knocks back.
This gun stinks absolute ass to the point it isn't even a funny meme, at least make it somewhat useable so its somewhat funny.
:cl:
balance: Derringer has better gun handling statistics and deals stagger on hit again,
/:cl:
=> Derringer buffs

_maps/shuttles/escape_shuttle.dmm
Adds lighting to the escape shuttles, normalizes the direction of seating to all face the middle, adds 2 additional hypersleep beds, and expands the bow section by one tile.
The escape shuttles have a few elements that have been bugged for a while, specifically the seating not functioning properly and lacking any sort of interior lighting of their own. This fixes these, and expands the shuttle slightly to accommodate more comfortable movement.
:cl:
qol: Made some quality of life adjustments to the genetic escape shuttles.
/:cl:
=> Adjusts Escape Shuttle appearance

code/game/objects/effects/misc.dm
Title.
They were dense and shouldn't be.
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/13579
Despite the fact that all the soundplayers are inside walls, apparently people were knocking walls down with plasma cutters and getting obstructed, especially during hijack.
:cl:
fix: Made soundplayers no longer dense.
/:cl:
=> Fixes soundplayer density

code/game/objects/effects/weeds.dm
Title.
This PR fixes weed walls being weird when smoothing on walls and also a rare instance where they could become invisible due to resetting to its initial (invalid) icon_state.
Bugs bad, fixes good.
:cl:
fix: Fixes weeds on walls sometimes going invisible.
/:cl:
=> Fixes some issues with weed walls

code/__DEFINES/colors.dm, code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/flamer.dm
Ports CM flame light colors instead of the existing one, new ones are a lot more rich in color and more epic looking in general, also i fixed a visual bug where the actual flame color is applied with a noticeable delay.
Color comparison:
**Normal -**
Before
After
**Plasma-**
Before
After
**Napalm-**
Before
After
Also demonstration of fixed flame light update: (look at how plasma flame uses orange light color before switching to the correct one)
Before
After
Better visuals - good, bugs - bad.
:cl:
fix: flames now spawn with correct flame light color
code: changed hex color codes of flame light color
/:cl:
=> Redone flames light colors

code/controllers/subsystem/points.dm, code/game/objects/structures/dropship_ammo.dm, code/game/objects/structures/dropship_equipment.dm, code/modules/requisitions/supply_export.dm
Every single change is documented over at https://hackmd.io/@dopamiin0/caschange1
In short: orbit more dramatically affects CAS pointgen. CAS now gets 5% of all exports added to their point total. The vast majority of CAS items have had their prices increased by 33-40%. A select few have had their cost increased more dramatically for balance concerns. A select few have had their cost increased by less, not at all, or reduced due to being previously underpowered/unpurchasable. Minirockets have been mini-reworked to have a base speed of 2s and a smaller explosion radius. 
PLEASE read https://hackmd.io/@dopamiin0/caschange1
I am begging you. If you ask something that is answered in the document you will be laughed at
Summarized: CAS is in a weirdly balanced state. It has some options, such …
=> CAS balance patch: Widowmaker is dead, long live widowmaker

code/datums/elements/strippable.dm, code/game/objects/items.dm, code/game/objects/items/cards_ids.dm, code/modules/mob/inventory.dm, code/modules/mob/living/carbon/human/inventory.dm
Previously when you attempted to take a dogtag ID, you instead generated a separate item, the info tag, which only held name and job and could stack with multiple other info tags and be put in the ship memorial. All that got removed by the strip UI overhaul, and so this PR puts it back in.
Adds routing to enable items to react to being stripped, like a gun exploding if someone hostile takes it or vital intelligence sending out a warning signal when it's stolen, plus more variable feedback options for why you can't strip something.
Fixes #13806 
Also a couple minor codeside spelling things.
:cl:
fix: Taking info tags from corpses works again
/:cl:
=> Reenables taking info tags from corpses

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/pistols.dm
Nerfs stagger from 2 to 0.5. Also nerfs the firedelay by 0.1 on all of them.
Hipower does 1.1 rather than 1.2, scatters a bit more and has natural recoil.
Makes super heavy pistols more in line with stagger on hit and general damage.
:cl:
balance: Another balance pass on superheavy pistols, their stagger has been significantly reduced, alongside their fire rate being minorly made worse (0.05 more seconds, so .35 for Deagle and .4 for automag.) Automag does a bit less damage and has a bit more scatter.
/:cl:
=> Superheavy pistol balanc pass

code/_onclick/hud/screen_objects/screen_objects.dm, code/game/objects/items/storage/storage.dm, code/modules/clothing/modular_armor/attachments/storage.dm
You can now right click webbings and helmets to draw from them, and you can ctrlclick to draw leftmost item from storage.
Drawing with right click from helmet, webbing, armor. Drawing leftmost from toolbelt.
https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/17ee28a4-7cc6-4783-9494-47b2fda02a26
Also fixes a bug where clicking an inventory UI element didn't properly pass down it's click arguments to the item in the slot. This means that you can actually right and ctrl click inventory slots to right click and ctrl click the item in the slot.
I couldn't do the 3rd additional (inserting into leftmost in belt) from https://github.com/tgstation/TerraGov-Marine-Corps/issues/13980 due to BYOND's contents list being a special snowflake and I don't want to anger it by trying to …
=> You can now right click webbings and helmets to draw from them, and you can ctrlclick to draw leftmost item from storage

code/game/objects/items/weapons/twohanded.dm
Copypastas SOMs fire axes bump slash on wield to Vali Claymore.
Good because hitting a xeno for about a third of the total damage on accident really sucks.
:cl:
qol: Vali Claymore only bump slashes when wielded.
/:cl:
=> Vali claymore bumpslash on wield

_maps/map_files/Arachne/TGS_Arachne.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm
Standardizes all Dropship, CAS, and Tadpole shipside pads to use the same hazard stripe object outline.
Currently, the ships that use hazard stripes for dropship outlines use the turf version, not the object version. While this initially has no visual impact, once a dropship leaves the occupied tile, these tiles reset to the default downward-facing orientation, which looks bad. This PR changes this so that the hazard stripes never occupy an area underneath the dropship spawn zone, preventing this issue. 
For the case of the Tadpole, since there are variable configurations, the hazard stripes being swapped for the object version instead of the turf version means that even in the case of overlapping with the longer Tadpoles, it will simply delete the stripes instead of causing the direction …
=> Standardizes Dropship Hazard Stripe Outlines

code/game/objects/machinery/vending/marine_vending.dm
Adds an eyewear category to the clothing vendor, with various cosmetic and prescription sunglasses from the loadout prefs. Also moves the ballistic goggles from headwear to this new category.
(Note: The duplicate sunglasses are due to the shades and sunglasses sharing the same name. Each of the sunglasses are the fake kind, so they do not provide flash protection.)
Having the cosmetic eyewear all in the same place will make customizing your character less tedious and difficult. Also the ballistic goggles being in headwear didn't really make much sense.
:cl:
add: Added an eyewear category to the surplus clothing vendor, containing various cosmetic and prescription eyewear.
del: Moved the ballistic goggles from the headwear category to the new eyewear category.
/:cl:
=> Adds An Eyewear Category to Clothing Vendor

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
I thought we have learned from Gelida at this point why two entrance FOB's are very bad. It extends FOB sieges to an unnecessary degree, multiplied by competent engineers. This flank is one tile larger than the last one, two tile entrances are yucky.
:cl:
balance: Re-added Magmoor LZ 2's SE flank.
/:cl:
=> Re-adds the Magmoor LZ 2 SE flank

tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx, tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
`false && ""` won't render but `0 && ""` will render 0
:cl:
fix: Fix stray zeroes in prefs
/:cl:
=> Fix stray zeroes in prefs

code/controllers/subsystem/blackbox.dm
This prevents people from farming hours during times where the server has no admin to run it (eternal EORD)
I don't know what label to even put this under CL so guh.
People farming hours when there aren't admins on is very cringe.
:cl:
del: Blackbox subsystem doesn't fire postgame
/:cl:
=> Blackbox subsystem doesn't fire postgame

code/modules/mob/living/carbon/human/species.dm
Reduces hold order from 10% damage resist per level to 5%
I decided against removing damage resist after talking to Tivi, decided to do this instead. People have been going SL/FC to exclusively spam hold order due to the insane damage resist it gives, alongside running heavy tyr 2 and premedding with it. Those are honestly fine, this pushes it over the edge.
:cl:
balance: Hold order gives 5% damage resist per leadership level instead of 10%.
/:cl:
=> Hold order nerf

code/game/objects/structures/mineral_doors.dm
This fixes sentries not being able to target through open doors and open doors blocking line of sight based abilities like fling and heal.
Bugfix good.
:cl:
fix: Fixes doors blocking line of sight when they shouldn't
/:cl:
=> Fixes doors being weird with line of sight

code/modules/projectiles/ammo_datums.dm
If boiler fills carrier's trap with acid mode, it would explode with neurotoxin smoke, this pr fixes it.
Fix - good.
:cl:
fix: fixed boiler making neuro traps with acid
/:cl:
=> Fix boiler making neuro traps with acid

code/modules/mob/mob_movement.dm
You can no longer bypass running out of stamina by just spamming the button.
Exploit bad.
:cl:
fix: fixed a running intent exploit
/:cl:
=> Fixes run exploit

code/datums/jobs/job/job.dm, code/datums/outfit.dm, code/modules/mob/new_player/preferences_setup.dm
Fixes backpack prefs overriding the actual specified backpacks in job datums, because of which ST and CE never spawn with a their back fuel tanks for example. Also made it possible to specify having no ID slot item and no backpack slot item at all, right now it's impossible, if you set ID to null it'd still spawn, if you set backpack to null it'd just spawn the one from prefs anyway.
Bugs - bad, fix - good, flexible datums - even better.
:cl:
fix: id card having no mob icon when spawning on mob
fix: fixed backpack prefs overriding spawn of job assigned backpacks
code: made it possible to specify to spawn without backpack or id in job datums
/:cl:
=> Fix backpack prefs overriding job backpacks

code/game/objects/effects/aliens.dm
Restores forgotten sprites of acid on walls, also i've made it so acid would have layer of item it is currently melting, so acid would no longer render over literally everything including mobs.
Without layers tweak:
With layers tweak:
:cl:
add: acid on walls now has unique set of sprites
fix: fixed acid rendering over everything
/:cl:
=> Restoration of acid wall sprite + layer tweak

code/modules/admin/debug_verbs.dm
Does what it says on the tin. You aren't supposed to flat out qdel walls apparently.
Runtime and deletionproof walls are bad.
:cl:
fix: Fixed admin wall deletions
/:cl:
=> Fixes admin wall deletions

code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm, code/modules/mob/living/carbon/xenomorph/castes/king/king.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
Queen and King have hard coded names, decided to work with them to give them unique names at each rank; like the olden times when it went Queen to Empress and King to Emperor.
Bug fix good.
:cl:
fix: Queen and King ranks should work now
/:cl:
=> Queen and King rank fixes

code/modules/mob/living/carbon/xenomorph/castes/mantis/abilities_mantis.dm
Fixes #14048
:cl:
fix: Fix mantis ravage keybind not working when not selected
/:cl:
=> Fix mantis ravage keybind not working when not selected

_maps/map_files/slumbridge/slumbridge.dmm
Title.
Apparently a few areas of Slumbridge have table/mainship/nometal instead of table/mainship etc.
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14043
The nometal variants of tables/chairs etc are meant to be used shipside mostly, not on groundside maps.
:cl:
balance: The SOM base tables on Slumbridge now produced metal when deconstructed.
/:cl:
=> Fixes Slumbridge having non-metal producting variations of objects

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/energy.dm
Rebalances this weapon slightly. The general intention is to nerf it, but I'm changing some other stuff just a little to compensate for the loss.
- No longer accepts the T-47 rail scope (this was basically a sniper scope).
- Lasers are no longer incendiary, and will not set xenos on fire. Instead, this weapon will now inflict the Microwaved debuff at maximum stacks (5), on every shot.
- Increased penetration from 5 to 10.
- Standard firing mode ammo usage reduced, basically amounting to a maximum of 50 shots (this was 40 before).
The X-Ray Laser Rifle has been allowed to remain in a very questionable spot in terms of balance. Setting xenos on fire, being a valid sniping option, and the preferred reqs option due to how good of a deal it is in terms of point cost and gun power -- all in …
=> X-Ray Laser Rifle minor rebalance

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
This pr updates the description of the crusher's Crest Toss ability to mention how harm intent changes it's action.
Letting players know how the ability works is good.
:cl:
spellcheck: Changed Crest Toss' description to mention it's effects while on harm intent.
/:cl:
=> Updates Crest Toss' Description

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm, _maps/map_files/desparity/desparity.dmm, _maps/map_files/icy_caves/icy_caves.dmm, _maps/map_files/slumbridge/slumbridge.dmm
Title.
I replaced them all with regular gun spawners.
EORG maps retain the tier based spawners as normal.
The tier-based weapon spawns are supposed to be deprecated for groundside spawn, recently (possibly due to the campaign update) overpowered weapons have started creeping onto the maps that still have the tier-based spawns. I've opted to finish the job and replace all the tier-based weapons entirely instead.
:cl:
balance: All ground maps use the regular spawning random gun spawning system instead of the ancient tier based system that could spawn overpowered guns.
/:cl:
=> Removes tier-based weapon spawns from ground maps

code/modules/projectiles/magazines/mounted.dm
Simply changes MG27 Box Mag desc to accurately reflect ammo count, somehow this got past whoever changed it last.
incorrect descriptions bad
:cl:
fix: MG-27 Box Magazine description now quotes correct ammo count
/:cl:
=> Fixes inconsistent MG27 Magazine description

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/energy.dm
Per title. This was unintended, and only the standard mode is meant to inflict the debuff.
Unintended features, begone. Balance is not yet too far gone.
:cl: Lewdcifer
fix: TE-X piercing mode no longer inflicts Microwaved due to a code oopsie.
/:cl:
=> Fixes an issue where the TE-X Piercing Mode inflicted Microwaved

code/modules/mob/living/carbon/xenomorph/abilities.dm
Gives the lay egg ability a description, describing how it behaves, and how empty eggs can have huggers inserted into them.
This ability currently doesn't have a description, which is bad.
:cl:
spellcheck: Added a description to the "lay egg" ability
/:cl:
=> Egg Lay Ability Description

dependencies.sh, tools/bootstrap/python37._pth, tools/bootstrap/python_.ps1, tools/requirements.txt
#14076 and #14077 were blindly merged so tooling broke as pillow now requires python>=3.8. ~~Bumped python to 3.11.0 which is the highest version pygit2 currently has wheels for windows~~
=> Bump Python version

code/__DEFINES/loadout.dm
This PR clarifies that the smart pistol bundle includes smart goggles in the purchase
It is very unclear that the bundle includes the smart goggles as well, so this clarifies that.
:cl:
spellcheck: Changed the smart pistol bundle's name in the smart gunner vendor to clarify that it comes with smart goggles.
/:cl:
=> Clarifies Smart Pistol Vendor Purchase

code/datums/jobs/job/freelancers.dm, code/modules/clothing/head/head.dm, code/modules/clothing/suits/marine_armor.dm
Updates freelancers to 2023 standards.
Complete changelog:
Medkit pouch instead of injector pouch.
Synaptizine and Russian Red injector in helmet (With all new helmet storage)
All armors now have 2 general storage slots (The armors that didn't have storage previously)
^ These slots are filled with 2 grenades by default
All freelancers are given a tofuburger and a canteen. (They really like tofuburgers)
In the year 2023, our current freelancers are disgraceful, this gives them more flavor and modernizes them somewhat.
:cl:
balance: Freelancers have better loadouts slightly.
/:cl:
=> Updates freelancers to 2023

code/modules/mob/living/carbon/xenomorph/castes/king/king.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Replaces the current ranks of broodling - archon with hatchling - ancient
Hatchling
Young
Mature
Elder
Ancient
After talking to Tivi I came to the realization that the ranks that I gave xenos were just really bad in clarity, the young - ancient we had previous is alot more clear in what ranking a xeno is.
Yes, this will mean that Elder with have the old Ancient icon next to them, and ancient will have the old primo icon next to them. Will take some getting used to
:cl:
spellcheck: Xeno ranks now go hatchling > young > mature > elder > ancient
/:cl:
=> Changes xeno ranks to hatchling - ancient

code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
Switches gorger from being punished on weed, to being rewarded on weeds.
It makes no sense for a xeno to be punished for being on weeds.
This keeps the gorger top speed the same at -0.6
:cl:
balance: Gorger no longer gets slowdown from weeds
/:cl:
=> Remove gorger weed speed penalty

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/revolvers.dm, code/modules/projectiles/magazines/revolvers.dm
judge fire rate nerfed from .35s to .8s
normal judge round damage changed from 30 to 70 damage to compensate
(image credit of Wormgang/ClosetedSkeleton)
buckshot judge is absurdly broken. it has equivalent DPS to a DB, can fire for longer, can be dual wielded (for even HIGHER effective DPS), and can aim mode. Akimboing judges with buckshot will melt most T3s in less than a second. It's genuinely baffling to me that it took the community this long to figure out just how comically broken it is. This nerf should make it serve its intended role as a powerful sidearm with multiple options available to it without it just being a "lol I win" gun.
:cl: dopamiin
balance: the Judge now has a much longer fire delay, but its standard rounds are more powerful.
/:cl:
=> The Judge has been found guilty. (Walance)

_maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
I accidentally moved tcomms to an unpowered area, this is bad. It is now in a power area
Bug bad
:cl:
fix: Lawanka tcomms work now
/:cl:
=> Lawanka tcomms fix

_maps/modularmaps/big_red/bigredlzvar1.dmm, _maps/modularmaps/big_red/bigredlzvar2.dmm, _maps/modularmaps/big_red/bigredlzvar3.dmm, _maps/modularmaps/big_red/bigredlzvar4.dmm, _maps/modularmaps/big_red/bigredlzvar5.dmm, _maps/modularmaps/big_red/bigredlzvar6.dmm, _maps/modularmaps/big_red/bigredlzvar7.dmm, _maps/modularmaps/big_red/bigredlzvar8.dmm
Read title.
The map seems to flow better when the Marshall's disk is not there, with instead the first three original disk spawns in Admin, Engineering and ETA. Marshalls is not a place Marines want to be, so they often will die there slightly, retreat to FOB and are encouraged to initiate a 2 hour FOB siege, since they are right next to it. When there are the 3 original disks, there will always be a disk in ETA, and marines have to actually push past Medbay to get to the first disk. This may lead to a Medbay wipe, but at the least they are not encouraged to hold there and die like if there was a disk there.
:cl:
balance: Big Red's Marshall disk spawn is now removed from all modulars.
/:cl:
=> Removes BR's marshall's disk spawn from all modulars

code/game/objects/machinery/vending/vending.dm
Makes it so clicking the restock button by a vending machine will restock all the items near it as well.
Reduces clutter in prep. Makes it much easier to restock crap on the ground without having to manually clickdrag every single item in yourself.
:cl:
add: Vending machines restock items near it (instead of only on the same tile) when you click "restock"
/:cl:
=> Vending machines now restock adjacent items.

code/modules/projectiles/gun_system.dm
Fixed a bug that meant attached guns (notably the spotting rifle and masterkey) never got their accuracy updated, which led to comically low accuracy. Dunno how no one noticed this earlier.
Bug fix.
:cl:
fix: Attached weapons will now properly update accuracy when wielded
/:cl:
=> Attached gun fix

code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Restricts boiler from rooting in while resting
It was a problem when you try to press Rest in panic but hit the root and just keep lying in-place while getting killed.
Less caused skill issues (it already caused one)
:cl:
fix: boiler now can't root while resting.
/:cl:
=> Restricts boiler from rooting while resting.

code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
Its kinda annoying when you try to grab something and you gain absolutely no response and you don't know is the issue in you or with code or with something else.
It will be a little clearer why you can't grab something in agility mode in the middle of saving someone/or just trying to drag something.
:cl:
qol: There is now a balloon alert popping up when you try to grab something as warrior in agility mode.
/:cl:
=> Adds balloon alert for when warrior tries to grab something in agility mode.

code/modules/requisitions/supply_export.dm
Before:
T1 - 300
T2 - 400
T3 + Shrike - 500
T4 - 1000
After:
T1 - 150
T2 - 300
T3 + shrike - 500
T4 - 1000
Currently in game you need: 2 drone kills to get a teleporter, 1 runny kill to get a plasma cutter, 4 T1 kills to get a b18, etc etc etc
when comparing, 1 sentinel is worth 0.6 defilers, (or 1 defiler is 1.6 sentinels) which just doesn't even feel right. Killing 2 sentinels should not be netting more points than killing a single defiler
Ratio chart:
Basically with higher pop comes a significantly larger amount of T1's, many of which have their sole round contributions being feeding points to the marine team by dying in the strangest ways you could imagine.
This PR seeks to change the point distribution given by xenos to make securing T3 kills more important, while also making T1's …
=> Adjusts the amount of supply points lower tier castes gives

code/game/objects/effects/countdown.dm, code/game/objects/structures/campaign_structures/capture_objectives.dm
When there is a timer running on an objective, you can now see the time left above the objective.
Better visibility
:cl:
qol: Timers on campaign objectives are now visible above the objective
/:cl:
=> Overhead campaign objective timers

code/game/objects/items/weapons/twohanded.dm
Breaching axe attack speed is 15 instead of 11. This probably will make no practical difference since you're still going to crump a nerd in two hits. Mainly just did this because it seems weird a 2 handed axe can swing faster than a one handed sword.
You'll now have an additional 0.4 seconds to reconsider your life choices before a breaching axe caves in your skull for the second time.
:cl:
balance: Breaching axe attack speed reduced to 15 from 11
/:cl:
=> Breaching axe nerf

code/datums/gamemodes/_game_mode.dm
Read title.
https://github.com/tgstation/TerraGov-Marine-Corps/pull/13496
You can see my whole rant in there about it as a NW map, but with many bad maps it seems to work fine in HvH so a full removal is likely not warranted. Also allows it to be used for campaign and such
:cl:
del: Prison Station is now only voteable on HvH gamemodes.
/:cl:
=> Makes Prison Station a HvH only map

code/datums/fire_support.dm, code/game/objects/items/firesupport_binoculars.dm
Fire support binos in campaign now on examine display:
Firemode type
Uses remaining
Cooldown remaining (if on CD)
Access to info is good.
:cl:
qol: Campaign firesupport binos show current mode uses and cooldown remaining if applicable
/:cl:
=> firesupport bino QOL

code/modules/reagents/reagents/toxin.dm
Kills an evil operator (:) used in toxin code.
Also improves xeno neurotoxin sanity, as the current logic could cause damage higher than it should do under circumstances where close to the stamina damage cap (or especially if somehow above it)
: is a very evil operator and I will exorcise it wherever possible.
Neurotoxin not being able to be somewhat wacky with its damage under very specific circumstances is neat too.
:cl:
code: Removes an evil operator
fix: Xeno neurotoxin now has one less edge case. 
/:cl:
=> Removes an evil operator & improves some neuro sanity.

code/game/objects/machinery/cic_maptable.dm
A (probably) proper fix for maptables when their target z-level changes.
I have no idea why we have two version of the map table that are almost identical, but resolving that can wait for another pr.
Having a map stuck on your screen for the entire game is not ideal.
:cl:
fix: fixed an issue with map tables when their target z-level changes
/:cl:
=> Maptable fixes

code/datums/gamemodes/campaign/campaign_rewards.dm, code/datums/gamemodes/campaign/faction_stats.dm
Cleans up asset/reward code to be much more generic.
A lot of checks that started as ones offs ended up being common to many asset types, and generally made the code nicer to look and and deal with. Mainly by splitting the activated effect proc into a proper proc chain.
Better, less snowflake code
:cl:
code: Some code improvements to campaign asset code
/:cl:
=> Improves faction asset code

code/game/objects/structures/droppod.dm
Cleans up the code for the specialty HvH pod types, and fixes a few bugs.
Better/less buggy code
:cl:
fix: You can no longer store other drop pods in supply pods
fix: You can no longer fit endless mechs into a single clowncar mech pod
/:cl:
=> HvH pod code improvements

code/datums/gamemodes/campaign/faction_stats.dm
When you return to base after a mission ends, it now applies a 1 second stun, to prevent the hilariously common post teleport FF.
Getting shotgun pb'd by your friend by accident is guh.
:cl:
qol: A 1 second stun is applied when returning to base after a campaign mission ends
/:cl:
=> Campaign RTB stun

code/datums/gamemodes/campaign/campaign_rewards.dm, code/datums/quick_load_outfits.dm, code/game/objects/items/storage/belt.dm
spotting rifle was missing from the asset purchase.
Made the loadout use the same preloaded belt.
having ammo is good.
:cl:
fix: The smartgun asset in campaign now has targeting rifle ammo
/:cl:
=> Missing smartrifle asset

code/game/objects/effects/weeds.dm
changes resting weed node and sticky resin node description to fit their colors
why do the sticky weed node say it's red when it's blue
:cl:
fix: sticky weed and resting weed node examines made accurate
/:cl:
=> Resin node examine change

code/modules/projectiles/ammo_datums.dm
increases the bullet range of the SG62 target rifle up to 40, which is the same as normal marksman gun bullets
doesnt touch the spotting rifle range, that's still 20
if you stick a scope on the SG62, you currently cant hit anything in the last two rows of tiles when facing N/S because the bullet disappears before then, which seems unintuitive
if 40 is too high, I'd be willing to move it lower just so that it at least covers the range of what you'd see on your screen when using a t47 scope
:cl:
balance: sg62 bullets now have a max range of 40, equivalent to other marksman guns
/:cl:
=> increases sg62 target rifle bullet range

code/modules/mob/living/carbon/xenomorph/evolution.dm, code/modules/mob/new_player/new_player.dm
Adds fade in type fullscreen overlay on xeno spawn and evolution
Adds immersion
:cl:
add: Added fade in type fullscreen overlay on xeno spawn and evolution
/:cl:
=> Xeno fade in on spawn and evolution
