code/game/objects/effects/effect_system/smoke.dm
Drop bomb in smoke, visibility clears for a bit.
The smoke doesn't actually vanish so you'll still suffer any negative effects from it.
This in my original idea that no one in gaming has ever thought of before. donutsteel.
https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/376f6b27-0f84-4545-9a8b-631d4e50f830
Cool effect, a way to temporarily counter the visibility limiting power of dense smoke.
:cl:
balance: Explosions will now temporarily reduce the opacity of dense smoke caught in the radius.
/:cl:
=> explosions clear smoke

code/modules/admin/verbs/datumvars.dm, html/statbrowser.js
So in admin tools, we have certain "VV" buttons, found in debugging, player panels, etc. that used to let us View Variables on any atom. After TG statpanel got ported over with #13546, those "VV" buttons stopped working altogether. Some examples below:
Player Panel
SQDL2 Queries
Investigating a little, I decided to review the code changes in the statpanel, and after trying a few things (admittedly because I didn't wholly understand this section of code) I found that this small change made the View Variables menu come up again like before.
I didn't perceive any immediate bugs or runtimes, so I figured this was the solution I was looking for. I might be wrong, and I might've screwed something up. Maintainers please make sure I didn't break game thank you much love.
Bug fix good. Seriously, …
=> Fixes View Variables not opening via HrefToken

code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
Title
give hivemind the more available version of psychic cure for a more flexible heal with less cooldown time
:cl:
balance: hiveminds now have the queen's version of psychic cure
/:cl:
=> Gives hivemind queen-level psychic cure instead of shrike-level psychic cure

code/controllers/subsystem/persistence.dm, code/game/objects/machinery/mortar.dm, code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/structures/crates_lockers/largecrate_supplies.dm, code/modules/projectiles/guns/specialist.dm
Adds heavy weapon rotation to roundstart kit.
Effectively, the TAT and RR can get replaced by other stuff, everything totals up to an imaginary power level of like 12, with the TAT being 6 and an RR being 3.
Current buckets are listed down below, name of the tab is "Operational Weapons". Rerolls every 24.
<details>
- Default - Which is the current one of just TAT and 2 RRs.
- Fire and Forget - TAT, 8 disposables, and 2 Thermobarics.
- Autorail - Flak gun and Railgun (With no HVAP!)
- Shock - 2 RRs and an MLRS
</details>
Adds more variety to roundstart marine rollouts and thoughts, gives 40-60 point range weapons that are underused some more time in the spotlight and lets us test new roundstart marine powerkit rollouts to see how it affects the game, which is the main thing I'm interested …
=> Adds roundstart heavy weapon rotation.

code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
Read title.
Puppeteer does uh, a _bit_ too much damage and is quite hard to kill due to how many puppet they can have blocking them. And in the wonderful words of Bowl: 
:cl:
balance: Puppeteer's max puppets reduced to 3
/:cl:
=> Reduces Puppeteer's max puppets to 3

code/datums/components/harvester.dm, code/datums/status_effects/debuffs.dm
Protects Ravagers in Endure from getting slowed down by vali tramadol attack
Fixing an oversight/inconsistency between vali and bullets slowdown for ravager
:cl:
balance: Ravagers in Endure are no longer slowed down by vali tramadol attack
/:cl:
=> Ravager endure vali slowdown protection

code/datums/gamemodes/campaign/campaign_rewards.dm, code/datums/gamemodes/campaign/faction_stats.dm
Instant effect assets will correctly reproc when obtained.
Asset work proper is gud.
:cl:
fix: Instant effect assets correctly reapply if obtained multiple times
/:cl:
=> Instant asset fix

code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
What it says on the tin. Sets to the normal t2 threshold.
Bug bad.
:cl:
fix: Puppeteer now has the proper evolution threshold
/:cl:
=> Fixes puppeteer evolution threshold

code/controllers/subsystem/monitor.dm
So for some reason Bravemole used a length on a number making it always return 0, meaning the calculation for how much of a stat buff xenos would get would always be 150%.
In normal people terms this means that the autobalance stat buff will care about how many burrowed there actually are
Bug left unfixed for 2 years bad
:cl:
fix: Autobalance will now care about the ratio of alive xenos to burrowed xenos when giving out stat buffs
/:cl:
=> Autobalance Fix

code/modules/client/preferences_gear.dm
This pr renames the various headwear in the loadout pref from TGMC to surplus.
The loadout pref makes it seem like the headwear is from the normal headwear category from the surplus clothing vendor, when it's actually from the surplus headwear category. If it wasn't for the fact that surplus headwear is much weaker than normal headwear, and lacks storage, this wouldn't be an issue, however due to this, the headwear in the loadout pref is currently a noob trap. This clarifies that you are equiping the surplus headwear, rather than the better headwear.
:cl:
spellcheck: Replaced the "TGMC" in the loadout pref headwear names to "surplus". Actually hats in the loadout pref unchanged.
/:cl:
=> Renames Headwear in the Loadout Pref to Surplus.

code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
I had a couple of campaign loadouts with the wrong typepath, so some freelancer standards in erts were just having their headsets exploding on spawn. aylmao.
Bug fix.
:cl:
fix: fixed a couple of freelancer ert loadouts having the wrong headset
/:cl:
=> freelancer fix

code/game/objects/machinery/cloning/cloning.dm
Basically, when you clicked the console for the first time to check for a cloning pod to link to, it would check around the user (or well, worse, usr) instead of itself, which'd require you to stand next to both the console and the pod for it to work correctly.
This PR makes it check around itself instead (with the bonus of using orange instead of range)
Disproportionately annoying minor bug.
Fix man good.
:cl:
fix: The cloning vat console now actually checks around itself for clone vats to link to.
/:cl:
=> Fixes an incredibly minor issue with the clone vats console

code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
This was a regression from #12253, where MOB_SIZE_BIG xenos previously couldn't ventcrawl
:cl:
fix: Fix boiler being able to ventcrawl
/:cl:
=> Fix boiler being able to ventcrawl

code/modules/client/preferences_savefile.dm
Fixes #14230
:cl:
fix: Fixed prefs bluescreening when invalid gear is saved
/:cl:
=> Ensure saved gear is in gear_datums when loading prefs

code/game/objects/effects/spawners/random/misc_structure.dm, code/game/objects/items/frames/table_rack.dm, code/game/objects/structures/tables_racks.dm
Fixed tables teleporting to nowhere upon using wood/rods on them.
Also ship tables now give you metal, otherwise why would there be nometal subtype.
And also fixed transforming ship tables upon wrenching, installing and wrenching them again to gain metal, as you should.
Working dead feature.
:cl:
fix: You can now gain metal from ship tables without transforming them. They also won't transform upon construction now.
fix: Table frames no longer will teleport to nowhere upon using wood/rods on them.
/:cl:
=> Table fixes.

code/game/atoms_movable.dm, code/game/objects/obj_defense.dm, code/game/turfs/closed.dm, code/modules/mob/living/living_defense.dm
Another throw pr, time for 6 months of bugs.
Throwing things into dense turfs or objects now makes them bounce off in a semi realistic way.
Currently, the thrown thing bounces DIRECTLY back at the thrower, which although comical for grenade FF, makes absolutely no sense as you watch things bounce in bizarre and impossible ways.
Or if you prefer quality pictures, we get blue instead of red.
ALso some mild reorg of some related code. Everything about throwing is fucking god awful though and need more of a rework but that's for another day.
Additionally fixes some exploits regarding grabbing items before they bounce.
I swear there was a bug report or 2 to close, but I can't find them.
More realistic/less guh throw bounce mechanics
:cl:
fix: Objects will no longer bounce at impossible angles …
=> throw bounce change

code/modules/mob/say.dm
Adds ghost runechat
Makes it easier for communication between ghosts without your message getting lost in a sea of dchat and OOC
:cl:
add: ghost runechat
/:cl:
=> ghost runechat

code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm, code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm
Baneling can now watch other xenos while in pod
Makes waiting for respawn less boring
:cl:
qol: Baneling can now watch other xenos while in pod
/:cl:
=> Baneling can now watch other xenos while in pod

code/modules/projectiles/magazines/misc.dm
Allows you to grab bullets from boxes and packets from your inventory like you can with flare packs.
Majorly for the sake of convenience so you dont fumble reloads as much. 
:cl:
add: Take out bullets from packets and boxes now with right click.
:cl:
=> Can right click packets and ammo boxes

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Adds a rouny plushie to Pillar of Spring's CIC storage.
Rouny plushies are: cute, adorable, based, and should have never been removed from PoS in the first place.
I bring it back, to please the elder gods.
Jokes aside, there's not really much proper reason beyond incredibly minor fun.
:cl: Lewdcifer
add: (Re-)added a rouny plushie to Pillar of Spring. It is located in CIC storage.
/:cl:
=> Adds a rouny plushie to Pillar of Spring

_maps/map_files/Sulaco/TGS_Sulaco.dmm
Adds a rouny plushie to Sulaco's telecomms room.
Sulaco never had a rouny plushie, so here it is. Just incredibly minor fun for peeps that like plushies.
:cl: Lewdcifer
add: Added a rouny plushie to Sulaco. It's in the telecomms room.
/:cl:
=> Adds a rouny plushie to Sulaco

_maps/map_files/Arachne/TGS_Arachne.dmm
Adds a rouny plushie to Arachne. It's in far northwest maintenance, in the hidden hydroponics room.
Rouny plushie missing. Add rouny plushie. Elder gods satisfied.
Just some incredibly minor fun for plushie lovers.
:cl: Lewdcifer
add: Added a rouny plushie to Arachne. It's in the hidden hydroponics room, far northwest in maintenance.
/:cl:
=> Adds a rouny plushie to Arachne

code/controllers/subsystem/persistence.dm, code/game/objects/structures/crates_lockers/largecrate_supplies.dm, code/modules/reqs/supplypacks.dm
Fixes the flak gun infinitiy exploit by making it a crate.
Fixes req heavy las
Things being broken are bad.
:cl:
fix: You can't infinitely dupe flak guns in seasonal, they now spawn in a crate like TAT for consistency.
fix: Heavy laser is now the deployable variant in req for the deployable version.
/:cl:
=> Mounted gun req and seasonal fix

code/modules/projectiles/ammo_datums.dm
The problem is that tg derivatives have space as a `/turf/open` (aka density `0`), thus making space not exit early there.
I didn't really see any other clean solution, thus leading to the `istype` (since we want to have special behavior for just a single `turf/open` child).
Edit: while I was sleeping, I guess you could switch on the behavior of if a turf is constructable on or not, unsure how that's handled in tg code (or is it just density and blacklist)
fixes #13782
// still don't know why you guys log bugfixes like these
:cl:
fix: Xenos can no longer spit onto space turfs
/:cl:
=> Fix xenos resin spitting on space tiles

_maps/bigred_v2.json, _maps/deltastation.json, _maps/desparity.json, _maps/gelida_iv.json, _maps/ice_colony_v2.json, _maps/icy_caves.json, _maps/lawanka.json, _maps/lv624.json, _maps/magmoor_digsite_iv.json, _maps/orion_outpost.json, _maps/prison_station_fop.json, _maps/research_outpost.json, _maps/slumbridge.json, _maps/vapor_processing.json, code/datums/gamemodes/_game_mode.dm, code/datums/map_config.dm, code/game/objects/machinery/computer/nuke_disk_generator.dm
This is a purely backend change that will not affect anything until mappers make use of it.
This PR makes makes nuke disk candidates belong to at least one "set" of disks, which are defined in the json of the map.
How this works (For you, mysterious Mapper) is:
You set up the json by having a name-weight list for your disk set's name.
You add the disk candidates to the map, and adjust their "set_associations" list accordingly.
You are done.
If you would like to, you can also add sets to "force_for_sets" on the disk candidate (**aswell as having said sets in the associations of the candidate**), which will make that candidate always appear for the given sets. This is only useful for sets with more than 3 disks (aka "base rng")
Disk sets must be at least 3 candidates. If more than 3, it …
=> Expands on random disks by adding disk sets

code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
I did not properly test my previous PR and turns out you could only watch xenos if you suicide from ability. If you died from normal death you still couldnt watch other xenos.
fix
:cl:
fix: baneling now can overwatch xenos if died from normal death
/:cl:
=> baneling overwatch 2

code/modules/projectiles/guns/mounted.dm
removes barrel charger from MG-28
With next to 0 aimmode slowdown encouraging mini-scope usage, this will make the gun a bit worse for being entirely used as an offscreen aimmode weapon
:cl:
balance: Removes barrel charger from MG-27
/:cl:
=> Removes barrel charger as an attatchment option for MG-27

code/modules/reagents/reagents/medical.dm
Per title. The healing is 2 per tick.
Gives another rare niche to Alkysine, and also gives ungas a way to clear hearing damage commonly caused by explosions and the like. This is an incredibly minor change with minimal impact on balance anyway, at least in my opinion.
:cl: Lewdcifer
balance: Alkysine now slightly heals ear damage.
/:cl:
=> Alkysine now heals ear damage

code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
Defender can no longer combo with a king to make a gamebreaking mega combo attack as it literally circles the glob ATATATATATATAT'ing a target until the server chugs.
https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/604dbdc0-f841-4e46-b849-eb5b3308563a
:cl:
fix: fixed a rare defender bug
/:cl:
=> No more ultimate instinct from defender charge

code/datums/components/jump.dm, code/datums/status_effects/debuffs.dm
You can no longer jump while stunned or buckled.
Fixed being able to attack while stunned with a weapon strapped to your hand.
Crucially, you can still do both while simply lying down.
Fixes #14168
Stunned jump funny.
Stunned attack wew.
:cl:
fix: You can no longer jump while stunned or buckled
fix: You can no longer attack with a strapped weapon while stunned
/:cl:
=> Jump and stun fix

code/game/objects/machinery/cic_maptable.dm
You can no longer interact with map tables when you shouldn't be able to.
I forgot to pass an arg, whoops.
Fixes #14290
Spooky things bad.
:cl:
fix: fixed map table interaction checks always passing
/:cl:
=> Map table fix

_maps/map_files/Fort_Phobos/Fort_Phobos.dmm, _maps/map_files/Iteron/Iteron.dmm
So it turns out the way cameranets are setup means headset cameras are not actually picked up at all to begin with, until chunks are already generated AND the headset cam moves enough to update chunks.
This gets around that. Also nice for command to be able to look around their base I guess.
Funny cameracode
:cl:
fix: fixed a camera issue in campaign
/:cl:
=> adds cameras to campaign ship maps

code/modules/projectiles/projectile.dm
Shooting sentries will now check its IFF flag.
Currently, all deployed guns (including sentries) only checked the IFF flag of the mob manning it, if any.
As far as I can tell, this is an oversight.
IFF working is good.
:cl:
fix: Sentry IFF flags are correctly checked when IFF projectile try to hit them
/:cl:
=> Sentry IFF fix

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Fixes #14265
Crest toss tosses the victim from the CRUSHER'S turf instead of teleporting the victim behind you or tossing from their turf (forwards).
This means some cases where previously you couldn't throw someone because there was a wall behind you will now allow a throw (into the wall, but still).
Crest toss now properly respects the intended throw range, as the victim is actually thrown from the xeno's turf.
The victim now has the hover flag when thrown, so they'll properly fly over cades instead of relying on funny snowflake checks. This also means they won't burst into flame when thrown OVER a flaming turf.
Previously, the throw TARGET was based on the range from the crusher. But the victim being on a different turf meant that max range was actually further than this. This caused …
=> Crusher toss fix

code/datums/gamemodes/campaign/campaign_mission.dm
Minor fix to mission ends.
Signal unregistering was happening after key objects were getting cleaned up, meaning extra map text messages were being spammed saying any remaining objectives had been destroyed etc.
No gameplay change.
Random messages bad
:cl:
fix: Fixed campaign missions ending causing unintended notifications in some instances
/:cl:
=> mission end wrap up fix

code/game/objects/items/explosives/plastique.dm, code/game/objects/structures/campaign_structures/destroy_objectives.dm
C4 now as a minimum 30 second timer on campaign destruction objectives (you can still set it longer if you wanted to for whatever reason...)
Less cheese opportunity, gives more time for counter ~strike~ play.
:cl:
balance: C4 now takes 30 seconds at minimum to detonate on campaign objectives
/:cl:
=> C4 timer increased for campaign objectives

code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Updates the description of Earth Riser to mention that the pillars can be launched by click-dragging them in a direction.
Apparently you can do this, and there is no info in-game about this being the case. This will help inform players about this ability, especially useful considering this is a relatively new caste.
:cl:
spellcheck: Changed the description of Behemoth's Earth Riser to mention the click-drag launching function.
/:cl:
=> Updates Earth Riser Desc

code/game/objects/structures/campaign_structures/deploy_blockers.dm
Drop pod blocker in campaign had an invisible sprite. This one is technically still a placeholder, but eh.
Invisible object bad.
:cl:
fix: Drop pod blocker objects in Campaign are no longer invisible
/:cl:
=> Fixed an invisible sprite

code/modules/projectiles/gun_attachables.dm
V34 stock now increases wielded slowdown by 0.05.
Super tiny change, but the gun is just slightly too quick to run with. Added to the stock instead of the gun so there's (a very small) extra point of difference for why you might want to not use the stock. It's still probably a bad idea though.
Brrt gun very slightly slower
:cl:
balance: V-34 stock now increases slowdown by 0.05
/:cl:
=> Micro v34 adjustment

code/modules/projectiles/guns/pistols.dm
It was deleting just `GUN_WIELDED_STABLE_FIRING_ONLY` and forgot about `GUN_WIELDED_FIRING_ONLY`
Because of which you couldn't fire from one hand after detach.
There is also a bug that you can't shoot from it after detach without dropping and picking it up, but I have no idea why it happens.
Less bugs.
:cl:
fix: fixed plasma pistol not shooting from one hand after detaching it as attachment from somewhere.
/:cl:
=> Fixes plasma pistol not losing attachment trait on detach.

code/game/objects/items/reagent_containers/glass/bottle.dm, code/game/objects/items/storage/firstaid.dm, code/game/objects/machinery/vending/vending_types.dm
Adds Syringe cases to the "Chemistry Equipment" Section of the NT Med.
These can hold at most 180u if you fill it with 3 bottles, which is still a lower capacity than a pill bottle.
On top of that, you can't directly drink liquid out of a bottle, so you need to either keep the syringe it comes with, or carry an autoinjector that you can refill.
:cl:
add: Syringe cases in the NT Medplus
/:cl:
=> Adds syringe case to NTMED

code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
- Removes all screenshaking from Behemoth's ability warnings, and from abilities in most cases.
- Fixed a bug where Landslide would displace adjacent allies. This is only meant to happen if said ally is directly in front of you.
- Fixed a bug where Landslide could destroy resin doors. Instead, resin doors will now open, letting the charge continue normally.
- Reduced Primal Wrath's screen distortion a little. Additionally, this effect no longer applies to allied xenos besides yourself.
Bug fixes good, clarity always appreciated, and screen changes too wack in excess.
:cl: Lewdcifer
del: Behemoth's ability warnings no longer cause screen shaking.
del: Behemoth's abilities have lost screen shaking in various cases.
qol: Reduced Primal Wrath's screen distortion a little. Additionally, this …
=> Various minor Behemoth tweaks (and a fix)

code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm, code/modules/mob/living/carbon/xenomorph/castes/behemoth/behemoth.dm, code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
- Reduces Behemoth's maximum health from 800 to 750.
- Reduces Behemoth's Wrath gain from 50% of damage received to 30%.
- Reduces the maximum amount of Wrath that can be attained from 800 to 750.
Behemoth was a tad bit too tanky, and Primal Wrath was being used much too often.
:cl: Lewdcifer
balance: Behemoth's maximum health reduced from 800 to 750.
balance: Behemoth's Wrath gain reduced from 50% of damage received to 30%.
/:cl:
=> Nerfs Behemoth's health, nerfs Primal Wrath gain

code/datums/gamemodes/crash.dm
Blacklists Big Red from being enabled on Crash gamemode.
The map is too big for crash. Silos are too far apart, disks can be either too close or too far from Canter.
Crash is meant more for low pop and smaller maps play a lot better, so Big Red cannot stay.
:cl:
balance: Disables Big Red on crash gamemode
/:cl:
=> No more BIG RED Crash

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
While Psychic Shield is being channeled, temporarily increase warlock's push resistance.
This increase (one tier of push resistance) still allows for 'big' mobs to push warlock and cancel the channel.
These 'big' xenos include: Behemoth, Boiler, Crusher, Gorger, Hivelord, King, Praetorian, Queen, Ravager. Roughly 30% of all xenos.
Tested a bit locally with a warlock and crusher, seemed to work all correctly.
Right now it's basically a death wish for a warlock to use the shield in a crowded hallway, as you'll get pushed by an ally and suddenly your ability is on cooldown and your allies will take unexpected damage. 
Or, someone's inadvertent misstep will make you absorb damage that instantly kills you (hence this spite PR).
:cl:
qol: Warlocks can only be pushed by big xenos while …
=> Adds push resistance to warlock while channeling Psychic Shield

code/modules/clothing/head/head.dm
It already has a sprite, and it's quite strange that it isn't set.
Less bugs.
:cl:
fix: Slouch hat is now visible on your head.
/:cl:
=> Fixes slouch hat not having on mob sprite.

code/datums/components/chem_booster.dm
Makes Vali require 1u of Synap instead of 3u to receive the effect of the activation.
This feels more like a fix, because it seems whoever made vali confused the 3u injection of a synap injector to mean that 3u of synap was injected.
A single dosage of Synaptizine is 1u, so vali should be using that value.
:cl:
balance: Vali uses 1u of Synaptizine instead of 3u
/:cl:
=> Makes Vali require 1u of Synap instead of 3u.

code/datums/components/harvester.dm
A harvester weapon with Kelotane applies some sunder, I plugged in the value of a slug shotgun, but if thats too high/low I can adjust.
Kelotane is currently really bad, and I think this differentiates it from Tramadol.
You would use the Tram for the slowdown, and Kelotane for the armor damage.
I think this would give both chems a fair niche.
:cl:
balance: Harvester weapon with Kelotane causes sundering
/:cl:
=> A harvester weapon with Kelotane applies some sunder.

code/__DEFINES/action.dm, code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Shows the amount of respawn charges you currently have via maptext.
Removed some vestigial ravager code from before the primo rework.
Helps people know this feature even exists without reading a throwaway sentence on the wiki.
<p float="left">
<span>Banelings can make more informed decisions on when to gas tad and induce malding in ungas.</span>
</p>
:cl:
add: Added a 'respawn charge' indicator for banelings on the explode ability.
code: Removed some vestigial ravager code from before the primo rework.
/:cl:
=> Adds respawn charge indicator to the baneling explode ability

code/game/atoms_movable.dm
Title.
During Lumi's throw changes, the wall impact was changed to have a "default" speed of 5 if no argument was passed.
Surprise, the impact **never** had the speed passed as impacting things happens in bump (which is outside of the throw itself).
Thus, all impacts were handled as if they were executed with a speed of 5 (resulting in five times higher damage in most cases).
This PR fixes that by preserving current thrown speed.
Unfortunately, has to be a movable var due to no viable vectors to pass it existing (tgmc does not have thrownthing datums like base tg, which would handle this).
args actually being passed seems kinda useful.
:cl:
fix: throw_impact() now actually receives the speed arg.
/:cl:
=> Fixes throw impact not respecting speed

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Some change about a year or two ago made runner evasion ignore pointblank shots (likely backend change in how firing is routed causing the signal evasion listens to to get reached on PBs, or something), despite pointblanks previously bypassing evasion & the author of the ability even stating PBs were intended to counter it in their original evasion PR.
This PR fixes that.
Fixes #14256, despite Lumis insistence on PB interactions "having never existed" (you can see me test it on a commit before it broke, if you look at the issue's comments, in case you happen to be sceptic)
Evasion is very strong, even more so after its "qol" changes that made you able to true chain it (extending duration without it having ran out first).
PBs used to be the only counter against a runner just sitting in …
=> Runners are once again subject to Pointblank shots (PBs)

_maps/map_files/icy_caves/icy_caves.dmm
Attempts to fix LZ2 to make it more appealing to choose for Marines and removes some ice rocks that made cover for xenos to easy. Adds more crash spawns for canterbury and removes the spawns where it could crash right beside the fog which makes life bad for marines, also removes it from crashing right beside disks. Moves the Disc spawn in Monorail area to be in the medbay/morgue area, i believe this to be best for both sides.
extends the fog in north monorail a bit more. also made the nuke hallway of death west spawn for xenos, further away to be more fair for marines.
This should hopefully make crash in Icy caves more bareable, and also make nuclear-war there better with the option of a more open LZ2 
:cl:
balance: Lz2 is more open and less cluttered.
balance: cantabury no longer crashes …
=> Icy cave balance changes

_maps/map_files/Arachne/TGS_Arachne.dmm
:cl:
fix: Deleted stacking pipes on Arachne.
/:cl:
=> Deletes stacking pipes on Arachne.

_maps/map_files/Sulaco/TGS_Sulaco.dmm
:cl:
fix: Deleted stacking pipes on Sulaco.
/:cl:
=> Deletes stacking pipes on Sulaco.

_maps/map_files/Theseus/TGS_Theseus.dmm
:cl:
fix: Deleted stacking pipes from Theseus.
/:cl:
=> Deletes stacking pipes from Theseus.

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
:cl:
fix: deleted stacking pipes on Pillar of Spring.
/:cl:
=> Deletes stacking pipes on Pillar of Spring.

_maps/map_files/BigRed_v2/BigRed_v2.dmm, _maps/modularmaps/big_red/bigredlibraryvar1.dmm, _maps/modularmaps/big_red/bigredlibraryvar2.dmm, _maps/modularmaps/big_red/bigredlibraryvar3.dmm
There is a now a chance for a disk to spawn in Library on BR. However, there will **_always_** be a disk in ETA now.
Also removes one crash spot since it would krill library disk
People like variety and I figure it is worth testing out. The old marshalls disk had the issue of being way close to FOB leading to FOB camping, this might have the issue of being too far out the way if there isn't an admin disk. An alternative would to also hardset Admin disk, and have engi/library disk swap, but needs testing first.
:cl:
add: Big Red now has a library disk
balance: Big Red ETA disk is now guaranteed. 
/:cl:
=> Adds Library disk to Big Red, hardsets ETA disk.

code/modules/mob/living/living_defense.dm
Fixes xenos resisting fire not removing the fire overlay.
Removed a couple of now redundant child procs.
Fix
:cl:
fix: fixed xeno fire overlays getting stuck when resisting
/:cl:
=> Xeno fire fix

code/modules/mob/living/living_defense.dm
Being thrown into a wall now has a sound effect.
The damage inflicted now actually respects armour (no throwing death squad into a wall until they die, sorry)
Also wall impacts may not have even worked in the past, apparently I fixed it incidentally during one of my throw pr's.
Fix and audio feedback
:cl:
fix: fixed wall throws not respecting armour
soundadd: added a sound effect when you're thrown into a wall
/:cl:
=> Wall hit changes

code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm, code/modules/mob/living/carbon/xenomorph/castes/beetle/beetle.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
Some outliers in throw speeds have some.. questionably high numbers.
To avoid death, this amends them to be in reasonable ranges (for abilities I assumed intent was to finish the throw in one tick, thus they're set to be slightly above range of the ability)
Who knew that fixing something broken for a long time might open up a rabbit hole.
:cl:
fix: Some throw speeds that were extremely high have been normalized.
/:cl:
=> Very quick speed pass

code/__DEFINES/action.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm, code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Amends various mistakes done in #14099 due to changes I didn't commit.
- All cooldown sounds are now played locally, meaning only the user will hear them. Previously, surrounding players could also hear them, which I had meant to change.
- Re-added the Savage cooldown. I completely missed this. It's the same as before (30s).
- Savage cooldown now has a duration indicator on the ability icon.
- Fixed an issue with Savage's plasma cost being half of what it should actually be.
- Fixed an issue where Runner's Evasion duration HUD indicator would persist sometimes. The indicator will now correctly disappear when it should.
- The sound changes were something I meant to do because it allows Runners and Hunters to engage in stealthy activities a bit better.
- I accidentally made Runner stronger …
=> Amends missing changes in Runner stuff, fixes an issue with Evasion's HUD indicator

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
If the client wasn't in the larva queue, there's no need to do the whole process of removing them and letting them know they've been removed.
Annoying getting incorrect messages
:cl:
fix: You should no longer get the 'You left the Larva queue.' message when returning to your corpse.
/:cl:
=> Better larva queue removal handling

code/game/objects/structures/window.dm
Have you ever felt unsatisfied by hurling people through windows?
No more.
Throwing people into windows now inflicts damage like wall throws, and the damage to the window scales with mob size.
Additionally, if a throw is strong enough to break the glass, the thrown thing will now continue to travel instead of just stopping pathetically.
Line up 3 windows and hurl a nerd through all 3 for combo damage!
Is fun.
:cl:
balance: Throwing things into windows will no longer stop the throw if the window breaks from the impact
balance: Throwing mobs into windows hurts like a wall throw
balance: Throwing mobs into a window scales damage to the window based on mob size
/:cl:
=> realistic window impacts

code/datums/gamemodes/_game_mode.dm, code/datums/map_config.dm, config/maps.txt
What it says on the tin. Debugdalus and Vapor Procecssing have the fastest load times; if someone is compiling for the first time, that is what they want. I understand this PR will likely be highly controversial; please put some thought into your comments as I know Grayson reads them and takes them into consideration; we all play on this map, after all.
**MEGA RANT INCOMING**
_Preface_
LV is one of the most polarizing maps in TGMC. On one hand, people love the theme of a jungle hell (hey, I do too) that is wet and hostile. On the other hand, and to which I believe is more important, is the map is absolutely abysmal for our current HvX gamemodes. The foundation it is built on it rotten and irreparable, from an age old that has next to no resemblance to the game we play today.
_Distress …
=> Locks LV to HvH votes only. Sets the default maps to Debugdalus and Vapor Processing

code/modules/mob/dead/observer/observer.dm
It wasn't checking for `istype` at all
:cl:
fix: Fix runtime in spatial agent shortcut
/:cl:
=> Fix runtime in spatial agent shortcut

code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
title
I accidentally blew myself up because i pressed E instead of W right after i spawned
:cl:
qol: Banelings can no longer explode before shutters unless they have a pod placed.
/:cl:
=> Stops banelings from exploding if it's before shutters and they don't have a pod

code/datums/gamemodes/crash.dm
Crash used to have the same blacklist from gamemode.dm, but that changed. All future maps blacklisting maps from HvX will have to do it in both areas.
Bug fix good. Totally blame Xander.
:cl:
fix: LV is no longer voteable on Crash.
/:cl:
=> Fixes LV being voteable on Crash

code/game/objects/effects/aliens.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm
If you have a stronger acid, you can now click on weaker acid directly to upgrade it.
Fixes a bug with acid upgrading not transferring the existing ticks
Huge acid QoL, especially for shit like flares and their animated sprite
Bug fix good
:cl:
add: If you have a stronger acid, you can now click on weaker acid directly to upgrade it.
fix: Fixed acid upgrading not inheriting the existing melt progress
/:cl:
=> If you have a stronger acid, you can now click on weaker acid directly to upgrade it.

code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
same type beat as #13796
i don't really want to write the signal shit for this right now, i have other bugs to fix
Fix #14179 
Fix #13795
uhh this also might address bug I've seen where banelings can go into crit negative despite not dying as such
:cl:
fix: Banelings will no longer bring sticky nades back to their pod upon dying.
/:cl:
=> Fix: Banelings will no longer bring sticky nades back to their pod upon dying

code/game/objects/items/storage/pouch.dm
So, `update_icon()` was getting called before the pouches were getting filled in the `Initialize()`, so I just put it in the `LateInitialize()` so it first loads up the stuff inside the pouch and only then updates it's look.
Fancy pouches in EORD.
:cl:
fix: Full pouches now don't look empty on spawn.
/:cl:
=> Fixes pouches looking empty on spawn while they aren't.

code/game/turfs/walls/resin.dm
Increases resin wall bullet armor from 60 to 70
Someone requested this PR
considering how ammo is infinite and how recently people have just been using aimmode MG's to shoot down walls, I dont think this is something that is as big as you say it is.
The optimal play for marines right now is to get 3 MG's who either carry an ammo box with them or better yet, use the free req beacon helmet module to have RO send them ammo all on aimmode to shoot down walls. This is the meta rn because:
zero risk of flamer FF or losing a PC
you can cover your teammates who do get close to the walls because you can just stop shooting the walls and aim at the xeno
hard to counter since any xeno that peaks will just get mowed down by the 3 MG's on aimmode 8 tiles away
the reason we got to this is from a many …
=> Increases resin wall bullet armor

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Defiler can inject eggs with neurogas from any range and this PR fixes it by adding an adjacent check to the ability.
Fixes an exploit and now the ability makes logical sense.
:cl:
fix: Defiler can only inject eggs adjacent to them.
/:cl:
=> Fix Defiler inject egg range

_maps/shuttles/tgs_canterbury.dmm
Read what is on the tin. Marines literally couldn't open it.
This blast door was placed without buttons. Even if it worked, I really don't see why you would want it. The blast doors on the bigbury make more sense.
:cl:
fix: Removes unopenable blast door on smallbury CIC
/:cl:
=> Removes random CIC blast door on smallbury

code/game/objects/machinery/squad_supply/supply_beacon.dm, code/game/objects/machinery/squad_supply/supply_console.dm
The req launch console now does not allow sending crates to supply beacons that are not on the ground. Thus when tad launches with beacons onboard, an oblivious RO will not deliver B18's to the hive. Also when tad lands, crates will be sent to the right place.
RO does not know when tad launches and has to ask the pilot if they moved every time a crate needs to be sent. This is silly.
Unlike antennas, beacons are static objects and should update their drop locations when moved.
Fixes issue #13039.
:cl:
qol: req can be confident that crates to a supply beacon on tad will arrive on tad.
fix: A supply beacon on tad will work after tad moves.
/:cl:
=> Filter Supply Beacon Drop Locations if its in the Air

code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/faction_stats.dm, code/game/objects/structures/campaign_structures/deploy_blockers.dm, tgui/packages/tgui/interfaces/CampaignMenu/CampaignOverview.tsx, tgui/packages/tgui/interfaces/CampaignMenu/index.tsx
Added some extra info for the current mission. Mission params details any special factors that effect the mission. Currently is only used for Tele/droppod blockers, but other things can be plugged or, or specific info can be manually added for particular missions.
More info good.
:cl:
qol: Campaign missions will specify if a teleport or drop pod blocker is active in the current mission
/:cl:
=> Campaign: Mission parameters

code/game/objects/items/storage/reagent_pouch.dm, code/game/objects/machinery/vending/marine_vending.dm
Adjust the default mix to have half as much trama.
Also adds in a variant of the pouch that spawns empty in the clothing vendor.
Tram metabolizes at half the rate, so you would eventually get tram OD if you keep using a 1:1:1:1 mix, so this addresses that.
:cl:
add: Added an empty reagent pouch to the clothing vendor.
balance: Adjust reagent pouch to 2:2:1:2 BKTT
/:cl:
=> Adjust reagent pouch ratio

code/__DEFINES/campaign.dm, code/__DEFINES/dcs/signals.dm, code/datums/gamemodes/campaign/campaign_assets.dm, code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/faction_stats.dm, code/datums/gamemodes/campaign/rewards/disablers.dm
Fixes asset activation checks not actually checking for the activatable flag. (you can no longer activate hostile assets!)
Added more feedback messages for various reasons why you couldn't activate an asset.
Messages now go to the person pressing the button instead of no one/the faction leader.
Fixed a bug that stopped disabler assets working correctly.
Fixes good, player feedback good.
:cl:
qol: failure to activate a campaign asset now provided more feedback to the user
fix: fixed a few issues with activating some campaign assets
/:cl:
=> Campaign asset fixes

code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Some of this code was redundant and I combined the checks into one statement. 
Also made it respect things with move resistance infinity (decals, etc.)
Bug bad.
:cl:
fix: Shrike vortex doesn't throw around things it shouldn't anymore (decals)
code: Smol shrike vortex code improvement
/:cl:
=> Cleans up shrike vortex code + fixes it throwing decals around

code/datums/gamemodes/infestation.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm
So during some rounds, people realized some weird behavior with the larva queue. Looking into runtimes, @Barnet2 saw this:
I've tried to correct this as seen in files changed. I don't know if this is the correct solution, and I'd appreciate it if @ZeWaka could look at this change to make sure it's okay. Otherwise you may slap me in the face.
Fixes a bug with larva stuff.
:cl: Lewdcifer
fix: Fixed some weird behavior in the larva queue.
/:cl:
=> Attempts to fix an issue with larva queue

code/game/objects/items/storage/belt.dm
Adds base pill bottles to light medical belt
Since marines have access to pill bottles now, I think it's fair that they should fit in the light medical rig belt.
:cl:
balance: Light medical belt holds pill bottles
/:cl:
=> Adds base pill bottles to light medical belt

code/modules/projectiles/guns/specialist.dm
title
This might be harder to shallow compared to removing miniscope on RR, though it had been argued that RR is stronger than SADAR and the fact that an offscreen weapon with high burst damage is not okay on the receiving end of said weapon (xenomorph players).
Would like to see maintainer's thoughts on this. If they say no to this, then this PR is a precedence for having miniscope on RR.
:cl:
del: remove miniscope on recoilless rocket
/:cl:
=> remove miniscope on recoilless rocket

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Per title. The HUD wasn't updating properly when Evasion was cancelled by something like fire, stagger, etc.
Bug fix good.
:cl: Lewdcifer
fix: Fixed an issue with the Runner HUD not updating properly when cancelled.
/:cl:
=> Fixes an issue with the Runner HUD not updating properly when cancelled

code/modules/projectiles/guns/mounted.dm
You no longer need to windup the FK-88 to fire it.
This used to be here since I had it since you didn't need to anchor it at the start of design, but ended up making it a requirement. So this is pretty necessary to make it more 'useable' in most scenarios considering the setup time of like half a minute.
:cl:
balance: You no longer need to wind up the FK-88 to fire.
/:cl:
=> FK-88 no longer has windup.

code/modules/mob/living/carbon/carbon_stripping.dm
`runtime error: Cannot read /image/progdisplay/friendly (/image/progdisplay/friendly).loc`
https://github.com/tgstation/TerraGov-Marine-Corps/blob/f5c8b3882c27faf0be9f9c5792b339247300c984/code/__HELPERS/mobs.dm#L122-L124
`needhand` was forgotten in the do_after args when strip menu was ported from newer tg, but it still worked anyway on 515 while being broken on 514
```dm
/image/a
/world/New()
var/atom/a = /image/a
world.log << a.loc // null on 515, on 514: Cannot read /image/a (/image/a).loc
```
=> Fix a runtime in stripping hands

code/modules/organs/limb_objects.dm
Decapping no longer bypasses the respawn timer.
Fixes #14444
Exploit bad.
:cl:
fix: Getting decapped should no longer bypass the respawn timer
/:cl:
=> Decap respawn fix

code/game/objects/items/explosives/grenades/marines.dm
allows stickies to be applied to the user, and only the user, from in hand
Quality of life and makes the stickies such as cloaker much more usable, and trailblazer to be used offensively by a marine who may be wearing fire armor and such. 
:cl:
qol: Allows grenades to be self stickied, instead of having to be applies by others
balance: Self-applied stickies allowing one to use them directly
/:cl:
=> Allows sticky grenades to be applied to self from your hand

code/modules/mob/living/carbon/xenomorph/castes/king/king.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Young - 10 hours (the same)
Mature - 25 hours (instead of 50)
Elder - 70 hours (instead of 100)
Ancient - 175+ (instead of 300)
Apparently they were too long, and the people nagging at me for it were probably right since it is a per caste thing, and people change caste around alot during a game. This is a copy from CM's xeno ranks outside of name.
:cl:
qol: Reduced xeno rank playtime requirements
/:cl:
=> Reduces xeno rank playtime requirements

code/modules/reagents/reagents/medical.dm
Sets russian red effect_str to 0.7
This is a 30% reduction to the healing and the cloneloss.
After the bugfix in this PR https://github.com/tgstation/TerraGov-Marine-Corps/pull/13926
The issue with russian red is that the numbers were too high, so this tones down the numbers slightly.
:cl:
balance: Russian red is 30% less effective
/:cl:
=> Russian Red Nerf

code/game/objects/items/storage/reagent_pouch.dm
draw_mode = 1
so it defaults to drawing on left click
TBH this thing only holds 1 item, it makes sense to pull out the item when you click the pouch.
I just forgot this existed when I added it.
:cl:
qol: reagent pouch defaults to draw mode enabled (left click to draw)
/:cl:
=> Sets reagent pouch draw_mode to default on

code/game/objects/items/storage/pouch.dm
I forgot that `LateInitialize` should be said to activate, in result icon just didn't update and for the moment of last pr I assumed it did the work. :Clueless:
I tested it properly this time, and unless some artifacts occure or occured, it should work fine. Stuff is still in needed pouches, it's empty when empty on spawn, full when full on spawn.
:cl:
fix: pouches now properly update, for real this time.
/:cl:
=> Fixes pouches not updating icon on spawn.

code/__DEFINES/dcs/signals.dm, code/datums/components/stun_mitigation.dm, code/datums/quick_load_outfits.dm, code/game/objects/items/jetpack.dm
Adds a heavy jetpack to HvH.
I will likely lock the upgrade behind something, but doesn't hurt to let people test it for now.
1. Travel speed is higher (critical for flying directly through windows)
2. Distance penalties for high slowdown are significantly lower (i.e. you can jetpack further with heavy armour/tyr/shield etc)
3. 5 second CD instead of 10
4. **If you are not on help intent, you will smash into mobs, stunning them briefly** (or yourself)
And some tweaks/improvements to jetpack code, only player facing change is using a jetpack will now actually tell you how much is left on the cooldown, if its not ready.
:cl:
add: Added a heavy lift jetpack to HvH, capable of travelling further with a heavy load, or smashing directly into mobs
qol: Jetpacks say how long is left on CD if you …
=> Heavy jetpack

code/game/objects/items/cocoon.dm
Victim is necessary for processing
runtime bad
:cl:
fix: Cocoon doesn't try to process after it releases its victim
/:cl:
=> Cocoon doesn't try to process after it releases its victim

code/_onclick/hud/new_player.dm, code/_onclick/hud/screen_objects/menu_text_objects.dm
Fixes the many runtimes related to lobby buttons, namely everything related to it screwing up for players who join before everything is finished initialized. Basically we prevent the `MouseEntered` proc from firing if it's not initialized because it can happen before the sound subsystem is even initialized and `Click` because god do I not want to risk it. 
Would test merge this just in case it doesn't work.
Runtimes bad, lobby buttons not being broken good.
:cl:
fix: Fixed lobby button runtimes and bugs (you shouldn't get 'Unknown Character' anymore)
/:cl:
=> Fixes the lobby button runtimes

code/controllers/subsystem/monitor.dm
Stalemate should no longer give 80-100 larva.
x5 mult is insane
:cl:
balance: stalemates no longer provide insane amounts of larva
/:cl:
=> stalemate adjustment

_maps/map_files/Campaign maps/nt_base/nt_base.dmm, code/__DEFINES/dcs/signals.dm, code/game/objects/effects/tele_blocker.dm, code/game/objects/items/blink_drive.dm, code/game/turfs/space.dm, code/game/turfs/turf.dm, tgmc.dme
Changed blinkdrives to check a turf proc to see if a turf can be teleported to.
This sends a signal, and added an effect object to listen to that and make turfs unable to teleport to.
Teleporting to the objective on Base rescue to bypass the mission bad.
Telegib good.
:cl:
fix: Can no longer teleport to the objective on Base Rescue in campaign
/:cl:
=> Teleblock changes

code/__DEFINES/mode.dm, code/datums/gamemodes/crash.dm, code/game/objects/items/binoculars.dm
Railgun isn't even supposed to be in crash. IC wise there is no ship in orbit to actually give railgun support at all, and its jsut a coder thing why the ship actually exists (this could be fixed however).
Railguns can also be used to blowup silos which is a hassle for admins.
Unintended feature.
:cl:
balance: Ship railgun is no longer available in Crash
/:cl:
=> Crash railgun removal

code/controllers/subsystem/minimaps.dm, code/modules/mob/living/silicon/ai/ai.dm
One happens when AI first spawns in, so obviously `old_turf` is gonna be null, in this case we should update ofc.
Other is just the tgui stat panel forgor to remove one of the `stat()s`
Runtime bad!
:cl:
fix: Fixed some AI runtimes
/:cl:
=> Fix AI runtimes

code/modules/ai/ai_behaviors/ai_behavior.dm, code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm, code/modules/mob/living/carbon/xenomorph/death.dm
Removed the random delays with attacks, it caused a whole bunch of stuff taking damage after deletion because we can't guarantee it'll still exist when the time to attack is up, uncool.
Otherwise this is just a bunch of signals are async thing where the spiderling got gibbed/otherwise deleted when trying to do stuff.
Stop clogging up muh runtime logs.
:cl:
fix: Fixed a bunch of spiderling runtimes
/:cl:
=> Fix a bunch of spiderling runtimes

code/modules/reqs/supplypacks.dm
ignore the branch name please 
Things should be named properly I think
:cl:
fix: fixes the names of the FK-88 and ATR-22 ammos in req
/:cl:
=> Renames these two artillery piece ammunition packs in req

code/game/objects/machinery/vending/marine_vending.dm
600->200 HEDPs.
600 grenades is enough for the entire game, encourages incredible amounts of spam, reduces logistical need for anyone to actually properly manage grenades RO wise, and generally was just an old overreaction to making grenades much more accessible.
At 200, it should still ideally be highly accessible alongside support grenades, but not quite overbearing to use if the force isn't properly longterm supplied.
:cl:
balance: Amount of free roundstart HEDPs reduced to 200 from 600.
/:cl:
=> Reduces roundstart grenades from 600->200

code/modules/reqs/supplypacks.dm
Most grenade boxes (other than wp/razor so I don't get owned) are cheaper overall.
cloak, smoke, frag, stickes are 310
incend, trail, m15s are 350
I didn't touch WP/Razorburn
Makes grenades reasonably priced, pair up with #14525 if you want.
:cl:
balance: Most grenade boxes are now cheaper, lower tier grenades have went from 500 to 310, and higher tier grenades to 350. Razorburn and white phos are untouched.
/:cl:
=> Makes most grenade boxes cheaper.

code/modules/client/client_defines.dm, code/modules/client/preferences_toggles.dm
Intended as a temp thing during the transition like 3 years ago so this is a bit overdue
:cl:
del: Removes the context menu toggle
/:cl:
=> Removes the context menu toggle

code/game/objects/items/storage/fancy.dm
Changes the slots from 25 to 18
Because someone made the chemrette package larger than the cig one but it uses the same sprite changes, when you go over 18 things inside it goes invisible. Theres no real reason that its larger so this pushes it back down.
I havent tested this, beyond failed every time I tried to run it and I dont know what the vscode version of how to host and run the game is, but the change is so minor there is no way its going to break something. Its literally changing slot sizes. Id appreciate if someone told me the updated method of testing things since the warnings that refused to allow it to run were about how I need to use vscode to do it and I have zero idea where to do that. That or open and run it while testing something else.
:cl:
fix: fixed a few things
/:cl:
=> Chemrette invis fix

code/modules/client/client_procs.dm
We have to co-exist with the other ss13 servers in the overall landscape and making clients downgrade builds conflicts with that. known bad versions can be blacklisted but telling clients not to use newer builds is reckless and puts clients in a hard place where they have to decide between servers that don't work with the older builds and servers that don't work with the newer builds.
=> Remove max client version

code/__DEFINES/mobs.dm
Changed the armour threshold for getting gibbed by a devastating explosion.
Previously you needed more than 5 bomb armour (i.e. not be naked). You now need 90 bomb armour (hiln on medium at minimum)
Gibbing is cool.
:cl:
balance: Humans are now gibbed by dev explosions unless they have 90+ bomb armour
/:cl:
=> Increased chance to gib humans with explosions

code/modules/projectiles/ammo_datums.dm
Uses get_dist_euclide instead of get_dist, for checking stun range.
Like throw range, stun range was wonky when it came to diagonal. Unlike throws which had worse range than they should, diagonal stuns go further then expected.
This is particularly noticable on the slug shotgun for example.
The player facing change is that instead of a square of turfs around you in stun range, its now (roughly) a circle, so something like a slug shotgun will in many diagonal cases now need to be one turf closer to the target than how it is currently.
Less wonky stuns at long range on diagonals
:cl:
balance: Projectile stuns no longer work at a greater distance then expected when fired at diagonal angles
/:cl:
=> Euclide range on projectile stuns

code/modules/projectiles/gun_attachables.dm, code/modules/projectiles/guns/rifles.dm
removes rds compatibility with mg60
you can buff to 100% faster firing with bipod and RDS; so this would make using aimmode a bit more of a tradeoff -- you want to shoot past allies, your shots have to be a little slower, etc. you can also still combo bipod with aim order to reach 100% faster firing, this just makes that maybe require a little more strategy for command to make the decision to use aim order for that benefit.
open to editing
:cl:
balance: removed the ability to use the red-dot sight on the MG-60
removal: the MG-60 can no longer take the red-dot sight as an attachment
/:cl:
=> removes rds compatibility with mg60

code/game/objects/machinery/doors/poddoor.dm
Talking about these and the ones up in lambda
Marines can break these comically easily, meanwhile xenos need a crusher, bit guh. You have to walk all the way around half the map if you happen to get a modular combo up in lambda, which I'm really not a fan of.
:cl:
balance: Makes the two tile pod door (namely used on big red) acidable
/:cl:
=> Makes the two tile pod door (namely used on big red) acidable

code/game/objects/structures/dropship_equipment.dm
Per title. Maintainers agreed that this was a better alternative than #14551.
If you check the PRs that I made before this one, you'll get a better image, but tl;dr is CAS ordnance shouldn't be fast enough to require inhuman reactions from xenos.
:cl: Lewdcifer
balance: CAS ordnance travelling times are no longer affected by spaceship orbit
/:cl:
=> CAS ordnance travelling times are no longer affected by spaceship orbit

code/datums/gamemodes/infestation.dm
This pr clarifies in the corruption text of AI bioscans that the cause of said corruption is caused by the current elevation of the ship.
Let's new players know that they could get a clearer scan if they were on a lower elevation.
:cl:
spellcheck: Adds clarification to the AI's bioscan that corruption is caused by the elevation of the ship.
/:cl:
=> Clarifies AI Bioscan Corruption Is Affected By Ship Elevation

code/modules/projectiles/ammo_datums.dm
adds max_range to sg153 bullets; this increases range of spotting rifle from 20 to 40, which matches the main sg62 and the DMR
the underbarrel spotting rifle doesn't shoot as far as the main sg62 rifle after i increased sg62 range. it actually just has the normal base bullet max_range without this PR. you can, while using the sg62, currently, hit things that are at the edge tiles of your scope, but if you try to dual-fire with the spotting rifle, your second bullet won't hit things that far out.
versatility thing, i guess. people dont take the sg62 for Reasons and often compare it to just a DMR; hopefully this can help lean a bit more into the niche of the unique spotting rifle ammos setting this gun apart from the DMR. im also not that into the practice of having to manage two different …
=> increases the range of sg153 bullets to 40 from 20

code/game/objects/items/explosives/plastique.dm
C4, or plastique explosives, no longer require a multitool to disarm, instead only requiring to click on the C4 to remove it.
Currently, C4 requires a multitool to disarm, meaning the only job that can reliably disarm the C4 are engies. Considering that both FC and SLs can acquire C4, this means that most of the time if a C4 is misplaced, it is just gonna destroy whatever (or whoever) it was planted on. This at least makes it easier to avoid accidents with C4.
:cl:
balance: C4 (Plastique explosives) no longer requires a multitool to disarm.
/:cl:
=> C4 (Plastique Explosives) No Longer Require A Multitool To Disarm

code/__DEFINES/conflict.dm, code/__DEFINES/dcs/signals.dm, code/game/objects/items/radio/radio.dm, code/modules/clothing/modular_armor/attachments/modules.dm
Alternate PR to #14594 
The antenna module loses its access to req beacons like in the referenced PR, but in exchange can reduce the interference of caves by one stage.
To do this, it first needs to be configured with a 30 second sync timer (which **does not** require you to stand in place), after which it will remain on indefinitely (barring unequipping it).
Reason for this channel is to avoid people "oceloting" an Antenna helmet to wear it when talking then take it back off. This makes it more of a commitment, and is a one-time thing as you very rarely have any reason to take your helmet off (never, in fact).
This means that in shallow caves, you will talk / hear like outside, and in deep caves you will hear like outside, but talk with some interference.
You also still have access to …
=> The Antenna module now improves comms in caves, loses req beacon

code/game/objects/items/reagent_containers/hypospray.dm
Changes the current acronym for hypervene in a hypo from Ht to Hy.
No other hypervene container uses Ht, so making the hypo use Hy makes it consistent with other hypervene bottles/injectors.
:cl:
spellcheck: Changed the acronym for the hypervene hypo to Hy
/:cl:
=> Changes Hypo Hypervene Acronym to Hy

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Banished objects that are solid (have density) will now push out any living beings on their tile before returning, if possible. This can potentially be used offensively (to force targets off a tile), but less to cheese like the previous state allowed.
Aims to counteract a specific technique relying on ending up on the same tile as certain solid objects. You shouldn't be on that tile, and telegibbing would be very rude to anyone, so this it is.
:cl:
balance: Banished solid objects now push out any living beings on their return tile (if possible) before returning.
/:cl:
=> Slightly reduces the cheese level of Wraiths

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Psycrush now targets turfs specifically.
Although instant casting/triggering is fine and intended, tracking mobs isn't really intended for this ability.
Should make it harder to bully a lone guy with a rapid cast.
:cl:
balance: Psycrush now only targets turfs
/:cl:
=> Warlock Psycrush nerf

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Psyblast/lance now requires the target to be in screen range to successfully cast.
What this means is if you target a mob, if they get off screen quickly enough the ability will fail to cast.
This doesn't make that much difference to blast consider it already has shorter range, but makes lance less guh to deal with as you get offscreened.
You can of course still jsut aim at a turf to line up the offscreen, but you lose the autotracking.
Less oppressive lance tracking shenanigans.
:cl:
balance: Psylance and Psyblast will now fail to cast if their target moves off screen
/:cl:
=> warlock psyblast nerf

code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
This fixes spiderlings stopping their attack after one slash, now they'll only stop if the widow is not adjacent to them
TerraGov-Marine-Corps/pull/13713 had broken it by removing a check, without this it's much harder to have them dealing damage
:cl:
fix: Widow's spiderlings will no longer just constantly stop attacking their target, now the widow will have to move away from the spiderlings and only then they will stop
/:cl:
=> Fixes spiderlings not continuing their attack

code/modules/screen_alert/command_alert.dm
Orders will now show what job sent the order, rather than being ambiguous.
Knowing who sent the orders can influence whether or not you would want to follow em. This makes it clearer, especially in the case of conflicting orders.
:cl:
add: Orders will now show what job sent them in the orders' header.
/:cl:
=> Orders Show Job Title of Order Sender

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Snatch now spends plasma only on success.
I guess it could be called a balance change, but you're like spending plasma even after you're told that the target has nothing to steal.
Less confusing stuff, which is confusing just to be confusing.
:cl:
fix: Snatch now spends plasma only on success.
/:cl:
=> Snatch now spends plasma only on success.

code/game/objects/structures/droppod.dm
Some small changes to pod behavior, mainly around orbit levels.
Pod drop time is now modified by orbit level. 7, 10, 14 seconds for low, medium, high orbit (current is 10 sec).
Pods now have a small degree of scatter, also varying by orbit level (note it still has all the safety checks etc, so it won't launch you into a wall or whatever). 2, 4, 6 tile radius for low, medium and high orbits.
Mass pod drops have a slightly larger scatter also based on orbit. Instead of just a flat 5 radius, its 5 + orbit level. It still increases based on number of pods dropping however.
Muh immersion from orbit levels, or something.
The mass drop specifically though I wanted to increase regardless, since you tend to get a very dense area of pods currently.
:cl:
balance: Drop pod drop time varies with orbit …
=> Drop pod orbit adjustments

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Basically, if you loop yourself while being on fire, and extuinguish yourself after this, you will be on fire after rewind.
Consistency.
:cl:
add: Time Shift now rewinds fire stacks.
fix: Wraith's Time Shift now properly rewinds sander.
/:cl:
=> Time shift now rewinds fire_stacks and on_fire.

code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/magazines/rifles.dm
Skirmisher now has 40 magazine capacity.
Makes the skirmirsher a more enticing choice, it currently suffers from terrible ammo economy overall as it has significantly worse magazine capacity compared to other weapons in the same overall class (BR, StormR, AK, etc) so this should help it stand out more.
:cl:
balance: Skirmish Rifle has been buffed to 40 magazine capacity instead of 30.
/:cl:
=> Skirmish Rifle buff, 30->40 mag cap

code/datums/keybinding/human.dm
Why C? Because it's unused on humans. Also space to jump is more intuitive for newer people I feel like.
Keep in mind if you aren't connecting for the first time your keybinds won't be affected by this!!!
2 different things on the same key by default is a bit questionable.
:cl:
qol: Rebound unique action to C by default (instead of space)
/:cl:
=> Rebinds unique action to C by default (instead of space)

code/controllers/subsystem/minimaps.dm
This means miners, gens and other stuff shows up on the minimap 
bug bad
:cl:
fix: Miners, gens and other stuff should actually show up on minimap now
/:cl:
=> Fix earlyadd minimap icons not showing up on minimap

code/datums/gamemodes/campaign/missions/base_rescue.dm, code/game/objects/machinery/computer/nt_access.dm
Time for each segment is changed from 1.5 minutes to 1 minute.
Time to activate each segment is changed from 15 seconds to 5 seconds.
Total round time increased from 12 minutes to 15 minutes (this is still in addition to the period before the timer starts, I forget what it is).
Also just removed a basically unneeded var.
This mission is very difficult for the SOM, hopefully this makes it a little less guh.
:cl:
balance: Made the timings for the base rescue mission easier for SOM
/:cl:
=> Base rescue mission time tweaks

code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/faction_stats.dm, code/game/objects/machinery/computer/nt_access.dm
Currently, ally jobs are ghosted at mission end, and everyone else is sent to spawn.
Changed to now have ALL players ghosted at mission end.
Additionally, all dead humans are qdel'd at mission end. Maybe good for perf when you no longer have 500 dead bodies with radios etc, but mainly QOL so overwatch isn't flooded with an ever growing list of KIA's.
Aims to fix two problems:
Players having half their kit missing after a mission etc
Players looting lots of good shit, letting winning teams snowball significantly in some cases
:cl:
balance: Campaign: All players are ghosted at the end of a mission
/:cl:
=> Campaign mission end ghostize

code/_onclick/ai.dm
What is says on the tin. You will be able to ping the baneling's pod as AI.
Consistency?
:cl:
add: You can now ping the baneling pod as AI.
/:cl:
=> Allows ai to ping alert the baneling pod.

code/game/objects/machinery/squad_supply/supply_beacon.dm
Don't assume you're always deployed when you change Z level
bug bad
:cl:
fix: Fixed a supply beacon runtime
/:cl:
=> Fix a supply beacon runtime

code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/faction_stats.dm
Returned the 'teleport to base' feature at mission end for anyone not on the mission z-level (i.e any shipside roles or people that didn't have a chance to deploy).
Also added a z-level check on cleaning up bodies. Mainly to avoid badmins accidentally messing with job slots if they have dead bodies on an admin z-level or something.
It was somewhat redundant to ghost them, let you dupe binos, and caused some minor bugs with overwatch.
:cl:
qol: Campaign: Players still on their home z-level will be teleported to spawn instead of ghosted at mission end
/:cl:
=> Follow up mission end QOL

tgui/packages/tgui/interfaces/CampaignMenu/index.tsx
(Probably) fixes the BSOD that seems to occasionally pop up in the campaign status panel.
I can't reproduce it to verify however.
BSOD essentially bricks the mode.
:cl:
fix: Fixes an uncommon BSOD on the campaign status screen
/:cl:
=> Campaign BSOD fix

_maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm, _maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm, _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm, code/datums/gamemodes/campaign/missions/asat_capture.dm, code/datums/gamemodes/campaign/missions/fire_support_raid.dm, code/game/objects/structures/campaign_structures/misc_structures.dm, tgmc.dme
Changes to both factions firesupport missions as well as ASAT capture for SOM.
Consolidates objectives into clusters to make them actually practical to defend, and added barricades (via landmark) to these clusters to help the defending team a bit more.
The SOM firesupport mission (i.e. marines defending) isn't clustered due to how the map is more linear in its design, so its instead two 'paths' of objectives for SOM to follow.
These missions were absurdly difficult for the defending team, this should make them a bit less wack.
:cl:
balance: Made fire support and ASAT capture missions in campaign easier for the defending team
/:cl:
=> Defensive mission walance

code/modules/projectiles/mounted.dm, code/modules/projectiles/sentries.dm
Salt pr? Maybe.
Seriously this thing is like, a gun laid on the ground. I can walk over a crate of these things just lying around but I can't jump over one when they set it upright?
This also allows xenos to counter emplacements when they get right into melee range by just shoving the marine off or by just standing on the gun; you can't shoot right on your tile when wielding an emplacement. Granteed, that first thing might keep the second thing from being a factor, but whatever.
:cl:
balance: Emplaced guns (such as the mg27) may now be jumped over.
/:cl:
=> Emplacements may be hopped over

_maps/map_files/BigRed_v2/BigRed_v2.dmm, _maps/modularmaps/big_red/bigredsouthwestetavar4.dmm
Deleted duplicate wooden barricade.
Also deleted the light tube which is floating in nowhere.
Consistency.
:cl:
fix: deleted some garbage on Big Red.
/:cl:
=> Deletes some garbage on big red.

code/game/objects/machinery/vending/marine_vending.dm
When moving the magnum to the SL vendor during it's release, MJP forgot to take it away from the special crash weapons vendor. This seems like an oversight, lest maintainers have their reason for letting it stay in.
:cl:
fix: Fixes the Magnum being available in Crash outside of the SL vendor.
/:cl:
=> Removes the magnum from the crash weapons vendor

code/modules/mob/inventory.dm
Prime example is baton staying in the hud layer despite being dropped
Bug bad
:cl:
fix: Stun batons should not ominously float above everything in the game after someone without access tries to pick it up anymore
/:cl:
=> Fix items being weird with layers if equipped is overriden the wrong way

code/game/objects/items/reagent_containers/glass/bottle.dm, code/game/objects/machinery/vending/vending_types.dm
Updates the description of the bottle of Doctor's Delight to describe it's effect and side-effect Also moves it to the Valhalla tab of the vendor.
Let's new players know what the chem does if they grab it from the Nanotrasen MedPlus. Also It's not available from the normal vendor, only Valhalla vendor, meaning it would fit better in the Valhalla tab.
:cl:
spellcheck: Updated the description of Doctor's Delight in the Nanotrasen Medplus to describe it's effects.
balance: Moves the Doctor's Delight reagent bottle to the Valhalla tab of the vendor
/:cl:
=> Updates The Bottle of Docter's Delight's Description And Moves It To The Valhalla Tab

code/game/objects/structures/dropship_equipment.dm
Changes the layer of rear attach points to be below objects, rather than above them. Note this does not affect larva hiding under them.
Items that are dropped on the same tile as rear attach points tend to be lost, due to being completely obscured by the attach point. This makes it less likely to lose items due to the layering. Also makes it look a bit less ugly by preventing items from sticking out from under the attach point.
:cl:
qol: The rear attach points will now layer under items, rather than over them.
/:cl:
=> Changes Layer of Rear Attach Points.

_maps/shuttles/tgs_bigbury.dmm, _maps/shuttles/tgs_canterbury.dmm
Title
Maintenance changes include making the tiles more consistent, moving some vendors, adding some glass panels around vendors where they were inconsistent, fixing some chairs facing the wrong way, fixing a duplicate air alarm, fixing floating intercoms.
The HSG is way overkill for crash, you really don't need it to hold canter considering the marine access to vendors. It makes canter even more comically holdable. 
:cl:
qol: Misc fixes to both crash ships
balance: The HSG nest has been removed from crash ships
/:cl:
=> Remove HSG nest from canter + some canter maintenance

_maps/map_files/Arachne/TGS_Arachne.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm
title
Sucklaco moment. Turns out sulaco and thesus just got four extra OBs for completely free (???)
also gives every shipmap the same amount of solid fuel (35)
:cl:
balance: Standardizes shipmap OB and solid fuel count
/:cl:
=> Standardizes OB rooms on all shipmaps

_maps/map_files/Iteron/Iteron.dmm, code/game/objects/structures/droppod.dm
The drop pod refresh asset will actually refresh mech, supply and sentry pods as expected.
Working thing good.
:cl:
fix: Campaign: Fixes the drop pod refresh asset not correctly replacing the specialty pods
/:cl:
=> Campaign: drop pod refresh fixes

code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
pt 2/4 minyun changes, scorpion can now spit weak acid on items and can be given plasma 
scorpion was a class that desperately could use plasma prior but couldnt be given plasma for ??? reasons. it was annoying af to anyone playing and anti-teamwork 4 no raisin
Scorpions being allowed to melt items means they can flares and other items, letting actual castes to do important things and leaving melting to a minion. Right now a main niche of minions is being used exclusively for the boring task of slowly dragging flares because no one wants to actually deal with them. This will assist with game monotony (AI can't acid btw)
:cl:
qol: Scorpions can now be given plasma
add: Scorpions can put weak acid on obj's
/:cl:
=> lets scorpion be given plasma + can now weak acid items

code/modules/reqs/supplypacks.dm
Title
This was unintended in the mjp pr + I see no reason why the backpack shouldn't be in req in case you lose it
:cl:
add: Added the SG-85 powerpack to req
fix: Fixes SG-85 ammo bins not being in req
/:cl:
=> Fixes the sg-85 ammo bin missing from req and adds it's powerpack to req

code/__HELPERS/icons.dm
Ports https://github.com/tgstation/tgstation/pull/76395
Fixes a roundstart runtime that nearly always happens. This means that people go in with runtime breakpointing disabled and may end up ignoring runtimes when developing. Bad juju
=> Adds file cycling for icon2base64 (#76395)

code/game/objects/structures/mineral_doors.dm
Title.
They weren't showing correct color in map preview, this fixes it.
Bugs bad.
:cl:
fix: Fixed mineral doors not showing correct coloring in map preview
/:cl:
=> Fixes flat door icons

code/modules/mob/living/carbon/xenomorph/castes/mantis/abilities_mantis.dm, code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
pt 4/4
This swipe does literally 25 damage to unarmored humans. all this swipe did was make it near impossible for non-AI mantis can actually manage to use it
mantis swipe now takes 250 plasma, and mantis now has 500 plasma total but can be given plasma by teammates
I think this one is pretty obvious. Mantis is by far the worst minion caste in the game right now for a player to use. While AI tend to hit a majority of their swipes, players struggle to hit anything at all even with proper positioning and getting the jump on marines due to the nature of the ability. If you've ever played mantis, you know what I'm talking about. The swipe is a 25 damage move to unarmored opponents (with basic mantis slashes already being 20), but its nearly impossible to hit cause of the windup. This makes …
=> Removes the delay from mantis swipe + they can be given plasma now

code/__DEFINES/jobs.dm, code/datums/jobs/job/marines.dm, code/datums/jobs/job/shipside.dm
What it says on the tin. Previously, FC was worth as much as a shipside role despite being the groundside commander. This really does not make any sense.
Consistency more or less; FC is atleast worth as much as a normal unga bunga. Also, a define used on an unused job is bad.
:cl:
balance: FC is now worth one marine in terms of larva points.
/:cl:
=> Makes FC worth as much larva points as a marine, removes unused specalist define

code/game/objects/structures/orbital_cannon.dm
When the OB is fired, an alarm for those not near the OB will play, their screen will shake, and a flavor message will be sent to their chatbox for even more Flavor™
Cinematics are cool.
:cl:
add: Firing the OB will play an alarm for those outside of hearing distance of the cannon and on ship, shake the ship, and send out a flavor message.
/:cl:
=> More OB cinematics for shipside

code/game/objects/items/weapons/blades.dm, code/game/objects/items/weapons/twohanded.dm
See title. The claymore previously used the much quieter sound and the machete a much louder sound. 
Sound consistency, big damage = big sound while small damage = small sound. Should hopefully make claymore users feel more powerful while also making xenos more aware of how hard they are being hit.
:cl:
balance: Swapped claymore and machete sounds.
/:cl:
=> Swapped Vali Claymore and Machete Sounds

code/game/objects/items/scanners.dm
Currently, health analyzers behave incorrectly once an ssd individual is scanned, and will display every scanned human as ssd thereafter. This is because the ssd data is never updated except if the target is ssd, thus never overwriting this information if it no longer applies.
This fixes that.
Fix man good.
:cl:
fix: Health analyzer SSD information is no longer wrong.
/:cl:
=> Fixes health analyzer SSD display

code/game/objects/items/reagent_containers/hypospray.dm
Prevents injecting synths and combat robots with hypos.
Attempting to inject synths/robots currently causes the hypo to "inject" 0 units. This makes it clearer to new players that robots can't use chems, and is overall less confusing.
:cl:
fix: Synths/Robots no longer can be injected with hypos.
/:cl:
=> Prevents Hypo Injecting Synths And Combat Robots.

code/datums/jobs/job/job.dm
Title. This just needs an early return, since this happens normally.
Less pointless runtime messages.
:cl:
code: cleaned up an unneeded crash message
/:cl:
=> Remove unneeded crash message

code/game/objects/items/reagent_containers/hypospray.dm
The recent PR that made robots / synths uninjectable as a whole instead of catching the case later post-change-requests assumed all injected targets would be carbons, which led to invalid var accesses on anything that was not a carbon.
This fixes that by only checking for carbon things if the target is actually a carbon.
Fix man good.
:cl:
fix: Injectors can inject (valid) non-carbon things again.
/:cl:
=> Fixes injections when targeting non-carbon targets

code/game/objects/structures/dropship_equipment.dm
Renames the rear attach point to interior attach point.
Why it makes some sense for the alamo, the current name isn't that good when it's in places like the middle of the tad. This has it make more sense, name-wise
:cl:
spellcheck: Renamed rear attach points to interior attach points
/:cl:
=> Renames The Rear Attach Point

code/game/objects/structures/dropship_equipment.dm
This pr changes the layer of rear attach points so that weeds, weed nodes, and xenos such as larvas and runners can no longer hide under them.
Doesn't make much sense considering it's supposed to be a panel attached to the floor why xenos can hide under them, which usually means marines aren't gonna check under the panel for xenos. Plus the only way you can tell a larva is under it is right clicking it, due to larvas being completetly covered by the rear attach point. Weeds weeds are for a similar reason.
:cl:
balance: Weeds and xenos can no longer hide under rear attach points
/:cl:
=> Xenos/Weeds can no longer hide under Rear Attach Points

.github/workflows/ci_suite.yml
\> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/cache@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
=> Fix CI deprecation warns

_maps/map_files/Arachne/TGS_Arachne.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm, _maps/shuttles/tgs_bigbury.dmm
What it says on the tin; the food vendor in question being the one you always eat at from prep. In addition, some ships were RNG on whether you would have a cigarette vendor at all (or in the bigbury's case, no cig vendor) which could jeopardize if you had chemrettes or not. This remedies that, too.
Convenience for the RO/Marine that wants to grab food quickly and send it down without the hassle of a long walk to a special vendor.
:cl:
add: Marine Food Vendors are now present in all requisition areas.
qol: All ships now have cigarette vendors guaranteed to spawn in
/:cl:
=> Adds Marine Food Vendors to all ship requisition areas + makes sure all ships have cig vendors

code/modules/clothing/modular_armor/attachments/cape.dm, code/modules/clothing/modular_armor/attachments/modules.dm
Makes it so that the chameleon cape, badge, kama, and reflective belt doesn't require holding your uniform in hand to attach.
Considering all of these are cosmetic, there's not much reason to not let them be attached to uniform you are currently wearing except that it makes it tedious. This makes it so you can play dress up without having to constantly drop everything on the floor from taking your uniform off.
:cl:
qol: The chameleon badge, cape, kama, and reflective belt can be attached to uniforms that are being worn.
/:cl:
=> Makes Chameleon Badge, Cape, Kama, and Reflective Belt Easier to Equip

code/__DEFINES/conflict.dm, code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/projectile.dm
Readds AMR lase slowdown on hit.
Removes flak ammo slowdown as lase slowdown is back in entirety.
AMR lase slowdown was not an issue, the gun was heavily reliant on it to be competieve as a sniper support weapon as it has subpar damage compared to something like an autosniper for much higher cost, considering the lase already serves as some sort of warning this was just an unnecessary nerf, the penetration nerf was enough.
:cl:
balance: Readds AMR lase hit slowdown.
/:cl:
=> AMR lase slows down again on hit, flak slowdown removed.

code/_onclick/hud/ai.dm, code/_onclick/hud/ghost.dm, code/_onclick/hud/hud.dm, code/_onclick/hud/human.dm, code/_onclick/hud/parallax.dm, code/_onclick/hud/picture_in_picture.dm, code/_onclick/hud/radial.dm, code/_onclick/hud/rendering/plane_master.dm, code/_onclick/hud/rendering/render_plate.dm, code/_onclick/hud/screen_objects/screen_objects.dm, code/_onclick/hud/screen_objects/text_objects.dm, code/_onclick/hud/xeno/hivemind.dm, code/_onclick/hud/xeno/larva.dm, code/_onclick/hud/xeno/xeno.dm, code/controllers/subsystem/minimaps.dm, code/datums/status_effects/debuffs.dm, code/game/objects/items/storage/storage.dm, code/modules/buildmode/buildmode.dm, code/modules/buildmode/buttons.dm, code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_health_procs.dm, code/modules/mob/living/living_verbs.dm, code/modules/mob/living/silicon/ai/multicam.dm, code/modules/mob/mob_movement.dm, code/modules/screen_alert/misc_alert.dm, code/modules/vehicles/mecha/_mecha.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm, code/modules/vehicles/mecha/mecha_ui.dm
Title. A bunch of this was shitcode and icon states/overlays were handled outside of the relevant procs.
This should fix stamina being invisible when you first spawn in (non existent icon state as the default lol), also some alerts being named weirdly.
This is less shitcode. 
:cl:
refactor: Cleaned up hud icons and overlays
/:cl:
=> Hud icon and overlays cleanup

code/modules/projectiles/guns/energy.dm
Basically title, you can no longer attach lasguns (and also Tesla) to laspouches.
I originally meant for this to also add the ability to charge mags but then I tested it and remembered you can... Already do that.
The ability to attach your pouch to your gun is absurd because it basically works as a super extended mag, which were removed for a reason.
:cl:
balance: You can no longer attach lasguns nor tesla to lasgun pouches for magazine use.
/:cl:
=> Laser pouch can no longer be used as a magazine for Lasguns or Tesla guns.

code/modules/projectiles/ammo_datums.dm
See title.
Saltpr? Maybe.
These guys have special slowflake plasma types that they either can't generate innately, or only generate up to a certain point. Going up against a pepperball user as rav means losing your ability to charge, which you have to generate yourself by slashing marines, which is a bit unfair.
This problem goes double for gorger, who doesn't generate ANY plasma by herself and requires standing still in order to generate blood. In addition, she's slow as hell which means any retard can basically completely drain her plasma gauge if they even barely try. Not fun.
:cl:
balance: Ravager, Gorger, and puppeteer will no longer be affected by pepperball
/:cl:
=> Ravager and Gorger are now pepperball immune

code/_onclick/hud/screen_objects/screen_objects.dm, code/modules/mob/inventory.dm, code/modules/mob/living/carbon/carbon_helpers.dm, code/modules/mob/living/carbon/carbon_stripping.dm
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14473
Fixes items disappearing if you try to equip them in the hands of someone who's lying down
Fixes the strap button appearing on items without straps
Fixes the strap button do_after being stackable
Fixes the warning message not being sent to the user when an item fails to equip
Fixes a misc runtime related to the gun ammo counter trying to put itself on the screen of a mob without a clien
Bug bad
:cl:
fix: Various fixes to the strip menu, check the PR
/:cl:
=> Fixes various strip related bugs (+ an extra runtime)

code/__DEFINES/skills.dm, code/modules/mob/living/carbon/human/human_attackhand.dm
CQC skill now adds a tremendous 5 (five) extra damage instead of 1 (note punch damage is still an rng number, so this only increases the max damage).
Adds a max damage floor, so negative cqc won't make you do literally nothing.
Adjusted the punch stun chance so it won't be quite so comically high with good CQC. (unchanced odds with normal CQC)
For reference
Needed for upcoming campaign changes.
:cl:
balance: CQC skill now does +5 max damage instead of +1
/:cl:
=> CQC skill tweaks

_maps/map_files/BigRed_v2/BigRed_v2.dmm, _maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm, _maps/map_files/LV624/LV624.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Research_Outpost/Research_Outpost.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm, _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm, _maps/map_files/debugdalus/tgs_debugdalus.dmm, _maps/map_files/generic/Admin_Level.dmm, _maps/map_files/oscar_outpost/oscar_outpost.dmm, _maps/map_files/slumbridge/slumbridge.dmm, _maps/modularmaps/big_red/bigredengineeringvar1.dmm, _maps/modularmaps/big_red/bigredengineeringvar2.dmm, _maps/modularmaps/big_red/bigredengineeringvar3.dmm, _maps/modularmaps/big_red/bigredengineeringvar4.dmm, _maps/modularmaps/big_red/bigredofficevar2.dmm, _maps/modularmaps/lv624/robotics.dmm, _maps/shuttles/big_ert.dmm, _maps/shuttles/tgs_bigbury.dmm, code/game/objects/effects/spawners/random/engineering.dm, code/game/objects/items/shards.dm, code/game/objects/items/stacks/sheets/glass.dm, code/game/objects/structures/window.dm, code/modules/codex/entries/stacks_codex.dm, code/modules/reqs/supplypacks.dm
Fixes #14638 
there was possibly a fix i could do without editing map but it would change more stuff so i just did this and it wanst any much big change.
basically since merging stacks is done by the stack attackby() any glass that was of the subtype of ../sheet/glass ( all glass stacks) would be able to merge the glass sheet into it, this solves it because the only subtype of ../sheet/glass/glass is ../glass/large_stack as far as i found
Fixes bug yay
:cl:
fix: glass can't turn into other glass types by merging it into a reinforced/phoron glass stack
/:cl:
=> Fix glass being able to be merged into any other glass type

code/modules/mob/living/carbon/human/life.dm
Aims to resolve the two cases explained in the linked issue.
For the disconnect, client was replaced with mind as that is more reliable (and should also get removed if you take a body.
For decaps, an additional check was added that either requires the head to be present, or for the target to not have a reattachable head.
Was done there instead of removing the trait on reattach as that would cause potential issues with other cases of DNRing.
Fixes #14745 
Fix man good.
:cl:
fix: It should be less likely for you to go DNR in cases where you shouldn't be DNR.
/:cl:
=> Possibly fixes some situations that would incorrectly DNR you.

code/modules/mob/living/carbon/xenomorph/castes/king/king.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Hatchling rank is no more. It now goes Young > Mature > Elder > Ancient > Prime
The amount of mental anguish I received when I saw an ancient titled xeno with a prime rank icon was very immense. In addition, this will make it so the rank icons line up with how they were before maturity removal.
This should be the last change I have to make to the system. I can live with "Primordial Prime".
:cl:
spellcheck: Hatchling xeno rank is replaced with young, prime is now the top xeno rank
/:cl:
=> Removes hatchling rank, adds prime

code/__HELPERS/unsorted.dm, code/game/atoms_movable.dm
Changed how throw bounces are calculated to work more consistantly.
Namely, throws that instantly collide (throwing something at a wall next to you) or certain unusual angles making things bounce towards you.
Its kind of guh since we're using exact angles, but its a tile based game with walls facing the 4 cardinal directions, so there were a few edge cases where bounces would still go in weird directions.
They should now always behave as you'd expect.
Realistic bounces or something.
:cl:
fix: Fixed some instances where throw bounces would behave funnily
/:cl:
=> Throw bounce improvements

_maps/map_files/DaedalusPrison/DaedalusPrison.dmm, code/game/area/daedalusprison.dm, code/game/turfs/closed.dm, config/maps.txt
Outskirt cave walls are actually cuttable now, the hull cave walls are now named "tough rock"
Removed two miners
Added more premaze
Medical is open to CAS, but cannot be landed in by tadpole
Hopefully makes the map a little better for Xenos, and makes the caves work more as intended.
:cl:
balance: Daedalus Prison: Removed two miners, more preweed, medical cannot be landed in by tad, and outskirt cave walls are actually pcable
spellcheck: Darkfrost hull walls are now named "tough rock"
/:cl:
=> Daedalus Changes (#1)

code/__DEFINES/dcs/signals.dm, code/__DEFINES/mobs.dm, code/datums/keybinding/xeno.dm, code/datums/status_effects/xeno_buffs.dm, code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm, code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
Title. Oppose is an ability with a 30 second cooldown that costs 100 blood. When activated, it heals every xeno in a radius of 3 tiles (the heal amount is less than a transfuse), as well as staggering and slowing marines in a radius of one tile.
If the Gorger manages to activate this ability from right on top of you, you take a bit of damage and get stunned.
inb4 "Knockoff crusher" comments or something
Rejuvenate functions as a good heal that has less startup cost, but one that also makes you slow as hell. For a primordial ability, its stats are terrible and it isn't very unique in general (Gorger already has feast). Oppose replaces this with an ability that isn't bad to use and also offers the Gorger more team-play.
:cl:
add: New Gorger primordial: Oppose. Staggers and slows nearby …
=> New Gorger Primordial Ability: Oppose

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Feedback when you successfully inject the egg + you can no longer open the egg mid do_after to get a free hugger
qol good bug bad
:cl:
qol: Defiler egg injection has more feedback now
fix: Opening the defiler egg mid progress bar makes the injection fail
/:cl:
=> Defiler egg injecting qol + bugfix

code/datums/actions/ability_actions.dm
Abilities weren't updating their icons by default on use (xenos separately just update all icons when they use plasma), leading to cooldown clocks etc not appearing.
Working visual good.
:cl:
fix: fixed abilities not updating their icon correctly on use in some cases
/:cl:
=> Action visual fix

code/__DEFINES/__game.dm, code/datums/gamemodes/_game_mode.dm
What it says on the tin. If the gamemode selected at the time (or in vote) is Crash, it can still be played. The only way it can be played is if someone votes Nuclear War in the lobby; which shouldn't usually happen, as pop drops most of the time after a vote.
This map is the worst of the worst when it comes to Nuclear War. The other crash maps (Icy Caves, Orion, Desparity) aren't great either, but somewhat(?) work for lowpop NW.
:cl:
del: Research Outpost is no longer votable when Nuclear War is selected.
/:cl:
=> Research Outpost is no longer votable if the gamemode is Nuclear War.

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Title
Currently the minion spawner requires 600 strategic points. This makes it incredibly unappealing to purchase, especially when a silo is only 200 points more, and provides larva and minions instead of only minions. While making it cheaper could make it purchased more, it competing for points with the silo means it would have to be incredibly cheap in order for it to be worth buying.
:cl:
balance: The Minion Spawner now uses tactical points instead of strategic.
/:cl:
=> Changes The Minion Spawner To Require Tactical Points Instead of Strategic Points

code/__DEFINES/loadout.dm
Removes the option to take only NVGs as SG.
They are included in the smartpistol bundle.
Opting out of the smartpistol is dumb when you can just leave it in prep or something.
:cl:
del: Removes the NVG-only smartgunner option.
/:cl:
=> Remove the non-smart pistol bundle from sg

_maps/map_files/BigRed_v2/BigRed_v2.dmm, _maps/modularmaps/big_red/bigredengineeringvar1.dmm, _maps/modularmaps/big_red/bigredengineeringvar2.dmm, _maps/modularmaps/big_red/bigredengineeringvar3.dmm, _maps/modularmaps/big_red/bigredengineeringvar4.dmm, _maps/modularmaps/big_red/bigredofficevar1.dmm, _maps/modularmaps/big_red/bigredofficevar2.dmm, _maps/modularmaps/big_red/bigredofficevar3.dmm, code/game/area/bigred.dm
What it says on the tin. The reason for the area split was to allow Xenos to build somewhat into LZ 2 Engineering.
Indoor APC's having weather effects on them was, for lack of a better word, wack. Outdoor APC's look fine. In addition, Tadpole could land in some highly contested spots for free; now Xenos can build there roundstart.
:cl:
balance: Xenos can build further into LZ 2 Engineering roundstart on Big Red, APCs for the outdoor areas on Big Red are now outside instead of inside.
/:cl:
=> Kills BR's indoor APC's that controlled outside areas, splits up LZ 2 engi into two areas.

code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
https://i.imgur.com/LmHmI2l.png
Title basically.
Makes runner evasion a pretty dedicated escape tool from group rather than just god mode.
:cl:
balance: Runner can no longer slash in invasion.
/:cl:
=> Evasion no longer lets you slash marines

code/datums/actions/ability_actions.dm, code/datums/gamemodes/campaign.dm, code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/faction_stats.dm, code/datums/gamemodes/campaign/individual_stats.dm, code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm, code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm, code/datums/gamemodes/campaign/missions/asat_capture.dm, code/datums/gamemodes/campaign/missions/base_rescue.dm, code/datums/gamemodes/campaign/missions/fire_support_raid.dm, code/datums/gamemodes/campaign/missions/patrol_mission.dm, code/datums/gamemodes/campaign/missions/phoron_capture.dm, code/datums/gamemodes/campaign/missions/supply_raid.dm, code/datums/gamemodes/campaign/perks.dm, tgui/packages/tgui/interfaces/IndividualStats/IndividualLoadouts.tsx
Some minor tweaks after the test we had.
Items that are out of stock will now be more clearly marked, showing as grey instead of red (which is easily confused for being invalid), and explicitly saying 'none currently available'.
Reduced winning team credit rewards.
Reduced the starting amount to 300 from 1000.
Mith armour for SOM correctly has a limit of 2 instead of 3 (so probably less rad spam!)
Increased the cost of a few perks.
Fixes some minor bugs.
Fixed some grammar mistakes.
Minor balance/UI tweaks for the better.
:cl:
balance: adjusted a few campaign loadout and perk things
/:cl:
=> Campaign: Various small tweaks loadout/perk tweaks

_maps/map_files/BigRed_v2/BigRed_v2.dmm
I never added sensor tower landmarks to BR (for campaign) because it was meant to be temporary... but it'll probably be a decade before I have a bunch of maps so eh.
No more funny adding in manually.
:cl:
fix: Added some missing campaign landmarks to BR
/:cl:
=> BR campaign landmarks

code/__HELPERS/logging/attack.dm, code/__HELPERS/mobs.dm, code/game/objects/machinery/telecomms/broadcasting.dm, code/modules/keybindings/bindings_atom.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/mob/living/silicon/ai/freelook/eye.dm
- Runtime related to target missing in the attack log message
- Runtime related to trying to display messages to clientless ghosts, causing dchat to not work
- Another runtime related to trying to display comms messages to ghosts, causing radio to not work
- Runtime related to a mob somehow calling `keyLoop` without a client being passed in as user
- An arg I forgot in the orphan hivemind onscreen countdown
- Some remote eyes not playing nice with the logic in the sound transferring to the user (because their `parent_cameranet` var gets set to a non `/datum/cameranet` for whatever reason, I've opted to just not let them hear at all until this code is refactored to have one unified var that determines the hud user)
runtime dad
:cl:
fix: Various runtime fixes, see the PR
/:cl:
=> Bunch of weird runtimes that broke one round then never happened again

code/datums/components/reequip.dm, code/modules/projectiles/gun_system.dm
Note: also removes .3 second delay for magharness. Since you get stunned anyway this shouldn't do anything?
Best case yay back tank worst case we find out why the delay is there and I redo this
:cl:
del: Removed split second delay on magharness
fix: Fix flamer back tank disconnecting with magharness
/:cl:
=> Fix flamer back tank disconnecting with magharness

code/datums/actions/ability_actions.dm, code/datums/actions/action.dm, code/datums/actions/item_action.dm, code/modules/clothing/clothing.dm, code/modules/clothing/modular_armor/attachments.dm, code/modules/clothing/modular_armor/modular.dm, code/modules/projectiles/gun_attachables.dm
Some fixes/code improvements.
Fixes #14831
Fixes certain toggle action (like underbarrels etc) interacting with ability toggles like jetpack.
The exclusive toggle stuff is now at the ability/activable level, since I realised thats actually the only place needed.
Unfucked various action code, mainly around suit lights and gun attachments that were just doing dumb/unneeded stuff.
Setting toggled overlays is now handled by update_button_icon() instead of set_toggle() directly.
Bug fix, cleaner code
:cl:
fix: fixed some actions interacting with other actions incorrectly
code: cleaned up some more action code
/:cl:
=> Action fixes

code/modules/projectiles/ammo_datums.dm
Halves (roughly) the sunder on penetration/impact, but doubles the penetration.
Currently the scout rifle does 25 sunder (on non impact, it has more) a second, which isn't fightable unless you want to sacrifice all your armor for one guy. Even a req weapon should be something you can fight. Top it off with the fact this weapon is IFF and you can stack it very well with your fellow marines to delete the armor off any xeno that enters your screen, which just isn't fun or fair to fight, even if the ammo is paid. 
Doubling it's armor penetration means this gun is basically built to take down high armor xenos, which means it shouldn't be useless with the sunder cut in half and will still be able to do it's job of taking down large xenos.
:cl:
balance: The basic scout rifle ammo now deals 5 …
=> Nerfs scout rifle sunder, buffs penetration

code/game/objects/machinery/vending/marine_vending.dm
i forget these are both mechanics that exist in our game
There probably shouldn't be plasma guns in crash, I'll leave the ammo incase someone does an event or something.
:cl:
fix: You can no longer get plasma guns on crash.
fix: You can find plasma guns in valhalla.
/:cl:
=> Plasma guns no longer spawn in crash, valhalla

code/game/objects/items/storage/firstaid.dm
MarineMed pill bottles can now be restocked in the vendor.
includes: bicaridine kelotane tramadol tricordrazine dylovene paracetamol isotonic 
A lot of pill bottles clutter the ground in medbay because you can't put them back in the vendor.
This addresses that issue.
:cl:
qol: MarineMed pill bottles can be restocked.
/:cl:
=> MarineMed pill bottles can now be restocked in the vendor.

code/game/objects/items/defibrillator.dm, code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Defibbing a dead marine turns on their camera.
This currently just exists as a knowledge check, which does nothing but harm CIC/AI players.
It's dumb and should not exist.
:cl:
qol: Defibbing a dead marine will turn on their camera
/:cl:
=> Defibbing a dead marine turns on their camera.

code/modules/admin/server_verbs.dm
Title. Yes/no prompt
I keep pressing this on accident while trying to start the round on local and it has no prompt so it basically just de-admins you if you're on localhost. This sucks
:cl:
admin: Added a prompt to the reload admins verb
/:cl:
=> Adds a prompt to the reload admins verb

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Reduces the cost of the minion spawner from 600 tac points to 400.
Right now this thing is incredibly expensive, especially compared to other tac buildings. This will hopefully make it more in-line with the cost of other tac purchase. I wasn't sure how to price this, so I set it to 400 so if it's bought round-start, there wouldn't be points for other tac structures. If it's still too expensive or too cheap, let me know
:cl:
balance: Reduced the price of the minion spawner from 600 to 400 tac points
/:cl:
=> Reduces The Cost Of The Minion Spawner

code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
MFW no one asks why SOM squaddies don't have light armour, but have weapons that are only available with light armour.
Missing equipment bad
:cl:
fix: fixed missing light armour for SOM squaddies in campaign
/:cl:
=> SOM light armour fix

code/datums/gamemodes/campaign/individual_stats.dm, tgui/packages/tgui/interfaces/IndividualStats/IndividualLoadouts.tsx, tgui/packages/tgui/interfaces/IndividualStats/IndividualPerks.tsx, tgui/packages/tgui/interfaces/IndividualStats/index.tsx
When you open the loadout screen, it will now automatically default to your current role, since that's what you're going to interact with 95% of the time.
Better QOL
:cl:
qol: Campaign loadout UI defaults to the job tab for your current job
/:cl:
=> Auto job tab select for campaign

code/modules/mob/living/living.dm
https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/e7257b5d-2a1b-4d21-9a9a-b1151371ec46
Marines can kinda do some still escapes currenly and it can be pretty hard for xenos to do something to stop it in certain cases.
For example the marine can just walk like this which isn't ideal.
This also restores behavior to the old one from before my diagonal PRs.
:cl:
balance: Marines cannot skip past xenos diagonally if there's an obstacle between them, check the PR for a more clear explanation
/:cl:
=> Xenos once again block marines diagonally

code/modules/projectiles/guns/rifles.dm
Removes VGRIP off SG.
Why did we give SG vgrip which allows it to have way less slowdown, makes it 0.85 rather than 0.95 which is just silly.
:cl:
balance: Removes vertical grip off SG-29.
/:cl:
=> Removes Vgrip off SG

code/modules/reqs/supply.dm, code/modules/vehicles/unmanned/unmanned_droid.dm
I thought this was done in the same PR we made antenna have this behavior. Apparently not.
See https://github.com/tgstation/TerraGov-Marine-Corps/pull/14594 and https://github.com/tgstation/TerraGov-Marine-Corps/pull/14596
I'd also like to add that depending on map plat holds can be near impenetrable by a relatively large portion of the hive. This gets even more apparent if the pop is low (the xenos either have to choose to give up the whole map to deal with a plat or just let the plat mine for free). This is pretty sub par from a design perspective in my opinion and is more an issue with the mode admittedly. The xenos should be able to attrition the miner at least.
Plat mining should probably not be something that can be done indefinitely and the marine who does it should have to risk …
=> Radiopack and AI drone beacon don't work in deep caves anymore

tgui/packages/tgui/interfaces/HiveStatus.tsx
Before
After
Comically too many t3s make this necesarry
:cl:
qol: Widened the hive status tgui window
/:cl:
=> Widens the hive status tgui window

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
ABILITY_NUCLEARWAR was put in the wrong place, this means it was a one time buy for some reason like its a primo
Bug bad
:cl:
fix: Fix acid pools having bad flags
/:cl:
=> Fix acid pool wrong flags

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm, code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm, code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
#14099 broke the shield dir check by checking for the target twice instead of xeno vs. target.
Not only does this fix it, it also improves the direction check to be more versatile instead of relying strictly on the xeno's dir, using angle relative to origin turf. Furthermore, also fixes some proc stuff so Savage no longer triggers if the pounce itself failed (which is the correct behavior).
Additionally, somewhat related, makes portals teleporting a thrown object adjust the throw origin turf to the portal target's turf.
Portals currently mess up anything that uses the throw origin turf for calculations (such as bounces), which may lead to issues with thrown objects. This should make them behave more reasonable.
Fix man good.
Portals not updating throw origin, while a minor issue, can be …
=> Fixes Xenomorph pounce bypassing shields & improves it a bit.

code/modules/projectiles/guns/shotguns.dm
Title. The edits to make it 1 are because martini and derringer are subtypes of the DB.
Seems [barnets nerf](https://github.com/tgstation/TerraGov-Marine-Corps/pull/13588) didn't really do much to curb the fact the DB is just flat out the best shotgun if you learn the reload and therefore overperforms. This aims to bring it more in line with the others. You can still fire it fast but you don't chunk as hard as a full powered shotgun. 
By the way this applies to the sawn off and the map spawned DBs too
:cl:
balance: Gave DBs a 0.7 damage multiplier, like the SH-39
/:cl:
=> Gives DBs a 0.7 damage multiplier

code/modules/mob/dead/observer/observer.dm
Apparently stopping orbit is its own thing
ium stupdi
:cl:
fix: Your ghost keeps bobbing even after you stop orbiting stuff now
/:cl:
=> Ghost bob fix 2

html/statbrowser.css
Simple one line change that hides the scroll bar on the stat panel if there is no need for it. I haven't actually tested it on base TGMC, only on my ~2 week old branch but it's just a CSS variable so should work.
One line change that fixes something I found annoying.
:cl:
fix: Hide statpanel scroll bar when not needed.
/:cl:
=> Show statpanel scroll bar only when needed

code/modules/client/preferences_toggles.dm
Fixes logic of the verb that toggles weather sounds.
Noticed during testing of some weather. Fake news confuses and annoys me.
:cl:
fix: Toggle Weather Sound verb has correct message.
/:cl:
=> Toggle Weather Sound verb has correct message

code/__DEFINES/sound.dm, code/modules/client/preferences_toggles.dm
The Toggle Ambience verb didn't actually stop ambience that was already running because it used the wrong channel. CHANNEL_AMBIENT is not used anywhere in the code except the define and this verb.
Bug fix. I don't know why CHANNEL_AMBIENT exists, CHANNEL_AMBIENCE is right there.
:cl:
fix: Toggle Ambience verb stops ambience that is currently playing.
/:cl:
=> Fix Toggle Ambience verb and delete CHANNEL_AMBIENT

code/__DEFINES/mobs.dm, code/_onclick/hud/screen_objects/screen_objects.dm, code/datums/keybinding/carbon.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm, code/modules/mob/living/living_verbs.dm
This is essentially a shameless ripoff of CM's resting. You can lay down instantly, but then cannot get up for 2 seconds after. In exchange you get up instantly after the 2 seconds have passed.
I also renamed the proc to be more clear about what it does and put in docs
As it stands right now xenos get punished for not mashing the hell out of their resting key because it is objectively better to do so as it makes you safer from being jumped. This should help make all xenos equal, lazy resting or not
:cl:
balance: Xenomorph resting now blocks you from unresting for 2 seconds, instead of it being a 2 second progress bar to get up
/:cl:
=> Xenomorph resting rework

code/game/objects/items/reagent_containers/autoinjectors.dm, code/modules/reagents/reactions/medical.dm, code/modules/reagents/reagents/medical.dm
- Repaths nanites so they don't get purged by hypervene or ozeo (or water)
- Makes nanites purge chemicals that heal brute or burn (also tramadol because I made nanites give its effects)
- Makes nanites HEAL a small amount of toxin damage (you can still take dylo with them by the way)
The goal of these changes is to make nanites more of a sidegrade to the classic BKTT, with some upsides as well as downsides.
Upsides being 
- You get a little more healing overall 
- You only have to carry blood restoring chemicals instead of pill bottles of BKTT
Downsides being
- You may find it hard to keep blood up if you're constantly taking damage
- You can't inject more on the fly, and if you get defiled (should be the only way to get your nanites purged) you have to get a new injector which will take …
=> Nanites purge healing meds but can't be purged (+ a buff to their healing)

code/modules/mob/living/carbon/xenomorph/abilities.dm
What it says on the tin. Shares the same checks as quickbuild so podding/tadding should also disable it, alongside shutters of course.
Less prep torture, given Queen is usually the one with it and they have things to do
:cl:
balance: All xenomorphs with acid now have strong acid during prep (Nuclear War)
/:cl:
=> Gives all xenos with acid strong acid during prep

_maps/magmoor_digsite_iv.json, _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Instead of disks being fully random out of 5 locations on Magmoor (this can lead to 2 cave disks or all disks being outside, leading to very different results of walance), adds 3 disk sets to Magmoor.
Dorms > Admin > Mining
Dorms > Engineering > Research
Engineering > Admin > Mining
Each of these disk sets has two outside disks and one caves (the cave being mining and research).
Makes the map less balanced on RNG, but still keeps the variety that disk sets give.
:cl:
balance: Magmoor disks are now sorted into 3 preset sets.
/:cl:
=> Magmoor Disk Sets

code/_globalvars/lists/mobs.dm, code/modules/codex/entries/mobs_codex.dm, code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm, code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm, code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm, code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm, code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm, code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm, code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm, code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm, code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm, code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm, code/modules/mob/living/carbon/xenomorph/evo_datum.dm, code/modules/mob/living/carbon/xenomorph/evolution.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Xenomorphs can now evolve to any xenomorph in the next tier, and to T4. For example, Runner can now evolve to Spitter or even Queen if there is a slot open. Queen and King still cannot evo, and Shrike can only evo to queen and king. Plus, larva can only evolve T1's.
This is a relic of trying to associate castes with eachother, like the Runner is red and Ravager is red too, so they should be in the same tree. Even for xenos that aren't really related at all (see: warrior and warlock). This allows for more flexibility in Xenomorph play, especially roundstart when Xenos go drone; they can now evo to whatever they want after quickbuild.
:cl:
balance: Xenomorphs can now evolve to any caste above their tier and T4, with exceptions made for the T4's and larva
/:cl:
=> Evolution Changes

code/modules/projectiles/guns/shotguns.dm
title
I don't think this gun really needs it to be good, it already has solid damage and this just makes it melt just about any xeno in a few seconds
https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/ccb6ab07-1ea4-44d1-967c-2528dc7504a6
(you could probably do it faster than this clip im not really trying to time it)
:cl:
balance: MBX is now two handed only
/:cl:
=> MBX can't be one handed

code/modules/screen_alert/command_alert.dm
decreases the skill required to send squad orders from 3 to 2 allowing asl to send orders
after prs #13810 nerf on leadership the ability to send squad orders was lost since the skill requirment remained the same.
Asl being able to act as Asl good.
:cl:
balance: squad order skill require from 3 to 2
/:cl:
=> ASL order fix

code/datums/gamemodes/campaign/loadout_items/SOM/head.dm
Some SOM roles no longer get RR in their hats.
SOM medics still get some RR (compared to tgmc corpsmen with neuraline), as well as some melee roles.
More level playing field.
:cl:
balance: Removed some RR from campaign
/:cl:
=> Kill most RR in campaign

code/modules/clothing/modular_armor/attachments/modules.dm, code/modules/clothing/modular_armor/som.dm
SOM bullet armour reduced across the board by 5 (with the exception of lorica module, which remains at parity with tyr 2).
This means SOM armour now has equal bullet armour to marines, but still has 5 worse laser armour.
Also fixed a minor armour bug, lorica had slightly lower slowdown than tyr 2 for some reason.
Makes some projectile weapons a bit more viable against SOM. Variety is good. Lasers are still (generally) better against SOM however.
:cl:
balance: SOM armour no longer has superior bullet armour compared to marines. Still retains a slight weakness to lasers
fix: Lorica armour has equal slowdown to tyr 2
/:cl:
=> Reduce SOM bullet armour

code/__DEFINES/campaign.dm, code/datums/gamemodes/campaign.dm
Adds a basic autobalance system.
After a new mission is selected, if one team notably outnumbers the other, all members of that team will get a prompt asking if they'd like to be swapped to the other team.
Of course this is voluntary, but there's really no point in forcing people into teams tbh, since people just refuse to play half the time if its not on the team they want.
Less skewed rounds when a bunch of people dc/leave/ragequit.
:cl:
balance: Campaign has an autobalance check at the start of every mission to try balance team numbers
/:cl:
=> Campaign autobalance

code/__DEFINES/campaign.dm
What it says on the tin. 12 was basically a placeholder, and VP victory was only intended as a fallback win condition in case a game dragged on for ages... but since the mode isn't entirely finished (i.e. the game ending missions don't exist yet), the VP limit might as well be reasonably obtainable for current gameplay.
Winnable games is good.
:cl:
balance: Campaign VP target reduced to 7 from 12 until round ending missions are added
/:cl:
=> Campaign VP target reduced to 7

code/controllers/configuration/config_entry.dm
This ports the str_list config subtype that was added as a part of tgstation/tgstation#54465
The tts voice blacklist config uses this subtype.
=> Port string list config type from tg, fix tts voice blacklist config

code/datums/fire_support.dm, code/game/objects/items/explosives/grenades/grenade.dm, code/modules/projectiles/ammo_datums.dm
Reduce rad strength across the board for rad grenades, rockets and missiles.
Radiation weapons were a little bit too strong, especially as in campaign you can tweak your loadout to get a bit more of them.
:cl:
balance: Reduced the power of radiation weaponry
/:cl:
=> Radiation nerf

code/modules/projectiles/guns/rifles.dm
Increased slowdown of the V-34 from 0.3 to 0.4
I'm happy with the damage application of the V-34, which is extremely high but suffers from terrible falloff. However, its slowdown was still a bit too low, making GETTING into effect range a bit too easy.
This is compared to its competition, the V-21 which requires you to be even closer when fuller auto, but has higher mobility.
:cl:
balance: V-34 has its slowdown increased from 0.3 to 0.4
/:cl:
=> V-34 speed reduction

code/datums/actions/item_action.dm, code/game/objects/items/motion_detector.dm, code/modules/clothing/suits/marine_armor.dm
Some as it turns out unrelated action bug fixes.
Fixes suit lights not updating on the mob sprite.
Fixes motion sensor being impossible to deactivate.
Fixes some duplicate icon updates for motion sensors.
Fixes #14929
Fix good
:cl:
fix: Visible suit lights now correctly update on the mob sprite when turning on and off
fix: You can actually turn off your motion sensor now
/:cl:
=> Misc action fixes

code/__DEFINES/dcs/signals.dm, code/datums/gamemodes/campaign/campaign_assets.dm, code/datums/gamemodes/campaign/missions/asat_capture.dm, code/datums/gamemodes/campaign/missions/fire_support_raid.dm, code/datums/gamemodes/campaign/missions/supply_raid.dm, code/datums/gamemodes/campaign/rewards/disablers.dm
Defensive missions now disable CAS for the attacking team (mortar support, if you have it, is still available).
Defense missions generally suffer from being extremely difficult for a number of reasons. CAS is not the sole or main cause for this, but it is a significant factor, as well used CAS absolutely crushes defensive positions.
Slightly more balanced defensive missions.
:cl:
balance: Campaign: Attacking teams on defensive missions can no longer call in CAS
/:cl:
=> Defensive mission cas disablers

code/modules/clothing/suits/marine_armor.dm
PMC standards specifically had a huge energy armour hole for no apparent reason.
Absolutely jobbing to volkite is bad.
:cl:
balance: PMC standard armour has improved energy armour in line with other pmc suits
/:cl:
=> PMC standard armour tweak

code/datums/components/beacon.dm, code/game/objects/machinery/squad_supply/supply_beacon.dm
Beacons will no longer layer over literally everything in the game.
Beacons are small sized again.
It looks terrible.
It don't fit in webbing.
:cl:
fix: fixed beacon layers
fix: fixed supply beacon weight class
/:cl:
=> beacon fixes

code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
organic bomb base timer before automatically detonating reduced from 15 secs to 5, now has the 1.5sec windup instead of an instant explosion
Very underused ability, at times worse because 3 puppets with fury blessing will almost always be a better option (and reducing your puppets for this ability feels weak). The acid itself isn't that strong either. Couple this with a base 15 sec timer before it explodes by itself without reaching a target (and with minion fuckery) makes this abillity very weak as the puppets will likely just die by the time it reaches its target.. In practice the total time before the puppets explode (without slashing anything) will be 6.5s (5 + 1.5s windup)
:cl:
balance: Puppeteers organic bombs base timer reduced, now uses a windup
/:cl:
=> puppeteers organic bomb base timer reduced, now has the windup

code/modules/clothing/masks/gasmask.dm, code/modules/clothing/modular_armor/modular.dm
With TTS back, I am reminded of how bad the gas mask filters are.
Removed the filter from the default gas mask. It now specifically only applies to a few gas masks like the tactical, swat etc.
Gas masks are a mandatory item and it makes people genuinely hard to understand, defeating the point of TTS to begin with.
Now you can specifically choose the hard to understand mask if you really want it.
:cl:
qol: Only some gas masks such as the tactical or swat masks have TTS filters
/:cl:
=> Gas mask TTS filter changes

code/__DEFINES/cooldowns.dm, code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Couple of lines of code that accommodate for cancelling evasion if active. Ability still goes on cooldown on activation regardless of if cancelled or not.
Has a 1 second cooldown before it can be deactivated to prevent accidental deactivations when trying to spam press it in the heat of combat. Could probably be 0.5 seconds if players feel it is too long ingame.
Yes it's a minor buff, but more importantly quality of life feature since evasion disarms the rounies and they must wait out the entire duration.
:cl:
qol: Runners can manually cancel evasion.
balance: Runners no longer disarmed for the entire duration of evasion if they cancel it.
/:cl:
=> Runner evasion can be cancelled early

code/modules/projectiles/ammo_datums.dm
Psylance only staggers for 1 second instead of 4.
4 seconds was never intended, it was a left over from before stagger was refactored to actually count duration accurately.
:cl:
balance: Psylance stagger reduced to 1 second
/:cl:
=> Adjust psylance stagger

code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm, code/modules/xenomorph/xenotowers.dm
Increases maturity gain from evolution tower to 0.8, basically the same as old 4 maturity towers
Evolution tower was in a terrible spot due to maturity only existing for primo, an extra 0.8 should be fine given maturity only spikes at primo now instead of young to ancient
:cl:
balance: Evolution now gives an extra 0.8 maturity instead of 0.2
/:cl:
=> Evolution tower buff

code/_onclick/click.dm
Abilities (like jetpack/blink/sectoid powers/etc) for humans will now work with shift click if you have your middle click pref toggled to shift click.
I forgot middle click pref is even a thing, so never added the code for humans.
If anyone has trouble with this before the pr is merged, you can change the pref to mmb and that will work fine.
Pref working is good.
:cl:
fix: shift click will work for human abilities such as jetpack, if you have toggled your pref from middle mouse button
/:cl:
=> Fix middle click pref for humans

code/__DEFINES/rust_g.dm, dependencies.sh
ports tgstation/tgstation#80955
This won't fix all of the crashes, but it will help with some and also help with finding them to have stack traces for the current version.
Gonna test merge first.
=> bumps rust-g to `3.1.0`

code/modules/mob/living/carbon/xenomorph/abilities.dm
Per title.
So you killed a guy and secured the body somehow. Now you have to pay a flat plasma cost. Don't forget that your drain can be interrupted by damage, and that this hits certain castes with lower plasma maximums (looking at you, woyer) much harder. There's not much point to it and all it does is punish caste choices for unholy reasons.
:cl: Lewdcifer
balance: Psydrain plasma cost reduced from 100 to 50.
/:cl:
=> Halves Psychic Drain's plasma cost

code/__DEFINES/dcs/signals.dm, code/_onclick/click.dm, code/_onclick/item_attack.dm
Adds proc attack_self_alternate()
When you are holding an item in-hand and you right-click it.
This was dumb, it was basically impossible to right click an item if it was in your selected hand.
:cl:
code: add proc attack_self_alternate()
/:cl:
=> Adds proc attack_self_alternate()

code/datums/actions/order_action.dm
decreases the skill required to send squad rallys from 3 to 2 allowing asl to send rally arrows once again
after prs #13810 nerf on leadership the ability to send squad rallys was lost since the skill requirment remained the same.
Asl being able to act as Asl good.
:cl:
fix: squad rally skill requirement from 3 to 2
/:cl:
=> ASL rally arrows fix

code/datums/gamemodes/campaign/faction_stats.dm
Attrition can no longer be lost if multiple people are setting or using attrition at the same time.
Funny disappearing attrition bad.
:cl:
fix: Campaign: fixed attrition sometimes being lost if several people were setting it at the same time
/:cl:
=> Attrition fix

code/game/objects/items/explosives/mine.dm
Normal claymores had the lower alpha meant only for AT mines.
I am dum and messed up the typepath.
After playing against sneaky claymores in HvH, I actually like them, so would be happy for them to stay. It was an unintended HvX balance change though, so would like thoughts on this.
:cl:
fix: fixed normal claymores being sneakier than intended
/:cl:
=> Mine alpha fix

code/datums/gamemodes/campaign/missions/asat_capture.dm, code/game/objects/structures/campaign_structures/capture_objectives.dm
Marines can no longer cap their own objective if it was in the process of being captured by SOM.
Instead it will simply cancel the hostile capture timer as intended.
Fixed up the win condition checks as marines don't cap any objectives.
Funny bug bad.
:cl:
fix: Campaign: Marines will no longer be able to steal their own ASAT objectives
fix: Campaign: Fixed some errors in the ASAT mission win conditions
/:cl:
=> ASAT mission fixes

code/modules/projectiles/ammo_datums.dm
SG-162 high impact and heavy impact now apply their CC for 1 second instead of 1 decisecond.
Pretty sure the intended amount of CC was 1 second, and not 1 decisecond
:cl:
fix: SG-162 high impact and heavy impact now apply their CC for 1 second instead of 1 decisecond
/:cl:
=> SG-162 high impact and heavy impact now apply their CC for 1 second instead of 1 decisecond.

code/__DEFINES/campaign.dm, code/datums/gamemodes/campaign.dm, code/datums/gamemodes/campaign/campaign_mission.dm
Changing team via autobalance now gives you an extra 50% credit bonus (or 200, if its at the start of the game).
If the sides are STILL not balanced after any team swaps (i.e. not enough people swapped) then the weaker team is given a light mech for every 5 people they're outnumbered by.
Incentivised actually swapping team for balance.
Helps the weaker team with mechs if the other team is full of smellies that don't want to swap.
:cl:
balance: Campaign: Switching team for autobalance rewards you with addition credits
balance: Campaign: If teams are still not balanced, the weaker team is given light mechs based on how outnumbered they are
/:cl:
=> Campaign autobalance tweaks

code/datums/gamemodes/campaign.dm, code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/faction_stats.dm, code/datums/gamemodes/campaign/individual_stats.dm, code/datums/jobs/job/job.dm, code/datums/personal_statistics.dm, code/game/objects/items/defibrillator.dm, code/game/objects/items/explosives/plastique.dm, code/game/objects/structures/campaign_structures/capture_objectives.dm, code/game/objects/structures/campaign_structures/deploy_blockers.dm, code/game/objects/structures/campaign_structures/destroy_objectives.dm, code/modules/mob/mob.dm, code/modules/projectiles/projectile.dm
The end of mission credit reward is now supplemented by an amount determined by your individual performance.
Using the personal stats datum, the following stats are recorded each mission, and you receive a reward for them.
**Projectile damage: 0.1 credits** per damage dealt. This is after armour.
**Melee damage: 0.2 credits** per damage dealt.
**Friendly fire damage** (both projectile and melee): **-0.2 credits** per damage dealt.
**Delimbs: 3 credits** per delimb
**Revives: 10 credits** per revive
**Being revived: 5 credits** per revive. Stay in the fight marine!
**Structure built: 3 credits** per structure
**Objective destroyed: 15 credits** per objective (-15 if you are a moron and blow up your own)
**Deploy blocker destroyed: 10 credits** per objective (-10 if you are a moron and blow …
=> Campaign individual performance rewards

code/game/objects/effects/effect_system/smoke.dm, code/game/objects/structures/orbital_cannon.dm
Tfoot OB duration (60 seconds) is now reduced by 4 seconds per level of fuel inaccuracy.
Tfoot OB is currently the only OB that has no downside for fuel inaccuracy outside of actual target accuracy (which doesn't matter as long as you don't fire it into a wall).
This means its less beneficial to spam 1 fuel tangle OB's.
Also added some missing autodoc as some shit is missing/unclear (like OB duration being labelled as 3 SECONDS when its actually a duration in 2 second ticks).
:cl:
balance: Tfoot OB's duration is reduced by 4 seconds per level of fuel inaccuracy
/:cl:
=> Tfoot OB inaccuracy penalty

code/__DEFINES/loadout.dm
Loadouts will no longer be cursed and not vend a gun/ammo/smart pistol etc.
The smart pistol and related stuff was not correctly added to the vendor.
Cursed loadouts bad.
:cl:
fix: fixed SG loadouts often not spawning everything they should
/:cl:
=> Fix smartgun loadouts

code/game/objects/machinery/computer/communications.dm
Cancelling delta now explicitly says it cancels both evac and SD. You know, the things only allowable in delta.
Helps schizo and/or bald players from doing the dumb.
:cl:
qol: Cancelling delta alert explicitly tells you that this controls both evac and SD
/:cl:
=> Delta level clarification

code/modules/xenomorph/resin_gargoyle.dm
Changes the resin gargoyles' alert sound to be growl alert, rather than the screech one.
The sound it currently uses is bad due to causing ear pain, especially if there are many of em and/or a lot of marines in an area.
:cl:
qol: The alert for resin gargoyles have been changed to use the growl sound effect instead of the screech.
/:cl:
=> Changes gargoyle's alert sound

code/datums/actions/item_action.dm, code/game/objects/items.dm, code/game/objects/items/blink_drive.dm, code/game/objects/items/implants/implant.dm, code/game/objects/items/jetpack.dm, code/game/objects/items/motion_detector.dm, code/modules/clothing/modular_armor/modular.dm, code/modules/clothing/suits/marine_armor.dm, code/modules/projectiles/gun_attachables.dm, code/modules/projectiles/gun_helpers.dm
Fix/improve a variety of action toggles.
- Suit lights can no longer have the button toggled when the light is on cooldown.
- Improved some code to reduce excessive/unneeded updates
:cl:
qol: Suit lights no longer mismatch their actual state and action state if spammed
/:cl:
=> Fix some toggle visuals

code/datums/gamemodes/campaign/missions/base_rescue.dm
Added light mechs to NT base rescue.
5 for SOM, 2 for TGMC.
Also added some extra text to clarify that SOM cannot deploy via teleporter at all during this mission.
This is quite hard for SOM, and even though they're attacking, marines are the ones choosing it. Some mech muscle should make it more interesting for them. Light mechs are weak enough that infantry can take them down quite easily without dedicated AT weapons.
:cl:
balance: Campaign: Made NT base rescue a bit easier for SOM
/:cl:
=> Base rescue mission tweaks

code/modules/projectiles/ammo_datums.dm
Title. Stuff like this won't happen anymore.
https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/1a0d6483-62b2-4d59-8186-37ca5ae7d48d
Stagger stacking like this is problematic due to us having a fair few weapons which fire way faster than the stagger dissipates, which results in xenos being staggered for over 10 seconds after the fight in some cases. I'd rather we make it not stack at all instead of nerfing those weapons to the ground, since it'd take away the point of a fair few of them (not to mention its hard maintainability wise, needing to make sure every gun is below a certain stagger duration to avoid silly stuff)
Also kurt said yes
:cl:
balance: Stagger doesn't stack in duration anymore
/:cl:
=> Stagger doesn't stack in duration anymore

code/datums/components/beacon.dm, code/game/objects/machinery/squad_supply/supply_console.dm
Change how Deployed Beacon on Tadpole work back to #14421.
Now it Auto update without needing to Redeploy it every time tad move, and can be deployed in Tad on whatever Z-Level tad is (but still can only be used groundside). Code thanks to lumi
It filter out non groundside beacon from the supply console list, so no clutter. Code thanks to ivan and electric.
One less thing to think about for Tadpole Pilot and ROs, while maintaining beacon usage only to groundside use.
:cl:
qol: Supply Beacon now Auto Update if Tad are moving across Z-level.
/:cl:
=> Beacon Auto update when changing Z-level instead of turning off

code/game/objects/machinery/vending/marine_vending.dm, code/modules/reqs/supplypacks.dm
See title. They're still in valhalla/hvh
This was literally pure flamer powercreep the day it was introduced, I have no idea why it took so long for anyone including me to decide to nuke this from orbit.
:cl:
del: You can no loner acquire long or wide nozzle in HvX.
/:cl:
=> Long and spread nozzle are gone from acquisition.

code/__DEFINES/jobs.dm
What it says on the tin
Maintainer request on transport officer PR 
:cl:
admin: Expert timelock increased to 25 hours
/:cl:
=> Increases expert timelock to 25 hours

_maps/shuttles/tgs_canterbury.dmm
moves around the windoor in the SG prep on the cantabury since it is now blocked by a synth vendor.
its nice to not break windows or to be trapped in a glass box.
Before:
After:
:cl:
fix: SG prep on cantabury no longer has its only door blocked
/:cl:
=> Shifts SG prep door on Cantabury so they may leave without breaking glass

code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/mob_grab.dm
Fixes choking someone to death... not causing any damage.
Fixes weapon miss chance never actually missing.
Fix some runtimes if you miss an attack.
Upgrading your grab now is faster with higher CQC skill.
When punching someone who is prone, you now always do max damage instead of the normal rng damage.
Unarmed attacks now uses the same target zone prob stuff as melee weapons, with the minor exception of it comparing cqc skills of the attacker and defender to modify miss chance.
The effect of this means unarmed attack will generally actually hit the target area you aim for instead of a complete rng shitshow, although some times you can now miss entirely.
Also replaced some one letter var shit.
Fixes and minor cqc buffs to make it mildly less useless
:cl:
balance: Unarmed damage against …
=> Human v Human melee tweaks and fixes

code/modules/reqs/supplypacks.dm
Title.
The base mags are probably the best type of ammo for the AMR so it makes little sense for the other ammo types to be more expensive.
(Also this appeases my reqtorio addition many moons ago.)
:cl:
balance: All AMR mags cost the same.
/:cl:
=> All AMR ammo costs the same.

code/__DEFINES/layers.dm, code/datums/components/jump.dm, code/game/objects/structures/campaign_props.dm, code/game/objects/structures/campaign_structures/destroy_objectives.dm
Proper preservation of jumper layer and passflags, for a for edge cases.
Edited a few layers for a more consistant experience. Namely that jumping now has its own specific layer, and a few prop overlays have a higher layer so a few things don't overlay over them improperly.
Killed an unused define
Visual clean up/fix some edge case issues.
:cl:
fix: fixed a couple of minor edge case bugs with jumping
/:cl:
=> Minor jump tweaks

code/datums/elements/connect_loc.dm, code/game/atoms/atom_movable.dm, code/game/objects/machinery/cic_maptable.dm
Connect loc now connects to locs, in the case of multi tile atoms.
Also made big map tables crossable like windowframes/tables etc, as a proof of concept.
Connect loc would only connect to your actual LOC, which creates weird behavior for multitiles in some cases.
:cl:
code: connect_loc now works properly for multitile atoms
/:cl:
=> Multi tile connect loc

code/game/objects/effects/effect_system/smoke.dm
You can now see through it woohoo
Sent primo is arguably the best in the game, gives a T1 a spammable, high damage gas that has no risk. The main benefit of gas is as a smoke screen that blocks LoS, given all the other benefits it has it should not block vision.
:cl:
balance: Sentinel gas nade is now transparent (you can see through it)
/:cl:
=> Sentinel nade is now transparent

code/modules/mob/living/carbon/xenomorph/death.dm
If autobalance is on and you die, or if you are a tier four and die, your respawn timer is not set (being a minion still doesn't set your respawn timer too, by the way!)
If you die with autobalance on, it is in the best interest of the hive to have you back in the fight ASAP lest they want your silo to be rushed, which is no bueno. On the T4 side, if you are the only leader because no one else wants to, it can kind of suck if you die and people bicker over who has to take the chore of being leader whereas you could just go Shrike. Keep in mind that King and Queen still have the timers to evo to them after death.
:cl:
balance: If autobalance is on or if you are a tier four, the xeno respawn timer is not applied
/:cl:
=> Xeno respawn timer changes 

code/game/objects/items/storage/belt.dm
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/15013
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/15013
Bugfix
:cl:
fix: fix typo in martini belt causing broken sprite
/:cl:
=> Fix martini belt sprite typo

code/datums/gamemodes/campaign/missions/destroy_mission.dm
Fixed a funny edge case bug in destroy mission victory condition checks.
Instant loss is bad
:cl:
fix: Campaign: Fixed a bug in destroy mission victory checks
/:cl:
=> Fix destroy mission win condition

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Fixes tail sweep, crusher stomp and ravager ravage going through walls if the person being affected by them is standing in a missing corner.
Before
https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/0e5d7c4e-b561-48ac-9ca1-0c1b84e4e2eb
After
https://github.com/tgstation/TerraGov-Marine-Corps/assets/22431091/bb310afb-8f03-4423-bd96-b8904a83f361
Bug bad
:cl:
fix: Xenos abilities shouldn't go through missing corners anymore
/:cl:
=> Adds some adjacency sanity to some xeno abilities

code/game/atoms/atom_movable.dm, code/modules/mob/living/living.dm
Fixes some throw bugs involving a mob being thrown while buckled, or having another mob buckled them.
Notably this fixes some weird longstanding interactions. Like not being able to powerfist a bike, but you could powerfist the driver and the bike would fly off with them.
Also added a failsafe, so if a thrown thing doesn't correctly get told to stop throw for whatever reason, it will still stop if it fails to actually move.
Bug bad.
:cl:
fix: fixed some throw bugs involving buckled mobs, and added a failsafe to catch any other edge cases
/:cl:
=> Yet more throw fixes

code/_globalvars/lists/flavor_misc.dm
What it says on the tin
Bug bad
:cl:
fix: Transport Officer icon should show in orbit menu
/:cl:
=> Hopefully fixes Transport Officer icon not showing in orbit menu

code/game/objects/items/explosives/mine.dm
Made some changes to accidental detonations.
Fire still cannot detonate AT mines, however light and medium explosions have a chance to do so if its armed (dev explosions will qdel it, and weak explosions are too weak).
A bit more interactivity, while still avoiding funny zack detonation hijinks.
:cl:
balance: Campaign: Light and medium explosions have a chance to detonate armed AT mines
/:cl:
=> AT mine tweaks

code/game/objects/machinery/vending/quick_vendor.dm
Fixes not being able to vend a beginner loadout in valhalla
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14451
Bugfix
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14451
:cl:
fix: Fix not being able to use the beginner loadout in valhalla
/:cl:
=> Beginner loadout vendor in valhalla works.

code/modules/projectiles/ammo_datums.dm, code/modules/reqs/supplypacks.dm
Does some ammo datum name housecleaning on the side so people stop bothering about the 8.8cm gun firing a 15cm shell.
Either way.
- APFDS
- damage 200->275
- penetration 70->50
- slowdown stays 0.5
- No longer has a minimum range.
- HE
- damage 50->100 (matches HE sadar)
FK-88 is insanely cost inefficent, I was too cautious cost wise so making it old sadar cost was a fools errand, 1000 points is a much fairer milestone to aim for, the ammo is also 50 points overall.
The ammo buffs are to make the ammo feel more high impact, you already have a high cost to entry, and the minimum range on AFPDS just makes it play silly as there's no real way for the player to tell that their shot missed due to the shell moving so quickly.
:cl:
balance: FK-88 Ammo changes. APFDS no longer has a minimum …
=> FK-88 buff, and some housecleaning

code/datums/gamemodes/_game_mode.dm
Properly formats requisitions stats at round end stats and adds one new line before `Requisitions produced:` so it's generally easier to read
big changes
:cl:
fix: Requisitions status at round end stats is now properly formated.
/:cl:
=> Fix req stats formatting

code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm
Weapons that require light armour also work with upgraded light armour (with the better shields).
:cl:
fix: Campaign: Fixed some guns not working with upgraded shield light armour as expected
/:cl:
=> Campaign light armor prereq fixes

_maps/map_files/Arachne/TGS_Arachne.dmm
Arachne has two sets of roundstart bomb ammo placements, while every other ship has one set. Removing the extra to ensure dropship ammo is equivalent across all maps.
Also fixes the stairs in disposals.
Consistency good, bugfix good.
:cl:
fix: Removed duplicated bomb ammo placements on Arachne.
/:cl:
=> Removes Duplicate Bomb Placements on Arachne 

_maps/ice_colony_v2.json
Even Big Red had more QB than this map, and this map is likely the most open in the game next to my notoriously open maps, which have way more QB. It's funny when you maze one of the big three open fields and run out of QB, hopefully this helps alleviate this.
:cl:
balance: Ice colony now has 2100 quickbuild points instead of 1600.
/:cl:
=> Gives ice colony 2100 QB from 1600

_maps/map_files/gelida_iv/gelida_iv.dmm
Preweeds much more of Gelida and adds a tunnel to the northwest cave.
South of this map barely had any weeds and when you spawned in the northwest caves you had to walk the long way out due to no tunnel. Gelida should feel much easier to play on when you have few weeding castes.
:cl:
balance: Preweeded Gelida IV and added a tunnel.
/:cl:
=> Preweeds Gelida IV and adds a tunnel

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Changes the externals of the two buildings outside the left LZ to reinforced walls.
<details>
<summary> Images </summary>
</details>
This LZ can become a nightmare to assault for xenos if marines flatten these two buildings, which is extremely easy considering they are both entirely regular walls. Making the externals of these two buildings reinforced should hopefully reduce the instances of flattened battlefields while still allowing marines to OB and gut these buildings if they need to hold inside them for whatever reason.
:cl:
balance: Reinforced the external walls of two buildings on Magmoor.
/:cl:
=> External reinforced walls for magmoor lz1 buildings

code/modules/mob/living/carbon/xenomorph/abilities.dm
Castes affected:
Sentinel
Hivelord
Spitter
Praetorian
Xeno spit is essentially the caste's basic attack, a ranged slash if you will. It trades perma damage and unlimited use (it has a plasma cost) while also helping prevent fractures for range. There is a good amount of ways to just shut down spit castes at medium range (slug, gl54 namely) and even more at close range. If this makes spit slash absurdly strong (queen already has the best of it with more HP and armor, being able to stay in melee for quite a long time) then I can tune down melee damage, however spit castes should be able to use their basic attack at range without being staggered out of it.
:cl:
balance: Xeno spit is unstaggerable
/:cl:
=> Xeno spit is unstaggerable

code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
The ride truly never ends, does it?
Even more Behemoth changes because I felt motivated. Mostly code improvements, some fixes, and a bit of balancing.
- Earth Riser now has a maximum of three pillars. Primordial version is uncapped, and is now limited by a 2s. cooldown instead.
- Earth Riser's displacement is now a knockback. This means it throws people, which has some implications on functionality. Mostly beneficial/buffs.
- Fixed an issue where footstep changes on Landslide were setup incorrectly, which could lead to wacky behavior in certain cases.
- Fixed an unintended result where the primordial version of Earth Riser had a much shorter cooldown than intended, which made it highly spammable and highly deadly.
- Fixed an issue where hitting Earth Pillars with Seismic Fracture wouldn't …
=> Even more Behemoth balancing and fixes

_maps/bigred_v2.json
Title
BR is a deceptively big map and often basically all of the caves besides silo goes unmazed if colony is mazed, allowing people to just run through it.
:cl:
balance: Big Red now has 2300 quickbuild points instead of 1800
/:cl:
=> Increases BR QB to 2300 from 1800

code/modules/power/groundmap_geothermal.dm
Now role that have more than Squad Engineer's engineer skill (3), like CSE/ST/Synth (4) and Early Synth (5) can Fix groundside Gens Faster. Shipside Gens already have this Feature.
Make Synth Extra Engineering skills useful.
:cl:
balance: Synth & Early Synth can fix Groundside Gens faster now.
/:cl:
=> Make Engineer Skill Affect Groundside Gens Repair Time

code/__DEFINES/loadout.dm
Removes the first aid kit from medic/SL vendor and medic spawn
Gonna be honest, I think this is a CM thing where their medkits fit in backpacks.
Adding it to backpacks here is giga storage creep, and their contents are all just available now in the vendors.
I think removing it from spawning is the play since it only exists as noob bait since you're better off just carrying a backpack with meds.
:cl:
del: Medics and SLs no longer get a firstaid box
/:cl:
=> Removes the first aid kit from medic/SL vendor and medic spawn

code/datums/jobs/squads.dm
Custom squads will now automatically pick the first most unused letter in the name: (e.g cool squad will be .o because .c is taken) the key can be found by examining your headset. people in the squad still have to use ; because im lazy and didnt fix it
:cl:
fix: Custom squads will now automatically pick the first most unused letter in the name: (e.g cool squad will be .o because .c is taken by charlie by default) the key can be found by examining your headset. people in the squad still have to use ; because im lazy and didnt fix it
/:cl:
=> Fixes non-custom squad members being unable to talk on custom squad comms

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
This removes 7 of Ice Colony's 16 phoron miners and places 1 new one.
Ice Colony has the highest number of phoron miners out of all of our maps, beating even Big Red's 13 miners. This map is already marine sided with its numerous open fields and choke points, but it gives marines an extreme snowball advantage just for taking the areas they would be taking to regardless of miners. Unlike Big Red, many of Ice Colony's miners are much harder to siege and many of them also help defend other miners, which creates a compounding problem where marines will have their full force at the southern disks which threatens a silo rush, while 6 phoron miners are ticking away and covering each others flanks up at the open fields near engi. 
My decisions on which miners to specifically remove are mostly …
=> Removes and moves Ice Colony phoron miners

code/datums/gamemodes/campaign/individual_stats.dm, code/datums/gamemodes/campaign/outfit_holder.dm
Fixed a bug causing some classes to get items they're not supposed to/duplicated. I set a default arg to the wrong thing.
Also made the unlock perk itself a bit safer just in case.
Fix good.
:cl:
fix: Campaign: Fixed an issue with some perks unlocking items incorrectly
/:cl:
=> Perk item upgrade fix

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm, code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm, code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
Xenos can use the following abilities while resting:
Acid well placement
Drone essence link
Hivelord, Drone create jelly
Hivelord resin pod
Carrier place trap
Widow create spiderling
More of a qol than flat out buffs. This just makes it easier for some Xenos to use some of their abilities while resting instead of having to unrest, use said ability and rest again.
:cl:
balance: Essence link (Drone), Create Jelly (Drone and Hivelord), Place Jelly Pod (Hivelord), Place Resin trap (Carrier), Create Spiderling (Widow), Acid well placement (several castes) can be used while resting.
/:cl:
=> More Xeno abilities useable while resting.

code/datums/gamemodes/campaign/faction_stats.dm
Fixed being inside something (like a mech) causing you to teleport to base instead of despawning
Being sent back to base with depleted gear unintentionally is not ideal.
:cl:
fix: Campaign: Fixed not being properly despawned at the end of a mission in some cases
/:cl:
=> end of mission tele fix

code/datums/gamemodes/campaign/missions/asat_capture.dm
Fixed the objective desc for TGMC to actually state the correct number of objectives you need to protect (2) instead of the amount SOM need to cap (5)
Misleading objective bad.
:cl:
fix: Campaign: Fixed an incorrect objective desc for ASAT Capture
/:cl:
=> ASAT desc fix

code/__DEFINES/dcs/signals.dm, code/_onclick/click.dm, code/_onclick/hud/interactive_emotes.dm, code/datums/keybinding/mob.dm, code/modules/mob/living/carbon/human/human_attackhand.dm
No one told me not to use right clicks, so making it set via a keybind as someone suggested so it does not interfere with abilities and underbarrel guns. It is unbound by default. When the associated key is pressed, a list of nearby players is given for the user to pick who to interact with. Or auto-pick for the user if there is only one nearby candidate.
Players can use right click again.
:cl:
code: Interactive emotes can be bound to a key instead of using right clicking.
/:cl:
=> Interactive emotes converted to using a keybinding

code/game/objects/machinery/robotic_cradle.dm
Fix robotic cradle sprite
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/13561
BTW var/repairing is never set to TRUE (in this file at least)
So unless this var is being set elsewhere, it looks to be completely unused? Oh well.
Bugfix
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/13561
:cl:
fix: Fix robotic cradle sprite
/:cl:
=> Fix robotic cradle sprite

code/game/data_huds.dm, code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm, code/modules/mob/living/carbon/xenomorph/castes/puppeteer/puppeteer.dm, code/modules/mob/living/carbon/xenomorph/life.dm, code/modules/mob/living/carbon/xenomorph/update_icons.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm, code/modules/mob/living/living_health_procs.dm
Fixes pheros not using any plasma if you're at full plasma... even off weeds.
Optimises the use of hud_set_plasma() so its not getting called multiple times every life tick and other random times. Instead, plasma is now only updated by the setter procs, and plasma hud is only updated when plasma actually changes.
Bug fix good.
Optimisation = better perf
Also the happy upside is that your plasma hud will update instantly when it changes (from using an ability etc) instead of waiting for a life tick.
:cl:
qol: Xeno plasma levels will update on the hud as soon as plasma levels change, instead of waiting for life ticks
fix: fixed pheros not using plasma if you were on full plasma, even off weeds
code: Improved some xeno plasma hud code
/:cl:
=> Xeno plasma code optimisation and bug fix

_maps/map_files/DaedalusPrison/DaedalusPrison.dmm, code/game/objects/structures/fence.dm, code/game/objects/structures/tables_racks.dm, code/game/turfs/snow.dm
Weaker reinforced tables
Pre-broken fences
A few more melt holes
Some new miners and some moved/removed
Fixed a bug where snow would show up as a missing texture on SDMM
Hopefully makes prep less torture for the normal xeno on Daedalus. Also, bug fix good.
:cl:
balance: Daedalus Prison has weaker tables and pre-broken fences for a better prep experience
fix: Snows shows up as a proper texture in SDMM
/:cl:
=> Daedalus Changes (#2)

code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/faction_stats.dm, code/datums/gamemodes/campaign/individual_stats.dm
Some minor credit tweaks.
A little more initial credits and mission end credits.
Loss bonus now also applies to mission credit reward (i.e. the fixed amount, not the individual performance credits)
Very modest increase in credit availability, and loss bonus is good to be less punishing to the losing team.
:cl:
balance: Campaign: Slightly increased some credit reward values, and loss bonus now applies to mission credit rewards
/:cl:
=> Campaign credit tweaks

code/datums/jobs/access.dm, code/datums/jobs/job/marines.dm, code/datums/jobs/job/shipside.dm
Tries to standardize hours and gives FC, SL completely new ranks as well as 300hr ranks for corpsman, engineer, mech pilot and  SG
The hours for ranks was completely nonsenical, now only squad marine has a snowflake 10 hour role. The rest go starting > 25 hours > 100 hours > 300 hours > 1000 hours.
:cl:
spellcheck: New groundside marine ranks
/:cl:
=> Groundside marine rank overhaul

code/modules/projectiles/ammo_datums.dm
20->50 wall damage bonus for HV, flak gets 5->25
Walls got some pretty big buffs to their resistances, and ACs entire gimmick is shooting down walls. So it has to be buffed to be up to par.
:cl:
balance: AC has significantly more wall damage to keep up with wall resistance buffs.
/:cl:
=> Autocannon wall true damage buff

code/game/objects/machinery/vending/vending_types.dm
Changes the layer of the flight surgeon dispenser on the tadpole to be above objects.
Currently, it not only gets lost under the clutter of items that is usually on the tad, but also layers under the tadpole wall itself. This makes using the soporific injectors in them a pain in the ass. This pr helps make it so using the dispenser a lot is a lot easier, especially for researchers/synths/CMOs performing tad surgery. 
:cl:
qol: The tadpole surgery dispenser now layers over objects
/:cl:
=> Changes Tadpole's Med Dispenser Layer

code/modules/mob/living/carbon/human/human_defense.dm
You can no longer embed a weapon by hitting a human. Throwing/projectiles/etc are unaffected.
Having your machinegun get embedding in someones face and effectively be lost forever is kinda funny, but extremely annoying.
:cl:
balance: Meleeing humans can no longer embed the item
/:cl:
=> Remove melee embed chance

code/__HELPERS/announce.dm, code/modules/mob/living/silicon/ai/say.dm
Implements minor announcement for AI's VOX ability.
This PR also adds `should_play_sound` override to `minor_announce`.
Reading chat is important
:cl:
add: AI VOX announcements are now visible on chat
/:cl:
=> AI VOX announcement 

code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Sunder multiplier: multiplies incoming sunder by this amount.
Gives queen a sunder multiplier of 0.8, crusher 0.5.
Of the three armored castes (queen, crusher, king), crusher has the least of being able to fight without sunder. The other two castes have an ability to operate at range even with sunder, but Crusher is always in there. Queen doesn't exactly require it per-say, but since they are still somewhat of a sunder magnet they have it. King literally needs sunder to die, so no multiplier on his end.
:cl:
balance: Queen has a sunder multiplier of 0.8 (takes 80% sunder), Crusher has a sunder multiplier of 0.5 (takes 50% sunder)
/:cl:
=> Sunder multiplier

code/__DEFINES/combat.dm, code/modules/mob/living/carbon/xenomorph/attack_alien.dm, code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm, code/modules/mob/living/carbon/xenomorph/castes/spiderling/castedatum_spiderling.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/unit_tests/_unit_tests.dm, code/modules/unit_tests/xenoaccuracy.dm
Instead of a 70% chance to hit a selected limb, widow and puppet minions now have a 5% to hit. Accuracy for Widow, Puppeter and all other castes have not been changed.
Widow and Puppeteer can use their minions as disposables to get free chest fracs. With this change they have to actually get into the fray, and even with that the free fractures won't be so free anymore. Their extremely low TTK has not changed, just less chance for more permanent forms of damage in exchange.
:cl:
balance: Widow and Puppeteer minions have a 5% chance to hit their selected limb (chest) instead of a 70% chance.
/:cl:
=> Adds a accuracy malus to Puppeteer and Widow minions

code/modules/mob/living/silicon/ai/say.dm
forgot to include receivers from my previous pull request
:cl:
code: Observers and AI now receive VOX announcement message
/:cl:
=> [NO GBP] Observers and AI itself can read VOX announcement too

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Fixes larva queue for real.
Turns out the issue was that in some cases a larva slot was reserved before you actually spawned, and in other cases it didn't, even with the same button.
It now ALWAYS reserves the larva.
Additionally fixed what looks to be another bug where reservation wasn't passed on correctly.
Honestly the whole 'is reserved' thing should be killed, but I can't be bothered checking every proc to see if there is some other admeme or otherwise way of spawning without reserving first, so someone else can do that.
Actually fixes exploit without breaking it in other ways.
:cl:
fix: Fixed a new issue with the larva queue
/:cl:
=> Larva fix for real

code/datums/gamemodes/infestation.dm
Landmark resins walls did not regen and had 200 hp because they didn't use the regenerating subtype, which literally every xeno builds
Fix good
:cl:
fix: Landmark resin walls now properly function
/:cl:
=> Fixes landmark resin walls

code/datums/personal_statistics.dm
After scenes that would go straight to the UN warcrimes tribunal, I've decided its better to simply remove points gain from delimbs entirely.
Chopping up the dead and dying for fun and profit is not ideal.
:cl:
balance: Campaign: Delimbing no longer provides additional credits
/:cl:
=> Remove delimb points from campaign

code/__DEFINES/rust_g.dm, code/modules/ai/ai_node.dm
rustg but with the pathfinder actually compiled also fixes a type with rustg_remove_node_astart to rustg_remove_node_astar
fixes advanced pathfinding procs being undefined
:cl:
fix: rust-g not compiled with pathfinder feature
/:cl:
=> rust-g with the pathfinder compiled

code/_onclick/adjacent.dm, code/game/objects/items/storage/internal.dm
Fixes some runtimes/adds an extra check.
It turns out locs does not actually show your multitile loc if you're not on a turf...
I don't think this is causing the MC death, but I did notice click code due to directional attacks is calling adjacent for basically everything when it shouldn't, so that may be pointing to the actual cause.
:cl:
fix: fixed a runtime with adjacency checks
/:cl:
=> Adjacency runtime fix

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Blowing up a portal now destroys BOTH portals.
Currently, you throw a nade through a portal, it destroys the other end, which means the wraith can just instantly build a new portal. To actually counter a portal you have to portal your end, which is often unsafe, and its frankly unintuitive that nuking a portal only hurts one end.
:cl:
balance: Blowing up a wraith portal kills both ends of the portal now
/:cl:
=> Wraith portal destruction change

code/game/objects/machinery/mortar.dm
Replaces the mortar in the roundstart mortar kit with a full mortar bag
Mortar has poor long range accuracy. Frequently the roundstart mortar kit is operated from the FOB resulting in friendly fire incidents. 
This lets an ordinary marine operate the mortar kit near the frontlines. This how the tool is intended to be used. Encourages more coordinated and strategic mortar usage. Mortar is cool.
:cl:
balance: Mortar kit now includes a bag.
/:cl:
=> Adds a mortar bag to basic mortar kit

code/modules/xenomorph/resin_gargoyle.dm
Adds in the flag that makes it a critical structure, making it visible in pinpointer and able to be tracked on xeno structures list.
The ignore weed removal flag was advised by Xander, saying that other structures had it added due to buggy nature of weeds. with structures(?)
Xenos can track them now, Marines can track them now.
:cl:
add: Gargoyles are now act the same as other structures, and can be tracked with Structure pinpointers and hive tracker.
/:cl:
=> Adds the Critical sructure and ignore weed removal tag on Gargoyle.

code/game/objects/items/explosives/plastique.dm
As the title says, it changes it's 17 (fire_level) and 32 (burn_level) to 9(rounded up), 62
If you ever get a moment to properly use this you better get mileage out of it instead of waiting for it all to melt.
:cl:
balance: 2x damage on Genghis charge flames, 0.5x on it's timer. (17, 31) --> (9, 62) (Time rounded up.)
/:cl:
=> Doubles the Damage of Genghis Charge flames but halves it's total burn time. (rounded up)

code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Increases crusher sunder multiplier from .5 to .7
Barnet gave me his blessing for this one
Crusher can currently outheal most sources of sunder, and doubly so with a hivelord beam. Making them take more sunder should make them leave combat instead of rarely dropping below 75% armor.
:cl:
balance: Increases crusher sunder multiplier
/:cl:
=> Increases crusher sunder multiplier

code/modules/factory/howtopaper.dm, code/modules/factory/parts.dm, code/modules/factory/unboxer.dm, code/modules/reqs/supplypacks.dm
Adds every grenade to reqtorio and standardizes the grenade recipe.
Reworks the cost and amount of WP, razor and M15 nades in reqtorio.
More recipes, more reqtorio, more fun.
:cl:
add: Adds Incendiary, Sticky, Cloak, Tfoot, Trailblazer, Lasernade, HEFA and Antigas grenades to reqtorio.
balance: Adjusted the price and yield of M15, WP and razor nades in reqtorio.
/:cl:
=> Reqtorio expansion V 1.6

tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
Mecha keybinds can now actually be set.
Seems they weren't added to the pref menu when ported, so you only got keybinds if you had a new/wiped account, and couldn't change them. Honk.
Being able to use hotkeys is quite useful.
:cl:
qol: Mecha controls can now be correctly hotkeyed
/:cl:
=> Mecha keybinds

code/__DEFINES/dcs/signals.dm, code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/xenomorph/castes/beetle/abilities_beetle.dm, code/modules/mob/living/carbon/xenomorph/castes/beetle/beetle.dm, code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm, code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm, code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm, code/modules/mob/living/carbon/xenomorph/castes/praetorian/praetorian.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm, code/modules/mob/living/carbon/xenomorph/update_icons.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Fixes #14883
Fixes all xeno charge abilities (rav/defender/beetle/prae) that had various issues that prevented them from working partially or entirely.
Refactored all these abilities to a single charge type since they're all fundamentally the same. Desnowflaked a lot of code, although it can probably be improved further.
Removed some old unused xeno vars.
Added a new xeno_flag var for xeno mobs (someone thats not me please move the gorillion vars that should be vars to actual flags)
:cl:
fix: fixed various bugs with xeno charge abilities
refactor: Refactored xeno charge abilities
/:cl:
=> Xeno charge fixes

code/game/objects/effects/landmarks/excavation_site_spawner.dm, code/game/objects/machinery/research.dm
Removes tier 2, 3, and 4 xenomorph research samples, and strikes the reference of being tier one from the remaining sample name.
Following the removal of probing, the only xenomorph sample capable of spawning is the tier one variant, through xenomorph excavation landmarks. This still spawns marked as a tier one sample, implying to players that the higher tier variants are still somehow available.
Removing any reference to being a tiered variant resolves this issue ("Xenomorph research sample - Tier one" to simply "Xenomorph research sample").
Additionally, since the higher tier variants are no longer available through gameplay, they have been removed from the research file to reduce clutter.
 
:cl:
del: Removed references to high-tier xenomorph research samples.
fix: Simplified the name …
=> Removes High-Tier Xenomorph Research Samples

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
get_dist() will return -1 when Loc1 and Loc2 are the same object. If one or both of them is not on the map, an infinite value is returned.
https://www.byond.com/docs/ref/#/proc/get_dist
:cl:
fix: Primordial crusher doesn't crash the server anymore.
/:cl:
=> Fixes near-infinite loop with primordial crusher ability

code/modules/projectiles/gun_system.dm
Fixed a runtime for gun sounds where the gun is now empty.
Runtime bad
:cl:
fix: fixed a gunfire runtime when firing the last bullet of some guns
/:cl:
=> Sound runtime

code/game/objects/machinery/vending/marine_vending.dm
I completely forgot about the crash vendor (said 100 times).
:cl:
balance: Antigas nades are now in the crash weapons vendor
/:cl:
=> Adds antigas nades to crash vendor

code/datums/elements/directional_attack.dm
Title.
Theres been complaints about people not liking smacking their allies while they try to shoot the xenos. This should also help xenos not waste their attack cooldown on friendlies. 
:cl:
qol: Disabled directional attacks for mobs of the same faction as you
/:cl:
=> Disables directional attacks for mobs of the same faction as you

tgui/packages/tgui/interfaces/BlessingMenu.tsx
fixs a typo in the blessing menu where both points were called strategic
typo bad
:cl:
spellcheck: Blessing menu no long has two strategic point values
/:cl:
=> Fix blessing menu typo

code/modules/vehicles/armored/interiors/periscope.dm
Idea came up that loader can also act as a scout that calls out what's going on during his downtime
Gives periscope NV and zoom
:cl:
add: Tank periscope has night vision and zoom
/:cl:
=> Tank periscope buff

_maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
Moves this silo one tile right (shown here)
Unlucky xenos can sometimes have the phero tower destroyed on crash, this should hopefully fix/reduce that
:cl:
fix: Moved a silo on orion out of marines reach.
/:cl:
=> Moves orion silo one tile

_maps/shuttles/minidropship_standard.dmm, code/game/objects/structures/crates_lockers/walllocker.dm
Changes the layer of the fire-safety lockers to layer above objects, changes it's position on the standard tad
Similar reason to #15174, moved it over so if #15174 goes through, the spot won't be covered completely by the 2 items.
:cl:
qol: Fire-safety cabinets now layer above objects
qol: Moved the fire cabinet on the standard tad model to the other side of the pilot computer.
/:cl:
=> Changes Fire-safety Locker Layer, Changes It's Position On Standard Tad

code/modules/mob/living/carbon/human/species.dm
Synthetics/Early Synthetics will no longer enter critical condition, but instead, at -30 health, you start to overheat rapidly. I've tried to make it so you can still self repair to delay your death or even stop overheating, but not getting repaired can quickly kill you. 
The numbers may need tuning, but my reason is the burn mods for synths are fucked up real good. Or I'm just not mathing right.
If the balance gods want I could just make it so they still enter crit but take a lot of burn damage so you can't be dragged by xenos or stuck in crit. But I want to try this option first.
Synths slumping over the moment they hit -50 health is pretty boring, along with the situations where your body could be hidden by xenos or you could be stuck in crit for a long time.
Synthetics not falling …
=> Synthetic critical condition changes

code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm, code/datums/gamemodes/campaign/loadout_items/SOM/pockets.dm, code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm, code/datums/gamemodes/campaign/loadout_items/SOM/uniform.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/uniform.dm, code/game/objects/items/storage/pouch.dm, code/modules/clothing/modular_armor/som.dm, code/modules/projectiles/guns/smgs.dm
More tweaks.
- SOM bio trooper equip cost is now split across the armour (75) and the rockets (50). This is because the armour itself unlocks the free rad smg and rad nades via pouches or backpack.
- Bio armour now has a limit of 4 instead of 2 (rockets still have a limit of 2)
- Xfuel is slightly more expensive at 40 instead of 25.
- Added 'standard' nade pouches, with HE, incendiary and for TGMC, laser hefa nades. No extra cost currently.
- Added an SMG-25 loadout for TGMC SL's. Has a plasma pistol attachment, and a mix of normal and AP ammo (extendo mags if you take mag pouches).
- Added SMG-25 loadouts for medic and engie also, with standard ammo. (replaced smg90 for medic as its kinda just worse)
- Fixes gorgon armour not being able to take overclocked shield mods.
- Engies no longer …
=> Loadout changes

code/modules/mob/living/silicon/ai/ai.dm, tgui/packages/tgui/interfaces/PlayerPreferences/GearCustomisation.tsx
category for misc. things that equipped to right-hand slot was tagged but unused in actual UI preferences.
sets up a new category for "Other" gear trinkets and enables them. choosing multiple trinkets from this category properly puts the extra trinkets into your backpack (if you have one)
fixes #15262
:cl:
fix: new category for other trinkets available in "gear preferences" under the "preferences" window
/:cl:
=> fixes a missing category in gear preferences

code/datums/gamemodes/campaign/perks.dm
Fixed an issue leading to duplicate loadout options for some SOM roles after picking the shield perk.
I have no idea how no one reported or even complained about this.
Fix good.
:cl:
fix: fixed a minor bug with the overclock shield perk for some SOM roles
/:cl:
=> Shield perk fix

code/modules/projectiles/gun_attachables.dm
Guns that fit in belt slot will now properly re-equip when dropped with a mag harness.
Fixes the inconsistency and hopefully makes these weapons less troll
:cl:
fix: Mag harness now functions properly for belt guns.
/:cl:
=> Fixes mag harness for belt guns

code/datums/jobs/job/marines.dm
Squad management autopop up now only opens on the relevant gamemode
Annoying pop up go home.
:cl:
fix: fixed the squad management pop up opening for SL's on non nukewar modes
/:cl:
=> Squad management fix

code/modules/projectiles/gun_system.dm
Title. Basically a revert of Lumis PR way back.
Aim mode fire delay order is kinda insane, let's you hit basically IFF speeds of fire downrange, which is kinda absurd. It being instant aim mode again should be enough.
:cl:
balance: Focus order no longer gives a firerate increase while aiming.
/:cl:
=> Focus aura no longer gives you firerate bonuses in aim mode.

code/game/turfs/walls/r_wall.dm
80 bullet/las armor.
3000 HP Again.
5k HP was definitely overkill.
:cl:
balance: RWalls have 3000 hp again rather than 5000, slightly higher armor.
/:cl:
=> rwalls have 3k hp again, even slightly higher bullet/las armor

code/modules/projectiles/gun_attachables.dm
-0.35 aim speed mult rather than fire delay.
Aim fire delay was a mistake, though it'll need a new gimmick so this should at least keep it a useable attachie over magnetic harness.
:cl:
balance: rds now gives bonus speed while aiming instead of increased firerate.
/:cl:
=> rds now gives aim speed mult instead of fire delay

code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Increased from 20 to 22, still below pre-rework Warrior
Warriors damage output was made extremely gimmicky with wall throws, and even then is mediocre damage. Stunning into marines means you are throwing them back into the marine horde, and stunning on a wall is the only useful application of the new warrior besides throwing behind you. Hopefully allows warrior to still have less damage (especially since jab was killed and replaced with something worse) but not the same damage as spitter slashing. Small numbers matter, alot.
:cl:
balance: Warrior slash increase from 20 to 22
/:cl:
=> Increases warrior slash damage

code/game/objects/machinery/deployable.dm, code/game/objects/structures/barricade.dm, code/modules/projectiles/sentries.dm, code/modules/vehicles/unmanned/deployable_vehicles.dm
Trying to disassemble some deployables is a balloon alert instead of to_chat
Balloon > to_chat
This is also less misleading, since this flag has nothing to do with anchored status.
:cl:
fix: Trying to un-deploy some things no longer gives a misleading message
/:cl:
=> Trying to disassemble some deployables is a balloon alert instead of to_chat

code/modules/projectiles/gun_system.dm, code/modules/projectiles/guns/energy.dm, code/modules/projectiles/guns/pistols.dm, code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/guns/shotguns.dm, code/modules/projectiles/guns/smgs.dm
Akimbo scatter mod is now a much clearer var.
Previously we have an upper and lower scatter modifier (helpfully named as an accuracy mod), and scatter was modified by a rand between these two values, muliplied by 2.
This is a funny leftover from before scatter was reworked, back when scatter doubled as a probability of scattering, so now the random variation is completely pointless and confusing.
Clearer/less shitty code
:cl:
code: Cleaned up akimbo scatter mod code
/:cl:
=> Code improvement for akimbo scatter

code/modules/mob/living/carbon/xenomorph/abilities.dm
Fixes not being able to select special resin walls
Its a fix! It also nerfs xenomorphs by letting them choose the worse wall types /s
:cl:
fix: Fixed xenormophs being unable to choose any other special resin wall other than the bulletproof one.
/:cl:
=> Restores the illusion of choice regarding special resin walls(Fixes not being able to select any other type)

code/game/sound.dm
ghosts now hear soudns in tank properly
crew sound may have been offset? this fixes that
Falloff doesnt work but playsound is hardcoded to take a turf so it needs a more in depth fix
:cl:
fix: fixed tank sound for ghosts, and may have fixed it being offset
/:cl:
=> Sound tank fixes

code/modules/mob/mob_grab.dm
Old values are: agressive grabs need 1 resist to escape, neckgrabs need 2, strangles need 3.
New values: Agressive grabs are now 2, neckgrabs are 4, strangle is now 6.
For those not nuanced, breaking the resist immediately pulls you out of the hold, so you only really to spend 1 second grabbed by a warrior before being able to resist out and pull out a gun in the same second.
Xenos are not affected by this PR as xenos cannot upgrade their grab state, and warrior doesn't upgrade, they just immediately have you by the neck.
CQC buffs also. For comparison, melee can hit you over and over for a stunlock, most people can shoot you dead before you reach them, and passive grabs do not have a delay for breaking out of them, simply queueing up a movement, even if you're unable to move, breaks the …
=> Each time you upgrade a grab, you have to resist one more time to escape. (HVH PR)

code/modules/mob/living/carbon/human/human_attackhand.dm
Removes the odd piece of coding that made people with more armor stun for shorter times, but people who are bare naked get stunned for a maximum of **6** (holy shit) seconds
If you get hit by a 25% chance stun (punches) or a disarm that can only go up to 35% max if you have max cqc and your target doesn't. 
You'd still more likely either get taken down by: Melee weapons, shotguns, airburst rifles/rifles in general and SMG AP burst auto equivalent weaponry honestly.
:cl:
balance: Punch stun and Shove stun no longer get lowered by more armor, and increased with less armor, and will now always stun for 4 seconds. (Old values: 6 second stun base, lowered by armor rating.)
/:cl:
=> Punchstun and shovestun no longer care about armor and always stuns for 4 seconds now. (HVH PR)

code/modules/mob/living/carbon/human/species.dm
Fixes an issue with hold order rounding damage to zero in some cases, notably in hostile weather where the damage is split between many limbs, resulting in leaders able to order marines to simply take no damage.
As this effects all limb damage, this means most likely a large variety of incoming damage will now do (very slightly, 0.whatever) extra damage, as its more accurately rounding.
Funny invulnerability is bad.
:cl:
fix: Fixed hold orders rounding certain incoming damage down to 0, such as weather
/:cl:
=> Hold order rounding fix

code/modules/mob/living/silicon/ai/ai.dm
ports https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/186
scout droids are meant to grant nightvision. AI is meant to have restricted vision.
scout droids of current do not have nightvision. AI deploying to one then returning to core gives the AI nightvision.
bugs bad.
:cl:
fix: fix scout droids not having nightvision
fix: fixes AIs getting permanent nightvision after deploying to their scout droid
/:cl:
=> scout droid fix port from rutgmc

code/game/objects/items/storage/belt.dm
swaps researcher med rig dexalin bottle for isotonic
other medrigs have iso so this is part consistency; iso is probably more useful since rig belt comes with tricord anyways for oxy damage; and i dont see much sense to this since researchers can just grab dex+ injectors for free from the medvend and use the superior version of the chem for no cost
probably a greater indicator that dex/dex+ need to be consolidated or differentiated more but i didn't have any big ideas on what to do there
:cl:
balance: researchers spawn with isotonic pill bottles instead of dexalin bottles in their belts
/:cl:
=> swaps research rig belt dexalin for isotonic

code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
Nerfs warlock HP from 375 to 325.
This caste has very high stats despite also being extremely safe. Hopefully this should make a warlock think twice before taking an AP rocket to the face which they would previously not even drop into crit from.
:cl:
balance: Lowers warlock HP from 375 to 325.
/:cl:
=> Lowers warlock HP

_maps/map_files/Campaign maps/som_base/sombase.dmm
One of the campaign maps had some object that was removed in the multitile rework, but it wasn't removed for whatever reason.
cleanup
:cl:
del: Removed a nonexistant item
/:cl:
=> Remove old type from map

code/game/objects/items/toys/cards.dm
d
:cl:
code: kotahi uses proper shuffling in backend
fix: Fix kotahi always spitting out 4 +4s in a row
/:cl:
=> Fixes kotahi shuffling

code/__DEFINES/xeno.dm, code/_onclick/hud/hud.dm, code/_onclick/hud/xeno/xeno.dm, code/game/data_huds.dm, code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/living/carbon/xenomorph/life.dm, code/modules/mob/living/carbon/xenomorph/update_icons.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Did what I did for huds, but now for the UI button thingos, making them update whenever plasma and health are updated.
Also removed a bunch of extra calls on these procs on live and init. There's still redundant health calls, but that requires a different refactor to ensure all damage is actually updating health to begin with.
Accurate UI elements is good.
:cl:
qol: Xeno side UI plasma/health icons now also update instantly on change
/:cl:
=> Proper updating for xeno health/plasma side buttons

code/game/objects/structures/orbital_cannon.dm
Instead of devastation being on only the tile an explosion hit with a cluster OB, it will extend outwards in a cross section in all 4 cardinal directions 1 tile.
Helps make cluster OB more comparable to the other OBs like HE and Tangle (perhaps incen pending buff). This also means more gibs for more FUN.
:cl:
balance: Cluster OB now has 1 more tile of devastation per hit
/:cl:
=> Gives cluster OB 1 more tile of devastation

code/__DEFINES/conflict.dm
Changes light armor slowdown from .3 to .2 and vlarmor from .2 to .15
Light armor while it should remain fragile, feels way too slow for what its purpose is supposed to fulfill.
With the slowdown being almost negligible when compared to medium armor the cons seem to outweigh any of the pros it should have.
Adjusting the slowdown should allow light armor to feel well "light."
:cl:
balance: Changes light armor slowdown from .3 to .2 and vlarmor from .2 to .15
/:cl:
=> adjusted values of larmor and vlarmor

code/modules/vehicles/mecha/mecha_defense.dm
Explosions now stagger the occupant of a mech.
On its own this pr will do nothing, but when my projectile code pr's are merged, that means the mech will suffer from the stagger damage penalty of the occupant. i.e. you can stagger mech to reduce damage by 50%.
This is intended to be paired with #15307 so explosions dont throw mechs AND stagger.
I'll probs roll this out to some xeno abilities later, but this is mainly done with HvH in mind.
More mech interactivity.
:cl:
balance: Explosions stagger the occupants of mechs, applying stagger damage penalties to their weapons
/:cl:
=> Mech stagger

_maps/map_files/Sulaco/TGS_Sulaco.dmm
~~another parity PR, wowza!~~
probably could've rolled this into the earlier parity PR, tbh; sulaco was two 30mm ammo crates short of every other map for CAS, so i added the two extras
parity good for shipmaps; weird to have access to supplies vary by shipmap, especially if those supplies aren't relevant to shipside use at all
:cl:
fix: adds two more 30mm GAU ammo crates to Sulaco CAS bay to keep it in parity with other ships' CAS bays
/:cl:
=> fix: sulaco cas bay parity

_maps/map_files/Fort_Phobos/Fort_Phobos.dmm, _maps/map_files/Iteron/Iteron.dmm
Minor edits to the campaign base maps. Fully removed the old loadout vendors, some other tiny QOL tweaks like extra crates to help people move gear for pods/teleporter if desired, added engie vendors for access to spare welding goggles and such.
:cl:
qol: Campaign: Added some extra crates to the home bases and other minor adjustments
/:cl:
=> Campaign base map tweaks

code/game/objects/items/explosives/grenades/marines.dm, code/game/objects/structures/dropship_ammo.dm, code/game/objects/structures/orbital_cannon.dm, code/game/objects/structures/reagent_dispensers.dm, code/modules/admin/fun_verbs.dm, code/modules/projectiles/ammo_datums.dm
**PLEASE TM, THERE COULD BE VERY FUCKED THINGS HAPPENING**
Completely changes around flame_radius to eliminate damage RNG and make duration RNG more sane. Incen OB now has the same burn_intensity as xfuel.
Swapped around burn_intensity and burn_duration values on everything I could fine, because previously duration was being used for burnlevel (the damage) and intensity for firelevel (the duration), which was extremely fucked.
Less RNG is usually better, plus incen was laughably bad at clearing resin walls, where you could have tangle OB do the same area denial but marines could move in and clear the walls themselves way more reliably.
:cl:
balance: Explosives using flame_radius (phos nades, incen nades) no longer have damage RNG, and less duration RNG
balance: Incendiary OB now has the …
=> Less RNG in flame_radius, incen OB buff

code/datums/actions/action.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Basically when you select bombard you take 3 seconds to dig in, but can move freely at any time during this. This was behavior removed with root that I forgot to bring back.
Should have been brought back with root removal to restore pre-root behavior.
:cl:
balance: Restores pre-root boiler dig mechanic, have to sit still and wait 3 seconds before firing a glob (you can still move, but cancels the channel)
/:cl:
=> Restores pre-root boiler dig mechanic

code/modules/reagents/reagents/other.dm
When you scan someone with water, it should now not say it is an unknown reagent.
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14537
Water shouldn't be a mystery reagent.
:cl:
fix: water is now scannable by medical scanners
/:cl:
=> Water is now recognizable by medical scanners

code/modules/mob/living/carbon/human/species.dm
Changes the values for Synthetic burn damage when in critical condition. These should be a little more lenient but still able to add a decent drawback and kill you if you don't repair quickly.
People will get into crazy situations on live and this could end up needing a tweak again, but we should just try this for now.
* Normal Synthetic damage range: 5-16
* Early Synthetic damage range: 7-19
* Both types will stammer when in critical condition.
* 12% chance each tick to spark with a visible message in chat.
I think I messed up the damage range last PR, some people have complained about Early/Normal Synthetics taking too much damage. These should be less intense but able to kill quickly.
Sparking occasionally and stammering are a cool flavor change.
:cl:
balance: The overheating damage …
=> Synthetic overheating damage tweak + cool effects

code/datums/quick_load_beginners.dm, code/modules/paperwork/beginner_tutorials.dm
edits beginner loadout tutorials. three parts:
1. wraps the text on them so they're manageable to edit in the future
2. updates outdated things (antenna usage for ammo drops, RDS on MG60)
3. adds more complete info on the engineer kits about everything in them including weapon handling
updates two loadouts:
1. grenadier had helmet module switched from antenna to HOD (matches armor on the set now and more useful)
2. smartminigunner had the backpack fire extinguisher replaced with one cloak grenade and an inap injector (there was another full-sized fire extinguisher in suit storage which doesn't feel very useful)
keep the newbie tutorials updated so they dont wonder why their tutorial talks about their MG60 having an RDS, or why the RO wont send ammo to their antenna when it's active. …
=> edits beginner loadout tutorials + updates some of the loadouts

_maps/map_files/Theseus/TGS_Theseus.dmm
nani said instead of trying to remove theseus, i should just rework it, so i spent four hours doing what i could to make PO lives easier :)
this PR doesn't fix the whole ship, but does some things, mostly in the hangar.
- moves all the cas stuff together
- re-aligns the alamo loading zones
- moves FC bunks to south of hangar, moves synth room there too
- redoes the staff officer area
- very gracefully shoves a spot in for the vehicle bay on the north of the hangar
ship has really bad flow; people don't know where the synth stuff is
holds a space for new vehicle features
fixes alignment of stuff with alamo since it got re-done
there's a lot of stuff that'll remain suck-y, like moving pods from req, if you're ST juggling OB and gens, or CSE juggling those and overwatch, etc. the woes of …
=> theseus edits

code/modules/clothing/modular_armor/style_line.dm
is it a fix? is it qol? we don't know
hairs now mask on style line hats where appropriate
everything but the headband has the flag `HIDE_EXCESS_HAIR` added, which is just a fancy way of saying that if you wear any of these hats, your hair won't clip to the sides or above around the hat. 
i think it looks really nice and makes the hats stand out more
here's how it is now
:cl:
qol: style hats now mask hairs behind them so they look like they're layered on your head properly
/:cl:
=> style hats now mask hair

code/datums/gamemodes/campaign/loadout_items/SOM/head.dm, code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm
SOM medic loadouts in campaign now have their RR in their hat like marine medics, and now always have 2.
Consistancy, fix wrong amounts.
:cl:
balance: Campaign: SOM medics now always have 2 RR injectors in their helmets
/:cl:
=> Consistant SOM medic supplies

code/datums/gamemodes/campaign/faction_stats.dm
When you spawn in during campaign, it will not auto open the loadout screen (but not for the reinforcement roles as they don't need it).
QOL, faster for this mandatory screen and helps new players.
:cl:
qol: Campaign: Loadout screen automatically opens on spawn where required
/:cl:
=> Campaign loadout popup

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Fix petrify getting stuck if the king is gibbed or otherwise deleted before it wears off.
Fixes #15336
:cl:
fix: fixed petrify getting stuck if the king was deleted before it wore off
/:cl:
=> Petrify gib fix

code/game/objects/items/explosives/grenades/marines.dm, code/game/objects/items/scanners.dm, code/game/objects/items/storage/backpack.dm, code/game/objects/machinery/constructable_frame.dm, code/game/objects/objs.dm, code/game/objects/structures/window.dm, code/modules/clothing/clothing.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/living_defense.dm, code/modules/power/batteryrack.dm, code/modules/power/cell.dm, code/modules/power/smes_construction.dm
Crit_fail, reliability and item_fire_stacks go into the bin.
real_explosion_block is moved to windows as thats the only place its used. Could be useful for other stuff but someone can move it back if it is needed.
Cleaned up a bit of incidental flare code since I was already touching it.
Unused/stinky vars.
:cl:
code: Cleaned up some object and flare code
/:cl:
=> Kill some obj vars

code/__DEFINES/campaign.dm, code/datums/gamemodes/campaign.dm, code/datums/gamemodes/campaign/rewards/reserves.dm
When your respawn timer runs out, the respawn window automatically opens for you.
Also made the respawn window open for ghosts on mission end (previous only did so for living mobs)
Finally made the rapid reserver asset also make the window pop up.
QOL, especially you didn't realise the timer was up/didn't hear the sound etc.
:cl:
qol: Campaign: Respawn window automatically opens when your respawn timer is up, or when the rapid reserve asset is used
/:cl:
=> Campaign auto respawn window

code/__DEFINES/layers.dm, code/datums/components/beacon.dm, code/game/objects/effects/temporary_visuals/miscellaneous.dm, code/game/objects/items/devices/minimap_tablet.dm, code/game/objects/items/radio/headset.dm, code/game/objects/machinery/computer/nt_access.dm, code/game/objects/machinery/computer/nuke_disk_generator.dm, code/game/objects/machinery/nuclearbomb.dm, code/game/objects/machinery/overwatch.dm, code/game/objects/structures/campaign_structures/campaign_structure.dm, code/game/objects/structures/campaign_structures/capture_objectives.dm, code/game/objects/structures/campaign_structures/deploy_blockers.dm, code/game/objects/structures/sensor_tower.dm, code/game/objects/structures/teleporter.dm, code/modules/events/intel_computer.dm, code/modules/power/groundmap_geothermal.dm, code/modules/vehicles/armored/__armored.dm, code/modules/xenomorph/pherotower.dm, code/modules/xenomorph/resin_gargoyle.dm, code/modules/xenomorph/silo.dm, code/modules/xenomorph/spawner.dm, code/modules/xenomorph/tunnel.dm
Uses layers for minimap blips, so important things layer over less important things.
Defibbable marines layer over living/undefibbable marines.
Tonk, disk computer, nuke, silo, campaign objectives etc all layer higher.
Fixes #14495
Better visual clarity.
:cl:
qol: Certain minimap blips such as important structures or defibbable marines layer over other blips
/:cl:
=> Minimap layers

code/game/objects/items/firesupport_binoculars.dm
Adjust some targeting code for fire support binos, and cleaned it up a bit.
- You now actually needactually see your target to lase so no more calling cas through walls, and you can block it with smoke etc.
- Lasing is now done against an atom, not turf. This means if you lase a human/mech/etc, THE FIRESUPPORT WILL TARGET THEM IF THEY MOVE. This only lasts until the firesupport is actually called in (i.e. once the lase goes away) so you still have time to run away before the firesupport blasts the spot you were standing in.
- This also means you could cancel the firesupport entirely if you break LOS around a corner or something, so in most cases its probably better to still target a turf, but could be funny for dropping missiles on mechs.
In the future I might add the ability to keep …
=> fire support bino tweaks

code/__DEFINES/_math.dm, code/controllers/subsystem/advanced_pathfinding.dm, code/controllers/subsystem/weeds.dm, code/game/atoms/atom_movable.dm, code/game/objects/items/devices/minimap_tablet.dm, code/game/objects/machinery/mortar.dm, code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm, code/modules/mob/living/carbon/xenomorph/facehuggers.dm, code/modules/projectiles/ammo_datums.dm
Byond's `view()` proc does not return objects in outwards order. It uses a very weird "snake" like pattern, starting from the top-left turf. This means that `leap_at_nearest_target()` was not infact leaping at the nearest target.
Additionally, I made it use Euclidean distance so that it prefers cardinal movement over diagonal movement, because diagonal `throw_at()` fucks up when theres a wall along the diagonal move.
:cl:
fix: Facehuggers will now prioritize the nearest marine, preferring cardinal directions.
/:cl:
=> Facehuggers actually prioritize the nearest marine

code/modules/projectiles/gun_attachables.dm, code/modules/projectiles/guns/grenade_launchers.dm
The single shot grenade launcher now fits magharn and rail flashlight
Consistency with the other GL, hopefully enabling loadouts to use this now that it has mag harness. Its a good side option for rushers to use and has a slightly slower fire rate of 1.25 seconds between grenades vs 1.2 on the GL70, so adding magharness should make it worth placing into loadouts.
:cl:
balance: GL-81 can now fit magnetic harness and rail flashlight.
/:cl:
=> GL-81 now fits attachments

code/modules/mob/living/carbon/xenomorph/life.dm
Title.
#15167 broke a certain case where some xenomorphs that have a set plasma regen limit can regenerate past said limit if they do a specific thing.
This fixes that by clamping the actual plasma regeneration before applying it.
(Alternatively could be done by having another arg in the add_plasma proc that tells whether to respect the cap, but since the proc I'm adjusting is the only one that is for natural plasma regeneration this should be fine)
Fix man good.
:cl:
fix: Certain xenomorphs can no longer regenerate past their plasma cap under specific circumstances.
/:cl:
=> Fixes caste passive plasma regen limits not applying under certain circumstances

code/datums/fire_support.dm
Campaign acid smoke was supposed to be opaque like the rest of the HvH smokes (like the acid nade)
Fix good.
:cl:
fix: Campaign mortar acid smoke is opaque
/:cl:
=> Fixes campaign mortar acid smoke

code/game/objects/effects/effect_system/smoke.dm
This shit is impossible to see right now. Between the various light sources and dark areas, would you even know there is anti gas here?
Current:
After:
Being able to see stuff is good.
:cl:
qol: Antigas smoke is more visible
/:cl:
=> Visible antigas

code/modules/factory/unboxer.dm, code/modules/reqs/supplypacks.dm
All AMR magazine refills were called the same in req, despite giving you one of three seperate mags. This corrects the supply pack names.
Additionally, railgun factory parts said they gave you different ammo types, but all three of them just gave you standard refills. They now actually give you the correct ammo types.
Fix man good.
:cl:
fix: Railgun factory parts now give you their respective ammunition types instead of only standard canisters.
spellcheck: AMR factory parts now can be differentiated by name as opposed to by feeling.
/:cl:
=> Fixes some factory oopsies nobody has bothered to fix

_maps/map_files/Arachne/TGS_Arachne.dmm
Expands the Arachne mech bay to allow for the incoming vehicle additions.
Update compatibility, good!
:cl:
add: Expanded the Arachne vehicle bay.
del: Removed the Arachne flight control station, to make room for the vehicle bay.
/:cl:
=> Arachne Vehicle Bay Expansion

code/datums/gamemodes/campaign/campaign_assets.dm, code/datums/gamemodes/campaign/missions/base_rescue.dm
Makes this mission better for SOM.
Marines can no longer use ANY firesupport assets (NT doesn't want you dropping bombs on their expensive outpost).
SOM automatically get some colonial militia support (fluffwise they're the ones that alerted/called in the SOM about this base).
Reduced SOM mech count to 4.
Significantly easier for SOM when they don't have to worry about CAS and mortar dropping on their head.
:cl:
balance: Campaign: NT Base Rescue no longer allows firesupport for TGMC
balance: Campaign: NT Base Rescue provides SOM with automatic militia support
balance: Campaign: NT Base Rescue reduced SOM mech count to 4
/:cl:
=> Base rescue tweaks

code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/missions/base_rescue.dm, code/datums/gamemodes/campaign/missions/mech_wars.dm, code/datums/gamemodes/campaign/missions/patrol_mission.dm
Reducedthe pregame wait to 90 seconds from 3 minutes.
Reduced it to 3 minutes from 5 for Mech War.
Reduced the delay before game timer starts from 3 minutes to 1.
Reduced it for Combat Patrol (and mech war by extension) to 3 minutes from 5 (it still needs time as a team will instantly lose if no one has deployed when that time has run out... as has happened at least once).
Extended NT Base Rescue game time by 2 minutes. As SOM are the hostile team I don't want to penalise them, however the reduction of game timer delay effectively makes it harder for the attacker on all other missions.
Less waiting around.
More pressure on the attacking team.
:cl:
balance: Campaign: Reduced game and pregame delays on most missions
/:cl:
=> Campaign game timer tweaks

code/datums/gamemodes/campaign/missions/supply_raid.dm
Adjusted the SOM supply raid mission so SOM have to destroy 6 objectives instead of 5 for a minor victory.
More in line with the Marine mission, where you have to destroy 4/6 objectives to win
:cl:
balance: Campaign: SOM have to destroy 6 objectives to win on Supply Raid
/:cl:
=> Supply raid objective tweak

code/modules/vehicles/unmanned/unmanned_vehicle.dm
Fixes #15360
No more unlimited ammo for the Igunananana
:cl:
fix: Iguana ammo boxes now properly delete themselves when they perform a reload that uses up all their ammo
/:cl:
=> Fixes unlimited Igunana ammo reloads

code/__DEFINES/_math.dm, code/__HELPERS/math.dm, code/modules/mob/living/carbon/xenomorph/facehuggers.dm
In my previous PR i claimed I made huggers prioritize orthogonal movement. I had a brainfart and mixed up Euclidean and Manhatten distance. This corrects my error.
:cl:
fix: Huggers *actually* prioritize orthogonal marines over diagonal marines.
/:cl:
=> Fix huggers for REAL

code/_globalvars/lists/game_modes.dm, code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/missions/patrol_mission.dm
Fixes the loot tables being in the wrong order for the SOM initiated combat patrol/mech war missions.
Made it a generic proc so it sets it for all missions/easy to update for other factions if required.
Fix.
:cl:
fix: Campaign: Fixed some loot tables being wrong from SOM initiated combat patrol/mech war missions
/:cl:
=> Campaign loot table fix

code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Mech explosive armour module now increases bomb armour by 25 instead of 50.
It was pretty smelly in HvH to have complete bomb immunity.
:cl:
balance: Mech explosive armour modules increased bomb armour by 25 instead of 50
/:cl:
=> Mech explosion resistance reduction

code/__DEFINES/dcs/signals.dm, code/datums/actions/weapon_actions.dm, code/datums/keybinding/weapons.dm, code/game/objects/items/weapons/blades.dm, code/game/objects/items/weapons/twohanded.dm
Both melee specials (sword lunge and axe sweep) can now be used at 0 stamina. This means if you use up all your stamina running, you can still use your special (you can't use it if you have actual stamina damage however, so wouldn't be able to do this repeatedly, or if you were suffering from neuro etc.
Sword lunge uses 8 stam instead of 12.
Axe sweep uses 10 instead of 12.
Axe sweep now takes you one step towards your target before attacking. Unlike  sword lunge, this is a Move, not a throw so you can't bypass cades and the like with it, but it does give you that tiny bit of extra mobility to give you an advantage (and can be used for pretty dirty combos in certain situations).
Both attacks properly use an attack dir (relevant for mech facings), and will no longer knockback mechs or …
=> Melee special attack adjustments

code/datums/gamemodes/campaign.dm, code/datums/gamemodes/campaign/missions/asat_capture.dm, code/datums/gamemodes/campaign/missions/fire_support_raid.dm, code/datums/gamemodes/campaign/missions/patrol_mission.dm
Adjusted a couple of timings.
First mission initial delay is a little longer again for latejoins.
Autobalance proc is called earlier so it doesn't get delayed by late z-level loading funniness
ASAT and fire support missions get slightly (1 minute and 30 seconds respectively) extra. Mainly this was just to line up the game clock starting with the attacking team deploying.
Fix some wack timing issues
:cl:
qol: Campaign: fixed the timing of the autobalance prompt
balance: Very slight increase in time for ASAT and firesupport missions
/:cl:
=> Campaign timing adjustments

_maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm, _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm, code/datums/gamemodes/campaign/faction_stats.dm, code/datums/gamemodes/campaign/missions/patrol_mission.dm, code/game/objects/effects/landmarks/landmarks.dm, code/game/objects/structures/campaign_structures/capture_objectives.dm
Fixed combat patrol on Orion not having sensor tower landmarks.
Fixed Patrick's Rest having 2 towers on the south side.
Fixes.
:cl:
fix: Campaign: Fixed an issue with towers on Orion Outpost and Patrick's Rest
/:cl:
=> Campaign tower fix

code/game/objects/items/weapons/blades.dm
This ability broke in the same way as xeno lunges, but I forgot to update this to a bump signal instant.
Working ability is gud.
:cl:
fix: Campaign: Fixed the sword lunge ability not properly doing damage
/:cl:
=> Sword lunge fix

code/__DEFINES/loadout.dm, code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/magazines/misc.dm, code/modules/projectiles/magazines/specialist.dm
Fixed BR-8 Magazine desc and shield module in SL loadout typo and clarify .45 acp ammo box is only for pistol and 8.6x70mm ammo difference of SR-81 and SR-127.
Clarity
:cl:
spellcheck: fixed BR-8 mag typos and clarify some bullet with same caliber.
spellcheck: fixed typo on Shield module in SL loadout. 
/:cl:
=> Fixed some typo and Clarify some ammo with the same caliber

code/__DEFINES/dcs/signals.dm, code/datums/keybinding/mecha.dm, code/modules/vehicles/mecha/combat/gygax.dm
Adds a hotkey to mech actuator overload.
Its really annoying not having a hotkey.
:cl:
qol: Mech actuator overload has a hotkey
/:cl:
=> Mech actuator overload hotkey

code/modules/codex/entries/guns_codex.dm
You can now check what weapon skill applies to a given weapon by checking its codex entry.
Choosing gun perks in campaign is kinda funny when its not clear which guns it will apply to in some cases.
:cl:
qol: Gun codex entries now state what weapon skill applies to them
/:cl:
=> Gun codex shows relevant weapon skill

code/datums/gamemodes/campaign.dm, code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/hvh.dm, code/datums/jobs/job/job.dm, code/modules/mob/living/carbon/human/life.dm
Removing job points now correctly removes job points, and removes job slots as required.
Made a couple of HvH things call this correctly. This means scaling roles (specifically SOM veterans) now actually dynamically scale, instead of just getting more and more slots as the  game progresses.
Additionally, some minor related HvH balance changes. SG scales in HvH like it does in HvX.
Vet base slots increased to 4 now that they will actually update correctly.
Corrected engie slots to 8, in line with medics.
Working code good. Previously it just deducted job points even if it went into the negative. While overall that meant you wouldn't get more slots than intended, it means you could stretch past what it should be at a given time.
In HvH, it simply wasn't calling the right proc to begin with, …
=> Job point fix

code/modules/projectiles/ammo_datums.dm, code/modules/vehicles/armored/_multitile.dm
Removes deva from tank shell
Reduce integ to 900
Tank immune to balance freeze according to Kurt, requested changes from Tivi and Kuro
:cl:
balance: Tank's LTB cannon no longer has devastation.
balance: Tank's integrity reduced from 1250 to 900 due to armor working again
/:cl:
=> Tank balance changes #1

code/modules/mob/living/carbon/xenomorph/evolution.dm
Fixes #15015
You no longer have to ghost in and out if you commit the sin of caste swapping/ regressing while zoomed in as boiler
:cl:
fix: Fixes view getting bugged if you regress/caste swap while zoomed in
/:cl:
=> Fixes caste swapping/regressing while zoomed in causing your vision to get stuck forward

code/game/atoms/_atom.dm, code/game/objects/obj_defense.dm, code/game/turfs/liquid_turfs.dm, code/modules/mob/living/living_defense.dm, code/modules/vehicles/mecha/mecha_defense.dm
Lava now has a lava_act proc at the atom level, instead of handling everything snowflakely in the laval proc itself.
Fixed lava not properly hurting mechs.
Lava will now actually damage/destroy objects.
Cleaned up some code a little.
Less snowflakey, lava actually destroys items insted of just floating around chilling.
:cl:
balance: Lava will actually melt objects now
/:cl:
=> Minor lava refactor

code/__DEFINES/is_helpers.dm, code/game/objects/items/tools/mining_tools.dm, code/game/objects/structures/mineral_doors.dm, code/game/turfs/closed.dm, code/game/turfs/walls/resin.dm, code/game/turfs/walls/wall_types.dm, code/game/turfs/walls/walls.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm, code/modules/xenomorph/xeno_turret.dm
A lot of things were doing istype(I, plasmcutter), So I added an istype helper isplasmacutter(I)
Also I've removed a bunch of balloon alerts, since getting 4 balloon alerts at the same time is completely useless.
Readable balloons good
:cl:
fix: Plasma cutter is no longer spammed by unreadable balloon alerts
code: adds isplasmacutter(I)
/:cl:
=> Make plasma cutter balloon alerts readable + is_helper

code/game/turfs/closed.dm
What it says on the tin. (Wish I could just add a map edit tag manually.)
The maps left with jungle walls (jungle outpost, slumbridge and lawanka) all use weedable grass. It is weird that these do not either given they are used on all those maps as well.
:cl:
code: Jungle walls spawn weedable grass when hit with a devastating explosion
/:cl:
=> Jungle walls spawn weedable grass when hit with a devastating explosion

code/modules/clothing/glasses/glasses.dm, code/modules/clothing/glasses/hud.dm, code/modules/reqs/supplypacks.dm
Welding goggles use `activate()` like every other eye wear. Medhuds should also work again, apparently the `if(QDELETED)` was not needed (yet it worked before I made any changes to it somehow?). A lot of the code is mostly so the action icons properly changed to reflect the state they were in.
Oopsy poopsy broke the glassies.
:cl:
fix: Welding goggles and HUD glasses work again. Night vision module req order spawns the actual module.
/:cl:
=> Glasses and goggles can be activated properly again

tgui/packages/tgui/interfaces/MarineSelector.jsx
in the synth vendor, there was a really long tag on a singular armor (flak jacket)
this pushed the "vend" button for all options outside the area of the default window
i've gone ahead and cleaned up the language for this, not only because the buttons didn't fit, but because I think the verbiage was too wordy and would rather not have it so close to the object name itself.
better looking ui
not super needed? it's 7px of difference
=> cleans up synth vendor tgui

_maps/map_files/icy_caves/icy_caves.dmm
Removes the plat miner above medbay from icy caves.
This plat miner is very easy to permanently take just by landing tad in the spot that it would already want to be in for pushing last disk. Icy Caves is also a lowpop map so xenos typically wont have many extra resources to devote to sieging an autism tad plat miner fort.
:cl:
balance: Removed outdoor plat miner from Icy Caves
/:cl:
=> Removes an outdoor plat miner from Icy Caves

code/game/objects/items/explosives/grenades/marines.dm
Dense smoke nades (the base type) has a radius of 6 instead of 7. All other nades unchanged.
The area of these nades is pretty massive, toning it down just a tiny bit should help make them more managable. Only a HvH change since in practice they almost never get used in HvX/they're borderline grief when they are.
:cl:
balance: M40 HSDP smoke grenade smoke radius reduced to 6 from 7
/:cl:
=> Smaller smoke radius for dense smoke nades

code/modules/vehicles/armored/armored_weapons.dm, code/modules/vehicles/mecha/equipment/weapons/weapons.dm
mechs/tanks can now aim at specific bodyparts like mobs.
This wasn't particularly relevant in hvx (outside of instant delimbing team mates with heavy cannon, aylmao), but is quite relevant to HvH.
Working feature good.
:cl:
fix: Mechs and tanks properly respect target def zone
/:cl:
=> vehicle def zone fix

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Title. Currently, phero info is setup in such a way that you have no in-game way to know whether you have 4 phero or 6+ phero. This gives you more knowledge about the true strength of pheromone affecting you, by providing the exact strength of pheromone in parentheses after the general category.
Also corrects a code comment about phero brackets which was just wrong.
Unneccessarily ambiguous information.
:cl:
qol: Pheromone strength in the statpanel now shows the actual value next to the approximate category.
spellcheck: Corrected a code comment about phero brackets which was quite outdated.
/:cl:
=> Xeno pheromone displays the exact value in the statpanel

code/__DEFINES/mobs.dm, code/game/objects/items/firesupport_binoculars.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/update_icons.dm, code/modules/projectiles/guns/specialist.dm
Fixes the laser layer, causing AMR/fire support bino laser to layer underneath everything else.
This is because it uses float layers, so higher number = lower float layer.
Also cleaned up some random unused defines/vars/procs that I noticed when looking at layers.
Hidden lase bad.
:cl:
fix: AMR/fire support bino lase no longer layers under clothing and such
/:cl:
=> Laser layer fix

code/game/objects/items/cocoon.dm, code/game/objects/machinery/vending/vending.dm, code/game/objects/obj_defense.dm, code/game/objects/structures/droppod.dm, code/game/objects/structures/fence.dm, code/game/objects/structures/mine_structures.dm, code/game/turfs/walls/walls.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm, code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm, code/modules/projectiles/sentries.dm, code/modules/vehicles/_hitbox.dm, code/modules/vehicles/unmanned/unmanned_vehicle.dm, code/modules/xenomorph/silo.dm, code/modules/xenomorph/spawner.dm
Fixes a few instances where object damage was incorrectly applying armour multipliers when it shouldn't (like mech component damage where armour had already been calculated).
And a few misc define fixes.
Bug fix.
:cl:
fix: fixed a few instances where object damage was incorrectly applying armour multipliers when it shouldn't
/:cl:
=> Object damage fix

code/modules/projectiles/ammo_datums.dm
Airburst shrap no longer incorrectly inherits IFF.
I'm not sure which pr broke it, but where the original projectile has IFF, the shrap after it explodes should not.
Funny IFF shrap bad.
:cl:
fix: fixed IFF shrap on airburst weapons
/:cl:
=> Airburst IFF fix

code/modules/clothing/modular_armor/modular.dm, code/modules/clothing/under/under.dm
If you inspect someone, you can see what modules they are wearing. If you do it to your armor directly, you can't.
This PR just bolts the same code the armor examine.
Much easier to know what your loadout is, especially if you spawned with it, like ERT's, EORD, starter sets.
:cl:
qol: helmets, armor and suits show their equipped modules on examine
/:cl:
=> Make it so helmets, armor and suits show their equipped modules on examine

code/datums/gamemodes/campaign/individual_stats.dm, tgui/packages/tgui/interfaces/IndividualStats/IndividualLoadouts.tsx, tgui/packages/tgui/interfaces/IndividualStats/IndividualPerks.tsx, tgui/packages/tgui/interfaces/IndividualStats/index.tsx
Should greatly improve the perf of this UI (usually its fine but some times/for some people it lags horribly).
Now it just loads the perk or loadout data (not both) and only loads it for the currently selected job tab.
Bad perf is bad.
:cl:
code: Some performance improvements to campaign loadout UI
/:cl:
=> Campaign loadout UI performance improvement

_maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm, _maps/map_files/oscar_outpost/oscar_outpost.dmm, _maps/modularmaps/oscaroutpost/oscarnorthvar1.dmm, _maps/modularmaps/oscaroutpost/oscarnorthvar2.dmm, _maps/modularmaps/oscaroutpost/oscarnorthvar3.dmm, _maps/modularmaps/oscaroutpost/oscarnorthvar4.dmm
Replaces the tl102 with hsg_102 in mapping files.
Turns out, https://github.com/tgstation/TerraGov-Marine-Corps/pull/15409 nuked the /tl102 with the /hsg_102, but they forgot that maps use these items...
:cl:
fix: fix the HSG_102 that spawn on maps having the wrong item path
/:cl:
=> replace tl102 with hsg_102 in maps

code/controllers/subsystem/vote.dm
A common complaint was the same map 3-4 times in a row. This eliminates that.
:cl:
del: Removes the ability to vote for the current map during groundmap vote
/:cl:
=> Removes the ability to vote for the current map during groundmap vote

code/__DEFINES/admin.dm, code/__HELPERS/type2type.dm, code/_globalvars/bitfields.dm, code/_onclick/hud/screen_objects/menu_text_objects.dm, code/modules/admin/admin_ranks.dm, code/modules/admin/holder.dm, code/modules/admin/panels/poll_panel.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/poll_managment.dm, code/modules/mob/new_player/new_player.dm, code/modules/mob/new_player/poll.dm
New permission, R_POLLS. Used for the Server Poll Management verb. Would be given to those with DBRANKS and maintainers to collect data. Needs lead permission to be merged.
**ACTIONS REQUIRED FOR THIS TO WORK**
Someone with +DBRANKS is required to add +POLLS to the followings ranks:
- Host
- Headcoder
- Headmin
- Seniormin
These ranks already have +DBRANKS. The following ranks need +POLLS but do not have +DBRANKS.
- Maintainer
- Art Maintainer
:cl:
admin: R_POLLS rank used for Server Poll Management
/:cl:
=> Changes Server Poll Management to use new rank, R_POLLS

code/game/objects/machinery/vending/marine_vending.dm, code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/plasma.dm, code/modules/reqs/supplypacks.dm
Edit: Kuro says keep funny free ammo.
Removed the funny free plasma cells from the weapon vendor, I didn't realise req guns already had free ammo for whatever reason?
Made the SMG/rifle a bit more expensive.
Also fixed a bug with the cannon having an incorrect couple of vars set by default
Funny spam bad.
:cl:
balance: Made SMG and rifle more expensive
fix: Fixed plasma cannon starting with an incorrect ammo type set
/:cl:
=> HvX plasma availability tweaks and fix

code/game/objects/machinery/vending/marine_vending.dm
As the PR title suggests, it simply adds the TE powerpack to the Automated weapon rack, as it just makes more sense to be there, after all swords with scabbards are available in the clothing vendor too right?
Just a simple QoL change really.
(it's in fact just one)
:cl:
qol: The TE powerpack is now available in the default, Crash and Valhalla Automated weapon rack
/:cl:
=> TE powerpacks are now available in the automated weapon rack

code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm, code/modules/projectiles/ammo_datums.dm
Boiler glob CD increased by 5 seconds (old elder time)
Boiler lance range only extends to their zoom range
These issues still plagued boiler even when it had root, but of course people didn't really play Boiler.
The gas uptime can be quite oppressive hence the CD nerf, should be fine around there given previous Elder boiler
The lance change is a bit more complicated. Lance going offscreen of boiler range seems to hint that it was made to counter snipers, as the snipers cannot see the Boiler. That doesn't exactly make sense since snipers are supposed to at least plink at the boiler. Lance still will remain effective in that it goes past the targeted turf while doing mega, mega damage. Normal glob keeps the 30 range since it cannot shoot offscreen without other xeno aid. The 25 range for …
=> Boiler nerfs #2 (hopefully final)

code/datums/keybinding/xeno.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/bull.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
**For the love of god do a test merge**
Bull has boiler's zoom ability
Bull is now a big mob (same size as crusher for the purpose of abilities)
For the zoom ability:
Crusher and Bull are interesting because they are both very similar and very different. One main difference is the fact that bull is not affected by razor wire, but Crusher is. Giving zoom to either of these xenos to allow them to make a good decision based on information given has been an idea that has floated in the air for awhile; though I feel like it is better for bull to have and crusher to not. Crusher has the ability to shrug off alot more than Bull, as well as the counter of razor as a surprise. Giving it zoom would sort of ruin the purpose. Bull has many more ways to die instantly when charging, thus I believe the …
=> Bull buffs

code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm
Added a missing whitelist for surt armour, for marine standards.
Fix.
:cl:
fix: Campaign: Fixed a missing whitelist requirement for Surt
/:cl:
=> Campaign: Missing whitelist for surt

code/modules/shuttle/marine_dropship.dm, code/modules/shuttle/shuttle.dm
Commissioned by @novaepee 
Touching the alamo console now cancels takeoff
This makes more sense. Marines are only safe *after* they took off fully, and not during the takeoff channel.
:cl:
fix: Touching the alamo console as a xeno stops takeoff
/:cl:
=> Touching the alamo console (as xeno) cancels takeoff

code/datums/gamemodes/_game_mode.dm, code/datums/round_statistics.dm, code/game/objects/structures/orbital_cannon.dm
Number of OB's fired will be added to round end stats.
Stats good.
:cl:
add: Add OB shots to round end statistics
/:cl:
=> Add OB shots to round end statistics

code/game/objects/effects/decals/contraband.dm
So, apparently posters are all broken. They've been broken for some time, but since I made the invalid icon_state icon an error sign now you can actually tell.
This PR should fix them.
People don't like looking at error signs all over the maps. 
:cl:
fix: Fixed posters displaying error signs instead of their valid icon.
/:cl:
=> Fixes posters

code/modules/mob/living/carbon/xenomorph/life.dm
Near halves the armor warding gives, essentially what I did in #14030.
As we learned with hold order, stacking armor values at the higher end can lead to some really wacky damage. For example, with king warding on crusher you could be receiving 3.75dmg from a T12 bullet, which not accounting for sunder (you can heal the in-combat sunder with hivelord beam or just existing, meaning getting shot by the small arms will only increase sunder very slowly) would take over 100 bullets to kill, realistically 70+ with sunder accounted for.
:cl:
balance: Warding pheros have near half effectiveness, from 2.5 armor per aura level to 1.5
/:cl:
=> Warding nerf

code/game/objects/items/storage/boxes.dm, code/modules/factory/unboxer.dm, code/modules/reqs/supplypacks.dm
This adjusts the several grenade boxes' pricing in req as well as the cost and amount of grenades produced in reqtorio.
All grenade boxes will now contain 25 grenades.
All reqtorio grenade factories will produce 50 grenades.
The reqtorio cost efficiency is 1.5 times cheaper than buying boxes.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/yashm/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/yashm/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head> …
=> Reworks Grenade req pricing and reqtorio pricing and yield. Actually adds cloak nade refill to req.

code/datums/skills.dm
gives Staff Officers POWERLOADER_TRAINED and ENGINEER_ENGI where they previously inherited the values for engineering and powerloader skills from the base skill datum, aka, what squad marines have.
Engineering skill affects whether you fumble with loading the OB or not, and whether you fumble changing out generators, which is a significant part of the SO's job. I'd like it to be one level lower but OB fumble procs on anything lower than ENGI; which changing would implicate other balance adjustments regarding SL or combat engi skillsets. 
Powerloader is helpful for req and OB, and Captain, for example, has max powerloader skill, FC has trained skill; I thought trained skill was appropriate for an SO where they'd be helping out with req or loading OB, especially as FC has it at trained …
=> gives SOs powerloader and engineer skills (so, buff)

code/datums/skills.dm
title
apparently this was also done previously but moved them from MASTER to EXPERT
CSE currently has the same leadership skill as SLs and SOs,
All other department heads (CMO, TO, PO, RO) have leadership at the "TRAINED" level
This makes CSE have leadership at the "TRAINED" level.
consistency. i don't know why a CSE would need higher skills really than like a CMO; even if they're the ones piloting TAD or whatever, I'm not sure why they were better at leadership things than a TO
:cl:
balance:  CSEs now have leadership level 2, down from leadership 3
/:cl:
=> lowers CSE leadership by 1 level

code/modules/clothing/suits/armor.dm
Title sums it up, but the current vest is worse at bullet stopping than regular marine armor. Little silly.
I've also thrown in a little laser and energy soft armor.
It just makes sense that a vest that's supposed to be good at stopping bullets is actually good at it. 
:cl:
balance: Increase bulletproof vests armor bullet resistance. Slight energy/laser increase.
/:cl:
=> Buffs the bulletproof vest to be actually good at stopping bullets

code/__DEFINES/skills.dm, code/datums/skills.dm, code/game/objects/items/stacks/sandbags.dm, code/game/objects/items/stacks/sheets/sheet_types.dm, code/game/objects/machinery/computer/computer.dm, code/modules/power/fusion_engine.dm
title. cse now has 5 construction and 5 engineering skill, just as cmo has 5 med and 5 surgery
early synths no longer outclass them.
skill_engineering_master --> skill_engineering_expert
skill_engineering_inhuman --> skill_engineering_master
makes sense from a logic standpoint that someone highly trained in a field be the best in it, or at least equal to a generalist but infallible support robot
actual practice won't effect too much, but CSEs will get mildly faster cade construction and engineering step time; and fusion cell removal from reactors will be instant
mostly forward-looking so if anyone does anything with the skillsets in the future, they're sensical and easier to build off of
("i want to make having more engineering skill do X thing; CSE is the ruler by which i measure and …
=> gives CSE engineering + construction 5, renames skill levels

code/__DEFINES/jobs.dm, code/datums/jobs/job/retired.dm, code/datums/jobs/job/special_forces.dm, code/datums/skills.dm
Veteran ERT members now all have SKILL_FIREARMS_TRAINED and SKILL_RIFLES_TRAINED (+1 from DEFAULT)
Special ops ERT members now have SKILL_SMG_TRAINED (+1 from DEFAULT)
These 2 are some of the most underpowered ERTs. I also believe its also logical for them to have better skills .
:cl:
balance: Veteran ERT now starts with their firearms and rifles skills at trained instead of the default(+1)
balance: Special Ops ERT now starts with their smg skill set to trained instead of the default(+1)
/:cl:
=> buffs to veteran ERT and specops ERT skills

code/datums/gamemodes/campaign/missions/mech_wars.dm, code/datums/gamemodes/campaign/rewards/mechs.dm
Some tweaks to mech colours in campaign so the different mech types are more distinguishable.
TGMC
SOM
Also moved around a bit of code/added some missing autodoc
Mech parts have no rhyme or reason to their design, nothing about them is particularly clear about being light, medium or heavy in class. Adds more visual clarity so you know if a mech is going to die to 2 rockets or 6.
:cl:
qol: Campaign: Updated mech colours to distinguish the different weight classes better
/:cl:
=> Campaign mech colours

code/game/objects/items/bodybag.dm
Examining Bodybag now show DNR timer and Defib status (DNR or Almost departed), you still have need to wear a medhud for it to work.
I'm tired of guessing when an almost departed body (disconnected people) get their ghost back (reconnected), even if its rare. Plus a DNR timer to give people time to prep for CPR if needed.
:cl:
qol: Examining stasis bag while wearing med hud now show defib status (DNR, Almost departed) and DNR timer
/:cl:
=> Examining Stasis Bodybag now show DNR timer and Defib status (DNR or Almost departed)

code/__DEFINES/dcs/signals.dm, code/datums/components/beacon.dm, code/game/objects/machinery/squad_supply/supply_console.dm
When you activate a beacon, it will do a noise to notify any nearby RO that something changed regarding the beacon list. 
I would have put an inverse noise, but I didn't find any that was good enough
Makes it easier for req workers to know when that dang beacon is down, PFC jim!
:cl:
qol: Activating supply beacons notify the shipside console with a noise
/:cl:
=> Activating supply beacons makes the supply console do a noise

code/__DEFINES/dcs/signals.dm, code/__DEFINES/traits.dm, code/datums/gamemodes/campaign.dm, code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/missions/base_rescue.dm, code/datums/gamemodes/campaign/missions/raiding_base.dm, code/game/objects/machinery/computer/nt_access.dm
Deploying beacons in Raiding Base now pauses the mission timer. Also increased beacons to 4 instead of 3.
Running disk on NT base rescue also pauses the timer. Slightly decreases mission timer since you can now potentially extend it out quite a bit.
The time pressure on these mission was quite tough , especially considering the beacon has a fairly long timer on raid base.
:cl:
balance: Campaign: Deploying an OB beacon in the Raiding Base mission pauses the game timer
balance: Campaign: Running a code computer on NT Base Rescue pauses the game timer
/:cl:
=> Campaign mission timer pause

code/modules/reagents/reagents.dm, code/modules/reagents/reagents/medical.dm, code/modules/reagents/reagents/other.dm, code/modules/reagents/reagents/toxin.dm
Makes all chems scannable by a health scanner by default
As we've seen in:
https://github.com/tgstation/TerraGov-Marine-Corps/pull/15326
https://github.com/tgstation/TerraGov-Marine-Corps/pull/15465
People want to be able to see what chems are circulating through their system.
I don't see any reason why we would want to have invisible chems, so imo they should all be made scannable in a single PR, rather than slowly make every single chem scannable individually.
:cl:
qol: All chems (except neuraline) are scannable by a health scanner
/:cl:
=> Make all reagents scannable by default

code/modules/mob/living/carbon/xenomorph/life.dm
Reverts tgstation/TerraGov-Marine-Corps#15463
Shit was way too much aparently, while the main culprit (or cause) for the initial PR was king making high armor xenos unkillable, this PR was a massive nerf to xenos overall, not only the high armor ones.
=> Revert "Warding nerf"

code/_onclick/hud/radial.dm, code/modules/radial/radial_body_select.dm
Makes the radial menu for applying ointment/medical packs fit all limbs.
Added a override to show_radial_menu for setting the min_angle to a lower value.
Massive QoL for medics.
:cl:
qol: Radial menus for applying medicine will now fit all LIMBS on a ring instead of having 2 pages.
/:cl:
=> Makes the radial menu for all medicine fit all limbs.

code/modules/projectiles/ammo_datums.dm
Fixes projectiles reflect more than they should, which notably leads to death tiles in cases where it recursively bounces enough times to trigger recusion checks which stops the projectiles from processing/deleting.
Funny death tile bad.
:cl:
fix: fixed infinite projectile reflection
/:cl:
=> Fix infinite reflect

tgui/packages/tgui/interfaces/CampaignMenu/CampaignAssets.tsx, tgui/packages/tgui/interfaces/CampaignMenu/CampaignMissions.tsx, tgui/packages/tgui/interfaces/CampaignMenu/CampaignPurchase.tsx, tgui/packages/tgui/interfaces/CampaignMenu/index.tsx, tgui/packages/tgui/interfaces/IndividualStats/IndividualLoadouts.tsx, tgui/packages/tgui/interfaces/IndividualStats/IndividualPerks.tsx
Colour tweaks for improved visibility maybe.
Selected colour is now green instead of orange.
If a loadout item has an equip cost, its cost is now orange.
Being able to see at a glance what items have a cost is good.
:cl:
qol: Campaign: Loadout options with a cost are now coloured to indicate this
/:cl:
=> Campaign UI colour tweaks

code/modules/vehicles/armored/__armored.dm, code/modules/vehicles/armored/_multitile.dm
Lets you throw shells inside of the tank by attacking it whilst at its entrance.
Moves  entrance code to the armored/sealed subtype , from armored/sealed/multitile , since it could be applied to 1 tile vehicles too . and so that if they get a interior , they can also be easy shell loaded.
Also adds a codex entry for anything that the tank can easily load:
No longer 10 minutes of spam clicking and leaving a tank to load in shells
:cl:
code: Moved entrance code from the armored/sealed/multitile type to armored/sealed. Refactors the NT mini tank code to work with this.
balance: You can now throw shells to the interior of the MT Ares by attacking the tank with them at an entrance.
/:cl:
=> Simplifies MT - Ares (Multitank tile) reloading. Refactors some tank code.

_maps/map_files/Theseus/TGS_Theseus.dmm, code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
This PR adds extra clone bays to TGS Theseus. It also shuffles the position of some gear and extends the room a little to make space. It also adds an emergency gun cabinet in the corner.
I always liked the fact our ships had unique traits, be it from pods capacity, layout making holding, or deploying easier. However, I figure we can go further in the variations, like having some ships support certain styles of play better. A bit like our seasonals in the weapons vendors. 
That's where this PR comes in. Basically, we get some of those weakass early vatborns for people to play around with, at the cost of having to spend some dosh on biomass to run them all. I do not forsee it being a substantial meta change, but I think it would be noticeable fluff, which changes from the repetition. 
:cl: …
=> Add extra clone bays to Theseus medical

code/game/objects/items/storage/boxes.dm
In #15488 I increased the nades but not the storage space so while boxes spawn with 25 nades, they can't actually hold them, i.e you can remove them but you can't put them back.
Fix good.
:cl:
fix: fixes grenade box storage amount for some of the boxes.
/:cl:
=> Fixes Nade box storage.

code/controllers/subsystem/silo.dm
Hotfix: Stops the larva gen calc including minions.
So minions are counted as xenos for the glob list purposes. This issue actually effects other stuff (like autobalance) not just larva gen, so a proper fix is needed, but pr'ing this now so benos don't get owned by having loads of minions.
Minion spam nerfing the hive is funny but notgud
:cl:
fix: Larva gen no longer counts minions when calculating xeno pop
/:cl:
=> Silo calc fix

code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
Brings king's pheros to the same level as prae pheros, because 6 phero strength is actually insane, and MAYBE xenos dont dying might be a bad thing but idk.
THIS SHOULD ONLY BE MERGED IF THE REVERT FOR https://github.com/tgstation/TerraGov-Marine-Corps/pull/15463 GOES IN
Alternative to making all warding pheros useless.
:cl:
balance: Lowers king pheros strength to 4.5
:cl:
=> Lowers king's phero power from 6 to 4.5

code/modules/projectiles/magazines/sentries.dm, code/modules/projectiles/magazines/specialist.dm
As the title says, this PR fixes the missing icons for the generic rocket launcher rocket and the M30 box magazine.
(just pretend those are the good ol normal sentry icons)
:cl:
fix: The M30 box magazine and the generic rocket launcher rocket have now a proper path
fix: Altought impossible to spot in normal game conditions, the 67mm internal tube rocket is now rightfully 68mm
/:cl:
=> Fixes the missing icon for the generic rocket launcher rocket and M30 box magazine

code/modules/factory/unboxer.dm, code/modules/reqs/supplypacks.dm
- AT ammo price for the 3-shell kits moves from 20 points to 40 points; or 13.3 points per shells
- AT ammo reqtorio kits moves from 100 points to 200 points; or 7 points per shell
- AT HE shell pack (x3) included 2 HE shells and 1 standard shell; this fixes that and makes them all HE
AT is devastatingly good but refills for it are pretty trivial right now. the work of a single well-placed AT shell is definitely worth way more than 3.3 req points. this keeps the supply pipeline for AT a little more in-parallel to the game impact the weapon has, while still providing decent room for one to do TATconomics and turn a profit off of kills to fund more shells to get more kills, etc.
:cl:
balance: AT-36 reqtorio supply packs now have 200 points 
fix: fixed the AT HE shell pack in req including 2 …
=> AT-36 ammo price increase and amount decrease

code/modules/projectiles/ammo_datums.dm
Title.
Flak ammo is pretty bad even with its funny AOE gimmick and regular ammo is always the way to go. This should help flak rounds fill a more supportive role without actually being definitively worse than the standard ammo.
It still takes more shots to kill a crusher with this buff than standard ammo but it does hurt tankier castes a bit more now.
:cl:
balance: Increases the sunder of AMR flak rounds.
/:cl:
=> Increases AMR flak ammo sunder.

code/modules/projectiles/gun_system.dm
Removes skill modifiers for fire delay based on user skill.
Makes skill level effect reload delay for mags that actually have it.
Also cleaned up some autodoc
These modifiers almost never came or could come into practice due to them only being checked when starting fire (i.e. auto/burst fire ignores it anyway) so were effectively pointless other than punishing like the CMO for semi auto firing a gun or something.
Adjusting reload delay is more useful in that it actually will do something, but this should make no particular change for HvX.
In HvH it means skill perks can help with slow loading guns like MG60/RPG/ALF etc.
:cl:
balance: Gun skills no longer effect fire delay for semi auto firing
balance: Gun skills effect reload delay for magazines that have one
/:cl:
=> Gun skill tweak

code/modules/shuttle/navigation_computer.dm
Tad can no longer land in areas with metal roofs. (It can smash through glass roofs just fine though).
The tad is strangely inconsistant with drop pods, and being able to land inside funny buildings just makes tad turtling easier and is generally worse for gameplay.
:cl:
balance: Tadpole can no longer land in metal roofed areas
/:cl:
=> Tad can't land indoors

code/__DEFINES/dcs/signals.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Mirage no longer lets you teleport across z-levels.
Teleporting to an illusion now breaks stealth.
Also added some missing autodoc/moved a proc to be neater
First is unintended, second is cheese that can't really be countered.
:cl:
balance: Swapping with an illusion via mirage now breaks stealth
fix: Mirage no longer lets you teleport across z-levels
/:cl:
=> Mirage changes

code/__DEFINES/dcs/signals.dm, code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Fixed the exploit that let bemo summon infinite rocks with next to no cooldown.
The cooldown from throwing the rock is now applied no matter what, including if other xenos throw it for you.
Funny infinite stun rock bad.
:cl:
fix: fixed throwing rock pillars now applying the cooldown in many cases
/:cl:
=> Bemo exploit fix

code/datums/jobs/job/shipside.dm, code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
Captain now spawns with the Captain's Beret and Captain's cloak.
Adds the red Captain's cloak variant to the Captain's locker.
Always felt odd Captain didn't start with these and adds the unused red variant of the cloak to the locker for more flavour.
:cl:
add: Captain now spawns with Captain's cloak and Captain's Beret.
add: Adds Captain's cloak red to Captain's locker.
del: Removes Captain's cloak from locker (Captain spawns with it now).
/:cl:
=> Updates Captain loadout. Adds red Captain cloak variant to Captain's locker.

code/modules/client/preferences_toggles.dm, code/modules/mob/living/carbon/human/examine.dm, strings/tips/xeno.txt
Fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/15586
Capitalized the spelling of hivelord in 2 round start tips I saw
Removed an extra dot at the end of a sound preference
Made a line of code go back to the line, as it clashes with the way we write our code.
Fixes good, and code improvements good. 
It should also be clearer what the holocards do.  They honestly could use a little icon, though. 
:cl:
qol: Made it clearer that the scans on medHud humans inspections refers to body scans, not handheld scanners.
spellcheck: fixed missing capitalization regarding 2 tips
spellcheck: removed superfluous dot at the end of Gas Mask preference
code: Go back to the line for some code.
/:cl:
=> Clarify body scans in the medHud + Minor fixes

code/game/objects/items/storage/storage.dm
Clicking on a storage with an item that cannot be inserted in said storage will open it
QOL, reduce jungling a bit when trying to reload.
For example, if you thought about opening your ammunition belt before the fight, you can do a tactical reload.
If you forgot to have the storage screen opened, you need to fumble a bit which is clonky. 
:cl:
qol: Clicking on a storage with an item that cannot be inserted in said storage will open it
/:cl:
=> Storage opening QOL

code/__DEFINES/factions.dm, code/game/objects/structures/orbital_cannon.dm, code/modules/screen_alert/command_alert.dm
- Orbital bombardment now plays screentext for every human, and changed the content of the message because "get out of danger close" is dumb
- If possible, I want to make this play over other sources of screentext (Send Orders especially, as it is used almost always before or during an OB) at some point, as a simple narration for the type of an incoming OB is *definitely* more important than whatever the PVT who just unlocked FC has to say. Maybe for a future PR.
- "Send Orders" will now clarify the faction of the sender (EDIT: regardless of TGMC affiliation)
- `faction_to_acronym` global list for getting faction acronyms to make this possible.
- Orbital bombardment playing screentext is a good idea to try and get attention of marines who can't afford to look in chat in the middle of …
=> some announcement qol

code/modules/projectiles/ammo_datums.dm
Increases the projectile scatter, lowers accurate range, adds damage falloff.
Lascarbine spread generally has very few of the drawbacks that typically come with shotguns, most notably being just as effective at range. With this change, spread will no longer be able to hit all three projectiles outside of a ~3 tile range and will have very weak damage at max range, killing a runner at range at about the same speed as the combat shotgun would with buckshot. For people who want to full sprint and rush at xenos this change will not affect them much, but people who want to sit back and snipe with a shotgun should switch to a different firemode.
:cl:
balance: Reduced lascarbine spread mode's effectiveness at range.
/:cl:
=> Makes lascarbine spread stats more in line with combat shotgun buckshot's

code/modules/projectiles/guns/specialist.dm
ided pr
Increases RG 220 wield delay from 1.2 to 2.0 seconds.
Currently, RG 220 is a very powerful operational weapon which easily farms kills and snowballs the game for marines. 
Because it's wield time is significantly shorter than other weapons of it's size/strength, it's incredibly safe to run as a primary weapon - you can wield it quickly out of stuns and force xenos off of you with a single shot.
This change forces RG220 users to carry a backup weapon or consider their positioning more carefully, similar to other weapons of it's caliber.
:cl:
balance: Increased RG220 wield delay from 1.2 to 2.0 seconds
/:cl:
=> Increases RG 220 wield delay

code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Wraith currently flops as it's support abilities are super niche even compared to other castes.
This pr is Kuro approved
Wraith's pretty much unused by xeno players after those two nerfs, sadly
:cl:
balance: Ups wraith damage from 20 to 24
/:cl:
=> Buffs wraith's melee damage, from 20 to 23

code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Fixes #15630
Being able to throw more than 3 rocks per game is good.
:cl:
fix: fixed bemo rock count being updated incorrectly
/:cl:
=> Bemo typo fix

code/datums/gamemodes/campaign/individual_stats.dm, code/datums/gamemodes/campaign/loadout_items/SOM/head.dm, code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/head.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm, code/datums/gamemodes/campaign/perks.dm
Wht it says on the tin. the first health perk unlocks heavy tyr/lorica for all jobs.
May be very strong, but overclocked shields are also rather good without slowdown, and there's more AP ammo available now so should be fine.
More perk bonuses/variety
:cl:
balance: Campaign: Improved constitution perk unlocks Tyr/Lorica for all jobs
/:cl:
=> Campaign: Improved constitution perk unlocks Tyr/Lorica for all jobs

_maps/map_files/Arachne/TGS_Arachne.dmm, code/game/area/mainship.dm, code/game/objects/machinery/door_control.dm, code/game/objects/machinery/doors/poddoor.dm
Changes to Arachne's Medbay, Dropship Storage, Marine Prep, Vehicle Bay, and others.
Adjusts Medbay layout to improve ease of use:
Expands Vehicle Bay to improve ease of use:
Swaps fabricator location in Dropship storage for easier CAS resupply:
General quality of life changes to improve usability.
:cl:
qol: Adjustments to Arachne Medbay, CAS Bay, Vehicle Bay, and Marine Prep layouts.
/:cl:
=> Arachne QOL Changes

code/game/objects/machinery/miner.dm
Ghosts can now see if there's minerals to sell, or what upgrades are on the drills. 
No reason why they can't see that.
:cl:
add: Add ghosts can now examine miners 
/:cl:
=> Allow ghosts to examine miners

code/modules/projectiles/ammunition.dm, code/modules/projectiles/magazines/misc.dm
Adds a 1.5 second delay when loading a magazine from an ammo packet
Reworks transfer_ammo to use the fill delay of the source magazine rather than the target (this is currently unused)
Ammo packets generally offer 2-4x space efficiency over magazines when stored in general pouches, armor storage or satchels. Once you have the muscle memory for reloading a primary magazine from ammo packets, there's very little downside to running them - even in the heat of battle. 
This change balances ammo packets by slowing down their reloads and enforcing a bit of realism (loading magazines takes time in the real world). Should encourage healthier and more realistic usage.
:cl:
balance: loading magazines from ammo packets now has a 1.5 second delay
/:cl:
=> Adds a delay when loading magazines from ammo packets

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/debugdalus/tgs_debugdalus.dmm, _maps/shuttles/alamo.dmm, code/game/objects/machinery/door_control.dm, code/game/objects/machinery/doors/shutters.dm
I should have made a progressive list, but I really fixed things as I saw them while overflying things, so this is made at commit time. 
- Verified again that every door has their firelocks
- Verified that all light fixtures, cameras, fire alarms and so on aren't on glass
- Verified that wall mounted things aren't stuffed on glass.
- deleted a number of duplicate lights
- Moved things like lights from being placed under firelocks, which makes no sense
- Added FC privacy shutters
- Added floorlights to the debugabus & POS hangar
- Move the button for medical surgery shutters to not be under cameras
- Moved the leader pods not all being in the centerline of the pod bay
- Added lights to the bathroom and all SO rooms.
- Fixed lots of the new POS hangar not having camera cover
I ran out of …
=> Several small cosmetic changes to debugabus + pos

code/_onclick/hud/interactive_emotes.dm
Finally found out why it was failing in live thanks to Barnet testing it. `can_interact` eventually calls `can_interact_with` and then `Adjacent` but from the point of view of the acceptance button, which always fails as it has no `loc`.
Fixes good.
:cl:
fix: Interactive emotes work.
/:cl:
=> Fix the accept button for interactive emotes

code/game/objects/items/binoculars.dm, code/game/objects/structures/reagent_dispensers.dm
Adds logging for using tactical binoculars to lase mortars, CAS, OB and railgun
Improved fuel tank logging (it works now)
Admin logging is useful for catching FF incidents.
:cl:
admin: Adds tactical binocular admin logging, improved fuel tank logging.
/:cl:
=> Tactical binocular and fuel tank admin logging

code/__DEFINES/loadout.dm
Puts back ar-55 in the leader vendors
ar-55 has been removed from leaders vendors in reaction to razorwire and he gl54 spam. Now that these two ammunitions are gone I think it'd be a good thing to introduce this support weapon to squad leaders and FCs.
"AR-55 is a rifle with AR12 stats with worse recoil and 14 less bullets. It loses aim mode if you remove its scope. With a barrel charger it has 0.3 bullet falloff which is not good for a long range weapon.
Its only pro is that it has a gl54 strapped to it allowing you to shoot airburst shrapnel, fire or tangle.
These gl54 ammo are limited in vendors and can be bought for a fairly expensive price for the rate at which they are expended."
:cl:
balance: Adds the ar-55 back in leaders vendors.
/:cl:
=> Adds back ar-55 to leader vendors

code/game/objects/machinery/vending/new_marine_vendors.dm
fixes #15665
tbh still not sure if bug or feature though
if RR was supposed to be removed from pouches for marines, i guess it should be removed from pouches for all marines
:cl:
fix: the FC GHMME now vends the right injector pouch
/:cl:
=> makes fc ghmme autoinjector pouch standard; fixes 15665

code/datums/storage/subtypes/belt.dm
title.
nice to have med stuff in one spot when doing groundside surgegryegreyryg; soap is also kind of mandatory, spaceacilin no longer cuts it.
:cl:
balance: medical rig belts now can hold soap
/:cl:
=> adds soap to allowed items in medical rig belt

code/datums/gamemodes/_game_mode.dm, code/datums/round_statistics.dm, code/game/objects/items/implants/sandevistan.dm
Title.
Players would be glad to know how many times someone was gibbed by it.
:cl:
qol: Game will now tally up how many times people used Sandevistans (as well as how many died to it).
/:cl:
=> Makes sandevistans a round statistic to show at round end

code/modules/projectiles/gun_helpers.dm
Clicking a magazine with a gun will tactical reload instead of click-dragging the sprite.
Easier input
:cl:
qol: Clicking a magazine with a gun will tactical reload instead of dragging the magazine
/:cl:
=> [Code bounty] Clicking a magazine to tac reload instead of drag

code/datums/components/harvester.dm
Selecting a new reagent in your harvester weapon will switch your old chem with the new chem.
Some QOL, allows you to be more adaptable with your chems, since you no longer need to smack a corpse in order to purge the old reagent.
:cl:
qol: Selecting a new vali chem will purge the old loaded reagent and load up the new chem
/:cl:
=> select_reagent() loads new reagent

code/__DEFINES/loadout.dm
Adds ar-55 to FC vendor
Someone may or may not have forgotten to add it to the FC vendor in #15662
:cl:
add: AR-55 can now be issued to Field Commanders through their assigned vendor.
/:cl:
=> Add ar-55 to FC vendor

code/modules/vehicles/armored/__armored.dm
Can you guess how much damage this APC has?
If you guessed 58.1%, you'd be right! Thats a whopping 1,162 health left until this baby is destroyed!
The current thresholds are at 90%, 70%, 59%, and 29%. This means the high damage sprite above appears before the APC is even below half health. This PR changes these numbers to 90%, 70%, 40%, and 20%. This most notably extends the medium damage sprite to cover 30% of the durability instead of 11%. 
Both teams should be able to know how damaged the vehicles are instead of having to guess whether the high damage sprite means the vehicle is fucked and needs to leave asap or if it still has more than half durability.
:cl:
qol: Tank and APC sprites will now more accurately reflect their current integrity values.
/:cl:
=> Shifts tank/apc damage sprite thresholds

code/modules/vehicles/armored/apc.dm
Set APC to intended integrity of 600.
Set APC soft armour to intended levels (40 for melee, acid and fire instead of 50)
Tank has 900 for reference, APC was set to 2000.
:cl:
balance: Significantly reduced unintented APC defensive stats
/:cl:
=> APC defensive fix

code/modules/vehicles/armored/apc.dm
Forgot to set the ram damage so it was inheriting from the way slower tank
:cl:
balance: Fixes APC having insane ram damage (it now has 25% of previous value)
/:cl:
=> Fixes APC having insane ram damage

code/datums/storage/subtypes/internal.dm
title.
currently holds 10 slots; this makes it 12.
autoinjector storage mod is also kind of backwards compared to med storage mod where the medkit pouch holds more and the medical storage holds less.
an injector storage module holds 10, up to 12 autoinjectors; an injector storage pouch holds 7 autoinjectors.
autoinjector storage is woefully inferior to medical storage, and probably always will be because of reagent amounts per item stored. so this doesnt fix that and doesnt really claim to.
mostly it's a very difficult module to work around, though, which i think for the drawbacks of less reagents per stored item, it should be minimally more flexible for playstyles.
10 slots = 2 sets of BTTK + 2 injectors of your choice (think dylo and hypervene)
12 slots = 3 sets of BTTK, or 2 sets of …
=> buffs autoinjector storage mod by adding 2 more slots

code/modules/xenomorph/xenotowers.dm
Changes the maturity gain amount from 0.8 to 0.4 per tower
In #14912 I did a massive overbuff which this PR rectifies. If you want to get the same old 4 maturity towers, you will have to spend all of your tower points (600 after silo) on it. Xenos are way stronger than during the maturity era, especially with early primo and I miscalculated.
:cl:
balance: Evolution towers give 0.4 maturity per tick instead of 0.8
/:cl:
=> Evolution tower nerf

code/__DEFINES/xeno.dm
#10523 changed the order of defiler chems to Ozy-Hemo-Trans-Neuro, this changes it back to the original Neuro-Hemo-Trans-Ozy
The original cycle made the standard combo of neuro smoke into hemo/trans/ozy slashes much easier. Defilers will suffer no more!
:cl:
qol: Defiler chems once again cycle Neuro-Hemo-Trans-Ozy.
/:cl:
=> Restores original order for defiler chems

code/datums/interior/interior_tank.dm, code/modules/vehicles/armored/__armored.dm, code/modules/vehicles/armored/_multitile.dm, code/modules/vehicles/armored/apc.dm, code/modules/vehicles/armored/medium_tank.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale.dm, code/modules/vehicles/mecha/mecha_mob_interaction.dm, code/modules/vehicles/sealed.dm
You can now exit or enter OTHER mobs into multitile vehicles.
Drag a mob (or click while grabbed) to shove a mob in or out of a tank/apc.
It still does the normal checks so you can't exploit it to shove xenos in or something (however it will work if EITHER you or the entering mob are at the door). Mainly useful for moving bodies in and out, or managing ungabrains I guess.
This doesn't address body/cryobags, but that can be another pr.
QOL.
:cl:
qol: You can click drag or grab click mobs into, or out of multitile vehicles
/:cl:
=> Vehicle entry QOL

code/datums/jobs/job/fallen.dm, code/datums/jobs/job/shipside.dm
Removes the radio that the mech pilot in valhalla spawns with
Fixes #15719
:cl:
fix: Removed the Valhalla mech pilot's radio
/:cl:
=> Removes Valhalla Mech Pilot Radio

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Removes an Rwall on the north LZ and a frost wall on the south LZ to allow vehicles to exit the alamo easier.
Fewer tanks stuck on the alamo
:cl:
fix: Tank and APC can now get out of the Alamo easier on Ice Colony
/:cl:
=> Clears space for tank/apc on Ice Colony LZs

code/datums/storage/storage.dm
Trying to store something (either directly or via quick equip) into an open storage that it can't fit in will no longer close said storage.
This was extremely annoying, where you'd quick equip store something, but because it always tries your open storage first, it would close it. So basically any time you stored your gun, your storage would close.
:cl:
fix: quick equip storing will no longer close your active storage
/:cl:
=> Storage closing fix

code/__HELPERS/announce.dm, code/datums/marine_main_ship.dm, code/modules/projectiles/ammunition.dm, code/modules/screen_alert/command_alert.dm, code/modules/shuttle/marine_dropship.dm
#15714 has quite a few missed features that its changelog says were added or whatever. Hopefully all this is working, but I was in a rush coding this
- Send Orders full faction alerts behave as intended, not sending screentext twice or an empty `assemble_alert`, and faction title works normally
- Delta alert now plays the air raid siren
- *Manual* dropship takeoff alarm is fully implemented now
- *Automatic* dropship takeoff alarm won't play sound as said in 15714's description(?)
Adding stuff that seems to have been left out accidentally is good. Also, same reason for the sounds as in #15714 and #15064: these are dramatic and attention-getting.
:cl:
fix: Dropship Takeoff Alarm is fully implemented
fix: Automatic dropship departure announcement no longer has sound
fix: Delta alert plays …
=> Fix some oversights from #15714

_maps/interiors/apc_medical.dmm, _maps/interiors/apc_transport.dmm, code/modules/vehicles/armored/interiors/periscope.dm
Gives the APCs periscopes, specifically 2 for the transport module, and 1 for the medical module.
Currently, being a support passenger for the apc means staring at an unchanging boxed room. This let's passengers such as doctors or synths that are going to be staying in the apc a lot look at something actually interesting.
:cl:
add: Added periscopes to the interior of APCs
/:cl:
=> Gives APCs Periscopes

_maps/modularmaps/big_red/bigredsouthetavar1.dmm, _maps/modularmaps/big_red/bigredsouthetavar4.dmm
This area was cave and so it was always powered, now its part of the lab like it should be.
APCless doors are bad for xeno health.
:cl:
fix: Fixed a big red modular south of ETA lab with a wrong area.
/:cl:
=> Fixes area on a big red modular

code/modules/mob/living/carbon/carbon_defense.dm, code/modules/mob/living/living_defense.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/15749
Thanks to Mr.Cuddles, Ytt, Ashe and Aug for spotting this bug.
Toxins clouds no longer get ignored by masks.
Added missing return variables in the parent proc, and addresed them in the child proc smoke_contact
:cl:
fix: fixes gas masks giving full immunity to chemical gasses. 
/:cl:
=> Fix gas mask protection bug

code/modules/projectiles/ammo_types/rocket_ammo.dm
https://github.com/tgstation/TerraGov-Marine-Corps/assets/20828943/eaebff5f-9bde-4fac-901e-d4cdff95be62
https://github.com/tgstation/TerraGov-Marine-Corps/assets/20828943/d1924b67-ee36-4b70-8937-eea43ffc6d38
(It was very funny and adds a risk for standing directly infront of tank.)
:cl:
balance: Tank cannon now gibs non-xeno mobs again
/:cl:
=> Tank cannon now gibs non-xeno mobs again

code/game/objects/machinery/door_control.dm
Changes the door control button to layer above objects
Currently, the buttons are hidden on things like the tad due to layering under the walls and objects on them. This let's them actually see and use the buttons more easily.
:cl:
qol: Door control buttons now layer over objects and the tad's walls.
/:cl:
=> Changes Door Control Button's Layer

code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
Only applies to praetorian since they are the only one with neuro spit
When a praetorian spits neuro at you while staggered, it will reduce the amount transferred by the stagger damage multiplier (50%)
I learned after I made xenos able to spit when staggered that their damage would be reduced by 50%, which honestly seems fine to me. Replicating the behavior to Praetorian spit which does stamina damage AND transfers toxins; this does not touch the gas cloud however, just the on-hit effect
:cl:
balance: Xeno spit toxin transfer amount reduced by half when staggered
/:cl:
=> Xeno spit toxin transfer amount reduced by half when staggered

code/modules/xenomorph/acidwell.dm, code/modules/xenomorph/xeno_turret.dm, code/modules/xenomorph/xenoplant.dm
Acid wells make opaque smoke when someone walks through them, acid turrets make opaque smoke when they get destroyed and heal fruit blows up into opaque smoke when a non xeno tries to eat it.
I'm pretty sure barnet didn't intend to change these in the PR where they made boiler and baneling smoke opaque.
This makes acid wells quite single use, only really useful as a utility to extinguish yourself and knock sticky nades off, which is sad. The main appeal of them WAS the line of sight block, considering it does next to no damage to heavier armors. 
The other two are just for consistency's sake.
:cl:
balance: Acid wells, acid turrets and heal fruit have opaque acid smoke again
/:cl:
=> Acid wells, acid turrets and heal fruit have opaque acid smoke again

_maps/map_files/DaedalusPrison/DaedalusPrison.dmm, _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
Adds the dropship consoles to both landing zones in Lawanka and the landing zone in Daedalus
Fix good.
:cl:
fix: Fixes missing alamo consoles on Lawanka and Daedalus
/:cl:
=> Fixes missing alamo consoles on Lawanka and Daedalus

_maps/gelida_iv.json
1600 is quite low for a full sized map and it seems xenos always run out of QB before even mazing all of the disks. This increases QB to 1900, still less than some other maps.
Marines can move very fast when unobstructed, and this map isnt as linear as most so marines can usually find a path without any maze.
:cl:
balance: Increased QB points on Gelida to 1900.
/:cl:
=> Increases QB for Gelida

code/modules/mob/living/living_defense.dm
The mob hitting mob sound was changed to a metal clang for unknown reasons.
Nonmetal walls are still cursed but thats barnet's problem.
:cl:
fix: fixed the mob on mob impact sound
/:cl:
=> Fix mob hit sound

code/datums/jobs/access.dm, code/datums/jobs/job/shipside.dm
New shipside ranks
Starting > 10hrs > 25 hours > 100 hours > 300 hours (5 ranks in total)
Captain
Captain > Commodore > Rear Admiral > Vice Admiral > Admiral
Staff Officer
Ensign > Lieutenant Junior Grade > Lieutenant > Lieutenant Commander > Commander
Chief Engineer
Ensign > Lieutenant Junior Grade > Lieutenant > Lieutenant Commander > Commander
Chief Medical Officer
Senior Physician > Head Physician > Medical Supervisor > Medical Director > Chief Medical Officer
Requistions Officer
Ensign > Lieutenant Junior Grade > Lieutenant > Lieutenant Commander > Commander
Synthetic
Mark I > Mark II > Mark III > Mark IV > Mark V
Pilot Officer
Ensign > Lieutenant Junior Grade > Lieutenant > Lieutenant Commander > Commander
Medical Doctor
Medical Student > Junior Resident > Senior Resident > General …
=> Shipside rank overhaul

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm, code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/projectiles/ammo_types/xenos/energy_xenoammo.dm
Reduces the AOE damage of Psyblast/crush against multitile vehicles.
Also removed some caste define stuff for warlock abilities. With the removal of maturity, they serve no purpose. This probably applies to the majority of ability caste vars, but we'll leave that for another pr.
Multitile vehicles are particularly vulnerable to any kind of AOE damage since it can hit up to 9 times. While I like the idea of being able to get better hits in, currently this means warlock in particular can do HUGE damage to vehicles.
:cl:
balance: Reduced AOE damage of psyblast/psycrush against multitile vehicles
/:cl:
=> Psycrush and psyblast multitile walance changes

code/game/objects/machinery/computer/communications.dm, code/modules/screen_alert/command_alert.dm
Only place full ranks are shown are currently in Manifest, neat to have them here too
:cl:
add: Full ranks show up in command annoucements
add: Instead of faction title, the job of the person sending the command shows up
/:cl:
=> Full ranks show up in command annoucements

code/datums/gamemodes/nuclear_war.dm, code/datums/jobs/job/shipside.dm
Removes minimum pop from Transport Crewmen
Meant to be merged with #15693, to make the apc more central to the operation once tad is nerfed.
:cl:
balance: Transport Crewmen no longer requires a minimum pop.
/:cl:
=> Removes minimum pop from Transport Crewmen

code/game/objects/items/explosives/grenades/grenade.dm
Grenades do not walk. Stop that.
Removes some random old CM code that doesn't do anything.
I would remove walk stuff entirely but simple mobs still use it. Someone totally should unfuck it though, TG made a movement SS.
:cl:
code: Removed some dead code
/:cl:
=> Removes walking grenades

code/datums/storage/storage.dm
Checks the right thing for the on click storage open thing.
Feature working more than once per item is good.
:cl:
fix: fixed opening storage by clicking with another item, properly
/:cl:
=> Proper storage fix

code/__DEFINES/objects.dm, code/datums/gamemodes/_game_mode.dm, code/datums/gamemodes/campaign.dm, code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/missions/airbase_raid.dm, code/datums/gamemodes/campaign/missions/base_rescue.dm, code/datums/gamemodes/campaign/missions/fire_support_raid.dm, code/datums/gamemodes/campaign/missions/mech_wars.dm, code/datums/gamemodes/campaign/missions/patrol_mission.dm, code/datums/gamemodes/campaign/missions/supply_raid.dm, code/game/objects/items.dm, code/modules/clothing/head/helmet.dm, code/modules/clothing/modular_armor/combat_robot.dm, code/modules/clothing/modular_armor/jaeger.dm, code/modules/clothing/modular_armor/mark_one.dm, code/modules/clothing/modular_armor/modular.dm, code/modules/clothing/modular_armor/xenonauten.dm
Updated map colour variant selection so the gamemode can specify the variant to use.
Specifically, this means during campaign, the map variant will change with each mission.
Also changed the default colour (for groundmaps and missions that don't specify anything) to black, instead of drab or desert in some cases.
Muh realism or something.
:cl:
qol: Campaign: Map variant for colours updates with each mission
/:cl:
=> Campaign map colours

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm, code/game/area/magmoor_digsite.dm
- Added a new garage above admin
- Revamped security to have more cover for xenos
- Removed a few windows from pharmacy
- Fixed a few missing pipes
<details>
</details>
Admin disk tends to be very marine sided as long as they have enough maze clear because there isnt a ton of cover for xenos to heal under. Pharmacy also tends to be a dead zone due to it having many sightlines through it while being blocked by machinery. This should make the two 2nd disks a bit easier to siege for xenos.
:cl:
add: Added more cover for xenos on the 2nd disks of Magmoor.
fix: Fixed a few missing pipes on Magmoor.
/:cl:
=> Magmoor tweaks

code/modules/shuttle/navigation_computer.dm
Allows tad to land on lavaland tiles, this does not include lava itself.
Maps like metnal and barrenquilla use this tileset and so tad cant even land on 99% of the map. Futureproofing for when this tileset becomes more common than just a few spots on Slumbridge
:cl:
fix: Tad can now land on lavaland tilesets.
/:cl:
=> Tad can land on lavaland tiles

code/game/objects/items/storage/pouch.dm, code/game/objects/items/storage/secure.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/closets/fitness.dm, code/game/objects/structures/crates_lockers/closets/job_closets.dm, code/game/objects/structures/crates_lockers/closets/l3closet.dm, code/game/objects/structures/crates_lockers/closets/secure/bar.dm, code/game/objects/structures/crates_lockers/closets/secure/engineering.dm, code/game/objects/structures/crates_lockers/crates.dm
Implement more uses of PopulateContents()
Storage + lockers both call PopulateContents() right after initialize. Please use this proc to fill these items instead of tying it directly on to Initialize().
This makes it easier for us to make subtypes call parent on initialize since this proc is easier to override.
:cl:
code: Implement more uses of PopulateContents()
/:cl:
=> Implement more uses of PopulateContents()

code/game/objects/items/stacks/stack.dm
Adds QoL feature of merging stacks of newly crafted items to existing stacks that user holds in their hands.
Makes life of an engineer a bit easier.
:cl:
add: Stacks of newly crafted items merge to existing stacks in user hands
/:cl:
=> Stacks of newly crafted items merge to existing stacks in user hands

code/_globalvars/lists/flavor_misc.dm
Bug bad.
:cl:
fix: Fixed transport crewman and assault crewman orbit menu icons.
/:cl:
=> Fixes transport crewman and assault crewman orbit menu icons

code/datums/gamemodes/campaign/loadout_items/SOM/head.dm, code/datums/gamemodes/campaign/loadout_items/SOM/pockets.dm, code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm, code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/medic.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/head.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm, code/datums/gamemodes/campaign/perks.dm, code/modules/clothing/modular_armor/som.dm, code/modules/clothing/modular_armor/xenonauten.dm
Fixed some incorrect access to EMP pouches (for marines) and shotgun shell pouches  (for SOM)
Fixed tyr/lorica armour for medics/engies having the wrong storage stuff
Fixed SOM medics not getting the upgrade V21 loadout with the SMG perk
:cl:
fix: Campaign: Fixed loadout issues
/:cl:
=> Campaign loadout fixes

code/game/objects/machinery/cryopod.dm
Roomba no longer permanently curses storages that get vacuumed
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14884
bugfix
:cl:
fix: Roomba no longer curses your storage if it sends it to cryo
/:cl:
=> Roomba no longer permanently curses storages that get vacuumed

_maps/map_files/slumbridge/slumbridge.dmm
Someone made the SOM mantay ray in the hangar dense **without telling me** and thus made the area unplayable for both sides. This replaces the unslashable, unmeltable, unshootable (allegedly) som manta ray with a pair of tank props that have 500 integrity
I am also bundling a quick fix in to remove the lava turf off these windows, not sure how they got here
map fixes good yes
:cl:
fix: Slumbridge's SOM hangar is open again
fix: Slumbridge lava prison no longer has a hole in the western reception
/:cl:
=> Removes Slumbridge's CAS prop, replaces with tank AND fixes lava prison tiles 

code/controllers/subsystem/explosions.dm, code/controllers/subsystem/tts.dm, code/modules/flufftext/Hallucination.dm, code/modules/instruments/songs/play_legacy.dm, code/modules/instruments/songs/play_synthesized.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Fix some sounds I broke
They were passing the sound as ``sound_to_use`` instead of ``soundin``
BTW we still have 2 broken sounds, idk what they are supposed to be.
cas/heavygun/proc/strage_turfs is calling ``get_sfx("explosion")``
ammo/xeno/web/on_hit_mob is calling ``get_sfx("snap")``
Neither of these SFX have ever existed and idk if they had sound files somewhere, but idk where to find out so Im just leaving it.
fix
:cl:
fix: fix some broken playsound_local (notably nades and TTS)
/:cl:
=> fixes proper args in playsound_local()

code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Reduces Behemoth's ability damage against vehicles to a 1.8 multiplier, down from a 10 multiplier.
Behemoth is doing an absurd amount of damage against tanks and apcs right now, doing over 800 damage if he charges his rocks into a vehicle, or around 350 if he stomps in the middle of a vehicle. This pr changes it so each charged rock hit will do about 50 damage, totaling 150 damage, and stomp doing 63 damage. Primal wrath's earth pillars do the equivilant of 3 charged rocks.
:cl:
balance: Reduced the damage multiplier of behemoth's abilities against vehicles from 10 to 1.8
/:cl:
=> Reduces Behemoth's Ability Damage Against Vehicles

code/modules/reagents/reagent_containers/jerrycan.dm
Examining jerrycans correctly show how much fuel is inside of it.
Bugfix. There isn't 200 units of fuel in a jerrycan when it is empty.
:cl:
fix: Jerrycans correctly show how much fuel is inside of it when examined.
/:cl:
=> Jerrycans show correct amount of fuel when examined

code/__HELPERS/game.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm, code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Quick build overrode a check which allowed building of resin walls in the alamo, which had previously been disallowed.
This also created a bug where you could open holes into space, as changing turfs on a shuttle doesn't work properly.
Spacehole bad.
:cl:
fix: fixed a couple of issues around building resin walls on the alamo
/:cl:
=> Alamo build fix

code/datums/gamemodes/campaign/rewards/reserves.dm
SL's can activate the rapid reserve's asset in campaign.
Often when you need to turn this asset on, your faction leader could already be dead, and you might have no command staff.
:cl:
balance: Campaign: SL's can activate the Rapid Reserves asset
/:cl:
=> SL enabled rapid reserves

code/modules/mob/living/silicon/ai/ai.dm
Fixes #15600
Borders on balance, but I'm going to assume that the explosion refactor years ago didn't intend on making the AI undraggable. This does make the AI more flingable by explosions when unanchored, but dem's apples.
Unbolting as an AI actually has a point?
:cl:
balance: AI can now be dragged when unanchored, but is more vulnerable to getting flung around by explosions than before.
/:cl:
=> Allows AI to be dragged when unanchored

code/_onclick/ai.dm
AI couldn't get coords on weeded tiles, this fixes that
AI has one less excuse for giving mortar/howtizer coords
:cl:
fix: AI can now use Ctrl Click on weeded tiles to get coordinates
/:cl:
=> Allows AI to get coords from weeds

code/datums/atom_hud.dm, code/modules/client/client_procs.dm
Thanks to @Notamaniac in #15860 who narrowed down the issue on this long standing bug.
Fixed the click catcher not working in some circumstances (such as after using revive()).
The way the proc was setup meant the click catcher was being created but not applied. Changed it so it now should apply correctly no matter what.
:cl:
fix: fixed the blackscreen click catcher not working under some conditions
/:cl:
=> Click catcher fix

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Fixes xeno death timers (for queen and king) not being respected.
Little bit stinky because it still relies on the xeno mob's base caste type, instead of anything relates to its actual caste datum, but eh.
:cl:
fix: fixed xenos being able to ignore queen and king death timers
/:cl:
=> Xeno leader death timer fix

_maps/map_files/riptide/riptide.dmm, code/game/objects/effects/misc.dm
fix destroyable forcefield
So that people stop running into instadeath zones on riptide
:cl:
fix: fix a mistaken var edit that made forcefields breakable
/:cl:
=> fix destroyable forcefield

code/game/objects/machinery/overwatch.dm
#15598 broke the ability to select laser targets for OB's
This probably needs a more comprehensive fix, alas staring at html makes my head ache.
And no, this doesn't let you OB on a marine cam, the selected_target var is checked to see whether it's an orbital beacon (bring back orbital beacons pls) or laser target
I won't get yelled at by Alan or other FC's for not firing the OB as an AI
:cl:
fix: Overwatch can select laser targets to fire OB's again
/:cl:
=> Fixes overwatch being unable to select targets to OB

code/datums/gamemodes/campaign.dm
I did a dum with a var, so attrition wasn't being used on respawn. Honk.
:cl:
fix: Campaign: Fixed respawns not using attrition
/:cl:
=> Attrition fix 2

code/game/objects/machinery/buttons.dm
Fingerprints seem to not work on this, no more Guess Who for the admins on who opened shutters against FC's or Captain's orders.
:cl:
admin: Added logging to LZ Containment Shutters
/:cl:
=> Adds logging to LZ Containment Shutters

code/modules/mob/living/carbon/xenomorph/evolution.dm, code/modules/mob/new_player/new_player.dm
This feature doesn't really do anything but mildly annoy the xeno for 2 seconds upon spawning or evolving. I'm tired of being mildly annoyed.
in gh#14149 the fade in was advertised as both a way to remove xeno hitlag and as an immersion thing. The xeno hitlag was proved to be false, but it was merged because of the immersion thing. I don't think the immersion thing is worth it, hence the removal
All minor inconveniences must be destroyed. Immersion isn't real
:cl:
del: Xenos evolution fade-in effect removed
/:cl:
=> Removes evo fade in for xenos

code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Changes behemoth rolling description to desc = "Toggles Rolling on or off. This can be used to displace talls but won't deal any damage."
I've seen behemoths use it offensively without knowing it's doing nothing, this will let them know it's a traversal ability and not a damaging tool.
:cl:
qol: clarifies that behemoth roll deals 0 damage in the ability description
/:cl:
=> Clarifies that Behemoth rolling ram deals no damage

code/datums/components/seethrough_mob.dm
Changes the alpha value of See Through when active from 100 to 170.
See Through, as of right now, lowers your character's sprite more than it needs to. It can be hard to see where you are while also trying to look around you. This is worse if you are playing a caste with a dark color palette and you're on top of weeds, which makes you nearly invisible if you're not looking directly at the sprite.
This value increase mostly fixes this issue while still allowing you to see things under your sprite.
For reference, See Through off:
:cl:
qol: Changed See Through's sprite alpha from 100 to 170.
/:cl:
=> See Through sprite opacity QOL change

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
see title
Getting such heavy screenshake when you pop rage is very disrupting, and can lead to you getting killed if you try and use it to make advantage of the damage and speed boost. An earlier PR for this was closed so the screenshake could be "Reduced to fluff levels," but no such PR has been made and I don't think there's an amount of screenshake low enough to be considered "fluff"
:cl:
balance: Ravager's Rage no longer shakes the screen of the ravager who used the ability
/:cl:
=> Ravager Rage Screenshake no longer effects the ravager

code/game/objects/structures/barsign.dm, code/game/objects/structures/signs.dm
Turns out /obj/structure/sign/ changes the icon var on initialize, which barsigns inherit from.
Less error signs
:cl:
fix: Barsigns should no longer show up as errors
/:cl:
=> Fixes bar signs

code/__DEFINES/campaign.dm, code/datums/gamemodes/campaign.dm, code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
Limited loadouts now scaling in quantity, based on pop.
40 and under = current min quantity.
100 pop = x3 normal quantity.
Also made the engie RR loadout limit 3 instead of 2, since its weaker than the SOM version.
More limited loadouts at higher pop is more interesting.
:cl:
add: Campaign limited loadout quantities scale with pop
balance: Campaign: LE RR loadout limit increased to 3 from 2
/:cl:
=> Scaling loadouts for campaign

code/modules/mob/living/living_defense.dm
Lava and fire will now not deal damage when jumped over, previously not igniting but still dealing the damage.
Jumping over fire shouldnt still apply half of the effects.
:cl:
balance: Lava and fire no longer deal damage when jumped over.
/:cl:
=> Lava and fire jumping

code/modules/projectiles/projectile.dm
Vehicles are not intended to be able to hit mobs on top of them.
Fixes this to actually work.
Significant balance fix for vehicles.
:cl:
fix: fixed vehicles being able to shoot mobs on top of them when they shouldn't have been able to
/:cl:
=> Tank Desant projectile fix

code/modules/mob/living/living_defense.dm
Lava will now keeps processing when someone with pass_fire goes over it.
Marines were not meant to stand on lava
:cl:
fix: Jumping onto lava now burns you when you land.
/:cl:
=> Lava hotfix

code/modules/reqs/supplypacks.dm
I swear I remember there being some discussion on this being a balance thing with the howitzer only getting tangle, but I might've mixed this up with WP. Anyways howitzer tangle shells were sharing the same datum as the mortar shells, hence you couldn't order them.
I also renamed the howitzer wp, in the rare case mortar WP gets added
Fixes #15900
Tangle mortar shells are slightly less condemmed to reqtorio hell
:cl:
fix: After two years - Tangle mortar shells can be ordered again
/:cl:
=> Fixes bug preventing tangle mortar shells from being ordered

_maps/modularmaps/big_red/bigredsouthwestetavar5.dmm
In this one module there's just an extra plat miner sitting in a hall. All of the other module equivalents only have 1 miner. This one has two, for some reason.
one day I will kill all modulars
Mfw rng marine buff
:cl:
balance: removes an extra plat miner from a big red modular variant that was not present on any other variants.
/:cl:
=> Removes an extra plat miner from big red – west Eta

_maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm, _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm, _maps/map_files/riptide/riptide.dmm
Each of these maps have less than 40 digsites, with Riptide having only 12 (compared to 80+ on other maps). This increases the number on each of these maps to ~100.
Digsites are a very good side objective for making money that naturally gets harder during a round as the freebies are taken and more respawn in harder to reach areas. Maps with few of these harder ones make it very easy to just wait the 5 minutes for them to respawn in the easy areas, so this PR adds a lot more variance on the areas and potential difficulty of digsites.
:cl:
add: Added a ton of researcher digsites to Riptide, Magmoor, and Lawanka.
/:cl:
=> Adds a ton of digsites to Riptide, Magmoor, and Lawanka

code/__DEFINES/preferences.dm
Renames the two chestburster prefs from "Latejoin Xenomorph" and "Xenomorph When Unrevivable" to "Join as Chestburster" and "Take Own Chestburster"
Clarifies when these are actually used to hopefully encourage people to turn these on instead of leaving every burst SSD to die.
:cl:
spellcheck: Renamed chestburster preferences.
/:cl:
=> Renames chestburster prefs

code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm, code/modules/mob/living/carbon/xenomorph/charge_crush.dm
- Gore: The bull now has poison glands in the roots of its horns that produce Ozelymelon, and the horns double as stingers. i.e Gore charge now also injects 10u Oze (same as Shrike sting). And it also deals 1 second of stagger (-50% damage).
- Headbutt: Stun time 2.5 > 2 seconds. Displacement 2 > 3 tiles (at max speed).
- Plow: Deals 0.2 seconds of stun (disarms whoever is hit), and can't multi-ram anymore.
Bull is objectively the weakest T2 in the game right now, worse than even T1s in most situations. I think one of the bigger issues with it is the fact that its abilities are designed for killing, and yet are also terrible at securing kills. Like man, if a marine enters crit (or even just lays down), its abilities are rendered completely useless, and slashing is generally a bad idea due …
=> Mini Bull rework and buff

code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm
Reduces puppet damage from 15 to 12, effectively reducing the damage of max puppets from 45 to 36.
Currently, puppets have stats equivalent to 2 spiderlings. This means that they do a shit ton of damage per minion compared to spiderlings, and are more tanky as well. This change aims to make puppets less "insta-death" and more "deadly wall" by reducing their damage but keeping their health the same.
:cl:
balance: Reduce puppet damage from 15 to 12
/:cl:
=> Reduces Puppet Damage

code/game/objects/machinery/vending/vending_types.dm
Makes the hypos in the NTMed default to being empty
This should make prep slightly less annoying now.
There never was a lack of hyposprays in the vendor, but people get annoyed when they have to vend a bicaridine hypo, just to empty it in order to fill it with what they want.
:cl:
qol: All the hyposprays in the NTMed are empty by default
/:cl:
=> Makes the hypos in the NTMed default to being empty

code/datums/emergency_calls/sons_of_mars_breachers.dm, code/datums/jobs/job/job.dm, code/datums/jobs/job/sons_of_mars_ert.dm, code/datums/skills.dm
Adds some skills to the SOM breacher ert/the SOM SL, including the axe sweep ability.
Actually gives them their own name so its not just a copy paste.
Big more interesting variety, makes the breacher variant a little better considering they have a strong focus on melee with axes.
:cl:
balance: SOM breacher ERTs have undergone more advanced training
/:cl:
=> Som ERT breacher skills

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Prevents crusher from crest tossing armored vehicles, aka the APC and tank
Considering how slow they are, being able to just get instantly displaced several tiles makes it difficult for tank to safely be near the front line. also prevents bugs like this
https://github.com/tgstation/TerraGov-Marine-Corps/assets/87689371/38e2a7ea-3a4c-424f-a32b-65976d6384e2
:cl:
balance: Crusher can no longer crest toss armored vehicles (such as the apc and tank)
/:cl:
=> Prevents Crusher from crest tossing vehicles

code/game/objects/structures/stool_bed_chair_nest/bed.dm
Adds a brake funtion to roller beds, allowing humans to toggle their anchor state on and off. Roller beds deploy with their anchor on by default.
Currently, using roller beds groundside carries the massive risk of a xeno coming by and kidnapping the patient, guaranteeing a perma. This will hopefully reduce the chances of this happening, and make roller beds much more useful for corpsmen.
:cl:
balance: Roller beds now have brakes that can be toggled with right click.
/:cl:
=> Adds brake function to roller beds

code/datums/storage/subtypes/pill_bottle.dm
Makes hypos not open pill bottles when you click on it to liquify a pill.
QOL
:cl:
qol: Liquifying a pill with a hypo no longer opens the pill bottle
/:cl:
=> Hypos no longer open pill bottles

code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/client/preferences_ui.dm
1) If a player joined, then ghosted or did nothing, and then another round started, they would have no keybinds because the new player code would create a save file, save the defaults into the file, **then** load the default keybinds, meaning the savefile would still have blank keybinds which would get loaded next round.
2) If the keybind list was for any other reason invalid, it would load a blank keybindings list.
3) If a player hit reset-keybinds, the default keybind list would get loaded into their preference datum *by reference*. See the 3rd commit for more info.
Players getting blank keybinds, joining the game, and being unable to move are only 40% likely to mentor help to ask why, and 60% likely to just go to some other server.
=> Keybinds misc fixes

code/game/objects/items/scanners/health_analyzer.dm
Fixes this, I forgot to put the ternary operator in parenthesis
fix
:cl:
fix: health analyzer revivable threshold no longer always says 20%
/:cl:
=> fixes health analyzer revivable threshold (for the final time)

code/datums/components/deployable_item.dm, code/game/objects/items/weapons/shields.dm
Prevents deployable shields from being deployed on the alamo and the tad.
Helps reduce ahelps for these things, and prevents an exploit
:cl:
fix: Deployable shields can no longer be deployed on the alamo and the tad
/:cl:
=> Prevent deployable shields on the tad and alamo

code/modules/shuttle/marine_dropship.dm
There might be either some spaghetti here, or someone just forgot to readd this line when doing a refactor
Fixes #15741
Queen/King/Shrike can no longer be theorectically trapped by locking all the doors as soon as it's inside
:cl:
fix: Alamo now unlocks itself when a T4 touches the console (as it used to)
/:cl:
=> Alamo doors unlock on hijacking the console

code/datums/storage/storage.dm, code/datums/storage/subtypes/bag.dm, code/datums/storage/subtypes/box.dm, code/datums/storage/subtypes/holster.dm, code/datums/storage/subtypes/internal.dm, code/datums/storage/subtypes/pill_bottle.dm, code/datums/storage/subtypes/wallet.dm
2 bugfixes:
Fix stacks breaking when you try merging stacks together
fix deleting an item inside a storage not properly removing it from the storage
Fixes #15910, #15879
bugfix
:cl:
fix: Merging stacks inside a backpack will no longer break
fix: Deleting something inside a storage will no longer break
/:cl:
=> Fix stacks in backpacks breaking

code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Huggers will no longer bounce if thrown into a mob.
Fixes #13686
:cl:
fix: Huggers will no longer bounce if thrown into a mob
/:cl:
=> Hugger throw fix

code/datums/components/attachment_handler.dm
Fixes #15365
Swapping out attachments would put the old attachment in your hand when removing it, but then put it in hand AGAIN after the new attachment was successfully added, leading to an invisible phantom attachment. This only occured while you had a free hand (i.e. swapping webbings since you don't have to hold the item to do so).
:cl:
fix: fixed a phantom attachment bug when swapping attachments in some cases.
/:cl:
=> Fixes an attachment component bug

code/game/objects/structures/barricade.dm
Deconstructing an upgraded metal barricade automatically factors in the metal used to upgrade it. This means deconstructing an upgraded metal barricade should return 5 sheets of metal (actual cost) instead of 4 (not upgraded cost).
Bug fix. Makes deconstructing more convenient since you don't have to degrade and then deconstruct to get the full refund.
:cl:
fix: Deconstructing an upgraded metal barricade now returns the actual cost of 5 sheets instead of 4.
/:cl:
=> Deconstructing upgraded metal cade refunds full cost

code/datums/components/deployable_item.dm, code/game/objects/machinery/mortar.dm
Trying to undeploying a mortar deployment now returns/dumps any chambered items onto the floor.
Fixes #15938
Bugfix. The mortar shell that I didn't launch or use shouldn't delete itself when I pack up my mortar to move it elsewhere.
:cl:
fix: Mortar's chambered items now drop onto the floor (instead of deleting itself) when undeployment attempt is made.
/:cl:
=> Trying to undeploy mortar refunds any chambered items

code/datums/marine_main_ship.dm, code/game/objects/structures/orbital_cannon.dm
Although OBs have penalties for loading an incorrect amount of solid fuel, the severity of this is calculated by subtracting the amount of fuel you have loaded from the required amount of fuel.
This means that if you have a requirement of 2 solid fuel for a tanglefoot OB, you can only ever get a penalty of 4 seconds due to inadequate fuel
On the other hand, if you get a requirement of 6 solid fuel, you can incur a penalty of up to 20 seconds of tanglefoot hang time due to inadequate fuel
letting something as important as OB innacuracy rely purely on RNG doesn't sit right with me
this also means you can do gamble obs every round instead of waiting for them to cost a bunch :^)
:cl:
balance: ALL Orbital Bombardment types cost 6 solid fuel
/:cl:
=> Makes OBs cost the same (solid fuel-wise)

code/modules/vehicles/_hitbox.dm
Day 7485 of Tivi's plan to ignore multitile bugs until I get annoyed enough to fix them.
You will no longer be cursed to fly into space/out of the alamo if you walk between two vehicles.
Fixes #15945, #15799
:cl:
fix: fixed walking between multitile vehicles causing issues
/:cl:
=> Fix cursed vehicle to vehicle movement

code/datums/keybinding/xeno.dm, code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
The description implies that the ability adds a stack of melting flame - It doesn't. What the ability actually does is extinguish the target, and deal extra damage depending on how many firestacks they have.
Less pyrogens charging a guy on fire and wondering - WHY HE NO SET ON FIRE AND WHY HE EXTINGUISH
:cl:
spellcheck: Pyrogen Fire Charge ability now accurately describes what it does - Extinguish the target and deal extra damage depending on their fire stacks
/:cl:
=> Pyrogen Fire Charge description correction

code/modules/vehicles/_hitbox.dm, code/modules/vehicles/armored/_multitile.dm
Make ex_act/lava_act consistant for multitile vehicles.
Currently both these effects are very strange for tanks.
Explosions do nothing unless they hit the middle turf (the tank object itself) while lava hits it for EVERY tile in lava.
Made them both consistant in this behavior - the more vehicle turfs in an explosion/lava, the more damage.
Reduced the damage for both of these to take this into account.
Weak explosions simply do nothing to tanks, while light does very little and heavy does a fair bit (dev still qdels)
Lava does 30 instead of 50 per tile, but considering the speed of a tank, trying to traverse an actual lava lake is still a sure fire why to lose your ride.
This also means you essentially get bonus damage if you catch the centre of the tank in lava or an explosion.
The …
=> Tank AOE damage stuff

code/modules/clothing/modular_armor/attachments/modules.dm
Increases surt's fire resistance from 35 to 45 per module
Currently, surt is not really useful, with it's only use being preventing yourself from being lit on fire, something that combat robots already benefit from without needing to sacrifice armor module slots for. The damage from fire can be mitigated by simply pre-medding, meaning surt has little use as is. This increase to it's fire resistance will hopefully give it more of a niche use when dealing with fire, especially if using heavy armor and if #16014 is merged. Also 
:cl:
balance: Increased surt's fire resistance per module piece from 35 to 45
/:cl:
=> Increases surt fire resistance to 45

code/__DEFINES/mobs.dm, code/datums/status_effects/debuffs.dm, code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
Reduces the ability delay of pyro's tornado and fireball ability to 0.6 seconds, down from 1 second. Increases the charge range by 2 tiles (5 tiles range), and changes the damage of pyros abilities from acid to fire.
Pyro is currently a very weak caste, being a squishy frontliner with sluggish abilities and a short range charge meant to combo with it's other abilities to do damage. These buffs aim to help make it be better at front-lining while keeping it as a squishy caste. The fire change is due to the caste dealing acid damage being incredibly unintuitive. Also 
:cl:
balance: Reduced the ability delay on pyrogens fireball and fire tornado to 0.6 seconds, down from 1 second.
balance: Increased the fire charge range by 2 tiles (from 3 tiles to 5 tiles)
balance: Changed pyros damage from …
=> Pyrogen Buffs and damage type rework

code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Fixed huggers bouncing off mobs for real.
Turns out there was a funny 2nd snowflake bounce call.
:cl:
fix: fixed huggers bouncing off mobs (again)
/:cl:
=> Fix hugger bounce for real

code/modules/projectiles/projectile.dm
Hitscan projectiles now properly set their direction.
Would creates issues where direction mattered, such as mechs with directional armour.
:cl:
fix: fixed hitscan projectiles not correctly setting their direction
/:cl:
=> Hit scan fix

code/__DEFINES/is_helpers.dm, code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Title, specifically them not doing damage to vehicles if they are tossed rather than rammed with landslide. Also makes it so the AoE attacks don't have to hit the center in order to do damage, rather they can hit any part of the tank.
Bugs bad
:cl:
fix: Behemoth's earth pillars should do damage to vehicles now if they are tossed at them
fix: Behemoth's AoE attacks will now damage all parts of the tank (previously only damaged it's center)
balance: Adjusted Behemoth's ability damage to compensate for attacks like meteor doing damage per vehicle tile hit
/:cl:
=> Fixes behemoth's earth pillar and AoE attacks not damaging vehicles outside of the middle

code/modules/vehicles/armored/__armored.dm, code/modules/vehicles/armored/apc.dm
Fixes up external loading vehicle weapons and actually make external loading secondary guns work as well.
Additionally, APC's can now correctly load normal crates. My understanding is that this was always the intention.
Working features good.
:cl:
fix: APC can load normal crates as intended
/:cl:
=> Vehicle loading fixes

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
As the title says it lets you cancel evade faster, I'd make it 0 but on the off chance someone double taps really fast this will help them, kinda.
You can now slash that shotgunner (1) more time while their fire delay is still up, jokes aside earlier evasion cancel gives more control over being unable to slash for a whole second.
:cl:
balance: Runner evasion can now be canceled at 0.3 seconds, instead of 1 second. (1 --> 0.3) 
/:cl:
=> Makes Evade cancel timer 0.3 seconds instead of 1 second

code/__DEFINES/conflict.dm
Reduces AMRs on-hit slowdown from 3 to 2.25
AMR currently has some of the highest slowdown of any gun, on par with a sadar. Unlike a sadar, you can have a whole magazine to use to cause this slowdown and do this from miles away. Combine this with the 50 AP and 135 damage, and whatever gets hit becomes a easy to attack target. 
:cl:
balance: Reduced the slowdown of the amr from 3 to 2.25
/:cl:
=> Reduce AMR's on-hit slowdown

_maps/map_files/slumbridge/slumbridge.dmm
Yeah no, this is not a good thing and needs to be quickly removed
Replaced it with this:
* Less unfair deaths
* This shouldn't happen anymore
https://github.com/tgstation/TerraGov-Marine-Corps/assets/80391698/e28af98d-8b04-4aeb-8391-e4daa281bb38
:cl:
fix: fixes a object fling trap in Slumbridge engineering
/:cl:
=> Removes an egregious object fling trap in Slumbridge

code/controllers/subsystem/minimaps.dm
Xenos can now see research digsites on the minimap just like researchers can.
There is no point to a side objective if only one team even knows it is there. Xenos should be able to prepare defences on these and researchers should need to prepare a team to take these objectives. 
:cl:
balance: Xenos can now see research digsites on the map.
/:cl:
=> Xenos can now see research digsites.

code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/bull.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm, code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Tl;dr Bull is no longer stun and knockback immune. All charges now deal 48 damage (2 slashes) exactly. Headbutt has even less stun. Bull's walking speed very slightly increased.
Stun immunity: **Gone**. It can be stunned by buckshot/slugs again, and knocked around by explosives.
Gore: 62 > **48 damage**. It now also does 1 second of slow alongside the stagger. Also also removed it's extra slash that (I think) made it more likely to frac and IB due to wacky code.
Headbutt: 20 > **48 damage**. 2 > **1.5 second stun**.
Plow: 20 > **48 damage**.
**Stun immunity:** This was given to bull as a sort of bandaid for being a terrible caste that couldn't accomplish anything worthwhile with its abilities. Now that its abilities are actually good, its no longer needed. Stun immunity makes Bull too …
=> Bull rework part 2

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Title, makes it so King's roar deals damage depending on how much of the vehicle is hit, up to 120 damage if the king is right next to it.
Currently, King's roar only deals 80 damage if it hits the center of the tank. This is very unintuitive, and isn't much considering it requires the King to sit there and stare at the tank while winding up his roar. This makes it so that even if the roar only grazes the tank, it will at least do something, rather than literally nothing, and will reward the king for hitting more of the tank.
:cl:
balance: King's roar now deals damage to all parts of the tank instead of just the center. Damage is 12 per tile at close range, 10 per tile at farther distances. 
/:cl:
=> Make King Roar's armored vehicle damage depend on how much is hit

code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Title, increases to be between 50-100, depending how long the crusher was charging.
Currently, crusher does about 20 damage max if it charges into the tank. This is abysmal, especially considering the crusher has to get in the tanks face to do this damage. This hopefully helps crushers actually do damage to the tank, outside of sitting on it and smacking it.
:cl:
balance: Crusher's charge now does more damage to tanks and apcs (from between 18-21 to between 50-100) depending on the charge distance.
/:cl:
=> Increase crusher charge damage against tanks

code/modules/projectiles/ammo_types/xenos/pyrogen_xenoammo.dm
Title, changes it from acid to fire
Pyro does fire damage now, not acid damage. Will slightly increase the AoE damage of fireball due to armor having lower fire damage resistance compared to acid.
:cl:
fix: Fixed pyrogen's fireball AoE checking for armor's fire resistance instead of acid
/:cl:
=> Fix pyrogen's fireball AoE checking the wrong armor type

code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
Spiderlings now ignore if the marine is incouncious and continue attacking them
https://github.com/tgstation/TerraGov-Marine-Corps/assets/32490372/0608a627-f672-4e7c-b364-0c2846758b35
https://github.com/tgstation/TerraGov-Marine-Corps/assets/32490372/5eaa9dfd-d0f7-4dd3-8cdc-8d3449a30e04
Spiderlings can now be attached to widow so if you want to crit drag a marine just put them on your back.
Also having to slash 10 times before to drain gave plenty of time for CAS to just murder your spiders.
You can also now finish a medded vali x2 nanite without them going up every ticks 
:cl:
add: Spiderlings can now attack uncouncious marines
/:cl:
=> Spiderlings can now attack uncouncious marines

code/modules/projectiles/guns/_shared_ammo_objects.dm
Title, changes the damage from acid to fire
This is something I missed when converting pyro from acid damage to fire damage in #16014. Makes it consistant with the rest of pyro's abilities
:cl:
fix: Fixed pyrogen's melting ground fire using ACID armor instead of FIRE
/:cl:
=> Fixes melting fire on the ground dealing the wrong damage type

code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Xeno jump CD changed from 2 seconds to 1 second (same as humans).
Makes xenos a bit more mobile, especially on the two most recent maps from CM that have a lot of close together platforms etc.
:cl:
balance: Reduced xeno jump CD from 2 seconds to 1 second
/:cl:
=> Xeno jump cd buff

code/game/objects/items/binoculars.dm, code/modules/clothing/modular_armor/attachments/modules.dm
You can no longer use binos (hand held or hat mod) while looking through things such as being in a tank seat.
Fixes #16053
:cl:
fix: fixed an exploit with binos
/:cl:
=> Fix bino exploit

code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm, code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm, code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/ammo_types/ags_ammo.dm, code/modules/projectiles/ammo_types/energy_ammo.dm, code/modules/projectiles/ammo_types/heavy_ammo.dm, code/modules/projectiles/ammo_types/mech_ammo.dm, code/modules/projectiles/ammo_types/microrail_ammo.dm, code/modules/projectiles/ammo_types/miscellaneous_ammo.dm, code/modules/projectiles/ammo_types/mortar_ammo.dm, code/modules/projectiles/ammo_types/pistol_ammo.dm, code/modules/projectiles/ammo_types/revolver_ammo.dm, code/modules/projectiles/ammo_types/rifle_ammo.dm, code/modules/projectiles/ammo_types/rocket_ammo.dm, code/modules/projectiles/ammo_types/shotgun_ammo.dm, code/modules/projectiles/ammo_types/smartgun_ammo.dm, code/modules/projectiles/ammo_types/smg_ammo.dm, code/modules/projectiles/ammo_types/sniper_ammo.dm, code/modules/projectiles/ammo_types/turret_ammo.dm, code/modules/projectiles/ammo_types/tx54_ammo.dm, code/modules/projectiles/ammo_types/volkite_ammo.dm, code/modules/projectiles/ammo_types/xenos/energy_xenoammo.dm, code/modules/projectiles/ammo_types/xenos/gas_xenoammo.dm, code/modules/projectiles/ammo_types/xenos/huggers_xenoammo.dm, code/modules/projectiles/ammo_types/xenos/pyrogen_xenoammo.dm, code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm, code/modules/projectiles/ammo_types/xenos/widow_xenoammo.dm
Fixex various projectile "on_hit" effects triggering on the incorrect turf in certain cases. This relates to how a projectile's loc does not change during a batch move, meaning the faster a projectile, the higher the inconsistancy could be.
Also made all the args for these on hit procs consistant.
Bug fix.
Consistant args good. Holy fuck there was so many variations.
:cl:
fix: fixed some projectile on hit effects triggering on the wrong turfs in some cases
/:cl:
=> projectile fixes and cleanup

code/game/objects/items/stacks/medical.dm, code/modules/reagents/reagent_containers.dm, code/modules/reagents/reagent_containers/hypospray.dm
Using an injector, splint, gauze, etc. in-hand (same button as wielding a weapon) will apply/inject them to yourself.
Pressing unique action with an injector in-hand will now open its menu.
Small QoL requested by Elsa. Less mouse movement good. Also more in line with how CM's autoinjectors function, making them more intuitive.
:cl:
qol: Using medical items in-hand will now apply them to yourself
qol: Unique action now opens the injector menu
/:cl:
=> Medical items now apply to yourself if you use them in-hand

code/game/objects/structures/crates_lockers/largecrate.dm, code/game/objects/structures/rocks.dm
Rocks have the defensive structure pass flag, allowing xeno leaps and such over them (but not jump).
Large crates (the big ones, and subtypes such as barrels and green storage boxes) are jumpable.
Some QOL for passability to be a bit more consistant with other stuff.
:cl:
balance: Largecrates are jumpable
balance: Large rocks can pouched over etc, similar to unwired cades
/:cl:
=> Pass flag changes

code/modules/projectiles/ammo_types/xenos/gas_xenoammo.dm
Fixes boiler direct hits on mobs reducing the smoke size.
#16056 unintentionally made direct hits with boiler globs reduce the size range down to one. This fixes a bug, and bugs are bad, therefor pr is good.
:cl:
fix: Boiler globs getting a direct hit should no longer reduce their smoke size
/:cl:
=> Fixes Boiler Direct Hits

code/modules/vehicles/mecha/combat/combat.dm
Allows marines to shoot through the mech if they have IFF, such as aim mode or smart gunners
Suggestion by Kuro, one of the complaints about mech was the inability to shoot through it at all as a marine. This helps to fix that by allowing IFF to shoot through the mech.
:cl:
balance: The mech can now be shot through using IFF (aim mode, smart guns, etc)
/:cl:
=> Allows Marines to shoot through mech using IFF

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Title, crush will now hit the hitbox of tanks and apcs for 10 damage each.
Consistency and intuitiveness. Will slightly lower the damage of insta-crushes on the tank/apc.
:cl:
balance: Warlock's crush now hits more parts of tanks/APCs, dealing 10 damage per part hit.
/:cl:
=> Warlock Crush Hits more of the Tank now

code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm, code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm, code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Title, changes a var name from vehicle_damage_mult to obj_damage_mult
Less confusing
:cl:
code: Changed vehicle_damage_mult in crusher charge ability to obj_damage_mult
/:cl:
=> Changes some bad/inaccurate var names in xeno abilities

code/modules/vehicles/_hitbox.dm
Title, makes it so xeno acid smoke deals damage based on how many tiles is in the smoke, between 400-500 if it just sits in a boiler cloud completely enveloped the entire duration.
Consistancey and intuitiveness. Also makes acid smoke more of a threat for apc/tanks
:cl:
balance: Xeno acid smoke will deal damage per tile of apc/tanks hit, between 400-500 if completely enveloped the entire duration of a boiler cloud.
/:cl:
=> Xeno Acid Smoke Deals Damage to APC/Tank Based on HItbox

code/game/turfs/turf.dm, code/modules/mapping/map_template.dm
Fixes static lighting for vehicle interiors.
While this does not fix lighting for shuttle interiors, they WERE impacted by this bug... they are just also impacted by a second bug that I can't figure out. (If anyone is smarter than me, its an issue specifically with shuttle code, and ChangeTurf() fixes shuttle turfs but I cannot for the life of me track down how).
Cool lighting effects.
:cl:
fix: Static lighting works in vehicle interiors, or other generated areas
/:cl:
=> Light interior fix

_maps/map_files/generic/Admin_Level.dmm, code/game/objects/machinery/buttons.dm, code/game/objects/machinery/vending/marine_vending.dm
Updates the vehicle spawner area in marine valhalla to use buttons to spawn vehicles, and removes two spawned vehicles that are there currently. Also adds the current vehicle guns to the valhalla req vendor.
Makes it easier to test vehicle stuff in valhalla without risking permanent loss of said vehicles.
:cl:
add: Added the APC/tank weapons to the valhalla req vendor
qol: Replaced the spawned vehicles in marine Valhalla with vehicle spawner buttons
/:cl:
=> Valhalla Vehicle Area Update

code/datums/elements/submerge.dm
logic typo meant grass and such wasn't submerging in cases where it should.
:cl:
fix: fixed an issue with grass or flames not submerging correctly in some cases
/:cl:
=> Submerge fix

code/datums/gamemodes/campaign.dm
Adds an arg to let admins force autobalance through on campaign.
If the teams are really unbalanced, the game is unfun. If one team refused to autobalance to that point, admins can just force them so its not a one sided stomp.
:cl:
admin: You can force autobalance during Campaign
/:cl:
=> Forced campaign autobalance option

code/modules/projectiles/ammo_types/heavy_ammo.dm
Buffs the tank's ap, sunder and falloff, also slightly buffs accuracy
Tank chaingun was never that good compared to LTB, even with IFF the gibcannon was way above it in performance, especially after the xeno buffs.
This should bring them close together in terms of performance.
:cl:
balance: Buffs the tank chaingun
/:cl:
=> Buffs the tank Chaingun

code/__HELPERS/ai.dm, code/game/objects/items/explosives/mine.dm, code/modules/projectiles/guns/sentries.dm, code/modules/projectiles/sentries.dm
Mines and sentries will now target tanks as applicable.
Needed for HvH.
:cl:
fix: Mines and sentries will target hostile tanks
/:cl:
=> Tank fixes for mines and sentry

code/game/objects/machinery/vending/marine_vending.dm
Adds vehicle modules to valhalla. Does not add the passenger module and clone module. Passenger due to not actually doing anything, and clone cause clone vats were not designed with being in Valhalla.
Let's people test vehicle modules in valhalla.
:cl:
add: Added the overdrive, zoom, smoke launcher, and medical vehicle modules to the req vendor.
/:cl:
=> Adds vehicle modules to valhalla

code/game/data_huds.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/client/preferences_ui.dm, code/modules/mob/living/carbon/xenomorph/castes/king/king.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm, code/modules/mob/living/carbon/xenomorph/death.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm, tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Can toggle rank on and off
Clientless xenos have no rank
Rank HUD deletes on death
Requested feature if you wanted to play anonymously, additionally this was possible before maturity removal and then I removed it. Sometimes people just want to play as Drone (123) and I don't think we should deny that to them. Additionally fixes good.
:cl:
add: Xeno Ranks: Preference to toggle them on and off
fix: Clientless xenos no longer have ranks
fix: Xeno rank HUD no longer persists after death
/:cl:
=> Allows toggling of xeno ranks + xeno rank fixes

code/game/objects/machinery/computer/dropship_picker.dm
No it doesn't fix the lag issue, but at least mashing during the lag period won't cause the Tad to bug out. Fix shamelessly stolen from discord.
Slightly less Tad borking
:cl:
fix: Mashing the confirm button on the dropship selector won't bug the Tad out
/:cl:
=> Fixes mashing confirm on the dropship selector bugging the Tad out

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Forced devolve properly does what it is suppose to do -- devolving an xeno instead of qdel'ing.
Bugfix.
:cl:
fix: Forced devolve works again.
/:cl:
=> Forced devolve works again

code/modules/vehicles/_hitbox.dm
Title, divides the damage that vehicles take by 5
Currently tanks/apcs are taking an absurd amount of damage trying to move out of boiler smoke. This should make boiler smoke less oppressive while still keeping it as a threat to stay away from. Standing still in the boiler smoke will do about 175 damage now.
:cl:
balance: Divided the damage dealt from boiler gas to tanks/apcs by 5
/:cl:
=> Reduces boiler damage against APCs/Tanks

code/game/atoms/atom_movable.dm
Adds a missing override.
Crash message go home.
:cl:
code: Added a missing signal override
/:cl:
=> Nosubmerge crash fix

code/_onclick/item_attack.dm, code/game/objects/items/weapons/weapon.dm
Title, removes the ability to attack with weapons if you are prone. This should include things like getting stunned from a pounce, or simply lying down.
Melee weapons being able to attack while prone has been a long standing bug, and I'm gonna finally fix it.
:cl:
fix: Can no longer attack with melee weapons while lying down.
/:cl:
=> Removes the ability to attack with weapons while prone

code/modules/reagents/reagent_containers/autoinjectors.dm, code/modules/reagents/reagent_containers/hypospray.dm
Injectors/hyposprays now display keybinds to use them when examined.
I changed how injectors work so Xander suggested this should probably be reflected in the description. Clarity good.
:cl:
add: Injectors/hyposprays now display instructions for using them in their description
/:cl:
=> Adds instructions for how to use hyposprays

code/modules/projectiles/gun_helpers.dm, code/modules/vehicles/armored/__armored.dm
:cl:
fix: Fixed tank aiming at darkness trying to shoot across zlevels: aiming at darkness now shoots at your actual target
/:cl:
=> Fixes tank aiming at darkness trying to shoot across zlevels

code/modules/vehicles/armored/__armored.dm, code/modules/vehicles/armored/armored_weapons.dm
looks like duplicate overlay handling was the issue from a previous ver, i just removed that and it still works fine so let's see how this fares
:cl:
fix: Probably fixed secondary tank weapon overlays duplicating
/:cl:
=> Probably fixes secondary tank weapon overlays duplicating

strings/tips/marine.txt
Corrects incorrect tip.
Based on 
`	if(HAS_TRAIT(affected_mob, TRAIT_STASIS))
return //If they are in cryo, bag or cell, the embryo won't grow.
`
Misinformation le bad
:cl:
fix: Fixes incorrect tip about larva growth being only slowed during stasis
/:cl:
=> Corrects incorrect tip about larvas and stasis

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Title, ravage will now hit the tank/apc hitbox from anywhere, rather than only if it hits the center too.
More consistant and intuitive. Does about 50 damage if ravage hits 3 parts of the tank.
:cl:
balance: Ravage will now hit any part of the tank and APC.
/:cl:
=> Ravage now hits more of the APC and Tank

code/modules/codex/entries/misc_codex.dm
This adds a weight check to the codex's text generation for all items that act as storage
Thus, this fixes #14633 
Removes some misleading codex entries
:cl:
add: Adds a weight check to the codex's text generation for all items that act as storage
/:cl:
=> Adds Weight Check to Codex Item List Generation

code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Fixed improper names when using the rankless pref
No more Mature Larva (123) when you are Hivelord (123) in reality (hopefully)
Fix good.
:cl:
fix: Fixed improper names showing when you played as a xeno without your rank turned on
/:cl:
=> Xeno name fix

_maps/map_files/DaedalusPrison/DaedalusPrison.dmm, code/game/area/daedalusprison.dm
Most of the walls are rwalls now instead of normal walls
Added a few rocks for xenos to heal
The prison area is mostly glass ceilings (tad can enter)
More excavation sites in the main prison for RSR
Daedalus Prison has been pretty marine favored since vehicles came out as normal walls are nothing to them (and marine bullets by that measure, but it is rarer for marines to shoot them down) so the map was just torn down. Additionally, Tadpole couldn't exactly play in half the map outside of caves, as well as RSR. This remedies that.
:cl:
balance: Daedalus Prison: Way more r walls, more rocks for xenos to heal, glass ceilings in many prison areas (tad can land) and more RSR excavation sites in the prison.
/:cl:
=> Daedalus Changes (#3)

code/modules/vehicles/armored/armored_weapons.dm
There was a missing equal sign that made it possible to fire the same shell twice. 
Step 1; Fire ltb
Step 2; Put shell back in
Step 3; Fire again
Is bug, bad.
:cl:
fix: Tanks can no longer fire the same shell twice
/:cl:
=> Fixes being able to get 2 shots out of 1 shell in Tank

code/_onclick/adjacent.dm, code/game/objects/items/storage/backpack.dm
Adds an adjacency check when trying to access a storage within a storage worn by someone else.
Bugfix
:cl:
fix: fixed being unable to take pills out of a pill bottle in someones duffel
code: items in storage now check a flag IN_STORAGE instead of type checking
/:cl:
=> Fixes being unable to draw from storages within a duffelbag.

code/__DEFINES/mobs.dm, code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/modules/mob/living/carbon/update_icons.dm
Fixes the way lying offsets are calcuated for carbon mobs.
Cleaned up bed offsets to work/look correct.
Bug fix.
:cl:
fix: fixed some minor offset issues with lying on beds
/:cl:
=> Lying offset fix

code/_onclick/ai.dm
Literally only used to delay the round by 30 seconds to a minute when xenos want to hijack and there is no way to stop it.
:cl:
balance: Disallows AI railgun to target FOB
/:cl:
=> Disallows AI railgun to target FOB

code/controllers/subsystem/lighting.dm, code/modules/mapping/map_template.dm
Fixed a runtime error that would come up when late loading z-levels, so basically only effected campaign.
Light objects are now created when the turfs are populated, so it doesn't need to be called manually later.
:cl:
code: Fixed a lighting runtime when late loading z-levels
/:cl:
=> Lighting error fix

code/datums/jobs/squads.dm
Fixes squad radio so command members can not only listen but also talk on custom squad radio channels
It annoyed rabbit lead. I fix bug for rabbit lead.
:cl:
fix: Command now can talk on custom squad radios
/:cl:
=> Fixes squad radio for non squad members

code/modules/reagents/reagent_containers/hypospray.dm
Allows hyposprays to inject their full amount in 1 go
It is now possible to fully inject a chem mix entirely in 1 go.
:cl:
qol: Hyposprays can inject their entire storage at once.
/:cl:
=> Hypospray can inject 60/120u at once

_maps/map_files/Sulaco/TGS_Sulaco.dmm
Adds alpha tcoms to sulaco, thereby fixing the null list error on squads.dm:461 while playing sulaco, and allows the successful creation of squads
Especially if we are moving towards a single initial squad system, I think this bug should be fixed, as this drawback of sulaco has been a non minor factor for people not chosing this antiquated map, almost entirely avoiding it on high pop when popular custom squads like pink or rabbits are in rotation.
:cl:
fix: Fixed inability to create squads on Sulaco
/:cl:
=> Fixes inability to create custom squads on sulaco

_maps/shuttles/minidropship_outrider.dmm
Oops
Fix good
:cl:
fix: doubled-up windows on Outrider Tadpole
/:cl:
=> Fixes doubled-up windows on Outrider

_maps/map_files/LV759/LV759.dmm, code/game/objects/structures/hybrisa_props.dm
This pr does a few things. Most notably, it opens up the research station (the place with the queen in a jar) by removing a lot of doors and some glass walls/doors to make navigation easier for xenos, removes a fair amount of sandbags outside the research station, replaces some of the road shutters with resin doors, and makes the signs, computers, and screens damageable and reduces their integrity down from 500 to between 50-80. A pair of tactical binoculars was also removed. Also removed some platforms by east colony streets and the pool.
The research station is a bit difficult to navigate as xeno, which is a bit odd considering that's supposed to be the origin of the xeno outbreak on the map. The sandbags act as free cades whenever the marines show up to the area, whether or not they …
=> LV-759 Clean Up And Balance

code/modules/mob/living/carbon/xenomorph/evo_datum.dm
This was intended in code, but this check was missing here
You're meant to be able to strain swap instantly without waiting for the evo timer
:cl:
fix: Fixed Strain Swapping not being instant and relying on evo timer
/:cl:
=> Fixes strain swapping not being instant

code/modules/reqs/supply.dm, tgui/packages/tgui/interfaces/Cargo.jsx
Makes it so that if the same item was sold as the last one, then it doesn't begin a new row, and instead adds up to the previous row. (With the following format: stack number x single item points (total stack points) )
Especially when for an example, selling credits or pizza, instead of a morbillion quachillion rows, you get this
:cl:
qol: Same as last rows in req export history now stack
/:cl:
=> Makes large req export histories more readable and less laggy

code/datums/gamemodes/campaign.dm
Respawning in campaign now DNR's your body like it used to.
The recent change to defibbing/DNR etc had the knock on effect in Campaign where people respawning would leave their bodies in a revivable state.
I was happy to leave this for a bit but its really not ideal.
Firstly because it makes it impossible to tell where GENUINELY revivable people are on the map.
Secondly because no one ever gets back into ssd corpses
Thirdly If someone did, there are no faction checks
And lastly it could mean dirt eating goobers could farm damage and revives on an SSd body.
:cl:
fix: Campaign: Respawning in campaign now DNR's your body like it used to
/:cl:
=> Campaign DNR fix

_maps/map_files/generic/Admin_Level.dmm, code/game/objects/machinery/buttons.dm
Title, adds a surgery area in valhalla, and modifies the xeno caves buttons to be usable by marines.
The first part is so that it let's new players practice surgery without putting some helpless soul in perma-sleep. The second part is so I didn't make another button solely with the ability that marines can use it to spawn humans.
:cl:
add: Added a surgery practice area to marine Valhalla.
code: Modified the marine spawner buttons in xeno Valhalla to be usable by marines.
/:cl:
=> Adds a Valhalla surgery area, modifies the marine spawner xeno button.

code/game/objects/effects/effect_system/smoke.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm, code/modules/projectiles/ammo_types/xenos/gas_xenoammo.dm
Basically puts boiler alot closer to CM boiler now that we are starting to take down offscreens.
Zoom reduced to about miniscope range (4 tiles)
Opaque gas is back
Boiler gas radius reduced from 4 to 3 tile radius
Able to shoot within 5 tiles of yourself
Boiler was a lot less toxic without opaque gas but did lack the utility a smokescreen gave. The toxicity was mostly because you literally could not interact with boiler at sniper range, even with root. This makes boiler have a good more deal risk/reward as they are much, much closer to marines but have the smokescreen. Additionally no zoom windup as that felt quite arbitrary.
:cl:
balance: Boiler - Zoom reduced to about miniscope range (4 tiles)
balance: Boiler - Opaque gas is back
balance: Boiler - Boiler gas radius reduced from 4 to 3 …
=> Boiler Tweaks

code/datums/storage/subtypes/internal.dm
Engineering storage armor modules now can hold miner upgrades.
Engineering storage should be able to hold equipment useful to engineers, and it always seemed like an oversight that miner upgrades were not included in this.
:cl:
add: Engineering storage modules can now hold miner upgrades.
/:cl:
=> Engi storage holds miner upgrades

code/modules/reqs/supply.dm
If an export value of an item is 0 it won't be **DISPLAYED**
Further declutters the export history by removing items that are worthless in terms of export value. Important to note, that these items will still be logged for administrative purposes, just merely won't be sent to the ASRS interface to clutter it.
:cl:
qol: Req export history no longer displays worthless items
/:cl:
=> Further declutters the export history

code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm, code/datums/jobs/job/clf.dm, code/game/objects/items/explosives/bombvest.dm
cut down from 2 seconds to 0.5
current vest detonate time takes too long for hvh gameplay and how weak clf are
:cl:
balance: clf suicide vest detonates faster
/:cl:
=> CLF gets faster suicide vest detonate time
