code/modules/mob/living/carbon/human/life/handle_organs.dm
title
It doesn't make sense you fall over when sitting in a chair
:cl:
fix: You don't fall over from a broken leg if buckled anymore
/:cl:
=> You don't fall over from a broken leg if buckled anymore

code/modules/requisitions/supply_export.dm
yes
bad
:cl:
fix: You dont sell things for /list points anymore
/:cl:
=> Yet another export fix

code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
Fixes some loadouts not having half their gear. The update to freelancers recently broke it for campaign.
Having a gun is good
:cl:
fix: fixed some freelancer loadouts in campaign
/:cl:
=> Campaign Freelancer fix

code/datums/gamemodes/campaign/faction_stats.dm
I did a whoopsie, causing people returning to base instead of ghosting as intended.
:cl:
fix: fixed campaign mission end ghostise not working correctly
/:cl:
=> Campaign ghostise fix

code/datums/status_effects/sectoid.dm
Fixed a couple of bugs with mindmeld.
The trait wasn't being removed when mindmeld was.
In certain circumstances you could lose mindmeld and be debuffed past your base stats.
Fixes good.
:cl:
fix: fixed a couple of issues with mindmeld
/:cl:
=> Mindmeld fix

tgui/packages/tgui/interfaces/ColorMatrixEditor.tsx, tgui/packages/tgui/interfaces/MatrixMathTester.tsx
Two interfaces were still using context, which is not valid for React
Fixes CI
N/A nothing player facing
=> Fixes tgui CI issue

code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Fixes #14668
Funny shuffle bug bad.
:cl:
fix: fixed unrelenting force causing shuffle issues in certain directions
/:cl:
=> Unrelenting force fix

code/modules/clothing/modular_armor/attachments/storage.dm
Fixed a couple of storage exploits.
Exploit bad
:cl:
fix: fixed some storage exploits
/:cl:
=> Storage exploit fix

code/modules/admin/view_variables/topic.dm
VV topic fix
VV topic fix
:cl:
fix: VV topic fix
/:cl:
=> VV topic fix

code/game/objects/machinery/vending/vending_types.dm
Add larva to valhalla vendor
Added larva to valhalla NanotrasenMed Plus vendor
For people that want to try recipes that need larva jelly or to try out the process of making one
:cl:
qol: Add larva to valhalla vendor
/:cl:
=> Add larva embryo to Valhalla's vendor

code/modules/admin/view_variables/admin_delete.dm
Candy's killing our headmins is bad, or something.
:cl:
admin: Only headmins and above can delete clients
/:cl:
=> Stops a funny admin issue

code/__DEFINES/admin.dm, code/modules/admin/view_variables/debug_variables.dm
Lowercasify "Vars"
Should help
:cl:
code: Lowercasify "Vars"
/:cl:
=> Lowercasify "Vars"

code/modules/admin/admin_verbs.dm, code/modules/admin/tag.dm
move osay to admin and view tags to debug categories
this is better.
:cl:
admin: move osay to admin category and view tags to debug category
/:cl:
=> move osay and view tags

code/modules/reqs/supplypacks.dm
Title.
These are basically rockets that can be aimmoded and the gun firing has no windup. This just makes it unfair to fight since you'll just get staggerslowed to death, with it also doing pretty good damage.
:cl:
del: Removes the HE GL54 nades from req
/:cl:
=> Removes the HE GL54 nades from req

code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
fixes a spelling error in the message you get when making jelly
good spelling is good?
:cl:
spellcheck: fix typo in jelly message
/:cl:
=> fixes typo in jelly message

code/datums/jobs/job/other.dm, code/modules/clothing/glasses/glasses.dm, code/modules/clothing/glasses/hud.dm
Title, had to make the hud_type var support lists
Just a thing they're missing imo, huds are handy
:cl:
qol: Spatial agent glasses have all huds now
/:cl:
=> Spatial agent glasses have all huds now

code/datums/components/harvester.dm
Bicard no longer magically heals dead bodies, or robots.
Exploit bad.
:cl:
fix: Harvester bicard no longer heals dead bodies or robots
/:cl:
=> Harvester bicard fix

code/__HELPERS/game.dm
=> Removes trange()

code/__byond_version_compat.dm, code/controllers/globals.dm, dependencies.sh
=> Update byond version for ci; remove max compile version warnings.

_maps/modularmaps/EORG/cs_mansion.dmm, _maps/modularmaps/EORG/cs_militia.dmm, _maps/modularmaps/EORG/cs_office.dmm, _maps/modularmaps/EORG/de_inferno.dmm, _maps/modularmaps/EORG/de_nuke.dmm
Title.
This isn't a good look.
The stairs are busted, have needed fixed forever. This PR fixes them.
:cl:
fix: Fixed some improper stairs on the EORG maps.
/:cl:
=> Fixes some busted stairs in EORG maps

code/modules/clothing/glasses/hud.dm
Bug
Keeping huds when you shouldn't bad
:cl:
fix: Fixed an exploit related to hudglasses
/:cl:
=> Fix hud thing I forgor

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
this wasnt updating icon, someone should kill the beenhit var
:cl:
fix: Punching an APC as warrior should update the icon properly now
/:cl:
=> APC punch fix

code/datums/gamemodes/campaign/loadout_items.dm, code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm, code/datums/gamemodes/campaign/loadout_items/SOM/belt.dm, code/datums/gamemodes/campaign/loadout_items/SOM/ears.dm, code/datums/gamemodes/campaign/loadout_items/SOM/feet.dm, code/datums/gamemodes/campaign/loadout_items/SOM/gloves.dm, code/datums/gamemodes/campaign/loadout_items/SOM/head.dm, code/datums/gamemodes/campaign/loadout_items/SOM/pockets.dm, code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm, code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm, code/datums/gamemodes/campaign/loadout_items/SOM/uniform.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/ears.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/eyes.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/feet.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/gloves.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/head.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/mask.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/uniform.dm
After probably 30 ahelps from people that variously forgot to equip shoes, weapons or uniforms, I've now properly setup the default choices for all roles.
So if you're in a real hurry you can just press go instantly, and at the very least you shouldn't accidentally leave empty slots.
Naked ungas is bad for morale.
:cl:
qol: Campaign loadouts have default options selected
/:cl:
=> Campaign loadout defaults

code/modules/projectiles/guns/specialist.dm
I have no idea how this ever worked at all
Makes the gun work like it's supposed to
:cl:
fix: Fixes the AMR for real now
/:cl:
=> Hopefully actually fixes the AMR

strings/tips/marine.txt, strings/tips/meme.txt, strings/tips/xeno.txt
New year, new tips.
You know the drill, and so do I.
:cl: the TGMC community
spellcheck: 2024 tips update
/:cl:
=> 2024 tips update

code/datums/gamemodes/campaign/outfit_holder.dm
aylmao.
Defaults when actual items didn't work.
working is good.
:cl:
fix: fixed defaults in campaign loadouts
/:cl:
=> actually working defaults for campaign

tools/build/build.js
mirrors https://github.com/tgstation/tgstation/pull/80958
=> Wait 10s in TGS build for ESBuild to exit

code/modules/mob/dead/observer/observer.dm
bob
:cl:
fix: Ghosts actually bob up and down now 
/:cl:
=> Fixes the ghost bob animation

code/modules/mob/living/carbon/human/inventory.dm
Title. Funny old code
Bug bad
:cl:
fix: Fixed magharness keeping the item in your suit slot after you take the suit off
/:cl:
=> Fixes magharness keeping the item in your suit slot after you take the suit off

code/__DEFINES/dcs/signals.dm, code/_onclick/click.dm, code/datums/keybinding/carbon.dm, code/datums/keybinding/mob.dm, code/game/atoms/_atom.dm, code/game/objects/effects/acid_hole.dm, code/game/objects/effects/weeds.dm, code/game/objects/items/storage/storage.dm, code/game/objects/structures.dm, code/modules/clothing/modular_armor/attachments/storage.dm, strings/tips/marine.txt
Deletes specialclick (now just CTRL+Click)
Deletes examine keybind (now just shift+click to examine)
Fixes right clicking being used before abilities when abilities were selected.
un-fucks what has been fucked.
:cl:
fix: fixed a few click-related issues
/:cl:
=> Fixes certain click interactions

code/game/objects/machinery/vending/marine_vending.dm, code/modules/clothing/modular_armor/xenonauten.dm, code/modules/clothing/suits/marine_armor.dm
I CAN'T FUCKING SEE!!!
:cl:
add: suitlight to crasher body armor
/ 🆑
=> suitlights to crasher armor

code/_onclick/click.dm
Fix spitslash on right click
bugfix
:cl:
fix: Spit slash RMB works again
/:cl:
=> Fix spitslash on right click

code/game/data_huds.dm, code/game/objects/items/defibrillator.dm, code/game/objects/items/radio/headset.dm, code/modules/mob/living/carbon/human/life.dm
So. Turns out that while I did correctly discern & fix the two issues I mentioned in a previous PR..
Disconnecting while ghosted ALSO DNRd you because get_ghost at the moment only returns a ghost if it has a client.
This adjusts that by adding a var to the proc that makes it return the ghost even if it has no client if true.
Additionally adjusts uses of get_ghost where it recognizing disconnected but not DNR ghosts is favorable (mostly defib huds and said DNR case).
Lastly, this also goes into defib code and adjusts conditions for various messages because some were plain wrong and others just have their conditions set kind of badly (it still fails for disconnected targets but should at least give you a different message).
Please TM this first because it is torture to test thoroughly.
Fix …
=> Even more DNR (& defib) fixes.

code/modules/clothing/modular_armor/xenonauten.dm
god help me
makes it not a downgraded flak vest ~~also stops the voices~~
:cl:
add: flak stats to crasher
/ 🆑
=> crasher with flak stats

code/modules/clothing/suits/marine_armor.dm, code/modules/projectiles/gun_helpers.dm, code/modules/projectiles/guns/specialist.dm
Funny flag change wasn't done properly.
Working stuff good.
:cl:
fix: fixed miniguns and SADAR being unwieldable
/:cl:
=> Fix autobalance, miniguns and sadar

code/datums/jobs/job/special_forces.dm
i forgor to give med skill
he's a medic with no med skill
:cl:
add: medskill to speccops
/:cl
=> gives specops medic a med skill

code/_globalvars/lists/mobs.dm, code/modules/mob/living/carbon/xenomorph/evolution.dm
TM before merge so I can keep updating the PR as bugs come
Fix good
:cl:
fix: Fixes various bugs with evolution
/:cl:
=> Evolution change hot fix

code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Small tweaks so weapon X regens health and sunder faster, considering it has no pheros.
Agonisingly slow healing is annoying.
:cl:
balance: Weapon X in campaign mode heals faster
/:cl:
=> Campaign weapon x tweaks

code/modules/projectiles/ammo_datums.dm
Reduced base deflagrate mult from 1 to 0.9 (i.e. 10% less likely).
Reduced volkite stagger from 1 second to 0.5 seconds
Slight nudge to make volkite less spicy in some situations.
:cl:
balance: Volkite deflagrate chance reduced by 10% and stagger reduced from 1 sec to 0.5 sec
/:cl:
=> Small volkite nerf

code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm, code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
Adjust/add points cost to various items in campaign.
Fairer prices.
:cl:
balance: Adjusted the points cost of some items in campaign
/:cl:
=> Various campaign item points tweaks

code/game/objects/structures/campaign_structures/capture_objectives.dm
Me add towers to Big Red.
Me forget to add the mission to list.
:cl:
fix: Sensor towers on BR will show up correctly during Mech War missions
/:cl:
=> Mech war tower fix

code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/head.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm, code/datums/gamemodes/campaign/perks.dm, code/modules/clothing/modular_armor/som.dm, code/modules/clothing/modular_armor/xenonauten.dm
Fixes #14966
Fixes some shield overclock loadouts being bugged for engies/medics (and SOM in general)
Fixes good.
:cl:
fix: fixed some campaign loadout bugs with overclocked shields and TGMC FC options
/:cl:
=> campaign loadout fixes

code/datums/gamemodes/campaign/missions/airbase_raid.dm, code/datums/gamemodes/campaign/missions/supply_raid.dm
IR dum.
BSOD bad.
:cl:
fix: fixed a BSOD in campaign
/:cl:
=> Fix campaign BSOD

code/modules/clothing/suits/marine_armor.dm
title
they will not support
:cl:
add: one word "drone" to "support"
/:cl:
=> fixes icon error with specops support

code/modules/projectiles/gun_system.dm, code/modules/projectiles/guns/grenade_launchers.dm, code/modules/projectiles/guns/specialist.dm
Properly sets some gun skill types, mainly for old spec weapons.
makes a couple of skill check stuff more consistant.
minor improvements
:cl:
fix: fixed some minor skill issues on some weapons
/:cl:
=> Misc skill stuff

code/__DEFINES/colors.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm, code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/magazines/rifles.dm
20mm goes pew pew
Also adds acid smoke 20mm nades.
Support weapon option.
:cl:
add: Added the GL-54 to normal marines in campaign
/:cl:
=> GL-54 campaign loadout

code/modules/mob/living/carbon/human/emote.dm
Removes this bad and unnecessary part of the game.
Remove unneeded bloat.
:cl:
del: Removed the jump emote
/:cl:
=> Removes jumping

code/game/objects/items/motion_detector.dm, code/modules/projectiles/gun_system.dm
I accidentally broke it with holstering other weapons the sensor wasn't attached too.
Bug bad.
:cl:
fix: Fixed tac sensor turning off when you holster a different weapon
/:cl:
=> Motion sensor fix again

code/modules/projectiles/guns/specialist.dm
Fixes the recoil on some spec weapons, and removes a few unneeded var definitions
Funny big recoil unintended
:cl:
fix: fixed the recoil on some weapons such as the BR-8
/:cl:
=> Recoil fixes

code/_onclick/click.dm, code/datums/keybinding/mob.dm
Removes the keybind for "Examinate"
Puts it in our click code chain instead.
Keybinds are weird, they override our click code chain.
So if you have this keybinded to shift (like default), then it fucks with other shift clicks.
:cl:
del: Deletes "Examinate" Keybind
/:cl:
=> Deletes examinate keybind.

code/_onclick/hud/fullscreen.dm
Haha funny path copypasta moment. Also makes the plane line just shared across the fullscreen overlays. 
Bug bad.
:cl:
fix: Vali necro overlay should show up again
code: The fullscreen overlays now all actually share the proper plane
/:cl:
=> Some fullscreen overlay fixes (this fixes the vali necro overlay)

code/datums/components/reequip.dm, code/modules/projectiles/gun_system.dm
Reverts tgstation/TerraGov-Marine-Corps#14826
TM only, mag harness still randomly fails without the delay for ~2 weeks. UnTM when it is fixed
=> Revert "Fix flamer back tank disconnecting with magharness"

code/modules/admin/panels/player_panel.dm
Title.
Consistency good.
:cl:
add: Adds Baneling to admin player panel tab.
/:cl:
=> Adds Baneling to Admin  Player Panel

code/game/objects/machinery/computer/buildandrepair.dm, code/game/objects/machinery/miner.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm, code/modules/power/fusion_engine.dm, code/modules/power/groundmap_geothermal.dm, code/modules/recycling/disposal-construction.dm, code/modules/recycling/disposal.dm, code/modules/recycling/sortingmachinery.dm, code/modules/shuttle/navigation_computer.dm, code/modules/vehicles/multitile/cm_armored.dm
Some of these seem to have been missed I presume.
Replaces .../proc/proc_name() with PROC_REF(proc_name)
code improvement
:cl:
code: extra_checks use PROC_REF() for their callbacks
/:cl:
=> makes sure extra_checks all use proc_ref

code/game/objects/items/marine_gear.dm
title
bugfix
:cl:
fix: Chicken protein bars no longer runtime
/:cl:
=> chicken protein bars no longer runtime when you eat a different type of protein bar

code/modules/shuttle/marine_dropship.dm
Topic is so fucking dumb, holy shit please move this to a tgui interface.
Fix the ability to do the following:
A: Capture the alamo remotely
B: Capture the alamo from another z-level
C: Capture the alamo while dead
D: Capture the alamo even with enough marines groundside
E: Any combination of the above
Bruh.
:cl:
fix: fixed various exploits with capturing the alamo
/:cl:
=> Capture exploit fix

code/modules/mob/living/carbon/xenomorph/evolution.dm
Exploit bad.
:cl:
fix: Fixes a certain exploit with caste swap and regress
/:cl:
=> Caste swap / regress exploit fix

code/__DEFINES/dcs/signals.dm, code/datums/elements/footstep.dm, code/game/objects/effects/temporary_visuals/explosions.dm, code/game/objects/structures/patrol_points.dm
Some visual additions to rappel effects in HvH.
You now visually drop down, mechs make a little dust kick up.
https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/52c149e1-1df0-425e-a5d9-0756111ed3a5
https://github.com/tgstation/TerraGov-Marine-Corps/assets/7869430/a3df7289-8d97-44b8-98b2-188900ad8ab7
Visuals cool.
:cl:
add: Improved rappel effects in HvH
/:cl:
=> Rappel effect+

_maps/map_files/Arachne/TGS_Arachne.dmm
Fixes medbay disposals. Prior pipework used a flipped junction where there should have been a downward-facing Y-junction.
Bugfixes good.
:cl:
fix: Fixed Arachne's Medbay Disposal.
/:cl:
=> Arachne Medbay Disposals Fix

.gitignore, code/controllers/subsystem/server_maint.dm, code/modules/asset_cache/asset_list.dm, config/config.txt
Ports https://github.com/tgstation/tgstation/pull/81433
MSO said is gud. Stops cache from clogging up every 5 minutes, and stop TTS killing things. Or something.
=> Moves inter-round caches to cache/. Deletes tmp/ between rounds

code/game/objects/items/storage/belt.dm
Fix martini belt not being clickable
Bugfix
:cl:
fix: Fix not being able to click martini belt
/:cl:
=> Fix martini belt not being clickable

code/datums/gamemodes/campaign.dm
I fucked up a few mults, leading to some hilarious results with mass mechs.
12 mechs is not good for balance
:cl:
fix: fixed some campaign autobalance logic
/:cl:
=> Campaign autowalance fix

code/game/objects/items/motion_detector.dm
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14895
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14895
Bugfix
:cl:
fix: Fixes a bug allowing you to have tac sensor active permanently
/:cl:
=> Fix an exploit with tac sensor being active permanently

code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm, code/datums/gamemodes/campaign/loadout_items/SOM/belt.dm, code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm
Updates the weapon descriptions in campaign.
They now specify the attachments they have, and mainly provides relevant information about their performance/use.
Also a minor change to make the default belt option for smartgunners an actual valid choice for the default gun selection.
More informative weapon descriptions.
Previously they were just the actual gun descriptions, which had a lot of useless information.
:cl:
qol: Campaign: Updated weapon descriptions in the loadout UI
/:cl:
=> Campaign weapon description updates

code/__DEFINES/conflict.dm, code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/carbon_defines.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/living/carbon/xenomorph/update_icons.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/projectiles/guns/specialist.dm
Merges xeno and human overlay lists together into one. should be no player facing changes.
cleaner code potentially, all defines in one place.
:cl:
code: merged overlay defines into one layer list
/:cl:
=> merge xenomorph and human overlay layers together

code/__DEFINES/loadout.dm, code/datums/loadout/loadout_helper.dm
Fixes not being able to vend job-appropriate gear in valhalla.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14598
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14636
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14739
Bugfix
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14598
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14636
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14739
:cl:
fix: Loadouts work in Valhalla now
/:cl:
=> Fix job-exclusive loadouts in Valhalla.

code/__DEFINES/combat.dm, code/datums/components/shield.dm, code/game/objects/items/weapons/energy.dm, code/game/objects/items/weapons/shields.dm, code/game/objects/items/weapons/twohanded.dm
Unfugs some cursed shield code.
There was lots of weird stuff going on that wasn't working correctly, like multiple armor interactions that shouldn't be happening (hard armour making shield WORSE at absorbing damage, for one), so fixed a few things. Notably, shields will take more damage from bullets.
Better/working code.
:cl:
fix: fixed some wonky shield behavior
code: Cleaned up some shield code
/:cl:
=> Shield code improvements

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
fucked up
:cl:
fix: Fixed the xeno ability going thru wall bug fix
/:cl:
=> Fix sanity fix

code/modules/shuttle/marine_dropship.dm, tgui/packages/tgui/interfaces/MarineDropship.jsx
The ship AI can no longer hijack/capture the Alamo
Changes check from ishuman() to isxeno()
Lol, lmao even
Bugfix
:cl:
fix: The ship AI can no longer hijack/capture the Alamo
/:cl:
=> The ship AI can no longer hijack/capture the Alamo

code/game/objects/items/devices/tablets.dm
There was some special handling missing for non-hardcoded squads
:cl:
fix: Fixes custom squad tablets not working
/:cl:
=> Fixes custom squad tablets

code/game/objects/machinery/overwatch.dm
Yanderedev tier code that people walked around instead of fixing
:cl:
fix: Fix Main console not being able to overwatch custom squads
/:cl:
=> Fix Main console not being able to overwatch custom squads

code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Grants hunter .1 speed.
Helps hunter be a bit more mobile and easier to combat aim mode balls. Don't think damage needs a buff with AP being added.
:cl:
balance: Increases hunter speed to -1.5
/:cl:
=> Hunter Buff

code/__DEFINES/skills.dm
I forgot the seconds define. Honk.
0.2 second bonus is not great.
:cl:
fix: fixed heightened stamina skill not properly lowering the stam regen delay
/:cl:
=> Stamina skill fix

code/game/turfs/walls/r_wall.dm
rwalls have 75 armor, 5000 hp
Makes Rwalls tougher to normal bullets.
:cl:
balance: Reinforced Walls have 75 laser/bullet armor and 5000 HP.
/:cl:
=> reinforced wall change

code/modules/admin/verbs/adminhelp.dm
Requested by an admin.
Requested by an admin.
:cl:
admin: Added message for recipient when a ticket is (un)marked, closed, or tiered.
/:cl:
=> Adds message for recipient when a ticket is (un)marked, closed, or tiered.

code/modules/vehicles/mecha/equipment/weapons/weapons.dm
=> Minor mech iff code improvement

code/modules/mob/living/carbon/xenomorph/death.dm
Fixes #15181
Also fixed some coder brand code in the proc above.
:cl:
fix: fixed xeno plasma hud getting stuck on death
/:cl:
=> fix plasma hud sticking on death

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
lorem ipsum
I am not testing this :)
Fix man good
:cl:
fix: The new larva queue check should no longer be broken.
/:cl:
=> Fixes larva spawns probably

code/modules/recycling/conveyor2.dm
Fixes conveyors not working on tiles with anchored objectives.
Whoops.
:cl:
fix: fixed conveyors not working in some cases
/:cl:
=> Conveyor fix

code/__DEFINES/dcs/signals.dm, code/game/atoms/_atom.dm
add emp signal
I need this
:cl:
code: add emp signal
/:cl:
=> add emp signal

code/datums/gamemodes/campaign/rewards/reserves.dm
I forgot to update this one to ckey when I changed how the deathtimer list worked.
:cl:
fix: Campaign: Fixed the tactical reserve asset
/:cl:
=> Fixes tactical reserve asset

code/_onclick/click.dm
Moves the directional attack/ranged attack proc so its not being called when it shouldn't.
Slight perf improvement, may or may not fix bugs, I unno.
:cl:
code: Tiny tweak to directional attack code
/:cl:
=> direction attack tweak

code/modules/reagents/reactions/medical.dm
The following chems now make 1u more per reaction (using lemoline):
- Meralyne
- Dermaline
- Ryetalyn
- Synaptizine
- Hyronalin
It was dumb that mixing 40u of chems would give 30u of reagent.
I really dislike lemolock, but if it remains in, I think it actually adding to the final recipe is fair.
:cl:
balance: Some lemolocked chems have a bit more generous reactions.
/:cl:
=> Some recipes which use 1u of Lemoline now add to the final volume

code/_onclick/hud/screen_objects/menu_text_objects.dm, code/modules/mob/new_player/new_player.dm
What it says on the tin
Misleading title leading players to believe they could see the whole hive list
:cl:
spellcheck: Changed "View Hive" lobby button to "View Hive Leaders"
/:cl:
=> Changes "View Hive" lobby button to "View Hive Leaders"

code/datums/elements/directional_attack.dm
This was causing an infinite loop
bad
:cl:
fix: The server should no longer die if you try to directional attack diagonally thru a wall
/:cl:
=> Directional attack adjacency sanity

code/modules/vehicles/armored/armored_weapons.dm, code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Wahhh
:cl:
fix: tanks and mechs have correct bullet movement speed now
/:cl:
=> Fixes vehicle shooting speed

code/datums/emergency_calls/retired.dm, code/datums/jobs/job/retired.dm, code/modules/projectiles/gun_system.dm
The leader had legs, bad.
This was the intention, but I forgor
:cl:
fix: Retired ERT leader doesn't have legs anymore as was intended
/:cl:
=> Fixes some unintended retired ert things

code/modules/projectiles/ammo_datums.dm, code/modules/vehicles/armored/_multitile.dm, code/modules/vehicles/armored/ammo_magazine.dm
basically straight buffs, blame kuro
:cl:
balance: buffed tank
/:cl:
=> Tank balance changes

code/modules/vehicles/armored/__armored.dm, code/modules/vehicles/armored/interiors/breech.dm
:cl:
fix: Fixes tank reload not updating UI
/:cl:
=> Fixes tank reload not updating UI

tgui/packages/tgui/interfaces/Hypospray.tsx
add <Section> to hypospray UI
looks better
no cl
=> add <Section> to hypospray UI

code/modules/projectiles/guns/mounted.dm
deletes the thing in the agls description about it not being able to rotate because it's wrong
closes #14058
:cl:
spellcheck: fixed AGLS description
/:cl:
=> deletes old part of agls description

code/__DEFINES/mobs.dm, code/game/data_huds.dm, code/modules/admin/fun_verbs.dm, code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm, code/modules/mob/living/carbon/xenomorph/castes/behemoth/behemoth.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/bull.dm, code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm, code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm, code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm, code/modules/mob/living/carbon/xenomorph/death.dm, code/modules/mob/living/carbon/xenomorph/evolution.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/mob/living/carbon/xenomorph/life.dm, code/modules/mob/living/carbon/xenomorph/say.dm, code/modules/mob/living/carbon/xenomorph/update_icons.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm, code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Removed some more xeno mob vars/turned some into flags.
I haven't touched any caste related stuff yet.
Better code.
:cl:
code: Cleaned up some xeno code
/:cl:
=> Clean up some more xeno code

code/game/objects/structures/supplypod.dm, code/modules/admin/verbs/centcom_podlauncher.dm
Fix admin pods being invisible.
Fix custom pods not working at all.
Fixes #14761
:cl:
fix: fixed admin pods
/:cl:
=> Admin pod fixes

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
ermm
I think github might get mad
:cl:
spellcheck: Fixed a typo in bulwark description
/:cl:
=> Fixes typo in bulwark description

code/controllers/subsystem/minimaps.dm, code/datums/interior/_interior.dm, code/datums/interior/interior_tank.dm
locator looked like it was stuck but that seems more like a minimaps issue
:cl:
add: Minimaps now work in the tank
/:cl:
=> (Mostly) fixes tank minimaps

code/modules/vehicles/armored/__armored.dm
stuff like removing guns etc
:cl:
add: restricted things like removing tank gun to tank crew only
/:cl:
=> Stops non tank users from touching tank

code/game/objects/machinery/vending/marine_vending.dm
Title
Allows more testing for players.
:cl:
add: Adds AMR incen and flak ammo to valhalla.
add: Adds TL Flak rounds to valhalla.
add: Adds cleaner nades to valhalla.
/:cl:
=> Adds AMR alternative ammo, TL flak ammo and cleaner nades to valhalla.

code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Wrong arg
:cl:
fix: fixed bemo rock throwing
/:cl:
=> Fix bemo throw

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Adds weeds outside of magmoor LZs, a few buildings, and the southwest cave.
Alleviates busywork for xenos, consistency with other maps.
:cl:
balance: Preweeded Magmoor
/:cl:
=> Preweeds Magmoor

_maps/map_files/generic/Admin_Level.dmm
berry simple, #14567 consolidated valhalla into 3 areas using regex replace, this just forces SDMM to do the busywork of parsing and removing any redundant areas.
because sdmm hasn't been forced to save and clean up the valhalla map since the area consolidation, anyone who tries to PR anything editing the physical map will get hit with some random 7,000 line changes. this makes it so that won't happen anymore by putting all these deletions in one little place (this PR), so reviewers can make more sense of what changes people are actually making later on
no player-facing changes
=> valhalla area compression the sequel

code/modules/projectiles/guns/energy.dm
Make the laspistol and the serpenta fully automatic.
No longer needing to give yourself carpal tunnel to use energy pistols.
We gave that to the other pistols so no reason to leave those out.
:cl:
balance: laspistol and serpenta are now full auto
/:cl:
=> Give laspistol and serpenta full auto

code/game/objects/machinery/nuclearbomb.dm
The AI used to be able to remote to the nuke, but that got changed in the TGUI pr. 
This PR brings it back. Now AI's can know the timer again. 
Fixes good
:cl:
fix: The AI can interact with the nuke again
/:cl:
=> Allow the AI to interact with the nuke again

code/datums/fire_support.dm
Fixed a few portraits showing the wrong person when calling in firesupport in campaign.
:cl:
fix: Campaign: Fixed a few mismatched portraits when calling in firesupport
/:cl:
=> Portrait fixes

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Fixes #15354
Cross dimensional reee is bad.
:cl:
fix: Queen screech will no longer go through z-levels
/:cl:
=> Queen screech fix

strings/tips/meta.txt
Adds say tech hint to meta.txt
Democratise the power of say tech, power to the people, everyone should know how to underline their text and weaponise cringe
:cl:
add: Adds say tech hints
/:cl:
=> Democratises say tech

code/controllers/subsystem/persistence.dm, code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/structures/crates_lockers/largecrate_supplies.dm
For the love of god stop adding guns that deploy on init directly to vendors.
Fixes #14095
Fixes #14133
Fixes #15364
Fixes #15169
Bugged heavy railcannon is funny but bad.
:cl:
fix: fixed flak guns being vended incorrectly
/:cl:
=> Flak gun fixes

code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm, code/modules/projectiles/ammo_datums.dm
Puts the deflag chance of the volkite charger back to 1 from 0.9.
Reduced the loadout cost of some volkite options.
Charger underperforms a little bit.
Some options are a bit expensive for what they actually give.
:cl:
balance: Increased volkite charger deflag chance slightly
balance: Campaign: Reduced the loadout cost of some volkite weapons
/:cl:
=> Minor volkite tweaks

code/__DEFINES/vending.dm, code/game/objects/machinery/bots/roomba.dm, code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/machinery/vending/vending.dm, tgmc.dme
Roomba tries to restock elligible items instead of just sending everything to cryo storage.
QOL. A lot better than just having a bunch of crap in cryo because people leave random crap from loadouts on the floor all over prep.
:cl:
qol: Roomba tries to restock elligible items
/:cl:
=> Roomba tries to restock elligible items

_maps/map_files/gelida_iv/gelida_iv.dmm
Closes #15396
I don't believe it was intended for one APC to power multiple intel computers. If it was then Grayson can close this.
:cl:
del: Removed duplicate intel computers on Gelida IV
/:cl:
=> Removes multiple intel computers in same areas on Gelida IV

code/datums/jobs/job/shipside.dm, code/modules/reqs/supplypacks.dm
As the title says, this Pr adds the supply tablet to req. 
No more running back and forth when you wake up late and someone took it, and didn't put it back
:cl:
qol: Added the ASRS supply tablet to req
/:cl:
=> Add the ASRS supply tablet to req

code/modules/projectiles/sentries.dm
Fixes #15403
Sentries will now shoot targets on the same tile as them.
Fix as it turns out the sentry actually should be able to do this (in most cases) but it just runtimes.
Cleaned up the code as was kinda of cursed with pointless/duplicate/inefficient code.
Notably, energy weapon turrets will now properly shoot through glass and the like.
ignored_terrains is cursed and needs to be replaced, but I'll leave that for another pr.
Bug fix.
Better code.
:cl:
fix: fixed sentries being unable to shoot targets on their own turf
fix: Fixed energy sentries not shooting through glass
/:cl:
=> Sentry fix and code improvements

tgui/packages/tgui/interfaces/Mecha/index.tsx
Mech stat UI has a jacked up default UI size that means every time you open it you have to resize it to do anything.
This is god awful.
:cl:
fix: fixed mech UI size
/:cl:
=> Mech UI size fix

_maps/map_files/Theseus/TGS_Theseus.dmm
Theseus edits missed a spot
Space tile shipside bad
:cl:
fix: Fills in space tile on Theseus
/:cl:
=> Fills in theseus space tile

code/modules/reagents/reagents/medical.dm, code/modules/reagents/reagents/toxin.dm
No reason to really be hidden from the player, just hurts newer players in the long run for no reason at all. 
:cl:
qol: The toxin reagent from QC+, Peri+ and Nanoblood now shows on medical scanners.
/:cl:
=> The toxin reagent from QC+, Peri+ and Nanoblood shows on scanners

_maps/map_files/gelida_iv/gelida_iv.dmm
Fixes a few instance of individual tiles of deep caves on the wrong spots on Gelida, as well as a few spots where cave areas cut into rocks.
Radio bugfix for a few tiles and consistency
:cl:
fix: Fixed a few misplaced area tiles on Gelida caves
/:cl:
=> Fixes a few stray cave areas on Gelida

code/modules/reqs/supplypacks.dm
What it says on the tin. Tivi request for tank to function properly.
=> Tank ammo in req

code/__DEFINES/cooldowns.dm, code/game/objects/items/whistle.dm
https://github.com/tgstation/TerraGov-Marine-Corps/assets/20828943/9353a204-8f20-4a8b-8325-24287f540243
It's FUN. Also code improvement.
:cl:
add: Whistle makes every human in range do the *warcry emote
/:cl:
=> Whistle now makes every human in range warcry

_maps/map_files/Sulaco/TGS_Sulaco.dmm
What it says on the tin. PoS already does this.
Additionally, adds the pipe Captain gets on other maps. Without it, he will cease to function!!!
Less roundstart tedium.
:cl:
qol: Sulaco generators and SMES are now preset
/:cl:
=> Presets Sulaco generators and SMES

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
people want req and TC fix
:cl:
fix: PoS req and tc
/:cl:
=> hotfix for PoS req and tc

code/game/objects/objs.dm
Welding repair amount scale off engi skill, different skill level should have different effect.
Make use of higher engi skill
:cl:
balance: Welder repair amount scale off Engi skill.
/:cl:
=> Welding repair amount scale off engi skill

code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
Womp womp
:cl:
fix: ACs can no longer use mech console
/:cl:
=> ACs can no longer use mech console

code/game/objects/structures/droppod.dm, code/game/objects/structures/patrol_points.dm
Add a little line to the desc of deploy points and mech pods explaining how mechs can use them.
Instructions good.
:cl:
qol: Campaign: Mech pods and deploy point descriptions explain how mechs can use them
/:cl:
=> Deployment desc update

code/datums/gamemodes/campaign/faction_stats.dm, code/modules/mob/mob.dm
Minor runtime + removed a trace thats not needed as that can happen intentionally.
:cl:
code: Fixed a minor runtime and removed an unneeded stack trace
/:cl:
=> Ghost runtime fix

code/modules/clothing/suits/labcoat.dm
title
we have the icon file and i think it's one of the better-looking jackets and would like to enable it in the synth vendor
:cl:
add: adds the paramedic labcoat
/:cl:
=> adds paramedic labcoat

code/game/objects/machinery/vending/marine_vending.dm
see title
yes, I know valhalla is fullbright, but dagger asked me to. I'll bring shadow to valhalla some other day.
walhalla completeness, Dagger promised me a hug if I pr this
:cl:
add: Adds night vision goggles to valhalla
/:cl:
=> Adds new night vision goggles to valhalla vendor

docs/faction-design.md
Updated the faction comparison docs for 2024, added comparison tables for ease-of-use, and more info for combat tactics and other aspects.
To know how to balance the game it's essential for accurately describe it's current state. 
:cl:
code: Updated faction comparison docs.
/:cl:
=> Changed faction comparison docs into multiple tables, added more sections

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Just a small AI expansion
AI uses evasion when running away at low hp
:cl:
add: AI can use evasion
/:cl:
=> AI can use evasion

code/modules/ai/ai_behaviors/ai_behavior.dm, code/modules/ai/ai_behaviors/xeno/xeno.dm, code/modules/ai/presets/xeno_presets.dm
Title
These usually shouldnt be suicidal
:cl:
add: Nymphs and non-minion AI will no longer be suicidal
/:cl:
=> Nymphs and non-minion AI will no longer be suicidal

code/datums/jobs/job/marines.dm
Title
Smartgunners aren't limited to SG-29 anymore.
:cl:
fix: update smartgunner's job description to present sg better in 2024
/:cl:
=> update smartgunner's job description

code/game/objects/items/pamphlets.dm
Prevents stacking pamphlets
:cl:
fix: Pamphlets now have the ability to prevent being stacked
/:cl:
=> Prevents stacking pamphlets

code/__DEFINES/jobs.dm, code/datums/gamemodes/_game_mode.dm, code/datums/jobs/job/job.dm, code/datums/jobs/job/marines.dm, code/datums/jobs/job/shipside.dm
Wuh oh
:cl:
add: Tank has been enabled
/:cl:
=> Enables Assault Crewmen

code/modules/vehicles/armored/armored_weapons.dm
Kuro said
:cl:
balance: LTA-AP spread decreased
/:cl:
=> LTA-AP spread decrease

code/datums/jobs/job/shipside.dm
They get one each
:cl:
add: Gives assault crewmen loader pamphlets
/:cl:
=> Gives assault crewmen loader pamphlets

_maps/map_files/DaedalusPrison/DaedalusPrison.dmm
Fix https://github.com/tgstation/TerraGov-Marine-Corps/issues/15595
I had to chop a little space south, but that's about all the character chance. No space tiles, as far as I see. 
Tank fits without PC
:cl:
fix:  Tank is no longer stuck in Daedalus LZ
/:cl:
=> Move the daedalus lz north 1 tile and make space for tank south

code/game/objects/machinery/hologram.dm, code/game/objects/machinery/overwatch.dm, code/modules/admin/server_verbs.dm
Fix : https://github.com/tgstation/TerraGov-Marine-Corps/issues/13706
Also made the reload admins button default to no, and removed an useless comment in the AI code. 
I did test it as AI and as an human
Fixes good
:cl:
fix: fixed AI's not being able to use the overwatch camera jump
code: Removed useless comment in the AI hologram code
admin: Made the Reload Admins button default to No
/:cl:
=> Fixes the overwatch jump camera button not working for the AI + small fixes

code/modules/mob/living/blood.dm, code/modules/surgery/generic.dm
Fixes surgery blood loss occuring when bleeders are clamped
Fixes being able to clamp infinitely
:cl:
fix: Fixes surgery blood loss occuring when bleeders are clamped
fix: Fixes being able to clamp bleeders infinitely
/:cl:
=> Fixes clamp bleeders surgery step

code/modules/projectiles/projectile.dm
Stop xeno turret FF.
:cl:
fix: fixed xeno turrets causing FF
/:cl:
=> Xeno turret fix

code/modules/factory/parts.dm, code/modules/factory/unboxer.dm, code/modules/reqs/supplypacks.dm
Title.
Reqtorio was missing the alternate mags for scout rifles.
More stuff to reqtorio fun.
:cl:
add: Adds alternate scout rifle magazines to reqtorio
/:cl:
=> Adds alternate Scout Rifle magazines to reqtorio.

_maps/bigred_v2.json
:cl:
fix: Big Red is now an actual desert for map variants
/:cl:
=> BR is now an actual desert for map variants

code/controllers/subsystem/monitor.dm, code/controllers/subsystem/silo.dm
Removes the stalemate system
Ruins more games than it fixes. For reference this is a image after 10 marines just had wiped: 
:cl:
del: Removes the stalemate system
/:cl:
=> Stalemate removal

code/__DEFINES/conflict.dm, code/modules/clothing/modular_armor/attachments/modules.dm, code/modules/clothing/modular_armor/combat_robot.dm, code/modules/clothing/modular_armor/jaeger.dm, code/modules/clothing/modular_armor/xenonauten.dm
Lumi says it is better readability, so here it is.
:cl:
code: Robot, non-modular jaegar and xenonauten use armor defines
/:cl:
=> Robot, non-modular jaegar and xenonauten use armor defines

code/modules/screen_alert/command_alert.dm
Fixes #15659
:cl:
fix: fixes another order exploit
/:cl:
=> Fix other order exploit

code/datums/jobs/job/fallen.dm
Yes.
This messes fixes directional attacks not working on the dummies you spawn in.
:cl:
fix: Valhalla xenos can use directional attacks on the puppets they spawn now
/:cl:
=> Valhalla xenos are of the xeno faction

tgui/packages/tgui/interfaces/MarineSelector.jsx
Vendors show points costs again.
:cl:
fix: fixed vendors not showing points costs
/:cl:
=> vendor UI fix

code/__DEFINES/dcs/signals.dm, code/datums/keybinding/human.dm, code/modules/vehicles/armored/armored_actions.dm
Title
I like keybinds.
:cl:
add: keybind for vehicle honk
qol: keybind for vehicle honk
/:cl:
=> Make keybind for vehicle honk

code/modules/mob/living/carbon/xenomorph/update_icons.dm
Fixes xeno fire overlays being fucky, sometimes layering under the xeno, or not immediately being visible after ignition.
:cl:
fix: fixed some visua issues with xeno fire overlays
/:cl:
=> Xeno fire overlay fix

code/game/objects/structures/dropship_equipment.dm
Fixes the sentry deploy system being offset incorrectly.
:cl:
fix: fixed a visual offset issue with sentry deployment systems
/:cl:
=> Sentry deployer offset

code/game/objects/structures/dropship_equipment.dm, code/modules/shuttle/marine_dropship.dm
Fixes #15690
:cl:
fix: fixed an alamo runtime on non hvx gamemodes
/:cl:
=> Alamo runtime fix 

code/modules/organs/organ_objects.dm
Fixes #15666
:cl:
fix: Stray organs will no longer clang loudly
/:cl:
=> Organ clang fix

code/game/atoms/atom_movable.dm, code/modules/vehicles/_hitbox.dm
Fixes #15698
Fixes mobs randomly getting teleported to tanks and other such shenanigans (or should, at least).
Fixes mobs 'falling off' the back of a vehicle but still getting moved along with it.
:cl:
fix: fixed some issues with mobs riding vehicles
/:cl:
=> vehicle fixes

code/__DEFINES/crafting.dm, code/datums/components/crafting/_recipes.dm, code/datums/components/crafting/crafting.dm, code/game/objects/items/stacks/sandbags.dm, code/game/objects/items/stacks/sheets/glass.dm, code/game/objects/items/stacks/sheets/mineral.dm, code/game/objects/items/stacks/sheets/sheet_types.dm, code/game/objects/items/stacks/stack.dm, code/game/objects/items/stacks/stack_recipe.dm, code/game/objects/structures/barricade.dm
Gonna have to port this back to TG:
- Fix crafting ignoring most checks
- Adds engineering skill check to crafting times (for things that require it)
bugfix
:cl:
fix: Fix crafting ignoring construction checks
/:cl:
=> fix crafting ignoring most checks

_maps/interiors/apc_medical.dmm, _maps/interiors/apc_transport.dmm
Title
:cl:
fix: fixed APC comms cutting out sometimes
/:cl:
=> Fixes APC having no invisible comm relay

code/game/objects/items/pamphlets.dm
Forgot to set the size 
:cl:
fix: ACs will get loader phamplets correctly
/:cl:
=> Fixes loader phamplets not spawning/size

tools/ci/od_lints.dm
No longer a pragma but a proper error or whatever
=> Fixes removed pragma

code/__DEFINES/is_helpers.dm, code/game/objects/items/power_cells.dm, code/game/objects/items/weapons/misc.dm, code/modules/projectiles/gun_helpers.dm
Fix powerpacks double reloading
Closes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/15729
bugfix
:cl:
fix: Fix powerpacks double reloading
/:cl:
=> Fix powerpacks double reloading

code/game/objects/machinery/vending/marine_vending.dm
beanbap
beans are very healthy and good for you :)
:cl:
add: Adds beanbag slugs to valhalla
/:cl:
=> Adds beanbag slug to valhalla vendor

code/modules/projectiles/ammunition.dm
=> Blank ammo fix

code/modules/projectiles/ammunition.dm, code/modules/vehicles/armored/__armored.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale.dm, code/modules/vehicles/mecha/mecha_mob_interaction.dm, code/modules/vehicles/sealed.dm
Update the do_after so you can ACTUALLY put corpses into vehicles as intended.
:cl:
fix: Putting corpses into vehicles actually works now
/:cl:
=> Vehicle corpse fix

code/game/objects/structures/crates_lockers/closets.dm
Fixes some exploits with closets.
Specifically this limits all structures from going into closets, but I couldn't think of any that have any particular reason why they should fit.
Exploit bad.
:cl:
fix: fixed an exploit with closets
/:cl:
=> Closet exploit

code/datums/elements/debris.dm, code/modules/projectiles/projectile.dm
Should lead to less playsound calls and less audio mess
:cl:
soundadd: Decreases bullet ping sound range
/:cl:
=> Decreases ping sound range

_maps/map_files/gelida_iv/gelida_iv.dmm
See title
Fixes good and LZ1 shouldnt have a single tile of LZ2 laying around.
:cl:
fix: Fixed a few areas on Gelida IV.
/:cl:
=> Fixes stray areas on Gelida IV

code/modules/unit_tests/weed_spread.dm
Just increase the time lol someone should totally fix this properly though
=> Lazy weed test fix

code/modules/reagents/chemistry/holder/holder.dm
Fixes a funny exploit.
:cl:
fix: fixed an exploit with reagents
/:cl:
=> Fixes reagent exploit

code/__DEFINES/colors.dm, code/__DEFINES/dcs/signals.dm, code/__DEFINES/misc.dm, code/game/atoms/_atom.dm, code/game/blood.dm, code/game/objects/effects/decals/cleanable.dm, code/game/objects/items/tools/cleaning_tools.dm, code/game/objects/structures/watercloset.dm, code/game/turfs/turf.dm, code/modules/reagents/chemistry/reagents/other.dm
Adds proc/wash()
Atomization for TG drinks
:cl:
code: adds proc/wash() to clean stuff
/:cl:
=> adds proc/wash()

code/datums/gamemodes/_game_mode.dm, code/datums/gamemodes/campaign.dm, code/datums/gamemodes/campaign/campaign_mission.dm, code/datums/gamemodes/combat_patrol.dm, code/datums/gamemodes/extended.dm, code/datums/gamemodes/infestation.dm
Cleaned up/improved end of mission/game messaging, including a little bit of fluff when the game ends.
Clarity, and LORE
:cl:
qol: Improved messaging around end of mission/game for campaign
/:cl:
=> Campaign end of mission/game messaging

code/game/objects/structures/flora.dm
See title.
Getting stuck on random plants has always been a pain in the ass, now xenos wont need to melt every tree they find.
:cl:
qol: Dense plants can now be slashed.
/:cl:
=> Xenos can slash dense plants

code/game/objects/items/toys/toys.dm
Cheaper basketball hoop technology has resulted in xenos now being able to destroy them with their claws.
https://www.youtube.com/watch?v=lBBR0bU8oMo
:cl:
qol: Xenos can now slash basketball hoops.
/:cl:
=> Basketball hoops can be slashed

code/__DEFINES/dcs/signals.dm, code/__DEFINES/dcs/signals/signals_reagent.dm, code/modules/organs/organ_internal.dm, code/modules/reagents/chemistry/holder/holder.dm
Adds some reagent signals for reagents:
Pre-add, Add, New, Remove, Del
From: https://github.com/tgstation/tgstation/pull/79862
Atomization for TG drinks
:cl:
code: Adds a couple reagent signals
/:cl:
=> Adds some reagent signals

code/datums/weather/weather_types/acid_rain.dm, code/game/atoms/_atom.dm, code/game/blood.dm, code/game/turfs/liquid_turfs.dm
turns clean_mob into clean_blood()
better to use /wash() to take care of our washing needs
:cl:
code: removes clean_mob() in favor of clean_blood()
/:cl:
=> turns clean_mob into clean_blood()

code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/corpsman.dm
Fixed an ammo issue for corpsman loadouts. Forgot to delete some redundant code.
Added a missing MRE for corpsman loadouts
:cl:
fix: Campaign: Fixed a couple minior corpsman loadout issues
/:cl:
=> Campaign corpsman fix

code/datums/emergency_calls/retired.dm, code/datums/jobs/job/retired.dm
Lowers probability of it spawning, gives the grunts shoes and makes them all augmented instead of being in wheelchairs.
Bounty requested. Apparently it was spawning too much and them being in a wheelchair made them weak. Leader still is in the minigun chair and legless however.
:cl:
balance: Retired ERT spawns less often, but can now walk (minus the leader)
/:cl:
=> Retired ERT adjustments

code/datums/storage/storage.dm, code/datums/storage/subtypes/bag.dm, code/datums/storage/subtypes/box.dm, code/datums/storage/subtypes/holster.dm, code/datums/storage/subtypes/internal.dm, code/datums/storage/subtypes/pill_bottle.dm, code/datums/storage/subtypes/wallet.dm
Fixes funny pill spam entirely.
Fixes #15796
Shake shake shake
:cl:
fix: fixed pref UI pill spam
/:cl:
=> Pref sound fix

code/game/objects/machinery/vending/marine_vending.dm, code/modules/clothing/under/marine_uniform.dm
Renames Charile Turtleneck to Charlie Turtleneck
Typo bad
:cl:
spellcheck: Charile removed
/:cl:
=> Charile typo to Charlie

code/modules/projectiles/ammo_types/heavy_ammo.dm, code/modules/projectiles/ammo_types/rocket_ammo.dm
PR made by Bill
"Xenos won't die instantly" -Bill Torres
:cl: 
balance: changed tank's rocket from 100 sunder to 20
balance: changed tank's minigun ltaap penetration from 10 to 15
/:cl:
=> Tank adjustments

code/modules/projectiles/magazines/misc.dm
Adds some packet descriptions
Most of the packets have a description, no reason for others not to have
:cl:
spellcheck: Added missing descriptions for a few packets
/:cl:
=> Fills in some packet descriptions

code/game/objects/machinery/vending/marine_vending.dm
see title
more toys for boys
:cl:
add: adds thermal tarps to valhalla (marine weapons vendor, specialist tab)
/:cl:
=> adds thermal tarps to valhalla

code/game/objects/items/tools/cleaning_tools.dm, code/game/objects/machinery/bots/cleanbot.dm, code/game/objects/machinery/suit_storage_unit.dm, code/game/objects/machinery/washing_machine.dm, code/game/objects/structures/watercloset.dm, code/modules/detectivework/footprints_and_rag.dm
call wash() instead of clean_blood()
no gameplay changes
More consistent behaviour when cleaning something it should always just call wash()
:cl:
code: swap out calls of .clean_blood() for .wash()
/:cl:
=> call wash() instead of clean_blood()

_maps/map_files/slumbridge/slumbridge.dmm, code/game/objects/structures/platforms.dm
Slumbridge was my first attempt at a real map. Now that I have more experience and I've seen gameflow, I have made changes to it that should be good QoL.
New flank route from prison to south eastern quadrant.
Another flank, while much less significant, allows xenos to go from the inner ring to the outer ring in prison south east. This should make flanking easier without going over lava.
I added a LOT more corpses for the corpse-hungry castes into almost every area, primarily the colonist dorms where I straight up forgot to add ANY corpses to begin with.
Replaced (almost) every single platform with a non-dense variant. These slow the pace down a bit too much and are basically a waiting game for when your stamina goes up after the jumping update. I also removed the req platforms everywhere …
=> Slumbridge wellness check

_maps/desparity.json, _maps/lawanka.json
In this case, flavor is free.
:cl:
add: Added harmless rain on desparity and lawanka
/:cl:
=> Adds (harmless) rain on Desparity and Lawanka

code/modules/projectiles/gun_helpers.dm
Fix telekinesis tactical reloads
bugfix
:cl:
fix: It's no longer possible to perform a bluetooth tactical reload with a magazine that is too far to reach
/:cl:
=> Fix bluetooth tactical reload

code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm, code/datums/outfit.dm, code/datums/quick_load_beginners.dm, code/datums/quick_load_robots.dm, code/game/objects/machinery/vending/beginner_vendor.dm, code/game/objects/machinery/vending/quick_vendor.dm, code/modules/clothing/modular_armor/combat_robot.dm, code/modules/clothing/under/marine_uniform.dm, tgmc.dme
Adds some beginner loadouts for robots
Now robots can also use the vendor that humans have been using to vend some pre-made loadouts.
:cl:
add: Adds loadouts to the beginner vendor for robots
/:cl:
=> Robot beginner loadouts

code/__DEFINES/sound.dm, code/game/objects/machinery/mortar.dm, code/modules/projectiles/gun_system.dm, code/modules/projectiles/projectile.dm, code/modules/vehicles/armored/armored_weapons.dm
Pretty universally agreed guns blow everyones eardrums out lets try this for a change
:cl:
soundadd: Decrease gun fire sound volume from 60 to 50
/:cl:
=> Decrease fire sound volume from 60 to 50

code/__DEFINES/dcs/signals/signals_reagent.dm, code/modules/reagents/chemistry/holder/holder.dm
Fixes a bug with the chem cap due to funny code port.
:cl:
fix: fixed a bug with the chem cap
/:cl:
=> Chem Exploit fix

code/_onclick/drag_drop.dm, code/modules/mob/living/simple_animal/friendly/cat.dm
Fixes #14428
What do you mean Martin is a cat IT LOOKS LIKE A DOG
Also this isn't good for the game but marines need nerfs badly
:cl:
fix: You can no longer pick up cats from a distance
/:cl:
=> Cat's cannot be picked up from range anymore

_maps/map_files/Sulaco/TGS_Sulaco.dmm
Connects a pipe in west medbay.
Working disposals is good.
:cl:
fix: Fixed a disposals pipe in Sulaco medbay.
/:cl:
=> Fixes a disposal pipe on Sulaco

code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
Allows other xenos to give plasma to pyrogen.
Fixes an oversight, plasma castes should be able to receive plasma.
:cl:
fix: Pyrogen can now be given plasma.
/:cl:
=> Pyrogen can be given plasma

code/game/objects/items/storage/holsters.dm
fix smg-25 holster
bugfix
:cl:
fix: smg-25 holster can no longer hold every item
/:cl:
=> smg-25 holster nerf

_maps/map_files/BigRed_v2/BigRed_v2.dmm, _maps/modularmaps/big_red/bigredsweastcornervar1.dmm, _maps/modularmaps/big_red/bigredsweastcornervar2.dmm, _maps/modularmaps/big_red/bigredsweastcornervar3.dmm, _maps/modularmaps/big_red/bigredsweastcornervar4.dmm, _maps/modularmaps/big_red/bigredsweastcornervar5.dmm
Title.
RipGrayson's approval.
Marines can make a very strong fortication that can easily ward off xenomorphs. There is a 1/5 chance that there will be two plat miners for marines to occupy and can have requisition supply marines with stronger fortications and weapons no matter what the xenomorphs throw at them.
:cl:
del: Remove Big Red's two plat miners and 1 normal miner near LZ2
balance: Prevent a 1/5 chance for marines to camp near LZ2 on two plat miners
/:cl:
=> Remove Big Red's cave miners near LZ2

code/game/objects/machinery/OpTable.dm
Probably fixes an occasional bug where surgery tables perma sleep someone.
Although I haven't been able to reproduce this, multiple people have reported this, and this is better code anyway.
:cl:
fix: Probably fixes some cases where a surgery table could put you to sleep forever
/:cl:
=> Surgery table fix

code/game/atoms/atom_movable.dm, code/game/objects/items/jetpack.dm, code/game/objects/items/weapons/swords.dm, code/game/objects/items/weapons/twohanded.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Bakes in some checks into knockback/safethrow.
Reduces check requirements prior to this proc (that may or may not have been checked at all)
Fixes various abilities being able to knockback things they shouldn't, like tanks.
:cl:
fix: fixed knockback working on somethings it shouldn't
/:cl:
=> Knockback improvement

code/game/objects/structures/bookcase.dm
Changes the bookcase integrity from 500 to 200
I swear i have no idea why are they so tanky it takes around 10 machete hits to take ONE down its genuinely infuriating
:cl:
balance: changed bookcase integrity from 500 to 200
/:cl:
=> Nerfs bookcases

code/__DEFINES/span.dm, code/__DEFINES/text.dm, code/datums/components/larva_queue.dm
Title says all you need to know
Larb
:cl:
qol: The larva queue button shows your position when active.
/:cl:
=> Show larva position on button

code/modules/projectiles/ammo_types/rifle_ammo.dm
Nerfs the TX11's sunder
TX11 right now outpaces the rest of the guns, while that's the niche it has due to sacrificing attachments, it does it a little bit too well, this should put it more in line
:cl:
balance: TX11 Sunder reduced
/:cl:
=> Slight nerfs to the TX11

code/modules/vehicles/armored/__armored.dm
Fixed ammohuds bugging out if you enter a vehicle when a gun has no ammo in it.
:cl:
fix: Fixed ammohuds bugging out if you enter a vehicle when a gun has no ammo in it
/:cl:
=> Vehicle ammohud fix

code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm, code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm, code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm, code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm, code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm, code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm, code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm, code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm, code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm, code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm, code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm, code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm, code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm, code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm, code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
Mostly buffs xenos stats across the board, while reducing speed, for a complete list of changes read the hackmd https://hackmd.io/@wlLEbadtQoCyE4iytTkonw/r1vSnLmBR
Xenos are really struggling right now, with the ammount of additions marines have gotten over time while xenos themselves have had almost no additions, these buffs should push them to have a better time on the game.
:cl:
balance: Makes xenos tankier and a little slower plus some other assorted xeno changes, read the hackmd linked on the pr
/:cl:
=> Mostly buffs xenos across the board, nerfs speed

code/datums/status_effects/debuffs.dm
Fixed some status effects applying when they shouldn't... such as on corpses.
:cl:
fix: fixed some status effects applying when they shouldn't
/:cl:
=> status effect fix

code/game/objects/items/binoculars.dm, code/modules/clothing/modular_armor/attachments/modules.dm
Did a funny to the logic on the last pr.
:cl:
fix: Binos actually work when they should
/:cl:
=> Binoc fix 2

code/datums/weather/weather.dm, code/datums/weather/weather_types/acid_rain.dm, code/datums/weather/weather_types/ash_storm.dm, code/modules/client/preferences_savefile.dm
Did you know that the weather pref has been inverted ever since it was added?
Yes, weather sounds off = you hear weather
Weather sounds on = you hear nothing.
P.S. someone should move all these smelly pref verb into the pref UI.
:cl:
fix: The weather sound pref is no longer the wrong way around.
/:cl:
=> Fixes the weather pref

code/modules/mob/living/carbon/xenomorph/evolution.dm
@lKiseki t4s couldnt pick strains
=> Should Fix T4 strains

code/game/turfs/floor_ground.dm
Puts mars sand back to red minimap colour, but with the new sand footsteps.
:cl:
fix: fixed red sand minimap colour
/:cl:
=> Accidental mars sand changes

_maps/map_files/kutjevo/kutjevo.dmm
Title.
Free additional 100 metals for a single map is stinky
:cl:
del: remove large metal stacks in Kutjevo
/:cl:
=> remove large metal stacks in Kutjevo

code/modules/client/preferences_savefile.dm
fix draw order not saving
fix
:cl:
fix: fix draw order not saving
/:cl:
=> fix draw order not saving

code/game/objects/items/binoculars.dm
Lets you unzoom binos by attackself again.
unintended change.
:cl:
fix: Binos can be unzoomed again via attackself
/:cl:
=> Allow attackself unzoom

code/_onclick/item_attack.dm, code/game/objects/items.dm, code/game/objects/items/storage/firstaid.dm
facepaint no longer opens pill bottles
TBH Facepaint behaviour should be more consolidated instead of being done on an individual basis like it's done here, but that should be done in a more comprehensive PR
qol.
:cl:
fix: Facepaint no longer opens pill bottles when trying to paint them
/:cl:
=> facepaint no longer opens pill bottles

code/modules/reqs/supply.dm
:cl:
fix: fixed tank vendor ui not resetting on new purchase
/:cl:
=> Reset tank ui on new purchase

code/modules/mob/living/carbon/xenomorph/abilities.dm
:cl:
fix: Fixed hiding ability let you layer under tank
/:cl:
=> Fixes hiding ability let you layer under tank

code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
Keeps track of gorger heals for end of round personal statistics
Increased feedback and more statistics simmilar to drone, hivelord, shrike, and queen heals.
:cl:
add: Gorger heals are now tracked
/:cl:
=> Tracks gorger heals

code/modules/reagents/reagent_containers/syringes.dm
Syringes can change injection between 5,10,15u
qol/buff
:cl:
qol: Syringes can now change injection size
/:cl:
=> Syringes can change their injection amount

code/modules/vehicles/armored/__armored.dm
Fix a runtime.
:cl:
fix: fixed a vehicle runtime
/:cl:
=> Runtime fix on storing mobs in tanks

code/game/objects/items/storage/boxes.dm, code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/structures/crates_lockers/largecrate_supplies.dm
Adds heavy smg ammo boxes to the req vendor and the box.
It missing
:cl:
add: Heavy SMG ammo boxes
/:cl:
=> Adds SMG-45 boxes

code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
Title
All builder castes were given sow some time ago, so now that widow has building abilities it should as well
:cl:
balance: Widow Primo now includes the sow ability
/:cl:
=> Gives primo widow sow

code/modules/vehicles/vehicle_attachments/weapon_attachments.dm
Fix a couple of bugs with bike mounted guns.
:cl:
fix: fixed a couple of bugs with bike mounted guns
/:cl:
=> Bike gun fix

code/modules/lighting/lighting_static/static_lighting_object.dm
Fixed an oversight in #16151 which led to issues when updating static light on turfs with baselighting.
Being able to see is good.
:cl:
fix: fixed an issue with turfs going dark in some cases
/:cl:
=> baselight fix

code/game/objects/structures/razorwire.dm, code/game/objects/structures/xeno.dm, code/modules/projectiles/guns/_shared_ammo_objects.dm
Fixes razor, sticky and fire effecting desants when they shouldn't really.
Less strange interactions on top of a tank
:cl:
fix: fixed tank desants being effected by razor, sticky and fire the vehicle crosses
/:cl:
=> Desant fix

code/game/objects/effects/temporary_visuals/miscellaneous.dm
After images are no longer mouse opaque.
:cl:
fix: After images are no longer mouse opaque
/:cl:
=> Fix after image mouse opacity

code/modules/factory/parts.dm, code/modules/factory/unboxer.dm, code/modules/reqs/supplypacks.dm
Adds cigarettes to reqtorio.
Much needed recipe.
:cl:
add: Reqtorio can now produce 500 cigarettes.
/:cl:
=> 500 cigarettes

code/controllers/configuration/entries/general.dm, interface/interface.dm
Fixes webmap url
Fixes webmap. Broken webmap is le bad, especially for new players.
:cl:
fix: Webmap fixed
/:cl:
=> Fixes webmap

interface/interface.dm
Fixes an emberassing oversight in my previous PR. Oopsie.
Broken webmap le bad.
:cl:
fix: Webmap fixed even if there are spaces in the map name
/:cl:
=> Fixes webmap even if there are spaces in the map name

code/game/atoms/atom_movable.dm, code/modules/admin/view_variables/filterrific.dm
Fixes transition_filter().
#16203 moved some procs around, but the args were in a different order to what it was and none of the existing instances were updated.
Proc work good.
:cl:
code: Fixed an issue with wrong ordered args in transition_filters()
/:cl:
=> Filter fix

code/game/objects/machinery/buttons.dm
Title
Valhalla marines shouldn't be getting access to headsets.
:cl:
fix: Fixed an issue with headsets and ASRS tablets in Valhalla
/:cl:
=> Removes headsets and ASRS tablets from spawning in Valhalla

code/game/objects/machinery/buttons.dm
This is unused, I forgot to remove it when making the button all that time ago I guess
dead var bad
:cl:
del: Deleted a dead var on the marine xalhalla spawner
/:cl:
=> Dead var death

code/game/objects/structures/reagent_dispensers.dm
Fixes a runtime with fueltanks trying to explode after they've already been qdel'd.
:cl:
fix: fixed a fueltank runtime
/:cl:
=> Fueltank runtime

code/datums/gamemodes/hvh.dm, code/game/turfs/turf.dm, code/modules/lighting/lighting_area.dm, code/modules/mapping/map_template.dm
Some improves/fixes to baselight stuff.
Fixes some excessive update calls.
Update baselighting proc simplified for readability.
:cl:
code: Cleaned up some baselight code
/:cl:
=> Baselighting fixes/improvements

code/game/objects/items/weapons/weapon.dm, code/modules/projectiles/gun_system.dm, code/modules/projectiles/mounted.dm
Have thing in active hand.
Have gun in off hand.
Right click to shoot offhand gun.
Sword and pistol lets go
:cl:
add: Guns can be fired offhand with right click
/:cl:
=> Off-hand shooting

_maps/map_files/Sulaco/TGS_Sulaco.dmm
Adds tcoms for the other 3 squads
Their radio currently isn't working. Wack.
:cl:
fix: Adds 3 missing squad telecoms to sulaco
/:cl:
=> Fixes Bravo, Charlie, and Delta squad chat on sulaco

_maps/map_files/Iteron/Iteron.dmm, code/game/objects/effects/landmarks/gamemode/campaign_vehicle_spawners.dm
Adds an LTAAP tank as the 3rd TGMC tank spawn (i.e. 80+ pop).
Tank weapon variety. Also it turns out LTAAP absolutely fucking SHREDS everything in HvH.
:cl:
add: Campaign: Marines 3rd tank spawn comes with LTAAP
/:cl:
=> LTAAP tank in campaign

code/modules/reagents/reagent_containers/autoinjectors.dm
Does what it says in the title
Some people are missing it
:cl:
qol: Isotonic autoinjector now has a tag
/:cl:
=> Gives Isotonic autoinjector a tag

code/modules/reqs/supply.dm
Every tab now gets the same type of data
Fixes an issue where several tabs bluescreen on opening
:cl:
fix: fixed supply bluescreening
/:cl:
=> Fixes supply tgui bluescreen

code/datums/components/after_image.dm, code/game/objects/effects/temporary_visuals/miscellaneous.dm
Actual fix, like I already had on sandevistan, honk.
Fixes #16289
:cl:
fix: fixed afterimage opacity for real
=> Afterimage actual fix

code/game/objects/items/stacks/medical.dm
Records kitting
I think it was meant to do this already, since there is a whole proc made for this. Must have been an oversight.
:cl:
qol: Kitting is now recorded for round end personal stats
/:cl:
=> Records kitting

code/datums/gamemodes/campaign/missions/mech_wars.dm, code/datums/gamemodes/campaign/missions/patrol_mission.dm
Tanks are now worth 30 points instead of 10 like mechs.
Point goal is 375 instead of 400 for Combat Patrol mission specifically (combined arms is still 400), as after reducing the total game time, it was a bit harder than it should be to get a points victory.
Walance.
:cl:
balance: Tanks are worth 30 points in Combined Arms instead of 10
balance: Combat Patrol mission's point goal is reduced from 400 to 375
/:cl:
=> Patrol mission point changes

code/_globalvars/lists/game_modes.dm, code/game/objects/items/implants/implanter.dm
Added some implants to the campaign reward tables.
New, exciting ways for players to gib themselves in front of their team.
:cl:
add: Campaign: added some implants to the mission reward tables
/:cl:
=> Campaign reward table additions

code/modules/factory/parts.dm, code/modules/factory/unboxer.dm, code/modules/reqs/supplypacks.dm
Adds SG-62 ammo bins to reqtorio
9 times out of 10 smartriflers will ask for this instead of the magazines
:cl:
add: Added SG-62 ammo bins to reqtorio
/:cl:
=> Adds SG-62 ammo bins to reqtorio

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
See title
Self heal ability should be used while healing, and this already works during fortify/crest.
:cl:
qol: Defender can now use regenerate skin while resting.
/:cl:
=> Defender can use regenerate skin while resting

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Adds 10 more intel computers to magmoor.
Maps should probably have more than one intel computer.
:cl:
add: Added 10 more intel computers to Magmoor.
/:cl:
=> Adds more intel computers to magmoor

code/modules/vehicles/powerloader.dm
It was used to open/close the panel to replace power cells of a powerloader but thats not a thing anymore
:cl:
code: removed useless powerloader code
/:cl:
=> Deletes some useless powerloader code

code/datums/storage/storage.dm, code/game/objects/items/storage/backpack.dm
- You can now open the duffelbag after a 2 second channel
- Moving while having the bag open closes it
Makes duffelbag less ass
:cl:
balance: You can now open worn duffelbags with a 2 second channel
/:cl:
=> Duffelbag tweaks

code/datums/components/_component.dm, code/datums/greyscale/_greyscale_config.dm, code/modules/admin/topic.dm, code/modules/admin/view_variables/debug_variables.dm, code/modules/paperwork/paper_bundle.dm
Fixes some funny code that is incompatible with 1640 and onwards.
:cl:
code: Made some 515.1640 compatibility fixes
/:cl:
=> 515.1640 compatibility fixes

code/modules/reagents/chemistry/recipes/other.dm
30 second aoe spammable stun serves no genuine purpose in TGMC.
:cl:
del: Removed the flash powder reaction
/:cl:
=> Flash powder removal

code/modules/vehicles/powerloader.dm
Closes #13405
You can now repair the RPL-Y powerloader
:cl:
fix: powerloader can now be repaired
/:cl:
=> fixes powerloader being unrepairable

code/modules/clothing/glasses/glasses.dm
Basically prevents this
:cl:
fix: fixed sunglasses duplicating in the clothes vendor
/:cl:
=> Fixes duplicating sunglasses

code/__DEFINES/maths.dm
Implements SPT_PROB and SPT_PROB_RATE macros from TG. It "Converts a probability/second chance to probability/seconds_per_tick chance"
Atomizes code change that is needed for my cooking PR, and for anyone else that might want to use it
:cl:
code: Implemented SPT_PROB and SPT_PROB_RATE
/:cl:
=> Implements SPT_PROB

code/game/objects/machinery/cloning/cloning.dm
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/16273
Also made the name not randomly capitalized, as well as added autodocs to the vars and procs
Things that require power working without power stink
:cl:
fix: Clone vat progress gets reset if it loses power
/:cl:
=> Clonevat power fix + autodoc

code/__DEFINES/DNA.dm, code/datums/gamemodes/objective.dm, code/game/objects/effects/landmarks/corpsespawner.dm, code/game/objects/items.dm, code/game/objects/items/defibrillator.dm, code/game/objects/items/scanners/health_analyzer.dm, code/game/objects/machinery/autodoc.dm, code/game/objects/machinery/flasher.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_damage.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/human_helpers.dm, code/modules/mob/living/carbon/human/life/handle_organs.dm, code/modules/mob/living/carbon/human/species_types/zombies.dm, code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm, code/modules/mob/living/carbon/xenomorph/embryo.dm, code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm, code/modules/reagents/chemistry/reagents/drinks/drink_reagents.dm, code/modules/reagents/chemistry/reagents/medical.dm, code/modules/surgery/brainrepair.dm, code/modules/surgery/eye.dm, tgmc.dme
Adds organ defines, and for the human_helper procs, adds get_organ_slot and remove_organ_slot
Makes things easier to use, edit, and harder to fuck up, also less lines, also makes porting things from TG easier since they use get_organ_slot and organ defines
:cl:
code: Organ defines, get_organ_slot, remove_organ_slot
/:cl:
=> Organ defines, get_organ_slot, remove_organ_slot

code/datums/gamemodes/campaign/rewards/disablers.dm
Fixes asset disablers not entirely turning off as intended, causing some assets to get stuck in certain cases.
:cl:
fix: Campaign: Fixed an issue with some assets getting disabled forever
/:cl:
=> Asset disabler fix

code/datums/personal_statistics.dm
removes a extra s from the line about rouny snatches
grammar
=> Fixes a extra s in round end report

code/datums/gamemodes/hvh.dm, code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
Fixes deploy points not working in Combat Patrol and Sensor Capture.
Fixes lighting not updating in Combat Patrol and Sensor Capture.
Literally unplayable, aylmao.
:cl:
fix: Fixed deploy points and lighting not working correctly in Combat Patrol and Sensor Capture
/:cl:
=> Combat patrol fixes

code/modules/reagents/chemistry/reagents/medical.dm
Makes neuraline show up on scanner
You'd think for something with an OD so devastating and a secondary effect it would show up on scanner.
:cl:
qol: Neuraline shows up on scanner now
/:cl:
=> Neuraline shows up on med scan now

code/__DEFINES/atom.dm, code/__DEFINES/dcs/signals/signals.dm, code/game/atoms/_atom.dm, code/game/objects/effects/aliens.dm, code/game/objects/items.dm, code/game/objects/machinery/deployable.dm, code/game/objects/objs.dm, code/game/objects/structures/barricade.dm, code/game/objects/structures/dropship_equipment.dm, code/game/objects/structures/handrail.dm, code/game/turfs/open.dm, code/game/turfs/turf.dm, code/game/turfs/walls/walls.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/projectiles/mounted.dm, tgmc.dme
Tested, but TM first in case I overlooked something.
Refactors a bit of acid code to be less horrible.
Its still kinda horrible, but less snowflake and funny atom var.
Mainly things are now done by atom procs as appropriate, and with signals for some behaviors instead of funny checks during process.
Better code.
:cl:
code: Cleaned up some acid code
/:cl:
=> acid code cleanup

code/controllers/subsystem/blackbox.dm
I have to move this table to innodb for replicated database reasons.
=> No more delayed inserts for feedback db.

code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
I did the dumb and fixed it for patrol/sensor but forgot the signal that makes it work in campaign.
:cl:
fix: fixed patrol points in Campaign
/:cl:
=> Patrol point fix (for campaign)

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Fixed timeshift giving perma godmod if the wraith dies before it ends.
Perma godmode xenos is bad.
:cl:
fix: fixed timeshift not ended if the wraith died early
/:cl:
=> Timeshift bugfix

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/ammo_types/ags_ammo.dm, code/modules/projectiles/ammo_types/rocket_ammo.dm, code/modules/projectiles/ammo_types/tx54_ammo.dm, code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
Fixed a bug with airburst projectiles not hitting things on their start turf as intended.
Also fixed a typo on obj hits causing a runtime.
Airburst won't go through windows and shit anymore.
:cl:
fix: fixed an issue with airburst projectiles
/:cl:
=> Airburst fix

code/game/objects/structures/window_frame.dm
Title.
It was broken and invisible, now it's fixed.
Invisible objects bad, one day I'm going to add an error sign to every dmi in the game.
:cl:
fix: Fixed a window frame going invisible.
/:cl:
=> Fixes an invisible window frame

code/_onclick/hud/fullscreen.dm
Broke fullscreen overlays in some situations with my previous pr.
Bug fix
:cl:
fix: fixed some fullscreen overlays not working
/:cl:
=> fullscreen fixes

code/modules/ai/ai_behaviors/ai_behavior.dm
Fixes many instances of AI mobs getting stuck in place for no apparent reason.
This includes AI mobs not doing anything if they're on the same turf as the target they're trying to kill (i.e. beetles charging a human just breaks their AI).
Basically AI has been fucked since widow came out. Aylmao.
AI working is quite useful.
:cl:
fix: fixed AI mobs getting stuck in place for no reason
fix: fixed AI mobs not attacking their target or doing anything at all, if on the same tile as their target
/:cl:
=> AI behavior fix

code/game/objects/machinery/vending/marine_vending.dm
thank you for the free gbp @Delnth 
you forgor
:cl:
fix: Valhalla reqtorio vendor may now vend unboxers.
/:cl:
=> Adds unboxer to valhalla reqtorio vendor

code/game/objects/machinery/doors/railing.dm
Basically fixes this:
Looks better
:cl:
fix: fixed retractable railings smoothing with walls for some reason
/:cl:
=> Removes smoothing from retractable railings

.github/PULL_REQUEST_TEMPLATE.md
Touching on the changelog portion, removed any reference to GBP since we don't use that, moved the second part about the :cl: above the section its talking about rather than below so it's more visible. Also slightly changed the wording.
I don't think people are actually seeing the bottom paragraph about the cl tags, this should help visiblity, also it being accurate to how we actually do things is nice
=> Updates the pull request template

.github/PULL_REQUEST_TEMPLATE.md
I forgot an arrow. Amends the wording slightly
=> Adds missing arrow to PR template

code/datums/components/attachment_handler.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/15812
:cl:
fix: fixed stuff like capes and kamas applying it's overlays while inhands.
/:cl:
=> Fixes stuff like capes and kamas applying it's overlays while inhands

code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm, code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm, code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
Per title.
I think it's a fun change! Gives minions more potential if they work together with crushers, too.
:cl: Lewdcifer
add: Xeno minions can now ride crushers.
/:cl:
=> Allows minions to ride crushers

code/game/objects/structures/droppod.dm
Fix a misc harddel or 2.
:cl:
fix: fixed a couple drop pod hard dels
/:cl:
=> Pod runtimes

code/__HELPERS/game.dm
Misc image runtime fix.
:cl:
fix: fixed a misc runtime
/:cl:
=> client image runtime fix

code/modules/logging/categories/log_category_game.dm
Fixed logging for minimap drawing. Apparently it was just never setup fully?
:cl:
admin: Fixed minimap drawing logging
/:cl:
=> Map draw logging

_maps/map_files/desertdam/desertdam.dmm, code/game/area/desertdam.dm
Title. They were broken.
Fixes good.
:cl:
fix: Fixed improper rotation of Chigusa platforms
fix: Fixed improper area colors for Chigusa
/:cl:
=> Fixes Chigusa platforms and area colors

code/datums/gamemodes/campaign.dm
No game changes, just forgot a bracket for autobalance admin messaging.
=> campaign autobal typo

code/modules/admin/fun_verbs.dm
MSO brought this up and I agree
yes
:cl:
admin: Admins can now announce and global narrate infinitely
/:cl:
=> Global narrate and admin announce no longer have a text length limit

code/modules/admin/panels/permission_panel.dm, code/modules/mob/mob.dm, code/modules/power/power.dm, code/modules/security_levels/keycard_authentication.dm
yea
linter not whining on every pr is good
Nothing player facing
=> Fixes some ambigious ins linter was complaining about

code/modules/mob/living/carbon/xenomorph/attack_alien.dm
yea
I think its funny
:cl:
fix: Friendly xeno nibbles have the attack animation again
/:cl:
=> Brings back xeno nibbling having an attack animation

code/datums/gamemodes/infestation.dm
God this annoyed me for literally since I started playing.
I also changed the names of the variables to be more easily understood.
Things functioning as intended is good.
:cl:
fix: Bioscan will no longer say "including one in 0" in place of where it's supposed to tell you where someone is located
/:cl:
=> Finally fixes bioscan saying "including one in 0"

code/game/objects/items/storage/belt.dm
Fixes the knife belt being a normal sized item.
Whole bunch of exploits.
:cl:
fix: The knife belt is the same weight class as other belts
/:cl:
=> Knife belt fix

code/game/data_huds.dm
The title
A thing working is good
:cl:
fix: fixed the queen overwatch icon
/:cl:
=> Fixes queen overwatch icon

code/datums/components/reequip.dm, code/modules/projectiles/gun_attachables/rail.dm, code/modules/projectiles/gun_system.dm
The magnetic harness is disabled for 2 seconds after being stripped from someone
It's really annoying when someone's gun get stuck on their bag and you just cannot get it off.
:cl:
qol: Stripping magharn'd weapons now disables the magharn for a couple seconds
/:cl:
=> Stripping magharn'd weapons now disables the magharn for a couple seconds

_maps/shuttles/tgs_bigbury.dmm
Buttons on the bigbury are now on walls correctly.
Floating buttons are ugly.
:cl:
fix: Bigbury buttons are now on the walls properly.
/:cl:
=> Fixes Bigbury buttons

code/modules/ai/ai_behaviors/xeno/xeno.dm, code/modules/ai/ai_behaviors/xeno/xeno_illusion.dm, code/modules/ai/ai_behaviors/xeno/zombie.dm
Fixes a typo.
Hunter illusions now pretend to attack correctly
:cl:
fix: Fixed a typo in ai codes.
/:cl:
=> Fixes ai typo

code/__HELPERS/type2type.dm, code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
Fixes #16560
Cleans up firenade code significantly to be less cursed.
Also makes firenado pathing better.
Fixes angle2dir not working properly with negative angles etc.
Better code, bug fixes.
:cl:
fix: fixed firenado going through dense objects
code: Improved firenado code and pathing
/:cl:
=> Firenado fixes/improvements

_maps/map_files/deltastation/deltastation.dmm
What it says as per the title.
This is a removed map, and an open supermatter is FUN. Make the slop map, more slop. As god intended.
:cl:
balance: Removes barriers around Delta Station's supermatter
/:cl:
=> Removes barriers around Delta Station's supermatter

code/__DEFINES/dcs/signals/signals.dm, code/game/atoms/atom_movable.dm, code/modules/lighting/emissive_blocker.dm, code/modules/mob/dead/dead.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/login.dm, code/modules/mob/living/logout.dm, code/modules/mob/living/silicon/ai/freelook/eye.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/mob/mob.dm, code/modules/shuttle/on_move.dm
What it says on the tin, ports misc bits of code from TG to make this (currently completely nonfunctional) code actually work.
This is a useful list... if it worked. Also specifically because I want to use it in #16611
:cl:
code: clients_by_z actually works now
/:cl:
=> Make clients_by_z work

code/game/objects/structures/reagent_dispensers.dm
Fixes a runtime with fueltanks.
I previously fixed another runtime here, but caused another, so now just checking qdeleted like it should have been originally.
:cl:
fix: fixed another fueltank runtime
/:cl:
=> Fueltank proper runtime fix

code/game/objects/items/explosives/grenades/grenade.dm
Explosive grenades now blow your hand off if they explode... in your hand.
https://github.com/user-attachments/assets/d0b95138-7263-4dd0-8b2b-405216be933c
Game is borderline unplayable without this feature.
:cl:
add: Explosive grenades will blow your hand off if they detonate in-hand
/:cl:
=> Makes  grenades peak

code/modules/projectiles/sentries.dm
Fixes #16362
:cl:
fix: fixed a BAS exploit
/:cl:
=> Sentry fix

code/game/objects/items/weapons/twohanded.dm
Gives king sledge immunity
Due to Kuro's changes on xenos that nerfed their speed, this makes king SUPER slow with no frenzy, meaning that stuff that slow a lot like vali and this (to some extent) really fuck over him.
Also i think that due being a 700 hp thank, this should be a thing for him too
:cl:
balance: Makes king immune to rocket sledge stun
/:cl:
=> Gives king sledge inmunity

code/game/objects/items/weapons/twohanded.dm
Bug Fix for #16596
Dumb oversight when removing the drip feature, fixed fuel cost and sound effect on attack on mob
bug fix
:cl:
fix: fixed chainsaw fuel cost on attack on mob
/:cl:
=> Chainsaw fix

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm, code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
The moon cutter thing now actually hits mobs during its lunge.
Funny weapon being broken for months/year without anyone noticing or reporting it.
:cl:
fix: Moonlight particle cutter actually hits mobs again mid lunge
/:cl:
=> Melee mech fix

code/modules/client/client_defines.dm, code/modules/client/client_procs.dm, code/modules/keybindings/bindings_atom.dm, code/modules/keybindings/bindings_client.dm, code/modules/mob/mob_movement.dm
Ports https://github.com/PMC-Unga-Marines/Unga-Marines/pull/299
Which is a tgmc specific version of https://github.com/tgstation/tgstation/pull/81464
Hot proc microopt
:cl:
code: Ported some optimisations to keyloop
/:cl:
=> keyloop microopt

code/game/objects/effects/decals/Cleanable/humans.dm, code/game/objects/effects/decals/Cleanable/robots.dm, code/game/objects/effects/spawners/gibspawner.dm, code/modules/recycling/disposal.dm
Port some changes from tg/RU so gibs aren't as funny during mapload.
Also removed a copy paste redundant proc.
Better load times or something.
:cl:
code: Gib code improvements for mapload
/:cl:
=> Gib code improvements

code/modules/projectiles/guns/plasma.dm
Plasma SMG has a description now
Less empty space, more overview on what the weapon does.
:cl:
spellcheck: Plasma SMG now has a description
/:cl:
=> Adds Plasma SMG description

code/datums/signals.dm
Ports some signal changes from TG.
https://github.com/tgstation/tgstation/pull/79153
https://github.com/tgstation/tgstation/pull/82641
https://github.com/tgstation/tgstation/pull/83244
:cl:
code: Signal code improvements
/:cl:
=> Signal improvements

code/modules/mapping/mapping_helpers.dm
If the light is already broken then our job is done anyway 
checks passing is good
:cl:
fix: Fixed light break helper complaining about already broken lights
/:cl:
=> Fix light break helper complaining about already broken lights

_maps/map_files/Vapor_Processing/Vapor_Processing.dmm
title
Maps need xeno spawnpoints
:cl:
fix: Added xeno spawn points to vapor processing.
/:cl:
=> Adds xeno spawnpoints to vapor processing

code/game/objects/structures/razorwire.dm
Fixes razorwire icons being an error or incorrect state in some cases.
:cl:
fix: fixed razorwire icons occasionally erroring out
/:cl:
=> Razorwire icon fix

code/modules/mob/living/carbon/human/inventory.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
=> Temporary hotfix for stripmenu equipping

code/datums/status_effects/xeno_buffs.dm
apparently applying warding pheromones AND THEN giving your puppet a warding blessing makes it reach god mode due to the blessing being multiplicative. This changes that to it a being flat bonus and should kill this bug forever
this never happens again.
:cl:
fix: fixes puppets ridiculous armor ratings if warding pheromones were applied before it got warding blessing
/:cl:
=> Fixes godmode puppet bug

code/_onclick/hud/screen_objects/menu_text_objects.dm
Literally what the title says, you can only use one of the buttons at once anyway
:cl:
qol: Merged Join game and ready up lobby buttons
/:cl:
=> Merges Join game and ready up lobby buttons

_maps/modularmaps/big_red/bigredlibraryvar2.dmm, _maps/modularmaps/big_red/bigredlibraryvar3.dmm
Last PR I only changed it for one library modular map because I apparently forgot there is 3 variants.
:cl:
fix: fixed bookshelves on some Big Red map variants still not being dense
/:cl:
=> BR bookcase density fix 2

code/modules/mob/mob.dm
Fixes a severe and wide ranging exploit.
:cl:
fix: fixed an equip exploit
/:cl:
=> Equip exploit fix

code/game/objects/machinery/telecomms/broadcasting.dm
Fixes a bad runtime. AFAIK squad TTS just doesn't work right now, which is funny because it looks like it didn't work for half of the TM period and just no one said anything.
:cl:
fix: fixed squad/radio TTS
/:cl:
=> squad/Radio TTS fix

code/game/objects/machinery/telecomms/broadcasting.dm
Should stop radio TTS playing for your own messages (i.e. hearing yourself twice).
Also makes radio TTS actually check correctly for deafness.
Fixes
:cl:
fix: fixed radio TTS playing when it shouldn't
/:cl:
=> Radio TTS fix

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Unties handle_stealth (used for process) and the new handle_stealth_move (for moving while stealthed).
Fixes an issue with regaining stealth damage (for breaking stealth calc) when moving.
Possibly fixes some funny exploit for moving while more stealthed than they should, but not certain.
Bug fixes.
:cl:
fix: fixed a bug with hunter stealth
/:cl:
=> Stealth fix

code/game/objects/items/plantable_flags.dm
Adds game logs for when the flag is deployed/undeployed.
Admins know who to blame for flag grief.
:cl:
admin: Added game logs for the flag
/:cl:
=> Adds flag logging

_maps/map_files/LV759/LV759.dmm, _maps/map_files/icy_caves/icy_caves.dmm
https://github.com/tgstation/TerraGov-Marine-Corps/pull/16735
see this PR
Icy caves is a somewhat xeno sided map, hoping these changes will make it easier for the marines to get to and hold disks/nuke
:cl:
balance: adjusts fog zones and cave width on icy caves
/:cl:
=> Decreases the size of some fog areas on icy caves, slightly widens western cave tunnels

code/__DEFINES/conflict.dm, code/game/objects/effects/effect_system/smoke.dm
AG smoke now clears any kind of smoke.
More utility value for being able to purge other smoke types, like dense normal smoke/WP smoke etc.
:cl:
balance: Anti-gas smoke now purges all smoke types
/:cl:
=> Anti-Gas universal purge

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm, code/datums/gamemodes/_game_mode.dm, code/datums/gamemodes/crash.dm
Prison Station is now again voteable on Nuclear War and Crash.
I have come to an epiphany that maybe I was too harsh on this map, and that players like to torture themselves nonetheless. Let the people have it if they vote it.
:cl:
add: Prison Station is now back in rotation.
/:cl:
=> Prison Station: Freedom

code/controllers/subsystem/tts.dm, code/game/objects/machinery/telecomms/broadcasting.dm
Makes radio TTS actually work.
There was like 3 different issues in the original pr so this had just never worked.
:cl:
fix: Fixed radio TTS for real
/:cl:
=> For real real radio TTS fix (real edition)

code/controllers/configuration/entries/game_options.dm, code/game/say.dm, code/modules/mob/living/say.dm, config/config.txt
Ports https://github.com/tgstation/tgstation/pull/88826/files 
Host request for performance
:cl:
server: Added TTS whisper config
/:cl:
=> Adds an off-by-default config option to optionally disable TTS audio on whispered speech

code/game/world.dm
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> [s] Remove world/topic throttling

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
it was merged without these lol
Prison station is big. A lot of walking to do.
:cl:
balance: Adds preplaced tunnel landmarks to Prison Station
/:cl:
=> Adds a few tunnel sites to prison station

code/modules/projectiles/ammo_types/rocket_ammo.dm
Removes its light explosion
"Fuck it how bad can it be"
:cl:
balance: Homing tank secondary pod damage nerfed
/:cl:
=> Homing tank secondary pod nerf

code/modules/projectiles/ammo_types/heavy_ammo.dm
This was the ONLY redeeming quality for the chaingun over the LTB and lumi removed it for ??? reasons in the aimmode pr which kuro didnt read
see above
:cl:
balance: Tank Chaingun has IFF again
/:cl:
=> Tank Chaingun has IFF again

code/modules/projectiles/ammo_types/heavy_ammo.dm, code/modules/vehicles/armored/armored_weapons.dm
nvm just do a quick pr for me
damage to 25, rof to 0.15
the game is opeee
:cl:
balance: nerfed tank ltaap firerate and damage
/:cl:
=> Nerf ltaap

code/modules/vehicles/armored/armored_weapons.dm
Still too good for cqc
:cl:
balance: tank micromissiles now fire in 3 shot bursts instead of 6
/:cl:
=> Nerf micro missiles again

.gitignore, code/__DEFINES/rust_g.dm
https://github.com/tgstation/tgstation/pull/87313/files
run usual rust g with a x64 target to compile for this
=> Makes OD Server Actually run with rust64

code/game/objects/machinery/adv_med.dm, code/game/objects/machinery/washing_machine.dm
=> Fix some wierd code found using OD unimplemented

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
I had some weirdness with this fix not working, then deciding to work. I hope it's not some sort of race condition I'm missing.
Wraiths being able to delete people is bad mkay
:cl:
fix: Wraiths can no longer delete people using banish.
/:cl:
=> Fixes wraiths being able to delete people using banish

code/__DEFINES/loadout.dm, code/modules/reqs/supplypacks.dm
Adds the HvH shrapnel Drill to HvX corpsmen vendor
Price is 16 points so you cannot buy both Meralyne pills + Dermaline pills
More vendor options
:cl:
Balance: Added the ESR-12 to Corpsmen loadout vendors
/:cl:
=> Adds Shrapnel drill to HvX

code/game/atoms/_atom.dm
fix VV "Jump To"
Admin VV stuff bugfix
:cl:
admin: fix VV "Jump To"
/:cl:
=> fix VV "Jump To"

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm, code/modules/xenomorph/maw.dm
Capitalizes options like titles (every word capitalized)
its/it's stuff
"Requires open space and time to place." is kind of redundant and also not present on every structure
rewording 
Say you got an "I", "T"
Followed by apostrophe, "s"
Now what does that mean?
You would not use "it's" in this case
As a possessive
It's a contraction
What's a contraction?
Well, it's the shortening of a word, or a group of words
By the omission of a sound or letter
:cl:
add: Added new mechanics or gameplay changes
spellcheck: general psi structure spellcheck/grammar/wording adjustments
/:cl:
=> General psi structure grammar/spelling/wording

code/game/objects/items/jetpack.dm
Fixes a jetpack exploit.
Throw code pls.
:cl:
fix: fixed an exploit with jetpacks
/:cl:
=> Jetpack exploit fix

code/game/turfs/floor.dm
Title
:cl:
fix: Fixed being able to tear up empty space
/:cl:
=> Fixes being able to tear up empty space

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Title
:cl:
fix: Fix mech explosion being on deletion and not dying
/:cl:
=> Fix mech explosion being on del

code/datums/jobs/squads.dm
Fixes custom squad radio overriding other radio channels. Like common.
Henk
:cl:
fix: Fixes custom squad radio overriding other radio channels
/:cl:
=> Custom squad radio fix

code/__DEFINES/calibers.dm, code/modules/projectiles/ammo_types/energy_ammo.dm, code/modules/projectiles/ammo_types/miscellaneous_ammo.dm, code/modules/projectiles/guns/sentries.dm, code/modules/projectiles/magazines/sentries.dm, code/modules/reqs/supplypacks.dm
MJP did this!!!
Finishes flamer and laser sentries and makes them available in req properly
fixes them all using the same audio 
Finishes unused sprites and code
:cl:
add: Flamer and laser sentry now available for purchase in req
soundadd: all sentries now use gun-type specific sounds (ie shotgun sentry sounds like a shotgun) instead of all using the default sound
/:cl:
=> Finish unfinished sentries

_maps/map_files/Research_Outpost/Research_Outpost.dmm
The way this crashsite is positioned cuts off one of the entrances as well as well as one of the entrances to the southern disk site. Kinda cringe.
:cl:
balance: moves a landing site on the Research Outpost map for the Crash gamemode
/:cl:
=> moves crash site on research outpost

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
:cl:
spellcheck: Carrier: Fixes the description of the primordial ability
/:cl:
=> fixes Carrier ability pronoun correction + term standardization

code/modules/factory/unboxer.dm, code/modules/projectiles/gun_attachables/rail.dm, code/modules/projectiles/guns/specialist.dm, code/modules/projectiles/magazines/flamer.dm, code/modules/projectiles/magazines/specialist.dm, code/modules/reqs/supplypacks.dm, code/modules/vehicles/armored/ammo_magazine.dm
"TGMC players cannot read" mirrored by "TGMC players cannot write"
Stylistic standardization looks nice I guess
:cl:
spellcheck: standardizes use of capitalization in the requisitions supply console
spellcheck: updates some item names in the requisitions supply console
/:cl:
=> Requisitions general grammar and stylistic changes

code/datums/components/bump_attack.dm
Checks if human before setting target, and if they have an ID
Oopsie, copied above instead of below.
:cl:
fix: humans bumpslash xenos again
/:cl:
=> Fixes bumpslash mistake

code/modules/reqs/supplypacks.dm
fix
gotta get sg ammo lol
:cl:
fix: SG category not showing in req
/:cl:
=> fix sg category

code/__DEFINES/skills.dm, code/datums/skills.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
Splits large vehicles into mech and large vehicles
No more acs with mechs for good
:cl:
fix: ACs can no longer use any mech related objects as intended
/:cl:
=> Mech skill

code/datums/world_topic.dm
We need this for the server banner on tgstation13 to work correctly
=> Add identifier to world status response

code/modules/mob/living/carbon/human/human_attackhand.dm
=> Adds periods to the 20-79 germ level text

code/datums/outfits/quick_load_beginners.dm, code/game/objects/machinery/vending/beginner_vendor.dm, code/modules/clothing/modular_armor/xenonauten.dm, code/modules/paperwork/beginner_tutorials.dm, code/modules/paperwork/paper.dm, code/modules/projectiles/guns/shotguns.dm
Fixes typos in the beginner tutorial papers
All papers can now be read by using them in hand
Adds a point defense sentry engi loadout
Adds a mortar engi loadout
More variety in beginner engi loadouts. Explains things such as placing and protecting sentries, how to use a pump shotgun, what flechette does, how to use the loki module, how to place and use a mortar, how to use rangefinders, how to order more shells from req, etc.
:cl:
add: Added two new beginner engi loadouts, point sentry and mortar.
qol: Papers can now be read by using them in hand.
spellcheck: Fixed typos in the beginner tutorial papers.
/:cl:
=> Adds new beginner engi loadouts + fixes beginner tutorial typos

code/datums/loadout/loadout_seller.dm
Fixes an exploit to let you get other roles essential kit.
Fixes #15547
Fixes #16698
:cl:
fix: fixed a loadout exploit
/:cl:
=> Loadout fix

code/__DEFINES/is_helpers.dm, code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
Title
Being unable to interact with certain xeno structures just because of wrong run intent is confusing
:cl:
qol: You can now interact with xeno structures like tunnels as a baneling while running
/:cl:
=> Baneling can now interact with xeno structures while running

code/__DEFINES/equipment.dm, code/game/objects/items/coins.dm, code/game/objects/items/toys/toys.dm, code/modules/mob/living/carbon/carbon.dm
Moves throws from the perfect present tense to the simple present tense
See #17002
:cl:
spellcheck: Updates item throwing chat messages to use the simple present tense instead of the perfect present tense.
/:cl:
=> Tense cleaning with throws

code/datums/changelog/changelog.dm
=> Fix changelog

code/datums/components/seethrough_mob.dm
Fix "Toggle Seethrough" toggle being lost when gaining primo
Bugfix
:cl:
fix: Fix "Toggle Seethrough" toggle being lost when gaining primo
/:cl:
=> Fix "Toggle Seethrough" toggle being lost when gaining primo

code/modules/mob/mob.dm
What it says in the title
When you vend something you expect to be able to interact with it from the get-go
:cl:
qol: vendors now vend the item into your selected hand
/:cl:
=> Vendors now vend the item into your selected hand

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Because it's a fix.
:cl:
fix: Fixed hivemind's health hud/ui.
/:cl:
=> Fixes hivemind health hud/ui

.github/workflows/gbp.yml, tools/WebhookProcessor/github_webhook_processor.php, tools/pull_request_hooks/autoLabel.js, tools/pull_request_hooks/autoLabel.test.js, tools/pull_request_hooks/autoLabelConfig.js
Copypaste https://github.com/tgstation/tgstation/pull/89190
=> Fix PR labeling

code/__HELPERS/time.dm
Same issue as the other one
:cl:
fix: fixed the time of day being offset
/:cl:
=> Fix station time timestamp

code/modules/clothing/modular_armor/combat_robot.dm
title
:cl:
balance: combat robots may now wear the mimir armour module
/:cl:
=> Allows combat robots to wear mimir

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Charge no longer deducts plasma before the ability actually finishes.
This wasn't a issue for rav, but it makes bloodthirster omega buffed.
:cl:
fix: fixed bloodthirster charge being stronger than intended
/:cl:
=> Fix Ravager charge issue

code/game/objects/machinery/overwatch/military.dm
The LT Grandpa Nganga at south compound
LT Grandpa Nganga at south compound
:cl:
spellcheck: Grammar fix for the overwatch console
/:cl:
=> Overwatch grammar fix

.github/workflows/codeowner_reviews.yml
For https://github.com/tgstation/TerraGov-Marine-Corps/pull/17083
=> Ports tg action for pinging non-org codeowners

code/controllers/configuration/entries/game_options.dm, config/config.txt
These are unused and should be controlled by code anyway
=> Remove deprecated config option

code/datums/skills.dm
Mech pilot can now actually use mechs.
:cl:
fix: Mech pilots actually have mech skill
/:cl:
=> Mech skill fix

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Kurocracy decree
:cl:
balance: mech no longer has directional armor
/:cl:
=> removes mech directional armor

.dockerignore, code/__DEFINES/tgs.config.dm, code/controllers/subsystem/ticker.dm, code/modules/admin/server_verbs.dm, tools/tgs4_scripts/PreCompile.bat
Mirroring tg https://github.com/tgstation/tgstation/pull/89385
=> Remove all references to tgs3

code/modules/mob/dead/observer/observer.dm
It has a search feature
:cl:
qol: teleport verb menu is tgui now
/:cl:
=> teleport verb menu is tgui now

code/modules/projectiles/ammo_types/smartgun_ammo.dm, code/modules/projectiles/guns/rifles.dm
Better handling, more damage, less sunder.
Removed minimum range.
Actual changes changes below
<details>
**Aim slowdown** Reduced to .6 from .85
**Wield Delay**: Reduced to .75
**Fire Delay**: .45 [5]
**Damage**: Upped to 60. [40]
**Sunder**: Reduced to 3.5. [5]
**Shell Speed**: 5 [4]
Removed minimum range.
**
</details>
Target rifle kinda stinks right now so hopefully this makes it less bad. The removal of minimum range should make it more appealing for most ranges and the damage profile change should make it better to shoot at things.
:cl:
balance: Target rifle changes. It has better handling, damage and bullet travel time. But worse sunder.
/:cl:
=> Smart target rifle changes

code/game/objects/machinery/overwatch/military.dm, code/modules/screen_alert/command_alert.dm
TGMC players are lazy, mirroring the ic waay it does it
:cl:
qol: Mugshots announcements will automatically capitalize themselves
/:cl:
=> Auto Capitalize mugshot announcements

code/controllers/subsystem/tutorials.dm
[
](https://github.com/tgstation/tgstation/pull/89172)
:cl:
fix: fixed a tutorial error
/:cl:
=> Fix undeleted query in tutorial code

code/__HELPERS/icons.dm, code/_onclick/hud/parallax.dm, code/datums/greyscale/layer.dm, code/modules/asset_cache/assets/crafting.dm, code/modules/mob/living/silicon/ai/death.dm
see https://github.com/tgstation/tgstation/pull/89357 for details
:cl:
code: optimized certain operations run by hyperscale and certain icon systems
/:cl:
=> Optimizes icon exists, and makes a bunch of iconstates situations use it

code/modules/mob/mob_helpers.dm
(continued from #17135)
my bad :]
=> forgot one of the ghost notifications

code/game/objects/items/radio/detpack.dm
Exploit bad.
Fixes #17175
:cl:
fix: fixed detpacks not deleting after exploding
/:cl:
=> Detpack fix

code/controllers/subsystem/points.dm, tgui/packages/tgui/interfaces/Cargo.jsx
see title
Lets you know important things :)
:cl:
qol: The supply console now displays notes attached to certain supply packs
/:cl:
=> Req consoles now display a supply pack's notes

code/modules/projectiles/ammo_types/smartgun_ammo.dm, code/modules/projectiles/guns/rifles.dm
Tittle
Got overbuffed, course correction time
:cl:
balance: SG-62 buff's have been reverted
/:cl:
=> Reverts the SG-62 buffs

code/__HELPERS/icons.dm
=> Fix getflaticon

code/game/atoms/atom_movable.dm, code/game/objects/effects/landmarks/gamemode/campaign_reward_spawns.dm, code/game/objects/effects/landmarks/gamemode/campaign_vehicle_spawners.dm, code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm, code/game/objects/items/firesupport_binoculars.dm, code/game/objects/items/marine_gear.dm, code/game/objects/items/plantable_flags.dm, code/game/objects/items/radio/headset.dm, code/game/objects/machinery/computer/crew.dm, code/game/objects/machinery/computer/intel_computer.dm, code/game/objects/machinery/computer/marines_consoles.dm, code/game/objects/machinery/doors/poddoor.dm, code/game/objects/machinery/miner.dm, code/game/objects/machinery/overwatch/_overwatch.dm, code/game/objects/machinery/squad_supply/supply_console.dm, code/game/objects/machinery/squad_supply/supply_pads.dm, code/game/objects/machinery/vending/loadout_vendor.dm, code/game/objects/machinery/vending/new_marine_vendors.dm, code/game/objects/machinery/vending/quick_vendor.dm, code/game/objects/machinery/vending/vending.dm, code/game/objects/structures/campaign_structures/deploy_blockers.dm, code/game/objects/structures/campaign_structures/destroy_objectives.dm, code/game/objects/structures/sensor_tower.dm, code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/game/objects/structures/teleporter_array.dm, code/modules/mob/mob_defines.dm, code/modules/reqs/supply.dm, code/modules/vehicles/sealed.dm, code/modules/vehicles/unmanned/unmanned_vehicle.dm
Faction var was defined in like 500 different places, making it a nightmare if you wanted to get the faction of things generally, instead of one specific type of atom.
:cl:
code: Faction is defined at the AM level
/:cl:
=> Faction var at AM level

code/modules/mob/living/carbon/xenomorph/abilities.dm
bugfix
bugs bad
closes #17195
:cl:
fix: Valhalla drains no longer add larva points to the actual hive
/:cl:
=> [s] Valhalla drains no longer add burrowed larva points to the actual hive

code/datums/components/attachment_handler.dm, code/datums/storage/storage.dm, code/game/objects/items/binoculars.dm, code/game/objects/items/firesupport_binoculars.dm, code/game/objects/items/storage/holsters.dm, code/game/objects/items/tools/misc_tools.dm, code/game/objects/items/tools/policetape.dm, code/game/objects/machinery/computer/crew.dm, code/game/objects/machinery/miner.dm, code/game/objects/machinery/vending/new_marine_vendors.dm, code/game/objects/machinery/vending/quick_vendor.dm, code/game/objects/machinery/vending/vending_types.dm, code/game/objects/obj_defense.dm, code/game/objects/structures/crates_lockers/closets/secure/cargo.dm, code/game/objects/structures/crates_lockers/largecrate_supplies.dm, code/game/objects/structures/dropship_ammo.dm, code/game/objects/structures/dropship_equipment.dm, code/game/objects/structures/prop.dm, code/game/objects/structures/rappel_system.dm, code/modules/clothing/modular_armor/mark_one.dm, code/modules/clothing/modular_armor/modular.dm, code/modules/mob/mob.dm, code/modules/organs/limbs.dm, code/modules/power/fusion_engine.dm, code/modules/projectiles/guns/grenade_launchers.dm, code/modules/projectiles/magazines/specialist.dm, code/modules/reqs/supplypacks.dm
given that tgmc players are wholly incapable of reading, it is difficult to argue for the benefits of this PR.
:cl:
spellcheck: You will no longer detach armor attachments "to" armour
spellcheck: Inventory-related warnings will now display an article
spellcheck: Officer's sword spellchecking
spellcheck: The quartermaster's stamp & locker will no longer be arbitrarily capitalized
spellcheck: Adds \improper to a lot of things that need it
spellcheck: Capitalizes projectile damage text
spellcheck: Adds a period to the armor equip interruption text
spellcheck: Req capitalization (Those who know)
spellcheck: Tactical binoculars -> pair of tactical binoculars
spellcheck: Removes the random space from face-mangling text
spellcheck: Makes grenade launchers report what grenade launcher type is …
=> A few grammar/style changes

code/game/verbs/ooc.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Mech can now be shuffled by xenos, but it cannot shuffle xenos
also fixed that dumb runtime
:cl:
balance: Mech can now be shuffled by xenos
/:cl:
=> Mech can now be shuffled by xenos

code/modules/mob/dead/observer/observer.dm
Adds Toggles and Follow subheaders for spectators.
Allows easier navigation.
:cl: The_Man
qol: Added Toggles and Follow subheaders to spectators.
/:cl:
=> Added subheaders Toggles and Follow to spectators.

code/game/objects/items/power_cells.dm, code/modules/projectiles/ammo_types/mech_ammo.dm, code/modules/projectiles/ammo_types/miscellaneous_ammo.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm, code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm, code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
Disables some weapons and changes others numbers in accordance with the doc
:cl:
balance: rebalanced mech weapons
/:cl:
=> Does mech balance numbers

code/modules/admin/admin_verbs.dm
arg fix
:cl:
fix: fixed admin smites not logging
/:cl:
=> Fix admin smite logs

code/controllers/subsystem/shuttle.dm, code/modules/admin/verbs/map_template.dm, tgui/packages/tgui/interfaces/ShuttleManipulator.jsx
still messy but at least it doesnt bluescreen
also fixed map shuttle upload which was disabled since 6+years cus uhhh reasons
:cl:
fix: fixed shuttle manipulator bluescreening, and not showing all options
fix: fixed admin shuttle uploads being disabled for 6+ years for no reason
/:cl:
=> Fix admin shuttle stuff

code/modules/admin/verbs/chat_commands.dm
You can now check the current seasonals from the comfort of prc
:cl:
add: Added the !tgs seasonals command for checking the current seasonals from discord
/:cl:
=> Adds !tgs seasonals

.github/workflows/discord_pr_announce.yml
See https://github.com/tgstation/tgstation/pull/89578
:cl:
code: Discord PR announcer bot is back
/:cl:
=> Readds discord PR announcer

tgui/packages/tgui/interfaces/MechVendor/index.tsx
:cl:
fix: fixed mech weight bar in the mech builder ui not coloring correctly
/:cl:
=> Minor improvement to mech weight bar

code/__DEFINES/MC.dm, code/controllers/master.dm, code/controllers/subsystem.dm, code/modules/unit_tests/subsystem_init.dm, tgui/packages/tgui/interfaces/ControllerOverview/OverviewSection.tsx, tgui/packages/tgui/interfaces/ControllerOverview/SubsystemDialog.tsx, tgui/packages/tgui/interfaces/ControllerOverview/SubsystemRow.tsx, tgui/packages/tgui/interfaces/ControllerOverview/SubsystemViews.tsx, tgui/packages/tgui/interfaces/ControllerOverview/contants.ts, tgui/packages/tgui/interfaces/ControllerOverview/filters.ts, tgui/packages/tgui/interfaces/ControllerOverview/index.tsx, tgui/packages/tgui/interfaces/ControllerOverview/types.ts
See more or less
https://github.com/tgstation/tgstation/pull/82769/files
https://github.com/tgstation/tgstation/pull/81461/files
https://github.com/tgstation/tgstation/pull/64448/files
https://github.com/tgstation/tgstation/pull/82139/files
:cl:
code: Added some tracking for tick allocation to subsystems
admin: added focus mode var to controllers, which can be toggled to get a focused profile of ONE subsystem
admin: added admin tgui for viewing MC and controller statuses
/:cl:
=> New MC profiling and debugging tools

code/modules/admin/debug_verbs.dm
tg port
:cl:
admin: added edge dev tools verb to admins for UI debugging
/:cl:
=> Add edge debug tools

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm, code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Fixes skipping 1 fire when going out of arc
Fixes not being able to start/single fire outside of arc
:cl:
fix: fixed mech spin-to-fire
/:cl:
=> Fixes some mech spin-firing stuff

code/modules/vehicles/mecha/_mecha.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm, code/modules/vehicles/mecha/combat/gygax.dm, code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
These were apparently very wrong since kuro didnt know how mech movespeeds worked
:cl:
fix: fixed mech movespeeds being very out of wack with intended values
/:cl:
=> Fix mech sprint numbers

strings/tips/marine.txt, strings/tips/meme.txt, strings/tips/xeno.txt
Title.
Submit your own tips to depart TGMC knowledge to anyone in lobby screen!
:cl:
spellcheck: 2025 tip update!
/:cl:
=> 2025 tip update!

code/modules/admin/server_verbs.dm
:cl:
fix: fixed reload-admins not working
/:cl:
=> Fix reload admins

code/modules/vehicles/mecha/combat/gygax.dm
See cl
:cl:
fix: fixed mech sprint not updating the overlay correctly
/:cl:
=> Fix mech sprint icon

code/controllers/subsystem/ticker.dm
https://discord.com/channels/498569646014857217/502919898700447775/1342873025271562292
=> Add tgs event

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Apparently it was supposed to take fire damage
:cl:
balance: mech take fire damage
/:cl:
=> mech take fire damage

code/modules/vehicles/mecha/equipment/mecha_equipment.dm, code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Check wasnt high enough
:cl:
fix: Fixed not all mech items respecting arms being blown off
/:cl:
=> Fixes not all mech items respecting arms being blown off

code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Gonna be replace with new modules later and this is causing issues rn
:cl:
balance: Removed melee core speed boost
/:cl:
=> Remove melee core speed boost

code/modules/vehicles/mecha/equipment/weapons/weapons.dm
title
Kurocracy
:cl:
balance: Mech can now reload on the move
/:cl:
=> Mech can now reload on the move

code/controllers/configuration/configuration.dm, code/modules/admin/server_verbs.dm
This wouldve been useful when ops guys were figuring out how to make config work
:cl:
admin: Added reload-config admin verb
/:cl:
=> Add reload-config admin verb

code/modules/xenomorph/maw.dm
see #17073 (I fucked up my branch management and had to remake this PR)
:cl:
add: The Acid Maw may now fire a facehugger shot
del: The Acid Maw may no longer fire an acid gas shot
add: The Acid Jaws may now fire an acid gas shot
del: The Acid Jaws may no longer fire a facehugger shot
/:cl:
=> Swaps hugger xortar and acid XOBs

code/__DEFINES/text.dm, code/game/objects/structures/droppod.dm
:cl:
fix: Fixed drop pods not centering screen text
/:cl:
=> Fix drop pods not centering screen text

.github/workflows/run_integration_tests.yml
Free runner time https://github.com/tgstation/tgstation/pull/89724
=> remove redundant mysql server

code/modules/admin/view_variables/mass_edit_variables.dm
From a  review in https://github.com/tgstation/tgstation/pull/89548/files
=> Change a var in mass modify

code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Relic of old mech, interfering with tests. will remove with new sprite stuff
=> Disable tfoot generator for mech

code/modules/admin/admin_verbs.dm
Your favourite badmins have been doing some misclicking
:cl:
admin: Remove from tank admin verb has a confirmation popup now
/:cl:
=> Remove from tank has a confirmation popup

code/_onclick/hud/ai.dm, code/_onclick/hud/ghost.dm, code/_onclick/hud/screen_objects/menu_text_objects.dm, code/_onclick/hud/screen_objects/screen_objects.dm, code/_onclick/hud/xeno/xeno.dm, code/game/objects/machinery/door_control.dm, code/game/objects/machinery/fire_alarm.dm, code/game/objects/machinery/vending/vending_types.dm, code/modules/buildmode/buttons.dm, code/modules/power/apc/apc.dm
Wow, technology.
This makes the game feel cleaner and more polished. It's so simple yet effective.
:cl:
qol: Mousing over clickable UI elements and wall mounted machinery now turns your cursor into a pointer
/:cl:
=> Mousing over clickable UI elements and wall mounted machinery now turns your cursor into a pointer

code/controllers/subsystem/chat.dm
This has been broken for god knows how long
Runtime bad, blackbox working good
:cl:
fix: Fixed chat subsystem resend blackbox runtime
/:cl:
=> Fixes chat subsystem resend blackbox runtime

code/modules/admin/panels/permission_panel.dm
Passes in the right asset datum and also sends it to the client instead of trying to shove it into the admin datum
Runtime bad
:cl:
admin: Perms change actually sends over assets and doesn't runtime
/:cl:
=> Perms change actually sends over assets and doesn't runtime

code/controllers/subsystem/ticker.dm
https://discord.com/channels/498569646014857217/502919898700447775/1345163510732034159 see convo above this
=> Move tgs roundend sync event to block Reboot

.github/workflows/discord_pr_announce.yml
https://github.com/tgstation/tgstation/pull/89732/files
=> Discord commit bot new look

code/game/objects/machinery/buttons.dm
Can't have contents for something that doesn't exist
runtime bad
:cl:
fix: Fixed a valhalla button runtime
/:cl:
=> Fix valhalla button runtime

code/datums/elements/strappable.dm, code/modules/ai/ai_behaviors/human_mobs/grenades.dm, code/modules/ai/ai_behaviors/human_mobs/weapon_module.dm, code/modules/projectiles/guns/shotguns.dm
AI weapon select order fixes.
Ensured AI will never deactivate/unwield weapons in edge cases.
AI will use unique action for pump action guns (SH-35 etc)
AI can reload closed receiver guns (i.e. DB, revolver, etc)
Improving AI incrementally.
:cl:
fix: Fixed a few AI weapon issues
/:cl:
=> AI weapon fixes

code/game/verbs/ooc.dm, code/modules/tgui_panel/external.dm
Sorted the OOC tab, added Communication and Fix subheaders.
Easier to find needed buttons.
:cl: The_Man
qol: Added Communication and Fix subheaders to OOC tab.
/:cl:
=> Sorted the OOC tab. Added Communication and Fix subheaders.

code/datums/components/seethrough_mob.dm
It'd try to access images and mob from a client that doesn't exist anymore if someone logged out with seethrough on.
Also makes the ability icon state update itself to off and set the activity bool to off.
Runtime bad, relog experience good good
:cl:
fix: Fixed a runtime when disconnecting with xeno seethrough on, ability icon for it will also update properly
/:cl:
=> Fix seethrough runtime and improve relog experience with it

code/_globalvars/lists/mobs.dm, code/modules/mob/living/carbon/xenomorph/evolution.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
…ive_caste
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/16220
Also detached some stuff from instanctiated types so you can use types for it, and added return types and assertions
Also new get_all_caste_members getter
:cl:
fix: fixed strains ignoring max caste limits
fix: Strain swap will now show all strains you can swap, including the base caste, excluding your own instead of all strains
/:cl:
=> Improve some xeno helpers and fix strains allow bypass of maximum_active_caste

code/modules/mob/living/carbon/human/human_species.dm
Monkey smart
Monkey madness
:cl:
add: simian intelligence increased
/:cl:
=> Monkey business

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
wwwww
:cl:
fix: Fixed failed mech dashes still using power
/:cl:
=> Fixes failed mech dashes still using power

code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Infinite shooting
:cl:
balance: You can no longer rearm mech weapons while firing
/:cl:
=> You can no longer rearm mech weapons while firing

code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
Fixes a typo causing some cursed behavior in some cases.
:cl:
fix: fixed one handed weapons appearing wielded by NPC's
/:cl:
=> AI weapon equip fix

code/datums/elements/shrapnel_removal.dm, code/modules/ai/ai_behaviors/human_mobs/heal_procs.dm, code/modules/ai/ai_behaviors/human_mobs/healing.dm, code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
Some general improvements to retreat AI, so NPC's won't get stuck, and will react more consistantly in a sensible manner.
Also a couple random runtime fixes.
AI better
:cl:
code: Improved some NPC behavior when retreating
/:cl:
=> AI Retreat improvements

dependencies.sh
3.1 isn't compiling on tgsatan for some reason.
Need to test merge this
=> Update to rust-g 3.7.0

code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
I did a funny.
Unfunny it.
:cl:
fix: NPC's actually wield their guns again
/:cl:
=> Actual AI wield fix

code/modules/vehicles/_hitbox.dm
Fixed SOM tank offsets, tivi did a funny with the render PR.
:cl:
fix: fixed SOM tank offsets
/:cl:
=> SOM tank offset fix

code/game/objects/structures/dropship_equipment.dm, code/game/objects/structures/flora.dm
See below
:cl:
fix: fixed dropship attachment points layering too low
fix: fixed tallgrass layering over too much
/:cl:
=> Fix some layering

code/modules/admin/verbs/centcom_podlauncher.dm
Was using the wrong glob wrongly
:cl:
fix: Fixed pod launcher not always working
/:cl:
=> Fixes pod launcher not always working

code/game/turfs/iron_floor.dm
Proper multiz seethroughness, for mappers to use
:cl:
add: Glass floors are seethough
/:cl:
=> Glass floors are seethough

code/_globalvars/lists/objects.dm, code/game/atoms/atom_movable.dm, code/game/objects/structures/stairs.dm, tgmc.dme
teegee copypasta
for mappers to use
:cl:
add: Added multiz stair subtype
/:cl:
=> Adds multiz stairs

code/game/objects/items/explosives/bombvest.dm
=> remove var relating to old bombvest filter

code/game/objects/effects/temporary_visuals/miscellaneous.dm, code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm, code/modules/mob/living/carbon/xenomorph/update_icons.dm
Tweaks lewds staggered shriek effect and gives it to queen
https://streamable.com/vcwovd
:cl:
qol: Added queen visually warping shriek wave
/:cl:
=> Queen visual warping shriek wave

code/modules/vehicles/_hitbox.dm
Just removing dumb hardcoded stuff
:cl:
fix: tank riding should work better now for non-mobs
/:cl:
=> Fixes bad casting in tank desants

code/game/objects/effects/effect_system/foam.dm
Foam has submerge component and footstep override now.
:cl:
add: Foam submerges like fire or tallgrass
/:cl:
=> Foam submerge

code/game/turfs/open/openspace.dm
=> Fix openspace not being seethrough in SDMM

code/_onclick/item_attack.dm, code/game/objects/effects/temporary_visuals/miscellaneous.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/xenomorph/attack_alien.dm
adds blood splatter when you attack someone with a sharp melee or xeno claws also adjusts the particles a bit
https://github.com/user-attachments/assets/99dd8346-1d9a-4bed-be96-02a42294336b
looks cool
:cl:
add: blood splatter on sharp melee and xeno claws
code: adjusted blood splatter particles
/:cl:
=> Blood Splatter on Melee

code/_onclick/hud/hud.dm, code/_onclick/hud/new_player.dm, code/_onclick/hud/screen_objects/menu_text_objects.dm
I did it mari see!!!
:cl:
fix: fixed a runtime with new player huds
/:cl:
=> Fix new player hud runtime

code/__DEFINES/mecha.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm, code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm, code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
Mixing these meant disabling stuff for xvh was kinda sucky
:cl:
fix:  you can reattach all mech weapons properly now
/:cl:
=> Splits greyscale can attach and can vend flags

code/modules/mob/dead/observer/login.dm, code/modules/mob/dead/observer/observer.dm
Useful for seeing whats going oon
:cl:
fix: ghosts can see mech hud now
/:cl:
=> Ghosts see mech hud now as part of squad hud

code/__DEFINES/rust_g.dm, code/controllers/subsystem/sounds.dm
Splitting up upcoming sound refactor
:cl:
code: added ability to cache sounds serverside
/:cl:
=> Adds SSsound caching

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
SpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpinSpin
:cl:
qol: Mech turns are now silent
/:cl:
=> Mech turns are now silent

code/datums/components/ai.dm, code/game/data_huds.dm, code/game/objects/items/radio/headset.dm
NPC's will no longer show as DNR on the minimap/hud
Clarity
:cl:
fix: NPC's no longer show as DNR on minimap/hud
/:cl:
=> NPC defib markers

_maps/map_files/Metnal_Operation/Metnal_Operation.dmm
Readds engi disk that got nuked for some reason
Makes the nuke push EAST wall ticker so it doesn't get PC that easily
Choke above underground bar made a bit bigger
Misc changes to flooring and shit 
Buf gix
:cl:
fix: fixed disk not spawning
/:cl:
=> Metnal bugfix and other changes

code/game/objects/structures/prop.dm, code/game/turfs/open.dm
Fixes the stencil letters not working
:cl:
fix: fixed floors layering too high
/:cl:
=> Fixes floors layering incorrectly

code/game/objects/effects/aliens.dm
Another did this even work before?
:cl:
fix: Fixed acid layering under what its on top of sometimes
/:cl:
=> Fix acid layering under what its on top of sometimes

code/game/objects/machinery/vending/marine_vending.dm
Reverts tgstation/TerraGov-Marine-Corps#12459
Derringer is, infact, strong enough to warrant a limit.
:cl:
balance: Derringer is once again limited in the gun vendor
/:cl:
=> Revert "Removes the cap of the derringer in the vendor"

code/modules/vehicles/mecha/mecha_movement.dm
Kurocracy decree
:cl:
qol: Mech overload automatically disables on running out of power
/:cl:
=> Mech overload automatically disables on running out of power

code/game/alternate_appearance.dm
Multiz maps should update the plane properly now
=> Update alt appearance planes on Zchange

code/game/objects/items/gift_wrappaper.dm, code/game/objects/machinery/computer/camera_advanced.dm, code/game/objects/machinery/computer/camera_console.dm, code/game/objects/machinery/kitchen/gibber.dm, code/game/objects/structures/rappel_system.dm, code/modules/atmospherics/machinery/atmosmachinery.dm, code/modules/atmospherics/machinery/components/unary_devices/cryo.dm, code/modules/client/client_procs.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm, code/modules/mob/living/silicon/ai/ai.dm, code/modules/mob/living/silicon/ai/freelook/eye.dm, code/modules/mob/mob.dm, code/modules/recycling/disposal.dm
Forgot to use a helper, fixes wierd layering stuff with overwatch, cas etc
:cl:
fix: Fixed rendering wonkiness with non-self camera perspectives
/:cl:
=> Fixes wonkiness with non-self camera perspectives

code/modules/mob/living/carbon/xenomorph/update_icons.dm
Me when I make a last second arg change and everything explodes
:cl:
fix: fixed queen shriek waves being hilariously slow 
/:cl:
=> Fixes slow mo shriekwaves

code/__DEFINES/is_helpers.dm, code/modules/mob/living/carbon/xenomorph/charge_crush.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
No more crusher oneshot sorry fellow crusher mains
:cl:
balance: Crusher charges always target mech legs
/:cl:
=> Crusher charges always target legs

code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
I smrt.
:cl:
fix: fixed NPC's not using guns
/:cl:
=> NPC gun equip fix

code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
Fixed NPC's storing offhand slot holders.
:cl:
fix: fixed NPC's sometimes storing offhand placeholders
/:cl:
=> Fix NPC item storing

code/game/turfs/turf.dm
fix
:cl:
fix: Openspace on multiz is unweedable
/:cl:
=> Open space is unweedable

code/modules/transport/transport_module.dm
30 and 400 tiles is a little much lol
:cl:
fix: The tram launches you through the windshield at mach 1 instead of mach 3
/:cl:
=> The tram no longer launches you through the windshield at mach 3

code/modules/mob/living/carbon/xenomorph/update_icons.dm
oops
:cl:
fix: fixed screech being delayed by half a second
/:cl:
=> Fix shriek sleeping

code/game/atoms/atom_movable.dm, code/modules/mob/living/living.dm, code/modules/xenomorph/recovery_pylon.dm
Noticable for like leevators and stuff
:cl:
fix: fixed some things like elevators screwing up rendering when changing z
/:cl:
=> Fix moved not updating planes properly

code/modules/mob/living/carbon/xenomorph/update_icons.dm
didnt test but plane was becoming detached!!
:cl:
fix: Probably fixed xeno wounds not layering properly in multiz
/:cl:
=> Probably fix xeno wounds not layering properly in multiz

code/modules/xenomorph/trap.dm
Render might have fluffed this
:cl:
fix: Traps will now layer lower again
/:cl:
=> Traps will layer lower

code/modules/ai/ai_behaviors/human_mobs/hazard_avoidance.dm
More chat lines for different hazards.
_"Well I've never seen a hazard like this before."_
:cl:
qol: Added some more NPC hazard chat lines
/:cl:
=> More NPC Hazard lines

code/__DEFINES/mecha.dm
society
:cl:
fix: Mechs will no longer sparkle on spawn
/:cl:
=> Mechs will no longer sparkle on spawn

code/modules/vehicles/armored/ammo_magazine.dm, code/modules/vehicles/armored/armored_weapons.dm, code/modules/vehicles/armored/interiors/breech.dm
Loading a round now calls out the ammo type loaded, adds a var to set the ammo type for future ammunition.
https://github.com/user-attachments/assets/fed5d053-119a-471d-8d49-b3793ed85de9
Gunner's also shout "On the Way!" when firing LTB.
https://github.com/user-attachments/assets/ca207d54-6ac5-49d3-9b7d-e54c88a956ed
:cl:
add: Tank Loaders now shout the ammo type when loaded ("HE, Up!")
add: Tank Gunners now shout when they are firing LTB ("On the way!")
/:cl:
=> Sabot, Up! (More tank callouts)

code/game/turfs/floor_types.dm
Title.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/17116.
Dupe bad.
:cl:
fix: Fixed an exploit with metal rods.
/:cl:
=> Fixes rod dupe exploit

code/game/atoms/atom_movable.dm
Also fixes runners being able to fly
:cl:
fix: Standing on tank no longer lets you fly
fix: Runners can no longer fly
/:cl:
=> Standing on tank no longer lets you fly

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
No idea what the hell was going on here
:cl:
fix: fixed some issues with xenos when not using their own mob as eyes
/:cl:
=> Fix xenos being unable to look up/down

code/modules/transport/elevator/elev_indicator.dm, code/modules/transport/elevator/elev_panel.dm
Lateload crap
:cl:
fix: fixed lift indicators not showing anything
fix: fixed elevator control panels erroring sometimes when they shouldnt
/:cl:
=> Elevator fixes

code/__DEFINES/ai.dm, code/datums/outfits/npc_marines.dm, code/modules/clothing/modular_armor/xenonauten.dm, code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/guns/shotguns.dm
Some more NPC presets for TGMC.
Easier testing/badminning
:cl:
add: Added some more TGMC NPC presets
/:cl:
=> More TGMC NPC presets

code/datums/actions/item_action.dm, code/modules/clothing/modular_armor/modular.dm, code/modules/clothing/suits/marine_armor.dm
Help their feeble human frens with light.
:cl:
add: NPC's actually use their suit lights now
/:cl:
=> NPCs use their suit lights

code/modules/mob/living/living.dm
idk how tg lives like this this sucks ASS
starting by cleaning up usability a little before refactoring how it sends the eye, and making it cancel instead of doing whatever that was
:cl:
qol: look up/down should feel better to use
/:cl:
=> Deshittifying lookup/down P1

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Fixes jaw(maw? whatever the fuck the small one is) stopping the xob from being built.
:cl:
fix: fixed maw stopping xob from being built
/:cl:
=> Jaw limit fix

code/modules/vehicles/mecha/equipment/weapons/weapons.dm
:cl:
fix: Allows reloading multiple mech weapons again
/:cl:
=> Allows reloading multiple mech weapons again

code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
:cl:
qol: Selecting a mech weapon in the builder UI again will unselect it
/:cl:
=> Selecting a mech weapon in the builder UI again will unselect it

code/datums/elements/turf_transparency.dm
overeager when trying to fix baseturfs
:cl:
fix: transparency should try to show space again
/:cl:
=> make transparency iconstate fallback space again

code/game/objects/effects/overlays.dm, code/game/objects/items/explosives/grenades/grenade.dm, code/game/objects/items/power_cells.dm
Suprise suprise more cm shitcode
:cl:
fix: Fix grenades warning icon being black on multiz
/:cl:
=> Fix grenade warning icon being black on multiz

code/modules/ai/ai_behaviors/ai_behavior.dm, code/modules/ai/ai_behaviors/xeno/xeno.dm
Fixed minions not attacking people.
:cl:
fix: The pacifist movement amongminions has been stamped out
/:cl:
=> Minion fix

code/modules/projectiles/ammo_types/mech_ammo.dm, code/modules/projectiles/ammo_types/rocket_ammo.dm, code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Fixes the rocket doing 100 sunder (oohmagah), makes it do 15 instead
Buffs shotgun since its kinda weak rn, now it has a bit less falloff and does sunder
Zoom module is gone from HvX
Balance good
:cl:
balance: Mech rocket no longer completely deletes armor
balance: Mech shotgun does sunder and has less falloff
balance: Removed zoom module
/:cl:
=> Mech changes

code/controllers/configuration/config_entry.dm
the fuck
:cl:
fix: Fixed config defaults being inverted for 6 years
/:cl:
=> Fix config defaults being inverted for 6 years

code/modules/lighting/lighting_static/static_lighting_source.dm
Uncommenting code
:cl:
fix: fixed static lighting piercing multiz
/:cl:
=> fix static lighting piercing multiz

_maps/map_files/Sulaco/TGS_Sulaco.dmm
Changes sulaco consoles in cic to military version as on other maps
Fix good
:cl: Atropos
fix: Sulaco now has working squad overwatch consoles
/:cl:
=> Fixes sulaco CIC consoles

code/modules/transport/transport_module.dm
it oneshots crusher rn lol
:cl:
balance: Drastically reduced damage on being hit by a tram
/:cl:
=> Drastically reduce damage on being hit by a tram

code/game/objects/machinery/camera/camera.dm
tgcopypaste
:cl:
add: Added multiz camera support
/:cl:
=> Multiz camera support

code/modules/mob/living/carbon/carbon.dm
:cl:
fix: Fixed colored NV goggles
/:cl:
=> Fix colored NV goggles

code/modules/vehicles/mecha/mecha_actions.dm, code/modules/vehicles/vehicle_actions.dm
kuro said so, and anti spammer measure
:cl:
balance: Mech cloak activates fire cooldown and has a small cd
/:cl:
=> Mech cloak activates fire cooldown and has a small cd

code/modules/vehicles/mecha/mecha_defense.dm
Mech projectiles now log who shot them when they hit mech
:cl:
admin: Mech projectiles now log who shot them when they hit mech
/:cl:
=> Mech projectiles now log who shot them when they hit mech

code/modules/vehicles/mecha/equipment/weapons/weapons.dm
uhhh yea idk what this even breaks
=> Fix oopsie with mech flash

code/__DEFINES/equipment.dm, code/game/atoms/atom_movable.dm, code/game/turfs/open/openspace.dm
probably a better set of flags to use?
:cl:
fix: Fixed openspace jumping
/:cl:
=> Fixes openspace jumping

code/modules/mapping/cordon.dm, code/modules/transport/elevator/elev_panel.dm, code/modules/transport/tram/tram_controller.dm, code/modules/transport/tram/tram_displays.dm, code/modules/transport/tram/tram_power.dm, code/modules/transport/transport_module.dm
Theres a reason we have the define oops
:cl:
fix: Fix trams/elevator stuff being slashable (and doing nothing)
/:cl:
=> Fix trams/elevator stuff being slashable (and doing nothing)

code/datums/beam.dm
You will not believe what the fix is
:cl:
fix: Fix beams being black on multiz
/:cl:
=> Fix beams being black on multiz

code/modules/vehicles/mecha/equipment/mecha_equipment.dm
No idea what the hell i was thinking
:cl:
fix: Fixed mech weapons visually duping
/:cl:
=> Fix mech weapons visually duping

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
oops
:cl:
fix: Fixed mech leg repair not fixing movespeed
/:cl:
=> Fix mech leg repair not fixing movespeed

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
player feedback is good
:cl:
qol: Mech limb being destroyed now plays a sound
/:cl:
=> Mech limb being destroyed now plays a sound

dependencies.sh
wierd stuff in https://github.com/tgstation/TerraGov-Marine-Corps/actions/runs/14127600047/job/39580123608?pr=17550 (works on local) hope this fixes it
=> Bump CI byond ver to prod ver

code/__DEFINES/configuration.dm, code/controllers/configuration/config_entry.dm, code/controllers/configuration/entries/dbconfig.dm, code/controllers/configuration/entries/game_options.dm, code/controllers/configuration/entries/general.dm
Fixes defaults properly and fixes keyed_list configs
=> More config fixes

code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Didnt test but uhh wrong var, lol
:cl:
fix: Fixed mech GL not spinning the mech
/:cl:
=> Fix mech GL not spinning the mech

code/__HELPERS/spatial_info.dm, code/game/sound.dm
per title, also uses spatial search instead of checking the entire Z
code for ai and tank could be cleaned up but uhhhh ill get around to it since I also want to fix this having way too high range like tg did
:cl:
add: Added multiz sound support
code: added support for non-wallpiercing sounds
/:cl:
=> Multiz sound support (also optimization and nonwallpiercing sound support)

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
another dunno how this was working
:cl:
fix: Warlock shield no longer falls on multiz
/:cl:
=> Warlock shield no longer falls on multiz

code/__DEFINES/dcs/signals/signals_tgui.dm, code/__DEFINES/text.dm, code/_onclick/hud/map_popups.dm, code/_onclick/hud/map_view.dm, code/controllers/subsystem/statpanel.dm, code/game/objects/items/devices/spyglasses.dm, code/game/objects/items/devices/tablets.dm, code/game/objects/machinery/computer/camera.dm, code/genesis_call.dme, code/modules/admin/view_variables/color_matrix_editor.dm, code/modules/client/preferences.dm, code/modules/client/preferences_ui.dm, code/modules/mob/new_player/poll.dm, code/modules/tgui/tgui_window.dm, code/modules/tgui_input/text.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm, code/modules/vehicles/mecha/mecha_ui.dm, tgmc.dme, tgui/.prettierignore, tgui/.prettierrc.yml, tgui/packages/tgui/interfaces/TextInputModal.tsx, tgui/packages/tgui/layouts/Window.tsx, tgui/public/tgui.html
Batch of fixes
Including the pref ui is finally not tiny edition for real this time!!!
https://github.com/tgstation/tgstation/pull/90317/files
https://github.com/tgstation/tgstation/pull/90285/files
https://github.com/tgstation/tgstation/pull/90256
https://github.com/tgstation/tgstation/pull/90255/files
https://github.com/tgstation/tgstation/pull/90215/files
https://github.com/tgstation/tgstation/pull/90039/files
https://github.com/tgstation/tgstation/pull/90277/files
Todo https://github.com/tgstation/tgstation/pull/90124 in a seperate pr
:cl:
fix:  fixed a bunch of tgui stuff
fix: fixed preference preview being tiny
fix: fixed tgui byond windows being tiny until they were edited
code: removed warning for being on 516
/:cl:
=> Misc 516/TGUI stuff updates

code/modules/admin/panels/permission_panel.dm
SQLtime should not be used for sql ironically since byonds time procs are broken (as usual)
=> Use NOW() in permission panel

code/modules/projectiles/guns/_shared_ammo_objects.dm
Looks neato and kuro decree
:cl:
fix: melting fire no longer emits light and just emissively glows
balance: melting fire now deals damage to vehicles
/:cl:
=> Melting fire fixes/walance

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm, code/modules/vehicles/mecha/mecha_actions.dm
Take 6 seconds to apply instead of 10 and disable your weapons & movement while being used
Being vulnerable while repairing is like, good
:cl:
balance: Mech repairpacks take 6 seconds to apply instead of 10 and disable your weapons & movement while being used
/:cl:
=> Mech repairpacks make you vulnerable while using them

code/__DEFINES/spatial_gridmap.dm, code/__HELPERS/_lists.dm, code/controllers/subsystem/spatial_gridmap.dm, code/game/atoms/atom_movable.dm, code/modules/mob/login.dm, code/modules/spatial_grid/cell_tracker.dm, tgmc.dme
Our spatial grids werent registering cliented mob on creation properly, so I went with the less lazy solution of just updating it to TG standard
:cl:
fix: fixed sound not always workign immediately on spawn
refactor: updated spatial tracking code somewhat
/:cl:
=> Spatial grid update

_maps/arachne.json, _maps/combat_patrol_base.json, _maps/debugdalus.json, _maps/iteron.json, _maps/multiz_debug.json, _maps/pillar_of_spring.json, _maps/sulaco.json, code/__DEFINES/maps.dm
THIS TIME IT WILL WORK
Fixes EORD and shipmaps
:cl:
fix: fixed space tiles again
/:cl:
=> Fix remaining Zs that should set baseturfs (last pr I swear)

code/__DEFINES/dcs/signals/signals.dm, code/__HELPERS/filters.dm, code/game/atoms/atom_appearance.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm, code/modules/vehicles/mecha/mecha_actions.dm
emissives for mech still showing & them being blocked out by the normal map
:cl:
fix: fixed wierd behavior with mech cloak and emissives
/:cl:
=> Fix warped invis-emissive interactions

code/game/atoms/atom_movable.dm, code/modules/vehicles/mecha/mecha_movement.dm
Mech did some snowflake crap for dirs, which I didnt fix (lmao) this fixes that
:cl:
fix: Fixes mech being diagonal sometimes (again)
/:cl:
=> Fixes mech being diagonal (again)

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
broke this behaviour while cleaning up my code
:cl:
fix: Mech relimb slashes will relay to torso when limb is destroyed
/:cl:
=> Mech relimb slashes will relay to torso when limb is destroyed

code/datums/interior/interior_tank.dm, code/modules/vehicles/armored/interiors/ammo_rack.dm
ammorack and door overlay layering under floor
:cl:
fix: fixed som ammorack layering under the floor
fix: fixed som tank exit hatch layering under the floor
/:cl:
=> Som tank interior layering fix

tgui/packages/tgui-say/516/TguiSay.tsx, tgui/packages/tgui-say/516/helpers.ts, tgui/packages/tgui-say/516/styles/main.scss
https://github.com/tgstation/tgstation/pull/90395
https://github.com/tgstation/tgstation/pull/90395
:cl:
fix: fixed 516 tgui say not focusing on open all the time
/:cl:
=> fix 516 tgui say focusing

code/modules/vehicles/mecha/equipment/weapons/weapons.dm
forgot to set the cooldown AFTER the fire oops
:cl:
fix: Fixed being able to magdump mech rockets
/:cl:
=> Fixes being able to magdump mech rockets

code/__DEFINES/_click.dm, code/_onclick/click.dm
m4 and m5 are undocumented and supported now, this is so they dont fire lclick
did the defines in click code as well cus why nto
yay mouse api changes
:cl:
fix: fixed m4 and m5 left clicking
/:cl:
=> stub new mouse buttons

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_conqueror.dm
same multiz fix as the usual
targets vehicles so at least ONE ability of conqs works on vehicles lmao
should do the rest too later
No Conq abilities dont work on vehicles rn lol
:cl:
balance: conquerors obliteration works on vehicles now
fix: fixed conqueror obliteration effects on multiz
/:cl:
=> Conq obliteration multiz fix and it targets vehicles now

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
it is now just a bunch of rapid moves in sequence, since it was very easy to never get trapped as mech
kurocracy decree
:cl:
balance: Mech dash no longer lets you go over things
/:cl:
=> Mech dash no longer lets you go over things

code/game/verbs/who.dm
Ping display when pressing Who verb for even more reasons to cope
Main TG has it - most games have it - why shouldn't we have it?
testing was done to ensure quality
:cl: Atropos
add: You can now see people's ping with Who verb!
=> Adds ping display to Who verb

code/modules/admin/fun_verbs.dm
during admin datum refactor
:cl:
fix: Admin check hive status works again
/:cl:
=> Admin check hive status works again

code/modules/admin/fun_verbs.dm
:cl:
fix: Fixed admin announcement only allowing one character
/:cl:
=> Fix admin announcement only allowing one character

code/datums/beam.dm
idk this worked so
:cl:
fix: Fixed tesla rifle not working
/:cl:
=> Fixes tesla rifle not working

tgui/packages/tgui-bench/package.json, tgui/packages/tgui-panel/chat/renderer.jsx, tgui/packages/tgui-panel/package.json, tgui/packages/tgui-panel/panelFocus.ts, tgui/packages/tgui-say/package.json, tgui/packages/tgui/package.json, tgui/packages/tgui/styles/functions.scss, tgui/packages/tgui/styles/interfaces/Mecha.scss, tgui/packages/tgui/styles/interfaces/NuclearBomb.scss, tgui/packages/tgui/styles/layouts/Window.scss, tgui/yarn.lock
… update
https://github.com/tgstation/tgstation/pull/90336
:cl:
fix: fixed misc tgui bugs
fix: fixed chat scroll breaking sometimes
/:cl:
=> Sass cleanup, fix scrolling breaking for the chat sometimes, tguicore update

code/datums/actions/ability_actions.dm, code/modules/mob/living/carbon/xenomorph/castes/king/abilities_conqueror.dm
Caught in the crossfire oops lol, but deserved
=> Relowercase action_cooldown_checked

code/controllers/subsystem/minimap/minimaps.dm
testing locally with debugdalus worked fine
:cl:
fix: minimap properly opens before you change zlevels again
/:cl:
=> minimap hotfix?

code/modules/balloon_alert/balloon_alert.dm
only get cliented mobs for balloon alert to viewers
:cl:
code: optimized balloon alerts
/:cl:
=> Baloon alert optimization

code/datums/keybinding/living.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_defines.dm
Looking down code was kinda messy for like, no reason?
This simplifies it, makes it track the direction you're looking, and uses a holder so the movement isn't extremely jittery
https://streamable.com/qj0zed
:cl:
refactor: Overhauled how looking up and looking down function. they should now not jitter, and trying to look up/down while already doing so will cancel the previous look up/down in the opposite direction
/:cl:
=> Deshittifys looking P2

code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
getter without a return value lmao
:cl:
admin: winget in sdql works
/:cl:
=> Winget sdql fix

tgui/packages/tgui-say/515/constants.ts, tgui/packages/tgui-say/516/constants.ts
516 say is case sensitive i think
:cl:
fix: Fixed tgui-say squad radio radio colors
/:cl:
=> Fix radio colors

code/datums/browser.dm, code/modules/admin/panels/permission_panel.dm, code/modules/admin/view_variables/view_variables.dm, code/modules/client/client_defines.dm, code/modules/client/client_procs.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/client/preferences_ui.dm, code/modules/mob/mob.dm, code/modules/tgui/tgui.dm, code/modules/tgui_input/say_modal/modal.dm, code/modules/tgui_panel/external.dm, interface/skin.dmf, tgui/packages/tgui-panel/index.tsx, tgui/packages/tgui-panel/settings/SettingsGeneral.tsx, tgui/packages/tgui-panel/settings/middleware.ts, tgui/packages/tgui-panel/settings/scaling.ts, tgui/packages/tgui-panel/themes.ts, tgui/packages/tgui-say/515/TguiSay.tsx, tgui/packages/tgui-say/516/TguiSay.tsx, tgui/packages/tgui-say/516/helpers.ts, tgui/packages/tgui/backend.ts, tgui/packages/tgui/drag.ts, tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx, tgui/packages/tgui/layouts/Window.tsx, tgui/packages/tgui/styles/functions.scss, tgui/packages/tgui/styles/layouts/TitleBar.scss, tgui/packages/tgui/styles/main.scss
https://github.com/tgstation/tgstation/pull/90416
https://github.com/tgstation/tgstation/pull/90418
Tivi and tivi can play the game on 516 properly now
:cl:
add: Added new mechanics or gameplay changes
qol: You can now change the size of the command bar and info buttons bar (top of the stat panel with changelogs)
qol: added a preference to scale window sizes up or not (off by default as before 516)
fix: improved non-standard monitor scaling on 516
/:cl:
=> DPI fixes for 516

code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
50 mag and 300 reserve to 10 mag and 60 reserve
Its effectively bottomless rn
:cl:
balance: mech flamer has much less ammo in the mag and in reserve
/:cl:
=> Divides all mech flamer ammo numbers by 5

code/game/objects/items/devices/tablets.dm
Removes access checks from tablets.
Pointless access restriction.
I tried to show the marine who was with me the tablet and they were denied and it was tragic.
Untested, will get to soon.
:cl:
del: Command tablets no longer check access for viewing.
/:cl:
=> Unrestricts overwatch tablets.

code/modules/mob/new_player/new_player.dm
Hit observe and it tells you marine respawn time and xeno queue wait time if its longer than 1
cat gif here
:cl:
qol: If larva queue is more than 2 people it will show how long it is in the tgui "are you sure" popup when you try to observe
/:cl:
=> If larva queue is more than 2 people it will show how long it is in the tgui "are you sure" popup when you try to observe

html/statbrowser.css
https://github.com/tgstation/tgstation/pull/90341
:cl:
qol: Stat panel is only scrollable if needed
/:cl:
=> Stat panel is only scrollable if needed

code/datums/jobs/job/shipside.dm
Fixes mechs not spawning at the proper amount, which is 40' pop.
Mech working good
:cl:
fix: Fixed mechs not spawning at the correct pop
/:cl:
=> Fixes mech spawning

code/__DEFINES/text.dm, code/datums/weather/weather.dm, code/datums/weather/weather_types/acid_rain.dm, code/datums/weather/weather_types/ash_storm.dm, code/datums/weather/weather_types/sand_storm.dm, code/modules/screen_alert/misc_alert.dm
Will show on the right side, aligns right
Better than the fluff + sound indicator
:cl:
qol: Dangerous weather will now play a screen alert warning when starting
/:cl:
=> Dangerous weather will now play a screen alert warning

code/modules/vehicles/armored/armored_weapons.dm, code/modules/vehicles/mecha/_mecha.dm, code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Erm, missing checks
:cl:
fix: Fix mech/tank being able to use equipment while stunned
/:cl:
=> Fix mech/tank being able to use equipment while stunned

code/modules/client/preferences_ui.dm, tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Ah eto bleh
:cl:
qol: Elaborates what the multiz performance preference does better
fix: Fixes multiz preference not looping properly
/:cl:
=> Fixes multiz preference not looping properly + elaborates what it does better

code/__DEFINES/icon_smoothing.dm
Randomly saw this comment lol, no clue what this even broke
=> Fixes random smoothing define being set wrong

_maps/map_files/Arachne/TGS_Arachne.dmm, _maps/map_files/Sulaco/TGS_Sulaco.dmm
Fixes AC + PO access on arachne (previously none of those 2 had access)
removes random space computers on sulaco (???)
Fix good - like how did nobody even try to fix the doors on arachne its been broken since i remember wtf
:cl: Atropos
fix: fixed PO+AC access on arachne
fix: removed random space computers on sulaco
/:cl:
=> Small Sulaco + Arachne fixes

code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm, code/modules/xenomorph/maw.dm
This should be the correct var to set for layering reasons, maybe tm would be ok?
:cl:
code: Swaps all pixel y to pixel z for falling from sky effects
/:cl:
=> Use pixel z for falling from sky effects

code/game/objects/structures/droppod.dm, code/modules/mapping/space_management/space_reservation.dm
Was dropping it on the soft cordon turfs which dropped it to lz
Ideally need to tweak how dumping is handled and fix the inbetween for hard and soft cordon but this fixes the actual issue for now
:cl:
fix: Droppods will no longer randomly appear near the LZ sometimes
/:cl:
=> Droppods will no longer randomly appear near the LZ sometimes

code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm, tgui/packages/tgui/interfaces/MechVendor/MechAssembly.tsx, tgui/packages/tgui/interfaces/MechVendor/data.ts
Better to use + fixes that mech weapons are nullable in the tsx type
:cl:
qol: The Alert for not meeting certain requirements in the mech builder to deploy is no longer a solo popup
qol: Added requirement to mount at least one gun and one engine to the mech so people dont deploy without them
/:cl:
=> Mech builder deployment improvements

code/__DEFINES/admin.dm, code/__DEFINES/cooldowns.dm, code/__DEFINES/logging.dm, code/__HELPERS/logging/game.dm, code/controllers/configuration/entries/general.dm, code/modules/admin/fun_verbs.dm, code/modules/admin/panels/ban_panel.dm, code/modules/admin/panels/player_panel.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/request_internet_sound.dm, code/modules/logging/categories/log_category_game.dm, config/config.txt, tgmc.dme
yet another sloppy port from main tg
now with double the effort!
Its annoying to get prayers / ahelps about music requests
and dedicated verb would be easier for the players to use 
also tibi said yes
Testing was done to ensure it works.
:cl: Atropos
add: Request music verb has been added! you can now easily request music
/:cl:
=> Request music verb

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm, code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Wah wah days since broken game 0
:cl:
balance: XvH Mech has 300 instead of 500 hp as originally intended
/:cl:
=> Mech has 300 instead of 500 hp as originally intended

code/modules/projectiles/guns/_shared_ammo_objects.dm
simply duh
:cl:
fix: Fire now falls down Zlevels
/:cl:
=> Fire now falls down Zlevels

code/modules/admin/verbs/request_internet_sound.dm
Title - im not going to list everything they could do as they dont even know themself
I TOLD YOU TIVI TO TM THIS WA!!! THIS I WHAT I WANTED TO AVOID
also fix of security very good
:cl: Atropos
fix: fixed mentors being able to see admin stuff
/:cl:
=> Fixes mentors being able to use admin stuff (request music verb)

code/game/objects/machinery/computer/dropship_picker.dm
title
More ways to find griefers good
how did nobody did this?
:cl: Atropos
admin: Added Tadpole logging (who picked it)
/:cl:
=> More TAD logging

code/game/objects/machinery/vending/new_marine_vendors.dm
Essential synth loadout (in the vendor) now includes soap
Kuro aproved
:cl: Atropos
balance: Synths essential kit now includes soap
/:cl:
=> Gives synth soap

code/modules/vehicles/cars/car.dm, code/modules/vehicles/mecha/mecha_movement.dm
Look when I say I want telemazor this isnt what I mean
:cl:
fix: Vehicles are no longer capable of phasing accross spacetime
/:cl:
=> Vehicles are no longer capable of phasing accross spacetime

code/modules/admin/holder.dm, code/modules/admin/verbs/datumvars.dm
https://github.com/tgstation/tgstation/pull/90667
https://github.com/tgstation/tgstation/pull/90665
=> Admin security fixes

code/game/world.dm
So I was looking at possible root causes for why lewds server fix worked and found 2 oddities
A) TGSreboot being called way too early
B) Logging wasnt shutting down correctly on non hard reboots
C) We were sending players to the rebooted server in 2 places, based on my local testing this SHOULDNT cause an issue but we shouldnt have that happening in the first place
Also added a reboot message cus why not
:cl:
qol: When the server reboots it will post a message in the chat
code: Improved code relating to restarting the server
/:cl:
=> Fixes oddities in world/Reboot()

.github/alternate_byond_versions.txt, .github/max_required_byond_client.txt, code/__byond_version_compat.dm, code/_globalvars/bitfields.dm, code/_onclick/hud/hud.dm, code/_onclick/hud/rendering/plane_master_group.dm, code/_onclick/hud/rendering/render_plate.dm, code/modules/admin/view_variables/debug_variable_appearance.dm, dependencies.sh
Wait until https://github.com/tgstation-operations/server-config-tgmc/pull/16
Go gulper be free port all the shitass tg tgui prs!!!
:cl:
code: 516 byond is now required to host the game
/:cl:
=> 516 is required for compile and tests

code/modules/admin/verbs/request_internet_sound.dm
Title
say if wrong changelog or sumthing
request sound sounds weird - internet music is more clean
:cl: Atropos
spellcheck: Request Internet Sound -> Request Music 
/:cl:
=> Renames internet sound to internet music

code/game/verbs/who.dm
Lets see if this argument is bait or real while cherry picking screenshots that support my argument
:cl:
admin: Admins now see how many lobby players there and and how many are afk
/:cl:
=> Admins now see how many lobby players there and and how many are afk

code/game/area/area.dm
Made them into overlays and less bright
:cl:
fix: Fire alarms now are less bright
/:cl:
=> Fire alarm brightness fix

code/modules/admin/fun_verbs.dm
I wonder who broke this haha
As a reminder to all Mentors dont abuse it so we can have nice things!!!!
:cl:
fix: mentors can subtle message again
/:cl:
=> mentors can subtle message again

code/modules/mob/living/living.dm, code/modules/unit_tests/create_and_destroy.dm
Mechs/tanks
:cl:
fix: Look up/down track the thing you're inside
/:cl:
=> Look up/down track the thing you're inside

code/modules/buildmode/submodes/boom.dm
Throw range wasnt used in the explosion itself so uh yeah
Fix good!
:cl: Atropos
fix: fixed build mode explosion mode (throw in explosions wasnt working)
/:cl:
=> Fixes build mode explosion mode

.gitignore
=> add vscode internal db stuff to gitignore

_maps/map_files/Sulaco/TGS_Sulaco.dmm, code/modules/mob/living/simple_animal/friendly/cat.dm
rage bait title
We are removing martin again
this time replacing them with someone else...
INTRODUCING MARTINA
(read code for more info)
:cl: Atropos
fix: Replaced 2nd martin on sulaco with martina (very original)
/:cl:
=> Removes extra martin from sulaco

code/game/objects/machinery/miner.dm
As title says miners will do a little ping (+message) when they're done!
uh i think this is QOL isnt it
knowing when the miner is done instead of imaginary timers seems good
and QOL good!
:cl: Atropos
qol: Miners now give noise (+message) when theres a shipment ready!
/:cl:
=> Miners ping when they're done processing

code/modules/mob/death.dm
Whenever someone gets gibbed it logged
More logging good.
and this one was what we wanted for months
:cl: Atropos
admin: Added simple gib log
/:cl:
=> Adds gib logging

_maps/map_files/Sulaco/TGS_Sulaco.dmm, code/modules/mob/living/simple_animal/friendly/cat.dm
Cleans up shitcode from https://github.com/tgstation/TerraGov-Marine-Corps/pull/17718
:cl: Atropos
refactor: Cleaned up martina code
/:cl:
=> Clean up of martina shitcode

code/_onclick/hud/rendering/plane_master_group.dm, code/_onclick/hud/rendering/render_plate.dm
https://github.com/tgstation/tgstation/pull/90523
luv me byond
:cl:
fix: Fixed Byond windows in tgui crashing dreamseeker
/:cl:
=> Fix Byondui crash

code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Accidentally removed this
:cl:
fix: Fixed crusher instakilling mechs
/:cl:
=> Fix crusher instakilling mechs

tools/pull_request_hooks/removeGuideComments.js
https://github.com/tgstation/tgstation/pull/90820
Finally someone who isnt me fixed it
=> Guide commment remove will no longer steal edits

interface/skin.dmf, tgui/packages/tgui-panel/settings/scaling.ts
https://github.com/tgstation/tgstation/pull/90796
Status bar (bottom left) dpi scaling
:cl:
qol: Status bar (bottom left text thing) now scales with monitor scaling settings
/:cl:
=> Status bar dpi scaling

code/modules/admin/verbs/adminhelp.dm
Title
i forgor to add this in the last pr whoops 
1 less button to press each time is also good
:cl: Atropos
admin: Tiering tickets unmarks them
/:cl:
=> Tiering the ticket Unmarks it

tools/pull_request_hooks/removeGuideComments.js
https://github.com/tgstation/tgstation/pull/90866
=> Fix guide comments remover

code/controllers/subsystem/advanced_pathfinding.dm, code/modules/ai/ai_behaviors/ai_behavior.dm, code/modules/ai/ai_behaviors/human_mobs/human_mob.dm, code/modules/ai/ai_behaviors/xeno/puppet.dm, code/modules/ai/ai_behaviors/xeno/xeno.dm, code/modules/ai/ai_node.dm, code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
AI goal nodes will work again properly, instead of freezing the NPC's.
Also fixed some other bugs with AI nodes that I discovered. Specifically with AI nodes not cleaning up correctly, although there is an unresolved bug that I slapped a bandaid on and a TODO, since it seems to date back to the original implementation and I can't figure out what the actual cause is.
Bug fix.
:cl:
fix: fixed AI goal nodes
/:cl:
=> Fix AI goal nodes

code/__DEFINES/loadout.dm
In https://github.com/tgstation/TerraGov-Marine-Corps/pull/17724 i forgor to add to loadouts this fixes that 
fix good
:cl: Atropos
fix: fixed soap not appearing in loadouts
/:cl:
=> Adds soap to loadouts

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Title
Game unplayable with this fr
:cl: Atropos
fix: Small table fix on POS
/:cl:
=> Small POS Fix

code/datums/status_effects/debuffs.dm
Always test every single commit, im stupid. You CAN and WILL fuck up even the smallest of changes.
https://github.com/user-attachments/assets/73e72bf4-aa5b-4ec4-9a6e-c71401286f2c
bug bad..
:cl:
fix: Sniper stacking works properly now for real 
/:cl:
=> Stacking debuff adjustment adjustment

code/__DEFINES/flags.dm, code/__DEFINES/fonts.dm, code/__HELPERS/game.dm, code/_onclick/hud/screen_objects/screen_objects.dm, code/datums/greyscale/config_types/new_mech.dm, code/datums/mind.dm, code/game/atoms/_atom.dm, code/game/objects/items.dm, code/game/turfs/walls/wall_types.dm, code/modules/mob/living/carbon/xenomorph/evolution.dm, code/modules/transport/tram/tram_doors.dm
These were either simple, needed checking and were uneeded, or deprecated
:cl:
fix: fixed aghost interaction with get larva
/:cl:
=> Cleans out some todos

code/modules/admin/smites/bloodless.dm
Title
Fix good
:cl: Atropos
admin: fixed bloodless smite 
/:cl:
=> Bloodless smite fix

code/modules/mob/mob.dm
Title
Show player panel was broken for god knows how long and more shortcuts is usually good imo
:cl: Atropos
admin: Added Player panel to VV (select options button)
/:cl:
=> Adds PP to VV

CONTRIBUTING.md
Fixes a good bit of grammar, removes old links that haven't been updated since 2018, removes references to old game mechanics, etc. 
Not player facing, only contributor.
=> Contributing.md update

code/datums/components/harvester.dm
Title
Dunno, fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/17132  though.
I guess this makes pistol sword vali more usable? 🤮 
~merge https://github.com/tgstation/TerraGov-Marine-Corps/pull/16950~
:cl:
fix: Harvester right click attack works
/:cl:
=> Right click attack with harvesters call their proc

code/modules/mob/living/carbon/human/human_attackhand.dm
It's joever
bug bad
:cl:
fix: Can no longer pat out melting fire on yourself
/:cl:
=> Melting fire self extinguish bugfix

code/__DEFINES/colors.dm, code/controllers/configuration/entries/general.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/preferences_verbs.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, config/config.txt
Reverts tgstation/TerraGov-Marine-Corps#17810
i didnt ask for opinions first so uh... whoops
and majority of admins says no to this
=> Revert "Admins can change their ASAY colors"

code/modules/admin/verbs/datumvars.dm, code/modules/admin/view_variables/topic.dm
see https://github.com/tgstation/tgstation/pull/90763/files
:cl:
fix: fixed security exploit concerning mentor permissions
/:cl:
=> Fix href view vv exploit for mentors

code/modules/vehicles/armored/__armored.dm, code/modules/vehicles/armored/vehicle_collision.dm
I died to this instakilling me
I died to this instakilling me
:cl:
balance: Tank wam will target mech legs
/:cl:
=> tweaks veh collision and makes it target legs on mech

code/modules/shuttle/navigation_computer.dm
Also optimized it by pasting tg code
:cl:
fix: Fixes tad preview while moving not working
/:cl:
=> Fixes tad preview while moving not working

tgui/packages/tgui/interfaces/EscapePod.tsx
Simple UI, untested
:cl:
code: Typescripted escape pod UI
/:cl:
=> TSX escape pod

code/modules/power/smes.dm, tgui/packages/tgui/interfaces/Smes.tsx
Simple conversion untested
:cl:
code: converted smes UI to TSX
/:cl:
=> TSXify SMES

code/game/objects/machinery/computer/dropship_weapons.dm, code/game/objects/structures/dropship_equipment.dm, tgui/packages/tgui/interfaces/CAS.tsx
This is the alamo version.... simple enough anyway
:cl:
code: typescripted CAS shuttle UI
/:cl:
=> TSXify Cas

tgui/packages/tgui/interfaces/PortableVendor.tsx
Simple enough , untested
:cl:
code: typescripted portable vendors
/:cl:
=> TSXify portable vendor

code/game/objects/machinery/computer/nuke_disk_generator.dm, tgui/packages/tgui/interfaces/NukeDiskGenerator.tsx
simple enouhg conversion, even found a bug this time
:cl:
fix: fixed an issue with the progressbar on nuke disk generators
code: typescripted nuke disk generators
/:cl:
=> TSXifies nukedisk generators

tgui/packages/tgui/interfaces/MarineCasship.tsx
Using enums, fixing button contents etc
:cl:
code: cleaned up CAS Plane UI backend
/:cl:
=> CAS plane UI housekeeping

_maps/map_files/generic/Admin_Level.dmm
Title
Ai not working in tdome requiring you to place your own nodes bad
Ai working right after placing allowing you to test faster good
:cl: Atropos
admin: Added Ai nodes to tdome (Ai can move and work again)
/:cl:
=> Adds ai nodes to the thunderdome

code/modules/projectiles/projectile.dm
Was making occasional death tiles
:cl:
fix: fixed a runtime causing death tiles
/:cl:
=> Fix untargetted projectiles runtime

code/__DEFINES/dcs/signals/signals.dm, code/modules/keybindings/bindings_client.dm, code/modules/keybindings/setup.dm, code/modules/mob/living/silicon/ai/ai.dm, code/modules/mob/mob.dm
ports https://github.com/tgstation/tgstation/pull/43241
https://github.com/user-attachments/assets/3f0bb8e6-f08e-43c5-b482-417044b63fd5
AI QoL must grow
:cl:
add: AIs now can set a location via Ctrl + number and jump their camera to that location by pressing that number
/:cl:
=> RTSlike camera jump binding for AI

code/modules/ai/ai_behaviors/human_mobs/healing.dm
=> compile fix

code/_onclick/human.dm, code/modules/mob/living/carbon/human/_species.dm, code/modules/mob/living/carbon/human/species_types/monkeys.dm
Fixes some issues with monkeys.
Monkeys no longer do MONSTROUS melee damage due to hitting twice per hit, one of which ignores all armour.
Monkeys have pass low structure again.
Monkeys have stamina.
Removed the code for random movement since they are all AI demons now.
For reference, currently monkeys do somewhere around 15 times more damage per hit than humans do, due to naturally far stronger melee hits, hitting twice, and ignoring armour on half of it.
:cl:
fix: Monkeys no longer do hugely more melee damage than intended
fix: Monkeys have pass low structure again
fix: Monkeys have stamina
/:cl:
=> Monkey fixes

code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm, code/modules/ai/ai_behaviors/human_mobs/human_mob.dm, code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm, code/modules/reagents/chemistry/reagents/drinks/drink_reagents.dm, code/modules/reagents/chemistry/reagents/food.dm, code/modules/reagents/reagent_containers/food/snacks.dm
Nutriment no longer has a 0.5 multiplier on the only use of nutriment_factor (all numbers ahve just been halved instead. Why god?)
Replaced a whole bunch of incorrect snowflake code using magic number multipliers with a proc that uses the actual vars, to calculate how much nutrition X amount of nutriment will create.
Fixed NPC's checking total reagent amount instead of bite amount, for food/snacks.
Better/working code good.
:cl:
fix: fixed NPC's some times not eating when they should
/:cl:
=> Nutriment fixes

code/modules/ai/ai_behaviors/human_mobs/engineering.dm, code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm, code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
Engineer NPC's can be told to repair miners.
Bot do more stuff.
:cl:
add: Engineer NPC's can repair miners
/:cl:
=> NPC's repair miners

_maps/modularmaps/big_red/bigredsecornervar3.dmm
title
fix good
also big thank you lumi for finding the issue
:cl: Lumipharon, Atropos
fix: fixed some ai nodes on big red
/:cl:
=> Big red south east ai nodes fix

code/modules/admin/admin_verbs.dm
port of https://github.com/tgstation/tgstation/pull/54939
What title says - previously show all logs was just all categories put together but still separated
this makes it so it shows everything but in order what happened making it easier to understand 
instead of having to copy paste and align times etc.
its better
Someone(lepi) requested it and i think its a good idea
:cl: uomo91, Atropos
admin: show all logs in PP now shows logs by time instead of categories 
/:cl:
=> 'Show all logs' now shows logs by time

code/datums/jobs/job/fallen.dm
oversight in code means you cant test supersoldier in valhalla,
this has been tested locally to work
people not being able to test supersoldier in valhalla is bad
:cl:
add: You can now spawn as Prototype Supersoldier in Valhalla
/:cl:
=> Adds Prototype Supersoldier to Valhalla

code/_onclick/ventcrawl.dm
Title 
days since tivi broke game: 0
Fix very good
:cl: Atropos
fix: Fixed vent crawling (finally!!!)
/:cl:
=> Vent crawling fix

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Title - few stray pipes i noticed and fixed
Fix good
:cl: Atropos
fix: fixed few pipes on prison station
/:cl:
=> Small prison pipe fixes

code/datums/personal_statistics.dm
Now you can see exactly how much damage that mg60 user did to you
:cl:
add: Added personal statistic for FF recieved
/:cl:
=> Adds personal statistic for FF recieved

code/modules/ai/ai_behaviors/human_mobs/human_mob.dm, code/modules/ai/ai_behaviors/human_mobs/weapon_module.dm
Fixes human NPC's not using their melee weapons.
Fix an order of operation issue when starting AI that would miss certain mob actions
:cl:
fix: fixed a couple of NPC bugs
/:cl:
=> NPC weapon fixes

code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/guns/specialist.dm
VSD nerfs overall.
Main Rifle (which is the SCAR thing iirc) has been *nuked*. It fired DMR rounds at *rifle fire rate.* It still fires DMR rounds at half damage and with 0.35 fire delay instead of 0.2. I also rebalanced the burst while I was at it.
MG fires at .25 which is the standard for rifle/heavy guns. No reason this should get special treatment.
Breaching shotgun is 1.5 from 1 second. Its a wall deleter so having it fire every second is kinda goofy. This is kinda goofy in general conceptually but I think its ok.
Autocannon fires at .45 (since its firing tank shells. This is kinda stupid when flak ammo is right there but w/e) like the tank autocannon does since its the same ass shells. It wields slightly faster to compensate.
VSD is comically overtuned in a decent chunk of ways. …
=> Rebalances VSD guns in a few ways.

dependencies.sh, tools/ci/install_rust_g.sh
Lets see if this even runs with the ddos
=> update rust to 3.11.0 and stop building it for CI

tgui/packages/tgui/interfaces/Mortar.jsx
Title
I can finally play arty
:cl:
fix: Fixes howi and mortar guis displaying NaN for latitude offset
/:cl:
=> Fixes howi and mortar guis displaying NaN for latitude offset

code/modules/reqs/supplypacks/weapons_packs.dm
heayvlaser
soul removal tbqh
:cl:
spellcheck: typo in heavylaser supply datum corrected (heayvlaser -> heavy_laser)
/:cl:
=> heayvlaser

code/modules/projectiles/guns/shotguns.dm
drops unwielded recoil to 3, and wielded recoil to 0.5
i dunno i never play marine Mack asked me to do this 
:cl:
balance:  Double barrel unwielded recoil from 4 to 3
balance:  Double barrel wielded recoil from 1 to 0.5
/:cl:
=> Reduce Double Barrel recoil

code/game/objects/structures/stairs.dm
Makes stairs resistant to everything for real this time (i tested it)
Fix good
:cl:
fix: fixed z level stairs being destructible
/:cl:
=> ACTUALLY fixes zstairs

code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
Fixes a bug where Spray Acid Line didn't acid_spray_act when it should of.
Bugfix.
:cl:
fix: Spray Acid Line now correctly extinguishes fire, stuns humans, etc.
/:cl:
=> Spray Acid Line Fix

code/datums/jobs/job/marines.dm, code/datums/jobs/job/shipside.dm
Title
Fix = good
:cl: Atropos
fix: fixed job descriptions displaying incorrect times
/:cl:
=> Job description fixes

code/__DEFINES/traits.dm, code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm, code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm, code/modules/mob/living/carbon/xenomorph/castes/widow/mutations_widow.dm, tgmc.dme
Adds a total of 3 mutations all for Warlock.
| Shell | Hive Toughness | Being adjacent to any resin wall grants 10/15/20 soft armor in all categories. |
| Spur | Web Yank | Leash Ball's cooldown is set to 80/65/50% of its original cooldown. Interacting with any Snaring Web will cause you to channel for 1 second which will stun and pull in leashed humans. |
| Veil | Incubator | Birth Spiderling's cooldown is set to 80/65/50% of its original cooldown. |
:cl:
add: Widow now has 3 new mutations that they can purchase if their hive has enough biomass and mutation structures. Not accessible without admin intervention for now.
/:cl:
=> Mutations: Widow

code/datums/gamemodes/campaign/loadout_items/SOM/belt.dm, code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
Fixes some items not having proper black/white lists in place.
:cl:
qol: Campaign: Fixed some missing blacklist/whitelist restrictions in loadouts
/:cl:
=> Campaign loadout black list/white list fixes

_maps/map_files/Vapor_Processing/Vapor_Processing.dmm
Northeast cave was space so you'd spawn as xeno and immediately die.
Space areas bad
:cl:
fix: Fixed an area on Vapor Processing
/:cl:
=> Fixes vapor processing area

code/_onclick/ventcrawl.dm, code/modules/atmospherics/machinery/atmosmachinery.dm
Title
More logging = good
:cl: Atropos
admin: Vent crawling (entering, exiting) is now logged (view round logs)
/:cl:
=> Vent crawling logging

code/datums/components/beacon.dm
Reverts tgstation/TerraGov-Marine-Corps#18004
Supply console cannot target beacons on the ground.
=> Revert "Radiopack beacon moves with you (the revival)" 

code/game/objects/items/stacks/sheets/glass.dm, code/game/objects/items/stacks/sheets/mineral.dm, code/game/objects/items/stacks/sheets/sheet_types.dm
Basically a lot of stuff had their recipes not appear 
as example wood iron and glass
now everything is correctly working
fix = good
:cl: Atropos
fix: fixed recipes not appearing on some materials (eg. wood, iron, glass)
/:cl:
=> Recipes not appearing fix

code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Fixes a mech weapon runtime and maybe a harddel.
Fixes mech windups not working if you move.
:cl:
fix: fixed a runtime with mech weapons
fix: Mech weapon windups work on the move like man portable weapons.
/:cl:
=> Mech fixes

code/game/turfs/snow.dm
Fixes a runtime when snow turfs are replaced by something else.
:cl:
fix: fixed a runtime with acid when snowtiles are replaced
/:cl:
=> Snow acid fix

code/modules/vehicles/hover_bike.dm
Fixed a layer issue on the hover bike, something with multiz messed up the layers.
:cl:
fix: fixed a layer issue on the SOM hoverbike
/:cl:
=> Hoverbike layer fix

_maps/map_files/Sulaco/TGS_Sulaco.dmm
Fixed one button having wrong ID
rearranged vendors in req and added loadout vendor
added some temporary walls to prevent people getting deleted for entering disposals (days since tivi broke game: 0)
fixes/improvements = good
:cl: Atropos
add: Added loadout vendors in req on sulaco
fix: fixed incorrectly wired button on sulaco
/:cl:
=> Small sulaco fixes

code/datums/outfits/freelancers.dm, code/game/objects/effects/landmarks/corpsespawner.dm, code/game/objects/machinery/vending/marine_vending.dm, code/modules/clothing/modular_armor/attachments/modules.dm, code/modules/clothing/suits/marine_armor.dm, code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/magazines/pistols.dm
Fixes my fumbles with ERT updates, that were found for now.
:cl:
fix: fixes SG-60 inhand sprites.
fix: fixes typepaths for freelancer armor.
fix: PMC SG-25 is now available in valhalla vendor.
fix: Fixes replicating MK90M4 pistol magazine in valhalla vendor.
fix: fixes missing items for freelancer loadouts.
/:cl:
=> Fixes for ERT updates.

code/modules/vehicles/armored/som_tank.dm, code/modules/vehicles/hover_bike.dm
Fix hover tank and bike animating pixel_y instead of pixel_z.
Will cause funny layering issues as it bobs up and down due to sideview.
:cl:
fix: fixed a minor visual issue with hover vehicle hover animations
/:cl:
=> Hover animation fix

code/datums/elements/shrapnel_removal.dm
I missed a couple of spots so the trait wasn't being removed in all cases as intended.
Bug fix
:cl:
fix: fixed NPC's sometimes getting stuck after removing shrapnel
/:cl:
=> Shrap trait fix

tgui/packages/tgui-bench/package.json, tgui/packages/tgui-dev-server/package.json, tgui/packages/tgui-panel/package.json, tgui/packages/tgui-panel/settings/SettingsGeneral.tsx, tgui/packages/tgui-say/package.json, tgui/packages/tgui-setup/package.json, tgui/packages/tgui/interfaces/ColorMatrixEditor.tsx, tgui/packages/tgui/interfaces/MedScanner/index.tsx, tgui/packages/tgui/interfaces/ParticleEdit/EntriesBasic.tsx, tgui/packages/tgui/interfaces/PlaneMasterDebug.tsx, tgui/packages/tgui/interfaces/Smes.tsx, tgui/packages/tgui/package.json, tgui/packages/tgui/stories/Input.stories.tsx, tgui/yarn.lock
Press the funny yarn button to update everything. This should fix the movement stuck thing with TGUI windows.
Sticky movement bad.
:cl:
fix: Probably fixed sticky movement from TGUI windows
code: Updated TGUI-core
/:cl:
=> tgui-core update
