tgstation/TerraGov-Marine-Corps

code/game/objects/structures/window.dm

Fixes windows flickering in and out of existance when being shot.
Objects update icon every time they take damage, but because windows use smoothing, every hit they queue themselves for smoothing again, but then base window code sets the icon to an invalid state, leading to no sprite for a split second before smoothing procs.
:cl:
fix: fixed a flicker issue with windows when taking damage
/:cl:

Window fix

---

code/modules/reqs/supply.dm
tgui/packages/tgui/interfaces/Cargo.jsx

Same orders now stack.
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/16237 by making the pending/denied/approved orders menu miles more optimized both on the network and rendering end. 
Also makes large orders easier to read.
Looks like this:
:cl:
qol: Makes large orders easier to read
fix: Fixes bug that can crash game on particularly large orders
code: Vastly optimized req request packets
/:cl:

Optimizes and declutters the requests panel

---

code/modules/mob/living/silicon/ai/ai.dm

Fixes AI being spawned twice
Makes it so that AI only gets spawned once, so that it doesn't send two announcements, the first one with incorrect name, instead only the second one with correct information.
:cl:
fix: Fixed AI double spawning
/:cl:

Fixes AI double spawning

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm

Converts the area that marines would normally get stuck podding into, to a empty nature reserve 
Less sad marines being stuck until xenoes come on and fr- kill them.
:cl:
balance: The area east of LZ2 has been converted into a nature reserve that you can no longer pod into and get stuck in.
/:cl:

Removes area where marines get trapped podding in on Big Red

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Changes the signal ID for the left side privacy shutters to 1
Currently it's bugged so that the OR2 shutters open both of them.
Thanks CrystalNole for reminding me of this
:cl:
fix: Pillar of Spring medbay shutters 1 are now linked to it's proper button
/:cl:

Fixes surgery privacy shutters on pos

---

_maps/map_files/generic/Admin_Level.dmm

Adds a few marine spawners to the shooting range of Valhalla.
Campaign has started becoming a lot more prevalent, and with that HvH gameplay as a whole. Adding marine spawners to Valhalla will make it easier to test weapons in an HvH setting, along with testing the effects of friendly fire.
:cl:
add: Added marine spawners to the firing range of Valhalla
/:cl:

Adds human target practice to Valhalla

---

code/datums/status_effects/debuffs.dm
code/game/turfs/space.dm

"Cold vacuum" that "instantly freezes you" will now extinguishes fire
Feels like an oversight that we apply spacefreeze onto mobs when they enter space but the fire keeps burning just fine in the infinite emptiness of space.
:cl:
balance: Space extinguishes fire
/:cl:

Space extinguishes fire

---

code/modules/surgery/generic.dm
code/modules/surgery/surgery.dm

Corpsman can now suture without fumbling
Field surgery is already weak as is without a medical APC or medical tad (which is infrequently chosen as the tad usually is better off with protection instead), this change makes it so that corspman can suture without fumbling. If I remember correctly, their fumble time is 4 seconds as is, which is impractical because to extend a lifetime of a corpse you have to do CPR every 7 seconds and every precious second counts. 
While I don't believe most corpsman will begin carrying sutures in most cases as only having a corpse once or twice have over -100% health post kitting is rare on most OPs, and would instead probably be medevaced like usual, this is a buff to corpsman on maps where corpses regularly gain over 200 combined damage post kitting and the …

Corspman can now suture without fumbling

---

tgui/packages/tgui/interfaces/Cargo.jsx

Makes the ordering console's width equal to the ASRS console screen width (1100px)
With my recent addition (https://github.com/tgstation/TerraGov-Marine-Corps/pull/16245) the rows are now too wide to display on the previous width, so I changed the screen to make it wider. I accidently only did this for the full, req's screen, and forgot about the outsider, ordering screen. Oopsie.
:cl:
fix: Ordering req console now the proper width
/:cl:

Fixes requesting console screen width

---

code/datums/personal_statistics.dm
code/game/objects/obj_defense.dm
code/game/turfs/walls/walls.dm
code/modules/vehicles/armored/__armored.dm

Tracks healing (which is rewarded one point per kitting (with my other PR, https://github.com/tgstation/TerraGov-Marine-Corps/pull/16295) /pill, and repairing (which is rewarded one point per 10 fixed)
Promotes teamwork and picking support classes. Both engineers and medics are in a peculiar spot at the moment with only barricading and reviving giving points, so in order to be most efficent you just spam barricades until you run out of mats then pretend you are a normal marine, and wait for people to die so you can revive them, which isn't how anybody really plays but it's what the system currently encourages. This PR aims to reward taking care of teammates, cades, and mechs/tanks, so that more people will play support roles, and those that do play support roles will be herded towards …

Tracks and rewards healing, repairing, and tanks killed in campaign

---

code/game/objects/items/explosives/plastique.dm

C4 is no longer damaged by explosions other than dev.
Stops them being qdel'd by chucking a load of nades at it.
:cl:
balance: C4 is immune to all explosions below devastate.
/:cl:

C4 ex_act tweak

---

code/modules/vehicles/armored/__armored.dm

You can now hand load tank guns as intended.
Also removed the alt click stuff since it's kinda redundant, as its all handled by m1.
Tanks had code to directly reload weapons externally (i.e. into the gun itself, not its magazine) however it was missing a check to ever actually allow this.
:cl:
fix: fixed being unable to directly load a tank weapon that required external loading
/:cl:

Direct load fix for tanks

---

code/modules/vehicles/_hitbox.dm

Little fix to stop tank riders getting thrown into space and other funny thing when the vehicle they're riding on changes z-level.
There is probably a better, more accurate fix we can put in place, but this is a long standing bug that required admin intervention so good to just squash it for now.
ahelp: Help admins, I was standing on tank and now I am dead in space ?!?!?!
:cl:
fix: Riding a tank across z-levels will no longer curse you to death
/:cl:

Desant z fix

---

code/datums/actions/observer_action.dm
code/datums/gamemodes/_game_mode.dm

SSD takeover will now load your active character slot (meaning name, gender, hair, eyes, age, ethnicity, flavour text, basically everything except subrace (human/robot/vatgrown)) with a check to see if the character is already in the round (optional, and based on config value)
Also adds a currently missing confirmation window, with the job also listed during confirmation.
Round removal is bad and we and other branches of ss13 have been trying to remedy it for years, and TGMC offers a variety of colourful options, including respawning after 30 minutes (With a fancy valhalla to test out things while waiting, great idea by the way!), taking over a newly born vatgrown soldier, the larva queue, taking over minion xenos, or least commonly used, taking over an SSD marine. 
This PR aims to …

SSD takeover now loads your active character slot

---

code/modules/mob/living/carbon/xenomorph/evo_datum.dm
code/modules/mob/living/carbon/xenomorph/evolution.dm
tgui/packages/tgui/interfaces/HiveEvolveScreen.tsx

Ties evolution to quick build.
If you have access to quick build, you can evo as much as you want.
Evo restrictions exist as a CM/Survivor era relic where there was an expectation of fighting during the prep phase.
Now with this gone, it no longer makes sense for xeno evolution to be restricted in prep phase.
:cl:
balance: Xenos no longer need evo points to evolve in prep phase
/:cl:

xenos can now fully evo pre-shutters

---

code/__DEFINES/dcs/signals/signals_keybindings.dm
code/datums/keybinding/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm

Title, adds the ability to cancel landslide charge with a keybind
Landslide can be a bit finicky to cancel with the mouse, so this will hopefully reduce the amount of suicidal behemoth charges.
:cl:
add: Added a keybind for canceling behemoth's landslide charge
/:cl:

Adds a keybind for canceling landslide

---

code/modules/projectiles/ammo_types/heavy_ammo.dm

Mecha heavy cannon no longer pierces tanks or mechs, but does get a 50% damage bonus against them.
Funny x5 hit due to piercing was bad.
:cl:
balance: Mecha heavy cannon no longer pierces mechs or tanks
/:cl:

mecha cannon change

---

_maps/map_files/Campaign maps/som_base/sombase.dmm

Fixes some maptables being the marine version.
Removed a stray nuke disk computer.
:cl:
fix: Campaign: fixed a couple of mapping issues on the Rocinante base map
/:cl:

Sombase map fixes

---

code/datums/gamemodes/campaign/campaign_mission.dm
code/datums/gamemodes/campaign/missions/asat_capture.dm
code/datums/gamemodes/campaign/missions/base_rescue.dm
code/datums/gamemodes/campaign/missions/raiding_base.dm

Made some missions with mechs having scaling numbers of mechs and/or tanks.
1. Raiding Base
2. ASAT capture
3. NT base rescue
Less mechs at lower pop.
More tanks at higher pop.
:cl:
balance: Campaign: Some missions with mechs now scale number of mechs and tanks with player pop
/:cl:

Campaign vehicle scaling

---

code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm

One deploy point was missing its mapper icon. No ingame difference.
:cl:
code: Fixed a missing mapper icon for deploy points
/:cl:

mapper icon fix

---

code/game/objects/items/stacks/sandbags.dm

Lets you empty full sandbags back into empty sandbags by right clicking
It's wierd that this is not possible, now it's possible to do
:cl:
add: You can now right click full sandbags to empty them,
/:cl:

Lets you empty sandbags

---

code/modules/reagents/reagent_containers/pill.dm

CLF zoomies are no longer freemium weight gain pills
Eating zoom pills made you fat, therefore no zoom. You were often better off just not eating these if you wanted to go fast.
:cl: Joe13413
balance: removed nutriment from zoom pills
/:cl:

Removes nutriment from zoom pills

---

code/datums/actions/observer_action.dm
code/modules/mob/mob_transformation_simple.dm

Fixes Four issues related to the ssd takeover PR (https://github.com/tgstation/TerraGov-Marine-Corps/pull/16253) 
1) If the confirmation panel times out, it automatically takes it as a yes
2) The ID card doesn't update with you, locking you out of the vendors besides the ones that do not require ID.
3) If you are overtaking a synth, it will pull your normal name instead of your synth one
4) TTS voice doesn't get changed
Fixes oversight by my previous PR. Sorry!
:cl:
fix: SSD takeover confirmation doesn't automatically assume yes
fix: SSD takeover now updates your ID as well
fix: SSD takeover now uses your synth name on synths
fix: SSD takeover now changes your voice too
/:cl:

SSD takeover fixes

---

code/modules/instruments/songs/play_synthesized.dm

Fixes #15907
This is normally the part where I bullshit you about how and why this was borked. I have no idea why this works, and I don't think it's because get_sfx() call that used to get triggered somehow messed with the frequency var.
Someone promised me their soul or something. In practicality it isn't really good for the game to have more marines playing awful songs and causing ear damage/brainrot, but at least what you put in is what you'll get.
:cl:
fix: Syntheised instruments should no longer be off key
/:cl:

Fixes synthetic isntruments being offkey

---

code/modules/events/hive_threat.dm
code/modules/events/intel_computer.dm
code/modules/events/ion_storm.dm
code/modules/events/stock_uptick.dm
code/modules/events/supply_drop.dm

Cleaned up the blacklists for some random events.
Funny comms blackout or intel computers in campaign is wew.
:cl:
fix: Certain random events will no longer happen in the campaign gamemode
/:cl:

Random event cleanup

---

code/modules/projectiles/ammo_types/rifle_ammo.dm

DMR minimum accuracy malus removed. It no longer misses at mid ranges.
It has mildly higher penetration at 17.5 rather than 15.
DMR having a min range doesn't really make much sense, it isn't a dedicated sniper rifle and missing at medium ranges where its supposed to shine makes it an awkward weapon to use. The mild AP buff should also help it be a more popular option compared to other marksman-class weapons. 
:cl:
balance: DMR no longer has minimum range penalties and has mildly higher penetration.
/:cl:

DMR no longer has minimum range accuracy, has mildly higher penetration.

---

code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/engineer.dm
code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/medic.dm
code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
code/datums/gamemodes/campaign/perks.dm

Gives the SOM medic and engie the MPI with UGL (instead of laser sight). I did the same with corpsman but forgot to look at the SOM side.
Fixed the SMG-25 belt holster not populating mag pouches.
Fixed SOM medics not getting the upgraded SMG loadout when they have the SMG perk.
Fixes and improvements to loadouts.
:cl:
balance: Campaign: SOM medic and engineer MPI loadouts now come with a UGL
fix: Campaign: SOM medics correctly receive the AP V-21 if they have the SMG perk
fix: Campaign: TGMC standards get SMG mags in their pouches if they chose the SMG belt holster
/:cl:

Campaign loadout fixes and improvements

---

code/modules/reqs/supplypacks.dm

Currently; Smoke and Flare Mortar Shells are more economically to buy outright rather than factory; which costs about 33% **more** to factory than to just buy. This Pull inverses this and makes it so you **save** 33% when you factory these shells over just buying them
It would actually make it economically viable to use the factory refills for Smoke and Flare Mortar shells, as currently you end up spending more for using the factory than if you just outright buy them
:cl:
balance: Changed price of Mortar Flare and Smoke Refills for Factory, they now cost 50 points per refill item
/:cl:

Adjust price of Mortar Smoke/Flare refills

---

code/__DEFINES/loadout.dm
code/datums/jobs/job/shipside.dm
code/datums/jobs/job/sons_of_mars_shipside.dm
code/game/objects/items/storage/pouch.dm
code/modules/reagents/reagent_containers/hypospray.dm

The medkit pouch now contains an advanced quick clot+ injector (30u qc+) and an advanced peridaxon plus injector (6u peri+ 12u hyronalin). Removed an advanced brute and burn kit to make space.
Currently the medkit pouch for corspman is inherently inferior to the advanced autoinjector pouch, as it lacks these two chemicals. People who choose to go with a medical pouch/prefer advanced injectors over autoinjectors for any reason has to go through the tedious process of emptying the autoinjectors into the advanced injectors every time, bogging down prep. This PR brings the medkit pouch in line with the exact same amount of reagents as you would get using the autoinjector pouch (except the dexalin and the oxycodone, dexalin is... questionably useful in rare, edge case scenarios, and oxycodone …

Brings the medic medkit pouch in line with the advanced autoinjector pouch

---

code/modules/vehicles/armored/_multitile.dm

Updated the TGMC campaign tank's description
There's currently not any xenos in HvH, so having the tank's description talk about how it's meant for destroying SOM is a nice bit of flavor.
:cl:
spellcheck: Changed the TGMC campaign tank's description to reflect it fighting the SOM
/:cl:

Updates the TGMC Campaign tank's description

---

code/datums/components/jump.dm

Closes #16032
Robots and synths do not have the ability to jump intentionally however get a "catch your breath message", this flavors it to them specifically
Robots and synths do not have a breath to catch
:cl:
fix: Synths and robots no longer get a "catch your breath" message when trying to jump, instead a silicon specific message
/:cl:

Less misleading jump stamina message

---

code/modules/reqs/supplypacks.dm

This pull adds the Rangefinding Binoculars to Requisitions for 200 Points, cheaper than the Tac Binos by 33% but more expensive than AI Targeting by double its cost, found under Explosive section just bellow the AI Module. This also includes a Fire Support Encryption key much like the Tac Binos crate does incase you want to co-ordinate with your Mortar/Artillery buddies.
Right now the only sources of Rangefinders is the Round start Mortar/artillery crate or from Engineers who purchase it from the NEXUS vendors, if you lose all of them that means you must buy Tac Binos instead; However someone mentioned in the Discord that Tac Binos do not work with Linking to mortars currently.
:cl:
add: Added Rangefinders to Requisitions for 200 Points, comes with free Fire Support Encryption Key!
/:cl:

Adds Rangefinder Binos to Req

---

code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/corpsman.dm
code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/engineer.dm
code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/field_commander.dm
code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/marine.dm
code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/squad_leader.dm
code/datums/gamemodes/campaign/perks.dm

Reduced unlock cost from 400 to 300.
Increased purchase cost from 40-50 to 80-90.
Increased SMG perk from 500 to 600.
They're relatively strong, I may have made the heat rate a little bit too generous... So make them more expensive so they're not as easily spammable.
SMG perk was a little too cheap considering the benefits.
:cl:
balance: Campaign: Increased purchase cost of plasma weapons by 50 credits
balance: Campaign: Decreased unlock cost of plasma weaponry by 100 credits
balance: Campaign: Increased the cost of Advanced SMG training by 100 credits
/:cl:

Campaign plasma gun cost changes

---

code/game/objects/effects/tele_blocker.dm

The telegib death area around the objective is now deactivated once both codes are sent.
Funny gibs probably bad in this case.
:cl:
fix: Campaign: NT base rescue telegib area is deactivated after both signals are sent
/:cl:

NT base rescue telegib fix

---

code/modules/admin/panels/Campaign_panel.dm
tgui/packages/tgui/interfaces/CampaignAdminPanel.tsx

The autobalance button now prompts if you want to force autobalance or simply suggest it as it normally runs.
More admin control.
:cl:
admin: Campaign panel autobalance button prompts if you want to force it or not
/:cl:

Campaign admin panel QOL - Nonforced autobalance

---

code/game/objects/machinery/buttons.dm

Title
Apparently there was a separate tank for TGMC HvH that I didn't add to Valhalla. This makes testing vehicle vs. vehicle more accurate and possible.
:cl:
add: Added the TGMC campaign tank to Valhalla
/:cl:

Adds campaign TGMC tank to Valhalla

---

code/game/objects/items/storage/boxes.dm

Title
:cl:
fix: fixed LR-73 ammo box overlay sprite
/:cl:

Fixes LR-73 ammo box overlay

---

code/__DEFINES/dcs/signals/signals_keybindings.dm
code/datums/keybinding/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm

Fixes an issue with Acid Shroud being able to be used infinitely.
Code improvements to be able to select acid shroud or just use it.
Bugs bad.
:cl:
qol: You can either select acid shroud or just use it on a button press.
fix: Acid Shroud can no longer be used infinitely.
/:cl:

Acid shroud fixes and QoL

---

code/modules/mob/living/carbon/xenomorph/evo_datum.dm

fix crash instaevo
Xenos should not be able to evo into a ravager from larva when the marines are on the planet.
:cl:
fix: Xenos can no longer instaevo when the shuttle is crashed on crash gamemode
/:cl:

fix crash instaevo

---

code/game/objects/items/frames/table_rack.dm

Deconstructing reinforced table parts gives two metal instead of one.
It cost 2 metal to make reinforced table parts.
It is likely not intended for the second metal you use to make it to just disappear.
:cl:
fix: Deconstructing reinforced table parts correctly give two metal instead of one.
/:cl:

Reinforced table parts give two metal

---

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Changes the text from `Sunder: <% armor> armor left` to `Armor: <% armor>`
This entry is very deceiving, sunder is the opposite of armor, so the % of armor left should not be labeled as sunder
:cl:
qol: The percentage of armor left is no longer labeled as sunder in the xeno stat panel
/:cl:

Clarifies armor stat panel entry

---

code/datums/gamemodes/campaign/rewards/teleporter.dm

Fixed the teleporter uses asset having twice as many uses as its supposed to. Whoops.
:cl:
fix: Campaign: Fixed the Teleporter Array charges asset having twice as many uses as intended
/:cl:

Tele asset fix

---

code/modules/mob/living/carbon/human/death.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/carbon/xenomorph/embryo.dm

Cleaned up some code weirdness I noticed when looking at death procs.
Larva now just qdel's on DNR via sig instead of funny snowflake check.
Synth is no longer completely immune to being gibbed due to funny CM legacy reasons.
Kill snowflake.
:cl:
balance: Synth is no longer immune to gibbing
/:cl:

Death fixes

---

code/datums/gamemodes/campaign/rewards/equipment.dm

Asset is now 1 use and cost 3 attrition.
Has 6 kits instead of 4.
The med asset has become the real gamer goblin choice, as everyone huffs up piles of giga cheap synap and advanced combat injectors.
That was never really intended, so now if you want to be a memester, it will actually cost quite a lot.
:cl:
balance: Campaign: Medical asset is now single use and costs 3 attrition
/:cl:

Campaign medical asset change

---

code/game/objects/items/blink_drive.dm
code/game/objects/items/explosives/mine.dm
code/game/objects/machinery/doors/airlock.dm
code/game/objects/machinery/doors/door.dm
code/game/objects/machinery/doors/windowdoor.dm
code/modules/clothing/modular_armor/attachments/modules.dm
code/modules/vehicles/armored/__armored.dm

Various EMP additions.
Tanks: Negligible damage, but will stagger the occupants
Blink Drive: Drains charges and delays recharge time
Eshield: Drains shield and delays recharge time
AT mines: No longer effected by EMP
Cleaned up EMP code for doors, slightly higher chance for them to get shocked.
More uses for EMP nades, and lets it counter some extra stuff.
AT mine EMP interaction is too exploitable (but funny)
:cl:
balance: Added EMP effects against tanks, blink drives and eshield modules. AT mines are now EMP immune
/:cl:

Emp changes

---

code/modules/projectiles/guns/rifles.dm

Makes burstmode actually have noticable scatter compared to full auto.
Its still pretty low, but screen edge+ its less accurate.
Kinda want to do this to the tgmc rifles, but will leave for another pr since thats hvx balance.
Downside of autoburst increased DPS
:cl:
balance: V-31 has slightly higher burst scatter
/:cl:

V-31 scatter adjustment

---

code/modules/vehicles/_hitbox.dm

Multitile vehicles now add things to desants if they land on a tank via throw (of any sort).
Also removed some unneeded code I think I forgot to remove during the hover tank PR.
People being able to phase under tanks via leaps/knockbacks/throws etc is bad.
:cl:
fix: Mobs that land on tanks via any kind of throw now are correctly added to desants
/:cl:

Tank throw fix

---

code/modules/clothing/modular_armor/mark_one.dm

Title, renamed to Jaeger Mk.I Pattern Helmet because it has no markings
:cl:
fix: fixed jaeger mk1 helmet duplicating in the armor vendor
/:cl:

Fixes jaeger mk1 helmet duplicating in the armor vendor

---

code/_onclick/hud/alerts.dm
code/modules/mob/dead/observer/observer.dm

Basically we never actually checked if the resolved old body was human before trying to run a human only proc on it, death
Runtime bad
:cl:
fix: Fixed being unable to join valhalla or the larva queue if you ghosted as a xeno
/:cl:

Adds extra checks to settings old bodies as undefibbable

---

code/game/area/patricks_rest.dm

Added a missing area flag for Patrick's Rest, in campaign.
:cl:
fix: Campaign: Radio works in caves on Patrick's Rest
/:cl:

area flag fix

---

code/game/objects/machinery/computer/communications.dm
code/game/objects/machinery/overwatch.dm
code/modules/screen_alert/command_alert.dm

CIC messages, and ship announcements (comms console) use the same cooldown as HUD orders from *Send Orders* and AI announcements. Also, they have a maximum length and CIC messages use `to_chat` now.
These are *way* too easy to spam due to lacking cooldowns or maximum lengths, giving them a character limit and making them share the cooldown of Send Orders and AI announcements will significantly reduce that.
Chances are, CIC messages that are really long are either really terrible and impossible to understand in the short time they're visible or being (ab)used to fill your screen with random letters for 30 seconds. A character limit should help with both of these issues.
*Little side note, CIC messages in general suck (because either using big volume on the radio or using Send Orders does …

CIC messages/ship announcements have the same cooldown as HUD orders (and more character limits)

---

code/game/turfs/closed.dm

title
in my defence this was never just an outrider issue it was true for all tads
xenos could hitch a ride outside the tadpole and this is probably kinda sorta maybe bad
:cl:
fix: Tadpole/Shuttle engines are now built from copium and are thus unable to be melted or crushed.
/:cl:

Adds RESIST_ALL flag to tadpole/ert engines to prevent melting/crushing

---

_maps/map_files/Campaign maps/som_raid_base/som_raiding_base.dmm
_maps/map_files/Campaign maps/tgmc_raid_base/tgmc_raiding_base.dmm
code/datums/gamemodes/campaign/missions/raiding_base.dm

TGMC raiding base no longer allows the beacon to be planted in the captain's office.
A few cosmetic map changes.
SOM plant their beacon in cap office literally every game, its a lame ass pokey corner.
:cl:
balance: Campaign: TGMC Raiding base no longer allows the beacon to be planted in the captain's office
/:cl:

Raid base edits

---

code/datums/components/harvester.dm

Harvester weapons now apply 5 stacks of fire when loaded with kelotane
Kelotane Harvester isn't being used because its effects can be dealt with only one rest. Now it'll take a full retreat or the active use of acid wells to get rid of the stacks. 
:cl:
balance: Harvester weapons now apply 5 stacks of fire when loaded with kelotane
/:cl:

Gives Kelotane Vali 5 fire stack (also use better proc)

---

code/modules/projectiles/ammo_types/rocket_ammo.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/guns/specialist.dm

Campaign rocket change.
Heat rockets now have a small scatter penalty. Should only really be relevant for offscreening as its pretty low.
Fixed ammo scatter actually... using the var at all.
Reduced the RR's weird -100 scatter thing to a sane -10 (utterly pinpoint unless you're like staggered and king debuffed).
Make offscreening vehicles a bit less reliable, especially against mechs.
:cl:
balance: Campaign: Heat rockets have slightly more scatter
balance: Recoilless rifle has -10 scatter instead of -100
/:cl:

Heat rocket scatter

---

code/datums/interior/interior_tank.dm
code/modules/vehicles/armored/__armored.dm

Things that you can put inside vehicles can be taken out by grabbing and using grab intent or drag n' drop on the interior door.
Fixes runtime caused by inserting a non-item into vehicles.
Prevents objects that cannot be picked up in hand from being permanently stuck inside vehicles when they should be allowed to be taken out if they're allowed to be placed inside.
:cl:
add: Vehicle interior door is on-par with its exterior door as it now allows you to take out non-mobs (like crates).
/:cl:

Vehicle interior door allows non-mobs to exit

---

code/modules/projectiles/guns/mounted.dm

This mounted weapon's only good quality is the giant explosion yet the scope is small, and has no IFF
This doesn't really improve it's issues but atleast you dont hit your teammates with a heavy explosion the size of an entire screen if you leave it on guided mode.
https://github.com/user-attachments/assets/9fc304c4-7c45-4308-ad0d-60132781c9b7
:cl:
balance: The FK-88 now has a fullscope instead of the old HSG sight it had.
/:cl:

Gives the heavy_isg/FK-88 a scope.

---

code/modules/mob/living/carbon/human/life/handle_shock.dm

Removes unnecessary space from shock's "is having trouble standing".
Additional space bad.
:cl:
spellcheck: Removes unnecessary space from shock's "is having trouble standing".
/:cl:

Removes unnecessary space from shock's forced emote

---

code/game/objects/machinery/computer/computer.dm
code/game/objects/obj_defense.dm
code/game/objects/structures/reagent_dispensers.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm
code/modules/mob/living/simple_animal/friendly/parrot.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/projectile.dm
code/modules/vehicles/atv.dm
code/modules/vehicles/mecha/mecha_defense.dm

...Or at least some of it. Probably.
Greatly reduced the amount of projectile hit chat messages.
Early check for mob hits to not generate chat data unless it actually needs it.
Also fixed a runtime with hitting mobs on solid turfs (yes it should have always worked, but it just runtimed. aylmao)
And lastly cleaned up arg names to be consistant in the bullet proc.
It seems that chat spam from projectiles does in fact generate considerable amounts of lag. Even on local, I can force up tidi using just 1 mech spam firing.
By making the chat messages only apply for higher damage projectiles (its far more relevant to know if something was hit by a rocket, vs 50 messages they were hit by a rifle), it makes things SIGNIFICANTLY less choppy in cases where there is huge message spam. (i.e. any …

Deletes projectile lag

---

code/_onclick/hud/fullscreen.dm

Fullscreen overlays are now a bit more sane when it comes to applying and removing, in particular if overlays are applied and/or removed repeatedly.
Most notably, being hit by projectiles applies and removes the overlay for every hit, but the code never really took into account that this could happen while the previous one is in the process of being animated out and removed.
Maybe better perf? But should be less wack, at the very least.
:cl:
code: Cleaned up some fullscreen overlay code. In particular this should improve projectile impact screen overlays
/:cl:

Fullscreen overlay code improvement

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

The SMES units inputs and outputs are looped on the Pillar of Spring. This fixes that issue.
Looping SMES units causes a variety of behaviors that are usually thought to be undesirable, causing the power consoles to misrepresent loads and APCs to not charge even when there should be excess power available, for example.
:cl:
fix: Fixed looping power issue with the SMES units on the Pillar of Spring.
/:cl:

Fixes looped power on Pillar of Spring

---

code/game/objects/structures/barricade.dm

true is for dissassemble, not decon, whoops.
barricades drop correct amount of materials.
:cl:
fix: fixed barricade decon dropping incorrect quantities of mats
/:cl:

barricade decon fix

---

code/modules/xenomorph/silo.dm
code/modules/xenomorph/spawner.dm

Resin silos now give spawned minions the correct hive number. This means corrupted resin silos now creates corrupted minions (and thus doesn't attack their owner hive).
Bugfix.
:cl:
fix: Resin silos now grant their spawned minions the correct hive number.
/:cl:

Resin silos give minions the correct hive number

---

code/datums/gamemodes/campaign.dm
code/modules/admin/panels/Campaign_panel.dm
tgui/packages/tgui/interfaces/CampaignAdminPanel.tsx

Adds a new button to the admin campaign panel, to forcefully shuffle the two teams.
Force autobalance button is good if one team simply has more players than the other, but doesn't really help if one team is just stacked with better players.
This button should (hopefully) be good in cases like that, to avoid one sided stomps.
:cl:
admin: Campaign: Added a team shuffle button to the campaign panel
/:cl:

Campaign - Shuffle team button

---

code/__DEFINES/dcs/signals/signals.dm
code/datums/components/riding/riding_mob.dm
code/modules/mob/living/carbon/xenomorph/attack_alien.dm
code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
code/modules/mob/living/carbon/xenomorph/xenoattacks.dm

#13924 broke all xeno actions that used damage or ap mod on attack.
Unbreaks these, and also purges a bunch of other shitcode like more bad copy paste, pointless checks and signals etc, and they now just use the correct procs.
Specifically, /mob/living/carbon/xenomorph/attack_alien was pretty much entirely horrible.
Working abilities, less spaghetti.
:cl:
fix: fixed all xeno abilities that use damage or ap mods on attack
/:cl:

Xeno attack fixes

---

code/modules/ai/ai_behaviors/ai_behavior.dm

Fixes AI glide size getting fucked out of wack.
Basically glide size is normally updated for mobs every time they move... but this is done in the client/Move proc, so AI mobs never reset their glide. This means if their glide changes due to something else (like being thrown via special ability/explosion etc), their glide gets fucked and never unfucked.
32 glide size looks cursed.
:cl:
fix: fixed AI mobs having cursed glide size in many cases
/:cl:

AI glide fix

---

code/modules/mob/living/simple_animal/hostile/retaliate.dm

Changes this line
Into this line
Thereby making the game check if hostile/retaliate creature is conscious or not before activating the Retaliate() proc
**Fixes #16420** 
Dead/Unconscious horses (and goats) should not considering retaliating when being hit.
:cl: Vondiech/Citruses
fix: GOATS no longer get an EVIL-looking GLEAM in their EYE when getting HIT while UNCONSCIOUS/DEAD.
/:cl:

Fixes evil goat (and hostile/retaliate animals proccing Retaliate() when hit while dead)

---

code/modules/mob/living/carbon/xenomorph/update_icons.dm

Stops these vis contents from being visible in the right click menu.
No real gameplay changes, but this was always annoying.
:cl:
qol: Xeno fire and wound overlays no longer appear in the right click menu
/:cl:

Xeno viscontent fix

---

_maps/map_files/generic/Admin_Level.dmm
code/game/objects/machinery/vending/marine_vending.dm

Brings all the factorio goodness in a compact, hopefully well organized package, in the form of a valhalla vendor. Currently has every factorio machines, the factorio paper guide, conveyor belts and the switch to go with it. Every refill available to req has is available with the only exception being drop pods as I suspect it could be used to deploy valhalla characters on the map. I am not sure. But if it's safe to do so I might add it.
It would allow req enthustiasts to experiment with factory designs in valhalla, check recipes, improve productivity, learn about the intricacies of production, so on and so forth.
:cl: Koenigsegg
add: Added a valhalla reqtorio vendor
add: Added the reqtorio valhalla vendor to the vehicle pit in valhalla
/:cl:

Introduce a reqtorio valhalla vendor

---

_maps/shuttles/minidropship_outrider.dmm
_maps/shuttles/minidropship_umbilical.dmm

See title. The only tadpole variants this effects are the vehicle carrier (outrider) and umbilical tadpoles.
Windows usually represent a weak point on a tadpole (can't be moved through, can't be fired through except by laser, can be destroyed by claws). However, covering them up with podlocks renders them completely slash-proof, requiring a xeno with acid to come and open up the tad. While this isn't inherently a problem, the outrider and umbilical tadpoles stand out by being the only tadpoles with this feature, and I see no reason why they especially need it.
:cl:
balance: removes podlocks from the outer windows of the "Outrider" and "Umbilical" tadpole variants
/:cl:

Removes podlocks on outward facing tadpole windows

---

_maps/map_files/LV759/LV759.dmm

Changes geotherm/SMES floors to plating and adds power cables to them (alongside adding power cables wired in parallel for the other two sets of generators) on LV-759
**Fixes #16035**
LV-759 having a functioning power grid marines can fix & set up would be alot nicer.
:cl: Vondiech/Citruses
fix: Geotherm gens/SMES on LV-759 now are properly wired to power grid making them actually able to power the map.
/:cl:

Fixes geotherm gens/SMES on LV-759

---

_maps/map_files/Arachne/TGS_Arachne.dmm

Changes Arachne body scanner & sleeper consoles from THIS
To THIS
Making them now functional as tested in-game.
**Fixes #15897**
non-functional scanner & sleeper consoles are bad
:cl: Vondiech/Citruses
fix: Fixes the consoles of a body scanner & sleeper on the Arachne shipmap.
/:cl:

Fixes Arachne body scanner & sleeper consoles

---

code/modules/reqs/supplypacks.dm

Title literally. This time less scuffed.
But if you *really* need to know.
SVD 150->300
HPR 150->300
Magazines unaffected.
HPR and SVD are killer deals for 150. With both sharing ammo with common street rifles that marines get ammo boxes for (Rifle!Family/Mosin respectively)
This should put them to a higher point value and cost and make it more obvious they're something inbetween a 40 point and the usual imports which either fall into 120 or 50 points respectively.
tl;dr They're way too good of killer deals at 150.
:cl:
balance: SVD and HPR now cost 300 points to buy in Requisitions instead of 150 to reflect their status.
/:cl:

Increases the cost of HPR/SVD to 300.

---

code/game/objects/items/radio/detpack.dm

You can now set the code and freq of a detpack by hitting it with a signaler (or hitting the signaler with the detpack).
Disarming a detpack now properly disarms it.
Moved the multitool code to the right place.
Easier to use detpacks - having to mess about with every single one is fiddly and time consuming.
:cl:
qol: You can update detpack freq and code by hitting it with a signaler, or hitting the signaler with the detpack
/:cl:

Detpack QOL

---

code/game/objects/machinery/doors/airlock.dm

Fixes #16332
Being shocked INSIDE a mech is funny, but not ideal.
:cl:
fix: Airlocks will no longer shock mech pilots
/:cl:

airlock shock fix

---

code/modules/vehicles/armored/som_armored_weapons.dm

The keybind for cycling through coilgun firemodes (swapping firemode bind) now actually works.
:cl:
fix: Fixed the hovertank coilgun hotkey
/:cl:

Coilgun bind fix

---

code/modules/projectiles/sentries.dm

Putting a sentry back up will no longer make it dense if it wasn't orignally so.
Funny dense COPE sentries.
:cl:
fix: Putting a sentry back up will no longer make it dense if it wasn't orignally so
/:cl:

Sentry density fix

---

code/modules/projectiles/ammo_types/rocket_ammo.dm

Low power mode now has 40 AP instead of 25.
Medium power has 50 AP instead of 40, and has 2 flash range like high power mode.
Generally low and med power mode aren't that useful currently.
This change means low power mode is now actually the highest DPS option against enemy vehicles, at the cost of burning through ammo exceptionally fast. This means a fully crewed tank can get optimal damage if they have a loader doing their job well. Bonus points if you switch back to high power as the finishing blow.
Med power is now a bit more viable, but still probably the weakest, although when it comes to simply shredding infantry, its likely more effective than high power, but the lack of neuron activation due to no gibs is big.
:cl:
balance: Campaign: Buffed Hovertank coilgun low and medium power …

Tank coilgun tweaks

---

tgui/packages/tgui/interfaces/EscapePod.jsx

This PR fixes "Launch evacuation pod" button on escape pod controllers. Without this PR this button isn't usable at all in any game condition.
Detailed description: due to logical error evac pod variable 'can_evac' disables button if TRUE. If FALSE this button also cannot be clicked due to no evacuation process. This way "Launch evacuation pod" button could not be activated in any in-game situation.
It fixes broken button. Now it is usable. Reviving implemented mechanics. Always good.
:cl:
fix: "Launch evacuation pod" button is now fixed and usable.
/:cl:

Escape pod button fix

---

code/modules/projectiles/gun_attachables/rail.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/guns/sentries.dm
code/modules/projectiles/sentries.dm

Sentries will now properly target tanks, and hostiles behind/on top of them.
Also cleaned up the ignore list by making it a glob instead of a gun var. There should no longer be a need for any snowflake there since I baked in laser checks into the actual targeting proc a while ago.
Bug fix, cleaner code.
:cl:
fix: fixed sentry targetting being blocked by tanks
/:cl:

Sentry tank fix

---

code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/16478
Bug bad
:cl:
fix: Fixed ghosts being able to make huggers jump out of bags
/:cl:

Fixes ghosts being able to make huggers jump out of bags

---

code/game/objects/structures/xeno.dm

Removes `XENO_DAMAGEABLE` from resin doors. Stops minions damaging resin doors. During testing, can still dismantle doors on harm intent, just won't have the slash effect afterwards since you are not attacking it.
Xenos should not be damaging their own doors.
:cl:
fix: Xenos cannot damage resin doors again.
/:cl:

Xenos can no longer damage their own doors

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm

Defender crest defence now increases their throw resist to the same level as big xenos.
This means light explosions (i.e. grenades) will not toss defenders around if they are crest down.
Fortify is unchanged, since that makes the defender entirely immobile and unmovable already.
Also removed some one letter var stuff in the file.
Tonk xeno has a bit more tonk in tonk mode.
:cl:
balance: Crest defence makes the user immune to light explosion tosses
/:cl:

Crest defence buff

---

code/modules/projectiles/ammo_types/ags_ammo.dm

xope pr.
AGLS frag wasn't intended to be able to hit one target with 15 projectiles at once (450 damage!), for pretty obvious reasons.
Funny insta kill goes brrr
:cl:
fix: fixed AGLS frag rounds detonating under mobs
/:cl:

AGLS frag fix

---

code/modules/reqs/supplypacks.dm

Smartgun reqtorio is insanely efficient for how basic SG drums are - each reqtorio refill provides 10 t29 drums or t85 bins for half the price of manually bought drums/bins. With the t62, this is even worse - ~700 points worth of t62 magazines for 250 points (this one is admittedly my fault)
to make things worse, all of the factory parts are available for free within the req vendor, meaning there's no "break-even point" where factory production of SG ammo becomes more efficient than buying it. Reqtorio simply *made sg cheaper*, outright for just a minute of setup.
This PR tones down the efficiency of reqtorio to ~130% (from 200%) for t29&t85 ammo, and 175% (from 280%) for t62 magazines. Still cheaper than just buying it outright, but less so.
2x ammo for sgs dawg 😭 
who merged this …

Increases the price of SG factory refills

---

code/modules/projectiles/projectile.dm

This PR gives suppressor a unique mechanic of making fired bullets a bit less visible. Before - After.
A suppressor does hide a muzzle flash and bullets don't emit light, but it's almost useless, because they are still obviously visible and it makes almost no noticable difference. It's still like firing tracer bullets. A suppressor doesn't fully represent "spec ops" or "tacticool" (whatever you name it) vibes and it's a bit dissapointing. It has some good points but truly isn't the best choice at anything (either accuracy, recoil or scatter, not even mentioning its noticable downsides). This PR grants a suppressor truly unique feature, perhaps giving marines a bit more subtle way of playing (not just run n' gun).
You may call it "suppressor buff" but I'd insist on calling it "uncovering …

Suppressor makes bullets less visible

---

_maps/map_files/Research_Outpost/Research_Outpost.dmm

Expands LZ 1 on Research Outpost
Currently LZ 1 on Research Outpost is too small for vehicles to traverse without crushing the floodlights, this expands the landing zone by a few tiles in all directions.
:cl:
qol: Research Outpost LZ 1 Minor Expansion for Vehicles
/:cl:

Research Outpost LZ 1 Expansion

---

code/modules/vehicles/_hitbox.dm

You will no longer get a permanent space debuff for riding a tank across z-levels.
:cl:
fix: fixed mobs getting perma space debuff when riding tanks across z-levels
/:cl:

Tank space fix

---

code/game/objects/structures/razorwire.dm
code/modules/projectiles/guns/_shared_ammo_objects.dm
code/modules/vehicles/armored/_multitile.dm

Fixes tank desants getting burned by fire in some cases but not others
Related fix that makes multitile vehicles have some baseline pass flags given to desant (in addition to the tank's own passflags, as current).
Connected to the above, removed a desant trait check for razorwire that should now be redundant.
Fixed xeno fire incorrectly referencing itself instead of the victim for a couple of checks.
Cleaned up fire code to be a bit simpler/consistant. Mainly there is just a single affect_atom proc instead of 3 different ones that ultimately just did the same thing in all cases. Some code cleanup as well.
Bug fixes and code improvement.
:cl:
fix: Fixed some fire bugs, notably fire will now correctly not effect people on tanks
code: Cleaned up some fire code
/:cl:

Fire fixes and code improvement

---

code/game/objects/items/power_cells.dm

Reduced the flashrange of cell explosions by 66%.
Cells are effectively grenades that also do a 4 second blind. This has no impact in HvX but is kinda wew in HvH.
:cl:
balance: Energy cell explosions have lower flash range
/:cl:

cell explosion nerf

---

code/__DEFINES/objects.dm
code/game/objects/items.dm
code/modules/projectiles/guns/_shared_ammo_objects.dm

Fix fire layering under resin walls.
Fixes pyrogen fire not spawning correctly.
Update some arg names as I hate proc args with the same name as vars, it makes it needlessly confusing.
Moved a couple of procs so they're in the right order, and made an extinguish amount define since it's used in two unrelated places.
:cl:
fix: fixed some fire bugs
/:cl:

Fire fixes

---

code/__DEFINES/is_helpers.dm
code/game/sound.dm
code/modules/instruments/songs/play_legacy.dm
code/modules/instruments/songs/play_synthesized.dm
code/modules/mob/living/silicon/ai/freelook/eye.dm

Removes the whole `sound_reciever` var, replaces it with an actual solution that doesn't require it. Also culls some single letter vars. Instrument preference is now respected as well.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/16230
Better code good, instrument preference being respected good.
:cl:
fix: AI eye hearing now respects instrument preferences
code: Improved the way AI eye hears
/:cl:

AI hearing code improvement + bug fix

---

code/game/objects/items/storage/backpack.dm

Fixed the cloak effect not properly deactivating from energy loss.
Funny bad args.
Exploit.
:cl:
fix: fixed scout cloak not properly deactivating on energy loss
/:cl:

Scout cloak fix

---

_maps/lv624.json

Increases quickbuild on LV624 (old LV) to 2000 from 1400.
This map has a lot of open space and 1400 is laughably low. On the rare chance this map is run as an event this should help xenos not feel naked the whole time.
:cl:
balance: Increased quickbuild on LV624 to 2000 from 1400.
/:cl:

Increases LV624 quickbuild

---

_maps/map_files/LV624/LV624.dmm

Expands the LZs slightly so that tank/apc can escape the alamo.
No more tank jail.
:cl:
fix: Tanks can now leave the alamo on LV624.
/:cl:

LV624 now fits tanks

---

_maps/map_files/LV759/LV759.dmm
code/game/objects/effects/spawners/random/misc_structure.dm
code/game/objects/structures/large_vehicle_props.dm

Makes a lot of changes to LV 759, notable examples:
- Redo of most of LV 759's caves keeping most of the original layout the same while attempting to make the open paths more clear.
- Extreme reduction in the number of "bulbous rock"' tiles that looked a lot like impassable rock.
- Removal of metal barriers in the middle of the road ways that made the roads very annoying for marine vehicles.
- Change to area designations to get rid of the problem with out of bounds areas being accessible.
- Reduction of cars on the roads in most areas to make the roads somewhat more clear.
- Removal of hundreds of platform corners that were not removed along with the full sized platforms.
Other changes were probably spoken about in #mapping, it is difficult to list them all due to the nature of this.
LV …

LV 759 Cleaning and Caves Improvement

---

code/modules/projectiles/ammo_types/xenos/energy_xenoammo.dm

See title
Without knockback it can be kinda hard to immediately tell who's been hit by the AOE and who hasn't if you don't have a medhud or something. It's just nice to know.
You can already tell if the laser beam hits you.
:cl:
qol: Warlock blast now shakes your sprite if the AOE hits you.
/:cl:

Warlock blast AOE now makes you jiggle around for a bit

---

code/modules/vehicles/armored/__armored.dm

If you are on a tank, you can now shoot without hitting the tank (unless you specifically aim at it).
If you are shooting at someone ON a tank, you will no longer hit the tank either. Note however this requires you to specifically target the desant, so misclicks will hit the tank still.
No more desant weirdness with targeting.
:cl:
balance: Tank riders can shoot, and be shot, freely without projectiles hitting the tank
/:cl:

Tank desant targeting

---

code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm

Lower's praetorian's health by 30.
For quite a while since the blanket xeno buffs, xenos have been a little overturned, so I think a few outstanding examples of overbuffed caste should be nerfed just a little. Praetorian got 60 more extra health, on top of a big acid spray and acid spit damage buff. I think it got a little too much health for how safe this caste is to play in general, and how much utility it has. 
:cl:
balance: slightly lowers Praetorian's health
/:cl:

Slightly lowers praetorian's health

---

code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm

Lowers the queens health by 50, but gives her -0.1 speed back.
For quite a while since the blanket xeno buffs, xenos have been a little overturned, so I think a few outstanding examples of overbuffed caste should be nerfed just a little. Queen got a massive health buff of 150, on top of the big slash and acid damage changes, which makes her spit slashing extremely deadly. This should make her have to be a little more careful with her life in general, while still keeping the deadly aspect.
:cl:
balance: slight queen nerf
/:cl:

Slight queen nerf

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm

Lowers the crusher's health by 55.
For quite a while since the blanket xeno buffs, xenos have been a little overturned, so I think a few outstanding examples of overbuffed caste should be nerfed just a little. Crusher is the first one I think of, besides warrior. It got a huge survivability buff of 125 extra hp, which was just complete overkill with how much armor it has, and its utility to its team, not even counting the fact that it can fish people.
This should make them have to be a little more careful with their life, while still being extremely tanky. 
:cl:
balance: slightly lowered crushers health
/:cl:

Slightly lowers crushers health

---

code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm

Gives behemoth a sunder multiplier of 0.8
Behemoth has been in a bit of a sad spot even after the buffs. It got a huge armor buff, but you're so slow, and your sprite so big, that you often can lose most if not all of your armor in one engagement if you got unlucky. This should help them better with the whole heavily armored slow bug thing. 
:cl:
balance: gave behemoth a sunder multiplier
/:cl:

Adds a sunder muiliplier to behemoth

---

code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm

Lowers defilers health by 20
For quite a while since the blanket xeno buffs, xenos have been a little overturned, so I think a few outstanding examples of overbuffed caste should be nerfed just a little. Defiler got 45 extra health, on top of that 5 extra armor in a bunch of categories. 
Defiler is such an amazing support caste for the entire team, with its gas spreading ability, weed, and pheros. It should be just a little more killable, imo, since I think it's the best t3 overall(if you're playing with your team), and did not really deserve that much extra health.
:cl:
balance: slightly reduced defilers health
/:cl:

Slightly lower health for defiler

---

code/modules/factory/parts.dm
code/modules/factory/unboxer.dm

AGLS Flare magazine assembly now correctly create its associated item instead of AGLS HE magazines.
AGLS HE magazine assembly no longer create its associated item immediately on unboxing and must follow its factory recipe.
Bug fixes. AGLS Flare magazine assembly was giving the wrong ammo type and was giving a 100 point discount on the HE mags and the other just ignored the whole point of factory.
:cl:
fix: AGLS Flare magazine assemblies now create AGLS Flare magazines instead of HE magazines.
fix: AGLS HE magazine assemblies now follows its factory recipe instead of immediately finishing on unboxing.
/:cl:

AGLS flare/he assembly fix

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm

Lowers warrior's health by 50.
For quite a while since the blanket xeno buffs, xenos have been a little overturned, so I think a few outstanding examples of overbuffed caste should be nerfed just a little. Warrior got a massive health buff of 100, and not only that, got a huge armor buff of 20 across the board on top of that. Warrior as it stands has more effective health than most t3's while already being a really strong caste that can fish marines or just throw them out of position. 
As it stands warrior is just overpowered right now, this should still leave it really strong, but just a little more killable.
:cl:
balance: lowers warriors health
/:cl:

Lowers warriors health

---

code/game/objects/items/stacks/sheets/sheet_types.dm

Reduces the cost to make barbed wire from 2 to 1.
No idea why it is more metal efficient to make and deconstruct razor wire for barbed wire.
Current:
- 2 metal -> 1x Barbed Wire -> 2 metal or 100% value
- 4 metal -> 1x Razor Wire = 2x Barbed Wire + 8 Rods  -> 6 metal or 150% value
This PR:
- 1 metal -> 1x Barbed Wire **->** 1 metal or 100% value
- 4 metal -> 1x Razor Wire = 2x Barbed Wire + 8 Rods  -> 4 metal or 100% value
:cl:
balance: It now costs a single metal to create a barbed wire.
/:cl:

Reduces barbed wire construction cost to 1 metal

---

code/game/objects/structures/dropship_equipment.dm

Reverts tgstation/TerraGov-Marine-Corps#15704
This PR caused the sentry deployment structures to be pixel shifted a tile north from where the actual collision is. It is labeled as a fix despite the fact that it only makes it harder to see where the collision is on the structure, so people use these as barricades on the tad due to the fact that its basically an invisible movement blocker.
I don't see any actual reason to keep this "fix", it just just an annoyance for xenos when the sentry deploys are used as barricades. If there is some larger issue with them that I'm missing(which is not elaborated on in the original pr) then my bad but prior to this fix the deployment structures worked fine and now they are pixel shifted for no reason.

Revert "Sentry deployer offset"

---

code/modules/projectiles/ammo_types/tx54_ammo.dm

Alternative to #16507.
Reduces the sunder on the tx54 airburst from 3 per pellet to 1.5 (21 total to 10.5). This reduces the sunder per second from 17.5 (higher than scout rifle's 12.5) to 8.75 (higher than flechette's 8.5).
These guns can crit a queen in 6 shots, and even hitting a queen twice is enough to force them to disengage or risk being mowed down by the marines.
Free weapons should not be invalidating all large castes.
:cl:
balance: GL54 and AR55 Airburst sunder reduced from 3 per pellet to 1.5.
/:cl:

Nerfs GL54/AR55 Airburst Sunder

---

code/datums/elements/debris.dm

Bullet pings are now chance based again, at 50%.
When impact particles was added, ping sounds were made 100%. This has the unfortunate side effect of maxing out sound channels extremely easily.
This isn't a perfect solution but should significantly reduce the funny sound channel maxing you frequently hear.
:cl:
soundadd: Bullet ping sounds changed back to not happening 100% of the time, to reduce sound channel issues
/:cl:

Bullet ping sound chance revert

---

code/datums/gamemodes/campaign.dm

I did a dumb and didn't async this, so it was happening ONE PLAYER AT A TIME.
:cl:
fix: Campaign: Autobalance will no longer take much longer to appear for players than intended
/:cl:

Async campaign autobalance

---

code/datums/actions/ability_actions.dm

Basically we would runtime on init because we are in nullspace when this runs and therefore don't have a turf
bug bad
:cl:
fix: Fixed a runtime when first spawning in as a xeno with pheros
/:cl:

Fix xeno icon update runtime

---

code/game/objects/machinery/squad_supply/supply_console.dm

Runtime in code/game/objects/machinery/squad_supply/supply_console.dm, line 84: Cannot read null.drop_location
runtime bad
:cl:
fix: Fix a supply beacon console runtime
/:cl:

Fix supply beacon console runtime

---

code/game/objects/items/weapons/shields.dm

Removes the strap from the deployable shield, people are using it to emulate the old shield we removed. 
Also I didn't repath it because it uses the marine shield `update_icon_state` handles shields with broken icon states, todo is probably make all shields have a broken icon state then we can repath it to the base shield path.
We removed the old shield for a reason. It's still an issue despite it having less integrity because it still allows armor stacking for a relatively large amount of slashes. It not being NODROP should allow it to still act as a shield but discourage its use as one since it's relatively simple for most castes to make you drop it.
:cl:
balance: Deployable shields no longer have a strap
/:cl:

Deployable shields no longer have a strap

---

code/modules/clothing/glasses/glasses.dm

This flag was being used for something it was not intended to be used for, guh
Welding goggles being unstrippable if put down are not cool
:cl:
fix: Fixed welding goggles hiding themselves in the strip menu
/:cl:

Fixes welding goggles hiding themselves in the strip menu

---

code/modules/mob/living/carbon/xenomorph/evolution.dm

get rid of 
we dont require you to be a drone to go into rulers anymore
:cl:
fix: Removed restriction to evolving to something besides drone when there is no ruler
/:cl:

Remove restriction to evolving to something besides drone when there is no ruler

---

code/datums/jobs/job/icc.dm

I forgor to push this one apperantly while playing HD2. I'm kinda a doofus.
Also renames it from ml101 (why did i do that) in the code to icc_heavyshotgun to fit the rest of the loadout names.
The ICC Leaders are finally no longer loaning their gear to their underlings.
:cl:
fix: Due to budget cuts, ICC ERT Leaders didn't get their loadout upon spawning. This has been rectified. And they should once again have loadouts.
/:cl:

ICC leaders are once again given loadouts.

---

code/game/objects/items/storage/firstaid.dm

Makes the following pill bottle types refillable:
- bicaridine
- kelotane
- tramadol
- tricordrazine
- dylovene
- paracetamol
- isotonic
These are all naturally available in the marine med, and can now be refilled by right clicking the vendor with the bottle instead of having to restock -> revend
:cl:
qol: MarineMed pill bottles are refillable via right click on the vendor
/:cl:

Makes pill bottles refillable at a pill vendor

---

code/datums/quick_load_beginners.dm
code/modules/paperwork/beginner_tutorials.dm

Replace the TE pouch supposed to spawn in the suit storage of the beginner shocktrooper loadout with a second flare pack.
Updated the phamplet accordingly.
The TE pouch cannot fit in the general armor storage module anymore so it's just an empty slot, I replaced it with another flare box to mirror the robot shocktrooper loadout that has 2 flare boxes in the suit storage.
:cl:
add: Added a second flare box in the shocktrooper loadout to replace the TE pouch that can't spawn there anymore
/:cl:

Update beginner shocktrooper (laser) loadout

---

code/game/objects/structures/rocks.dm

Stalagmites (the normal ones, not the dark ones) are dense again as intended.
Also made the little crystals pushing out of the ground nondense as that was weird.
I pranked Grayson by accidentally making the dark stalagmites dense when he didn't want, then he counterpranked me by making the other ones dense.
:cl:
fix: fixed a couple density issues on some rocks
/:cl:

Rock density fixes

---

code/__DEFINES/_subsystems.dm
code/__DEFINES/xeno.dm
code/controllers/subsystem/mobs.dm
code/datums/status_effects/debuffs.dm
code/datums/status_effects/sectoid.dm
code/datums/status_effects/status_effect.dm
code/datums/status_effects/xeno_buffs.dm
code/modules/mob/living/brain/life.dm
code/modules/mob/living/carbon/human/dummy.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/carbon/life.dm
code/modules/mob/living/carbon/xenomorph/castes/puppet/puppet.dm
code/modules/mob/living/carbon/xenomorph/life.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/mob/living/living.dm
code/modules/mob/living/silicon/ai/life.dm
code/modules/mob/living/simple_animal/friendly/cat.dm
code/modules/mob/living/simple_animal/friendly/corgi.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/mob/living/simple_animal/friendly/parrot.dm
code/modules/mob/living/simple_animal/hostile/carp.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm

Makes xenomorph health/sunder healing, evo progress, maturity, and plasma regen scale based on delta_time/second_per_tick, also makes some of the xenomorph status effect buffs also use this system for their ticking healing 
In cases where lag gets really bad, this can really help, as each tick will heal more based on how much time has passed since the last time it has run. 
:cl:
add: Xenomorph life will now adjust the amount of healing/sunder/plasma/evo/maturity based on any extra time that Life has not run for.
/:cl:

Makes xenomorph health/sunder healing, evo progress, maturity, and plasma regen scale based on delta_time/second_per_tick

---

code/modules/mob/living/carbon/xenomorph/saddles.dm

title
bugs bad
:cl:
fix: Runner saddles now correctly unbuckle the mob riding if they are removed
/:cl:

Fix runner saddles not unbuckling a rider if the runner is desaddled

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
_maps/modularmaps/big_red/bigredatmosvar2.dmm
_maps/modularmaps/big_red/bigredatmosvar3.dmm
_maps/modularmaps/big_red/bigredatmosvar4.dmm
_maps/modularmaps/big_red/bigredatmosvar5.dmm
_maps/modularmaps/big_red/bigredatmosvar6.dmm
code/game/objects/structures/barsign.dm

The invincible area in Big Red atmos now has enclosed area and forcefields to prevent wraith cheese.
Barsigns now go on walls like they should.
Fixed a stray mirror.
Fixes
:cl:
fix: Wraiths can no longer cheese into the hull area of Big Red atmos.
fix: Barsigns now go on walls again.
fix: Fixed a floating mirror on Big Red.
/:cl:

Fixes bigred area and barsigns.

---

_maps/modularmaps/big_red/bigredlibraryvar1.dmm

Bookshelves in BR had a funny var edit to be nondense.
I have no idea why this is the case, so cleaning it up.
Mystery var edit bad.
:cl:
fix: fixed some bookshelves on Big Red being nondense
/:cl:

Big Red bookshelf density fix

---

code/__DEFINES/loadout.dm

See title. This gun has the incredible 21 sunder per shot and 140 damage of the GL54 while also being able to provide its own suppressive fire and finishing shots that the GL54 cant. This gun is comparable to the other high end req weapons such as the scout rifle and AMR and should stay as a req weapon rather than being free roundstart. 
"who gives out 520 points req guns for free" -yyzsong 2023
:cl:
balance: AR55 is no longer in FC and SL vendors.
/:cl:

Removes AR55 from SL and FC vendors

---

code/modules/projectiles/ammo_types/mortar_ammo.dm
code/modules/projectiles/ammo_types/tx54_ammo.dm

Mortar smokes no longer have any flash.
GL54 smokes no longer deal shrapnel.
Getting flashed by tangle/cloak smoke is super annoying, and it seems like an oversight that mortar has flash range while howie doesnt.
GL54 smokes are hard to use as support because each of the 5 projectiles has a 10% chance to shrap, quickly filling your teammates with metal.
Support ammo types are underused and shouldnt harm your own team when you try to use them.
:cl:
balance: Mortar smokes no longer flash teammates.
balance: GL54 smoke ammos no longer shrapnel teammates.
/:cl:

Reduces friendly fire on support ammo types

---

code/modules/mob/living/living.dm

x player has been away for 3000 minutes!
bug fix
:cl:
fix: AFK alert now shows the correct amount of minutes afk.
/:cl:

AFK alert now reads correctly

---

code/datums/components/jump.dm
code/modules/mob/living/carbon/update_icons.dm

Jumping now uses pixel_z instead of pixel_y (like TG) to represent height. This means it doesn't interfer with anything else that edits (and hard sets) pixel_y, like pull offsets.
Fixed jumping layer being weird if you're on a higherly layer (like being on a tank).
Fixed a small visual bug when jumping in water.
Fixed pixel offsets getting messed up with drags in some situations
Ivan will stop bullying me now
:cl:
fix: fixed some minor visual issues with jumping in some situations
fix: Fixed some drag pixel offset issues
/:cl:

Jump and related fixes

---

code/modules/reagents/reagent_containers/hypospray.dm

Added a check in the hypospray code that creates a 2 second delay on attempting to inject someone else who is not the same faction as you and alerting both the injectee and injector as to this occuring.
Tested on a local client with zero (0) runtimes/errors
Made sincerily with imdedplzrestart energy.
In any situation where HvH is involved, if one person has a peridaxon+ or qc/qc+ full hypospray set to inject on maximum they can just click on an enemy once in close range (use shield if you want to get close) and they will die in 10 seconds flat unless they already have extreme amounts of hypervene in their system. This fundamentally changes how HvH gamemodes work by having one person with a shield running around with hyposprays injecting people with OD levels of meds and almost instantly …

Hyposprays/Autoinjectors now have 2 second injection delay on non-same faction injectees

---

code/game/objects/machinery/vending/marine_vending.dm

Removes Bomb Vest from Marine Vendors
Kuro said he'd merge #16489 if I did this.
:cl:
balance: Explosive Vests no longer in marine vendors.
/:cl:

Removes Bomb Vest from Marine Vendors

---

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm

Clarifies that you can't attack or dodge point blank shots in the ability description
Less rouny's going "THE ABILITY SAYS I DODGE ALL PROJECTILES SO I SHOULD DODGE THEM AAALL"
:cl:
spellcheck: Runner evasion ability text updated to clarify that you can't slash while evading, and that point blank shots still hit you.
/:cl:

Minor runner evasion description update

---

code/modules/mob/living/carbon/xenomorph/damage_procs.dm

See title
Devastation has been somewhat iffy for a while. In general, devastation explosions are hard to land. CAS rockets, OBs, suicide vests etc. are some of the few ways that devastation explosions can occur, but they're also extremely hard to land. Xeno buffs have made devastation less impactful, and it rarely gibs xenomorphs.
:cl: Joe13413
balance: Devastation does 100 more damage to xenomorphs
/:cl:

Increases devastation damage by 100 against xenos

---

code/game/objects/structures/rappel_system.dm

- Rappel now allows more than one person to use it at once
- Rappel no longer retracts after every person using it
- Rappel takes twice as long.
- Rappel now allows fireman carrying, taking twice as long.
Rappel currently sucks. Only one person can use it at a time, and shuffling the one person is extremely easy. Going up it requires the TO to replace it over and over, making it require constant attention and impossible to use to help small groups retreat. It also disallows fireman carrying so medics get little use out of it. These problems all combine to make it incredibly clunky and hardly worth the same slot as the HSG.
This PR intends to encourage its use in both large and small team play, rather than only as a way to move individuals up and down as it currently is. The time it takes …

Improves Rappel

---

code/datums/components/_component.dm
code/datums/components/companion.dm
code/modules/clothing/modular_armor/attachments/modules.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm

Tyr now has 50% ranged stun mitigation like B18.
Also added a remove_component proc since I noticed the same getcomponent stuff was being used in various places.
Makes Tyr more viable compared to just running overclocked shield mod, by making shotgun stuns unreliable against it.
Also turbo charges stun mitigation if you're packing Tyr and a shield.
:cl:
balance: Campaign: Gave Tyr for both factions 50% ranged stun mitigation like B18
/:cl:

Tyr HvH buff

---

code/modules/projectiles/ammo_types/ags_ammo.dm
code/modules/projectiles/ammo_types/microrail_ammo.dm
code/modules/projectiles/ammo_types/rocket_ammo.dm
code/modules/projectiles/ammo_types/tx54_ammo.dm

Secondary projectiles (i.e. tx54 and various others) now consistantly deploy their secondary projectiles one step back from their impact target.
Also added a missing arg for knockback on the TX54 specifically (technically a nerf)
A recent bug fix to these projectiles (stopping them from spawning a variable distance away from their impact target) had the side effect of making direct hits a lot more powerful, since they then reliably hit with all projectiles.
This should tone that down a bit, while still being consistant.
:cl:
balance: Reduced direct hit damage from GL-54 and other related ammo types against most targets
/:cl:

Secondary projectile changes

---

code/modules/mob/living/carbon/human/human_defense.dm

Lowered melee stun chances by a flat 10% (i.e. a 15% stun chance is now 5%).
Melee stuns no longer chain stun.
Melee stun chance now scales with maxhp (i.e. the health perks will make you harder to melee stun).
Less ggnore while still being extremely dangerous.
:cl:
balance: Campaign: Melee stun chance lowered by a flat 10%
balance: Campaign: Melee stun chance scales with max hp
balance: Campaign: Melee stuns can no longer chainstun
/:cl:

HvH melee stun changes

---

code/__DEFINES/traits.dm
code/datums/gamemodes/campaign/perks.dm
code/game/objects/items/stacks/stack.dm
code/game/objects/structures/barricade.dm

The construction perk now gives Engineers (and only engineers) an additional bonus:
Metal barricades have an extra 75hp (37.5% more) and plasteel cades have an extra 100hp (20%).
Made the perk a little more expensive.
Engineers are kinda lacking in benefits, and cades in general are rather easy to destroy in HvH, so this should make them a little better at fortifying without just being omega strong.
:cl:
balance: Campaign: Construction perk allows Engineers to build stronger cades
/:cl:

Campaign engineer buff

---

code/modules/mob/living/carbon/xenomorph/life.dm

Didn't realize heal_wounds was used in other places, this gives it a default arg of expected seco
Fixes bad bugs and hopefully makes the revert PR not needed
:cl:
fix: shrike healing and crit healing should now work
add: regen delays now properly are handled by seconds_per_tick
/:cl:

fix shrike healing & crit healing and properly addresses regen delays

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm

Reduced Hunter health from 360 to 320.
Increased melee armour from 40 back to 55.
The Kuro buffs really made hunter far stronger than it had any business being, with the sole exception of melee (where it should be strongest), where it was actually significantly nerfed.
This change reduces it overall survivability while preserving/restoring its melee toughness.
:cl:
balance: Hunter health reduced from 360 to 320
balance: Hunter melee armour increased from 40 back to 55
/:cl:

Hunter stat adjustment

---

code/game/turfs/walls/resin.dm
code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm

Gives fireproof and bulletproof resin walls +150 max health.
Gives hardy resin walls +100 health, as well as 50 melee armor and 50 bomb armor.
Special Resin walls now cost 125 instead of 100 psy points.
The special resin walls are laughably bad for how limited their uses are, especially considering that they die *in the exact same amount of melee hits* compared to normal resin walls, with the exception of hardy walls because they have more max health.
Well, now that isn't quite the case: all special walls are now actually better than resin walls at least by a marginal amount thanks to *all* of them having extra health, while hardy resin walls are explicitly the counter to melee and make for a good general usage upgrade compared to normal walls. Better get out the flamer or these ones. …

Buffs Special Resin Walls

---

code/datums/jobs/job/survivor.dm
code/game/objects/items/tools/hydro_tools.dm
code/game/objects/items/tools/surgery_tools.dm
code/modules/admin/verbs/selectequipment.dm
code/modules/clothing/suits/armor.dm
code/modules/clothing/suits/jobs.dm
code/modules/mob/living/carbon/life.dm
code/modules/reagents/chemistry/reagents/other.dm

Adds new stuff for survivor and survivor v zombie events.
Water now purges zombium (Mandela effect, I always thought it already did this).
Survivors now have water bottles.
Alcohol now gives pain reduction at lower thresholds.
Hatchets, scythes, scalpels, and circular saws all have decent melee stats now.
Armor vests now fit guns, aprons now fit hatchets and scythes.
Certain survivor loadouts now have more equipment, such as atmos tech getting metal foam nades and chaplain getting a shotgun.
Added a few new survivor loadouts:
Bartender, equipped with a shotgun and lots of alcohol.
Chemist, equipped with hyposprays and medical equipment.
Roboticist, equipped with tools and a build-a-sentry.
Easier survivor events and more survivor content. Survivors v zombies is now much easier to set up! …

Survivening: More survivor content

---

code/modules/ai/presets/zombie_presets.dm
code/modules/mob/living/carbon/human/species_types/zombies.dm
code/modules/mob/living/carbon/human/zombie.dm

Adds a new zombie, the Smoker.
Has an ability to emit a smokescreen to help hordes of zombies close the gap on people with guns.
AI Smokers will use this ability when 2 tiles from a target or when below 50% health.
https://github.com/user-attachments/assets/1ef9d794-b7f7-43b1-b52e-b31738f453a0
More variety for zombie events
:cl:
add: Added new zombie type, the Smoker.
/:cl:

Adds Smoker Zombie

---

code/game/atoms/atom_movable.dm
code/modules/mob/living/carbon/human/human.dm

Z change fix

---

code/__DEFINES/vehicles.dm
code/modules/projectiles/projectile.dm
code/modules/vehicles/unmanned/deployable_vehicles.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm

Fixed deployable Iguana having way more health then the normal one.
Deployable Iguana IFF signal is set off the deploying mob.
Unmanned vehicles now display their hud to the correct faction.
Normalised unmanned vehicle armour so its not immune to energy damage anymore.
:cl:
fix: fixed deployable Iguana HP being higher than intended
add: Unmanned vehicle IFF and hud are based off the deploying mob
balance: Unmanned vehicles no longer have 100 energy armour
/:cl:

Unmanned vehicle fixes

---

code/datums/components/deployable_item.dm
code/modules/projectiles/guns/sentries.dm

COPE sentries properly display their health/ammo on the currect hudtype if throw deployed.
Currently they only show up if normally deployed, which is basically never, with the COPE.
:cl:
fix: cope sentry hud appears correctly when deployed via throw
/:cl:

COPE hud fix

---

code/game/objects/items/radio/detpack.dm
code/modules/assembly/signaler.dm

Detpacks and signallers now randomise their signal code when spawned.
While very uncommon, if multiple people are using detpacks at the same time, they'll likely trigger the other guys detpacks because most people don't bother to change the code or freq.
This changes makes it very unlikely to happen accidentally.
:cl:
qol: Detpack and signaller code is randomised upon spawn
/:cl:

Detpack code randomisation

---

code/datums/components/jump.dm
code/modules/animations/animation_library.dm

A better fix to a weird animate interaction.
The previous fix (and someone please tell me why byond has this issue to begin with) meant we critically lost jump spin animations when gravity is turned down.
This fix ensures jumps don't fuck out in water, while jump spin still works.
Spin2win
:cl:
fix: jump spins work again in low grav
/:cl:

Weird animate fix

---

code/datums/gamemodes/campaign/individual_stats.dm

Loadouts can now only be equipt once the next mission is selected.
Encourages players to be more strategic in their loadout choices, based on mission type.
Particular with the secondary kit PR in mind.
:cl:
add: Campaign: Loadouts cannot be equipt until the next mission has been selected
/:cl:

Can't equip loadout before mission selection

---

code/game/objects/machinery/camera/deployable_camera.dm

Small campaign change to delete any deployed cameras at the end of the mission, so they don't clog up the camera menu.
:cl:
qol: Campaign: Any deployed cameras are deleted on mission end
/:cl:

Deployable camera cleanup on mission end

---

code/datums/gamemodes/campaign.dm

When a new mission is selected, the campaign overview screen is opened for all players.
This popup means all players will see (whether they actually read it is another question) the mission briefing/objectives, encouraging them to think about what they're going to do.
:cl:
add: Campaign: Mission briefing pops up when a new mission is chosen
/:cl:

Mission brief popup

---

code/modules/projectiles/sentries.dm

Fixes a runtime for sentry targeting, when they're not on a turf (i.e. tad/alamo sentries)
I noticed this runtime for sentries months ago, but forgot to PR it.
:cl:
fix: fixed a sentry runtime
/:cl:

Sentry targeting fix

---

code/modules/projectiles/guns/shotguns.dm
code/modules/reqs/supplypacks.dm

Removed the sawn-off from req.
Returneddamage mult back to 1 (was 0.7).
Returned back to one hand fire.
Doubled damage falloff.
Also added some missing SECONDS defines
Sawn off was in a weird place where as a cheap req gun, it used to just be a straight upgrade to the actual marine DB, while after the collective db nerfs it just became a straight downgrade in every possible way.
With these changes its purged from marine use as it should have always been, and turns it back into the nasty cqc weapon that it used to be, with higher damage, but huge fall off( at 3 tile stun range, after these changes it will actually do noticably **less** damage than it does currently), which makes it more useful in its actual niche of ERT/HvH weapon.
:cl:
del: Sawn-off shotgun removed from req
balance: …

Sawn-off changes

---

code/game/objects/items/stacks/sandbags.dm

Removes a break in the loop that caused you to loose a sandbag
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/16606
People don't like the last sandbag when they empty
:cl:
fix: You no longer loose the last sandbag when emptying full sandbags
/:cl:

fix sandbag emptying not giving you the last sandbag back

---

_maps/map_files/desertdam/desertdam.dmm

What it says on the tin. No more open-air plats, some were made phorons. Plat miners added to the underground lab. Intel computer that had infinite power killed, since that ship is simply powered.
Not being able to turn off an intel computer is not ideal, and every game (even on a bad map) turning into rappeling for plat miners is sort of guh.
:cl:
balance: Removes a Chigusa intel computer, Chigusa plat miner removals and movals
/:cl:

Removes a Chigusa intel computer, Chigusa plat miner removals and movals

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

If you change z-levels while affected by Timeshift, it is canceled.
Updates Timeshift's description to mention that it is canceled if target changes z-levels.
Using Timeshift on marines who just barely left into orbit on the TAD and suddenly become marooned when they're pulled from orbit to ground side is apparently "bug abuse". So, bug fixing.
:cl:
fix: Wraith's Timeshift cancels if the target changes z-levels.
/:cl:

Wraith's Timeshift Cancels on Z-Level Change

---

code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/living_defense.dm
code/modules/projectiles/guns/_shared_ammo_objects.dm

Fire and the type of fire that Pyrogen uses now considers soft armor (instead of hard armor) and also prevents your body temperature from increasing. This means:
- No more endless screaming for walking through fire.
- No more taking damage for walking through fire.
- No more getting too hot for walking through fire.
- Because of all of the above, your very fragile splints no longer instantly break for walking through fire.
I hope that H-Armor + Surt not getting actual fire immunity is a bug and not a feature.
:cl:
fix: All types of fire no longer damages or heats you up if you have 100% fire soft/hard armor.
/:cl:

Having 100% Fire Armor Gives You Actual Fire Immunity

---

code/modules/mob/living/carbon/inventory.dm

Fixes handcuffs breaking your resist and still trying to resist non-existant handcuffs after you were handcuffed once, super annoying, doesn't let you resist fire.
Fixes a tiny annoyance that nobody has bothered to fix
:cl:
fix: Handcuffs won't break your resist anymore
/:cl:

fixes handcuffs breaking resist when you are un-handcuffed

---

code/__DEFINES/loadout.dm
tgui/packages/tgui/interfaces/LoadoutManager/index.tsx

Mostly the title
Easier preparation for FC and synth players
:cl:
qol: The loadout vendor now contains two new tabs for the Field Commander and the Synthetic. Loadout vendor now works with their respective essential kits.
/:cl:

FC and Synth loadout vendor tabs + their respective essential kits work with loadout vendors

---

code/modules/vehicles/mecha/_mecha.dm
code/modules/vehicles/mecha/mecha_defense.dm

Buffed the effects of EMP'ing a mech.
Energy drain base amount increased from 20% to 40%.
Damage base increased from 400 to 600.
Occupant stagger base increased from 6 to 8 seconds.
Weapon disable base time increased from 4 to 5 seconds.
Weapon disable effects now stack in duration, so you can basically chain stun mechs with EMP spam.
Makes EMP's better against what is probably their main target.
:cl:
balance: Buffed EMP effects against mechs
/:cl:

Mech EMP buffs

---

code/game/objects/structures/dropship_equipment.dm

Fixes #16668 
Sentries will no longer fire when undeployed out of sentry tad modules.
:cl:
fix: fixed sentries being able to fire out of undeployed sentry holders
/:cl:

Sentry deploy fix

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

When shutters are closed, the ability cost for planting weeds is halved upfront rather than costing half after successful ability usage. 
The ability's button now shows the current ability cost rather than the consistent 75.
This essentially means:
- No more error messages when you try to plant weeds despite having enough plasma to afford the discounted price.
- You can actively see the ability cost of what weed you want to plant.
Bugfix and it is nice to see what the ability costs when you change weeds besides "alot" or "more than normal weeds".
:cl:
qol: Plant Weeds ability's button now dynamically shows its ability cost rather than the consistent 75.
fix: Plants Weeds ability no longer prevents usage if you have more than post-discounted, but less than before-discounted plasma (for …

Plant Weeds Dynamically Shows Ability Cost

---

code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm

title
We use the map based system now so this is just pointless now
:cl:
del: Remove tunnel naming
/:cl:

Remove tunnel naming

---

code/datums/keybinding/human.dm
code/datums/keybinding/living.dm

Swaps jump to C and unique action to spacebar.
Jumping being on spacebar by default makes no sense. It isn't a common occurance and usually is a specialized action to deal with a specialized problem while unique action is pretty key to using like an entire subclass of weapons for mahrines and beans. I don't get why unique action was moved instead of jump. This mainly is to help new players. There's also a bunch of critical xeno stuff put on spacebar like charge toggle and rage.
:cl:
tweak: Unique action by default is back on spacebar while jump is on C.
/:cl:

Swaps unique action and jump default keybinds.

---

code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm

What it says on the title.
This probably shouldn't be happen, no idea why it was changed.
:cl:
fix: Naming a tunnel no longer leaks your ckey
/:cl:

Naming a tunnel no longer leaks your ckey

---

code/modules/projectiles/sentries.dm

Fixes #16694 and other various ways of exploiting sentries into walls. Now they will simply not fire on a dense turf.
Also some mild code cleanup:
Consolidated some copy paste code for sentry stop fire into a proc.
Removed a redundant smoke check in pathing.
:cl:
fix: fixed a sentry exploit
/:cl:

Sentry exploit fix

---

code/datums/personal_statistics.dm
code/game/objects/items/explosives/grenades/grenade.dm

Fixes the nade hand exploding message playing if your hand wasn't actually blown off (i.e. a sticky nade on you, or stored directly in a pocket slot etc).
Also added a personal stat to make you feel bad about how many hands you blew off because you threw the pin instead of the nade.
:cl:
fix: fixed the grenade hand explode message playing if your hand wasn't actually blown off
/:cl:

Nade message fix

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Xenomorphs who walk now ignore portals.
Prevents accidental wraith grief with portals and to match the fact that marines can move ontop of portals while xenos cannot without entering.
:cl:
balance: Xenomorphs can toggle movement intent to walk in order to bypass/ignore wraith portals.
/:cl:

Xenomorphs can walk to ignore portals

---

code/__DEFINES/jobs.dm

Changes the Xeno to Marine ratio back to 2.46, down from 3, as it was originally.
I originally suggested that the xeno ratio should be turned down because the stat buffs coupled with how hard they can stack from drains was making them snowball hard once they got a few drains going. The issue now is that both the xeno to marine ratio and the drain points required for a new larva got simultaneously nerfed, and now we're running into the issue where deaths are far more punishing and doom you to the 20 minute long respawn timer if you were hoping to queue up again. I've gone entire rounds without being able to join because of how long the queue takes.
For that reason, I'd rather try reverting the ratio change and keep the drain change to see if this makes it less painful to play xeno.
:cl: …

Changes Xeno to Marine ratio back to 2.46

---

code/modules/mob/living/carbon/xenomorph/charge_crush.dm

When a Crusher crushes a living being into being QDEL'd, the text correctly says "annihilates" instead of "anihilates".
:cl:
spellcheck: Crusher now annihilates instead of "anihilates".
/:cl:

Fixes crusher "anihilate" typo

---

code/game/objects/items/radio/detpack.dm
code/modules/vehicles/unmanned/deployable_vehicles.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm

Skinks are not meant to have any combat capabilities.
No more unavoidable dev explosive.
:cl:
fix: Skinks can no longer take c4 as a weapon.
/:cl:

Fixes skinks equipping C4 as a weapon

---

code/datums/storage/subtypes/internal.dm

Not 100% sure this is the best fix, but A: I don't want to dive into inventory code and force weight classes to take priority over the can_hold() list, which would cause a whole bunch of other issues, and B : I can't think of a way to make it specifically ignore all children of a type. Hence this bandaid fix 
Less INFINITE AMMO*
:cl:
balance: Standard webbing can no longer hold powerpacks/powerbackpacks
/:cl:

Standard webbing can't hold powerpacks/powerbackpacks anymore

---

code/modules/mob/living/carbon/xenomorph/embryo.dm

Chestbursting can happen in the Deathmatch Area (as in the area where you go to when you EORD Respawn) without admin intervention.
If people wanna play xenos during EORD, they should be allowed to. And the people who don't wanna play xeno should be able to shoot said xenos for existing. Only really happens if EORD lasts ages and not when the round restarts in a couple minutes.
:cl:
add: You can now chestburst while in EORD/Deathmatch Area without requiring admin intervention.
/:cl:

Chestbursting can now happen in EORD/Deathmatch

---

_maps/map_files/Research_Outpost/Research_Outpost.dmm

Moves and removes some of the landing sites that were dysfunctional.
These spots either had sides completely blocked, only open to a one tile gap, or in one case completely crushed one of the disks. These spots will be far less painful to play.
:cl:
balance: Moved some crash landing sites on Research Outpost.
/:cl:

Moves crash landing spots on Research Outpost

---

_maps/map_files/Bluesummers/bluesummers.dmm

Various changes to make the map slightly less hostile.
<details>
<summary>Pictures</summary>
Less clutter on the south of Hydroponics Wing
Wider path above the dormitories
Various small things, such as the west disk being wide enough for vehicles without breaking any walls.
</details>
Research digsites are now roughly 60% out of caves.
Caves are generally a bit wider.
Less hostile toward marines, paths are more equal now.
:cl:
balance: Bluesummers is a bit easier for marines now.
/:cl:

Bluesummers v1.1 patch

---

code/modules/reqs/supplypacks.dm

Salt PR? Maybe.
Rocket sledge is sort of analogous to the ZX in that they're both powerful melee weapons with high damage and no ammo costs. Technically the ZX can fit slug but like who cares about slugs
Despite this, rocket sledge's price is radically lower than the ZX's despite the addition of a new feature (stunning t3s). It should have a price tag similar to the ZX, if not identical.
It shouldn't cost literally one t3 at the very least.
:cl:
balance: Rocket sledge price 600 -> 850
/:cl:

Increases rocket sledge price

---

code/datums/gamemodes/campaign/loadout_items/_TGMC/secondaries.dm

Fix the SH-34 secondary in campaign for smartgunners actually spawning the gun.
:cl:
fix: Campaign: Fixed SH-34 secondary not spawning
/:cl:

SH-34 secondary fix

---

code/game/objects/structures/barricade.dm

To go with https://github.com/tgstation/TerraGov-Marine-Corps/pull/16557.
Buffs most barricade types. Changes are as follows:
> **Barbed Wire Upgrade**
> Damage: 10 -> 15
Meant to compensate for xeno health and armor buffs slightly. Still worse than before.
> **Metal Barricade**
> Health: 200 -> 250(300 with barbed wire)
> Concussive Upgrade: 40 bomb armor -> 80 
> Ballistic Upgrade: 30 bullet/laser/energy armor -> 50(80 with base armor)
> Acid Upgrade: 20 acid armor -> 35(75 with base armor)
My thoughts here are that metal cades are laughably weak in all aspects and their upgrades do not help this feeling. This is probably the biggest buff here, and I am willing to tone it down a bit or perhaps increase the cost to build them to 5 to compensate. 
Firstly, acid cades are the big one: a …

Buffs Barricades

---

code/__DEFINES/skills.dm
code/modules/vehicles/powerloader.dm

Powerloader skill now affects movement speed while inside of a powerloader as intended where each point decreases movement delay by 0.1 seconds.
For powerloaders, the base movement delay has been increased from 0.4 seconds to 0.6 seconds and the least possible delay is 0.2 seconds. This (plus bugfix) means the following:
Everyone Else: 33% slower
Engineers: 20% slower
FC/SO: Unchanged
PO/TO/Mech/AC/TC: 25% faster
Synths/Captain/CE/RO/ST: 50% faster
Bugfix. As for the balance change, 0.4 seconds became the norm for at least 7 whole months (aka how long this was broken); everyone got used to it or don't care anymore. So, make it worse for marines (who shouldn't be doing this anyways) and better for shipside roles.
:cl:
balance: Powerloader is now generally slower for marines, but generally …

Changes Powerloader Speed & Fixes Powerloader Skill

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm

Hunter stealth being broken is now by total damage received in stealth, instead of the damage from a single hit being over a threshold.
The number is now 45 damage (number pulled out of my ass). i.e. a full burst from a rifle will break stealth, but 1-2 shots probably won't.
The damage threshold recovers by 10 damage per sec (i.e. you get hit once or twice so you're 25/45 damage taken, but stay stealthed and wait around a corner for a bit, and that recovers back to 0/45.
Less fucking god awful, certain guns were previously hard locked out of ever breaking stealth.
This is only set to get worse with the new mechanic letting xenos buff their armour, locking out more guns from stealth break.
:cl:
balance: Hunter stealth break from incoming damage is now a total amount (45) instead of a …

Hunter stealth damage threshold

---

code/datums/gamemodes/nuclear_war.dm

Raises silo scaling to 2x from 1.5x. 
This will result in the same amount of xenos roundstart while providing 33% more larva gen during the round.
For context, silo scaling was 2x up until #13925 which reduced it during the time of maturity removal.
Since then, 2 major changes have been made to larva gen:
First, the ratio scaling was fixed in #15523 and #15563.
These changes mean that xenos are less likely to reach an overbearing ratio via passive generation alone.
Secondly, points required for a larva was increased with #16572 (and later #16697 making that the only change)
This resulted in 25% less xenos, which was a necessary change roundstart but leaves xenos rarely with enough larva gen to ever have more xenos than roundstart - often xenos will die causing others to die and creating a …

Raises silo scaling to 2x

---

code/modules/admin/admin_verbs.dm

Removes the [Yes / No] prompt from the toggle_sleep verb.
9/10 times this gets used you want it being done as quickly as possible so having a confirmation prompt is not a good thing, and if you are misclicking it you can undo it just as easily.
:cl:
admin: Toggle Sleeping no longer has a confirmation prompt.
/:cl:

Removes confirmation for toggle_sleep verb

---

code/modules/projectiles/ammo_types/energy_ammo.dm

Direct hits from a tesla no longer drains plasma from castes that have the CASTE_PLASMADRAIN_IMMUNE caste flag.
The castes are immune to plasma drain. This tesla ball drains plasma from castes that are immune when they aren't suppose to. Bugfix.
:cl:
fix: Xeno castes who are suppose to be immune from plasma drain no longer have their plasma drained when directly hit by a tesla ball.
/:cl:

Direct Hits from Tesla Ball no longer drains from the Plasmadrain Immune

---

_maps/shuttles/tgs_bigbury.dmm
_maps/shuttles/tgs_canterbury.dmm

Fixes the buttons on the south end of the canterbury and bigbury being inaccessible, preventing opening the south entryways.
Being able to open doors is good
<details> 
<summary>screenshot</summary> 
</details>   
I was not able to test bigbury since I couldn't figure out how to make the server load it, but, since it's a near identical change I think it's safe.
:cl:
fix: fixed buttons on canterbury and bigbury for opening the south entryways
/:cl:

Fixes inaccessible buttons on canterbury and bigbury

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Wraith portals are unaffected by lava.
Bugfix. I don't see why portals should be affected by lava since lava deals direct damage to the portal as opposed to everything else which either does nothing (bullets) or straight up deletes it (grenades). Seems like an oversight.
:cl:
fix: Wraith portals are no longer affected / destroyed by lava.
/:cl:

Wraith Portals are Lava Immune

---

code/modules/shuttle/mini_dropship.dm

This fixes the hunter from being able to break the tad console from stealth
1. Breaking objects from stealth does not appear to have been intentional to begin with:
<details> 
<summary>Original object attack interaction code</summary>
`/datum/action/ability/xeno_action/stealth/proc/on_obj_attack(datum/source, obj/attacked)
SIGNAL_HANDLER
if(attacked.resistance_flags & XENO_DAMAGEABLE)
cancel_stealth()`
</details>
2. Stealth hides the interaction telegraph as pictured in this screenshot. (Which further indicates that "free" kills of the tad was likely never intended).
<details> 
<summary>Interaction telegraph</summary>
</details>
3. Balance considerations:
3.A There is a lack of effective counter to this beyond baby sitting the console constantly, which is anti fun.
3.B Hunter stealth and …

Fixes hunter being able to break the tad console from stealth

---

code/_globalvars/lists/mobs.dm
code/datums/gamemodes/_game_mode.dm
code/datums/gamemodes/crash.dm
code/modules/mob/living/carbon/xenomorph/evolution.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Various changes to make crash more fair.
- Removes hivemind, hivelord, and wraith from crash.
- Xenos get extra t3 slots one xeno later on crash. (see below)
<details> 
<summary> How many xenos for a t3 slot? </summary>
</details>
1. Wraith is the bane of this mode and can very easily cheese the Canterbury, this is not fun gameplay and lowpop suffers from having wraith in this mode. Hivemind is completely unkillable on crash and very annoying when it endlessly spams sticky weeds and walls, and hivelord is in a similar position with its large bulk allowing it to spam endless resin and sticky weeds, while also having the healbeam which can give a queen or other large xeno nearly 100% uptime, which is a bit too strong when marines are so short on staff.
2. Marines are not well equipped to …

Rebalances Crash

---

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm

Title
These are both free inputs like selecting pheromones and therefore shouldnt be eaten by stagger.
:cl:
balance: Defiler and carrier can now pick reagents/huggers while staggered.
/:cl:

Defiler and carrier can now pick reagents/huggers while staggered

---

code/game/objects/machinery/nuclearbomb.dm

Prevent activating nuke from showing both your ic name and ckey in dchat
Good for people that want to keep their IC secret
:cl:
fix: fixed nuke notification in dchat
/:cl:

Give (some) privacy back to nuke activation

---

code/modules/projectiles/ammo_types/rocket_ammo.dm

Reduced HE sadar AP value to 75 from 100.
Reduces HE sadar sunder to 50 from 100.
Semi related change, unguided HE rockets now throw mobs 4 tiles instead of a rediculous 7.
The way sunder interacts with explosions from the rocket means HE rockets actually do MORE direct damage than an AP sadar against all xenos, while also dealing slowdown and stagger.
This means HE rockets are objectively better, other than the possibility of FF splash damage.
:cl:
balance: Reduced HE sadar AP value to 75 from 100
balance: Reduces HE sadar sunder to 50 from 100
balance: Unguided HE sadar rockets throw mobs 4 tiles instead of 7
/:cl:

HE sadar nerf

---

code/modules/mob/living/carbon/xenomorph/xenomorph.dm

During prep / quickbuild phase, xenomorphs can now pull items without a delay.
We got quickbuild. Half cost on weeds. Surely we can have instant pull as well? It's annoying to wait to pull items during the prep phase.
:cl:
qol: During prep / quickbuild phase, xenomorphs can now pull items without a delay.
/:cl:

Xenos can instantly pull items during Quickbuild phase

---

code/controllers/subsystem/explosions.dm

Fixes explosion throw range of 0 not being respected.
Plasma cannon blast mode will no longer throw things on direct hit.
:cl:
fix: fixed plasma cannon blast mode causing throw on direct hit
/:cl:

Explosion throw range fix

---

code/game/objects/machinery/vending/vending.dm
code/modules/vehicles/_hitbox.dm
code/modules/vehicles/armored/_multitile.dm
code/modules/vehicles/armored/som_tank.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale.dm

Adds explosion block to tanks, mechs and vending machines.
1 for vendors and tank (although being multitile, it will effectively be more for tank)
2 for the fat mechs.
For those unaware, explosion block basically means the range drawn through that obj/turf is reduced by that number.
I.e. with a block of 1, standing behind a vendor will protect you from the 3 tile range grenade in the pic below, but a grenade right next to the vendor would still hit you.
Also slightly tweaked bomb armour for HvH tanks (5 less soft armour, 5 more hard) to maintain more or less the same damage from actual explosions.
More interesting ways to interact with/mitigate explosions.
:cl:
balance: Added some explosion block to vendors, mechs and tanks
/:cl:

Explosion block additions

---

code/game/objects/effects/misc.dm
code/game/turfs/closed.dm
code/modules/shuttle/marine_dropship.dm

Added explosion block to some stuff that was missing it.
Fixes #16413
Specifically, shuttle walls/structures, and fog blockers.
I'm tempted to add this to more things to make the game more interesting (i.e. hiding behind a vending machine to avoid a grenade explosion or something) but will leave that separate, as a walance change.
Explosions will no longer travel through the walls of the alamo as though it wasn't there at all (big enough explosions will go through, just like normal walls however).
:cl:
fix: Fixed shuttle walls and fog blockers being completely ignored by explosions
/:cl:

Explosion block fixes

---

code/game/objects/machinery/nuclearbomb.dm

You can no longer portal the nuke.
Fixes #12615
Being able to queen scree the marines and have a wraith drop a portal to instantly steal the nuke is cringe.
:cl:
balance: The nuke can no longer travel through portals
/:cl:

Nuke can no longer be portalled

---

code/game/objects/machinery/vending/vending.dm

Putting a fallen vendor up now makes it dense again.
Spooky ghost vendor bad.
:cl:
fix: fixed vendors being stuck as nondense after falling over
/:cl:

Vendor density fix

---

code/__DEFINES/tools.dm
code/_onclick/item_attack.dm
code/game/atoms/_atom.dm
code/game/objects/effects/weeds.dm
code/game/objects/items/tools/mining_tools.dm
code/game/objects/objs.dm
code/game/objects/structures/mineral_doors.dm
code/game/objects/structures/xeno.dm
code/game/turfs/closed.dm
code/game/turfs/walls/resin.dm
code/game/turfs/walls/wall_types.dm
code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
code/modules/xenomorph/_xeno_structure.dm
code/modules/xenomorph/xeno_turret.dm

Plasma cutters can be used on resin doors without a delay similar to resin walls.
Closes #16471
Weeds no longer has any plasma cutter interaction (as a normal attack is good enough to kill the weeds).
Closes #15284
By default, trying to use a plasma cutter on a object while on harm intent will try to attack the object normally if possible.
Other intents (or if above doesn't do anything) will try to cut down the object (which comes with the standard 1000 charge cost).
The bonus damage/interaction between plasma cutters and xeno turrets have been expanded to all xeno structures, but now causes 100 charge per attack.
1. I got annoyed that I can't one-shot resin doors with a plasma cutter (its also a bug).
2. I actually just wasted 1000 charge on cutting weeds on walls. I'm coping.
3. "Starts …

Plasma Cutter Changes

---

code/modules/projectiles/ammo_types/heavy_ammo.dm
code/modules/projectiles/ammo_types/rocket_ammo.dm

If you direct hit a mob with a rocket, you will now knock them back 1 tile BEFORE the explosion happens.
This means direct rocket hits will now knockback the target from the explosion AWAY from the firer, instead of rng any direction, which can easily ggnore xenos when they get rng knocked into the marine blob.
RNG ggnore from funny explosion mechanics is lame as shit.
:cl:
balance: Direct hit explosions from rockets will now reliably throw the victim away from the firer, instead of a random direction
/:cl:

Rocket explosion knockback improvement

---

code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm

Undoes #16049 for defiler speed, returning them to -1 speed
Speed is by far the most important stat for defiler and currently a defiler emitting frenzy is _**slower**_ than a light armor marine with a move order.
Defiler has access to many of the best tools for shutting down rusher marines such as neurotoxin and hemodile, both of which are completely useless when they are too slow to slash the marine. 
Making defiler a fat slow gas machine heavily skews its usefulness toward the queen screech -> gas combo, which leaves the caste as almost useless when xenos dont have a queen. Shifting defiler's power to itself instead of its queen combo will leave it in a much healthier state for the game.
:cl:
balance: Defiler: Speed increased by .1
/:cl:

Reverts Kuro defiler speed change

---

code/game/objects/machinery/squad_supply/supply_console.dm

Lowers the cooldown on the supply drop console from 30 seconds to 15.
RO frequently finds themselves overwhelmed by req orders on higher pop as more and more people are around to ask for ammo and other things right as you send a crate. Other shipside roles _should_ be able to help fill in when needed, but the console's long cooldown means even a lone RO will be sitting around staring at the timer tick.
Lowering the cooldown will free ROs to work more efficiently when orders are coming in rapidly, and allow 2 or more people to use the console without wasting time when it is needed on higher pop.
:cl:
balance: Supply drop console cooldown reduced from 30 seconds to 15.
/:cl:

Lowers supply drop cooldown.

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm

Changed damaged threshold to break hunter stealth to 25, from 45.
45 was way too high, taking into account armour.
:cl:
balance: Hunter stealth damage threhold changed to 25 from 45
/:cl:

Hunter stealth damage threshold change

---

code/game/turfs/walls/resin.dm

Increases plasma cutter's damage against resin walls from 231 to 301.
Bugfix since I didn't mean for plasma cutters to be nerfed this hard against resin walls.
:cl:
bugfix: Plasmacutters now do 301 damage instead of 231 damage against resin walls. Enough to one-shot thick resin walls as intended.
/:cl:

Plasmacutters one-shot common resin walls as intended

---

_maps/map_files/LV759/LV759.dmm

Xenos can no longer build outside the LZ
Fixes an oversight and brings it up to standard.
:cl:
Fix: Xenos can no longer build outside the LZ on LV759
/:cl:

Fixes xenos building outside LZ on LV759

---

code/modules/reqs/supplypacks.dm

What a mouthful.
As in the title, this PR increases the costs of scout rifle ammo in reqtorio for all of its magazines
Standard Magazines go from 200 points to 300 (50% cost to 66% cost)
Incendiary and Impact magazines go from 200 points to 600 (**25**% cost to 66% cost)
Similar reasoning as to #16479: The addition of these recipes to reqtorio effectively halved the price of this magazine. All of the requisite reqtorio parts to make them are given for free, so there is no "break-even" point where reqtorio _becomes_ more efficient than just buying the magazines outright; it simply is.
Incendiary and Impact magazines being the same price is some really nasty work as well, given that they cost twice as much as the regular magazines but can be made in reqtorio for a fourth(!) of their usual …

Increases the price of Scout Rifle reqtorio refills

---

code/modules/clothing/modular_armor/attachments/modules.dm

Add a clause to the eshield description, noting that it increases vulnerability to certain damage types.
Of the people that I've pointed this out to in game, it seems virtually no one is aware that using the shield module reduces their armor to certain damage types. Since armor modules don't have a codex link on shift-clicking them, and reviewing your armor's codex link only shows the final stats without any direct indicator of modifications, the only way one might notice this is if they carefully compare stats before and after applying a module.
Which almost no one seems to do and is a kind of hard thing to notice if you don't go in already looking for it.
This just makes the information more accessible.
:cl:
qol: eshield's description now notes that the eshield module reduces a marine's …

Adds details to the eshield module's description

---

code/modules/projectiles/guns/energy.dm

Turns out tesla gun is the only energy gun that can not equip recharger batteries. Seems like an oversight of the original pr #12997 since I do not see any mention of it.
Energy gun using standard energy cells should be able to use the side grade energy cells all the other energy guns use.
:cl:
balance: tesla rifle can use recharger batteries
/:cl:

Tesla rifle can now load rechargables.

---

code/datums/personal_statistics.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm

Warlock's Psychic Shield can be re-selected to switch to an alternative shield if they are Primordial.
The alternative shield halves the shield's health from 650 to 325.
The alternative shield can be detonated early to direct reflected projectiles toward a target in front of them (135 degrees).
Example of Warlock reflecting a Recoilless Rifle toward a Moth:
Example of Warlock's shield breaking too early because of the reduced health:
Comparison to Warlock's normal shield health:
Warlock is great at doing damage without having to risk much. Their abilities don't really need line of sight to their target as they do area-of-effect damage, though direct hits do more damage. In some cases, Warlock's Psychic Lance which is their current primo ability is arguably worse than their base Psychic …

Psychic Shield: Targetted Reflection (Warlock Primo)

---

code/game/objects/machinery/vending/marine_vending.dm

Plasma gun ammo is no longer free and unlimited from the standard vendor.
Powerful, spammable guns that are balanced around ammo scarcity are unsurprisingly unbalanced when there is no ammo scarcity. This leads to people repeatedly spamming explosive rounds because they can carry 40 mags around in a box with them.
The cannon should also really cost more than the other guns, but I'll leave that for another PR.
:cl:
balance: Plasma gun ammo has been confined to req
/:cl:

Plasma ammo to req

---

_maps/shuttles/minidropship_outrider.dmm

Removes the un-crushable spot on the outrider tad.
The red square is the tile that used to be immune to crusher charges, with the yellow arrows being the lanes that this PR opens up.
A positive of this is that vehicles can now enter/exit from the side entrance, as well as there being 2 new tiles of extra space.
Outrider tad is currently objectively the best tad on the majority of the maps in the game due to its indestructible back wall and very easily defendable choke entrances. It still is, but this makes it slightly less oppressive in spots where it would otherwise be nearly unkillable.
:cl:
balance: uncrushable tile in the outrider tad has been opened (side door made 3 tiles, windows extended to include north side walls)
/:cl:

Outrider tad tweaks

---

code/datums/elements/directional_attack.dm

What it says on the tin. This is mainly an issue for various xeno abilities, which will waste their CD on a ghost they can't see or interact with.
Ghost cuck is bad.
:cl:
fix: fixed directional attacks trying to hit ghosts
/:cl:

Directional attacks won't hit ghosts

---

code/__DEFINES/mobs.dm
code/__DEFINES/xeno.dm
code/_onclick/hud/screen_objects/screen_objects.dm
code/modules/xenomorph/_xeno_structure.dm
code/modules/xenomorph/resin_gargoyle.dm
code/modules/xenomorph/silo.dm
code/modules/xenomorph/spawner.dm
code/modules/xenomorph/xeno_turret.dm

Unfucked piles of horrible copy paste code in the pockets of various different xeno structures to instead be universal, and based off flags.
Fixes an issue where proxy alerts remained at the original z-level, even if the structure moved (i.e. silo on alamo) leading to hilarious issues like getting a warning when an ert spawns and knowing exactly what it is.
Also fixes silos not alerting if a vehicle approaches instead of a mob.
Bug fix, no more spaghetti.
:cl:
fix: fixed silos not alerting if a vehicle approached
fix: fixed xeno structures detecting things on old z-levels
code: Reworked some xeno structure damage and proximity alert code
/:cl:

Xeno structure alert fixes

---

_maps/map_files/Bluesummers/bluesummers.dmm

Replaces the stalagmites on bluesummers with small cosmetic rocks.
Random dense objects every 4 tiles is painful to play around.
:cl:
Balance: Stalagmites on Bluesummers have been replaced with cosmetic rocks.
/:cl:

Replaces stalagmites on bluesummers

---

code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm

Changes shrike's speed from -0.4 -> -0.6
Shrike losing this much speed really hurts it as a caste especially given that they have no sort of gapclosing ability like, say, warrior does. Its two stuns also move marines away from it, meaning that it's heavily dependent on positioning to make full use of the duration of the stun for things like oze sting.
It's also worth mentioning that 0.2 slowdown for a measly _100 health_ and _2 slash damage_ is nowhere near a worthwhile trade; to bring up warrior again, it got 100 hp, a sunder mult, and three slash damage for _0.1 movespeed._
It may be worthless to point out but shrike is also an essential part of xeno, so being forced into this sluggish ass caste to prevent the hive from collapsing is just really fucking annoying.
:cl:
balance: Buffed …

reverts kuro shrike speed nerf and also health buff

---

code/modules/projectiles/guns/specialist.dm

Should have zero impact in HvX.
Reduces the scout rifle accuracy slightly, and tweaked the campaign scout loadout.
Scout is a little TOO good at delimbing due to its extremely high accuracy. This should make it a bit less reliable at doing so.
No real change in HvX since you already get accuracy bonuses against big stinky xenos.
:cl:
balance: Reduced BR-8 accuracy slighty
/:cl:

Reduce Scout accuracy slightly

---

code/controllers/subsystem/explosions.dm

Weak explosions no longer get counted for screen shake calculations.
Also cleaned up the code to be a bit nicer around screen shake and sounds (previously BOTH were disabled by the silent arg)
Less screenshake from weak explosions which can be more spammable (like plasma cannon or that ICC shotgun).
:cl:
balance: Weak explosions no longer contribute to screen shake
/:cl:

Explosion shake tweak

---

code/datums/elements/strappable.dm

Fixes strappable items not turning off their nodrop if they are forcefully unequipped (such as due to a delimb).
Picking up cursed items is funny but bad.
:cl:
fix: fixed strappable items not turning nodrop off, when forcefully unequipped
/:cl:

Strappable fix

---

code/datums/gamemodes/campaign/rewards/equipment.dm

Increased the cost of the scout in campaign from 2 for 6 points to 10 points.
Personal purchase is unaffected.
Its a bit too spammable and effective for its attrition cost
:cl:
balance: Campaign: Increased cost of Scout rifle asset from 6 to 10 attrition for two.
/:cl:

Increase scout cost in campaign

---

code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm

Engineers in campaign now spawn with a full stack of plasteel and 2 full stacks of metal in their suit storage.
Engies deserve some love, and the previous amount of mats would get used in 2 seconds so kind of forced them to use pocket/secondary slots of viable amounts of building.
:cl:
balance: Campaign: Increased engineer plasteel and metal amounts in suit storage
/:cl:

Campaign engie mat buff

---

code/modules/projectiles/gun_helpers.dm

Changes tac reload back to a single do_after instead of two.
Now, the unload is instant, while the reload is back to the original duration (i.e. double).
This change was actually a very large stealth buff to tac reloads, as A: tac reloading empty was twice as fast, and B: The skill bonus applied twice, so tac reloads were actually twice as fast AGAIN.
So this returns tac reloads back to their intended duration - the speedy reloads was especially noticable after the change to make it a single click instead of click drag.
:cl:
balance: Tac reload windup time is now purely for the new mag
fix: Fixed tac reload getting the skill bonus twice.
/:cl:

Tac reload change/nerf

---

code/datums/gamemodes/campaign/loadout_items/SOM/secondaries.dm
code/datums/gamemodes/campaign/loadout_items/_TGMC/secondaries.dm
code/datums/gamemodes/campaign/loadout_items/secondary_types.dm
code/modules/reagents/chemistry/reagents/medical.dm
code/modules/reagents/reagent_containers/autoinjectors.dm

Added Re-Grow injectors to medic's advanced chem secondary kit.
The injector has 6 doses, each dose on inject will regenerate ALL missing limbs on the subject. New limbs are biotic however, so are weaker than standard.
Also fixed a couple of minor loadout bugs.
Fixed duplicate 'extra ammo' secondary for medics, and it not being the default choice as intended.
Fixes #16817 The COPE sentry secondary having TGMC sentry ammo in it.
I still prefer for delimbs to be in HvH, but some weapons make it a bit too easy to achieve. This adds some counterplay and further increases the usefulness of medics.
:cl:
add: Campaign: Added Re-Grow to advanced med secondary kit, allowing for regeneration of missing limbs
fix: Campaign: Fixed a couple of minor secondary kit bugs
/:cl:

Re-Grow - limb regeneration for campaign

---

_maps/map_files/kutjevo/kutjevo.dmm

Moved research digsites on Kutjevo to be less marine sided.
Too many digsites in the no-build zone makes research extremely easy.
:cl:
balance: Moved research digsites on Kutjevo to be less marine sided.
/:cl:

Redoes Kutjevo digsites

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

see title.
Preventing the use of abilities in dense objects is probably fine but the implementation is incredibly flawed as it not only keeps you from switching abilities while in dense objects but also applies to the fog from gamemodes like crash, and the use of xeno abilities in the fog is much less problematic than use in constructed walls as the fog is only in a few static locations you can walk away from.
This is an incredibly hacky solution only covering one caste I made because I was malding but I don't have the knowledge required to work out a better solution and nobody else is going to do it.
the fog is made of like nicotine smoke that prevents me from getting mad but vaping is bad for you so I won't breathe it in
:cl:
balance: ravager can rage and endure in solid objects now …

Ravager can endure and rage in fog/dense objects

---

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
code/modules/xenomorph/acid_pools.dm
code/modules/xenomorph/maw.dm
code/modules/xenomorph/pherotower.dm
code/modules/xenomorph/silo.dm
code/modules/xenomorph/spawner.dm
code/modules/xenomorph/xenotowers.dm

Cleaned up and deshitcoded various xeno structure hitbox and visual bound stuff.
This means building structures will now actually check YOUR location, not the location to the south west of you. This means there will probably be a few more random little corners you can build in.
Couple of structures were made to only occupy 1 tile since thats visually what it looked like, but there should be no gameplay changes.
I want to make xeno structures actually check the ENTIRE bound area for being valid instead of one tile, but thats a larger change (and for example would mean you couldn't silo in alamo cockpit) so I'll leave it for a separate PR.
Less shitcode, more intuitive building.
:cl:
fix: Xeno structures actually build on your location instead of to the south west
/:cl:

Xeno structure bound fixes

---

code/modules/reqs/supply.dm

Fixed tank vendor ammo duplication.
Fixes #16039
It turns out the UI act where this was supposed to happen is actually never called anywhere, honk.
Exploit bad.
:cl:
fix: fixed an ammo duplication exploit with the tank vendor
/:cl:

Tank vendor fix

---

code/datums/components/deployable_item.dm
code/game/objects/machinery/minelayer.dm
code/game/objects/machinery/mortar.dm
code/game/objects/structures/teleporter.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/guns/sentries.dm

Minisentry deploy/undeploy time reduced from 3 seconds to 1 second.
Made the deploy component actually use the undeploy time (previously this did literally nothing as it just checked the deploy time for both deploy and undeploy)
Minisentry is just a straight worse version of the big sentry, this makes them a little bit better for rapid pack/unpack.
:cl:
balance: Minisentry deploy/undeploy time changed from 3 seconds to 1 second
fix: fixed deployables using deploy time for undeploying instead of undeploy time
/:cl:

Mini sentry deploytime buff and bug fix

---

code/modules/vehicles/_hitbox.dm

Fixes desants not being removed when a vehicle is destroyed (so mainly the APC since it doesn't have a wrecked state).
fixes #16297 (probably), if its still an issue.
Bug fix
:cl:
fix: fixed desants not being removed when a vehicle is destroyed
/:cl:

Desant fix on vehicle destruction

---

_maps/map_files/Research_Outpost/Research_Outpost.dmm

This disk is in the same building as the nuke.
Probably should not let marines take a disk on the nuke site
:cl:
balance: The nuke room on Research Outpost may no longer also have a disk.
/:cl:

Removes a disk candidate site from Research Outpost

---

code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
code/datums/jobs/job/icc.dm

ICC leader now spawns with a gun.
All ICC now have a Bicaridine bar and oxycodone injector in their helmets.
Non-medics now have ointment and gauze in their suit storage, medics get a fire extinguisher.
Rifle medic loadout gets a pistol and magazine in bag.
Leaders now get two incendiary grenades, a fire extinguisher, and a combat injector.
Fix loadouts and make ICC stronger and more on par with other factions.
:cl:
fix: ICC leaders will now spawn with their guns and ammo.
balance: ICC now have more meds and fewer empty inventory slots.
/:cl:

Fixes ICC Leader and adds gear to ICC loadouts

---

_maps/map_files/Arachne/TGS_Arachne.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/TGS_Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm

Merges FC and SL prep into one, complete with a drawable map table for group planning
Moves minimap tablet from CIC to the FC/SL preps on each ship to encourage use more
(Note: Pictures outdated; minimap tablet is on the FC vendor in each of these photos)
This also gives room for more spacious medic/engi/SG preps on Pillar of Spring specifically:
Theseus has SL prep split by squad. Because of this Theseus instead has a minimap briefing room outside the FC office:
FCs and SLs need to work and plan together to ensure the marines' victory but the rooms they prepare in are often completely across the ship. This is bad for several reasons:
- FC/SLs can't plan during the first minutes of drop, which is the only time you get before engis/etc already have their gear setup.
- It's harder to plan …

Merges SL and FC prep rooms

---

code/datums/gamemodes/campaign/loadout_items/SOM/secondaries.dm

Fixes #16875
Specifically, the sword actually spawns, and backpack is no longer a prereq (if you do have a backpack it gives you extra shit though, but this means you can have blink drive and dual sword if you want).
:cl:
fix: Campaign: Fixed the esword secondary not spawning, and requiring a backpack
/:cl:

Campaign: Esword secondary fix

---

.github/workflows/ci_suite.yml

https://github.com/tgstation/tgstation/pull/88988/files
OD was bumped to .net 9 now which isnt in the image

Fix OD lint compile

---

_maps/map_files/Arachne/TGS_Arachne.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

See title
Fixes good
Removing map tables was requested because they made the room cramped
:cl:
fix: Fixed stray windows and tiles on Pillar of Spring
del: SL prep rooms now have 1 map table instead of 2 for space
/:cl:

Fixes map errors on Pillar of Spring + map table adjustment

---

_maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
_maps/map_files/Campaign maps/nt_base/nt_base.dmm
_maps/map_files/Campaign maps/som_base/sombase.dmm
_maps/map_files/Campaign maps/tgmc_raid_base/tgmc_raiding_base.dmm

Fixes TGMC raiding base have a full mateba belt.
Swaps a few AR-11's with scopes on some maps with nonscoped versions.
Fixes SOM supply base having some space tiles (which was bizarre, as the turfs they DID have previously... never actually existed as it's own turf type).
:cl:
fix: Campaign: Fixed some map issues
/:cl:

Campaign map fixes

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm

Crusher/shrike Flings were completely ignoring move_resist
Can no longer fling petrified marines as intended originally, and armor lock will also be fling resistant
:cl:
fix: fixed petrified marines being flingable, along with other typically immobile situations being flingable
/:cl:

Flings now respect move_force

---

code/modules/mob/living/carbon/human/human_damage.dm
code/modules/mob/living/living_health_procs.dm

When an xenomorph drags a crit human (or any species that doesn't have NO_BREATHE), they now correctly deal only oxygen damage instead of brute damage and oxygen damage at the same time.
Before this, dragging a crit human would deal 3 brute damage and 3 oxygen damage per tile dragged.
After this, dragging a crit human would deal 3 oxygen damage per tile dragged (as intended).
Species who do not breathe, like combat robots, are unaffected by this as they do not have to deal with oxygen damage.
Bugfix.
:cl:
fix: Humans (or any breathing species) who are critdragged by xenomorphs now correctly take only oxygen damage instead of brute damage and oxygen damage at the same time. 
/:cl:

Fixes xeno dragging crit humans doing brute damage

---

code/modules/screen_alert/command_alert.dm

Decapitalizes full faction announcement titles done by the FC/CMO/Captain/etc using send orders (in chat only - the title is still loud in maptext)
It's kinda jarring and just seems to be some kind of oversight on Lumi's part. Also, more consistency: this doesn't seem to happen with squad leader announcements
:cl:
fix: Full faction announcements (done by the FC, CMO, etc...) will no longer have fully capitalized titles in chat. (on-map titles are still capitalized)
/:cl:

decapitalizes full faction announcement titles for consistency

---

_maps/map_files/generic/Admin_Level.dmm

Valhalla lacking a soda dispenser and that's bad.
Given how Valhalla is a place for testing and its missing one big tool for testing chem. I decided to add a wall soda dispenser to Valhalla's chem room. 
:cl:
add: Adds soda dispenser to Valhalla.
/:cl:

Adds Soda Dispenser to Valhalla.

---

code/modules/clothing/modular_armor/attachments.dm

When forcedropped equip() is not called again so this fixes snowflaked handling of the action for attachments
:cl:
fix: fixed an exploit allowing some attachments to persist when taken off
/:cl:

Forcedropped objects with attachments lose their actions correctly

---

code/modules/reqs/supplypacks.dm

see title
what goddamn federal agent calls it the, "Recoilless standard missile"
:cl:
spellcheck: Recoilless Rifle shell factory refills are now named similarly to their single-shell counterparts.
/:cl:

Renames the RR's factory refills to be in line with the single shell purchase options

---

code/modules/projectiles/guns/rifles.dm

Some mild handling nerfs to the V-35.
Slightly increased wield slowdown and wield time, and worse scatter/acc on the move.
Makes the V-35 less good/reliable at blowing off limbs without simply nerfing the damage and making it useless.
:cl:
balance: Campaign: Small handling nerfs to the V-35
/:cl:

V-35 handling nerfs

---

code/modules/mob/living/carbon/human/human.dm

fix "Set Species"
the admin VV was passing a /datum/species to the proc when the proc only calls for a string.
I've just added a check to convert a datum into a string to ensure it works wether you pass a string or a datum
bugfix
:cl:
admin: fix VV "Set Species"
/:cl:

fix admin VV "Set Species"

---

code/game/objects/machinery/computer/crew.dm

Fixes #5751
Fixes crew monitor console displaying ALL humans.
It now just checks players with a matching faction. i.e. no more detecting hostile erts etc.
Also means we can make SOM versions etc in the future.
Some autodoc as well. Theres other ass code in crew monitor, but I don't want to touch it in this PR.
Exploit bad.
:cl:
fix: Crew monitors no longer track all humans
/:cl:

Crew monitor fix

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
code/game/area/prison.dm

Title. (THIS DOES NOT INCLUDE UNDERGROUND ROOFS)
This changes (I believe) only two main things:
1) Pods can now drop into Prison Station
2) Tad can now land everywhere that isn't underground
The issue here is arbitrarily making the entirely "indoors" map having metal roofs or not, like is normally easily done in a map (if there is a building it has a roof!) Marines will still have to clear out walls for tad/pods, etc. If you think there is an area on Prison Station that really, really should not have tadpole land (besides the already existing underground) just say in the comments and I can change it.
:cl:
balance: Prison Station metal roofs are now glass, allowing marines to pod and land Tadpole.
fix: Fixes some stray wall props on Pillar of Spring.
/:cl:

Makes all Prison Station metal ceilings into glass ceilings (and another PoS fix)

---

code/_globalvars/lists/mobs.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm

You can no longer evolve to Wraith. It's off the T2 evo list.
Kuro doesn't like it. I agree. Abilities are very strong, and it being fragile would probably just make it CBT to play. It is sentenced to Hell until someone reworks it to not be cracked and, at the same time, not be frustrating to play.
:cl:
del: Wraith can no longer be picked. Forcefully devolved Warlocks will devolve to Warriors instead.
/:cl:

Disables Wraith

---

code/datums/gamemodes/_game_mode.dm
code/datums/personal_statistics.dm
code/datums/round_statistics.dm
code/modules/xenomorph/maw.dm

Adds stat tracking to acid maw and jaw uses
stats r cool
:cl: Cheese
add: Acid Maw and Jaw uses are now stattracked
/:cl:

Add stat tracking to acid maw and jaw

---

code/datums/components/chem_booster.dm

Another shake of the stick about vali balance, as I wasn't a fan of the other pr proposals.
Really just for TM to see if this sort of thing is a better solution or not.
1. Reduces the vali heal multiplier from 6 to 4 (this applies to brute and burn heal)
2. Meraderm has a small negative mult for the opposing heal type
3. Xeno chems (and satrapine) have negative vali modifiers
See pics below for the exact numbers.
While vali has various combos and strats you can use with it, all issues it have ultimately stems the incredibly high healing power you can generate out of it, outhealing xeno DPS, often when fighting multiple at once.
For reference, vali mega healing peaks out at something like 2 to 3 times stronger than Russian Red (and this isn't even taking into account neuraline, which is an …

Vali healing changes

---

code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm

quick aside I noticed while working on my gorger strain (coming 2032)
Right now, drones have a single usable ability while riding honse:
which is kinda goofy. 
This pr allows drones to switch their pheros, print a resin glob, and use their primo Empower while on a rideable xeno.
Healing, building, planting weeds, etc. can still only be done while not mounted.
technically they should still be able to Heal while mounted but I'm uncomfortable with the balance ramifications of spamming heal on a mounted crusher. so I won't be doing that
Pheros and the glob are strategic decisions that could conceivably be done from horseback
Enhancement is literally Useless if you're pocketing a rideable rn, since they'll run out of your sight immediately and snap it. This lets you exchange …

Drones can now use (slightly) more abilities while mounted

---

code/__DEFINES/dcs/signals/signals_keybindings.dm
code/datums/keybinding/mob.dm
code/game/atoms/atom_movable.dm
code/modules/client/client_defines.dm
code/modules/keybindings/bindings_atom.dm
code/modules/keybindings/bindings_client.dm
code/modules/mob/living/living_movement.dm
code/modules/mob/living/silicon/ai/freelook/eye.dm
code/modules/remote_fob/computer.dm

Ports the Block Movement keybind which replaces our current face north/south/west/east keybinds and means that grabbing things with ctrl no longer needs to bolt you in place
The grab keybind (ctrl) being on the same unchangable stop movement button (ctrl) was painful and caused many xeno deaths. No more shall we suffer!
:cl:
qol: Block Movement is now on a keybind that you can use to face directions without moving.
/:cl:

Ports tg Block Movement keybind

---

code/datums/storage/storage.dm
code/datums/storage/subtypes/internal.dm

Lumi edit: Fixes webbing fitting things it shouldn't.
~~Lets all small items into regular (3 slot) webbing.~~
bug fix
~~Lets you use regular webbing more generally, instead of just a magazine pouch on your uniform. Not giving it the G8 general purpose belt treatment and make it one slot as it doesn't make sense given the sprite. Maybe if it was a drop pouch.~~
~~Adds comments to Storage.dm, because i feel that it may not be clear enough. As it played a role in webbing being able to hold TE powerpacks.~~
~~Might need to add Sheets, razorwire, sandbags, and snow to the cant hold list, as it seems a bit odd to me that you can store 120 metal in the vest. I don't think that was an intended change, but i can't find anyone talking about it, it just sorta popped in somewhere.~~
:cl:
fix: Regular …

Regular webbing storage fix and adds comments to storage.dm

---

code/__HELPERS/mobs.dm
code/modules/mob/say.dm

Title
:cl:
fix: Fixed dchat runechat only showing for the owner
/:cl:

Fixes dchat runechat only showing for the owner

---

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm

Call of Younger now respects the target's pronouns instead of just using "his" for all cases
Ability descriptions will now use "facehugger" instead of just "hugger" or "young one"
Corrects description for the Use/Throw Facehugger ability (The ability will always throw the facehugger, and you cannot just bring it into your hand)
Also notes the ability to use Use/Throw Facehugger directly on a facehugger to recycle it
Capitalizes hugger turret name and gives it an actual description (Seriously people)
:cl:
spellcheck: Carrier: Call of Younger will now respect the target's pronouns
spellcheck: Carrier: Adds proper ability description to the Build Hugger Turret ability, capitalizes ability name
spellcheck: Carrier: Abilities will now exclusively use the term "facehugger" instead of "hugger" …

Carrier ability pronoun correction + term standardization

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm

Nerfs crusher sunder multiplier and total health.
Following the removal of aim mode, crusher became a real bastard to play against, this should reign him in somewhat
:cl:
balance: Crusher sunder mult nerfed, Crusher total health nerfed
/:cl:

Crusher nerfs

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/modularmaps/big_red/bigredengineeringvar1.dmm
_maps/modularmaps/big_red/bigredengineeringvar2.dmm
_maps/modularmaps/big_red/bigredengineeringvar3.dmm
_maps/modularmaps/big_red/bigredengineeringvar4.dmm
_maps/modularmaps/big_red/bigredetavar1.dmm
_maps/modularmaps/big_red/bigredetavar2.dmm
_maps/modularmaps/big_red/bigredetavar3.dmm
_maps/modularmaps/big_red/bigredetavar4.dmm
_maps/modularmaps/big_red/bigredetavar5.dmm
_maps/modularmaps/big_red/bigredofficevar1.dmm
_maps/modularmaps/big_red/bigredofficevar2.dmm
_maps/modularmaps/big_red/bigredofficevar3.dmm

title, and the canterbury crashed onto office modular had no office apc.
Intel are a great objective for pulling marines away from the standard paths, more will help with this.
:cl:
add: Added 5 new intel computers to Big Red.
fix: Fixed an APC on a modular in Big Red.
/:cl:

Adds 5 more intel computers to big red + fixes an apc

---

code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm

Buffs sentinel across the board
So it turns out that in my original xeno buff pr I had planned to buff sentinel, but actually completely forgot to add the sentinel buffs. The caste has been performing below its T1 counterparts so this should bring it up to par.
Tldr: I forgor to buff it, teehee
:cl:
balance: General buffs to sentinel and retrograde damage and survivability
/:cl:

Buffs to Sentinel/Retrogade Sentinel stats across the board

---

code/modules/mob/living/living_movement.dm

Restores old functionality to binoculars and similar.
Bugfix
:cl:
fix: Block Movement keybind now lets you rotate scopes and binoculars like before.
/:cl:

Block Movement keybind now lets you rotate binoculars and scopes again

---

code/modules/projectiles/guns/shotguns.dm

SH-39 can no longer be one handed.
Kills (or makes harder) gross slow stacking of slugs + vali slowdown.
Combat shotty is rather good when one handed, which means no slowdown, and more recently can be offhand fired with vali sword for gross slow stacking.
There's really no other reason why you'd one hand a combat shotty, considering shields were removed and akimbo is unreliable. Unless you have been delimbed I guess.
:cl:
balance: SH-39 can no longer be one handed, again
/:cl:

Kills one handed combat shotgun

---

code/datums/components/bump_attack.dm

Stops friendly melee marines and ERTs from hitting each other accidentally in passing.
Lessens the blood on my hands while near friendly factions.
Don't think it works for SOM/ICC/CLF as they use different IFF tags from each other.
:cl:
fix: human bump attacks respects human IFF
/:cl:

Human bump attacks respect friendly human factions

---

code/modules/projectiles/ammo_types/rocket_ammo.dm

Tank gibs now check for godmode before gibbing.
Funny gibs while in godmode from armourlock/petrify/hvh spawn protection is funny but probs bad.
:cl:
fix: Tank gibs now check for godmode
/:cl:

Tank gib godemode check

---

code/_globalvars/lists/mobs.dm

Tivi forgot to add this strain to The Big List
Bloodthirster now appears in valhalla spawnlist, among other places. Now please fix the balance tivi I beg y
:cl:
fix: Bloodthirster is now represented on the global list of all xeno types
/:cl:

Adds bloodthirster to global list of all xeno types

---

_maps/modularmaps/big_red/bigredofficevar2.dmm
code/game/area/bigred.dm

Gives the crashed canterbury modular its own area
Previous pr added a duplicate APC, now the areas are split like they shouldve been.
Fix so big red passes checks
:cl:
fix: Crashed canterbury on big red now uses its own area.
/:cl:

Big red modular fix

---

code/modules/projectiles/guns/sentries.dm

Corrects laser sentry gun flags.
No longer has IFF, and properly counts ammo via shots remaining.
:cl:
fix: The laser sentry no longer has IFF when it shouldn't have
/:cl:

Fixes laser sentry IFF

---

code/game/objects/items/cards_ids.dm

Adds Marine's Rank to their ID card, prefixed.
This has been made using VSCode this time, no suffering in DM.
Kuro didn't seem to have a problem with xenos being able to read rank when asked.
I have made an additional commit that'll make xenos not be able to see ID cards if desired to prevent targeting.
Information Good.
Marines/Mentors can tell, at an examine, what rank a Marine is, and infer if they may need help or not. Rather than having to wait for them to say something.
:cl:
add: Marine's Rank is now prefixed to their ID card
/:cl:

Adds Marine Rank to ID Card

---

code/__HELPERS/time.dm

Fixes timestamps showing incorrectly due to timezone no longer being set to incorrect UTC
high prio since these are also used in admin logging
:cl:
fix: Fixes round time timestamps
/:cl:

Fixes timestamps

---

code/datums/jobs/job/marines.dm
code/datums/jobs/job/shipside.dm

If it isnt the consequences of our speedmerhg
TM this
Fixes #16988
ID cards now actually update for rank, rather than everyone being a PVT until they change squad.
Fuckup on my part, changing for ranks worked once and foolish me didn't bother to do some further digging
:cl:
fix: updates ID cards to respect rank rather than everyone being a PVT
/:cl:

Fixes ID cards not updating rank at roundstart.

---

code/__DEFINES/dcs/signals/signals_keybindings.dm
code/datums/keybinding/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

Missing keybind and sprite got lost somewhere
:cl:
fix: Ravager: fixed deathmark not having a keybind
fix: Ravager: fixed deathmark not having a sprite set
/:cl:

Deathmark fixes

---

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm

Some maps use CEILING_UNDERGROUND in caves instead of the other ones
Jaws aren't meant to be built underground
:cl:
fix: removes the ability to place jaws in caves on a few specific maps
/:cl:

Downgrades the Acid Jaws' build check ceiling level (???)

---

code/modules/projectiles/ammo_types/energy_ammo.dm
code/modules/projectiles/guns/energy.dm

Make the default firemode of laser carbine auto burst standard so you don't have that weird switching from spread mode to spread mode the first time you vend the gun.
Rename the lasers bolts by the cripple mode to crippling laser from impact laser.
Switching your gun from spread mode to spread mode is weird, autoburst standard is called standard so it should be default.
Having the crippling lasers be named impact lasers is just plain confusing.
:cl:
fix: you no longer switch from spread mode to spread mode the first time you change mode on lasbine
spellcheck: lasers from cripple mode are now properly named
/:cl:

A few fixes to laser carbine

---

code/__HELPERS/mobs.dm

Also doesn't generate the runetext if they're off zlevel, since dchat is across the entire game and its pointless overhead.
Not tested because I'm too lazy to check with 2 clients.
Seeing a bunch of invisible ghosts talking as admin or observer with ghost vision off is aylmao
:cl:
fix: Ghost runetext is no longer visible if the ghost itself is not
/:cl:

You can no longer see ghost runetext when you can't see the ghost

---

code/__DEFINES/loadout.dm
code/game/objects/machinery/vending/new_marine_vendors.dm

Pretty much the title
I don't think such an important role specific item should be hidden in an obscure location
:cl:
qol: KLTD smart goggles are located in the smartgunner equipment rack again
/:cl:

Puts the KLTD smart goggles back in the smartgunner equipment rack

---

code/datums/jobs/job/marines.dm
code/datums/jobs/job/shipside.dm
code/datums/jobs/job/sons_of_mars_shipside.dm
code/datums/jobs/job/sonsofmars.dm
code/datums/jobs/job/xenomorph.dm

hey did you know that every job was noted as being a starting role except for the TO which had a 100 hour timelock written down for it even though we have like 20 jobs with 10 hour timelocks now
also indicates that SOM groundpounder jobs are also available in crash
also does a typo and- 
you know what fuck you read the file changes it isn't that hard
probably should not mislead new players like this
:cl:
fix: Job descriptions now correctly display the required playtime needed to unlock them
/:cl:

Updates job descriptions

---

code/datums/components/jump.dm
code/datums/components/riding/riding_mob.dm

Mobs buckled to a jumping mob are now compelled to jump at the same time as their carrier.
This looks much better and allows mobs with a rider to pull off much fancier maneuvers.
<s>Calling the component directly like this is total slop but this is how it's done everywhere else so </s>
Obliterated. Lumi helped me find a better solution, jump component now iterates through mobs buckled to the jumper and forces them to jump.
:cl:
qol: mobs buckled to a jumping mob now jump alongside them
/:cl:

Jumping mobs now make any mobs buckled to them jump

---

tgui/packages/tgui/interfaces/HiveStatus.tsx

Makes the hive status wider so that it fits all the T3 castes on the screen when you initially open it instead of it being cut off.
Before:
After:
@ivanmixo wanted this.
:cl:
fix: Hive status GUI's width is now longer to fit all castes rather than cutting them off.
/:cl:

Hive status GUI is now wider

---

code/modules/projectiles/guns/mounted.dm
code/modules/projectiles/guns/rifles.dm

Adds Vertical grip to MG-27 MMG and MG-60 MMG.
GPMG got removed VGRIP cause of Aim Mode gameplay. That's gone now so I think its fine to return VGRIP to this for now. The wield penalty is pretty insane with VGRIP so the tradeoff is very, very steep.
MMG has vertical grip now. Since I'm roleplaying my best Tiviplus impression. I'm not elaborating any more.
:cl:
balance: MMG and GPMG have vgrip now.
/:cl:

Adds Vertical Grip to MG-27 and MG-60.

---

code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
html/changelogs/AutoChangeLog-pr-17012.yml

As the title suggests, this nerfs the Sizzler Strain's firerate. From 0.5 to 0.75
<details>
<summary>Video Reference</summary>
I too, don't understand why my PC turned into Bandicam. This is the old firerate
https://github.com/user-attachments/assets/330a0668-667b-48f1-83d5-20633bdd2e49
This is the new firerate
https://github.com/user-attachments/assets/067bd299-efa3-4489-a9e1-083559efa6d9
</details>
The Sizzler Strain has an absurd firerate for a "shotgun" type of a xeno that spits burn damage out.
:cl:
balance: Sizzler strain
/:cl:

Nerf: Sizzler Caste firerate

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm

Title
That one
This miner can be caded extremely easily, tad can park less than a screen away and it's besides a disk, so it's always easy to defend.
This shouldn't be a plat miner.
:cl:
balance: Replaces plat miner on south ice colony with a phoron one
/:cl:

Replaces plat miner in south of ice colony for a phoron one.

---

code/datums/gamemodes/campaign/loadout_items/SOM/head.dm
code/modules/clothing/modular_armor/attachments/modules.dm
code/modules/clothing/modular_armor/attachments/storage.dm
code/modules/reqs/supplypacks.dm

Updates some armour module descriptions to better reflect how they work and the level of protection they provide
changes the capitalization of their names
Moves the mark indicator a step forwards to ensure that the name is always at the start
changes how SOM armour module helmets are referred to in their purchase UI (??? I don't play sloppaign)
Updates req orders to reflect all of this
uh...
:cl:
spellcheck: Updates armour module stylization
/:cl:

Armour module style touchups

---

code/__DEFINES/traits.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm

Warlock is no longer immobilized when casting with their psyblast ability.
Makes it consistent with how Pyrogen can cancel their fireball ability. It is also annoying when you misclick or get shuffled so you just shoot into a wall and waste your cooldown.
:cl:
balance: Warlock is no longer immobilized when casting with their psyblast ability.
/:cl:

Warlock no longer immobilized during Psyblast

---

code/modules/xenomorph/maw.dm

Fix stattracking for acid jaw
Me? Testing my code? I would never!
:cl: Cheese
fix: Acid Maw stats no longer also include acid jaw stats.
server: something server ops should know
/:cl:

fix jaw stat tracking

---

code/datums/outfits/quick_load_outfits.dm
code/datums/outfits/som_ert.dm

Yep, was missing `SUIT_IN_HOLSTER` in my list of slots to check in my script
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/16987
Outfits having stuff they're supposed to good
:cl:
fix: Some SOM and marine hvh outfits' holster contents are once again filled
/:cl:

Fix outfits missing their holster contents

---

code/controllers/subsystem/persistence.dm

Removes the high power seasonal entirely.
All the pistols in this seasonal (except G-22) are straight huge buffs to marine options, since they are all ERT guns.
:cl:
balance: Highpower pistol seasonal removed from the game
/:cl:

Removed 2nd pistol seasonal from the game

---

code/modules/projectiles/ammo_types/rocket_ammo.dm

Disposable AP down from 100 to 50.
Sunder down from 100 to 25.
Disposable was doing more damage than HE sadar, which is wew as fuck when they're easily spammable.
Also 100 sunder is in general, fucking horrible.
:cl:
balance: Disposable AP and sunder reduced from 100 and 100, to 50 and 25
/:cl:

disposable nerf

---

code/game/objects/items/scanners/health_analyzer.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/human.dm

Added "Toggle Health Scan" verb to spectators. Upon enabling will display health scanner UI window to the user.
Useful functionality for spectators and admins.
:cl: The_Man
add: Added new verb "Toggle Health Scan" for spectators.
qol: If "Toggle Health Scan" is enabled, spectators will health scan on click.
/:cl:

Adds "Toggle Health Scan" verb to spectators

---

code/datums/world_topic.dm

Adds a ping topic. This will help with haproxy health checks since it's cheaper than polling status
(PS I haven't compiled or tested this but it should be fine probably, if you test it for me I will love you forever)

Add ping topic

---

SQL/database_changelog.md
SQL/tgmc-schema.sql
code/__DEFINES/_subsystems.dm
code/datums/jobs/job/special_forces.dm
code/datums/jobs/job/survivor.dm

See https://github.com/tgstation/tgstation/pull/89348 (admin ranks are 2 bytes wide when they should be 3 wide like the max in byond)
Staminaloss can be negative which meant many deaths werent saving
Fixed certain job names exceeding the character limit of job roles (lmao)
```sql
ALTER TABLE `admin_ranks`
MODIFY COLUMN `flags` mediumint(5) unsigned NOT NULL,
MODIFY COLUMN `exclude_flags` mediumint(5) unsigned NOT NULL,
MODIFY COLUMN `can_edit_flags` mediumint(5) unsigned NOT NULL;
ALTER TABLE `death`
MODIFY COLUMN `staminaloss` smallint(5) signed NOT NULL;
```
:cl:
server: Fixed certain things not saving in the DB
/:cl:

Fix several DB issues

---

code/datums/jobs/job/fallen.dm
code/datums/outfits/shipside.dm

Adds the assault crewman to Valhalla so you can actually use the APCs and tanks.
Since #16941, there wasn't a way to use the tanks in Valhalla since MP was fulfilling this role.
Now you can just be the AC.
:cl:
add: Added assault crewman to Valhalla, allowing you to test tanks and APCs again.
/:cl:

Adds assault crewman to Valhalla jobs

---

code/game/atoms/atom_movable.dm
code/game/turfs/liquid_turfs.dm
code/modules/mob/living/living_defense.dm
code/modules/projectiles/guns/_shared_ammo_objects.dm

Maybe TM this first. I checked through the stop_throw signal related procs and it should all be fine, but its possible I missed some weird interaction.
Throwing items across lava will no longer burn them.
Thrown things will no longer visually submerge mid throw
Jumping (or being thrown into) fire or liquid turfs (water/lava) will now instantly proc the relevant effects.
Generally a small refactor/cleanup for liquid turf procs, to make the code a bit cleaner and reusable.
Bug fixes.
:cl:
fix: fixed items being burnt by lava while mid throw
fix: fixed things visually submerging mid throw
fix: fixed mobs not being immediately ignited when landing in fire/lava
/:cl:

Fire and liquid turf jump/throw interaction fixes

---

code/modules/projectiles/projectile.dm

Tittle
Allows too much meme potential with stacking weapons, and although said weapons are fine otherwise, if shoulder fire remains in the game they'd have to be nerfed because of it
:cl:
balance: Shoulder fire has been removed from the game
/:cl:

Removes shoulder fire from the game

---

_maps/map_files/gelida_iv/gelida_iv.dmm

Alternative to just killing them all
Mistiming the jump when you are on rush can get you killed, and even if it didn't, it's extremely annoying
They shouldn't block movement at all, they are decorations.
:cl:
qol: Makes the platforms on gelida non dense
/:cl:

Makes the platforms on gelida non dense

---

code/datums/beam.dm

Fixes beams not visually hitting their targets in many cases.
Currently beams draw angle between the source and the target directly, which takes into account pixel_x and pixel_y. This makes beams look wonky against xenos since the beam shoots out to the left of them, due to them all having pixel shifts as they have large sprites.
I kept the source tracking since currently beams are sourced from things that DO want that pixel tracking (i.e. slow moving projectiles).
:cl:
fix: fixed a visual issue with beams
/:cl:

Beam visual fix

---

code/datums/elements/riding.dm
code/game/objects/machinery/OpTable.dm

Title.
Yes.
:cl:
add: Fireman carried people can be laid on top of surgery tables directly instead of having to drop to grab them again and click on the table.
/:cl:

Allows fireman carried people to be laid on surgery tables

---

code/game/objects/structures/orbital_cannon.dm

The OB landing sound now actually plays to all mobs in the specified radius.
Generally just improves this proc to not be shitty.
Currently, it uses hearers() which is blocked by all opaque atoms (like walls).
:cl:
fix: fixed mobs not hearing the OB sound some times
/:cl:

OB sound fix

---

code/modules/projectiles/ammo_types/energy_ammo.dm
code/modules/projectiles/guns/energy.dm

Tittle
~~Laser guns were balanced with no aim mode in mind, so they had better stats overall + hitscan, however following the deletium of aim mode, they, despite not having aim mode, got shoulder fire as well, making them overtuned compared to ballistics.
This should put them in line as having better handling than ballistics but a bit higher falloff to make up for hitscan~~ 
Shoulder fire is gone so falloff changes are no longer needed
Rifle and MG lose rail scope, I don't think they should have this since hitscan is a thing
:cl:
balance: Laser Rifle and MG can no longer equip rail scope
/:cl:

Laser Rifle and MG lose rail scope

---

code/modules/shuttle/marine_dropship.dm

buff window/cockpit wall health to 600 from 500
matches all of the other tads which use generic reinforced windows
would be crazy if using the explicitly designed tadpole pieces was a requirement for each tad variant but nah slop it up
:cl:
balance: increases health of standard tad variant windows/cockpit wall to 600(was 500) to match other tad variants
/:cl:

Buff standard tad cockpit/window health 

---

code/modules/projectiles/guns/sentries.dm

Fixes #17088
Laser sentry can no longer offscreen xenos with its hitscan zero scatter memery
I assume(?) that it wasn't intended for this to have offscreen range.
:cl:
fix: Laser sentry no longer has offscreen range
/:cl:

Laser sentry range fix

---

code/game/objects/items/radio/detpack.dm

Fixes #17085
Oversight when I did some minor refactor stuff.
:cl:
fix: Signalling an exploding detpack now simply disarms again instead of completely deactivating
/:cl:

Detpack signal fix

---

code/modules/clothing/gloves/marine_gloves.dm

Adds electrical insulation to Officer Gloves.
Field Commanders are often responsible for repairing APC's which exposes them to electric shocks.
Field Commanders have engineering skill so should have gloves that allow them to use these skills.
I am malting after I as FC tried to repair the APC on the Canter during crash but got shocked (hardstunned) when mending the APC wires so we got nuked.
:cl:
balance: Officer/FC gloves are now insulated.
/:cl:

Adds electrical insulation to Officer Gloves.

---

code/__DEFINES/loadout.dm

see title
the ability to buy a radiopack for 15 SL vendor points is retained in case you want four for some reason
offers SLs a more approachable alternative to lugging around a supply beacon all game. 15 points is a pretty scary buyin cost for an item that is arguably only about as useful as a standard supply beacon with a bit of QOL functionality, nevermind the fact that this also forces you to wear a backpack...
:cl:
balance: Marine squad leaders may now take the radiopack as a backpack option
/:cl:

Allows squad leaders to take a radiopack as a backpack option

---

code/controllers/configuration/entries/general.dm
code/datums/world_topic.dm
code/modules/admin/verbs/chat_commands.dm

mirror of https://github.com/tgstation/tgstation/pull/89421 and https://github.com/tgstation/tgstation/pull/89447
used by the server-info-fetcher, https://github.com/tgstation-operations/server-info-fetcher/pull/2
:cl:
config: Add PUBLIC_ADDRESS as a config option, serves to show the public IP for players to connect to.
/:cl:

Add public address config option

---

code/__DEFINES/is_helpers.dm
code/__DEFINES/traits.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm

Also fixes mechs being unable to spawn themselves more ammo if they had just spawned their mech
Everyone except spatial agents can only spawn mechs once, spatial agents also ignore the cd
also fix the cd applying to things that are not spawning a new mech
kurocracy decree
:cl:
balance: Everyone except spatial agents can only spawn mechs once
fix: having just spawned a mech now does not prevent you from spawning ammo
/:cl:

Everyone except spatial agents can only spawn mechs once

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm

Fixes a few instances where stagger was still being treated as stacks instead of duration.
Hunter silence stagger is 1 second instead of 0.1 seconds.
Sticky spit is 1 second instead of 0.2 seconds.
Warrior punch stagger is defined in the define instead of the stagger proc for clarity (no change)
:cl:
fix: fixed hunter silence and sticky spit applying far less stagger than intended
/:cl:

Stagger fixes

---

code/game/objects/machinery/overwatch/_overwatch.dm
code/modules/screen_alert/command_alert.dm

What it says on the tin. Would do more but the screen popup cannot handle more than this without a smaller font
120 is woefully not enough for some more complex commands, this should make it a good deal easier
:cl:
spellcheck: Increases command message length to 200 characters from 120 and 100
/:cl:

Increases command message length to 200 characters from 120 and 100

---

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm

Mechs once again (visually) explode on destruction.
Also added some minor screenshake and sound effect like I did for tank.
Tivi stinky
:cl:
fix: fixed mech destruction effects
/:cl:

Mech explosion fix

---

code/__DEFINES/emote.dm
code/datums/emotes.dm
code/game/objects/items/weapons/blades.dm
code/modules/mob/living/carbon/human/emote.dm
code/modules/projectiles/guns/revolvers.dm

Adds a new emote *trick, which you can bind to do a flip trick (like the revolver or karambit) on any item.
Tricking weapons is a mostly harmless cosmetic emote that's locked behind revolvers and karambits due to the influence of one cowboy-obsessed Russian gunslinger. And CS skins.
No more! Now you may trick items as you please, potentially providing endless entertainment to your comrades by juggling ammo boxes on your way groundside.
:cl:
add: Added *trick emote that lets you do tricks on weapons and items alike.
/:cl:

Adds *trick emote, allowing you to do_trick() (revolver trick) on items.

---

code/datums/keybinding/xeno.dm

wawaw
more clarity
lumi told me to
:cl: Cheese
qol: Strain keybinds now use the strain name, rather than the parent name, in the keybinding menu.
/:cl:

Change keybind names to the actual strains, rather than the parent caste

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/client/preferences_gear.dm

does what it says on the tin
tested card decks spawning from roundstart customization and marine vending with no issues
https://github.com/user-attachments/assets/fe4b0487-b520-4083-977f-0c7b98e1a96a
KOTAHI/Not Uno was added to vendor/customization two years back but I cant find any reason/explanation as to why conventional card decks weren't.
:cl:
add: Card decks are now available for Marines in Character Customization and Marine Armaments Vendors
/:cl:

Adds standard deck of cards to marine vendor/customization

---

code/__DEFINES/dcs/signals/signals.dm
code/modules/keybindings/bindings_atom.dm
code/modules/vehicles/mecha/_mecha.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
code/modules/vehicles/mecha/mecha_mob_interaction.dm
code/modules/vehicles/mecha/mecha_movement.dm

see
https://github.com/tgstation/tgstation/pull/79749
https://github.com/tgstation/tgstation/pull/87900
https://github.com/tgstation/tgstation/pull/77345
kurocracy decree
:cl:
balance: mechs no longer have tank controls
fix: block movement keybind now lets you turn while you strafe correctly in a mech
fix: fixed mech turn sounds playing when they shouldnt
/:cl:

Mech movement fixes and changes

---

code/modules/vehicles/armored/__armored.dm
code/modules/vehicles/armored/_multitile.dm
code/modules/vehicles/armored/armored_actions.dm
code/modules/vehicles/armored/interiors/chairs.dm
code/modules/vehicles/armored/interiors/periscope.dm
code/modules/vehicles/armored/som_tank.dm

Fixes exploit where you can use periscope while driving
Since driving is way more interesting with the improved vision and your loader is often already too busy to do callouts, gave it periscope vision
Increased periscope vision by 1 tile to compensate i guess
Also improved the code for periscope while i was there
:cl:
balance: the tank driver now gets the old periscopes tier of zoom and nightvision
balance: the tank periscope has 1 extra range now
fix: fixed periscope being usable while driving the tank
/:cl:

Tank driver periscope fix

---

code/modules/mob/living/carbon/xenomorph/castes/behemoth/behemoth.dm

Title. Literally.
This caste is kinda always going to be trash with the heavy footstep sounds. I think the kit is still way too overloaded but this is a good step at getting it in a better state.
:cl:
balance: Behemoth no longer has heavy footstep sounds.
sounddel: Behemoth no longer has heavy footstep sounds.
/:cl:

Behemoth no longer has heavy footstep sounds.

---

code/modules/xenomorph/maw.dm

See title
Uerhh
:cl:
qol: Acid Maws and Acid Jaws now notify ghosts when fired, and their point of impact may be jumped to.
/:cl:

XOB and xortar fire now alerts ghosts like marine OBs do

---

code/game/objects/items/radio/detpack.dm
code/modules/assembly/signaler.dm

For detpacks:
Unique action now turns the detpack on/off.
Added guidance to linking signaler/detpack codes to its description.
Some detpack messages converted to balloon alerts.
For signalers:
Unique action now sends a signal.
Detpacks should be able to be operated without a menu. It's way more intuitive.
:cl:
add: Unique action for signalers now sends the signal
add: Unique action for detpacks now turns them on/off
qol: Balloon alerts added to some detpack messages
/:cl:

Various Detpack QoL

---

code/game/area/area.dm

Random bug I found while checking something else.
areas_in_z will no longer have dup entries due to modulars.
:cl:
code: Fixed modular mapping creating dup entries in areas_in_z 
/:cl:

Area by z dup fix

---

code/game/objects/structures/rocks.dm

The 4 tile grassy rock pile thing can now be jumped on/walked around on.
There's definitely other stuff that needs this but uh, someone's gotta remind me.
Walk on the pebble.
Don't get stuck on the pebble.
Be dry on the pebble.
:cl:
qol: Large grassy rock piles can be jumped onto and walked upon
/:cl:

Critical rock change

---

code/modules/vehicles/armored/__armored.dm

1 second delay if you do a full 180, 0.5 seconds if you turn 90 degrees.
Very short delay, maybe should be longer but we'll see.
Makes positioning matter a bit more, and adds some more counterplay where xenos can flank and punish an out of position tank slightly better.
Also probably less accidental FF gibs, although I would argue thats a downside.
:cl:
balance: Tank turret rotation adds a delay to firing
/:cl:

Adds a delay to tank firing after turning its turret

---

code/game/objects/machinery/cloning/cloning.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
code/modules/mob/living/living.dm
code/modules/mob/mob_helpers.dm

`notify_ghosts()` presently flashes the window... a lot...
This is very annoying if you're someone like me that alt-tabs when they're dead. I'd like to have window flash notifications enabled, but not for unimportant stuff like some schmuck getting revived! Now your window will only flash if it's something related to you being able to re-enter the round (cloning, burrowed larva, and offered mobs.
Window flashing is a helpful feature but it's presently overused.
:cl:
refactor: Window flashing (i.e. taskbar notifications) while a ghost will now only trigger for stuff related to round re-entry and adminhelps, instead of it happening for everything.
/:cl:

notify_ghosts now only flashes the window for stuff related to round re-entry

---

code/modules/projectiles/ammo_types/smg_ammo.dm
code/modules/projectiles/guns/smgs.dm
code/modules/projectiles/magazines/misc.dm
code/modules/projectiles/magazines/smgs.dm

Buffs the machine pistol, standard smg and heavy smg
These guns have fallen off pretty hard post xeno buffs. Although, in general, buffing things in response to other things is powercrepe and bad, I do think these three need it.
Overall, they have better ammo economy thanks to increased mag sizes.
Ammo packets have been adjusted according to the mag increases
:cl:
balance: The marine standard smg, heavy smg and machine pistol's mag sizes have been increased
balance: The ammo packets for the smgs have had their total bullet count increased
/:cl:

Buffs standard SMGs overall

---

code/modules/projectiles/guns/sentries.dm

title
Laser sentry with 8 tile range is capable of off-screen shooting if approached from the north/south
For other turrets this is perfectly fine, as you can dodge the bullets and they're subjected to accuracy rng, but the laser turret is not, making it just about impossible to push from those directions
The laser turret is also just about a direct upgrade over the standard turret, so this should maybe make it slightly less of an obvious pick over it, though really a laser turret is just ass design
:cl:
balance: nerf laser turret range by 1 tile (8 -> 7)
/:cl:

Nerfs laser sentry range by 1 tile

---

code/game/objects/structures.dm
code/game/objects/structures/barricade.dm
code/game/objects/structures/platforms.dm

Default climb delay for structures changed to 1 second from 5(!!) seconds.
Having to take 5 seconds to climb onto a table is insane.
Robro buff.
:cl:
balance: Default climb delay for structures (such as tables) changed to 1 second from 5 seconds
/:cl:

Default climb delay change

---

code/datums/storage/subtypes/belt.dm

title
For a medical rig that can hold defibs, cryobag, rollers, and hypospray, it's weird that for 4 years it cannot hold tweezers. Let medical rig continue its niche to hold different medical items compare to the lifesaver which hold more pills and stuff.
also ESR-12
:cl:
balance: medical rig can now hold tweezers and ESR-12
/:cl:

let medical rig hold tweezers and ESR-12

---

_maps/map_files/desertdam/desertdam.dmm
_maps/map_files/riptide/riptide.dmm
_maps/modularmaps/corsatdome/corsatdomeicecolony.dmm

Title.
Kuro wants it, walance must be restored to TGMC.
:cl:
balance: Removed Russian Red from a few groundside maps.
/:cl:

Removes Russian Red from ground maps

---

code/game/objects/items/radio/detpack.dm

Old Demolition mode is the new Breach mode (3, 4, 4  explosion)
Demolition is a wider explosion that has no deva, meaning it can't destroy walls (0, 7, 9)
Detpacks set to 'breach mode' now explode on the **opposite side of the wall to where you placed them**. (see below)
Detpacks are in a really weird spot right now. Demolition is purely better than breach, in every way possible. They're intended to be used for traps, but because both explosions are so focused, they can't be used for it. I'm guessing the intention was that breach deals less friendly damage, but with how expensive detpacks are (and also the changes I'm making below) it's just.. kinda useless.
Breach changes:
Because of how explosion code works, _placing a detpack on a wall is less effective than placing it on the floor_. …

Reworks breach/demolition modes for detpack

---

code/modules/mob/living/carbon/carbon.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale.dm

also fixed the trait to give you full vision for 10 tiles instead to make sure widescreen fits?
Kurocracy decree for the new mech role
:cl:
balance: Mech has night vision
/:cl:

Mech has night vision

---

code/__DEFINES/mecha.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm

Per title, this behaviour is a flag
Basically when you click behind you you spin to face it before firing
Kurocracy decree
:cl:
balance: Non-HvH mechs now spin to fire
/:cl:

Non-HvH mechs now spin to fire

---

code/modules/reagents/chemistry/reagents/drinks/drink_reagents.dm
code/modules/reagents/chemistry/reagents/food.dm

What is says on the tin.
Gamer reagents that boost healing while avoiding chem stacking penalties and having no OD limits exist purely to enable powergaming.
:cl:
balance: Removed healing from non medical reagents
/:cl:

Kills cringe reagent healing

---

code/datums/storage/storage.dm
code/datums/storage/subtypes/internal.dm
code/game/objects/items/storage/holsters.dm

All items spawned into storage are now actually stored in the storage datum correctly.
Also added some code to ensure if items are somehow forcefully moved out of a storage datum, they can through the proper exit procs.
Improper storage created a variety of issues.
Also removed a whole bunch of funny invoke_async's since they actually get handled properly now.
Needed for AI changes.
:cl:
fix: fixed some issues with items not being stored or withdrawn from storage datums correctly
/:cl:

Storage datum fixes

---

code/modules/reagents/chemistry/machinery/chem_master.dm

For some reason ghosts had a fucking fumble timer when they clicked on a chemmaster. This PR removes this
:cl:
fix: Ghosts no longer fumble when opening the chemmaster's UI
/:cl:

Adjusts chemmaster skill requirement

---

code/__DEFINES/xeno.dm

//List of weeds with probability of spawning
GLOBAL_LIST_INIT(weed_prob_list, list(
/obj/alien/weeds/node = 80,
/obj/alien/weeds/node/sticky = 5,
/obj/alien/weeds/node/resting = 10,
))
=>
GLOBAL_LIST_INIT(weed_prob_list, list(
/obj/alien/weeds/node = 5,
/obj/alien/weeds/node/sticky = 85,
/obj/alien/weeds/node/resting = 10,
))
Reduction of mindless xenomorph preparation.
In order to ensure sticky weeds dominate xenos are forced to replace every normal weed node in an area by individually standing on top of each one and planting a sticky weed sac. I believe this is currently the worst part of xeno side preparations.
This will have balance impacts, however I strongly believe they will be minimal relative to the improvements to the enjoyment of xeno preparations. If this is too overpowered, …

Starting weeds are now majority sticky.

---

code/__HELPERS/math.dm
code/__HELPERS/unsorted.dm
code/datums/fire_support/gun_run.dm
code/game/objects/structures/dropship_ammo.dm
code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/projectiles/guns/flamer.dm
code/modules/projectiles/sentries.dm
code/modules/vehicles/armored/som_armored_weapons.dm
code/modules/xenomorph/xeno_turret.dm

Adds get_traversal_line and implements it in a few relevant situations.
Also removed the duplicate getline and replaced with get_line.
Bresenham line uses diagonal steps, which is problematic with how it's used in many situations, as any sort of movement/sight ultimately uses cardinal directions (even when going diagonally).
The new proc fills in those diagonal gaps so this can be used more accurately in many cases.
:cl:
code: Adds get_traversal_line, like get_line but filled in cardinal steps when going diagonal
/:cl:

Traverse line proc

---

code/modules/vehicles/armored/apc.dm

Tittle, move delay from 0.5 seconds to 0.35 seconds
Also removes overdrive and zoom from the list of modules it can equip (it doesnt have a sprite it wasnt meant to use them tivi)
:cl:
balance: Buffs APC move speed
removal: APC can no longer use tank modules (Overdrive, zoom)
/:cl:

APC changes

---

code/datums/outfits/quick_load_robots.dm
code/modules/paperwork/beginner_tutorials.dm

Combat robots that make the grave mistake of using the beginner loadouts will find themselves without the medevac beacon and text tutorial, the horror. This PR adds the medevac beacon to more accurately reflect the human corpsman beginner loadout.
poor combat robot didn't know where his beacon was and it made me sad.
:cl:
fix: Combat robot corpsman beginner loadouts now spawn with medevac beacons like their human counterparts.
/:cl:

Combat robot corpsman beginner loadouts now spawn with medevac beacons

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

scorpion autofire does not currently stop when right click is lifted due to some shennanigans with ai_controller not being removed when the mob is possessed. checking for a client fixes this.
bug squash
:cl:
fix: scorpion auto-spit doesn't get stuck shooting anymore
/:cl:

fixes scorpion autofire getting stuck shooting

---

code/__DEFINES/combat.dm
code/modules/mob/living/carbon/xenomorph/attack_alien.dm
code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/warlock.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
code/modules/mob/living/carbon/xenomorph/evolution.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
code/modules/mob/living/simple_animal/simple_animal.dm

Combed through some vars and decided to get rid of unnecessary stuff, make actual use of the `attack_sound` var, and implement an `attack_effect` var as setup for future xeno castes (such as Conqueror).
Squeaky clean code (just ignore the absolute mess that is mob code).
:cl: Lewdcifer
code: Minor clean-up of xeno vars. Gets rid of unnecessary overrides, uses the attack_sound var, and implements an attack_effect var as setup for future content.
/:cl:

Minor clean-up of xeno vars

---

code/modules/reagents/reagent_containers/food/snacks.dm

Fixes the eating messages using the wrong (10 year old) values.
Marines will be unable to eat if the next bite would make them fat.
Better to use our nice pretty nutrition defines instead of incorrect 10 year old numbers.
New players will no longer be fat and slow 24/7.
:cl:
add: Marines have been better trained about nutrition and will stop eating before they get fat.
fix: Eating messages use the correct nutrition values.
/:cl:

Re-educates marines on safe dietary practices.

---

code/modules/admin/admin_verbs.dm

Didnt test this
:cl:
fix: Fixed get mob not working on cryod mobs
/:cl:

Fix get mob not working on cryod mobs

---

code/modules/shuttle/marine_dropship.dm

Also add a sanity check so no runtimes when you try to cap on extended
Hijacking when on the ship may be funny but this is def unintended.
:cl:
fix: You can no longer hijack alamo shipside
/:cl:

Prevents hijacking the alamo when its already shipside

---

code/modules/clothing/glasses/glasses.dm
code/modules/clothing/glasses/night.dm

Glasses/Goggles can no longer be toggled. Huds and night vision should be unaffected
Fixes #17050
No more mysterious hud visor appearing when you activate your ballistic goggles
:cl:
fix: Glasses/Goggles can no longer be toggled in hand creating an empty hud visor sprite
/:cl:

Fixes glasses/goggles being able to be toggled

---

code/modules/events/hive_threat.dm

Title.
Spatial agents getting picked as a hive target is very funny but should probably not happen.
:cl:
fix: Neutral faction mobs can no longer be hive targets
/:cl:

Neutral faction mobs can no longer be hive targets

---

code/game/objects/machinery/buttons.dm

Adds recon, assault, and vanguard mechs to the valhalla spawner button.
Useful for testing mech interactions as xeno
:cl:
add: Valhalla vehicle spawner buttons now include the three types of mechs.
/:cl:

Adds mechs to valhalla vehicle spawner button

---

code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Huggers will now instantly die if they land on a vehicle.
there's currently a 'trick' carriers can do where if they throw a hugger onto a vehicle, marines can't shoot it because it isn't considered a desant. this feels a little slimy and maybe a little bit of an exploit. items can't be desants right now, so this is the next best thing.
(if this is considered too harsh we could throw the huggers off the vehicle instead of killing them)
:cl:
balance: Huggers now die if thrown onto a vehicle.
/:cl:

Facehuggers can no longer land on vehicles

---

code/modules/error_handler/error_viewer.dm

Basically just lists how many different *types* of runtime we get (so it counts the number of entries in the organized view)
This is useful info since generally the raw number of runtimes or runtimes skipped isn't overly useful info in a lot of cases. 
:cl:
add: Added a counter for sources of runtimes in runtime viewer
/:cl:

Adds a counter for sources of runtimes in runtime viewer

---

code/game/objects/items.dm
code/modules/vehicles/armored/armored_weapons.dm

Fixes runtime that happens when taking items out of ammo rack
Fixes runtime when unloading the breech by hand, the ammo counter actually gets updated to reflect that now
Runtime bad
:cl:
fix: Fixed runtime when taking ammo out of tank ammo racks
fix: Ammo counter for tank should update correctly now when manually unloading breech
/:cl:

Fixes tank runtimes

---

code/modules/admin/admin_verbs.dm

They can't see dchat when alive and if they're dead they can just use the normal say verb like normal people.
I don't see the point of them being able to use dsay if they can't even see what they wrote if they're not dead.
:cl:
admin: Mentors can no longer use the dsay verb
/:cl:

Mentors can no longer use the dsay verb

---

code/datums/keybinding/admin.dm

Pressing F7 would trigger a warning marked as a runtime when a non admin pressed the bind.
Mentors are handled separately in the admin verb proc itself
Runtime log less clogged
:cl:
admin: Blocks admin keybinding usage by people who aren't admins/mentors
/:cl:

Blocks admin keybinding usage by people without holders

---

code/datums/storage/storage.dm

The call stack here was a mess to navigate for such a specific fix.
`remove_from_storage` calls `forceMove` which sends `COMSIG_MOVABLE_MOVED` down the line which every item in storage has registered to call `remove_from_storage` so that gets called again. And eventually when they're all done and start returning back the line eventually it'll run into the MRE's override which deletes the MRE and by extension the storage datum, but since the `forceMove`'s call to `remove_from_storage` is still not finished it'll try to still access `parent`'s vars, which causes a runtime.
This could use a TM if you feel like it, I don't know if reordering this here will cause some weird behaviour.
Runtime bad.
:cl:
fix: MREs no longer runtime when the last piece of food is removed from them
/:cl:

Adresses `remove_from_storage` calling itself in most cases

---

code/modules/admin/panels/player_panel.dm
code/modules/admin/topic.dm

Barnet said it's alright, and notes/kick/ban are locked behind R_BAN. 
Just makes life a little easier for maintainers, and the actual admin stuff is locked away behind a perm maints don't get anyways.
:cl:
admin: Maintainers now have access to player panel (minus notes, banning, kicking, etc)
/:cl:

Allows maintainers to view player panel

---

code/modules/vehicles/armored/interiors/chairs.dm

Armoured vehicles now have their faction set by the driver (not unset when you get up), same as mech.
Don't have AI and other stuff target friendly vehicles.
:cl:
fix: Armoured vehicles now have their faction set by the driver
/:cl:

Tank faction setting

---

code/game/objects/machinery/squad_supply/supply_beacon.dm

This PR gives the supply beacons the ordering interface, accessible via right click only when its anchored. This gives them the same functionality that radiopacks do, but doesn't exactly render them as radiopack replacements since you still need to actually go to the beacon to order things from it.
The RO's attention span may possibly be one of the most important resources for marines, second only to their precious requisition points. By minimizing the conversational back-and-forths on req radio ("what sentry did you want again? who needed the zx? we don't have the points..."), this PR aims to reduce both marine and RO frustration, as well as free up the RO to perform other tasks like reqtorio or vendor supply drops.
By allowing marines to just put in an order for what they need …

Gives supply beacons the supply ordering interface

---

code/datums/storage/storage.dm

This should be a safer, less runtime prone way of doing this. First we make sure it's actually a mob that exists, then if it has a client and then if the mobs active storage is src. Had some runtime happening where it'd complain about `null.s_active`
runtime bad
:cl:
fix: fixed a storage runtime
/:cl:

Fixes a storage runtime

---

code/modules/mob/dead/observer/observer.dm

This is causing runtimes because SSticker doesn't have a mode, when a lot of hive code relies on the mode.
Sidenote I have no idea under what changelog tag to put this under so uhh
runtime bad
:cl:
code: You can no longer join valhalla before the round has started
/:cl:

Prevent people joining valhalla before round has started

---

code/game/objects/machinery/overwatch/military.dm

Fixes the main overwatch console getting stuck assigned to one squad after using squad monitor.
Getting stuck to one squad means you can only use lases from that squad.
:cl:
fix: fixed the main overwatch console getting stuck to one squad
/:cl:

Overwatch fix

---

code/__HELPERS/math.dm

get_line and get_tranversal_line updated to be more accurate.
This should be the same/similar to some previous behavior, notably stuff like flamer.
It turns out the TG line proc I kept is kinda... shitty, as seen in this picture. It was prioritising the dominant axis far too much, so I've changed it to error accumulation.
Incidentally this should make AI FF detection much better, among other misc improvements.
:cl:
fix: get_line and get_tranversal_line are much more accurate
/:cl:

Line improvements

---

code/game/objects/effects/aliens.dm
code/game/objects/effects/overlays.dm
code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
code/modules/shuttle/ripple.dm

Adds more hazard detection for NPCs.
They will now avoid:
1. Landing shuttles (RIP Adelina)
2. Incoming CAS
3. The various types of acid spray
4. Warlock psycrush
5. Prae abduct
This in addition to already avoding nades and fire.
Let me know if there are any other obvious things they should try to avoid.
Smarter AI.
:cl:
add: Added more things for NPC's to avoid as hazards
/:cl:

More AI hazard detection

---

code/__DEFINES/__game.dm
code/__DEFINES/directional.dm
code/__DEFINES/machines.dm
code/__DEFINES/misc.dm
code/game/objects/machinery/fire_alarm.dm
tgmc.dme

Make sure grayson sees this before merge
We should be using this instead of switch() on init, since it makes these display properly in map editors, lets you pixel offset them, and means less copy paste
I was going to add the fire alarm one as an example but its kinda cursed so its a todo(tm) instead
Needs a lot of mapping changes so I leave it up to the mappers to fix all the uses where this macro should be used (apcs,platforms, etc etc)
:cl:
code: added MAPPING_DIRECTIONAL_HELPERS for mappers. please use this instead of dir and pixel varedits and initialize() switches
/:cl:

Adds new MAPPING_DIRECTIONAL_HELPERS from tg

---

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm

:cl:
qol: Mech repair retargets itself to the chest now when a limb is repaired
/:cl:

Mech repair retargets itself to the chest now when a limb is repaired

---

code/modules/client/preferences_toggles.dm

code\modules\client\preferences_toggles.dm:118:error: "Join as Chestburster": invalid expression (1357)

makes 516 compile

---

code/__DEFINES/ai.dm
code/game/objects/structures/barricade.dm
code/modules/ai/ai_behaviors/ai_behavior.dm
code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
code/modules/projectiles/sentries.dm

Improved the code, fixing various issues.
Notably for the players, NPC's will now:
1. Actually open cades when possible instead of nerd raging them to death
2.  Will not destroy obstacles that belong to their faction
3. Cades and sentries have their faction var set by their builder/deployer
4. Will more accurately figure out what obstacles to deal with
5. Will attack resin walls in their way
Now that obstacle handling is split out to a obj var, we can add more specific behavior as needed, without all the funny snowflake.
PR up for review, but there's probably a few more things I will add before merge.
Smarter AI
:cl:
add: NPC obstacle handling improved
qol: Barricades and sentries have their faction set by their deployer. NPC's will avoid destroying friendly obstacles
/:cl:

Better AI obstacle handling

---

code/modules/ai/ai_behaviors/human_mobs/human_mob.dm

If you grab a friendly human NPC, they will stop moving.
Lets you wrangle NPC's better, hold them still for equipping/healing/feeding etc.
:cl:
qol: Grabbed friendly human NPC's will not move
/:cl:

NPC wrangling

---

code/datums/outfits/quick_load_beginners.dm

Current loadout doesn't give plasteel as it used to, this causes you to lose out on equipment points since it'll use up all 75 while only giving you 52 points of gear.
The pr basically just gives the loadout back its plasteel with 50 in the engineer module and another 10 metal to help use 3 leftover points.
Its just a trap to pick this loadout since you lose 23 equipment points.
:cl:
Fix: Standard engi loadout now fully uses its points

Fix for engineers standard loadout

---

_maps/bigred_v2.json
_maps/bluesummers.json
_maps/daedalusprison.json
_maps/desertdam.json
_maps/desparity.json
_maps/gelida_iv.json
_maps/ice_colony_v2.json
_maps/icy_caves.json
_maps/kutjevo.json
_maps/lavaoutpost.json
_maps/lawanka.json
_maps/lv624.json
_maps/lv759.json
_maps/magmoor_digsite_iv.json
_maps/metnal.json
_maps/orion_outpost.json
_maps/oscar_outpost.json
_maps/prison_station_fop.json
_maps/research_outpost.json
_maps/riptide.json
_maps/vapor_processing.json
_maps/whiskey_outpost_v2.json
code/__DEFINES/maps.dm
code/_onclick/hud/parallax.dm
code/modules/mob/mob.dm

Since some ground maps are in space this makes it look pretty again 
:cl:
fix: Slumbridge,deltastation and other maps now have working parallax
/:cl:

Remove hardcode groundside noparallax and split it out into a Z trait

---

code/modules/power/multiz.dm

Looks to have been a concern by grayson on the previous multiz attempt, so I'll just fix this now
:cl:
balance: MultiZ Cables can't be destroyed
/:cl:

MultiZ Cables can't be destroyed

---

code/__DEFINES/atom_hud.dm
code/_onclick/hud/rendering/plane_masters/plane_master_subtypes.dm
code/game/atoms/_atom.dm

:cl:
qol: Certain HUDs will now appear over game world objects. Most notably this means that xeno HUDS now layer over smoke
/:cl:

Certain HUDs will now appear over game world objects

---

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm

Kurocracy decree
:cl:
balance: mech legs now slow increasingly based on hp instead of when destroyed
/:cl:

mech legs now slow increasingly based on hp instead of when destroyed

---

code/__HELPERS/ai.dm

Makes AI actually check for the faction of droids/turrets.
No more killing the AI ripley.
:cl:
fix: NPC's actually check turret and droid faction when looking for targets
/:cl:

droid and turret faction checks

---

code/__DEFINES/sound.dm
code/game/objects/items/storage/storage.dm
code/game/sound.dm
code/modules/projectiles/guns/grenade_launchers.dm

No vol, no sound, played on an area
atomization in prep for playsound refactor.
you should NOT be doing any of these it just wastes cpu time
:cl:
code: passing invalid playsound() arguments will now cause a runtime
/:cl:

Playsound will now scream under certain conditions

---

code/modules/clothing/glasses/glasses.dm

Another "no idea how this worked before"
Fixes spatial agent sunglasses
:cl:
fix: Fixed untoggleable glasses turning themselves off on load with no way to turn them on
/:cl:

Fix untoggleable glasses turning themselves off on init

---

code/modules/reagents/chemistry/reagents.dm

NPC's won't give chems to corpses anymore.
This means they should actually work down the priority list to bandages and such.
He's dead, Jim.
:cl:
fix: NPC's will no longer give chems to corpses
/:cl:

NPC death checks for chems

---

code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
code/modules/ai/ai_behaviors/human_mobs/weapon_module.dm

Added some procs for NPC's to store held items.
Specifically when equipping weapons, they will now try store whatever is in their hands first.
This means if they have a pistol/knife out and try equip a rifle, they'll store the smaller weapon instead of just dropping it on the floor like a dweeb.
Better inventory management, paves way to actual equip items in use later.
:cl:
add: NPC's store equipped weapons when equipping new ones
/:cl:

NPC item storage

---

code/game/objects/machinery/vending/marine_vending.dm

Adds the new req sentries (shotgun, sniper, flamer, laser) to the valhalla vendor, along with the minisentry and BAS (technically already acquirable, but having to go engie for it was kinda stinky)
Also renames the "Mounted" section of the valhalla req vendor to the "Emplaced" section to fit the sentries in
:cl:
add: Adds the shotgun, sniper, flamer, and laser sentries to the valhalla req vendor
add: Adds the minisentry and build-a-sentry to the valhalla req vendor
spellcheck: Renames the valhalla req vendor's "Mounted" tab to the "Emplaced" tab
/:cl:

Adds extra sentries to valhalla

---

code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm

Increases the Melter strain's health by 50 and all of their armor by 5.
Ever since gas got nerfed to be see-through, Melter became terrible since that was suppose to be the replacement of Evasion. To make up for this terribleness, they get some survivability.
:cl:
balance: Melter, a strain of Runner, now has +50 more health and +5 armor across the board.
/:cl:

Increases Melter's Health & Armor

---

code/modules/xenomorph/_xeno_structure.dm

Was not using a helper?
closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/17371
:cl:
fix: Fixed silo alerts alerting on friendlies
/:cl:

Fixes silo alerts alerting on friendlies

---

code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
code/modules/projectiles/ammo_datums.dm

Fixes Dragon's passflags to use the new managed passflag procs.
Removes unused variables left over from Dragon PR.
Bugfix.
:cl:
code: Dragon's abilities use the managed passflag system.
/:cl:

Dragon Passflags

---

code/modules/xenomorph/maw.dm

Per title, ONLY maw is impacted
6->12 sec
Part of the fun of strategic launch detected is the dread, and ours impacts instantly rn. This is thus funnier and gives you more time to react
:cl:
balance: Doubled xeno maw impact time from 6 to 12 seconds
/:cl:

Double xeno maw impact time

---

code/__DEFINES/dcs/signals/signals.dm
code/__DEFINES/mobs.dm
code/datums/components/chem_booster.dm
code/datums/status_effects/xeno_buffs.dm
code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm

**Commissioned by Elsa**
Gorger now mooches 25% of a Vali's current greenblood, plus 10 units, on each drain attack.
This blood is directly converted into gorger blood ammo at 1.25 per each unit of greenblood.
Balance has been plugged into defines and may be subject to change. 
Vali users get a little message in chat letting them know their greenblood is being stolen. Let me know if it should be bigger.
Improves Gorger's status as a Vali Counterplay. 
Reduces the benefit of intentionally letting a gorger feed off you to farm max greenblood from them 
:cl: Sun-Soaked, Comissioned by Elsa
balance: Gorger's drain and carnage attacks now steal greenblood from the target, if they have a vali harness.
/:cl:

[BOUNTY] Gorger drain abilities now steal Greenblood 

---

code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
code/modules/mob/living/carbon/xenomorph/castes/dragon/castedatum_dragon.dm

Dragon movement decreased from -0.5 to -0.1.
Dragon is now even slower while using Dragon Breath.
Dragon's armor gain while using Dragon Breath is decreased from 15 to 10.
Apparently, it is too fast according to Kuro (and others).
:cl:
balance: Dragon is now slower on average and even slower while using their ability, Dragon Breath.
balance: Dragon's armor gain while using Dragon Breath has been decreased from 15 to 10.
/:cl:

Dragon Movement Speed Nerfs / Dragon Breath Armor Reduction

---

code/game/objects/effects/decals/Cleanable/humans.dm

basically just adds some randomization to blood decals so they look less repetitive
looks cool
:cl:
add: more seamless looking blood decals
/:cl:

Seamless Blood Decals

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale.dm

Nerfs mech EHP by over 50%.
Removes access to the flamer because it just fucking murderfucks everything in sight.
For reference, the single use AT rocket will now insta kill a recon mech, even from the front.
Current mech rework has completely and utterly fucked mech balance. This doesn't fix it, and frankly I can't until mech changes are done, but this should make them less cringe.
:cl:
balance: Significantly nerfed mechs in campaign
/:cl:

Campaign mech nerfs

---

code/modules/projectiles/ammo_types/heavy_ammo.dm
code/modules/vehicles/armored/ammo_magazine.dm
code/modules/vehicles/armored/armored_weapons.dm

Nerfs autocannon fire rate from 0.35 to 0.45.
Reduced HE radius from 3 to 2.
Removed the sunder from HE direct hit.
Reduced magazine capacity from 100 to 50.
AP ammo buffed to 40 dam, 45 pen and 4 sunder (its still worse than HE in most situations though).
Autocannon tank, specifically HE ammo, is extremely shitty for xenos to play against.
Its very high DPS, large AOE spammable damage with constantly stacked slowdown, sunder, weed removal, and insane ammo economy.
This probably doesn't even rein it in enough, but its better than current state.
:cl:
balance: Nerfed tank autocannon and HE ammo, AP ammo slightly buffed
/:cl:

Some autocannon nerfs

---

code/modules/mob/dead/observer/login.dm
code/modules/mob/dead/observer/observer.dm

Reverts tgstation/TerraGov-Marine-Corps#17370
Breaks observers.
days since tivi last ruined the game: 0

Revert "Ghosts see mech hud now as part of squad hud"

---

code/modules/ai/ai_behaviors/human_mobs/healing.dm

NPC medics will no longer try to revive people that are unrevivable.
:cl:
fix: NPC's will no longer try to revive undefibbable patients
/:cl:

NPC Undefibbable check

---

code/game/objects/structures/droppod.dm
code/game/objects/structures/stool_bed_chair_nest/bed.dm
code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
code/modules/vehicles/__vehicle.dm

NPC's will stay buckled to medivacs, and vehicles when not the driver (i.e. back of a hoverbike, in a sidecar, etc).
Also made drop pods actually in the TGMC faction so marine NPC's won't smash them to bits.
Smarter AI.
:cl:
qol: NPC's will stay buckled to medivac's and vehicles when not the driver
qol: NPC's will no longer smash drop pods as obstacles
/:cl:

NPC buckle improvements

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm

Per title. Should fix issues where T4 strains do not correctly set a death timer, allowing these to be bypassed. To provide an example, if King has a strain called Conqueror, and Conqueror died, a death timer would be set for the Conqueror but not for the King, which meant that people could immediately evolve to King again. This is fixed by this PR.
bug fix good
:cl: Lewdcifer
fix: Fixes death timers for T4 strains.
/:cl:

Fixes death timers for T4 strains

---

code/game/objects/effects/weeds.dm

Weak explosions from things like the autocannon are highly spammable, and AOE, spammable weed removal is actually a really strong ability, as it directly debuffs target xenos even further.
:cl:
balance: Weak explosions no longer damage weeds
/:cl:

Weak explosions no longer destroy weeds

---

code/datums/gamemodes/campaign.dm
code/datums/gamemodes/infestation.dm

If you turn off end of round sounds in prefs it will also apply to round end sounds. Also renamed some single letter vars in gamemode code.
While testing this I had to listen to our shitty ambience noises that, for whatever reason, are low quality as hell and last like 10 minutes. Absolutely torturous.
:cl:
fix: Toggling round end sounds actually applies to round end sounds and not just world rebooting sounds.
/:cl:

If you toggle off EOR sounds it actually works

---

code/modules/ai/ai_behaviors/human_mobs/heal_procs.dm

NPC's check for the instant revive trait that robots have.
NPC's medics will simply just revive dead robots, instead of trying to heal them up to defib threshold (and failing since they have no robo meds)
:cl:
fix:NPC's will revive robots regardless of health, as intended
/:cl:

NPC checks for instant revive trait

---

code/modules/shuttle/marine_dropship.dm
code/modules/tgui/states/alamo.dm

Makes it so only the actual hive leader (the one at the top of the list in hive status, oldest alive T4, the xeno who "rises to lead the hive") can jack or capture alamo, rather than any T4
This has been admin policy for the longest time, just makes it easier codewise. 
:cl: Cheese
add: Only the actual hive leader can jack or capture alamo now, rather than every T4. (The xeno at the top of the list in hive status is hive leader)
/:cl:

Only actual hive leader can jack or capture alamo

---

code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm

Adds more debuffs to the scaling of dancer damage
Dancer is supposed to scale off of debuffs that other xenos can apply and these debuffs were missing, notably pyrofire
:cl: Cheese
balance: Dancer debuff scaling now also respects Shatter, Pyrofire, and Melting debuffs. 
/:cl:

Dancer Debuff list expansion

---

code/modules/vehicles/mecha/mecha_movement.dm

same issue as footsteps
:cl:
fix: mech no longer spams steps on tram movement
/:cl:

Forced mecha movement no longer plays the stepsound

---

code/modules/vehicles/armored/__armored.dm

Same issue as wound overlays
:cl:
fix: fixed tank turret turning black on multiz maps
/:cl:

Tank turret no longer turn black on z prolly

---

_maps/map_files/Arachne/TGS_Arachne.dmm
_maps/map_files/Sulaco/TGS_Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
code/datums/gamemodes/nuclear_war.dm

Adds a second Corporate Liaison slot to Nuclear War and adds a second CL spawnpoint to the maps that didnt have two.
Liaison is our only pure roleplay job, which means on busy rounds they are stuck talking to themselves while everyone else is doing their jobs. Adding a second slot frees up more opportunity to have someone to roleplay with and create more memorable rounds where two people have a buddy cop dynamic while everyone else is fighting.
TLDR: Roleplay is more fun with a friend!
:cl:
add: Added a second Corporate Liaison slot to Nuclear War.
/:cl:

Adds a second Corporate Liaison slot to Nuclear War

---

code/modules/reagents/chemistry/reagents/medical.dm

See #16170 (ty @Ephemeralis)
tl;dr: nanites will only heal & consume nanites when a user meets a minimum threshold of 3 damage, instead of nanites being spent on 0.25 chip damage
Nanites aren't very good right now, and barely anybody takes them. The large amount of DOTs and chip damage in the game (melting fire, sentinel spit, IB 0.25 brute ticks) that you'll suffer through the average round basically ensure you'll need to chug down a comically large amount of food to keep your nutrition and blood up.
At the present moment, they're just strictly worse than the 'sidegrade' to BKTT they're meant to be. Having them handle chip damage better will make them at least usable (you'll still be punished horribly for taking a lot of damage).
🆑
balance: Nanites now only spend themselves to heal brute …

Reopens "Nanites only heal brute/burn if they can fix at least 3 damage"

---

code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm

this is fake news, anyone can evolve into shrikes
LIAR
:cl:
spellcheck: You will no longer believe the lie that only drones can evolve into Shrikes
/:cl:

Removes lie from drone castedatum

---

code/game/objects/obj_defense.dm
code/modules/clothing/modular_armor/attachments.dm
code/modules/clothing/under/ties.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/guns/revolvers.dm
code/modules/projectiles/projectile.dm
code/modules/vehicles/vehicle_attachments/vehicle_modules.dm

CL
:cl:
qol: Attaching non-gun things now plays sounds
fix: Fixed revolvers not playing their open sound
fix: fixed projectiles trying to play a nonexistent sound constantly when they hit an object
fix: fixed a runtime with RR windup
/:cl:

Fix a batch of new sound runtimes

---

code/modules/mob/dead/dead.dm
code/modules/mob/living/silicon/ai/freelook/eye.dm
code/modules/mob/mob.dm
code/modules/shuttle/on_move.dm

and a dupe relay fulllscreen call
Yet another refactor exposing shitcode
:cl:
fix: fixed zlevel changes being called multiple times in some cases
/:cl:

Remove old hacks for on_changed_z_level not being callled by moved

---

code/modules/vehicles/mecha/mecha_mob_interaction.dm

Mech wrecking throws you out and people leaving the engine runnning is annoying so 2 birds with 1 stone
:cl:
fix: Mech overload will now disable when a mob leaves
/:cl:

Mech overload will now disable when a mob leaves

---

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm

:cl:
fix: fixed mechs not showing damage overlays for arms
fix: fixed mech not showing damage overlays for destroyed limbs
fix: fixed destroyed limbs not updating when boosting/firing
/:cl:

Fixes mech damage overlays

---

code/modules/projectiles/gun_system.dm

proj fire at sets loc directly and this was initing them un nullspace cus idk reasons
:cl:
fix: Fixed projectiles being black on multiz
/:cl:

Fix projectiles being black on multiz

---

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm

Was making it so clicking it again didnt unobserve, oops
:cl:
fix: fixed the UI button to follow a xeno being clicked again not stoppping you from watching the currently watched xeno
/:cl:

Fix xeno observe not setting the xeno var

---

code/_globalvars/misc.dm
code/modules/mob/living/carbon/xenomorph/evolution.dm

Oops
People were using this to exploit sunder reset
closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/17309
:cl:
qol: strain and caste swap cooldowns now say have much time you have left when you click them
fix: fixed strain swap cooldown not working
/:cl:

Fix strainswap having no delay

---

code/modules/vehicles/armored/__armored.dm

q
:cl:
fix: Tank gun and damage overlays are no longer black on multiz
/:cl:

Tank gun and dam overlays are no longer black on multiz

---

code/__DEFINES/dcs/signals/signals.dm
code/datums/jobs/job/shipside.dm
code/datums/keybinding/xeno.dm
code/game/buckling.dm
code/game/objects/machinery.dm
code/game/objects/machinery/computer/nuke_disk_generator.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
code/modules/projectiles/guns/sentries.dm
code/modules/projectiles/magazines/sentries.dm
code/modules/reqs/supplypacks/weapons_packs.dm

mawp mawp mawp mawp
free gbp?
:cl:
spellcheck: fixes tense in unbuckling text
spellcheck: standardizes sentry and ammunition names for the sniper sentry, and the magazine names for both the sniper and shotgun sentry
spellcheck: updates nuke disk generator text
spellcheck: COMISG -> COMSIG
spellcheck: rewords TO job spawnin description
spellcheck: adds a missing period to the body scanner's chat log message
spellcheck: corrects breath -> breathe in the "fresh air fills your lungs" message
spellcheck: adjusts wording for boiler, praetorian, and gorger abilities
/:cl:

Some extra grammar & style stuff (part two?)

---

code/game/objects/structures/dropship_equipment.dm

Currently: tangle emitter does not produce tangle until it is turned off/on again
This is because dropship equipment's "linked_console" var is null until the player does something with the equipment (???)
As far as my tired 2am brain can tell this is the only way for equipment to know which console it is linked to so this PR just disables the emitter roundstart and adds some balloon alerts so new players figure out "oh I have to enable it in the console"
Fixes buggy behaviour
Probably makes more sense to just have it start enabled, but there is literally no way to get a reference to the console & this makes sure new players know about enabling/disabling the emitter ig
:cl:
add: Tangle emitter starts disabled to prevent a bug
qol: Tangle emitter now gives feedback on whether it's …

Tangle emitter disabled by default

---

code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Resin huggers now extingush their target
You can no longer crush huggers in hand
mari approved it lole
Being able to invalidate half of a caste by pressing two buttons is kinda bad i think. Extingushing is a more interesting way to stop marines from removing larval huggers than just making flares not ignite or w/e
:cl: Cheese
add: Resin huggers now extinguish their target
balance: You can no longer crush huggers in hand, as a human
/:cl:

Carrier Buffs

---

code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/life.dm

Adjusts critdragging code to include throwing, besides normal pulling. This effectively makes xeno abilities that displace the target also inflict oxyloss, instead of limiting this functionality to pulls only. Furthermore, critdrag now also updates health, preventing humans from being dragged any further than they should be.
Prevents xenos from dragging people for insane distances and sending them to Brazil.
:cl: Lewdcifer
balance: Being thrown while in crit will now apply oxyloss and update health. This prevents xenos from dragging people for insane distances.
/:cl:

[BOUNTY] Xeno throws while in crit now apply oxyloss

---

code/modules/projectiles/ammo_types/mech_ammo.dm
code/modules/projectiles/ammo_types/rocket_ammo.dm
code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm

Mech light booster/gen is lighter now to allow for better weight control
Mech GL has halved ammo capacity to curb spam, has lower weight to compensate
Mech micro rockets are actually nerfed now (i nerfed the wrong ones last time lol), and had their weight adjusted upwards since theyre pretty good
Mech shotgun has the same falloff as marine shotgun now as opposed to double, and lower weight
Mech flamer has lower weight
Mech rocket launcher has lower weight
Better balance for mech
:cl:
balance: Mech light booster/gen is lighter now to allow for better weight control
balance: Mech GL has halved ammo capacity to curb spam, has lower weight to compensate
balance: Mech micro rockets have been properly nerfed, their weight has been increased
balance: Mech shotgun has the same falloff as marine …

More mech balance changes

---

code/datums/components/beacon.dm
code/game/objects/machinery/squad_supply/supply_console.dm

Chnages the tracking to be the owner instead of a turf
most noticable when trying to drop something on tram
:cl:
fix: Fixed supply beacons missing if the beacon moves
/:cl:

Fixes supply beacons missing if the beacon moves

---

code/game/objects/machinery/computer/camera_advanced.dm

CAS shouldnt be able to see shipside ideally
:cl:
fix: Fixed player cameras hopping over zlevels when they shouldnt
/:cl:

Fixes eyes hopping all zlevels

---

code/datums/gamemodes/crash.dm

Attempts to fix crash spawning >1 xenos every 2 minutes "larva spawn cycle".
We aren't sure this is actually the cause, however as mentioned the change to put the balance scales call after the check time update is a good idea to avoid any potential problems if balance scales check somehow was slow.
Fixes a bug slopping crash rounds.
:cl: Isy232, ivanmixo
fix: Attempts to fix crash spawning >1 xeno per larva spawn cycle.
/:cl:

Crash Xeno Spawn Fix

---

code/game/objects/structures/xeno.dm

15 seconds -> 30
fifteen fucking seconds is wayyyyy too short of a duration given how slow resin jelly is to produce, how easily spammable fire is, and how many xenos need it at once. Maybe 15 is acceptable for like, a spitter, or something, but xenos' main mode of engagement is still melee.
Not to mention that in the big xeno buff PR, the general trend was to make xenos slower, but have more health. This obviously reduces the effectiveness of resin jelly, as it makes engaging and disengaging much slower.
:cl:
balance: Increases resin jelly duration from 15 seconds to 30 seconds.
/:cl:

increases resin jelly duration

---

code/game/atoms/atom_movable.dm
code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm

Diag wasnt resetting the dir to nondiag on failed move, so we now do that
To make sure king can still beam diagonally, it now tracks the last attempted move dir, which means you no longer need to hug a wall to use diag mech beam
:cl:
fix: Fixed failed diag movement making the atom dir diagonal
qol: As a side effect of the above, king no longer needs to hug a wall to shoot laser diagonally, and just tracks the last attempted movement
/:cl:

Fix failed diag movement making the atom dir diagonal (ft. king buff)

---

code/modules/transport/linear_controller.dm

Nips any preemptive fuckery with nuke deleting etc in the bud early
:cl:
balance: Tram ignores smashing the nuke
/:cl:

Tram ignores smashing the nuke

---

code/game/objects/effects/aliens.dm
code/game/objects/structures/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm

Same fix as fire
also deleted some unused crap
:cl:
fix: Acid spray, sticky, firenados fall on openspace
/:cl:

Acid spray, sticky, firenados fall on openspace

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Note the T3 penalty for crash is current 1 (unchanged) and 0 for all other modes.
Previous Functionality:
The T3 penalty of 1 would remove 1/3rd of the 2nd T3 slot from the hive on crash.
The hive would always have a minimum of at least 1 T3 slot.
The penalty only impacts the 2nd T3 slot by a single xenomorph.
New Functionality:
The T3 penalty of 1 removes 1 whole T3 slot.
The hive has a minimum of 0 T3 slots. (No T3 slots on ultra lowpop crash).
The T3 penalty removes the 1st T3 slot.
The minimum of always 1 T3 slot isn't sensible for crash balance.
Reducing the number of T3 slots on Crash is a good way to reduce the power of xenomorphs on Crash without reducing their numbers.
We have a lot of xeno players who I do not want to deny their play any more.
:cl:
balance: Adjusted how the T3 …

Adjusts the Crash T3 Xeno Penalty.

---

code/datums/gamemodes/crash.dm
code/datums/gamemodes/infestation.dm
code/datums/gamemodes/nuclear_war.dm

Enables changing the required xenos to evolve Queen, King, or anything else added to the list to values dependent on the current game mode.
Enables disentangling pop requirements for crash and nuclear war for better balancing.
:cl: Isy232, Ivanmixo
balance: Crash now requires 10 xenos for Queen and 14 for King and 8 for Hivelord.
balance: Nuclear War now requires 4 xenos for Queen and 12 (unchanged) for King.
code: Xeno evolution pop requirement can now depend on game mode.
/:cl:

Xenomorph Pop Requirements by Gamemode

---

code/datums/shuttles.dm

TM before merge just to make sure we dont have any new wierd edge cases
maybe I should put it in a different order idk
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/17443
:cl:
fix: fixed wierd behaviour with things under shuttles showing when they shouldnt. Shuttles will now always try to revert a plating instead
/:cl:

Fix many shuttle tiles not setting a baseturf and thus creating really wierd shit

---

code/game/turfs/turf.dm

Since the baseturf z level setting and the other fixes this is no longer needed and its created giant plating cubes in the transit z
:cl:
fix: fixed transit zlevel having a bunch of plating
/:cl:

Fallback baseturf is space again

---

code/game/objects/structures/droppod.dm
code/modules/mapping/space_management/space_reservation.dm

From 3x3 to one large static area for everyone to use, so people see each other when dropping and dont see the walls (I think they still appear when its too close to edge though sadly?)
Yay seeing teammates or something
:cl:
qol: Improved drop pod drops. They now use a permanent area that all drop pod users drop into when dropping instead of creating a tiny one every time
/:cl:

Reworks drop pod reservations

---

code/modules/transport/transport_module.dm

Fixes hitboxes teleporting wherever and desants also teleporting wherever
:cl:
fix: fixed wierd teleporting riding interactions on trams with tank riders and the tank hitbox
/:cl:

Tram/elevator hitbox/desant fixes

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Sorry for fucking up, sorry for not testing that.
Here is the fixed version that shouldn't divide by 0.
Crash Test:
https://cdn.discordapp.com/attachments/500801682058379265/1356024294605455440/image.png?ex=67eb0f89&is=67e9be09&hm=109da5ac0bb6c796a5794093058715c0bf2344d5f8b35861f42109d791008387&
Nuke War Test:
https://cdn.discordapp.com/attachments/500801682058379265/1356024768226132140/image.png?ex=67eb0ffa&is=67e9be7a&hm=c472930d840624886a850848c02c1511694d76043410d128f34fa118b6c5ba33&
Fixes my fuckup causing division by 0.
:cl:
fix: Fixes my crash t3 balance change dividing by 0.
/:cl:

Crash T3 Penalty Fixed

---

code/__DEFINES/xeno.dm
code/game/objects/items/explosives/grenades/flares.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm

Dynamic plasma cost is cool; 2x faster casting matches the plasma cost reduction on flares which cost 50% plasma when scaling by dissolvability. So you can now melt 2 flares for the price of the former 1 in time and plasma. Oh and your walls will be 2x more expensive.
It's dynamic I guess
:cl:
balance: 2x faster acid casting on flares, plasma cost affected by dissolvability (0.5x flares, 2x walls)
/:cl:

Acid cost affected by dissolvability, cast delay buffed against flares

---

code/modules/projectiles/ammo_datums.dm

…nside them (tank hitbox)
TM this, this is what was causing canister bursts to hit the tank hitbox, since they were initing and then trying to move out of a valid target. Likely affected other similar cases but tank is the most notable. Dunno about any other knock-on effects this might have.
:cl:
fix: Fixes directiona lbursts (canister,  buckshot) hitting solid objects if it spawns inside them (tank hitbox, walls, etc)
/:cl:

Fixes directionalburst(canister) hitting solid objects if it spawns inside them (tank hitbox)

---

code/datums/gamemodes/crash.dm

Always two there are. No more, no less. A master and an apprentice.
Balance scales will always spawn xenos gradually until there are at least 2.
Solo xeno is the worst experience in the game, two xenos are at minimum needed for ultra-lowpop to be playable.
:cl:
balance: Crash will always have at least two xenos, instead of one.
/:cl:

Crash always has at least two xenos

---

code/datums/components/seethrough_mob.dm

proly the result of pixel_x/y etc changes in 516
:cl:
fix: Fixed toggle seethrough offsetting your sprite on 516
/:cl:

Fixes toggle seethrough offsetting your sprite on 516

---

code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm

Kuro did this
:cl:
fix: fixed dragon backhand doing nothing to mech
/:cl:

Fix backhand passing wrong blame mob arg

---

code/controllers/configuration/entries/general.dm
code/modules/client/client_procs.dm
config/config.txt

Most of the major servers have started forcing 516 and the remaining major issues we have is just the dpi stuff and stuff ive pred
I didnt test this byond connecting with my latest 516 client i admit
:cl:
server: Changed client version warnings to be in config
/:cl:

Change client version warnings to be config like tg

---

code/datums/gamemodes/crash.dm

15 minutes is less than 30 minutes
pretty simple
Xenos get "infinite" respawns every 5-2 minutes - marines after death have to wait for 30
15 minutes would make it so deaths still matter but you have a chance to play game again
instead of rotting in cope chat for 25 minutes 
Testing was done to ensure quality
:cl: Atropos
balance: Marine respawn time on crash is now 15 minutes
/:cl:

Respawn time on crash is now 15 minutes

---

code/modules/projectiles/ammo_types/tx54_ammo.dm

1. Canister Submunitions now ricochet off walls 2 times
2. Reduces scatter of Canister submunitions (Was 6, now 4)
3. Increases range of Canister submunitions (Was 7, now 12)
Damage values very likely need adjusting.
https://github.com/user-attachments/assets/ace97af8-e925-4b99-8706-150bfc2ca271
Canister is mostly considered worthless alongside HE and APFSDS counterparts, it's almost never taken by higher-playtime tankers. This gives it an area-denial effect allowing the tank to reach, slightly, around corners and into mazes.
The range is increased, this does mean projectiles can reach offscreen, but its necessary for ricochet, and LTB rounds can travel very far anyway, guarantee there's no sniping shenaniganry here you cant pull off with LTB HE.
The scatter was reduced to allow for more …

LTB Canister Ricochet and Rework

---

code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
code/modules/mob/living/living_defense.dm
code/modules/vehicles/mecha/_mecha.dm
code/modules/vehicles/sealed.dm

Use a range define
use spatial search instead of hearers
works on mechs too now
fixes get dist todo crap
fixes the in vision range stuff not applying to vehicles
fixes args not being the same
fixes the default arg runtiming the proc (wtf lol)
:cl:
refactor: Screech_act refactored, performance improved
fix: Screech now calculates distance from queen for effect correctly instead of just applying the minimum for mech/tank/apc
fix: Screech now considers vehicles for line of sight calculations for screech effects
/:cl:

Screech_act refactor

---

tgui/packages/tgui/interfaces/MechVendor/MechAssembly.tsx
tgui/packages/tgui/interfaces/MechVendor/MechWeapons.tsx
tgui/packages/tgui/interfaces/MechVendor/index.tsx

See CL for list of  p player facing changes
I also started using fill and grow cus uhh me bald so it should look better on 516
:cl:
qol: Mech builder colors are scrollable now
fix: Mech builder UI looks less scrunched oup on 516
qol: Mech builder weapon extra detail is smaller and better formatted now
qol: Mech builder UI is less tall
qol: Mech Builder UI now shows you more explicitly the Hand and Back weapons with an icon
qol: Mech builder UI scales better when being dragged around
/:cl:

Improves the mech builder UI yet again

---

code/modules/vehicles/armored/armored_weapons.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm

Only was a problem with non-singlefire windup weapons which mech now has in form of the rpg
:cl:
fix: fixed being able to fire without windup for mech rpg
qol: mech will now spin when checking windups
/:cl:

Fixes mech and tank not handling windups correctly

---

code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale_core.dm

regression
:cl:
fix: Fixed mech boosting weapon overlays not updating
/:cl:

Fix mech boosting weapon overlays not updating

---

code/__DEFINES/cooldowns.dm
code/__DEFINES/mecha.dm
code/modules/vehicles/mecha/equipment/mecha_equipment.dm
code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm
code/modules/vehicles/mecha/mecha_actions.dm

This is so certain weapons have shared CDs like rapidfire and high alpha strike ones
also fixed dual rocketpod due to the windup
todo put these in the UI
Stop broken combos, kurocracy blabla
:cl:
fix: you can no longer fire the alternate mech gun while winding up a weapon
balance: smg and rifle share cooldown and cannot be fired at the same time
balance: mech shotgun and rocket pod share cooldown
/:cl:

Adds mech shared cooldown weapon groups

---

code/modules/admin/topic.dm

Mentors can see playtime now basically
El headmentor wants it I think?
:cl:
admin: mentors can now see players' playtime
/:cl:

Viewing a players playtime is now R_ADMIN and R_MENTOR

---

code/modules/vehicles/armored/__armored.dm
code/modules/vehicles/sealed.dm

Tank/APC now fall down zlevels
Sealed vehicles dont spin when falling
:cl:
fix: tank/apc fall down zlevels now
/:cl:

Vehicle zmovement fixes

---

code/datums/jobs/job/other.dm
code/modules/admin/debug_verbs.dm

read title
I dont want to emote - i want to speak while griefing
aka its annoying having to use looc instead of directly speaking to xenos while doing admemery
:cl:
qol: Spatial agents can now speak xeno common
/:cl:

Spatial agents can now speak xeno

---

tgui/packages/tgui-panel/audio/player.tsx

https://github.com/tgstation/tgstation/pull/90445
https://github.com/tgstation/tgstation/pull/90445
idk you tell me
:cl:
fix: Chat wont crash if we fail to play an admin sound
/:cl:

Dont crash the chat if we fail to play an admin sound

---

_maps/map_files/DaedalusPrison/DaedalusPrison.dmm

Removes the second gen on Daedalus, it was meant to be removed but I forgot
Two gens on one map unintended
South gen is too easy to get
:cl:
del: Removes second gen on Daedalus
/:cl:

Removes second gen on Daedalus

---

code/game/objects/machinery/vending/vending.dm

The attempt_restock proc did not acknowledge the show feedback variable for its balloon alerts so I added a simple check to each one.
The attempt_restock proc can't make use of the display_message_and_visuals proc due to scoping or else I would've used that.
If the nanoammo PR is merged, this solves a visual bug, but it was generally bad that the attempt_restock proc was not acknowledging the feedback argument.
:cl:
fix: Attempt_restock() proc now values your feedback
/:cl:

Added check for attempt_restock() feedback

---

code/game/objects/items/cocoon.dm

Per title.
This bypasses xeno restrictions on dragging dead people. That's very wack.
:cl: Lewdcifer
balance: Xenos can no longer pull resin cocoons.
/:cl:

Xenos can no longer pull resin cocoons

---

code/controllers/subsystem/persistence/_persistence.dm
code/game/objects/items/storage/holsters.dm
code/game/objects/machinery/vending/marine_vending.dm
code/modules/projectiles/guns/revolvers.dm
code/modules/projectiles/magazines/revolvers.dm
code/modules/reqs/supplypacks/imports_packs.dm

The speedloaders for the R-44 SAA are the base type for all revolver speedloaders, which is atypical as base types are often abstract base types for other subtypes.  I created a new type for the R-44 SAA speedloader that derived from a second abstract base type.  The purpose of the double abstract base type is because the R-44 SAA itself is also based off two abstract base types, so I wanted to ensure the gun and the magazine have similar type paths.
I replaced all instances where loadouts or items were being loaded with the old SAA speedloaders with the new one.
Avoids potential errors for other work regarding revolver ammunition.  If the NanoAmmo PR is merged, it will allow the NanoAmmo to stock the SAA speedloaders because the base type pathing was causing an error with the …

Moved SAA speedloaders from base type to subtype

---

code/modules/vehicles/mecha/mecha_actions.dm

What it says on the tin
very hard to use long cd things like the micromissiles
:cl:
balance: Caps cloak mech gun cooldown CD after uncloaking to 1 second, and treats the fire cooldown as half of it's reality for this purpose
/:cl:

Cap cloak gun cooldown CD after uncloaking to 1 second, and treat the fire cooldown as half of it's reality

---

code/datums/jobs/job/shipside.dm

One slot will be granted every 20 players, starting at 40 players.
Kuro thinks they're ready for general use and the last few tests went okay, most tweaks needed are balance finetuning
:cl: Tiviplus, Kuro, Tyeagg, GregorMN, Lumipharon
add: XvH Mechs have been permanently reenabled. One slot will be granted every 20 players, starting at 40 players.
add: Mechs have been reworked to be faster compared to humans, but less tanky (sort of a diver/flanker role)
balance: Mechs no longer have directional armor, and are more mobile (diagonal movement, spinning to fire)
add: Mechs have been resprited and repaletted and will update their sprite on boosting or being destroyed, and they will leave a wreck
qol: Mechs also have many new visual effects
add: Mech weapons are now split into back and hand …

Permanently reenables mechs

---

code/modules/admin/fun_verbs.dm

Title
Copy of https://github.com/tgstation/TerraGov-Marine-Corps/pull/17623
fix good
Testing was done to ensure quality.
:cl: Atropos
fix: Fixed Global narrate only allowing one character
/:cl:

Fix global narrate only allowing one character

---

code/modules/power/groundmap_geothermal.dm

Bluespace gens can now be corrupted properly (as long as you are a caste that can corrupt, e.g shrike)
NOTE: Regular geothermals still cannot be corrupted, this is intentional & if you want to change it feel free to make the PR (I'm taking a break from coderstuff for a bit)
Let me know if there's any other problems with generators
Bugfix good
:cl:
fix: Bluespace gens can now be re-corrupted properly, if damaged but not exploded
/:cl:

Fixes applying corruption to bluespace gen

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Wall impact damage multiplier has been increased from x0.5 to x1.0 of the Warrior's melee damage.
Added a punch damage multiplier and set it to x1.2 of the Warrior's melee damage (this before Empower and Lunge).
The Warrior isn't performing so well nowadays, and needs some extra help.
:cl: Lewdcifer
balance: The Warrior's wall impact damage multiplier has been increased from x0.5 to x1.0 of the Warrior's melee damage.
balance: The Warrior's punch damage multiplier has been increased from x1.0 to x1.2.
/:cl:

Increases the Warrior's wall impact and punch damage

---

code/modules/projectiles/magazines/revolvers.dm

I'm back...
Changed the name of the R-44 SAA speedloader and the description.
https://github.com/tgstation/TerraGov-Marine-Corps/pull/17648 was supposed to address a bug with the NanoAmmo PR that's in progress, but it turned out that the typing wasn't the (only?) issue.  The R-44 speedloaders and R-44 SAA speedloaders share the same exact name and that causes an issue with the NanoAmmo, so I just added "SAA" to the name and matched the description to it.
:cl:
fix: Changed R-44 SAA speedloader's name
/:cl:

Changed name/desc of SAA R-44 speedloaders

---

code/datums/storage/subtypes/belt.dm

look above at the pr title
It can hold injectors, analyzer other small med stuff - so why shouldn't it hold hypospray? 
hypo is same weight as pills both big rig and lifesaver are still better than this so i think its fine to add hypo
Testing was done to ensure quality.
:cl: Atropos
add: Small medical rig can now hold hyposprays (60u version)
/:cl:

Light medical rig can now hold hyposprays

---

code/modules/mob/living/carbon/xenomorph/charge_crush.dm

Crushers charging mech legs will instead target chest if legs have no hp
Effectively one charge oneshots legs two shots oneshot the entire thing
If you managed to get it off twice in a row it should be valid to get the kill imo?
:cl:
balance: Crushers charging mech legs will instead target chest if legs have no hp
/:cl:

Crushers charging mech legs will instead target chest if legs have no hp

---

code/modules/vehicles/mecha/combat/greyscale/greyscale_core.dm

https://tenor.com/de/view/ahui-gif-26935354
Kinda specific I know
:cl:
fix: Fix mechs being destroyed while not facing south and without an occupant making overlays layer wrong
/:cl:

Fix mechs being destroyed while not facing south and without an occupant making overlays layer wrong

---

code/game/objects/items/weapons/twohanded.dm
code/modules/mob/living/carbon/xenomorph/attack_alien.dm
code/modules/mob/living/carbon/xenomorph/castes/king/abilities_conqueror.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
code/modules/vehicles/__vehicle.dm

Per title. These are the changes:
- Endurance's maximum block health reduced from 1600 to 1200.
- Endurance no longer allows the usage of other abilities while it is active.
- Vehicles (such as mechs and tanks) cannot be attacked while Endurance is active.
Conqueror is currently able to get away with some things it shouldn't, and this is a good start as any (and hopefully sufficient enough) to stop that from happening.
:cl: Lewdcifer
balance: Conqueror's Endurance's maximum block health reduced from 1600 to 1200.
balance: Conqueror's Endurance no longer allows the usage of other abilities while it is active.
balance: Vehicles (such as mechs and tanks) cannot be attacked while Conqueror's Endurance is active.
/:cl:

Nerfs Conqueror's Endurance ability

---

code/game/objects/structures/crates_lockers/closets.dm

Gogo gadget pocket bfg
:cl:
fix: You can no longer put tanks, apcs and mechs into closets
/:cl:

You can no longer put tanks, apcs and mechs into closets

---

code/game/objects/machinery/nuclearbomb.dm

title
right now only disabling gives the message while enable is in the logs 
putting both in chat should make it easier to see what happened without having to dig logs
:cl: Atropos
admin: More nuke logging (enabling is seen in chat)
/:cl:

enabling nuke sends message to admins

---

code/modules/admin/admin_verbs.dm

title
Only other way to check current state of autoballance is to inspect xeno 
and even then you have to do math to figure out exact %
math bad - numbers being shown to me good
Testing was done to ensure quality.
:cl: Atropos
admin: set xeno buffs verb now also shows current autoballance
/:cl:

Set xeno buffs shows current autoballance

---

code/datums/status_effects/debuffs.dm
code/modules/projectiles/projectile.dm

There was an issue with the stacking debuff potentially applying from your own shots and therefore cucking the next shots if the target you shot was moving towards you (because the timer only starts when the bullet hits, target being closer means less bullet travel time, target closing distance in the meantime, shortening the travel time while the timer is still adjusted for the old distance, yadda yadda)
I've just made the effect track the gun it was last shot with and if its the same gun hitting the xeno we just don't apply the damage modifier. This should help address at least some of the edge cases and is the most practical solution I could think of on short notice.
Should hopefully make you cuck yourself less when using marksman weapons.
:cl:
fix: The sniper stacking debuff should be …

Stacking debuff adjustment

---

code/controllers/configuration/entries/general.dm
code/game/verbs/ooc.dm
config/config.txt

https://github.com/tgstation/tgstation/pull/90441
Will need config changes once the forum changes are done, DB changes are done already
:cl:
add: Added a forum-byond account link verb. Will be enabled when the forum has been fixed to be able to link accounts again
/:cl:

Add forum link verb

---

code/modules/factory/machines.dm

for factory machines - it was saying 100 instead of 1 
Fix good
:cl: Atropos
fix: fixed factory machines displaying incorrect times
/:cl:

Fix wrong req timers

---

code/game/objects/machinery/tesla_turret.dm
code/modules/reqs/supplypacks/engineering_packs.dm

Max range reduced to 6 from 7.
Max targets reduced to 3 from ONE HUNDRED OR MORE DEPENDING ON THE CELL
Increased req cost to 400 from 250 (same as a turret)
Increased power use per hit to 100 from 75.
Tries to rein in the utter bullshit of this item, I don't know why it was even merged honestly, its just a tesla gun turret only 20 times better in every way.
This item is really fucking poorly balanced, even with these nerfs holy shit is it completely bad design.
It has no target cap, and doesn't require LOS, so even in smoke it will hit 20 xenos nonstop and prevent them from using abilities.
Xenos have literally no way to counter or mitigate this in any way, other than destroying it.
It uses normal cells which means it can have 10,000 power with a basic high cap cell, so it has absurd …

Tesla turret nerfs

---

code/datums/gamemodes/_game_mode.dm
code/datums/gamemodes/crash.dm
code/modules/mob/living/carbon/xenomorph/evolution.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Adjusts T3 slot scaling on crash to not fall off with larger hives as they do in nuclear war.
Reduces hivelord xenomorph pop requirement to 5.
Reduces caste swap timer in crash to 5 minutes.
This is to fix the issue with highpop crash being slightly too favourable to marines.
Shows 2 Open T3 slots at 6 xenos, including a T3.
Also shows hivelord (which I evolved) at this number of xenos.
Shows reduction to caste swap timer in Crash Gamemode
:cl:
balance: Xenos Caste swap timer in crash is now only 5 minutes.
balance: Hivelord xenos requirement 8 => 5 in crash.
balance: Xenos T3 slots now scale better beyond the 1st in crash, second slot at 6 instead of 7 now.
/:cl:

Crash T3 Slots Scaling Increased + Hivelord Pop Reduction + Caste Swap Timer Reduction

---

code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm

Dragon Breath immediately ends if the caster (Dragon) enters critical / dies.
Corpses don't breathe fire. Bugfix.
:cl:
fix: Dragon Breath no longer continues to happen if Dragon enters critical or dies prematurely.
/:cl:

Dragon Breath only works while awake

---

code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm

Reactivating the Dragon Breath ability while it is in the middle of breathing fire now ends the ability instead of giving the "already breathing fire" balloon alert.
Apparently it was not intuitive to just switch abilities, so adding recasting to cancel it is cool.
:cl:
qol: You can now cancel Dragon Breath by reactivating the ability.
/:cl:

Recasting Dragon Breaths ends it early

---

code/game/objects/effects/landmarks/landmarks.dm

Resin landmarks were actually landmarks for tunnels, this fixes that
Does not change any actual landmarks as jelly pod landmarks are unused
Spotted it by chance, codefix good
:cl:
fix: Jellypod landmarks no longer spawn tunnels
/:cl:

Jellypod landmarks now actually work 

---

code/modules/projectiles/gun_helpers.dm

I added this years ago as the first thing to use rclick for since I didnt have many ideas, but we now have the better functionality of the underbarrel gun for this so I think its hindering that, and who is really using this
:cl:
del: Attack hand alternate on guns no longer toggles safety if there is no underbarrel gun
/:cl:

Attack hand alternate on guns no longer toggles safety

---

tgui/packages/tgui-panel/settings/SettingsGeneral.tsx
tgui/packages/tgui-panel/settings/scaling.ts

https://github.com/tgstation/tgstation/pull/90634
:cl:
qol: you can now reset the adjustable pane splitters in chat settings
/:cl:

Reset button for adjustable pane splitters

---

_maps/map_files/Sulaco/TGS_Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm

what it says on the title
how did nobody notice??? (or care)
I mean mechs should have pods right?
also theseus was missing 2nd computer 
Sulaco before 
Sulaco After
And theseus (tad picker was moved east closer to tad stuff)
:cl: Atropos
add: Added mech drop pods on sulaco and theseus
add: Added 2nd mech (builder) computer on theseus
/:cl:

Adds mech pods on sulaco and theseus

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm

Title, moves the bsg on big red further into engineering.
Current bsg location is in a cramped almost right next to an LZ, making it incredibly easy to get running and to keep protected. Moving it deeper into engineering means that they will have to make more progress before they can set up the bsg, and the more open room means they will need more materials to fully protect
:cl:
balance: Big Red's bsg has been moved deeper into engineering.
/:cl:

Moves bsg on big red further into engineering

---

code/modules/projectiles/ammo_types/heavy_ammo.dm
code/modules/projectiles/ammo_types/rocket_ammo.dm

Certain powerful projectiles that lack notable feedback (because they're just high damage, not explosions) now cause very brief screenshake (0.2/0.3 seconds).
Makes it a bit clearer when a tank has shot you with an AP round etc.
:cl:
qol: Some powerful projectiles such as tank AP rounds have brief screenshake on hit for user feedback
/:cl:

Heavy projectile feedback

---

code/game/objects/structures/lattice.dm

Xenos now need to use disarm intent instead of harm intent to destroy catwalks
In the heat of combat, it can be very annoying to be met with a do_after while trying to either hit or grab a marine thats standing on a catwalk. I believe this is also the reason as to why you remove snow on disarm and not harm.
:cl:
qol: Destroying catwalks now requires disarm intent instead of harm intent.
/:cl:

Catwalk destruction now on Disarm intent [MDB Ignore]

---

code/modules/food_and_drinks/kitchen_machinery/griddle.dm

Griddles can now be jumped and walked over like tables.
Table sized object that is usually next to tables should be jumpable like tables.
:cl:
add: Griddles can now be jumped over and walked on.
/:cl:

Griddles can now be jumped on like tables

---

code/game/objects/structures/crates_lockers/closets.dm

Title
Right clicking is very a lot nicer than pulling the ID off of your chest to open something.
:cl:
add: Lockers can now be unlocked with right click.
/:cl:

Lockers can now be unlocked with right click

---

code/datums/jobs/job/shipside.dm
code/datums/outfits/shipside.dm

Previously as example robo ac's would spawn WITHOUT loader pamphlet - if 2 robo ac's spawn  they literally cant get loader
i also added RO as a bonus
Not having job essential items bad
:cl: Atropos
fix: Robo ac's/ro's now get their job items (pamphlet/tablet)
/:cl:

Robo Ac's/Ro's now get their job items

---

code/modules/power/apc/apc_attack.dm

Right clicking an APC with an open hand will now unlock it (assuming you have the correct access and skill to use the APC).
Engineer powercreep?
Helps with muscle memory, feature many other servers have, helps reduce tedium when fixing APCs.
:cl:
add: APCs can now be unlocked with right click.
/:cl:

APCs can now be right clicked to unlock

---

code/datums/jobs/squads.dm

SLs are no longer put in a squad if it has another SL in it.
Example: If there is already a Charlie SL, you cannot spawn as a Charlie SL.
You can still transfer yourself to squads with another SL in it, and CIC can still do the same
Should stop 'four delta SLs' and provide a good spread of leadership across squads, making it more likely a squad will have an SL and less likely to have a 'too many cooks in the kitchen' situation
..also, I think this is the intended behaviour. So bugfix good, I guess?
:cl:
add: SLs are no longer put in a squad if it has another SL in it. SLs can still transfer to whatever squad they want, regardless of whether there's a squaddie in it
/:cl:

No more allocating multiple leaders in a squad

---

code/modules/xenomorph/xeno_turret.dm

Fixed turrets using the wrong range value when putting together its target list (this is separate from actually trying to hit one of these targets).
Will reliably target mechs/tanks etc.
:cl:
fix: fixed xeno turrets not targeting mechs/tanks in some cases
/:cl:

xeno turret targetting fix

---

code/modules/recycling/disposal.dm
code/modules/recycling/sortingmachinery.dm

Powered and unpowered disposal units can now be emptied with right click.
No more misclicks causing guns to be trapped in a disposal bin forever.
:cl:
add: Disposal units can be right clicked to eject their contents.
/:cl:

Disposal units can now be emptied with right click.

---

code/modules/mob/living/carbon/human/examine.dm

Inspired with what main TG has
More precisely admin observers can shift click examine mobs and will get all the usual admin options
instead of right clicking or player panel or vv you can just inspect people for all the tools
Less button pressing = good
Qol = good
:cl: Atropos
admin: Inspecting people while ghosted shows admin buttons
/:cl:

Admin ghosts can now examine mobs to pull up chat links

---

code/datums/gamemodes/_game_mode.dm
code/datums/round_statistics.dm
code/game/objects/machinery/computer/nuke_disk_generator.dm
code/modules/requisitions/fulton.dm
code/modules/requisitions/supply_export.dm

Completing a disk cycle rewards requisitions points per cycle equivalent to the function with x as the number of current players.
CAS Points are also added at a rate of 1/10.
Notable points are highlighted.
The points gain is dependent on player count because point gain based on selling dead xenos correlated to player count, with more xenos having more chances to die and be sold. Additionally, more players should generally have more points spread between them.
To maintain balance xenomorph sell prices are halved, including CAS points.
T1 150 => 75
T2 350 => 175
T3 600 => 300
_(Shrike included in T3, unchanged)_
T4 1100 => 550
To avoid a nerf to fulton packs, fulton packs have had their uses doubled to 6.
Reduction to snowballing and increase to objective based gameplay.
Rounds that are …

Objective Based Requisitions Points Gain.

---

code/game/objects/machinery/computer/nuke_disk_generator.dm

Every cycle of a nuclear disk completed gives marines +2 Vendor Points.
This totals to 10 points per completed disk and 30 total for all 3 disks.
This totals to a lot less than the original implementation which added 50 on each disk completion for a total of 150.
PR Tested on local thanks to advice from Demir
**[April 3 Update], Disentangles crash and Nuclear War**
After running 1 disk cycle on CRASH:
After running 1 disk cycle on NUCLEAR WAR:
Utilizes slightly modified code from: #16162
The idea was good, this allows marines to have a small trickle of sustained resources without requisitions.
The original implementation was too generous with the points, allowing engineers to buy 3 sentries from gained points.
By halving the total number of gained points this should be reasonable.
:cl: …

Crash Vendor Points Resurrected.

---

code/__DEFINES/reagents.dm
code/game/objects/items/scanners/health_analyzer.dm
code/modules/reagents/chemistry/reagents.dm
code/modules/reagents/chemistry/reagents/food.dm
code/modules/reagents/chemistry/reagents/medical.dm
code/modules/reagents/chemistry/reagents/other.dm
code/modules/reagents/chemistry/reagents/toxin.dm
code/modules/reagents/chemistry/recipes/other.dm
tgui/packages/tgui/interfaces/MedScanner/data.ts
tgui/packages/tgui/interfaces/MedScanner/index.tsx

Adds a means of prioritizing reagents in the health scanner UI.
Also fixes Lipozine's OD, as it was written incorrectly.
Promotes a more consistent chemical contents look, more important chems at the top, less important at the bottom.
:cl:
qol: Health scanner reagents have some semblance of order
fix: Lipozine OD works
/:cl:

Lays foundation for Reagent Priority in health analyzers chemical contents list

---

_maps/map_files/riptide/riptide.dmm

Fixes areas without blockers that basically let you go out of bounds - screenshots bellow
this is bad i think
also LZ has another hole and 4th small one
:cl: Atropos
fix: fixed holes (that let you go out of bounds) on meridian riptide
/:cl:

Fixes holes (that let you go out of bounds) on meridian riptide

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm

Hunters attacking in stealth will now always break stealth.
Currently stealth only breaks once you've fully charged up stealth (i.e. you can do a stunning stealth attack).
Consistant with object attacks.
Its wack to smack someone repeatedly while still increasing stealth level.
:cl:
balance: Hunter attacks now always break stealth
/:cl:

Hunter stealth attack consistancy

---

code/datums/status_effects/debuffs.dm

Resisting while having a low amount of melting fire on you now correctly paralyzes you instead of only spinning you.
The issue was that adding negative stacks qdel'd the status effect early when it hit zero. Thus, no paralyze when it should of.
A bugfix of a bug that been around for a long while.
:cl:
fix: Resisting while having a low amount of melting fire on you now correctly paralyzes you instead of only spinning you.
/:cl:

resisting low stacks of melting fire correctly paralyzes you

---

code/__DEFINES/mode.dm
code/modules/shuttle/escape_pod.dm

Marines can no longer immediately hit the launch button on escape pods when evacuation is called to immediately begin the launching process.
Marines can manually launch the escape pod once 7.5 minutes has passed while evacuation is active.
Automatic escape pod launching has been increased from 8 minutes to 10 minutes.
The time spent to go from groundside to shipside during hijack is to prep whatever you want to do shipside, let it self destruct or evac. It shouldn't be for immediately leaving right after xenos land; basically wasting everyone's time.
:cl:
add: Examining the escape pod controller now will tell you how long until you can manually launch and how long until it automatically launches.
balance: Marines can no longer immediately launch escape pods when they are activated. …

instant evacuation launch begone

---

code/datums/actions/species_actions/prototype_supersoldier_action.dm

Suggested by mack
:cl:
add: Supersoldiers now get the "Longer Throw" stim, which lets them throw as far as if they were jumping without doing so
/:cl:

Supersoldier throwing farther stim

---

code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
code/modules/projectiles/guns/_shared_ammo_objects.dm

Adding some fire interactions for some xeno abilities. Let me know if there are others that could logically/plausible do so that I've missed.
The following abilities weaken/extinguish fire in their areas of effect.
- Psycrush (warlock)
- Roar(king)
- Wind current (dragon)
- Unrelenting force (shrike)
More fire interactions for xeno is good for active gameplay, instead of jelly or bust.
:cl:
balance: Psycrush, roar, wind current and unrelenting force all weaken fire in their AOE's
/:cl:

Fire counter abilities

---

code/__DEFINES/dcs/signals/signals.dm
code/_onclick/xeno.dm
code/modules/projectiles/guns/_shared_ammo_objects.dm

Xeno can pat fire on help intent to put it out.
Each pat = 10 fire stacks.
Cooldown is whatever your caste's attack delay is.
Dunno if UP or OP on numbers.
Minor but universally accessible way for xenos to engage with fire.
:cl:
balance: Xenos can pat out fire on open turfs with help intent
/:cl:

Xeno fire patting

---

code/modules/power/apc/apc.dm

As title says 
right now at 30% first equipment are turned off then lights and then everything
Why should equipment be turned off before lights? 
Lights turning off first seem better in like every way
you get more runtime from stuff while most of the time lights groundside are smashed in the first place - while shipside you might get extra 10 20 seconds out of the autodoc/whatever else
:cl: Atropos
qol: Apc's will first turn off lights then equipment
/:cl:

Apc's first turn off lighting then equipment

---

code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm

What title says - drones had missing flag to be given plasma 
Fix good
:cl: Atropos
fix: Drones can again receive plasma from queen
/:cl:

Fix drones unable to receive queen plasma

---

code/modules/projectiles/gun_system.dm

For literally forever magazines have always ejected in the DEAD CENTRE of the tile, and I'm SICK AND TIRED OF IT
This randomises their placement, preserving my remaining sanity.
Makes the debris marines leave behind when fighting a bit less monotonous to look at.
https://cdn.discordapp.com/attachments/1119971876148609065/1370798865841655962/autism.mp4?ex=6820cf6d&is=681f7ded&hm=d96ffb5d8536d4bbb13f64c0db88f5e44ee8911034d4cd635f994a7d1baf3356&
:cl:
add: Randomises the offset of ejected magazines.
/:cl:

Randomised magazine ejection offsets

---

code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm

Halves the delays to 1.5 seconds from 3 for the dragon's grabbed ability variations, reduces slap execution damage to 76.5 and  breath execution to 110, slap now also only spreads damage to 3 limbs
Currently the delay on the dragon's grabbed varieties of the ability are slow enough that it's a good way to self-sabotage if you use it. This PR halves the delays to make it actually a viable option besides just pulling the marine away and slashing them
:cl:
balance: Reduces the delay on casting finishers on marines that are grabbed to 1.5 seconds from 3
balance: Dragon breath execution now deals 110 and slap deals 76.5, and slap only spreads damage to 3 limbs
/:cl:

Buff dragon's grabbed variations by halfing the delay and nerfing the damage

---

code/game/objects/machinery/miner.dm

Title
NEVER let me code fr 
Fix good
:cl: Atropos
fix: fixed miners saying mineral value instead of ammount
/:cl:

Fix miners saying mineral value instead of ammount

---

code/modules/vehicles/mecha/mecha_actions.dm

Just noticed i forgot to pr this while cleaning up branches lmao
:cl:
fix: Assault armor no longer uses power unless it activates
/:cl:

Assault armor no longer uses power unless it activates

---

html/browser/banpanel.css

More precisely area where you input the ban reason is bigger 
I can barely read 2 lines and scrolling is kinda weird - more space to see reason good (imo)
Before and after
:cl: Atropos
admin: Ban reason input window is now bigger to improve readability 
/:cl:

Makes reason window in ban panel bigger

---

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
code/game/area/prison.dm

Makes some areas of prison metal roof again. The only change from this is restricted tad landing in a few places.
Security areas and high security cells are under metal roofs.
Also the little beach area is its own area instead of being in maint, and is unroofed entirely.
Engineering is underground, since it was moved INTO CAVES but kept the glass roof, letting tad land in the middle of a cave area, and right next to a common silo spot.
Currently prison is the most tad friendly map in the game, since 90% of it is glass roof, and (almost?) zero metal roofs.
These changes means tad can't just lad/rappel directly to disks or nuke (or bluespace gen). You can still land close, just not on top of them anymore.
:cl:
balance: Some areas on Prison Station are under metal roofs again, namely around …

Prison areas changes

---

code/datums/keybinding/xeno.dm

More precisely plant weeds is being used on 2 other places where it shouldnt be (place and select pattern)
look code for more info
Fix good
:cl: Atropos
fix: Fixed place and select pattern keybindings for xenos
/:cl:

Fixes xeno keybindings

---

code/datums/elements/directional_attack.dm

Directional attack will no longer make you randomly whack corpses
No more beating a dead horse (unless you are clicking on it)
:cl:
fix: Directional attack no longer hits corpses.
/:cl:

Fix directional attacks hitting corpses

---

code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm

Let's Widows unburrow if something forces them to lay down while burrowed, primarily from taking an SSD Widow.
Spider fix
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/14483
:cl:
fix: Burrowed SSD Widows can now unburrow
/:cl:

SSD Widow burrowed fix

---

code/game/objects/structures/barricade.dm

An oopsie from when solid plasteel cades were introduced, could generate additional mats.
Bug Fix
closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/17862
:cl:
fix: Solid plasteel cades give correct material refund
/:cl:

Solid plasteel cades give correct material refund

---

code/modules/admin/admin_verbs.dm
code/modules/admin/verbs/adminhelp.dm
code/modules/client/client_procs.dm

Port of main tg! which was a port from skyrat
What the title says 
players can see who said what in their latest ticket
Nice QOL for players letting them see the ticket history - and easily respond to admins (outside of using the ahelp)
Since currently it can be hard to find the messages from admins after few minutes cuz chat keeps on scrolling
images bellow
(yes i know its a lot of shitcode but im _trying_)
<details>
<summary>Screenshots</summary>
</details>
:cl: Atropos
add: You can now View latest ticket from admins/mentors with the new verb!
code: Made some ahelp code easier to read
/:cl:

Adds View latest ticket verb - allowing players to see their latest ticket

---

code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm

Title, makes the sizzler's smokescreen shoot transparent gas, instead of opaque. Also increases their spit damage by 5, and the gas cloud by 5 (effectively 10 if it's a direct hit). The bomblets will also now do up to 6 damage each (up from 0).
As it currently stands, sizzler is just a straight upgrade to boiler, being able to do everything a boiler can much faster, safer, and more frequently. Making the gas transparent will at least mean going sizzler is giving up the ranged cloak that boiler provides for more front-line AoE damage. The damage increases is meant to compensate from the lack of opaque gas.
:cl:
balance: Sizzler's smokescreen is now transparent
balance: Sizzler's smokescreen bomblets now do 6 damage each
balance:: Sizzler's spit now does 20 damage, and the gas cloud does 15 …

Makes sizzler's opaque gas transparent, increases damage on spit and bomblets

---

code/__DEFINES/movement.dm
code/modules/projectiles/projectile.dm

Works as follows:
UP: Is the turf above passable? if yes go there
DOWN: is the turf below passable? if no check if the first turf in direction of travel is passable, if yes go there
```
* Specifically, you have to on an edge or flying to shoot DOWN (so people can see you)
* but, if you're below, you want to only be able to shoot up if people can see you
```
This is intended to be paired with a multiz shadow thing I am working on for the ledge stuff
Yay shooting up and down
:cl:
add: Added  shooting upwards on multiz, you can shoot up as long as the turf above you is free
add: Added shooting downwards on multiz, you can shoot downwards as long as the turf below you is free or you are next to a ledge you can shoot down
/:cl:

Multi z shooting mechanics

---

.github/workflows/ci_suite.yml

Significantly lowers the CI usage of this repository by not running the tests on every single commit--it will still run on PRs

Don't run CI on pushed commits (while keeping pull requests)

---

code/modules/vehicles/armored/__armored.dm

https://github.com/tgstation/TerraGov-Marine-Corps/pull/17856/commits/9921552976f98d30c1b312eca6ef0614fa594506 accidentally tied the vehicle_collision proc to the vehicle crush sound cooldown, which caused a multifold delay in crush speed (because only one tile would trigger damage and only at 1s intervals).
I simply moved the vehicle_collision proc before the early return to solve this.
Bugfix good.  APC was crushing objects and walls, in the worst case scenario, less than 1/3rd its original speed.  Tank was less affected, but still affected and this should help.
:cl:
fix: fixed vehicle collision damage trigger speed
/:cl:

Untied vehicle_collision from sound timer

---

code/datums/elements/riding.dm
code/game/objects/items/weapons/twohanded.dm

What is says on the tin.
Wielding a gun with a large sprite now renders the gun over the offhand icon.
Looks better.
:cl:
qol: Large sprites in hand slots layer over offhand icons
/:cl:

Offhand icon layers under other hud objects

---

code/datums/health_scan/advice/traumatic_shock.dm

Tramadol advice will no longer pop out if you are a nanite user, since it gets purged by nanites and only gives you your mega pain reduction for 3-6 Life ticks anyway
Also, it was hidden with nanites in the old system
:cl:
fix: Fixed Tramadol advice showing for people with nanites in their system
/:cl:

Health analyzer: fixes Tramadol advice popping out in nanite users

---

code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm

Added a couple of missing hazards - dragon warning thingos, and king murderbeam.
Standing in death beam is bad.
:cl:
add: Added a few more hazards for NPCs to look out for
/:cl:

Missing NPC hazards

---

code/__DEFINES/ai.dm
code/__DEFINES/dcs/signals/signals.dm
code/__DEFINES/is_helpers.dm
code/game/atoms/atom_movable.dm
code/game/objects/items/stacks/rods.dm
code/game/turfs/liquid_turfs.dm
code/game/turfs/turf.dm
code/modules/ai/ai_behaviors/ai_behavior.dm
code/modules/ai/ai_behaviors/human_mobs/hazard_avoidance.dm

NPC's are significantly less likely to walk into lava, unless they have no other choice.
NPC's more accurately path towards a target (the direction to target provided by get_dir is quite often not the closest dir you'd expect).
NPC's mill about less, when escorting another atom. i.e. following a friendly mob, and within the desired range, they will be far more likely to just  hold still.
The lava fix isn't perfect, as they will at times get stuck (similar to being stuck behind a wall), but thats generally  better than suicide, and in the future I should be able to setup a pathing system so it can find a way out when stuck.
More sensible pathing, less tweaking out, less lava suicide.
:cl:
qol: NPC's move around far less, when escorting someone
fix: NPC's path more accurately towards their …

NPC movement improvements

---

code/datums/status_effects/debuffs.dm
code/modules/ai/ai_behaviors/human_mobs/healing.dm
code/modules/mob/living/living_defense.dm

NPC's will actually try resist out of melting fire and intoxication.
Fixed a runtime in intoxication where it runs out mid resist channel.
NPC melting to death bad.
:cl:
fix: fixed NPC's not putting out melting fire and intoxication
/:cl:

NPC resist fixes

---

code/__DEFINES/ai.dm
code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
code/modules/ai/ai_behaviors/human_mobs/human_mob.dm

NPC's are much better at pathing around friendly obstacles (i.e. barbed cades, friendly mechs), or indestructable ones.
Less getting stuck.
:cl:
fix: Improved NPC obstacles avoidance for friendly and indestructable obstacles
/:cl:

Friendly obstacle avoidance improvement for NPCs

---

_maps/map_files/riptide/riptide.dmm

Title
Apparently people are using the mech weapons in HvX, despite these being balanced for HvH. Also an intelligence computer two tiles next to a disk is incredibly bad due to the easy points.
:cl:
del: Removed mech weapons from the riptide cave ship
del: Removed intelligence computer on the riptide cave ship
/:cl:

Removes intelligence computer and mech weapons from riptide ship in caves

---

code/game/objects/items/explosives/grenades/bullet_grenade.dm

During testing I discovered that HEFA grenades are able to instantly crit any full health xeno. The only two exceptions were king and crusher that were close to crit. Every other xeno caste was either gibbed or in crit from one grenade detonating at their feet. 
SADAR, CAS, tank shots, flak guns, etc. do not possess this capability. 
Furthermore, by using heavy armor and attaching the Hod Ballistic Deflection module (standard equipment) this guarantees that you won't receive any shrapnel unless you are standing next to the grenade at point blank range. You can also load this grenade into a grenade launcher and spam them to your heart's content.
The two methods to obtain these grenades are ordering a box from req which costs 500 points for 25 grenades or using a factory to produce them. …

Nerfs easy method to instakill any full health xeno

---

code/__DEFINES/cooldowns.dm
code/modules/power/power.dm

Adds a cooldown for electric wire damage
When attached to a generator, electrified razorwire can instakill some castes and deals massive amount of damage to any others. This is funny but also a little ridiculous if properly utilised
:cl:
balance: Electrified razorwire has a cooldown, instead of being applied as fast as you can accidentally walk into it
/:cl:

Adds a cooldown for electric wire

---

code/datums/weather/weather_types/acid_rain.dm
code/datums/weather/weather_types/ash_storm.dm
code/datums/weather/weather_types/sand_storm.dm

Increases the time between the harmful weather warning being sent and the weather actually hitting from 30 seconds to 60 seconds.
Make new map with harmful weather -> "wow this weather sucks guys we should remove it" -> only big red keeps weather
Giving both teams more time to actually act around weather will allow them to actually shift their plans to deal with it instead of instantly dying to the death storm and we can hopefully use the system instead of blaming maps for having it.
*probably needs a testmerge to see if this is still too little or is too long.
:cl:
balance: Harmful weather will now warn 60 seconds before hitting instead of 30.
/:cl:

Increase the telegraph timer for harmful weather

---

code/game/objects/machinery/research.dm

As title says nerfs numbers on rsr 
mainly because xeno sell prices got lowered after introduction of disk req and rsr was missed
previous: 50/150/250/800
New: 50/100/200/400
:cl: Atropos
balance: credits earned from research sell for less points (50/100/200/400)
/:cl:

RSR sell prices nerf

---

code/datums/gamemodes/campaign/loadout_items/_TGMC/secondaries.dm
code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/smartgunner.dm

Fixes the marine db secondary not giving primary ammo if you have a bag.
SG-62 primary has actual primary ammo if you don't have an ammo belt (i.e. you have a db)
Having ammo is good.
:cl:
fix: Campaign: Fixed some loadout ammo issues with SG-62 and SH-34
/:cl:

Minor Campaign loadout fixes

---

code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/standard.dm

Gives SoM's axe squaddies Paracetamol, Isotonic, Rye pill packets, a cigar, matches, and a inaprovaline injector when taking the G8 General purpose belt.
Currently the axe gets nothing but an empty belt when they take it, this gives them some stuff.
Alternatively i could shove a bunch of throwing knives in it, cause lmao.
:cl:
balance: Campaign axemen get items inside general belt
/:cl:

Campaign Axeman general storage belt items

---

code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm

Makes NPC repair for APC's more robust. They should now be able to repair them regardless of what state they're in, as long as they have the tools.
They still can't build new ones though, so getting them to try fix a busted one won't help.
Reliable repair
:cl:
fix: NPC engineers can reliably repair APC's
/:cl:

NPC apc repair fix

---

code/modules/ai/ai_behaviors/human_mobs/human_mob.dm

Ordering an NPC to escort a mob will now actually work.
I had the arg in the wrong place, so they'd go to them, but not follow.
:cl:
fix: fixed NPC's being told to follow someone, not actually doing so
/:cl:

escort order fix

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
code/modules/projectiles/guns/_shared_ammo_objects.dm

Pyrogen HP 400 => 380.
Pyrogen damage per fire tick per fire stack 2.5 => 2.0.
20% DOT Reduction.
PRIOR To these changes, a Pyrogen fireball landing 1 tile beside a medium armour marine who stood still would deal **60 burn damage.**
AFTER these changes, a Pyrogen fireball landing 1 tile beside a medium armour marine who stood still would deal **50 burn damage.**
Pyrogen tends to significantly outperform spitter in ranged damage and area denial even when only relying on ranged abilities such as fireball and firestorm.
Pyrogen also has health, speed and armour superior to spitter.
Pyrogen also has superior melee utility and screech/gas follow up with inferno.
Pyrogen is generally just too stacked as a caste, especially in the risk to reward tradeoff. Reducing its health will force it to …

Pyrogen Health 400 => 380. Damage per fire stack over time 2.5 => 2.0.

---

code/game/area/kutjevo.dm

Seems someone put it as interior instead of exterior, which I am too lazy to change so it is just ceiling_underground now
Maybe caves shouldn't be able to be podded into, erm
:cl:
fix: Kutjevo Refinery cave nuke is now actually caves
/:cl:

Fixes Kutjevo nuke having no ceiling

---

code/game/objects/structures/crates_lockers/secure_crates.dm

The crates now have the proper icon instead of ERROR
:cl:
fix: Basic secure crates are no longer an ERROR sprite
/:cl:

Fixes secure crate sprites being ERROR

---

_maps/map_files/icy_caves/icy_caves.dmm

Adds a single wire to Icy Caves to connect the BSG to the colony power grid
Fix good
:cl:
fix: Added missing wire connecting BSG to everything on Icy Caves
/:cl:

Adds a wire to BSG on Icy Caves

---

code/modules/mob/living/carbon/human/examine.dm

What the title says - now when xenos examine humans they will see how many U of X reagent is inside them
and defiler can now see common meds like bic kelo + some special ones like nanites oxy etc. (look code for full list)
<details open>
<summary>image (as defiler) </summary>
</details>
whole idea came from looking at NTFvsALIENS so this is technically a port? but not fully shrug
also suggest any description changes as its very basic at the moment
Extra info for the defiler seems like a good idea since they can get the idea of what marine is using - a lot of chems? time for some ozy. no dylo at any point? neuro spam etc.
while update for normal xenos is a nice QOL 
:cl: Atropos
balance: Defiler can now see common medicine like bic. kelo. and other like oxy. or nanites
balance: Xenos can …

Updates xeno chem examine + adds more for defiler

---

code/modules/mob/dead/observer/login.dm

As byond member you can choose your orbit but it wouldnt load next game
fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/4980
Fix good
:cl: Atropos
fix: fixed BYOND member ghost orbit not working properly after restart
/:cl:

BYOND memebers ghost orbit fix 

---

code/game/objects/machinery/cloning/cloning.dm

A lot of people don't know or check the 'take offered mob' button in the status panel, so clones are probably taken less often than they would otherwise be.
:cl:
qol: Clones are available via the take SSD mob ghost action
/:cl:

Clones are added to the take SSD list

---

code/game/objects/structures/crates_lockers/largecrate_supplies.dm
code/modules/reqs/supplypacks/operations_packs.dm

Makes flare crates (containing 140 flares / 10 packs) available to purchase from requisitions for 75 points. 
This also ammends the description of the flare crate to correctly state how much it contains, since last I checked I don't think 20 flare boxes equals 100 flares.
As of Runian's latest pr (#17948) flares will no longer be infinitely obtainable through surplus flare pouches from the clothing vendor. 
This isn't really an issue since marines start with 200 flare boxes, but assuming it is merged then if for whatever reason they run out (E.G: Highpop rounds, marine stupidity) the RO would not be able to buy more.
Considering the RO can buy an infinite number of the rest of the grenades (and also flare shells for the mortar / howi), having flares also available shouldn't do any harm. …

Flare Crates purchasable from req.

---

code/game/objects/items/explosives/plastique.dm
code/game/turfs/walls/resin.dm
code/modules/projectiles/guns/flamer.dm

Fireproof resin walls now prevent flamers from penetrating them, making them immediately stop upon reaching the fireproof wall.
They will now not suck as much because flamers will no longer be flame through the "fireproof" resin wall. Now xenos can stand immediately behind the wall instead of 5 tiles away from the wall because the other side of wall just so happen to be an ocean of fire.
:cl:
balance: Fireproof resin walls now prevent flamers from penetrating them, making them immediately stop upon reaching the fireproof wall.
/:cl:

Fireproof resin walls block flamer shots

---

code/modules/projectiles/gun_attachables/attachable.dm

Fixes attachment activation sound. Flashlights and other attachments will create sounds when activated again
if(activate(user)) always returns false which skips the activation sound effect, you could probably remove it all together but I'm having strange problems with localhosting right now so I don't want to change it
After PRing this I realized there's another bug with attachments, which may be also present in other things, where the UI button in the top left to activate flashlight sometimes does nothing (reproduceable on localhost and the server) 
:cl:
fix: Fixes attachment activation sound
/:cl:

Fix attachment activation sound

---

code/modules/clothing/modular_armor/som.dm

Updates the SOM medium shield armor name and description. In campaign and everywhere else in the code it is called medium armor or just battle armor, but the item name is called light armor.
This PR brings the item in line with it's other references, making it less misleading.
:cl:
fix: Update SOM medium shield armor name and description
/:cl:

Update SOM medium shield armor name and description

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

Title
Xenos probably shouldn't be resting so close to the front but it's pretty lame to have a basic mechanic denied by stagger when stuff like spits aren't either.
:cl:
balance: Xenos can rest/unrest while staggered
/:cl:

Xenos can unrest/rest while staggered

---

code/modules/projectiles/magazines/misc.dm

all other pistols + even 357 packets are small unsure why mateba is medium
if kuro thinks its bad he can just close this simple as
Every pistol + revolver packet is small sized so i dont see why mateba should be different - yes its a req weapon and? why should it be harder to store
:cl: Atropos
balance: Mateba ammo packets are now small sized (previously medium)
/:cl:

Mateba packets are now small

---

.github/workflows/ci_suite.yml

Port of https://github.com/tgstation/tgstation/pull/91186
Removes the windows test build from CI suite.
(I don't know anything about github workflow, but Tivi said I needed to port this or whatever I can from it to fix the error checks.) 
I hate red x's.
Nothing player-facing.

Removes CI windows build

---

code/game/objects/items.dm

Adds a check has_limb_for_slot into mob_can_equip, which stops you from equipping gloves when you're missing hands or boots when you're missing feet etc
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/17978
No more disappearing gloves/boots causing ahelps. Also preventing weird ghost items, I'm still not exactly sure where the gloves were going.
:cl:
fix: You can no longer equip items if you don't actually have the limbs for them.
/:cl:

Equipping clothing without the limbs for them will no longer disappear the clothing

---

code/datums/actions/ability_actions.dm
code/datums/gamemodes/_game_mode.dm
code/datums/personal_statistics.dm
code/datums/round_statistics.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm

Adds in around 19 new (or just plain unused) abilities to be tracked on the round end stat panel, primarily for newer xenos that just hadn't had any of their abilities tracked at all.
These abilities are the following;
1. Acid applied to objects. (I.E: Walls, Items, Cades... etc.).
2: Melter acid shroud.
3: Melter acid rocket.
4: Globadier grenades.
5: Globadier mines.
6: Defender charge.
7: Boiler acid globs.
8: Boiler neuro globs.
9: Pyrogen fireball.
10: Pyrogen inferno.
11: Pyrogen firestorm.
12: Behemoth boulders.
13: Globadier XADAR.
14: Runner / Hunter pounces (and savages).
15: Runner evasion.
16: Hunter cloaking (and number of victims).
17: Defender tailsweep.
18: Shrike flings.
19: Shrike psychic cures.
Also adds a new personal stat, which tracks the acid YOU apply to objects. …

More roundend stats for xenos.

---

code/modules/vehicles/motorbike.dm

bike rev no longer reduces max fuel capacity
whoopsie, bug bad
:cl:
fix: bike revs no longer appear to give you more fuel, where they were reducing max fuel, now correctly removes fuel
/:cl:

bike rev no longer reduces max fuel capacity

---

code/__DEFINES/layers.dm
code/game/objects/structures/misc.dm
code/game/objects/structures/xeno.dm
code/modules/atmospherics/machinery/components/components_base.dm
code/modules/power/lighting.dm
code/modules/shuttle/shuttle.dm
code/modules/xenomorph/acidwell.dm

Let me know if there are other obvious ones to fix.
Fixes catwalks layering over stairs.
Fixes dropship smoke effects layering badly with the warning shadow, hiding northern warning turfs.
Fixes floor lights layering over objects.
:cl:
fix: fixed some floor layering/plane issues
/:cl:

Plane fixes

---

code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm

Charge CD is 12 seconds instead of 4.
Kuro said it was always meant to be this.
Highly spammable movement ability on a ranged caste is lame as fuck. You can still use it for entry or escape, but now you can't so easily use it for both.
:cl:
balance: Pyrogen flame dash CD is 12 seconds instead of 4
/:cl:

Pyro charge CD fix

---

code/modules/mob/mob_grab.dm

Fixed Warrior being able to aggressive grab throw marines, resulting in much further fishes and less abilities used.
Warrior being able to throw marines over 7 tiles with their lunge ability, then fling them even more tiles away is slightly broken I think. Admins also see it as bug abuse so krill it.
https://github.com/user-attachments/assets/265c37e4-f473-464c-85e5-7cb12fea1f8b
:cl:
fix: Fixed Warrior aggressive grab throw bug.
/:cl:

Fixed Warrior throw bug

---

code/modules/vehicles/_hitbox.dm

Changes how desants are effected by movement slightly.
Mobs are now thrown off if not conscious (i.e. dead xenos don't stay on)
Items are also thrown off (slightly lower distance though)
Cluttering vehicles with shit on top of them is very exploitable since it can be used to make the tank extremely difficult to click.
Also just using the tank as an inventory mule is cringe.
:cl:
balance: Corpses and items are thrown off vehicles on move
/:cl:

Desant throw changes

---

code/datums/weather/weather_types/sand_storm.dm
code/datums/weather/weather_types/snow_storm.dm

Ruins the game.
Changes some weather interactions for humans (xenos are unchanged).
Sand: Does 2 damage per second instead of 6, but ALSO applies 2 seconds of stagger (this doesn't stack).
Snow: Applies 1 unit of slowdown (again, this doesn't stack).
Weather is kinda shitty. It either does absolutely nothing, or it just fucking kills you super fast, neither of which are very engaging.
These changes means these two weather types have distinct and clear downsides that aren't just utterly lethal, so it's an actual decision point for marines if they want to fight in the weather, or hunker down inside.
Fighting in the weather will put marines at a disadvantage, instead of just wiping them entirely.
The damage values of sand now means it will counter your premed, but it won't actually kill you …

Weather changes

---

code/modules/vehicles/motorbike.dm

bike revving now no longer removes fuel to negatives, as it was lacking sanity
bug bad
no cl

bike revving now no longer removes fuel to negatives

---

code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm

Fixes #18033
Minions (and zombies) opening cades is bad
:cl:
balance: Minion proof latches have been installed on all folding cades
/:cl:

Minion cade fix

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Didn't really know how to word it correctly on the title so I'll just describe it here.
Currently, it is possible for priority candidates (tier 4 xenos) to obtain hive leadership without the appropriate flag. This means that a dragon, a caste without pheros, can become a ruler, and since it doesn't have pheromones, well... you probably see the issue by now.
What I did here is add a check for the appropriate flag, so that priority candidates without it are not valid choices. I also went through the tier 4s and made sure they all had the flag, which they do, except for Dragon. Probably not a coincidence.
Dragons have no pheros, and hives shouldn't be made to suffer for it.
:cl: Lewdcifer
code: Priority candidates for hive leadership now need the appropriate flag to become rulers. This …

Priority candidates for hive leadership now need the appropriate flag to become rulers

---

code/modules/mob/living/carbon/xenomorph/mutation_upgrade.dm

Alerts weren't showing up at the top right after a mutation was brought. This fixes that and makes it show up.
Bugfix.
:cl:
fix: Alerts from mutations now properly show up.
/:cl:

Mutation Alert Bugfix

---

code/game/objects/structures/dropship_ammo.dm

Price of tfoot minirockets increases from 200 to 400 points.
Tanglefoot CAS spam is very boring gameplay, but right now it is one of the most optimal ways to play CAS. Increasing its price is reasonable, especially if #18026 is going to be considered.
:cl:
balance: Tanglefoot minirockets price increased from 200 to 400
/:cl:

Increased price of tanglefoot minirockets from 200 to 400 points.

---

code/__DEFINES/mode.dm
code/datums/gamemodes/nuclear_war.dm
code/datums/jobs/job/shipside.dm

The amount of xenomorphs required to evolve into Queen is reduced by 2 if there are enough population for the first mech pilot job slot to be opened and reduced by another 2 when assault crewman job slots are opened.
This means the required xenomorphs will be 6 when the population is 40 and then 4 when the population is 50.
It is possible that mech pilot and assault crewman job slots to open on so-called lowpop (20 people in lobby/observing while the other half plays the game). I think it's cringe that marines are able to get their specialist role(s) while xenos don't get anything for it. Roles meant for higher pop should be opened on both sides instead of just one.
:cl:
balance: On Nuclear War, the amount of xenomorphs required to evolve into Queen is decreased by 2 if there can be a …

Mech/Tank Reduces Evo Requirement for Queen

---

code/modules/projectiles/ammo_types/energy_ammo.dm

BFG wall pierce now reduces range by 10 instead of 2.
i.e. you can pierce 1 wall and actually hit things, instead of like 7+
Funny cave/maze snipes are super wack.
:cl:
balance: Greatly reduced the BFG's ability to pierce walls
/:cl:

Less BFG wall pierce

---

_maps/shuttles/tgs_bigbury.dmm
_maps/shuttles/tgs_canterbury.dmm

Title
on small bury it replaces crew monitoring on big bury i did some shuffling of chem to make it nicer
i dont believe a single person used crew monitor more than once - we have new content let players use it
also cmo should be in med not sitting in cic
:cl: Atropos
add: Added medical overwatch to canterbury and big bury
/:cl:

Adds medical overwatch to canter and big bury

---

code/modules/projectiles/ammo_types/mech_ammo.dm

'Light' mech rockets were doing sadar level explosions because someone didn't check the typepaths.
Currently its 0, 4, 6 when it should be 0, 0, 4.
THis should be obvious
:cl:
fix: fixed mech light rockets being hugely more powerful than intended
/:cl:

fix light mech rockets

---

code/__DEFINES/mobs.dm
code/datums/gamemodes/_game_mode.dm
code/datums/gamemodes/crash.dm
code/modules/mob/living/carbon/xenomorph/evolution.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

The STATUS TAB has the right time, but the actual caste swap button was showing the wrong time since it was referring to the old 5 minute timer instead of the actual time.
Also changed the var name to be more accurate, since its just a cooldown duration, not an actual timer.
bugfix
:cl:
fix: fixed the caste swap button displaying the wrong time in nuke war
/:cl:

Fix caste swap timer showing the wrong time

---

code/_globalvars/game_modes.dm
code/datums/gamemodes/_game_mode.dm
code/modules/mob/living/carbon/xenomorph/castes/dragon/castedatum_dragon.dm
code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
code/modules/mob/living/carbon/xenomorph/evolution.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm

Designed to mirror the Tank / Mech roundstart players checks.
Dragon requires a roundstart population of 50.
King requires a roundstart population of 40.
Xenos requirements reduced to alleviate the case of lobby sitters enabling tank but blocking Dragon / King.
Dragon xenos requirement 13 => 8.
King xenos requirement 12 => 8.
For code reviewers, the var/evolve_min_xenos and var/maximum_active_caste were not located in the section of xeno_defines.dm where the other evolution variables were which was annoying so I moved them.
Parity between sides for better balanced rounds.
With lots of lobby sitters, Marines get access to Tank but Xeno numbers may never reach dragon, Favouring Marines.
With plenty of midround joiners, Marines have no Tank but Xenos reach dragon, Favouring Xenos.
_True and …

Dragon / King Population Locks

---

code/game/objects/machinery/vending/quick_vendor.dm

If you make the mistake of selecting the Quick Vendor during crash, you will be blacklisted from using your points later when disks are printed.
This fix simply removes the blacklist. The existing code already deducts all the points and checks to make sure you have full points before letting you use the Quick Vendor.
No more noob traps.
:cl:
fix: Fix quick vendor blacklisting marines from using points during crash
/:cl:

Fix Quick Vendor blacklisting vendor usage

---

code/__DEFINES/is_helpers.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/mutations_melter.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
tgmc.dme

Adds a total of 3 mutations all for Melter (Runner Strain).
| Shell | Acid Release | Upon entering critical, release stunning acid in a radius of 2/3/4 tiles. This resets upon reaching full health. |
| Spur | Fully Acid | All of your stash damage is burn damage and is now checked against acid. You inflict 1/2/3 additional melting acid stacks. |
| Veil | Acid Reserves | Corrosive Acid is now applied 50/75/100% faster. |
:cl:
add: Melter now has 3 new mutations that they can purchase if their hive has enough biomass and mutation structures. Not accessible without admin intervention for now.
/:cl:

Mutations: Melter

---

code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/mutations_globadier.dm
tgmc.dme

Adds a total of 3 mutations all for Globadier (Spitter Strain).
| Category | In-Game Name | In-Game Description |
| Shell | Self Explosion | Toss Grenade can target yourself. Targeting yourself will toss the grenade under you and reduce the detonation time by 0.5/0.75/1 seconds. The resulting detonation time can never go under 0.5 seconds. |
| Spur | Blood Grenades | Toss Grenade will deal damage equal to 20/17.5/15% of your maximum health and allow you to throw a non-healing grenade if you had none. |
| Veil | Repurposed Capacity | Toss Grenade stores 1/2/3 less grenades, but recharges a grenade 2/4/6 seconds faster. |
:cl:
add: Globadier now has 3 new mutations that they can purchase if their hive has enough biomass and mutation structures. …

Mutations: Globadier

---

code/datums/status_effects/debuffs.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/mutations_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/mutations_melter.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/mutations_retrograde.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/mutations_sentinel.dm

Drain Sting was dividing by zero. That was fixed and now the ability works as intended.
Acidic Slasher didn't correctly register signals. That was fixed.
Some mutations that still had leftover `if(!.)` in the structure update proc now has it removed which let it continue and do the rest of the mutation effects.
Updates Melter's mutations so it uses the proc from #18082
Makes the melting acid status effect spawn less particles in general.
Various bugfixes from mutations.
:cl:
fix: Sentinel's Drain Sting now works as intended.
fix: Sentinel's mutation Acidic Slasher now correctly deals its Intoxicated Stacks on slash.
fix: Various mutations now correctly get their effects when mutation structures are updated.
/:cl:

Mutation Bugfixes

---

code/datums/gamemodes/infestation.dm
code/datums/gamemodes/nuclear_war.dm

The Nuclear War gamemode (and its parent) no longer overrides King's evolution requirement which caused it to forcibly be set to 12 (which #17896 did not account for).
Bugfix.
:cl:
fix: King's evolution requirement is no longer overridden by the Nuclear War's evolution requirement of 12.
/:cl:

King Evolution Requirement fix

---

code/__DEFINES/traits.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/mutations_hivelord.dm
tgmc.dme

Adds a total of 3 mutations all for Hivelord.
| Shell | Hardened Travel | Resin Walk now grants 10/15/20 armor in all categories. You cannot regenerate plasma while it is active. |
| Spur | Rejuvenating Build | You heal 1/2/3% of your maximum health whenever you successfully use Secrete Resin. |
| Veil | Protective Light | Healing Infusion now also applies the effects of resin jelly for 15 seconds. The plasma cost is now 2x/1.75x/1.5x of the original cost. |
:cl:
add: Hivelord now has 3 new mutations that they can purchase if their hive has enough biomass and mutation structures. Not accessible without admin intervention for now.
/:cl:

Mutations: Hivelord

---

code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
code/modules/mob/living/carbon/xenomorph/castes/carrier/mutations_carrier.dm
code/modules/mob/living/carbon/xenomorph/egg.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm
tgmc.dme

Adds a total of 4 mutations all for Carrier.
| Shell | Shared Jelly | If you are under the effect of Resin Jelly, all thrown huggers gain fire immunity. Each thrown hugger reduce the duration of the effect by 3/2/1 seconds. |
| Spur | Leapfrog | Thrown huggers can now leap 1 tile at a time. All activation times are 0.8/0.7/0.6x of their original value, but will never be faster than 0.5s. |
| Veil | Oviposition | Egg Lay now creates eggs with your selected type of hugger inside. The plasma cost is set to 50/40/30% of its their original value and its cooldown is set to 50% of its original value. You lose the ability, Spawn Huggers. |
| Veil | Life for Life | Spawn Facehugger's cooldown is set to 70% of its …

Mutations: Carrier

---

code/__DEFINES/dcs/signals/signals.dm
code/datums/status_effects/debuffs.dm
code/modules/mob/living/carbon/human/human_damage.dm
code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
code/modules/mob/living/carbon/xenomorph/castes/pyrogen/mutations_pyrogen.dm
code/modules/mob/living/carbon/xenomorph/castes/pyrogen/pyrogen.dm
tgmc.dme

Adds a total of 3 mutations all for Pyrogen.
| Shell | Flame Cloak | If you are ontop of fire, you gain 5/10/15 armor in all categories. |
| Spur | Only Fire | Fire Charge deals no damage, does not consume melting fire stacks, and now pierces humans. Humans who are hit get 2/4/6 melting fire stacks. |
| Veil | Burnt Wounds | Melting fire stacks you inflict causes 15/25/35% healing reduction against brute and burn. |
:cl:
add: Pyrogen now has 3 new mutations that they can purchase if their hive has enough biomass and mutation structures. Not accessible without admin intervention for now.
/:cl:

Mutations: Pyrogen

---

code/__DEFINES/traits.dm
code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
code/modules/mob/living/carbon/xenomorph/castes/bull/mutations_bull.dm
code/modules/mob/living/carbon/xenomorph/charge_crush.dm
tgmc.dme

Adds a total of 3 mutations all for Bull.
| Shell | Unstoppable | Charging will grant you complete stagger immunity if you reach the maximum number of steps minus 1/2/3. |
| Spur | Speed Demon | Charging costs twice as much plasma. The speed multiplier per step is increased by 0.02/0.04/0.06. |
| Veil | Railgun | Charging now takes 4/8/12 more steps to reach maximum charge. |
Charging no longer directly sets your stored plasma and instead use the `use_plasma` proc; this means your plasma HUD now updates to reflect your current plasma and that it is no longer possible to have negative stored plasma from this.
:cl:
add: Bull now has 3 new mutations that they can purchase if their hive has enough …

Mutations: Bull

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
code/modules/mob/living/carbon/xenomorph/mutation_datum.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/xenomorph/_xeno_structure.dm

Xenomorph structures that are created without an specified hive number parameter within the centcom z-level will have their hive number replaced with Valhalla if it is created within xenomorph's Valhalla area or Admeme if elsewhere.
Valhalla xenomorphs can access the mutation menu without needing the caste flag that allows their caste to buy mutations. This does not mean that they are able to buy mutations as the mutation structures are still admin-only / unobtainable through normal gameplay. 
Makes it easier for admins to mess around with xenomorph structures within the Centcom Z-level, let it be Thunderdome or Valhalla. 
In addition, makes it easier for people who are interested in testing out mutations (if the admins do spawn in the mutation chambers to let them to do so).
:cl:
qol: …

Xenomorph Structures & Mutations for Valhalla/Admeme

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/mutations_ravager.dm
code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
tgmc.dme

Adds a total of 3 mutations all for Ravager.
| Shell | Little More | Endure further decreases your critical and death threshold by 20/35/50. |
| Spur | Deep Slash | Ravage's armor penetration is increased by 10/15/20. |
| Veil | Recurring Rage | Rage will automatically attempt to activate when your health reaches the minimum required threshold. Rage's cooldown is 90/80/70% of its original cooldown. |
:cl:
add: Ravager now has 3 new mutations that they can purchase if their hive has enough biomass and mutation structures. Not accessible without admin intervention for now.
/:cl:

Mutations: Ravager

---

code/datums/gamemodes/campaign/loadout_items/secondary_types.dm

Secondary kit for x3 AG nades. Costs a small 15 credits.
More accessible counter to smoke spam, but at a cost so AG itself is not spammable.
:cl:
balance: Campaign: AG nades are available as a secondary kit
/:cl:

Campaign: Antigas secondary kit

---

code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm

Fixed smartgunners not actually being able to use overclocked shields in campaign.
:cl:
fix: fixed overclocked shields not working for smartgunners
/:cl:

Campaign smartgunner shield fix

---

code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Praetorian's Spray Acid Cone now bypasses the carbon's acid timer cooldown to do acid_spray_act.
Fixes a bug where the acid just stopped coning because marine's "cooldown" for taking acid damage from stepping into acid puddles is the same as the one for taking acid damage/stunned from being sprayed with acid.
:cl:
fix: Getting directly hit by Praetorian's Spray Acid Cone now ignores the cooldown for taking acid damage - meaning that humans no longer can stop or ignore its effects because just they were hit too recently by acid.
/:cl:

Spray Acid Cone bypasses carbon acid cooldown

---

code/modules/reagents/chemistry/reagents/medical.dm

Floors the volume of medical reagents (and only medical reagents) added from vapor reactions - namely foam and smoke.
This prevents microdosing small amounts of powerful chems like neuraline in these reactions to get absurd amounts of AOE healing from tiny volumes.
So you can still have healing foam/smoke, but the higher reagent requirement means that if you want to do it with more powerful/limited chems, you'll need to use a lot more of them.
These kinds of transfer methods duplicate chems significantly, which is amplified by the number of mobs they can effect at the same time.
This allows a single neuraline injector and a pill or 2 of meraderm to do rediculously huge amounts of healing - far more than the original amounts would otherwise allow.
:cl:
balance: Foam and smoke reagents …

Foam and smoke microdose removal

---

_maps/shuttles/minidropship_big.dmm
_maps/shuttles/minidropship_factorio.dmm
_maps/shuttles/minidropship_food.dmm
_maps/shuttles/minidropship_mobile_bar.dmm
_maps/shuttles/minidropship_outrider.dmm
_maps/shuttles/minidropship_panopticon.dmm
_maps/shuttles/minidropship_standard.dmm
_maps/shuttles/minidropship_umbilical.dmm
_maps/shuttles/minidropship_urbantower.dmm
code/__DEFINES/dcs/signals/signals.dm
code/game/objects/machinery/door_control.dm
code/modules/shuttle/mini_dropship.dm
code/modules/shuttle/navigation_computer.dm
tgui/packages/tgui/interfaces/Minidropship.tsx

Adds a button to toggle tadpole shutters within the tadpole console
This PR should make TOs and others close the shutters more often, them not activating the shutters is a problem. I cant remember the last time during an evac the shutters have been closed in an appropriate amount of time, a delay of a few seconds could cost the lives of most people on board for no reason
- It's like how a good xeno uses hotkeys sure you could just click the UI button but in a combat situation you don't want to scan your buttons looking for the right one
- The position changes with the rotation making it harder to find
- The button is already very tiny
- Reduce UI physical and mechanical load
- It will allow the pilot to multitask better, they don't have to worry about finding the button in time to save …

Add a button to toggle tadpole shutters within the tadpole console

---

_maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
_maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm
code/datums/gamemodes/campaign/missions/fire_support_raid.dm
code/game/objects/structures/campaign_structures/misc_structures.dm

Reduced mission time from 10min to 9 min.
Added some predeployed sentries.
These missions tend to be VERY hard to win as the defender. This should create more urgency for the attacking force, and making it harder to just overrun the defenders, especially at lower pop.
:cl:
balance: Campaign: Fire support missions are a little easier for the defenders
/:cl:

Fire support mission tweaks

---

_maps/map_files/generic/Admin_Level.dmm

Adds an old/campaign mech weapons vendor to valhalla vehicle area
Currently you can summon old/campaign mechs via vehicle spawner in valhalla, but can't actually give them any weapons. This allows for people to actually test campaign mechs
:cl:
add: Added a mech weapons vendor to Valhalla
/:cl:

Adds a mech weapons vendor to valhalla

---

code/game/objects/effects/effect_system/smoke.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
code/modules/mob/living/carbon/xenomorph/castes/gorger/mutations_gorger.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm

Warlock can no longer switch their ammo type while Psychic Blast is in the process of firing via right-click.
The alpha of the gas from Defiler's Wide Gas was decreased from 120 to 60.
Unmoving Link, the Gorger mutation, was not giving the correct armor. It has been fixed.
Gaseous Spray, the Boiler mutation, did not account for the ammo types associated with Primordial Boiler. It has been fixed.
The illusion from Fleeting Mirage, the Hunter mutation, now uses the correct typepath to initialize itself with which means the AI behavior is now correctly set.
Bugfixes and balancing of mutations.
:cl:
fix: Warlock can no longer switch their ammo type while Psychic Blast is in the process of firing.
balance: Mutations: The gas from Wide Gas is now significantly easier to see through.
fix: …

Various Mutation Bugfixes

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/mutations_bloodthirster.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/mutations_ravager.dm
tgmc.dme

Adds a total of 3 mutations all for Bloodthirster (Ravager Strain).
| Shell | No End | Endure can be used in critical. It now costs 150/125/100% of its original plasma cost. |
| Spur | Early Rage | Rage can be activated at 55/60/65% maximum health. For the purposes of calculating rage power, your current health is assumed to reduced by 5/10/15% of your maximum health. This cannot go beyond the amount required for Super Rage. |
| Veil | Safety Trap | Endure further decreases your critical and death threshold by 50/75/100. If Endure ends while your health is under the default death threshold, you die instead. |
:cl:
add: Bloodthirster now has 3 new mutations that they can purchase if their hive …

Mutations: Bloodthirster

---

code/game/objects/structures/campaign_props.dm
code/game/objects/structures/campaign_structures/destroy_objectives.dm
code/game/objects/structures/prop.dm

Adds the can_climb_over function to various multi tile objects that needed it.
i.e. if you get blown onto a tank prop, you can actually just walk off now.
Also changed vehicle prop layer back to default, since sidemap makes it unneeded.
Getting stuck is lame.
:cl:
qol: Various multitile objects allow you to walk around on top of them normally, instead of being stuck in place
/:cl:

Walkover additions

---

code/__DEFINES/status_effects.dm
code/datums/status_effects/debuffs.dm
code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
code/modules/mob/living/carbon/xenomorph/castes/puppeteer/mutations_puppeteer.dm
tgmc.dme

Adds a total of 3 mutations all for Puppeteer.
| Shell | Flesh For Life | If damage taken would put you into critical, lose 1.5/1.25/1x amount of plasma instead. |
| Spur | Suffocating Presence | Dreadful Presence will inflict a temporary effect that deals 4/6/8 stamina damage every second instead. |
| Veil | Shifting Costs | Stitch Puppet's cost is 20% of its original cost. Bestow Blessing costs 40/30/20% more. |
:cl:
add: Puppeteer now has 3 new mutations that they can purchase if their hive has enough biomass and mutation structures. Not accessible without admin intervention for now.
/:cl:

Mutations: Puppeteer

---

code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm

:cl:
fix: Fixed boilers being unable to fire up/down zlevels
/:cl:

Fixes boilers being unable to fire up/down zlevels

---

code/game/atoms/_atom.dm
code/game/objects/structures/window.dm
code/game/turfs/closed.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/xenomorph/castes/king/abilities_conqueror.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/mutations_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/mob/living/living_defense.dm
tgmc.dme

Adds a total of 3 mutations all for Oppressor (Praetorian Strain).
| Shell | Lone Healer | Psychic Cure can now target yourself. Healing yourself is only 50/60/70% as effective and will set the cooldown to 200/175/150% of its original value. |
| Spur | Smashing Fling | Psychic Fling deals 100/125/150% damage equal to your melee damage, enables collusions, but no longer immediately stuns. If the target collides with a human, object, or wall: both are briefly paralyzed and dealt damage again. |
| Veil | Stand-In Recycler | You gain the Recycle ability. It costs 80/65/50% of its original cost. |
Psychic Fling's 0.2 second paralyze is replaced with a passthrough flag to go through mobs and forces them drop their …

Mutations: Shrike

---

tgui/packages/tgui/interfaces/IndividualStats/index.tsx

This PR fixes an issue where the campaign loadout menu could have content (such as the primary & secondary weapon slots) cut off when at high screen scaling. The loadout window is now scrollable when available screen space is not sufficient to display the whole window. The scrollbar only appears when necessary to view all content. 
It is good to be able to select equipment without having to change display settings. I looked at making only the relevant sections of the window scrollable, but that suffered from the same issue of cutting off content when resizing the window. 
Equipping items and selecting perks were tested and still function as expected.
<details> <summary>Images</summary>
</details>
:cl:
fix: fixed campaign loadout UI at high screen scaling
/:cl:

Campaign Loadout UI fix

---

_maps/shuttles/tgs_canterbury.dmm

I swapped around the locations of two medical vendors and one shower.  The MarineMed and NanotrasenMed Plus vendors are now next to each other horizontally in the south east corner of canter medical, and the shower has been moved to where the NanotrasenMed Plus vendor previously was located.
Before:
After:
This change makes it easier to set up cades at canter south during round start. The MarineMed vendor cannot be wrenched and moved around, and therefore was a permanent obstacle for optimal cade setups. This change moves it to be further inside medical relative to the south exit, which allows for a greater range of cade setups.
:cl: Scav
qol: Rearranged the positions of two vendors and the shower in canter medical
/:cl:

Moved around two vendors (and the shower) in canter medical

---

_maps/map_files/Sulaco/TGS_Sulaco.dmm

Before
After
Replaces:
Leader room duplicate weapons rack
Medic room duplicate nanomed plus
Engineer room duplicate clothing vendor
Smartgunner room clothing vendor
Leader and specialists have to go outside of the room into the general area to equip a loadout which leads to their shit spreading all over the place, most of the vendors I replaced have duplicates in the room and are less important than the loadout vendor
:cl:
add: Automated loadout vendors in specialist and leader rooms on sulaco
/:cl:

Add automated loadout vendors in specialist and leader rooms on sulaco

---

_maps/shuttles/tgs_canterbury.dmm

Re-added a light fixture in canter medical that I accidentally deleted when re arranging vendors in my last PR
Being able to see while performing surgery is good actually
:cl: Scav
fix: Re-added a light fixture in canter medical
/:cl:

Canter medvendors rearrange (UPDATE - re added light fixture)

---

code/__DEFINES/mode.dm
code/_globalvars/misc.dm
code/datums/actions/observer_action.dm
code/datums/gamemodes/_game_mode.dm
code/datums/gamemodes/crash.dm
code/datums/gamemodes/extended.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/carbon/xenomorph/death.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Xenos will no longer need to wait to respawn if there is burrowed larva.
The xeno respawn timer generally hurts lowpop gameplay a lot more than normal or highpop because on higher pops there will be a larva queue to take xenos as soon as they are available, while on lowpop there may be one or two burrowed sitting around and if a xeno player dies then they need to wait a whole 5 minutes before they can take the slot.
Letting xenos respawn as soon as they have a larva for them will help to make lowpop less stompy and hives more resilient to one or two xenos dying.
:cl:
balance: The xeno respawn timer has been removed. You can now spawn as soon as there is a burrowed available.
/:cl:

Removes xeno respawn timer

---

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_conqueror.dm
code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm

Decreases the conqueror's health from 800 to 650
Increases the dash ability cooldown from 3.5s to 4.5s
So yeah conqueror is pretty very incredibly overtuned especially since the king pop requirement has been lowered down to 8 which makes it almost impossible to kill on lower pops and still very hard to kill with higher pops
:cl:
balance: Conqueror's hp 800 -> 650
balance: Conqueror's dash cd 3.5s -> 4.5s
/:cl:

Slight conqueror rebalance

---

code/modules/mob/living/carbon/xenomorph/castes/boiler/mutations_sizzler.dm
code/modules/mob/living/carbon/xenomorph/castes/king/mutations_conqueror.dm

Fixes two typos in mutation descriptions in Neurotoxin Swap (Sizzler) and Telefrag (Conqueror).
Typos are bad.
:cl:
spellcheck: Mutations: Neurotoxin Swap's description now has the conjunction "and" that it was missing.
spellcheck: Mutations: Telefrag's description now uses the correct duration to display as seconds.
/:cl:

Fixes Mutation Typos

---

code/game/objects/structures/barricade.dm

Acid upgrade for cades gives the correct bonus of 35 extra resist instead of 75.
A certain someone is going to get paddled for sneaking through a huge walance change in a fix pr.
:cl:
fix: Acid barricade upgrades no longer give far more resist than intended
/:cl:

Acid cade fix

---

code/game/objects/structures/barricade.dm

Prevents upgrading a barricade multiple times in a row via stacking do_afters by making it so it doesn't go through if it already was upgraded.
Stops this:
:cl:
fix: You can no longer infinitely stack armor on barricades by upgrading when you're not suppose to.
/:cl:

Fixes infinitely stacking barricade armor upgrades

---

code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm

Mech sword now always aims chest.
(Almost) guaranteed one hit delimbs is uh, not ideal.
:cl:
balance: Mech laser sword always hits chest
/:cl:

Mech sword walance

---

code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/mutations_shrike.dm

Smashing Fling now scales at 150/175/200% damage from 100/125/150% damage.
Psychic Choke has been moved to the Veil (utility) category as it wasn't offensive enough to be sorted into Spur (attack) mutations.
Utility Fling has renamed to Body Fling and moved to the Spur category from the Veil category. It no longer reduces the cooldown of Psychic Fling. Instead, it causes flung xenomorphs to deal 150/175/200% damage and 2 seconds of paralyze to humans that they collide with.
Per feedback, Smashing Fling apparently sucks when compared to unchanged Psychic Fling. In addition, Utility Fling was boring and there was little reason to choose it.
:cl:
balance: Mutations: Smashing Fling now scales at 150/175/200% damage from 100/125/150% damage.
balance: Mutations: Psychic Choke is now a veil …

Shrike Mutation Changes

---

_maps/map_files/Arachne/TGS_Arachne.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/TGS_Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
_maps/map_files/debugdalus/tgs_debugdalus.dmm
code/game/objects/machinery/artillery/mortar.dm
code/game/objects/structures/dropship_equipment.dm

Did you even know this thing existed?
Buffs the spread on the double barrel mortar from 2 to 1.
A long time ago, in a forgotten age, people were evidently spamming this thing on the long tad by mounting three mortars and firing 12 shot fire missions from hell at xenos. 
Long tad doesn't exist anymore. Double mortar deserves better.
:cl:
balance: Double barrel mortar now spawns roundstart, like the HSG nest.
balance: Double barrel mortar spread: 2 -> 1
spellcheck: Makes it more obvious that the double barrel mortar exists.
/:cl:

Double barrel mortar buff

---

code/game/objects/machinery/telecomms/machines/relay.dm

Comms works properly on the 1st mission of campaign again.
Note that this bug was due to some changes @TiviPlus made to maploading as part of multi z changes, but I am not certain what specifically broke it.
However relays should always be powered as far as I am aware (breaking power shipside still cuts comms), so this seems fine.
:cl:
fix: fixed comms not working on the 1st mission of campaign
/:cl:

Comm relay fix

---

code/game/objects/machinery/OpTable.dm

NPC's will no longer desperately try get out from under the knife.
Having to sedate NPC's is somewhat funny but annoying.
:cl:
qol: NPC's won't try resist off operating tables
/:cl:

NPC's stay on op tables

---

code/game/objects/machinery/computer/nuke_disk_generator.dm

Fixed a runtime that would completely bug out disk computers on crash, due to no proper check before trying to give vendor points.
The game getting cursed because someone doesn't have their ID on is bad.
:cl:
fix: fixed disk computers in crash sometimes bugging out
/:cl:

crash disk computer fix

---

code/modules/projectiles/mounted.dm

Fixes #18240
:cl:
fix: fixed a pixel offset bug when mounted weapons were deconstructed by someone other than the operator
/:cl:

Fix mounted weapon offset bug

---

code/datums/status_effects/debuffs.dm

Pyrogen fire was runtiming attempting to set the icon_state after the status effect had ran its last tick and been deleted, this fixes that.
Runtime fix good
:cl:
fix: Fixed a runtime when pyrogen fire expires.
/:cl:

Fixes a runtime with pyrogen fire

---

code/modules/mob/living/carbon/xenomorph/castes/boiler/mutations_boiler.dm

Rapid Fire, one of Boiler's mutations, now correct scales its fast cooldown duration at 50/40/30% instead of 50/30/10%.
Bugfix. Not intended for it to be this much scaling per description.
:cl:
fix: Mutations: Rapid Fire's fast cooldown duration now correctly scales at 50/40/30% instead of 50/30/10%.
/:cl:

Fixes Mutation Rapid Fire CD Scaling

---

_maps/map_files/Orion_Military_Outpost/orionoutpost.dmm

Moves two of the crash landing sites to have better entryways into the canterbury, as these spots both had awkward walls and rock preventing crusher lanes on multiple sides.
Landing sites need open space for the canterbury doors or else sieges are much more difficult.
:cl:
balance: Moved crash landing sites on Orion Outpost to have better shutter positions to exit and siege.
/:cl:

Moves Orion crash landing sites

---

code/datums/components/harvester.dm
code/game/objects/structures/barricade.dm

Fixes #18288 
Also corrects an arg for harvesters to use the actual flag instead of TRUE
:cl:
fix: Ungas can no longer remotely upgrade barricades with their megamind powers
/:cl:

Fixes remote cade upgrades

---

code/modules/projectiles/ammo_types/xenos/pyrogen_xenoammo.dm

Pyrogen fireball currently detonates on the cade's tile when hitting one, instead of the tile it hit the cade. 
This PR makes it detonate outside the cade rather than inside.
Old behavior:
New behavior:
Fixes an inconsistent projectile behavior. Xeno projectiles should stop on the tile it hit, rather than splashing over the cade. Burning the extra tile deep meant marines could not repair the cade safely, which made pyrogen significantly stronger at sieging than dedicated siege castes.
:cl:
balance: Pyrogen fireball now detonates on the tile it hit an object, rather than the object's tile.
/:cl:

Pyrogen fireball now respects cades

---

code/modules/mob/living/carbon/human/death.dm

Title. When you're pulling a human and they die, you won't stop pulling them unless you're a xeno or some other non-human mob.
You don't have to spend the extra second to re-grab incapacitated humans when you're pulling them for rescue or _other_ purposes and they die. I think this is purely QoL and not balance (mainly because I genuinely can't think of a way this could creep into being balance, someone can make a point otherwise though).
:cl:
qol: Humans won't stop pulling other humans when the pulled human dies.
/:cl:

Humans won't stop pulling other humans when they die

---

code/datums/components/riding/riding.dm

Buckling into a ridable vehicle now actually sets the offsets/layers immediately, instead of when you move.
:cl:
fix: fixed offsets and layering when first buckling to vehicles
/:cl:

Vehicle post buckle fix

---

code/__DEFINES/ai.dm
code/controllers/subsystem/advanced_pathfinding.dm
code/modules/ai/ai_behaviors/ai_behavior.dm

If an NPC cannot find a path to a goal node, it will now ignore the goal node permanently after a certain number of attempts.
Previous PR's have made it less likely that NPC's should get stuck, but as it can never be foolproof, this is a final measure to ensure NPC's dont simply get stuck permanently if something fucky is happening with the node map/badminnery/my shitcode explodes etc.
Adds some admin logging so it can be investigated - handy if it turns out to be a mapping issue.
Also fixed a semi related runtime I noticed, and cleaned up a couple of now inaccurate comments.
Ensures NPC's will never get perma stuck in place.
:cl:
fix: If NPC's cannot path to a goal node after repeated attempts, they will now simply ignore it instead of getting stuck in place
/:cl:

NPC goal unsticking

---

code/modules/ai/ai_behaviors/ai_behavior.dm
code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm

Finally removes some old spiderling AI shitcode from the main npc behavior datum, and makes it a spiderling specific thing.
NPC mobs will no longer just stop moving because they are on the same turf as their target.
All NPC mobs switching their brains off because of one funny spiderling check is bad.
:cl:
fix: fixed NPC's not moving if they are on top of their target
/:cl:

NPC escort fix

---

_maps/shuttles/tgs_bigbury.dmm
_maps/shuttles/tgs_canterbury.dmm
code/game/objects/machinery/autodoc.dm

Look mom im making marine buff PR while playing xeno
No cmo (99%) on crash sucks 
theres a carrier or you get anything except frac and you gotta wait forever in the autodoc
lets lower the waiting part so you can play the game more
:cl: Atropos
balance: Crash autodoc is now 2 times faster
/:cl:

Crash autodoc is now 2 times faster

---

code/game/objects/machinery/vending/marine_vending.dm
code/game/objects/machinery/vending/vending_types.dm

SH-410 is not available from gun vendors.
I don't know why this gun was added - it's just 'high dps gun', with MASSIVE AP to make it absurdly good against high armour castes, and funny burst mode for huge burst damage with either ammo type.
For reference, the SH-15 it was compared to has something like half the DPS this does.
Someone is free to add it to req or give it to ert or something, but this is not balanced for roundstart gameplay, and since it does nothing but damage, there's really no point in nerfing it instead of removing it.
:cl:
balance: SH-410 removed from normal gameplay
/:cl:

Remove SH-410 from normal play

---

code/modules/projectiles/guns/smgs.dm
code/modules/projectiles/magazines/smgs.dm

Reverts MP-19 ammo capacity back down to 30.
Its a pistol, 30 round mag is already the highest in the game for pistols, and it has extremely good DPS, zero slowdown when wielded and perfect/scatter accuracy.
With a massive 45 round mag it has absolutely no downsides. A pistol should not be better than most 2 handed weapons.
:cl:
balance: MP-19 has 30 round mags again
/:cl:

MP-19 ammo nerf

---

code/datums/gamemodes/campaign/loadout_items/_TGMC/secondaries.dm
code/modules/projectiles/guns/energy.dm

Increases ammo consumption of the energy pistol on standard mode by 33%. In practice, this means that the standard firemode for the laser pistol goes from 30 shots, to 20 shots.
Pistols in TGMC have great DPS, great mobility, and great one-handed accuracy, which is all offset by their extremely low magazine capacity. The laser pistol has an extremely high magazine capacity for its class, which sets it above most other pistols. Along with its other benefits such as lightspeed velocity, the incendiary fire mode, its ability to take a bayonet, etc etc, makes it way overtuned compared to the other pistol options.
Decreasing its ammo capacity down to 20 puts it in line with the other options.
:cl: Joe13413
balance: Decreased the ammo capacity of the laser pistols standard fire mode to 20, from …

E-pistol nerf with less stupid this time

---

code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm

Pyrogen changes:
Pyrogen has more plasma but regens it slower, relying on actively fighting to regen plasma quickly.
Max plasma: 325 -> 1000
Plasma Regen 25 -> 30
Pyrogen now gains plasma on hit, equal to 2.5x slash damage (~55 plasma per slash)
Abilities are more expensive, especially ranged ones.
Fire charge: 30 -> 75
Fire charge now restores plasma when consuming firestacks, equal to firestacks * 20 (200 plasma at max burn)
Fireball: 50 -> 300
Firestorm: 50 -> 300
Inferno: 50 -> 125
Infernal Trigger: 40 -> 100
Pyrogen is very good at spamming down a chokepoint forever, and is currently able to use every ability the second they are off cooldown _without ever running out of plasma_ while on weeds.
Giving pyrogen higher plasma costs and alternative ways to restore plasma should encourage …

Rebalances pyrogen plasma
