tgstation/TerraGov-Marine-Corps

- code/modules/admin/admin_verbs.dm
Reverts the code to an ugly hack because of how areas work.
> Jump to Area ugly hack

- code/game/objects/items/storage/toolbox.dm
> Toolboxes New to Initialize

- code/game/objects/effects/weeds.dm
- code/modules/atmospherics/machinery/components/components_base.dm
I think that this is the proper way to go, otherwise we are going to keep finding more and more things breaking with planes.
Fixes: #1819
Fixes: #2087
> Fixes vent and weed layer issues.

- README.md
Badges will be pretty now since markdown requires a blank line to separate which me stupid brain didn't know.
> Aligns the readme a bit better

- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
- code/__DEFINES/components.dm
- code/__HELPERS/unsorted.dm
- code/datums/gamemodes/game_mode.dm
- code/game/objects/machinery/door_control.dm
- code/game/objects/machinery/doors/poddoor.dm
- code/game/objects/machinery/doors/shutters.dm
> Refactors Prison timed poddor locks

- code/modules/projectiles/updated_projectiles/guns/smgs.dm
:cl:
balance: rebalanced the GAL9
/:cl:
> Balance changes to the GAL9

- code/__DEFINES/mobs.dm
Reduces damage from body temp changes by 50%
Fire sucks for everyone, let people tank it a little harder.
:cl:
balance: Damage from body temperature has been halfed.
/:cl:
> Reduces body temp damage for humans

- code/modules/shuttle/on_move.dm
> Fix shuttle gibbing

- code/modules/admin/admin_verbs.dm
- code/modules/admin/holder.dm
The previous solution was introducing some unnecessary code for what was my oversight in the first place.
> Cleaner fix for area jumping.

- code/controllers/stonedmc/subsystem/job.dm
- code/datums/emergency_calls/clf.dm
- code/datums/emergency_calls/colonists.dm
- code/datums/emergency_calls/deathsquad.dm
- code/datums/emergency_calls/freelancers.dm
- code/datums/emergency_calls/imperium.dm
- code/datums/emergency_calls/pizza.dm
- code/datums/emergency_calls/pmc.dm
- code/datums/emergency_calls/sonsofmars.dm
- code/datums/emergency_calls/upp.dm
- code/datums/emergency_calls/upp_commando.dm
- code/datums/gamemodes/distress.dm
- code/datums/gamemodes/game_mode.dm
- code/datums/jobs/job/job.dm
- code/datums/jobs/job/shipside.dm
- code/modules/admin/fun_verbs.dm
- code/modules/admin/topic.dm
- code/modules/mob/living/carbon/human/human.dm
Thanks to @psykzz  for helping fix the Synth camera issue.
Fixes: #2065
Closes: #2108 
Fixes: #2085
> Fixes some job and rank quirkiness

- code/datums/mind.dm
It's not a proper admin tool which is why it was forgotten here.
> Removes unused mind panel.,

- code/controllers/stonedmc/subsystem/chat.dm
- goon/code/datums/browserOutput.dm
> Chat no longer lags during server init.

- code/datums/jobs/squads.dm
- code/game/objects/machinery/overwatch.dm
- code/game/say.dm
> Fixes aSL's

- code/__DEFINES/components.dm
- code/_onclick/item_attack.dm
- code/game/objects/items/storage/backpack.dm
- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/mob/living/carbon/human/human_helpers.dm
- code/modules/projectiles/updated_projectiles/gun_system.dm
converts scout cloak to use signals
:cl:
fix: fixed a bug that allowed a cloak scout to use a melee weapon without shimmering
/:cl:
> Scout cloak signals

- code/modules/admin/server_verbs.dm
- config/config.txt
> Removes removed config, locally restarting is now better

- code/modules/power/apc.dm
- code/modules/power/terminal.dm
Fixes: #1977
Fixes: #1983
Fixes: #1997
> Fixes most APC issues

- code/controllers/stonedmc/subsystem/ticker.dm
A little bit dirty but still the cleanest solution we have until someone starts developing this again.
> Fixes TGS pinging people on graceful shutdown

- .travis.yml
- tools/travis/check_filedirs.sh
> Revert Lintenfixes

- code/_globalvars/lists/client.dm
- code/_onclick/click.dm
- code/_onclick/drag_drop.dm
- code/modules/client/client_defines.dm
- code/modules/client/client_procs.dm
> [s] Fixes the middleclick mouse drag exploit

- code/modules/admin/admin_verbs.dm
> Fixes admin jump

- code/__HELPERS/global_lists.dm
Fixes these 2 runtimes because these are just types and not meant to be initialized.
> Fixes init runtime with keybindings

- code/game/objects/items/scanners.dm
Humans/carbons couldn't be scanned unless they were synths.
> Health scanner fix

- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> Adds a "Cancel" option to back down when given the choice to select a possible larva spawn point

- code/_globalvars/lists/mapping.dm
- code/controllers/stonedmc/subsystem/mapping.dm
- code/datums/map_config.dm
Noticed these during the other PR, atomizing for clarity.
> Removes unimplemented mapping lists and variables

- _maps/WIP/Z.01.Desert-Dam.dmm
- _maps/map_files/BigRed_v2/BigRed_v2.dmm
- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
- _maps/map_files/LV624/LV624.dmm
- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
- _maps/map_files/Sulaco/Sulaco.dmm
- _maps/map_files/Theseus/TGS_Theseus.dmm
- _maps/map_files/debugdalus/tgs_debugdalus.dmm
- code/modules/shuttle/computer.dm
- code/modules/shuttle/marine_dropship.dm
> Fixes dropship consoles

- code/modules/shuttle/marine_dropship.dm
> Fixes shuttle lights breaking too early

- _maps/WIP/Z.01.Desert-Dam.dmm
- _maps/map_files/BigRed_v2/BigRed_v2.dmm
- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
- _maps/map_files/LV624/LV624.dmm
- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
- _maps/map_files/Theseus/TGS_Theseus.dmm
- code/game/objects/items/toys/toys.dm
> Fixes maps having holodeck items in them

- code/modules/admin/panels/note_panel.dm
So minor I won't even bother describing it. I'm not even going to tag this as a fix. That's how minor it is.
Fixes: #2150
> Fixes an extremely minor visual text issue

- goon/browserassets/css/browserOutput.css
It was like twice bigger than a command headset, queen is command headset size now and shrike is slightly less, yet still more than regular text.
:cl: LaKiller8
tweak: Hivemind size should now be more comparable to marine radio comms, also removed the italics.
/:cl:
> Hivemind visual tweaks

- code/datums/gamemodes/game_mode.dm
Mind transfers are always fun.
> Fixes some EORD runtimes

- _maps/shuttles/alamo.dmm
- code/game/objects/machinery/telecomms/machines/relay.dm
> Fixes transit alamo comms

- code/_onclick/adjacent.dm
Ends a long quest in search of the elusive `nullspace`. We believe with the facts brought forward to the scientific community we can attest beyond reason of doubt about this place being a mere legend.
> Adds a null loc check in item Adjacent()

- _maps/map_files/BigRed_v2/BigRed_v2.dmm
- code/datums/datacore.dm
- code/game/objects/items/gift_wrappaper.dm
- code/game/objects/machinery/computer/security.dm
- code/game/objects/machinery/newscaster.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/living.dm
- code/modules/mob/mob.dm
- code/modules/paperwork/paper_bundle.dm
- code/modules/paperwork/photocopier.dm
- code/modules/paperwork/photography.dm
Should fix most issues related to photo code
> A slight photo refactor

- code/datums/emergency_calls/emergency_call.dm
- code/datums/jobs/squads.dm
- code/game/objects/machinery/overwatch.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/living_verbs.dm
Fixes: #2165
3AM PR hopefully won't break shit please be gentle
> Fixes some more mind dirtyness

- code/modules/shuttle/marine_dropship.dm
:cl: LaKiller8
balance: The queen can now override the planetside shuttle lockdown if all doors are locked after 60 seconds of standing still.
/:cl:
> Allows the queen to override shuttle lockdown

- code/modules/shuttle/marine_dropship.dm
> Fixes dropship interface visual issue

- code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
I would explain how it works but it's 2AM please forgive me. Just trust me that it does.
> Fixes the freakin' smoke runtimes for real

- code/controllers/subsystem/ticker.dm
- code/controllers/subsystem/vote.dm
- code/game/world.dm
- code/modules/tgs/core/datum.dm
- code/modules/tgs/v3210/api.dm
- code/modules/tgs/v4/api.dm
Fuck me can't test this shit locally
> Hopefully fixes the reboot issues

- code/game/objects/items/storage/backpack.dm
> Fixes a scout cloak issue

- code/datums/jobs/job/shipside.dm
:cl:
balance: Removes the roundstart tanker jobs until the old tank is decommissioned and sold for scrap and we implement the new vehicles.
/:cl:
> No more tankers

- code/game/objects/items/defibrillator.dm
Micro cleanup. Started it because of #2184 but then saw the issue was a bit deeper.
> get_ghost() cleanup

- code/__DEFINES/conflict.dm
- code/__DEFINES/objects.dm
- code/game/objects/items/stacks/stack.dm
- code/game/objects/items/weapons/weapon.dm
- code/game/objects/structures/supplypod.dm
- code/game/objects/structures/xeno.dm
- code/modules/admin/verbs/podlauncher.dm
- code/modules/mob/living/carbon/xenomorph/update_icons.dm
split from #2171 by request of @Rohesie
> move macros

- code/_onclick/hud/fullscreen.dm
- code/modules/mob/living/carbon/life.dm
- code/modules/mob/living/status_procs.dm
Per title. Port of https://github.com/tgstation/tgstation/pull/41759
:cl:
add: Eye blur effect now uses byond's filters.
/:cl:
> Replaces eye blur effect with real one

- _maps/debugdalus.json
> Fixes debugdalus traits

- code/__DEFINES/components.dm
- code/modules/mob/living/carbon/xenomorph/attack_alien.dm
- code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
- code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
- code/modules/mob/living/carbon/xenomorph/damage_procs.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
> Signals Episode 7 The Signals Awaken

- code/game/objects/explosion.dm
This one is one me :c
Fixes: #2093
> Fixes explosions not working

- code/modules/client/preferences.dm
This is the only place that could have realistically been causing this, leave it up for ~2 days, if it doesn't reappear, merge it.
> Hopefully fixes the pref saving bad output runtime

- code/__DEFINES/atom_hud.dm
- code/datums/atom_hud.dm
- code/datums/jobs/job/job.dm
- code/game/data_huds.dm
- code/game/objects/items/storage/backpack.dm
- code/modules/clothing/outfits/vv_outfit.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/inventory.dm
- code/modules/mob/living/carbon/inventory.dm
- code/modules/mob/living/living.dm
:cl:
del: Now that the jobs display are handled by the squad HUD, the security one for jobs is removed. SecHUDs still allow to set people as wanted statuses and whatnot.
/:cl:
> Sechud jobs begone

- code/game/objects/machinery/teleporter.dm
there was no user being passed
> Fixes teleporter attack_hand runtime

- code/datums/gamemodes/game_mode.dm
No loc means runtime on login. This just changes the order.
> Fixes EORD ghost runtimes

- code/datums/jobs/squads.dm
- code/game/objects/machinery/overwatch.dm
> Fixes  ASL radio for real

- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> Feedback for joining as larva.

- code/modules/reagents/Chemistry-Machinery.dm
Due to the visit of a user trying to do href exploits last test, decided to expand a bit on the logging of things the person tried to abuse and didn't already warn the admins, besides one more here and there.
> [s] Href exploit checks

- code/game/objects/items/storage/storage.dm
> A different medkit size fix

- code/__DEFINES/layers.dm
- code/game/objects/machinery/computer/camera_advanced.dm
> Fixes AI eye layer to be above all the things

- code/__DEFINES/layers.dm
- code/game/objects/machinery/computer/camera_advanced.dm
This reverts commit a031bf5fe062e9fcfabedcab3b56fbc0e5f95ca4.
This PR shouldn't have been merged. The questions weren't answered.
> Revert "Fixes AI eye layer to be above all the things (#2110)"

- code/modules/admin/fun_verbs.dm
> revert this change pushed to wrong branch before merge

- code/modules/admin/fun_verbs.dm
The first menu was scary, making admins think it can't be cancelled, the intant move should be asked last.
> Force dropship usability changes

- code/modules/projectiles/updated_projectiles/guns/flamer.dm
Holy shit how did NOONE notice this huge oversight for so long (myself included)
> Makes fire work properly

- code/modules/admin/debug_verbs.dm
@Roh if you come up with a better title feel free to change this I wasn't feeling very creative
> Slight debug verb improvement

- code/__DEFINES/mobs.dm
- code/_globalvars/bitfields.dm
- code/game/objects/items/explosives/grenades/flashbang.dm
- code/game/objects/items/flashlight.dm
- code/game/objects/machinery.dm
- code/game/objects/machinery/autodoc.dm
- code/modules/mob/living/carbon/carbon_defines.dm
- code/modules/mob/living/carbon/human/human_helpers.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/carbon/human/life/handle_breath.dm
- code/modules/mob/living/carbon/human/life/handle_disabilities.dm
- code/modules/mob/living/carbon/human/life/handle_fire.dm
- code/modules/mob/living/carbon/human/life/handle_grabbed.dm
- code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
- code/modules/mob/living/carbon/human/life/handle_organs.dm
- code/modules/mob/living/carbon/human/life/handle_pulse.dm
- code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
- code/modules/mob/living/carbon/human/life/handle_status_effects.dm
- code/modules/mob/living/carbon/life.dm
- code/modules/mob/living/carbon/monkey/life.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/living_health_procs.dm
- code/modules/mob/living/living_helpers.dm
- code/modules/mob/living/status_procs.dm
- code/modules/reagents/chemistry_reagents/medical.dm
- code/modules/surgery/eye.dm
> Life() cleanup and microoptimizations

- code/modules/admin/fun_verbs.dm
> Fixes the release object verb

- code/controllers/subsystem/ticker.dm
- code/game/objects/explosion.dm
- code/modules/admin/server_verbs.dm
You can now force a roundstart easier, also fixed an issue with the condition checking
> Admin round-start tweaks

- code/modules/admin/fun_verbs.dm
- code/modules/mob/camera/imaginary_friend.dm
The message should only display once now, they should be less hacky.
> Imaginary friend fixes

- code/game/blood.dm
> Fixes blood overlay issues

- code/game/objects/structures/stool_bed_chair_nest/chairs.dm
- code/game/objects/structures/watercloset.dm
- code/game/objects/structures/windoor_assembly.dm
- code/game/turfs/walls/walls.dm
I should just regex for the fourth argument being a number but I gotta learn regex better first
> Another do_after runtimes

- code/modules/client/preferences_toggles.dm
- code/modules/mob/camera/imaginary_friend.dm
- code/modules/mob/living/carbon/human/death.dm
- code/modules/mob/logout.dm
- code/modules/mob/mob_defines.dm
- code/modules/mob/typing_indicator.dm
Should help with stuff
Fixes: #2238
Fixes: #2288
> Typing indicator fixes

- code/datums/gamemodes/distress.dm
> Fixes roundstart bioscans showing location

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
> Fixes the Ice Colony landing zones

- code/modules/mob/living/carbon/human/human.dm
> Fixes pocket equip issues

- nano/templates/chem_dispenser.tmpl
> Fixes a space in chem dispenser

- code/game/objects/machinery/cryopod.dm
Like three associated with it since user was null
> Fixes AI cryo runtime

- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/dead/observer/login.dm
- code/modules/mob/dead/observer/observer.dm
> Adds a preference for observer actions

- code/controllers/subsystem/ticker.dm
- code/modules/admin/fun_verbs.dm
- code/modules/admin/holder.dm
Also fixed da code.
Fixes: #2237
> Allows admins to set a custom tip of the round

- config/config.txt
Unknown setting in configuration: 'guest_jobban'
> Removes removed config.txt entry

- code/modules/client/preferences_savefile.dm
Ask Psy as for why it's necessary in case it's not clear.
> Fixes keybinding prefs for players who played here previously

- code/datums/gamemodes/distress.dm
:cl: LaKiller8
tweak: Each side now gets the relevant round-end sound according to whether they won or lost, with 
roundstart observers getting some special fun ones.
/:cl:
> Adds faction based roundend sounds

- code/game/objects/items/reagent_containers/food/snacks.dm
This allows you again to cut pizza with a knife when not on HELP intent.
> Fixes pizza

- code/game/objects/items/toys/toys.dm
> Fixes xeno basketball being enabled by default

- code/modules/mob/dead/observer/observer.dm
We don't have atmos anyway, anyway can see what space is and does.
This will make the follow buttons line up much nicer.
> Removes the "Analyze Air" observer button

- code/game/turfs/floor.dm
> Fixes being unable to remove broken plating

- code/game/objects/structures/window.dm
Small bug, you could pass through certain windows. This was my doing.
> Window canpass fix

- code/game/objects/machinery/computer/communications.dm
Add human / xeno count to distress beacons for admins
Helps making decisions
> Add human / xeno count to distress beacons for admins

- code/modules/projectiles/updated_projectiles/guns/specialist.dm
Like every gun now has ammo counter, cmon.
:cl:
tweak: Added ammo counter to most spec weapons and grenade launchers.
/:cl:
> Adds ammo counters to most spec weapons and launchers

- code/game/objects/items/tools/mining_tools.dm
> Fixes plasmacutter battery removal

- code/modules/bsql/core/library.dm
Credit to PJB in the coderbus Discord
> Fixes BSQL on linux

- _maps/map_files/BigRed_v2/BigRed_v2.dmm
No ground maps are supposed to have cameras at the moment, forgot about this one in the AI port.
> Removes Big Red cameras

- code/game/objects/machinery/bots/mulebot.dm
- code/game/objects/structures/stool_bed_chair_nest/chairs.dm
- code/game/verbs/atom_verbs.dm
- code/modules/mob/living/living.dm
- code/modules/vehicles/cargo_train.dm
- tgmc.dme
> Fixes ghost pulling

- code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
- code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
> Fixes elite drones and carriers

- code/datums/components/squeak.dm
> Fixes observer crossed mouse squeaking

- code/game/objects/structures/window.dm
> Fixes simple window deconstruction

- code/modules/mob/login.dm
This will still runtime but at least it won't break the server
> Fixes a null in player list if the player disconnects at a bad time

- code/game/objects/machinery/doors/firedoor.dm
Way too spammy for zero benefit.
> Removes emergency shutter admin message

- code/controllers/subsystem/server_maint.dm
Yes they shouldnt happen
But this is still logged, and if it does, at least the rest of the game wont be fucked up in major ways
> Adds additional null protection from /tg/

- code/controllers/subsystem/ticker.dm
- code/modules/tgs/core/datum.dm
- code/modules/tgs/v3210/api.dm
- code/modules/tgs/v4/api.dm
Tested on the server, works fine.
> Fixes graceful shutdown pinging for real

- code/modules/admin/verbs/adminhelp.dm
> Fixes ahelp spelling error

- code/datums/jobs/access.dm
> Fixes a slight access issue

- code/modules/mob/living/carbon/xenomorph/abilities.dm
> Fixes xeno spit cost

- code/__HELPERS/global_lists.dm
- code/__HELPERS/mobs.dm
- code/datums/emergency_calls/clf.dm
- code/datums/emergency_calls/freelancers.dm
- code/datums/emergency_calls/imperium.dm
- code/datums/emergency_calls/pmc.dm
- code/datums/emergency_calls/sonsofmars.dm
- code/datums/emergency_calls/upp.dm
- code/datums/emergency_calls/upp_commando.dm
- code/datums/namepool.dm
- code/game/objects/machinery/computer/medical.dm
- code/game/objects/machinery/computer/security.dm
- code/game/objects/machinery/computer/skills.dm
- code/modules/client/preferences_savefile.dm
- code/modules/language/language.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species.dm
- tgmc.dme
old code had a lot of code duplication and unneeded capitalize() calls
> Improves random name code

- code/game/objects/items/storage/backpack.dm
- code/game/objects/items/tools/mining_tools.dm
- code/game/objects/items/weapons/stunbaton.dm
- code/game/objects/machinery/bots/mulebot.dm
- code/game/objects/machinery/cell_charger.dm
- code/game/objects/machinery/floodlight.dm
- code/game/objects/machinery/spaceheater.dm
- code/modules/power/apc.dm
- code/modules/power/cell.dm
- code/modules/projectiles/updated_projectiles/magazines/energy.dm
> Fixes cells icon updating

- code/_globalvars/misc.dm
- code/game/objects/machinery/computer/camera_advanced.dm
/tg/ still has this problem so someone can port it there
Fixes: #2346
> Fixes overwatch eye layer issues

- code/game/objects/structures/crates_lockers/crates.dm
- code/game/objects/structures/crates_lockers/largecrate.dm
- code/modules/vehicles/powerloader.dm
Fixes #2383 
Cleans up code a tiny bit.
> Fixes powerloader clamp issues

- code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
> Fixes queens losing strong acid when going into ovi mode.

- code/__DEFINES/is_helpers.dm
- code/modules/mob/living/carbon/human/human_status_procs.dm
> Fixes synthetic blind and deafness issues

- code/game/objects/structures/crates_lockers/largecrate.dm
> Fixes largecrate issues

- code/__DEFINES/components.dm
- code/controllers/subsystem/vote.dm
> global signal for vote button

- code/controllers/subsystem/input.dm
- code/datums/keybinding/client.dm
- code/datums/keybinding/mob.dm
- code/game/verbs/ooc.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/keybindings/bindings_client.dm
- code/modules/keybindings/setup.dm
Tested locally, Psy said most of this is done via keybindings so there's no reason to keep this code around as it only makes stuff confusing.
Fixes: #2399
> Clarifies the hotkey preference name, removes obsolete SSinput things

- code/modules/shuttle/marine_dropship.dm
> Fixes a queen calldown issue

- code/modules/mob/living/carbon/human/human.dm
> Fixes some light slashing issues

- code/_onclick/ai.dm
- code/modules/mob/living/silicon/ai/ai.dm
> Fixes AI zlevel interactions

- code/modules/mob/living/carbon/human/human_attackhand.dm
> Fixes tinglingblistered

- code/game/objects/machinery/fusion_engine.dm
> Fixes fuel engine interaction

- _maps/map_files/Theseus/TGS_Theseus.dmm
> Adds light to the AI chamber

- code/controllers/subsystem/direction.dm
- code/controllers/subsystem/job.dm
- code/datums/jobs/squads.dm
- code/game/objects/machinery/cryopod.dm
- code/game/objects/machinery/overwatch.dm
- code/modules/mob/living/carbon/human/human.dm
> Fixes a ton of squad issues

- code/modules/projectiles/updated_projectiles/guns/specialist.dm
- code/modules/projectiles/updated_projectiles/magazines/pistols.dm
- code/modules/projectiles/updated_projectiles/magazines/smgs.dm
Fixes the issue of M42A rounds ejected from the rifle being unable to be put back into the magazine. 
It fixes a bug, as outlined in #2194
> Weapon/Magazine Caliber Fix

- code/game/objects/objs.dm
Removes an unnecessary check. Trivial.
> Unbuckle check.

- code/__DEFINES/is_helpers.dm
- code/_globalvars/lists/mobs.dm
- code/modules/mob/living/carbon/xenomorph/evolution.dm
:cl:
balance: Xenos gained the ability to regress back into lower tier stages, even back into larvas.
/:cl:
This should make losing rulers easier to deal with, besides allowing for higher hive versatility.
> Regress xeno ability

- code/modules/admin/server_verbs.dm
> Adds a missing line to the round end delay verb

- _maps/map_files/BigRed_v2/BigRed_v2.dmm
- _maps/map_files/LV624/LV624.dmm
- code/game/objects/structures/barricade.dm
It should've been deleted long time ago in first place.
> Removes LV wooden barricade snowflake variant

- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
> Fixes prison power issues

- code/__DEFINES/callbacks.dm
- code/datums/callback.dm
- code/game/objects/effects/effect_system/effect_system.dm
- code/game/objects/effects/effect_system/explosions.dm
- code/game/objects/explosion.dm
- code/modules/organs/limbs.dm
mostly to remove spawn() calls and remove some duplicate code, functionality should be exactly the same, please no change requests to change functionality.  definitely point out anything that changes functionality as it is unintended.
Fixes #2412
> Effects refactor

- code/modules/admin/panels/permission_panel.dm
- code/modules/admin/panels/player_panel.dm
- code/modules/admin/topic.dm
> Changing the admin rank via PP no longer reopens the permission panel

- code/game/objects/items/reagent_containers/food/snacks.dm
> Fixes pizza issues

- code/modules/keybindings/bindings_client.dm
> Fixes focus chat mode

- code/game/turfs/floor_ground.dm
- code/game/turfs/open_ground.dm
> Fixes turf destruction issues

- code/modules/mob/living/carbon/human/human.dm
Synths just love being blind and deaf
> More dirty ear damage modifications

- code/datums/jobs/job/marines.dm
> Fixes latejoin squad leader

- code/game/objects/machinery/computer/camera_advanced.dm
> Overwatch camera can now see through walls(if there's coverage)

- code/modules/projectiles/updated_projectiles/projectile.dm
:cl:
balance: Warding nerfed. Instead of being able to reduce damage up to 12.5%, it can only go up to 5%.
/:cl:
> Warding nerf.

- code/_globalvars/lists/objects.dm
- code/controllers/subsystem/lighting.dm
- code/controllers/subsystem/machines.dm
- code/datums/datacore.dm
- code/game/area/area.dm
- code/game/objects/machinery/computer/medical.dm
- code/game/objects/machinery/computer/security.dm
- code/game/objects/machinery/computer/skills.dm
- code/game/objects/machinery/computer/station_alert.dm
Who thought it could be so simple?
> Reduces roundstart lag

- code/game/objects/items/stacks/stack.dm
> No more xeno bob the builders

- code/controllers/subsystem/atoms.dm
- code/controllers/subsystem/overlays.dm
- code/game/world.dm
- code/modules/client/client_procs.dm
So this is why stuff wasn't working properly.
> Fixes some asset and MC shenanigans

- code/game/atoms.dm
- code/game/atoms_movable.dm
- code/game/objects/items/cards_ids.dm
- code/game/objects/objs.dm
- code/game/turfs/turf.dm
- code/modules/admin/holder.dm
- code/modules/client/client_procs.dm
- code/modules/mob/living/living.dm
This should prevent breaking stuff and be a nice admin QoL
> Adds more VV helpers

- code/_onclick/ai.dm
> Fixes more AI click interactions

- code/__DEFINES/is_helpers.dm
- code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
The ability can only be used when there are burrowed larvas available.
> Less call of the burrowed spam.

- code/game/objects/machinery/fusion_engine.dm
> Fixes fusion engine cell issue

- code/game/objects/machinery/computer/camera_advanced.dm
- code/modules/mob/living/silicon/ai/freelook/cameranet.dm
- code/modules/mob/mob.dm
This may or may not help. We'll see.
> Cameranet tweaks

- code/__DEFINES/spaceman_dmm.dm
- code/controllers/globals.dm
- code/datums/actions/action.dm
- code/datums/datum.dm
- code/datums/weakrefs.dm
- code/modules/client/client_procs.dm
- code/modules/projectiles/updated_projectiles/guns/specialist.dm
- tgmc.dme
https://github.com/tgstation/tgstation/pull/45188
> Ports SHOULD_CALL_PARENT from /tg/

- code/modules/mob/living/carbon/human/species.dm
> Synths can scream again

- code/game/say.dm
- code/modules/mob/living/silicon/ai/say.dm
It's not /tg/ but it sure is a hella lot cleaner
> Slightly condenses the AI tracking href

- code/datums/mind.dm
- code/modules/admin/holder.dm
- code/modules/client/client_procs.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/mob/living/carbon/human/login.dm
- code/modules/mob/living/carbon/human/logout.dm
- code/modules/mob/living/carbon/xenomorph/logout.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/login.dm
- tgmc.dme
> Adds admin notification for people who DC'd after 15 minutes

- code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
:cl: LaKiller8
qol: Call of the burrowed now tries to spawn observers first, by their time of death like other methods to do get xeno.
/:cl:
> Call of the burrowed now tries to spawn observers first

- code/__DEFINES/admin.dm
- code/modules/client/client_defines.dm
- code/modules/client/client_procs.dm
- code/modules/mob/say.dm
> Reworks the automute system add a message weight option

- code/_onclick/hud/human.dm
- interface/skin.dmf
Hotkeys verb dont exist, plus that should be capitalized
> Fixes 2 slight interface issues

- code/datums/browser.dm
- code/game/objects/items/radio/radio.dm
- code/game/objects/machinery/adv_med.dm
- code/game/objects/machinery/autodoc.dm
- code/game/objects/machinery/bots/mulebot.dm
- code/game/objects/machinery/computer/Operating.dm
- code/game/objects/machinery/computer/atmos_alert.dm
- code/game/objects/machinery/computer/crew.dm
- code/game/objects/machinery/doors/airlock.dm
- code/game/objects/machinery/navbeacon.dm
- code/game/objects/machinery/spaceheater.dm
- code/game/objects/objs.dm
- code/modules/power/apc.dm
- code/modules/power/generator.dm
- code/modules/power/generator_type2.dm
- code/modules/power/power_monitor.dm
- code/modules/recycling/disposal.dm
Also had to do a slight interface update cleanup since such a tiny change made me find quite a few issues.
Removed updateDialog since it was redundant.
Mass replaced all occurences with updateUsrDialog
Neither of those can nor should be used in process due to the way interface interaction works, and hacking it together is not really feasible. Interfaces that want to update constantly should be using nanoUI instead.
> Allows the AI to use the autodoc

- code/modules/admin/debug_verbs.dm
- code/modules/admin/holder.dm
Will make testing locally easier
> Adds an easy spatial agent verb

- code/game/objects/items/storage/backpack.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/suits/armor.dm
- code/modules/clothing/under/under.dm
:cl: LaKiller8
balance: You can now equip the spec cloak with any armor.
/:cl:
Otherwise nothing should change behavior-wise, the restricted stuff is heavily flawed and would essentially require a n^2 loop to do properly.
FIxes: #2519
> Clothing restriction changes

- code/modules/admin/admin_verbs.dm
> Fixes give mob mind issues

- code/controllers/subsystem/vote.dm
> Cancelling a vote is now a popup

- code/modules/admin/verbs/podlauncher.dm
> Fixes a pod runtime for human users

- code/game/objects/structures/tables_racks.dm
> Fixes rack deletion issues

- code/modules/admin/topic.dm
The other ones dont work anyway for other species
> Admins now only see valid hairstyles in the apearance menu

- code/game/turfs/walls/wall_types.dm
> Fixes resin wall cutting

- _maps/map_files/LV624/LV624.dmm
> Fixes LV orientation issues

- code/modules/clothing/head/helmet.dm
Increases the max storage space of helmets to 4.
Two flasks can fit. Also two of whatever other small items that the helmet allows.
:cl:
balance: Two flasks should be able to fit in helmets now.
/:cl:
> Increases helmet max storage to 4

- code/modules/mob/living/carbon/life.dm
- code/modules/mob/mob_helpers.dm
When you are unconscious, you won't hear any sounds. When you exit the state, your hearing shall be back
Only natural for a person to not be able to hear while he's unconscious
:cl:
tweak: toggles deaf when unconscious
/:cl:
> Makes you deaf while unconscious

- code/game/atoms_movable.dm
- code/modules/language/language_holder.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/monkey/monkey.dm
:cl: LaKiller8
tweak: Synths can now understand xenos, but can't speak with them.
/:cl:
> Synths can now understand xenos (but can't speak xeno)

- code/game/objects/machinery.dm
- code/game/objects/structures.dm
Fixes: #2359
This may need more testing since it can break stuff, but we should move towards doing it this way in the future rather than combining the two checks.
> Fixes plasmacutter interactions

- code/modules/mob/living/simple_animal/friendly/corgi.dm
> Removes extra space from Mr. Wiggles

- code/modules/mob/living/carbon/xenomorph/life.dm
If no candidate gets chosen it gets bugged.
> Fixes xeno AFK timer issue

- code/modules/client/client_procs.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
:cl: LaKiller8
tweak: Added the much-wanted clientside FPS preference.
/:cl:
> Adds a client FPS preference

- code/game/objects/structures/flora.dm
- code/modules/reagents/chemistry_reagents/alcohol.dm
> Fixes trees being gin in the codex

- code/game/verbs/ooc.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/holder.dm
- code/modules/admin/verbs/pray.dm
> Links in OOC are now clickable

- code/modules/client/asset_cache.dm
- code/modules/client/client_defines.dm
- code/modules/codex/codex_client.dm
- code/modules/keybindings/focus.dm
- code/modules/mob/living/blood.dm
- code/modules/mob/living/carbon/carbon_defines.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/mob_defines.dm
- code/modules/mob/taste.dm
I keep promising myself I'll do that, but I'm usually doing something else that would require stopping.
> Moves variable definitions to their path definition files

- goon/code/datums/browserOutput.dm
No longer you will have to enter an empty space to reset it
> CSS QoL tweak

- code/datums/jobs/job/job_exp.dm
Admins fucking around may not have a mind, and this proc shouldn't fail because of it.
> Fixes job experience runtime

- code/modules/client/preferences.dm
Fixes runtime with empty keybindings
> Fixes runtime with empty keybindings

- code/modules/client/asset_cache.dm
> Fixes pencode tmgc logo

- _maps/shuttles/tgs_canterbury.dmm
These should've been added, but we forgot
> Add two advanced pinpointers to the Canterbury

- _maps/shuttles/tgs_canterbury.dmm
Replaces a random station alert console with a glorious fax machine
> Replaces a random station alert console with a glorious fax machine

- code/game/objects/items/binoculars.dm
Gives binoculars nightvision
Kinda required for CAS to be effective.
:cl:
balance: tactical binoculars allow you to see in the dark
/:cl:
> Gives binoculars nightvision

- code/game/objects/effects/landmarks/corpsespawner.dm
- code/game/objects/items/bodybag.dm
> Fixes bodybag body handling

- code/modules/admin/fun_verbs.dm
> Makes the custom info verb better to use

- code/modules/mob/living/carbon/xenomorph/life.dm
This happens when you yeetus deletus yourself as a xeno as an admin
> Fixes xeno takeover issue

- code/datums/jobs/job/shipside.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/living/silicon/ai/ai_verbs.dm
:cl: LaKiller8
tweak: You can now change your AI name, remember to follow the rules folks!
/:cl:
> Adds an AI name preference and a shutdown verb

- code/modules/mob/dead/observer/observer.dm
Thanks stranger for reporting this
> You can no longer claim any mob

- code/controllers/subsystem/vote.dm
> Admins can now start votes without toggling them for everyone

- _maps/map_files/LV624/LV624.dmm
The other unrelated changes are because someone didn't mapmerge properly so it didn't do the automatic turf cleanup
> Fixes LV shutter orientation issues

- code/game/objects/structures/tables_racks.dm
> Fixes rack climbing

- code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
> Praetorians can no longer spray through poddoors

- code/modules/organs/limbs.dm
> Fixes decapitation ghost hair

- code/game/objects/machinery/computer/camera_advanced.dm
- code/game/objects/machinery/overwatch.dm
> Adds camera tracking to the overwatch console

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
> Fixes simple animal emotes

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
- _maps/map_files/Theseus/TGS_Theseus.dmm
- _maps/map_files/debugdalus/tgs_debugdalus.dmm
TC is disabled anyway and right now Synth and FC/Cap can use it
> Temporarily removes the tank

- code/datums/jobs/job/shipside.dm
> Fixes Staff Officer comms title

- code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Approved by Rohesie
:cl: LaKiller8
balance: Queen larval growth has been removed.
/:cl:
> Removes queen larval growth

- code/modules/admin/fun_verbs.dm
- code/modules/admin/holder.dm
- code/modules/admin/topic.dm
> Adds xeno panel for the admemes

- code/__HELPERS/text.dm
- code/datums/jobs/job/job.dm
- code/datums/jobs/job/shipside.dm
- code/modules/admin/topic.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
> Fixes a few small oof with AI names

- code/datums/jobs/squads.dm
> Fixes common channel after marine transfers

- code/_onclick/hud/plane_master.dm
- code/game/objects/effects/decals/decal.dm
- code/game/objects/effects/weeds.dm
- code/game/objects/machinery/igniter.dm
- code/game/objects/structures/lattice.dm
- code/game/turfs/closed.dm
- code/game/turfs/open_ground.dm
- code/game/turfs/plating.dm
- code/modules/atmospherics/machinery/components/components_base.dm
- code/modules/atmospherics/machinery/pipes/pipes.dm
- code/modules/atmospherics/machinery/pipes/simple.dm
- code/modules/power/cable.dm
- code/modules/recycling/disposal.dm
- tgmc.dme
Keep this testmerged for a while, may cause some visual weirdness.
> Adds ambient occlusion

- code/game/objects/machinery/vending/new_marine_vendors.dm
Boot knives now come with marine essential sets.
It makes everyone's life easier.
:cl:
add: Marine essential clothing sets now come with a boot knife included.
/:cl:
> Adds a boot knife to basic marine sets.

- code/game/verbs/ooc.dm
- code/modules/mob/typing_indicator.dm
> Makes the input wrappers look like verbs

- code/modules/admin/verbs/adminhelp.dm
> Ahelp marking now displays properly

- code/datums/emergency_calls/pizza.dm
Roh wanted this
:cl: LaKiller8
tweak: The pizza ERT is now admin only.
/:cl:
> Makes the pizza ERT admin only

- code/game/objects/items/binoculars.dm
> Fixes binoculars vision focusing

- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
> Fixes prison station cheesing LZ vents

- code/game/objects/machinery/autodoc.dm
The console may have gotten destroyed
> Fixes a few autodoc runtimes

- code/modules/client/preferences_savefile.dm
Roh please title this better I literally can't at the moment
> 15 Changes To savefile_version That Will Surprise You

- code/datums/jobs/job/shipside.dm
> Fixes the AI name on latejoin

- code/game/objects/structures/watercloset.dm
> Fixes bucket overfilling

- code/game/objects/structures/watercloset.dm
> Fixes floating sinks

- code/datums/gamemodes/extended.dm
No more infinite rounds without admins!
> Makes extended unvoteable

- code/datums/keybinding/mob.dm
- code/modules/mob/mob_movement.dm
- code/modules/mob/mob_verbs.dm
> Makes some object mob verbs living instead

- code/datums/gamemodes/crash.dm
Sites were not random, because i did a name match on the list, effectively getting the first item.
> Fix crash spawn sites for Canterbury

- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Fixes an issue where the shrike would not be able to track a queen because its intelligent.
> Shrike can now track a queen

- code/game/objects/items/tools/cleaning_tools.dm
> Fixes soap attacking

- _maps/map_files/BigRed_v2/BigRed_v2.dmm
> Removes big red pipe cheesing

- code/modules/mob/mob.dm
- html/templates/header.html
> Makes changelog less laggy

- code/game/objects/structures/watercloset.dm
> Fixes washing grabs

- code/game/objects/machinery/nuclearbomb.dm
> Add ghost alert for the nuke

- .github/CODEOWNERS
> Add psykzz as codeowner for gamemodes

- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> Fixes an issue with xeno ghosting

- code/modules/admin/verbs/varedit.dm
> Allows mass varediting of bitfields

- code/modules/shuttle/computer.dm
- code/modules/shuttle/marine_dropship.dm
This should hopefullyTM work
Fixes: #2698
> Fixes shuttle issues

- code/controllers/subsystem/weeds_decay.dm
stops decay from removing nodes
> Fix xeno weed decay

- code/game/objects/items/flashlight.dm
> Remove processing from flares

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
> Fix hivelord thicken ability

- code/modules/power/apc.dm
> Fixes APC repairing

- code/modules/vehicles/vehicle.dm
> Fixes train movement issues

- code/modules/shuttle/marine_dropship.dm
Increase shuttle time for marine major
> Increase shuttle time for marine major

- _maps/map_files/Theseus/TGS_Theseus.dmm
Self-explanatory
AI can actually use their holograms yay
:cl:
add: Added some holopads around the Theseus.
/:cl:
> Adds some holopads around the Theseus

- code/datums/gamemodes/crash.dm
Fixed #2730
Allow only one SL for crash
> Allow only one SL for crash

- code/__DEFINES/is_helpers.dm
- code/__DEFINES/misc.dm
- code/controllers/subsystem/chat.dm
- code/datums/emotes.dm
- code/game/verbs/ooc.dm
- code/modules/admin/fun_verbs.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
- code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
- code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
- code/modules/projectiles/updated_projectiles/gun_attachables.dm
- goon/code/datums/browserOutput.dm
> Chat subsystem optimization plus a fallback solution

- code/modules/xenomorph/xeno_structures.dm
> Fixes resin silo names

- code/game/objects/structures/xeno.dm
> Sticky resin no longer stacks on lying people

- code/game/objects/structures/crates_lockers/closets.dm
> Fixes opening closets with grabs

- code/datums/callback.dm
> Fixes varset_callback on deleted stuff

- code/modules/xenomorph/xeno_structures.dm
> Fixes xeno resin hitsounds

- code/modules/admin/fun_verbs.dm
Allows dropships to goto any valid target, instead of a hardcoded list.
> Fixes force dropship

- _maps/map_files/Theseus/TGS_Theseus.dmm
Fixes the holopads in requisitions and briefing being under catwalks. Please give me points github bot.
Can click on them
> Fixes holopads underneath catwalks

- code/game/objects/structures/tables_racks.dm
A tiny bit dirty, can improve if necessary.
Fixes: #2765
> Fixes reinforced table deconstruction

- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/living_health_procs.dm
- code/modules/mob/living/status_procs.dm
Also slightly cleans up the code
Fixes: #2747
> Fixes revive cleaning up some effects incorrectly

- code/modules/projectiles/updated_projectiles/guns/specialist.dm
> Fixes shotgun spelling issue

- code/modules/projectiles/updated_projectiles/ammunition.dm
This gets rid of the parent logic but unfortunately I don't see a cleaner solution for this
Fixes: #2724
> Fixes shotgunbox issues

- code/_onclick/ventcrawl.dm
> Fixes ventcrawl runtime

- code/datums/wires/_wires.dm
It may not have an user if it's like an explosion or something
> Fixes a wire cutting runtime

- _maps/map_files/BigRed_v2/BigRed_v2.dmm
> Fixes a wall being under a girder.

- _maps/map_files/Theseus/TGS_Theseus.dmm
- code/game/objects/machinery/door_control.dm
- code/game/objects/machinery/doors/airlock_types.dm
- code/game/objects/machinery/doors/poddoor.dm
Improvements to AI stuff on the ship. Like an extra holopad. And better doors and shutters. And cameras in the ERT shuttle bays.
AI has more control
> Stuff the AI will like (hopefully not broken this time)

- code/_globalvars/lists/objects.dm
- code/datums/gamemodes/crash.dm
- code/game/objects/machinery/nuclearbomb.dm
- code/modules/shuttle/marine_dropship.dm
:cl:
add: Marines lose when leaving without a nuke set on crash
/:cl:
> Marines lose when leaving without a nuke set

- code/game/objects/machinery/telecomms/broadcasting.dm
- code/game/objects/machinery/telecomms/machines/server.dm
- code/modules/mob/living/carbon/human/say.dm
- code/modules/mob/mob_helpers.dm
> Fixes devoured comms

- _maps/map_files/Theseus/TGS_Theseus.dmm
- code/game/objects/machinery/doors/poddoor.dm
- code/game/objects/machinery/doors/shutters.dm
> Fixes poddoor and shutter issues

- code/game/objects/machinery/door_display/door_display.dm
> Fixes research shutter display

- code/datums/gamemodes/game_mode.dm
Hopefully shouldn't break anything and be smoother TM
> Reduces the roundstart notransform lock time

- code/datums/gamemodes/crash.dm
Fixes issue with xenos winning a minor when the nuke has been planted.
> Fix xeno minor conditions

- code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
> Fixes hunter stealth attack issues

- code/datums/map_config.dm
> Fixes ship map reference name replace

- code/datums/jobs/squads.dm
> Fixes aSL not having orders available

- code/__DEFINES/is_helpers.dm
> Fixes being able to take over aghosted xenos

- code/game/objects/items/reagent_containers/food/snacks.dm
- code/game/objects/items/trash.dm
> Fixes fortune cookie interactions

- code/game/objects/structures/crates_lockers/closets.dm
> Fixes unclosed HTML tags

- code/game/objects/machinery/fax.dm
> Fixes fax machine eating IDs

- code/modules/codex/entries/engineering_codex.dm
I join for one game after months away, and I already remember why I created the codex in the first place.
A bit more information is automated, and doesn't bother mentors.
> Detonation pack Codex

- code/modules/mob/living/carbon/human/human.dm
> Fixes powerloader attack animation

- code/modules/mob/mob_grab.dm
> Fixes xeno fog cheesing

- code/modules/mob/new_player/preferences_setup.dm
> Fixes bad eyesight preference

- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
> Fixes warrior runtime

- code/game/objects/items/storage/storage.dm
hide_from already checks if the s_active is src, this shouldn't cause any other issues
Fixes: #2866
> Fixes storage window weirdness

- code/game/objects/items/radio/headset.dm
> Cleans up headset code

- code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
Removes the screen shake effect for xenos when queen screeches.
:cl:
balance: Changed queen screech to do nothing to xenomorphs
/:cl:
> Removed Queen screech's screen shake for xenomorphs

- code/game/objects/items/explosives/grenades/marines.dm
> Fixes flares not burning weeds

- code/game/objects/structures/xeno.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
> Fixes even more fog cheesing

- code/modules/mob/living/carbon/human/update_icons.dm
> Fixes invisible shoes

- code/modules/admin/fun_verbs.dm
Cleans up the code and very likely fixes it
> Youtubedl tweaks

- goon/browserassets/js/browserOutput.js
Ports https://github.com/tgstation/tgstation/pull/46384
> Fixes goonchat line height for IE8

- code/modules/admin/SDQL2/SDQL_2_parser.dm
https://github.com/tgstation/tgstation/pull/43698
> Cleans up workaround for fixed compiler bug

- code/game/objects/items/radio/headset.dm
- code/game/objects/items/reagent_containers/food/snacks.dm
Burger is spelled without "-"
also removes whitespace
> Fixes the burger name from -burger and removes 1 bit of whitespace

- code/game/objects/explosion.dm
> Fixes damage after deletion runtimes

- code/game/objects/structures/tables_racks.dm
> Fixes harm intent table interactions

- code/game/objects/items/flashlight.dm
- code/game/objects/items/storage/boxes.dm
- code/game/objects/items/storage/storage.dm
- code/game/objects/items/weapons/blades.dm
- code/modules/projectiles/updated_projectiles/gun_attachables.dm
Fixes: #2738
Thanks to Henri for helping me out with this
> Fixes the mysterious storage runtime for good

- code/datums/gamemodes/distress.dm
- code/datums/supplypacks.dm
- code/game/objects/machinery/vending/marine_vending.dm
- code/modules/projectiles/updated_projectiles/ammunition.dm
> Unshitcodes ammoboxes even further

- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
Only happened with new accounts, culprit found.
> Fixes a menu runtime

- code/datums/browser.dm
- code/game/world.dm
- code/modules/client/preferences.dm
- code/modules/tgs/event_handler.dm
- tgmc.dme
Essentially #2929 , credit to the original author, who's always welcome around here.
The config changes have been made, @spookydonut , so this can be merged whenever convenient.
> LaK bugfixes

- .gitignore
thanks to psy for discovering this
> ignore visualstudio compile cache files from midi2piano

- code/modules/client/preferences_gear.dm
Maybe later I can figure out how to make the good eyesight toggle automatically spawn glasses. But not today.
Just regular ol' glasses. Not rpg glasses or goggles.
:cl:
add: Added prescription glasses to the loadout.
/:cl:
> Adds prescription glasses to marine loadout

- code/modules/mob/living/carbon/xenomorph/castes/ravenger/ravenger.dm
- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/spawn_xenos.dm
> add more unit tests

- code/datums/gamemodes/crash.dm
:cl:
balance: Increased the number of xenos that will naturally spawn in Crash game mode.
/:cl:
> Crash xeno numbers patch

- code/__DEFINES/mobs.dm
- code/modules/atmospherics/machinery/atmosmachinery.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/taste.dm
> Removes two variables and substitutes them with the cooldown list

- code/game/turfs/turf.dm
- code/game/turfs/walls/wall_types.dm
- code/game/turfs/walls/walls.dm
- code/modules/projectiles/updated_projectiles/projectile.dm
Adds the armor datum to turfs, so we can handle their damage better.
:cl:
balance: Walls are now very resistant to bullets. You'll need to be more creative to destroy them now. They are still vulnerable to acid spit.
/:cl:
> Wall armor: resistant walls

- code/game/objects/items/motion_detector.dm
- code/game/objects/items/stacks/cable_coil.dm
- code/game/objects/items/stacks/stack.dm
- code/game/objects/items/toys/toy_weapons.dm
- code/game/objects/structures/stool_bed_chair_nest/janicart.dm
- code/game/objects/structures/xeno.dm
- code/modules/detectivework/footprints_and_rag.dm
- code/modules/paperwork/paper.dm
- code/modules/paperwork/paper_bundle.dm
- code/modules/paperwork/paperbin.dm
- code/modules/power/cell.dm
Some things, like lasgun/normal cells, wouldn't display the "This is a [thing]. It is a [size] item." This makes them do that. Also makes motion detectors display it before, rather than after, saying what their settings are.
> Makes more examines use atom/examine

- code/controllers/subsystem/chat.dm
- code/datums/emotes.dm
- code/game/objects/explosion.dm
- code/modules/projectiles/updated_projectiles/projectile.dm
* Reduces some pointless logs.
* Removes the hitmarker to reduce processing on being shot.
* Does a little fix on projectiles code.
> bullet_act-related (mostly) tweaks

- code/modules/atmospherics/machinery/atmosmachinery.dm
- code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
- code/modules/atmospherics/machinery/components/binary_devices/pump.dm
- code/modules/atmospherics/machinery/components/binary_devices/valve.dm
- code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
- code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
- code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
- code/modules/atmospherics/machinery/components/unary_devices/heat_exchanger.dm
- code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
- code/modules/atmospherics/machinery/components/unary_devices/portables_connector.dm
- code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
- code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
- code/modules/atmospherics/machinery/pipes/pipes.dm
:cl:
balance: Atmospheric equipment can no longer be deconstructed or destroyed, for balance. You can still weld vents.
/:cl:
Also fixes the following runtime, legacy of not having the attack toolchain:
```
[20:21:13] Runtime in obj_defense.dm, line 3: The air supply pipe taking damage after deletion
proc name: take damage (/obj/proc/take_damage)
usr: CKEY/(Michael Garrat)
usr.loc: (Warden's Office (227, 143, 2))
src: the air supply pipe (/obj/machinery/atmospherics/pipe/simple/supply/hidden/layer1)
src.loc: null
call stack:
the air supply pipe (/obj/machinery/atmospherics/pipe/simple/supply/hidden/layer1): take damage(5, "brute", "melee", 1, null, 0)
the air supply pipe (/obj/machinery/atmospherics/pipe/simple/supply/hidden/layer1): attacked by(the wrench (/obj/item/tool/wrench), Michael …
```
> Undamageable atmospheric stuff

- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
- code/game/objects/items/explosives/plastique.dm
- code/game/objects/items/radio/detpack.dm
- code/game/objects/machinery/doors/airlock.dm
- code/game/objects/machinery/doors/poddoor.dm
* Fixes being unable to C4 or detpack airlocks and poddoors.
* Fixes being able to C4 or detpack something already carrying one, which would lead to bad deletions.
* Fixes being able to crowbar open poddoors.
* Cleans up some var-edits in prison station.
> Poddoor, airlock, detpack and c4 bugfixes

- code/game/objects/items/tools/flame_tools.dm
> Fixes not being able to pick up lighters.

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
:cl:
fix: ice lz1 (top left one) restored to full size to avoid squashing people
/:cl:
> ice lz1 unshrunk

- _maps/map_files/LV624/LV624.dmm
Moved the survivor spawn placed in surgery outside
Fixes issue #3040 
:cl:
fix: Issue #3040 
/:cl:
> Moved medical survivor spawn

- code/modules/projectiles/updated_projectiles/ammo_datums.dm
:cl:
balance: acid spit stops wherever you clicked again
/:cl:
> gives acid AMMO_EXPLOSIVE

- code/modules/unit_tests/spawn_humans.dm
- code/modules/unit_tests/spawn_xenos.dm
> test for bad qdels

- code/game/objects/items/scanners.dm
- code/game/objects/machinery/OpTable.dm
- code/game/objects/machinery/Sleeper.dm
- code/game/objects/machinery/autodoc.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/carbon_defines.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/carbon/human/life/handle_pulse.dm
Fixes #2826
The issue was that pulse was updated in life, but only ever 5 life ticks. So on certain cases you could get dead people whose pulse wasn't updated.
Instead, I'm changing it to update on demand. No need for this to be in `Life()`
> Fix heart pulse issues

- code/game/objects/items/bodybag.dm
> cryobag scanner fix

- code/controllers/configuration/entries/game_options.dm
- code/game/objects/items/defibrillator.dm
- code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/mob/living/carbon/human/human_helpers.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/living_helpers.dm
* Removed unused configs.
* Moved human var definitions.
* Cleaned up some defib code and added early returns.
* Removed a duplicate defib spark system object.
Still hunting for the synth bug, whose cause or reproduction method I'm not yet fully certain of.
> Small human and defib cleanup

- code/game/objects/structures/tables_racks.dm
> Table-ghost interaction fix.

- code/datums/gamemodes/game_mode.dm
> readds snowsuits to ice survivor spawns

- code/modules/reagents/Chemistry-Reagents.dm
- code/modules/reagents/chemistry_reagents/medical.dm
> stops reagent purge_list getting bigger every mob tick.

- code/controllers/subsystem/mobs.dm
- code/modules/mob/living/carbon/human/dummy.dm
- code/modules/mob/living/living_health_procs.dm
> Mob processing issues

- code/datums/gamemodes/crash.dm
> Less xenos on Crash

- code/modules/projectiles/updated_projectiles/projectile.dm
A little oversight in behavior on the new projectile system.
> Explosive projectiles will try to hit a target before exploding in the turf

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
- _maps/map_files/LV624/LV624.dmm
- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
I didn't have anything to do, so I forked build and fixed a few map things, like this:
literally: some wires, some pipes, some lights, and something else I've already forgotten. I haven't added anything new or changed a lot.
Actually, I'm doing this PR because of a broken pipe in the Prison Station between the dining room and the kitchen.
> Changes to the map that no one will notice

- _maps/map_files/Port_Hamburg/Port_Hamburg.dmm
- _maps/map_files/Sulaco/Sulaco.dmm
- _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
- code/game/area/port_hamburg.dm
- code/game/area/vaporprocessing.dm
- code/modules/lighting/lighting_source.dm
- code/modules/projectiles/updated_projectiles/ammo_datums.dm
- tgmc.dme
- tools/travis/check_grep.sh
a bunch of these weren't using -P to make them PCRE
> fix travis greps

- _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
adds some silos a nuke and computers to vapor processing
> add crash stuff to vaporprocessing

- _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
> fix errant area varedit

- code/game/atoms_movable.dm
- code/game/objects/machinery/bots/medbot.dm
> lints COMSIG_MOVABLE_BUMP

- .gitignore
- .vscode/extensions.json
- .vscode/tasks.json
Adds dreamchecker task with regex to ctrl-click errors
Get dreamchecker.exe (windows) or dreamchecker (linux) and put it in the base directory of your local repo.
https://github.com/SpaceManiac/SpacemanDMM/releases
> Adds a dreamchecker task for vscode users

- code/game/objects/machinery/computer/camera_advanced.dm
- code/game/objects/machinery/computer/communications.dm
- code/game/objects/machinery/overwatch.dm
Fixes #2931
Fixes #2930
Fixes #2926
> AI interaction fixes

- code/__DEFINES/objects.dm
- code/game/objects/items/restraints.dm
- code/modules/mob/inventory.dm
- code/modules/mob/living/carbon/human/inventory.dm
- code/modules/mob/living/carbon/inventory.dm
- code/modules/mob/mob.dm
Bug of mine in where the proc didn't differentiate between dropped from hands and removed from an actual gear slot, leading to incorrect behavior.
> Limb armor on unequip fix

- code/_onclick/item_attack.dm
- code/game/objects/items.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/projectiles/updated_projectiles/gun_system.dm
> Tiny memory use reduction on /obj/item

- code/modules/projectiles/updated_projectiles/ammo_datums.dm
> makes staggerstun args more sensible

- .vscode/tasks.json
> fix weird bug with dreamchecker

- code/game/objects/machinery/doors/windowdoor.dm
> Xeno-damageable windoors

- code/modules/mob/living/carbon/human/emote.dm
> Signal emote fix

- code/game/objects/structures/tables_racks.dm
* Fixes #3003
* Fixes another bug in where clicking on a table with a valid tool would place the tool on the table and start deconstructing/interacting with it.
> Table bugs

- code/game/objects/machinery/autodoc.dm
- code/modules/mob/living/carbon/human/human_damage.dm
* Fixes #2957
* Adds a check to the surgery start proc, which could be started multiple times, causing things like the OD.
* Fixes an issue when setting a patient with internal bleeding to brute-fixing surgery would cause the autodoc enter an eternal loop of fixing a kind of damage it can't fix.
* Cleans up the code some to standards.
> Autodoc cleanup and fixes

- Dockerfile
- code/__DEFINES/is_helpers.dm
- code/__DEFINES/layers.dm
- code/__DEFINES/maths.dm
- code/__HELPERS/unsorted.dm
- code/_onclick/hud/plane_master.dm
- code/game/objects/machinery/autodoc.dm
- code/modules/organs/limbs.dm
- code/modules/surgery/generic.dm
> 513 compat

- code/modules/mob/living/living_health_procs.dm
Fixes rejuvenate not removing embedded objects.
> Embed on rejuvenate fix

- code/__DEFINES/components.dm
- code/controllers/subsystem/dcs.dm
- code/controllers/subsystem/garbage.dm
- code/datums/components/full_auto_fire.dm
- code/datums/elements/_element.dm
- code/datums/elements/windowshutter.dm
- code/game/objects/items/bodybag.dm
- code/game/objects/items/circuitboards/circuitboard.dm
- code/game/objects/items/circuitboards/computer.dm
- code/game/objects/items/marine_gear.dm
- code/game/objects/machinery.dm
- code/game/objects/machinery/camera/camera_assembly.dm
- code/game/objects/machinery/computer/computer.dm
- code/game/objects/obj_defense.dm
- code/game/objects/structures/fence.dm
- code/game/objects/structures/window.dm
- code/modules/atmospherics/machinery/other/meter.dm
- code/modules/atmospherics/machinery/portable/canister.dm
- code/modules/power/cable.dm
- code/modules/power/terminal.dm
- tgmc.dme
ports elements
This adds a windowshutter element which is for the prison windows to spawn and close a shutter when they break.
To do this I also had to enforce parent calling for the deconstruct() proc
> ports elements

- code/game/objects/items/binoculars.dm
> Binocs interaction bug fix

- code/game/turfs/floor_types.dm
- code/game/turfs/open.dm
- code/game/turfs/turf.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
* Fixes #3188
* Improves the building ability button to properly update on change.
> Walls on shuttles fixes

- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> Queen timer fix

- code/_onclick/hud/alien.dm
> Nightvision

- code/game/objects/items/embedding.dm
- code/game/objects/machinery/autodoc.dm
- code/modules/organs/limbs.dm
- code/modules/surgery/implant.dm
Fixes sharpnel surgery shennanigans.
> Shrapnel surgery fix

- code/datums/actions/observer_action.dm
- code/modules/admin/fun_verbs.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
> Hive status datum browser.

- code/modules/mob/living/carbon/human/human.dm
> Check-pulse fix

- _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
removes a ton of single tile passages
:cl:
tweak: vapor has less single tile passages
/:cl:
> Makes vapor less bad

- code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
- code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
- code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
- code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
- code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
- code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
- code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
- code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
- code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Changes xenos overall slash/tackle and some abillities numbers with the hopes it will make them more balanced
Last balance change on xenos kind of screwed up their numbers,this pr is trying to fix that,numbers bellow are slash numbers unless it says otherwise
:cl:
balance:Various xenomorph stats adjustments.
/:cl:
Balance is fun
> Xeno Rebalance

- code/modules/projectiles/updated_projectiles/ammo_datums.dm
- code/modules/projectiles/updated_projectiles/guns/specialist.dm
Nerfs and changes a bunch of marine related stuff
As we all know,marine damage is bokers,this is an attempt to make it not bonkers,as per rohesie's request
:cl:
balance:Various marine gun damage reductions
/:cl:
Thanks to MJP for thinking up the changes and for balance chat on discord.
> Damage deescalation for marine side

- code/modules/clothing/head/helmet.dm
Got changed by accident in #3176
> B18 helmet sprite fix

- code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
> deletes two apostrophes

- code/datums/gamemodes/game_mode.dm
As per title. If anyone needs more EORD roles, please tell me now!
Because WE NEED MORE VARIANTS.
:cl:
add: Added more EORG roles, no deathsquad roles yet though.
/:cl:
> More End of Round Deathmatch roles

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
- code/game/objects/effects/landmarks/corpsespawner.dm
- code/modules/clothing/masks/gasmask.dm
:cl:
balance: Removed antihug properties of map-spawned masks.
/:cl:
> Removes antihug properties of map-spawned masks

- code/modules/goonchat/browserOutput.css
We'll start by making the background an olive green-grey.
> Darkmode tweaks

- code/game/objects/items/defibrillator.dm
> adds four full stops

- code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
This method is a bit more accurage.
> Improves Unrelenting Force's target facing.

- code/modules/mob/living/carbon/xenomorph/attack_alien.dm
:cl:
balance: Xenos are now able to put out hosts on fire through help-intent.
/:cl:
> Xeno firefighters

- code/_onclick/ventcrawl.dm
- code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
- code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
> Fixes ventcrawling when resting

- code/game/verbs/ooc.dm
Ports the /tg/ verb in case chat is bork
> Fix chat verb

- code/modules/clothing/gloves/marine_gloves.dm
- code/modules/clothing/shoes/marine_shoes.dm
- code/modules/clothing/suits/marine_armor.dm
Makes all marine armor cover Hand/Feet,nerfs all boot and gloves acid and melee armor,changes marine armor stats
This will hopefully make the armor choice more meaningful by making it affect all damage you take,buffing heavier armor sets but nerfing lighter armor sets,also changes bio armor due to stamina changes
:cl:
balance: rebalanced marine gloves,boots and armor
/:cl:
> Rebalance of marine armor

- code/controllers/globals.dm
- code/datums/datum.dm
- code/datums/elements/_element.dm
- code/datums/emergency_calls/emergency_call.dm
- code/game/atoms_movable.dm
- code/game/objects/obj_defense.dm
- code/game/objects/structures/fence.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/projectiles/updated_projectiles/gun_attachables.dm
- dependencies.sh
https://github.com/SpaceManiac/SpacemanDMM/releases/tag/suite-1.1
> New spacemandmm release

- code/modules/projectiles/updated_projectiles/guns/shotguns.dm
Burst Fire Delay 2 => 6
This gun was a little too good, this nerf isn't major. Its still a good gun just has its DPS lowered a bit.
:cl:
balance: Custom Built Shotgun Burst Fire Delay 2 => 6
/:cl:
> Custom Built Shotgun Nerf

- code/__DEFINES/components.dm
- code/datums/elements/windowshutter.dm
aaaaaaaaaaaaa what shitcoder wrote this
> unfuck shutter element

- code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
Lowers runners speed by 0.1.
Roh asked me to do it.
:cl:
balance: Runner speed reduced slightly, plasma regeneration increased.
/:cl:
> Lowers runners speed by 0.1.

- code/modules/power/apc.dm
> Minor APC cleanup

- code/controllers/configuration/entries/game_options.dm
- code/datums/gamemodes/crash.dm
- code/datums/gamemodes/game_mode.dm
Adds a xeno coefficient for crash to better balance the starting numbers.
> Crash coefficient

- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
> Fixes xenos not on the main ground being deleted on hijacks

- code/modules/projectiles/updated_projectiles/guns/flamer.dm
> Fire bugfix

- code/game/objects/items/storage/backpack.dm
- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/mob/living/carbon/human/species.dm
They should be 3 different signals, really. This will need a better refactor.
> Fixes bad signals

- code/game/objects/items/scanners.dm
It doesn't check if the target is qdeleted
> Fixes a health scanner do_after runtime

- code/game/objects/items/radio/headset.dm
Could have a null `assigned_squad`
> Squad tracker runtime fix

- code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Increases cooldown from 8 seconds to 16 seconds
Queen heal is causing immortal xenomorphs memes right now,this nerfs that
:cl:
balance:adjusted queen heal
/:cl:
> Increases Queen heal cooldown

- code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
removes shift spits from queen because it only has 1 spit type now
> removes shift spits from queen

- code/game/turfs/turf.dm
- code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
bug fix
'bug fix' fixes #3337
:cl: Hughgent
fix: Carrier hugger traps can no long be stacked on one tile.
/:cl:
> Multi Carrier trap fix

- code/modules/projectiles/updated_projectiles/ammo_datums.dm
- code/modules/projectiles/updated_projectiles/guns/rifles.dm
- code/modules/projectiles/updated_projectiles/magazines/rifles.dm
Changes dmr to 70 damage and 15 ap,increases fire delay to 0.9,decreases ammo per magazine to 10
DMR right now is kind of underwhelming,it has low ammo and the damage it does is kind of meh,this makes it into more of a marksman rifle,changes requested by mjp so go scream at him
:cl:
balance: Decreased DMR rate of fire and ammo capacity, and increased its damage.
/:cl:
> Changes DMR a bit

- code/modules/mob/living/carbon/xenomorph/embryo.dm
- code/modules/reagents/chemistry_reagents/toxin.dm
Changes Larva growth
Larval growth is weird right now. If you aren't toxined, you won't burst. This aims to change that.
:cl:
balance: Larval toxin now advances larva less, but larva naturally grow more. Overall, there's slower growth. It no longer heals oxygen damage.
/:cl:
> Larval toxin changes

- code/game/objects/items/reagent_containers/hypospray.dm
> gives hyposprays and its subtypes melee range

- code/datums/emergency_calls/emergency_call.dm
- code/datums/emergency_calls/xeno.dm
This one is mine. Looks like I failed to commit these changes before.
> Xeno ERT fix

- code/__DEFINES/mobs.dm
- code/datums/gamemodes/game_mode.dm
- code/game/objects/machinery/cryopod.dm
- code/modules/admin/holder.dm
- code/modules/admin/panels/mode_panel.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/carbon_defines.dm
- code/modules/mob/living/carbon/human/login.dm
- code/modules/mob/living/carbon/human/logout.dm
- code/modules/mob/living/carbon/login.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/mob/living/carbon/xenomorph/life.dm
- code/modules/mob/living/carbon/xenomorph/login.dm
- code/modules/mob/living/carbon/xenomorph/logout.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
- code/modules/mob/new_player/new_player.dm
- tgmc.dme
> AFK, Respawn and Game tab tweaks

- code/modules/projectiles/updated_projectiles/projectile.dm
> Feedback fixes

- code/modules/projectiles/updated_projectiles/guns/specialist.dm
fixes #3348 
(is there a specific reason this grenade launchers firing proc is so different from the m92, the specialist one?)
> m81 grenade launcher fix

- code/game/objects/effects/aliens.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/suits/marine_armor.dm
- code/modules/clothing/suits/utility.dm
- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
- code/modules/mob/living/carbon/xenomorph/charge_crush.dm
- code/modules/mob/living/carbon/xenomorph/damage_procs.dm
- code/modules/mob/living/damage_procs.dm
- code/modules/mob/living/living_defense.dm
- code/modules/mob/living/living_health_procs.dm
- code/modules/organs/limbs.dm
- code/modules/projectiles/updated_projectiles/guns/flamer.dm
* Handling armor block like /tg/ does.
* Xeno melee armor fixed.
* Fixed some Crusher abilities to now respect armor.
> Xenos armor fixes

- code/game/objects/items/radio/detpack.dm
Minor issue, one of the timers nor properly flagged as stoppable.
> Detpack runtime fix

- code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Nerfs queen speed
Queen is fast as fuck boi,and it honestly looks silly and is too strong,so this is a nerf to her speed,she'll still be faster than before rework but not as much
:cl:
balance: nerfed queen speed
/:cl:
> Nerfs queen speed

- code/modules/projectiles/updated_projectiles/gun_system.dm
fixes #3306 
slightly more realism, it grabs the bullet in the chamber rather than one from the magazine.
:cl: Hughgent
fix: Cocking a gun now produces the correctly loaded in chamber round.
/:cl:
> fixes cocking the gun producing the wrong bullet.

- code/game/turfs/snow.dm
Oldie but a goodie. Fixes #2961 
You can now actually place lightsticks (in snow) again.
:cl: Hughgent
fix: You can now place lightsticks in the snow again.
/:cl:
> Fixes Lightsticks

- code/game/objects/structures/crates_lockers/crates.dm
- code/game/turfs/floor_types.dm
- code/game/turfs/open.dm
makes crates not climbable to avoid weird ctrl-click interaction causing you to start pulling and climbing it
actually calls the alien construction helper on shuttle/ship floor now to fix an issue allowing for stacking resin structures infinitely
monki fix
:cl:
fix: minor bugfixes
/:cl:
> small bugfixes

- code/_onclick/item_attack.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/living_defense.dm
Old unmaintained code conflicting
> Human armor fixes against item attacks

- code/__DEFINES/components.dm
- code/_onclick/telekinesis.dm
- code/datums/components/clothing_tint.dm
- code/game/objects/items.dm
- code/game/objects/items/cloaking.dm
- code/game/objects/items/marine_gear.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/head/misc_special.dm
- code/modules/clothing/masks/breath.dm
- code/modules/clothing/masks/gasmask.dm
- code/modules/codex/entries/clothing_codex.dm
- code/modules/mob/inventory.dm
- code/modules/mob/living/carbon/human/inventory.dm
- code/modules/mob/living/carbon/inventory.dm
- tgmc.dme
aaaaaaaaaaa i dont know how I didn't notice how badly tinting was done.
Closes #3385
> clothing_tint component

- code/datums/gamemodes/game_mode.dm
- code/datums/jobs/job/survivor.dm
- code/datums/skills.dm
- code/game/objects/items/storage/backpack.dm
- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/suits/armor.dm
This is in general a large buff to survivors, they start with decent armor and master in all skills except combat ones.
If you want an IC explanation, consider why you, out of everyone in the colony, is still alive while the others are dead. You must be really lucky or really good.
Survivor is masochistic already, why not give them a little something to slightly increase their chance of making it out alive as well as giving the marines a reason to rescue survivors.
Also, lots of PR's, some I've made, have side effects of making survivors harder, this should help to counter that.
:cl:
balance: Survivor gets master in all non-combat skills.
balance: Survivor gets decent armor.
/:cl:
> Rambo Survivors

- code/modules/client/asset_cache.dm
- code/modules/goonchat/browserOutput.html
todo: make goonchat use the separate fontawesome asset cache
Fixes #3351
> fixes tgui-next icons

- code/modules/mob/living/carbon/xenomorph/attack_alien.dm
- code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
- code/modules/mob/living/carbon/xenomorph/life.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Hunter sneak attack bonus damage is now removed. Hunters will not get increased damage from sneak attacks.
Hunter op plz nerf.
:cl: BurgerBB
balance: Removed hunter sneak attack damage.
/:cl:
Closes #3390 
Closes #3440
> Removes sneak attack bonus damage from hunter

- code/modules/admin/fun_verbs.dm
- code/modules/goonchat/browserOutput.css
The squads should look a bit better, and command is rather distinct.
> More darkmode tweaks

- code/datums/components/dripping.dm
> Dripping component processes instead of timer-loops

- code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
:cl:
balance: Slows down the Shrike a little.
/:cl:
> Shrike slowdown

- code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
Someone will have to test better to re-add something like this.
> Removes the broken Defender Lunge

- code/__DEFINES/is_helpers.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/shuttle/marine_dropship.dm
This should avoid some cheesiness.
> Xeno rulers can only crack open the dropship doors if they are inside of it, or if they are all closed

- code/game/objects/effects/effect_system/particle_effects.dm
- code/game/turfs/snow.dm
- code/modules/mob/living/living_defense.dm
Fire and Snow interactions
:cl:
add: you can now instantly put out fires by resisting on snow
add: fire melts snow
/:cl:
> Fire and Snow interactions

- code/modules/mob/living/carbon/xenomorph/evolution.dm
Fixes players evolving to shrike when they are jobbanned.
> Fix shrike jobban

- _maps/icy_caves.json
Makes Ice caves use the ice variant
It's a Ice themed map,I didn't sprite a whole line of ice armor sprites for funzies grrr
:cl:
tweak:make icy caves use ice variant
/:cl:
> Makes Ice Caves use ice variants

- code/modules/clothing/gloves/marine_gloves.dm
- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/clothing/shoes/marine_shoes.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/suits/armor.dm
- code/modules/clothing/suits/marine_armor.dm
All armor sets now will cover hands/feet and all gloves/boots have been nerfed
It makes all armor in the game work the same and stops memes of marines with invincible hands and feet
:cl:
balance:reworks all non-marine armor sets
/:cl:
> Reworks all armor sets to be like marines ones

- code/modules/projectiles/updated_projectiles/guns/rifles.dm
:cl:
balance: The DMR can no longer point-blank. Its fire delay has been slightly increased.
/:cl:
> DMR minor nerf

- .github/workflows/autobuild_tgui.yml
https://github.com/tgstation/tgstation/pull/47961
> Uses actions to automatically rebuild tgui if files are changed, then push the result.
> Triggers on push to master, pushes results to master.
> Also disables build checking in Travis because it's unimportant now.
> autobuild tgui-next

- code/modules/clothing/head/helmet.dm
Changed marines helmet stats and heavy helmet description.
Most marine helmets didn't have their bio armor updated (because I forgot) so now they do,heavy helmet had some weird stats and a copy pasted description so that's fixed as well.
:cl:
tweak: Changed marine's helmets stats and heavy helmet description.
/:cl:
> Some helmet changes

- code/game/objects/structures/barricade.dm
> Barbed wire duping fix

- code/game/objects/machinery/overwatch.dm
Active squads are no longer hardcoded since init.
> Main overwatch computer fix

- code/__HELPERS/admin.dm
- code/game/objects/machinery/computer/communications.dm
- code/modules/admin/topic.dm
- tgmc.dme
Adds an admin approval proc, basically expanding on the idea of how the distress call is handled.
This allows things to happen while admins are offline, but when online allows admins to gate certain activities as required.
> Adds an admin approval proc

- code/controllers/configuration/entries/general.dm
- code/datums/gamemodes/game_mode.dm
defaults to off
really really really annoying when testing.
> Makes duplicate name joining a config option

- Dockerfile
- code/__DEFINES/typeids.dm
- code/__HELPERS/text.dm
- code/__HELPERS/unsorted.dm
- code/datums/datacore.dm
- code/game/objects/items/paint.dm
- code/game/objects/machinery/computer/arcade.dm
- code/game/objects/machinery/computer/card.dm
- code/game/objects/machinery/computer/computer.dm
- code/game/objects/machinery/computer/marines_consoles.dm
- code/game/objects/machinery/doors/brigdoors.dm
- code/game/objects/structures/barsign.dm
- code/modules/admin/verbs/varedit.dm
- code/modules/mob/mob_helpers.dm
- code/modules/paperwork/carbonpaper.dm
- code/modules/paperwork/paper.dm
- code/modules/shuttle/supply.dm
513.1501 added some warnings for ancient procs
> Changed Replacetext to Oldreplacetext in preparation for 510 - rahlzel
> Fix dumb ancient text procs

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
logic was inverted
:cl:
fix: resinwalker now works again
/:cl:
Fixes #3504
> Fixes resinwalker

- code/_onclick/item_attack.dm
- code/game/atoms.dm
- code/modules/requisitions/fulton.dm
As per title. Removes a layer of wrapper by deleting tool_act and introduces preattack which can be overridden much more cleanly. Also removes an untidy override in the fulton devices with this new proc. Completely barebones PR.
Code quality.
> Removes a layer of wrapper for tool_act.

- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Nerfs warrior in damage/armor/health and cooldown/plasma on abilities
Warrior is too strong,never let it be said I can't be wrong about something
:cl:
balance: Nerfs warrior
/:cl:
> Nerfs warrior

- code/datums/atom_hud.dm
- code/modules/admin/SDQL2/SDQL_2.dm
all hail the linter
```
code/modules/admin/SDQL2/SDQL_2.dm, line 717, column 5:
error: attempted operator++ on a list
code/modules/admin/SDQL2/SDQL_2.dm, line 724, column 5:
error: attempted operator++ on a list
code/modules/admin/SDQL2/SDQL_2.dm, line 746, column 6:
error: attempted operator++ on a list
code/datums/atom_hud.dm, line 47, column 2:
error: attempted operator-- on a /mob
code/datums/atom_hud.dm, line 86, column 3:
error: attempted operator++ on a /mob
```
> Fix new linter errors

- .github/workflows/stale.yml
Autolabel prs with no activity after 7 days as stale.
> Stale automarking

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
- _maps/map_files/icy_caves/icy_caves.dmm
> Fixes marines being able to bypass the SD shutters

- code/game/objects/machinery/vending/vending.dm
Add feedback for vendored items
> Add feedback for vendored items

- code/_onclick/drag_drop.dm
- code/modules/mob/mob.dm
> Xeno MouseDrop fix

- code/game/objects/items/storage/backpack.dm
:cl:
tweak: Going unconscious toggles the scout cloak stealth off.
/:cl:
> Scout cloak tweak

- code/datums/gamemodes/game_mode.dm
more larva in superlowpop
also what psy did in #3542 (ignore the commit name im retarded haha) because it's a good idea
//actually not what psy did because that causes bugs but i'll update this pr if necessary
better lowpop balance
:cl:
balance: burrowed are generated a bit more quickly
/:cl:
> larva generation math now rounds to nearest full integer rather than flooring

- code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
Speed up larva growth
Reduces the time spent as larva, increasing response time from a respawn.
:cl:
tweak: Larvas now evolve twice as quuick
/:cl:
> Speed up larva growth

- code/datums/gamemodes/game_mode.dm
- code/modules/mob/living/carbon/human/dummy.dm
- code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
When calculating the number of humans, revivable humans are included
Improves balance of humans / xenos
> larvapoints includes revivable humans

- code/datums/gamemodes/crash.dm
- code/datums/gamemodes/game_mode.dm
Marines never got the bioscan, but this way they get it but require communication.
Immersions
:cl:
add: Marines now get a fax in Crash with bioscan information
/:cl:
> Add Fax on bioscan

- _maps/map_files/icy_caves/icy_caves.dmm
- _maps/tyson_station.json
- _maps/vapor_processing.json
Also clean up map names
:cl:
tweak: moved the nuke on icy caves to the north east
/:cl:
> Move the nuke to the top right of icy_caves

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivelord/hivelord.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3557
> Fixes hivelord resin walker

- code/game/objects/machinery.dm
This stops machines idly drawing power.
> Remove idle processing for machines

- strings/tips/marine.txt
- strings/tips/meme.txt
I have altered the tips. Pray I do not alter them further.
stop-drop-roll tip removed because there's already one in meta tips.
> tip changes

- code/modules/mob/living/carbon/human/dummy.dm
Dummies need species set or they'll runtime. This is a light species version, mostly just visual.
> Species dummies

- code/game/objects/machinery/computer/communications.dm
Adds all the options to the admin approval.
Instead of asking the caller what ERT they want.
> Fixes distress call

- code/game/data_huds.dm
- code/game/objects/items/defibrillator.dm
- code/modules/mob/dead/observer/observer.dm
:cl:
add: People who go DNR now become skulls on medHUD instead of lightning bolts.
/:cl:
> makes DNR people become skulls on medhud

- code/modules/surgery/surgery.dm
Autodoc changes along with unskilled corpsman take almost 15 seconds for every action. This reduces that down to a more reasonable number
I dont want to remove the autodoc changes just yet.
Instead buffing manual surgeries.
:cl:
balance: Increased the benefits of skills when performing surgery.
/:cl:
> Buff surgery based on skills

- code/datums/gamemodes/crash.dm
Fixes xenos not getting selected at round start.
> Ensure we have roundstart xenos on crash

- _maps/map_files/icy_caves/icy_caves.dmm
Makes some of the caves 2 tiles wide, increases the size of hte room with the blue disk gen
fighting in tight spaces suck
:cl:
tweak: size of the blue disk room on icy caves
/:cl:
> Add more space near the blue disk generator

- code/game/objects/items/flashlight.dm
allow lamps to be broken
:cl:
add: desk lamps can now be broken
/:cl:
> allow lamps to be broken

- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/guns/shotguns.dm
title
Spellign good
:cl:
spellcheck: Fixed some gun descriptions
/:cl:
> Small gun description fixes

- _maps/shuttles/tgs_canterbury.dmm
title
requested by a player
:cl:
add: marines can now more easily die from lung cancer during crash
/:cl:
> puts ciggies on the cant

- code/modules/projectiles/magazines/rifles.dm
Changes T-12 magazine from calling it a carbine, to calling it an assault rifle.
Fixes the T-12 magazine description.
Consistency and accuracy in descriptions.
:cl:
spellcheck: fixed a typo
/:cl:
> Changes Description

- code/__DEFINES/components.dm
- code/__DEFINES/is_helpers.dm
- code/datums/balance.dm
- code/datums/gamemodes/game_mode.dm
- code/modules/mob/death.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
- code/modules/mob/login.dm
- code/modules/mob/logout.dm
- tgmc.dme
Add a new global datum that registers to signals to track balance changes throughout the game.
records those changes into the database for later analysis.
Balance
:cl:
add: balance tracking
/:cl:
> Add balance tracking

- code/modules/goonchat/browserOutput.dm
- code/modules/goonchat/browserOutput.js
Tanks orange man. https://github.com/tgstation/tgstation/pull/48524
> Port spamlinter goonchat thing

- code/game/world.dm
This is that https://github.com/tgstation/tgstation/pull/48542.
MSO said that the cooldown isn't long enough. Hopefully we get clarification on that in this decade. Probably needs changes. Currently exists more of a reminder that this needs doing.
Thanks oranges. Luv u.
> Ports from oranges: Readd cooldowns on the world topic #48542

- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/adminhelp.dm
Small changes to hopefully improve admin QOL.
> Clarify some discord ahelp commands

- code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Title
Crusher man bad
:cl:
balance: Crusher Armor has been nerfed
/:cl:
> Crusher Armor nerf

- code/modules/projectiles/gun_attachables.dm
Changes the description on lasgun lenses minorly, mostly typo fixes or clarity changes.
Clarity is good for the game
:cl:
spellcheck: Fixed typos and minorly changed some lens descriptions on the lasgun.
/:cl:
> Minorly changes the description on lasgun lenses.

- code/_onclick/item_attack.dm
Wonder why nobody reported this, it looks like an old bug.
> Fixes the attack animation with weapons against living

- code/datums/emergency_calls/emergency_call.dm
- code/game/objects/machinery/computer/card.dm
- code/game/objects/machinery/computer/communications.dm
- code/game/objects/machinery/telecomms/machines/receiver.dm
- code/game/objects/structures/tables_racks.dm
- code/modules/admin/verbs/varedit.dm
- code/modules/detectivework/footprints_and_rag.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
- code/modules/mob/living/simple_animal/friendly/parrot.dm
- code/modules/organs/limbs.dm
- code/modules/reagents/Chemistry-Machinery.dm
- code/modules/recycling/sortingmachinery.dm
- dependencies.sh
> bump spacemandmm suite to 1.2

- code/modules/mob/new_player/new_player.dm
Fixes typo from 
> You will have to wait at least 5 minutes before being able to respawn!
to
> You will have to wait at least 30 or 2 minutes before being able to respawn as a marine or alien, respectively!
Typos need fixing.
:cl:
fix: Fixed a typo regarding observing.
/:cl:
> Observe Typo Fix

- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/magazines/rifles.dm
Changes the stats on the carbine, increasing its max ammo and making it fire slightly faster. Adjusts aim slowdown on four PFC Primary weapons.
Adjusts some of the values on four guns, and generally improves the Carbine.
Improves Carbine ROF, Ammo per Mag, slightly increased move speed.
Reduces LMG move speed.
Increases Assault Rifle move speed slightly.
Was going to change the DMR but it behaved oddly.
Carbine was underperforming, and things like the LMG were too fast. Adjusted stats to reflect this.
:cl:
tweak: Tweaked Carbine stats. Should generally perform better. Increased Carbine Mag Size.
balance: Reduced LMG mobility effectiveness. Somewhat increased for the Assault Rifle, Carbine.
/:cl:
> Carbine Tweaks + Aim Slowdown Changes.

- tools/mapmerge2/requirements.txt
Source: https://github.com/tgstation/tgstation/pull/48693
> Upgrade pygit2 dependency to v1.0.1

- code/modules/client/message.dm
- code/modules/keybindings/bindings_client.dm
Source: https://github.com/tgstation/tgstation/pull/48594
> Some changes suggested by lummox

- code/modules/client/client_procs.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
Source: https://github.com/tgstation/tgstation/pull/48316
> Keybinding update fix

- code/game/objects/obj_defense.dm
- code/game/objects/structures/supplypod.dm
Source: https://github.com/tgstation/tgstation/pull/48268
> Minor potential runtime fixes

- code/__DEFINES/admin.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/holder.dm
- code/modules/admin/panels/ban_panel.dm
- code/modules/admin/panels/note_panel.dm
- code/modules/admin/verbs/adminhelp.dm
- code/modules/admin/verbs/chat_commands.dm
- code/modules/client/client_defines.dm
Porting https://github.com/tgstation/tgstation/pull/47954
> TGS refs refactor

- code/_onclick/hud/alerts.dm
- code/_onclick/hud/ghost.dm
- code/_onclick/hud/hud.dm
Taken from https://github.com/tgstation/tgstation/pull/48793
> Fixes alerts

- code/datums/status_effects/status_effect.dm
Source: https://github.com/tgstation/tgstation/pull/48377
> Potential stacking status effect runtime fix

- code/controllers/subsystem/timer.dm
- code/datums/components/squeak.dm
- code/datums/datum.dm
- code/datums/emergency_calls/emergency_call.dm
- code/datums/gamemodes/crash.dm
- code/datums/wires/_wires.dm
- code/game/objects/machinery/camera/camera.dm
- code/game/objects/machinery/computer/camera_console.dm
- code/modules/admin/verbs/centcom_podlauncher.dm
- code/modules/atmospherics/machinery/components/components_base.dm
- code/modules/atmospherics/machinery/datum_pipeline.dm
- code/modules/mob/inventory.dm
- code/modules/projectiles/ammo_datums.dm
- code/modules/reagents/Chemistry-Holder.dm
- code/modules/reagents/chemistry_reagents/toxin.dm
- code/modules/shuttle/escape_pod.dm
https://github.com/SpaceManiac/SpacemanDMM/pull/123
> remove unreachable code

- code/modules/goonchat/browserOutput.js
Port of https://github.com/tgstation/tgstation/pull/49867
> [s] Fixes XSS Exploit Defeating Sanitization of Any String in Goonchat

- code/modules/clothing/suits/marine_armor.dm
7 is ancient runner armor so clearly harness needs it
makes harness slightly less of a meme.
Still 33% worse than light armor tho
:cl:
balance: buffed harness minorly
/:cl:
> harness buff

- code/modules/client/preferences_savefile.dm
> Fix UI color when sanitizing hexcolors

- code/game/objects/effects/aliens.dm
Synths don't scream anymore when burning alive in acid spray.
> Synths don't scream

- code/modules/recycling/disposal.dm
Fix xenos throwing people into disposals
> Fix xenos throwing people into disposals

- code/modules/projectiles/ammo_datums.dm
Buffs flechette, making it more of a mid range option than buckshot.
:cl:
balance: Flechette is hopefully not bad anymore
/:cl:
> Fleccheteman

- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/guns/specialist.dm
Buffs the RPG majorly, it's generally agreed upon to be kind of bad.
Makes the RPG far better on direct hits, which should hurt a lot considering if you miss 2/3 rocket types don't really do much
:cl:
balance: RPG direct hits are far deadlier!
/:cl:
> Buffs the RPG

- code/modules/xenomorph/xeno_structures.dm
Fixes to silos and larva spawning
Silos didn't previously unregister when being destroyed.
> Fixes to silos and larva spawning

- Dockerfile
- code/modules/projectiles/ammo_datums.dm
- dependencies.sh
> Update to SpacemanDMM 1.3

- .github/CODEOWNERS
Stepping down as Sprite and Map Maintainer
> YEETS myself from codeowners

- _maps/map_files/Theseus/TGS_Theseus.dmm
Title
Ask Monki, was his request. I guess Theseus marines should be able to use FOB drones
:cl:
add: Added FOB drone computer in Theseus Hangar
/:cl:
> Placed FOB drone computer in Theseus hangar

- _maps/shuttles/tgs_canterbury.dmm
Canterbury uniform surplus vendor replaced with weapons vendor. One of the GHMME closets in cryo replaced with a uniform surplus vendor so that we won't lose them.
More mags for even more guns
:cl:
add: Added uniform surplus vendor in Canterbury Cryo
add: Added weapon vendor in Canterbury main area
del: Removed uniform surplus vendor in Canterbury main area
del: Removed one GHMME closet from Canterbury Cryo
/:cl:
> Vendor switcherino

- code/game/objects/structures/xeno.dm
- code/modules/mob/living/carbon/xenomorph/egg_item.dm
> Fix corrupted xeno eggs spawning regular hive huggers

- code/modules/mob/new_player/preferences_setup.dm
> Fixes synth name resetting

- Dockerfile
- SpacemanDMM.toml
- code/__DEFINES/spaceman_dmm.dm
- dependencies.sh
> Update to spacemandmm 1.4

- code/modules/mob/living/silicon/ai/say.dm
- code/modules/mob/living/silicon/say.dm
> Fixes AI speaking into ;

- code/datums/gamemodes/crash.dm
- code/modules/shuttle/computer.dm
- code/modules/shuttle/docking.dm
- code/modules/shuttle/marine_dropship.dm
Fix crash ignoring targets after its crashed
> Fix crash ignoring targets after its crashed

- code/datums/components/orbiter.dm
- code/modules/mob/dead/observer/observer.dm
Fix orbiting by porting latest from /tg/
> Fix orbiting by porting latest from /tg/

- code/game/objects/machinery/smartgun_mount.dm
- code/modules/projectiles/ammo_datums.dm
Gives the M56D IFF and more damage/pen
Have you even seen one ran as a non-joke other than in crash where you get a free one? Giving it IFF makes it far more useable and better.
:cl:
balance: m56d now has iff
spellcheck:Removed some comments related to it not having IFF.
/:cl:
> M56D IFF adding

- .github/CODEOWNERS
Additionally adds me (psykzz) to every review
> Replace Cultist with Kwin for mapping

- code/modules/mob/living/living_defense.dm
oneline change
Aghaghaghagh spongebob me bob the pyros retarded and flamed me again! agagaga I'm fucking dying to overheating aghhhhhhhh *deathgasp
:cl:
balance: If you get put out you will also slightly cool down
/:cl:
> You will now cool down when putting you get put out

- code/modules/goonchat/browserOutput.js
I missed this one when updating the file before.
> Fixes a goonchat bug

- code/modules/mob/living/carbon/xenomorph/death.dm
🐒 
Should help with the AI spam on WO since new decals arent formed if there are existing ones
:cl:
add: AI xenos will now gib on death, this should help with lategame lag on WO
/:cl:
> AI xenos will gib on death

- code/modules/codex/categories/category_reagents.dm
Helps to indentify issues when initalizing reagents.
Happened recently with the chem rework
> Stack trace badly setup reagents

- code/game/objects/machinery/computer/skills.dm
Ancient Baycode, it could cause a `null` entry in datacore, breaking a lot of things.
This way the computer can still be used to check on records and edit them, but not outright delete them.
> [s] Removes the ability to delete records through the employement records computer

- code/game/objects/machinery/nuclearbomb.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3632
> Fix anchoring the nuke on a shuttle

- code/modules/mob/living/living.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3643
> Fix xeno offset on pull

- code/modules/mob/living/carbon/human/human_helpers.dm
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3562
> Fix invisible synth head on droplimb

- code/modules/goonchat/browserOutput.css
- code/modules/mob/living/carbon/xenomorph/say.dm
Hivemind chat should be larger like a leader
> Increases the size of hivemind's hivemind say

- code/__HELPERS/view.dm
- code/modules/mob/dead/observer/say.dm
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3795
Additionally removes the range check which is nice.
> Fix always bold deadchat

- code/__HELPERS/admin.dm
- code/modules/admin/topic.dm
> Add some extra logging to approvals

- code/datums/components/squeak.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3781
> Reduces squeak volume

- _maps/map_files/Theseus/TGS_Theseus.dmm
WIP, but changes the Theseus map majorly with new looks and building content.
Adds more POLISH.
:cl:
tweak: Changes the theseus
balance: May change strategies on the theseus
/:cl:
> Theseus Changes

- code/__HELPERS/_lists.dm
- code/controllers/subsystem/ticker.dm
- code/modules/admin/verbs/centcom_podlauncher.dm
- code/modules/admin/verbs/podlauncher.dm
- code/modules/language/language_holder.dm
- code/modules/mob/dead/observer/observer.dm
> safepick proc to define

- _maps/whiskey_outpost_v2.json
Gets Whiskey Outpost to work temporarily for an event with AI xenos.
So I can test this AI xeno thing.
:cl:
add: New Json file I guess.
fix: Now its in rotation temporarily.
/:cl:
> Adds Whiskey Outpost json file.

- code/game/objects/machinery/groundmap_geothermal.dm
stops crushers completely destroying them before marines even arrive
stops crushers completely destroying them before marines even arrive
:cl:
balance: power generator can no longer be destroyed
/:cl:
> Makes the generators indestructable

- code/game/objects/machinery/computer/communications.dm
fixes #https://github.com/tgstation/TerraGov-Marine-Corps/issues/3797
Fixes answering random to a distress call
> Fix distress calls

- code/modules/admin/fun_verbs.dm
> Add flame range to custom admin bombs

- _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
Yeah I missed two rows of areas and had a synth spawn in space. Fixed that.
You won't suffocate if you enter the generator room. Also, Synth will actually spawn on the planet instead of right in space. Cool, eh?
:cl:
add: Added missing areas
del: Removed wrongly placed second synth spawn
/:cl:
> Fixes whiskey outpost

- code/__DEFINES/mobs.dm
- code/__HELPERS/mobs.dm
- code/modules/mob/living/living_verbs.dm
Replaces the `uninterruptible` arg with more specific checks in the form of bitflags.
> do_mob flags

- code/datums/gamemodes/game_mode.dm
- code/datums/jobs/job/job.dm
- code/modules/mob/new_player/new_player.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3764
> Fixes bank accounts

- code/modules/mob/living/carbon/xenomorph/say.dm
This actually addressed Terra's comments about the hiveminds name
> Bold the hiveminds name in chat

- code/__DEFINES/mobs.dm
- code/__DEFINES/traits.dm
- code/game/objects/items/scanners.dm
- code/modules/clothing/under/ties.dm
- code/modules/mob/living/carbon/human/life/handle_pulse.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_verbs.dm
- code/modules/reagents/chemistry_reagents/toxin.dm
Turns fakedeath into a trait so we can track the sources and react to its changes. Same as /tg/
> fakedeath trait

- code/modules/admin/server_verbs.dm
:cl:
admin: Admins can now issue a shutdown command mid round. It will automatically shut the server down at the end of the round.
/:cl:
> Admins can now shut the server down mid round. it will automatically shut the server down at the end of the round.

- code/modules/mob/living/carbon/human/examine.dm
All Xenos can see if an impregnated human is inoculated with Larval accelerant if examined.
:cl:
add: All Xenos can see if an impregnated human is inoculated with Larval accelerant if examined.
/:cl:
> Xeno Examine Impregnated Human - See Growthtoxin.

- code/game/objects/structures/platforms.dm
🐵 
mfw the xenos go through the platform instead of around it
:cl:
balance: Platforms are now destructible until xeno AI pathfinding is improved
/:cl:
> Makes platforms more destructible

- code/modules/projectiles/gun_attachables.dm
BC delay penalty removed, added more scatter/accuracy malus. Reduced damage bonus by 10%
BC is really bad right now, outside of shotguns. I'm going to try to make it more worthwhile or just deletus it I guess.
:cl:
balance: BC stats changed a bit. Less damage bonus but fire delay is gone! The accuracy and scatter penalties are higher though.
/:cl:
> BC changes

- code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
- code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
- code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
- code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
- code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
- code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
- code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
- code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
- code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
- code/modules/mob/living/carbon/xenomorph/charge_crush.dm
- code/modules/projectiles/ammo_datums.dm
Changes the maturity scaling of most benos. This is mostly the same as #3774 until Kuro orphaned it. So I had to do it.
Smooths the curve out for most benos. It's helpful for curbing the powertide.
:cl:
balance: A lot of beno changes. Too many to list. Check out the PR! Checkout https://github.com/tgstation/TerraGov-Marine-Corps/pull/3831 !
/:cl:
> Xeno caste changes, mostly buffs.

- code/game/objects/effects/decals/crayon.dm
- code/game/objects/items/toys/crayons.dm
- code/modules/mob/living/say.dm
Cleans up the code, adds the fun_allowed config check
:cl:
add: eating a crayons will give you a small amount of toxin damage. Mime crayons will also mute you for 30 seconds.
/:cl:
> Crayon cleanup

- code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
This is a pain to not be able to do this as an admin.
This was added as an attempt to fix hiveminds but didn't help.
> Make hiveminds right clickable again

- code/modules/shuttle/marine_dropship.dm
Fixes #3847
Previously the move topic was happening before asking, this delays that until after we are sure we want to proceed.
> Fix the canterbury launching before confirming the launch

- code/modules/shuttle/docking.dm
> Fix alamo crash not happening

- code/game/objects/explosion.dm
Now the explosion proc will actually create fires
> Fix explosion not actually creating fires

- code/modules/projectiles/gun_helpers.dm
Removes two instances of a word that violates GitHub TOS
> Something Something TG Station

- code/game/turfs/walls/wall_types.dm
New lobby art by Drawsstuff
new lobby art!
:cl: Drawsstuff
add: New lobby art
/:cl:
> New lobby art

- code/game/objects/items/storage/marine_boxes.dm
- code/game/objects/machinery/vending/new_marine_vendors.dm
Title.
newbies no longer die horribly, and they no longer die horrifically
:cl:
fix: Readded helmets to SG box
/:cl:
> Smartgunners get helmets in their boxes

- code/_onclick/drag_drop.dm
- code/modules/mob/inventory.dm
- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
- code/modules/mob/living/carbon/xenomorph/damage_procs.dm
- code/modules/mob/living/carbon/xenomorph/life.dm
- code/modules/mob/living/carbon/xenomorph/say.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
- code/modules/mob/living/damage_procs.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_defense.dm
- code/modules/mob/living/living_verbs.dm
- code/modules/mob/mob_movement.dm
- code/modules/mob/typing_indicator.dm
- code/modules/projectiles/projectile.dm
Additional cleansup updatehealth on godmode
> Fixes hivemind dying to explosions

- code/modules/projectiles/guns/pistols.dm
- code/modules/projectiles/guns/revolvers.dm
- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/guns/shotguns.dm
Title says all.
Pistols/revolvers lost QFA. Gained gyro
Rifles gain scopes.
Kuro was lazy and didn't add scopes to rifles, pistols having gyros make sense, and QFA broke the game while on pistols since it gave you 0 fire delay.
:cl:
balance: Scopes added to rifles, gyros added to handguns, removed qfa from scout shotgun and handguns
/:cl:
> Removes QFA from handguns, adds gyro to handguns and scopes to rifles.

- tools/mapmerge2/requirements.txt
There's vulnerabilities fixed in the newer version.
> [s] updates pillow requirements

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
big surprise. This time I changed up req, added an autolathe and some other things. Replaced engineering's reactor cells to full ones because it's annoying to have empty reactors and empty fuel cells at roundstart. UH some holopads and cameras too.
> Pillar stuff round something

- code/modules/clothing/masks/gasmask.dm
- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/guns/pistols.dm
- code/modules/projectiles/guns/revolvers.dm
- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/guns/shotguns.dm
- code/modules/projectiles/guns/smgs.dm
- code/modules/projectiles/guns/specialist.dm
- code/modules/projectiles/magazines/smgs.dm
All ERT and some minor guns that marines get (ppsh/mosin/88mod) get a balance overlook in this PR.
PMC sniper gains IFF so it can snipe
I fixed the 3 round burst fire meme on the Sniper.
I gave the 88Mod and Auto-9 full auto to give them more oomph
I removed the QFA from the 88mod from balance concern.
Check this chart for most of the changes
https://docs.google.com/spreadsheets/d/1te8qQTOC-bRVPyGJH55P7l-Bd4LggmUTh5XrK7dZ080/edit#gid=0
Gives most things a balance overview making them better or worse.
A lot of these guns have been left in the dust. This attempts to stop that.
:cl:
del: Deleted the PPSH light bullet, and Heavy rifle accuracy penalty. QFA on 88-Mod.
balance: A heavy overlook on most guns. Can't be put into words. Check the PR …
> Non standard weapon re-balance

- code/modules/client/preferences.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3728
stripped_input encodes the name in html.
This then got stripped by reject_bad_name.
Opt'd to just let reject_bad_name handle everything
> Fix nicknames

- code/game/objects/machinery/vending/new_marine_vendors.dm
Fixes vendors not showing a category if it used points instead of buyflags.
> Fix vendors with points and buy_flags

- _maps/map_files/Theseus/TGS_Theseus.dmm
In place of #3930 since its conflicting
> Fixes line endings

- code/modules/mob/living/living.dm
I intorduced the wrong value here a while back
> Fix dragging offsets

- code/game/objects/items/embedding.dm
- code/modules/mob/living/living_defines.dm
- code/modules/projectiles/projectile.dm
* embedded_objects is now a lazylist, one less list per living
* embedding now works properly on destroyed limbs
> Embedding fixes

- _maps/map_files/Sulaco/Sulaco.dmm
fixes the pipe showing up in chemistry, the window in engineering, and also makes the main entrance for SD a bit longer.
> Fixes some errors on the sulaco

- code/game/objects/machinery/miner.dm
> Remove rogue to_world call

- .gitignore
This allows me to generate docs locally and not have to ignore it each time.
> Add dmdoc to gitignore

- code/modules/projectiles/projectile.dm
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3899
🐒 🔧 
:cl:
fix: fixed a explosive projectile runtime
/:cl:
> Fixes the explosive projectiles runtime

- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
> Fix warrior punch spam

- code/modules/projectiles/ammunition.dm
- code/modules/projectiles/gun_attachables.dm
- code/modules/projectiles/gun_system.dm
- code/modules/projectiles/guns/energy.dm
- code/modules/projectiles/guns/misc.dm
- code/modules/projectiles/guns/pistols.dm
- code/modules/projectiles/guns/revolvers.dm
Roh asked me to 
Free mats bad
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/3983
:cl:
fix: The lathe can no longer be abused for free materials
/:cl:
> Fixes the lathe resource exploit

- code/modules/mob/living/status_procs.dm
GODMODE mobs shouldn't be getting affected by them.
> Fixes hiveminds suffering status effects

- code/modules/projectiles/gun_attachables.dm
Fixes permanent bipod slowdown
:cl:
fix: fixes bipod bug
/:cl:
> bipod aim slowdown fix

- code/game/objects/machinery/vending/vending.dm
- code/modules/projectiles/magazines/rifles.dm
fixes a small calibre error in the T29 magazine description
> Fixes error in SG magazine description

- code/_onclick/item_attack.dm
- code/game/atoms.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/projectiles/guns/flamer.dm
* Adds better logging for unarmed attacks, item attacks and thrown item attacks.
* Includes FF messages for all of them.
* Cleans up some ancient code.
* Fixes thrown items doing zero damage against anything with 1 or more armor.
> Added logging and code cleanup

- code/game/objects/items.dm
Happens when you disconnect while zooming through an item
> Fixes a zoom runtime

- code/__DEFINES/layers.dm
- code/__DEFINES/misc.dm
- code/_onclick/hud/fullscreen.dm
* Removes one sleep call in favor of a timer.
* Generally updates it to the /tg/ version, not much changes really.
> Fullscreen cleanup

- code/modules/shuttle/marine_dropship.dm
> Fixes ending the round on crash

- code/modules/goonchat/browserOutput.css
> Inverts headcoder colour on darkmode

- code/game/data_huds.dm
> Sunder hud is cleared on death

- .travis.yml
https://github.com/tgstation/tgstation/pull/51045
> Fix some of the .travis.yml lints

- code/modules/mob/living/carbon/xenomorph/abilities.dm
> fix: Thick resins causing lighting issues

- code/modules/organs/limbs.dm
1 variable change, head increased hp
better for people without helmets
if you've taken 150 brute damage and you don't have a helmet for some reason you're dead anyway.
this just means that people without helmets won't also have an effective decrease in hp by 2/3.
:cl:
balance: increased the amount of damage (100 -> 150) heads can take before decap. Hurrah for headbands!
/:cl:
> increase head max damage to 150

- _maps/shuttles/tgs_canterbury.dmm
- code/game/objects/machinery/doors/airlock_types.dm
- code/game/objects/structures/window.dm
- code/game/turfs/walls/wall_types.dm
> The Cant smooths with itself only

- code/controllers/subsystem/explosions.dm
- code/game/objects/items/defibrillator.dm
- code/game/objects/items/explosives/grenades/flashbang.dm
- code/game/objects/items/explosives/grenades/spawnergrenade.dm
- code/game/objects/items/flash.dm
- code/game/objects/items/flashlight.dm
- code/game/objects/items/implants/implantneurostim.dm
- code/game/objects/machinery/flasher.dm
- code/modules/mob/living/carbon/monkey/monkey.dm
- code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/reagents/chemistry_reactions/other.dm
This is the /tg/ standard, since it's something that can affect even things technically without eyes, like borgs.
Simple mass-replacement to need less changes during ports.
> replaces flash_eyes() for flash_act()

- code/modules/projectiles/projectile.dm
Little typo. Funny enough I had seen this issue for hard armor and fixed, but didn't notice it for soft armor.
Also fixed the feedback.
> Soft armor fix

- code/game/objects/items/storage/marine_boxes.dm
- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/magazines/rifles.dm
You only have 200 max ammo in the drums.
You only get 2 total drums rather than 3.
You have 15 pen instead of 20.
Reduces the amount of ammo you get
:cl:
balance: SG drums only have 200 rounds. You only get 2 total from the vendor. It has 15 pen instead of 20.
/:cl:
> Smartgunner changes

- code/modules/projectiles/projectile.dm
fixes bullet debug
it doesn't change anything
:cl:
/:cl:
> debug was broke

- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
p smol cleanup
Hopefully this is the inspiration for others to do more of these types of changes. 
They are small yet effective.
> smol cleanup of recurring injection

- code/modules/clothing/glasses/glasses.dm
Fixes #3537 
Missing the attack_hand for the action button
> Fixes welding googles

- code/modules/organs/limbs.dm
I used the same logic for adding than for removing flags.
Fixes #4060
> Limb flags fix

- .travis.yml
> Fix travis config warning

- code/modules/projectiles/magazines/specialist.dm
I forgot about this.
Idk cocking guns
:cl:
fix: cocking M4RA incin rounds now spits out the right caliber.
/:cl:
> Fixes the M4RA incin

- code/datums/balance.dm
Wish i didn't fuck this up twice.
> Fix balance tracker take 2

- code/game/objects/machinery/vending/vending.dm
> Fix vendored data

- code/game/objects/effects/misc.dm
My bad
Things on lower layers than the fog effect are now clickable
> Allow people to click under hidden fog

- code/game/objects/items/embedding.dm
> Fix string interpolation in embedding

- code/game/objects/objs.dm
additionally fixes some stack_traces
This was inadvertedly removed in the soft/hard armor changes.
> fix: defaults bio armor to 100 for /obj

- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/adminhelp.dm
Ported from /tg/ https://github.com/tgstation/tgstation/pull/51221
> [s] Sanitize ahelps

- code/modules/client/client_procs.dm
inspired by me laughing at @terranaut1 crashing often until he updated
:cl:
add: You now get warned about using client versions with known crash bugs
/:cl:
> Add warning for old client versions

- _maps/map_files/Sulaco/Sulaco.dmm
Southern auth machine wasn't accessible
> Fix keycard auth machines

- code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
> Add plasma drain for stealthy hunters

- code/game/objects/structures/girders.dm
Fixes #4113
fixes infinite metal from deconstructing girders
Bugs bad bugfixes good 
also I get GDP to spend
:cl:
fix: fixed infinite metal from girders
/:cl:
> Fixes infinite metal from girders

- code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
as title
boilers can use their abilities
:cl:
fix: fixes boilers being unable to make bombs
/:cl:
> lets boilers make bombs whenever they're not zoomed

- code/modules/mob/living/carbon/human/human_defense.dm
Title. 
Screech does more at point blank range and screen edge. But if you go threw walls it does way less stun and damage.
Screech bad
Stuns threw wall bad.
:cl:
balance: Screech overall does more haloss unless it's going threw a wall.
/:cl:
> Screech is more effective at point blank and screen edge, goes threw walls at *2 instead of *7..

- code/modules/clothing/suits/armor.dm
Whoever made this forgot to add bio protection to it for some reason.
survivor man never had bio armor for some reason. He should now.
:cl:
balance: Survivor armor has bio protection now.
/:cl:
> Survivor armor now has bio protection

- .editorconfig
Since we're using vsc and editorconfig anyway, might as well be right.
> Update editorconfig to our requirements

- code/game/objects/machinery/nuclearbomb.dm
I forgot to disallow users to set nuke timer lower
> Fixes nuke timer being set too low

- interface/interface.dm
Stops users going to empty webmaps
> Add a safety check to webmaps

- code/modules/admin/admin_verbs.dm
- code/modules/admin/topic.dm
Adds two new buttons
- Remove all job slots
- Remove all slots from a job
Helps with setting up custom events
:cl:
admin: updated job panel, add remove all job slots and remove all slots from a job
/:cl:
> Improve job panel

- code/modules/mob/living/simple_animal/friendly/mouse.dm
Closes https://github.com/tgstation/TerraGov-Marine-Corps/pull/4143
Reduces the frequency that mouses squeak.
> Reduce mouse squeak frequency

- _maps/map_files/Sulaco/Sulaco.dmm
fixes #4161
fixes
:cl:
fix: fixed missing link and var for the button and door for medbay Sulaco
/:cl:
> [Map Edit Fix] Fixing Sulaco's Medbay Exit

- _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
fixes #4154
fixes
:cl:
fix: fixed unpowered and locked vendors on whiskey outpost
/:cl:
> [Map Edit Fix] Fixing WO Vendors

- code/modules/modular_armor/attachables.dm
This was a bit much.
It gave you insane acid protection overall.
:cl:
balance: Mimir now only gives 20 bio/acid protection. Slows down by .2 rather than 2.5
/:cl:
> Mimir no longer gives you effecive acid and bio immunity, slows down a bit less.

- code/game/turfs/walls/walls.dm
Walls are a bit too, well, wall-y right now. So here's a bit of a reduction to their bullet and laser armor. 
I guess we'll just have to see. 
:cl:
tweak: Metal wall armor reduced
:cl:
> Wall Armor Reduction

- code/modules/projectiles/ammo_datums.dm
T-35 slug damage is reduced from 80 to 65, slowdown reduced from 4 to 2. 
It just is, deal with it. 
:cl:
balance: T-35 Slug Damage and Slowdown reduced
/:cl:
> Nerfs Shotgun Slugs

- code/game/objects/items/storage/firstaid.dm
🆑 
add: Added Labels to Syringe Cases
/🆑
Pretty self explanatory. Now Syringe Cases tell you what inside without having to shuffle between them.
> Adds Labels to Syringe Cases

- code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
Makes him faster. He really needs it.
Prae is really not in a good spot right this moment. He needs the speed.
:cl:
balance: Prae is barely slower than a spitter now, pheromones are 3/3.5/4/4.5 now.
/:cl:
> Prae is faster, has better pheros early

- code/game/objects/structures/xeno.dm
Replaces spawn for `INVOKE_NEXT_TICK`
> Cleanup a spawn in xeno doors on destroy

- _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
Fixes some windoors that are wrong.
Fixes some signs that are wrong.
Fixes
:cl:
fix: fixed whiskey outpost's windoors that were wrong
fix: fixed whiskey outpost's signs that were wrong
/:cl:
> [Map Fix] WO Signs and Windoor

- code/modules/projectiles/guns/rifles.dm
LMG got faster fire rate, better gun stats, higher slowdown to give it more a heavy weapon feel rather than an AR with more magazine size.
AR got more slowdown and lost angled grip as it basically made the carbine irrelevant.
This attempts to make the carbine more relevant by giving it auto fire and making it a faster variant of the AR. And removes its angled grip.
This changes the rifle family to be more unique amongst themselves, rather than the AR just reigning over all of them.
The Carbine now has .2 fire delay and .1 burst delay and full auto. Giving it a fast AR niche but has low overall ammo. Meaning you'll run out fast. (32 vs 50.)
The AR lost the ability to take an A-grip, and gained .1 slowdown because it had .4 before, and the a-grip made it far too fast to wield overall in my …
> Rifle family has been re-statted, carbine and lmg have been reworked.

- code/game/objects/machinery/doors/airlock.dm
> Fixes xeno powered door check

- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/magazines/revolvers.dm
- code/modules/projectiles/projectile.dm
Adds ricochet ammo for the .357
I was told the .357 was bad, now you get to feel like liquid.
:cl:
add: the .357 now has ricochet ammo
/:cl:
> Ricochet ammo for the 357

- code/datums/supplypacks.dm
- code/game/objects/machinery/vending/marine_vending.dm
Closes #4196 
These were missing from these. 
If you misclick you're not fudged out of your helmet.
:cl:
fix: Adds modular helmets to req supply packs and surplus uniform vendor
/:cl:
> Adds modular helmets to req vendors and helmets.

- code/modules/projectiles/guns/rifles.dm
DMR might've had less or more slowdown than it was supposed to due to this weird line. I think I fixed this?
Fixes the slowdown.
:cl:
fix: Slowdown on the DMR is no longer "0.05 slowdown seconds". It is now .75, as it should be.
/:cl:
> DMR no longer has weird aimslowdown values.

- code/__DEFINES/dcs/signals.dm
- code/datums/components/ai.dm
- code/game/atoms.dm
This is an attempt to allows admins to read combat logs on WO.
> Ignore combat logs for AI

- code/game/objects/machinery/computer/communications.dm
> Fixes broken computer sprites

- code/modules/power/cable.dm
Fixes 
```
David starts to fix some of the wires in David's r_leg.
David starts to fix some of the wires in David's l_leg.
```
> Fix synth limb name when repairing

- code/game/objects/machinery/autodoc.dm
Instead of visible messages, just made the autodoc speak since its basically talking anyway.
> Autodoc uses runechat

- code/game/turfs/turf.dm
LZs and the sulaco areas are now weedable.
> Allow weeds in more locations

- code/game/objects/items/cosmetics.dm
Applying facepaint makes you harder to see.
> Facepaint makes you harder to see

- code/game/world.dm
> Remove shipmap from world status

- code/_globalvars/lists/mobs.dm
- code/datums/gamemodes/game_mode.dm
- code/modules/mob/living/carbon/human/death.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/mob/living/living_health_procs.dm
> Makes bioscan code hugely faster

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
stop going into space
:cl:
fix: pillar no longer has a route into space
/:cl:
> Fix non hull pillar windows

- code/__HELPERS/unsorted.dm
- code/controllers/subsystem/shuttle.dm
Forgot to port this from my tg pr
> Load shuttles in transit level

- code/modules/modular_armor/modular.dm
This basically means you gotta remove the suit to get defibbed.
> Add conducts to modular armor

- code/modules/admin/topic.dm
This is the 2nd attempt at fixing faxes.
> Fixes empty default subject on admin faxes

- code/__DEFINES/status_effects.dm
- code/datums/status_effects/gun_skill.dm
- code/modules/projectiles/gun_system.dm
- tgmc.dme
Adds status effects that can stack and effect gun skills.
Allow us to make drugs that can buff or debuff accuracy or scatter.
> Adds status effects that can effect scatter and accuracy

- code/modules/projectiles/guns/specialist.dm
because David wouldn't shut up about it
probably not intentional
🆑 
balance: svd can no longer bust
/:cl:
> svd no longer has burst

- code/__HELPERS/ai.dm
- code/__HELPERS/game.dm
- code/datums/gamemodes/game_mode.dm
- code/modules/shuttle/marine_dropship.dm
- code/modules/shuttle/shuttle.dm
> switch some GLOBs to zlevel lists

- code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
Just fixes a few minor grammar mistakes in panther caste descriptions. You can't be "adapt" at something, after all.
muh grammur
:cl:
spellcheck: fixed typos in panther caste_descs.
/:cl:
> Fixes panther caste_descs typos

- tgmc.dme
Fixes #4250
These were previously missed on the other reagents port
> Add missing reactions

- code/modules/mob/living/carbon/xenomorph/life.dm
Small buff to sunder recovery
:cl:
balance: sunder recovery is faster while resting
/:cl:
> Buffs sunder recovery while resting

- code/__DEFINES/cooldowns.dm
- code/_onclick/item_attack.dm
- code/controllers/configuration/entries/general.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/living_helpers.dm
- code/modules/projectiles/gun_attachables.dm
- code/modules/projectiles/guns/flamer.dm
- code/modules/projectiles/projectile.dm
Ghosts and kicks anyone who goes over the configured FF amount, whenever there are no admins on the server.
Gives admins time to respond to FF events.
:cl:
admin: auto ghost and kick excessive FF offenses when no admins present
/:cl:
> Better admin controls over FF

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
> Fix APC in hanger security on ice colony

- code/game/objects/structures/razorwire.dm
Fixes #4237
Being pulled out of razorwire by someone else would never untangle you
> Fix razorwire entangle bug

- code/datums/gamemodes/game_mode.dm
> Fix empty count for round end

- code/modules/mob/living/carbon/xenomorph/emote.dm
> Fix xeno emotes

- _maps/shuttles/escape_shuttle.dmm
- code/modules/shuttle/escape_pod.dm
> Fixes exploding evac shuttles

- code/modules/mob/living/say.dm
> AI can no longer near mobs on turfs they can't see

- tgmc.dme
> Fixes admin away messages

- code/game/objects/machinery/autodoc.dm
This was an attempt at fixing #3896, but i found nothing wrong when testing.
I still did some work to clean up the procs
> Improve autodoc

- code/modules/mob/dead/observer/orbit.dm
Better tools for admins
@terranaut1
> Allow admins to find and orbit mindless mobs

- _maps/map_files/Sulaco/Sulaco.dmm
> Fix pixel_x = 0 warning on Sulaco

- code/datums/components/orbiter.dm
> Fix orbit offsets

- code/modules/atmospherics/machinery/atmosmachinery.dm
> Stop xenos vent dragging marines past fog

- code/modules/clothing/suits/marine_armor.dm
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/4286
donut said
:cl:
fix: fixed Guardsmen armor item sprites
/:cl:
> Fixes gaurdsmen icons

- code/game/objects/machinery/vending/new_marine_vendors.dm
This PR stops engineers from getting basic combat gloves 
Fixes good 
:cl:
fix: fixed engineers getting 2 kinds of gloves
/:cl:
> Fixes two engineers getting 2 kinds of gloves

- code/game/objects/machinery/vending/new_marine_vendors.dm
> Fixes gloves not vending

- code/modules/mob/living/living.dm
tg port
clarity and looks cool
:cl:
add: Your point arrows will now be "thrown" to where you pointed at
/:cl:
> Throwable points

- code/__DEFINES/dcs/signals.dm
- code/game/objects/machinery/Sleeper.dm
- code/game/objects/machinery/autodoc.dm
- code/game/objects/machinery/cryopod.dm
- code/game/objects/structures/crates_lockers/closets.dm
- code/modules/shuttle/on_move.dm
Closes #4291
Closes #4293
Theres things other than tarps this will happen for
:cl:
fix: being crushed by a shuttle gibs you now
/:cl:
> Fix mobs surviving being crushed by shuttles

- code/game/objects/structures/razorwire.dm
This PR fixes #4221 
long needed fix
:cl:
fix: hivemind no longer gets stuck in razorwire when moving over it
/:cl:
> fixes hivemind getting stuck in razorwire

- code/modules/mob/living/carbon/human/emote.dm
Yoinked most emotes tg had that we didnt
Arr pee
:cl:
add: Bunch of new emotes for humans
/:cl:
> Some more emotes

- code/modules/modular_armor/modular.dm
This PR fixes #4299
Closes #4299 
critical fix bugs bad
:cl:
fix: fixed the ability to gain super speed via exploiting detaching 1 armor piece from modular armor
/:cl:
> fixes super sayan speed modular armor

- code/modules/admin/topic.dm
stop fucking with eord
:cl:
admin: Announce to affected players when mass-bussing happens who did it
/:cl:
> Announce to affected players when mass-bussing happens who did it

- _maps/map_files/Sulaco/Sulaco.dmm
Fixes some rogue areas that were space getting you killed. (like south evac)
> Fix spaces areas in sulaco

- code/game/objects/structures/mortar.dm
Decreasesed load/targetting times slightly, range requirement, and increased the explosion radius
benos stop fobcamping pls
Hopefully mortar is less shit now
:cl:
balance: Mortar range requirement decreased
balance: Mortar explosion size increased
balance: Mortar reload and targetting times
/:cl:
> Buffs mortar 

- code/game/objects/machinery/vending/new_marine_vendors.dm
how many coders does it take to screw in a lightbulb
I ACTUALLY tested mine
:cl:
fix: actually fixed engis getting two pairs of gloves
/:cl:
> Actually Fixes the goddamn engi gloves bug

- code/game/objects/items/marine_gear.dm
Also passes damage onto the mob
> Walking on a tarp reveals it

- code/game/objects/items/storage/belt.dm
- code/game/objects/items/storage/pill_packets.dm
- code/game/objects/items/storage/pouch.dm
As per title.
Because pill packets deserved to be fixed.
:cl:
fix: Fixed certain things about pill packets.
/:cl:
> Fixes Pill Packets
