tgstation/TerraGov-Marine-Corps

- code/datums/jobs/job/shipside.dm
- code/game/objects/items/devices/tablets.dm
- code/game/objects/items/radio/headset.dm
- code/game/objects/items/storage/pouch.dm
- code/game/objects/machinery/vending/new_marine_vendors.dm
Title
Actually good to USE features you know
:cl:
fix: Headset cams will now be assigned to squad cameranets correctly
add: Gave HuD tablets to SLs, POs, FCs, and the captain
/:cl:
> Gives HuD tablets to SLs, POs, FCs, and the captain

- code/game/objects/machinery/vending/new_marine_vendors.dm
- code/modules/modular_armor/helmets.dm
- code/modules/modular_armor/modular.dm
Fixes cooldown and some spelling
:cl:
fix: fixed helmet modules not toggling
spellcheck: fixed a few typos in the modular package description
/:cl:
> Fixes modular helmets

- code/datums/elements/gestures.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/living.dm
- tgmc.dme
Allow humans to use ALT and drag middle click to do a quick callout.
Currently you have "dir", "push dir", "pull back dir".
Quicker more emergent communication
:cl:
add: Humans can now do gesture based callouts
/:cl:
https://streamable.com/5bkumk
> Add gesture based callouts for humans

- strings/tips/marine.txt
- strings/tips/meme.txt
- strings/tips/meta.txt
- strings/tips/xeno.txt
As per title; Adds more tips into the game and removes defunct tips that were since then outdated by recent updates.
Because we need more tips and we need to get defunct ones out of the players' brains.
:cl:
add: Added new gameplay tips.
del: Replaced/Removed defunct tips.
tweak: Tweaked some more tips to get better insight.
/:cl:
> Tips Galore! Adds tips and removes defunct ones.

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Fixes some bugs with species spawning and checking.
> Fix species issues

- code/modules/modular_armor/attachables.dm
As pre title, fixes only some text though.
Because people won't be blamed.
:cl:
fix: Fixed some typos for modular armor.
/:cl:
> Fixes Modular Armor II

- code/game/objects/effects/overlays.dm
- code/game/objects/items/binoculars.dm
Fucking blase dragged me out of bed at 3am for this 
The non-shitcode way
closes https://github.com/tgstation/TerraGov-Marine-Corps/pull/4363
:cl:
fix: Mortars will now fire correctly
/:cl:
> Correctly fixes turfs being deleted

- code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
title,
about 40 more hp
kuro complained about his bad hp, though I think runner might need a nerf but this is an ok start to making hunter less bad.
:cl:
balance: hunter has 40 more hp total
/:cl:
> gives hunter more hp

- code/game/objects/effects/weeds.dm
Dragging your sprite onto the weed sprite will redirect to window / frame underneath
QOL
:cl:
add: Dragging your sprite onto the weed sprite will redirect to window / frame underneath
/:cl:
> Makes climbing easier over weeds

- code/game/objects/machinery/vending/marine_vending.dm
a
Kuro please 
:cl:
add: Added facepaint to surplus vendors
/:cl:
> Add facepaint to surplus vendors

- code/modules/modular_armor/attachables.dm
- code/modules/modular_armor/helmets.dm
title
Keep it clean
:cl:
code: Moved mimir head module into the correct file
/:cl:
> Moves mimir head module into the correct file

- code/game/objects/machinery/smartgun_mount.dm
bug fixes and changes for my hmg, based on feedback and suggestion
reduces ff and the possibility of some dumbass marine shooting your beautiful gun
:cl:
balance: gave the HMG 100 more health, and 50 bullet and 100 bio armor
fix: fixed a bug in which picking up the HMG with an item in your active hand would cause it to disappear 
balance: HMG deploy and HMG pickup time increased by 2 seconds to 5 seconds
/:cl:
> HMG integrity increased by 100, added 50 bullet armor, 100 bio, and bug fix

- code/controllers/subsystem/garbage.dm
https://github.com/tgstation/tgstation/pull/51890
a
:cl:
code: GC will timeout correctly
/:cl:
> Ports tg gc timeout fix

- code/game/objects/items/weapons/shields.dm
Enables the repairing of shields, namely riot shields. They have integrity already, but were unable to be repaired. 
Now you can fix shields. 
:cl:
add: Riot Shields Now Repairable
/:cl:
> Shield Repair

- code/controllers/configuration/entries/general.dm
Mobs and so would bob around, especially noticable at higher FPSes
This was because their glide was being multiplied by 0 to always be 0
Might need a round of TMs to see if the number needs to be tweaked
ITS GOOD WHEN MOVEMENT WORKS YES
:cl:
fix: Moving things bobbing/teleporting, especially at higher FPSes, will no longer do so
/:cl:
> Gliding fix/tweak to make it actually work

- code/game/atoms_movable.dm
Caused them to go invisible as well.
> Fixes a bug in where moved ammo would change sprite

- config/config.txt
This adds more songs to the lobby music shuffle, specificially https://youtu.be/JUNROUfqJr0 and https://youtu.be/Zo60Lx5KXEI
more variaty and distinguished appearance for the game
:cl:
add:2 new and fun tracks for the lobby
/:cl:
> this makes more songs available during lobby

- code/game/objects/machinery/smartgun_mount.dm
Reduces the volume of the hmg by 10%
It was a little loud
> Reduces the volume of the hmg by 10%

- code/modules/shuttle/on_move.dm
Fixes hivemind dying to shuttles
> Fixes hivemind dying to shuttles

- code/game/objects/items/devices/tablets.dm
Increases the view range on leadership+ tablets
The tablets for SLs were increased a tile as well since feedback was it was too small.
> Buff Hud tablet view distance

- code/game/sound.dm
> Fixes bad lobby music

- code/controllers/subsystem/vote.dm
Wasn't checking if the specific value was set, only if one of the values were.
> Fix end of round map votes

- code/controllers/subsystem/mobs.dm
- code/modules/mob/living/living.dm
This smooths out mob processing load, in theory.  Will need some load testing
> Experimental mob processing smoothing

- code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
Slows down drones since they have gotten quite fast recently.
> Drone speed nerf

- code/datums/gamemodes/crash.dm
> Fixes for the crash cinematic

- code/modules/shuttle/marine_dropship.dm
Fixes the locked console on the canterbury.
> Fix Canterbury console

- code/game/objects/items/marine_gear.dm
> Fix tarp messages

- code/game/objects/machinery/vending/vending.dm
Allows you to click items on vending machines to replace them instead of drag/drop
@Alterist
> Improve restocking vending machine QOL

- code/__DEFINES/cooldowns.dm
- code/datums/components/suit_autodoc.dm
Stops ungas spamming the toggle.
> Add a cooldown to the autodoc toggle

- code/__DEFINES/cooldowns.dm
- code/game/objects/items/defibrillator.dm
- code/game/objects/items/tools/hydro_tools.dm
- code/game/objects/machinery/autodoc.dm
- code/game/objects/machinery/iv_drip.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
- code/modules/mob/living/carbon/xenomorph/death.dm
Death to rng
consistency
:cl:
tweak: Removed RNG from: IVs signalling transfusion status, Suit preventing defib, scythe clearing out plants, Hivemind announcing its under attack, Autodoc beginning and stopping procedures
/:cl:
> More prob removal

- code/datums/gamemodes/crash.dm
> Remove shuttle spawn verb

- code/modules/projectiles/guns/revolvers.dm
Tricks can also be done with two revolvers inhand
Also cleared out a piece of shitcode
https://streamable.com/ly8wvc
:cl:
add: You can now do tricks with one or two revolvers in your hand
/:cl:
> Revolvers can now do tricks

- code/modules/organs/wound.dm
yuck
yes
:cl:
code: Cleaned up wounds.dm
/:cl:
> Cleans up wounds.dm

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
sigh
Xenos in fob before drop bad
:cl:
fix: Removed vents in Ice colony LZ1
/:cl:
> Fixes the LZ1 vents on ice

- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
:cl:
fix: Prison disposals can no longer be ejected
/:cl:
> Fixes prison disposals

- code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Quick and easy
:cl:
fix: Huggers are storable again
/:cl:
> Hugger store fix

- code/modules/projectiles/guns/revolvers.dm
> Revolver trick fix

- dependencies.sh
> SpacemanDMM suite 1.5

- code/modules/lighting/lighting_corner.dm
https://github.com/tgstation/tgstation/pull/51546
free about 5%
:cl:
code: Optimized lighting
/:cl:
> Lighting optimization

- code/__DEFINES/lighting.dm
- code/__HELPERS/game.dm
- code/modules/lighting/lighting_source.dm
- code/modules/lighting/lighting_turf.dm
https://github.com/tgstation/tgstation/pull/51004
Free 16%
:cl:
code: Optimized lighting corners
/:cl:
> Lighting optimization 2

- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Special thanks to Zack for finding this
Killing the last few hugger exploits
:cl:
fix: fixed a hugger exploit
fix: hugger timers will delete themselves
/:cl:
> Hugger exploit fix

- code/modules/shuttle/marine_dropship.dm
> Stop ghosts interacting with the Canterbury console

- code/modules/admin/verbs/chat_commands.dm
Adds the round time to the bot command `!tgs check`
Would help to distinguish round progression.
> Add round time to !tgs check

- _maps/map_files/generic/Admin_Level.dmm
New EORD arena, somewhat based on a fishing village and some old ideas. Includes the Tomb of the Unknown Soldier, some fancy tiling made possible with Spooky's shuttle refactor, changes the map dimensions slightly, saving about  450 tiles of empty space. 
Old EORD arena is alright, but it's showing its age. It's also slightly bigger, so it's better for higher populations. There was an attempt at reducing the map ids so it shouldn't affect loading.
:cl:
add: New EORD arena! Shoot your enemies and PB your friends. Can you find the hidden rare weapons?
/:cl:
> New EORD Arena

- code/__DEFINES/conflict.dm
- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/gun_attachables.dm
- code/modules/projectiles/guns/flamer.dm
Some of this was awful and hard-coded causing issues for people trying to rebalance flamer
> Fix some flamer code

- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Recreates #4423 which was reverted
> Facehuggers can be removed if you're fast enough (again)

- code/modules/client/client_procs.dm
Reduces the required client version to join the server down to 513.1493
Compiling still requires a more recent version of byond to compile.
> Minimum required client version is now 513.1493

- code/modules/reqs/supplypacks.dm
Once we have a competent command going up and a person to load the OB we quickly run out of OB ammo that's quickly used up in the round.
After using up all the OB ammo there should be at least an option to order more.
:cl:
add: Added OB shells to the req console all of them cost 40 points for any type.
add: Added Solid fuel tanks aswell each one costing 15 points
/:cl:
> Adds orbital shells + solid fuel to the req list

- code/datums/jobs/job/shipside.dm
- code/datums/skills.dm
title
How hard is it towait 10 seconds for the RO to give you something. For example this screenshot is what happened after a fucking marine couldnt wait 10 seconds
:cl:
balance: The RO has a taser
/:cl:
> Gives RO a taser

- code/game/objects/machinery/vending/vending.dm
Fixes lasgun cell getting restocked and recharged for free.
> Fix stocking uncharged lasgun cells

- code/modules/mob/death.dm
- code/modules/mob/living/carbon/xenomorph/death.dm
Fixes xenos being able to instantly respawns as xeno / human.
> Fix xeno deathtimers

- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
It was already quite long
Delays are bad
:cl:
add: Hive collaspse is 5mins max down from 15mins
/:cl:
> Hive collaspse timer shortened

- code/game/objects/items/marine_gear.dm
Fix hivemind or INCORPOREAL mobs triggering the open
> Add INCORPOREAL to tarps

- code/game/objects/machinery/vending/vending.dm
When we merged https://github.com/tgstation/TerraGov-Marine-Corps/pull/4504 travis didn't run for some reason, and it was failing to compile.
This fixes that
> Fixes bad variable in vending.dm

- code/__DEFINES/admin.dm
- code/__DEFINES/equipment.dm
- code/__DEFINES/is_helpers.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/debug_verbs.dm
- code/modules/admin/holder.dm
- code/modules/mob/dead/observer/observer.dm
easier to use
:cl:
admin: replaced take over mob verb with drag ghost to mob to change ckeys
admin: improved spawn verb
/:cl:
> Ports improved spawn and ckey changing from TG

- code/game/objects/machinery/doors/airlock_types.dm
> Fixes sulaco engine room access

- _maps/_basemap.dm
- _maps/shuttles/tgs_canterbury.dmm
dont know when this broke but it did
> Fix travis not testing templates properly

- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/magazines/rifles.dm
Actually makes every other marine weapon a viable choice again.
:cl:
balance: increased wield delay by 0.3 seconds, reduced ammo capacity to 7
/:cl:
> Nerfed the T-127

- code/modules/projectiles/ammo_datums.dm
title
idk this was planned for a long time
:cl:
balance: taser now do stamina damage
/:cl:
> tasers no longer instantly stun now do stamina damage

- code/__DEFINES/dcs/signals.dm
- code/datums/keybinding/xeno.dm
- code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
- code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
- code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Allows ravs to ignore crit for 10 seconds, but can still die from too much damage
Give ravs some buttons, and allow them to go "more ham"
:cl:
add: Added new Rav ability: Ignore Pain - Allows ravs to ignore crit for 10 seconds, but can still die from too much damage.
/:cl:
> Add new Rav ability: Ignore Pain

- code/_onclick/xeno.dm
- code/datums/components/bump_attack.dm
- code/datums/gamemodes/game_mode.dm
- code/datums/round_statistics.dm
Tracking the number of bump vs normal attacks
Stats
> Add bump slash tracking vs normal attacks

- code/modules/projectiles/gun_helpers.dm
> Fix magically deleted mags during reloads

- code/modules/organs/limbs.dm
moves head hp from 150 back down to 100
decaps are basically impossible right now
this is dumb
:cl:
tweak: head health is now 100 again.
/:cl:
> give me back my decaps

- .gitignore
- code/datums/jobs/access.dm
Apparently the CL's gender was always swapped whenever they spoke into the radio. This updates one potential cause from text to the define for gender.
Resepect my pronouns
:cl: Hughgent
fix: the CL now has proper pronouns on the radio.
/:cl:
> Gender fix

- code/modules/admin/verbs/datumvars.dm
This was broken with ref tracking pr since we seem to have different systems and expectations
> Fixes view variables

- code/__DEFINES/_subsystems.dm
- code/controllers/subsystem/timer.dm
tg port
timer not break good
:cl:
code: timer priority 
/:cl:
> Adds timer priority

- code/game/objects/machinery/smartgun_mount.dm
title basically
this was way too much
:cl:
balance: HMG now can only hold 300 rounds in its boxes, or 300 clicks and 100 bursts. Rather than 700
/:cl:
> HMG now only carries 300 rounds, and not 700

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
hivelord now has heal
this caste is literal garbage lol
:cl:
balance: hivelord has drone heal now
/:cl:
> hivelord buff, now has heal

- code/_globalvars/admin.dm
Title basically.
Before we had the 30 minute respawn as a concession because of our low population. Now that we get average 50~ players we don't really need this to be so short anymore.
:cl:
balance: Marine respawn time doubled.
/:cl:
> respawning as marine is now 1 hour instead of 30 minutes

- code/modules/modular_armor/modular.dm
Made attaching stuff to the exoskeleton a lot faster
No one wants to wait three seconds each time to attach 4 things to Jaeger armor. 
:cl:
tweak: made attaching stuff to modular armor faster.
/:cl:
> Made attaching components to exoskeleton faster

- code/__HELPERS/unsorted.dm
tg port
speed
:cl:
code: Sign macro optimized
/:cl:
> Sign micro improvement

- code/game/objects/items/cards_ids.dm
might as well
sweep
:cl:
fix: Minor cleanup
/:cl:
> Cleans out some vars

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
title
:cl:
fix: Removed a stray pipe
/:cl:
> Stray ice pipe fix

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Fixes the OR2 sink
and the Req banner covering the requests console.
> Fixes small issues on pillar 

- code/game/objects/items/storage/belt.dm
apparently some new people were confused
less confuse
:cl:
fix: The G8 pouch states that it can hold drum and box magazines
/:cl:
> Updates g8 desc

- code/modules/mob/living/living_health_procs.dm
Reset sunder on rejuvenate
Admin revive should reset everything
> Reset sunder on rejuvenate

- code/modules/admin/server_verbs.dm
> Fixes wording when toggle looc

- code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
- code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
- code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
- code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
- code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
- code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
- code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
- code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
- code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
title basically
beno man squishy, this adds on average should make benos take more bullets before dying.
Ravager is ass right now.
:cl:
balance: Ravager deals 10 more damage. Every xenomorph but runner has gained 50 health.
/:cl:
> Adds 50 more health to every beno but runner, adds 10 slash damage to ravager

- code/game/atoms.dm
- code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Fixes combat logs for null entries
Huggers no longer go forever idle when thrown
throw_impact calls parent resets throwing
> A number of fixes related to huggers

- code/game/objects/items/devices/mirage.dm
- code/game/objects/machinery/vending/marine_vending.dm
- tgmc.dme
Basically its a grenade that spawns fake copies of you that run up to things
I'd make a armor module for it too but MJP has enough conflicts to deal with
It's !fun!
:cl:
add: Mirage grenade that when triggered creates fake copies of you that run up to enemies
/:cl:
> Adds the mirage grenade

- code/modules/projectiles/guns/smgs.dm
Fixes https://discordapp.com/channels/498569646014857217/500801682058379265/738519809842479217
> M39 codex update

- code/game/verbs/who.dm
Helps with adminabuse of another admin
> Add PP links in staffwho for admins

- code/game/objects/machinery/vending/new_marine_vendors.dm
title
this was merged with my changes and the sg 
:cl:
fix: you no longer get the powerpack from the fc vendor
/:cl:
> removes the powerpack from the fc vendor

- code/game/objects/structures/stool_bed_chair_nest/bed.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/4588
> Add buckled signal to the medievac bed

- code/game/objects/items.dm
- code/game/objects/items/storage/storage.dm
> Hotfix for the thing

- code/game/atoms_movable.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/organs/limbs.dm
- code/modules/organs/organ_internal.dm
Less harddels good
Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.
:cl:
fix: Cleaned up some refs
/:cl:
> Cleans up some refs

- code/datums/gamemodes/crash.dm
Thought i fixed this before, but no i missed the one important bit...
> Fix crash nuke

- code/__HELPERS/qdel.dm
https://github.com/tgstation/tgstation/pull/52810
no
:cl:
fix: fixed lazylist qdelling
/:cl:
> Qdel macro fixes

- code/modules/modular_armor/storage.dm
Seems logical
Should see more use and break up the magazine/IS monotony
:cl:
balance: Engi jaeger pouches can hold tools
/:cl:
> Tools can be held in engi jaegers

- code/modules/admin/debug_verbs.dm
- code/modules/mob/living/carbon/xenomorph/update_icons.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Fixes runtimes related to atom proccalls and null wounds
> Fixes runtimes related to atom proccalls and null wounds

- code/modules/power/port_gen.dm
Max sheets set to 10
30s max per sheet
Generators are OP.
:cl: 
balance: nerfs the pacman
/:cl:
> Nerfs the pacman

- code/modules/lighting/lighting_source.dm
Ports https://github.com/tgstation/tgstation/pull/51943
> Fixes lighting updates from opaque objects state change

- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/keybinding_init.dm
- code/modules/unit_tests/spawn_humans.dm
- code/modules/unit_tests/spawn_xenos.dm
- code/modules/unit_tests/unit_test.dm
- code/modules/unit_tests/xeno_logical_scaling.dm
Adds more unit tests
Catch errors quicker
:cl:
code: Added more units tests
/:cl:
> Add keybinding and xeno logical scaling unit_test

- _maps/map_files/Sulaco/Sulaco.dmm
Fixes duplicate pipes.
Less errors.
Closes #4398
:cl:
fix: Fixed some duplicate pipes on the Sulaco
/:cl:
> Sulaco Pipenet Fix

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
FC should have no SG
Tazers are as reccomended by psy in whatever tazer PR it was again
:cl:
balance: Removes SG in the POS and adds tazers to POS armoury
/:cl:
> Removes FC SG (again(again)) and adds tazers to POS

- code/game/objects/machinery/vending/marine_vending.dm
One line PR designed to add the sexiest shotgun in the game to Req. It isn't beautiful because it outperforms other shotguns or is OP, it's beautiful because of the sounds and overall aesthetic. 
:cl:
add: Added the Paladin-12 pump shotgun as an alternate choice for marines.
/:cl:
> Adds paladin to req weapons vendor

- code/modules/reqs/supplypacks.dm
Fixes mimir helmet order giving the wrong module
Merge my prs pls
:cl:
fix: Fixes mimir helmet order giving the wrong module
/:cl:
> Mimir helmet fix

- code/game/say.dm
Should fix all marines being PVTs when talking and having the proper rank when emoting with the paygrade PR
:cl:
fix: fixed paygrades
/:cl:
> Fixes paygrade texts

- code/datums/weather/weather_types/acid_rain.dm
- code/datums/weather/weather_types/ash_storm.dm
- code/datums/weather/weather_types/sand_storm.dm
Interesting
How about we dont gib people
Forgot to do the probability changes earlier
Slightly nerfed it since it was catching a lot of people offguard with its strength
:cl:
balance: Nerfed storm damage and slightly decreased probability f harmful storms
fix: fixed storms gibbing people
/:cl:
> Fixes weather gibbing and other handy tweaks

- code/modules/modular_armor/helmets.dm
can
yes
:cl:
fix: Modular helmet icons will update on use correctly
fix: Modular helmet binoculars will deactivate correctly
fix: Modular helmet welding helmet will update tint correctly
/:cl:
> Assorted modular helmet fixes

- code/__DEFINES/layers.dm
- code/datums/chatmessage.dm
- code/modules/mob/mob.dm
- code/modules/mob/say.dm
https://github.com/tgstation/tgstation/pull/52959
https://github.com/tgstation/tgstation/pull/52584
yes
:cl:
add: Tame-ased runechat layering
fix: Runechat emotes will now not show correctly
/:cl:
> Ports various runechat stuff

- code/modules/admin/panels/mode_panel.dm
- code/modules/admin/topic.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
- code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
- code/modules/mob/living/carbon/xenomorph/evolution.dm
- code/modules/mob/living/carbon/xenomorph/login.dm
- code/modules/mob/living/carbon/xenomorph/logout.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Might want to consider bumping the savefile version to reset xeno names but I wanna hear admins thoughts on that first
:cl:
add: Xenos now have IC names
admin: ...yes you have to follow naming rules
/:cl:
> Xeno IC names

- code/__HELPERS/type2type.dm
https://github.com/tgstation/tgstation/pull/53035
> type2path fix

- code/modules/recycling/conveyor2.dm
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/4717
also changed proc/update to update_icon()
Solves scooby-doos newest mystery
:cl:
fix: fixed conveyor switches being interactable and slightly changes conveyor code
/:cl:
> Fixes conveyors

- code/_onclick/drag_drop.dm
closes https://github.com/tgstation/TerraGov-Marine-Corps/pull/4736
Fixes not being able to show inventory.
> Fix showing inventory

- code/datums/jobs/job/job_exp.dm
- code/datums/jobs/job/marines.dm
Squad marine playtime ranks
Recognition for your playtime
:cl:
add: Squad marines now rank up from E1 to E3 based on playtime
/:cl:
> PFC paygrades based on playtime

- code/game/objects/structures/razorwire.dm
Title, change stuff to use welder_act and so instead of attackby
yes
:cl:
fix: Razorwire can no longer be repaired when it's at full health
code: cleaned up razorwire code a bit
/:cl:
> Razorwire can no longer be healed when it is at full/cleanup

- code/controllers/configuration/entries/game_options.dm
- code/modules/client/client_procs.dm
- config/config.txt
tg port
:cl:
add: Config for changelog to automatically open if theres new changes
/:cl:
> Ports agressive changelog

- _maps/map_files/LV624/LV624.dmm
- code/game/area/lv624.dm
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/4716
less dyin good
also readded ambience that was commented out for some reason
:cl:
balance: LV has more rainproof areas and more accurate areas
/:cl:
> Adds more cover to lv

- code/game/say.dm
Radio code is yucky
fix
:cl:
fix: Paygrades will display on comms correctly
/:cl:
> Fixes paygrades on comms

- code/game/objects/structures/orbital_cannon.dm
- code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Raises the cool down on ravagers charge and raises the plasma cost (6 seconds to 10, 250 plasma to 300 plasma)
Ravager got a health buff of 50+ so their engage/disengage ability should be tweaked
:cl:
tweak: Raises the cool down on ravagers charge and raises the plasma cost (6 seconds to 10, 250 plasma to 300 plasma)
/:cl:
> Nerf's ravager charge CD and raises the plasma cost

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Adds the missing Surplus Vendor.
:cl:
fix: Adds missing surplus clothes vendor to PoS.
/:cl:
> PoS Surplus Vendor

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Fixes a few walls, surplus vendor.
Mistakes were made.
:cl:
fix: PoS walls.
/:cl:
> Actual PoS Fixes

- code/game/objects/structures/orbital_cannon.dm
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/4759
:cl:
fix: fixed ghosts using OB consoles
/:cl:
> Fixes Ob exploit

- code/game/objects/effects/acid_hole.dm
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/4766
:cl:
fix: fixed crawling through walls with shutters on them
/:cl:
> fixes crawling through holes with shutters

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
More spacious canteen, minor fixes.
Please let this be the last one.
:cl:
tweak: More PoS stuff
/:cl:
> PoS Stuff (Again)

- code/modules/client/preferences_savefile.dm
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/4694
Since this is a preference change, do not TM. 
If you want to test it, test it locally.
> Add savefile entry for missing keybindings

- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Changes an incorrectly placed area.
Fixes mistakes I made.
:cl:
fix: Fixed an area in Prison. The APC now actually works.
/:cl:
> Prison APC/Area Fix

- tools/hooks/dmi.merge
- tools/hooks/pre-commit.hook
- tools/hooks/python.sh
- Update precommit hooks to work in GitHub Desktop (https://github.com/tgstation/tgstation/pull/51404)
- Skip app execution aliases when searching for Python (https://github.com/tgstation/tgstation/pull/53569)
> Make precommit hooks more robust

- code/modules/projectiles/guns/specialist.dm
decreases fire delay on the GL to 1.2, just long enough that you won't have two out at once
nerfs movement speed a bit as compensation
Makes the GL less shit by giving it a place as an offensive machine instead of being inferior to even the single shot GL due to fire delay
:cl:
balance: buffed GL firerate
balance: nerfed GL wielded speed
/:cl:
> buffs GL firespeed, reduces movepeed

- code/modules/reqs/supply.dm
Added dropship access also for lowpop
fix + less ungas buyin dumb stuff
:cl:
balance: Added slightly more access to cargo console
fix: Req consoles will now check for access correctly
/:cl:
> Supply consoles are now locked properly

- code/datums/armor.dm
one less number in the list
:cl:
code: Fully removed magic armor
/:cl:
> Removes magic armor

- code/controllers/subsystem/processing/slowprocess.dm
- code/game/turfs/walls/resin.dm
- tgmc.dme
Puts them not on ssobj and instead on a slower processing ss so they dont clog up ssobj
also checks that timers arent spammed
:cl:
code: regenning walls process better
/:cl:
> Makes regenning walls slightly less bad

- _maps/map_files/Sulaco/Sulaco.dmm
Req shutters now face the right way.
Firing Range objects moved a bit.
Engine made a bit prettier.
Will the Sulaco ever be finished?
:cl:
tweak: More Sulaco tiles
fix: Sulaco req shutters
/:cl:
> Sulaco Shutter Fix +Minor Changes

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Adds a Booze-o-mat to the CL's quarters.
Hides 5 bottles of vodka on the ship.
Demkova kept pestering me about it
More booze is good(?)
:cl:
add: Booze-o-mat Vendor in CL's quarters on the Pillar
add: 5 hidden bottles of vodka on the Pillar
/:cl:
> Pillar of Spring - Alcohol

- SpacemanDMM.toml
mhmm tg port
also todo enable dissalowing relative pathing in a later pr
:cl:
code: DMDoc will use typepaths
/:cl:
> DMDoc will use typepaths

- code/game/objects/structures/tables_racks.dm
What it says
Shameless bar buff
:cl:
add: clicking on tables with items will now place them where you click
/:cl:
> Table pixel offset

- code/datums/elements/scalping.dm
- code/game/objects/items/weapons/blades.dm
- code/modules/projectiles/gun_attachables.dm
- tgmc.dme
It's a Element
Also cleaned up some bayonet shitcode
Mhmm yes
:cl:
add: Machetes and Knives can now be used to scalp dead xenos
/:cl:
> Xeno scalping

- code/modules/projectiles/guns/rifles.dm
0.5 slowdown to 0.4 and adds angle grip to it's attachment list.
T-12 should be able to kill secure as reliably
:cl:
tweak: 0.5 slowdown to 0.4 and adds angle grip to it's attachment list.
/:cl:
> Buffs T-12's wield slowdown and adds angle grip to it's attachments

- code/datums/skills.dm
Captain while still a shipside role is a strong role, they have many years in training and had to have shown skill in all aspects, in order to get that promotion to Captain.
More people playing captain.
:cl:
balance: captain got a buff in skills.
/:cl:
> Buff captain skills

- code/datums/emergency_calls/emergency_call.dm
shush'd
agony
:cl:
fix: fixed linter error
/:cl:
> Makes linter shut up by fixing it

- code/datums/chatmessage.dm
- code/game/say.dm
- code/modules/mob/say.dm
From Citadel Station's [#12487](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12487)
**Because** _why_ `not`?
:cl:
add: You can now emphasis in the say verb. By || italics ||, ++ bold ++ or __ underline __
/:cl:
> Text Emphasis (CitMain Port)

- code/datums/elements/scalping.dm
agh
:cl:
fix: You will now only scalp when on harm intent
/:cl:
> Scalping fix

- code/modules/reqs/supply.dm
Mhm
:cl:
fix: STs can use req consoles again
/:cl:
> STs can use req consoles again

- code/game/objects/structures/dropship_equipment.dm
You're welcome carnus
:cl:
tweak: dropship table will layer consistently and will relay clicks by powerloaders
/:cl:
> dropship table will layer consistently and will relay clicks by powerloaders

- code/game/objects/structures/misc.dm
Buckets can now be slashed
Xenos foiled by a fucking BUCKET yet again
:cl:
tweak: Buckets can now be slashed
/:cl:
> Buckets can now be slashed

- code/datums/jobs/job/marines.dm
- code/datums/jobs/job/shipside.dm
Might want to tweak the hours, idk
Captain, Corpsmen, smartgunners, engineers and squadleads now have playtime based paygrades
:cl:
add: Captain, corpsmen, smartgunners, engineers and squadleads now have playtime based paygrades
/:cl:
> Captain, corpsmen, smartgunners, engineers and squadleads now have playtime based paygrades

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
No more spacewalks
:cl:
fix: fixes pillar having destructible walls
/:cl:
> fixes pillar having destructible walls

- code/game/objects/items/reagent_containers/pill.dm
- code/game/objects/items/storage/firstaid.dm
- code/game/objects/items/storage/pill_packets.dm
Adds the leporazine packet and adds it to the fire medkits.
Gives them something different.
:cl:
add: Added leporazine packets to the fire medkit in place of a advanced burn kit.
/:cl:
> Replaces one of the ointments in the fire medkit with a leporazine packet

- code/_globalvars/lists/client.dm
- code/modules/client/client_procs.dm
fixes woopsie ,probably was causing issues
:cl:
fix: fixed asset oversight that probably broke things
/:cl:
> Removes legacy asset glob

- code/controllers/subsystem/points.dm
https://github.com/tgstation/TerraGov-Marine-Corps/issues/4857
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/4857
:cl:
fix: Fixes space amazon denying your request across the mortal barrier
/:cl:
> Fixes space amazon denying your request across the mortal barrier

- code/game/objects/structures/xeno.dm
No more red beno  swarm
:cl:
fix: Fixes screenwide red xenos
/:cl:
> Fixes screenwide red xenos

- code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
the person that made them from suits to backpacks forgot to add a (src)
1.5 year old bug gone, now you can be stylish
:cl:
fix: fixes officer cloaks not spawning in officer lockers
/:cl:
> fixes officer cloaks not spawning in officer lockers

- code/datums/gamemodes/offduty.dm
bad copypaste
stinky
:cl:
fix: fixes offduty gamemode process
/:cl:
> fixes offduty gamemode process

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
This should probably also be fixed in linter
:cl:
fix: Fixes linter throwing an error in a code block
/:cl:
> Fixes linter throwing an error in a commented code block

- code/modules/organs/limbs.dm
Snow said it was bugging em so eh
Spellig
:cl:
spellcheck: fixed an unrecognizable mess type
/:cl:
> Adds an an to unrecognizable mess

- code/datums/jobs/squads.dm
it forgot to actually get the guy's skills to change them
year old bug bad
:cl:
fix: fixes acting squad leaders not getting order abilities
/:cl:
> fixes acting squad leaders not getting order abilities

- code/game/objects/machinery/sellingpad.dm
this should probably be less snowflake but its good enough
oversight fix
:cl:
fix: you can sell embryos on asrs pad now
/:cl:
> asrs pad also includes embryos now

- code/game/atoms.dm
On paper this should increase render speeds a decent margin without changing functionality
Needs testing on the server to see the impact and see if there any bugs
:cl:
code: Rendering is faster, server crashes will happen less
/:cl:
> Experimental maptick optimization

- _maps/map_files/debugdalus/tgs_debugdalus.dmm
new version of debugdalus (the test map)
it's twice as small but has more densely packed stuff, so your spaceman doesnt have to move as much
the current one is kinda too vast and empty, this one is more densely packed, takes less space and has updated stuff
:cl:
add: adds a new version of debugdalus
/:cl:
> adds a new version of debugdalus

- code/game/objects/items/binoculars.dm
you can now switch binocular mode with altclick, also does early returns
makes them less archaic to use
:cl:
tweak: you can now switch binocular mode with altclick
/:cl:
> you can now switch binocular mode with altclick

- code/modules/projectiles/gun_system.dm
what the title says, its apparently a deliberate feature i dont know why exists so it would be better to testmerge it to see if something breaks maybe
closes #4867
isss duuumb
:cl:
tweak: underbarrel attachments now dont deactivate on pb
/:cl:
> underbarrel attachments now dont deactivate on pb

- code/datums/looping_sounds/weather_sounds.dm
less loud
Imagine complaining and not just doing a oneline change
:cl:
tweak: Makes some weather slightly quieter
/:cl:
> Makes some weather slightly quieter

- code/game/objects/items/devices/tablets.dm
SLs should be able to actually hold their standard equipment
:cl:
balance: Makes hud tablets smaller
/:cl:
> Makes hud tablets smaller

- code/game/objects/structures/xeno.dm
Considering it needs a hivelord or queen to place it it should have a decent duration for its worth
:cl:
balance: Buffs jelly from 12 to 15 seconds duration
/:cl:
> Buffs jelly from 12 to 15 seconds duration

- code/game/objects/items/binoculars.dm
fixes this
code suggestion moment
oh no
:cl:
fix: fixes tac binos verb
/:cl:
> fixes tac binos verb

- code/game/objects/items/storage/pouch.dm
Title
Makes it a bit more unique, and hopefully slightly more runnable.
:cl:
tweak: tweaked general pouch to max storage space rather than slots
/:cl:
> generic pouch changed to work from slots to max storage space

- code/datums/gamemodes/distress.dm
Changes an M to an X
I'm blind and didn't change this in the previous PR.
:cl:
fix: Xenos now actually get a minor victory on hijacking
/:cl:
> Victory Condition Fix

- code/_onclick/hud/radial.dm
- code/controllers/subsystem/weeds.dm
- code/game/objects/effects/weeds.dm
- code/game/objects/objs.dm
- code/game/turfs/turf.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
- code/modules/mob/living/living.dm
All mobs with armor were hard deling
all objs with armor were hard deling
all turfs with armor were hard deling
fixes weed nodes hard del, sorta
fixes hivemind hard del
fixes radial menu hard dels
fixes acid hard deling when on objs
Lag bad
:cl:
fix: Fixes a lot of bad garbage collection, game should be even faster
/:cl:
> Fixes a lot of bad garbage collection

- code/modules/modular_armor/armor_pieces.dm
grr
rrgf
:cl:
spellcheck: fixes things being called jaegger
/:cl:
> fixes things being called jaegger

- _maps/map_files/Sulaco/Sulaco.dmm
SO Lockers on the bridge.
They were missing from the map.
:cl:
add: SO lockers on Sulaco bridge.
/:cl:
> Add SO Lockers to Sulaco

- code/game/turfs/turf.dm
https://github.com/tgstation/tgstation/pull/54245
:cl:
fix: Fixes shuttle memory leak
/:cl:
> [s] Fixes shuttle memory leak

- code/modules/mob/mob_verbs.dm
whee
:cl:
tweak: You can respawn when in crit in eord
/:cl:
> You can respawn when in crit in eord

- code/controllers/subsystem/overlays.dm
https://github.com/tgstation/tgstation/pull/53787/files
:cl:
code: overlays use less memory
/:cl:
> Overlay list fix port

- code/modules/clothing/gloves/marine_gloves.dm
- code/modules/clothing/shoes/marine_shoes.dm
Raises Glove/Boot Armour.
Less frequent delimbing.
help how do I stop github from tagging my other account in every PR I make
:cl:
tweak: Raises glove/boot armour.
/:cl:
> Raises Glove/Boot Armour

- code/modules/clothing/suits/marine_armor.dm
title
kuro and a few others asked
:cl:
tweak: tweaked pas vest to be old medium armor sprite
/:cl:
> Replaces the PAS vest sprite with the old medium armor sprite

- code/modules/admin/verbs/faxes.dm
One letter added.
Spellcheck good.
:cl: Wayland/AIIA
spellcheck: Fixed a typo in fax logs.
/:cl:
> Fixes a spelling mistake in fax logs

- _maps/map_files/BigRed_v2/BigRed_v2.dmm
- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
- _maps/map_files/LV624/LV624.dmm
- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
- _maps/map_files/icy_caves/icy_caves.dmm
Adds LZ numbers that only magmoor had to every major map.
easy to know now what LZ is what
:cl:
add: adds LZ number to every major LZ
/:cl:
> adds LZ numbers to every(major) Map LZ

- code/datums/emergency_calls/pmc.dm
Fixes a spelling error in the PMC smartgunner intro text.
:cl:
fix: PMC smartgunners are no longer sent from Nanostrasen, so we can no longer avoid paying them.
/:cl:
> Fixes PMC spelling error

- code/modules/clothing/shoes/miscellaneous.dm
Clown shoes now appear when worn. Closes #5005 
Is it?
:cl:
fix: Clown shoes now appear when worn, honk!
/:cl:
> Clown shoes now appear on mob

- code/modules/reqs/supplypacks.dm
Increases minigun req cost from 60 to 80, in line with other spec weapons.
It's getting ordered nearly every round, so I'm revisiting.
:cl:
tweak: We appear to be running low on miniguns, so have increased their cost accordingly.
/:cl:
> Increases Minigun Cost

- code/datums/fluff_emails.dm
Forth -> Fourth
We no longer measure snowsuit storage in measurements from outside this reality.
:cl:
spellcheck: We no longer use the fifth dimension to store our cold-weather gear.
/:cl:
> Go Fourth and Conquer

- code/game/objects/items/storage/backpack.dm
- code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
- code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
- code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
- code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
Fixes spelling errors, profanity, and removes weird meta references.
Watch yo profanity
bruh how many times will I have to fix forth/fourth
:cl:
spellcheck: Xenos descriptions are now more accurate. The Captain's cloak is now opulent.
/:cl:
> Fixes Xenos Descriptions

- code/modules/organs/pain.dm
- strings/tips/xeno.txt
Fixes typos relating to the highest pain and the xeno tip.
Because.
:cl:
spellcheck: Fixed a few typos relating to pain and xeno acid.
/:cl:
> Fixes some typos

- code/modules/keybindings/bindings_client.dm
Changes a **for** loop conditional to prevent it from throwing `list index out of bounds`
Error bad. Fix Good.
:cl:
fix: Fixed a list index out of bounds runtime related to keybinds.
/:cl:
> Fixes the /client/keyUp: list index out of bounds runtime when using ESC key

- code/game/objects/structures/xeno.dm
- code/modules/projectiles/guns/flamer.dm
hate firecode
:cl:
fix: Jelly will properly fully protect you from fire and more fixes
/:cl:
> Jelly will properly fully protect you from fire and more fixes

- .github/update_tgs_dmapi.yml
Runs every UTC midnight, makes a PR if there's an update
Sample: https://github.com/Cyberboss/tgstation/pull/15
This repo is way out of date (v4 vs current v5), you should carefully look at the first PR
> Adds automatic TGS DMAPI updates

- code/modules/goonchat/browserOutput.dm
Unnecessary with new update to byond
:cl:
fix: fixed a fix
/:cl:
> Removes the bad thing

- _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Adds missing shutters to Magmoor.
Shutters good.
:cl:
fix: Added missing shutters to Magmoor
/:cl:
> SmolMoor now featuring shutters

- code/modules/reagents/reagents/medical.dm
title basically
its either this or delete them
:cl:
balance: rebalanced radiation medication to rapidly heal toxin damage at the cost of doing brute damage to you
/:cl:
> makes radiation medication rapidly cure toxins at the cost of damage

- code/modules/mob/living/carbon/xenomorph/abilities.dm
I am going to stab splinter with a rusty nail for using a space
:cl:
fix: Hvemind can weed again
/:cl:
> Fixes hivemind weeding

- code/game/objects/items/stacks/sheets/glass.dm
- code/game/objects/structures/barricade.dm
- code/game/objects/structures/window.dm
SPOOKY PLEASE STOP PINGING ME
closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/4791
:cl:
fix: fixed being able to build directional glass on barricades
refactor: standardized glass code
/:cl:
> Refactors glass

- code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
This PR adds a cooldown to throwing huggers
Tivi wanted this
:cl:
balance: there is now a cooldown to not just drawing and throwing but also throwing huggers alone
/:cl:
> adds a cooldown to throwing huggers

- code/datums/components/orbiter.dm
Fixes a seldom called signal handler error. (of my own making~)
Changes the proc to properly handle the incoming arguments. The second of which is just a number.
I noticed it while I was testing and dragging my ghost into mobs.
Debugging is like being a detective, but you are also the culprit sometimes.
:cl:
fix: Fixed a runtime related to ghost movement.
/:cl:
> Fixes a seldom called ghost glide_size signal handler error

- code/__DEFINES/access.dm
- code/datums/jobs/access.dm
- code/datums/jobs/job/shipside.dm
Gives FC scaling ranks and adds a MO-4 rank. I didn't add a MO-3 because in the structure we used off (based off the US) it'd be captain and that'd confuse the crap out of most people probably
field commander has scaling ranks which makes it consistent with the video game and stuff so you can tell if someones played it too much
:cl:
add: Added scaling fc ranks
/:cl:
> Gives field commanders ranks and adds a marine o5 rank 

- code/datums/jobs/job/marines.dm
the ultimate reward that darius and David asked for if you play way too much tgmc (1000 hours)
the ultimate reward to ~~laugh at people who play way too much~~ REAL determined gamers.
:cl:
add: Added cool rank to squad marine if you play a ton. 
/:cl:
> Gives PFC a secret rank if you play way too much tgmc

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
Tivi is a big stupid doo doo head
> Hivelord bracket fix

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
Reverts tgstation/TerraGov-Marine-Corps#5120
Nice instant selfmerge now do it properly
> Revert "Hivelord bracket fix"

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
Properly now
Travis fails no more, at least not via the master being wrong.
:cl: Hughgent, Tiviplus
fix: Travis no longer fails always.
/:cl:
> Fixes the problem travis was having with the master

- code/datums/weather/weather_types/sand_storm.dm
What it says
sounds neat
:cl:
add: Sandstorms are now telegraphed with a siren
/:cl:
> Sandstorms are now telegraphed with a siren

- code/modules/mob/living/living_defense.dm
#fuckfirecode
Jelly properly useful
:cl:
balance: Resin Jelly will now stop xenos from igniting
/:cl:
> Jelly will now stop xenos from igniting

- code/__DEFINES/layers.dm
- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Its not that hard to make them less bad you know
:cl:
fix: fixed huggers layering under south facing barricades
/:cl:
> Facehuggers will layer over everything

- code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
title
david asked, proper ammo
:cl:
fix: fixed p90s spawning in mr25 closets
/:cl:
> pmc smg cabinets spawn proper mr25s

- code/modules/shuttle/computer.dm
- code/modules/shuttle/ert.dm
ERT shuttles were a problem
:cl:
admin: Logs shuttle launches
/:cl:
> Logs shuttle launches

- _maps/map_files/icy_caves/icy_caves.dmm
Adds shutters to LZ2.
I MAY have forgotten to re-add the shutters during my last PR.
:cl:
fix: Added shutters to Icy Caves LZ2
/:cl:
> Icy Caves LZ2 Shutter Fix

- code/datums/jobs/job/survivor.dm
- code/modules/clothing/head/hardhat.dm
survivor now have a survival knife and hardhat for lite
its flavorful and survivor need help real bad
:cl:
balance: survivor has survival knife and hard hat on non cold maps
/:cl:
> Gives survivor a knife and hard hat

- code/game/objects/effects/decals/Cleanable/humans.dm
- code/game/objects/effects/spawners/modularmappingspawner.dm
dont qdel things before they init and dont qdel(src) in your own init.
> Fix atom init issues

- code/__DEFINES/actions.dm
- code/_onclick/click.dm
- code/datums/actions/xeno_action.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
- code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Avoid the abilities having to do this individually
:cl:
add: Some xeno abilities should be easier to target mobs.
/:cl:
> Make xeno abilities easier to target

- code/__DEFINES/dcs/signals.dm
- code/modules/mob/living/carbon/xenomorph/attack_alien.dm
- code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
This doesn't add anything that can bypass shields but its been requested to make it possible to have abilities able to bypass shields.
I've also added the ability to bypass armor as a byproduct.
There was what looks like a bug where hunter sneak attack with disarm intent wasn't applying the pain bonus properly, I've fixed that but may need feedback on if this should just be removed.
> Allow xeno attack code to bypass shields

- code/game/objects/items/reagent_containers/autoinjectors.dm
- code/modules/reagents/reagents/medical.dm
makes hydrocodone work, and changes it from an oxycodone clone to more of an emergency painkiller meant to keep you going for a little while.
It has 4 OD threshold and the b18 seems to consistently give you 2, which should be enough for at least 2-3 ticks of nearly full pain resist and tramadol will carry you.
Hydrocodone actually works. And does something. Makes it more of an actual chem rather than whatever it is.
:cl:
balance: hydrocodone actually works, has a 4u overdose limit and metabolites very quickly.
fix: fixed hydrocodone not working
/:cl:
> Hydrocodone changes, makes it actually work

- code/__DEFINES/preferences.dm
17 is cringe and makes little to no sense.
something something underage marine makes no sense bad
:cl:
tweak: minimum marine age is 18
/:cl:
> makes the minimum age of marines 18

- code/modules/projectiles/ammunition.dm
- code/modules/reqs/supplypacks.dm
Fixes #5116 
You can now order boxes specifically full of Machine Pistol ammo
:cl: Hughgent
fix: T-19 ammo now available in requisitions
/:cl:
> Adds T-19 ammo to supply pack

- _maps/map_files/Theseus/TGS_Theseus.dmm
Fixes #4870 
As the title
:cl: Hughgent
fix: moves the viro closet to not block the door in research
/:cl:
> moves a viro closet over two tiles on Theseus

- _maps/map_files/Sulaco/Sulaco.dmm
Prep, cryo, req, medbay, and the memorial moved to the bottom floor.
Telecomms, pilot's bunk, CL's office, morgue, and research moved to the top floor.
All the important stuff is on the same floor. No longer do you need to drag a ton of crates up and down ladders.
:cl:
fix: Sulaco's important things are on the bottom floor
/:cl:
> Sulaco Rework (Again)

- code/modules/xenomorph/xeno_structures.dm
Silos spit out corpses used to create them when destroyed.
Fixes the issue with corpses being used in the silo vanishing into the void.
:cl:
fix: When destroyed, resin silos drop the corpses used to create them
/:cl:
> Resin Silo Corpse Fix

- code/modules/reagents/reagents/medical.dm
This medicine never functioned normally.
This medicine will now properly function
:cl: Hughgent
fix: Hyronalin will now function normally
/:cl:
> Typepath fix for Hyronalin

- code/game/objects/effects/aliens.dm
god this is still pretty bad but at least its not directly calling crossed()
> Minor refactor of acid spray crossed

- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Removes the shitty light in the wall in middle of screen.
Bad Light
:cl:
fix: Removes a light in a wall on prison
/:cl:
> Removes light in wall on prison

- code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
Fixes the castedatum's `actions` lists broken by a combination of recent splitting by maturation and the addition of headbite.
:cl:
fix: Fixed bug with Bull gaining and losing the wrong abilities when aging.
/:cl:
> Fixes Bull losing headbite and headbutt abilities from aging

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
- _maps/map_files/Sulaco/Sulaco.dmm
title
people probably forgot this even existed
:cl:
fix: fixed cl not getting their briefcase on sulaco/pos
/:cl:
> adds the cl briefcase to the sulaco/pos

- code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Time to get familiar with the audodoc github-pages thing.
removed two variables as they were not being referenced or used anywhere in code.
`acid_delay`
`tackle_chance`
minor bugfixes found when going through this.
:cl: Hughgent
fix: defender fortify on ancient now just as good as elder.
/:cl:
> Xenomorph caste documentation

- code/game/objects/machinery/vending/marine_vending.dm
- code/modules/clothing/suits/marine_armor.dm
Back by popular demand. the harness.
For those who seek it out. They can have the bragging rights they so desire.
:cl: Hughgent
add: Back by popular demand, the harness is available again in the surplus equipment vendor.
/:cl:
> Re-Adds the Harness to the game, via surplus equipment vendor.

- code/_globalvars/lists/ai_nodes.dm
- code/datums/components/ai.dm
Implements a hardcap of 100 AI instances at most to exist.
Stops admins from DoSing the server
:cl:
tweak: The admins can now only spawn so many things with AI attached overall
/:cl:
> Implements a hardcap towards spawning AI

- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Stuns bad, time to kill some CC
PART 4-
Warrior
NERFS
Fling stun time halved
Compensation (If any)
Warrior is fine as it is, it has decent stats and decent overall stuff. I could give it more health I guess, but run makes it incredibly safe.
Stuns bad, death to the stuns.
Read compensaton.
:cl:
balance: Warrior fling time halved
/:cl:
> Stun changes part 4 - warrior

- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
gives sentinel the ability to spit acid
sentinel is kinda a bad case right now, it'd be nice to make it a tad bit better, this gives it more versatility, i can reduce the damage if its too oppressive.
:cl:
balance: gives sentinel the ability to spit light acid
/:cl:
> gives sentinel the ability to swap to light acid spit

- code/modules/surgery/surgery.dm
/ to .
:cl:
fix: Fixes a surgery callback
/:cl:
> Fixes a surgery callback

- code/modules/mob/living/carbon/xenomorph/abilities.dm
Lots of people want changes, so here they are.
:cl:
balance: Headbite is only usable on the dead
balance: Headbite can't be used while on fire
balance: Headbite will cancel if damage is taken
/:cl:
> Headbite Changes

- code/game/objects/effects/aliens.dm
These were hard deleting because they're looping instead of using process
> make acid use process

- code/__HELPERS/text.dm
> Fixes Replacement Character bug

- code/__DEFINES/dcs/signals.dm
- code/datums/components/mobile_power.dm
- code/game/objects/machinery.dm
- code/modules/power/port_gen.dm
- code/modules/power/power.dm
- dependencies.sh
- tgmc.dme
MLGTASTIC/SPCR wanted to add a generator that powers via range instead of area, I have written this component to allow them to add that as the signal code for it ended up being... complicated.
New feature (maybe)
> Add mobile_power component

- code/__DEFINES/_subsystems.dm
- code/__HELPERS/_lists.dm
- code/controllers/subsystem/runechat.dm
- code/controllers/subsystem/timer.dm
- code/game/world.dm
Port https://github.com/tgstation/tgstation/pull/54977 fix and also had to just update the timer subsystem code
> update timer subsystem and fixes a bug

- code/__DEFINES/objects.dm
- code/game/objects/items/bodybag.dm
> Fixes new lints detected by the spacemandmm update

- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
PART 6-
Queen
NERFS
Screech now deals stamina damage instead of haloss.
Compensation (If any)
Queen now has a hivelord level heal
queen is more of a chess king than a queen, and should probably have more support abilities than direct combat abilities in general
:cl:
balance: queen screech now deals stamina damage, she has gained healing in return
/:cl:
> Stun changes part 6- queen

- .github/workflows/test.yml
https://github.com/tgstation/tgstation/pull/54735
:cl:
code: Linting annotation
/:cl:
> Linting annotation

- code/controllers/configuration/configuration.dm
- code/modules/power/cable.dm
- tools/ci/check_grep.sh
title
:cl:
code: 0 length timer linting
/:cl:
> 0 length timer linting

- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Fixes xeno health overlays layering strange
:cl:
fix: Fixes xeno health overlays layering strange
/:cl:
> Fixes xeno health overlays layering strange

- code/controllers/subsystem/atoms.dm
- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/initialize_sanity.dm
Borrowing https://github.com/ParadiseSS13/Paradise/pull/14770
Working code good
:cl:
code: Init sanity unit test
/:cl:
> Init sanity unit test

- code/controllers/globals.dm
- code/controllers/subsystem/timer.dm
- code/controllers/subsystem/weeds.dm
- code/datums/components/largeobjecttransparency.dm
- code/datums/looping_sounds/_looping_sound.dm
> Check for 0 length timers in _addtimer

- code/game/objects/structures/barricade.dm
Per title.
Fixes issue: https://github.com/tgstation/TerraGov-Marine-Corps/issues/5336
Fixes a bug that can grant infinite metal resources. Bad.
:cl:
fix: Can no longer crowbar anchored barricades for infinite metal. Thanks to Elsa for bringing it to my attention.
/:cl:
> Fixes Infinite Metal From Crowbarring Anchored Metal Barricades

- code/modules/projectiles/guns/rifles.dm
gdp free stuff I've sleppt for 3 hours in the last 24 hours help
tx-15 can't be fired one handed
shotgun consistent }bad
:cl:
fix: fixed tx-15 being fireable one handed
/:cl:
> tx-15 one hnaded fix

- code/datums/components/footstep.dm
- code/game/turfs/open.dm
- code/game/turfs/plating.dm
runtimes bad
for there were thousands of runtimes every round start as the marines silently ghosted their way to prep.
no longer.
:cl: Tiviplus
fix: apparently barefeet were causing runtimes with every step. Fixed it
/:cl:
> Barefoot step runtime fix

- code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
PART 3-
~~Rouny~~ Runner
NERFS
Pounce delay from 6 to 13
Compensation (If any)
Runner gets more health overall, caps at 240, runner overall didn't need anything other than this. And honestly this nerf should've happened a long time ago.
Stuns are bad. Death to stuns.
Runner specifically has probably needed a minor nerf and after headbites I think its fair to nerf its 1v1 minorly.
:cl:
balance: runner pounce delay made 13 rather than 6, and runner hp buffed up to capping at 240.
/:cl:
> Stun changes part 3- Runner

- code/game/objects/structures/barricade.dm
nerfs plasteel cade hp by 100, nerfs reinforced cade armor by 20, nerfs acid upgrade by 10
fobs sieges last a long time, this should make them last a bit less longer
:cl:
tweak: renamed the ballistic armor upgrade for cades to reinforced
balance: nerfed plasteel cade hp by 100, nerfed reinforced armor upgrade for metal cades to 30 melee, nerfed acid by 10 to 20
/:cl:
> nerfs ballistic/acid barricade armor upgrade and  nerfs plasteel hp by 100

- code/modules/mob/new_player/new_player.dm
:cl:
fix: Fixes player polls runtime
/:cl:
> Fixes player polls runtime

- code/datums/gamemodes/game_mode.dm
forgot a trailing qdel
:cl:
fix: Fixes undeleted query
/:cl:
> Fixes undeleted query

- code/__HELPERS/cmp.dm
- code/__HELPERS/icons.dm
- code/game/atoms.dm
- code/game/objects/structures/xeno.dm
Port without the wierd stuff
Splinter needs these and I need them anyway
:cl:
code: Add filter helpers
/:cl:
> Add filter helpers

- code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
title
Better immersion and mechanics description.
:cl: Slotbot
add: neurotoxin in select reagent description
tweak: gas prompts wording
spellcheck: fixed a few typos
/:cl:
> Fixes Defiler gas prompts wording, Improves Select Reagent description

- code/controllers/subsystem/timer.dm
didnt read
:cl:
code: Removes buggy timer batching system
/:cl:
https://github.com/tgstation/tgstation/pull/55140
> Ports TG timer thing

- code/game/objects/items/bodybag.dm
This is why I dont merge before 24h btw
:cl:
code: Fixes bad code in tarps
/:cl:
> Fixes bad code in tarps

- code/game/objects/items/explosives/grenades/marines.dm
- code/game/objects/items/flashlight.dm
As per title. Based on CM's.
Because pressing R is something tedius for your fingers.
:cl:
tweak: Activating flare grenades now put you into throw mode.
/:cl:
> Activating flare automatically puts you in throw mode

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
This PR removes a small portion of the shutters outlined here:
So people won't make the mistake of adding cades there.
:cl:
del: Removed the northern shutters in LZ1 of Ice Colony
/:cl:
> Minor ice edits

- code/__DEFINES/mobs.dm
- code/game/objects/items/implants/implantneurostim.dm
- code/game/objects/items/scanners.dm
- code/game/objects/items/weapons/holo_weapons.dm
- code/modules/mob/living/carbon/carbon_defines.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/life/handle_shock.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/life.dm
- code/modules/mob/living/carbon/shock.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
- code/modules/mob/living/damage_procs.dm
- code/modules/mob/living/living_defense.dm
- code/modules/mob/living/living_health_procs.dm
- code/modules/projectiles/gun_system.dm
- code/modules/reagents/reagents/medical.dm
halloss is a terrible mechanic we ditched ages ago for good reason, and now that nothing seems to use it just make agony deal stamina loss and delete it entirely.
This might not be a clean removal.
Halloss is a terrible mechanic, just use the normal pain system or stamina. Its not in the game anymore anyway, it can die in a hole.
:cl:
del: Removed halloss as a system. Nobody will remember it
/:cl:
> deletes halloss and any mention of it from tgmc entirely

- code/controllers/configuration/configuration.dm
- code/controllers/subsystem/weeds_decay.dm
- code/datums/components/riding.dm
- code/game/objects/structures/dropship_ammo.dm
- code/modules/client/client_procs.dm
- code/modules/power/cable.dm
- code/modules/power/groundmap_geothermal.dm
Fixes some issues, for now this, will fix more runtimes.
Fixes #5365 
Fixes #5379 
Fixes #5377 
Fixes #5376 
Fixes #5380 
fixing issues.
:cl:
fix: fixes runtime errors caused by 0 lenght timers.
/:cl:
> Fixes runtime issues in code.

- code/modules/reagents/reagents/alcohol.dm
Fixes a typo.
There's one less typo.
:cl:
spellcheck: fixed one typo
/:cl:
> Fixes a typo

- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Per title.
Fixes the Hive Status Limit calculations so they have full precision.
:cl:
fix:  Hive Status T2 and T3 limit calculations fixed.
/:cl:
> Fixes T2 and T3 Hive Status Limit Calcs

- code/game/objects/structures/dropship_ammo.dm
- code/game/objects/structures/dropship_equipment.dm
dropship table costed the pilots their entire point supply for the round, reduced it from 300 to 25.
Reduced ammo costs overall by half or 1/3rdish on average. GAU reduced massively.
So you can actually get ammo and not be fudged because someone joined as medical doctor
:cl:
balance: reduced cas ammo cost overall and dropship surgery table
/:cl:
> reduces cas cost for ammo overall and ds surgery table cost

- code/game/objects/items/reagent_containers/pill.dm
- code/game/objects/items/storage/firstaid.dm
- code/game/objects/items/storage/pill_packets.dm
- code/modules/reagents/reagents/medical.dm
Diversifies toxin-healing chems
Someone else fucked things up and I wanted to fix it.
We don't need 3 chems doing the exact same thing, so now we don't.
Arithrazine is reset to exactly what it was before, as it's a component of some pre-mixed medicines.
Hyronalin is changed to the T2 version of antitox. It heals 1 toxin/tick with no side effects, but doesn't purge hostile chems.
Ryetalin is changed to a long-duration shield against toxins, but heals no damage on it's own. A 30u dose will last for ~40 minutes, but will only last 60 seconds or less if mixed with Tricord, Bicard, or Kelo.
Russian Red is changed to an emergency revival medicine like Neuraline. 1u/tick metabolism rate, 5 bruteheal, 5 burnheal, 2.5 toxheal, but does 2 cloneloss. 
This can only be healed in cryo.
Pills are 10u …
> Tox heal chems diversified

- .github/workflows/test.yml
- tools/ci/check_grep.sh
> Fix CI failure

- code/modules/orbits/spaceship.dm
I was perhaps a bit too 'conservative' in my original wording, all those year ago.
Attempts to hammer home the consequences of your actions by pressing buttons as a player.
No CL needed.
> Harsher wording on the retreat proc

- .github/CONTRIBUTING.md
> Add requirement to autodoc new procs and vars to Contributing.md

- code/modules/projectiles/ammo_datums.dm
you get pen or you get sunder, not both.
Damage reduced to 40, sunder to 5.
15 sunder 55 damage 40 pen and 12 shots is a big funny man meme
:cl:
balance: nerfed lasgun overcharge to 5 sunder and 40 damage
/:cl:
> Nerfs lasgun overcharge

- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
fixes a bug caused by #5420.
bugfix
:cl:
fix: fixes generating negative burrowed when hijacking.
/:cl:
> fixes problem of reverse giving larva on hijack.

- code/datums/keybinding/xeno.dm
- code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
1. Adds hotkey setting for Evasion.
2. Fixes a minor bug with Evasion (wish I knew about the last_move_time var sooner).
Hotkeys and bug fixes.
:cl:
fix: Hotkey added for Evasion.
fix: Minor bug with Evasion corrected.
/:cl:
> Adds Evasion Keybinds and Fixes Minor Evasion Bug

- code/datums/emotes.dm
- code/modules/mob/living/say.dm
Ports:
https://github.com/BeeStation/BeeStation-Hornet/pull/156
https://github.com/BeeStation/BeeStation-Hornet/pull/236
:cl: CthulhuOnIce, BeloneX
add: Added automatic-punctuation.
/:cl:
> Auto-punctuation.

- code/game/objects/structures/stool_bed_chair_nest/chairs.dm
- code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
- code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
title
:cl:
code: cleaned up bed and chairs code
/:cl:
> Minor cleanup of beds and chairs

- code/__DEFINES/dcs/signals.dm
- code/game/objects/effects/effect_system/particle_effects.dm
- code/game/objects/items/bodybag.dm
- code/game/objects/machinery/pipe/construction.dm
- code/game/objects/structures/fence.dm
- code/game/objects/structures/reagent_dispensers.dm
- code/game/objects/structures/window.dm
- code/modules/vehicles/cargo_train.dm
a
:cl:
code: Cleaned up Move() and Signal defines slightly
/:cl:
> Cleans up Move() and Signal defines slightly

- code/__DEFINES/objects.dm
- code/__HELPERS/unsorted.dm
- code/datums/actions/item_action.dm
- code/game/objects/items.dm
- code/game/objects/items/shards.dm
- code/game/objects/items/weapons/weaponry.dm
- code/game/objects/structures/xeno.dm
- code/modules/clothing/glasses/hud.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/modular_armor/modular.dm
- code/modules/projectiles/gun_helpers.dm
- code/modules/projectiles/guns/specialist.dm
:cl:
code: removed depracated vars on items
code: documented items
code: more misc cleanup
refactor: refactored item actions into a lazylist
/:cl:
> Refactors item actions to a lazylist, documentation and deprecation pass

- code/game/objects/items/binoculars.dm
- code/game/objects/items/portable_vendor.dm
- code/game/objects/items/storage/fancy.dm
- code/game/objects/items/tools/shovel_tools.dm
- code/game/objects/machinery/fire_alarm.dm
- code/game/objects/machinery/kitchen/gibber.dm
- code/game/objects/machinery/sentries.dm
- code/game/objects/structures/barricade.dm
- code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
- code/game/objects/structures/janicart.dm
- code/modules/power/smes.dm
What it says
:cl:
fix: fixed a likely cause for sticky plasteel overlays
code: Cleaned up various overlay code
refactor: Turret icon updates will be much faster
/:cl:
> Refactors various overlays to  use the correct proc and fixes turret overlays performing like trash

- code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Fixes #5474 
bugfix
:cl:
fix: fixes xeno grabbing starting even when not adjacent when grabbing via ctrl click.
/:cl:
> fixes xenos ctrl click starting to grab humans on distance.

- SpacemanDMM.toml
- code/__DEFINES/spaceman_dmm.dm
- code/game/world.dm
Update to use auxtools :chefkiss:
https://github.com/SpaceManiac/SpacemanDMM/wiki/Setting-up-Debugging
> Auxtools debugger

- code/game/objects/structures/barricade.dm
Fixes minor bug with barbed barricades not dealing damage to alien attackers.
Bug fix.
:cl:
fix: Fixes minor bug with barbed barricades not dealing damage to alien attackers.
/:cl:
> Fixes Minor Bug With Barbed Barricades

- code/modules/projectiles/guns/specialist.dm
title
fix
:cl:Slotbot
fix: PMC sniper has IFF again
/:cl:
> Fixes PMC sniper IFF

- code/modules/admin/panels/permission_panel.dm
https://github.com/tgstation/tgstation/pull/55485/files
> [s] Fixes dbrank exploit

- code/modules/projectiles/gun_system.dm
Fixes being able to fire with pre-aim mode fire rate while retaining the IFF.
Fixes #5542
:cl:Slotbot
fix: fixes #5542 by adding a busy check at able_to_fire proc
/:cl:
> Fixes Aim Mode fire rate debuff bypass.

- code/game/objects/structures/dropship_equipment.dm
Fixes #5547 
Fixes #5548 
Less runtimes
:cl:Splinter, Hughgent
fix: Fixed runtimes with the dropship operating table
/:cl:
> Fixes runtime's associated with Dropship Operating Tables

- code/modules/admin/server_verbs.dm
- code/modules/admin/verbs/chat_commands.dm
So people can see how laggy serv is from discord
:cl:
add: New !tgs lagcheck command to check server time dilation
code: Moved some code to the correct file
/:cl:
> Adds the Lagcheck command

- code/game/objects/machinery/doors/windowdoor.dm
Fixes bug with windoor collision.
Fixes bug with windoor collision.
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/5575
:cl:
fix: Fixes bug with windoor collision.
/:cl:
> Windoor Collision Fix

- code/modules/mob/dead/observer/orbit.dm
Closes #5500 
Does the suggestion of the #5500, from tests this doens't seem to break anything, seemingly on TG it aint also closed so i guess it works fine.
QOL
:cl:
tweak: ghost orbit menu doens't auto-close when you choose to orbit something.
/:cl:
> makes orbit menu not close when choosing something to follow.

- code/game/turfs/snow.dm
Fire now melts snow in proportion to its intensity (burn stacks).
Added realism; and interesting terrain interactions that should exist.
:cl:
add: Fire now melts snow in proportion to its intensity (burn stacks).
/:cl:
> Fire Now Melts Snow Stacks

- code/__DEFINES/dcs/signals.dm
- code/datums/keybinding/human.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/mob_helpers.dm
Adds a keybind for rail attachment.
adds a keybind for QOL.
:cl:
add: Added keybind for rail attachment(Default key is F)
/:cl:
> Rail attachment keybind

- code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
fixes #5579 . Add a condition where boiler can't switch globule type.
fixes a bug, not critical but it confused me once
:cl:
fix: Boiler can't change of globule type if it will prevent them from firing or making a new globule
/:cl:
> Fix boiler globule lock

- code/datums/jobs/job/shipside.dm
- code/datums/skills.dm
fixes  #5620 , Ai has now master engineer skills
fixes a bug
:cl:
fix: Ai doesn't fumble anymore with OB console
/:cl:
> Ai is now a master engineer

- code/modules/projectiles/gun_helpers.dm
Removes requirement to stand still when activating aim mode. You still need to wait for the bar to fill up though.
Improves the general flow of the fight as this was mostly a clunky mechanic and aim mode appears to be slow enough as is.
:cl:Slotbot
balance: removes aim mode requirement to stand still (you still need to wait for the bar to fill up)
/:cl:
> Removes requirement to stand still when activating aim mode

- code/game/objects/machinery/vending/marine_vending.dm
adds ammoboxes "that are already in code" to the marine vendors
better roundstart prep HOPEFULLY less magazines thrown away
:cl:
tweak: adds ammoboxes "that are already in code" to the marine vendors
/:cl:
> add ammoboxes to vendors

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
It makes LZ1 on Ice Colony not result in absolutely cancer CBT rounds.
:cl:
tweak: tweaked the area outside of LZ1 ice to be more open.
/:cl:
> Unfucks LZ1 ice.

- code/modules/reagents/reactions/food_drink.dm
fixes #5629 
closes #5629
:cl: Holistic
tweak: Moonshine have new recipe
fix: Moonshine now havent got same recipe with vodka
/:cl:
> Fix of #5629

- code/modules/reagents/reactions/other.dm
fixes #5630
closes #5630 
:cl: Holistic
tweak: Removed one virus recipe.
fix: Now virus food have only one recipe.
/:cl:
> Fix of two recipes for virus food

- code/game/objects/effects/weeds.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Added the weeds_speed_mod var for configuring xeno movement speed on weeds on a per-caste basis.
MJP's request
is it?
:cl:Slotbot
tweak: added the weeds_speed_mod var for configuring xeno movement speed on weeds on a per-caste basis.
/:cl:
> Made a var for xeno movement speed on weeds

- code/modules/reagents/reagents/medical.dm
this keeps the OD from as 15
and rises critical OD to 20
so keeps the Idea of 2 pills being too much. while giving space to major fuckup of 3 pills. 
fixes #5621
:cl:
fix: OD too close to critical OD on RR
/:cl:
> this fixes #5621 without changing stuff to much

- code/game/objects/items/weapons/misc.dm
Fixes #5659 
Tense error.
'hits' is a boring word
:cl:
fix: Fixes powerfist grammatical error.
/:cl:
> Corrects Powerfist Spelling Error

- code/game/objects/effects/weeds.dm
- code/game/objects/obj_defense.dm
- code/game/objects/structures/orbital_cannon.dm
- code/game/objects/structures/xeno.dm
Puts an end to the hugger trap shuttle crush bug for good.
As above.
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/5660
:cl:
fix: Hugger traps crushed by the shuttle no longer discharge huggers (again).
/:cl:
> Fixes Shuttle Crushed Huggers

- code/__DEFINES/__game.dm
- code/modules/mob/new_player/new_player.dm
Per title.
Immersion.
:cl:
tweak: The in-game year is now 2416.
tweak: In addition to this, the ingame year is now dynamic.
/:cl:
> 2415 > 2416

- code/game/objects/items/explosives/plastique.dm
Copypasted detpack explosion ring sound and added small explosion area to C4. Hopefully the correct way.
C4 is no longer a magic wall delete for the added I M M E R S I O N
:cl:
tweak: C4 now does small explosion and plays detpack ringing when detonation time is up
/:cl:
> C4 explosion sound

- code/modules/projectiles/guns/rifles.dm
Makes the GPMG better at support fire during offensive actions, at the cost of more slowdown.
The GPMG should feel good at suppression, this helps it.
:cl:
balance: GPMG aim speed delay increased to 6, aim fire speed decrease is 0.1 now.
/:cl:
> GPMG aim mode speed slow increased to 6 aim fire delay made 0.1

- code/modules/client/preferences_gear.dm
It adds an eye patch for 2 points to the preference load-out gear.
:cl:
add: Added an eye patch to load-out gear.
/:cl:
> Adds an eye patch to preference gear.

- code/datums/keybinding/xeno.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
1. Adds hotkey for Healing Infusion and Hive Rally
2. Improves code for Healing Infusion; hopefully stops inconsistent buff SFX behaviour reported by some.
Bugfixes.
Adds hot keys.
:cl:
add: Hotkeys added for Rally Hive and Healing Infusion.
fix: Possible fix for Healing Infusion SFX inconsistency.
code: Code improvement for Healing Infusion.
/:cl:
> KBs for Healing Infusion + Rally Hive. Healing Infusion code improvement

- code/modules/reqs/supplypacks.dm
Lowers price of combat satchel, they were too high pricy
Now ungas would get their combat packs more often
:cl: HolisticDelight
tweak: Price of combat satchel in req decreased.
/:cl:
> Combat pack tweak

- code/game/objects/machinery/vending/marine_vending.dm
Fixes pathing so it doesn't override the default vendor, #5671 
Railscopes back in regular vendor
:cl:
fix: Fixes HvH attachment vendor path.
/:cl:
> Fixes HvH attachment vendor

- code/modules/mob/new_player/sprite_accessories.dm
makes it so that combover and combover 2 hairstyles don't have the same path
:cl:
fix: combover and combover 2 are now properly separate
/:cl:
> combover fix

- strings/names/last_name.txt
Because.
No accidental namechecking to see if it is not allowed
:cl:
del: Removed some names in the last name list.
/:cl:
> Needed (removed two names)

- code/modules/projectiles/guns/pistols.dm
marines have learnt to aim with pistols
0.65 slowdown for now across the board
marines are gunning now
also all default guns should get aim mode tbh
:cl:
balance: pistols in general get aim mode
/:cl:
> pistols get aim mode now 

- code/modules/projectiles/guns/revolvers.dm
revolvers get aim mode
0.75 slow 0.25 fire delay
marines are gunning
every normal gun should really get aim mode
:cl:
balance: revolvers get aim mode
/:cl:
> revolvers get aim mode

- code/controllers/configuration/entries/game_options.dm
- code/game/objects/effects/misc.dm
Fixes the fog wall being passable with living humans and bullets/grenades/etc.
Fixes a bug.
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/5702
:cl:
fix: Fixes the fog wall being passable with living humans and bullets/grenades/etc.
/:cl:
> Fixes Fog Wall Being Permeable to Humans/Bullets/Grenades

- code/__DEFINES/jobs.dm
- code/datums/jobs/job/job_exp.dm
- code/datums/jobs/job/marines.dm
- code/datums/jobs/job/shipside.dm
Changes and add time-lock times on some jobs. Here is a recap of every job and their time-lock
// No Time lock
Marine
Engineer
Corpsman
SG
ST
MO
CL
Rsr
//1 hour
RO
//3 hours
SL
AI
PO
SO
//10 hours
FC
CSE
CMO
Synth
//15 hours
Captain
These hours are not much too ask if you compare to the griefing power these roles have. I don't know why or how you would play a role shipside where you can fuck the whole round if you don't have at least a basic understanding of the game ground side. 
You should not be in a position of leader if you can't tie your own laces
Having captain fresh from CM being here just to meme around is not that rare, and this PR can hopefully curb this a bit.
:cl:
admin: Stricter time lock for shipside and command jobs
/:cl:
> New time locks

- code/game/objects/structures/xeno.dm
Fixes xeno tunnel bugs related to keeping the dialogue open, as well as proofing tunnels against future possible bugs/unintended behaviours.
Fixes xeno tunnel bugs related to keeping the dialogue open, as well as proofing tunnels against future possible bugs/unintended behaviours.
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/5721
:cl:
fix: Fixes a bug related to keeping the xeno tunnel selection interface open.
code: Proofs xeno tunnels against future bugs/unintended behaviours.
/:cl:
> Bug Fixes for Xeno Tunnels

- code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
:cl:
refactor: refactored xenoupgrade.dm to massively improve readability
/:cl:
> Improves the readability of xenoupgrade.dm

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Should completely fix the lingering Healing Infusion Aura bug.
Fixes a bug.
:cl:
fix: Fixes lingering bugs with the Healing Infusion aura visuals.
/:cl:
> Should Fix Healing Infusion Aura Issues For Good

- code/datums/jobs/access.dm
- code/datums/jobs/job/shipside.dm
Gives Synthetics the time progression they should have.
Synthetic is essentially a mini captain that can and should do most shipside job especially when there is a lack of command.
People should be encouraged to play this role as well as it will let others know how much experience that player has.
We have ranks for that very reason. Plus it is my first PR so wanted to start out simple.
:cl: SpaceLove
add: Synthetic ranks added
/:cl:
> Synthetic Rank Progression

- code/game/objects/effects/aliens.dm
- code/game/objects/items/explosives/grenades/marines.dm
- code/game/objects/structures/barricade.dm
- code/game/objects/structures/razorwire.dm
- code/game/objects/structures/tables_racks.dm
- code/game/objects/structures/watercloset.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/carbon/human/human_attackpaw.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/xenomorph/attack_alien.dm
- code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
- code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
- code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
- code/modules/mob/living/carbon/xenomorph/charge_crush.dm
- code/modules/mob/living/carbon/xenomorph/damage_procs.dm
- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
- code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/projectile.dm
Fixes damage delays for most relevant damage events.
Either fixes a bug or fixes a feature so obnoxious and unwanted it may as well be a bug.
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/5681
:cl:
fix: Fixes damage delays for most relevant damage events.
/:cl:
> Damage Delay Eliminated For Most Relevant Things

- code/datums/jobs/job/shipside.dm
No ranks were given when below 10 hours
ranks good
:cl:
fix: fixes synth rank when below 10 hours
/:cl:
> Fix Synth ranks

- README.md
- sound/credits.txt
Two things:
- Removes the Panther sprite license as it is no longer in the game.
- Typo for the new GAU sounds has been fixed.
Because.
remove:  Removed the outdated license about the Panther sprite.
tweak: Fixed the GAU license PR typo.
/:cl:
> Licensing Changes

- code/modules/shuttle/cas_plane.dm
Title
Fix
:cl:
fix: Can't refuel condor mid flight anymore
/:cl:
> Cas can't refuel mid flight

- code/datums/emergency_calls/pmc.dm
As written on the tin.
Funny PMC SGs being more than fifty percent of the god damn team most of the time. This'll make them more likely to pick standard, instead.
:cl:
tweak: Drops PMC SG probability to 30
/:cl:
> Drops PMC SG probability to 30

- code/datums/jobs/job/marines.dm
Right now your rank only changes as SL if you late join. This fixes that
:cl:
fix: SL rank now correctly changes with playtime if you join at round start
/:cl:
> Fixes SL Paygrade only working on late join

- code/datums/gamemodes/game_mode.dm
Fix #5881
:cl:
fix: Game no longer end when hijacking
/:cl:
> Fix game end

- code/modules/projectiles/gun_system.dm
- code/modules/projectiles/guns/specialist.dm
- code/modules/security_levels/keycard_authentication.dm
- code/modules/shuttle/cas_plane.dm
someone should remove the sleep spam in autodoc at some point
:cl:
code: Removes various bad sleeps
/:cl:
> Removes various bad sleeps

- code/modules/power/fusion_engine.dm
No compromises for terrible game design.
:cl:
tweak: The fusion generators no longer randomly break down.
/:cl:
> The fusion generators no longer break down.

- code/modules/projectiles/guns/rifles.dm
local man forgets to push offsets
fix
:cl:
fix: fixes hk11 attachment offsets.
/:cl:
> fixes hk11 offsets

- code/modules/projectiles/guns/shotguns.dm
v-10 shotgun works again
fix this thing
:cl:
fix: v10 no longer checks for non map variants flags
/:cl:
> fixes v10 not having map variant

- code/game/objects/machinery/vending/marine_vending.dm
it shouldn't be there in the first place, its not a decently designed attachment
bc bad, bc die
:cl:
del: Removed barrel charger
/:cl:
> removes barrel charger from req vendor

- code/modules/projectiles/guns/rifles.dm
fixes carbine offsets that were broke in MJP PR #5849 
fix broken sprite
:cl:
fix: fixes T18 attachments having wrong offsets.
/:cl:
> Fixes carbine offsets.

- code/modules/projectiles/guns/pistols.dm
0.65 to 0
Yes. (wHY NOT)
:cl:
balance: pocket pistol no longer slows you down when aiming
/:cl:
> pocket pistol hsa no aim slowdown

- code/game/objects/items/explosives/grenades/grenade.dm
- code/game/objects/items/explosives/grenades/marines.dm
since surr wont bother I guess ill do it
:cl:
balance: Flamed grenades will respect detonation timers
/:cl:
> Flamed grenades will respect detonation timers

- code/modules/reqs/supplypacks.dm
this allow req to "sell/require/buy" some medical items
being:
**name = "Advanced medical packs"**
_5 brute kits 5 burn kits 5 splints
cost: 10_
**name = "tweezers"**
_contains a pair of tweezers
cost: 20_
**name = "advanced big hypospray"**
_contains a big hypo spray aka 120u
cost: 12_    ((regular hypo is 5 so this is a lil more than double the price))
adds a way to ressuply medics on the field with a more direct interaction from req instead of needing MOS to restock and vend kits. also gives ways to re aquire lost tweezers and big hypos although for a steep price
:cl:
add: big hypo to the req orders
add: advanced medical pack crate to the req orders
add: tweezers to the req orders
/:cl:
>  medical attention REQuired

- code/__DEFINES/dcs/signals.dm
- code/_onclick/click.dm
title
:cl:
add: Xenos can now rightclick to use abilities
code: Rclick signal framework
/:cl:
> Xenos can now rightclick to use abilities + Rclick signal framework

- code/datums/actions/rightclick_toggle.dm
- code/modules/mob/dead/observer/login.dm
- code/modules/mob/living/login.dm
- code/modules/mob/living/logout.dm
- tgmc.dme
waiting for sprites
:cl:
add: Adds a right click hud toggle
/:cl:
> Adds a right click hud toggle

- code/modules/client/client_defines.dm
Bit of a stopgap till we can add more functionality
:cl:
tweak: Clients will default to rclick menu on
/:cl:
> Clients will default to rclick menu on

- code/modules/projectiles/guns/rifles.dm
0.1->0.3 for 1.65
nerf or nothing
:cl:
balance: tl 127 aim mode nerf
/:cl:
> nerf tl-127 aim mode fire speed

- _maps/map_files/Sulaco/Sulaco.dmm
:cl:
fix: Fix map lint fail
/:cl:
> Fix map lint fail

- tools/ci/check_grep.sh
:cl:
fix: fixed a rogue comma
/:cl:
> Fix rogue comma

- code/controllers/subsystem/blackbox.dm
:cl:
fix: fixed a broken database query
/:cl:
> Fixes blackbox query

- code/__DEFINES/dcs/signals.dm
- code/modules/client/client_procs.dm
:cl:
refactor: Clients should now delete properly
admin: admins will be alerted when the server is left on with no staff
/:cl:
> Likely fix various client caused bugs by cleaning client deletion

- code/controllers/failsafe.dm
- code/controllers/master.dm
- code/datums/helper_datums/stack_end_detector.dm
- tgmc.dme
https://github.com/tgstation/tgstation/pull/56008
:cl:
code: The MC will now instantly restart upon stack overflows
/:cl:
> Ports MC stack overflow protection

- code/modules/client/client_procs.dm
Requested by Xander
:cl:
admin: Enables automute logging and admin messages
/:cl:
> Enables automute logging and admin messages

- code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
why did it never have this
spits have a max range anyway so you can't snipe
boiler has learnt to spit acid again
:cl:
balance: boiler spits acid
/:cl:
> boiler gets acid spit i guess

- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/bespoke_id.dm
https://github.com/tgstation/tgstation/pull/49676/files
:cl:
code: Adds unit test for bespoke ids
/:cl:
> Adds unit test for bespoke ids

- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/weed_ability.dm
Just checks if you can plant the weed and plasma
:cl:
code: Adds unit test for weeding
/:cl:
> Adds unit test for weeding

- code/__DEFINES/dcs/signals.dm
- code/_onclick/click.dm
- code/modules/projectiles/gun_attachables.dm
- code/modules/projectiles/gun_system.dm
Title
:cl:
add: Gun attachments can now be fired with rclick
/:cl:
> Gun attachments can now be fired with rclick

- code/__DEFINES/_subsystems.dm
> Fix linter if(true) detections

- code/modules/mob/dead/observer/logout.dm
- code/modules/mob/dead/observer/observer.dm
:cl:
fix: Likely fix for strange ghost behaviour
/:cl:
> Likely fix for ghost hard dels

- code/modules/mob/living/carbon/xenomorph/death.dm
- code/modules/mob/living/carbon/xenomorph/egg_item.dm
- code/modules/mob/living/carbon/xenomorph/embryo.dm
:cl:
code: Misc. xeno code cleanup
/:cl:
> Misc. xeno code cleanup

- code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
> Revert "boiler gets acid spit i guess"

- code/modules/flufftext/Dreaming.dm
Less shitcodey
:cl:
refactor: Minor dreaming refactor
/:cl:
> Minor dreaming refactor

- code/_compile_options.dm
- code/modules/client/client_procs.dm
title
:cl:
server: Add maximum reccomended version of byond
/:cl:
> Add maximum reccomended version

- code/controllers/subsystem/direction.dm
- code/controllers/subsystem/weeds_decay.dm
- code/game/objects/machinery/autodoc.dm
- code/modules/organs/limb_objects.dm
- code/modules/organs/limbs.dm
- code/modules/requisitions/fulton.dm
- code/modules/surgery/bones.dm
:cl:
code: Generic code cleanup pass and documentation
/:cl:
> Generic code cleanup pass and documentation

- code/game/objects/items/storage/internal.dm
:cl:
code: cleans up some inventory code
/:cl:
> Fix spawn() returns and clean up /obj/item/storage/internal/proc/handle_mousedrop

- code/game/objects/structures/barricade.dm
sandbags have too much health and can be repaired and setup up pretty quickly
sandbags too good
:cl:
balance: sandbag intregrety halved
/:cl:
> lowers sandbag health

- code/_onclick/ai.dm
- code/_onclick/click.dm
- code/_onclick/other_mobs.dm
- code/_onclick/xeno.dm
Better this way
:cl:
code: Unarmedattack no longer converts params twice
/:cl:
> Unarmedattack no longer converts params twice

- code/_onclick/xeno.dm
params2list(null) returns an empty list but this line can't handle a null reference.
> Fix xeno unarmed attack bad index runtime

- code/game/objects/machinery/vending/new_marine_vendors.dm
15 to 30
pill bottles are vastly better than hyposprays and these are mixed entirely minmaxed so i don't get it being 15
30 is more far
:cl:
balance: medic pil bicamera/keloderm bottle price doubled
/:cl:
> pill bottle 30 from 15

- code/modules/projectiles/ammo_datums.dm
- code/modules/projectiles/guns/pistols.dm
pp no longer has multipliers
no dumb obsfuation 
:cl:
code: removes pocket pistols multiplier obfuscation
/:cl:
> pocket pistol obsfucation removal

- code/game/objects/machinery/vending/new_marine_vendors.dm
Fixes the name of the vendor sentry voucher to what it actually deploys.
Lets people know what it actually is since I for one avoided it because of the wrong wording.
:cl:
spellcheck: changed -580 Point to 571-C Base
/:cl:
> Sentry voucher fix

- code/_globalvars/lists/client.dm
title
it's from beestation.
:cl:
server: added more blacklisted versions
/:cl:
> adds more blacklisted versions

- code/modules/unit_tests/weed_spread.dm
Already takes too long and would take longer if mwe made it work properly
:cl:
fix: Weed unit test is now consistent
/:cl:
> Removes weed removal unit test

- code/modules/mob/living/carbon/human/human_damage.dm
:cl:
fix: Fixed divide by 0 runtime
/:cl:
> Fixes divide by 0 runtime

- code/controllers/subsystem/blackbox.dm
Something tells me psy didnt test this originally
:cl:
fix: fixed the blackbox death query again
/:cl:
> Fix DBquery second edition

- code/modules/mob/living/carbon/xenomorph/emote.dm
:cl:
fix: needhelp emote is now activated with needhelp instead of heedhelp (N instead of H)
/:cl:
> Heedhelp to Needhelp

- code/__DEFINES/dcs/signals.dm
- code/game/atoms_movable.dm
- code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
- code/modules/mob/living/living.dm
throwimpact isnt called if you dont hit anything
:cl:
fix: Fixed spammed runner pounce runtime
/:cl:
> Fix spammed runner runtime

- code/game/objects/effects/manifest.dm
- code/game/objects/items/stacks/rods.dm
- code/game/objects/machinery/adv_med.dm
- code/modules/projectiles/gun_helpers.dm
- code/modules/projectiles/guns/revolvers.dm
- code/modules/projectiles/guns/specialist.dm
- code/modules/reagents/reagents.dm
- code/modules/tooltip/tooltip.dm
- tools/ci/check_grep.sh
:cl:
code: Removes illegal src edits and adds a lint for them
/:cl:
> Removes illegal src edits and adds a lint for them

- SpacemanDMM.toml
- code/__DEFINES/_tick.dm
- code/__DEFINES/spaceman_dmm.dm
- code/_compile_options.dm
- code/game/world.dm
a few elements taken fromhttps://github.com/tgstation/tgstation/pull/56724
:cl:
code: 514 compatability
/:cl:
> 514 compat

- code/datums/beam.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
https://github.com/tgstation/tgstation/pull/55193
:cl:
refactor: Beams are now more performant
/:cl:
> Beam refactor to use signals

- code/datums/actions/xeno_action.dm
- code/datums/components/suit_autodoc.dm
- code/datums/elements/scalping.dm
- code/datums/marine_main_ship.dm
- code/datums/wires/airlock.dm
- code/game/area/area.dm
- code/game/objects/machinery/buttons.dm
- code/game/objects/machinery/door_control.dm
- code/game/objects/machinery/doors/airlock.dm
- code/game/objects/machinery/doors/airlock_control.dm
- code/game/objects/machinery/doors/brigdoors.dm
- code/game/objects/machinery/doors/door.dm
- code/game/objects/machinery/doors/firedoor.dm
- code/game/objects/machinery/doors/windowdoor.dm
- code/game/objects/machinery/telecomms/machines/allinone.dm
- code/modules/ai/ai_behaviors/carbon/carbon.dm
- code/modules/ai/ai_behaviors/carbon/xeno/xeno.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/projectiles/gun_attachables.dm
- code/modules/shuttle/on_move.dm
this probably needs a round or two of tm
:cl:
refactor: refactored doors and various other code to remove sleeping signals
/:cl:
> Fixes a bit over half of the sleeping signal handlers

- code/modules/projectiles/guns/specialist.dm
it has iff again, when someone redid how iff works they broke this
it has iff and is supposed to
:cl:
fix: anti material rifle has iff again
/:cl:
> anti material rile has iff

- code/game/objects/items/implants/implant_cloak.dm
:cl:
fix: Minor cloak formatting changes
/:cl:
> Minor cloak formatting changes

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Fix areas lacking in south east ice colony
:cl:
fix: Remove instant death tiles in Ice colony
/:cl:
> Ice colony instant death fix

- code/game/objects/machinery/computer/communications.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Oversight this wasn't already added.
:cl:
fix: Announcements now check ic filter
/:cl:
> Add ic filtering for announcements

- code/modules/clothing/suits/marine_armor.dm
so they inherit pas level stats from the marine armor
also normalizes shipside armor
game consistency
:cl:
fix: shipside armor now has pas vest stats
/:cl:
> the normal marine vest uses pas vest stats, and normalizes non pas vest stats to pas vest for shipside armor

- SQL/database_changelog.txt
- SQL/tgmc-schema.sql
- code/__DEFINES/_subsystems.dm
- code/modules/admin/panels/note_panel.dm
https://github.com/tgstation/tgstation/pull/55800/files
:cl:
admin: Adds playtime tracking to notes
server: DB schema update
/:cl:
> Adds playtime tracking to notes

- code/game/turfs/walls/wall_types.dm
:cl:
fix: fixed a broken lobby screen and removed deprecated ones
imageadd: New lobby screen by Aisha
imageadd: New lobby screen by Dragonfruits
/:cl:
> Adds 2 new lobby screens by Aisha and Dragonfruits and removes some unused ones

- code/controllers/subsystem/runechat.dm
- code/game/world.dm
This is a long overdue fix ported from tg.
> Fix tick_lag changes breaking everything

- _maps/map_files/Sulaco/Sulaco.dmm
I don't know how they even got there but I may be responsible
:cl:
fix: Got rid of the mini rocket pods that were on the public engi vendors of sulaco
/:cl:
> Gets rid of the random rocket pods on sulaco

- code/modules/vehicles/unmanned/unmanned_vehicle.dm
:cl:
fix: fixed unmanned overlay
/:cl:
> Fixes unmanned overlay

- code/game/objects/items/weapons/blades.dm
For some reason these changes didn't get pushed into the original PR.
Fixes #6097
fixes
:cl:
fix: Fixes loading reagents in the harvester, makes breaking bicaridine effect not trigger an attack
/:cl:
> Fixes loading reagents in the harvester, makes breaking bicaridine effect not trigger an attack

- code/__DEFINES/traits.dm
- code/datums/status_effects/debuffs.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Refactors and improves the code of Healing Infusion such that it has no lingering override issues and its effects are applied as a formal status effect.
Per pull request.
:cl:
code: Improves the code of Healing Infusion such that it no longer overrides variables between targets, and is applied as a formal status effect.
/:cl:
> Refactor/Code Improvement for Healing Infusion

- code/game/objects/effects/effect_system/foam.dm
Fixes the only dreamchecker warning. It's an early return, FALSE meant to indicate failure, but it doesn't work in spawn so just remove it.
Makes you not instinctively ignore warnings, which lead to better code.
:cl:
code: fix dreamchecker warning
/:cl:
> Fix dreamchecker warning

- code/_compile_options.dm
- code/controllers/subsystem/silo.dm
- code/datums/components/mobile_power.dm
- code/datums/elements/shrapnel_removal.dm
- code/game/objects/items/implants/implant_chem.dm
- code/game/objects/structures/dropship_ammo.dm
- code/game/objects/structures/xeno.dm
- code/game/sound.dm
- code/modules/ai/spawners/human.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
after 1540 `as anything` works correctly and `as()` is the wrong way to do things.
> as anything macro

- code/game/objects/machinery/vending/vending.dm
Continuation of #5718 , with Tivi's changes in.
:cl:
fix: Fixed vendor speeches.
/:cl:
> Fixes vendor speeches

- code/datums/components/remote_control.dm
- code/modules/vehicles/unmanned/unmanned_vehicle.dm
title
:cl:
fix: fixed remotes being able to shoot while controlling
/:cl:
> Remote control click fixes

- _maps/modularmaps/EORG/old.dmm
- code/modules/mapping/modular_mapping.dm
Re-adds the old EORG arena before #4473 as one of the selectable modular map options.
Nolstalgic reasons.
:cl:
add: The old EORG map now has a chance to spawn as an EORG arena!
/:cl:
> Old EORG is back, as a modular map!

- .github/PULL_REQUEST_TEMPLATE.md
- html/browser/changelog.css
- tools/WebhookProcessor/github_webhook_processor.php
https://github.com/tgstation/tgstation/pull/56890
This is less generic and better overall
> Replace tweak with QOL and Atomic

- code/modules/modular_armor/attachables.dm
baldur buff
kuro keeps screaming at me about it
:cl:
balance: baldur mk1 slowdown reduced and light range slightly higher, mk2 has no slowdown
/:cl:
> baldur buff

- code/_onclick/human.dm
- code/_onclick/other_mobs.dm
Title
:cl:
code: Adds code for rightclicking with empty hand
/:cl:
> Adds attack_hand_alternate for rightclicking with empty hand

- code/__DEFINES/layers.dm
- code/_onclick/hud/fullscreen.dm
- code/modules/mob/new_player/new_player.dm
Immersion.
:cl:
tweak: Spawning as a marine (not a xeno) will have a little fade in as you spawn, like in Bay.
/:cl:
> Spawn marine fade in

- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Three tiles were space tiles
Fix
:cl:
fix: No more instant death on ice colony
/:cl:
> Fix space tiles in Ice Colony

- code/_onclick/hud/screen_objects/screen_objects.dm
No more hard del, i hope
Perf increase
:cl:
fix: CIC orders no longer runtime
/:cl:
> Cic orders fix runtimes

- code/game/objects/machinery/computer/camera_advanced.dm
`origin` is a machinery and didn't have client attached. Using `owner` shows the user the list correctly. Fixes #6021.
Bug fix.
:cl:
fix: overwatch jump to camera works again
/:cl:
> Fix overwatch jump to camera

- code/datums/status_effects/debuffs.dm
- code/game/objects/structures/xeno.dm
Fixes two bugs.
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/6145
Fixes minor copy pasta bug with the Healing Infusion effect end message.
:cl:
fix: Larva can now use tunnels.
fix: Fixes minor copy pasta bug with the Healing Infusion effect end message.
/:cl:
> Minor Bug Fixes

- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
allows people to have number inname, accounting for vatborns
vatborn name broken
:cl:
fix: synths can now have numbers in name.
fix: people now can have numbers in name to account for vatborns.
/:cl:
> Allows people to have numbers in name.

- code/__HELPERS/_logging.dm
- code/__HELPERS/game.dm
- code/__HELPERS/type2type.dm
- code/controllers/subsystem/vote.dm
- code/datums/recipe.dm
- code/modules/admin/IsBanned.dm
- code/modules/food/recipes_microwave.dm
- code/modules/mob/living/carbon/human/say.dm
- code/modules/mob/living/silicon/say.dm
- code/modules/mob/living/simple_animal/friendly/parrot.dm
- tools/ci/check_grep.sh
> Remove return .'s and add a lint for it

- code/game/objects/items/storage/backpack.dm
Fixes #6119
:cl:
fix: fixed the description
/:cl:
> Update the backpack description to reflect its function more.

- _maps/map_files/Sulaco/Sulaco.dmm
This add some holopads to many places in the sulaco. Some places include req, evac, the CL office or even near the alamo. 
It is essentially fluff, but let me be cortana yelling at marines.
:cl:
add: Added many holopads. 
/:cl:
> Add some needed holopads to the sulaco.

- code/modules/mob/new_player/new_player.dm
> You are now ready fix

- code/game/objects/items/weapons/blades.dm
When filling up the harvester, it transfers an amount based on the reagent container's setting as opposed to as much as possible.
More control over reagent management.
:cl:
qol: harvester fill up amount is based on beaker setting as opposed to the maximum possible amount
/:cl:
> Harvester fill up amount is based on beaker setting

- code/game/objects/machinery/vending/new_marine_vendors.dm
- code/modules/paperwork/paper.dm
Adds instructions about the Vali module so people know what it generally does.
People have to ask what it does less.
:cl:
qol: added instructions FAQ paper to vali set
/:cl:
> Adds vali instructions paper to vali set

- _maps/map_files/Sulaco/Sulaco.dmm
Just add some god damn lights
Less blind and fixes an oversight.
:cl:
add: Added new lights to the hangar mostly.
/:cl:
> First Commit, increase the numbers of lights in the sulaco.

- code/__DEFINES/__game.dm
- code/__DEFINES/admin.dm
- code/_globalvars/admin.dm
- code/controllers/subsystem/points.dm
- code/game/verbs/ooc.dm
- code/modules/client/preferences.dm
Less spam and broken shit
:cl:
admin: Adds more sanitization
/:cl:
> Adds more sanitization

- _maps/map_files/Sulaco/Sulaco.dmm
Add some more cameras to the sulaco i forgot in my first PR 
AI no longer so blind in medical
:cl:
fix: Fixes some missing lights and cameras on sulaco.
/:cl:
> Add more cameras to the sulaco.

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
I want to see things goddamnit.
No blind
:cl:
add: Add some extra cameras in the sulaco
/:cl:
> Adds some cameras to Pillar of spring, plus a couple of lights.

- code/modules/mob/living/carbon/xenomorph/login.dm
Admin request
:cl:
fix: Fix appearance bans on xenos
/:cl:
> Fix appearance bans on xenos

- code/game/objects/items/defibrillator.dm
How many times can we fix this stupid proc
:cl:
fix: Probably fixes incorrect ghosts being called for revive.
/:cl:
> Fixes magic revives (again)

- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/power/apc.dm
How did no one fix this before
Just intended functionality
:cl:
fix: Makes it so the AI can access the APC menu.
/:cl:
> Fixes the AI not having access to APC's

- code/modules/requisitions/_supply_export.dm
No longer can you sell crates for 3 points after buying them for 1 point
stonks bad
:cl:
fix: You can no longer sell crates for req points.
/:cl:
> Crates no longer sell for req points (This kills the stonks)

- code/game/objects/items/reagent_containers/hypospray.dm
you can restock hypo clicking on pill bottles
when you click in a pill bottle with a hypo that have ENOUGH SPACE for its contents (aka 15u free for a 15u pill. or 10u for a 10u pill)
it will use up one of the pills inside the bottle to automatically dissolve inside the hypo
QoL for hypos
:cl:
qol: you can restock hypos by clicking on the pill bottle
/:cl:
> you can restock hypo clicking on pill bottles

- code/modules/xenomorph/xeno_structures.dm
Silo will now correctly mature
No idea how I missed that
:cl:
fix: Silo will now correctly mature
/:cl:
> Silo were not maturing if placed after shutters

- code/modules/reqs/supplypacks.dm
Cut the price from 30 points to 10
Even if tesla cells are rechargeable it's really slow and you can't get more rechargers, and no one uses tesla gun at all :(
:cl:
balance: Tesla cells now cost 10 instead of 30
/:cl:
> Lowers the cost for tesla cells to be 10 instead of 30

- code/datums/components/chem_booster.dm
Fixes runtime from vali actions/overlay removal.
fix
:cl:
fix: fixed vali actions runtimes
/:cl:
> Fixes vali actions/overlay removal runtime

- code/game/objects/items/jetpack.dm
The jetpack now has a small windup (0.3 seconds). You can move while winding up
Gamers became too good with jetpack, this nerfs it a bit. It should still be worth its 15 points. 
:cl:
balance: Jetpack now has a windup of 0.3 seconds
/:cl:
> Jetpack nerf

- code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Per title.
Per title.
:cl:
fix: Removes Headbite and Regurgitate from Wraith.
/:cl:
> HOTFIX - Removed Headbites and Regurgitate From Wraith

- code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
signals were causing a loop also weren't being unregistered.
> Hotfix for wraith signal issues

- code/game/objects/items/tools/flame_tools.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/clothing/glasses/hud.dm
- code/modules/clothing/glasses/thermal.dm
- code/modules/clothing/head/collectable.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/head/jobs.dm
- code/modules/clothing/head/misc.dm
- code/modules/clothing/head/soft_caps.dm
- code/modules/clothing/masks/breath.dm
- code/modules/clothing/masks/miscellaneous.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/spacesuits/miscellaneous.dm
- code/modules/clothing/suits/jobs.dm
- code/modules/clothing/suits/miscellaneous.dm
- code/modules/clothing/suits/wiz_robe.dm
> Mass replace  flags_armor_protection = 0

- .tgs4.yml
- code/game/world.dm
- tools/tgs4_scripts/PreCompile.sh
- tools/tgs4_scripts/PreSynchronize.bat
- tools/tgs4_scripts/PreSynchronize.ps1
- tools/tgs4_scripts/PreSynchronize.sh
Preemptive changes to allow for managing TGMC through tgsv4, and allowing it to run on linux without having issues with extools. 
For tgsv4: Ported the pre-compilation and pre-synchronization scripts from /tg/ (though note I ported the version before the common build tools, as TGMC has not yet adopted them). Also ported over the ``.tgs4.yml`` file intended to be used for easier creation of TGMC instances on tgsv4 clients. (https://github.com/tgstation/tgstation/pull/55993)
For running on linux: ported a fix that prevents attempting to use the win32 dll for extools on linux machines. (https://github.com/tgstation/tgstation/pull/51118)
best wishes,
bobbah 'bee' brown
Can be ran on Linux, can be managed by tgsv4 which is going to be a lot more relevant in the near future.
:cl: bobbahbrown …
> Add scripts for running with tgsv4 + fix linux compatibility issue with extools

- code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
These are individual names and are proper nouns
> Make Larva proper nouns

- code/modules/reagents/reagents/medical.dm
Dramatically increases hypervene metab rate
Hypervene stopped purging itself after MJPs PR that made neurotox not purge it, but its metab rate is so low one autoinjector shot was lasting like 10 minutes.
:cl:
fix: Hypervene no longer remains in your system for an obscene amount of time
/:cl:
> Increase Hypervene Metabolism Rate

- code/modules/unit_tests/spawn_humans.dm
Was causing minimaps and SSambience PRs to fail for no reason
> Fix spurious test fail

- code/modules/tgui_panel/tgui_panel.dm
port of https://github.com/tgstation/tgstation/pull/57432
:cl:
fix: Icons in tgui shouldn't disappear any more.
/:cl:
> flush queue in preloading part of tgui_panel

- tgui/packages/tgui-dev-server/reloader.js
- Fixed a regression in tgui-dev-server, which made it reload before it finished copying files.
- Made copying work on Linux over SMB shares by using readFileSync and writeFileSync instead of copyFileSync, because copyfile kernel call doesn't work for this. It is slightly slower, but not very noticeable.
port of: https://github.com/tgstation/tgstation/pull/57499
> Fix TGUI Reloading

- code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Gee what could go wrong
:cl:
admin: Add banish logging
/:cl:
> Add banish logging

- code/modules/mob/new_player/poll.dm
https://github.com/tgstation/tgstation/pull/57462/files
:cl:
fix: fixed voter fraud
/:cl:
> Fix voter fraud

- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/binary_insert.dm
https://github.com/tgstation/tgstation/pull/53217/files
> Binary insert test

- code/game/objects/structures/droppod.dm
Title
:cl:
qol: Drop pods now fall from the sky
/:cl:
> Drop pods are now animated

- code/game/objects/structures/xeno.dm
Fixes potential hard deletes for destroyed xeno tunnels.
Fixes potential hard deletes for destroyed xeno tunnels.
:cl:
code: Potential hard deletes for destroyed xeno tunnels fixed.
/:cl:
> Fixes potential hard deletes for destroyed tunnels

- code/game/objects/items/megaphone.dm
Megaphone does not bypass IC filter
fixes #6238 
:cl:
fix: megaphone respects IC filter
/:cl:
> Megaphone Respects IC filter

- code/modules/xenomorph/xeno_structures.dm
Title
Will make healing dead bodies from acid turrets easier
:cl:
balance: Xeno turrets shoot on random body parts, easier to heal people that were killed by it
/:cl:
> Turrets shoot on random part of body

- _maps/map_files/Sulaco/Sulaco.dmm
The sulaco surgery didn't have power. This fixes that.
Makes buggy thing not buggy 
:cl:
fix: fix missing wires in sulaco surgery
/:cl:
> Add two missing wires to Sulaco surgery

- _maps/map_files/Sulaco/Sulaco.dmm
Mostly the hangars and medical. Again. Again. And again.
Not so dark during normal operation, and weirdly obscured.
:cl:
fix: fixed some missing lights and cameras in the sulaco.
/:cl:
> Add some cameras and lights to the sulaco. Again.

- code/_onclick/item_attack.dm
- code/_onclick/other_mobs.dm
- code/controllers/subsystem/explosions.dm
- code/game/objects/items/stacks/medical.dm
- code/game/objects/items/weapons/blades.dm
- code/game/objects/items/weapons/misc.dm
- code/game/objects/items/weapons/stunbaton.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
- code/modules/mob/living/carbon/xenomorph/damage_procs.dm
- code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Addresses certain problematic corner cases for the incorporeal status.
Addresses certain problematic corner cases for the incorporeal status.
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/6258
:cl:
fix: Incorporeal entities can no longer be attacked in melee, point blanked, grabbed, or shoved around by explosives.
/:cl:
> Adding Missing Incorporeal Checks

- _maps/map_files/Sulaco/Sulaco.dmm
Turns out, the ship with no fire alarm has no fire doors either! This PR corrects that.
clonk
:cl:
fix: Fix missing fire alarms
/:cl:
> Adds a lot of missing fire shutters to the sulaco. Sister commit to the fire alarms.

- code/modules/projectiles/gun_attachables.dm
Fixed some descriptions in attachments
More accurate descriptions help marines choose their loadout better.
:cl:
fix: fixed some inaccurate gun attachment descriptions
/:cl:
> Fix gun attachments descriptions

- code/modules/modular_armor/storage.dm
Minor fixes to descriptions
Honestly says what they do
:cl:
fix: Modules provide accurate descriptions
/:cl:
> Fixes wording in modules

- code/__DEFINES/skills.dm
- code/game/objects/items/stacks/stack.dm
Boost engie construction time 
Less cadehugging, more combat engies. Maybe?
:cl:
balance: Engies build faster
/:cl:
> Engies build faster

- code/__DEFINES/dcs/signals.dm
- code/datums/keybinding/xeno.dm
- code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
Adds a hotkey binding for Scatterspit.
Adds a hotkey binding for Scatterspit.
:cl:
add: Hotkey binding added for Scatterspit.
/:cl:
> Scatterspit Hotkey

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Just POS mapping fix. Please don't turn me into a mapper, ghosts 
Make thing work
:cl:
fix: fixed POS garbage conveyor & a superfluous wall
/:cl:
> Bunga. Removes a ugli wall from POS garbage & make the disposals work

- code/__DEFINES/mode.dm
- code/modules/mob/living/carbon/xenomorph/abilities.dm
Silo from 900 to 1200. Some feedback when building silo so xenos know their price
Cocoon is in the game, it's easy to get mass psy points so this is needed to make marine first push not as decisive
:cl:
balance: Silo price up from 900 to 1200
qol: Feedback message when you build a silo so you know its price
/:cl:
> Silo price up

- code/modules/client/preferences.dm
adds tgui preferences to char setup
gives preference settings for people about tgui, so if they use linux, old windows or something they can turn compatible mode, solve many monitors issues etc
:cl:
qol: added tgui preferences to char setup
/:cl:
> TGUI Preferences to char setup

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
remove some lights and ads a new vent system to PoS prep
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
> Venting out lights for PoS

- code/modules/mining/remote_fob/remote_fob_fobdrone.dm
AI couldn't see shit using the drone. This fixes that in a simple way. 
Seeing good.
:cl:
fix: fix the AI being blind while using the FOB drone.
/:cl:
> Booga Booga the FOB drone has a light now so you can see things.

- code/game/objects/structures/cas_plane_parts.dm
- code/game/objects/structures/dropship_equipment.dm
Just a missing examine. Where are my tendies. 
:cl:
fix: You can now see the amount of ammo the condor minigun has by just looking.
/:cl:
> You can see how much ammo the condor minigun has now. Also typo fix.

- code/game/objects/items/stacks/sandbags.dm
- code/game/objects/items/storage/pouch.dm
Title
Sandbags are absolutly not convenient to use, this fixes it. Real combat engie one day?
:cl:
balance: Sandbags are no longer bulky, can hold in construction pouch and be build faster by engies
/:cl:
> Sandbags are no longer bulky, can hold in construction pouch and be build faster by engies

- code/game/objects/items/explosives/grenades/marines.dm
> Fix certain nades always harddelling

- code/_onclick/click.dm
- code/game/objects/items.dm
Hmm yes shitcode that falls apart when you touch it
:cl:
fix: fix uniqueaction not working
/:cl:
> Fix uniqueaction

- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
the medbeam shouldn't be as avalibable as it is right now
5 second cd of a decent continous healing beam that heals sunder rapidly is dumb
:cl:
balance: healing infusion cd increased
/:cl:
> nerfs healing infusion cd

- code/modules/projectiles/gun_helpers.dm
:cl:
fix: fixed a exploit with rightclicking on guns
/:cl:
> Fix rightclick safety thing

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Just fix the APC not having power
Pepsico
:cl:
fix: Missing wire in POS hangar fixed
/:cl:
> Missing wire in hangar

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
AI is less blind, especially in random places like in the middle of some hallways.
Just seems like cool vibes really.
:cl:
fix: fix weird gaps in camera coverage on pillar of spring.
/:cl:
> Adds more cameras to the POS

- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Add hard del protection to observers in candidate queue for larvas
:cl:
fix: No more negative burrowed larva
/:cl:
> Queue larva system hard del protection

- code/modules/mob/living/carbon/xenomorph/abilities.dm
Title
Useless remnant from cap gameplay
:cl:
del: Nests are no longer buildable
/:cl:
> Nests are no longer buildable

- code/datums/jobs/job/xenomorph.dm
- code/modules/mob/living/carbon/xenomorph/evolution.dm
Title
We have time lock for marines important role, the same should be true for the leader of the hive. You need the queen to know the game enough to be able to lead, and 10 hours seems fine to me.
Queen is even more important due to psy points, because only her can devo the crazy hivelord that is spending all the points in turrets near fob
:cl:
admin: Queen time role is time locked (10 hours)
/:cl:
> Queen time lock (10 hours)

- code/datums/jobs/job/shipside.dm
Marine boots that used to start empty now start full; mostly shipside roles such as RO and CSE, and roles like FC that should have had full boots in the first place.
Fixes an oversight.
:cl:
qol: Certain roles that used to have empty combat boots, such as FC and CSE, now start with a boot knife in them on spawn.
/:cl:
> Marine Boots QoL

- code/modules/reagents/reagents/medical.dm
Makes arithrazine scannable
Peri+ injectors have 2 units of unknown, now it will be known. Plus youll know if you OD someone on Arith.
:cl:
qol: arithrazine becomes scannable
/:cl:
> arithrazine scanning

- code/game/objects/items/reagent_containers/autoinjectors.dm
Replaces Arith with Hyro in injectors.
Arith is more expensive to make, worse, and dangerous. There is literally no reason for it to be in injectors other then to nerf the usage.
:cl:
qol: Swaps arith for hyro in injectors
/:cl:
> Arith Replacement

- _maps/map_files/BigRed_v2/BigRed_v2.dmm
- _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
- _maps/map_files/LV624/LV624.dmm
- _maps/map_files/Lava_Outpost/LavaOutpost.dmm
- _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
- _maps/map_files/MarineHQ/MarineHQ.dmm
- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
- _maps/map_files/Research_Outpost/Research_Outpost.dmm
- _maps/map_files/Sulaco/Sulaco.dmm
- _maps/map_files/Theseus/TGS_Theseus.dmm
- _maps/map_files/debugdalus/tgs_debugdalus.dmm
- _maps/map_files/icy_caves/icy_caves.dmm
- _maps/modularmaps/big_red/operation.dmm
- _maps/modularmaps/lv624/atmospherics.dmm
- _maps/modularmaps/lv624/cargo_bay.dmm
- _maps/modularmaps/lv624/internal_affairs.dmm
- _maps/modularmaps/lv624/robotics.dmm
- code/modules/power/cable.dm
Fixed the powernet/ disposalnet and atmosnet on pretty much all maps (except WO and vapor processing, etc.)
Redid SMES setup in Ice colony because it was THAT awful.
Fixed bunch of camera dirs.
Now pretty much all maps should have working powernets and stuff at roundstart without any benos sabotaging by melting shit.
[Please](https://cdn.discordapp.com/attachments/643135004926541824/825813257351725056/unknown.png)
[STOP](https://cdn.discordapp.com/attachments/643135004926541824/825813298335187014/unknown.png)
[I BEG YOU](https://cdn.discordapp.com/attachments/643135004926541824/825813355117281330/unknown.png)
[MAKE IT STOP!](https://cdn.discordapp.com/attachments/643135004926541824/825813555240108042/unknown.png)
^ These are the worst offenders in my journey. …
> Fixes/Changes Powernet/ Disposalnet and Atmosnets on most maps (and some cameras)

- code/modules/clothing/suits/labcoat.dm
Minor changes to the armored lab coat, pretty much making it how it was intended to be
Makes the coat how it was envisioned to be
:cl:
balance: Armored lab coat weight 0.3 -> 0.2
balance: Armored lab coat coverage increased to full body -head
balance: Armored lab coat soft melee protection 35% -> 30%
/:cl:
> Minor buff to armored labcoat

- code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
-0.4 to .1
drone shouldn't be as fast as an ancient runner on weeds considering it can make weeds itself and has decent utility overall
this caste has been massively powercreeped overtime 
:cl:
balance: drone speed up on weeds reduced
/:cl:
> drone speed up from weeds massively reduced

- code/modules/mob/living/carbon/xenomorph/abilities.dm
- code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
- code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
You can switch spits just by clicking the spit button, both actions are merged
Less buttons is good
:cl:
qol: Select spit and spit buttons are merged
/:cl:
> One less button, merge spits button

- code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Title
:cl:
fix: Wraith get psy drain
/:cl:
> Wraith get psy drain

- code/modules/mob/living/carbon/human/examine.dm
Adds an examine message whenever someone is aslept, more like a QOL. It is a semi-direct port from CM.
There, all safe and sound.
:cl:
qol: Added an examine message whenever someone was admin slept.
/:cl:
> Asleep examine message

- code/game/objects/items/weapons/misc.dm
Powerfist uses lasgun battery, 1k capacity. 
No longer need a screwdriver to remove battery, just clips the next battery into the power fist
One standard battery can now provides 11 max setting punch, rather than 33 with a 10k high cap battery
A powerfist will throw at max setting big mob (like queen) 6 tiles away (rather than.... 15), drone (standard xenos size) 9 tiles away, and human 12 tiles away
Make this weapon less of a broken meme toy for marines. Changing the battery is also more convenient, and they are more available
:cl:
balance: Power fist throw distance is now linear with the mob size
balance: Powerfist only takes now lasgun battery as power source. That mean 3 times less punch per battery overall. You can change the battery just by clicking on the powerfist with a full one, …
> Power fist balance (another PR, yes)

- code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
- code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
Shrike and queen lose the ability to produce eggs, defiler gains it
Remnant of capture gameplay begone. Defiler get it because it can make egg bomb
:cl:
balance: queen lose the ability to produce eggs, defiler gains it
/:cl:
> Eggs can be done only by defiler

- code/modules/mob/living/carbon/xenomorph/abilities.dm
Apparently the operation * takes priority on ?   . 
:cl:
fix: Silo price fixed
/:cl:
> Fix silo price

- code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
Title
Can lay it currently but not plant, fix
:cl:
fix: Defiler can lay eggs
/:cl:
> Defiler can actually plant eggs

- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Title. Sometimes it was 2.5 minutes
2.5 minutes is so short that some hives die cause drone forget to go to shrike. This is ridiculous
:cl:
balance: Hivemind collapse will now ALWAYS be 5 minutes
/:cl:
> Hivemind collapse will now ALWAYS be 5 minutes

- code/modules/projectiles/ammo_datums.dm
See title.
Because it's funny.
:cl:
balance: gives slugs the same slowdown that TX15 slugs have.
/:cl:
> Slugs have slowdown again

- code/game/objects/effects/aliens.dm
- code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
- code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
Rework made acid spray not having the same behaviour as before, this fixes it
Also make fresh acid stun for 1 second rather than 0.5, since apparently 0.5 was not enough to fix the exploit
:cl:
fix: Prae acid spray back to normal
balance: Fresh acid (from acid spray) stun when you walk on it, acid is considered fresh for 1 second rather than 0.5 previously
/:cl:
> Prae spray behaviour fix

- code/modules/projectiles/ammo_datums.dm
Reduces the damage and Sunder of the AT rifle.
Absurdly overpowered. Even more so when stacked up.
:cl:
balance: Reduces damage and sunder of AT Sniper.
/:cl:
> AT Sniper nerf

- _maps/modularmaps/EORG/basketball.dmm
- code/modules/mapping/modular_mapping.dm
Nearly full map:
:cl:
add: Added the Basketball Arena as one of the EORD options, map made by me.
/:cl:
> Basketball Arena End of Round Deathmatch map

- code/modules/mob/living/carbon/xenomorph/abilities.dm
- code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
- code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
- code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
- code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
- code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Remove nest being buildable for good and merge select resin and build resin in one button
Buttons bloat begone
:cl:
fix: Nests are really gone now
qol: Select resin and build resin buttons are merged
/:cl:
> Remove nests for good and remove one button

- code/datums/emergency_calls/sonsofmars.dm
- code/datums/emergency_calls/upp.dm
:cl:
fix: Fixed HvH variants of ERT that will despawn automatically after spawning.
/:cl:
> HVH ERT Fix

- code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
Carrier is able to lay eggs
Carrier is the class that has the most reason to have eggs right now. It is able to store eggs, but not make it?
It is also the king of traps, and laying eggs is totally in its spirit.
It allow carrier to have a backup of huggers in certain zone, and overall gives it more strategic possibilites
:cl:
balance: Carrier can lay eggs
/:cl:
> Carrier can lay eggs

- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Silo less will now take 5 minutes, rather than 10 minutes
Small pools are here, so halving the time required to make a pool when a pool is basicly half the price makes sense.  
Keeping it at 10 would allow to much delay IMO
:cl:
balance: Silo less timer from 10 minutes to 5
/:cl:
> Silo less from 10 minutes to 5

- code/_onclick/click.dm
- code/modules/projectiles/gun_system.dm
Allow to click drag on black tiles while shooting. 
Huge QOL when shooting. Can hurt performance, so should be TM'd before merging
:cl:
qol: You can aim at black tiles while shooting
/:cl:
> You can aim at black tiles while shooting

- code/datums/atom_hud.dm
Title
Might be useless, might fix https://github.com/tgstation/TerraGov-Marine-Corps/issues/6382
:cl:
code: Protection against temporary visuals hard del
/:cl:
> Protection against temporary visuals hard del

- code/game/objects/items/tools/extinguisher.dm
:cl:
qol: Clicking yourself with the fire extinguisher while on HELP intent and with the safety off will extinguish yourself instead of bashing.
/:cl:
> Extinguisher QOL

- code/game/objects/items/storage/backpack.dm
- code/game/objects/structures/mortar.dm
makes frontlnie mortar more viable and adds more interesting options to the game
:cl:
balance: mortar kit and shells are bulky rather than huge, engineer bag is able to hold them
/:cl:
> mortar kit and shells are bulky rather than huge, engineer bag is able to hold them

- code/modules/mob/living/carbon/human/species.dm
This is my meme PR for the month.
You thought I was joking, Tivi? Think again.
:cl:
add: Adds handholding. Now you can hold your SL's hand before you get atomized by GOOD HITS. Help intent and aim at either hand (not arm). Locked behind fun config.
/:cl:
> Handholding

- code/game/objects/items/weapons/twohanded.dm
It's a spear buff. It's still weaker than a machete one-handed, but since it's a spear and not a bulky fire-axe, you realistically can still do pokey with it. Wielded, matches fire axe, because needs both hands. Has reach of 2 because spears are long, and historically in the code spears have always been the reach thing. That's their thing. 
If someone wants to go dumb unga they can now. That's basically it. I doubt many people, or any really, will use these over guns and actually be effective with them at all. 
:cl:
balance: Buffed spears. 
/:cl:
> Spear Buff.

- code/modules/mob/living/carbon/xenomorph/abilities.dm
Lay egg was removed from queen, but given to carrier, and defiler. Despite this the cost for egg laying completely bulldozes whatever plasma they'd have, especially for defiler considering how slow their plasma regen is
Can't be used much when it uses up all your plasma, Lowered from 400 to 200
:cl:
balance: Lowered the cost for laying eggs from, 400 plasma to 200 plasma.
/:cl:
> Halves lay egg cost

- code/_onclick/hud/screen_objects/screen_objects.dm
Title
There was no hardel protection
:cl:
fix: CIC order and rally no longer runtime
/:cl:
> Stop arrow from runtiming

- code/datums/gamemodes/crash.dm
- code/datums/gamemodes/distress.dm
- code/datums/gamemodes/extended.dm
- code/datums/gamemodes/infestation.dm
- code/datums/jobs/job/marines.dm
- code/modules/projectiles/guns/rifles.dm
- code/modules/reqs/supplypacks.dm
🆑 
add: Smartgunner is back
/🆑
> Revert "disables smartgunner, makes smart machinegun useable by anyone"

- strings/tips/marine.txt
- strings/tips/meme.txt
- strings/tips/meta.txt
- strings/tips/xeno.txt
:cl:
fix: Tips are updated, removed some outdated tips.
/:cl:
> Tips update

- code/controllers/subsystem/vote.dm
- code/datums/gamemodes/crash.dm
- code/datums/gamemodes/distress.dm
Title
Was like that before
:cl:
admin: Automatic votes at the end of each round
/:cl:
> Automatic votes at the end of each round

- code/game/objects/items/storage/belt.dm
- code/modules/projectiles/gun_helpers.dm
Now if your hands are full, or there is a magazine in your gun, Pistol Belt reloading will instead perform a "Tactical Reload"
Nerfs insta reloading for akimbo pistols.
Also changes the tactical reload code slightly to make this easy.
:cl:
balance: Now if your hands are full, or there is a magazine in your gun, Pistol Belt reloading will instead perform a "Tactical Reload"
/:cl:
> Nerfs Pistol Belt Reloading

- code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
less slash
hunter shouldn't be doing this much damage
:cl:
balance: nerfs hunter slash by 3 points, weed speed from -0.4 to .1 and he's slightly slower off weeds too
/:cl:
> hunter nerf, speed and slash nerf

- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/magazines/rifles.dm
br gets 40 round magazines
dmr gets slightly faster wield delay and less aim mode slowdown
battle rifle is bad, it should've had double the mag capacity from the start
dmr is a bit bad, it could use some minor love
:cl: 
balance: dmr has slightly less slowdown, less aim slowdown, and battle rifle has had its capacity upped from 25 to 35
/:cl:
> bbuffs dmr and br

- code/modules/admin/admin_verbs.dm
- code/modules/admin/holder.dm
Admin requested for events
:cl:
admin: Mass replace admin verb
/:cl:
> Mass replace admin verb

- code/modules/projectiles/gun_helpers.dm
I broke tactical reloading by missing one character, the all important '!'
bug fix, merge please before i get buried in angry pings
:cl:
fix: fixes tactical reloading
/:cl:
> fixes tactical reloading

- _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Fixes this:
Doesn't deserve a changelog
idk, map look good, life good?
> Fixes the biggest sin on prison

- code/game/turfs/walls/wall_types.dm
Rouny cute
:cl:
add: New releases from TerraGov Publishing! Rouny the Big Red Dog will teach the world how to love big.
/:cl:
> Adds Rouny: the Big Red Dog Title screen

- code/game/objects/items/weapons/blades.dm
Makes the Claymore that spawns in the Captain's Room on Theseus the same force as machetes. RenGusta asked me to do this.
consistant damage values are good??
:cl:
balance: the captain's Claymore should now have slightly more damage
/:cl:
> Buffs Claymore

- code/modules/client/preferences_gear.dm
Adds a Flower Pin to the loadout menu.
Cute! :D
:cl:
add: Added a Flower Pin to the loadout menu.
/:cl:
> Flower pin.

- code/game/objects/items/storage/boxes.dm
Makes it so you can instantly pick up all ammo in a tile to the ammo box á la trashbags.
One line PR lets go
Not having to spam left click and e to fill ammo boxes is good. Less prep time.
:cl:
qol: You can now click a stack of magazines with the ammo box to fill the ammo box with.
/:cl:
> Ammo Box Pickup QoL

- code/modules/mob/living/carbon/xenomorph/abilities.dm
Title
:cl:
fix: Can psydrain / cocoon stacked bodies
/:cl:
> Psy drain and cocoon couldn't be used on stacked bodies. It's the fix

- code/controllers/subsystem/vote.dm
- code/datums/gamemodes/crash.dm
- code/datums/gamemodes/distress.dm
First ship map will happen 5 seconds after the end of round, not 70 seconds
EORD is too short, and groupmap didn't have time to proc apparently
:cl:
admin: Shipmap and Groundmap votes happen sooner
/:cl:
> Tweak vote timer

- code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
Brings back a bit of depended upon code lost during #5803 probably because it is also was what the hive status used, and testing requires using multiple clients.
Software regression bad. Fix good.
:cl:
fix: Xeno Queen overwatch from hivemind chat works again!
/:cl:
> Fixes Xeno Queen overwatch using hivemind chat

- code/modules/paperwork/paper.dm
Updated the Vali manual to be in-line with the last rework.
less mhelps
:cl:
qol: updated Vali manual to be in-line with the recent rework of the active effect
/:cl:
> Vali instructions page update

- code/datums/gamemodes/game_mode.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/mob/mob_verbs.dm
Title
:cl:
admin: Bypassing respawn as an admin will leave a trace in admin logs
/:cl:
> Log admin respawns

- code/controllers/subsystem/overlays.dm
https://github.com/tgstation/tgstation/pull/58378/files
> Fix SSoverlays holding too many icons

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
- _maps/map_files/Sulaco/Sulaco.dmm
- code/game/objects/structures/reagent_dispensers.dm
fixes a few issues, for instance the POS and Sulaco ones were in showers and space respectively. also makes it actually refill like glasses and stuff. and please, stop calling it horny code and what not if you don't actually meaning, its really stressing me out and making me feel bad
because its currently broken
:cl:
fix: milk dispenser placements
/:cl:
> Fixes milk dispenser bugs and unintended placements

- code/_compile_options.dm
- code/modules/client/client_procs.dm
49 is latest stable beta
:cl:
code: Suggested byond versions have been updated
/:cl:
> update byond ver reccomedations

- code/datums/actions/order_action.dm
Title
:cl:
fix: You will no longer be ordered to attack the floor
/:cl:
> Orders now use area

- code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Fixes non-larval huggers not attacking infected humans.
Fixes a bug.
:cl:
fix: Fixes non-larval huggers not attacking infected humans.
/:cl:
> Fixes Combat Huggers not Attacking Infected Humans

- code/game/objects/items/storage/storage.dm
Fixes: #6202 
Exploit bad. Fix good. If you use this exploit before a merge and update I will find you and I will drown you in milk.
:cl:
fix: Fixed being able to remove items from storage on your person once dead.
/:cl:
> Fixes being able to remove items from storage while dead

- code/game/objects/items/reagent_containers/food/snacks.dm
You know who you are
Cleaned up some baycode mess
:cl:
qol: monkey cubes now tell you when they're wrapped
code: cleaned up monkey cube code
/:cl:
> Monkey cubes will now tell you how to use them + cleanup

- code/game/objects/structures/stool_bed_chair_nest/bed.dm
title
:cl:
qol: Medevac beds can be instantly activated with right click
/:cl:
> Medevac beds can be instantly activated with rclick

- code/__DEFINES/equipment.dm
- code/__HELPERS/icons.dm
- code/game/objects/machinery/doors/airlock.dm
https://github.com/tgstation/tgstation/pull/58607/files
> icon2html optimization

- code/controllers/subsystem/minimaps.dm
- code/controllers/subsystem/vote.dm
- code/datums/map_config.dm
Title
Prevent some runtime and the backup solution is needed for CBT tests to pass
:cl:
code: Prevent runtimes when config failed to load + backup solution when next_map.json is not found
/:cl:
> Prevent runtimes when config failed to load + backup solution when next_map.json is not found

- code/modules/reagents/reagents/toxin.dm
Title, fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/6619 
That made Defiler reagent slash seriously useless. It was a reliquat of cap gameplay, there are no reason for larval to be beneficial for the marine
:cl:
balance: Larval won't purge neurotox
/:cl:
> Larval won't purge neurotox

- code/__DEFINES/calibers.dm
- code/game/objects/items/storage/backpack.dm
- code/game/objects/items/tools/maintenance_tools.dm
- code/game/objects/machinery/sentries.dm
- code/game/objects/machinery/smartgun_mount.dm
- code/modules/projectiles/ammunition.dm
- code/modules/projectiles/guns/pistols.dm
- code/modules/projectiles/guns/revolvers.dm
- code/modules/projectiles/guns/rifles.dm
- code/modules/projectiles/guns/shotguns.dm
- code/modules/projectiles/guns/smgs.dm
- code/modules/projectiles/guns/specialist.dm
- code/modules/projectiles/magazines/flamer.dm
- code/modules/projectiles/magazines/pistols.dm
- code/modules/projectiles/magazines/revolvers.dm
- code/modules/projectiles/magazines/rifles.dm
- code/modules/projectiles/magazines/shotguns.dm
- code/modules/projectiles/magazines/smgs.dm
- code/modules/projectiles/magazines/specialist.dm
- code/modules/vehicles/multitile/hardpoints.dm
- tgmc.dme
Went through the code and made all calibers i could find a #define.
Pretty much code cleanup because i plan on doing stuff with ammo in the near future.
Cöde clean
:cl:
code: calibers are now defines.
/:cl:
> #DEFINEd calibers in cöde

- code/modules/mob/living/carbon/xenomorph/abilities.dm
Removes Headbite from Crash v3 with less commits please god
Wasn't needed, and shouldn't exist in crash, only Hunt.
:cl:
balance: Removed Headbite from Crash.
/:cl:
> Crash Headbite Removal V3

- code/modules/modular_armor/modular.dm
Greyscale jaeger and bird's pr fixed the same issue twice
> Remove duplicate checks

- code/__DEFINES/calibers.dm
- code/modules/projectiles/ammunition.dm
- code/modules/projectiles/guns/shotguns.dm
- code/modules/projectiles/guns/specialist.dm
- code/modules/projectiles/magazines/shotguns.dm
- code/modules/projectiles/magazines/specialist.dm
> Change accidentally lowercase define

- code/game/objects/structures/barricade.dm
titel
:cl:
qol: Cades can be rotated instantly clockwise with right click
/:cl:
> Cades can be rotated instantly clockwise with rclick

- code/datums/jobs/job/job.dm
- code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/xenomorph/xeno_structures.dm
Fix negative burrowed. No bug sighted for now. Ready to merge
Xeno economy suffers from larva debt, stop the larva debt
:cl:
fix: Negative larva fixed
/:cl:
> Fix larva queue

- code/modules/mob/living/carbon/xenomorph/abilities.dm
Lol
:cl:
fix: Small silo cannot be placed in medium-high pop
/:cl:
> Fix small silo being placeable on high pop

- code/controllers/subsystem/direction.dm
- code/datums/jobs/job/shipside.dm
- code/datums/jobs/squads.dm
- code/game/objects/items/radio/headset.dm
- code/game/objects/machinery/nuclearbomb.dm
Cleanup
Less awful var naming
autodoc
replace magic strings with defines
fix missing SS recover
remove dead end and dupe code
:cl:
code: HUD tracker code improvements
/:cl:
> Tracker cleanup

- code/__DEFINES/attachments.dm
- code/modules/codex/entries/weapons_codex.dm
- code/modules/projectiles/gun_attachables.dm
- code/modules/projectiles/gun_helpers.dm
- code/modules/projectiles/gun_system.dm
- tgmc.dme
Fixed stuff not using defines when it should, qdeleting images, bad var names and a bit more
:cl:
code: improved attachment code
/:cl:
> Attachment code improvements

- code/modules/power/apc.dm
Looks cool
:cl:
qol: APC screens now glow
/:cl:
> Emissive apcs

- code/__HELPERS/icons.dm
https://github.com/tgstation/tgstation/pull/58796/files
> icon2html supports MA's

- code/modules/admin/verbs/adminhelp.dm
This shouldve been the case anyway but who knows why its so inconsistent
> Code improve return ahelp I guess

- _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
Minor change to attempt to res git
@TiviPlus
> Incredible change to attempt to resurrect git

- code/modules/mob/living/carbon/xenomorph/abilities.dm
Adds a check for whether there is a wall at/behind/left/right of a silo spot before being able to place one.
Less silos abuse. maybe less ahelps.
:cl:
balance: added a check for whether there is a wall at/behind/left/right of a silo spot before being able to place one
/:cl:
> Makes silos unable to be placed near walls as much

- code/_onclick/hud/screen_objects/menu_text_objects.dm
was runtiming if it inited after ssatoms
:cl:
fix: fixed lobby characters not setting properly
/:cl:
> Fix name not appearing in  lobby ui properly

- code/game/objects/machinery/vending/marine_vending.dm
- code/game/objects/machinery/vending/vending.dm
Title. Also, you can set two different vendor so their inventory isn't shared (team_one and team_two)
HvH one day?
:cl:
add: HvH vendors are now tabbed vendors
/:cl:
> Update HvH vendor to be tabbed one

- code/modules/projectiles/gun_helpers.dm
You can tac reload while moving
I think tac reloads aren't very useful since you have to stop moving to do it. This will make them a little more useful.
:cl:
balance: You can tac reload while moving
/:cl:
> Tac Reload Buff

- code/modules/projectiles/guns/smgs.dm
title.
all guns fit on back this doenst fit on back because no reason at all annoying as balls(it fits in suit storage its just annoying when running two guns)
:cl:
balance: PPSh now fits on back.
/:cl:
> PPSh now fits on back slot.

- code/modules/reqs/supplypacks.dm
Title
It's absolutly USELESS. You can sell with a fulton without a beacon
:cl:
del: Remove fulton beacon from req
/:cl:
> Remove fulton beacon from req

- code/game/objects/items/stacks/sheets/glass.dm
- code/modules/projectiles/guns/specialist.dm
Method one-
Each T81 GL is worth 1.75 metal sheets when autolathed. No one ever takes them as they're single shot, so the 250 in the vendor became 430 metal sheets, or 8 and a half stacks.
They're now worth 10% of that, so yeah. No more shoveling half of the round's grenade launchers for near-unlimited metal.
Method two-
If you have an autolathe and a stack of 20 rglass, you can feed the rglass in.
Print off one sheet of rglass. Print off all the metal that the rglass gave you, 9 or 10 sheets. Print off a stack of 19 glass.
Click on the glass with the rglass. Now you have 9 metal created from nothing, 20 rglass, and an autolathe ready to go again. Elapsed time: 5-10 seconds for around 10 metal.
This brute-force fixes the metal glitch by making it so low value it's not worth attempting. If …
> In which two ways to get large quantities of metal for no cost are described fully and completely.

- code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Wraiths Can't Banish While Incorporeal
Wraiths Can't Banish While Incorporeal
:cl:
balance: Wraiths can no longer Banish while incorporeal.
/:cl:
> Wraiths Can't Banish While Incorporeal

- code/game/objects/machinery/doors/poddoor.dm
- code/game/objects/machinery/doors/railing.dm
- code/game/objects/machinery/doors/shutters.dm
- code/game/objects/machinery/doors/windowdoor.dm
All parts not working reverted #6746
:cl:
fix: Invisible shutters
/:cl:
> Revert parts not working of #6746

- code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Removes an excess cooldown notification from Phase Shift.
Removes an excess cooldown notification from Phase Shift.
:cl:
qol: Removes an excess cooldown notification from Phase Shift.
/:cl:
> Excess Cooldown Notice Removal for Phase Shift

- .gitignore
- .vscode/tasks.json
Remove old task that i forgot maybe? Though i deleted it.
Also add tgmc.mdme to gitignore as it's a temp file anyway. That will make it possible to commit in the middle of a build
:cl:
code: No more VSC warning
/:cl:
> Fix vsc warning when building

- code/_compile_options.dm
1554 is stable apart from the malformed sendmaps json which we dont use
> Update reccomended compile vers

- _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
linters was warning me of shitty var-edited sandbags in WO, which weren't even the correct dir, they are now gone
idk, you guess
> fixes Whisky Outpost Sandbags (and map linters?)

- code/modules/projectiles/guns/energy.dm
- code/modules/projectiles/magazines/energy.dm
a
:cl:
fix: Minor fixes to Terra Experimental weapons and ammo.
/:cl:
> Minor TE description changes

- code/modules/clothing/under/ties.dm
webbing is bulky
so you can't carry 3x the ammo in a backpack
:cl:
balance: webbing is bulky now
/:cl:
> webbing is bulky

- code/modules/client/preferences_ui.dm
- code/modules/mob/new_player/preferences_setup.dm
The species was wrongly set on create_random_character, and it prevented hair choices. This is the fix
We missed grad hair
:cl:
fix: You can chose your hair now
/:cl:
> Fix hair choice on new character

- code/game/objects/items/reagent_containers/reagent_container.dm
ergonomics and QoL
:cl:
qol: Rclick now lets you change the reagent transfer on ANY reagent container
/:cl:
> Rclick now lets you change the reagent transfer on ANY reagent container

- code/modules/reqs/supply.dm
Mistook an assoc list for a flat list. Meant that supply console was breaking on the second supply buy
:cl:
fix: Supply console fixed
/:cl:
> Fix supply not working

- code/game/objects/machinery/sellingpad.dm
- code/modules/reqs/supply.dm
- code/modules/requisitions/fulton.dm
Export history was breaking when an incorrect object was sold. This is the fix. With some luck, the last fix needed (sigh)
:cl:
fix: Export history
/:cl:
> Export history fix

- code/datums/gamemodes/infestation.dm
Fix base turf
:cl:
fix: Resin walls no longer invicible
/:cl:
> Fix invicible resin walls

- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Fixes Distance Stacking for Hugger Trap Alerts
Fixes Distance Stacking for Hugger Trap Alerts
:cl:
fix: Hugger trap alert output fixed.
/:cl:
> Fixes Distance Stacking for Hugger Trap Alerts

- code/datums/jobs/job/xenomorph.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Fix the ugly runtime from larva spawning in null space
:cl:
fix: Larva on minimap
/:cl:
> Larvas are on minimap

- .github/workflows/run_approval.yml
Will auto approve first time workflows on pr creation or every 10 minutes unless it touches build.bat or github actions
shameless webedit
> Automatic approve workflows

- code/game/objects/machinery.dm
- code/game/objects/structures/dropship_equipment.dm
- code/modules/mob/living/carbon/xenomorph/castes/wraith/wraith.dm
- code/modules/mob/living/carbon/xenomorph/hive_datum.dm
- code/modules/projectiles/gun_attachables.dm
- code/modules/projectiles/gun_helpers.dm
- code/modules/projectiles/gun_system.dm
- dependencies.sh
> Update to spacemandmm 1.7

- code/game/objects/machinery/vending/marine_vending.dm
- code/modules/projectiles/gun_attachables.dm
Makes your bullets faster, thats it
It makes bullets faster at the cost of not having any other barrel attachment
:cl:
balance: added a marine barrel attachment that makes bullets faster
/:cl:
> Adds a marine attachment that makes your bullets faster

- .github/workflows/run_approval.yml
> Dont run approval on prs

- code/game/objects/structures/barricade.dm
Sandbag barricade icons now update when repaired
Noticed this while playing and figured it should be easy to fix. It was. Small problem, small pr.
:cl:
fix: Sandbag barricade icons now update when repaired
/:cl:
> Sandbag barricade icons now update when repaired

- code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
- code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Readded Recall due to popular demand.
Readded Wraith's Recall so Wraiths can click spam Banish again.
:cl:
qol: Readded Wraith's Recall due to popular demand so Wraiths can click spam Banish again.
/:cl:
> Recall Reinstated

- code/__HELPERS/mobs.dm
- code/modules/mob/new_player/preferences_setup.dm
Fixes the pref random_char species selection code runtime.
Also datum/namepool/clf (which doesn't have valid name lists??) was hardcoded to get unique names from?
Note that local testing might default you to a random guest account causing you to not save/ load prefs.
I am sick of the runtimes everytime i start the game in VSCode.
:cl:
fix: random char runtimes
/:cl:
> Pref rand char fix

- code/game/objects/machinery/vending/vending.dm
I didn't push the right version last PR, so it had no chance of working
:cl:
fix: Restocking works
/:cl:
> Fix restocking

- code/__DEFINES/dcs/signals.dm
- code/datums/keybinding/xeno.dm
Add a keybind for vent crawl
Death to macros
:cl:
add: Keybind for vent crawl
/:cl:
> Keybind for vent

- code/modules/shuttle/shuttle.dm
Title
:cl:
fix: Fix ert shuttles and canterbury
/:cl:
> Fix ert shuttles and canterbury

- code/modules/mob/living/silicon/ai/ai.dm
Title. Maybe there's a better way of doing this? 
:cl:
fix: Fix AI not being able to give orders ground side
/:cl:
> Fix AI not being able to give orders ground side

- code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
- code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
Tail Sweep is now activated instantly rather than being used via middle click.
SFX/sound added to Tail Sweep.
Tail Sweep usage QoL improved.
Tail Sweep SFX are improved.
:cl:
qol: Tail Sweep is now used instantly when clicked or its hot key is used.
code: Tail Sweep cosmetics/sound improved.
/:cl:
> Tail Sweep SFX and QoL Improvements

- code/modules/projectiles/projectile.dm
Added a new var on projectile, the friendly_fire_multiplier var. This will reduce the damage from FF
FF is a terrible mechanic because it punishes the victim of the bad player that just sprayed around.
This is an easy solution that has the benefits of not touching to HvH, and not affecting the HvX balance too much.
I've chose a var on the projectile rather than a global var cause MJP asked to be able to balance for each gun
:cl:
balance: Damage from friendly fire is reduced a tiny bit
/:cl:
> Friendly fire damage is reduced

- TGS3.json
https://github.com/tgstation/tgstation/pull/55403
Brought to you by me.
Webedited by me.
Found by me.
> changelogs compiling no longer supported by tgs3

- code/game/objects/machinery/doors/airlock.dm
Airlocks gained 20 melee armor. Knifebashing a metal door is an unfunny meme.
I suppose I should figure out how to log this for admins. *sigh*
Airlocks gained 20 melee armor. They'll gain admin logging once I figure out how to do this.
We're apparently MRP, and beating down airlocks with knives is kinda weird. Use a machete at least.
:cl:
balance: Airlocks have melee armor
/:cl:
> Airlock changes

- code/modules/error_handler/error_handler.dm
https://github.com/tgstation/tgstation/pull/59049/files
> preserve oom runtimes

- code/game/atoms_movable.dm
https://github.com/tgstation/tgstation/pull/59223/files
> Always call moved on doMove

- code/__DEFINES/dcs/helpers.dm
- code/datums/components/_component.dm
https://github.com/tgstation/tgstation/pull/59185/files
> Loadcomponent to macro

- code/datums/components/_component.dm
https://github.com/tgstation/tgstation/pull/59116/files
> Fix a signal unregister bug

- code/datums/components/udder.dm
- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
- tgmc.dme
https://github.com/tgstation/tgstation/pull/58910/files
you can milk anything shitcode free 
:cl:
refactor: refactored udders
/:cl:
> Refactor udders to a component

- code/controllers/configuration/configuration.dm
- code/datums/gamemodes/extended.dm
- code/datums/map_config.dm
- code/modules/admin/topic.dm
- config/modes.txt
Small mode config refactor. Extended is no longer a special mode for some reason. Allow to add HvH gamemode without being votable
:cl:
config: Extended now is in modes.txt
/:cl:
> Extended now is in modes.txt

- code/__DEFINES/MC.dm
- code/__DEFINES/_subsystems.dm
- code/controllers/subsystem/timer.dm
- code/datums/datum.dm
https://github.com/tgstation/tgstation/pull/59073/files
https://github.com/tgstation/tgstation/pull/55803/files
> Port ss timer def and TIMER_DELETE_ME

- code/datums/components/_component.dm
- code/datums/datum.dm
https://github.com/tgstation/tgstation/pull/59154/files adaptation
> Port signal microopts

- code/controllers/subsystem/ambience.dm
https://github.com/tgstation/tgstation/pull/59071/files
:cl:
fix: ambience wont be played in lobby anymore
/:cl:
> Dont play ambience in lobby

- code/game/objects/machinery/squad_supply/supply_console.dm
Title
:cl:
fix: Fix supply drop console
/:cl:
> Fix supply drop console

- code/__DEFINES/cooldowns.dm
- code/modules/shuttle/mini_dropship.dm
10 seconds of cooldown when you land before being able to launch back
No more tadpole baiting, or at least harder to do
:cl:
balance: Added a cooldown to tadpole launching (10 seconds)
/:cl:
> Added a cooldown to tadpole launching

- code/modules/projectiles/magazines/pistols.dm
Fixes Auto9 mag sprite
gets rid of pointless lore
less autism in code
:cl:
fix:  Auto9 magazines should no longer look suspiciously like giant floating text that spelled out FIX
:cl:
> Fixes Auto9 mag sprite

- code/modules/projectiles/gun_system.dm
Title.
I don't even know why energy gun are snowflakes anyway, they have mags too?
:cl:
fix: gun can reload now
/:cl:
> Fix gun not reloading properly

- code/controllers/subsystem/input.dm
- code/modules/keybindings/bindings_client.dm
https://github.com/tgstation/tgstation/pull/59339/files
:cl:
code: client button hold optimizations
/:cl:
> port keyloop opts

- code/game/objects/machinery/computer/communications.dm
title
:cl:
fix: Sanatize command announces better
/:cl:
> Sanatize command announces better

- code/game/objects/obj_defense.dm
> Add Should call parent to obj_destruction

- code/game/objects/machinery/overwatch.dm
Title
:cl:
fix: fix overwatch
/:cl:
> Fix overwatch

- code/__DEFINES/spaceman_dmm.dm
> Auxtools Expression evaluation

- tools/tgs4_scripts/PreCompile.bat
@SplinterGP
already fixed this serverside this is the repo fix
> Server testmerge fix

- code/modules/reqs/supply.dm
- code/modules/shuttle/shuttle.dm
I broke the request console. This is the fix
:cl:
fix: Fix request console
/:cl:
> Fix request console

- code/modules/projectiles/gun_system.dm
Title
:cl:
fix: Fix runtime for gun keybinds
/:cl:
> Fix runtime for gun keybinds

- code/game/objects/items/binoculars.dm
could probably use signals instead of mouse intercept but lazy
:cl:
fix: binoculars now can laser target properly.
/:cl:
> fixes binoculars targetting

- _maps/map_files/Theseus/TGS_Theseus.dmm
minor theseus aesthetic improvements
> Theseus cameras and stuff

- code/game/objects/machinery/doors/airlock.dm
teh admins said they want it
:cl:
admin: Adds logging to shipside doors
/:cl:
> Adds logging to shipside doors

- code/modules/mob/living/living_verbs.dm
- code/modules/mob/logout.dm
Title.
Admins can check logs to see where ghosting happened.
:cl:
admin: Game logs now save the location of mob ghostings.
/:cl:
> Add location data to ghost verb logs

- code/__DEFINES/dcs/signals.dm
- code/datums/keybinding/human.dm
- code/modules/projectiles/gun_helpers.dm
- code/modules/projectiles/gun_system.dm
Title, as requested
:cl:
add: Fire mode keybind
/:cl:
> Fire mode keybind

- code/datums/gamemodes/distress.dm
- code/datums/gamemodes/game_mode.dm
- code/datums/gamemodes/hunt.dm
- code/datums/gamemodes/infestation.dm
Fix bioscans not working + make them a bit more consistent
:cl:
fix: Fix bioscans
/:cl:
> Fix bioscans

- code/controllers/subsystem/persistence.dm
title
FAMAS gaming
:cl:
balance: remove famas from seasonals
/:cl:
> Removes FAMAS from seasonals

- code/__DEFINES/jobs.dm
- code/datums/jobs/job/xenomorph.dm
- code/modules/mob/new_player/new_player.dm
Stop burrowed larva count from being hidden in lobby
This is just a terrible feature IMO. I added a warning, but knowing that xeno really have a ton of burrowed would probably incentivize players to go even more to xeno whenit's really needed
:cl:
qol: You can see how many burrowed there are from lobby
/:cl:
> You can see how many burrowed there are from lobby.

- code/game/objects/machinery/doors/airlock.dm
Title.
Headmin wants it.
:cl:
admin: Shipside airlock attacks now log to admin chat also.
/:cl:
> Log shipside airlock attacks to admin chat

- .vscode/launch.json
ports: https://github.com/tgstation/tgstation/pull/59295
> Run and Debug now uses Dream Daemon

- tgui/docs/component-reference.md
- tgui/packages/tgui/components/Box.tsx
ports: https://github.com/tgstation/tgstation/pull/59383
> preserve whitespace for box

- code/modules/keybindings/bindings_atom.dm
- code/modules/mob/mob_movement.dm
ports: https://github.com/tgstation/tgstation/pull/59558
:cl:
code: Input system won't request in-place movements constantly anymore.
/:cl:
> Prevent SSinput from constantly requesting moving in-place

- code/game/objects/items/weapons/shields.dm
:cl:
fix: shields won't go invisible anymore.
/:cl:
> Fix shield typo causing shields to go invisible

- .gitignore
- .vscode/settings.json
VSC had a version change and automaticly is changing settings, so this update it and gitignore it so we don't have anymore issues
> Git ignore vsc settings + update it

- tgui/packages/tgui/interfaces/Changelog.js
Pass the UTC true arg to the dateformat lib so it does not adjust for timezone (has the effect of putting the last or first day in the wrong month).
Correct dates.
:cl:
fix: Fixed the tgui changelog dates being inaccurate to the source files.
/:cl:
> Fix tgui changelog dates

- .github/PULL_REQUEST_TEMPLATE.md
- tgui/packages/tgui/interfaces/Changelog.js
- tools/WebhookProcessor/github_webhook_processor.php
- tools/ss13_genchangelog.py
ports: https://github.com/tgstation/tgstation/pull/59152
> Adds content expansion PR Type

- code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
let's you combo at mature rather than at ancient
makes ravager better at lower tiers
:cl:
balance: makes eviscerating charge cost 100 less plasma
/:cl:
> eviscerating charge costs 500 plasma, rather than 600

- code/__DEFINES/objects.dm
- code/game/atoms.dm
- code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
- code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
- code/modules/power/lighting.dm
Fix Nightfall
Fix Queen not being able to give plasma to King
:cl:
fix: Nightfall now applies on all electrical lights like it should
fix: You can give plasma as a queen to king
/:cl:
> Fix nightfall

- code/modules/admin/topic.dm
Sets the new new_player mobs name to the old mobs key before transferring it away.
Fixes: #6951
:cl:
fix: Fixed send to lobby breaking the ghost orbit panel.
/:cl:
> Fix send to lobby breaking the ghost orbit panel

- code/modules/client/client_procs.dm
title
This should not be lower than the servers version if we are not planning to downgrade right?
:cl:
code: Update the max recommended byond  client version.
/:cl:
> Update max recommended byond client version

- code/game/objects/items/radio/encryptionkey.dm
Title
Engineers are often begging to have mats on general or engie channel, it's cleaner com for everyone if they have req channel
:cl:
qol: Give engineers req channel
/:cl:
> Give engineers req channel

- code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
... until caste_flags are inevitably reworked later.
Less defunct flags and all the useful ones a kong needs.
:cl:
fix: Fixed King caste_flags, so it can now be healed by and become a leader for the Queen.
/:cl:
> Fix King caste_flags once and for all

- code/game/data_huds.dm
- code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
- code/modules/mob/living/carbon/xenomorph/xenomorph.dm
add ratio to pain hud. Stamina and pain count less, so the perception of human health by xeno will be more accurate
The current pain hud is outdated, pain and stamina are no longer that important
:cl:
balance: Update pain hud (what xeno see on humans) to be more reliable. Pain and stamina have way less impact on it.
/:cl:
> Update pain hud

- .github/CONTRIBUTING.md
Adds some new contributing guidelines from TGstation, most of them we already enforce, just makes this explicit and known to new coders.
> Adds New contributing guidelines from TGstation.

- code/game/objects/structures/xeno.dm
Doors will instantly open when you try to cross them as a xeno, and not as soon as you get closer.
Much better perf, less silly than previous system,  allow to wait in ambush behind the door
:cl:
balance: Resin doors open when you try to cross them as a xeno, and no longer when you are near them. Still instantanious
/:cl:
> Resin doors refactor

- code/controllers/subsystem/job.dm
If there are silos, late join xenos will spawn in silos, and not in random locations
Prevent funny spawn kills
:cl:
qol: If there are silos, late join xenos will spawn in silos, and not in random locations
/:cl:
> Late join xenos spawn in silos

- code/game/objects/items/weapons/shields.dm
shield appreantly had 100 bio armor, reduced to 50, so you get 50 bio armor with just a shield which is still pretty high
shield no longer gives you as much bomb protection to prevent stacking to become immune to grenades
grenade immunity bad
bio immunity very very bad
:cl:
balance: shield has less bomb armor, and no longer has bio armor immunity, only 50%.
/:cl:
> shield has less bomb armor, and no longer gives you immunity to bio, only half bio armor

- code/__DEFINES/dcs/signals.dm
- code/datums/actions/xeno_action.dm
- code/datums/keybinding/xeno.dm
- code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Title
More convenient
:cl:
qol: Switching hugger now has 2 keybinds, one gives a radial menu to choose the hugger and the other switches in old fashioned way.
/:cl:
> Switching hugger uses radial + keybind for it

- code/game/objects/machinery/overwatch.dm
Title
:cl:
fix: Rebel can access their overwatch
/:cl:
> Fix rebel access to Overwatch

- .vscode/launch.json
You can chose how you will launch your test servs in VSC. Seeker is default
> Give launch options between seeker and daemon

- .vscode/settings.json
- code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
Halve most of spit delay of spitter. Keep in mind the ammo itself add 0.5 seconds of delay, so at ancient a spitter has a delay of 1 seconds (1.3 when young)
Spitter is the worste caste in the game (maybe with hunter), and you are much better off with a sentinel with it's neat neuro spit and neuro sting.
This gives more dps to spitter, but doesn't make it too powerfull as plasma is a big limiting factor
:cl:
balance: Spitter can spit more often
/:cl:
> Spitter spit buff

- _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
- _maps/map_files/Sulaco/Sulaco.dmm
- _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
- code/game/objects/structures/reagent_dispensers.dm
removes milk dispenser
bad meme
:cl:
del:milk container
/:cl:
> removes milk dispenser

- code/modules/projectiles/ammo_datums.dm
The non-awaited sequel to #7104 and #7013 where I actually remove shake as was previously taken for granted except that arg specifically does not default to 0 and is at the end of the autodoc info.
Make it true:
:cl:
fix: Fixed "standard revolver bullet" still having shake.
/:cl:
> Fix my ammo datum changes for real this time
