tgstation/TerraGov-Marine-Corps

code/__DEFINES/conflict.dm, code/__DEFINES/mobs.dm, code/game/objects/effects/effect_system/smoke.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/carbon_defense.dm, code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/living_health_procs.dm, code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/flamer.dm, code/modules/reagents/reagents/toxin.dm
Neurospit reworked to output much lower Stamina damage, transfer neurotoxin chems to the target (subject to bio armor) and create weak, translucent neurotoxin gas.
Boiler neurotoxin gas now extinguishes fire and burning mobs.
Losing all Stamina now no longer causes an 8 second stun; instead it imposes a 1 second stun and ~11 seconds of slow and stagger that recurs up to once per 10 seconds while Stamina is still depleted. This allows people with fully depleted Stamina to still act.
Stamina damage dealt to a target that has maxed Stamina damage now deals an equal amount of oxy damage instead.
Neurotoxin no longer overdoses. While a victim with maxed Stamina damage would take Stamina damage from neuro, it instead takes half this amount as oxy damage and half as toxin damage, while causing …
=> Neurospit Tweak: Stamina Damage Nerfed, Weak Neurogas Spawn and Neurotoxin Reagent Transfer Added

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
This PR modifies the entry points of LZ1 and LZ2.
Compare and contrast pictures with the [webmap](https://affectedarc07.github.io/SS13WebMap/TGMC/PrisonStation/)
As have been mentioned by people on the discord ~~(and kindadread who owes me a crash token after this)~~ the siege of prison stations LZ's at the moment is complete torture as you can only really siege the entrance as neither crushers nor boilers can effectively make use of their main abilities on any spots which isn't the front entrance, this plus the additional fact that any other breaching points other than the entrance are extreme choke holds which makes it practically impossible to make good use of them.
This PR will alleviate these issues via expanding the breaching points as to make xenos have more breathing room and make …
=> Prison Station LZ 1 & 2 adjustments

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/Sulaco.dmm, code/game/objects/effects/overlays.dm, code/game/objects/structures/dropship_ammo.dm, code/game/objects/structures/dropship_equipment.dm, code/game/objects/structures/orbital_cannon.dm
1) Removes the random inaccuracy from all CAS munitions that had it
2) Makes CAS munitions travel time affected by orbit
3) Makes High velocity ammo the same as 30mm but with slightly less travel time
4) Slightly increases the cost of GAU ammo cost
5) Dramatically reduces the amount of free ammo/weapons CAS starts with:
CAS starts with 1 banshee, 1 widowmaker, 2 boxes of 30mm, 2 HE rocket stacks, 1 GAU, 1 mini rocket, 1 rocket pod on both the Sulaco and the POS. 
6) Replaces the useless medevac with an operating table for the alamo
7) Slightly buffs mini rocket and fatty fly time (7 to 6 seconds at base orbit)
8) Moves the dropship printer closer to the condor on the sulaco
9) The blinking green dot of CAS stays up for the entire duration a CAS projectile is coming in.
10) Makes railgun …
=> CAS Balance Tweaks

code/modules/projectiles/guns/revolvers.dm
0.15 from 0.00000003
revolver broken, this make more balanced
:cl:
balance: revolver has a 0.15 fire delay from 0.0000003, mateba has a higher aim mode delay
/:cl:
=> revolver has a real fire speed now, mateba has higher aim mode delay

code/datums/gamemodes/distress.dm
Removes survivor job from being picked.
Survivors exploit xenos being afk while waiting for the round to start or young xenos overextending far from weeds, thinking survivors are worse than marines, to kill them in a semi-RNG fashion.
:cl:
del: removed survivor from pickable jobs
/:cl:
=> Removes Survivor from the pickable jobs in Distress

code/_globalvars/admin.dm
This changes marine respawn time from 30 minutes to 45 minutes, simple as.
Marine respawns were made 30 minutes after the addition of headbite, and aim mode has made marine even stronger since then.  Xenos seem to have an issue with killing marines fast enough to reduce their numbers effectively before marines respawn or get new latejoins, especially on highpop
EDIT:I am a monkey and fucked up the changelog
🆑 
balance: marines now take 45 minutes to respawn instead of 30
/🆑
=> Changes Marine Respawn Time

code/__DEFINES/mobs.dm, code/game/data_huds.dm, code/game/objects/items/bodybag.dm, code/game/objects/items/defibrillator.dm, code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/living/carbon/human/human_defines.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/living_health_procs.dm
Putting a human body in a cryobag will prevent its brain to decay
Since headbiting is on its way out, corps are often overwhelmed with dead bodies. This will make triage easier
:cl:
balance: Cryobags prevents the DNR timer to tick 
/:cl:
=> Cryobags freeze the DNR timer

code/datums/jobs/job/shipside.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/species.dm
Fixes synth paygrade (Mk. I, II, III) not showing. Always shows paygrade. Showing the paygrade was disabled in generic species class and only enabled in some, **not** including synthetics. But even if that variable was false the default paygrade was still shown. Because it wasn't used anywhere else I've deleted it to default to always show the paygrade.
Other fix would be to add `show_paygrade = TRUE` to synthetic species, but as explained I think it's better to remove that variable.
Fixes #6051 
Bug fix and code simplification.
:cl:
fix: synthetics' paygrade now displays properly
code: remove /datum/species/show_paygrade
/:cl:
=> Synth job time fix

code/game/objects/machinery/vending/new_marine_vendors.dm
Shoves the open-faced Infantry armor helmet into its own set rather than separate them.
Like EVA and EVA-skull helmets before them, so that you can still use the helm attachies.
:cl:
tweak: Shoves the open-faced Infantry armor helmet into its own set, removed the open-faced helmet as an option to pick in the vendor menu.
/:cl:
=> Puts Infantry Open-Helm to Infantry Armor Set in Vendor

code/_onclick/item_attack.dm, code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/living/carbon/xenomorph/attack_alien.dm, code/modules/mob/living/carbon/xenomorph/xenoattacks.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/mob/mob_movement.dm
Removes melee_accuracy mob var from code. Code-wise xenos have effects for when they fail the melee accuracy check, but it is always at 100%. For marines, it is only changed to 80% when they run and doesn't present engaging choices to make regarding it.
Marines don't have a 20% chance to fail a melee attack because they toggled the run intent, which makes melee consistent and removes unclear interactions.
:cl:
del: Removed 20% chance to miss melee attack when running
/:cl:
=> Removes melee_accuracy mob var

code/controllers/subsystem/evacuation.dm
:cl:
fix: Shipside self-destruct animation has been fixed.
/:cl:
=> Shipside SD fixes

code/datums/gamemodes/game_mode.dm, code/game/objects/effects/decals/contraband.dm, code/game/objects/items/cards_ids.dm, code/game/objects/items/cosmetics.dm, code/game/objects/machinery/cryopod.dm, code/game/objects/structures/ladders.dm, code/game/verbs/suicide.dm, code/modules/admin/fun_verbs.dm, code/modules/assembly/holder.dm, code/modules/detectivework/scanning_console.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/give.dm, code/modules/mob/living/silicon/ai/ai_verbs.dm
Fixes some TGUI alert/input_list calls that had incorrect number of arguments. Adds some spaces after commas where they were missing.
Fixes:
- monkeys can now suicide (the prompt shows now), tested
- can pick xenos as ghost (fixes #6076), tested
- putting someone in cryo while they're not SSD prompts them to confirm, **not** tested, requires at least two people
- AI can change display status (fixes #6101), tested
Fixes.
:cl:
fix: taking over SSD xenos works again
fix: monkeys can suicide again
fix: prompt when someone tries to cryo you works again
fix: AI can change display status again
/:cl:
=> TGUI call fixes

code/modules/projectiles/gun_helpers.dm
Weapon toggles (field strip, toggle fire mode, eject mag etc) were implemented as verbs for `/obj/item/weapon/gun`, which leads to issues when you have more than one gun equipped (see #6049). I've added similar verbs for `/mob/living/carbon/human` which pick the active firearm (the one in your current hand or if it's empty in the other hand). This doesn't affect gun in inventory slot, because you wouldn't be able to do anything with it because of later checks, while the old verbs allow you to select it. I've left the verbs for guns so they are still in right click menu. I had to add "(Weapon)" because otherwise both usage tips show in Weapons category tab. I've also simplified the code a bit.
Fixes #6049
The game no longer asks you to choose which weapon to toggle when you have one in …
=> Weapon toggles QoL changes

code/_onclick/item_attack.dm
PB shots and melee were missing 100% of the time
:cl:
fix: Melee and PB shots don't miss
/:cl:
=> Fix PB shot missing

code/modules/xenomorph/xeno_structures.dm
Fix https://github.com/tgstation/TerraGov-Marine-Corps/issues/6131
:cl:
fix: Making a new silo will now correctly reset the siloless timer
/:cl:
=> Fix silo timer not being reset

code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
`smoke_contact` for xenos wan't updated to check for the new trait.
Bug fix.
:cl:
fix: boiler neurotoxin properly extinguishes xenos
/:cl:
=> Fix boiler gas not extinguishing xenos 

code/game/objects/effects/acid_hole.dm
Adds synth check to throwing grenade in acid hole. Fixes #6126.
Bug fix.
:cl:
fix: synthetic cannot throw dangerous grenades in acid holes now
/:cl:
=> Add synth check to throwing grenade in acid hole

code/game/objects/machinery.dm, code/game/objects/machinery/computer/computer.dm, code/game/objects/machinery/vending/vending.dm
Allows tipped vendors to be put back up. Makes disabled machinery unusable for AI and humans. Fixes #6127.
The tipped vendors are now powered, which allows interacting with them. Interaction will either be tgui (dispensing) if the vendor isn't tipped or putting it back up if it is.
Fixes. Allows fixing vendors. Disallows AI from using broken things.
:cl:
fix: disabled computers are now unusable (repair with blowtorch)
fix: tipped over vendors can be put back up
fix: AI can't use disabled machines now
/:cl:
=> Vending and computer repair fixes

code/game/objects/items/defibrillator.dm
Adds a hint to defibrillator on examine and when the battery runs out. Meant to inform people that they can recharge defibrillators with corpsman backpack.
Fixes #6119. 
Informs about game mechanics. Increases the chance of revival.
:cl:
qol: defibrillator recharging hints
/:cl:
=> Add defibrillator recharge hint

code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm, code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
Ancient Xenos now provide the proper upgrade point yield when targeted with Salvage Biomass.
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/6150
:cl:
fix: Ancient Xenos now provide the proper upgrade point yield when targeted with Salvage Biomass, counting as a maxed out Elder Xeno.
/:cl:
=> Ancient Xenos Now Provide Proper Salvage Biomass Upgrade Yields

code/game/objects/structures/stool_bed_chair_nest/bed.dm
Fixes:
[18:27:57] Runtime in unsorted.dm, line 39: unbuckle overridden. Use override = TRUE to suppress this warning
proc name: stack trace (/datum/proc/stack_trace)
usr: Fernandos33/(Case Husk)
usr.loc: (Tadpole Drop Shuttle (150, 83, 3))
src: the medevac stretcher (/obj/structure/bed/medevac_stretcher)
src.loc: the floor (151,82,3) (/turf/open/shuttle/dropship/floor)
call stack:
the medevac stretcher (/obj/structure/bed/medevac_stretcher): stack trace("unbuckle overridden. Use overr...")
the medevac stretcher (/obj/structure/bed/medevac_stretcher): RegisterSignal(the medevac stretcher (/obj/structure/bed/medevac_stretcher), "unbuckle", /obj/structure/bed/medevac_str... (/obj/structure/bed/medevac_stretcher/proc/on_mob_unbuckle), 0)
the medevac stretcher …
=> Fixes medevac stretcher runtime

code/modules/vehicles/powerloader.dm
Added DELONDROP to powerloader clamps so you can't give them. They aren't actually deleted, but moved into powerloader object storage. It's a bit hacky, but allows exiting by pressing Q. Refactors the code a bit. Fixes #6044.
Alternative fix would be to make them NODROP and only allow to exit ripley by unbuckling, but I think it's worse, because Q won't longer work.
Game exploit fix.
:cl:
fix: you can no longer give marines ripley hands to move crates fast
/:cl:
=> Fix giving powerloader clamps

code/modules/projectiles/gun_helpers.dm
Fixes #6153. The default tab for verbs is actually Commands. Or rather [default_verb_category client var](http://www.byond.com/docs/ref/info.html#/client/var/default_verb_category). This removes that tab, so the old weapon verbs are available only in right-click menu. The better mob verbs are in Weapons tab.
Bug fix.
:cl:
fix: weapon verbs are now only in Weapons verb tab
/:cl:
=> Remove (Weapon) verbs from Commands tab

_maps/map_files/Sulaco/Sulaco.dmm
Moves one of the alamo crash spots that was opening up the side of the ship to space, It's a few tiles further up and right now.
space bad
:cl:
fix: Alamo crash can no longer create a hole a space to on the sulaco
/:cl:
=> Fix dropship crash opening space

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
adds a eastern lavaland area to that one tile with an X in the middle
Instant death tiles in a playable area is not a good idea
:cl: Vondiech
fix: A rouny made of space dust has fixed so that an instant death tile on magmoor is no more.
/:cl:
=> Instant death tile on magmoor removed

_maps/map_files/Sulaco/Sulaco.dmm
Fixes the walls being fucked up near the vendor and while I was at it I made the vendors a little further back so you can stand in front of them without blocking anyone going through the hallway
bug bad
Not standing in the hall is just nice little QoL if a lot of people are walking by
:cl:
fix: Filled in a missing wall on the sulaco, made a light fixture not float.
qol: There is a little more space to stand in front of the public engi vendors on sulaco without taking up space in the hallway.
/:cl:
=> Misc Sulaco map fix + public engi vendor QoL

code/__DEFINES/mobs.dm, code/modules/xenomorph/xeno_structures.dm
Silo proximity alert will now work. They now detect hostiles with a range of 10 instead of 2
Will give xenos hives early warning to give them time to come defend pool
:cl:
fix: xenos silo proximity alerts now work
balance: range of proximity alerts is now 10 instead of just 2
/:cl:
=> Silo proximity alert fix, balance

code/modules/projectiles/gun_system.dm
You can shoot while wielding. You still can't start shooting while activating aim mode.
Fixes an unintended mechanic change to wielding.
:cl:
fix: you can start shooting while wielding again
/:cl:
=> You can start shooting while wielding again

code/game/objects/items/weapons/twohanded.dm, code/modules/clothing/suits/marine_armor.dm, code/modules/modular_armor/modular.dm
Updates various two handed weapons to be more on par with the modern machete and allows them fit in more clothing slots.
Increases the damage on all two handed weapons but the damaged glaive.
Fireaxe wielded dmg: 45 -> 75
Dual esword wielded dmg: 70 -> 150 (This is an admeme only weapon)
Spear unwielded dmg: 14 -> 25
Spear wielded dmg: 24 -> 40
Spear throwing dmg: 30 -> 75
Glaive wielded dmg: 60 -> 90 (I kept the original +15 damage that this had when compared to the fireaxe)
Glaive throwing dmg: 50 -> 65
All two handed weapons are now able to be stored on the armor storage slot.
Axes are now able to be stored on the belt slot, not just the backpack slot.
For reference, the machete does 60 dmg and the knife does 25 dmg, both of these are one handed and considered balanced.
Note: This is …
=> Two Handed Update

code/__DEFINES/monitor.dm, code/modules/mob/new_player/new_player.dm
Inbalance join popup will now show up when burrowed larva account for 20% of the xenos alive, and the shutters are still shut or xenos are losing 
Former system didn't work well before shutters
:cl:
qol: better unbalanced join detector
/:cl:
=> Balance join update

code/game/objects/machinery/smartgun_mount.dm
Adds a line to the TL-102 description informing readers that it can be repaired with a blowtorch.
The TL-102 can be repaired. No one knows this however, a description telling people this would be useful.
:cl:
add: The TL-102 can be repaired with a blowtorch, adds that information to its description.
/:cl:
=> Adds description to TL-102 telling how to repair it.

code/modules/projectiles/guns/flamer.dm
Boiler neurogas now properly extinguishes areas of fire within it.
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/6205
:cl:
fix: Boiler neurogas now properly extinguishes areas of fire within it.
/:cl:
=> Boiler Neurogas Now Extinguishes Fire Properly

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Title
Before psydrain, losing all your silos would mean xenos would have lose, and the timer was just here to prevent useless delay from a running shrike.
Now, even if xenos don't have a lot of points when that happen, they still got a chance to get another one if they manage to slaughter a whole bunch of marine and psydrain them.
This also makes losing silos less of a punition that it needs to be
:cl:
balance: Siloless collapse are now 20 minutes instead of 10
/:cl:
=> Siloless collapse takes 20 minutes instead of 10

code/controllers/subsystem/silo.dm
Nerf base pool output from .65 to.4
Marines are getting steamrolled. I don't think it's the right solution, but we need a bandaid before balance freeze so this will do
:cl:
balance: Silo output reduced
/:cl:
=> Silo base spawn rate nerf

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Title
:cl:
fix: Xenos can see how much time before the hive collapse due to no silos
/:cl:
=> Xenos can correctly see the siloless collapse timer

code/game/objects/machinery/miner.dm
Miner overclock upgrade reduces crate production time from 140 seconds to 120 instead of 140 to 70
This upgrade power creeped the shit out of miners and is overpowered, it needs to be toned back significantly.
:cl:
balance: Miner overclock upgrade is less effective
/:cl:
=> Nerfs Miner Overclock Upgrade

code/modules/projectiles/projectile.dm
Gives the TL-102 HSG the ability to have IFF bullets pass over it the same way it does with Sentries.
From my experience I've found that the main reason the TL-102 dies is because it gets FFd in five seconds. I figure since its function is similar to a Sentry it shouldn't be able to be killed by FF.
:cl:
balance:  Gives the TL-102 HSG the ability to have IFF bullets pass over it the same way it does with Sentries.
/:cl:
=> Allows IFF Bullets to pass over the TL-102 HSG

code/game/data_huds.dm, code/game/objects/machinery/smartgun_mount.dm
Gives the TL-102 HSG a health and ammo indicator like the Sentries have.
Gives some visual feedback for ammo and health of the TL-102
:cl:
add: Gives the TL-102 HSG a health and ammo indicator like the Sentries have.
/:cl:
=> Gives the 102 a hud like the sentries

code/game/objects/items/reagent_containers/autoinjectors.dm, code/game/objects/items/reagent_containers/glass/bottle.dm, code/game/objects/items/reagent_containers/pill.dm, code/game/objects/items/scanners.dm, code/modules/reagents/reactions/medical.dm, code/modules/reagents/reagents/medical.dm
this mainly affects neurotoxin and larval accel
it makes no sense that the purging chemical is purged by common battlefield afflictions making it annoying to heal people ut of toxin damage, and having it as a medicine child makes no sense from a game design standpoint in my opinion
:cl:
balance: hypervene isn't purged by chems that purge any medicine like neuro/larval.
/:cl:
=> hypervene no longer is purged by /medicine purges

code/modules/projectiles/gun_system.dm, code/modules/projectiles/guns/energy.dm
As per title. Ported from CM, that isn't crapcode.
To know you are running out of ammo in the heat of battle.
:cl:
qol: Ballistic weapons have a rattling sound when fired at 25% ammo left.
/:cl:
=> Guns Rattle When Low Ammo

code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/magazines/rifles.dm
1. Changed the type 71 burst from 2 rounds to 3
2. upped the ammo count from 40 to 42 to remain evenly dividable
I felt that that the type 71 only having a burst fire of 2 rounds wasn't very strong although unique, with it set to 3 it will be a little less useless
:cl:
balance: Burst fire 2 -> 3
balance: Magazine size 40 -> 42
/:cl:
=> Changes type 71 to 3 burst

code/controllers/subsystem/job.dm, code/controllers/subsystem/silo.dm, code/datums/gamemodes/distress.dm, code/datums/jobs/job/job.dm
Xenos will get larva (same as before pools) and psych points (1/15 of a silo) everytime a marine spawn for the first time. Respawn will not give anything
This deals with the issue of people joining up late, and only chosing marine making the game unbalance for xenos. This system is more fair for xenos, while still retaining the current philosophy of "no free larva for marine respawn"
:cl:
balance: Xenos gain larva and psych points everytime a marine spawn , even for very late joins. Doesn't work for respawn
/:cl:
=> Psych balance tweak

code/game/objects/machinery/miner.dm
Miners store up to 8 crates of ore before they need to be emptied instead of 2
Right now someone basically has to be at a running miner 24/7 even if xenos aren't pressuring the miner at all because you have to sell crates once every 5 minutes. This PR makes you need to sell less often and thus a miner which isn't actively being attacked by xenos doesn't need 24/7 support from some poor marine who got stuck with crate duty.
:cl:
qol: Miners don't need to be emptied as often
/:cl:
=> Miner Holds More

code/modules/mob/new_player/new_player.dm
Unbalance join detector will not pop anymore when all xenos are dead and no larva, or when the round is ERP
:cl:
fix: No more unbalance join message when all xenos are dead
/:cl:
=> Unbalance message fix

code/_globalvars/admin.dm
Ttile
Don't know if people will like it, but I think the marines push mid round are a bit sad. This will maybe allow marines to make a second push mid round that's more dangerous than the one they are currently doing
Give feedback
:cl:
balance: Respawn for marines are now 30 minutes instead of 45
/:cl:
=> Marine respawn from 45 minutes to 30 minutes

code/game/objects/items/defibrillator.dm, code/modules/mob/living/carbon/xenomorph/embryo.dm
Chest bursting now inflicts lethal brute damage, and organ damage, rib fractures and internal bleeding from which the victim can be revived.
Removes a source of perma death from the game, enabling bursted players to get back into the fight; makes getting treated for larva less absolutely critical.
:cl:
balance: Chestburst victims are now revivable, albeit with internal bleeding, rib fractures and organ damage.
/:cl:
=> Chestburst Is No Longer Permadeath

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/Sulaco.dmm, code/__DEFINES/objects.dm, code/modules/mining/remote_fob/remote_fob_actions_misc.dm, code/modules/mining/remote_fob/remote_fob_computer.dm
Remove the check making AI unable to use fob drone. The fob drone starts with already full mats, and has no longer any limits in mats. Mats are auto ejected when alamo leaves
QOL additions
:cl:
balance: AI can use fob drone
qol: Fob drone is prefilled with mats, and you can put as many mats in it as you want
qol: Mats are automaticly ejected when alamo leaves
/:cl:
=> AI can use fob drone, no more mats limit for it

code/controllers/subsystem/points.dm, code/controllers/subsystem/silo.dm, code/modules/power/groundmap_geothermal.dm
A corrupted gen output of psych points will now scale with the server populatiob, AKA the number of client online. 
The base server pop for calculation is 50, so if there are 50 players the output will be of 0.03 psych per second per gens ( a third of currently) 
Trying to make high pop and low pop have the same balance. Also, since psy drain is pretty strong, that passive outcome is no longer that needed
:cl:
balance: Corrupted generators output scale with the players count. Also big nerf compared to previous output
/:cl:
=> Gens psych points outpute scale with server pop

code/__DEFINES/mobs.dm, code/_onclick/hud/screen_objects/screen_objects.dm, code/game/objects/effects/temporary_visuals/temporary_visual.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/mob/living/carbon/xenomorph/damage_procs.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/xenomorph/xeno_structures.dm
1. Xeno hive health alert % decreased from 33% to 25%
2. Preference settings made more intuitive; previously the wording was misleading.
3. Xeno hive alerts can now visibly ping non-turf targets
4. Various minor other improvements
Improves the functionality of Xeno Health alerts and Xeno Hive alerts in general.
:cl:
code: Xeno hive alert code improved; can now visibly ping non-turf targets.
tweak: Xeno health alert preferences made more intuitive.
/:cl:
=> Xeno Health Alert Improvements

code/controllers/subsystem/points.dm, code/game/objects/structures/dropship_ammo.dm, code/game/objects/structures/dropship_equipment.dm
Standard Rocket fly time reduced to 4 seconds (from 6): affects all rockets except widowmaker and mini rocket
Widowmaker price reduced to 75 (from 175) and fly time reduced to 3 (from 4)
Banshee cost reduced to 150 (from 175)
Napalm cost reduced to 200 (from 350)
Fatty cost reduced to 200 (from 300)
Minirocket fly time reduced to 4 seconds and flash range reduced
Orbit level now impacts fly time and point generation half as much (+-16.6% per orbit level above or below standard)
Keepers didn't get a price reduction because they're the only rocket I believe was deadly enough to warrant it's crazy high price, the reduced fly time is good enough for it.
Most good POs use only laser/GAU because rockets just aren't good. They're very expensive and not faster than the GAU. The GAU costs 7.5 …
=> CAS Balance Pass (orbit effect reduction, rocket buff)

code/modules/projectiles/guns/shotguns.dm
Groundside double barrel doesn't have burst fire anymore.
Burst shotguns are bad balance,one shot memes begone.
:cl:
balance:groundside double barrel doesn't have burst anymore
/:cl:
=> Burst shotgun begone

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, code/game/objects/machinery/door_control.dm, code/game/objects/machinery/doors/shutters.dm
You can now control the shutters for the engi armory more easily.
It makes things tidier and actually work.
:cl:
fix: Fixes a missing button for the armory shutters on PoS engineering.
/:cl:
=> Actually make it so the engineering shutters have their own buttons.

code/game/objects/effects/temporary_visuals/temporary_visual.dm
/obj/effect/temp_visual/xenomorph/xeno_tracker_target
Failures: 1246
qdel() Count: 1341
Destroy() Cost: 90ms
Total Hard Deletes 795
Time Spent Hard Deleting: 67615ms
:cl:
fix: fixed bad code causing lag
/:cl:
=> Fix a cause of screen hard dels

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/rifles.dm
GPMG now fires faster and LMG has more attachies to use.
Fire rate only works in incrementals of 0.05 which means guns like the GPMG (0.165 rof) and LMG (0.180 rof) actually end up with a rof of 0.2 which is the same as the assault rifle,meaning that they are much weaker than what they were supposed to be,I'm compensating that by making the GPMG have 0.15 firerate (same as p90) and increasing the damage falloff to make up for the extra 0.015 rof, and making the LMG have more attachies,it's not perfect but IDK if that problem will ever be fixed so letting these guns have worse performance than they should in the meantime doesn't sit well with me.
:cl:
balance:Buffed GPMG fire rate and increased damage fall off.
balance:LMG now can use agrip/underbarrel flamer/greande launcher/masterkey. …
=> ROF Compensation Buffs to the GPMG and LMG

code/modules/reqs/supplypacks.dm
reduces point defense price to 40 and its ammo to 5, and reduces UAC cost to 100
sentries are too overpriced for a very weak thing that does 10/20 damage for 60/120 points, this alleviates it a bit and gives marines more ways to hold a forward location more safely,
:cl:
balance: sentry prices reduced.
balance: point defense sentry ammo price reduced.
/:cl:
=> Reduce sentry costs

code/modules/projectiles/gun_helpers.dm
When affected by an aim order (any tier) you enter aim mode instantly instead of having a 1 second wait
Makes aim order slightly less useless
:cl:
balance: focus orders let you enter aim mode instantly
/:cl:
I wanted to make it partially negate fire rate reduction based on tier but I couldn't figure out how to do that without it needing you to enable and re enable aim mode for the fire rate changes to trigger
=> Small Aim Order Buff

code/__DEFINES/mode.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/xenomorph/xeno_structures.dm
All turrets are destroyed on hijack. A free turret on top of the free super silo is given when hijacking
The psych points are reset when the alamo hijack. This is done so groundside and shipside are two clearly separated game moment, and a bit easier to balance (yeah i know, balancing shipside...) Piling in on 100 turrets in alamo makes it impossible for marines to ever breach it, on top of the super pool being busted
:cl:
balance: Xeno turrets are destroyed on hijacking
/:cl:
=> Turrets are destroyed on hijack

code/modules/projectiles/gun_attachables.dm
Agrip adds 5 scatter to your gun
Funny agrip man reduces wield timers and the downside is more scatter for... unwielded guns? that's not even a real negative, now it adds a bit of scatter to the gun.
:cl:
balance: Agrip now adds 5 scatter to the gun when attached.
/:cl:
=> Agrip now has an actual negative

code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/projectiles/ammo_datums.dm
Acid spit of xeno turrets no longer ignore xenos. Doesn't do any damage to them though
Should reduce the whole shuffle cheese around turrets by xenos, probably won't make it impossible but that'll help a bit
:cl:
balance: Xeno turrets no longer have IFF spit.
/:cl:
=> Xeno turrets lose IFF

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Fixes the shared cooldown for Grapple Toss and Fling so it works properly.
Fixes the shared cooldown for Grapple Toss and Fling so it works properly.
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/6266
:cl:
fix: Shared cooldown for Grapple Toss and Fling fixed so that using one doesn't cause the other to have an indefinite cooldown.
/:cl:
=> Cooldown Fix for Fling and Grapple Toss

code/modules/xenomorph/xeno_structures.dm
Creating a pool will create a tunnel north of it, if the tile is empty
Makes xenos able to quickly defend pool even if their is no hivelord in their rank. Maybe will allow xenos to spread the pools, which can be a good counter to big unga balls since losing one pool is not the end of the world
:cl:
add: Spawning a new silo will generate a tunnel north of it automaticly 
/:cl:
=> Making a pool create a tunnel next to it

_maps/map_files/Sulaco/Sulaco.dmm
The sulaco, unlike pillars of spring lacked fire alarms. 
Not even one.
I know it is an older model but it really should have some, at least in engineering. This PR fixes that.
Old ship can now pass some better safety standards. 
:cl:
fix: Fixed the complete absence of fire alarms on the sulaco
/:cl:
=> Add some fire alarms to the sulaco. Along with ONE camera because i can't be bothered to make another PR just for that one.

code/modules/projectiles/guns/rifles.dm
Makes general-purpose machine gun shoot slower with aim mode on.
Currently, marines can just spam GPMGs with little to no penalties, as it has a superior fire rate with AND without aim mode.
:cl:
balance: General-purpose machine gun shoots a bit slower with aim mode on.
/:cl:
=> Nerfs GPMG's aim mode rate of fire.

code/__DEFINES/mode.dm
Turrets go from 100 to 150 psych points
To account for cocooning which gives a lot of points. And xenos should not be able to make 100 turrets in cave at random spot like right now
:cl:
balance: Xeno turrets are now 150 psy points
/:cl:
=> Xeno turrets more expensive

code/game/objects/items/misc.dm
This thing is obsolete and unused, I removed it with my miner PR but I think it got reverted by someone fixing a merge conflict
:cl:
code: got rid of unused/obsolete compactor upgrade
/:cl:
=> Delete Obsolete Compactor Upgrade

code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm, code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm, code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm, code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm, code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm, code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm, code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm, code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm, code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm, code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm, code/modules/mob/living/carbon/xenomorph/evolution.dm, code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
When evolving to a higher class, you'll keep the upgrade points you accumulated when aging.
As an exemple, an ancient drone evolving to a hivelord will keep 420 upgrade points, so it will emerge as an elder hivelord, and no longer a young one like previously. You can never get ancient when evolving, only lower upgrades because highier tiers ask for more upgrades points for each level
Regressing also keeps points
Also adjust the amount of points given when recycling a xeno body, because a typical xeno body will have way more upgrade points
Give more incentive to evolve to higher caste, as previously xenos were relunctant to give out their ancient T1/T2 if that meant having to stop playing for some minutes, while waiting to get mature again.
This remove a tedious part of playing xenos, that …
=> Xenos upgrade points are kept when evolving 

code/controllers/subsystem/silo.dm, code/modules/xenomorph/xeno_structures.dm
No more maturity. Base output is up to compensate a bit
Less urgency to win first push. Maturity was needed because xenos would lose against first marine respawn, this is less true if they manage to get a lot of cocoon.
:cl:
balance: silos no longer mature. base output is 0.5 instead of 0.4
/:cl:
=> Silo have the same output whole game

_maps/map_files/Sulaco/Sulaco.dmm
Cameras were pointing into the wall. Bad 
Realism. 60fps. What else.
:cl:
fix: Sulaco medical had cameras pointing the wrong way.
/:cl:
=> Oogga - Fix some cameras orientation on Sulaco

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Changed pools collapse timer from 20 minutes to 10 minutes.
Pools collapse doesn't happen before 13:00, which condition did not exist when the PR to increase the timer was thought of. Until 13:00 xenos have enough time to organize/protect themselves from early all-out pushes, which the timer was meant to counter. By having the timer be lower, there is less delay before the round ends when the xenos are decisively losing.
:cl:
balance: changed pools collapse timer from 20 minutes to 10 minutes
/:cl:
=> Changes pools timer from 20 to 10m

code/datums/gamemodes/distress.dm
Hivemind collapse shipside is now and supposed to be a Xeno minor victory.
Hivemind collapse shipside is now a Xeno minor victory.
Fixes funny win condition left out previously.
:cl:
fix: fixed win conditions.
/:cl:
=> Fixes hivemind collapse shipside win condition

code/game/objects/structures/orbital_cannon.dm
Warcrimb fire on incen ob
Used to be mainly for maze clearing but HE outclasses incine in lethality, and clearing due to the fact deva explosions flattens r-walls in the radius of the explosion.
This pr just makes it more lethal for xenos by giving it a burst of damage if a xeno was in the area while it landed.
:cl:
balance: Incendiary OB now drops a 17 tile WP smoke that lasts for half the duration of the OB (flame_duration 40, warcrime 20)
/:cl:
=> Puts WP smoke on Incendiary OB

code/datums/gamemodes/distress.dm
Changes win conditions regarding shipside.
Marines wiping out Xenos shipside is now a Marine minor victory.
Xenos get a super pool when boarding the ship and enough points to spawn a turret or two before boarding and after as well. This encourages marines to push and try to salvage the round whilst they still have the option to hold SD and attain a draw to deny the Xeno victory. Xenos still have the option to avoid getting destroyed by early evacs or marines hoarding req points to ensure wins by just capturing the alamo. Wiping out Xenos at the cost of the ship is a small victory but at a much greater cost.
If Xenos camp the FOB and force an early evac and still hijack:
https://github.com/tgstation/TerraGov-Marine-Corps/pull/5734#issuecomment-761137632
This also punishes Xenos for stealth …
=> Changes win conditions

_maps/map_files/Sulaco/Sulaco.dmm
Middle of the ship had a pointless space area that was creating instant kill zones on alamo crash in the area.
Just decided to get rid of the pointless space area and make synth's room a little more spacious in the process.
🆑
fix: fixed an instant kill zone caused by alamo crash on sulaco
qol: Synth's room is a little more spacious on sulaco.
/:cl:
=> Small Remap of Sulaco synth room to prevent instant kill zone on alamo crash

code/modules/mob/living/carbon/human/human.dm
this changes the code so medic training HELPS you to fireman carry. instead of making it worst for you
medics are fucking TRAINED to save marines. they are EXPECTED to pick people up and save them. if ANYONE in the corps will know how to get em back to safety it should be the corps and this PR. gives medic a BONUS in fireman carry instead of a MALUS like it was before
:cl:
balance: medics now fireman carry faster than marines do
/:cl:
=> buff medics fireman carry ((in the code. medics would take MORE time than marines))

code/modules/mob/living/carbon/carbon_defense.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/projectiles/ammo_datums.dm, code/modules/reagents/reagents/toxin.dm
makes neurotoxin spit only inject light neurotoxin which doens't purge med chems, same for the cloud.
neurotoxin spit injecting full neurotoxin which purges most medicine chems and also are injected in high quantity at range is very strong, so this makes it weaker, all the other neurotoxin uses are untouched
:cl:
balance: neurotoxin from neurospit doens't purge medicine anymore, all other neurotoxin sources remains same.
/:cl:
=> neurospit now injects non purging neurotoxin

code/__DEFINES/jobs.dm, code/datums/jobs/job/marines.dm, code/datums/jobs/job/shipside.dm
This is a revive of https://github.com/tgstation/TerraGov-Marine-Corps/pull/6333
"As we are constantly moving towards high pop, I believe synthetics getting more slot every 40 pop makes sense as generally there is a lack of command. Synthetics can do most shipside job, and as the pop increases, it generally gets difficult to manage shipside. Addition of a support role of Synthetic will ensure this.
I may change the pop number upon testing and feedback. This needs testing."
:cl:
balance: Gives 1 Synth job slot every 40 pop.
/:cl:
=> Adds 1 Synths job slot every 40 pop

code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm, code/modules/projectiles/ammo_datums.dm
Fixes bug with scatterspit projectiles going too far.
Max range increased to range 8.
Fixes bug with scatterspit projectiles going too far.
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/6387
:cl:
fix: Fixes bug with scatterspit projectiles going too far.
balance: Scatterspit max range increased to 8 tiles.
/:cl:
=> Fixed Bug With Scatterspit Projectiles Going Too Far

code/game/objects/machinery/vending/new_marine_vendors.dm
Adds a 15 point buyable to corpsmen vendors; the combat backpack. Balanced around the fact that you get 2 less meraderm hypos / case, and/or 1 less neuraline in return for greatly increased storage space.
With the constant addition of anti-chems (neuro, larvae injection being used more, neurotox clouds, ranged prae neuro) and the nerf to webbing (no surgical vest), corpsmen gaming is at an all time low. One of the issues is that storage is a huge issue; you have to carry extra hypervene (or ryt if your a gamer like fernando), dylovene (to deal with OD's of these xeno chems) and dexalin (same reason), alongside other specialized meds such as iron sugar. This means you basically have little to no room for ammo to be an actual corpsman; a healer and defender of your patients. This PR helps …
=> Corpsmen Storage QoL V2

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm, code/game/objects/machinery/doors/shutters.dm
simply adds the ID part to this
if any of the buttons on the place it landed has it's ID set to null then it would've triggered the transit shutters because the transit shutters were also null, **this is bad.**
~~kindadread owes me a crash token or two for this favor~~
:cl: Vondiech
fix: Transit shutters can no longer be triggered by any buttons on shipside or groundside that has its ID set to null
/:cl:
=> Transit shutters has had its ID changed

code/modules/mob/living/carbon/xenomorph/abilities.dm
Psy drain will now take 5 seconds instead of 10 seconds
With psy drain being the combat option over cocoon, it seems completly fair that it should take less time than its counterpart. This reinforce the idea for xenos that they should use it on the frontline, while cocoon should be reserved near backline 
:cl:
balance: Psy drain will now take 5 seconds instead of 10 seconds
/:cl:
=> Psy draining is quicker

code/modules/reqs/supplypacks.dm
Basically lowers the prices of all OB related materials ( Fuel blocks from 10 to 5, Incin, cluster to 20, HE lowered to 30, Plasma drain to 15)
I made the pr for buying OB's way before capture removal, where OB would be mostly used for exploding a nested marine or clear a maze, I kept it high because you're able to deny the xenos a lot of caps if they bunched them up. With pools you're not really gonna OB a pool unless xenos were dumb enough to place it in open roofs.
I kept HE at a high price due to it's buff of having all of their tiles do a devastation explosion.
:cl:
balance: Lowered the price of all OB related materials, ( Fuel blocks from 10 to 5, Incin & cluster to 20, HE lowered to 30, Plasma drain to 15)
/:cl:
=> Cuts fuel blocks price in half, Lowers most OB's by half

code/_onclick/ai.dm
Just lets you use that thing more swiftly. QoL
Qol again
:cl:
qol: Adds a shortcut for the AI to turn on & off fire alarms using shift & Ctrl click.
/:cl:
=> Adds a shortcut for the AI to turn on & off fire alarms using shift & Ctrl click.

code/game/objects/machinery/vending/marine_vending.dm
Moves ammo boxes from RO vendor to Big Ammo vendors. A QoL improvement so 30 ammo boxes aren't all sitting on one tile as most RO's just vend them all into a crate and off load it. Marines do not have to bother RO's for something this simple anymore (especially on rounds without a dedicated RO this is annoying).
QoL improvement for low and mid pop. Slight lag reduction (no longer are 30 + ammo boxes stacked on one tile) and anti-roomba (since ammo boxes spawn on the vendor and roomba can't move on vendor tiles). I no longer have to fucking spam left click 30 times every round im RO. On sulaco, there are 30 ammo boxes; on PoS, there are 45 (due to the PO vendors existence).
:cl:
qol: RO Ammo boxes moved to big ammo vendors.
/:cl:
=> QoL Ammo Box

_maps/map_files/Sulaco/Sulaco.dmm
Made changes to the Sulaco map, increased the amount of cameras available for the AI to look through. 100% ship visibility. I fixed all the cameras (that I found) directions to attach to the walls. Fixed a power cable not being connected to the CLs room, fixed the AI core interior doors being linked the the exterior door button, now they are independent. Added two maint doors behind the AI core.
Gives the AI enhanced shipside intelligence and interfacing capability. The CLs office now recharges properly without requesting an engineer to fix it. Gives engineering their own autolathe now. Hardens the AI core making it more defensible.
:cl:
qol: Fixed AI interior shutters being tied to exterior button (First thing I ever fixed never mentioned it)
qol: More cameras around the ship
qol: fixed …
=> QOL Sulaco tweaks and fixes.

code/modules/vehicles/unmanned/unmanned_droid.dm, code/modules/vehicles/unmanned/unmanned_vehicle.dm, code/modules/vehicles/unmanned/unmanned_vehicle_remote.dm
:cl:
spellcheck: Fixed some grammar errors regarding with droids
/:cl:
=> minor droid grammar fixes

code/game/objects/machinery/vending/new_marine_vendors.dm
Adds lack of jaeger exoskeleton and paint, removes fluff radio item. This makes it so a FC doesn't have to run to prep for jaeger if he chooses the jaeger life.
Fixes a oversight.
:cl:
del: Removes redundant radio to lessen clutter from FC essential kit.
fix: Fixed FC vendor not having jaeger exo or facepaint; comes in essential commander kit now.
/:cl:
=> Fixes FC Vendor.

tools/tgs4_scripts/PreCompile.sh
Port of https://github.com/tgstation/tgstation/pull/58108 which I just did on /tg/. TGS precompile was missing a dependency which would result in rustg not being usable on the host if it wasn't previously installed.
Fixes some tgs4 deployments.
:cl: bobbahbrown
server: Fixed missing dependency for libssl1.1 in PreCompile.sh
/:cl:
=> Update dependencies installed for TGSv4 precompile scripts

code/game/objects/effects/effect_system/smoke.dm, code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/machinery/vending/new_marine_vendors.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_defense.dm
Cloak grenades now only stealth marines. Cut cloak grenade supply in half to account for this.
Makes cloak grenades easier to play around and can help as an option that encourages pushing by allowing marines to advance while being harder to be focused down or ganged up on by xenos due to being stealthed. Xenos can still see the smoke, so marines using these aren't completely unpredictable either. 
Having xenos be stealthed like currently is much better for xenos than marines being stealthed since xenos can generally tank a few stray shots and most of their skills are projectiles, have a good area of effect or bumpslash, meaning they don't need to specifically see their target to be effective or worry about FF.
:cl:
balance: cloak grenades cloak only marines instead of marines and xenos, …
=> Cloak grenades only stealth marines, supplies cut in half

code/modules/projectiles/ammo_datums.dm
Reduces revolver screenshake, apparently seems to be too much, often confusing people alot and making people 🥴 , this reduces it by half, revolver ocelot requested this.
Reduces a very strong effect to player vision which caused people to be very confused when happened and was delivered by a free gun and etc.
:cl:
balance: revolver screenshake when hit reduced by half.
/:cl:
=> reduces revolver screenshake a bit.

code/modules/reqs/supplypacks.dm
railgun goes from 130 to 75, rounds reduced from 4 to 3 as you only get one. 
anti mat from 120 to 70, ammo normal halved in price
M4RA goes from 80 to 50
These guns are incredibly niche and only useful in certain situations and I don't really see the point of making as expensive anymore. Xenomorphs get infinite respawns now so power weapons don't need to be as limited
:cl:
balance:  power req guns reduced in price. railgun goes from 130 to 75, rounds reduced as you only get one. anti mat from 120 to 70, ammo normal halved in price M4RA goes from 80 to 50
/:cl:
=> makes some power weapons (m4ra, railgun, anti material rifle) cheaper

code/game/objects/items/storage/pouch.dm, code/game/objects/machinery/vending/new_marine_vendors.dm
Revives #6099 with some extra additions.
Makes engi materials much less expensive to buy via points, gives a significant buff to engi starter, buffs construction pouch to 4 slots instead of 3 to compensate for all these extra mats.
Engi materials were always the worst thing about combat engi; you can barely buy any and your starter kit is trash. On top of that, your storage options suck for mats even if you somehow get more later on. This PR aims to solve those issues, which will allow combat engis to actually be combat engis; both shooting at the enemy, cading flanks, and setting up miners without having to ebeg if you try to do only one of these. Currently combat engis only gameplay is plasma cutter memes, or hugging a miner for 20 minutes in hopes of getting materials from a RO (and …
=> Combat Engi Rework; Electric Boogaloo Edition

code/__DEFINES/cooldowns.dm, code/game/objects/effects/aliens.dm, code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm, code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Make the cone spray more consistent in the way it is blocked by obstacles. You can now spray in diagonals. Remove all ugly sleep with timers. You will now fall over when crossing a fresh acid spray poodle, to prevent the bug when you could avoid the paralyse by walking toward the praetorian, spitter or boiler
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/5859
Collision : 
Diag cone:
Code is a bit neater, diagonal cone is cool, remove possible exploit
:cl:
code: Acid spray cone code no longer uses sleep.
refactor: Cone spray use recursive code, which mean blocking the middle row will not block the other part of the cone. In short, collisions are more consistent
add: Praetorian can spray diagonally
fix: You can no longer avoid acid spray by running towards the caster. …
=> Praetorian cone sprays rework + acid spray exploit fix

code/modules/reqs/supplypacks.dm
Changes portables to 30 points and base to 60 points in requisitions.
This PR puts the turret prices in line to around 4-5 mins of profit from a phoron (for portable) or 4-5 mins of time of profit for plat (for base) without overclock. This allows marines to be actively rewarded for capturing miners because they can finally defend them without having to pull half the force from the front (which makes miners useless since if half the marine force isn't at front they usually fall apart due to how marines and xenos are balanced). Capture a phoron and portable it on alarm mode and cade it to protect against T1's and Wraith's (who can still affect miner outposts; they just have to actually put effort now). Base turrets for plats if marines get that far and are willing to spend the cash on …
=> Turret Price Change

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
There was a recent round where the tadpole landed on the tiny island in the middle of prison, stopping the xenos from reaching them or hijacking, this fixes that by making that area accessible and traversable
no accidental marine delays
:cl:
fix: Marines should no longer be able to delay prison rounds by tadpoling to the tiny island
/:cl:
=> Fixes Tadpole on Prison issue

code/game/objects/items/stacks/sheets/sheet_types.dm
Makes razorwire infinitely easier to make. Just use metal in hand and click on razorwire. Old method stays in the game cause I don't want to comment it out lest it be used for other projects (as example code, etc).
Less hassle and more QoL for engis.
:cl:
qol: You no longer have to fumble around with barbed wire and rods to create razorwire; it can now be made straight from the metal menu.
/:cl:
=> Razorwire now buildable from metal menu

code/modules/mob/living/carbon/human/human_defense.dm
Essentially, this fixes a bug I found recently that...probably has been here a long time? Probably. Maybe. Basically upon testing screech and examining the vars of the affected human at various ranges, I found that, well, screeching right next to the target was doing 70 stamina damage while screeching at screen edge from the target was doing 130, and the admittedly short stun time was also doing...wrong. So I took the numbers and swapped them and tested it and hey, wouldn't you know, it worked. Last seen numbers said in PRs have stated intended screech values as 130 beside Queen, and 70 at screen edge, so I've kept those numbers. The 140 is for purposes of having that be the actual numbers, since with the max as 130, you would be only getting 120 stamina damage while adjacent to the …
=> Queen Screech Update PR. 

code/modules/mob/living/carbon/human/human_damage.dm
Halves slowdown from wounds, and makes it happen when you have 50 or more damage (up from 40).
Reduces a big source of slowdown for marines, which coupled with stuff like Jaeger suits and other sources of slowdown, reduced marine speed drastically.
:cl: Lewdcifer
balance: Wound slowdown halved, appears slightly later
/:cl:
=> Halves slowdown from wounds

code/__DEFINES/supply.dm, code/modules/clothing/head/helmet.dm, code/modules/clothing/suits/marine_armor.dm, code/modules/reqs/supplypacks.dm
Rebalances B17 and B18 to actually be power armors worth buying. Changelog has the most details.
B17 and B18 are really subpar power armors despite their price tag and their purpose. They are supposed to be vanguards that push in ahead of everyone while tanking, but it does this job poorly. Not only is it only 5 melee above heavy jaeger tyr 2 (which is only 12 points as opposed to 60 or 100), it doesn't have the utility of jaeger, or the speed of PAS despite being a req buyable item (for a hefty price tag). The same is for B18; its even worse as it has the slowest movement debuff in the game even without welding a gun (1.15). This PR serves to solve this issue by giving both medium tags (0.55 debuff instead), upping their values, and hence making this less of a "well I have too much money …
=> Power Armor made useful again

code/game/objects/items/weapons/blades.dm
Changes harvester effect slightly and moves them from longer effects to shorter ones with more immediate impact.
Changed harvester effects cost from 10u to 5u. 
- Kelotane effect now ignites all mobs in the cone, dealing additional fire damage, without leaving fire tiles. 
- Tramadol effect deals 60% bonus damage that ignores armor, but the slow lasts 1s instead of 2s. 
- Bicaridine effect heals 12.5 brute instead of 10 brute. If you target yourself, it instantly (without the usual channeling delay) heals 6 brute and restores 30 stamina.
> For reference, when metabolized 10u of bicaridine heals 50 brute and if the volume is above 20, 10u heals 75 brute, while also giving 60% of tramadol's pain reduction.
First, I think these changes should be tested before merge.
The changes allow for …
=> Harvester effects small rework

code/game/atoms_movable.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/life.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Humans in hardcrit now take low amounts of oxy damage when dragged while in hardcrit.
(originally insta death)
I have no idea what I'm doing with github, so let me know if I messed up the PR.
Critdragging helps xenomorphs secure kills and is seen as a good feature, but being dragged across the entire map, or having to drag someone across the entire map, is not fun gameplay. Making humans take around 5 oxygen damage each tile allows xenomorphs to still do what would reasonably already be expected, but stops singular marines being dragged to completely irrecoverable positions.
:cl: Chipswithchops
add: Humans in hardcrit now take low oxy damage per tile when dragged by a xenomorph 
\:cl:
=> Humans now take low oxy damage when critdragged

code/controllers/subsystem/silo.dm
Xenos had the right amount of larva per minute shipiside, but the number in hive status were wrong
:cl:
fix: Larva output number in hivestatus is now correct shipside
/:cl:
=> Larva output of super pool was wrong

_maps/map_files/Sulaco/Sulaco.dmm
#6441 had a pipe overlap and shouldn't have been approved and merged, this fixes that
perhaps not having 1000 warnings pop up everytime sulaco is loaded is good for game?
=> fixes recently introduced Sulaco Pipenet issues

code/game/objects/structures/mortar.dm
Removes the delays for operating the Mortar without the engineering skill. Any PFC can operate it as fast as anyone else.
The Mortar is hardly used as it requires a valuable engineer to camp at the FOB all day. I personally like using the Mortar however I don't because Engineers are too valuable to sit at the Mortar all day. This allows an regular old squad marine to use the mortar as effectively as anyone else.
:cl:
balance: Removes Engineer skill requirements for Mortar.
/:cl:
=> Removes Engineer skill requirement for Mortar

code/modules/organs/limbs.dm
Recently arm has been very much aimed by most people and this nerfs it, my consideration for buffing the arm its that it has same armor as chest with alot of debuffs once broken/removed, unlike leg, so i've buffed its health to 125, needing more 25 damage for delimbing, also robolimbs suck they need buffs.
Makes arm aiming not alot way superior than the other limbs, its now harder to delimb.
:cl:
balance: arm is now harder to delimb, max damage raised to 125
/:cl:
=> Nerfs arm aiming.

code/game/objects/structures/xeno.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm, code/modules/xenomorph/xeno_structures.dm
1. Distance data is now included for Hive and Tunnel status lists.
2. Should fix a bug that stopped Tunnel lists from being openable.
1. Distance data is now included for Hive and Tunnel status lists.
2. Should fix a bug that stopped Tunnel lists from being openable.
:cl:
code: Distance data is now included for Hive and Tunnel status lists.
fix: Should fix a bug that stopped Tunnel lists from being openable.
/:cl:
=> Hive Status and Tunnel List Info Now Includes Distance

code/modules/projectiles/guns/energy.dm
You had to switch back to standard mode to get autofire
:cl:
fix: Autofire mode in lasgun will be on when you buy the gun
/:cl:
=> Fix lasgun autofire mode not being on at init

code/modules/organs/limbs.dm
Makes it so you have a proper malfunction threshold with robo limbs and slight buff from 0.66 to 0.50 reduction to damage.
Currently, robo limbs penalize you too much. They malfunction randomly (with no way to fix this except full repair), do not benefit from autodoc / chems, and on top of this require you to restructure your entire setup around it (welder, jaeger helmet or welding helmet if you use PAS, and cables).
This PR seeks to alleviate the worst aspect of the robo limbs (random malfunctions) by removing them entirely, and buffing the amount of damage robo limbs take. This still forces a permanent condition on marines (since they still have to re-order their gear around it), but it also makes it not a "im delimbed, might as well cryo" moment.
Reason why it is important to keep this …
=> Robo limbs proper malfunction and slight damage reduction buff.

code/modules/mining/remote_fob/remote_fob_fobdrone.dm
FOB drone can move on ice turfs now, I'm not sure why they were blacklisted in the first place but if someone can come up with a compelling reason to keep them black listed I'll remap the ice off the LZ instead.
LZ2 ice colony not a pain in the ass to use
:cl:
fix: The FOB drone can now move on ice tiles in ice colony LZ2
/:cl:
=> Fixes FOB drone on ice colony LZ2

code/game/objects/items/stacks/barbed_wire.dm, code/game/objects/items/stacks/sheets/sheet_types.dm
:cl:
qol: Metal/Plasteel sheets and barbed wire now have the NOBLUDGEON flag, which prevents accidentally damaging the cades while hitting them on harm intent. This also means you cannot attack anyone with it anymore, not like it really matters...
/:cl:
=> Barricade QOL

code/game/objects/effects/overlays.dm
Cas laser when shooting will always be shooting, no more sneak shooting in xeno
The laser being BELOW mobs doesn't make any sense IC wise, and it is allowing cas stealthkill if the xeno is not 100% vigilant. 
The laser was added so it was fair and xeno could be able to act to avoid being killed, but if you can hide the laser it doesn't allow that
:cl:
balance: The cas laser can no longer be hidden below an object or a mob
/:cl:
=> Cas laser layer change

code/datums/components/chem_booster.dm
Removes reagent modification from Vali. Replaces it with brute/burn heal and stamina regen.
- Restores 6 or 12 brute and burn based on effect
- Stamina regen happens if you have a connected weapon and scales inversely with active time, from 7 and becoming 0 past 20 seconds.
Changes the reagent storage function to store and inject only 30u so that people don't accidentally overdose.
Connection a weapon takes 1 second instead of 2.
Now the suit checks for germ level rather than necrotized limb flag when deciding on what limb to increase the germ amount pf past 20s. This is due to the necrotized flag not doing damage or other effects associated with high germ levels and thus allowing a way to circumvent the system in specific cases. It shouldn't change almost anything in practice.
Makes Vali …
=> Simplifies Vali

code/datums/jobs/job/pmc.dm, code/datums/jobs/job/shipside.dm, code/game/objects/effects/landmarks/corpsespawner.dm, code/game/objects/items/storage/belt.dm, code/game/objects/items/storage/marine_boxes.dm, code/modules/clothing/suits/armor.dm
Completes one of these approved suggestions.
https://tgstation13.org/phpBB/viewtopic.php?f=65&t=20487
Allows an empty pistol to be reloaded from a pistol belt using right click so long as right click is disabled and there is no ammo within.
https://tgstation13.org/phpBB/viewtopic.php?f=65&t=20487
It was an approved suggestion.
I think it would make reloading these low capacity weapons far easier. 
:cl:
add: Allows an empty pistol to be reloaded from a pistol belt using right click so long as right click is disabled and there is no ammo within.
/:cl:
=> Allows reloading from pistol belt.

code/game/objects/machinery/miner.dm
I used my understanding of combat floodlight code to do this, so it might not be THE BEST way to do this, but it works and when I tested it I got no errors.
As for what this does, it makes have no light when broken, small light when light repair, decent light when medium repaired, and 8 tiles of light when fully operational. This also simulates the intense mining that a miner does; your drilling into the earth and such, yada yada.
A buff to properly defended miners (at minimum caded, at max with turrets and cades), while a nerf to stealth mining (the light is 1 tile extra of a floodlight; a single xeno patrol for 30 seconds to 1 min is now enough to spot stealth miners since they give off huge light).
:cl:
add: Miners now give off their own light; both in the repairing process and in the …
=> Gives light to miners if repaired.

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
annoying fence gets in way of FOB drone
can build cades in spot the useless fence is in
:cl:
qol: moved fences on the ice colony LZ2 flanks, this means you can put cades where they used to be on the FOB drone now
/:cl:
=> Ice LZ2 QOL fence removal

code/modules/mob/living/carbon/human/human_damage.dm, code/modules/mob/living/carbon/human/species.dm
Increase the damage reduction given by hold order
before PR, ~7% per order level
leadership 2: ~.93
leadership 3: ~.87
leadership 4: .8
after PR, 10% per order level
leadership 2: .9
leadership 3: .8
leadership 4: .7
Move order is pretty much always the best order to use because aim orders only good benefit (instant aim mode activation) is niche and hold orders don't do enough. Hopefully this makes hold order better.
:cl:
balance: hold orders are more effective at reducing incoming damage
/:cl:
=> Hold Order Buff

code/__DEFINES/actions.dm, code/_onclick/click.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm, code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm, code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm, code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Add a lot of target flags on xeno abilities, so it's easier to hit the desired target. Hitting the turf where the target is will automaticly redirect your ability on the target
Remove unused targeting flags
With lag, byond being bad, high TD, you sometimes have to spam your abilities to manage to hit you target. This makes it easier to hit those, which is nice QOL
:cl:
balance: Hitting the turf where the target is will automaticly redirect your ability on the target. This works for most xeno ability
code: Remove unused targeting flags
/:cl:
=> Xeno abilities easier to land on targets

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
:cl:
fix: Wraith can't phase into ice colony LZ1 through a gap in the shutters
/:cl:
=> Fix a gap in ice colony containment shutters that wraith could phase through

code/modules/mob/living/carbon/xenomorph/abilities.dm
Title
So you can know when a hivelord is puttin turrets everywhere like it's TF2. 
:cl:
qol: Xeno message is sent to the hive when silos/turrets are built
admin: Psy points spent are now saved in game log
/:cl:
=> Xeno get a message when silos/turrets are built. It is also registered in the game log

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Fixes what i fucked up in #6531 also makes central dome and surrounding areas....area'd
fixes a bug and reduces pockets of SPACEEEEEE! on prison
:cl:
balance: water around central dome on prison are now accessible
fix: fixed the pocket of space localized entirely within prison station that was killing marines/xenos
/:cl:
=> No more inbetween space areas on prison

code/game/objects/items/explosives/bombvest.dm
Synths can no longer operate suicide vests
They were never supposed to.
:cl:
fix: Synths can no longer operate suicide vests
/:cl:
=> Synths can no longer operate suicide vests

code/datums/beam.dm, code/modules/projectiles/ammo_datums.dm
Lowers tesla shell speed from 2 to 0.1, lowers drain, and plasma regen disable from 30 to 20, and increases the slow telsagun has 0.5 to 2.
I copypasted code onto beam.dm, probably gonna get yelled by tivi.
No one uses tesla since plasma nades outperform it, even with the stagger buff I did to it, lowering the speed lets it stagger, drain, and slow xenos for longer.
:cl:
balance: Lowers tesla shell speed (2 to 0.1), lowers drain, and plasma regen disable (30 to 20), and increases the slow telsagun has (0.5 to 2)
/:cl:
=> Tesla Is now 0.1 shell speed, lowers total drain time, and slowdown up.

code/modules/reqs/supplypacks.dm
Makes lemoline easier to use, changing its price from 50 req points to 25, half.
Lemoline is supposed to be the substitute of larva jelly, req orderable; larva jelly and lemoline are ussed to make advanced healing chems. With the end of cap gameplay and the carrier/Defiler rebalance, hardly any round you will get a marine with a larva to extract and turn into jelly; while lemoline should cover this, it being 50 req points make it so no mentally sane RO ever buys it since means not being able to drop Spec guns to marines/mats and so. While also making the life of researchers and chemists a lot harder. Rebalancing it to 25 points instead of 50 for a 10u bottle of lemoline that works for 40u of adv.chems, makes lemoline not as scam, and will make ROs buy it more.
:cl:
balance: Req Lemoline …
=> Lemoline is too expensive, make it cheaper.

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Leader xenos now stop receiving pheros from a dead queen, they keep leader status however.
Doens't make sense for these pheros to stay even after death, which essentially are infinite pheros since queen doenst even need to be alive to give them by staying after a queen dies.
:cl:
balance: leader pheros are now removed when queen dies.
/:cl:
=> leader xenos now lose queen pheros when queen dies.

code/datums/components/chem_booster.dm
In #6576 I added a movement speed buff to Vali that scales with item slowdown in order to make it good for people who wear heavy armor/shield without making it godlike for light-armored marines. But the calculation was not working properly for certain item slowdown ranges. 
After thinking it over, adding this in a non-exploitable fashion is not worth the added performance and complexity, so I'm removing it and changing buff values to match this.
Normalizes movement speed bonus from Vali. so it is simpler.
:cl:
balance: removes item slowdown scalability from vali speed buff, changed Paracetamol buff from -0.2 to -0.1 and Neuraline buff from -0.4 to -0.3.
/:cl:
=> Vali movement buff fix

code/modules/reqs/supplypacks.dm
Makes OB warheads and solid fuel go up in a locked crate that requires engineering access. 
Huge QoL as it makes buying fuel and/or warheads worth it beyond roundstart ones as you no longer have to drag all of them to and from OB room via multiple ripley trips; you merely have to grab the crate itself. This also locks it behind engineering to prevent random ungas or yourself from accidentally opening it right away (since, once its open, it can't be put back into the crate).
:cl:
qol: OB warheads and fuel bought in req now comes in a locked crate for easy movement to / from OB room and to prevent random opening / theft of the crate.
/:cl:
=> OB Req QoL V2

code/modules/mob/living/carbon/xenomorph/charge_crush.dm
No more gore pets like:
Bug bad. Fix good. Clearly it is intended for this "free" extra attack to always harm as the old broken code suggests.
:cl:
fix: Bull's extra gore attack now always harms instead of using what ever intent is selected.
/:cl:
=> Fixes Bull's gore free attack using the wrong intent

code/modules/projectiles/ammo_datums.dm
Will extinguish all mobs hit by the projectile (including human, so double edged sword). Will also remove some fire stacks from the tile, or extinguish the turf if the fire is weak enough
Marines have more and more way of setting xenos on fire. 
Cas was introduced, then the vali, then the plasma pistol, then the latest mortar buff.
Meanwhile, xeno keeps having only two way of "contering" flamers, acid wells (terrible, cost so much plasma, so long to refill),
acid spray(usefull)
and of course hivelord, with jelly. 
Basicly, if you are against flamer, you NEED an hivelord, and sometimes you just can't have it with your comp.
This gives prae some utility against flames, nothing too crazy. 
This will also make prae as usefull to counter fire as spitter; 30 seconds between each spray is not …
=> Prae spit extinguishes fire

code/modules/projectiles/ammo_datums.dm
Reverts tgstation/TerraGov-Marine-Corps#6611
prae no longer extingushes fire on spitting
Prae spit probably shouldn't extingush fires and the person that merged it said they thought it meant something else extingushing
:cl:
del: Prae spits no longer extingush fire
/:cl:
=> Revert "Prae spit extinguishes fire"

code/modules/mob/new_player/new_player.dm
Fixes: #6551 
Bug bad. Fix good. Closing dialogs should not count as affirmative input.
:cl:
fix: Closing the "Warning : the game is unbalanced" dialog when joining late as a marine no longer proceeds to spawn you in.
/:cl:
=> Fixes still spawning as a marine after closing the "game is unbalanced" dialog

code/modules/xenomorph/xeno_structures.dm
Some code added for turrets was acting on silo by mistake
:cl:
fix: No longer weird damage overlay on silo
/:cl:
=> Fix some turret proc acting on silo as well

code/game/turfs/floor_types.dm
Fixes: #6342 
Please give this one a thorough review and suggest any better alternatives as I did not want to waste a ton of time to figure out why rfloors are `/turf/open/floor/engine` in the first place or why `/turf/open/floor/engine/make_plating()` the proc that usually handles tile removals so they can't be duplicated is totally bypassed for this type. My guess is there are some very old legacy reasons and if I were to change it could have unforeseen and dire consequences.
:cl:
fix: Fixed a glitch which could break the metal economy. 
/:cl:
=> Fixes infinite metal from reinforced floors exploit

code/modules/projectiles/ammo_datums.dm
DMR given 40 tile range same as snipers.
DMR has standard range despite being a "Designated marksman rifle" meaning it can't even use its 30 tile accuracy for some reason. Now bullets won't go poof before even reaching the accuracy falloff.
:cl:
balance: DMR gets sniper range
/:cl:
=> DMR now has sniper range

code/game/objects/structures/orbital_cannon.dm
Fixes: #6363 
Closes: #6596 
*Sorry @joshypooh I didn't see your existing PR when I made this one as it didn't reference the issue, message me on discord if it gets closed and you'd like help contributing a different fix.
:cl:
fix: Ghosts no longer have a fumble time when looking at the OB cannon console.
/:cl:
=> Fixes ghosts fumbling with the OB cannon console

code/modules/mob/living/carbon/xenomorph/say.dm
Shows the Hiveminds nickname in its radio chat.
It allows Xenos to be able to tell who the hivemind is.
:cl:
qol: Shows the Hiveminds nickname in its radio chat.
/:cl:
=> Shows the Hiveminds nickname in its radio chat.

code/game/objects/items/explosives/bombvest.dm
Blowing yourself up now takes a brief moment to trigger displaying a warning icon above your head (like when using a rocket launcher), and results in you losing all your limbs.
Devastation radius from 0 -> 2 allowing high caliber wearers to inflict serious wounds on any one or anything directly next to them.
Highly demanded. Removes the lack of a round removal disincentive that should come with a very strong "suicide" item. Prevents unfun instant jetpack explosion shenanigans. 
:cl:
balance: Tactical explosive vests now have a short wind up time, more close range damage, and a guarantee you will become a dead nugget.
/:cl:
=> Tactical explosive vest balance attempt

code/controllers/subsystem/minimaps.dm, code/game/objects/machinery/cic_maptable.dm
Random bug i encountered while doing other stuff:
If a maptable exists roundstart , it will get an empty command groundside map and get that empty map saved in the subsystem.
Meaning that every map table and command headset with the groundside minimap (both of which share the same minimap) won't be able to open the minimap because an empty one from the maptable's fetch_minimap_object proccall was saved.
Happens most likely due to the atoms subsystems initializing the maptable waay before the minimap subsystem has the chance to generate the minimaps itself, causing fetch_minimap_object to fuck up.
This bug won't happen if the map doesn't start with a map table initially, which is the case for debugdalus. Might be why this bug got through, since spawning a maptable when one doesn't exist …
=> Fix maptables and command headset minimaps

code/__DEFINES/mode.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm
You can no longer build small silos if the active pop of the server is superior to 30
The full small silo start for xenos is too good, and more important, it is actively discouraging marines to push. 
I'm keeping small silos cause they are nice to have in small pop
:cl:
balance: Can no longer place small silos in medium-high pop
/:cl:
=> Small silo linked with pop

code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/life.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm, code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm, code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Title.
Fixes: #6503
I guess permadeath for marines is bad during Distress Signal rounds? Here your crutch is a little better now.
:cl:
fix: Shrike's unrelenting force no longer displaces dead humans.
fix: Warrior's fling no longer works on dead humans.
fix: Unconscious humans pulled through a Wraith teleport receive equivalent critdrag damage based on distance traveled. 
/:cl:
=> Fixes a few instances of xenos moving bodies beyond critdrag range

code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Prevents `charge_crush`  logic from acting on resin silos and turrets, doors in their slow form and walls will still be crushed as normal.
Crusher harming these structures appears to have been an oversight as I was unable to find a way for any other caste to cause them harm, so it stands to reason it shouldn't be happening.
:cl:
fix: Crusher charge no longer damages resin silos and turrets. No more mystery silo damage alerts.
/:cl:
=> Fixes crusher charge damaging resin silos and turrets

code/_onclick/hud/screen_objects/screen_objects.dm, code/modules/mob/living/carbon/xenomorph/evolution.dm
Adds a bit of evolution code to retain `zone_selected` when xenos change caste.
Fixed a small bug causing `set_selected_zone()` to pass the wrong mob to an overridden `update_icon()` making it fail to update `zone_selected` in some cases.
QoL good. Xenos needing to rundown a post evolution checklist in order to get back to full readiness is bad. It was worse when it reset the old mmb/shiftclick pref and this is almost as annoying.
:cl:
qol: Xenos now keep their selected targeting zone when evolving/regressing.
fix: Fixed a small bug with the zone selection hud.
/:cl:
=> Xenos keep their targeting zone selection across evolutions

code/modules/modular_armor/modular.dm
Fixes invisible jaeger helmets created when trying to cancel coloring them.
Adds a check after color selection in helmet coloring code to actually cancel coloring when no color is selected.
bug fix good
:cl:
fix: Fixes invisible jaeger helmets created when trying to cancel coloring them.
/:cl:
=> invisible helmets bad

code/modules/reqs/supplypacks.dm
ReQ cost change to an item that doesn't really get any use due to its expensive cost.
Jetpack cost: 15 -> 12
Jetpacks aren't used by a lot of marines, not because of the drawbacks it has (Lack of backpack storage/second weapon) but because its price in req is way expensive for what it does.
The item doesn't need to be stronger in my opinion, it has already the ability to escape warriors/shrikes brazil abilities and give a nice leap when you need to keep shooting at a target to finish it. That's why lowering the price would maybe make it more usable. A lot of ROs thinks jetpacks are a waste of points.
At first I wanted to put the jetpack in the vendor to make it consistant but I was afraid it would become a powergaming strategy (we don't want that to happen).
Valks/surts/hlin are highly …
=> Lower Jetpacks cost from 15 to 12

code/modules/mob/dead/observer/observer.dm
Adds a couple tweaked versions of the xeno tracker topic code to observers so they can use the normal hive status buttons to orbit xenos or jump to silos even easier.
QoL good.
:cl:
qol: Xeno hive status buttons work for observers too!
/:cl:
=> Makes xeno hive status buttons also work for ghosts

code/game/objects/items/storage/belt.dm, code/modules/clothing/under/ties.dm, code/modules/modular_armor/storage.dm
:cl:
qol: Made health analyzers and medical tweezers to be stored on more medical storages (medical belts for the former, webbings and medical armor modules for the latter)
/:cl:
=> Allows health scanners and tweezers to fit in more storages

code/game/objects/items/stacks/medical.dm, code/modules/organs/limbs.dm
Gives a splint health variable to limbs. Splint health gets decreased every time a splinted limb takes damage by the amount of damage and the splint gets removed at 0 health. Applied splint health is 15 per medical skill rank. If you splint yourself, you get 15 less splint health, but the amount can't be below 0.
As it stands right now valk's autosplint feature makes it a bit too convenient over the other modules, this should bring up the bottom line, while valk still has the benefits of instant and infinite splints.
:cl:
balance: splints require taking a certain amount of damage to break, based on medical skill of the one applying it. Anyone with medical skill adds 15 splint health per medical skill rank. If you splint yourself, this is reduced by 15, but can't be lower than 0.
balance: …
=> Splints require additional hits to break based on medical skill

code/game/objects/machinery/smartgun_mount.dm
Fixes a TL-102 ammo counter bug.
If the 102 is deployed with ammo, the ammo counter wont update until it is fire once. Its mild, but annoying.
Bugs = Bad
:cl:
fix: Fixes a TL-102 ammo counter bug.
/:cl:
=> Fixes a TL-102 ammo counter bug

code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Bull gore does double the damage, and it's aimed at the groin for maximum gore
Gore was only doing one free attack, and this is really terrible if you compare to the 5 seconds stun of a headbutt charge.
This makes gore more competitive, and allow the bull players to actually chose what options is better for what situation
:cl:
balance: Double the damage of bull gore and make it damage the area the player is aiming
/:cl:
=> Bull gore buff

code/modules/mob/living/carbon/xenomorph/evolution.dm
Fixes duplicate xeno regression software regression of my own making. Oops. 
Closes: #6724
Extra xenos bug bad, even if it is kind of funny.
Not worth a changelog or gdp.
=> Fixes xeno zone selection QOL regression bug

code/datums/components/bump_attack.dm
Fixes an invert bump attack message
looks to have been broken in https://github.com/tgstation/TerraGov-Marine-Corps/pull/6377
Bug fix - although there isn't an issue report, there was one on discord.
https://discord.com/channels/498569646014857217/504094319075131402/835344058171523134
:cl:
fix: bump attack toggle message was inverted
/:cl:
=> Fix bump attack message

code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
Blocks defenders from laying down while fortified.
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/6216
:cl:
fix: defenders laying down while fortified
/:cl:
=> Fix fortified defenders laying down

code/modules/mob/living/living_defense.dm
Adds the `updating_health = TRUE` argument to the apply damage code for thrown objects hitting non humans.
Fixes: #6686 
> Tank knives because you're an armor caste with moderate melee armor
If only.
Fix good. Delayed damage bad.
:cl:
fix: Fixed throw force damage delay for xenos.
/:cl:
=> Fixes thrown item damage application delay

code/modules/modular_armor/modular.dm
title
:cl:
fix: Open helmets use the correct colors and can be colored
/:cl:
=> Fix open helmets

code/modules/mob/living/death.dm, code/modules/mob/living/living.dm
Title. Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/5703
:cl:
fix: Corpses are no longer invisible in cloak nades
/:cl:
=> No longer invisible when dead in cloak smoke

code/modules/clothing/under/ties.dm
David yelled at me to do this even though I have no experience with coding lmao. If it's wrong yell at him.
I fixed the shoulder holster to support the T-19 machinepistol since one of the more recent changes seems to have broken it.
**If I needed to account for weapon modifications like the extended barrel and T-19 Stock making the weapon to large to fit than that is something beyond my know-how.**
It's good for the game because the shoulder holster has historically allowed for the T-19 to be placed inside of it but a few days ago a change was made removing that functionality.
Changelog
:cl:
fix: Edited the /obj/item/storage/internal/tie/holster path to allow for the standard_machinepistol
/:cl:
=> Updating the Shoulder Holster to fit the T19

code/game/objects/items/weapons/twohanded.dm
No longer can you pull off inhuman throw and pickup speeds with multiple spears, or any other two handed weapons, in melee range.
While we can't stop in keyboard or in mouse keypress macros to switch hands, toggle throw, and click the targets direction we can make it a little harder to give yourself godlike DPS on the reload.
Anyone looking to argue that they need to use a pickup macro to use the weapons should then also be okay with balancing throw force based on the fastest possible tool/macro assisted throw and pickup speed of the weapons.
:cl:
code: Two-handed weapons can no longer be picked up with a macro.
/:cl:
=> Pickup macro made null for two handed weapons (or 2 of them unwielded)

code/modules/client/preferences_toggles.dm
Adds the TGUI compability button present in the character setup as a byond verb, in the preferences tab.
Some people have issues with tgui, and using tgui to fix a tgui issue is not good, and leaves them stuck.
:cl:
add: You can now toggle TGUI window compability mode from the preferences tab too
/:cl:
=> Adds TGUI compability mode as a byond verb

code/modules/projectiles/gun_system.dm, code/modules/projectiles/projectile.dm
Terragov has updated their suppressors, they are now packaged with space kraut magic makes the tracing capabilities of bullets gone, now more usefull for your tacticool stealth TP-23 by making it harder for xenos to spot your boolets, also for stealth sniper man.
Its good trust me, now suppressors are even more stealthy
:cl:
balance: TerraGov made suppressors remove tracers from bullets using space kraut magic.
/:cl:
=> removes tracer rounds from suppressors

_maps/map_files/LV624/LV624.dmm
A lot of changes to make LV much less of a grass and river hell hole that forces xenos to constantly fight in caves only.
1) LV starts pre-weeded everywhere except domes (as they are randomized and I really don't want to touch that as a new mapper).
2) Indestructible rocks on certain parts of the caves to prevent PC cheese, while still retaining the PC as a good tool.
3) Opened up certain flanks while closing other flanks; makes far east and far west caves less of a death trap.
4) Adds and repairs several bridges to make river combat less shit.
5) Adds more dirt and removes a lot of grass so that xenos can weed more on colony / near rivers so that fighting near them isn't suicide.
6) Adds more "lanes" in Colony; more flank points so as to slow marines down.
7) Fixes the easy west cave …
=> LV Rework V3

code/__DEFINES/dcs/signals.dm, code/datums/components/clothing_tint.dm, code/datums/elements/special_clothing_overlay.dm, code/datums/greyscale/greyscale_configs.dm, code/datums/greyscale/json_configs/modular_visor_emissive.json, code/datums/greyscale/json_configs/modular_visor_emissive_skull.json, code/game/objects/items.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/modular_armor/modular.dm, tgmc.dme
Jaeger vendor next
Has a toggle because why not
:cl:
qol: Jaeger visors now glow in the dark, this can also be toggled with right clicking on the helmet
/:cl:
=> Adds emissive jaeger visors that glow in the dark

code/game/objects/effects/effect_system/foam.dm, code/game/objects/structures/razorwire.dm
Razorburn gas makes regular razorwire. You can't repair it anymore without metal, so I believe this is acceptable.
Tweak to make a marginal item more relevant and keep crushers out. Also prevent acid from one-shotting a whole canister in one go.
:cl:
balance: Razorburn starts at full HP.
/:cl:
=> Foam razorwire doesn't exist anymore.

code/datums/weather/weather_types/sand_storm.dm
Adds a chat notice to the sand storm `weather_act` just like the acid rain has. 
Taking damage with no feedback is bad, even if there was an alarm before the storm.
:cl:
qol: Damage taken from harmful sand storms now comes with a combat log notification.
/:cl:
=> Include a notice with sand storm damage like acid rain does

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm
Don't apply `TRAIT_PSY_DRAINED` during `set_undefibbable()` anymore.
Do apply it on successful headbite, so we can still get the use out of the hud icon for non distress modes.
Eating a bullet, going cold, or calling undefibbable any other way prevents psy draining for some reason. This is the fix.
:cl:
fix: Fixed psy drain not working on some corpses which it should.
/:cl:
=> Fix psy drained trait being applied too often

code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Make xeno stings (larval and neuro) no longer instant.
Reduce to 0.5 seconds the time between each sting
You can't do anything against xeno stings as a marine, and neuro is ultra cancer.
This nerf sentinel by a lot, but I think it's neuro spit is good enough to keep that caste relevant.
:cl:
balance: Make xeno stings (larval and neuro) no longer instant. It takes 0.5 seconds to get first sting
/:cl:
=> Nerf xeno sting

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Banished Targets Now Disgorge Living Contents
Stops living contents from leaving/being ejected from banished targets in Brazilspace, thus being trapped there forever.
:cl:
code: Banished targets are now emptied of all living mobs before being sent to Brazilspace.
/:cl:
=> Banished Targets Now Disgorge Living Contents

code/modules/mob/living/carbon/xenomorph/abilities.dm
Add the trait to the victim BEFORE calling `set_undefibbable()` which apparently also halts some processing of the mob including its status HUDs. While I checked for the trait being applied to the mob via VV my timing was off and it would never update it visually. Oops.
Fix good.
:cl:
fix: Fixed the xeno hud not updating their victims psy status symbol after headbite.
/:cl:
=> Fix headbite xeno hud update that I broke.

code/modules/admin/admin_verbs.dm
Simply adds a check for a message body to early return for short circuiting further dsay code if there is no message to send in the first place.
Less pointless warnings good.
:cl:
admin: DSAY no longer pesters mentors who cancel or submit an empty message with a notice about needing to be dead to do the thing they canceled doing.
/:cl:
=> Make accidentally opening the admin dsay dialog less annoying

code/modules/xenomorph/xeno_structures.dm
Fixes: #6809
Makes the resin turrets behave like acid wells only spawning the smoke if they are destroyed by actual damage.
Fix good.
:cl:
fix: Xeno turrets crushed by alamo landing no longer make acid smoke.
/:cl:
=> Fix xeno turrets broken by the alamo spewing acid smoke

code/game/objects/items/storage/large_holster.dm, code/game/objects/machinery/vending/marine_vending.dm
Puts all Mk1 jaeger modules in the armor vendor. Harvester blade at clothing vendor right below the machete scabbard.
Also harvester blade scabbard has unique name now so that it doesn't fuck with vendor entries.
Halp i accidentally picked wrong module lemme change it
:cl:
add: Mk1 Jaeger modules in armor vendor
/:cl:
=> Mk1 Jaeger modules in armor vendor

code/modules/client/client_procs.dm, code/modules/mob/new_player/login.dm
Copypasta some `/client/verb/showrevinfo()` code to be run during `/mob/new_player/Login()` upon connection.
Probably a candidate for a TM itself as I do not know how to simulate the conditions needed to spoof testmerges for testing with or without tgs running.
Informed players good. Hopefully will reduce confusion when things come and go without a trace in the changelog.
:cl:
qol: You will now be notified of any active testmerges automatically when you login.
/:cl:
=> Automatically show testmerges on login if there are any

code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
Update the `mechanics_text` for Bull's charges so they are visible from the evolution panel for curious players perusal.
"This ability not found in codex." bad.
:cl:
qol: Codex now contains info on Bull's various charge modes.
/:cl:
=> Add Bull's charge modes descriptions to the codex

code/game/objects/machinery/miner.dm
Adds a check of cardinal directions around miners for an open turf for shipments to happen.
Wraith can no longer phase in to make a walled in miner work against the marines, so it's time for this meta strat that can guarantee 30+ points per miner setup this way to die.
:cl:
balance: Automated miners require an open side to properly operate.
/:cl:
=> Automated miners require an open side to sell ore

code/datums/components/chem_booster.dm
Fixes Vali not disabling if activated and immediately after that the exoskeleton is unequipped.
fix
:cl:
fix: fixed vali not deactivating if activated and immediately after that the exoskeleton is unequipped
/:cl:
=> Fixes Vali not disabling if unequipped soon after turned on

code/controllers/subsystem/vote.dm
Title.
More people tend to vote in the later polls after they have died once or twice in EORD. The most important of the three should get the last slot especially because respawning makes you lose the vote UI button and must be found in the OOC tab.
Gamemode polls can always be started by players the following round if the turnout was subpar, but we are stuck with that map 1 or 2 people total voted for (Prison or Barrenquilla) without admin intervention.
:cl:
qol: Groundmap Vote is now the last of the post round automatic polls instead of the first.
/:cl:
=> Reorder end of round automatic votes, groundmap last

code/modules/mob/living/living.dm
Touch some 3 years old code that is now only used by xeno spit and scatter spit abilities to fix a bug which made it not account for `zone_selected` at all due to a missing arg.
RNG bad. Stinks of stealth balance or a lack of testing.
:cl:
fix: Fixed Xeno (scatter) spit targeting ignoring body zone selection.
/:cl:
=> Fix xeno spit and scatter spit aiming

code/datums/keybinding/xeno.dm
Two keybinds had the same way so wraith blink was not showing
:cl:
fix: Wraith blink has its keybind back
/:cl:
=> Fix wraith blink keybind not showing

code/modules/projectiles/ammo_datums.dm
See title.
Large disparity between the sunder per second and sunder per magazine between the TP14 and TP23, which are supposed to be side-grades. Doing this lowers said disparity to more reasonable levels, and doesn't make the TP14 effectively a straight upgrade over the TP23.
Also helps with the giant meme that is dual TP14s shredding ancient queens in the time it takes to empty one magazine (~3 seconds).
Done at the request of Georgeur/Revy
:cl:
balance: lowered TP14 sunder to 1.4, kept most commonly used ammo types at 2.
balance: changes TP14 to 1.65, buffs TP23 bullet sunder to 2.15.
/:cl:
=> Rebalances standard issue pistol sunder (TP14 to 1.65, TP23 to 2.15)

code/datums/gamemodes/crash.dm, code/game/objects/machinery/nuclearbomb.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Updated the crash nuke logic to be compatible with the new xeno tracker.
Added a `set_all_trackers` proc to the hive_datum.
Fixed the nuke activated `SIGNAL_HANDLER` args so they actually work.
Fix good.
:cl:
fix: Fixed the xeno tracker not pinpointing the active nuke during crash.
/:cl:
=> Fix xeno tracker not updating for crash nuke activation

code/game/objects/effects/aliens.dm
Turrets an prae are producing /obj/effect/xenomorph/spray when spitting. This object is also used by acid spray abilities, which mean that my latest bugfix was also producing a runtime;
This fixes the runtime
:cl:
fix: runtime on prae spit
/:cl:
=> No more runtime on prae acid spit and xeno turrets

code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Check for `TRAIT_UNDEFIBBABLE` which gets set when SSmobs stops processing a mob and if found manually call `med_hud_set_status()` to update the HUD which otherwise would remain static.
:cl:
fix: Fixed Xeno psy status HUD not updating for some mobs after draining.
/:cl:
=> Fix xeno psy hud not updating for non-processing mobs

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Removes a couple `check_state()` so xenos may take the harmless action of setting their tracker target while resting.
While resting for heals and plasma is one of the best times to check hive status and select things to track.
Xenos can use a bunch of abilities while resting now including pheros, so why not something as simple and low impact as picking a xeno or silo to track?
:cl:
qol: Xeno tracker target can be updated while resting.
/:cl:
=> Allows xeno tracker target selection while resting

code/game/objects/machinery/vending/vending.dm
Restocking an item with an infinite supply will no longer make the amount of item increment.
This does not fix the stock showing even for negative stocks, as it is working fine on local serb?
:cl:
fix: No longer can break infinite supplies by restocking
/:cl:
=> Prevent restocking of infinite supplies

.github/workflows/conflicts.yml
fetching mergable is async because ??? and fails rarely
=> Pin conflict labeler commit and increase timeout

code/controllers/subsystem/silo.dm, code/datums/jobs/job/job.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Adjusted some logic checking for `MODE_PSY_POINTS` that should now be checking for `MODE_PSY_POINTS_ROUNDSTART` since both Hunt and Distress Signal gamemodes use `MODE_PSY_POINTS` now, but only Distress has `MODE_PSY_POINTS_ROUNDSTART`
Closes: #6892
Mode breaking bugs bad. Fix good.
:cl:
fix: Fixed silos generating larva during Hunt.
/:cl:
=> Fix hunt/distress MODE_PSY_POINTS flag collision

code/_globalvars/lists/objects.dm, code/game/objects/structures/xeno.dm, code/game/turfs/turf.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm, code/modules/mob/living/carbon/xenomorph/facehuggers.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm, code/modules/projectiles/projectile.dm, code/modules/xenomorph/xeno_structures.dm
Standardizes xeno structures/buildable category for future changes.
Fixes structure stacking.
Resin pods no longer block buildings.
Standardizes xeno structures/buildable category for future changes.
Fixes structure stacking. Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/5869
Resin pods no longer block buildings; QOL.
:cl:
code: Standardizes xeno structures/buildables categories for future changes.
fix: Fixes xeno structure stacking.
qol: Resin pods no longer block buildings; QOL.
/:cl:
=> Improved Xeno Structure Placement

code/__HELPERS/game.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm
Fix small silo build fail message.
Fix `get_active_player_count()` proc only used for small silo checks and events checking for any `mob.stat` instead of not dead.
Not checking for alive players only is stinky.
Xenos saying "players" over hivemind when they can't build a silo is bad.
:cl:
fix: Fixed get active players alive_check.
spellcheck: Fixed OOC wording on small silo text when there are too many players.
/:cl:
=> Improve small silo active player count and notice

code/game/turfs/snow.dm
Melts snow when crossed by a charging charger.
Snow sucks. This adds a fun way for xenos to clear it.
:cl:
add: Crusher's and Bull's charges now double as snow plows!
/:cl:
=> Charging xenos now plow snow when at full steam

code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Remove the species check on xeno anti-human pull. Why was it there anyway?
Less synth combat, and less incentive for synths to be anywhere near xenos willingly.
:cl:
fix: Fixed synths being able to pull xenos.
/:cl:
=> Fix Synths being able to pull Xenos

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Resin Nodes no Longer Block Buildings
Resin Nodes no Longer Block Buildings; QoL improvement for placement with some minor balance implications.
:cl:
qol: Resin pods now actually no longer block most buildings.
/:cl:
=> Resin Nodes no Longer Block Buildings

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Evasion now fails as it should if the runner is targeted by flamethrower projectiles, or hasn't moved in the past 0.5 seconds.
Evasion now fails as it should if the runner is targeted by flamethrower projectiles, or hasn't moved in the past 0.5 seconds.
:cl:
fix: Evasion now fails as it should if the runner is targeted by flamethrower projectiles, or hasn't moved in the past 0.5 seconds.
/:cl:
=> Fixed Movement Bug With Evasion

code/modules/modular_armor/storage.dm
jaeger storage modules no longer slow you down
This is no longer necessary honestly, you don't need to be penalized for having a storage module and I did this with an entirely different expectation and belief that there'd be a wide variety of storage modules for you to pick, but then they literally never got expanded.
This doesn't need to exist anymore outside of extreme cases.
:cl:
balance: medical, general and engineering jaeger storage no longer slow you down at all, from 0.1.
/:cl:
=> jaeger storage modules no longer slow you down

code/controllers/subsystem/points.dm, code/game/objects/items/cocoon.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm
See CL
Xeno are getting too much psy points now, which lead to short games (when xeno kill a push, even if the push managed to kill pools, they will be able to produce so much silo behind that that it's game over)
This will make games longer, and give marines a second / third shot
:cl:
balance: Psy drain from 60 psy points to 40
balance: Cocoon now only works for 5 minutes, so it produces 80 points rather than 160 but is less risky to make
balance: Psy points generated from generators are reduced by 25%
/:cl:
=> Nerf psydrain, nerf generators psy points output, rebalance cocoon

code/__DEFINES/dcs/signals.dm, code/datums/keybinding/human.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/mob_helpers.dm, code/modules/projectiles/gun_helpers.dm, code/modules/projectiles/gun_system.dm
Title
Also moved the signal registering and handler for rail attachments to gun cause it makes more sense
:cl:
add: Keybinds for unloading gun and underrail attachments
/:cl:
=> Keybinds for unloading gun and underrail attachments

code/__DEFINES/mobs.dm, code/modules/reagents/reagents/toxin.dm
1. Transvitox: Each tick converts 0.25 * the number of cycles this toxin has been in the victim's body * 2x for each other Xeno chem in the victim's system burn damage to toxin.
2. Whenever its victim takes brute damage, Transvitox deals extra toxin damage to it if its current toxin doesn't exceed 180 toxin, equal to 10% of the damage dealt up to a maximum of 180 tox damage. This extra damage is doubled for each other Xeno chem in the victim's system.
Transvitox doesn't suck ass anymore.
:cl:
balance: Transvitox reworked: it now converts only burn damage to toxin, and whenever its victim takes brute damage, Transvitox deals extra toxin damage to it equal to a % of this damage. Toxin damage inflicted/converted in this way is capped at 180. Effect is enhanced for each other Xeno toxin in …
=> Transvitox No Longer Sucks

code/modules/mob/living/carbon/xenomorph/facehuggers.dm
1: Larval hugger passive activation time decreased from 4 seconds to 2 seconds.
2: Larval proximity activation time increased from 0.5 seconds to 0.75 seconds.
3: Slash hugger impact activation time decreased from 1.3 seconds to 0.5 seconds to reflect the fact that it's intended for use in direct aggression and it has the lowest impact of all the hugger types.
4: All other non-larval huggers had their impact activation time decreased from 1.3 seconds to 1 second, passive and jump activation time decreased from 2 seconds to 1.5 seconds.
Makes the Carrier great again (i.e. no longer shit).
:cl:
balance: Larval hugger passive activation time decreased from 4 seconds to 2 seconds.
balance: Larval proximity activation time increased from 0.5 seconds to 0.75 seconds.
balance: Slash hugger …
=> Facehugger Trigger Time Rebalance

code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Fix `COMSIG_MOVABLE_MOVED` and `COMSIG_ATOM_DIR_CHANGE` signal handler (and child procs) code that does direction comparison to check for changes interpreting one or more `null` directions as an actual change.
Fix good. Mitigated only by the fact plow charges move blocking mobs out of your way first once full on charging.
:cl:
balance: Body blocking xeno chargers while they are in CHARGE_BUILDINGUP phase no longer resets their momentum if they shuffle through you.
fix: Fixed some xeno charger movement signal handlers not checking for null directions.
/:cl:
=> Fix xeno charge steps resetting from null direction signals

code/modules/mob/living/blood.dm
Most probable reason why synth sometimes had blood loss
:cl:
fix: Should fix synth blood loss
/:cl:
=> Should fix synth blood loss

code/game/objects/structures/xeno.dm
Hugger traps can now explode normally.
Hugger traps can now explode normally.
:cl:
fix: Hugger traps can now explode normally.
/:cl:
=> Hugger Traps Can Now Explode

code/modules/projectiles/ammo_datums.dm, code/modules/reqs/supplypacks.dm
Blue fire price from 100 to 60
Blue fire delay from 3.5 seconds to 2 (like normal fire)
Blue fire is clearly not worth 100 points right now, so let's reduce the price.
Also reduce the fire delay to be the same as normal fire, as i don't see why a req item should not be a straight upgrade from its free counterpart
:cl:
balance: Blue fire price reduced to 60 from 100
balance: Blue fire firedelay reduced to 2 seconds (rather than 3.5)
/:cl:
=> Blue fire buff

code/__DEFINES/is_helpers.dm, code/controllers/subsystem/silo.dm, code/datums/gamemodes/crash.dm, code/datums/gamemodes/distress.dm, code/datums/gamemodes/hunt.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/mob/living/carbon/xenomorph/charge_crush.dm, code/modules/mob/living/carbon/xenomorph/hive_datum.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm, code/modules/xenomorph/xeno_structures.dm, tools/ci/check_grep.sh
Renames "/obj/structure/resin" typepath to "/obj/structure/xeno/resin" and adds xeno_structure_flags var in "/obj/structure/xeno". The flag is for bitflags I'm adding in #6979 
Adds a way to make general changes to xeno structures instead of having "xeno" and "resin" structures that don't come from the same place.
:cl:
code: changed xeno structures typepaths, adds xeno_structure_flags var
/:cl:
=> Renames xeno structure typepath

code/controllers/configuration/entries/game_options.dm, code/controllers/subsystem/ticker.dm, config/config.txt
Adds config values to override the respawn timers for both marines and xenomorphs which are read on the Ticker's Initialize.
MARINE_RESPAWN and XENO_RESPAWN are now config values that you can set to override the default respawn timers.
Hard-coded values are bad and this lets the values be changed globally without needing to be manually changed ingame.
:cl:
server: Two new config values for overriding the respawn timers of both marines and xenomorphs.
/:cl:
=> Adds the ability to override the default respawn timers via a config value

code/game/objects/items/storage/belt.dm
Does what the title says.
Also verifies there's actually something in the martini belt before attempting to access it because runtimes.
Bug fix good.
:cl:
fix: Martini Belts can no longer give you invalid 'fixme' items
/:cl:
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/6949
=> Fixes martini belts giving you a fixme sprite when you pull out the last round from a stack

code/modules/admin/verbs/datumvars.dm, code/modules/admin/view_variables/mark_datum.dm, tgmc.dme
I was testing stuff on local and wanted to proccall something with a marked thing, but mark no work. This annoyed me enough to fix it, so, here we go.
Also moves marking into its own file as a proc so it can be used in the future if someone bothers porting other vv stuff.
Admins being able to mark stuff is pretty neat.
:cl:
fix: Admins can now actually mark things via the varedit dropdown.
code: Moved marking into its own file as a proc for easier access in the future.
/:cl:
=> Fixes varedit marking

code/game/objects/machinery/miner.dm
A 3 second windup is needed to damage miners. This makes them more durable, and way more easy to defend against wraith or fast runners
Miner integrity system was never designed for wraith, so it was stupidly easy to kill miners with it witout taking any risks.
:cl:
balance: Miners now take time to disable
/:cl:
=> Miners are more durable

code/modules/xenomorph/xeno_structures.dm
The proc handling destruction called the part qdeling it before it actually sent the message. This moves the parent call to the end of the proc as is standard for destroy-related procs, fixing the message (and possibly some other stuff considering stuff generally doesn't like getting called after being qdeld)
Correct info about silo destruction is good.
:cl:
fix: Destroying a silo now shows the correct coordinates instead of X: 0 Y: 0
/:cl:
=> Fixes the silo destruction message

code/modules/mob/living/say.dm
Fixes a runtime caused by saying just "." or ":" trying to access the next non-existent character in the message for a department key.
Fix good.
:cl:
fix: Say verb get_key() no longer runtimes.
/:cl:
=> Fix say.dm index out of bounds

code/__DEFINES/is_helpers.dm, code/game/objects/items/weapons/blades.dm
The harvester blade didn't handle being clicked with an item that is not a container very well, resulting in runtimes. This fixes that.
runtimes bad.
:cl:
fix: Harvester Blades no longer runtime if clicked with things that aren't reagent containers.
/:cl:
=> Fixes a minor harvester blade related runtime

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Buffs Crusher a little, see changelog. Feel free to suggest different numbers or argue why unga do not deserve this in the comments.
Fixes a missing `updating_health` arg.
Brings Crest Toss friendly fire mechanics in line with that of Warriors displacements.
Removes and/or converts Crest Toss and Stomp stam damage to brute.
Some Stomp discussion: https://discord.com/channels/498569646014857217/504094319075131402/848408671897124865
Brings stomp back from the desolation of overnerfdom. It should not be something you just quickly get up and run away from. It can actually be used for melee range brawls and escapes from chasing harvesters.
Why is crest toss such high cooldown and plasma cost anyway? It is supposed to counter cade huggers last I checked. The stam damage is on its way to …
=> Improves Crushers abilities a little, removes stam damage

code/game/objects/effects/landmarks/corpsespawner.dm
Forgot to update their burst flag, so a destroyed silo left out some bodies that could be siloed again
:cl:
fix: Corpses spawned in silo in hunt cannot be siloed again
/:cl:
=> Corpses spawned in silo in hunt fix

code/game/objects/machinery/cloning/cloning.dm
Cloning vats no longer always use 30000 power each tick.
Active power usage for cloning vats is 30000
Idle power usage is now 3000
"Engineers, why is medbay dark?"
:cl:
fix: Cloning Vats use less power if not running
/:cl:
=> Cloning Vats have actual power state usage

code/modules/orbits/spaceship.dm
Fix:
```
Runtime in callback.dm, line 98: undefined proc or verb /obj/machinery/computer/navigation/priority announce(). 
proc name: Invoke (/datum/callback/proc/Invoke)
```
:cl:
fix: Fixed the orbital level change arrival message never being announced.
/:cl:
=> Fix orbital change priority message callback runtime

code/modules/mob/living/silicon/ai/freelook/eye.dm
One line fix to check for eyeobj existence.
Fix
:cl:
fix: AI can now recover from a camera blackout if it was looking at an escape shuttle, or anything else causes deletion.
/:cl:
=> Fix AI Eye permanent deletion if looking at an escape shuttle

code/game/objects/items/weapons/shields.dm
you no longer have hard melee armor with a shield and they make you a decent bit slower
shields are innanely good in modern tgmc and -5 damage off every slash in the game and then -50% is way too much considering losing one hand is no longer as much of a downside as it used to be
:cl:
balance: shields no longer have hard melee armor and slow you down a bit more
/:cl:
=> removes hard melee from shields and they make you slower

code/__DEFINES/dcs/signals.dm, code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/revolvers.dm
Makes regular revolver ammo only stagger and knockback if fired via a long barrel. Moves shake to Mateba which it did not have before.
Call it a reactionary kneejerk salt PR all you want, but the ocelot gimmick is getting real aggravating to fight despite the new downsides of backpack revolvers with the stamina buffs.
2 revolver hits = 1 slug of stagger but you can fire 3.5 slugs worth and just keep dropping and pulling out more "slug shooters" making it strictly better than a shotgun for stagger, knockback, slow, and shake effects.
Stagger is a literal meme so much so Queen is snowflake immune:
```dm
var/stagger_immune = FALSE
if(isxeno(carbon_victim))
var/mob/living/carbon/xenomorph/xeno_victim = victim
if(isxenoqueen(xeno_victim)) //Stagger too powerful vs the Queen, so she's immune. …
```
=> Rebalance Snub-nosed Revolvers

code/datums/jobs/job/other.dm, code/modules/mob/camera/imaginary_friend.dm
See title and changelog.
Makes figurative spoon feeding and hand holding easier.
:cl:
add: Added Runechat text to Imaginary Friends for them and their owners to see.
add: Added a Xeno Suit cosmetic for Imaginary Friends.
add: Added Darkness, Change Appearance, and HUD toggle verbs to Imaginary Friends.
qol: Imaginary Friends now continue to hear ghosts and other IFs while active.
fix: Fixed the Show/Hide ability button requiring two toggles to work the first time for Imaginary Friends.
fix: Fixed Imaginary Friends possibly being naked spatial agents and blocking clicks.
/:cl:
=> Add Runechat text to Imaginary Friends and other QoL

code/modules/shuttle/mini_dropship.dm, code/modules/shuttle/navigation_computer.dm
Title.
Makes the console slashing messages to the xeno a little clearer and follow the collective centric notice conventions.
Currently the ship stays in brazil if this happens. That is bad right?
:cl:
fix: Fixed Tadpole getting stuck in the air with a slashed console.
/:cl:
=> Make Tadpole land if the console is killed mid-air

code/__DEFINES/cooldowns.dm, code/__DEFINES/dcs/signals.dm, code/datums/components/shield.dm, code/game/objects/items/explosives/bombvest.dm, code/game/objects/items/weapons/shields.dm
Adds checks that *should* prevent anyone from using this silly combo.
It's either this, or deletion. Look on the bright side the sprite is still mostly visible from just one face.
Shield + vest is extra bad for 2 reasons:
1. Blocks the one face of the vest sprite that is easy to see.
2. Adds armor to a build that is supposed to be the definition of a glass cannon.
:cl:
balance: Shield now stops the bomb vest from exploding when equipped and up to 5 seconds after drop.
/:cl:
=> Kills shield vest combo

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/pistols.dm, code/modules/projectiles/magazines/pistols.dm
Removes scope attachment slot and reduces ammo max range.
No other *normal* pistol in the game allows you to attach full blown scopes to it. How did this even get past review? I heard it was a shitpost speedmerge.
Gun should be more specialized and situational, not the perfect tool for long range flame area denial. Flamer and miniflamer do exist, and this is only a *sidearm*.
Actually balance this uber utility weapon. Make people happy.
:cl:
balance: Plasma pistol no longer accepts scope attachments.
balance: Plasma pistol now has 7 range, not 40.
/:cl:
=> Balance plasma pistol

code/modules/keybindings/bindings_atom.dm, code/modules/mob/mob_movement.dm
Reverts tgstation/TerraGov-Marine-Corps#7073
This breaks movement, sometimes you will do two movements at once
=> Revert "Prevent SSinput from constantly requesting moving in-place"

code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/guns/shotguns.dm, code/modules/projectiles/guns/specialist.dm
Title.
Balance? All I know is Splinter told me to do it, and snipers are super annoying to fight with it.
:cl:
balance: TL-127, Mosin, and SVD sniper rifles no longer have aim-mode.
/:cl:
=> TL-127, Mosin, and SVD lose aim-mode

code/game/objects/machinery/floodlight.dm
Changes resistance flags for the colony floodlight switch to make it indestructible.
The colony floodlight switch is responsible for turning on/off the colony floodlights, and is irreplaceable. It can also be destroyed by xenos, (usually done at roundstart), rendering the floodlights permanently inoperable. This is clearly an oversight.
:cl:Terrariola
balance: Colony floodlight switches can no longer be destroyed by xenomorphs.
/:cl:
=> Xenomorphs can no longer destroy colony floodlight switches.

code/game/objects/machinery/vending/vending.dm, tgui/packages/tgui/interfaces/Vending.tsx
Stop encoding and decoding from breaking strings. Delete `adminscrub()` altogether next?
Items with special characters in names can be dispensed. Like the "S&W .357 revolver"
:cl:
fix: Fixed a problem with vendors refusing to vend items containing symbols in their name.
/:cl:
=> Fix Vendor product_name encoding issue

code/game/objects/effects/landmarks/itemspawner.dm
Removes spawn" maid itemspawner. It spawns blindfold, bunny ears and black skirt altogether.
We are a MRP server based on the lore of marines vs xenomorphs. Even with RP events here and there, I don't see a reason to keep these maid outfits especially with bunny ears, blindfold, black skirt that may potentially promote rule 8 violations(erotic, lewd rp). Unlike the bartender loadout which does have a reason sometimes to exist for the sake of RP events.
:cl: SpaceLove
del: Removed Maid outfit spawn command.
admin: Removes Admin ability to spawn maid loadout.
/:cl:
=> Removes maid spawn.

code/__DEFINES/dcs/signals.dm, code/controllers/subsystem/persistence.dm, code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/gun_attachables.dm, code/modules/projectiles/guns/revolvers.dm, code/modules/projectiles/magazines/revolvers.dm
Splits tp-44 ammo into its own type, and improves signal code, and more in changelog.
Better code.
Fixes: #5827
:cl:
refactor: Refactored some revolver ammo code for less signal headaches later.
fix: Fixed handfuls of loose .44 ammo breaking speed loaders.
fix: Fixed the .357 seasonal item ref and speed loader ammo type.
spellcheck: Removed an extra "That" from revolver ammo rejection notices.
/:cl:
=> Revolver ammo refactor, fix speed loader bug

code/game/objects/machinery/autolathe_datums.dm, code/game/objects/machinery/vending/marine_vending.dm, code/modules/reqs/supplypacks.dm
marines get 2 free autominers, 15 points for more
Autominers should not be effectively free.
:cl:
balance:autominers are only acquireable by req
/:cl:
=> autominers aren't acqureable by autolathe, req only

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Endure can now be used while staggered instead of Ravage.
Endure can now be used while staggered instead of Ravage.
:cl:
fix: Endure can now be used while staggered instead of Ravage.
/:cl:
=> Fixes Bug With Endure

code/game/objects/items/explosives/bombvest.dm
Title
Xenos are whining. Makes exploding harder.
:cl:
balance: Increases bombvest's timer to Two seconds
/:cl:
=> Increases Bombvests timer to Two seconds

code/modules/tgui/tgui_input_list.dm, tgui/packages/tgui/interfaces/ListInput.js
Port of https://github.com/tgstation/tgstation/pull/59668
Better tgui lists.
:cl: jupyterkat, Wayland-Smithy
qol: you can now press space or enter to select in tgui input lists
fix: tgui input lists no longer break when duplicate keys are passed
/:cl:
=> Port tgui input list improvements

code/modules/codex/entries/mobs_codex.dm, code/modules/mob/living/carbon/xenomorph/attack_alien.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm, code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm, code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm, code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm, code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm, code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm, code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm, code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm, code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm, code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm, code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm, code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm, code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm, code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm, code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/unit_tests/xeno_logical_scaling.dm
Clears out leftover tackle_damage entries in xeno caste datums from when tackling existed. 
:cl:
code: Cleared out old tackle values
/:cl:
=> Removes old tackle damage values

code/game/objects/machinery/vending/vending.dm
No money concerns for lighters. Nanotrasen trusts that no AI's will abuse this. Because they can't. Nothing powerful is behind money, just fluff.
Makes the AI more in control of a couple machines. Better fluff. 
They couldn't at all before.
:cl:
qol: The AI can now vend from MONEY restricted vendors.
/:cl:
=> The AI can now buy things.

code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
resin jelly has it's cooldown working, and sending double messages
broken cooldown bad, and getting two messages is annoying
:cl:
fix: fixed resin jelly not having proper cooldown and sending double messages when your hands are full
/:cl:
=> resin jelly ablities have proper cooldown and no longer send double messages when your hands are full

code/game/objects/machinery/squad_supply/supply_beacon.dm
Make it so the OB beacons always have squad or human name tied to them. Like  
`
Orbital beacon (Mandalore gaming)
`
Hopefully make it easier to avoid some friendly fire accidents.
:cl:
add: Added a new way to ID the beacons
/:cl:
=> Make it so the OB beacons always have squad or human name tied to them.

code/modules/projectiles/ammo_datums.dm
it doesn't need this anymore, it has a max range already
makes medium acid spit castes way less painful to play, dear god
:cl:
qol:acid spit with no puddle no longer stops where you click
/:cl:
=> medium acid spit no longer has AMMO_EXPLOSIVE

code/__DEFINES/misc.dm, code/game/objects/items/tools/shovel_tools.dm, code/game/turfs/turf.dm
Basalt, a thing similar to dirt, can now be dug up for sandbags and makeshift defenses
Its hard to tell just why we can not dig up basalt leading me to think it was a oversight to now allow it
:cl:
fix: Basalt should now be able to dig up for sandbags
/:cl:
=> Makes shovels able to dig up Basalt for sandbags

code/__DEFINES/dcs/signals.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm, code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
There's code in place for pouncing someone while stealthed, but it never got reached due to the relevant destealth signal firing at pounce start instead of end. It's more or less nothing (1 slowdown 3 stagger) since hunter already inherits runner's 2 second paralyze regardless of stealth.
Also cleans up some duplicate code (attacking out of stealth with harm and disarm intent is line for line identical) and some code that wouldn't be reached (once you unstealth via pounce you can't sneak attack).
Nerfs hunter stealth by making the five second cooldown start when you leave stealth instead of only having a cooldown when you first enter it and when you deactivate it manually, which was weird. Thoughts on this welcome, given its use and plasma cost I'm not sure the cooldown matters at all. …
=> Cleans up some code to do with hunter stealth and pouncing, stealth cd starts at exit

code/modules/codex/entries/weapons_codex.dm
Because a vertical grip doesn't actually reduce scatter chance by 100%. burst_scatter_mod is multiplied by burst size to determine additional scatter for non-semiauto fire.
Fixes #6522 
:cl:
spellcheck: Rephrased codex entries for attachments with burst scatter modifiers
/:cl:
=> Rephrases a codex entry to clarify attachment burst_scatter_mod

code/modules/power/cable.dm
Fixes `Runtime in atoms.dm, line 801: Attempted to add fingerprint without an action type.`
caused by
`the power cable (/obj/structure/cable): handlecable(the T-18 carbine (Wielded), ...)`
Add the missing type arg and stop it calling when guns whack it.
Fix good.
:cl:
fix: Fixed an issue with add_fingerprint and power cables.
/:cl:
=> Fix an issue with add_fingerprint and power cables

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
removes a random beach tile where it shouldn't be on prison station
muh immursons
:cl:
fix: a rogue beach tile on prison station have been captured and sent to centcom for study
/:cl:
=> Fixes rogue beach tile on Prison Station

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
- Cameras added to south maintenance, east maintenance, in the captain toilet and in the preps.
- Moved some ugly cameras in the preps.
- Added a few lights as well
Some areas were invisible for no good reason, and some cameras were floating in the air. This fixes some of this.
:cl:
add: Added extra cameras & lights to Pillar of Spring
fix: fixed a few cameras placement
/:cl:
=> Upgrades camera visibility, placement and lights

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Fixes Defiler Emit Gas so That Last Puff is Actually Larger as Intended.
Despite the obvious intent of the comments, the smoke size is always rounded down, so the last puff never achieves the intended increment in size.
Fixes Defiler Emit Gas so That Last Puff is Actually Larger as Intended; bug fix.
:cl:
fix: Emit Noxious Gas's last puff is now larger as previously intended.
/:cl:
=> Fixes Defiler Emit Gas so That Last Puff is Actually Larger as Intended

code/__DEFINES/cooldowns.dm, code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
See changelog.
Doors are weak and needing to wait to close them as hivemind is just garbage. Will not make doors "over powered" for trapping marines (unless they are dumb enough to rush past a ton of open ones anyway), and just gives them an extra incentive to blow up or burn doors before crossing or hunt down the hivemind dedicating its time to playing antimov AI with doors.
:cl:
balance: Hivemind resin door manipulation cooldown is gone.
qol: Hivemind can now open and close doors with Ctrl+Click as well as Alt+Click.
fix: Fixed a duplicate proc override for /xenomorph/hivemind/
/:cl:
=> Hivemind door open cooldown gets the axe

code/modules/mob/living/carbon/xenomorph/update_icons.dm
Fix a runtime that happened when xeno were gibbed, and still tried to update wound overlay
=> Fix runtime when xeno are gibbed

code/modules/xenomorph/xeno_structures.dm
A side effect of #7015 moving the call to before the qdel looks like.
Delay the `handle_silo_death_timer()` code for 1 tick so the silo can actually be deleted before it checks for any existing silos.
Fixes: #7203
:cl:
fix: Fixes the silo collapse timer.
/:cl:
=> Fix silo collapse timer

code/game/objects/machinery/vending/new_marine_vendors.dm
medic can no longer buy it
this was massive powercreep, it should die in a hole
:cl:
balance: medic can no longer buy the combat backpack in their point vendor.
/:cl:
=> deletes medic being able to buy the combat backpack

code/modules/projectiles/guns/revolvers.dm
Inverts the mag type handful check to a speedloader check instead of assuming all non handfuls are speedloaders.
Ammo packet should not act as a giant speedloader.
:cl:
fix: Fixed revolver reload logic.
/:cl:
=> Fix revolver reload logic

code/game/objects/machinery/squad_supply/supply_beacon.dm
Adds a check for `/area/shuttle/dropship` when activating because just checking the z level is not enough it seems when that can change by going groundside. An alternate solution is to have them auto de-activate in an `onShuttleMove()` override.
OB beacons are meant to be used "on the planet" and as such the only way to get one planted on the Alamo is to fly it groundside first then attempt to plant a beacon, however that beacon stays activated even after hijack for funny dropship OB memes. This change rectifies that.
:cl:
fix: Fixed OB beacons being activatable on dropships.
/:cl:
=> Fix OB beacons being activatable on dropships like Alamo

code/game/objects/structures/fence.dm
Those map start broken fences are now less horrible. How are they bad?
Despite making only of rods, they could not be shot past... Why? No idea... Likely a oversight, this has now been corrected!
Bombs are less likely to end fences life
Fences now have a bit more HP to reflect on that they are used
Also shocking fences even tho they are made out of rods, the same ones that make grills had no armor.
Thus giving them a small bit of armor similar to grills would help make them ever more consistent 
Ups the amout of rods needed to 4 as thats how many the sprite has
No one ever fixes these and for good reason, they harm everyone by blocking fire, taking metal and being unmovable.
If there is ever, EVER a reason repair them its for looks as they are right now as a xeno can safely without being …
=> Improves fences

code/modules/projectiles/gun_system.dm
Synths won't use underbarrel attachments.
No more will synths be able to fire an underbarrel flamer or underbarrel grenade launcher. 
Fixes #7016
Combat synth goes in the bin. 
:cl:
fix: No more underbarrel guns for synthetics. 
/:cl:
=> Synths don't get guns.

code/__DEFINES/mobs.dm, code/datums/actions/xeno_action.dm, code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
1. Debuff stacks from the Wraith's warp field are increased; 2 stagger stacks up from 1, and 3 slowdown stacks up from 1.
2. Banish cooldown and plasma cost decreased for friendly living targets and non-barricade targets to 60% and 40% respectively.
3. Fixes bug with Phase Shift toggling off consuming its baseline plasma cost.
4. Hyperposition windup will increase by 0.25 seconds per tile after 20 tiles of distance down from 0.5 seconds per tile after 10 tiles of distance.
5. Using Resync while phased out (reverting to your prior location at the start of the Phase Shift) mostly removes the next cooldown for Phase Shift, reducing it to 3 seconds.
Makes Wraith a little easier to use and more impactful at lower skill levels.
Allows Wraith to use Banish more readily for utility purposes.
:cl: …
=> Wraith Buffs

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm, code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Xenos from the same hive as the one that drops or throws a Facehugger no longer reset that Facehugger's jump timer when they leave its tile.
Xenos from the same hive as the one that drops or throws a Facehugger no longer reset that Facehugger's jump timer when they leave its tile.
:cl:
code: Xenos from the same hive as the one that drops or throws a Facehugger no longer reset that Facehugger's jump timer when they leave its tile.
/:cl:
=> Improved Anti-Shuffle Hug so Carrier Allies Don't Reset Jump Timers

code/game/objects/machinery/camera/camera.dm, code/game/objects/machinery/camera/deployable_camera.dm, code/game/objects/structures/orbital_cannon.dm, code/modules/mob/living/silicon/ai/ai.dm, code/modules/shuttle/computer.dm, code/modules/shuttle/marine_dropship.dm
If you check the 'Game' tab, you can now see :
- Orbital level
- Orbital canon status
-  Alert level
Maybe in the future:
- Supply points
- Active miners ?
- Active marines ?
- Status of Alamo, Tadpole & Condor ?
Relative to the notifications :
- Add a notice when a camera goes offline
- Add a notice when the railgun fires
- Add a notice when the Alamo takes off.
It drives the feeling of the AI being a more aware presence, just like someone who is literally wired into the ship.
On a more straight forward level, all of this info is already presented on other consoles. 
It mostly saves on having to constantly open this damn camera list to find the weapons room or CIC.
Pretty happy with this ngl!
:cl:
add: Added notifications to the AI whenever the Alamo moves, the railgun is fired, the OB …
=> Add a suite of notices and information to the AI

code/modules/power/fusion_engine.dm
Turn it on and off. Basic.
They can't fuel it, so this isn't particularly breaking anything.
Quality of life, especially when the only engineer is dead or SSD.
:cl:
qol: The AI can now turn fusion reactors on and off.
/:cl:
=> Allow the AI to turn fusion reactors on and off.

code/game/objects/structures/fence.dm
Title.
Dovetails nicely with the recent fence health buff since they are even more annoying to clear out before shutters now.
Makes xeno prep less unfun.
:cl:
qol: Some groundmap fences start broken, so xenos do not need to slash them all to get around during prep.
/:cl:
=> Randomly break groundmap fence lines at round start

code/datums/actions/item_action.dm, code/modules/projectiles/gun_attachables.dm
Fixes the Hydro Cannon
Fixes the hydro cannon hud button. Now you can actually activate the hydro cannon by clicking the hud button. It also removes ATTACH_ACTIVATION from the hydro cannon, so the load from attachment verb will no longer toggle the hydro cannon. Unique action and the hud button will now be the only ways to toggle it, but I'm assuming people defaulted to unique action anyways. 
Fixes #6695 
It just works. That's really it, the hud button didn't work before and now it does. 
:cl:
fix: Fixed Hydro Cannon hud button.
refactor: Hydro Cannon only works via unique action and hud button, not load from attachment.
/:cl:
=> Hydro Cannon Fix

code/game/objects/structures/dropship_equipment.dm
This makes the condor radial gun not printable anymore. 
Fixes #6996 
Now nobody will print it and find themselves with an unmovable gun that wasted 400 dropship points. 
:cl:
fix: Condor Radial Minigun no longer printable. 
/:cl:
=> Condor Minigun Fix

code/game/objects/items/reagent_containers/food/snacks.dm, code/modules/projectiles/gun_attachables.dm
Makes pizza sliceably by sharp objects and not sliceable by objects that aren't sharp. Also makes attachables add their sharpness to the gun when attached. The only attachables with sharpness that isn't 0 are bayonets, so this makes a bayoneted gun able to slice pizza.
Makes pizza sliceable and adds a new attachment stat change. Basically attachments will now transfer their sharp to the gun when attached and remove it when taken off. So you can slice pizza with a gun if it has a bayonet on. 
Pizza will now be sliceable. 
:cl:
add: Attachments now transfer their sharp to the gun. 
fix: Pizza and other foods are now sliceable. 
/:cl:
=> Makes Pizza Sliceable

code/game/objects/items/tools/flame_tools.dm
Increases the transquantity of the base cigarette so that chems will transfer at a functional rate. Before this the rate was so slow that if you put say, a single healing chem in the cigarette's 30u limit which is already half filled by nicotine, it would transfer 0.05 of each reagent per tick and thus do nothing. With transquantity at 1 it transfers 0.5u per tick of nicotine and 0.5u of whatever chem or mix of chems you add to take up the other half of the cigarette's chem volume. 
Fixes #6372 
It makes it so you can put chems into a regular cigarette via dipping it in a bottle or injecting it and have them properly transfer to you when smoking it. 
:cl:
fix: Non-Chemrette cigarettes now transfer chems properly. 
/:cl:
=> Cigarette Chem Fix. 

code/game/objects/machinery/doors/airlock_types.dm
Fixes PoS research Pen doors, which was broken by a certain pr
Bruh
:cl:
fix: PoS research doors should now be accessible.
/:cl:
=> Fixes PoS research doors

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Title.
Being number 1 in the larva queue ready to spawn with no silos and watching 5 xenos spawn in from the lobby is bad.
:cl:
qol: Observers can spawn from the larva queue without silos before shutters open on Distress rounds.
/:cl:
=> Fix observers being locked out of pre-shutter larva on Distress rounds

code/game/objects/structures/window_frame.dm
Annoying guessing game of is there a frame there or not goes away. (except if badmins del windows)
:cl:
fix: Fixed window weeds not updating after the frame is gone.
/:cl:
=> Fix window weeds not updating after the frame is gone [UTMOST PRIORITY]

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Fixes hiveminds getting immediate respawns on core destruction. Ghostize wasn't properly setting the respawn timer, but DEATH does. And so death they get. 
Fixes #4653
It fixes an unintended behavior. 
:cl:
fix: Hiveminds don't get fast respawns from dying. 
/:cl:
=> Hivemind respawn fix

code/modules/surgery/implant.dm
Lets you pull shrapnel out of head/chest surgically without opening the bone, you just need to cut/retract or use an incision manager.
There's basically no reason to not just use tweezers and slap in some bic right now, and if you could reach the pieces with tweezers they probably aren't inside the ribcage. With this surgery should be the better option any time you're opening the limb anyway (chest, typically) or there's multiple pieces of shrapnel.
:cl:
qol: You don't need to open the bone to remove shrapnel from head/chest
/:cl:
=> Simplifies surgical shrapnel removal on head/chest

code/modules/modular_armor/helmets.dm
Welding helmet modules currently remove eye protection when toggled on instead of adding it. 
Makes the welding helmet module provide eye protection. 
:cl:
fix: Welding helmet module protects eyes properly. 
/:cl:
=> Fix for welding helmet module

code/__DEFINES/mobs.dm
Ravagers had acid blood because the CASTE_INNATE_PLASMA_REGEN define had the same number as the CASTE_ACID_BLOOD define. 
Nothing but boilers is supposed to have acid blood. 
:cl:
fix: Ravagers have normal blood now. 
/:cl:
=> Acid blood bugfix

code/modules/clothing/glasses/meson.dm
Mesons no longer give a modified lighting plane alpha. They still reveal turfs that are lit up or within your light radius, but won't work as some weird night vision analogue. 
No more funni meson stuff. An alternative to #7306 
:cl:
balance: Mesons dont hide darkness slightly anymore, removing a effect that on diagonals each light  showed xenos 2/3 tiles away
/:cl:
=> Mesons no longer reveal a lighting plane.

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
warrior can fling you literally across slightly more than half a screen with a malleable grab compared to fling itself which requires much more careful coordination and grabbing for a shittier overall ability (fling itself stuns for less time I think too)
This gives you a reason to fling instead of tossing on a grapple considering warriors bread and butter is lunge anyway, so I don't see the need for it to be better than fling in about every aspect outside of rare situations where you're caught with lunge on cooldown.
Also 5 tiles is way too much when comboed which lets you literally throw marines 10 tiles away.
Warrior grapple toss throws you way too many tiles away. Three is more fair and slightly less frustrating to deal with than five.
:cl:
balance: warrior grapple toss distance …
=> warrior fling distance on grapple toss reduced to 3 from 5

code/game/objects/structures/crates_lockers/closets.dm
Adds checks to stuffing things into closet so ghosts/hiveminds can't do it. 
No more ghost bullying. The hivemind bit is to be thorough since testing indicated they could do it. 
:cl:
fix: The veil has been pushed back closed. Ghosts can no longer interact with the living. 
/:cl:
=> Closet based ghost bullying fix

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/specialist.dm
railgun loses 100 damage to put it in line with it's general damage range
knocks you back a tile further and doesn't shake your screen
750ms more wield delay
mag-h instead of scope so you can't snipe people 14 tiles away to gib them
250 is way too much, 150 is more fair
:cl:
balance: railgun lost 100 damage from 250 to 150, knocks back further and no longer shakes the screen when you're hit, 750ms more wield delay, mag harness instead of scope
/:cl:
=> railgun rebalance- less damage/stagger, mag-h instead of scope, more wield delay

code/game/objects/effects/landmarks/landmarks.dm
Basically this just removes the thermobaric XMAS launcher from the weapon spawn list in the tier 5 weapon spawner landmark. It removes the 50% chance of a thermobaric that spawns in EORD being impossible to reload. 
Because this way we won't get people mhelping during EORD asking why their thermo won't reload. 
:cl:
fix: EORD thermobarics can be reloaded reliably.
/:cl:
=> Fixes unreloadable EORD Thermobaric

code/modules/mob/living/carbon/xenomorph/damage_procs.dm
The two checks being removed in this were what was preventing dead xenos from being ahealed properly. This will not allow you to stack damage on dead xenos, because there's already a check for if a xeno is dead in the take damage proc that stops things from moving on to adjustBruteLoss or adjustFireLoss. 
Fixes #7348 
Allows admins to heal dead xenos without having to resort to transforming them into the same caste and then re-upgrade them. 
:cl:
fix: Admins can aheal dead xenos again.
/:cl:
=> Fixes ahealing dead xenos

code/modules/keybindings/bindings_client.dm
Allow to use é, è, etc. in keybinds. Works for french keyboard, probably will be usefull for spanish or italian one as well.
I'd rather have a TM before merge, this may (though it's unlikely) break some keybinds in standard QWERTY keyboards. I doubt, but better be safe than sorry
I unlock one more keybind for myself. 
:cl:
qol: You can use é and è as a keybind
/:cl:
=> Fix é keybind[DNM]

code/modules/modular_armor/helmets.dm
This just removes the noise from this module. You can spam it, but only your own feed will get filled.
Spammers suck, and the noise is too distinct for a cooldown to really make it less annoying.
:cl:
qol: disable antenna module beeping due to spam.
/:cl:
=> Disable the antena module beeping to cull spam.

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
New : 
Old : 
This fixes a weird hole in the area thing
:cl:
fix: fixed a messy area on the POS hangar, extended the fire shutters to match. 
/:cl:
=> Switch around the POS hangar areas so the fire alarms don't abruptly stop in the middle of an hallway.

code/modules/reagents/machinery/chem_master.dm
Adds a prompt to the chem master when you dispense a pill bottle to let you name it, the way you can with pills and injectors.
Using the hand labeler afterwards is annoying.
:cl:
add: You can name pill bottles when you dispense them from a chem master
/:cl:
=> Lets you name pill bottles

code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Nerfs jelly to 20 seconds of cd from 5
Considering from pods you can already make jelly, and jelly in general has a 15 second duration (and is an item that never goes away) having it have an actual cooldown beyond the amount of plasma it uses makes a decent level of sense.
Jelly should have a cooldown that matters so you can't basically infinitely keep someone with fireproofing for basically ever. Which is pretty dumb in of itself. This only gives it 5 seconds of effective CD.
:cl:
balance: spawn jelly has 20 seconds of cooldown from 5
/:cl:
=> nerfs jelly to 20 seconds from 5

code/game/objects/machinery/vending/marine_vending.dm
can't refill them, too good
too good for basically making ib and organ damage irrelevant. spend more points if you want more
:cl:
balance: can't refill qc+ and peri + at marine med
/:cl:
=> you can't refill qc+ and peri+ at marine med

code/modules/clothing/glasses/night.dm, code/modules/reqs/supplypacks.dm
An alternative to mesons. Req only. Name, price and icon are open to discussion.
I really like the pseudo nightvision properties of meson but it seems others disagree for various reasons. Now its a req item with nothing but the light alpha adjustment. I believe this is a much better alternative than adding night vision to marines and should stay in the game.
A terribly cropped image for clarity.
This PR is intended to be implemented with either #7306 or #7307
:cl:
expansion: Added meson-like goggles to req
/:cl:
=> Imager Goggles

code/game/objects/items/storage/boxes.dm
It wasn't named right, so it was showing up as M15 grenade box in the operational vendor. 
Now it will be named right. 
:cl:
fix: Impact Grenade Box Vends Properly. 
/:cl:
=> Proper Impact Grenade Box Name

code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm, code/modules/mob/living/carbon/xenomorph/life.dm
All xeno healing aside from hivelord laser calculates an amount to heal and then applies that separately to both brute and burn damage. This makes it apply as much as possible to brute, and then the remainder to burn.
Also increases base healing by 25% to compensate, requested by lewdcifer.
Fixes #7344 
Moderate nerf to xeno sustain against any split damage, usually from grenades or one dude in a crowd with a flamethrower. Might be worth bumping up heal numbers depending on how it pans out.
:cl:
fix: Xeno healing now splits properly between brute and burn instead of doubling, base healing increased 25% to compensate
/:cl:
=> Removes double healing from most xeno sources

code/game/turfs/walls/resin.dm
nobody ever updated this, daels 600, which iirc is the max hp a resin wall can have.
kinda silly they can survive these.
:cl:
fix: resin walls now die to devastating explosions such as OBs, and other things
balance: resin walls now die to devastating explosions. Which include HE OBs.
/:cl:
=> full health resin walls now die to devastating explosions

code/datums/elements/plasma_on_attack.dm, code/datums/elements/plasma_on_attacked.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm, tgmc.dme
Ravager now gets fury when attacked, 50% of the damage received and their passive regen is severely reduced
This makes ravager less do nothing against suppression, making them able to reciprocate while we reduce its plasma regen so they dont regen quickly around without being actively in combat.
:cl:
expansion: Ravager now also gets fury on receiving damage.
balance: Ravager Passive fury regen has been severely reduced.
/:cl:
=> Ravager gains fury when damaged and passive regen reduced.

code/modules/reagents/reagents/toxin.dm
1. Hemodile no longer deals stamina damage.
2. Hemodile base slowdown increased from 1 to 1.5.
3. Hemodile slowdown is multiplied by 2 for each other Xeno chem in the victim's system (Neurotoxin and Transvitox).
Makes Hemodile worth a shit.
Adds interesting synergies with other Xeno chems and castes.
:cl:
balance: Hemodile no longer deals stamina damage.
balance: Hemodile base slowdown increased from 1 to 1.5.
balance: Hemodile slowdown is multiplied by 2 for each other Xeno chem in the victim's system (Neurotoxin and Transvitox).
/:cl:
=> Hemodile Buff

code/game/objects/machinery/vending/marine_vending.dm
Title.
:cl:
fix: Impact grenades are actually in normal vendors, not HvH one
/:cl:
=> Fix impact grenades being in HvH vendor only

code/__DEFINES/mode.dm
Distress right now for half of the round is literally as bad as hunt is in terms of having no concrete objective for the marines to focus on, and so the xenomorphs are encouraged to not even place a silo at all.
While this stops instant SILO RUSH B this makes it so xenomorphs aleast have to place a silo into a decent portion of the round (Considering most rounds start around at 12:25, it should be atleast be 25 minutes or so before you NEED a silo, rather than 40 minutes.)
Makes distress more of a objective based game mode rather than just a meme tdm until an hour into the round
:cl:
balance: silo collaspe takes 45 minutes from roundstart to begin happening, rather than an hour
/:cl:
=> Siloless collaspe is at 45 mintues into a round rather than an hour

code/controllers/subsystem/persistence.dm, code/modules/projectiles/guns/revolvers.dm, code/modules/projectiles/guns/smgs.dm
UZI is built to be used one handed and akimbo, use it to your hearts content. Renamed from GAL-9 since gal-9 sounds dumb, renamed to MP-2
CMB is tp-44 fire rate considering it's an autorevolver and fires revolver/small so it does less damage, also has a 2 round burst mode if you want to get cool or something.
Adds new bucket and makes shitty old guns viable again.
:cl:
expansion: new seasonal bucket with uzi and cmb revolver
balance: cmb now has tp-44 fire rate, now has a 2 round burst with 0.1 fire delay. Uzi buffed to fire as fast as normal smgs and is built for one handed use.
/:cl:
=> adds a new bucket with an uzi and cmb revolver, and buffs and restats them

code/modules/projectiles/projectile.dm
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7309
:cl:
fix: Fix projectile double tap
/:cl:
=> Fix projectile double tap

code/_onclick/click.dm, code/_onclick/xeno.dm
Fixes Right Click mode for Xenos so that it doesn't try to auto-attack at the same time it uses an ability (thus triggering bump slash cooldowns).
Also stops turf targeting with melee attacks from triggering bump slash cooldowns.
Fixes Right Click mode for Xenos so that it doesn't try to auto-attack at the same time it uses an ability (thus triggering bump slash cooldowns). This will allow things like the Wraith's Blink to be used much more fluidly with bump attacks and slashes in general.
Also stops turf targeting with melee attacks from triggering bump slash cooldowns.
:cl:
fix: Fixes Right Click mode for Xenos so that it doesn't try to attack at the same time it uses an ability (thus triggering click/bump slash cooldowns).
fix: Turf targeting with melee attacks no longer triggers …
=> Fixes Right Click Mode for Xenos

code/modules/organs/limbs.dm
Properly clears flags when a limb is removed. This doesn't change behavior at all since nothing a broken limb can do happens if it's destroyed. Also the bleeding flag cleared instantly anyway since a destroyed limb has no wounds.
It annoys me seeing untreatable breaks on med scanners even if they don't do anything. 
:cl:
fix: If your arm gets torn off, it isn't broken any more.
/:cl:
=> Fixes destroyed limbs also being broken

_maps/map_files/LV624/LV624.dmm
Just a missing switch which seems to have been forgotten in map change.
:cl:
fix: fixed a missing floodlight in LV engineering
/:cl:
=> Add a missing floodlight switch to LV engineering

code/game/objects/machinery/camera/camera.dm
Some cameras weren't giving some undeserved info in powerless areas.
:cl:
fix: fixed cameras notifying the AI of their demise, despite a lack of power.
/:cl:
=> Make it so cameras check for power before notifying the AI

code/modules/admin/panels/game_panel.dm
Just a bit of QoL.
:cl:
admin: expand the quick create paths
/:cl:
=> Add more paths to quick create for admins.

code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm, code/modules/mob/living/carbon/xenomorph/life.dm
Xeno's main healing proc gets an additive bonus based on recovery pheromone strength. Since it's additive, it should've been increased by 25% in #7377 but I missed it. Whoops.
Minor fix on a merged pr, also updated comments.
:cl:
fix: The recent 25% boost to xeno healing now also includes the gain from recovery pheromones
/:cl:
=> Fix two values I forgot to adjust during the xeno heal change

code/modules/mob/living/carbon/human/human_damage.dm
Human's heal_limb_damage proc doesn't correctly pass its named args to the limb's heal_limb_damage proc, this fixes that.
Bug fix.
The only place that currently uses the proc in question is medical cryotubes, which as a result of this won't fix broken bones any more. Previously they did from the tube's passive healing, regardless of the installed cryo mix.
:cl:
fix: Cryotubes no longer fix broken bones due to incorrect argument passing
/:cl:
=> Fixes limb heal argument passing

code/game/objects/effects/effect_system/smoke.dm, code/game/objects/structures/xeno.dm, code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm, code/modules/mob/living/carbon/xenomorph/facehuggers.dm, code/modules/reagents/reagents/toxin.dm
Adds the ability for defilers to inject hemodile and transvitox into eggs for later popping.
Aliens opening gas eggs manually is now intentional instead of a failure to retrieve the hugger.
Fixed a runtime with egg huggers trying to clear their source when they don't have one.
Adjusted transvitox to not mention your wounds crusting over when you do not in fact have any wounds.
Further develops a relatively unused piece of defiler's kit without necessarily adding much new power (neuro is probably still just better than the other two most of the time). 
Bug fixes.
:cl:
add: Defilers can inject hemo and transvit into eggs now if they want.
fix: Injected eggs don't have to grow up a second time
/:cl:
=> Lets defilers inject other gasses into eggs, cleans up gas eggs

code/modules/projectiles/gun_system.dm
Xenos can now attack floor guns to turn off the rail light if there is one.
Tired of infinite pocket pistols lying around providing light forever until one of the castes with acid clears it. If you want lights to leave around as a marine bring flares.
Closes #7438 
:cl:
add: Slashing guns as a xeno will turn any lights on them off
/:cl:
=> Lets xenos turn off rail flashlights by slashing the gun

code/game/objects/items/defibrillator.dm, code/modules/mob/living/carbon/xenomorph/embryo.dm
Makes larvae start processing again on host defib. Defibber gets a direct warning that their patient has an embryo.
Currently, if you die and get ressed with an embryo it'll stay at its current state of growth and never progress, making you immune to larval facehuggers forever. This's bad. The other options were either destroying the embryo on any death, which's bad because murder should not be a medical treatment, and letting growth continue through death, which seemed just a bit too much.
:cl:
fix: Larva now start growing again if their host stops being dead.
/:cl:
=> Larva now start growing again if the mob they're in is defibbed

code/datums/jobs/job/shipside.dm
Basically the title. The comment next to the CSE rank time for O-4 is now accurate to the actual time, 100h. 
Clarity and giving proper information. 
:cl:
spellcheck: CSE rank time now properly lists 100 hours instead of 50 hours. 
/:cl:
=> Adjusts comment next to CSE rank time to be accurate

code/_globalvars/lists/objects.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/xenomorph/xeno_structures.dm
Basically this just adds a minimum distance between xeno turrets, to make it so they can't place them too close to one another. It works like the silo minimum distance but with a shorter distance. In this case, the minimum distance between turrets is 6 tiles. 
Prevents the spamming of large amounts of turrets in a small area. 
:cl:
balance: Xeno turrets can't be built too close to each other. 
/:cl:
=> Xeno Turret Minimum Distance

code/__DEFINES/qdel.dm, code/__DEFINES/time.dm, code/__HELPERS/_logging.dm, code/_compile_options.dm, code/controllers/configuration/entries/general.dm, code/controllers/subsystem/garbage.dm, code/datums/datum.dm, code/game/world.dm, code/modules/admin/debug_verbs.dm, code/modules/admin/holder.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/datumvars.dm, code/modules/admin/view_variables/reference_tracking.dm, config/config.txt
This port some improvement on how to handle hard del from tg
https://github.com/tgstation/tgstation/pull/56724 : this was already ported in part, i'm adding the rest here
https://github.com/tgstation/tgstation/pull/57728 : this is better ref tracking. I'm not adding the unit test from this
https://github.com/tgstation/tgstation/pull/58972 : fixed some bugs of the hard del traker
https://github.com/tgstation/tgstation/pull/59371 : this optimized the ref tracker
This needs config update and probably LAA
https://github.com/tgstation/tgstation/pull/59750 : if the same type hard del too much, hard dels on that specific type will be disabled.
=> Hard del tracking, disabling and handling changes

code/modules/projectiles/gun_system.dm
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7435
:cl:
fix: Rail flashlight can be shut down by nightfall
/:cl:
=> Rail flashlight can be shut down by nightfall

code/modules/projectiles/guns/rifles.dm
This PR allows the T-64 to attach an angled grip. That's it.
The T-64 sits in a weird spot between a marksman rifle and an assault rifle and sees very little use in comparison to its peers. Due to the fact the T-37 can equip an angled grip while the T-64 couldn't made the slower, more damaging T-37 actually faster to wield. Hopefully with this PR it will bring the weapon more in line with being a mid-ground between AR and DMR.
:cl: Joniroq
balance: T-64 battle rifle can now have an angled grip.
/:cl:
=> Tweaks for the T-64 Battle Rifle

_maps/shuttles/triumph.dmm, code/game/objects/items/radio/intercom.dm
Adds a new intercom type for the rebel dropship the Triumph and replaces the Alamo dropship intercoms that are currently on it with the Triumph intercoms. It uses the previously unused Normandy intercom frequency. 
Makes the intercom match the dropship. 
:cl:
fix: Triumph shuttle has appropriate intercoms.
/:cl:
=> Triumph Intercoms

code/modules/admin/panels/game_panel.dm
Ammo and equipment added
Easier testing, easier admining
:cl:
admin: Added dropship equipement to the quick create menu
/:cl:
=> Added dropship equipement to the quick create menu

code/game/objects/machinery/mortar.dm
Z  = good
QoL 
:cl:
qol: You can now use Z to activate your mortar. Simple QOL.
/:cl:
=> Make it possible to put down the mortar using the activate hotkey

code/modules/projectiles/guns/rifles.dm
addds tl-127 aim mode
2.35 seconds per shot in aimmode, compared to the old like 1.9
undeltes the tl-127, which is literally probably the worst gun in the game (that you can get from a marine vendor, CONSISTENTLY, I'd argue some seasonals are worse than it.), considering the mosin isliterally just better in every way conceiveable and the DMR has aim mode AND fires faster and has better situational usage in most scenarios
:cl:
balance: tl has aim mode
/:cl:
=> readds tl-127 aim mode

code/_onclick/ai.dm, code/game/objects/machinery/doors/airlock.dm, code/game/objects/machinery/doors/airlock_types.dm
Title. It was removed cause ai could lock them to prevent hijack, but you can't interact with doors on grounds, so it's fine.
Remove locking shuttle doors for ai by ctrl clicking
Also clean some src.vars
Usefull for droids, so they can actually leave the shuttle when controlled by the ai
:cl:
qol: Ai can manipuate shuttle doors even groundside, but won't be able to lock them (unless it uses the console)
/:cl:
=> Ai can manipulate shuttle doors

code/modules/modular_armor/attachables.dm
This nerfs Hlin down to about 90% bomb armor with a full suit, so you can self talk about ten grenades instead of.... an infinite amount due to having literal explosive immunity. #7115 was closed for being too drastic at nerfing it to 80% bomb armor, so this compromises between full immunity and a heavy nerf to put it at 90%. 
Hlin, GL, shield is an incredibly strong combo, but even just Hlin and constant GL spam is really, really strong and incredibly annoying to go against. Hlin will still be good and have a niche for GL users, but having literal full immunity is, in my opinion and the opinion of quite a few others, way too strong. 90% reduction is still very good and nothing to scoff at. Being able to tank about ten grenades before going into crit is still very useful for someone …
=> nerfs hlin to more acceptable armor levels

code/modules/projectiles/gun_attachables.dm
Adds nightvision to the antimaterial rifle's scope. 
Makes it a bit less of a hassle to use the comparatively more expensive antimat sniper rifle. Plus this way it will be more of an upgrade compared to the IFF sniper.  The 2.5 second fire delay compared to the IFF sniper's 1.75 second, same damage with the only benefit being more sunder and the laser. The laser which loses its targeting under a stiff breeze and can see an unmoving xeno be targeted and then lose the targeting with it still not having moved. So, NV scope. 
:cl:
balance: Antimaterial rifle has an NV scope now. 
/:cl:
=> Antimaterial Rifle NV Scope

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Fixes this issue : https://github.com/tgstation/TerraGov-Marine-Corps/issues/7500
:cl:
fix: fixed a misplaced poster.
/:cl:
=> Fix the poster bulging downward. As it turns out, there is a weird thing with the direction giving out a pixel offset.

code/datums/jobs/job/shipside.dm
SO now starts at O-3, goes to O-4 at 25 hours, and O-5 at 50 hours. Basically just adds another rank to make them a three rank role instead of their awkward and un-needed position as one of the only two rank roles. Also it's a four slot role so starting them off at O-3 makes for less O-4+ all running around the ship.
Better distinction between novice SOs and very seasoned SOs, also more satisfying rank progression for those who do play SO more.
:cl:
add: Added O-3 to SO as starting rank. SO now gets O-4 at 25 hours and O-5 at 50 hours. 
/:cl:
=> SO rank changes

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
Really just a simple fix, without modifying the map itself.
Fixes good.
:cl:
fix: fixed engineering staff on POS not having access to their gun cabinet.
/:cl:
=> Give the POS engineering armory a special gun cabinet, so they can open it. Turns out they couldn't before.

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm, code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Fixes #7499 which was an issue with an object being in two places at once, rather than duplication.
You can catch thrown facehuggers(even leaping ones) with an open hand and throw intent active, but they'll keep trying to attack you. Use in hand to kill it, you monster.
Fixes storages breaking if you put a facehugger inside, the hugger will jump out when you open it now.
Repaths non-larval huggers to condense their similarities and make them not fit on your face.
Fixes things mentioned above, a bit of code improvement, improves some ingame feedback on what huggers are doing.
:cl:
add: Humans can use a hugger in-hand to crush it.
fix: Huggers don't break storage containers and will leap out now.
fix: Catching huggers works now instead of causing quantum huggers.
/:cl:
=> Facehugger catching

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
If Rage is used while at less than 0 HP, the Ravager will regain HP whenever it slashes a living target equal to 50% to 100% of the damage dealt depending on Rage Power (how low the Ravager's HP was when Rage was used).
Makes Raging and fighting while at critical HP actually worth the risk outside of strict 1 v 1 scenarios because you now might actually not get instantly deleted via life leech.
:cl:
balance: If Rage is used while at less than 0 HP, the Ravager will regain HP whenever it slashes a living target equal to 50% to 100% of the damage dealt depending on Rage Power (how low the Ravager's HP was when Rage was used).
/:cl:
=> Super Rage Gives Ravager Bloodborne/Life Leech Slashing

code/modules/reqs/supplypacks.dm
Literally just the title. Spoke with one of the more prominent T-26 users as of now and it was quickly agreed that the T-26 is way too cheap ever since NV was added by #7522. So this remedies that by increasing the cost to match the greatly increased effectiveness. 
T-26 is really strong right now since NV was added to it, probably should have had a price increase in that PR, but this fixes that instead. Though a bit late. 
:cl:
balance: T-26 AMR now costs 75 points, up from 60. 
/:cl:
=> Increases price of T-26 AMR to 75 points

code/modules/projectiles/ammo_datums.dm
Smartrifle damage from 15 to 25. For comparison rifle bullets deal 25 while mg bullets deal 20 comparing a t12 to a gpmg. Even comparing the t25 to t29, smartrifle has less damage and sunder per second for less mag capacity and req only mags + reloading mags with the ammo box.
For each time the t25 shoots 5 times (0.2) the t29 shoots 4 times (0.25), totaling 75 vs 80 dmg and 5 vs 8 sunder
Hell if I did the math right a t12 on aim mode can out-dps it while having vendor ammo assuming full auto, burst auto is even better and even moreso bfa burst auto since burst  doesn't take into account aim delay. If one wants to go smartrifle he's better off even going normal marine with T18 BFA with no worries about running out of ammo.
This should give it more of a reason to be considered over the …
=> Increases T-25 Smartrifle damage

code/modules/reqs/supplypacks.dm
Basically the title. Gets rid of the **four** useless, five point squad supply crates cluttering the Operations req menu. 
Otherwise this PR just clarifies on a variety of req orders to make things more specific and substantially more beginner friendly for ROs.
Clarity is good, and bloat in the req menus is bad. 
:cl:
del: Removed the useless squad supply crates from the req vendor.
spellcheck: Changed a variety of item names in the req menu to more accurately reflect their contents and items
/:cl:
=> Cleans up and clarifies the req menu

code/game/objects/structures/dropship_ammo.dm
Smoke minirockets receives cloaking smoke. Ilums offset from 5 to 3.
Now there is a reason to use smoke mini's. They have 7 radius smoke (like grenade) which clears fast, making them unable to hold screening for a long time but still useful.  
Ilums on most maps had often issues like landing behind walls, making them lighting actually nothing what is needed most times (and hit marines with 25% chance, funny). _For example: old 5 radius gives 11x11 square what is ~0.83% hit chance for single tile and 26% for 4x8 corridor. ~2% and ~57% with new._
:cl:NeinAnimas
balance: It's now easier to hit what you targeting with illumination minirockets.
balance: Never used smoke minirockets receives cloaking smoke.
/:cl:
=> Slight utility minirockets buff/rework 

code/__DEFINES/dcs/signals.dm, code/game/objects/effects/overlays.dm, code/modules/mob/living/silicon/ai/ai.dm
There is a noise for the OB one.
I'd like to have the CAS flares link directly to the condor, but i am not certain how to do it.
:cl:
expansion: The AI is now notified when a CAS or OB laser is created or goes out.
/:cl:
=> Make it so the AI has a notification for when lasers goes out.

code/game/objects/structures/window.dm
Cell windows will be destructible now, but not deconstructible. 
Indestructible windows that aren't blocking off space areas are unnecessary and bad. 
:cl:
balance: Prison Station cell windows are now destructible and acidable but still not deconstructible. 
/:cl:
=> Destructible cell windows. 

code/__DEFINES/traits.dm, code/game/objects/machinery/sentries.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm, code/modules/mob/living/living.dm, code/modules/xenomorph/xeno_structures.dm
Different implementation of #7494 
Hunter stealth grants a trait that makes turrets not target you as long as it's present.
Getting shot by AI when you're invisible is lame. 
:cl:
balance: Turrets won't target you when you're stealthed via hunter ability.
/:cl:
=> Turrets don't detect people in stealth

code/modules/modular_armor/storage.dm
Ever since #6858, storage modules don't actually slowdown at all, this updates their descriptions to properly reflect that and be less misleading and potentially confusing to newer players.
Clarity and accurate information is good.
:cl:
spellcheck: Description of Jaeger storage modules updated to reflect the fact that they no longer slow you down.
/:cl:
=> Updates storage modules desc to reflect no slowdown

code/modules/client/client_procs.dm
By default will reject while panic bunker is on and ppl only observed but if you set required playtime to 1 and you have a playtime of 1 you will be rejected anyway
=> Fix living panic bunker rejecting too agressively

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Defender can now charge from its Fortify stance when both Charge and Fortify are off cooldown.
Makes Fortify more viable and improves its ability to be integrated into Defender combos as a preface/launch point, making Defender play more fluid and flexible.
:cl:
balance: Defender can now charge from its Fortify stance when both Charge and Fortify are off cooldown.
/:cl:
=> Defender Can Charge From Fortify

code/__DEFINES/mode.dm, code/controllers/subsystem/ticker.dm, code/datums/gamemodes/civil_war.dm, code/datums/gamemodes/game_mode.dm, code/modules/admin/server_verbs.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/new_player/new_player.dm
Change the respawn time to 10 minutes in Civil War
Dying is way easier in civil war than in infestation modes, lowering the respawn time allow for the quicker pace gameplay of HvH to be less frustrating
:cl:
balance: Respawn time of 10 minutes for Civil War
/:cl:
=> Respawn time of 10 minutes for Civil War

code/__DEFINES/mobs.dm, code/_onclick/ventcrawl.dm, code/modules/atmospherics/machinery/atmosmachinery.dm, code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm, code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm, code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
1: Minor refactor of vent crawling. Some snowflaking removed. Infrastructure added for unique ventcrawl interactions.
2: Hunters can now crawl into and out of vents in 1 second down from 4.5 seconds.
3: Larva can now crawl into and out of vents in 1 second down from 4.5 seconds.
1. Removes snowflakery. 
2. Adds useful infrastructure for ventcrawl.
3. Castes that should be better at ventcrawling are.
:cl:
code: Partial refactor of vent crawling. Snowflaking removed. Infrastructure added for unique ventcrawl interactions, and custom ventcrawl parameters at the caste level.
balance: Hunters can now crawl into vents in 1 second down from 4.5 seconds.
balance: Larva can now crawl into vents in 1 second down from 4.5 seconds.
/:cl:
=> Minor Vent Crawl Buff; Hunters and Larva Can Vent Crawl Faster

_maps/map_files/Theseus/TGS_Theseus.dmm
changes Theseus aft escape shuttles to pods, as they should be 
oh god oh f**k
:cl:
fix: Theseus Aft Escape Pods have been properly installed, the engineers that installed escape shuttles have been fired.
/:cl:
=> Theseus Escape Pod Fix

code/modules/mob/living/carbon/xenomorph/life.dm
Xenos don't take less damage/heal better on crit with warding, back then it was way worse and i nerfed it half mostly so it woulndt be that huge of a nerf, still i think it does a way too good job and makes recovering from crit and not dying to it veery veery better, which led me to remove it.
Warding in my view makes xenos recover way too much and die way too slow off weeds when on crit, this removes this interaction totally, i don't think thats that much of a nerf but its considerable, but warding already is very good by giving armor don't think it doing this more is necessary
:cl:
balance: Xenos don't take less damage/heal better on crit with warding anymore.
/:cl:
=> warding doenst make you recover/die less on crit.

code/controllers/subsystem/persistence.dm
This PR fixes the spelling mistake of High-power pistols (formerly Hiph-power) and the lack of capitalization of Cops (formerly cops).
As it is currently literally unplayable with these horrific crimes against English, this makes the game literally playable.
:cl:
fix: Fixed English in seasonal weapon rotation titles (Hiph to High and cops to Cops).
/:cl:
=> Fixes spelling and capitalization of seasonal weapon rotation titles

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
- Add some firedoors
- Move the cafetaria area a bit to the right
- Move some lights and fire alarms away from the glass
- Shift req map table away toward the wall to make pushing crates easier
The map makes more sense.
:cl:
fix: fixed a number of missing firelocks, firelocks and other machinery stuck on the wall, shift the req map table towards the wall on the POS.
/:cl:
=> Tweak to the POS

_maps/map_files/Sulaco/Sulaco.dmm
- The sulaco had 2 turrets, the POS has 3, theseus 4, this settles things a bit more
:cl:
tweak: Gave the sulaco three turrets, to bring it up to snuff.
/:cl:
=> Add an extra dropship turret to the sulaco

code/__DEFINES/area.dm, code/game/area/general.dm, code/game/objects/items/binoculars.dm, code/game/objects/machinery/squad_supply/supply_beacon.dm, code/modules/shuttle/cas_plane.dm
fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/7420
All shuttles cannot be targeted by tactical binoculars, ob beacon, or direct cas hit. 
If perfectly timed, can kill all the hive without xeno able to do anything.
And anyway, this is only used to delay hijack without xeno having any counters, this is meh
:cl:
balance: All shuttles are immune to direct cas and ob hit
/:cl:
=> All shuttles are immune to direct cas and ob hit

code/controllers/subsystem/persistence.dm
Swaps rifle bucket 2 from an uzi to a M412 and a HK-11.
SMG bucket with MP27 and MR25
Makes Rifle bucket 2 more unique, there's already a free m412 and it's barely different from the normal AR, and the HK-11 is a pretty odd sidegrade to the LMG effectively with it's stats overall. And is locked to the UGL.
The MP-27 could use some testing as I think it's pretty bad overall. And the MR-25 is a SMG sidegrade, fires slower and has more in the magazine.
:cl:
expansion: seasonal gun bucket expanded-rifle bucket 2 has a M412 and HK-11 rather than just an Uzi. And added a new bucket with an MR-25 and the MP-27
/:cl:
=> Changes rifle bucket 2 to a M412 and a HK-11 and new smg bucket

code/_onclick/ai.dm
Raycon good, wires bad. 
Use ctrl click now.
Easier AI time :)
:cl:
qol: The AI can toggle the fire alarms with ctrl click only now.
/:cl:
=> This unifies the Alt and Ctrl click over fire alarms from the AI into one.

code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
Drones speed were nerfed due to being used for the insta larval sting which was nerfed later.
Bringing back their speed on weed will help them prepare and maze/support and do a bit of combat in exchange for damage.
:cl:
Balance: Drone weed speed: from -0.1 to  -0.4 and damages from : 16/16/20/20 to 16/16/18/18
/:cl:
=> Buffes drone speed on weeds and lowers its damage to 16/16/18/18

_maps/map_files/Theseus/TGS_Theseus.dmm
- Add some AI holopads in some hot spots
- Change some cameras spot so they are not floating or fixed on windows
- Add some fire alarms to areas missing them
- Add two cluster warheads, bringing the total to three
- Move the cryo cells to the side, which looks better in my opinion
- Few tables added to medical lobby
- Fire shutters added to a number of place lacking them
- Delete a big handful of duplicate cameras
- Change some power monitoring consoles to the actually 'useful' type
- Add a console for the alamo in the hangar, so people do not NEED to go the CIC
- Fix a missing cable for disposal APC
- Add a biomass beaker
Those changes bring the theseus closer to a prettier, more streamlined map which we can eventually see frequently.
:cl:
expansion: Add some AI holopads in some hot …
=> Whole lot of changes for theseus

code/modules/mob/living/carbon/human/human_defines.dm
When a living mob tries to pull someone, it checks whether they're buckled to anything and if they are it automatically tries to pull the buckling thing instead. However, carbons have the flag BUCKLE_PREVENTS_PULL which prevents the pull attempt entirely. This removes that flag from humans, so if you try to drag one you'll ignore them and try to drag whatever they're buckled to.
Won't change behavior for buckling to any anchored things (normal beds, chairs, medevacs) since the attempt to pull them fails anyway, still can only pull roller beds.
Annoyed at not being able to click spacemans.
:cl:
fix: Trying to pull someone buckled to a rollerbed will now make you start pulling the bed.
/:cl:
=> Lets people on roller beds be pulled

code/game/objects/structures/stool_bed_chair_nest/bed.dm
If you examine a medvac beacon it'll tell you where the bed it's linked to is, but due to just trying to get the x/y coords directly this fails and gives 0s whenever a bed is in storage. This fixes that.
Bugfix.
:cl:
fix: Medevac beacons reliably relay linked bed coordinates instead of sometimes saying they're at 0/0.
/:cl:
=> Fixes medevac beacons not displaying the linked bed's location properly

_maps/map_files/Research_Outpost/Research_Outpost.dmm
Balances Crash locations for fairness towards Xenos, removing the chance of location blocking that Xenos cant access, while also widening fog for certain silos so exploiters cant destroy them anymore.
Marines have had it incredibly easy to crash for a long time, no developer has wanted to do anything for it, this is my first step to trying to balance it while making it so that both teams have a fighting challenge against each other. By removing the chance of blockage from inaccessible rocks and the chance of silos being glitch destroyed. Also gives marines more of a challenge and Xenos fairness, at this point, everyone hates crash so I want to try and make it fun again.
:cl:
balance: no more crash locations for canterbury that block the sides in a way that makes it impossible for Xenos to …
=> Research outpost balance changes for crash & tweaks.

code/modules/mob/living/carbon/human/emote.dm
I have no idea why this was happening, but this fixes it.
:cl:
fix: fixed typos in snaps and hugging emotes
/:cl:
=> Fix typo with the snapping emote and hugging emote

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Makes HP colors account for negative health values instead of defaulting to green.
Fix good,
:cl:
fix: Fixed hive status xeno health color when negative, like when in crit.
/:cl:
=> Fixes hive status xeno health color when negative

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm, code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
The message for king summoning pod and actual abilities are very small in the text box, making it hard to read. This removes the unnecessary overrides for the messages to fix the small announcements.
The king summoning pod creation and the king hive summon ability message are comically small compared to the text around it and other announcement messages. By normalizing the size of these announcements with others, it improves legibility and recognition of these important hive messages.
:cl:
fix: Increased the size of microscopic king pod creation and king hive summoning announcements.
/:cl:
=> Removing King Announcement Overrides

code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm, code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm, code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
This makes the boiler ammo feature _NOT A COMPLETE NOOB TRAP!_
It gives some advantage and a raison to use it, instead of simply gimping xenos while adding complexity.
:cl:
balance: made the boiler bombard cooldown when it has more acid stored
/:cl:
=> Shitcode the boiler into having a faster ROF depending on the amount of ammo stored

code/_onclick/xeno.dm
There's an attack delay after clicking most things as a xeno, but this isn't triggered by open turfs. Since resin floors are basically the equivalent of an open turf anywhere xeno-controlled, this removes the delay after clicking them too.
Functional consistency.
:cl:
fix: Xenos don't have an attack delay after clicking on weeds, the same way they don't after clicking normal floors.
/:cl:
=> Clicking a resin floor as xeno won't trigger attack delay

code/_onclick/ai.dm, code/modules/shuttle/marine_dropship.dm
It was fun to lock the rear door of the alamo, but this was certainly too OP and unfair to them.
Fairness good.
:cl:
balance: Made the AI unable to use the dropship doors while it is hijacked.
/:cl:
=> Make the AI lose control over the dropship doors when the beans hijackk it.

code/modules/projectiles/guns/shotguns.dm
Three lines of code are added to the Double Barrel shotgun, those three lines are adding the scopes to the TS-34. Mini-scope, marine-scope and scope. 
/obj/item/attachable/scope,
/obj/item/attachable/scope/marine,
/obj/item/attachable/scope/mini,
Give a wider range for usage for the TS-34 instead of only being the funny pointblank weapon to insta-crit runners and hunters. Adding these scopes to the TS-34 will make the double barrel shotgun far much viable in other situations than PB. It can be used as a defensive and a support weapon. Double Barrel shotguns were used for hunting and I wouldn't be suprised if hunters sometimes used scopes on them. Thank you
For footage on how the Double Barrel works and looks with a scope check: 
https://youtu.be/51a5YrTYUVc
:cl: Grandpa
expansion: Expands …
=> Add TS-34 Scopes

code/modules/projectiles/gun_attachables.dm
So, the underbarrel attachments have had an `attachment_firing_delay` for the longest time but the underbarrel flamer is the only attachment that actually properly uses it. Both the masterkey and the UGL currently have _no_ fire delay what so ever and can just be spam click rapid fired. 
This PR specifically fixes the UGL not having a fire delay and also balances it by giving it a fire delay of 1 second, the masterkey remains untouched for now because it is frankly shit code that I don't want to touch and don't fully understand, and also no one uses it. 1 second may seem high but is still faster than the rotary GL at 1.2 seconds of fire delay, the balance part of this PR is mainly meant to combat impacts being insanely deadly in a UGL due to being able to insta spam two of them and …
=> Fixes the UGL not having a fire delay by giving it a fire delay of 1 second

code/game/area/sulaco.dm
The OB/CAS prevention flags were stopping them.
Brings back functionality that :b:roke
:cl:
fix: fixes supply beacons not working in every LZ's
/:cl:
=> fixes supply beacons not working in every LZ's

code/modules/modular_armor/helmets.dm
I hate the back and forth of req being Like
"Turn on your antena"
"I already turned it on"
"Does not work"
"Fine, i am doing it now"
"Stop moving"
"Does not work"
"Ah come on, i just sent it"
"Fuck you, get it at the FOB"
"Asshole!"
This PR should make it a bit easier.
:cl:
qol: Increased antenna beacon duration from one minute to four minutes.
/:cl:
=> Make the supply beacon from the antenna last 4 minutes instead of 1

code/game/objects/items/lightreplacer.dm
This thing isn't very useful, and it basically does not fit in most kits, as many more useful things take priority, leading to it being rarely used. Even when marines take control of places with lights.
You are telling me that this thing is bigger than a roller bed which can teleport people?
You are telling me a shrimp fried this rice?
:cl:
qol: made light replacers smaller 
/:cl:
=> Make the light replacer small. Because it is too big for its usefulness.

code/datums/jobs/job/special_forces.dm
There was two lines. One adding the medhud and one adding the NVG googles.
This deletes the forgotten line.
Fixes the leader not having lights and it brings them to the same standard as the base guys.
:cl:
fix: Fix the special force leader incorrectly spawning with a Med hud
/:cl:
=> Fix the special force leader incorrectly spawning with a Med hud

tgui/packages/tgui-panel/styles/goon/chat-dark.scss
Per title. Changes most of the Dark Mode colors in hopes that these will be better for our eyes, and attempts to deal with some atrocities currently present in Dark Mode.
Our old dark mode colors were sometimes too dark, in some cases. This pull request aims to change that for the better.
I figured I should explain this with the assistance of some screenshots.
Firstly, a side-by-side comparison of the old and new colors, respectively:
The changes are barely noticeable save in some cases, such as the Alpha channel and Fire Support channel, which have much more tame color hues. The same can be said for the Requisitions channel.
Up next, xenomorph alerts/announcements. The top is the new one, and the bottom is the old one.
As you can see, I've gone for a more bright option here since I felt …
=> Changes Dark Mode colors to more eye-friendly options

code/game/objects/items/defibrillator.dm
As title
It's basically funny having a headless dude walking around normally, but it can lead to problems like unfixable organ damage. Plus inconsistencies, like the whole eyes, ears, and mouth still working thing.
:cl:
fix: Beheaded synths need their head actually reattached before they can be revived
/:cl:
=> Prevents defibbing headless synths

code/modules/projectiles/guns/mounted.dm
HMG could use a bit of time shaved off it's deploy, in general if it's moved often and 500~ms less should go a bit to making it feel easier to deploy, could reduce it to 7.5 and shave off a whole second, but I think 8 is fine.
Undeploy is now 3 seconds across the board, and should make HMG esp way better to play with. As moving the gun takes drastically less time.
HSG and HMG shouldn't take quite this long to undeploy.
:cl:
balance: HMG deploys ~500ms faster, and HSG/HMG undeploy far faster. (3 seconds as opposed to 5 and 8.5 respectively)
/:cl:
=> HMG/HSG undeploy in 3 seconds, HMG deploys ~500ms faster.

code/datums/actions/xeno_action.dm
Removes the "You will now activate this ability with shift click/middle click."
removes annoying message
:cl:
qol: Removes the "You will now activate this ability with shift click/middle click." annoying message that made no sense on xenos selectable message.
/:cl:
=> Removes annoying Message on selecting an ability

code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/projectiles/gun_system.dm
The undefibbable check was on the wrong person, so you couldn't give cpr if you yourself were undefibbable.
Also increases damage from suicide to ensure that you're below health thresholds.
Bugfix
:cl:
fix: Trying to give cpr to someone who's gone cold will fail properly now
fix: Suiciding gives more oxy damage, just so the body meets damage thresholds for cpr checks
/:cl:
=> Fixes cpr'ing undefibbable bodies

code/__HELPERS/game.dm, code/_globalvars/admin.dm, code/controllers/configuration/entries/game_options.dm, code/controllers/subsystem/ticker.dm, code/modules/admin/holder.dm, code/modules/admin/server_verbs.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/new_player/new_player.dm
Purges the few remnants of xeno respawn timers from the code.
No longer will the status page lie and say 2 minutes until larva respawn. You can immediately join the queue thanks to #7684.
:cl:
del: Removes remaining references to xeno respawn timers missed earlier.
/:cl:
=> Removes Last Remaining References To Xeno Respawn Timers

code/game/objects/items/frames/light_fixtures.dm
As title, new light fixtures made out of metal should work now.
Fixes #7801 
Bugfix.
:cl:
fix: You can once again make light fixtures.
/:cl:
=> Fixes new light fixtures being destroyed upon creation

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
1. Warrior Punch can target unacidable objects, but won't damage them.
2. Warrior Punch can now break cameras appropriately.
Fixes Warrior Punch to work as intended.
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/pull/7615
:cl:
fix: Warrior Punch can target unacidable objects, but won't damage them.
fix: Warrior Punch can now break cameras appropriately.
/:cl:
=> Warrior Punch Can Target But Doesn't Damage Unacidable; Other Fixes

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Grav crush will still be strong against cade and such, less against marine
King should be good at one thing : kill the fob. Xeno should not use it while defending, they should prefer silos and turrets. This makes king a more specialsed caste, rather than what it is currently
Alternative to : https://github.com/tgstation/TerraGov-Marine-Corps/pull/7806 
which just give you an arbitrary length which a round should last. This is an half ass solution, if xeno wiped out marines they should be able to finish the fight now ; not 30 minutes later because of some stupid time limit
:cl:
balance: Grav crush does less damage to mobs
/:cl:
=> Grav crush does less damage to mobs

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm, code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
runner literally does not use plasma at all, you could chain a near infinite amount of evades, which is pretty nuts. Now you can only chain a few.
Plasma should be a real thing that exists, and it works well with savages tradeoff of plasma.
:cl:
balance: evade now costs 75 plasma to use, runner has higher plasma reserves at lower tiers of maturity and regen overall, same plasma at ancient.
/:cl:
=> evasion now actually has a real plasma cost, runner plasma reserves at lower tiers increased, and regen increased

_maps/map_files/LV624/LV624.dmm
Also it lets people drop pod there. Check the map diff for a real idea of what happened
Crappy way to allow people to drop pod near at the LZ without dropping directly onto the FOB, so LZ2 isn't instantly more appealing simply thanks to drop pods.
:cl:
expansion: Added a backdoor to LV LZ1, which can be used to drop pod in.
/:cl:
=> What if we made LV LZ1 bigger? This makes it bigger. 

_maps/map_files/Sulaco/Sulaco.dmm
A lot of beans died to bring us this information. 
It just felt a little too random for people who died, and it wasn't even a window anyone looked out from.
:cl:
fix: removed the tiny space window south of sulaco preps to stop beans from dying there like IDIOTS
/:cl:
=> Fixes the little space view south of prep in sulaco killing beans during crash, by making it into a little room

code/modules/organs/limbs.dm
Byond lists start at index 1
Makes polyhex actually do anything against late infections, makes spaceacillin stronger at low germ levels and weaker at higher ones.
Bug fix.
:cl:
fix: Fixed an error with antibiotic germ clear amounts, polyhexanide should work now.
/:cl:
=> Fixes limb infection index error

code/modules/projectiles/ammo_datums.dm
After also using the TX-11 for quite a while, it is frankly not very good as well. This seeks to carve it's niche out a bit more as better against higher armored Xenos in terms of both penetration/damage and sunder. 20 penetration puts it on par with other "high velocity" ammunition, while still lacking the damage and pure sunder that they do due to having a larger bullet. This should hopefully further cement the TX-11 as a good gun on aim mode in the middle of an unga ball, doing solid sunder and decent damage against the heftier Xenos. 
The TX-11 isn't very good right now, this hopes to remedy that by cementing it's position as a LSW a little more. It will perform better against _most_ Xenos with the increased penetration, but some castes won't feel it at all due to already having so …
=> Buffs the TX-11 by 10 pen and 0.25 sunder

code/game/objects/items/cocoon.dm
Closes #7857 
#7823 added a new argument to cocoon's life_draining_over to properly handle it being called from a signal, but didn't put the additional argument in the right place for the non-signal call.
bugfix
:cl:
fix: Cocoons don't open instantly
/:cl:
=> Fixes cocoons opening instantly

code/datums/jobs/job/marines.dm, code/game/objects/machinery/kitchen/smartfridge.dm, code/modules/reagents/machinery/chem_dispenser.dm, code/modules/reagents/machinery/chem_master.dm
Makes the smartfridges in medical all-access.
Gives corpsmen chemistry door access.
Adds a delay to using chemistry machines without medical training.
I'm tired of people breaking into chemistry every single round. This starts to address that by making it unnecessary in some cases (corpsmen, using the fridge) and otherwise making it, if not less rewarding, slightly more annoying for the actor.
:cl:
qol: Everyone can use the medbay smartfridges.
balance: Corpsmen have chemistry access now.
balance: Trying to use the chem dispenser/chem master without at least basic medical training will incur delays.
/:cl:
=> Chemistry access changes

_maps/map_files/LV624/LV624.dmm
Fixes the LZ1 shutters not being properly surrounding the LZ
Make the path north of the LZ into a walkable area, 
Moves the button back into its place, 
Add a tiny light east of the LZ
This fixes things that were broken, which is good.
It also makes the area north of the LZ work for drop pods. I have no clue which it wasn't working before.
Heck, i might add a door there.
:cl:
qol: Made it possible to drop pod north of LV LZ1
fix: fixed a few issues with the LZ
/:cl:
=> Number of oversight fixes for LZ1

code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
Currently king minimap icons uses, for some reason, queen golden crown instead of the specifically sprited red crown. This fixes the bug by relocating the proc call of set minimap icon to after the king is spawned.
No longer will there be two queens wandering around on the minimap. The king gets their own specially sprited red crown, as intended.
:cl:
fix: Fixed King minimap icon to proper red crown.
/:cl:
=> Fixes King Minimap Icon

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm, code/modules/mob/living/carbon/xenomorph/castes/wraith/wraith.dm
1. Wraiths can no longer use Phase Shift while in the space of a phase blocking shutter, even if it's open.
2. Materializing in a solid object with Phase Shift no longer deducts plasma; it counts as if you had Resynced instead.
3. While the fight is Groundside Wraiths cannot phase shift into dropship area tiles from non-dropship area tiles.
4. General minor improvements to Wraith code.
Fixes some lingering issues with phase shift.
Improves Wraith code quality.
:cl:
fix: Wraiths can no longer use Phase Shift while in the space of a phase blocking shutter, even if it's open.
fix: Materializing in a solid object with Phase Shift no longer deducts plasma; it counts as if you had Resynced instead.
balance: While the fight is Groundside Wraiths cannot phase shift into dropship area tiles from …
=> Wraith Ability Refactor/Fixes

code/__DEFINES/dcs/signals.dm, code/game/atoms_movable.dm, code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
1. Evasion will now dodge thrown objects, including say impact grenades.
1. Evasion gains functionality it should have, and now definitely needs to have in light of impact grenades.
:cl:
balance: Evasion now will dodge thrown objects.
/:cl:
=> Evasion Now Dodges Thrown Objects

code/game/objects/items/scanners.dm, code/modules/atmospherics/machinery/pipes/pipes.dm, code/modules/recycling/disposal.dm
There's an element for hiding under tiles and displaying t-ray-scannable objects but the scanner itself, uh. Didn't use it. At all. Fixes that, plus adds the element to atmos/disposals pipes. 
Fixes
:cl:
fix: T-ray scanners show cables
fix: The atmos/disposals pipes that show up on t-ray will now actually be there when you crowbar up the floor tile.
/:cl:
=> Fixes t-ray scanners not showing wires

code/__DEFINES/loadout.dm, code/game/objects/machinery/vending/marine_vending.dm, code/modules/reqs/supplypacks.dm, code/modules/requisitions/fulton.dm
Basically everything in the title, fulton gets a price increase from 5 to 10 and is limited to three uses, ASRS gets a hefty price decrease from 50 to 30, the fulton is added to the SL vendor at 22 points, and the req operational vendor has two fultons in it at round start.
The ASRS is literally, completely useless in it's current state due to being completely overshadowed by fultons. This is meant to make the fultons somewhat more reasonably priced for their versatility and limit them as well, while also making the ASRS more appealing. Do you approve the three fulton orders that the Marines put in or just give them an ASRS to use instead? This should make the ASRS much more competitive with fultons, given the unlimited vs limited aspect and the fulton's increase in price. 
Adding it to …
=> Fultons are now limited use and more expensive, decreases price of ASRS, and adds fultons to SL vendor and operational vendor

code/_onclick/ai.dm, code/modules/security_levels/keycard_authentication.dm
This PR allows the AI to turn on swipe related things such as red alert using ctrl click.
This PR raison d'être is that everyone keeps freaking dying, leaving the CIC deserted at the times we need it the most. 
Being that the AI is pretty much 70% of shipside command at any given game, it seems silly for them not to be able to u
:cl:
expansion: Allows the AI to use keycard devices using ctrl click
/:cl:
=> Allow the AI to turn on red alert (without ctrl click now)

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/Sulaco.dmm
I have been asked to do this at the behest of admins due to an entitled attitude when it comes to obtaining corrupted xenos as the new groundside eggs make it easier to get a monkey infected
:cl:
del: Removed monkey cubes from shipside
/:cl:
=> Remove monkey cubes from shipside

code/modules/projectiles/guns/flamer.dm
Proc call was missing an argument.
Bug fix
:cl:
fix: Flamer ammo hud won't disappear when firing
/:cl:
=> Fixes flamer ammo hud disappearing

code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
crusher is a pretty good caste overall, in general i think it's near unpunishable outside of set scenarios or slapping it with a sadar to the fucking face
this should punish crusher far more for being out of position in team fights and make him unable to cycle as effectively
Crusher is absurd as it is, don't think you can argue against it, it got it's on demand stun back. It deserves a slap.
:cl:
balance: crusher is far slower on weeds (-0.15 instead of 0.4)
/:cl:
=> Crusher  has less weed speed

code/__DEFINES/mode.dm
60 to 90, effectively considering most drops are at 12:20/30, this is 60/70 mintutes.
King comes in way too fast into the game in general
:cl:
balance: king is locked for 90 minutes rather than an hour
/:cl:
=> king takes 90 minutes to enter the round

code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
This is a revival of https://github.com/tgstation/TerraGov-Marine-Corps/pull/7764
I think it was closed too fast and the feedback was apparently some guy yelling in the author DM's.
While i don't really have a horse in this race, i think it is worth having it around for discussion.
.
.
.
As reference, here are the current damage tiers of other similar castes:
Caste: Young / Mature damage - Elder / Ancient damage
Old Ravager: 26 - 32
New Ravager: 25 - 28
Defiler: 23 - 26
Hunter: 21 - 24
King / Queen / Shrike / Prae / Warrior: 20 - 23
Boiler / Wraith / Spitter: 17 - 20
Outliers from this damage increase trend:
Defender: 17 - 21
Bull: 19 - 21
Notice how the current "old" implementation of ravager conducts an increase in melee damage from 26 to 32, a total of 6 points compared to the nearly …
=> Reduces ravager slash damage

code/game/objects/machinery/vending/new_marine_vendors.dm
It makes it clearer when you are actually not meant to have access, if the vendor is dead or if you are simply lagging.
It should also help new players orient themselves towards the proper vendors when they spawn as anything besides squad marine. I've had to help more than a couple new engis or whatever find their preps.
:cl:
qol: made it clear when you do not have access to a vendor. 
/:cl:
=> Makes it clearer when you are denied access to a vendor

code/modules/reqs/supplypacks.dm
Adds plasma cutters as a requisition order for 30 points.
Currently the utility of plasma cutters is somewhat limited by scarcity, if an engineer doesn't buy one there is literally no other way to obtain one outside of scavenging it from the map. Allowing requisitions to order plasma cutters makes sense, and allows for marines to have some limited counterplay on certain maps that have narrow cave chokepoints.
:cl:
add: You can buy plasma cutters from requisitions now
/:cl:
=> Adds plasma cutter order to requisitions 

code/modules/admin/panels/note_panel.dm
Adds round id and playtime display in notes panel.
PR thanks to @Jordie0608. Ported from his tg pr https://github.com/tgstation/tgstation/pull/60811
Will help admins immensely.
:cl:SpaceLove
admin: Display playtime and Round ID on note panel{For Admins}.
/:cl:
=> Display round id and playtime in notes panel

code/modules/mob/new_player/new_player.dm
This removes the overflow text resulting from an extremely long message. Ghosts can spawn as larva immediately upon spawning anyways if they look at the respawn timers.
The observe warning text no longer overflow into the confirm button. Also, the seconds timer has been changed to a minute unit scale.
OLD
NEW
If there was a way to resize the box, I would do that instead. But a quick dive does not allow for size override of the tgui_alert().
:cl:
fix: Reduced observe warning text at post round start.
/:cl:
=> Reduces Observe / Ghost at Post-Round Start Text

code/modules/projectiles/gun_system.dm, code/modules/projectiles/guns/rifles.dm
Removes the snowflake code stuff from the bolt action, using cock() code for chambering ammo, also makes it now not autochamber the bullet when reloaded.
Better code with less vars and snowflake.
:cl:
code: changed the TL-127 bolt action rifle code to behave more like a bolt action, it also now doenst autochamber on loading another magazine.
/:cl:
=> Makes the bolt action rifle act closer like a bolt action codewise.

code/modules/reagents/reagents/toxin.dm
Transvitox bonus damage now also applies to burn damage converted as well as brute damage dealt to a victim under its effects.
Transvitox is easily the weakest xeno chem and has been notably underwhelming in practice thus far; this should help boost it a little, while also making its behaviour more consistent.
:cl:
balance: Transvitox bonus damage now also applies to burn damage converted as well as brute damage dealt to a victim under its effects.
/:cl:
=> Transvitox Bonus Damage Now Applies to Converted Burn Damage Too

code/modules/mining/remote_fob/remote_fob_computer.dm
Adds flag that make the FOB drone console indestructable from Marine or Xeno action.
No more funny plasma cut or RR at start of round to instantly grief the marine side from making a FOB.
Im surprised it hasnt happened yet and only in my testing that I discovered this.
:cl:
fix: Made FOB drone console indestructable by both marines and xenos.
/:cl:
=> Makes FOB Drone Console Indestructable

code/modules/power/groundmap_geothermal.dm
Removes apparent accidentical copy paste do after checks for generator decorruption.
No longer are unskilled welders locked from being able to decorrupt a generator simply because someone else got there first.
Fixes #7935 
:cl:
fix: Marines and other unskilled mobs can now decorrupt generators that have previously been decorrupted and repaired.
/:cl:
=> Removes Unintended Buildstate Check For Gen Decorruption

code/modules/mob/living/carbon/xenomorph/evolution.dm
Adds blue crown leadership check on evolution as well.
Blue crown sticks with xeno, despite evolution. No more need to reset leadership by the queen for magical blue crown.
:cl:
fix: Fixed blue crown xeno for leadership disappearing upon evolution.
/:cl:
=> Fix Blue Crown Leadership Being Deleted On Evo

code/modules/reqs/supplypacks.dm
Title. I already added mortars in vendor
I think minigun in civil war is okay
:cl:
balance: Mortar and minigun can be bought in civil war
/:cl:
=> Mortar and minigun can be bought in civil war

code/modules/mob/living/carbon/xenomorph/castes/wraith/wraith.dm
No one is meant to go there, but this is just an extra check to ensure wraiths can't either.
Fixes #6602
:cl:
fix: Ensures wraiths can't reach planetside telecoms. 
/:cl:
=> Adds telecoms to the list of no go places for wraith

code/modules/mob/living/carbon/xenomorph/evolution.dm
I am dumb. Misspelled minimap_leadered_icon. Right now, it's just redundantly setting the regular xeno icons instead of the proper blue crown icon.
Actually fixes the blue crown retainment on evolution.
:cl:
code: Properly pulls the correct leadership string for xeno leaders upon evolution.
/:cl:
=> Actually Fixes Xeno Leadership Icon Upon Evolution

code/game/objects/structures/misc.dm
YES THIS IS A SALT PR WHY ARE BUCKET DENSE AND BLOCKING XENO!!!!
A FUCKING BUCKET SHOULD NOT BE ABLE TO BLOCK A 100 KILOS SENTINEL!!!!
THIS IS A BUCKET!!!!
YOU CANT EVEN SEE THEM ON WEEDS YET THEY ARE BLOCKING????!
Buckets are almost invisible death traps for xeno. Not cool
:cl:
fix: Bucket are no longer DENSE
/:cl:
=> Buckets are no longer DENSE

code/game/objects/machinery/vending/marine_vending.dm
as a bonus it also means it saves in loadouts
qol
makes it save in loadouts 
:cl:
qol: ts-34 can now be vended without the belt, and also saves in loadouts without the belt
/:cl:
=> ts-34 is now gettable in the marine vendors without having to get the belt

code/game/objects/effects/acid_hole.dm, code/game/objects/effects/elevator.dm, code/game/objects/effects/misc.dm, code/game/objects/items/disks.dm, code/game/objects/machinery/camera/camera.dm, code/game/objects/machinery/cloning/cloning.dm, code/game/objects/machinery/computer/camera_console.dm, code/game/objects/machinery/doors/airlock_types.dm, code/game/objects/machinery/doors/multi_tile.dm, code/game/objects/machinery/doors/shutters.dm, code/game/objects/machinery/fuelcell_recycler.dm, code/game/objects/machinery/mortar.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/ladders.dm, code/game/objects/structures/orbital_cannon.dm, code/game/objects/structures/safe.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/game/objects/structures/window.dm, code/game/shuttle_engines.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm, code/modules/power/groundmap_geothermal.dm, code/modules/power/lighting.dm, code/modules/reagents/reagents/toxin.dm, code/modules/requisitions/fulton.dm, code/modules/shuttle/marine_dropship.dm
Simple find and replace of all mentions of the flags (Unacidable | Indestructable) to Resist_All. Functionally identical.
Less strange spaghetti code. The flag RESIST_ALL was previously globally defined as the combination of Unacidable | Indestructable yet code still redundantly uses those two. This unifies all mentions of those two flags with RESIST_ALL.
:cl:
code: Replaced all mentions of the two flags (Unacidable | Indestructable) with a singular Resist_All.
/:cl:
=> Conversion from Unacidable | Indestructable to Resist_All

code/modules/mob/living/carbon/human/inventory.dm
Several proc calls were missing user override, resulting in wrong fallthrough logic in if chain at storage handle_item_insertion(). This response does not null out gun_user, allowing players to fire pistols while the gun exists in storage.
No more super Ocelot with pistols firing from jumpsuit, armor, and helmet storage.
Fixes #6901
:cl:
fix: Fixes quick equip gun insertion into various storages failing to de-register user firing action.
/:cl:
=> Fixes Quick Equip Gun Insertion Into Storage Failing To De-Register Firing Action

code/modules/reagents/machinery/chem_dispenser.dm
Fixes untrained people having a delay when using alcohol/drink dispensers, forgot to handle that when I added it to the chem dispenser.
Fixes an index error in dispenser hacking.
Bug fixes
:cl:
fix: You don't need medical training to use bar machines now
fix: Hacking dispensers with a multitool works
/:cl:
=> Chem dispenser fixes

code/game/objects/effects/landmarks/landmarks.dm, code/game/objects/items/weapons/blades.dm, code/game/objects/items/weapons/weaponry.dm
This also adds a better file description to the file.
We already have three katanas. This is better for fluff reasons. I consulted a 'japanese sword enjoyer' with a big chin regarding the name & possible shape. 
Better fluff & better description.
:cl:
add: Switched a katana type to another sword for fluff reasons. 
code: Added some extra comments to blades.dm
/:cl:
=> Makes butterfly katana into a more regular sword with a different name

code/__DEFINES/dcs/signals.dm, code/game/atoms_movable.dm, code/game/objects/effects/decals/Cleanable/fuel.dm
More specifically, when anything on fire (active welders, lit cigarettes, lighters) lands on or hits them, or when a mob on fire walks over them.
Doesn't make sense that the only things which ignites fuel puddles are existing ground fires and lighters, especially since the lighter didn't even have to be on before. Plus throwing a cigarette to light a fuel spill up is cool.
:cl:
add: Most things on fire will ignite fuel puddles.
/:cl:
=> Lets fuel puddles catch on fire from most burning things

code/datums/emotes.dm, code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm, code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/living/carbon/human/inventory.dm, code/modules/mob/living/carbon/human/species.dm, code/modules/mob/living/carbon/shock.dm, code/modules/organs/limbs.dm
Necrosis is supposed to cripple any limb it's on and make it nonfunctional, but right now it doesn't actually do that in a bunch of cases. This fixes that by replacing relevant things that check for a LIMB_DESTROYED flag with is_usable(), which checks for necrosis.
You can still walk with necrotized legs/feet because that's tied into inventory code and needs to be handled a little separately.
Bugfix.
:cl:
fix: You can't hold stuff in a necrotic arm.
fix: Necrotic limbs hurt the same way amputated ones do.
fix: Dead fingers can't snap.
fix: Dead hands can't roll a wheelchair.
add: You can tell if any of your limbs are dead when checking yourself for wounds.
/:cl:
=> Makes necrosis do stuff

code/modules/projectiles/ammo_datums.dm
Brings slugs closer to the other shells in terms of damage, as well as increased sunder at the cost of AP.
Slugs are really bad. They're outperformed at range by flech at every tier of armor except warded crusher due to their low base damage. 
This gives it a niche outside of "pester the enemy xeno with stuns from very far away."
:cl:
balance: increased slug damage and sunder at the cost of AP
/:cl:
=> Shotgun Shell Rebalance - Slugs

code/modules/shuttle/shuttle.dm
Parralax is very neat, but the fact that it completly stops when you are in transit area kinda break the illusion for tadpole and alamo. Removing is better IMO
:cl:
del: Remove parralax slowdown
/:cl:
=> Remove parralax slowdown

code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Reverts tgstation/TerraGov-Marine-Corps#7894, at @TiviPlus's request.
Crusher's in an iffy spot balance-wise, Tivi wanted me to make this revert and I'm not particularly opposed to it.
:cl: Lewdcifer
balance: Reverts Crusher speed reduction on weeds.
/:cl:
=> Revert "Crusher has less weed speed"

code/datums/emergency_calls/special_forces.dm, code/datums/jobs/job/special_forces.dm, code/game/objects/items/weapons/shields.dm, code/modules/projectiles/guns/pistols.dm
This PR contains stuff for the special force ERT and some shield tweak : 
- Breacher role, who comes with a pistol and a riot shield. Probably weaker than the average guy thanks to a lack of a mag harness.
- The shield is like the basic SS13 polymer shield, but it is made of metal. 
- Removed the health analyser from the leader given he doesn't have the skills for it. Gave him grenades instead.
Leader has gear that he can use.
Breacher makes the ERT closer to the SWAT feeling i've been trying to achieve.
:cl:
expansion: Expanded the special force ERT to have a shield wielding guy. 
/:cl:
=> Gives the special forces a freaking riot shield on a breacher role. Awesome.

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/magazines/misc.dm, code/modules/projectiles/magazines/rifles.dm
Changes the T-25 to be less of a Rifle equivalent and moves it more towards being a LMG equivalent.
Ammo capacity- 50->80
Wield delay- 0.6->0.9
Aim slowdown- 0.55->0.7
Damage- 25->20
AP-> 15->10
Sunder 1.5->1
Ammo Capacity
50->80
----
The T-25 should lean more towards a supportive role with this change and I believe giving it higher ammo capacity to trade off the damage/pen and gunstats it lost would be good enough combined with the .5 more sunder I gave it to make it lean towards a supportive stance rather than an aggressive pushing stance with the gun.
Compared to the SMMGs 200, it still loses out 120 bullets, for a faster firerate and better utility options (UGL/Miniflamer) and it still has far better gun stats than the T-29. Aswell as a far larger attachment roster (Bayoent, etc..) …
=> T-25 smartrifle minor rework

code/modules/projectiles/sentries.dm
This Pr allows the AI to properly interact with sentries. The amount of things you can do is still very limited, but at least you can stop people from forgetting radial or something.
One step closer to shodan. Lowers the impact of bad engineers.
:cl:
qol: made it possible for the AI to actually interact with sentries.
/:cl:
=> Makes the AI able to use sentries again

code/modules/projectiles/ammo_datums.dm
increases the buckshot accurate range to 5 and reduces falloff by 1
Buckshot is kinda weird in a way that it is very good(only against low armor classes) at PB and trash at everything else, its supposed to be bad as range goes on but, not only it spreads, hitting less pellets due to it, but it also loses a lot of damage and misses alot after 3 tiles, now this maxes it hit more at a higher range but it will still hit 1 or 2 pellets due to spread anyway
:cl:
balance: buckshot has less falloff
balance: buckshot accurate range(not spread) has been increased to 5 tiles.
/:cl:
=> Makes buckshot a bit more effective mid range

.github/workflows/generate_documentation.yml, dependencies.sh
Build from source because https://github.com/SpaceManiac/SpacemanDMM/issues/268 exists in spacemandmm 1.7
=> Build dmdoc from source to fix parsing bug

code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
Pretty self explanatory, Bull gets all charges at Young instead of Headbutt at Mature and Gore at Ancient. This is a "buff" but is really more of a QoL change, Gore is not so much stronger than Headbutt (in most cases it is not stronger at all) that it should be locked until Ancient. Gore and Headbutt are used in different situations and not getting your other form of charge until Ancient kind of sucks and makes Bull gameplay less interesting until you hit that point. 
Gore is not directly better than Headbutt, it is more of a side grade used in a different situation. Unlocking it at Elder makes more sense, Ancient lock sucks and makes Bull less interesting until you hit Ancient which takes a fair bit of time. This is barely a buff at all.
:cl:
balance: Bull gets all charges at Young …
=> Bull now gets all charges at Young instead of having them be time gated

code/game/objects/items/weapons/misc.dm
A simple addition of a stun that scales with power level of the powerfist being used.
When used on marines, the maximum power level results in very short knockdown that exists only to drop weapons and a stun lasting 3 seconds. The stun time precisely depends on the power level of the powerfist being used.
On xenos, the stun is significantly shorter. As they recieve several reductions in stun time, the exact values could not be determined but testing resulted in approximately 0.5 seconds of stun. I observed that a noticable amount of stun time is actually done while the xeno is flying through the air, resulting in a very short practical stun time once the xeno stops flying. If anything, it gives the xeno in question a very nice scare rather than anything actually debilitating, other than …
=> Powerfist Now Applies a Stun Scaling With Power Level

code/modules/mob/living/living.dm
Skips processing of status effects tracked on mob (not datum ones), health updates (shouldn't be changing if they're in stasis), and organs (which then prevents chems metabolizing).
Apparently you still heal through chems while in a stasis bag. This fixes that.
A stasis check could be added to carbon's life too, but it's not necessary because the only thing carbon does is breath and that independently checks stasis.
:cl:
fix: Stasis bags prevent metabolizing chemicals
fix: Some negative status effects will be paused while in stasis, resuming once you leave
/:cl:
=> Adds stasis check to living

_maps/map_files/BigRed_v2/BigRed_v2.dmm
Adds more buildings and some features to big red.
This gives marines a reason to explore the map to access new storage of supplies in LZ1 as well as to access an underground Nanotrasen facility. This gives a nice RP addition to it and hopefully won't just mean marines rush Xenos. Xenos gains access quickly via lambda to this underground facility or at least most of it as only marines can access the other entrance without Xeno interruption. the underground facility allows Xenos a silo/hive spot that makes more sense but at the same time, they have less freedom to flee or run so it needs to be protected well. 
I think the players will really enjoy the process and cosmetic feel of the new additions. Both entrances cannot be camped as the main marine one has a large hangar door that won't …
=> Big Red V2.1 - Big additions.

code/modules/clothing/head/head.dm
Read the title and ask me what else it could possibly be about? Marine berets get the ARMOR_NO_DECAP, preventing decapitations. This does not mean you **won't** go down just as fast, you're just NOT permenantly removed from the round.
Very certain there are better ways to approach this issue, but I am not familiar with such approaches therefore this is the best I can and will be able to do
Being **severely** punished with a decapitation just because you want to spruce up your own fashion is actually pretty lame, not gonna front? Berets already have extremely awful armor stats to boot, meaning the result kind of stays the same anyway — you died. Why twist the knife in further with a "fuck you, you're outta the round for good"? Might as well just remove them (and similar hat items that …
=> Gives Berets a NO_DECAP flag

code/modules/language/language_holder.dm, code/modules/mob/living/carbon/human/species.dm, code/modules/mob/living/say.dm, code/modules/mob/living/silicon/say.dm
This pull request gives synth access to binary using the :n key. Basically the same thing as cyborgs.
The AI actually has it already, but like, no one can actually listen to it lmao.
This also features a comment a check and general prettying up of this check. 
It gives synths and silicon a bit of their own mini group, distinct from command. Kind of like their own channel. 
:cl:
qol: Brought Binary radio for synths
/:cl:
=> Look sir, synths with access to Binary radio!

code/modules/projectiles/ammo_datums.dm
Direct hit paralyze time changed from 0.5/0.1 seconds to 1 full second. 
No outrunning the gas spread anymore if you're direct-hit. I've done this a few times over the past month, and it's weird.
:cl:
balance: Boiler acid glob direct hits now stun for 1 full second rather than 0.5 or 0.1 seconds.
/:cl:
=> Boiler direct hit buff

code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
Per title. Increases Defiler's melee and bullet armors across all upgrades by +5, with the exception of laser armor, which has been standardized as per the previous two for Young Defilers given the existence of energy weapons. Besides this, the armor changes are kept small considering how much a percentage can influence damage over time.
Defiler, a caste about approaching the enemy with abilities like Reagent Slash and Noxious Gas, has trouble soaking up the damage it receives during its approach and barely has staying power, not to mention it is susceptible to slugs, buckshot, and explosives in general.
This should help it a little without making it an oppressive caste, which is one of my primary concerns while making this PR.
:cl: Lewdcifer
balance: Increased Defiler's armor by 5.
/:cl:
=> Increases Defiler's armor

code/game/objects/machinery/overwatch.dm
reopening of #7963
orders last way longer
10->15 ticks
may increase cd later if it's too opressive but i think 50 seconds is a good time for a order duration
orders are kinda trash and I tihnk making them last longer is a good start to up their viablity
:cl:
balance: marine orders last 30 seconds longer
/:cl:
=> orders last longer

code/modules/reagents/reagents.dm, code/modules/reagents/reagents/alcohol.dm, code/modules/reagents/reagents/food.dm, code/modules/reagents/reagents/other.dm, code/modules/reagents/reagents/toxin.dm
Reaction_mob has an argument named metabolize. It's not used in the declaration or in any children, and I don't know what it would do given that it's called when a reagent comes into contact with a mob. Metabolization is handled by on_mob_life, so that's not it. The only thing that calls reaction_mob is the holder's reaction proc, and it's never used it.
Cleanup.
Also fixes acid hiding the message when it melts your mask/helmet, due to incorrect argument order.
:cl:
fix: Acid will now tell you when it melts your helmet or mask (sulphuric/polytrinic, not xeno acid)
/:cl:
=> Removes an extra argument from mob reagent reaction

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
QOL change to help carrier optimize spawning huggers and plasma usage.
Carrier gets to use non-combat abilities while resting.
Carrier gets to optimize plasma usage by being able to rest while using these abilities.
:cl:
qol: Carrier can use retrieve egg and spawn hugger while resting.
/:cl:
=> Carrier can use non-combat abilities while resting.

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Sulaco/Sulaco.dmm, code/modules/mob/living/carbon/xenomorph/facehuggers.dm, code/modules/reqs/supplypacks.dm
This makes facehuggers ignore AI monkeys and puts the monkey cube boxes back in their respective places on each map. Player controlled monkeys are not affected.
Solves the problem presented in #7652 while still allowing for monkey related gimmicks and gives researchers something to do. Reduces the chances of unfair XvX gameplay happening.
It's better than nothing I guess.
:cl: Matlap
add: Monkey cubes are now back in research.
bal: Facehuggers will now ignore AI monkeys.
/:cl:
=> Facehuggers ignore AI monkeys, adds the monkey cubes back to the research lab.

code/modules/projectiles/ammo_datums.dm
Buckshot other projectile scatter from 10->4
Buckshot is fucking trash, it literally loses all of it's effectiveness past tile ONE.
Tile. ONE.
Now I've tested this and this makes buckshot effective until tile 3 rather than just tile ONE.
Buckshot in general isn't that attractive, this should make it generally more actually viable at it's CQC role since rn it's literally useless past using it as a PB stick, and that point just use flechette so you can shoot the xeno as it approaches you.
:cl:
balance: Buckshot extra projectiles have less scatter.
/:cl:
=> Reduces buckshot extra projectile scatter

code/game/objects/items/stacks/medical.dm, code/game/objects/items/tools/flame_tools.dm, code/modules/assembly/mousetrap.dm, code/modules/clothing/under/ties.dm
Seems these were forgotten
:cl:
fix: Some messages will now use pronouns correctly instead of their/they
/:cl:
=> Fix some pronouns not using the pronoun helper

code/controllers/subsystem/monitor.dm, code/modules/admin/admin_verbs.dm
Fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/8097
Admins should be able to fiddle with stats buffs without having to do every 2 mins
:cl:
fix: Fix admins xeno buff not staying
/:cl:
=> Fix admins xeno buff not staying

code/game/turfs/walls/resin.dm
This PR reduces the amount of health walls have to 300.
Reduces the tick damage of flamers from 50 to 15.
Gives walls 60% bullet soft armor, so they have the same general health overall.
Walls spawn stronger as well, +50 HP to thick and normal walls.
Changes Ex_Act defines as well, other than devastation.
This makes melee a more effective option of dealing with walls while keeping bullets not quite as effective against walls, reduces the effectiveness of a flamer in killing a wall, gives melee weapons a decent niche beyond being trash memes.
This also makes walls that are recently made, much much better.
:cl:
balance: Wall rework, max HP lowered, they've been given armor against bullets/lasers so their TTK is about the same, they're less effective against fire, high armor piercing …
=> Resin wall rebalance

code/game/objects/items/weapons/blades.dm
Machete and Officer sword get 15 more force for 75, and bump attacks.
Makes machete more viable and gives it an edge over vali usage, considering it has NO utility in the game rn considering you can 2 shot weeds with a bayoneted gun and not sacrifice anything, and vali has bump attacks already. I don't see the point of not just letting this happen.
Makes the machete into an option you can pick over the spear, which doesn't have bump (though I might give it bump) for +1 reach and more damage if you wield it.
:cl:
balance: machete/officer sword have bump attacks and deal 15 more damage
/:cl:
=> machete/officer sword have bump and +15 more force

code/modules/projectiles/ammo_datums.dm
Tweaks neurotoxic spit & the gas it leaves to actually be helpful and effective.
Marines currently are nearly unstoppable unless your entire hive knows what they are doing and are skilled which isn't 24/7. current neuro spits are worthless and easily fixed, marines have so many tools that help crush forward while  Xenos has no real strength to stop other than acid turrets which are only temporary, more so as they cant be built as close to each other anymore.
This tweak allows neurotoxic spit for sentinel, praetorian, queen to be worth something in team battles that slow a marines push and makes them weary rather than having them continue forward unchecked which is hard to deal with. in return I've increased the cost somewhat so this isn't something that can be spammed but used well to …
=> Neurotoxic Spit Tweaks.

code/game/objects/items/storage/backpack.dm
You can't put more than 2 pistols in bags anymore.
Pistols can be used as a secondary, or you can reload them pretty efficiently with the pistol belt.
https://media.discordapp.net/attachments/504094319075131402/881174890210820196/sins.PNG?width=874&height=670
Pistols loadout have:
-Incredible DPS. You can kill ancient runner in one sec with tp 23
-Amazing sunder
-Instant reload. Taking a two new pistols from a combat back pack takes half a sec
-Insane speed. Because zero slowdown, no need to wield
-Basically immune to stun. You don't have to wield, you can just take new pistols
And the compromise for that is:
- It's long to make your l... Wait, no longer the case, you can just use loadout vendor
- You have to come to fob to reload quite often. 
That's it.
Pistols in bag are an issue since …
=> You can't put more than 2 guns(pistol, revolver) in bags anymore

code/modules/mob/living/carbon/human/human_attackhand.dm
Marines should be able to tell what the general damage to their body is better than the current system which barely tells you anything since it genericizes past 40 brute/burn
this adds 60 to 100 and 100+
marines can tell how eviscerated they are
:cl:
balance: marines have more messages telling them the severity of their wounds when they self examine
/:cl:
=> Adds more stages of health self examinatoin

code/modules/mob/living/carbon/xenomorph/attack_alien.dm
The slowdowns were not applied when a runner was dragging a human for exemple. Two solutions to fix that : 
- make the crusher slows down when the rider grabs something. While possible, i don't like this because as a crusher i don't want to be slowed down and die because my rider is stupid
- Prevent runner from dragging. Which makes sense, the runner is too busy riding to drag
No more funny drag
:cl:
fix: Prevent from dragging while riding a crusher
/:cl:
=> Prevent from dragging while riding a crusher

code/game/verbs/ooc.dm, tgui/packages/tgui-panel/styles/goon/chat-dark.scss, tgui/packages/tgui-panel/styles/goon/chat-light.scss
Per title. A new admin rank, Senior Admin, will be added in-game, and it requires a defined OOC color to account for its existence.
Allows us to give a new rank, as a courtesy, to former leads who have retired but continue to be admins.
:cl:
add: Added a custom OOC color for a new admin rank.
/:cl:
=> Adds a custom OOC color for a new admin rank

code/game/objects/items/marine_gear.dm
Combat flashlights are now unacidable as a response to #8100
Combat flashlights are an inferior alternative to flares yet they somehow got nerfed without proper reason. Flares are easier to carry, easier to resupply AND have added utility of burning targets when thrown at them. Flashlights are generally used because of map spawns rather than somebody intentionally packing a whole bag of flashlights (instead of packing flares which is at least 4 times more space efficient I believe).
Now flashlights have a niche instead of becoming obsolete.
:cl:
balance: Combat flashlight is now unacidable
/:cl:
=> Flashlights are now not useless

code/game/objects/effects/effect_system/smoke.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/living_defines.dm
Makes smoke apply its affects when a mob crosses it, in addition to the usual 2 second process tick. Caps the frequency at a value set per smoke type but defaulting at 1 second.
Requested by Zack.
~~Chem smoke has its own internal limit of once per .4s limit per cloud.~~ Not how it works, actually.
Also fixes stacked smoke clouds not both applying effects. Apparently that was broken.
Makes just sprinting through a smoke cloud less free. ~~You still only get about 12 volume of reagents (6 each light and standard neuro) running the full length of a defiler neuro cloud with a gas mask on, but without this change it was about 1.2u.~~
:cl:
balance: Smoke clouds can apply their effects when you walk into one.
fix: Stacked smoke clouds will both apply their effects instead of only one.
/:cl:
=> Smoke affects you when you step into it

config/config.txt
On some PR bravemole made the default on local widescreen, which is pretty wonkers since ingame its 15x15 and some stuff act differently on some different viewsize(scopes in example), so this puts it at the same as it is in tgmc so it doenst make any difference from someone who's testing and what happens ingame, this made me break my head a little trying to figure why some scopes which shoulndt be modifying viewsize were doing it, then i remembered i were on widescreen.
:cl:
config: default config setting of view has been changed to 15x15 other than default 19x15, basically only affects local server settings for anyone downloading code from github.
/:cl:
=> Puts default config viewsize to 15x15 again

code/game/objects/machinery/vending/marine_vending.dm, code/modules/reqs/supplypacks.dm
You can get jetpacks from the utility tab now. 5 of them free, if this is not too much i'll make it widely avaiblable
Jetpacks are rarely used, despite their low price in req. This is because a lot of the time, you need this extra ammo in the bag, and jetpack is not that interesting in your loadout.
Putting the jetpack for free at the start of the game will allow players to experiment with new builds, and i don't think jetpack is that strong against xenos
:cl:
balance: 3 jetpacks free in vendors
/:cl:
=> Jetpack are now free

code/game/objects/machinery/doors/airlock.dm
Doors will now only log when the bullet impacts and only send the FF message before the hijack ship launches
:cl:
admin: Doors will now only log when the bullet impacts and only send the FF message before the hijack ship launches
/:cl:
=> Fix door shooting/hitting logging excessively

code/game/objects/items/storage/belt.dm
Limits the medical belt to only 3 magazines stored.
Currently the dedicated ammo storage belt can hold 5 magazines.
The medical belt can hold 14.
That's kind of absurd.
:cl:
balance: Medical belts can only hold up to three magazines. Their total storage isn't changed.
/:cl:
=> Limits max magazines in med belts

code/game/objects/machinery/deployable.dm, code/modules/projectiles/gun_system.dm, code/modules/projectiles/guns/mounted.dm, code/modules/projectiles/guns/sentries.dm, code/modules/projectiles/mounted.dm, code/modules/projectiles/sentries.dm
Fixes Issue #7926 
Also fixes the issue where a sentry will continue blasting its last target while knocked down.
Puts deployed machine armor values as based on the thing it is deployed from.
Adds a list of typepaths that will be of turf the sentry ignores.
These are set to the miners, and other deployed items.
Fixes a pair of bugs. Makes setting armor values item based. Allows for ignoring terrain so we can have cool things in the future like laser sentries that shoot through glass.
:cl:
balance: Sentries can now shoot past other deployed items and Miners.
fix: Fixes the issue with null internal guns on sentries.
fix: Fixes Comrade sentry.
code: Updates /deployable and makes armor values dependent on the deploying item.
/:cl:
=> Sentry Tweaks

_maps/map_files/BigRed_v2/BigRed_v2.dmm
Fixes this unmapped tile in Big Red LZ1.
Instant death bad. Spacetiles bad. Instant death by unmarked spacetile even worse.
:cl:
fix: Fixed an unmapped area in Big Red LZ.
/:cl:
=> Fixes unmapped area in Big Red

code/game/objects/machinery/miner.dm
Reinforcement module for miners now makes them immune to castes without CASTE_STRONG or MOB_SIZE_BIG flag
I've literally never seen any upgrade other than automation module on miners for months and haven't seen reinforcement module used ever since it got added. The added integrity is practically useless when the miner breaks on the first hit no matter what. So now it needs to be broken by a caste that can break acided walls to make sure fast flanking castes can't just hit and run.
Overclock buff was removed from the PR due to maintainer demand
:cl:
balance: Miner reinforcement upgrade protects against non-strong castes
/:cl:
=> Miner module buff for reinforcement

code/modules/reagents/machinery/chem_dispenser.dm, tgui/packages/tgui/interfaces/ChemDispenser.js
As title. Hit the delete recipes button, choose 'only one', and then press the recipe you wanna clear.
Also fixes a bug with dispenser fumble checks.
Being able to clear a specific recipe is better than having to clear all recipes if you want to remove one and then readd all the others.
:cl:
add: You can choose to only remove a single chem recipe instead of all of them when using a dispenser.
fix: You can't start fiddling with a chem dispenser while you're busy doing something else.
/:cl:
=> Lets you clear a single recipe from dispensers

code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Ravager's Rage now has maximum power when used at any negative HP amount instead of -57 HP or less. This is to make things more consistent and offset the loss of extra critical HP that the original rage power scaling was based on.
Rage Power is now properly adapted to the bonus Critical Hit Points that currently exist. Rage Power scaling is made more consistent and simplified.
:cl:
balance: Ravager's Rage now has maximum power when used at any negative HP amount instead of -57 HP or less.
/:cl:
=> Rage Power is Now Maximized While at Negative HP

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Well "Exploit" might be a strong word, more like map design oversight. However yesterday Xeno players had no qualms building a solid 10+ tile deep resin wall before the shutters opened, preventing Marine from effectively leaving the FOB in that direction.
The fix is so disgustingly simple its amazing it hasn't been done sooner, by the magic of changing **1** **(ONE)** area tile Xenos can now no longer build on the taxiway until the shutters are opened.
Tested locally and everything seems to be in order.
Fixes a map issue and makes LZ2 slightly less horrible to deal with.
:cl: Joniroq
fix: Fixed a mapping oversight on Ice Colony's LZ2, no more cheesing resin walls right up against the shutters.
/:cl:
=> Fixes Ice Colony's LZ2 resin wall before shutters exploit

code/modules/organs/limbs.dm, code/modules/organs/wound.dm
Tuning for wound/limb infection.
Wounds gaining germs is unchanged, but once they're closed they'll slowly clear out their own infection if it's not too high. Kitting helps here.
Slightly rescaled how fast wound germs transfer to the limb: a minimum amount are required so a fresh wound won't start transferring instantly.
Infected limbs are now much more apparent to their player, with repeating messages the same way broken bones show up. These're suppressed if you have spaceacillin in you.
Health analyzers have a lower threshold for detecting infected wounds.
Also a minor fix with wounds not changing their current state correctly when they worsen. Shouldn't affect function at all, just how they show up on examine.
They're a bit excessive right now. This might be too much, but there's …
=> Toning down infections

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/pistols.dm, code/modules/projectiles/magazines/pistols.dm
I can try targeting akimbo more effectively while retaining the pistol's original design if this nerf is too harsh, but this is just a basic nerf on the TP-14 to guarantee that it is no longer melting xenos so easily.
Testing in-game pre-nerf: 
The akimbo pistol can reduce a 500 health Ancient Empress to 80 health in 42 shots. 
The pistol can empty its mag in 3 seconds with a fire rate of 8 shots per second.
It deals 69.3 sunder from 42 shots.
After nerf:
It reduces Ancient Empress to 44 health in 42 shots. Still takes 3 seconds.
It deals 42 sunder from 42 shots.
Yes, I think I tested poorly to get an increase in damage after the nerf, but it's still weaker anyways purely statistically.
Now the sunder is less insane, at 16 sunder per second for akimbo. It can still laser beam right now …
=> TP-14 Standard Pistol Nerf

code/datums/elements/pathfinder.dm
Fix ai speed
Crusher will no longer zooooom. Works for all castes of course
:cl:
fix: AI crusher will no longer have the speed of a runner
/:cl:
=> AI crusher will no longer have the speed of a runner

code/modules/mob/living/carbon/human/inventory.dm
There seems to be a delay placed on a function that handles inventory actions. Since there was a several tick delay on doing actions, this reduces it to 1. I'm not sure if anything relies on it being exactly 3 ticks instead of 1. I tested it just to see if it reduced equip delay and it worked fine.
I checked lastest /tg/station code and they use different code. This code is either from baystation, CM, or just some really old code.
The delay can also be removed entirely to allow the code to be called at any time. But it could also cause some other issues like doing things before you're meant to, or simply being able to do inventory actions way too fast.
Now you wont have to press the same button multiple times unless you send actions faster than the world tickrate at 50ms intervals. If you …
=> Update inventory.dm, get_active_held_item() returning every 3 world.time ticks now reduced to 1.

code/game/objects/items/storage/belt.dm
increases the slots of ammo belt, letting you storage 6 magazines instead of 5.
The ammo belt is by far the generally most useless belt, letting you storage only 5 magazines while other belts let you storage ammo for much much longer staying, people often infact prefer to just put magazines in magazines pouch and take something else on belt since this carries so little ammo.
:cl:
balance: magazine ammo belt now has 6 slots from old 5
/:cl:
=> Increases ammo belt storage slots.

code/__DEFINES/dcs/signals.dm, code/datums/keybinding/client.dm, code/game/verbs/ooc.dm
Copies prefs and spans and bans from OOC because I don't know how to touch those, and since it involves preferences and possibly database stuff: I don't think we modify those until changes are fully merged permanently.
I'm not entirely sure about the safety of the admin-related checks since I didn't look into all of the admin code, but when I tested in-game alone (I don't know how to get multiple clients on a local server), it was fine.
So people can talk to their entire team through OOC means.
:cl:
add: Adds Team OOC, two new verbs in the OOC tab called XOOC and MOOC for Xeno and Marine.
code: Modified ooc.dm, adding two new verbs.
admin: XOOC and MOOC should have clickable player panel links for admins, and admins can see XOOC and MOOC chat and talk in them.
/:cl:
Screenshot, 2 …
=> Update ooc.dm. Adds two new OOC verbs for team-based OOC.

code/datums/status_effects/debuffs.dm
End-user summary- If you sleep on a bed with sheets and are not in crit, you'll heal 0.25 brute, 0.25 burn, 0.125 toxloss, 25 stamina, and a variable amount of cloneloss (-0.1 to 0.2, depending on your overall health). If you sleep on the floor, you get a quarter of those values.
First off, this uses regular ticks, not lifeticks, so there's that. You heal 20 times in the span that chems would heal you once, so let me just get that outta the way. The numbers are bigger than they look to be.
Adjusts health_ratio number to be -0.5 or greater, hence you'll heal if sleeping above crit. If you're crit, you're SOL, and probably also getting eaten by a ravager or something.
Does fancy math to standardize the base healing amount to 0.25 per two seconds when in a bed with a bedsheet on it. Let's …
=> Sleeping changes

code/modules/projectiles/guns/smgs.dm
Accuracy mult when wielded reduced by .3, and added .1 to the unwielded accuracy so it fits better into it's designated role as a one handed automatic firearm.
Unwielded scatter reduced from 5 to 2.
Added Aim mode
0.1 fire delay adding so it has 0.25 fire delay and 0.55 slowdown.
This'll make the T-90 have a better defined niche as a decently fast aim mode chasing weapon, but it'll have rifle fire rate. (IT CAN'T TAKE GYRO SO DON'T COMPLAIN ABOUT IT)
Gives both guns better definements in their niche.
T-90 gets aim mode, which it needed a while ago, and T-19 gets better one handed stats.
:cl:
balance: T-90 has aim mode, and T-19 has better one handed stats (reduced scatter by 3 and accuracy buff by .1), two handed accuracy reduced from 1.5 to 1.2.
/:cl:
=> T-90/19 semi buff/aim mode adding

code/game/buckling.dm, code/modules/mob/mob_movement.dm, code/modules/vehicles/ridden.dm
Turns out that the reason you couldn't move with people on your back is because you'd move initially, they'd try to move, they'd bump into you, they'd fail to move due to bumping into you, and then you'd fail to move due to them failing to move.
Fixes #8168, #8166, and #7917
Fixes.
:cl:
fix: People buckled to beds will lie down.
fix: You can move while carrying someone on your back.
/:cl:
=> Fixes buckling to beds and carrying mobs

code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/machinery/vending/vending.dm
Prevents restocking stacks if they don't have the amount the stack initially had.
Gauze and ointment in the marine meds are infinite.
Limiting the better, specialist option while making the general option more available.
If you really need more kits, you can buy 50 of each for 5 req points.
:cl:
balance: Marine meds have infinite gauze and ointment
balance: Stacks can't be restocked in vendors unless they have the count they started with.
/:cl:
=> Infinite gauze, finite brute kits

code/modules/projectiles/gun_system.dm
This reverts commit b605c33542ac9f2245204a8b175612dc78a4f29c.
Remove being able to shoot on adjacent tile
I keep shooting at weeds, or in other marines. And i keep seeing people shooting at random
:cl:
qol: No longer shooting at adjacent tiles
/:cl:
=> Revert "fixes not being able to shoot on adjacent tiles. (#8066)"

code/game/objects/machinery/vending/marine_vending.dm
Ads mk221s to the vendor so the admins will stop killing me
Just adds mk221s to the vendor. Its available right now in roughly 6 per ship so you can remove most of those if you want.
You can remove the engineering guns and I wont break through walls which you all hate
:cl:
add: MK221 added to marine weapon vendor list
/:cl:
=> MK221 to vendor

code/modules/projectiles/ammo_datums.dm
Make the praetorian have higher sustainability on its spits, while also keeping some of its fire rate.
Praetorian wont constantly run out of spit, but the spits are not super fast or super slow anymore.
Should be more enjoyable to play. You can still actively fire spits and wont have to rest on weeds for two or three times as long as you spend spitting, but you also wont fire so slow that you do minimal damage like the first PR tried to remedy.
:cl:
balance: Praetorian acid spit cost and speed changed to be 90 plasma cost and have +2 delay.
/:cl:
=> Buff Praetorian acid spit

code/game/objects/items/explosives/grenades/chem_grenade.dm, code/modules/reagents/reactions/other.dm
Chemical fire now functions properly. WP smoke can now be made chemically. Might look at explosives... but I think that's well-covered by ungas already.
Pre-assembled chem grenades now have a 2-tile radius, same as magic grenades.
Large beaker chem grenades can be made with up to a three-tile radius, one larger than magic fire grenades and one smaller than magic WP grenades.
WP smoke can be made via chemical reaction. A large beaker grenade is about as large as a WP grenade, but has no fire.
Nerfs fuel-air smoke. Radius was too large. It's still big but not "two screens" big.
Adds gunpowder. Chem on par with normal grenades, can be made slightly larger than a M15, but leaves a brief cloud of smoke upon detonation.
Adds ANFO. Chem with heavy explosion, limited to two tiles max, smaller …
=> Incin chems rebalance

code/modules/mob/dead/observer/observer.dm
Should fix most issues with the last respawn pr
:cl:
fix: Infinite marine respawn are no more, i hope
admin: Logging when a ghost take an ssd mob
admin: Human names are randomised when taken by a ghost
/:cl:
=> Fix infinite respawn, randomise name on ssd take, add admin loging

code/game/objects/items/reagent_containers/autoinjectors.dm
The other ingredients in a combat injector (bkt) purge ryetalin, so you'd get either one or zero ticks of it working before it got removed. Replacing rye with dylo makes it more reliable as a low-grade purgative option. It also adds minor toxin healing, which isn't super important but isn't otherwise available in base marine loadout supplies.
An injector having ingredients that purge each other is a little wack and led to cases where one reagent would just never apply.
:cl:
fix: Combat injectors have dylovene instead of ryetalin, so they'll purge toxins more reliably.
/:cl:
=> Replaces ryetalin in combat injectors with dylovene

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/rifles.dm
Auto eject might as well be qol, though it's a balance change.
Both of these guns get magnetic harness to make them more useable overall, as a single disarm is death with these guns otherwise.
Good for feel for the MPi, and STG/MPi really need magh.
:cl:
balance: MPi (AK) and storm rifle get magnetic harness, MPi autoejects on empty.
/:cl:
=> AK and Storm Rifle have mag harness, AK gets auto eject

code/modules/projectiles/guns/rifles.dm
M16A4 is more a slight hybrid between an AR/Carbine now, has the general stats of a AR with more damage, has better burst fire than an AR, has inbetween T-12 and carbine level aimed movement speed. It gets superior burst fire with less inbetween time between shots (-0.05 because -0.1 was kinda insane in testing.)
This should move the M16 to have a more defined niche overall in the gun community.
BFA removed because of balance concerns.
Removed autoburst to make bursting more skill based.
Makes the M16 have a more defined overall niche, makes it a bit more unique in the rifle category.
:cl:
balance: M16A4 can no longer fit BFA, has less delay between bursts, has no autoburst, aim speed movement is faster and lower base scatter.
/:cl:
=> M16 changes- Faster burst reset, no BFA, less base scatter, better aim speed. No autoburst

code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm, code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
prae has bomb resist 1
acid cone plasma upped to 450
acid cone slowdown on use halved
Makes prae a bit better and forces it to think a bit more about plasma management when using their cones.
:cl:
balance: prae acid cone plasma cost upped to 400 from 200, cone slowdown halved on use, bomb resistance has been upped overall.
/:cl:
=> Prae buff/nerf- Cone acid upped to 400, cone slowdown halved, bomb resist 1

code/datums/gamemodes/crash.dm
Crash really have infinite xeno, and they respawn in half a second, so death is meaningless. It's a bit sad, and marines are getting crushed again and again, unless xenos are really trolling.
Xenos have the same respawn potential, but it will be graduate (one larva every 2 minutes until game is balanced) rather than being instantanious (lol 3 xeno deaths --> instant three xeno respawns)
:cl:
balance: Xenos have slower respawn in crash
/:cl:
=> Xenos have slower respawn in crash

code/modules/admin/verbs/adminhelp.dm
Passes a raw form of the initial message to MessageNoRecipient() which always sanitizes.
Also @TiviPlus this is a port too 😝 https://github.com/tgstation/tgstation/pull/60826
Less HTML encoded garbage in new ticket chat logs.
Before:
After:
:cl:
fix: Fixed new ticket admin/mentor help message double sanitizing.
/:cl:
=> Fixes new ticket admin/mentor help message double sanitizing

code/modules/reqs/supplypacks.dm
all seasonal guns are 5 points, mags 1 point
adds mkh and judge seasonal
seasonals should generally be cheaper overall IMO, and some of these are needed in req because i either forgot or wanted to do this first.
:cl:
balance: seasonal guns are 5 points in req overall, magazines 1 point.
qol: some new seasonal guns are added to req in imports
/:cl:
=> seasonal guns are cheaper in imports, adds some seasonals to req

code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
Young/Mature->28 (2 more)
Elder/Ancient->30 (2/1 more)
Standardizes ravager elder/mature slash damage, as it was destandardized one time.
Considering endure got 20 nerf bats, ravager can have it's damage upped to near old levels again (2 less still.)
:cl:
balance: ravager upped to 28/30 melee damage respectively. (Young/Mature and Elder/Ancient)
/:cl:
=> ravager melee damage buff and standardization

code/_onclick/drag_drop.dm
If you click drag an object onto itself, it'll click on the object. No problems in-game after some testing.
Less missed clicks, you can click on moving targets properly, and you don't need to have esoteric knowledge to have an advantage over other players.
:cl:
code: Click dragging an object onto itself will click on the object instead of doing nothing.
/:cl:
https://user-images.githubusercontent.com/22848292/134054555-a8249378-9a44-41b5-95fc-850d4c00011e.mp4
=> Lazy click drag fix

code/modules/organs/limbs.dm
Humans take normal damage through their species' apply_damage proc, which includes reducing it based on their brute/burn_mod. So if limbs apply it too, that's twice.
Fix.
:cl:
fix: Synths don't apply their damage reduction twice anymore.
/:cl:
=> Fixes synths applying racial resistances twice to limb damage

code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
Lowers prae spray cost from 400 to 300.
So you still have to think about the plasma usage, but you don't have to retreat to regain plasma as soon as you use the spray. Pre-nerf, you can only fire acid spit 5 times if you use acid spray, or neuro 4 times. -1 times if you want to use frenzy pheromones to run away. It also sometimes ends up running out before you get to the guy and slash them, depending on the situation. Though it's still a step up from before, when acid spit costed 150 plasma, and where if you acid sprayed you could only spit 3 times before running out of plasma, which did pretty much nothing.
:cl:
balance: Praetorian acid spray cost is now 300 instead of 400.
/:cl:
=> Lower praetorian acid spray cost from 400 to 300

code/_onclick/hud/_defines.dm, code/_onclick/hud/hud.dm, code/_onclick/hud/human.dm, code/_onclick/hud/screen_objects/screen_objects.dm, code/game/objects/items/storage/marine_boxes.dm, code/modules/projectiles/gun_helpers.dm, code/modules/projectiles/gun_system.dm, code/modules/projectiles/guns/energy.dm, code/modules/projectiles/guns/flamer.dm, code/modules/projectiles/guns/shotguns.dm, code/modules/projectiles/guns/specialist.dm, code/modules/projectiles/mounted.dm
For akimbos, and attachments. Also fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/7558
Knowing how much ammo you have is pretty cool IMO
:cl:
qol: You can have multiple ammo huds
del: Remove the ability to disable ammo hud
/:cl:
=> You can have multiple ammo huds

code/modules/organs/limbs.dm
Makes the self splinting time delay 3x from 4x
Self splinting timer delay of 3x based on individual's skill. Even if a medic splints themselves it used to be 4x now it should be 3x delay. It also helps marines who are mid combat get splinted a bit quicker if they are carrying splints on their own. 
got it approved by PL as well
:cl:
balance: self splinting delay is now 3x instead of 4x
/:cl:
=> Self splinting timer delay is 3x instead of 4x

_maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
All the features in excruciating detail : 
- Added a few QOL changes to whiskey outpost, changes include paths, sandbags, loadout vendors, corrected gun vendors.
- Added a bunker for command to hide out in if things get too rough. Oh and also gave them some unmanned vehicles. (Added captain spawn planetside too)
- Gives cargonia a WP factory to either cause immense amounts of FF or defeat the xenos.
- Replaced briefing with 2 plat miners for easy access and beacuse nobody ever uses briefing.
- Gives the marines a few bikes for fast transit.
- Puts HSG nests back in their rightful place.
- Gives the marines some more metal and razorwire and stuff like that.
- Made the forest shack a bit nicer. For when you just want to hide from all the xenos.
- Fixed the little security checkpoint, Now …
=> Whiskey Outpost QOL update

code/game/objects/structures/stool_bed_chair_nest/bed.dm
fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/8380
Not a real issue, just clearer this way
:cl:
fix: medevac will properly tell you when you forgot to linked it to a beacon
/:cl:
=> Fix medvac priority check

_maps/map_files/BigRed_v2/BigRed_v2.dmm
Removes a strange row of landing consoles in dorms.
LZ consoles do not belong in dorms, they belong near landing pads, protected by marines.
:cl:
fix: Removed some landing consoles accidentally placed in dorms.
/:cl:
=> Removes extraneous landing consoles in Big Red dorms

code/modules/projectiles/guns/mounted.dm
200 integrety
50 bullet and 100 bio armor
dies a bit TOO fast and standard mounted armor.
:cl:
balance: t27 get's 75 more deployed hp for 200 total.
fix: t27 gets the same mounted armor as all other machineguns
/:cl:
=> t27 has normal mounted armor and 75 more integrety

code/modules/projectiles/guns/shotguns.dm
Tweaks shotgun wielded slowdown. T39 wielded is extremely slow at 0.6, with both less alpha damage and less damage in a full magazine, when compared to something like the T35 at 0.55, or even the Paladin, Mk221, or marine double barrel at 0.35. 
This PR makes the wielded slowdown of shotguns more proportional to their burst damage capabilities, as well as making it so that certain guns, like the V10 and Mk221, aren't just better versions of the T35 and T39 respectively.
Basically, 30% damage malus, aka T39, gets 0.35 slowdown. 25% malus, paladin and Mk221, get 0.4. No damage mod, T35 and V10, get 0.45 slowdown. Double barrels get 0.6 slowdown, which is incidentally old T39 slowdown, due to their fast firerates.
T39 might have an actual niche after this, although the wield time for it is …
=> Shotgun wielded speed tweaks

code/modules/mob/mob.dm
Emotes no longer show over ui
Emotes no longer show over ui
:cl:
fix: Emotes and typing indicator no longer show over ui
/:cl:
=> Emotes no longer show over ui

code/modules/client/preferences_savefile.dm, code/modules/client/preferences_ui.dm, tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx
Unhardcodes gender and enables neuter
Robots are an it not a he or she
And if someone wants to use this they now can
:cl:
add: You can now select Neuter as a gender in preferences, particularily reccomended for robots
/:cl:
=> Enable neuter gender in prefs

code/game/objects/items/storage/pill_packets.dm, code/game/objects/items/storage/pouch.dm
Improves the medical pouch available from the essential vendors for non-corpsman marines.
Changed contents from ointment, gauze, a tram injector, a 4pill trico packet, and splints to 8pill bkt packets, a 6pill trico packet, an inapro autoinjector and still splints.
Increases first aid pouch's max storage slots from 5 to 6, which I'm not inherently wild about but included on request.
Changed the restriction on the pouch's contained items to fit the new contents.
Right now they're real bad. Improving them guarantees a baseline of available meds for latejoiners independent of other people hoarding/resupply methods.
:cl:
balance: Marine healthkit pouches from the starting vendors are improved: they come with bkt pills, more tricord, splints, and an inaprovaline autoinjector. They've also got …
=> Improves first aid pouches

code/modules/projectiles/guns/specialist.dm
Only logs one gun and useless since booms mesage
:cl:
admin: removed admin message from flareguns
/:cl:
=> Remove excess message amdins

code/modules/projectiles/gun_system.dm
Title
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8404
:cl:
fix: Fix ammo hud breaking when stocking back gun in vendor
/:cl:
=> Fix ammo hud breaking when stocking back gun in vendor

code/__DEFINES/loadout.dm
Adds the radiopack as a backpack option for synth
Probably a good idea to give the dedicated support role a tool designed for support.
:cl:
balance: Synth vendor has radiopack as a backpack option
/:cl:
=> Added Radiopack to Synthvendor

_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Add some presetted weed nodes on prision station.
Make xenos job easy and less painfull giving they more time to do prep and more noob friendly for new players in weed castes, like drones, hivelords and etc
:cl:
balance: prison station now starts weeded
/:cl:
=> prision station preweed

code/modules/vehicles/unmanned/unmanned_droid.dm
Simple enough
Changes the alerts and adds an alert for when you try to repair a full hp droid
Droid healthbar updates when the droid gets repaired
Current alerts sound a bit off. ~~These new ones are a bit large due to [src] but acceptable as long as you play above 800x600
Also you can rename the droid to shitfart14 MK9001 and it'll work~~ (nah nevermind)
The healthbar health being different from the actual health is annoying and confusing
:cl:
fix:droid healthbar updates when repaired
spellcheck:(I guess?) changed welder_act wording
/:cl:
=> change /droid/welder_act wording and update droid healthbar again

code/modules/projectiles/gun_system.dm
Build a sentry health nerf
In our actual state build a sentry is better than normal sentrys in every sense. This PR focus on keeping build a sentry as a quick deploy turret used for supress fire instead of a sentry able to do so and also hold points and work as traps with the rocket sentrys and etc.
:cl:
balance: Build a sentry healh goes from 500 to 250
/:cl:
=> build a sentry nerf

code/modules/mob/living/carbon/human/husk.dm, code/modules/mob/living/living_health_procs.dm, code/modules/organs/limbs.dm
Zombies properly heal internal wounds
Double the heal rate
Zombies heal from broken bones
Zombies are still very much paper against marines, but they are more of a threat in groups. Playing zombie will also be more enjoyable
:cl:
fix: Zombies properly heal internal wounds
balance: Double the healing rate of zombies
fix: Zombies can heal from broken bone (has no effect on balance)
fix: Fix a runtime that could prevent human zombies from resurrecting
/:cl:
=> Buff zombies health regen

code/controllers/subsystem/monitor.dm, code/modules/mob/living/carbon/xenomorph/abilities.dm
Note i think SHUTTERS_CLOSED is the permanent state of SSmonitor in crash so idk if this would be op there or something
Weeding and building should be allowed to be done more freely before marines arrive to give builder xenos a proper chance to build with less resting needed
:cl:
balance: Halve weed and building cost before shutters open
/:cl:
=> Halve weed and building cost before shutters open

code/modules/projectiles/guns/shotguns.dm
Removes all UBF, masterkey, and underbarrel GLs from the main shotguns, barring Mk221's underbarrel GL.
Super burst damage on top of super burst damage with no real regard for fire delay is kinda wack and leads to people deleting xenos in like half a second.
I did this for pette btw.
:cl:
balance: masterkey, underbarrel flamer, and underbarrel GL for t39, t35, and v10 are now gone
/:cl:
=> no more underbarrel guns for shotgun (except plasma pistol, you're fine)

code/modules/projectiles/ammo_datums.dm
Reverts tgstation/TerraGov-Marine-Corps#8008
Reverts tgstation/TerraGov-Marine-Corps#8008
Closes https://github.com/tgstation/TerraGov-Marine-Corps/pull/8443
Closes https://github.com/tgstation/TerraGov-Marine-Corps/pull/8440
Buckshot has been powercreeped and its time to reel it in
:cl:
balance: buckshot has more falloff
balance: buckshot accurate range(not spread) has been reduced to 3
/:cl:
=> Revert "Makes buckshot a bit more effective mid range"

code/game/verbs/ooc.dm
Per title. Uses Maintainer OOC coloring.
Kuro wanted it, I deliver.
:cl: Lewdcifer
add: Art Maintainer role, has same OOC color as Maintainers
/:cl:
=> Adds an Art Maintainer role in OOC color code

_maps/map_files/BigRed_v2/BigRed_v2.dmm, _maps/map_files/LV624/LV624.dmm, code/game/objects/effects/glowshroom.dm, code/game/objects/items/reagent_containers/food/snacks/grown.dm, code/game/turfs/walls/walls.dm, code/modules/reagents/reagents/toxin.dm
Converts glowshrooms into a structure instead of an effect. Why were they an effect? Who knows.
Closes #8463 
It's kinda dumb to not be able to interact with them, and xenos can't deal with the indestructible light source which is kind of an issue.
:cl:
fix: glowshrooms can now be destroyed
/:cl:
=> Glowshrooms are destroyable

code/modules/projectiles/gun_system.dm, code/modules/projectiles/guns/revolvers.dm, code/modules/projectiles/guns/shotguns.dm
Title. The shotgun and revolver ammo counters now line up properly with the rounds in the chamber.
Closes #8386, although I couldn't reproduce the "you can pump it to empty it" part, the guns seem to lock as they should.
Ammo counter being accurate good.
:cl:
fix: The ammo counter for the shotgun and revolvers now works properly 
/:cl:
=> Fixes up ammo counters for shotguns and revolvers

code/datums/elements/pathfinder.dm
Ai were not resetting next_move_slowdown
closes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8487
:cl:
fix: Ais no longer stack slowdown
/:cl:
=> Fix infinite slowdown on ai

code/game/objects/machinery/vending/vending.dm, code/modules/projectiles/guns/specialist.dm, code/modules/recycling/conveyor2.dm
Vendors no longer eat items if depowered. Ghosts can no longer turn conveyor switches. Mirage nade now works in grenade launcher ( funny meme).
Closes #4706
Closes #5795
Closes #8279
Stuff working is good, I suppose
:cl:
fix: vendors no longer eat items if depowered
fix: mirage nades now work with grenade launchers
fix: ghosts can no longer interact with conveyor switches
/:cl:
=> Closes up some misc issues.

code/__HELPERS/unsorted.dm, code/game/objects/effects/landmarks/corpsespawner.dm
Title
They are not interesting to follow
:cl:
qol: Dead colonists are no longer in ghost follow menu
/:cl:
=> Fix dead colonists being in follow menu

code/datums/components/attachment_handler.dm
Title.
T35 got miniflamer removed from it. You can still vend t35-miniflamer. This PR fixes it.
Black market attachment combos die.
:cl:
fix: Fixes loadout saved guns/armor with illegal attachments being vended.
/:cl:
=> Fixes loadout saved guns/armor with illegal attachments being vended.

code/modules/hydroponics/seed_datums.dm
adds some of the "new" reagants to plants
Quietus added to deathberries.
Quick-clot plus added to blood tomato.
Paracetamol added to apple
Somolent added to Ambrosia deus.
Messsa's Tear and Srandar's hand looked at. Might repurpose those two. But that's a later thing.
more content for RSR, updates old botany content with the last year of chem changes
:cl:
expansion: 4 plants now have different chems. Deathberries, Blood tomatos, apples, and ambrosia deus now have Quietus, Quick-clot plus, paracetamol, and somolent, respectively.
/:cl:
=> plant update

code/_compile_options.dm, code/modules/shuttle/marine_dropship.dm, tgui/packages/tgui/interfaces/MarineDropship.js
Add an automatic cycle mode to alamo. When arriving to its destination, the shuttle will fly back towards its previous destination after X seconds + the time for the engines to be ready.
This is a bounty for elsa.
Easy to configure system, that prevents the whole "please captain cycle ship". You can disable it easily, so it shouldn't be a balance concern
:cl:
qol: Automatic cycle alamo mode
/:cl:
=> Automatic cycle alamo mode

code/modules/projectiles/guns/energy.dm
Fixes ammo counter for energy guns because I didn't notice their procs don't call parents.
I forgot this. Wanted to do it as part of a bigger PR coming up but was told to atomise. 
Ammo counter working is neat.
:cl:
fix: ammo counter works for energy weapons
/:cl:
=> Fixes energy weapon ammo counter

code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Decreases the minimum steps for charge to begin from 6 steps to 5. Increases bull's speed per step from 0.10 to 0.15. Decreases headbutt charge's stun formula to be about 1.8 seconds at most. Plasma mult. increased to 2. 
This caste ain't useable. It really ain't. Just about everything that can be done to be proficient requires such extreme luck that you are better off playing _anything_ else for the sake of simplicity. 6 steps meant constant scoping for lanes, meaning anyone paying any ounce of attention is going to know to move away. Couple this with the fact that Bulls move at such a sluggish pace when charging in **linear path** that punishment is astoundingly simple, even if they are caught offguard. 
:cl:
balance: Tones down the calc for headbutt charge stun to (charge speed x 30) …
=> Tweaks Bull Charge

code/modules/projectiles/guns/flamer.dm
flamer gets its hydro cannon back
:cl:
fix: fixes the missing hydro cannon on the marine flamer
/:cl:
=> fixes the missing hydro cannon

code/modules/requisitions/supply_export.dm
Title
This prevents marine from farming minions too efficiently. You can still get easy points from them, but not as fast as before.
:cl:
balance: Minions req reward reduced from 10 to 5 points
/:cl:
=> Minions req reward reduced from 10 to 5 points

code/modules/reqs/supplypacks.dm
Reduces price of the ZX Burst shotgun from 120 points to 80 points.
The ZX is probably a nice weapon. However due to its cost, it's nearly impossible to see it in action; in any circumstances where one can buy a ZX, a set of B18 is almost always worth the price instead. Dropping the cost of the ZX to minigun levels will allow the weapon to actually be used, as well as give a frame of reference for its effectiveness.
:cl:
balance: Reduced price of the ZX Burst shotgun from 120 to 80.
/:cl:
=> Reduces Price of the ZX Burst Shotgun

code/modules/clothing/head/helmet.dm
Per title. Stuff like packaged cheeseburgers, burritos, etc. now fit in helmets.
My fucking burrito doesn't fit in the helmet. This has been confirmed as heresy by multiple marine mains and I am inclined to agree. Also, packaged foods have a cool looking icon added onto the helmet when it's inside, so this PR effectively enables
_**f a s h i o n .**_
:cl: Lewdcifer
balance: Packaged foods now fit in helmets.
/:cl:
=> Packaged foods now fit in helmets

code/game/objects/items/implants/implant_items.dm
Per title. Attack force has been increased to 75, on par with the machete, and its attack speed has been increased to 8 from the average 12 for all melee weapons. Additionally, it can now bump attack, but note that bump attacks do not respect attack speed, so you can only really benefit from the attack speed by mashing click like your life depends on it.
Consulted with David beforehand, he said he was okay with buffing it, just need him to give me the O.K. in regards to the changes I've made.
The armblade is a T3/T4 reward, and despite this, it's incredibly underwhelming. With 60 force and no bump attack, it is arguably a worse alternative compared to the machete and the vali sword. This PR aims to amend that by making it just a little bit better than its normally accessible counterparts, …
=> Buffs the Mantis Armblade implant

code/__DEFINES/mobs.dm, code/game/objects/items/reagent_containers/autoinjectors.dm, code/modules/mob/living/carbon/human/life/handle_shock.dm, code/modules/mob/living/carbon/shock.dm, code/modules/reagents/reagents/medical.dm, code/modules/reagents/reagents/toxin.dm, code/modules/surgery/surgery.dm
This PR should rework all of pain and shock, but before I do that, I need to understand it (and ideally let everyone ELSE understand it too). 
**So, to start, here's the CURRENT status of pain and how pain works before I start tweaking things-**
All ticks are 2-second lifeticks.
Pain is handled in /code/modules/mob/living/carbon/shock.dm
This file takes all of your direct physical damage, adds it up based on a ratio (1.2 points per burn, 1 point per brute and cloneloss, and 0.75 per point of oxyloss or toxloss) and then adds the total amount of chemical pain (handled in reagants, usually negative) together, *then* adds the total amount of limb pain (40 if necrotized or delimbed, then 30 per break, unless splinted or valk'd, then it's 15 per), THEN adds 1.5 pain per point of organ damage …
=> Pain rebalance

code/modules/clothing/head/head.dm
Per title. Berets and headbands had shared names; this PR gives each item its own name.
Since they all had the same exact name, it can be very difficult to differentiate each item in a vendor. This PR amends that.
:cl: Lewdcifer
fix: Berets and headbands no longer share names.
/:cl:
=> Gives names to berets and headbands

code/datums/actions/order_action.dm
Title. 
Command can no longer haunt you with rally orders to their corpse.
:cl:
fix: Command can't haunt you with rally orders from beyond the grave.
/:cl:
=> Fixes command being able to send rally orders while dead

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Health and sunder stats added to game panel.
Plasma is already displayed in game panel, so it would be nice to have health and sunder displayed.
:cl:
qol: Health and sunder stats added to xeno gamepanel.
/:cl:
=> Xeno health and sunder are now displayed in game panel

code/modules/projectiles/ammo_datums.dm, code/modules/reqs/supplypacks.dm
Removes stagger and screenshake from A19/TX-8 Scout Rifle impact ammo. Slowdown and knockback are the same. 
If the gun in question was slower firing, I'd get _why_ the ammo is the way it is. But it ain't. The A19 is a pre-burst T-64 with built in IFF, it ain't any **business** having applying 2 stagger stacks, a full slowdown stack on the rate of fire it has. 
:cl:
balance: Deletes stagger and screenshake from A19 impact. 
balance: Damage increase to 30.
/:cl:
=> Nerfs A19 Impact Ammo

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Closes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/8740
fix: Fix picking up a dead facehugger as a carrier revive them, and they can be reused normally
=> Fix carrier exploit

code/modules/projectiles/ammo_datums.dm
Incendiary slugs now deal significantly more damage. Knockback and airburst procs removed. Inflicte slowdown and knockback (2) to targets. 
There was absolutely no reason to use this ammo. The damage was absolutely awful **because** airburst was literally causing it to do **30%** of its base. It was outperformed by weapons that had ammunition or modes that could achieve the same effect except significantly better. **There was also an accuracy malus that really did not need to exist, especially when you consider that this is on a slow firing gun. No other ammunition like this has this drawback, and they are completely capable of constantly applying fire stacks. So therefore, I have given up and decided that drawback is to be deleted.**
:cl:
balance: Incendiary slugs now deal 65 damage, 10 …
=> Buffs Incendiary Slugs

code/modules/mob/living/carbon/carbon_defense.dm
Per title. Removes stamina drain and toxin damage from tanglefoot.
You really shouldn't need a gas mask for smoke that _just_ drains plasma from xenos and nothing else — just to mitigate the effects of the very tool that should be aiding you and your team in halting a push by using said smoke. It doesn't do anything meaningful for gameplay and overall just feels like it's there just to be there.
:cl:
balance: kills stam drain from tanglefoot. 
/:cl:
=> Kills Stamina Drain From Tanglefoot

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm, code/modules/mob/living/carbon/xenomorph/life.dm
Title. It's supposed to give them 10% additional healing from any sources per currently leeched target, but didn't work due to two seperate small issues (one in the heal proc itself, one in vampirism code) (Notice, this "any sources" still only is "those that use heal_wounds()", others get skipped but that has been the case initially too)
This fixes those issues and therefore makes it work properly*.
*The Ravager's heal abilities during enrage do not use heal_wounds() so this doesn't apply to them still. Adding the used comsig to them on the other hand would make them also trigger other things that hook into it e.g. hivelord's healing infusion. Unsure which of the two states is preferred so I didn't touch this logic as of now.
Things working instead of breaking seems kinda good.
:cl:
fix: …
=> Fixes Ravager vampirism

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Warrior lunge doesn't work if you aim it adjacent, since it only does the relevant check when the warrior moves. This adds handling for if the lunge doesn't move you.
Fixes #8821 
:cl:
fix: Lunging at an adjacent target as warrior will grab them.
/:cl:
=> Fixes adjacent warrior lunge

code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
The place handling going into the tube used forceMove... but exiting just hardset the loc var?? This changes it to also use ForceMove, and appears to have resolved the issue with this.
Always hearing medbay after having been cryoed once is kiinda wack.
:cl:
fix: Exiting a cryo tube will no longer cause weird hearing behavior.
/:cl:
=> Fixes cryo causing sound duplication after exiting.

code/modules/clothing/modular_armor/attachments/storage.dm
Title.
Increases the storage slots of the module to 5, same as medical storage module.
The storage module can now hold almost everything only an engineer would use (does not include plasma cutter and miner modules).
(Honestly? The list might be an overkill)
Not even Engineers uses this module, hopefully this will give the module some use.
:cl:
balance: Increases the storage slot of the engineering storage module to 5
The storage module can now hold ~~filled sandbags,~~ razorwire, handheld charger, c4, razorburn grenades, detpack, signaler, circuitboards, and the light replacer
/:cl:
=> Buffs Engineering Storage Module

code/game/objects/effects/effect_system/foam.dm
Per title. Metal Foam health has been decreased from 200 to 120, which takes about roughly 4-6 slashes depending on the caste.
Makes Metal Foam less of a pain to deal with.
:cl: Lewdcifer
balance: Metal Foam health 200 > 120.
/:cl:
=> Nerfs Metal Foam health

code/__DEFINES/objects.dm
Per title. Damage multiplier against resin reduced to x2 from x4.
Checked with the Project Lead before making the PR, he said he was fine with nerfing the PC, just need him to approve these changes.
Reduces the effectiveness of the Plasma Cutter, which as it stands currently, has proven to be a very oppressive tool against all manner of structures.
:cl: Lewdcifer
balance: Plasma Cutter nerf: damage multiplier against resin x4 > x2.
/:cl:
=> Nerfs the Plasma Cutter against resin structures

code/game/objects/items/tools/shovel_tools.dm
Title.
Shovel speed from 20 to 10 if the etool is sharpened. Can be 15 as well.
The only time I've seen someone use the sharpened etool is when a squad marine was using it to oneshot weeds.
:cl:
balance: Buffs shovel speed of sharpened etool from 20 to 10
/:cl:
=> Sharpening an Entrenching Tool reduces the amount of time it takes to dig

code/modules/projectiles/ammo_datums.dm
Changes scatter spit  scatter rate and damage
Scatter spit isn't very good right now, it does little damage even if you manage to PB people. right now its a mosquito bite. and when you get in the range you are oftentimes punished by losing half your hp to marine fire just to use the ability. this at least makes it more usable. 
this should help make Spitter more useful as its spit damage even at ancient does little damage that is including the 15%+ per maturity.  
Abilities like this are overlooked and their damage is considered "ok" but people don't take into account acid armor, not to mention the projectile's speed is quite slow compared to marine bullets.
the ability will now be useful.
:cl:
balance: scatter is now 2
balance: projectile damage is now 20 from 10.
/:cl:
=> Scatter spit Range, Scatter, Damage

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/revolvers.dm
TP-44 ammo nerfed/changed.
-10 damage.
-1.5 sunder.
+10 pen.
0 scatter from 2.5 when wielded naked.
Makes tp44 deal less damage to low health low armor castes, and keeps it a threat against medium and higher armor castes while making it not delete everything in sight in one magazine.
It also does too much sunder, really.
:cl:
balance: tp44 does less damage (-10), plus ten pen. 0 scatter when wielded base from 2.5.
/:cl:
=> tp44 balance changes

code/modules/projectiles/guns/revolvers.dm
Apparently, an increased fire delay was supposed to be part of the recently merged TP-44 changes (#8841). This PR aims to actually reduce the fire rate a little bit. Tested it in-game, felt fine.
Gives the TP-44 its intended balancing, makes them a little bit less overpowered than they are currently.
:cl: Lewdcifer
balance: TP-44 fire delay 0.15 > 0.2.
/:cl:
=> Nerfs TP-44 revolver fire rate

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Changes rage power below 0 health to be set to 0.5, instead of 1.0. This halves the sunder recovery, damage bonus, speed boost, and leech strength (stacking with the damage nerf, so a slash that used to heal 60 will now heal 22.5). Endure HP bonus is cut to 3/4ths (now 150 instead of 200). Does nothing to rage above 0 HP.
Also changes super rage threshold checks to still actually work, but that doesn't matter for gameplay.
Effectively everyone I've asked, xeno or marine, has thought that Ravager super rage is way too strong currently. This will still keep rage threatening but prevents Ravagers from outhealing anything other than burst damage like shotguns and artillery, while also taking marines into crit in three hits at movement speeds faster than any T3 should be going. This might be …
=> Ravager super rage nerf

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Removes 2nd Magmoor nuke, adds some missing spawn protection to a couple xeno silos.
Bugs bad and I'm pretty sure all silos should have fog blockers for crash.
:cl:
fix: Removed extra Magmoor nuke.
fix: Patched some holes in xeno spawn protection on Magmoor.
/:cl:
=> Misc. Magmoor fixes

code/modules/admin/verbs/datumvars.dm
This fixes the issue regarding varedit permission not being allowed to actually var edit. Important vars still stay locked behind debug.
This should help the headmins not give +debug to ranks and not cause server security issue.
So varedit does what it does and hopefully doesn't let headmin cause server security flaw.
:cl:
admin: varedit does varediting.
/:cl:
@BraveMole
=> fix vv issue

code/modules/projectiles/gun_attachables.dm, code/modules/projectiles/gun_helpers.dm, code/modules/projectiles/gun_system.dm
Adds 50% aim mode delay removal to deployed bipod and support for simple aim mode delay modification.
I think that the idea of a standing marine with no aim mode fire delay from bipod for cover fire is an interesting concept to explore further and plays well around bipod's niche.
:cl:Slotbot
expansion: adds 50% aim mode delay removal to deployed bipod, which combined with red dot reaches 100% (yes, GPMG enjoyers)
/:cl:
=> Adds aim mode delay removal to deployed bipod

code/modules/projectiles/guns/shotguns.dm
Leicester Repeater damage multiplier increased to 2 from 1.5, resulting in 60 damage from 45.
Gun got gutted as a result of MJP's revolver ammo nerf. This fixes that. 
:cl:
balance: Leicester Repeater damage multiplier increased to 2x from 1.5x. 
/:cl:
=> Buffs the Repeater

_maps/map_files/icy_caves/icy_caves.dmm
New area northeast of caves, Monorail & Research.
More fun spots, cave gameplay constantly on this map is boring.
:cl:
add: new area northeast of caves.
balance: West-LZ1 to make it a bit more open north of it. also made lz1 bigger so marines got more room
balance: the pre shutter open no-build zone has been reduced.
balance: added more weed nodes and doors in caves for quality of life.
/:cl:
Red is the build zone. blue is a no-build zone.
LZ1
LZ2
LZ1 change.
New area.
NO you cant access the tank, it's behind indestructible podlocks and it's zoned out. only there for cosmetics
=> Icy Cave's addition's and tweak.

code/game/objects/machinery/vending/marine_vending.dm
Read title; simple enough.
The frequency of players going as SL, FC, or synthetic is pretty low, thus bottlenecking requistion from having a marine deploy a supply beacon in planetside. Even if marines have an antenna for their helmet, they (1) won't be in FOB and (2) marines have better things to do than to be a literal supply beacon.
:cl:
qol: requisition has a free supply beacon; now it's a skill and communication issue if requisition doesn't have a supply beacon deployed in planetside
balance: round start supply beacon without a round start SL, FC, or synthetic
/:cl:
=> Requisition gets free supply beacon

code/game/objects/effects/effect_system/foam.dm, code/modules/reagents/reactions/other.dm, code/modules/reagents/reagents.dm
Dis is jpr pr with a fix:
Grenades and canisters are left unchanged.
The minimum chem requirements for a razorburn mix that does anything is 7 nanites and 3 foam. Breaking this down, there is a 3/3 hardcap (smaller amounts will mix but won't do anything), and an additional 7u nanites catalyst softcap. 
Razorburn no longer deletes reagents in it's holder when it reacts, so it's viable to just directly add foaming agent to the nanite beaker (and is probably the easiest way to do so), but all razorburn reactions that aren't exactly 7/7 with no leftover nanites will *actually* have nanites in the foam now, as intended.
0-cost infini-fields of razorwire are unhealthy for the game. Minimize without removing, yay.
:cl:
balance: razorwire microdosing is dead
/:cl:
=> Nerf razor wire

_maps/map_files/Minerva/TGS_Minerva.dmm
Somehow during all of Minerva's testing, nobody noticed that the Drop Pod Bay didn't have an external access button.
Also, I didn't notice it.
PR to fix that, and a few other assorted post-launch issues.
People like to use Drop Pods, this allows for that without admin intervention.
:cl:
fix: Adds exterior access button to Minerva's Drop Pod doors.
/:cl:
=> Fixes Minerva Drop Pod Doors

code/modules/projectiles/guns/rifles.dm
Per title.
The fact that you can have a secondary shotgun, on a shotgun, is already weird enough. You can also fire both _simultaneously_ for some god forsaken reason. You can mix and match flechette, buckshot, and slugs for the imbalanced combination of your choice. All things considered, it's nowhere near balanced and arguably something that shouldn't be allowed.
:cl: Lewdcifer
balance: TX-15 autoshotgun no longer accepts masterkey shotguns.
/:cl:
=> Disallows the masterkey shotgun as an attachment for the TX-15 Auto Shotgun

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/rifles.dm
TX-11 extra delay reduced to 0.25 from 0.5. 
TX-11 scope zoom offset increased to 7 from 5.
Bad gun is now stronger. 
In other news. The zoom offset is to atleast provide a reason to keep it on the gun rather than ditch it. May or may not be necessary with burst changes...
The burst delay on the other hand is...necessary. Currently its **genuinely** awkward and 60 true damage or not, a gun like this is not strong enough to justify a 0.5 second delay. 
:cl:
balance: TX-11 extra delay decreased to 0.25 from 0.5.
balance: TX-11 scope zoom increased to 7 from 5. Stop littering. 
/:cl:
=> TX-11 Buffs

code/modules/mob/living/blood.dm
The code for applying the effective blood level reduction for not having a heart no longer has its effect almost immediately overridden by the code that returns your effective blood level to normal if you don't have a damaged heart.
In other words, not having a heart now halves your effective blood level, as it was intended to.
I also made the code for handling damaged hearts use the is_bruised() and is_broken() procs instead of directly checking for damage thresholds. This means that disconnecting someone's heart from the rest of their body via surgery will now impose the same effects on their blood level (and effective blood level) that breaking their heart would.
Code cleanup + not having a heart actually kills you if your blood level isn't dummy high.
:cl: ATHATH
fix: Not having a …
=> fixes a bug that made not having a heart not do much other than make you undefibbable

code/game/objects/items/storage/pill_packets.dm
Changes the dashes in the icon_state to underscores
Caused by #8916 adding these in but then mistakenly putting in dashes instead of underscores, causing the issues.
Fixes #8927 
This fixes pill packet sprites in firstaid pouches so they are visible, invisible pill packet sprites are considred widely to be not good.
:cl: Vondiech
fix: Pill packets are now visible again with the new sprites that were added to them.
/:cl:
=> Fixes pill packet sprites not showing

code/modules/projectiles/guns/smgs.dm
Adds `/obj/item/ammo_magazine/smg/uzi/extended` to the UZI's list of allowed ammo types
Fixes #8794 
~~Reason why this broke is unkown but for whatever reason `allowed_ammo_types` does not allow subtypes of ammo types~~
Reason why this was broken has been identified #8673 that was merged about 2 weeks ago changed the reload proc in such a way that although it would allow `allowed_ammo_types` to be put into a magazine, it did not check for subtypes of those magazines, causing this issue.
This is essential for CLF since they spawn with a backpack full of these clips, also overall not good for an extended clip to not fit into the gun despite being made specifically for that gun.
:cl: Vondiech
fix: You can now …
=> You can now put the gal-9 extended clip back into the UZI again.

code/modules/clothing/shoes/marine_shoes.dm
Added `/obj/item/storage/box/MRE` to the list of allowed items that can be put inside of the marine combat boots.
This PR has been fully tested on a local build with zero (0) runtimes or errors (the shoe sprite not updating, #8950, is unrelated)
Fixes the grievances outlined in #8856
As the issues outlined in #8856 the grievances caused by lack of spaghetti MRE filled shoes is clear, without the marine ability to put MRE's in their boots to be ready for consumption in battle it will severely affect their morale and ability to fight in such a way that it can affect the balance of the in-game round and therefor cause an unfair advantage to xenos.
Also this'd work nicely for those whom wish to have a mid-fight snack.
:cl: Vondiech
balance: You can now store MRE's in your combat boots for a …
=> I can't BELIEVE it's not shoe MRE's!

_maps/map_files/icy_caves/icy_caves.dmm, code/game/objects/structures/crates_lockers/largecrate.dm, code/game/objects/structures/tables_racks.dm
Marines have gotten into a habit of rushing the Icy Caves pirate coat, this PR removes it along with all ground side plasma cutters. 
The ground side pirate captain suit has apparently gotten known enough to the point where it's showing up each round and disrupting balance. The plasma cutters were in the same situation and also needed removed.
:cl:
balance: Icy Caves is back to it's original self, without the lab complex to the NW of the map.
balance: All Icy Caves plasma cutters have been replaced with pickaxes.
balance: The Icy Caves pirate coat has been replaced with a regular colonist uniform.
balance: Barrels no longer drop 10 metal by default when destroyed.
/:cl:
=> Cleanses Icy Caves of gamer gear

code/datums/beam.dm
Tesla doesn't drain plasma from xenos who can't be given plasma. The flag is currently put on xenos where the plasma code is used for a resource that isn't plasma and is managed differently.
Tesla also gives stagger and slowdown, which are still applied on all xenos.
This makes it so that the plasma gun doesn't mess with the plasma of xenos who have special plasma management, just because they share code. When the plasma gun was made, there weren't such cases and plasma on all xenos was abundant.
:cl: Slotbot
balance: tesla gun doesn't drain plasma from xenos who have special plasma management, other tesla debuffs remain the same
/:cl:
=> Tesla no longer drains plasma from xenos who can't be given plasma

_maps/map_files/Minerva/TGS_Minerva.dmm, code/modules/paperwork/paper.dm
Corrects further issues from Minerva post-launch. Improves tilework, adds lived-in content (General debris, etc), and replaces the cloning radios that kept blowing up vatborns.
Improvements to an existing shipmap, increases usability.
:cl:
fix: Fixes a few issues on the Minerva, such as explosive radios.
/:cl:
=> Content Patches for the Minerva, Volume 2

code/game/objects/items/marine_gear.dm, code/game/objects/items/reagent_containers/food/snacks.dm, code/game/objects/machinery/vending/marine_vending.dm, code/modules/reagents/holder.dm, code/modules/reagents/reagents/food.dm
Changes the way protein bars are generated so that they are no longer creating and then deleting a fake protein bar, just to create a real protein bar. As a side effect of this you will no longer be able to purchase specific flavors of protein bars.
Because 
1. the protein bars did not vend into your hands like old protein bars
2. the vendors vended fake protein bars into your hands that you could not see
3. the fake protein bars would prevent you from picking anything up even though they were deleted as soon as they entered your hands
:cl:
del: You can no longer vend specific flavors of protein bars
fix: Stopped filling your hands with fake protein bars
fix: nutriment has taste as intended
qol: Protein bars now vend into your hands as they should
/:cl:
=> Protein bar Fixes and Tweaks

code/game/objects/items/explosives/grenades/grenade.dm
Title. A grenade struck by a light explosion has 50% change to activate
I removed it by mistake in the grenade pr. This should prevent insta grenade stack kill, while still allowing fun.
:cl:
add: Bring back grenade chain explosion
/:cl:
=> Bring back grenade chain explosion

code/modules/projectiles/guns/shotguns.dm
-55% damage brings it closer to prebuff (stealth buff mind you) stats, plus it's generally easier to use now, and having a t-39 you can literally use on any gun is straight up terrible game design, this moves it closer to the utility option it's supposed to be.
Hyper stealth buff moment, surprised it took this long to fix it. 
This is literally absurd.
:cl:
balance: masterkey has a higher damage multplier malus, 0.45 from 0.7.
/:cl:
=> masterkey has a 0.45 damage multiplier from 0.7

code/modules/reagents/reactions/medical.dm
Makes Quick-Clot Plus craftable
The recipe for it as follows:
2 part Quick-Clot
2 parts Lemoline
2 parts Iron
The amount of QC+ needed for treatment seems never enough of what is available, the recipe creates 1 unit of QC+ out of 6 units of the recipe. Not enough medics already bother with chems to care anyways.
:cl: Kait
expansion: Added a recipe for QC+, making it craftable. The recipe for 1 unit is: 2 parts Lemo, 2 parts Iron, 2 parts Quick-Clot.
/:cl:
=> Makes Quick-Clot Plus craftable again

code/game/objects/items/explosives/grenades/chem_grenade.dm
Razorwire grenades and canister can no longer be opened with wirecutters and the containers inside removed.
Previous fixes have not worked to stop this.
Certain individuals have been abusing the razorwire recipe and the fact that the razorwire grenades can be opened to coat maps in razorwire, in combination with plasmacutting everything in sight. This has made rounds with those individuals online generally unfun for xenos, in that they're extremely restricted due to the sheer volume of it.
This solves one of those problems by making purchaseable razorwire grenades, in line with regular grenades, unopenable. The contents of said grenades remain the same so their intended use will be unchanged, and the recipe remains the same for admin shenanigans. Tested, and works as intended with no …
=> Razorwire grenades can no longer be opened

code/modules/clothing/modular_armor/attachments/chestplates.dm
This (https://github.com/tgstation/TerraGov-Marine-Corps/pull/8723) put a value of 50 when it should have been 40
bugfix
:cl:
fix: Fix acid armor value for jaeger heavy
/:cl:
=> Fix acid armor value for jaeger heavy

code/game/objects/effects/overlays.dm, code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Removes the xeno specific point code
It did basically the same thing, but without the features of the existing code.
Xeno points are now also _thrown_.
:cl:
code: Removed xeno specific throw card.
/:cl:
=> Remove redundant point code

code/modules/power/cable.dm
- Fixes the message so it doesn't look wrong
- Makes the burn overlays update after you repair em
Bug bad
:cl:
fix: Burn overlays update when you patch yourself with cable
fix: Fixes patching burnt wires with cable giving the wrong message
/:cl:
=> Fixes patching burns with wire and burn overlays not updating

code/game/objects/items/reagent_containers/autoinjectors.dm, code/game/objects/items/reagent_containers/glass/bottle.dm, code/game/objects/machinery/vending/marine_vending.dm, code/game/objects/machinery/vending/vending_types.dm
Okay, so, we know nanomachines are crummy, they drain your blood and usually end up doing more harm than good, sure, we could buff them.
Or we could give them to everyone, JPR mentioned them being a fun toy for researchers. Let's make it a fun toy for everyone!
Adds Nanomachine injectors and Bottles to the Marinemed and Chemistry vendors respectively, for all to use.
Due to the current questions about razorwire nades and such, i'm hoping to throw my hat in for a solution to the new Medical Nanomachine problem, partly due to Nanomachines not being obtainable in such a case (Reffer to PR #9012).
I believe, that while (Medical) Nanomachines are practically useless, several players have mentioned they're fun to use.
Now, I think Mera/Dermaline already fits the bill for Lemoline healing, with …
=> (Medical) Nanomachines: For all!

code/game/objects/machinery/vending/new_marine_vendors.dm
Title.
As promised in https://github.com/tgstation/TerraGov-Marine-Corps/pull/8892, I shall give synthetics the high-capacity industrial blowtorch in spawn so that they have QoL and show that contributors observe. Engineers have to buy one for 15 points, but since synthetic is dedicated support role, they need all the help they need. No sane synthetic would give away the high-capacity industrial blowtorch to any engineer.
:cl:
qol: Synthetic spawns with high-capacity industrial blowtorch
/:cl:
=> Synthetic spawns with high-capacity industrial blowtorch

code/__DEFINES/loadout.dm
Title; read next part
Fundamentally, the T-25 ammo box is a demand for any sane T-25 smartgunner. They rush to requisition to get more ammo (at least, this is what I do). This PR will allow smartgunners to have T-25 ammo boxes UNDER CERTAIN PARAMETERS!
All smartgunners have 50 SG points to buy their weapon and ammo. The current round start T-25 smartgunner spawns with 8 T-25 magazines, totaling up to 640 ammo. T-25 costs 35 SG points, and T-25 mags costs 2 SG point, giving a remainer of 1 SG point.
I propose to let T-25 smargunners be able to choose to get T-25 ammo boxes but no more than 2. One T-25 ammo box will cost 6 SG points and containing 320 ammo, so they can choose to use 12 SG points to get 640 ammo.
Yes, 6 points from buying 3 T-25 mags result in 240 ammo since 80*3 = 240, …
=> Add T-25 ammo box in SG vendor UNDER CERTAIN PARAMETERS

code/__DEFINES/loadout.dm
Title
During coding, I thought about giving it 5 points, then I saved it. However, 5 points would give T-25 too much ammo, so I THOUGHT I changed it to 6 points. Git played me.
:cl:
fix: Change from 5 SG points to 6 SG points to buy ammo boxes; I have integrity
/:cl:
=> Make T-25 ammo boxes cost 6 SG points, NOT 5 SG points

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Fixes a mistake I made in the warrior primordial PR, giving warrior punch twice the damage output of a regular slash.
Meaning a lunge+punch combo would be equivalent to eating 4 slashes.
Sorry to every player who lost limbs because of that mistake.
Marines will maybe stop losing their feet
:cl:
fix: fixed warrior punch doing more damage than it's suposed to
/:cl:
=> Fixes warrior punch

code/modules/projectiles/ammo_datums.dm
Increases Tl-127 flak slowdown to 1.5 from 1 and decreases max range to 15 (the rail scope caps out at 23 tiles)
Flak ammo is a meme. It isn't all too useful against larger xenos (as a matter of fact, it hardly accomplishes much at all against them). 
:cl:
balance: Increases bolt action rifle slowdown to 1.5 from 1 and decreases max range to 17 (from the meme that is 40 tiles)
/:cl:
=> Tl-127 Flak Touch Up

code/datums/jobs/job/shipside.dm, tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
Title.
Why researcher doesn't have medical radio is a mystery that doesn't need to get solved. It will get resolved by giving researcher medical radio without having them greytide and get radio.
Also, researcher is no longer in the same job category as CL.
:cl:
qol: Researcher has medical radio to talk in medical.
fix: Researcher is under support now instead of flavour.
/:cl:
=> Give researcher medical radio access and put researcher under support

code/modules/reqs/supplypacks.dm
Removes the Tyr head module from the Mark 2 Requisitions order crate.
You can already get it for free from the surplus armor vendors, as there isn't a Mark 2 specific variant.
:cl:
del: Removed Tyr helmet attachment from Mark 2 crate, as it's free in surplus vendors.
/:cl:
=> Removes Tyr head module from Requisitions order

code/modules/projectiles/guns/rifles.dm, code/modules/projectiles/magazines/rifles.dm
0.25->0.2 fire delay (so effectiively 5 BPS from 4)
26->30 magazine capacity.
0.45->0.35 wield slowdown.
0.6->0.5 wield delay.
This makes the MKH stand out in it's class, it suffers from low magazine capacity compared to most other assault rifle damage weapons (30 vs 40 on the AK, it's direct competitor.) but has good fire delay compared to everything else.
Makes the MKH98 more unique compared to the rest of it's peers, and makes it stand out as a unique choice, it still suffers in utility options and attachments, and it's a seasonal.
Gives it an edge against other guns like the AK, at worst I'd like to atleast see it moved to 0.2 and 30 rounds with the slowdown change.
:cl:
balance: MKH98 changes- 0.2 fire delay from 0.25, 30 round magazines, 0.5 wield delay from 0.6, 0.35 aim slowdown …
=> MKH changes

_maps/map_files/LV624/LV624.dmm, _maps/map_files/desertdam/desertdam.dmm
The latest LV rework broke CAS without flares due to an oversight, Chigusa never had the appropriate landmark to actually start CAS without flares so I fixed that while I was at it.
Bugs bad, also PO's would probably like to fly their planes without waiting for a flare.
:cl:
fix: Fixed a bug preventing CAS without flares on LV624.
/:cl:
=> Fixes CAS issues with LV and Chigusa

_maps/shuttles/tgs_bigbury.dmm, _maps/shuttles/tgs_canterbury.dmm
Adds tool vendors to canterbury and bigbury, removes a wall and moves a lamp on each.
On crash combat robots/synths/engineers have no real source of cables/blowtorches/replacement tools except looting toolbelts and toolboxes causing these to be in high demand, especially on higher pop or late into the game.
:cl:
qol: add tool vendors to canterbury and bigbury
/:cl:
=> Add tool vendor to crash

code/modules/projectiles/guns/specialist.dm, code/modules/projectiles/magazines/specialist.dm
Make mini pepperball mags smaller
Didn't consider the size of the mags while making the pepperball attachment, the mini magazines hold less bullets than regular pepperball so they should be smaller.
Also considered letting marines put mini pepperballs into pistol mag pouches but unsure yet.
Mini pepperball magazines currently take up too much space.
:cl:
balance: Change mini pepperball magazine size from 3 to 2
/:cl:
=> Make mini pepperball mags smaller

code/game/objects/machinery/vending/marine_vending.dm
Title.
You can find infinite fire extinguishers, both big and mini, in the Specialized tab underneath the Automated Weapons Rack.
You can ALSO have fire extinguishers in loadout!
Currently, you get fire extinguishers in two ways: in limited supplies from fire locker or mass produce from autolathe. The former is how almost everyone gets it and the latter is how almost no one gets it. Since friendly fire from fire is common and the demand for fire extinguisher is always on the rise, it is time to make the process of acquiring fire extinguisher easier!
:cl:
qol: infinite fire extinguishers are now in vendors! Find it in the Specialized tab under flamethrowers. I wonder why I put infinite fire extinguishers underneath flamethrowers.
/:cl:
=> INFINITE FIRE EXTINGUISHERS!!!!

code/modules/clothing/modular_armor/attachments/uniform.dm
hyper forgot to set this in his pr a month ago, since I've been taking a long break I didn't notice until i played today and opened up my webbing and found SEVEN SLOTS of magazines.
Webbing is only supposed to hold three things, no more. There's a reason black webbing exists.
:cl:
fix: webbing only holds 3 items again.
/:cl:
=> webbings only have 3 slots again

_maps/map_files/Theseus/TGS_Theseus.dmm
Title.
We have this map forever, and yet it does not have that prep QoL that PoS & Minerva have, and both of them are younger!
Weird that the CM maps like Theseus and Sulaco don't have this prep QoL. Food for thought.
:cl:
add: Protein bars at Theseus's prep. Now you can reduce the clicks in prep!
/:cl:
=> Put protein bars in Theseus's prep

_maps/map_files/Sulaco/Sulaco.dmm
Title.
Pillar of Spring and Minerva have them, so I'm putting protein bars to the shipside maps that should have them.
:cl:
add: Protein bars at Sulaco's prep. Now you can reduce the clicks in prep!
/:cl:
=> Put protein bars in Sulaco's prep

code/__DEFINES/loadout.dm, code/game/objects/machinery/vending/marine_vending.dm
T-29 smartgunners can now spawn with 5 T-29 drums (one in T-29 and four purchased with SG points) at the expense of not getting the 4 free SG drums that spawn in surplus vendor. Yeah, it's kinda weird that early round T-29 smartgunners get more ammo. Relic of an old past that I recall.
Been a long two days to buff T-29 ammo. See #9089 and #9095. Bravomole and I compromise to this, and MJP is not opposed to it.
:cl:
balance: T-29 smartgunners can now spawn with 5 T-29 drums (one in T-29 and four purchased with SG points) at the expense of not getting the 4 free SG drums that spawn in surplus vendor.
del: No more 4 free SG drums that spawn in surplus vendor. At least T-29 smartgunners spawn with 1,000 ammo!
/:cl:
=> T-29 ammo buff compromise

code/modules/projectiles/guns/shotguns.dm
Moves damage reduction from 55% to 40%, and doubles falloff.
Sets fire delay to 2 seconds, as normal shotguns.
Higher base scatter.
The masterkey now behaves like a pump action shotgun with t-39 damage malus style, but has high falloff and scatter making it hard to use beyond 1 tile, as it should be.
:cl:
balance: Masterkey has a lower damage malus, higher scatter and lower RPM.
/:cl:
=> Masterkey balance changes

code/game/objects/items/tools/extinguisher.dm, code/game/objects/machinery/vending/marine_vending.dm
Title.
Marines need a quick way to extinguisher marines on fire, and they have no fire extinguishers. It also helps with making loudout that have fire extinguishers.
Also, update mini fire extinguisher desc to help marines differentiate between the two when they look in vendor.
:cl:
fix: Vahalla now has fire extinguisher
fix: update mini fire extinguisher desc so that you can tell the difference between the two
/:cl:
=> Vahalla now has fire extinguisher & update mini fire extinguisher desc

_maps/map_files/BigRed_v2/BigRed_v2.dmm, _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm, _maps/map_files/LV624/LV624.dmm, _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm, _maps/map_files/Minerva/TGS_Minerva.dmm, _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm, _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm, _maps/map_files/Sulaco/Sulaco.dmm, _maps/map_files/Theseus/TGS_Theseus.dmm, _maps/map_files/icy_caves/icy_caves.dmm
OSHA came to inspect every landing zones, and they realized that it was not shiny enough to prevent dumb marines from stepping into landing zones!
Also, holy smokes. +2,205 −1,163? My bad. I went crazy with mapping.
Consistency across shipside and planetside maps' landing zones. Arrow and box tiles in shipside helps marine indicate where Alamo doors are at when Alamo is not in shipside. Outline of Alamo to REALLY show where Alamo will be.
Not even CM SS13 has this, and I remember fondly when I encounter such Alamo LZ design, I was like, "Why doesn't CM have this? This is smart."
Spooky is correct. Mapping is all about finding pretty tiles.
:cl:
add: Every shipside maps follow PoS Alamo LZ tiles
/:cl:
=> Every shipside AND planetside maps have standardized landing zone tiles

code/game/objects/objs.dm, code/modules/clothing/modular_armor/attachments.dm, code/modules/clothing/modular_armor/attachments/storage.dm
Title. Fixes #9130. Adding ONE LINE CODE gets the fix.
~~I'm still not sure how modules give more bio armor. That is a mystery for another day, so this is just a fix.~~ The mystery is solved. #4096 points to such reason. Also, thanks InterroLouis for the feedback.
How storage module and helmet modules give 100 bio armor is insane, not to mention on top of M.II Mimir. No more tanking acid shots or neurotoxin. You take it like everyone else.
Cope and seeth, M.II Mimir users.
I have a strong sense that this will make sent pretty oppressive.
:cl:
fix: storage modules don't give more armor as intended. Now you can't have 200+ or possibly 300+ bio armor to spawn
balance: marines don't stack bio armor like no tomorrow, so expect the sentinel castes to give you a harder time 
/:cl:
=> Soft armor, including Jaegar storage and helmet modules, don't give 100 bio armor

code/modules/projectiles/guns/rifles.dm
Going to try this the second time.
It's a rifle, so it should have point blank. Players expect PB, but instead they get bayonet. This is especially relevant when T-25 smartgunners are clicking at crit xenomorphs.
:cl:
add: T-25 has point blank
balance: T-25 has point blank
/:cl:
=> T-25 has Point Blank

_maps/map_files/BigRed_v2/BigRed_v2.dmm
Title.
Hazard signs show where xenomorphs can melt into. Since the Big Red changes, these signs are not needed.
:cl:
del: Delete some hazard signs in Big Red
/:cl:
=> Delete some hazard signs in Big Red

code/modules/projectiles/ammo_datums.dm
Sent will not be oppressive but still good.
Sent was balanced around marines with 200+ bio soft armor. Now marines are choking under neurotoxin. This PR, approved by Bravemole, will ensure that marines don't take in the suck too hard but letting sents do their job.
:cl:
balance: Decrease reagent_transfer_amount in light of marines losing 200+ bio; Sent will not be oppressive but still good.
/:cl:
=> Decrease reagent_transfer_amount in light of marines losing 200+ bio

code/game/objects/items/radio/encryptionkey.dm, code/game/objects/items/radio/headset.dm
Adds supply channel to all radio headsets
Allows communication between req and field much more effectively than RO shouting "GET MINERS" or "WE GOT POINTS, WHAT DO YOU WANT?" in common channel. Cleaner common channel and more supply orders, lovely.
Headsets can now be activated in hand to toggle supply comms
:cl:
add: Added supply channel to all headsets. Toggle by activating in hand
/:cl:
=> Common Supply Channel

code/modules/projectiles/guns/rifles.dm
Title.
In Bravemole's eyes, and to be honest me too, the T-25 is T-12+. MJP didn't intend this to happen, and I have abused this for too long. Other xenomorphs players feel the same.
I am doing this ahead of time in light of MJP's possible rework on this.
I swear, this is not a smear campaign for me to hog T-25 since these main features are the reason why players go SG. 
:cl:
balance: T-25 now cannot take keymaster, mini flamethrower, and UGL
/:cl:
=> T-25 now cannot take keymaster, mini flamethrower, and UGL

code/modules/projectiles/guns/specialist.dm
Title.
The SADAR allows mag harness, mini scope, and build a sentry as attachments. It's likely that marines want the mini scope since you outrange xenomorphs and shoot funny SADAR off screne and you can use a belt harness to get SADAR back.
Also, players that know how to use SADAR will ask RO to get SADAR, then they receive SADAR, but SADAR doesn't have mini scope. Such players like mini scope.
:cl:
add: SADAR spawns with mini scope
balance: SADAR spawns with mini scope
/:cl:
=> SADAR spawns with miniscope

code/__DEFINES/dcs/signals.dm, code/__DEFINES/traits.dm, code/datums/status_effects/xeno_buffs.dm, code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm, code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Makes psychic link channel-able while moving.
Xenos don't stand still when gorger is using the ability on them and the ability ends up being underused.
:cl:
balance: psychic link is now channel-able while moving
fix: fixes signal loop in psychic link damage redirect
/:cl:
=> Makes psychic link usable while moving

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Added `NON_ASCII_CHECK` to `/datum/action/xeno_action/hive_message/action_activate()`
This PR has been fully tested for anti-ascii on a local build with zero (0) runtimes or errors.
I don't think admins, and likewise most players, like the idea of queen announcement being turned into an ascii shitposting-fest.
Fixes #9147 
:cl: Vondiech
fix: Hive Message now checks and filters ascii.
/:cl:
=> Queen announcement filter now checks for ascii

code/datums/elements/deployable_item.dm
Fixes a Duplication glitch of the Build a Sentry attachment
Doesn't let someone place infinite Build a Sentries
:cl:
fix: Made it so you couldn't deploy the BaS while it being a no drop
/:cl:
=> Fix BaS Dupe

code/controllers/subsystem/greyscale.dm, code/modules/clothing/modular_armor/attachments.dm, code/modules/clothing/modular_armor/attachments/badges.dm, code/modules/clothing/modular_armor/attachments/visors.dm, code/modules/clothing/modular_armor/modular.dm
Makes the greyscale palettes for jaeger armor and helmets cache at round initialization. This is much more performant.
See above
:cl:
code: Makes the greyscale palettes for jaeger armor and helmets cache at round initialization. This is much more performant.
/:cl:
=> Cache Greyscale Palettes at Round Init

code/modules/projectiles/gun_system.dm
Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/8941
:cl:
fix: Mk221 unique action will eject shells again.
/:cl:
=> fixes mk221

code/game/objects/items/storage/storage.dm
fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9046
:cl:
fix: No more sound when a ghost open a storage
/:cl:
=> No more sound when a ghost open a storage

code/datums/gamemodes/game_mode.dm, code/datums/round_statistics.dm
Stealing #9132 and deleting some irrelevant statistics.
Also, show roundend statistics for warrior lunge.
More than just sents are using neurotoxin sting. Also, siloing bodies? Headbites? Those statistics aren't needed. Warrior delimbing people?
:cl:
fix: Change "sentinels stung" to "neurotoxin sting was used" in roundend statistics
add: Show roundend statistics on how many times warrior lunges.
del: roundend statistics on headbite and siloing bodies. Hunt is dead.
/:cl:
=> Polishing up xenomorphs' roundend statistics

code/game/objects/items/weapons/blades.dm, code/game/objects/items/weapons/twohanded.dm
Vali related tools lose bump, spear and machete.
Vali bump is honestly not that great of an idea, spear atleast, shouldn't have it. I might just only remove spear bump. But I feel like marine bump other than machete is a bad idea, it gives machete some level of reason to be used over the spear or machete or vali spear etc.. 
I feel like spear should lose it, but I think Vali melee in general shouldn't have bump. I like the idea of a high risk high difficulty playstyle that vali should have.
:cl:
balance: vali tools like spear and sword no longer have bump attack.
/:cl:
=> Removes bumpattack from vali related tools

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm, code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
Title.
Bravemole forgot that psychic summon is 1,100 plasma, and he didn't change the cost of psychic summon. I'm making this PR to bring awareness to this.
:cl:
balance: change plasma_cost on King's psychic summon, meaning he can psychic summon at young
fix: King can use psychic summon from young and mature now
/:cl:
=> Change plasma_cost of Psychic Summon so that young King can use Psychic Summon

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Adds hypersleep consoles to POS cryo room.
Apparently the Pillar of Spring has missing cryo consoles and marines are now bothering me about it.
:cl:
fix: The Pillar of Spring now has cryo consoles.
/:cl:
=> Adds hypersleep consoles to POS

_maps/map_files/Research_Outpost/Research_Outpost.dmm
Fixes silo camping.
Moves silos and gives them more room so not only aren't they really up close to disks, they got more room to.
:cl:
balance: slight changes to map around silos
balance: deleted some silos and moved some
/:cl:
1
2
3
=> Research outpost Crash silo fixes.

code/modules/projectiles/ammo_datums.dm, code/modules/projectiles/guns/flamer.dm, code/modules/projectiles/guns/pistols.dm
This aims to bring the plasma pistols niche back and give it some QOL
Changed the guns accuracy stats to 1, the shots will not always miss xenos. This was because I didnt quite understand the var when I initially added the gun. Willing to lower it again if its too powerful.
Plasma pistol shots range increase to 14 from 7.
Gives plasma pistol its t47 scope back.
If a turf is hit, any mobs on top of it will be ignited. This is too make it consistent.
If the turf that is hit is a wall, its firestacks will be tripled to give its original role back. Walls gained a ton of flame armor to nerf flamers but it also killed the plasma pistols niche. This will give it back without making the fire oppressive in combat. Flame duration is unchanged.
There was a nerf aimed for flamers that gave walls a …
=> Plasma pistol buff

code/modules/projectiles/guns/flamer.dm
Miniflamer now will not do any bonus damage to mobs hit in the initial fire stream.
Miniflamer can now be connected to the backpack fuel tank once more.
I was supposed to nerf the miniflamer when I did the flamer rework, I forgot so here it is. This will aim to make the miniflamer less oppressive damage wise yet still keep its area denial capabilities.
When I refactored guns I accidentally removed the ability to connect the miniflamer to a back tank. This remedies that.
:cl:
balance: Miniflamer now will not do any bonus damage to mobs hit in the initial fire stream.
fix: Miniflamer can now be connected to the backpack fuel tank once more.
/:cl:
=> Miniflamer nerf.

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Savage had a bug : https://github.com/tgstation/TerraGov-Marine-Corps/issues/8882
Just fixing the code would mean that runner would expend all its plasma after savaging, which is meh.
With the rebalance, the damage is proportionnal with the amount of plasma (like it was intended), but you spend only 40% of your remaining plasma. 
Savage cause more damage but cost more plasma, which might be a more interesting trade than currently
:cl:
balance: Savage makes more damage but cost more plasma (proportional to the amount of plasma stored)
/:cl:
=> Rebalance savage

code/game/objects/items/portable_vendor.dm, code/game/objects/machinery/vending/vending.dm
You can no longer nade vendor to get free stuff
Fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9162
Caused nade chaining to be catastrophical.
:cl:
del: Remove vendor malfunction from explosions
/:cl:
=> Remove vendor malfunction

code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Title.
Restricting this ability to hivemind was a bad idea in retrospect. It's locking a fun ability that would suit well queen just to promote playing hivemind. Hivemind will still be better at controlling minions because of its ability to move around the map quickly, but queen should be able to tell minions where to go as well
:cl:
balance: Give queen the command minion ability
/:cl:
=> Give queen command minions

code/game/objects/effects/aliens.dm
fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9192
:cl:
fix: Acid splatter no longer damage dead marines
/:cl:
=> Acid splatter no longer damage dead marines

code/modules/projectiles/gun_helpers.dm
fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9213
Lasguns can now also use tactical reload
Split tactical reload in two : first you remove the mag, wich takes 0.25 seconds, then you add the new mag which takes 0.25 seconds. Overall, this takes as much time than the current tactical reload.
Bonus: you can also use tactical reload on a empty gun and it will be twice as fast as currently
tacticool reload
:cl:
qol: Laser guns can now use tactical reload
fix: No longer possible to stack ammo with tactical reload exploit
/:cl:
=> Allow lasgun to tactictal reload and prevent tactical reload exploit

code/game/verbs/ooc.dm, code/modules/admin/holder.dm, code/modules/admin/preferences_verbs.dm
Makes admin color dependent of R_COLOR Perms, and removes its need for showing the color for any staff(useless)
Closes #9212 
:cl:
admin: now roles with rights to color changing will have access to change their color and show it as opposed to all showing but only changing with rights to  R_FUN
/:cl:
=> OOC Color rights fix

code/game/data_huds.dm
Time to bring back #8599 from the dead.
This PR changes STAMINA_RATIO_PAIN_HUB from 0.5 to 0.25.
From Bravemole, 
"Pain hud is actually (unlike what you are saying) 25% pain 100% health, 50% stamina. Pain IS an important information because it slows down you a lot, and cause stagger."
Xenomorphs see health bar based off of such variables, and it's time to make xenomorphs' life a little easier.
Xenomorphs see marine's health bar, xenomorphs make choices off of marine's health bar.
:cl:
balance: xenomorphs' pain hub on marines are less reliant on stamina damage.
/:cl:
=> Xeno health hud buff 2.0

code/modules/projectiles/ammo_datums.dm
Removes screenshake from A19/TX-8 Scout Rifle impact ammo. Slowdown, stagger, and knockback are the same.
#8760, but #8744 reverted this PR. Git played Hyper and xenomorphs.
This should have been nerfed but didn't. I blame Git.
:cl:
balance: Deletes screenshake from A19 impact.
/:cl:
=> Nerfs A19 Impact Ammo 2.0

code/game/objects/items/weapons/twohanded.dm, code/modules/reqs/supplypacks.dm
- Removed stagger so xeno abilities are not interrupted; 
- Made Queen protected from stun because she's the Queen;
- Price increased from 50 to 60 points.
Based on feedback, i'm nerfing it a bit. 
:cl:
balance: rocket hammer balance pass
/:cl:
=> Rocket hammer balance pass (nerf)

code/game/objects/machinery/vending/marine_vending.dm
Per title.
Tesla already exists, and M40-T smoke has been in a rather questionable spot balance-wise. Drain gas is being reduced in general, in favor of Tesla being kept as a free weapon in vendors.
:cl: Lewdcifer
balance: Drain gas nade box removed from requisitions's vendor.
/:cl:
=> Removes M40-T box from reqs vendor

code/game/objects/structures/dropship_ammo.dm
Per title.
50 points is a very laughable cost. Also, drain gas is being reduced/nerfed in favor of Tesla being kept as a free weapon.
:cl: Lewdcifer
balance: CAS tanglefoot rocket cost 50 > 150.
/:cl:
=> Increases cost of Tanglefoot CAS rockets

code/modules/projectiles/ammo_datums.dm
Per title.
At Bravemole's request, more than anything. Screenshake's pretty wack, anyway.
:cl: Lewdcifer
del: Projectile screenshake removed.
/:cl:
=> Removes all instances of screenshake on projectiles

code/game/objects/machinery/vending/vending_types.dm
Removes the contraband of wall mounted nanomed and update normal inventory to include removed yet still relevant chems.
Contraband is a leftover mechanic from SS13. Wallmounted Nanomeds are there for marines to get a quick heal/resupply which you can't do unless an engi first repairs power then hacks a nanomed. This hopefully makes both repairing power and using combat injectors more popular
Also removes hyperzine since it no longer exists
:cl:
del: Moved wallnanomed contraband inventory to normal inventory, removed hyperzine
/:cl:
=> Wall Nanomed Contraband Removal

code/modules/reagents/machinery/chem_dispenser.dm
Title.
Bihexajuline is a chemical that causes extreme pain and fixes bones at cryogenic temperatures. It's the juice that provide the SNAP CRACKLE POP in cryotube.
Milk is required to make this. I'm not sure why, but it does. Maybe bone likes cold milk, not room-temperature milk. Only Sulaco and Theseus have /obj/item/reagent_containers/food/drinks/milk , which hinder PoS and Minerva from producing bihexajuline.
Can also add this in chem dispenser.
:cl:
add: add milk in soda dispenser
balance: marines have access to milk; JUICE UP, BOYS AND GIRLS!
qol: you can finally make Bihexajuline in all shipside maps; if there isn't a soda dispenser nearby medical, I will change that in another PR.
/:cl:
=> add milk in soda dispenser

code/controllers/configuration/entries/general.dm, code/controllers/subsystem/timer.dm
Ports fixes below:
https://github.com/tgstation/tgstation/pull/59718
https://github.com/tgstation/tgstation/pull/63427
https://github.com/ss220-space/Paradise/pull/539
More chances for smooth experince
:cl:
fix: Ported fixes of SStimer subsystem from RU SS220 Paradise
config: Added a new config var: flag/log_timers_on_bucket_reset
fix: fixed potential bucket corruption in timer reset_buckets
fix: timers not removing from second queue on init
/:cl:
=> Fix: port SStimer fixes
