tgstation/TerraGov-Marine-Corps

code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Title
:cl:
fix: Fix larva dying when hijacking
/:cl:

Fix larva dying when hijacking

---

code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
code/modules/mob/living/carbon/xenomorph/castes/king/king.dm

Nightfall has lower CD and higher range
Crush has lower windup (1sec), but canceling it cost plasma
Young king get grav crush
Spam cancelling gravity crush is bad, and this prevents it (and the windup was too big anyway, too easy to dodge if you were not spam cancelling)
Nightfall is not as cancer as some said, it's barely usefull right now, so let's buff it to make it usefull
Young king is stupidly weak if you consider its price, and it takes ages to get to mature. It should not be that useless when spawning, and giving it grav crush when spawning will fix that a bit
:cl:
balance: Nightfall; better range and lower CD
balance: Gravity crush; higher plasma cost, lower windup, canceling the windup consumme the plasma
balance: Young king get grav crush
/:cl:

Buff king abilities + Young king get grav crush

---

code/game/objects/items/bodybag.dm

Alien Slashes Now Attack Bodybag Occupants
Alien Slashes Now Attack Bodybag Occupants
:cl:
fix: Alien slashes now hit bodybag occupants.
/:cl:

Alien Slashes Now Attack Bodybag Occupants

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm

Title + shortened duration for king to spawn, to account for the time the xeno will take to get to the pod
Prevent funny ghosting just to get king
:cl:
balance: The king is selected among live xenos
balance: I takes 5 minutes for the king to spawn, rather than 10 
/:cl:

King is selected among live xenos

---

code/controllers/subsystem/vote.dm

Less loud
That noise is way louder than the rest and it hurts my ears
:cl:
fix: Lowered the vote noise.
/:cl:

Lower the 'Vote started' sound volume

---

code/datums/weather/weather.dm

Title
Save everyone ears
:cl:
sound: Weather sounds less loud
/:cl:

Weather sounds less loud

---

code/datums/jobs/job/terragov.dm

Will tell you which faction you spawned in
:cl:
expansion: Inform you on which faction you are on when spawning in HvH mode
/:cl:

Flavour text for HvH

---

code/modules/projectiles/guns/rifles.dm

Simply put, i felt that this ERT was a bit of a pushover, especially given how they do not really have a magnetic harness in case they get knocked down.
Plus, they are freaking aliens with advanced technology! Their stuff should be good!
:cl:
balance: Slightly increase sectoids fire rate.
/:cl:

Slightly buff the fire rate of sectoids rifle.

---

.vscode/settings.json
code/datums/skills.dm

FC get more basic skills
FC should not be the powergamer role it is now. 
:cl:
balance: FC has less skill in pistols and melee
/:cl:

Remove a lot of skills from FC

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

Endure CD increased to an effective 50 seconds of cooldown
Endure makes ravager way too safe, and fifty seconds of effective cooldown isn't really that long in TGMC, and I doubt you can be caught off guard that often, I think the hardstats on endure are perfectly fine but the CD should be higher.
:cl:
balance: Endure has 60 second cooldown, effective 50
/:cl:

endure has a higher cd

---

tools/bootstrap/node.bat

Hopefully helps with the Juke Build
<!-- Describe The Pull Request. Please be sure every change is documented or this can delay review and even discourage maintainers from merging your PR! --

Updates the bootstrap node.bat to be more in pair with /tg/

---

code/__DEFINES/dcs/signals.dm
code/datums/keybinding/human.dm
code/modules/mob/living/carbon/give.dm
code/modules/mob/living/carbon/human/human.dm

Give keybind + refactor
Macro begone
:cl:
add: Give keybind
/:cl:

Give keybind

---

code/game/objects/items/weapons/twohanded.dm
code/modules/client/client_defines.dm
code/modules/projectiles/gun_system.dm

Kill macros
Macros are bad. Cheating is not allowed on this server
:cl:
del: Macros have been disabled to avoid server lag and abuse
/:cl:

Kill macros

---

code/_onclick/click.dm
code/datums/weather/weather.dm

Better xeno ability targeting code, should do what the players want 99% of the time while still allowing easier targeting
:cl:
code: Targeting code should allow players to use xeno abilities on the desired target more easily 
/:cl:

Fix targeting code

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/specialist.dm

Less knockback
+150 more damage
Much higher stagger
20 more sundering
40 force when meleeing
1 second less of wield delay.
-19 seconds of fire delay (that a lot)
Makes the railgun viable, hopefully.
:cl:
balance: railgun deals 250 damage from 150, does 90 sundering, 40 force when hitting someone with it, 1 second less of wield delay, and has much higher stagger. 1 seconcd fire delay from 20.
/:cl:

railgun deals more damage and sunder, has MUCH less fire delay, and has more stagger effects

---

code/game/objects/structures/xeno.dm

Title.
Fun?
:cl:
expansion: Hivelord can apply resin jelly to xenos by throwing it at them.
/:cl:

Hivelord can apply jelly via throw

---

code/game/objects/items/storage/fancy.dm
code/game/objects/items/tools/flame_tools.dm

Fixes a typo causing the bicardine cig dissapear when lit.
:cl:
fix: fixed bicardine cigarette sprite dissapearing when lit
/:cl:

Fix bicardine cigarette sprite dissapear when lit

---

code/modules/mob/living/carbon/human/human_attackhand.dm

Gives some additional vague information in self examine based on the presence of oxyloss and toxin damage. 
Just a little bit more information for people. 
:cl:
expansion: Self examine gives a bit more info.
/:cl:

Improved self examine

---

code/__DEFINES/dcs/signals.dm
code/_globalvars/lists/abilities.dm
code/datums/keybinding/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
tgmc.dme

Emit Gas now activates immediately when selected.
Radial mode support added for Defiler reagent swapping in addition to existing cycling options.
Refactored Defiler reagent selection.
Improves Defiler QoL.
:cl:
qol: Emit Gas now activates immediately when selected.
qol: Radial mode support added for Defiler reagent swapping in addition to existing cycling options.
code: Refactored reagent selection.
/:cl:

Defiler Control QoL

---

.github/ISSUE_TEMPLATE/bug_report.yml

Update bug_report.yml description

---

code/modules/projectiles/gun_system.dm

No hard del protection was present

Hard del protection on gun user

---

code/game/objects/items/binoculars.dm
code/game/objects/machinery/overwatch.dm
code/game/objects/machinery/squad_supply/supply_beacon.dm
code/game/objects/structures/orbital_cannon.dm

- Moved the AI notifications to the devices who call the fire. This is to get around the delay that they apply.
- The AI now knows which warhead has been fired.
-  Adds the warhead type to admin logs too.
- Added a little noise (triple beep) to improve the AI soundscape.
- Added some missing periods(?) to the end of some sentences in the beacon.
:cl:
qol: Added some noises for the AI whenever the OB is fired.
qol: Added the OB warhead type to AI notifications
fix: typos in beacon code.
fix: improved some backend stuff so the AI is warned before everyone else
/:cl:

Improves the orbital canon AI notifications.

---

code/modules/mob/living/silicon/ai/ai.dm

The AI can sees current cargo points in their tab.
Saves on returning to your core and hovering to cargo. No new info, just streamlined.
Plus, they are literally plugged in the ship, they should know.
Did you know the AI cannot see any fire, power or atmospheric alarms? There isn't code for it!
:cl:
qol: The AI can now see current supply points within their game tab.
/:cl:

The AI now has points on a hot tab.

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Especially fixes the weird req outgrowth into the hallway.
Also move a camera onto a wall instead of onto a vendor.
It makes fire alarms less weird.
:cl:
fix: reshape some areas to fit fire alarms better.
/:cl:

Fix some areas looking weird on the POS

---

code/modules/reqs/supplypacks.dm

Railgun reduced to 40 from 75, as at 75 you mightas well get a SADAR
AMR/IFF snipper reduced by ten
1 use rpg reduced to 5
Makes lesser used req stuff more appealling
:cl:
balance: Reduced the price of the Railgun, IFF/AMR snipers and 1 use RPGs in req
/:cl:

Reduces the prices of some req guns

---

code/game/objects/items/radio/headset.dm

Cocoon was breaking it + runtime when putting the radio fixed
:cl:
fix: Fix undefibbable icons on minimap
/:cl:

Fix undefibbable icons on minimap

---

code/__HELPERS/_lists.dm
code/controllers/subsystem/points.dm
code/datums/chatmessage.dm
code/modules/reqs/supply.dm

HvH req should work now
You can buy cool stuff to kill the opposite side
:cl:
fix: Fix HvH req
/:cl:

Fix HvH req

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/Sulaco.dmm
code/game/objects/structures/window.dm

More windows, a camera and a dream.
Makes the AI slightly less weak. Slightly.
:cl:
add: AI core strengthened on the Pillar of Spring
/:cl:

Add strong windows and a camera to the POS AI core.

---

code/modules/client/preferences_savefile.dm
code/modules/client/preferences_ui.dm

Forgot to save keybinds, because i'm dumb
:cl:
fix: Keybinds are saving now
/:cl:

Fix keybinds not being saved[CRITICAL]

---

code/modules/client/preferences_ui.dm

closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7274
:cl:
fix: Fix be special settings (EORD, etc) not showing on tgui
/:cl:

Fix be special settings (EORD, etc) not showing on tgui

---

code/modules/shuttle/mini_dropship.dm

Fix the bug that happened when two people use the console at the same time, one was stuck in tadpole camera mode
:cl:
fix: Fix perspective bug with tadpole
/:cl:

Fix perspective bug with tadpole

---

code/modules/projectiles/guns/shotguns.dm

combat shotgun can be fired one handed 
a much needed buff to a near useless gun
:cl:
balance: you can fire the combat shotgun one handed
/:cl:

combat shotgun can be fired one handed

---

code/modules/client/client_procs.dm

Update max version to 1557

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7273
:cl:
fix: Fix Eviscerating Charge Keybind
/:cl:

Fix Eviscerating Charge Keybind

---

code/modules/admin/panels/player_panel.dm
code/modules/admin/topic.dm

This is mostly for admins, but jeez. How was this not added before.
Things easier for admins.
:cl:
admin: add the hivemind to player transform
/:cl:

Add the hivemind to the player panel menu.

---

config/config.txt

Title
Not need to git ignore localy config to have widescreen

Widescreen on local

---

tgui/packages/tgui/components/Button.js

Better system to register keybinds, more intiutive
:cl:
qol: Better keybind registering system
/:cl:

Better keybind registering system

---

code/game/objects/structures/xeno.dm

Fixes a minor bug with acid well deconstruction.
Fixes a minor bug with acid well deconstruction.
:cl:
fix: Missing return added to Acid Well dismantle code.
/:cl:

Adds Missing Return to Acid Well Dismantling

---

code/modules/client/client_procs.dm

Port of https://github.com/tgstation/tgstation/pull/60079
No really it's tg code just ported over from that linked PR: https://github.com/tgstation/tgstation/pull/60079
Seriously go look at their files if you doubt me https://github.com/tgstation/tgstation/blob/master/code/modules/client/client_procs.dm#L446-L449
Ported tg fix.
:cl:
fix: Fixed all clients being forced to Fit Viewport on connect regardless of their Auto Fit Preference.
/:cl:

Ports tg forced Fit Viewport on connect fix

---

code/game/objects/machinery/computer/camera_advanced.dm
code/modules/shuttle/navigation_computer.dm

Title. WTF lakiller 
closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7261
closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/6862
:cl:
fix: Fix tadpole eye going to null space
/:cl:

Fix tadpole eye going to null space

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Just an extra missing light.
:cl:
fix: Add a missing light to POS starboard hallway.
/:cl:

Add a missing light to one of POS hallway.

---

code/__DEFINES/traits.dm
code/game/objects/items/bodybag.dm
code/modules/projectiles/gun_system.dm

closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/6943
:cl:
fix: Cannot shoot while tarping anymore
/:cl:

Fix tarp shooting

---

code/modules/projectiles/guns/shotguns.dm

I broke Double Barrels. 
Fixes Double Barrels
:cl: The Fuckup: Hyper2Snyper
fix: Fixes Double Barrels
/:cl:

Fixes Double Barrels and Martini

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7335
Easier targeting for banish wasn't a good idea after all
:cl:
fix: Wraith banishing no longer auto-target humans rather than cades or nades
/:cl:

Fix wraith banish targeting

---

code/datums/gamemodes/game_mode.dm
code/datums/round_statistics.dm
code/game/objects/items/defibrillator.dm

Adds stat tracking for human deaths and revives.
More accurate data before I overnerf revives to see if it's actually needed first.
Additional statistics!
:cl:
expansion: Human deaths and defib-based revives now are logged as a statistic.
/:cl:

Deathstats

---

_maps/map_files/Sulaco/Sulaco.dmm

As the title says.
:cl:
add: Added a map table to the Sulaco CIC.
/:cl:

Add a map table to the sulaco CIC.

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

This is to fix a strange issue where some fire alarms have no effect.
:cl:
fix: fixes a few missing fire alarms doors on POS.
/:cl:

Add some fire alarms to the firing range of POS.

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

One in the hangar, one north of the shooting range, one in medical maintenance.
:cl:
add: Add some water tanks to the water scarce POS.
/:cl:

Add a couple water tanks to the POS. There is only one in the ship at the moment.

---

code/game/objects/items/storage/storage.dm

closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7346
Also make it so the visual changes (moving the item from the bag to the ground, for exemple) happen only when the check is finished. How it is done currently is a bit weird, this is more realistic
:cl:
fix: Fix being able to queue multiple items draw from backpacks
/:cl:

Fix being able to queue multiple item draws from backpacks

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/pistols.dm
code/modules/projectiles/magazines/pistols.dm

45/15/3, staggers, slows, no shake however.
Consdering the automag has one second fire delay, it has a 1.2 dmaage mult for 54 damage.
Considering these guns fire incredibly slowly I don't think this is too much damage.
The automag and deagle sucks.
:cl:
balance: buffed automag and deagle to do much more damage, stagger and slow xenos on hit
/:cl:

buffs the automag and deagle by giving them their own bullet

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Also move some cameras who were stuck on doors or floating in mid air on POS.
Less tedium, result remains the same. 
Prettier ship too.
:cl:
qol: Made the OB room on POS less bad. Did you notice POS sounds like something rude?
fix: Fixed some oddly placed or oriented cameras on the POS.
fix: Fixed a few floating lights and APC's
/:cl:

Switch things around in the OB room to not be CBT. 

---

code/__DEFINES/layers.dm
code/game/objects/machinery/hologram.dm

This changes the layer to 2.52, where catwalks are layered to 2.51
Less ugly and it makes my brain do happy chemicals
:cl:
fix: Change the holopad layer so it renders above catwalks
/:cl:

Make the holopad layer above catwalks.

---

code/modules/mob/mob_verbs.dm

The logic was inverted
:cl:
fix: Admin respawn bypass is now logged in the correct cases
/:cl:

Fix admin respan logging

---

code/modules/projectiles/guns/specialist.dm

Makes impact grenades work with the T-81. Fixes #7386 
It fixes a bug! Hurray. 
:cl:
fix: Impact grenades work with the T-81 launcher. 
/:cl:

T-81 impact grenade fix

---

code/datums/loadout/loadout_helper.dm

Fix runtime when using the loadout vendor as a non-squad role (try to access a null list). Players won't notice this
:cl:
fix: Loadouts vendor will no longer runtime when equipping a loadout as a non squad role
/:cl:

Loadout runtime fix

---

.github/workflows/stale.yml

Contributors have 7 days befofe label + 3 days after
Less dead prs in the tracker
Github

Change stale autoclose from 7 days to 3

---

code/game/objects/items/storage/boxes.dm
code/modules/mob/mob.dm

fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7375
:cl:
fix: Fix quick equip not respecting storage delay
/:cl:

Fix quick equip not respecting storage delay

---

code/controllers/subsystem/job.dm
code/datums/jobs/job/xenomorph.dm
code/modules/admin/topic.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

fixes https://github.com/tgstation/TerraGov-Marine-Corps/pull/7136/files not working at all
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7316
:cl:
fix: Fix observers not being able to spawn when no silos are there in distress before shutter drop
fix: Fix larvas spawning outside silos when there are silos
/:cl:

Fix larva spawn in silo PRs 

---

code/__DEFINES/mobs.dm
code/game/objects/effects/aliens.dm

Fixes corrosive acid melt times, and the adjustment for processing times.
Fixes corrosive acid melt times, and the adjustment for processing times.
:cl:
fix: Fixes corrosive acid melt times, and its processing time adjustment, considerably faster like it was before.
/:cl:

Fixes Corrosive Acid Melt Times and Process Time Adjustment Math

---

code/__DEFINES/dcs/signals.dm
code/datums/keybinding/human.dm
code/modules/projectiles/gun_helpers.dm
code/modules/projectiles/gun_system.dm

Title
:cl:
expansion: Add a gun safety keybind
/:cl:

Add a gun safety keybind

---

code/game/objects/machinery/vending/new_marine_vendors.dm

fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7417
Also remove unused essential kits that induced me in error
:cl:
fix: SL have its medhud back in essential kits
/:cl:

Fix SL medhud

---

code/modules/reqs/supplypacks.dm

fix
fix
:cl:
fix: smartrifle magazines pop up in req
/:cl:

smartrifle pack fix

---

code/modules/shuttle/shuttle_rotate.dm

It rotates too now
Prettier
:cl:
fix: Fix shuttle windows not rotating
/:cl:

Fix shuttle windows not rotating 

---

code/__DEFINES/admin.dm
code/modules/admin/fun_verbs.dm
code/modules/admin/topic.dm
code/modules/admin/verbs/adminhelp.dm

Replaces the mentor ghost check with a confirmation warning them of losing their previous body, and fixes it ghosting non mentor admins regardless of if the target mob can take the IF or not.
Admin QOL
:cl:
admin: Added a button to become an Imaginary Friend to the ticket panel.
/:cl:

Adds a button to become an Imaginary Friend to the ticket panel, and log their creation to active tickets

---

code/modules/mob/living/carbon/xenomorph/castes/king/king.dm

Title
:cl:
fix: Larvas cannot become king anymore
/:cl:

Larvas cannot become king anymore

---

interface/stylesheet.dm
tgui/packages/tgui-panel/styles/goon/chat-dark.scss
tgui/packages/tgui-panel/styles/goon/chat-light.scss

For some reason noone added the userdanger spans?
:cl:
fix: certain player messages will now appear large and red correctly
/:cl:

Fix userdanger messages

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

removes duplicated pipe on Pos
less pipenet warnings

Fixes pos pipenet

---

code/game/objects/machinery/sentries.dm

Title
:cl:
fix: Fix premade sentries IFF (tadpole, canterbury, fob drone, etc...)
/:cl:

Fix premade sentries IFF

---

code/modules/projectiles/guns/rifles.dm

fix
fix
:cl:
fix: t-25 iff
/:cl:

fix t-25 not having iff

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Per title.
Per title.
:cl:
fix: Minor text fix for the Wraith's Place Warp Shadow ability.
/:cl:

Minor Text Fix For Place Warp Shadow

---

code/controllers/subsystem/persistence.dm
code/controllers/subsystem/ticker.dm
tgui/packages/tgui-panel/styles/goon/chat-dark.scss
tgui/packages/tgui-panel/styles/goon/chat-light.scss

Adds roundstart announcement containing the current season for each season group, current season name and description.
It is more clear what seasons are active at roundstart.
:cl:
qol: Added active seasons announcement, changed seasonal buckets names/descriptions to be more flavourful
qol: Added tgchat format styles
/:cl:

Adds seasonal system roundstart announcement

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

This mostly fixes the drop pod room.
More consistent.
:cl:
fix: fixed some walls of the POS being outerhull instead of being hull.
/:cl:

Remplace some weird bits of outerhull in the POS

---

code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm

Runner has an extreme issue dealing with melee bump enemies such as vali, and I think personally that it should have higher armor protection against these enemies, as it can't evade them at all.
Runner can't really do anything against a vali shield so it should get more protection against a vali shield.
:cl:
balance: runner has higher melee armor now.
/:cl:

Runner has higher melee armor

---

code/game/objects/machinery/doors/airlock.dm
code/modules/mob/living/silicon/ai/ai.dm

This allows the AI to interact with groundside electronics. Just like on the ship basically. 
Some people asked for a test merge, especially so the AI has something to do groundside. 
:cl:
balance: Allows the AI to interface with groundside equipment
/:cl:

Allows the AI to have interactions across Z levels.

---

code/game/objects/items/reagent_containers/glass.dm
code/modules/reagents/reactions/medical.dm
code/modules/reagents/reagents/medical.dm

Adds bihexajuline, a medicine for fixing broken bones while in cryo. Overdose causes all your bones to break. Puts some in the starting cryo mix. Recipe is 2 bicaridine, 1 milk, 2 iron for 5 bihex.
Keeps crunch tube functioning if #7353 is merged, but shifts it into a mixable chem with proper functionality. 
:cl:
add: Added bihexajuline for treating broken bones in cryo. Recipe is 2 bicaridine, 1 milk, 2 iron
add: Put bihexajuline in the starting cryo mix
/:cl:

Adds bihexajuline

---

code/datums/gamemodes/civil_war.dm

Enable this role in civil war
We now have the iff tech, so this is possible
:cl:
add: SG is added in civil war
/:cl:

Enable SG on civil war

---

code/game/data_huds.dm

fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7362
:cl:
fix: Fix hud going DNR when ghost leave body
/:cl:

Fix DNR hud when ghost leave body

---

code/datums/loadout/item_representation/_item_representation.dm
code/datums/loadout/loadout.dm
code/datums/loadout/loadout_helper.dm
code/modules/buildmode/submodes/loadout.dm

Iff signal and access can be customised on the id before saving
Job (so the title, the rank, the skillset) and headset are hardcoded (if the path doesn't exist in the code, it won't save anything). So you can't make custom jobs
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7467
:cl:
expansion: Loadout tools will now save job title, id's access and iff signal, and headset
/:cl:

Loadout tools will now save job title, id's access and iff signal, and headset

---

_maps/map_files/Twin_Pillars/Twin_Pillars.dmm
code/_globalvars/lists/typechache.dm

Change some vendors that were mixed, prevent people from buying PAS.
Also, add some sec vendors to the ship, because apparently people like to have handcuffs
:cl:
fix: Fix coloring in hvh
add: Give sec vendors in hvh, so admins don't have to spawn handcuffs
/:cl:

Fix coloring in hvh

---

code/datums/jobs/job/marines.dm

Standard rebel marine needed an outfit in order to have the right iff signal
:cl:
fix: Fix iff for standard rebel marine
/:cl:

Fix iff for standard rebel marine

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/projectiles/guns/rifles.dm

Scope removed, fun is not allowed here
This gun should not be in hvh with a scope
:cl:
balance: Remove the scope from TX_11 in hvh
/:cl:

Remove the scope from TX_11 in hvh

---

code/game/objects/machinery/doors/shutters.dm

Title
:cl:
fix: Fix shutters being crushable by tadpole
/:cl:

Fix shutters being crushable by tadpole

---

code/modules/projectiles/gun_system.dm

fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7332
YOUR MOVE ZACK
:cl:
fix: Minigun no longer has aimbot
/:cl:

Fix minigun aimbot

---

code/modules/projectiles/gun_system.dm

Runtime will happen when no attachments
:cl:
fix: Fix runtime in gun system
/:cl:

Fix runtime in gun system

---

code/game/objects/items/explosives/mine.dm

Title
:cl:
fix: Fix mines not blowing up xeno
/:cl:

Fix mines not blowing up xeno

---

code/modules/reqs/supplypacks.dm

See title. Decrease is from 7 to 6. Not huge, but it might be enough to change things a little.
:cl:
balance: Very slight reduction in price of HE and WP sadar rockets, with the aim of varying ammo usages.
/:cl:

Lower the price of sadar WP and HE by 1 point, so we see something besides AP for once.

---

code/__DEFINES/dcs/signals.dm
code/controllers/subsystem/minimaps.dm
code/datums/keybinding/mob.dm

Title
:cl:
qol: Keybind for minimap
/:cl:

Keybind for minimap

---

code/game/turfs/space.dm

Title
Tivi bad
:cl:
fix: Fix prison being in space instead of the ocean
/:cl:

Fix prison being in space

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
_maps/map_files/Twin_Pillars/Twin_Pillars.dmm

Weapon , med, armor and clothes vendor added in req
More convenient for ROs
:cl:
qol: Add some vendors in req
/:cl:

Add some vendors in req

---

code/game/objects/items/radio/headset.dm

For exemple, rebel SL did not have their command channel. This is the fix
:cl:
fix: Fix rebel squadies not having all their comm channels
/:cl:

Fix rebel squadies not having all their comm channels

---

code/modules/projectiles/guns/specialist.dm

Fixes the issue with T-72's description not matching its caliber. 
Things should match up. Just ask Byoo. 
:cl:
spellcheck: Fixed a typo in the T-72 disposable rocket launcher description. 
/:cl:

T-72 wording fix. 

---

code/__DEFINES/loadout.dm
code/game/objects/machinery/vending/new_marine_vendors.dm

fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/7555
Move the sg items from essential sets to points system, so it's handled by the loadout vendors without any issue
Damn you mjp
:cl:
fix: Smartrifle are available in loadout vendors
/:cl:

Fix smartgunner loadout vendors

---

code/game/objects/items/storage/belt.dm

mp belt no longer holds pistols
this is like not okay at all
:cl:
fix: mp belt no longer holds pistols
/:cl:

mp belt no longer holds pistols

---

code/modules/atmospherics/machinery/components/unary_devices/cryo.dm

Most of the information is in the title.
Still can't put people in it, just turn it on.
:cl:
expansion: Allow the AI to access cryo cells.
/:cl:

Allow the AI to access cryo cells. Seems like an oversight.

---

code/modules/projectiles/guns/specialist.dm

Title. Closes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/7520
:cl:
fix: Fix minigun safety
/:cl:

Fix minigun safety

---

code/datums/emergency_calls/clf.dm

This simple PR brings back the CLF. It was deactivated, but i do not see any reason why we shouldn't be able to see them.
More ERT's is fun.
:cl:
add: Brought back the CLF ERT to life.
/:cl:

Reactivates the CLF ERT

---

code/__DEFINES/obj_flags.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/mob/living/carbon/xenomorph/charge_crush.dm
code/modules/power/smes.dm
code/modules/power/smes_construction.dm

Warrior punch didn't check resist flags using bitmath and crusher charge only checked for indestructible.
Can't check for unacidable for crusher charge because theres a lot of things that cant be melted but should be crushable.
:cl:
fix: Warrior punch no longer allows you to destroy many machines that can not otherwise be damaged
fix: Crushers can no longer destroy SMESes
/:cl:

Fix two xeno exploits

---

code/__DEFINES/dcs/signals.dm
code/game/objects/items.dm
code/modules/projectiles/gun_system.dm

title. Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7492
:cl:
fix: Should prevent HSG to keep firing after you released mouse button
/:cl:

Force to stop shooting your gun when unscoping

---

code/modules/projectiles/gun_attachables.dm

.2 instead of .5 like a gyro, should hopefully make the vgrip a more viable choice in peoples loadouts.
hopefully will give people a reason to run this over agrip, and if rds buff is merged will lead to more variable loadouts.
:cl:
balance: vgrpi helps you move moderately faster in aim mode, not as much as a gyro, however.
/:cl:

vgrip makes you faster in aimed mode

---

code/modules/projectiles/gun_system.dm

One signal was not unregistered properly, and crashing while firing cause a runtime because the client is null, which can cause the gun to malfunction when reconnecting
:cl:
fix: fixes some gun runtimes that would render the gun innoperable.
:cl:

Runtimes in gun system fix

---

code/__DEFINES/span.dm

Span define was missing a '
Fixes #7608 
'
:cl:
fix: Health analyzers should quit their nonsense now
/:cl:

Fixes health analyzers

---

code/__DEFINES/mode.dm
code/datums/jobs/job/job.dm

Silos are a bit weak compared to king and such, this makes a more interesting choice.
Long game are started to become too marine favored, this balance late game a bit. 
:cl:
balance: Silo produces 18% more
/:cl:

Silo output buff

---

_maps/shuttles/alamo.dmm

Fix good, Bugs bad
Changelog
:cl:
fix: fixed a missing camera on the alamo
/:cl:

Returns a missing camera from the alamo, so i do not have to stare at a dirty, fuzzy line of three blocks.

---

code/_onclick/ventcrawl.dm

Per title.
Removes unaddressed merge garbage.
:cl:
fix: Merge garbage for ventcrawling fixed.
/:cl:

Fixed Merge Garbage From Vent PR

---

code/game/objects/items/storage/marine_boxes.dm
code/game/objects/machinery/vending/marine_vending.dm

Everything is in the title. This fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7621
:cl:
fix: fixed some typos regarding the T 29 crate
/:cl:

Fixes the T-29 being called the T-26, as well as the T-25 being calledd the T-26

---

code/modules/modular_armor/helmets.dm

yes its that exploit
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/4746 
:cl:
fix: fixed a helmet binoc exploit, it doens't let you shoot while zoomed anymore.
/:cl:

helmet binoc exploit fix

---

code/datums/components/overlay_lighting.dm

https://github.com/tgstation/tgstation/pull/60239
https://github.com/tgstation/tgstation/pull/60336
Ports what I PRed to TG
:cl:
refactor: Movable Lighting will perform better now
/:cl:

Overlay lighting vis obj -> underlays

---

code/modules/admin/verbs/pray.dm

This put the verb on /client/ instead of /mob/
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7571
:cl:
qol: Allow everyone to pray!
/:cl:

Allow everyone to pray

---

code/__DEFINES/dcs/signals.dm
code/datums/components/largeobjecttransparency.dm
code/datums/elements/light_blocking.dm
code/game/area/area.dm
code/game/area/general.dm
code/game/area/sulaco.dm
code/game/atoms.dm
code/game/atoms_movable.dm
code/game/objects/effects/aliens.dm
code/game/turfs/open.dm
code/game/turfs/open_ground.dm
code/game/turfs/snow.dm
code/game/turfs/space.dm
code/game/turfs/space/transit.dm
code/game/turfs/turf.dm
code/modules/assembly/infrared.dm
code/modules/atmospherics/machinery/atmosmachinery.dm
code/modules/mob/mob.dm
code/modules/xenomorph/xeno_structures.dm

See https://github.com/tgstation/tgstation/pull/59910/files
https://github.com/tgstation/tgstation/pull/59658/files
for what this does
I tested this a bit but a tm wouldnt hurt
:cl:
refactor: Backend movement changes
/:cl:

Port movement proc multitile improvements

---

code/controllers/subsystem/minimaps.dm
code/modules/mob/living/silicon/ai/ai.dm

This is reworking this previous PR : 
https://github.com/tgstation/TerraGov-Marine-Corps/pull/7279
I tried to force push towards it, but it keeps giving me some errors, so forgive me for opening another. Hopefully this will not break on integration tests.
This makes the thing actually work
:cl:
add: Give the AI a minimap. Rejoice.
/:cl:

Try to give the AI an AO minimap.

---

code/modules/xenomorph/xeno_structures.dm

Title. It was intended in last PR but i added a wrong flag
:cl:
fix: Fix resin holes not dying off weed
/:cl:

Fix resin holes not dying off weed

---

code/datums/jobs/job/special_forces.dm

This PR gives the SAS some NVG's and combat injector. 
This fixes their utter lack of lights, and it makes them a little different from other ERT's.
I do not believe this will make them overpowered, given their lack of firepower. 
:cl:
balance: gave the Special force ERT NVG's and combat injectors 
/:cl:

Update the SAS

---

code/game/objects/structures/dropship_ammo.dm

gives SOME indication one has been fired.
clearance good
:cl:
tweak: CAS fired flares have a slight yellow tint to the light
/:cl:

CAS fired flares get a slight yellow tint to them

---

code/game/atoms_movable.dm
code/modules/mob/living/carbon/xenomorph/charge_crush.dm

Forgot about dual definitions
:cl:
fix: Fixed crusher charging
/:cl:

Fix crusher charging

---

code/modules/mob/living/carbon/xenomorph/evolution.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Fixes #7637 
Fixes #7638 
:cl:
fix: fixed evolving/regressing not working with xenos with different plasma mechanics, now they account for their plasma regen limit.
/:cl:

Fixes regress/evolve for xenos that use plasma_regen_limit

---

code/game/objects/machinery/doors/firedoor.dm

Title describes it all
:cl:
qol: sound for the firelocks welding
/:cl:

Make it so there is a welding sound when you weld a firelock

---

code/game/objects/machinery/vending/marine_vending.dm

-1 instead of 1
dyslexia
:cl:
fix: the TGMC finally sent out it's new edition of flareguns, the E2, you no longer only have one exactly flaregun as marine. But many.
/:cl:

fix flaregun vendor amounts

---

code/__DEFINES/monitor.dm
code/controllers/subsystem/monitor.dm
code/game/objects/structures/orbital_cannon.dm
code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
code/modules/mob/living/carbon/xenomorph/death.dm
code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm

Title
King is here, i changed the balance in psy points a bit, and i realised OB were not relevant in who is winning
:cl:
code: Update monitor balance calculation
/:cl:

Update monitor balance calculation

---

code/game/objects/items.dm

Double clicking on iitems in backpack instantly dropped them in the ground
:cl:
fix: Fix doube clicking items in backpack dropping them
/:cl:

Fix doube clicking items in backpack dropping them

---

code/game/atoms.dm
code/game/atoms_movable.dm
code/game/objects/machinery/doors/firedoor.dm
code/game/objects/machinery/doors/railing.dm
code/game/objects/machinery/doors/windowdoor.dm
code/game/objects/machinery/line_nexter.dm
code/game/objects/structures/barricade.dm
code/game/objects/structures/platforms.dm
code/game/objects/structures/razorwire.dm
code/game/objects/structures/tables_racks.dm
code/game/objects/structures/windoor_assembly.dm
code/game/objects/structures/window.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Title
:cl:
fix: fixed barricades being passable too often
refactor: refactored more movement code
/:cl:

Checkexit & Uncross now respects dir

---

code/modules/projectiles/gun_system.dm

Fix minigun having issues with sticky mouse button (you can shoot just with one click, rather than holding down mouse button)
:cl:
fix: Fix minigun able to shoot without holding the mouse button down
/:cl:

Fix minigun

---

code/modules/mob/living/carbon/xenomorph/attack_alien.dm

fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/7705
:cl:
fix: Fix slashing dead human lights
/:cl:

Fix slashing dead human lights

---

code/modules/projectiles/gun_helpers.dm

Converts "\<span class...\> \</span\>" to span macros that were missed in the great regex.
Doesnt affect anything in game.
No changelog. Doesnt change anything in game.

Converts Some Span Classes to Span Macros That Were Missed

---

code/__DEFINES/mode.dm
code/datums/gamemodes/game_mode.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Title.
No longer needed with the queue
:cl:
delete: Remove xeno respawn time
/:cl:

Remove xeno respawn time

---

_maps/map_files/Theseus/TGS_Theseus.dmm

The FCDR takes the basketball court spot. The AI takes the FCDR spot.
The basketball court takes the AI spot.
This is a PR made on behalf of Alterist.
Makes a tiny bit more sense, and the AI doesn't have to listen to the firing range as much.
:cl:
expansion:  Shifted a couple areas of theseus around to make more sense. Added some floor plates to the hangar to make it prettier./
/:cl:

Shoves the AI into a different corner of theseus

---

code/datums/loadout/loadout_manager.dm
code/modules/client/preferences_savefile.dm

Loadouts can be deleted
Seriously byond, why is it so hard to handle list
:cl:
fix: You can delete loadouts
/:cl:

Fix loadout deletion

---

code/datums/loadout/item_representation/_item_representation.dm

Remember to test your code kids
:cl:
fix: Loadouts vendor works again
/:cl:

Fix loadouts

---

code/modules/power/groundmap_geothermal.dm

This also adds an intact generator. You might want for a map or saving time on testing sometimes.
More consistent :)
:cl:
qol:  the AI can interact with colony generators :)
/:cl:

Allow the AI to turn on groundside generators like shipside ones, provided that they are intact.

---

_maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm

Numbers good
:cl:
qol: Added some LZ numbers to barrenquilla
/:cl:

Add big floor numbers to barrenquilla mining facility

---

code/__DEFINES/rust_g.dm
code/__DEFINES/rust_g_overrides.dm
code/modules/admin/SDQL2/SDQL_2_wrappers.dm
dependencies.sh
tgmc.dme

https://github.com/tgstation/tgstation/pull/60190/files
:cl:
code: TGUI has been optimized
/:cl:

Url encoding improvement

---

code/modules/projectiles/ammo_datums.dm

Shooting directly north is bugged. This fix.
Urak of the Blue Tribe fix bug. Make world strong. Ooga.
:cl:
fix: bonus projectile math when shooting directly up.
/:cl:

Mild bonus projectile fix

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/xenomorph/attack_alien.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Straight up deletes all mentions and usages of queen slashing permissions from the code.
Slashing permissions is an ancient relic from the CM era. The only use now is by griefers in the queen role, Im not going to mention names \*cough\* Striz \*cough\*, to deliberately neuter the hive. It is time to put down it's shambling corpse and lower it into the grave.
:cl:
del: Removed Queen slashing permissions.
/:cl:

Removes Queen Slashing Permissions

---

code/modules/projectiles/gun_attachables.dm

Makes red dot sight reduce aim mode fire rate debuff by 50%.
MJP said it's good, ask them if you have questions
Contender to magnetic harness for the rail attachment slot
:cl:
balance: red dot reduces fire delay from aim mode by 50%
/:cl:

Makes red dot sight reduce aim mode fire delay by 50%

---

code/game/objects/items/cocoon.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Fixes two bugs:
- Some xenos were spawning due to cocoon releasing when the alamo was hijacking, and were immediatly killed 
- If there is no silos shipside, you can manage to spawn groundside. This doesn't fix totally the issue, since you still will be able to spawn from lobby, but that's an improvement
:cl:
fix: Fix larva spawning groundside while the hive is hijacking
/:cl:

Fix larva spawning

---

code/modules/projectiles/guns/pistols.dm

Automag is basically just pocket flech.
The only flech I'll accept is shotgun.
162 damage in a third of a second as a pistol is pretty wack.
:cl:
balance: Increased automag burst delay and scatter.
/:cl:

Automag Nerf

---

code/datums/gamemodes/civil_war.dm

Respawn in hvh set to 5 minutes, because the game is really fast
:cl:
balance: Respawn is set to 5 minutes in HvH
/:cl:

10 minutes is long in hvh, respawn is set to 5 minutes

---

code/modules/projectiles/gun_system.dm

You were able to target yourself. Doesn't do anything apart a runtime though

Fix gun system runtime

---

code/modules/projectiles/gun_system.dm

Fix a runtime with minigun
No player facing charges

Fix minigun runtime

---

code/game/objects/machinery/overwatch.dm
code/modules/projectiles/gun_system.dm

Missing return
No player facing charges, this was just runtiming

Runtime overwatch

---

code/game/objects/structures/xeno.dm
code/modules/vehicles/vehicle.dm

Including droids.
Code is meh though
Droids should not be able to bypass sticky resin
:cl:
balance: Sticky resin slows down vehicles
/:cl:

Sticky resin slows down vehicles

---

code/datums/loadout/loadout_helper.dm
code/datums/loadout/loadout_seller.dm

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/7832
:cl:
fix: Fix wrong headset being given to rebels from loadout vendor
/:cl:

Fix wrong headset being given to rebels from loadout vendor

---

code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
code/modules/unit_tests/xeno_logical_scaling.dm
dependencies.sh

Bump ci to the version we are compiling the server on.
Fix xeno_logical spawning that will no longer work. It should have never worked, initial(a.vars[b]) doesn't work when a is a typepath. It was working because the typepath was in a list, and the compiler failed to understand it was a typepath
this last image shows the old behaviour. This no longer works, it was ""fixed""
We should check the code on the version we are on

Bump ci version

---

code/datums/actions/xeno_action.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm

Simple relocation of the variable declaration from individual unique actions to the parent xeno_action.
Further refactoring in preparation for a new Hive Management Panel. I am chopping these up into tiny bite sized PRs for easier review.
:cl:
refactor: Relocated variable declaration of psy point costs of certain xeno actions from individual actions to parent xeno_action.
/:cl:

Relocates Psy Points Cost to Xeno Action

---

code/modules/vehicles/unmanned/unmanned_vehicle.dm

Title
Boiler less useless against droids
:cl:
balance: Unmanned vehicles take some damage in acid boiler smoke
/:cl:

Unmanned vehicles take some damage in acid boiler smoke

---

code/controllers/subsystem/job.dm
code/datums/gamemodes/game_mode.dm
code/datums/jobs/squads.dm

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/7834
:cl:
fix: Fix squad preferences for rebels
/:cl:

Fix squad preferences for rebels

---

code/modules/projectiles/gun_system.dm

fix the gun jammin when you are trying to shoot yourself
:cl:
fix:  fix gun jamming
/:cl:

[CRITICAL] fix gun jamming

---

code/__DEFINES/factions.dm
code/game/objects/items/radio/headset.dm

Title
Also changed the sound to something better
It was funny though
:cl:
fix: Headsets will no longer blow up in your face for no reason
/:cl:

Headsets will no longer blow up in your face for no reason

---

code/game/objects/machinery/vending/new_marine_vendors.dm

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/7833
:cl:
fix: Fix able to buy forbidden items in civil war
/:cl:

Fix able to buy forbidden items in civil war

---

code/game/objects/structures/razorwire.dm

Fixes good
Bugs bad
:cl:
fix: fixed hivemind eyes getting caught onto razorwires by adding a check
/:cl:

Stops the hivemind from getting caugh ton razorwires

---

code/modules/clothing/under/under.dm

why are these normal sized lmao
:cl:
fix: uniforms are bulky now
/:cl:

uniforms are bulky

---

_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
_maps/map_files/Research_Outpost/Research_Outpost.dmm
_maps/map_files/Vapor_Processing/Vapor_Processing.dmm
_maps/map_files/icy_caves/icy_caves.dmm
code/datums/skills.dm
code/game/objects/effects/landmarks/corpsespawner.dm

Players should not be getting ahold of meme equipment without admin intervention
:cl:
del: Delete clown paraphernalia from maps
/:cl:

Delete clown paraphernalia from maps

---

_maps/shuttles/alamo.dmm

It allows the AI to talk to marines on it. 
Also it lets people on the ground request a rotate faster.
:cl:
qol: Added an holopad to the alamo.
/:cl:

Gives the alamo an AI holopad.

---

code/modules/reagents/reagents/other.dm

has infinte cycles after 6 to 10, less stamina loss recvoery (-0.15 from 0.5) but same limb health
makes water have a bit more utility as a budget paracematol that purges chems you don't like
:cl:
balance: after the initital rush of effects are over, water still has an effect on you. Heals minor stamina loss and health damage.
/:cl:

water buff

---

code/_compile_options.dm

Bump max compile version

---

code/game/objects/machinery/vending/marine_vending.dm

1 to -1
closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7874
marines got their head shipment
:cl:
fix: tyr head attachie is infintie
/:cl:

tyr head is now inifnite

---

_maps/map_files/debugdalus/tgs_debugdalus.dmm

- Added some cameras to the normandy landing zone
- Moved a bunch of lights, APC's and cameras around so they look in the correct direction
- Added a few lights to better light the hangar
- Added dropship vouchers so you can just buy more ship points.
More fixes & it makes the place looks smoother.
:cl:
admin: Improved the testing environment of the debug ship by adding more lights, making look better & adding dropship vouchers
/:cl:

Bunch of changes on debug ship

---

code/modules/projectiles/guns/shotguns.dm

Sawnoff shotgun in one hand is iconic
Sawn off is rare enough and also 15 points to get in most places, so having a funny gimmick sidegrade to the TS-34 is fun.
:cl:
balance: you can fire the sawn off shotgun in one hand.
/:cl:

you can fire the sawnoff one handed

---

code/game/turfs/walls/wall_types.dm

I drew a thing. Might look to see if I can fix it up later, since compressing the file down into something manageable has affected quality somewhat. But people might not care so posting this now.
Just some additional flavour.
:cl: Joniroq
add: Added new Lobby Art
/:cl:

New Lobby/Main Menu Art

---

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Apparently no one understand anything about how silos or cocoon works, so this aims to clarify this a bit
:cl:
qol: Clarify silo and larva generation
/:cl:

Clarify silo and larva generation

---

.github/workflows/stale.yml

Updates the github message on pr stale tag.
Accurate info
Github

Updates github close timer message

---

code/datums/loadout/loadout_helper.dm

Title
:cl:
fix: Fix sg having infinite sg goggles with loadout vendor
/:cl:

Fix sg having infinite sg goggles with loadout vendor

---

code/controllers/subsystem/silo.dm
code/datums/gamemodes/game_mode.dm
code/datums/jobs/job/job.dm
code/datums/jobs/job/xenomorph.dm
code/datums/round_statistics.dm
code/game/objects/items/cocoon.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/xenomorph/xeno_structures.dm

Title
Can be used to balance larvas source. More info good
:cl:
qol: Larvas sources are shown at the end of the game
/:cl:

Larvas sources are shown at the end of the game

---

code/modules/mob/living/carbon/human/life.dm

Title
There will be way more respawns in civil war, and the game is more casual so this is to prevent stupid attrition
:cl:
expansion: In civil war, becoming undefibbable will make your job available again
/:cl:

In civil war, becoming undefibbable will make your job available again

---

code/game/objects/structures/flora.dm

Title
Because this is dumb: 
:cl:
fix: Fix rock layer on magmoor
/:cl:

Fix rock layer on magmoor

---

code/_compile_options.dm
code/game/objects/machinery/computer/droppod_control.dm
code/game/objects/structures/droppod.dm
code/game/turfs/space/transit.dm
code/modules/shuttle/computer.dm
code/modules/shuttle/marine_dropship.dm
code/modules/shuttle/mini_dropship.dm

Fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/7813
Fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/7509
Also, if TESTING is defined, there won't be any shuttle and pods timelock anymore
:cl:
fix: Tadpole is in cloud again
/:cl:

Fix tadpole clouds

---

_maps/map_files/Theseus/TGS_Theseus.dmm

Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/7879
Bug fix good. 
:cl:
fix: fixes the northern sl vendor on theseus from being only working with alpha squads
fix: adds an hypersleep console in preps
/:cl:

Fixes theseus northern squad leader vendor from being inaccessible

---

code/datums/components/riding/riding.dm

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/7795
:cl:
fix: Fix xeno able to open shutters
/:cl:

Fix xeno able to open shutters

---

code/game/objects/items/tools/maintenance_tools.dm

Prevents spamming handheld chargers inhand in order to charge multiple times simultaneously.
Bug fix, grammar.
:cl:
fix: Handheld chargers can only be used one time at a time
/:cl:

Handheld charger cleanup

---

code/modules/reagents/reagents/other.dm

Makes space cleaner clean you even if you're wearing shoes.
Bugfix
:cl:
fix: Space cleaner works on humans even if you're wearing shoes.
/:cl:

Space cleaner cleans mobs with shoes

---

code/datums/elements/plasma_on_attack.dm
code/modules/mob/living/carbon/xenomorph/attack_alien.dm

I could make it a check for ravagers only but whatever.
This just makes it impossible to slash dead simple animals.
Fixes #7342
:cl:
fix: fixes ravager getting free rage from hitting simple mobs.
/:cl:

Makes it so beans can't hit dead simple animals anymore.

---

code/modules/reagents/machinery/chem_master.dm

The wiki describes the AI as being able to use pretty much any machines. 
This PR makes the AI closer to being able to use any machines.
Balance is minimal given you still lack hands to put things in, so humans are still needed.
:cl:
qol: made the AI able to use the chem master. or at least, access it.
/:cl:

Gives the AI proper access to the chem master

---

code/__DEFINES/mobs.dm
code/modules/mob/mob_movement.dm

Speeds up diagonal movement, from a *2 delay to only *1.6 compared to cardinal movements.
Right now, moving in diagonal is stricly a "qol" thing, because you moving north then west is taking the SAME time than moving north-west. 
This means than in almost all cases, moving diagonally is a bad choice : 
- You don't chose which path you take, since you will cross two tiles, and a player will be incapable to predict which tiles he will cross
- You stay on the same spot twice as long, so you are far easier to shoot. As a xeno, moving diagonally while under fire is a death sentence
In all these cases, moving cardinally is either better or at least equal to moving diagonally ; there are no cases where moving diagonally is a good tactical choice
With this PR, we give the player a new tool to …

Speeds up diagonal movement 

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm

Title
This is meant for droids and such, but i see no reason why crusher could be able to fling objects like shirke for exemple.
:cl:
balance: Crusher can fling objects that are not anchored
/:cl:

Crusher can fling objects that are not anchored

---

code/modules/shuttle/cas_plane.dm

:cl:
fix: fixed a missing cas message
/:cl:

Fixes an incorrect tochat

---

code/game/atoms_movable.dm

https://github.com/tgstation/tgstation/pull/60756/files
:cl:
fix: Fix flashing with item attacks
/:cl:

Fix flashing with item attacks

---

code/datums/emotes.dm

https://github.com/tgstation/tgstation/pull/60772
:cl:
fix: Ghost emotes are only sent from player mobs to reduce clog
/:cl:

Ghost emotes are only sent from cliented mobs

---

code/__DEFINES/supply.dm

The SADAR is way too cheap at 90 points and i'm seeing way too many of them rushed early game, which can be fair if it's the only thing you're going for but at 120 you'll see less overall of them in a game and more like one or two
I'd like to do a full rework to the RPGs sooner or later (RR, SADAR, and maybe add a midgame one) but this is a good stopgap for now
SADAR is heads and shoulders above everything else so this really represents that.
:cl:
balance: SADAR RPG costs 120 from 90 in req.
/:cl:

SADARs cost 120 from 90

---

code/modules/clothing/glasses/night.dm

more consistent lore?
less confuison
:cl:
spellcheck: the sg nvgs have been renamed, and no longer mention the m56
/:cl:

sg nvg rename real quick

---

code/modules/mob/living/silicon/ai/ai.dm
code/modules/shuttle/cas_plane.dm
code/modules/shuttle/marine_dropship.dm

Try to make the notifications a bit less ugly and choppy by capitalizing them
:cl:
fix: fixed the capitalization of some shuttle id's so they work better with the AI
/:cl:

Make the AI dropship movement notification prettier

---

code/modules/shuttle/cas_plane.dm

Fix cas
French coder broke it
:cl:
fix: Fix cas
/:cl:

[CRITICAL]Fix cas

---

code/__DEFINES/dcs/signals.dm
code/datums/keybinding/human.dm

Splinter said he would fix, but that was 10 years ago so
Unused keybind, just leads to confusion
:cl:
del: Remove unused holster keybind
/:cl:

Remove unused holster keybind

---

code/game/objects/effects/decals/posters/bs12.dm

am dumb. this exists solely because im a moron and the actual pr's CL dumb
changelog good
:cl:
fix: TP44 attachment offsets reverted to pre-snubnose values
/:cl:

functioning changelog for previous tp44 pr thing

---

code/game/objects/items/storage/marine_boxes.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/flamer.dm
code/modules/projectiles/magazines/flamer.dm

Bad code, it is not used.
It shoud not be used, because the code is bad

Remove green fire from code

---

code/datums/gamemodes/game_mode.dm
code/datums/round_statistics.dm
code/modules/mob/mob_verbs.dm

@jroinc's #8070 copy pasted, only change is to show revives and respawns separately as requested by maintainers.
More accurate logging, but this time for real.
:cl:
expansion: Logs respawns to lobby and displays them alongside revives as round statistic.
/:cl:

Respawn stats logging V2

---

code/game/objects/items/shards.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/organs/limbs.dm

Nothing major just housekeeping

Cleanup of misc limb and species code

---

code/__DEFINES/shuttles.dm
code/controllers/subsystem/points.dm
code/datums/emergency_calls/deathsquad.dm
code/datums/emergency_calls/emergency_call.dm
code/datums/emergency_calls/pmc.dm
code/datums/emergency_calls/sectoid.dm
code/datums/emergency_calls/upp.dm
code/datums/emergency_calls/upp_commando.dm
code/datums/gamemodes/crash.dm
code/datums/shuttles.dm
code/game/objects/machinery/computer/communications.dm
code/game/objects/machinery/computer/dropship_weapons.dm
code/game/objects/structures/dropship_equipment.dm
code/modules/admin/topic.dm
code/modules/power/lighting.dm
code/modules/reqs/supply.dm
code/modules/shuttle/ert.dm
code/modules/shuttle/ert_big.dm
code/modules/shuttle/marine_dropship.dm
code/modules/shuttle/mini_dropship.dm

Some DUDE asked me to do this as this would prevent some accidents involving ID's.
Better code mostly.
:cl:
code: Moved all shuttle ID's to defines.
/:cl:

Moves all the shuttle ID's to defines in Shuttle.dm

---

code/__DEFINES/shuttles.dm
code/game/objects/structures/dropship_equipment.dm
code/modules/shuttle/cas_plane.dm

Turns out, that part wasn't done! 
Bug bag, fixes good.
:cl:
fix: fixes CAS for good this time. Right?
/:cl:

Fixes CAS 2 : Electric boogaloo

---

code/game/objects/items/flashlight.dm

Make flashlights slashable. 
No thanks. Also makes sense since you can slash flashlights on gun
:cl:
balance: you can slash flashlights off
/:cl:

you can slash flashlights off

---

code/game/objects/items/storage/belt.dm

that's it
nerfs pulling 8 pistols out of your ass 
:cl:
balance:g8 pouch can only hold one gun
/:cl:

makes it so g8 pouch can't hold more than one gun

---

code/game/objects/machinery/autolathe_datums.dm

I appear to have copy pasted a little here
:cl:
fix: Fixes autolathe not having conveyors
/:cl:

Fixes autolathe not having conveyors

---

code/game/objects/structures/orbital_cannon.dm
code/modules/admin/topic.dm

Per title, improved admin tooling
:cl:
admin: Admins can now cancel OB's and OB firing now has a game log
/:cl:

Admins can now cancel OB's and OB firing now has a game log

---

code/modules/ai/ai_behaviors/xeno/xeno_illusion.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
code/modules/projectiles/projectile.dm

Just visual effect. Will help marine to distinguish fake from real hunters. You would still need to play attention to see it
Bit hard to notice where is the real one
:cl:
balance: Hunter illusion flickers when hit by projectiles
/:cl:

Hunter illusion flickers when hit by projectiles

---

code/datums/skills.dm

This PR expands the AI list of skills to include things like leadership and surgery.
The AI currently is only skilled in engineering matters. Given there are some factors which are affected by skills like autodocs and some orders, it seems like an oversight. 
:cl:
balance: Improved AI skills, they're now a master of all, for whatever the AI can use their skills for.
/:cl:

The AI now has expanded skills

---

code/modules/admin/panels/player_panel.dm
code/modules/admin/topic.dm

Player panel gets:
-Exposed related cid and ip
-Exposed account and seen ages to
🐈 
:cl:
admin: Adminplayer panel improvements
/:cl:

Improve admin evasion tooling

---

code/controllers/configuration/entries/general.dm
code/modules/client/client_procs.dm
config/config.txt

Admin tooling
DNM until config is updated
:cl:
config: split a server config
/:cl:

Split new account config

---

code/game/objects/items/marine_gear.dm

Reverts tgstation/TerraGov-Marine-Corps#8119
David don't like it, didn't see

Revert "Flashlights are now not useless"

---

code/datums/jobs/job/shipside.dm
strings/tips/marine.txt

Extra tip and a note in the synthetic spawning stuff.
Helps people know about the game features.
:cl:
add: Added a tip and note to synths referring them towards binary radio
/:cl:

Add a couple in game notes referring to binary radio.

---

code/datums/skills.dm

<s>makes captain have level 3 surgery</s> 
did this PR as a way to see how a PR is made but sent it to the wrong place so im editing this PR instead
makes captain have level 1 surgery
so captain can do surgery when theres no shipside medical staff
:cl:
add: Captain now has level 1 surgery.
/:cl:

makes captain have level 1 surgery

---

code/modules/mob/mob_verbs.dm

Admin respawn bypass message_admins()

---

code/modules/projectiles/ammo_datums.dm

From 1 shell speed to 2.
It's too easy as a marine to dance around and dodge acid from turrets, making it very gameable. This makes turrets worthier opponents, without raising the health or the damage
:cl:
balance: Xeno turret projectiles go faster
/:cl:

Xeno turret projectiles go faster

---

code/modules/admin/admin_verbs.dm

Approved by lewd
Lets maints fetch logs to debug

Change log fetching to r_admin instead of r_asay

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Per title its near the couch maint room
Grandpa vs Pit Boss fist fight when
:cl:
add: Add a boxing ring to Pillar
/:cl:

Add a boxing ring to Pillar

---

code/modules/modular_armor/attachables.dm
code/modules/modular_armor/helmets.dm

This PR Aims to make Mimir mk 1 and Mimir mk 2 better at what they are supposed to do.
Previously it seems nobody quite knew what Mimir did besides make you immune to xeno gas clouds.
Mimir mark 1 chest and head armor values are as follows.
Bio goes from 0 to 15.
rads dont matter
acid goes from 0 to 15
Mimir mark 2 chest and helmet armor are as follows.
Bio goes from 20 to 40
rads still don't matter
acid goes from 20 to 30.
It's hard to find information on what equipment gets used or not besides from hear-say, but Mimir is supposedly the least used armor mod thing thanks to a few different reasons with the main one apparently being that Tyr was better even without the gas immunity. 
This PR makes Mimir much more competitive with other modules and makes it excel at what it's supposed to do …

Mimir Buff

---

code/controllers/subsystem/persistence.dm

24 hours to refresh from 4 days
we have enough seasonals that we can refresh far more often IMO, i'm gonna add a few more in the future and i'd rather have them swap often (every day or so) so we can get some seen more variety out there.
2 hours might be too short though, 6 might be better. Though I think 2 hours is better
:cl:
tweak: seasonals now refresh every 24 hours rather than 4 days.
/:cl:

seasonals change every 24 hours rather than 4 days

---

code/modules/xenomorph/xeno_structures.dm

get_dist works across z levels, because ???? So i added a z level check
:cl:
fix: Fix xeno turrets trying to shoot droids on other z levels
/:cl:

Fix xeno turrets not checking z level of droids

---

code/modules/projectiles/guns/shotguns.dm

Fixes Issue #8154
Also changes the code a little so this doesnt happen again.
Fix good.
:cl:
fix: Fixes that thing with the derringer.
/:cl:

Fixes the issue with Unloaded Derringer bullets not being able to be loaded back into the Derringer.

---

code/modules/projectiles/gun_system.dm

Fixes attachment weapons firing when the gun is not in hand.
Fixes attachment weapons firing at inventory objects.
Fixes
:cl:
fix: Fixes attachment weapons firing when the gun is not in hand.
fix: Fixes attachment weapons firing at inventory objects.
/:cl:

Fixes some issues with attachment weapons firing when they shouldnt.

---

code/game/objects/items/storage/fancy.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8165
:cl:
fix: Fix lighter in cigarette packet can be removed
/:cl:

Fix lighter in cigarette packet

---

code/modules/projectiles/gun_system.dm

You can shoot while sprinting again
Wasnt meant to be the way i made it
:cl:
fix: You can shoot while sprinting again.
/:cl:

You can sprint while shooting again

---

code/controllers/subsystem/spawning.dm

Fix ai xeno runtime

---

code/game/objects/structures/stool_bed_chair_nest/bed.dm

Fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/8134
:cl:
fix: Fix being able to send two people with one medevac
/:cl:

Fix being able to send two people with one medevac

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm

Reduced plasma cost from 75 to 25.
Removed wind up time.
Makes Hunter's Mark significantly more viable/practical.
:cl:
balance: Reduced Hunter's Mark plasma cost from 75 to 25.
balance: Removed Hunter's Mark wind up time.
/:cl:

Hunter Mark Improvements

---

.github/workflows/generate_documentation.yml
dependencies.sh

Updates to 1.7.1 so we dont need to build dmdoc from source anymore

Update to spacemandmm 1.7.1

---

code/game/objects/machinery/roomba.dm

Clicking on roomba with harm intent and fun config allowed will have a 50% chance of deleting it.
And a 50% change of deleting you.
This thing is stealing my stuff, we need a way to kill it
:cl:
add: Roomba roulette. Just click on the roomba!
/:cl:

Roomba roulette

---

code/controllers/subsystem/vote.dm
config/modes.txt

Title. Need a config change.
I didn't test this
Gamemode almost ready, don't need admin intervention
:cl:
config: You can vote for civil war now
/:cl:

You can vote for civil war now

---

code/modules/projectiles/guns/specialist.dm

Fix flare gun shooting nades
:cl:
fix: Fix flaregun shooting nades
/:cl:

Fix flaregun shooting nades

---

_maps/modularmaps/EORG/de_dust2.dmm
_maps/modularmaps/EORG/original.dmm

Add more any nodes to maps that didn't have those
Admins can use spawners in EORD
expansion: Add ai nodes to EORD
/:cl:

Add ai nodes to EORD

---

.github/CONTRIBUTING.md

Add some map specific guidelines every map change or new map must follow
:cl:
expansion: Add ai nodes to EORD
/:cl:

Map contrib guidelines added

---

code/datums/components/ai.dm
code/datums/elements/pathfinder.dm
code/modules/ai/ai_behaviors/ai_behavior.dm

Ai will stop processing if you login to a mob with ai. It will resum if you log out
You no longer have to fight against the ai to try to go somewhere
:cl:
qol: Ai will stop processing if you login to a mob with ai. It will resum if you log out
/:cl:

You can take full control of the ai

---

code/game/objects/items/defibrillator.dm
code/game/objects/items/scanners.dm

Adds QC+, Peri+, and nanoblood mentions to the scanner's recommended treatment when appropriate.
Clarifies what to do with a heartbroken corpse, and makes it clear when someone's permaded. Also reverses the order of the checks so you hear about them being permaded over having organ damage.
Additional clarity for some medical roles, updates some text.
:cl:
fix: Altered some descriptive text for the medscanner and defib.
/:cl:

Scanner and defib wording changes

---

code/datums/gamemodes/civil_war.dm

Title
So admins can spice up games if they want
:cl:
add: Admin spawned xeno can use abilities in civil war
/:cl:

Admin spawned xeno can use abilities in civil war

---

code/_onclick/hud/parallax.dm

:cl:
fix: fixed parallax animation
/:cl:

https://github.com/tgstation/tgstation/pull/61341/files port

---

tgui/packages/common/color.js

:cl:
fix: fixed some tgui colors maybe being wierd
/:cl:

port https://github.com/tgstation/tgstation/pull/61324/files

---

code/__HELPERS/qdel.dm

:cl:
fix: fixed a deletion bug
/:cl:

https://github.com/tgstation/tgstation/pull/61078/files port

---

tgui/packages/tgui/components/Tooltip.tsx

https://github.com/tgstation/tgstation/pull/61343 port
:cl:
code: TGUI tooltip optimization
/:cl:

TGUI tooltip optimization

---

code/_onclick/hud/radial.dm

https://github.com/tgstation/tgstation/pull/54870/files port
:cl:
fix: fixed some radial menus looking wierd
/:cl:

Fix radial menu flags

---

code/modules/balloon_alert/balloon_alert.dm

https://github.com/tgstation/tgstation/pull/61035/files port
:cl:
fix: fixed soe balloon alerts looking wierd
/:cl:

Ballon alerts flags fix

---

code/modules/power/cable.dm

https://github.com/tgstation/tgstation/pull/60843/files port

Unused proc removal

---

code/__DEFINES/atom_hud.dm
code/game/data_huds.dm
code/modules/projectiles/mounted.dm
code/modules/projectiles/sentries.dm

Title
:cl:
fix: Sentry ammo is visible again
/:cl:

Add back sentry ammo hud

---

code/__DEFINES/rust_g_overrides.dm

https://github.com/tgstation/tgstation/pull/60802 port

Stringify urlencode

---

code/__DEFINES/lighting.dm
code/__HELPERS/lighting.dm
code/game/atoms_movable.dm
code/modules/lighting/emissive_blocker.dm

port https://github.com/tgstation/tgstation/pull/61249/files

Emissive code improvement port

---

code/modules/projectiles/guns/rifles.dm

20->12 scatter
it already has insane falloff, I think that's enough of a downside, 12 scatter still isn't anything to scoff at to be fair.
This should make it a bit more viable and take it out of trash fire tier into ok
:cl:
balance: machinecarbine scatter reduced by 8 to 12 from 20.
/:cl:

reduces machinecarbine scatter by 8

---

code/modules/vehicles/unmanned/unmanned_droid.dm

:cl:
fix: droids can be repaired again
/:cl:

Fix droid repair

---

code/_compile_options.dm
code/modules/client/client_procs.dm

latest is stable apart  from an iimage animate graphical bug
:cl:
code: Updated max reccomended byond versions
/:cl:

Bump Max reccomended byond versions

---

code/__HELPERS/string_lists.dm
code/game/objects/items.dm
code/modules/mob/living/carbon/human/species.dm
tgmc.dme

Add clothing whitelist support

---

code/modules/projectiles/guns/revolvers.dm

old description mentions a bad rof
tp44 has anyhting but bad rof
old description didn't make sense anymore as the original fire rate was going to be 0.3, it's now 0.15 and there's no going back sooo
:cl:
spellcheck: minor tp44 description changes
/:cl:

tp44 description changes

---

code/modules/projectiles/magazines/flamer.dm

Why do you call it "mini" if its same size as large one?
Make mini incinerator tank easier to carry.
:cl:
balance: mini incinerator tank now small item
/:cl:

Mini incinerator tank now small item

---

code/_onclick/adjacent.dm

Per title, cleaned up with AS es while i was there
:cl:
code: Backend vehicle multitile prep
/:cl:

vehicle multitile adjecency support and minor cleanup

---

code/__DEFINES/traits.dm
code/modules/mob/living/living_defense.dm

Add the unignitable trait

---

code/modules/projectiles/guns/rifles.dm

rename/relore because the original one was ???
ak47 generic 
MPi-KM is funnier and is the actual variant the ak ingame is based off of so
:cl:
spellcheck: ak got renamed to MPi-KM, and has a new description.
/:cl:

ak relore/name

---

code/_globalvars/lists/typechache.dm

Actually does nothing, code cleaning i guess

Small code cleaning i guess

---

code/modules/mob/dead/observer/observer.dm

Reverts tgstation/TerraGov-Marine-Corps#8295
reverting till it can be fixed

Revert "Fix infinite respawn, randomise name on ssd take, add admin loging"

---

code/game/objects/effects/landmarks/corpsespawner.dm

Stop corpse spawner from processing on mobs

---

code/modules/projectiles/gun_system.dm

Title. Now you can properly flame xenos
:cl:
fix: Fix not being able to fire at dark zones with attachment
/:cl:

Fix not being able to fire at dark zones with attachment

---

code/game/objects/structures/stool_bed_chair_nest/bed.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/mob_defines.dm

Added a faction check before you can use a medevac
No more shipside boarding
:cl:
balance: You cannot use enemy medevacs
/:cl:

You cannot use enemy medevacs

---

code/modules/mob/living/living.dm

As a xeno: if you are on help intent, you will never be blocked by another xeno
No more body blocking. Maybe more shuffling hell, i think it's a fair price to pay
:cl:
qol: As a xeno: if you are on help intent, you will never be blocked by another xeno
/:cl:

Priority change in shuffling

---

code/game/objects/structures/stool_bed_chair_nest/bed.dm

Moves faction tracking from a bed to the beacon it's linked to.
Fixes #8321 
:cl:
fix: Medevacs work.
/:cl:

Fixes medvacs not working

---

code/game/objects/items/motion_detector.dm

Title
:cl:
fix: Fix motion detector working in pockets
/:cl:

Fix motion detector working in pockets

---

code/controllers/subsystem/explosions.dm

Cuts down on spammy logs to emphasise the useful ones
:cl:
admin: Explosion logging tweaks
/:cl:

Explosion logs will now only send to chat shipside

---

code/modules/mob/living/carbon/human/species.dm

title this doesnt work right in multiple ways

Fix the humans_need_surnames config

---

code/datums/jobs/job/shipside.dm
code/game/area/general.dm
code/modules/reagents/reactions/medical.dm
code/modules/reagents/reagents/medical.dm

Recipe changes- Meralyne and Dermaline larva juice recipes removed, use the lemoline reaction now. Neuraline also altered to use lemoline. 
Lemoline catalysis added, turns larba juice into lemoline if you end up getting one.
Quietus uses three chloral hydrate, three lemoline, and one dylovene to make one unit of quietus.
Somolent uses one unit each of sleep toxin, tricord, paracetamol, and doctor's delight to make 4 units of somolent. 5u of lemoline is required, but not consumed.
Medical nanites require 10u of nanites, 5u of radium, 100u of iron, and 5u of lemoline to make one unit of medical nanites. Cooperation with an engineer is required to get these. Additionally, they can be harvested from an injected subject via dialysis once made.
Stimulon requires 10u of synaptizine, 20u of …

Chem rework 7.0

---

code/game/area/areas/shuttles.dm
code/game/area/centcom.dm
code/game/area/general.dm
code/modules/lighting/lighting_area.dm
code/modules/lighting/lighting_static/static_lighting_area.dm
code/modules/mob/living/silicon/ai/multicam.dm

https://github.com/tgstation/tgstation/pull/61544

Default basecolor to white

---

code/modules/projectiles/gun_system.dm
code/modules/projectiles/projectile.dm

Fix harddel from stock when the gun is taken from the loadout vendor

Fix gun harddel

---

code/game/objects/effects/temporary_visuals/miscellaneous.dm

title
:cl:
qol: centered small eplosions animation
/:cl:

Center small explosions

---

code/game/objects/effects/weeds.dm

Speed weeds to just weeds
Speed weeds are just normal weeds
:cl:
qol: change speed weed name to weed
/:cl:

Change weed name

---

code/game/turfs/turf.dm
code/modules/lighting/lighting_static/static_lighting_turf.dm

https://github.com/tgstation/tgstation/pull/61530 and some adjacents

Lighting fix batch

---

code/controllers/subsystem/weeds.dm
code/controllers/subsystem/weeds_decay.dm
code/datums/actions/action.dm
code/datums/browser.dm
code/datums/status_effects/status_effect.dm
code/game/objects/effects/weeds.dm
code/game/objects/items.dm
code/game/objects/items/radio/detpack.dm
code/game/objects/machinery/computer/crew.dm
code/game/objects/machinery/overwatch.dm
code/modules/buildmode/buttons.dm
code/modules/clothing/shoes/marine_shoes.dm
code/modules/language/language_holder.dm
code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/mob/living/silicon/ai/freelook/chunk.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/energy.dm
code/modules/xenomorph/xeno_structures.dm

Some harddel fix

---

code/game/turfs/turf.dm

https://github.com/tgstation/tgstation/pull/61569/files
:cl:
fix: Fix shuttle lighting & turfs
/:cl:

Fix shuttle lighting & turfs

---

code/modules/reqs/supply.dm

Right-clicking radiopack pulls the last items stored THEN opens the interface right now. This fixes that to no longer draw when right clicking
No more double action on a single button
Also added instructions when examining.
:cl:
fix: fixed right clicking radiopack pulling out items
/:cl:

Radio Backpack Right-click Fix

---

code/modules/projectiles/guns/energy.dm

Fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/8350
WOW NICE FIX GIVE ME GBP AND MAKE ME MAINTAINER
:cl:
fix: Fix energy guns not auto ejecting
/:cl:

Fix energy guns not auto ejecting

---

code/modules/ai/ai_behaviors/ai_behavior.dm

Title
:cl:
fix: Fix loging into ai not giving you full control
/:cl:

Fix loging into ai not giving you full control

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
code/modules/mob/mob_movement.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8228
:cl:
fix: Fix hivemind slowdown issues 
/:cl:

Fix hivemind slowdown issues 

---

code/game/objects/effects/landmarks/corpsespawner.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8319
:cl:
fix: Fix corpsespawner looking psydrainable
/:cl:

Fix corpsespawner looking psydrainable

---

code/modules/mob/living/carbon/xenomorph/evolution.dm
code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm

Title. Also allow xeno upgrade to be updated properly in crash
:cl:
fix: Fix xeno instant evolving
/:cl:

Fix xeno instant evolving

---

code/modules/projectiles/guns/shotguns.dm

I removed it by inadvertance
:cl:
fix: Fix shotgun pump lock
/:cl:

Fix shotgun pump lock

---

code/controllers/subsystem/weeds.dm
code/controllers/subsystem/weeds_decay.dm
code/game/objects/effects/weeds.dm

Title.
Also make weed behavior a bit more sensible
Change speed weed sac name in weed sac
:cl:
fix: Fix weed decaying
/:cl:

Fix weed decaying

---

code/_onclick/hud/screen_objects/menu_text_objects.dm

:cl:
code: The menu loads faster
/:cl:

Immediate initialize menu

---

code/modules/projectiles/guns/shotguns.dm

temp fix till hyper get's off his buttocks and makes flamer refactor
this is a dumb combo
:cl:
balance: shotguns don't get miniflamer anymore
/:cl:

shotguns no longer get miniflamer

---

code/datums/status_effects/debuffs.dm
code/game/area/general.dm
code/game/turfs/space.dm

Still hurt a bunch
Useless instakill creates way more issues than it is supposed to resolve
:cl:
balance: Space no longer instantly kills you
/:cl:

Space no longer instantly kills you

---

code/__DEFINES/loadout.dm
code/datums/loadout/loadout_helper.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8320
:cl:
fix: Fix being able to get all uniform from loadout vendor
/:cl:

Fix being able to get all uniform from loadout vendor

---

code/modules/mob/living/carbon/human/husk.dm

Allow them to recognise friendly sombies
:cl:
zombies: Give zombies medhud
/:cl:

Give zombies medhud

---

code/modules/mob/dead/observer/logout.dm
code/modules/mob/dead/observer/observer.dm

Fix some observer harddels

---

code/game/objects/structures/stool_bed_chair_nest/bed.dm

Fix medevac harddel

---

code/game/objects/machinery/squad_supply/supply_console.dm

Fix supply beacon harddel

---

code/game/turfs/turf.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm

Fix turf current acid harddel

---

_maps/map_files/Research_Outpost/Research_Outpost.dmm

Bugfix of a silo without fog protection.
Bugfix
:cl:
fix: I fixed a broken fog area.
/:cl:

ResearchOutpost crash fog fix

---

code/modules/projectiles/ammo_datums.dm

This has had double the slowdown of slugs sice ages, and also has stagger, knockback, and huge range on top
:cl:
balance: nerfed high velocity ammo slowdown
/:cl:

Nerf high velo to something more reasonable

---

code/game/objects/items/explosives/grenades/grenade.dm

No player facing change, this code doesn't work and shouldn't work anyway

Remove dead code from nade

---

code/modules/projectiles/guns/specialist.dm

Fixes  #8419 
Grenade launcher now have an allowed_grenades list which is checked when loading
Fixes  #8419 
:cl:
fix: UGLs loading any grenade
/:cl:

GLs now check via list if they are allowed to loada certain grenade

---

code/modules/projectiles/magazines/revolvers.dm

CMB speedloader can reload CMB revolver. Wow.
Maybe the speedloader with the same name as the gun should be able to speedload the gun?
:cl:
fix: CMB speedloader can reload CMB revolver
/:cl:

CMB speedloader can reload CMB revolver

---

code/_onclick/hud/screen_objects/menu_text_objects.dm

:cl:
fix: fixed a new player error
/:cl:

Fix immediate connection runtime

---

code/game/verbs/ooc.dm
code/modules/mob/dead/observer/orbit.dm

AI can now talk in MOOC and shows up in the ghost orbit menu.
Closes #8304
Closes #7460 
AI QoL. 
:cl:
qol: AI core can be orbited in the ghost orbit menu
fix: AI can talk in MOOC
/:cl:

Closes some AI issues

---

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm

Dead code, it's annoying me when i'm trying to look for something

Remove gut and queen heal code

---

code/modules/modular_armor/attachments/modules.dm

2 sided: A) someone didnt reuse right typepath B) someone used nonstatic lists
Closes #4784
:cl:
fix: fixed valk not removing its effects
/:cl:

No more infinite valk

---

code/game/turfs/space.dm

Prevent this
https://media.discordapp.net/attachments/752974171197276230/894230618353852486/Screenshot_52.png
:cl:
fix: Space area are correctly assimilated as space
/:cl:

Fix being able to go around hull

---

code/__DEFINES/mode.dm
code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm

50 psy poinst instead of 100
Less powerfull than its acid counterpart, the lower price will make it more used
:cl:
balance: Sticky turrets cost only 50 psypoints rather than 100
/:cl:

Sticky turrets cheaper

---

tgui/packages/tgui-panel/styles/goon/chat-dark.scss
tgui/packages/tgui-panel/styles/goon/chat-light.scss

Per title. Makes it more purple.
Muh different color.
:cl: Lewdcifer
add: Changed Maintainer OOC color
/:cl:

Changes Maintainer OOC color

---

code/modules/mob/living/living.dm

Fixes : https://github.com/tgstation/TerraGov-Marine-Corps/pull/8141 not working as intented. Big xeno were still blocking small xeno
TM first, this might cause strange things with humans and xeno
No more body block
:cl:
fix: Big xeno can no longer body block small xenos
/:cl:

Fix shuffling not working 100% as intended[DNM]

---

code/game/objects/items/reagent_containers/glass/bottle.dm
code/game/objects/machinery/vending/vending_types.dm

Makes a sanguinol and zombium bottle, adds them to the medvendor hacked "toxins" section.
New ayy toxins, so they go on the marine vendors with the other ayy toxins for RSR use and IC counterplay.
:cl:
add: Adds sanguinol and zombium to medvendor hacked section
/:cl:

Adds new Toxins to medvedor

---

code/controllers/configuration/entries/general.dm
config/config.txt

Remove one unused config flag

---

code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/guns/rifles.dm
code/modules/projectiles/magazines/rifles.dm

MJPPPPPPPPPPPPPP
ALso yes i tested this
Also fixed a rongly named dmr magazine while at it
:cl:
fix: The answer to how many TGMC PRs it takes to give the Battle rifle burst fire is now up to three
/:cl:

Finally fixes the BR

---

code/modules/mob/living/carbon/xenomorph/castes/beetle/abilities_beetle.dm
code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
tgmc.dme

You can now dodge the forward charge of beetle, since it will target the turf you are on and not you directly.
Give it more health to compensate
Stun gameplay not fun
:cl:
balance: Beetle forward charge can miss, as it's targeting the turf you are on, and not yourself directly. Just move away or on the side to doge
balance: Beetle get 400 health (from 300 health) to compensate
/:cl:

Rebalance beetle

---

code/modules/mob/living/carbon/xenomorph/castes/mantis/abilities_mantis.dm
code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
tgmc.dme

Mantis is now faster, but ravage takes a 0.5 second windup
Stun gameplay bad, and differenciates beetle and mantis more
:cl:
balance: Mantis is faster
balance: Mantis ravage have a 0.5 seconds of windup
/:cl:

Rebalance mantis

---

code/datums/gamemodes/crash.dm

Title
Xeno don't need this and it's cancer mechanic
:cl:
balance: Remove body drag from crash
/:cl:

Remove body drag from crash

---

code/game/objects/items/tools/research_tools.dm

Adds check to xeno analyzer to see if there are rewards for the xeno tier.
no runtime
:cl:
fix: fixes runtime when analyzing non-analyzable xenos
/:cl:

Fixes analyzing non-analyzable xeno tiers

---

code/game/objects/machinery/roomba.dm

Roomba will tell you how disappointed he is that you left your trash for him to pickup
Immersion
:cl:
qol: Roomba is more expressive
/:cl:

Roomba is more expressive

---

code/modules/projectiles/gun_system.dm

Title
Easier to use secondary when needed
:cl:
qol: Akimbo doesn't force you to switch hands if the gun in your inactive hand cannot be shot unwielded
/:cl:

Akimbo doesn't force you to switch hands if the gun in your inactive hand cannot be shot unwielded

---

code/__HELPERS/ai.dm

Title, if you are at least 50% invisible minions won't detect you
Minions killed solid snake gameplay, this fixes that
:cl:
balance: Ai xeno cannot see invisible marines/xeno
/:cl:

Ai xeno cannot see invisible marines/xeno

---

code/modules/projectiles/sentries.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8573
Fix
:cl:
fix: Stealthed hunter cannot be seen by marine turrets
/:cl:

Stealthed hunter cannot be seen by marine turrets

---

code/game/objects/structures/dropship_equipment.dm

bugfix
:cl:
fix: fixes the tl102 nest not having a scopesoundadd: added a new sound thingy
/:cl:

fixes the tl102 nest not having a scope

---

code/__DEFINES/machines.dm
code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/sentries.dm

C̶u̶r̶r̶e̶n̶t̶l̶y̶,̶ ̶l̶a̶s̶e̶r̶ ̶g̶u̶n̶ ̶t̶u̶r̶r̶e̶t̶s̶ ̶w̶i̶t̶h̶ ̶h̶i̶t̶s̶c̶a̶n̶ ̶a̶r̶e̶ ̶a̶b̶l̶e̶ ̶t̶o̶ ̶h̶i̶t̶ ̶x̶e̶n̶o̶s̶ ̶w̶i̶t̶h̶ ̶n̶e̶x̶t̶ ̶t̶o̶ ̶n̶o̶ ̶c̶h̶a̶n̶c̶e̶ ̶o̶f̶ ̶m̶i̶s̶s̶i̶n̶g̶ ̶t̶h̶e̶ ̶t̶a̶r̶g̶e̶t̶.̶ ̶I̶'̶v̶e̶ ̶s̶e̶e̶n̶ ̶c̶o̶u̶n̶t̶l̶e̶s̶s̶ ̶x̶e̶n̶o̶s̶ ̶g̶e̶t̶ ̶k̶i̶l̶l̶e̶d̶ ̶a̶l̶m̶o̶s̶t̶ ̶i̶n̶s̶t̶a̶n̶t̶a̶n̶e̶o̶u̶s̶l̶y̶ ̶b̶y̶ ̶l̶a̶s̶e̶r̶ ̶g̶u̶n̶ ̶m̶o̶u̶n̶t̶e̶d̶ ̶o̶v̶e̶r̶c̶h̶a̶r̶g̶e̶ ̶t̶u̶r̶r̶e̶t̶s̶.̶ ̶T̶h̶i̶s̶ ̶r̶e̶m̶o̶v̶e̶s̶ ̶t̶h̶e̶ ̶b̶u̶i̶l̶d̶-̶a̶-̶s̶e̶n̶t̶r̶y̶ ̶ ̶a̶t̶t̶a̶c̶h̶m̶e̶n̶t̶ ̶f̶r̶o̶m̶ ̶t̶h̶e̶ ̶l̶a̶s̶e̶r̶ ̶g̶u̶n̶ ̶w̶e̶a̶p̶o̶n̶s̶ ̶t̶o̶ ̶g̶e̶t̶ ̶r̶i̶d̶ ̶o̶f̶ ̶s̶o̶m̶e̶ ̶p̶o̶w̶e̶r̶c̶r̶e̶e̶p̶.̶
Decreases the accuracy of laser gun turrets instead of removing them as per maintainer request. (I spent 2h doing this help)
X̶e̶n̶o̶s̶ ̶a̶r̶e̶ ̶n̶o̶ ̶l̶o̶n̶g̶e̶r̶ …

Decreases the accuracy of lasergun turrets

---

code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
code/modules/projectiles/ammo_datums.dm

Scorpions now spit acid that can go through over xenos, rather than neurotox
Make scorprions a bit better, also make them usefull against robots and such
:cl:
balance: Scorpions now spit acid that can go through over xenos, rather than neurotox
/:cl:

Buff scorpion spit

---

_maps/map_files/debugdalus/tgs_debugdalus.dmm
code/controllers/subsystem/excavation.dm

Fixes SSexcavations from runtiming due to spawner count being less than the maximum amount of active excavations.
Also removes researcher debug setup left over on debugdalus.
fix and cleanup
:cl:
fix: fixes SSexcavations runtime due to low spawner count
/:cl:

Fixes SSexcavations runtime from low spawner count

---

code/__HELPERS/jatum.dm
code/datums/loadout/loadout_helper.dm

Not great code, but it's jatum's fault anyway
:cl:
fix: Fix pill bottles being empty on loadouts sometimes
/:cl:

Fix pill bottles being empty on loadouts sometimes

---

code/__DEFINES/mobs.dm
code/__DEFINES/mode.dm
code/datums/gamemodes/distress.dm
code/datums/gamemodes/game_mode.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Title. If shutters are drop at 12:25, the 5 minutes silo less timer can happen at 12:40
Incentive for marines to early shutter drop, when the incentive is currently on dropping them as late as possible
:cl:
balance: Silo collapse happens 15 minutes after shutter drop
/:cl:

Silo collapse happens 15 minutes after shutter drop

---

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm

Simply changes the text from a new Queen order to reference the correct panel.
Now references the correct panel
:cl:
spellcheck: Fixed an incorrect word for Queen orders
/:cl:

Changes "Status Panel" to "Game Panel" for Queen orders

---

code/game/objects/machinery/camera/camera.dm
code/modules/mob/living/silicon/ai/freelook/cameranet.dm
code/modules/shuttle/cas_plane.dm

Title
Cas can be the worst job if no one is lasing. You can already spend some time doing nothing because the fight is in cave, let's not aggrave that.
Cas PO don't want to spend 1 hour shooting into the void "Please cas flare", this doesn't encourage teamplay.
I'm buffing the laser to encourage them from being thrown, this buff cas slightly.
I'll see if cas needs a nerf following this pr, probably a shadow where it's currently flying?
:cl:
balance: Cas can begin fire mission without an active laser, flare and laser have better view range
/:cl:

Cas can begin fire mission without an active laser, flare and laser have better view range

---

code/modules/reagents/machinery/chem_master.dm

i accidently deleted the ability to make 90% of the pills in the chemmaster whoops
because the chemmaster shouldn't be missing 90% of the pills because i messed up while changing the chemmaster code.
:cl:
fix: 90% of the pills are no longer missing from the chemmaster
/:cl:

Brings back all the pills

---

code/game/objects/effects/weeds.dm

Was caused by connect loc refactor
:cl:
fix: Fix sticky weeds not accellerating xeno
/:cl:

Fix sticky weeds not accellerating xeno

---

code/__DEFINES/mobs.dm
code/datums/components/attachment_handler.dm
code/game/objects/items.dm
code/modules/clothing/modular_armor/attachments/modules.dm

what title says, but by consequence also anything that layers under helmet :P
:cl:
expansion: helmets now layer under armor.
fix: Hlin now appears on xenonauten properly.
/:cl:

Tyr xenonauten now layers over the helmet so it displays as   intended

---

code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/logout.dm

Title. TM first please
:cl:
fix: fix dead mobs in ssdmoblist
/:cl:

Should fix dead mobs in ssdmoblist

---

code/modules/shuttle/cas_plane.dm
tgui/packages/tgui/interfaces/MarineCasship.js

Title. fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8767
:cl:
fix: Cas infinite fuel
/:cl:

Fix cas infinite fuel and runtime

---

code/modules/mob/dead/observer/observer.dm

Logic was apparently inversed
closes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8579
:cl:
fix: Fix not being able to take ssd mobs
/:cl:

Fix not being able to take ssd mobs

---

code/modules/shuttle/cas_plane.dm

You are now able to launch cas as soon as 5+ marines are on ground
closes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8747
:cl:
fix: Fix cas not being able to launch mission despite marines already on ground
/:cl:

Fix cas delay 

---

code/__DEFINES/say.dm
code/__DEFINES/traits.dm
code/__HELPERS/_lists.dm
code/__HELPERS/unsorted.dm
code/game/atoms_movable.dm
code/game/objects/items/radio/intercom.dm
code/game/objects/items/radio/radio.dm
code/game/objects/items/taperecorder.dm
code/game/objects/machinery/hologram.dm
code/game/say.dm
code/modules/assembly/voice.dm
code/modules/mob/mob.dm

https://github.com/tgstation/tgstation/pull/60219
:cl:
code: Make get_hearers_in_view more performant
/:cl:

Port tg get_hearers

---

code/__DEFINES/__game.dm
code/game/objects/machinery/computer/camera_advanced.dm
code/game/turfs/turf.dm
code/modules/mob/living/silicon/ai/ai.dm
code/modules/mob/living/silicon/ai/freelook/cameranet.dm
code/modules/mob/living/silicon/ai/freelook/chunk.dm
code/modules/mob/living/silicon/ai/freelook/eye.dm
code/modules/shuttle/navigation_computer.dm

Title. from https://github.com/tgstation/tgstation/pull/59165
Better perf according to tg
:cl:
code: Better perf with cameras
/:cl:

Port camera update from tg

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Make it twice as fast to use recurring injection as a xeno. Also, if you fail to inject any toxin, you don't get a cooldown, (plasma is still used).
Very hard to pull off a recurring injectiosn, this makes it easier but still fair for marines (keep moving and you wont be injected)
:cl:
balance: Make it twice as fast to use recurring injection as a xeno. Also, if you fail to inject any toxin, you don't get a cooldown, (plasma is still used).
/:cl:

Buff recurring injection

---

code/modules/clothing/head/jobs.dm

Title.
Equality for all berets.
:cl:
balance: adds armor to job berets
/:cl:

Gives armor to job berets

---

code/game/verbs/ooc.dm
tgui/packages/tgui-panel/styles/goon/chat-dark.scss
tgui/packages/tgui-panel/styles/goon/chat-light.scss

Per title.
Staff with OOC color good.
:cl: Lewdcifer
add: New OOC color for eventmins.
/:cl:

Adds a new OOC color for eventmins

---

code/controllers/subsystem/advanced_pathfinding.dm
code/modules/ai/ai_behaviors/ai_behavior.dm

Fix some runtime with on advanced pathfinding

---

code/modules/reagents/machinery/chem_dispenser.dm

Adding Tomato Juice to Booze Dispenser
Its in a booze-o-mat already but its rarely accessed to at all, its used for a chem that is incredibly weak already, the hard accessibility of the fucking TOMATO JUICE already makes it absolute.
:cl:
expansion: Added damn tomato juice to booze dispensers
/:cl:

ADD TOMATO JUICE

---

code/_onclick/hud/parallax.dm
code/modules/mob/mob.dm

Title.
Expensive, and uneeded on ground
:cl:
code: Remove parallax when on ground
/:cl:

Remove parallax when on ground

---

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm

Title. Fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/8615
:cl:
fix: No more primo exploit with queen devo
/:cl:

Should fix crash exploit with queen devo

---

code/game/objects/machinery/vending/marine_vending.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8843
Tool pouch still full
Tool pouches still full because i don't think there should be a lack of tools, that's not a balance issue it's just annoying when you have to run around for your wrench
:cl:
fix: Fix free electronic pouches being full
/:cl:

Fix pouches

---

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm

Fixes : https://github.com/tgstation/TerraGov-Marine-Corps/issues/8885
Also fix the multi king
:cl:
fix: No more multi king
fix: Xeno turrets no longer can be placed next to each other by spamming
/:cl:

Fix hive blessing bugs

---

.vscode/extensions.json

Git lens is needed for new contrib guide and colorised bracket is cool

add some vsc recommended extensions

---

code/modules/projectiles/ammo_datums.dm

Fixes @hyper2snyper's goof. Do this again and I will instill my wrath upon your DM's. 
FIxing incendiary slugs awful stats. 
:cl:
balance: Incendiary slugs, yet again, no longer have airburst and do normal damage. Again.
/:cl:

My Anger is As Hot as These Incendiary Slugs

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Window flashs and there is a loud sound played when it's your turn to be a larva. 
More anti-afk security
QOL mostly
:cl:
qol: Window flashs and there is a loud sound played when it's your turn to be a larva (larva queue)
/:cl:

Improvement larva queue

---

code/modules/client/client_procs.dm

makes this work 
:cl:
fix: the Hypertext in old chat to reload TGUI Chat when it doens't load now works
/:cl:

make the click HERE to reload fancy chat work

---

code/controllers/subsystem/idlenpcpool.dm
code/modules/lighting/lighting_static/static_lighting_source.dm

Nothing to see here, move along citizen

Double if fix

---

code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/mounted.dm
code/modules/projectiles/guns/pistols.dm
code/modules/projectiles/guns/rifles.dm
code/modules/projectiles/guns/smgs.dm
code/modules/unit_tests/spawn_guns.dm

Add unit test to prevent fire rate of 2.75 and other non-sense
Number people don't know how the code works
:cl:
code: Unit test for guns expanded. Also put the fire delays at their correct values, have no effect on gameplay
/:cl:

Gun unit test

---

code/modules/power/lighting.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8962
:cl:
fix: Fix light replacing exploit
/:cl:

Fix light replacing exploit

---

code/game/turfs/space.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8870
Probably a bit overkill, but i don't know what is causing this so here we go
:cl:
fix: Fix hivemind space freeze bug
/:cl:

Fix hivemind space freeze bug

---

_maps/map_files/LV624/LV624.dmm
_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
_maps/map_files/Twin_Pillars/Twin_Pillars.dmm
code/game/objects/structures/crates_lockers/largecrate.dm
code/modules/mob/living/simple_animal/friendly/corgi.dm

Title
Bravemole told me, and I comply.
:cl:
fix: code
/:cl:

Making Ranger code better

---

code/game/objects/items/bodybag.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8942
:cl:
fix: Fix tarp getting spotted by minions
/:cl:

Fix tarp getting spotted by minions

---

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
code/modules/mob/living/carbon/xenomorph/evolution.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8960
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8963
Shitcode from me
:cl:
fix: Deevo from queen works as intended
fix: Wraith can no longer regress while shifted
/:cl:

Fix queen deevo and prevent wraith shift regress exploit

---

code/modules/client/preferences_ui.dm

Title
Prevent spawning as a human with a name like "Thinker-243"
:cl:
qol: Prevent bad name by randomising the name on species change
/:cl:

Changing species randomise your name

---

code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Title, fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/8896 (only the 2nd bug)
Also remove some of bad code
Unfair mechanic, clear bug abuse
:cl:
fix: Fix carrier timing exploit
/:cl:

Should fix carrier timing exploit

---

code/datums/loadout/item_representation/_item_representation.dm
code/datums/loadout/loadout_helper.dm

Title. It will no longer save the custom content, and just give you the default one which is what you want 95% of the time
:cl:
fix: Fix storage nested in storage. Aka, pills and synrigue case in pouches or things like that
/:cl:

Fix storage nested in storage. Aka, pills and synrigue case in pouches or things like that

---

code/__DEFINES/loadout.dm
code/game/objects/items/storage/pouch.dm
code/game/objects/machinery/vending/vending_types.dm

Tool vendor is now a shared vendor, has unlimited supplies, and his linked to loadout vendor.
The tool pouche now contains a welder and not a multitool
Tools being in limited supply is dumb, it's absolutly not a balance concern. Welding tool are far more usefull than multi-tool. 
Contraband is a silly mechanic, engie points makes way more sense
:cl:
balance: Tool vendor is now a shared vendor with unlimited supplies
balance: Tool vendor no longer has contraband, the huge tank welder is moved to engie points
expansion: Tool vendor is now linked with loadout system
qol: Tool pouches contains a welding tool rather than a multi-tool
/:cl:

Tool changes

---

code/_onclick/click.dm

Only worked when clicking on darkness, confusing as hell
:cl:
del: Remove middle click swap
/:cl:

Remove middle click swap

---

code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_verbs.dm

You can point even in darkness (if you can see it, like xenos do). Remove the stupid cm design that made leaders have bigger arrow and less cooldown.
Pointing good. Removed any los check since, if you can click it, you can see it. And since it's just pointing, absolutly not gamebreaking
:cl:
qol: You can point even in darkness (if you can see it, like xenos do). Cooldown is 1 second for everyone
/:cl:

Pointing atom qol

---

_maps/map_files/LV624/LV624.dmm
_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
_maps/map_files/Research_Outpost/Research_Outpost.dmm
_maps/map_files/icy_caves/icy_caves.dmm
code/controllers/subsystem/persistence.dm
code/datums/jobs/job/sonsofmars.dm
code/game/objects/effects/landmarks/landmarks.dm
code/game/objects/structures/crates_lockers/largecrate.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/guns/rifles.dm
code/modules/projectiles/magazines/rifles.dm
code/modules/reqs/supplypacks.dm

Mjp changed the ak47 but did only 20% of the job, i'm doing the rest
High confusion from having a bloody ak47 mag from a mpi-km
:cl:
fix: Properly rebrand ak47
/:cl:

Properly rebrand ak47

---

code/game/objects/machinery/computer/camera_console.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8813
:cl:
fix: Fix searching in camera input list
/:cl:

Fix searching in camera input list

---

code/game/objects/effects/overlays.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/5893
:cl:
fix: Camera laze is no longer visible
/:cl:

Fix visible camera laze

---

code/game/objects/machinery/miner.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8907
Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/8738 (duplicate)
:cl:
fix: Fix automatic miner upgrade removal
/:cl:

Fix automatic miner upgrade removal

---

code/modules/mining/remote_fob/remote_fob_fobdrone.dm

Gives the FOB Drone meson vision and a bigger light radius to accompany the meson vision. FOB Drone still can't see objects and mobs through walls so, don't worry.
This should make round start FOB building easier for engineers new and old especially new ones.
:cl:
qol: FOB drone now has meson vision
qol: FOB drone now has a bigger light radius
/:cl:

FOB Drone Vision Improvements

---

code/_globalvars/lists/keybinding.dm
code/modules/client/client_procs.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/client/preferences_ui.dm
code/modules/keybindings/bindings_client.dm
code/modules/keybindings/setup.dm
tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx

Remove focus chat option
Pretty sure no one uses it (raise your hand if you do), plus i receive mhelp from time to time from newb that cannot move because of this
:cl:
del: Remove focus chat option
/:cl:

Remove focus chat

---

code/datums/loadout/item_representation/_item_representation.dm
code/datums/loadout/loadout_helper.dm

Closes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/7407
:cl:
expansion:  Can save boot content in loadout
/:cl:

Can save boot content in loadout

---

code/modules/projectiles/ammo_datums.dm
html/changelogs/AutoChangeLog-pr-8647.yml

I'm embarrassed to make this PR.
Max range reduced to 3 tiles. 
4 tiles was a little too much and since it already does pretty high damage on a pretty short rate of fire. 
:cl:
balance: Repeater max (status effect) range decreased to 3 from 4. 
/:cl:

Tones down Repeater staggerstun

---

code/modules/reqs/supplypacks.dm
tgui/packages/tgui/interfaces/Cargo.js
tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx

Put all ammo next to their weapon in req
Put explosives (mines, grenades, mortar) in explosives
Put droids in vehicles
Remove attachments from req
:cl:
qol: Req supply back reorganised
qol: Added a search function to req
del: Remove attachment from req
/:cl:

Order supply pack + add search function

---

code/__DEFINES/dcs/signals.dm
code/game/atoms_movable.dm

Lock the dir during a throw
This looks better when throwing diagonnally
:cl:
add: Throw looks better (no more stuttered direction change)
/:cl:

Better visual throw

---

code/controllers/subsystem/shuttle.dm
tgui/packages/tgui/interfaces/MarineDropship.js

Fixes spelling error in Alamo console, Instantanious -> Instantaneous.
Also the same spelling error in shuttle subsystem comments.
Spelling error.
:cl:
fix: Alamo console spelling error rectified.
/:cl:

Fixes instantaneous spelling error

---

code/datums/actions/xeno_action.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm

Title. Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/8681
:cl:
fix: Fix hivemind cooldown exploit
/:cl:

Fix hivemind cooldown exploit

---

_maps/shuttles/alamo.dmm
code/game/turfs/open.dm

Alamo has been expanded! Recent developement found that the Alamo can increase load while maintaining its aerodynamic structure. This means that the Alamo has TWO MORE CHAIRS, TWO MORE INTERIOR TILES, AND TWO MORE NANOMEDS!
Also, code in tiles that we have but never use which then I use. See code/game/turfs/open.dm
There were dead space with the Alamo that we could use for chairs and room while maintaining its aesthetics. This could also be seamlessly updated to slotbot's grates. All I did was moved practically half of Alamo down and added the space needed.
:cl:
expansion: Alamo expands! It has two additional chairs, interior tiles, and NanoMeds!
/:cl:

Alamo Expanded!

---

code/modules/projectiles/guns/rifles.dm

Fixes fire sound for TX-11 and M412
Fix
:cl:
fix: sound fix for tx-11 and m412
/:cl:

Sound fix for TX-11 and M412

---

code/datums/jobs/job/shipside.dm
code/game/objects/items/radio/headset.dm

Previous attempt at researcher headset fix results in this PR: #9051
While researcher has access to med comm, I did not look into code deep enough and due to that PR, researcher cannot locate extraction sites.
Researcher now have medical comm and can see where extraction sites are. My bad.
:cl:
fix: Researcher now have medical comm and can see where extraction sites are. My bad
/:cl:

Researcher Headset Fix 2.0

---

_maps/map_files/Sulaco/Sulaco.dmm

Title.
As I was mapping, I realized Walten wasn't where he was. I attempted to find him, but alas he was missing. We brought him back, my dear gentlemen.
:cl:
fix: Put Walten back in Sulaco
/:cl:

Put Walten in Sulaco

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm

I made a mistake when mapping. Alamo now clips through wall without fix.
My bad. Attention to detail be like
:cl:
fix: Big Red LZ2 NOW doesn't let Alamo clip through wall.
/:cl:

Big Red LZ 2 Fix

---

code/datums/jobs/job/pmc.dm
code/modules/projectiles/guns/rifles.dm

Title.
Trying this the third time, this time with better coding knowledge.
When players spawn in as PMC ERT and get PMC SG, apparently they don't have a mag harness. As par usual of SG gameplay, you don't want to lose that smartweapon. 
:cl:
qol: PMC SG spawns with mag harness on T-29
/:cl:

PMC SG spawns with mag harness on T-29

---

.vscode/extensions.json

removes bracket colorizing from recommended extensions(has been integrated on vsc)

removes Bracket colorizing extension(integrated on vsc)

---

code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm

So you get mass teleport when young.
It's rare to see an ancient king; mass teleport is a nice ability that give king a use rather than "kill fob brrr". I think that timelock in general are stupid and doesn't add anything to the game. 
This makes king a bit more interesting to play
:cl:
balance: King can use mass teleport when young
/:cl:

Give king all abilities when young

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/9120
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/8961
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/8995
:cl:
fix: AI with Auto-spit will no longer infinitely target things.
fix: Calls the correct checks on auto-spit, no more spitting from vents and the like.
/:cl:

Fixes for auto spit

---

code/game/objects/machinery/vending/vending.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9164
:cl:
fix: Prevent stocking in vendors that are broken/unpowered
/:cl:

Prevent stocking in vendors that are broken/unpowered

---

code/_onclick/hud/screen_objects/screen_objects.dm

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9074
:cl:
fix: Fix runtime with hive call
/:cl:

Fix runtime with hive call

---

code/modules/projectiles/gun_helpers.dm

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9148
:cl:
fix: Fix ugl being reloadable in storage
/:cl:

Fix ugl being reloadable in storage

---

code/modules/codex/entries/guns_codex.dm
code/modules/projectiles/guns/energy.dm

Fixes an issue where you could overcharge lasgun cells.
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/9125
:cl:
fix: Fixes an issue where you could overcharge lasgun cells.
fix: Fixes the carbine scatter exploit.
/:cl:

Lasgun fixes

---

code/datums/actions/xeno_action.dm

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9119
:cl:
fix: Fix hivemind abilities being useable while unmanifested
/:cl:

Fix hivemind abilities being useable while unmanifested

---

code/game/objects/items/cocoon.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm

It was not dependant on the pop
:cl:
fix: Fix cocoon psy point output
/:cl:

Fix cocoon psy point output

---

_maps/map_files/debugdalus/tgs_debugdalus.dmm
code/__DEFINES/equipment.dm
code/_compile_options.dm
code/modules/ai/ai_node.dm
code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
code/modules/atmospherics/machinery/pipes/pipes.dm
code/modules/shuttle/mini_dropship.dm
code/modules/shuttle/on_move.dm

They should not be qdeled
Also add tadpole to debuglabus, because no one cares about normandy
:cl:
fix: Protect ai nodes and pipe from tadpole crushing
/:cl:

Protect ai nodes and pipe from tadpole crushing

---

code/__DEFINES/mobs.dm
code/modules/admin/admin_verbs.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/logout.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9118
:cl:
fix: Ghosts can no longer steal aghosted bodies
/:cl:

Ghosts can no longer steal aghosted bodies

---

code/game/objects/items/explosives/bombvest.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9165
Exploit
:cl:
balance: Prevent using the suicide vest when cloaked
/:cl:

Prevent using the suicide vest when cloaked

---

code/__DEFINES/monitor.dm
code/modules/ai/ai_behaviors/ai_behavior.dm
code/modules/ai/ai_behaviors/xeno/xeno.dm
code/modules/ai/ai_behaviors/xeno/zombie.dm
code/modules/mob/living/carbon/xenomorph/castes/beetle/abilities_beetle.dm
code/modules/mob/living/carbon/xenomorph/castes/beetle/beetle.dm
code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
code/modules/mob/living/carbon/xenomorph/castes/mantis/abilities_mantis.dm
code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
code/modules/projectiles/ammo_datums.dm

Mantis and beetle will no longer flee.
Since they stick in the fight, nerf their hp so their overall usefulness stay the same.
Plus see CL for other changes
Close combat minions manage to flee only 5% of the time, because they are stupid. This feature only meant that marines had to shoot it longer, even when they constituate no danger; i think that's lame.
Minions will with this update generate as much damage as previously, but will eat less bullets
:cl:
balance: Mantis and beetle no longer flee from fights when low health
balance: Beetle hp from 400 to 260
balance: Mantis hp from 200 to 150
balance: Beetle forward charge only stuns for 2 seconds, 30 seconds of cooldown (it was 4 seconds, 10 seconds before)
balance: Mantis ravage cooldown upped from 6 seconds to 30 seconds
balance: …

Rebalance minions

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

Title
U donkey
:cl:
fix: Scorpions can spit again
/:cl:

Scorpions can spit again

---

code/__DEFINES/dcs/signals.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Signals was rarely sent, so it was overiding
no player facing charge

Fix runtime from forward charge

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Title. 
Stop beetles from charging a wall
:cl:
fix: Charge and similar xeno abilities will no longer be used by ai xenos when they can't see the target
/:cl:

Charge and similar xeno abilities will no longer be used by ai xenos when they can't see the target

---

code/modules/mob/living/carbon/xenomorph/evolution.dm

Title
:cl:
fix: Xeno can evolve while resting again
/:cl:

Xeno can evolve while resting again

---

code/datums/keybinding/_keybindings.dm
code/datums/keybinding/carbon.dm
code/datums/keybinding/client.dm
code/datums/keybinding/mob.dm
code/datums/keybinding/movement.dm

forgot to remove those. Not affecting anything

Clean classic mode hotckey

---

code/__DEFINES/dcs/signals.dm
code/datums/components/attachment_handler.dm
code/datums/loadout/item_representation/gun_representation.dm

Miniflamers vended from the loadout vendor will have the proper attachments equipped.
fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/9098
:cl:
fix: Miniflamers vended from the loadout vendor will have the proper attachments equipped.
/:cl:

Miniflamer Fix

---

code/datums/components/harvester.dm

Fixes [#9209](https://github.com/tgstation/TerraGov-Marine-Corps/issues/9209)
:cl:
fix: fixes harvester bicardine attack
/:cl:

Fixes harvester Bicardine attack

---

code/modules/projectiles/gun_attachables.dm

Title
QOL
:cl:
qol: Gun attachment are activated by default when you attach them
/:cl:

Gun attachment are activated by default when you attach them

---

code/modules/ai/ai_behaviors/xeno/xeno.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9211
also make minions climbing window frames like players do
:cl:
fix: Prevent ais from nocliping through shutters
/:cl:

Prevent ais from nocliping through shutters

---

code/controllers/subsystem/explosions.dm

Per title.
At Bravemole's request, more than anything. Screenshake still wack, anyway.
:cl: Lewdcifer
balance: Explosion screenshake reduced.
/:cl:

Reduces screenshake from explosions

---

code/modules/projectiles/gun_system.dm

title
Closes #9272 
:cl:
fix: fixed autofire getting burst fire debuff on guns that has burst fire
/:cl:

fixes autofire getting scatter debuff from burst

---

code/_compile_options.dm

Up the maximum recommend version

---

code/game/objects/structures/window_frame.dm

Window frames can now be slashed
Why would you need acid to kill a window frame
:cl:
balance: Window frames may now be slashed
/:cl:

Makes window frames slashable

---

code/modules/factory/howtopaper.dm

Fixes grammar and spelling errors.
Immersion. It's also far cheaper to buy this than it is to buy the individual parts usually, so renamed to an instructional pamphlet rather than your first factory, as it generally isn't your first.
:cl:
fix: Nanotrasen now send you the updated leaflet with your factory pack - now with 73% less spelling errors!
/:cl:

Factory pamphlet spelling errors

---

code/modules/client/client_procs.dm

Users with old version have crashes, and every other ss13 server is on latest

Warn users for their byond versions

---

code/game/turfs/walls/wall_types.dm

Title.
Remember #9062? Remember angry Tanya? Yeah, you're wondering why you are not seeing this title art. I forgot to code it in.
Yeah.
:cl:
fix: you can see title_painting16 now in title screen.
/:cl:

now we can see angry tanya in title screen

---

code/controllers/subsystem/persistence.dm
code/game/objects/machinery/vending/marine_vending.dm

Adds a new seasonal group of shotgun seasonals and gets rid of some shotgun tab bloat.
New seasonals make for more varied gameplay and this was requested by Bravemole.
:cl:
add: Added Paladin and Mk221 to seasonal weapons as an entire new season.
del: Removed Paladin and Mk221 from Shotgun weapon tab in marine vendor.
/:cl:

New Shotgun Seasonal

---

code/modules/projectiles/gun_helpers.dm

Title
:cl:
qol: You can tactical reload gun attachments
/:cl:

You can tactical reload gun attachments

---

code/modules/vehicles/unmanned/unmanned_droid.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm

Closes #8620
Moved the code for welderact() on droids down to unmanned and generalised it a bit. 
Fixing apparently missing behaviour
:cl:
fix: The unmanned tank drones can now be repaired with a welder
/:cl:

All unmanned vehicles can now be fixed with a welder

---

code/modules/reqs/supplypacks.dm

Increases the price of the IFF sniper from 30 to 50 (price subject to change)
20 round mag, high damage, sunder, night vision and IFF
for 30 points
:cl:
balance: increases the price of the IFF sniper
/:cl:

Increases the cost of the IFF sniper

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
code/game/objects/machinery/vending/marine_vending.dm

PoS, Theseus, and Sulaco have free conveyor belts like Minerva.
Make life easier to set up reqtorio. Also, good map practices should transfer to other maps.
:cl:
add: Give free conveyor belts in req for free reqtorio
/:cl:

Give free conveyor belts in shipside maps due to free reqtorio

---

_maps/map_files/Theseus/TGS_Theseus.dmm

Title.
Other shipside maps have 4 roller beds in medical, and Theseus should have them, too.
:cl:
add: give 4 roller beds in Theseus
/:cl:

give 4 roller beds in Theseus

---

_maps/map_files/desertdam/desertdam.dmm

Due to lack of playtime, It escaped my notice that Chigusa was never updated to include researcher excavation sites, this PR fixes that issue.
Researchers might like to do stuff on Chigusa.
:cl:
fix: Added excavation sites to Chigusa.
/:cl:

Fixes Chigusa's lack of excavation sites

---

code/controllers/subsystem/monitor.dm
code/datums/jobs/job/job.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Crash is bugged as hell and i don't know how, this adds some logging to investigate
:cl:
code: Fix one crash runtime + add logging to jobs and larva
/:cl:

Fix one crash runtime + add logging to jobs and larva

---

code/__DEFINES/jobs.dm
code/modules/admin/panels/ban_panel.dm
code/modules/mob/dead/observer/observer.dm

title
better than banning people from playing the game because they are acting stupid in vahalla
:cl:
add: Add valhalla specific ban
/:cl:

Add valhalla specific ban

---

code/datums/actions/rightclick_toggle.dm
code/modules/mob/dead/observer/login.dm
code/modules/mob/living/login.dm
code/modules/mob/living/logout.dm
tgmc.dme

Remove the button to change right click setting
You should not use that setting, since you can't play 1/4 of the game in classic mode. If you really want to use it, it's in preference still. And that's one less button for the rest of the players
:cl:
del: Remove right click setting action
/:cl:

Remove right click setting action

---

code/game/atoms_movable.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/mob/living/living.dm

Fix poucing pushing the target, and fix bumpslash pushing the target. Probably some side effects, so tm first
:cl:
fix: Runner pounce no longer pushes the target
fix: Xeno no longer pushes in bumpslash
/:cl:

Fix some move issues

---

code/game/atoms_movable.dm
code/game/objects/machinery/doors/windowdoor.dm
code/game/objects/structures/stool_bed_chair_nest/bed.dm
html/changelogs/AutoChangeLog-pr-9229.yml

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9259
as well as another movement issue with windoor
:cl:
fix: Fix buckled bag not moving with roller bed
/:cl:

Fix buckled bag not moving with roller bed

---

code/modules/projectiles/guns/energy.dm

Title
Pistol laser akimbo is boinkers right now, this makes it to reasonable level
:cl:
fix: Fix laser pistol having automatic fire mode
/:cl:

Fix laser pistol having automatic fire mode

---

code/modules/mob/living/living_health_procs.dm

Title
They were attacked by ai zombies
:cl:
fix: Fix zombie players resurecting in xeno faction
/:cl:

Fix zombie players resurecting in xeno faction

---

code/controllers/configuration/entries/general.dm
code/controllers/subsystem/advanced_pathfinding.dm
code/modules/ai/ai_behaviors/ai_behavior.dm

Disable that expensive system when needed
Rutgmc needs it 
:cl:
code: Disable advanced pathfinding if a flag is present
/:cl:

Disable advanced pathfinding if a flag is present

---

code/modules/projectiles/projectile.dm

Title
:cl:
fix: Fix wraith primo against hitscan projectiles
/:cl:

Fix wraith primo against hitscan projectiles

---

strings/tips/marine.txt
strings/tips/meme.txt
strings/tips/meta.txt
strings/tips/xeno.txt

It's the new year, and the PR that added tips was last year at April. Time to add more and delete tips in light of new meta.
Tips are good.
:cl:
add: New tips.
del: Old tips.
/:cl:

2022 Tip Updates

---

code/modules/shuttle/navigation_computer.dm

fix shuttle computers webedit edition

---

tgui/packages/tgui/interfaces/BlessingMenu.tsx

:cl:
fix: hive blessing menu tabs is fixed and won't go over each other.
/:cl:

fix hive blessing

---

code/game/objects/machinery/doors/windowdoor.dm

This sleep in doors was making the whole pathfinding system sleeping. Ais were freezing. Very bad
:cl:
code: Fix a sleep in pathfinding
/:cl:

Fix a sleep in pathfinding

---

_maps/map_files/LV624/LV624.dmm

Title.
Big Red, a beloved map, has a medbay with cryotubes. When marines secure it, and if they can, they have the option to fix APC so that cryotubes to heal marines.
I don't about players, but this is very nice for corpsmen. When engineers do their job, it helps corpsmen heal marines. Then again, not many players take advanage of planetside cryotubes since they are too busy ungaing and pushing.
LV-624, another beloved, deserves this. I'm not sure how to implement cryotubes in other maps without radically changing it, but this will do. Marines have the choice to hold hydro, which is next to medbay. If marines are tactically sounded in the mind, have map knowledge, deal with logisitical issues, and know medical, hydro is a good place to stay and launch from. Gotta work hard for that …

Two Cryotubes in LV-624's medbay

---

code/game/data_huds.dm
code/game/objects/items/reagent_containers/glass/bottle.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/projectiles/ammo_datums.dm
code/modules/reagents/reagents/toxin.dm

Mjp forgot it
:cl:
del: Remove light neuro
/:cl:

Remove light neuro

---

code/controllers/subsystem.dm

See https://github.com/tgstation/tgstation/pull/64500
:cl: MrStonedOne
fix: Fix the mc getting completely chaotic due to background ticker subsystems
/:cl:

Fix: the mc getting completely chaotic due to background ticker subsystems (tgstation#64500)

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm

Reverts tgstation/TerraGov-Marine-Corps#9220
I really should not have to explain why this should not have been merged
:cl:
del: Removed defender ricochet
/:cl:

Revert "Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them."

---

code/game/objects/effects/misc.dm
code/game/objects/effects/overlays.dm
code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

https://github.com/tgstation/TerraGov-Marine-Corps/issues/9417 fix
:cl:
fix: Fix wraith primo overlay issue
/:cl:

Fix wraith primo overlay issue

---

code/modules/projectiles/guns/rifles.dm

0.5->.55
Makes the autosniper shoot 2BTS rather than 3 BTS.
:cl:
balance: T-81 Autosniper fires 500ms slower.
/:cl:

Autosniper fires slower.

---

code/modules/asset_cache/transports/asset_transport.dm

https://github.com/tgstation/tgstation/pull/62845/files

Double slow asset send limit

---

code/__DEFINES/MC.dm
code/datums/weather/weather.dm

https://github.com/tgstation/tgstation/pull/63222/files

Remove objects from currentrun on stopprocess

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/human/life/handle_shock.dm
code/modules/mob/living/carbon/shock.dm

Change the pain system a bit. Rather than using a switch and ramping up pain, traumatic_shock is converted into shock_stage at a rate linear with the difference between shock stage and traumatic shock.
This keeps overall the same idea that jpr had with pain, while being easier to balance out (and to understand)
I also try to make this process more reactive (aka you gain shock stage fast, but you can heal from it fast), but numbers are hard and this will need further balancing
Make pain system easier to understand. Shock is stacking faster but also disappearing faster
:cl:
balance: Shock is stacking faster but also disappearing faster
/:cl:

Pain update 

---

code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9149
Hyper it never worked, sad
We might need spitter castes after that fix, be aware of that
:cl:
fix: Fix spit timing
/:cl:

Fix spit timing

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Range is down to a 3x3 square
Easier to understand the range since it is the same as the visuals. The plasma cost was a bit high, and it prevented combos
:cl:
balance: Wraith's time stop range down to a 3x3 square
balance: Plasma cost down to 150 from 200
/:cl:

Tweak wraith time stop

---

code/game/objects/effects/overlays.dm
code/game/objects/items/binoculars.dm
code/modules/mob/living/carbon/human/death.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
code/modules/mob/living/carbon/xenomorph/death.dm
code/modules/mob/living/living.dm
code/modules/mob/living/silicon/death.dm
code/modules/mob/living/simple_animal/simple_animal.dm

I didn't take into account that different child had different constructor arg. That's ugly don't do that
:cl:
fix: Fix gib animation
/:cl:

Fix gib animation

---

code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
code/modules/mob/living/carbon/xenomorph/charge_crush.dm

:cl:
fix: Fix bull primo
/:cl:

Fix bull primo

---

code/modules/mob/living/living.dm

Title
:cl:
fix: Marine can no longer shuffle xenos
/:cl:

Marine can no longer shuffle xenos

---

code/modules/client/client_procs.dm

https://github.com/tgstation/tgstation/pull/64536/files

Client del signal port

---

code/modules/admin/panels/note_panel.dm

https://github.com/tgstation/tgstation/pull/64514/files

notes asset fix port

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm

fixed sound for larva spawn menu popup
notification for spawn menu
:cl:
fix: fixed larva spawn menu sound
/:cl:

fixes xeno larva spawn menu sound

---

code/modules/projectiles/projectile.dm

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9482
:cl:
fix: Fix projectiles hitting allies in aim mode
/:cl:

Fix projectiles hitting allies in aim mode

---

_maps/map_files/Minerva/TGS_Minerva.dmm

More content fixes for the Minerva, post-hangar fix. Corrects some pipelines, cameras, windoors and windows.
Having a working ship is a good thing.
:cl:
fix: Mapping fixes for the Minerva
/:cl:

Fixes for the Minerva

---

code/game/objects/machinery/overwatch.dm

fixes 2 typos
englis
:cl:
spellcheck: fixed two overwatch typos
/:cl:

overwatch notification typo

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Prevent from lunging if the target is too far
:cl:
qol: Prevent warrior from lunging if the target is too far
/:cl:

Warrior lunge range qol

---

code/modules/projectiles/guns/sentries.dm

Scatter reduced to 2
20 was insane and this sentry was useless, especially compared to other.
:cl:
balance: Reduce big sentry scatter to 2
/:cl:

Reduce big sentry scatter

---

code/_onclick/hud/rendering/plane_master.dm

:cl:
fix: fixed movable lights colors not showing
/:cl:

Fix movable light colors

---

code/game/turfs/turf.dm

https://github.com/tgstation/tgstation/pull/61730/files
this worked when testing on vapor/debugdalus
:cl:
fix: maybe fixed shuttle lights being dark
/:cl:

Maybe fix shuttle lights

---

code/_onclick/hud/hud.dm
code/_onclick/hud/rendering/plane_master.dm

The render plate parent was rogue
:cl:
fix: fixed hud layering
/:cl:

Fixes HUD layering

---

code/game/objects/items/explosives/grenades/grenade.dm

Title
Too much lag. Funny, but sorry
:cl:
balance: Remove chain explosions
/:cl:

Revert "Bring back grenade chain explosion (#8972)"

---

code/game/objects/items.dm
code/game/objects/items/storage/backpack.dm
code/game/objects/items/storage/boxes.dm

Title.
Better one line change.
Delete line on #9294 for a better solution.
:cl:
fix: no nade chain in any item
/:cl:

PREVENT_CONTENTS_EXPLOSION in item

---

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm

Revert to the same windup as before
I went overboard with the previous nerf
:cl:
balance: Primo runner snatch windup reduced from 1 seconds to 0,5
/:cl:

Unnerf primo runner

---

code/__DEFINES/loadout.dm

synth has a built in
:cl:
fix: fixed synth vendor having a medhud when synths get a built in one
/:cl:

Remove synth vendor medhud

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm

Stuns not stopping, it letting you skip cd
:cl:
fix: fixed some defender primordial bugs
/:cl:

Fix some centrifugal force bugs

---

code/game/turfs/walls/wall_types.dm

Remove an old title painting since it shows an old gun that we don't use.
Allow an old title painting to be used! Finally, a xenomorph title painting!
Add a new title painting thanks to Lich! It's also animated, making it one of the rare title paintings that actually animate!
We shall continue the trend of adding new title paintings to fresh up the change of pace with loading!
:cl:
imagedel: Remove an old title painting since it shows an old gun that we don't use.
imageadd: allow an old title painting to be used! Finally, a xenomorph title painting!
imageadd: Add a new title painting thanks to Lich! It's also animated, making it one of the rare title paintings that actually animate!
/:cl:

Three updates on title painting!

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm

Title.
"We can now rapidly cgareg forward again." Self-explanatory.
:cl:
fix: misspelling on primo crusher's rapid advance
/:cl:

Fix misspelling on primo crusher's rapid advance

---

code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm

Title.
Carrier doesn't have ability to store eggs anymore. This is a relic of an old time.
:cl:
del: Remove stored egg from carrier's game panel
/:cl:

Remove stored egg from carrier's game panel

---

code/game/objects/machinery/vending/new_marine_vendors.dm

looked wierd on tgui
:cl:
fix: xenonauten essentials has descsriptions now
/:cl:

xenonauten essentials has descs now

---

code/datums/elements/deployable_item.dm
code/game/objects/machinery/minelayer.dm
code/modules/projectiles/gun_system.dm

It was only working for sentries, now it works for everything
QOL
:cl:
qol: You can deploy all deployable items by cntrl clicking the ground
/:cl:

You can deploy all deployable items by cntrl clicking the ground

---

code/__DEFINES/loadout.dm
code/datums/jobs/job/marines.dm
code/game/objects/machinery/overwatch.dm
code/game/objects/machinery/squad_supply/supply_beacon.dm
code/game/objects/machinery/vending/new_marine_vendors.dm
code/modules/reqs/supplypacks.dm

Title
They currently are used for two things:
-delaying hijack/capture by spamming fob
-Grief/mistake ob
SL have binos, and it's a better system
:cl:
delete: Remove ob beacons from game
/:cl:

Remove ob beacons from game

---

code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm

Title
:cl:
fix: Fix neurotoxin sting being on queen and shrike primos
/:cl:

Fix neurotoxin sting being on queen and shrike primos

---

code/modules/projectiles/ammo_datums.dm

Neurospit buff in the slowdown_stack
Neurotoxin is having a hard time since its chem purge got nerfed and is hardly used in most times, maybe this can give it more of an use to xenos placing neurotoxinspit castes into a more of a support role giivng marines slowdown
:cl:
balance: rebalanced something
code: changed some code
/:cl:

Neurospit buff

---

code/game/objects/structures/teleporter.dm

Title.
Simple balance change that should've been there in the first place.
:cl:
balance: teleporter comes with a high-cap cell installed
/:cl:

Teleporter comes with a high-capacity cell installed

---

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9585
Fixes: Wraith primo effect was staying if the wraith was killed during the effect
:cl:
fix: Wraith primo effect was staying if the wraith was killed during the effect
fix: Runner primo works again
/:cl:

Fix wraith and runno primo

---

code/game/objects/structures/platforms.dm

fixes: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9469
:cl:
fix: Fix being able to diagonally walk through platforms
/:cl:

Fix being able to diagonally walk through platforms

---

code/modules/mob/living/carbon/xenomorph/evolution.dm

Fix larva being ancient when you regress
:cl:
fix: Fix larva regress exploit
/:cl:

Fix larva regress exploit

---

code/modules/reqs/supplypacks.dm

Title.
This gun needs some love.
:cl:
balance: T-26 AMR price reduced from 75 to 65
/:cl:

T-26 AMR price reduced from 75 to 65

---

code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm

Makes gravity nade works on where you throw it. (I tested it and works).
If its not the right way to fix it, excuse my lousy byond code.
Fixes: #9570
Fix 
:cl:
fix: Added in the proc view center on loc. 
/:cl:
https://user-images.githubusercontent.com/82890915/153613577-c8ce4c26-dd75-4a95-a746-d0228a016217.mp4
(Dont know where to put the video).

Shrike's gravity nade fix.

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
code/modules/projectiles/projectile.dm

The laser visual effect was staying when you were crossing and when it was frozen by wraith
:cl:
fix: Fix a visual bug with lasers and wraith primo
/:cl:

Fix a visual bug with lasers and wraith primo

---

code/modules/projectiles/ammo_datums.dm

When initially coding them I uh, may or may not have forgotten bullets can just miss, especially past their optimal range which for xeno ones by default isn't very high. Thanks zack for reminding me.
As lances are a single-target-focus ammo type which sacrifices most of its aoe and suppression ability for doing high damage on a direct hit, it seems unfun to have such be at the mercy of rng, especially since they already require digging in & and a channel to fire in the first place. Them having perfect base accuracy (akin to a wielded sniper rifle when standing still) should make them more viable to actually use without missing everything thats not very close.
Higher speed also serves for the purpose of increasing its viability despite requiring major setup.
Everything else has been left …

Buffs primordial boiler's lance glob accuracy and speed

---

code/_onclick/hud/rendering/plane_master.dm

:cl:
fix: fixed wraith effects cutting each other
/:cl:

fix render effect cutting

---

code/datums/elements/deployable_item.dm

Okay so this is a bandaid fix, so if there's a better way of going around this please yell at me.
Fixes #9632
Deployables not working on attach points makes the tadpole PO sad.
:cl:
fix: The dropship sentry and dropship MG should work now.
/:cl:

Fixes deployables on dropship equipment

---

code/game/objects/items/storage/belt.dm
code/modules/clothing/modular_armor/attachments/uniform.dm

title, basically.
Makes the laser pistol more useable, rather than being complete trash to use and carry.
:cl:
fix: laser pistol fits in shoulder holster
balance: pistol belts can hold 6 lasgun magazines
/:cl:

laser pistol can be held in shoulder holster, and pistol belts can hold 6 lasgun mags

---

_maps/map_files/icy_caves/icy_caves.dmm

Gitkraken messed up deleted the old pr. here is a new one
Made blue disk semi impossible to get and a messy area
:cl:
fix: bad regions and messed up apc's are now fixed
/:cl:

Northwestern Icy caves APC's fixes

---

code/modules/language/language_holder.dm

Synthethics can now talk with xenos
Alow synths and AI to talk with xenos and plan about human extermination
:cl:
add: Synths and AI can speak in xenocommon now
/:cl:

Synths can speak in xenocommon

---

code/datums/jobs/access.dm
code/datums/jobs/job/shipside.dm
code/datums/skills.dm

Adds 5 different pay grades, with each one of them controlling the Corporate Liaison's "title"/rank, based on the playtime hours of each person's time as a Corporate Liaison, with: Starting - Corporate Intern - "Int", 10 hours - Corporate Associate - "Assoc", 25 hours - Corporate Partner - "Ptnr", 50 hours - Corporate Analyst - "Anlst", 100 hours - Corporate Supervisor - "Spvr"
While such an addition may seem pointless at first, in actuality, it rewards the very idea of playing the role of a Corporate Liaison, whereas it traditionally exists primarily to be shit on by marines. The whole idea is to implement a bloated corporate structure with arbitrary ranks that technically don't change permissions, however in actuality it is a good addition in order for overall encouragement of both …

Corporate Liaison Playtime Ranks (Approved by Tivi)

---

code/__DEFINES/loadout.dm
code/game/objects/machinery/vending/new_marine_vendors.dm

It turns out there are two essentials lists, what makes this even more embarrassing is that I edited them properly in a previous PR.
Oops, this fixes the essentials lists so they actually give you what I said they would in the PRs.
:cl:
fix: makes the essentials kit edits actually work now, oops.
/:cl:

Minor previous PR essentials fix

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
_maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
_maps/map_files/Research_Outpost/Research_Outpost.dmm
_maps/map_files/icy_caves/icy_caves.dmm

Title.
MJP's engineer rework claims that it shall remove all free planetside plasma cutters, but that PR is taking too long. I do this myself in less than 5 minutes.
:cl:
del: Remove all free plasma cutters in all planetsides
/:cl:

Remove all free plasma cutters in all planetsides

---

code/modules/projectiles/ammo_datums.dm

APHE now passes trhough turfs and not mobs, and has a slower shell speed
Gives people more time to react, and the pass through mob thing was kinda dumb, honestly.
:cl:
balance: APHE on AT Gun now flies slower, and now passes through turfs/walls and not mobs.
/:cl:

at gun changes

---

code/game/objects/structures/teleporter.dm

Title
Broke crash a bit
:cl:
balance: Nuke can no longer be teleported
/:cl:

Nuke can no longer be teleported

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/projectiles/magazines/rifles.dm

Title + fix the ammo caliber in the name
It deserves a box like the rest I'd say? Plus it was already in the code, just not used
:cl:
balance : Give BR ammo boxes in vendor
/:cl:

Give BR ammo boxes in vendor

---

code/datums/components/suit_autodoc.dm
code/datums/jobs/job/freelancers.dm
code/modules/clothing/head/head.dm
code/modules/clothing/modular_armor/attachments/storage.dm
code/modules/clothing/modular_armor/attachments/uniform.dm
code/modules/clothing/suits/marine_armor.dm
code/modules/clothing/suits/storage.dm
code/modules/clothing/under/marine_uniform.dm
code/modules/clothing/under/under.dm
code/modules/codex/entries/clothing_codex.dm
code/modules/projectiles/guns/rifles.dm

Updates the Freelancers equipment, making them more comparable to regular marines.
Freelancer Leader:
Freelancer Medic:
Freelancer Standard:
I have also allowed the armor type /storage to have pockets set to null. This is for ease of modularizing things.
I also fixed a runtime with valk i found.
The ERTs havent been maintained recently, and due to various changes to the marine loadout its been hard to fight xenos as them.
The freelancers didnt even have basic attachments like the magnetic harness. The medic didnt even have tweezers.
This aims to give the Freelancers some standing in the current meta. The freelancer leader will get valk and all the freelancers guns have been given magnetic harnesses.
The freelancers have also been given some optimal storage modules.
This aims to give the …

Modernizes Freelancers

---

code/datums/jobs/access.dm

Capitalizes and adds a space to the CL timerank abbreviations
Because it looks ugly without a space between the rank and the name
:cl:
fix: Adjusted CL rank abbreviations
/:cl:

Abbreviation fix

---

code/modules/projectiles/ammunition.dm

Title
Fix
:cl:
fix: Fixes magazines deleting themselves when emptied by hand.
/:cl:

Fixes magazines deleting themselves when emptied by hand.

---

code/modules/xenomorph/xeno_structures.dm

Harversting drone primo flowers doesn't destroy them, it makes them immature again.
Make flower actually usefull. It is now an investment, since the more flowers you have, the better it is. As compared as right now, where you have no reason to make a flower rather than healing directly.
:cl:
balance: Harversting drone primo flowers doesn't destroy them
/:cl:

Harversting drone primo flowers doesn't destroy them

---

code/datums/jobs/job/job.dm

I fucked up. Again.
Fixed #9870, where jobs WITHOUT outfit variants weren't getting any ID access.
Tested and works :^)
Access is pretty useful
:cl:
fix: fixes a 100% intentional April fool's prank
/:cl:

Fix outfit variants 2: electric boogaloo

---

code/modules/recycling/conveyor2.dm

Yeah, it has 500 integrity. Not anymore.
Count each conveyor belts, then multiply by 500 integrity.
Xeno salt, and I see how marines abuse the love out of this. This is what you get for abusing this, marines.
:cl:
balance: Nerf conveyor belt from 500 integrity to 50
fix: Conveyor belt inherits 500 integrity; not anymore.
/:cl:

Nerf conveyor belt from 500 integrity to 50

---

code/modules/mapping/modular_mapping.dm
code/modules/unit_tests/_unit_tests.dm
code/modules/unit_tests/map_templates.dm

Unit test for invalid mappaths

---

code/modules/shuttle/cas_plane.dm
tgui/packages/tgui/interfaces/MarineCasship.tsx

TSX MarineCasship
Also add the following keybinds when the window is focused:
WASD and arrow keys for selecting attack direction
space to launch
enter to toggle engines
:cl:
qol: When the CAS jet UI when focused can now set fire direction with arrow keys, toggle engines with enter, take off with space
refactor: refactored some CAS jet backend
/:cl:

Cas tsx and new hotkeys

---

code/__DEFINES/_subsystems.dm
code/__DEFINES/dcs/signals.dm
code/controllers/subsystem/atoms.dm
code/game/atoms.dm
code/game/objects/effects/spawners/modularmappingspawner.dm
tools/read_init_times.py

I just copy pasted Tgs file for this and tweaked it for us, tm before merge

update atomns init

---

code/modules/projectiles/guns/rifles.dm

Title
Forgot to remove in previous pr, honestly PP is as much as an issue on T25 than it is on a shottie
:cl:
balance: Remove plasma pistol from T25
/:cl:

Remove plasma pistol from T25

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

eyeblur removed
Per title. 
Annoying and next to worthless status effect that does nothing but induce motion sickness while the Wraith is perfectly safe and comfy in godmode. 50% damage reduction and heavy slowdown are enough. 
:cl:
bal: Eyeblur removed from blink.
/:cl:

Removes Eyeblur from Blink

---

code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/projectile.dm

3x damage for guns and xeno melee.
I think and believe our population is too high on average on a basic god given TGMC round, and we need a PR like this to reduce our overall player count by removing people from the round faster.

Triples damage from guns/acid spit and xeno melee

---

code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
code/modules/projectiles/projectile.dm

Revert "Triples damage from guns/acid spit and xeno melee"

---

code/game/atoms.dm

https://github.com/tgstation/tgstation/pull/43834

No longer wait for lateinitialize

---

tgui/packages/tgui/interfaces/Sentry.tsx

tsx sentries

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm

Title. Looks like I missed the return to core ability when coding the wall stuff and noone reported it before. This fixes that issue.
Fix man good
:cl:
fix: Hiveminds can use the return to core ability if on a closed turf.
/:cl:

Fires hiveminds being unable to return to core if in a wall

---

code/game/objects/structures/barricade.dm

Title.
Tivi said it was okay after 3 hours of engineer balance in #dev-general
:cl:
balance: Reduce required sheet to upgrade metal barricade from 2 to 1
/:cl:

Buff: Reduce required sheet to upgrade metal barricade from 2 to 1

---

tgui/packages/tgui/interfaces/DroppodControl.tsx

tsx droppod control

---

tgui/packages/tgui/interfaces/Droppod.tsx

TSX droppods

---

code/__DEFINES/dcs/signals.dm
code/__DEFINES/equipment.dm
code/datums/keybinding/human.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/client/preferences_toggles.dm
code/modules/client/preferences_ui.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/inventory.dm
tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx

You can now have two quick draws woo
Stop pinging me about it okay
:cl:
qol: You can now add a new quick equip hotkey, as well as set where you quick draw from in the preferences menu
/:cl:

Alternate quick equip hotkey

---

code/game/objects/effects/landmarks/landmarks.dm
code/game/objects/machinery/vending/marine_vending.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/energy.dm
code/modules/reqs/supplypacks.dm

Gives the tesla second mode, which adds IFF but reduces effect range.
People asked for it. Fun is good.
:cl:
add: Tesla "focused" mode. Decreases range from 4 to 3, adds IFF.
code: Made tesla inherit from las rifle.
code: Added shooting modes to tesla
code: Added second projectile type to tesla
/:cl:

Tesla IFF mode

---

code/modules/mob/living/carbon/human/inventory.dm

Title
:cl:
fix:  Fix quick draw being inversed with alternate
/:cl:

Hot fix quick draw being inversed with alternate

---

code/modules/projectiles/guns/mounted.dm

Title.
MJP forgot to include this, and this should be included in the desc in case if someone new examines AT gun to see how to use it. I know that if I don't know a new weapon, I examine it.
:cl:
qol: update AT gun desc on how to anchor
/:cl:

update AT gun desc on how to anchor

---

code/datums/jobs/job/shipside.dm

bag
make s sense, they are a doctor. They are allowed a pair of oversized tweezers.
:cl:
balance: Adds twezeers to researcher
qol: RSR has tweezers
/:cl:

researcher spawns with tweezers in his bag

---

code/__DEFINES/_subsystems.dm
code/controllers/subsystem/modularmapping.dm
code/game/objects/effects/spawners/modularmappingspawner.dm
code/modules/unit_tests/map_templates.dm
tgmc.dme

I have no idea what caused it but splitting it into an ss is a good idea and fixed it
:cl:
fix: fixed a batch of modular mapping bugs
/:cl:

Fix BR runtimes and map load loops

---

code/__DEFINES/mode.dm

Title. It was 5 before
5 minutes is really long. It make PC minion upgrade not worth the points. 
:cl:
balance: You only need to wait 1 minute before taking another minions/ssd mob
/:cl:

You only need to wait 1 minute before taking another minions/ssd mob

---

code/game/objects/items/stacks/medical.dm

Reverts tgstation/TerraGov-Marine-Corps#9968

Revert "bandages heal more, but take longer to use"

---

code/game/objects/structures/teleporter.dm

Title.
Examining new thing is good. Reading how to deploy and undeploy is good. I was surprised that my other PRs didn't catch this. So it goes.
:cl:
add: update teleporter desc to tell the player how to deploy and undeploy teleporter
/:cl:

Update teleporter desc

---

tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx

Im gonna be honest I kept mixing this up so this will make it clearer than the latin terms
:cl:
qol: Changed the Ui gender options to be more clear
/:cl:

Make the gender option more clear on what they do

---

code/game/objects/items/stacks/medical.dm
code/modules/mob/living/blood.dm
code/modules/organs/limbs.dm

We will remove bleeding out from limb gone actually

Revert "Splints work as tourniquets"

---

code/datums/components/ai.dm
code/modules/ai/ai_behaviors/ai_behavior.dm
code/modules/ai/ai_behaviors/xeno/xeno.dm

Title. TM first please, this is tested but there's a lot of cases
no player facing changes

Fix ai runtime

---

code/modules/mob/living/blood.dm

Title
This is not needed actually
:cl:
del: Remove bleeding from missing limbs
/:cl:

Remove bleeding from missing limbs

---

_maps/map_files/Icarus_Military_Port/icarus_military_port.dmm

Title.
Tivi and Bravemole said no.
:cl:
del: Remove rear attachment port in Icarus LZ2
/:cl:

Remove rear attachment port in Icarus LZ2

---

code/game/objects/structures/cargo_container.dm

fixes what looks like a 2x1 container but its actually 2x2
its annoying and blocks movement when it shouldn't
:cl:
fix: 2x1 cargo container collision height
/:cl:

fix container height

---

README.md

Please check the **[Preview](https://github.com/ElectronicsArchiver/TerraGov-Marine-Corps)**.
- Converted raw links to referenced links
- General formatting / spacing / separation
- Refactored licensing information into table
- Added license badges
- Linked license material sources
CC licenses are of version 4.0, but since they were
designed as direct upgrades to 3.0, there shouldn't
be any issues.
CC Attribution -> CC BY ? 
No the game, but its repo.
Better overview of licensing notices.
Cleaner look, improved readbility.

README Rework

---

code/game/turfs/walls/wall_types.dm

:cl:
add: Added new titlescreen
/:cl:

adds a new and improved title screen

---

code/game/objects/items/tools/shovel_tools.dm

Adds checks on shovel to not be sharpened while it's being sharpened. Doesn't affect anything except the name. 
Bugfix. If you really want to have super sharp shovel just drop it on the ground and call some friends. Didn't fix that yet.
:cl:
fix: Shovel can't be sharpened more than once
/:cl:

No more sharpened sharpened shovel

---

_maps/map_files/Sulaco/Sulaco.dmm

Title.
Derrick's recent Sulaco may have excluded these.
:cl:
fix: Add two research consoles in Sulaco
/:cl:

Add two research consoles in Sulaco

---

_maps/shuttles/minidropship.dmm

adds comms to tadpole like in condor and alamo
you wont need to rely on other dropships just to get comms in tadpole
:cl:
add: comms to tadpole
/:cl:

add comms to tadpole

---

code/_compile_options.dm

Bump byond

---

code/modules/mob/typing_indicator.dm

1 liner. Allows quick closing of the input with the button or ESC.
QOL good. Brings the functionality of the wrapped hotkey dialog used for typing indicators in line with the raw verb.
:cl:
qol: The hotkey "Say" input can now be Canceled like "Me"
/:cl:

Add a Cancel button to the hotkey "Say" input

---

code/game/objects/items/scanners.dm

Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/8786
:cl:
fix: tweezers and so will no longer remove implants
/:cl:

Fix implants being removable

---

code/game/objects/items/radio/encryptionkey.dm

Title.
Researcher and Req are deeply in love with each other, therefore it makes sense that researcher gets radio access. I was surprised that researcher doesn't have this, so this is simply a one line change.
Consequently, MD and CMO will get access to req radio.
:cl:
add: Give researcher, MD, and CMO req radio access
/:cl:

Give researcher, MD, and CMO req radio access

---

code/datums/gamemodes/game_mode.dm
code/datums/jobs/job/sonsofmars.dm
code/modules/mob/mob_verbs.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/magazines/energy.dm

JUst a couple of minor tweaks.
SOM SL was missing SL skills, and a couple of description changes to the caliver and culverin to make it clear both use the powerpack (and how to load it), as well as the powerpack itself making it clear that it can recharge cells for your buddies.
I also added some more jobs to the EORD list because why not.
Please let me know if you have any feedback about SOM so far, but I haven't heard of any issues at least, so that's a good start.
Clearer instructions on how to use things are good.
SL being skilled as an SL is good.
:cl:
add: Added a few more jobs to EORD, such as SOM veterans and freelancer.
fix: Added some missing description info to some SOM equipment, and added missing SL skills to the SOM leader.
/:cl:

Small SOM tweaks

---

code/modules/projectiles/guns/rifles.dm

Their firesound name got changed with along with their actual names by accident. Honk.
Inbuilt perfect silencer bad.
:cl:
fix: Fixed AR11 and PR412 fire sound
/:cl:

Fix fire sounds for PR412 and AR11

---

code/game/objects/machinery/autodoc.dm

It's time to let the eyes not die when using autodoc.
Sometimes, it's hard to navigate the autodoc UI. Inspiration from CM.
:cl:
qol: Update Autodoc UI to make it easier on eyes to cllick on the correct procedure
/:cl:

Update Autodoc UI

---

_maps/map_files/Minerva/TGS_Minerva.dmm

Title.
Req wasn't connected to APC, so fix that. Also, symmetry is nice.
:cl:
fix: Fix APC wiring and symmetry in Minerva's req
/:cl:

Fix APC wiring and symmetry in Minerva's req

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Current fix:
Something happened in req due to a map conflict merge, so fix that.
cl main mad
Also, some pipings were bad. 
Fix wack AI nodes.
There were claims that space exist here, but I see nothing. Maybe it's the glitch that is shown in the pictures.
:cl:
fix: Fix PoS CL Office
/:cl:

Fix PoS CL Office and Req

---

code/game/objects/items.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/carbon/human/update_icons.dm

"Hey what if I remove this? Surely it's only in charge of what it says it is... Oops"
Fix good
:cl:
fix: Robot visors work again, children of the machine god rejoice!
/:cl:

Robo visors work again

---

code/modules/xenomorph/xeno_structures.dm

Title, basically.
Interaction makes sense, if it does it to xenos, should to marines. Will increase EMERGENT GAMEPLAY overall.
:cl:
balance: acid wells now extingush fire on any mob that steps on them.
/:cl:

Acid wells now extingush all mobs who step on them, not just xenos

---

code/__DEFINES/loadout.dm
code/_globalvars/lists/objects.dm
code/game/objects/machinery/squad_supply/supply_console.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/magazines/unmanned_vehicle.dm
code/modules/reqs/supplypacks.dm
code/modules/vehicles/unmanned/unmanned_droid.dm
code/modules/vehicles/unmanned/unmanned_turrets.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm

unmanned vehicles at its current state is best described as absolutely horrible and not fun to play also a waste of points, this aims to make them at least viable 
makes the previously horrible unmanned vehicles to be somewhat viable in combat and skirmishes
uavs have been rebalanced to be more helpful in combat, but will require more maintenance from marines with lower health and lower ammo count especially for heavy turret, increased bullet armor to compensate for lower health so it can survive ff somewhat also lowered ammo costs because it has way less ammo now
:cl:
add: light uav to engi vendor for 50 points
add: muzzle flash when firing
add: allows unmanned vehicles to be dropped by supply pad
balance: reduced light uav integrity to 150
balance: reduced medium uav integrity to 200 …

make unmanned vehicles viable

---

code/datums/gamemodes/game_mode.dm
code/datums/round_statistics.dm
code/game/objects/machinery/research.dm
tgui/packages/tgui/interfaces/Research/Types.tsx
tgui/packages/tgui/interfaces/Research/index.tsx

Add statistic for acquired credits through research in the research console and round-end stats.
Makes it possible for people to check how much req points researcher is producing, which is an interesting stat and can possibly help other players determine whether to provide more support to good researchers.
:cl:
qol: adds a stat for produced req points through research to researcher console and round-end, updates console UI
/:cl:

Add statistic for acquired credits through research

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
code/game/objects/structures/prop.dm

Move FC's office to give him more space and be next to CO.
Replace old FC's office into chapel.
Fix space tiles in req. Yeah, there were space tiles despite sprites saying otherwise. It's a weird bug.
Expand briefing and make TGMC letters go underneath chairs.
Add another grinder for chem users to use.
Space tiles really bad. Damn, map conflicts.
Since briefing is added, I removed the office briefing space that was next to CO, replaced that with FC's office, and make chapel.
RipGrayson gave me code to make TGMC letters in briefing go underneath chairs.
:cl:
add: Expand PoS' briefing and make TGMC letters go underneath chair
add: another grinder for chem users to use in PoS
add: Move FC's office to give him more space and be next to CO.
add: Replace old FC's office into chapel.
fix: space …

Additional PoS Polish

---

code/modules/projectiles/gun_system.dm

fixes #10113
issue with weapons (noticably shotguns) not letting you killing yourself. you can now kill yourself with them. god speed.
:cl:
fix: fixes not being able to suck-start a shotgun (suicide)
/:cl:

fixes not being able to kill yourself

---

code/modules/projectiles/gun_attachables.dm

-0.1 shaved off your slowdown.
Gives vgrip some kind of gimmick beyond being bad due to the wield speed increase.
:cl:
balance: vertical grips reduce your wield slowdown.
/:cl:

vertical grips speed you up slightly when attached

---

code/modules/projectiles/projectile.dm

Have you ever crashed when loads of bullets are flying around?
Have you ever wanted to fire guns at absurdly high rates of fire?
This PR fixes an extremely old bug that has plagued the server and it seems our predecessors, crashing everyone on screen.
Shout out to @2whatever2 for discovering the source of the bug: When a turf is hit by a bullet, a short bullet bounce animation is played. When a large number of these bounces are done on a single turf, the act of actually REMOVING the image from the turf just randomly mass crashes everyone on screen.
This is a byond bug so who knows why it actually happens, but it seems they way these were being handled was kinda shit code anyway, so I changed it to overlays which has fixed the problem.
This now opens the doors to guns with all the dakka, …

Banish mass crashes to the shadowrealm

---

code/datums/jobs/job/shipside.dm

Changes the PO duty and spawn message
The current PO duty and spawn message are ancient, the spawn message in particular suggests that you shouldn't leave the Almo without reason (POs haven't been flying the Alamo themselves way before the addition of automatic).
This updates them to more closely match modern policy and PO playstyle.
:cl:
qol: PO duty and spawn message have been updated
/:cl:

Changes PO description

---

code/game/turfs/walls/wall_types.dm

Adds some SOM to lobby art.
_BURNING FLESH_
:cl:
add: Added new lobby art
/:cl:

New SOM lobby art

---

code/__DEFINES/dropship_equipment.dm
code/game/objects/items/binoculars.dm
code/game/objects/structures/dropship_ammo.dm
code/game/objects/structures/orbital_cannon.dm

make railgun better at its job
currently you can just ignore railgun by standing in the middle of the laser, gives it minirocket stats for clearing weeds and area denial, increased cooldown to 5 minutes and spread to compensate
:cl:
code: railgun targeting changed from pick to rand
balance: increased railgun spread
balance: changed railgun to be explosive
balance: increased railgun cooldown to 5 minutes
balance: reduced time it takes to fire and land railgun
/:cl:
https://user-images.githubusercontent.com/98577688/166409471-847f21d9-d772-4210-b66a-ad3af1491310.mp4

Railgun Changes

---

code/game/objects/items/scanners.dm

Title.
Hyper intended to bold this, but he forgot to finish the bolding.
:cl:
fix: bolding on medical scanner for brain damage
/:cl:

Fix missing<b> in medical scanner for brain damage

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Not to be mistaken with hive message (the queen big text), this is the otherwise completely worthless game tab text message that queens used to be able to set.
Well I removed the code relating to that on the abilities side when I merged orders into hive message but forgot to check the rest of the files for any dangling code aspects. These are the few I believe remain within the code.
Worthless and inactive code remaining in the main game loop means bad performance and technical debt.
I'm doing my part to clean up the code. (Insert Starship Troopers)
Code already does nothing. No changelog.

Removes Remaining Remnants of Hive Orders

---

.github/CODEOWNERS

Remove old org team members that can not automatically, and probably do not want even with a special action, to be pinged by CODEOWNERS.
No CL

CODEOWNERS maintenance

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Fixes #9990 by adding in the proper deletion check.
Now objects being destroyed in banish space dont come back as an invisible wall.
:cl:
fix: Wraith banish no longer inserts invisible wall if banished object is destroyed.
/:cl:

Fixes Banish Returning Null Structure

---

code/datums/gamemodes/crash.dm
code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
code/modules/mob/living/carbon/xenomorph/evo_datum.dm
code/modules/mob/living/carbon/xenomorph/evolution.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm

Yet another ancient section of code from CM that made larva evolution a snowflake in the handling of evolution processes. Well no longer. Now it updates along the same functions as every other xeno in the game.
Obligatory how old git blames:
An atomized change PR from my current ongoing hive status TGUI overhaul. And old snowflake code bad.
:cl:
refactor: Larva evolution handing is now processed along the same functions as all other xeno castes.
/:cl:

Refactors Larva Evolution Code

---

code/game/objects/items/power_cells.dm
code/game/objects/items/tools/mining_tools.dm

https://github.com/tgstation/TerraGov-Marine-Corps/pull/10105
:cl:
expansion: PC now gains 200 charge when it hits a living creature
del: Removed PC emp act
balance: PC cell size from 8500 to 7500
/:cl:

Github my beloathed (PC gains charge on hit)

---

code/_onclick/ventcrawl.dm
code/modules/atmospherics/machinery/atmosmachinery.dm

Removes broken check that was a holdover from other codebases with functioning atmospherics. TGMC's atmo is the lobotomized variant that I should probably take a shovel to and finally bury some last remaining vestigial functions. Someday. For now, this fix.
Suspicious Xenos can now see where they are going.
:cl:
fix: Xenos in vents can now see the pipe network overlay.
/:cl:

Fixes Pipe Visualization

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Title. Punch and jab did not respect user armor.
Fix good
:cl:
fix: Warrior punch and jab respect mob armor
/:cl:

Armor check fix punch and jab

---

code/__DEFINES/loadout.dm
code/datums/loadout/loadout_helper.dm

Title
:cl:
fix: Fix loadouts giving marine access to nanomed vendor
/:cl:

Fix loadouts giving marine access to nanomed vendor

---

code/modules/projectiles/guns/specialist.dm

Per title.
Instakill from offscreen is quite unfun.
:cl: Lewdcifer
balance: RL-152 no longer accepts mini scopes.
/:cl:

Removes mini scope from RL-152

---

code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm

isdead is a typecheck rather than a 'has target died' check
Bugfix
:cl:
fix: Fixed a tiny bit of unreachable code in gorger transfusion failure messages
/:cl:

Fixes a gorger target dead check

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

Title.
Fix good.
:cl:
fix: Fixed xeno structure selection out of bounds error.
/:cl:

Fix xeno structure selection out of bounds error

---

code/modules/reagents/reagents/medical.dm

Title
Drugs should not have any effects on dead marines, this is just a bug fix
:cl:
fix: Fix inap, RR and neuraline working on dead bodies
/:cl:

Fix inap, RR and neuraline working on dead bodies

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm

Title.
Fix good.
:cl:
fix: Fixed hivemind mob perma rest on ghosting.
/:cl:

Fix hivemind mob perma rest on ghosting

---

code/game/turfs/walls/wall_types.dm

New lobby art, created by player **Ghost_Guts**.
Added as a lobby image with his permission.
More lobby art good.
:cl: Ghost_Guts (added to code by Lewdcifer)
imageadd: New lobby art: between a crate and a hard place.
/:cl:

New lobby art - between a crate and a hard place

---

code/__DEFINES/loadout.dm
code/game/objects/machinery/vending/new_marine_vendors.dm

Fixes : #10339
Fixes good
:cl:
fix: SG stuff can now be saved in loadouts again
/:cl:

SG loadout fix

---

code/game/objects/machinery/dropship_part_fabricator.dm

The PR PO mains have wanted for so, so long. Menu is still clunky but it's a LOT better.
-Balloon alerts to fabricator. Much prettier and visual feedback for the buttons.
-Fabricator active icon will show now. Minor fix, sorry for not atomizing this properly, it's on line 77/78
-Changed href 'produce' to 'choice' because produce is a fucking horrible name
-Some comments to un-shitify the code somewhat, if there should be any more please tell me because I'm bald as fuck at making code readable and I know I missed a lot.
-Adds a queue to the fabricator. Queue is visible at the bottom, can be cleared if needed. This is like 90% of the code.
Queue has been a long-awaited feature that nobody's bothered to code for... fucking years, holy shit. It's pure QOL and it's massive QOL at that. …

Dropship fabricator queue

---

code/game/turfs/walls/wall_types.dm

Adds two new images to the lobby art selection, made by **SilencedMP5A5 / Ocelot** and **Ghost_Guts** respectively, with permission from both authors.
More lobby art good.
:cl: Lewdcifer
imageadd: New lobby art: a good meme never dies.
imageadd: New lobby art: droid bullies larva.
/:cl:

More lobby art - A good meme never dies + Droid bullies larva.

---

_maps/modularmaps/big_red/barracks.dmm
_maps/modularmaps/big_red/operation.dmm

Relocate APC in Big Red's barrack and operation.
Change up barrack a bit to make up for the lost function of said APC room.
Why APC is not in the same room as disk is lost to me. I will have to go through each map to ensure that APC is easy to hold and not Hell to maintain.
:cl:
add: another APC in Big Red's barrack and operation since they house green disk
add: Change up barrack a bit to make up for the lost function of said APC room
/:cl:

Relocate APC's location in Big Red's barrack and operation

---

code/game/objects/machinery.dm
code/game/objects/machinery/autodoc.dm
code/modules/mob/living/carbon/shock.dm
code/modules/organs/limbs.dm
code/modules/organs/organ_internal.dm

Bet you didn't know this even happened. Usually completely irrelevant, and absolutely uncommunicated except via body scanners/autodocs. And coughing, sometimes.
Streamlining medical. Germs hang out on limbs and do stuff there, plus if they went necrotic they already have a route to hurt organs.
:cl:
del: Internal organs can't get infections. They mostly didn't already.
/:cl:

Removes germs from internal organs

---

code/game/objects/machinery/doors/door.dm

UAVs (droid and such) can open doors by bumping into it. If the door is locked, unpowered or anything else they cannot open it
QOL basically
:cl:
qol: UAVs can open doors by bumping into it
/:cl:

UAVs can open doors

---

code/game/objects/items/tools/mining_tools.dm

Do plasma cutters need this? Probably not. Is it going to matter with any frequency? Probably not. Am I making this PR anyway? Yes. 20% of the caste's max regenable plasma drained per hit.
Also conjugates plasma cutter's attack verbs, since they were showing up weird.
Fixes an inaccurate tool name.
:cl:
add: Plasma cutters now cut plasma, 20% per hit.
/:cl:

Makes plasma cutters cut plasma

---

.vscode/extensions.json

DMI editor which i saw on TGstation extensions: https://marketplace.visualstudio.com/items?itemName=AnturK.dmi-editor
absolutely madlad whoever did this

Adds DMI editor to VSC extension recommendations 

---

code/datums/elements/deployable_item.dm
code/game/objects/machinery/minelayer.dm
code/game/objects/machinery/mortar.dm
code/game/objects/structures/teleporter.dm
code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/guns/mounted.dm
code/modules/projectiles/guns/sentries.dm

fix https://github.com/tgstation/TerraGov-Marine-Corps/issues/10411 and some other bugs
:cl:
fix: Fix teleporter being mountable
/:cl:

Fix teleporter being mountable

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Range from 10 to 20
Portal are now invulnerable to bullets, but marines can destroy it with any explosion
Human can no longer cross portal
Portal were nerfed because marines could cross them (and be braziled). This has been removed, so we can buff portals again.
They are more interesting as a support tool than a super brazil tool
:cl:
balance: Wraith portal range buffed from 10 to 20
balance: Wraith portals are no longer vulnerable to bullets; they are now vulnerable to explosions
balance: Human can no longer cross portal
/:cl:

Buff wraith portal

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Blink from 50 to 30
Banish from 100 to 50
time stop from 150 to 100
protal from 100 to 50
Wraith is always starving for plasma, which cripples the caste. It relies entirely on abilities since it's very squishy with little damage, it needs more plasma
:cl:
balance: Reduce plasma cost of all wraith abilities
/:cl:

Reduce plasma cost of all wraith abilities

---

code/modules/surgery/organs_internal.dm

Title
:cl:
fix: Fix organ damage not being treated by surgery
/:cl:

Fix organ damage not being treated by surgery

---

code/_compile_options.dm
code/game/world.dm
code/modules/client/client_procs.dm
code/world.dm
dependencies.sh

Needed for portal fancy graphics. Client not affected

Bump byond to latest

---

code/modules/projectiles/guns/specialist.dm

Title, spawns wiht proper gun flags.
Fixes this bug.
:cl:
fix: RL-72 has proper gunflags on spawn.
/:cl:

RL-72 has proper gunflags on spawn

---

code/modules/organs/organ_internal.dm

Needs a separate arg since we're adjusting an existing modifier after the first change.
Fixes #10462 
:cl:
fix: Healing lungs removes slowdown
/:cl:

Fixes lungs not updating slowdown

---

_maps/bigred_v2.json
_maps/desertdam.json
_maps/icarus_military_port.json
_maps/ice_colony_v2.json
_maps/icy_caves.json
_maps/lv624.json
_maps/magmoor_digsite_iv.json
_maps/prison_station_fop.json
_maps/research_outpost.json
_maps/vapor_processing.json
_maps/whiskey_outpost_v2.json
code/datums/map_config.dm

Hey so did you know that all maps have an announce_text but you never see it in-game?
wanna guess why?
announce_text never actually got defined into what the .json has in it
As such i have now added `announce_text = json["announce_text"]` to `map_config.dm` 
Removed "###SHIPNAME###" from all .json map files and replaced it with a simple "ship", adjusted some spelling for this to function.
Removed code designed to replace "###SHIPNAME###" with the name of the ship map since it didn't actually work and i can't be bothered to try and spend alot of effort for a _very_ tiny flavor benefit.
I have also changed the icarus military port announce_text from this
to this
"Within the last couple days the Icarus Military Port has confiscated contraband from an illegal smuggling ship running narcotics …

Roundstart map announce_text fixed & icarus military port announce_text changed

---

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm

Snatch doesn't work on corpses.
Fixes #10484 
:cl:
fix: Runner primo snatch can't be used on corpses
/:cl:

Runners can't graverob

---

code/modules/projectiles/guns/rifles.dm

Reduces Mpi slowdown by .1 to .6, considering .7 is LMG level, this seems better for the gun.
MpI can now take vgrip or underbarreled guns.
Gives the MPi a bit more of a gimmick and a slight buff considering its poor overall performance in the grand scheme.
:cl:
balance: MPi slowdown reduced a bit, it can take vgrip or underbarreled guns now as attachments.
/:cl:

Mpi-KM attachment changes and slowdown reduction

---

code/game/objects/items/jetpack.dm

No more wasted fuel while buckled to big things, and no more taking small buckled things along for a free ride.
Fix good.
:cl:
fix: Fixed jetpack flying while buckled.
/:cl:

Fix jetpack flying while buckled

---

code/modules/unit_tests/_unit_tests.dm
code/modules/unit_tests/unit_test.dm

I used this reference tgstation/tgstation@9eed0893e4e11b1c0e8d81f4ceaaf99962b054a3
Now you can use test-driven development
:cl:
code: Tgstation Test explorer for VScode now work properly
/:cl:

Tgstation Test explorer for VScode now work properly

---

code/modules/mob/living/blood.dm

If a human is above maximum blood volume (about 7% above normal max) the extra blood will fall out. Go for the high score and splash your friends. QC suppresses bleeding as usual but once it runs out you pop. Doesn't apply any actual damage.
Fixes #10488 
Prevents just putting iron/qc in your system and getting to ignore anything that affects blood level.
:cl:
add: If you have too much blood in you and no quickclot, all the extra blood will spill.
/:cl:

Blood over maximum leaks out

---

code/modules/surgery/necrosis.dm
code/modules/surgery/organs_internal.dm
code/modules/surgery/surgery.dm

Necrosis needs to go first.
Fixes #10524 
:cl:
fix: If you have both organ damage and necrosis, trying to treat with a membrane will prioritize the necrosis.
/:cl:

Swap surgery prio for necrosis and organ repair

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/modularmaps/big_red/bigredtoolshedvar1.dmm
_maps/modularmaps/big_red/bigredtoolshedvar2.dmm
_maps/modularmaps/big_red/bigredtoolshedvar3.dmm
_maps/modularmaps/big_red/bigredtoolshedvar4.dmm
_maps/modularmaps/big_red/bigredtoolshedvar5.dmm

Fixes a few issues with the engineering tool shed modular map.
Fixes a few modular map issues on Big Red
Better generated Big Red
:cl:
fix: fixed minor map issues
/:cl:

Big Red modular map fix

---

code/game/turfs/walls/wall_types.dm

Adds new lobby screen. Credit to LCPL Fitz 'Caesar' Sholl
This pic goes hard feel free to screenshot
:cl:
imageadd: New lobby art: Woyer boxing
/:cl:

Adds Woyer Boxing lobby screen

---

.vscode/extensions.json
.vscode/settings.json

the removed extension ins't needed anymore because spaceman's extension already does that better https://github.com/tgstation/tgstation/pull/66862

DMI editor actually works now + remove outdated extension

---

code/_onclick/ventcrawl.dm
code/modules/atmospherics/machinery/atmosmachinery.dm
code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
code/modules/organs/organ_internal.dm

Cleans up cryo code, fixes the weird vision thing as well as blindness just flicking for a moment, makes kidneys not produce trouble while in cryo.
Also lets cryo ignore robotic limbs when determining whether to auto-eject, since it doesn't treat those.
Fixes #10297 
General cleanup.
:cl:
fix: You don't get weird vision while in cryo
balance: Kidneys don't produce drawbacks while in cryo
/:cl:

Cryo fixes

---

code/__DEFINES/xeno.dm

Fixes defiler being able to choose sanguinal. Fixes #10523 (funny)
Fix good. Sanguinal choice is not intended.
:cl:
fix: Defiler can't choose sanguinal
/:cl:

Defiler fix MKII

---

code/modules/organs/limbs.dm

Title
https://github.com/cmss13-devs/cmss13/pull/618
More feedback to player about health and character state. Also you'll probably screaming your ass off if your arm fell off
:cl:
qol: Delimbing procs scream emote
/:cl:

Scream on delimb

---

code/datums/keybinding/xeno.dm

Just needed a 4 line `/datum` ez
Button good. 
:cl:
qol: Added a keybind for Wraith: Time Shift.
/:cl:

Add wraith time shift keybind

---

code/controllers/subsystem/vote.dm
tgui/packages/tgui/interfaces/Vote.js

Example, you can vote for 2 out of 4 maps during map voting.
This type of vote is superior in all points to single choice votes.
See https://en.wikipedia.org/wiki/Approval_voting 
For example, let's say 60% of the players want to play HVX, but 35% vote distress and 25% vote nuclear war. This let combat patrol win despite only having 40% in support of HVH. To avoid that HVX lover would strategically vote for either Distress or Nuclear war, which can lead to weird effect like everyone voting nuclear war despite it being less popular than distress in our example.
Same can be said with maps, etc. Multiple voting system allow people to just vote for their favorites (or least hated) choice without having to strategize
:cl:
add: Allow multiple choice voting
/:cl:

Allow multiple choice voting

---

.vscode/extensions.json

Title
For a full game development experience in VSC

Add sound preview extension to recommended

---

code/_globalvars/lists/mapping.dm
code/controllers/subsystem/job.dm
code/datums/gamemodes/crash.dm
code/game/objects/effects/landmarks/landmarks.dm

Remove a system that was unused
Confusing and useless
:cl:
code: Remove a unused part of jobspawning system
/:cl:

Remove a unused part of jobspawning system

---

code/modules/reagents/reagents/medical.dm

Reverts my accidental changing of Arithrazine
Accidental undocumented changes aren't good
:cl:
fix: Reverts Arithrazine to it's old form
/:cl:

Fixes Arithrazine

---

code/game/turfs/walls/wall_types.dm

Add three new title arts, one from Ghost_Guts | sleepy eyed robot, and two from Foster.
From Ghost_Guts | sleepy eyed robot
From Foster
Add a slight animation in the PFC Jim title art to show that he's NOT doing okay AND replace a title art that has a MP using a minigun with a smartgunner facing against a rav and warrior which is also made by Foster.
I change the MP one since MP is no more. I wonder who that smartgunner is.
Foster and sleepy eyed robot gave us content for the community to appreciate! Since I volunteer to add these title art, this is the PR.
I also add in a not well known part of PFC Jim's letter since it's very cool. Bravemole likes the picture, so I put it in as an easter egg for all to see.
:cl: nova_epee, Ghost_Guts | sleepy eyed robot, and Foster
imageadd: added two …

Updating and Adding Title Art

---

code/game/data_huds.dm

Title. Added by Combat Patrol PR
No player facing change

Fix a runtime when setting up hud with a neutral faction mob

---

code/controllers/subsystem/vote.dm

Stops you from voting infinite times when the vote doesn't have multivote enabled.
Fixed #10623
Funni vote bug is bad
:cl:
fix: Vote ballot stuffing has been fixed
/:cl:

Fix vote fixing

---

code/controllers/subsystem/vote.dm

Mid game votes are literally the worst. Fixes #10649
Fixes a 3 year old bug that meant the result of a gamemode vote triggered mid game would override the results of the end of game gamemode vote, where the midround vote was for a different gamemode to the current gamemode, but the end of round  vote was for the current gamemode.
Also future proofed gamemode votes so if you vote for a gamemode that has a mode specific map it'll restart to load the correct map (currently you can't actually vote for civil war/combat patrol pregame if their specific map isn't already loaded, so this can now be changed if desired).
Votes working as intended = good
combat patrol getting loaded without patrol base = bad
:cl:
fix: gamemode votes should now work as expected in all cases.
/:cl:

Fix mid round gamemode vote bug

---

code/modules/client/preferences_ui.dm

Title. You'd get a blue screen
Note: doesn't fix robots getting blue screen but that's harder to fix
:cl:
fix: Fix plural gender not able to chose gear
/:cl:

Fix plural gender not able to chose gear

---

code/modules/projectiles/projectile.dm

Projectile code still had a funny bit of code where it did a return prob(.). This works fine in 514.1584, but in 1585 this breaks entirely, meaning it would be impossible to shoot past objects.
Fixes this bug before it becomes an actual problem, and clean up the shitcode.
:cl:
fix: fixes a projectile bug for a future version of byond
/:cl:

Squish shitcode and a future bug

---

code/game/objects/items/motion_detector.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10657
:cl:
fix: Fix motion detector shutting down impromptly
/:cl:

Fix motion detector shutting down impromptly

---

code/game/objects/machinery/doors/airlock_types.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10606
:cl:
fix: Fix ai controlling doors groundside
/:cl:

Fix ai controlling doors groundside

---

code/modules/admin/admin_verbs.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10514
:cl:
fix: Set Xeno buffs admin verb is now in percentage
/:cl:

Set Xeno buffs admin verb is now in percentage

---

code/modules/shuttle/on_move.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10286
:cl:
fix: Fix direction on pipe changing when tadpole is landing
/:cl:

Fix direction on pipe changing when tadpole is landing

---

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9836
:cl:
fix: Fix inconsistent hugger activation on hit
/:cl:

Fix inconsistent hugger activation on hit

---

code/modules/atmospherics/machinery/atmosmachinery.dm
code/modules/projectiles/gun_helpers.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9487
:cl:
fix: Fix being able to vent out in dense object
/:cl:

Fix being able to vent out in dense object

---

_maps/map_files/Minerva/TGS_Minerva.dmm

Title.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/10477.
Bugs bad, another issue down.
:cl:
fix:The CAS storage doors on Minerva now work as intended.
/:cl:

Fixes nonfunctional CAS doors on Minerva

---

code/modules/shuttle/mini_dropship.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9513
:cl:
fix: Prevent from spamming launch in tadpole
/:cl:

Prevent from spamming launch in tadpole

---

code/game/objects/effects/landmarks/corpsespawner.dm
code/modules/mob/living/carbon/human/death.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9261
:cl:
fix: Fix corpse spawner being counted in statistic
/:cl:

Fix corpse spawner being counted in statistic

---

code/game/objects/items/radio/detpack.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9515
:cl:
fx: Prevent sending detonation signal from a different z level
/:cl:

Prevent sending detonation signal from a different z level

---

code/__HELPERS/unsorted.dm
code/modules/mining/remote_fob/remote_fob_fobdrone.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9702
:cl:
fix: Fix fob drone placing cade diagonally
/:cl:

Fix fob drone placing cade diagonally

---

code/datums/components/autofire.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9867
TM first maybe
:cl:
fix: Fix burst breaking gun in high lag situation
/:cl:

Should fix burst breaking gun due to lag

---

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10515
:cl:
balance: Prevent placing silo and other blessing's building near fob, outside of weeds, etc.
/:cl:

Add location check for building silos and such

---

code/game/objects/structures/droppod.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9402
:cl:
qol: Drop pod ejects marine if the marine dies
/:cl:

Drop pod ejects marine if the marine dies

---

code/modules/shuttle/marine_dropship.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9414
This check is actually not needed as if it's tampered then either it is already ground side or moving
:cl:
fix: Fix alamo being stuck shipside if you touched the console too late
/:cl:

Fix alamo being stuck shipside if you touched the console too late

---

code/modules/projectiles/projectile.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9613
:cl:
fix: Fix stagger not being applied with deployed gun
/:cl:

Fix stagger not being applied with deployed gun

---

code/datums/elements/deployable_item.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9949
:cl:
fix: Cannot deploy via alt click menu
/:cl:

Cannot deploy via alt click menu

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10491
:cl:
fix: Prevent corpse lunging
/:cl:

Prevent corpse lunging

---

code/game/objects/structures.dm

Bumping into a climbable structure will make you climb automatically
Gotcha CM
:cl:
qol: Add auto climbing
/:cl:

Add auto climbing

---

code/modules/organs/limbs.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10661 
:cl:
fix: Fix synth's getting human limbs after aheal
/:cl:

Fix synth's getting human limbs after aheal

---

code/__DEFINES/equipment.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
code/modules/projectiles/projectile.dm
code/modules/xenomorph/xeno_structures.dm

Only used to prevent to shoot yourself in really high TD and to prevent being shot twice from percing ammo in rare occasions.
Probably not worth the performance cost. Not shooting yourself can be done with simpler src == firer checks
:cl:
code: Minor performance increase in projectile code
/:cl:

Remove permutated from projectile code
