_maps/map_files/icy_caves/icy_caves.dmm

**NEW PR: past one was too old and gave errors that i couldn't fix. thankfully they are fixed now**
I have been getting some dm's to bring back my icy caves edit, so here it is with fixes and some changes.
Swaps around Crash disk locations, move some stupid silo spots in Crash and changes them up to make it a bit more challenging for marines as they dominate this map whilst not giving Xenos free handouts either. LZ2 is redone sorta. Lz1 has been tinkered with and northwest caves have a new area, 
:cl:
balance: LZ2 semi redone to make it more appealing for marines
balance: some LZ1 changes
balance: moved crash disk locations
balance: removed some silos like that one in the nuke disk area and replaced them elsewhere
balance: caves have been fully pre wedded as they should
add: new area …

Icy caves v2.0

---

code/__DEFINES/monitor.dm

Title.
After much discussion between Yellow | SO and Bravemole, Bravemole is okay with spawn rate revert but not minion stats revert. Xenomorph's winrates are at an all time low.
:cl:
balance: revert minion spawn rate nerf, so for 50 players, each spawner can generate 7 mobs
/:cl:

Revert Minion Spawn Rate Nerf

---

code/__DEFINES/loadout.dm
code/modules/mining/remote_fob/remote_fob_actions_misc.dm
code/modules/mining/remote_fob/remote_fob_computer.dm

Title. Git will remember.
PR is bringing awareness to the almost non-existence of this tool.
Engineers have a budget, and spending 26 engineer points for a green sentry, the UA 571-C, is not one of them. Marines spawn with at least four UA 571-C crates which include additional ammo, whereby the voucher does not give more ammo. It is also the fact that if FOB drone is dead, voucher is useless. A time-sensitive item that no one uses should go unless we have a better use of this.
Even if I were to give this to CSE, which is unlikely, CSE has to spawn before Alamo flies, which is even more unlikely than CSE getting a voucher.
Voucher was made by terranaut1, legendary in TGMC, in #3566 . He said, "for sentry gun placement there's vouchers available you can buy at the engi prep vendor for the …

remove Sentry gun voucher

---

code/game/objects/machinery/autolathe_datums.dm

Removes contraband items from autolathe
Further removal of hacking from commonly used machines. Autolathe is something marines rarely use anyways so having a barrier for the only useful item, the industrial blowtorch, was kinda meaningless anyways.
If requested I will also fully remove handcuffs and electropack since they are both obsolete items
EDIT: The request was to remove ALL items so industrial welder is gone from the game.
:cl:
del: Autolathe contraband items removed
/:cl:

Autolathe Contraband Removal

---

code/datums/actions/item_action.dm
code/modules/clothing/modular_armor/modular.dm

Title. Thank you Bravemole and Hyper for helping me through my insanity and fumbling check of 2 hours for essentially adding 6 lines of code.
Sometimes, turning on lights doesn't tell you that your lights are on. The reason for this is because the action icon or the mob's armor sprites doesn't indicate anything about it.
Long time ago before Jaegar, all armors have shoulder lights to indicate whether you have lights on or not. This is a design from CM SS13 that we inherited but lost due to Jaegar. 
This is why marines tell smartgunners or marines with imagers to turn on their lights. There is almost no way of telling whether your, that is the smargunner or imager players, lights are on or not. The surest way is to turn off NVG or imager, but (1) you can't do that in the middle of combat …

Overlay on Suit Toggle Button when Turning On and Off Suit light

---

code/modules/projectiles/guns/rifles.dm

TX-11 and T-18 have had extra delay removed.
These weapons are burst focused and making their one upside over other firearms (or sidegrade gimmick in the case of the tx-11) seems quite unneeded now, if the issue lies with BFA, add extra delay to BFA.
:cl:
balance: TX-11 and T-18 extra delay removed.
/:cl:

TX-11 and T-18 no longer have extra delay on burst fire.

---

code/game/objects/items/storage/boxes.dm

Adds the PREVENT_CONTENTS_EXPLOSION flag to grenade boxes. If a grenade blows near a grenade box, the grenades inside won't blow
Chain grenades are pretty funny, let's be honest, but they're extremely devastating
Brave said he wouldn't remove chain grenades but he would accept a PR which made grenade _boxes_ not explode
This makes the game more fun while pleasing people who like chain grenades
:cl:
balance: Explosions no longer blow grenades inside grenade boxes. The FOB is safe once more
/:cl:

Grenade boxes don't chain grenade

---

_maps/map_files/Minerva/TGS_Minerva.dmm

Moves Minerva Tadpole to a more central location, Compresses Self Destruct, and moves the dropship ammo closer to the Condor.
Areas of note:
Condor Ordinance: 
Tadpole Repositioning: 
Self Destruct Compression: 
Addresses some complaints in regards to ease of access of systems, improving the user experience.
:cl:
fix: Minerva hangar has been retrofitted for increased usability.
/:cl:

Minerva Hangar Retrofit

---

code/modules/projectiles/guns/revolvers.dm

Closes #9317
So there's a 5 frame window where you can use quick equip to quickly put the revolver (while it's invisible for the trick) away into an inventory. This fixes that. 
Less bugs. Unless unintended =/= inconsistent applies here and this revolver trick should be uniquely bugged.
:cl:
fix: The revolver toss trick should no longer bug inventories out if you quick equip it while it's in the air.
/:cl:

Fixes quick equip exploit for the revolver toss trick

---

code/modules/admin/fun_verbs.dm

Closes #9312
A random comma was left over, causing a runtime
Less bugs, unless inconsistent =/= unintentional and this was some insidious grand plan to stop admins from using this verb
:cl:
fix: The Global narrate verb is fixed.
/:cl:

Fixes global narrate

---

code/modules/projectiles/guns/sentries.dm

Closes #9252
Restricts the sentry kit box to only be able to hold sentries and it's ammo
Fixes storage creep, unless we're going with the inconsistent=/= unintentional thing again. I did ask and was only met with cold contemptuous discord silence, which more or less implied "Is this guy for real?" 
:cl:
fix: Sentry kit boxes can only hold sentries and their respective ammo now, crushing the horrible meta of being able to carry 5 backpacks by hand, or 5 other objects of large and dubious size.
/:cl:

Sentry kit box can only hold ammo and sentries

---

code/game/turfs/walls/resin.dm

Makes walls die in 1-3 hits from light explosions (Grenades, etc..) 100-150 from 25-50.
Walls die instantly from heavy explosions as well as devastate.
I like this change personally for a few reasons, it makes explosives far more effective at removing walls as it should, and heavy explosions are rare enough to be decent at it.
Light explosions need to be better at destroying walls, as right now they're absurdly bad. The initial stats I pooped out are bad.
:cl:
balance: Heavy level explosions break resin walls instantly, light explosions deal far more damage to resin walls.
/:cl:

Resin walls take more explosion damage, and die instantly to heavy explosions.

---

code/game/objects/effects/effect_system/smoke.dm

Changes Transvitox and hemodile to non transparent.
Makes both now viable for use rather then heavily risk death in a group combat scenario because of its opacity
:cl:
balance: opacity for transvitox and hemodile no longer 60 but 255
/:cl:
1
2

Defiler Hemodile and Transvitox gas is no longer transparent.

---

code/controllers/subsystem/timer.dm

Previously it was possible for events to enter the short queue when the timer is offset by more than BUCKET_LEN
Now it is forced to schedule events into the second queue if the timer is processing slower then world time goes allowing the timer to keep up
This PR provides a better definition of `TIMER_MAX` to avoid scheduling timed events that are more than one window of buckets away in terms of `timeToRun` into buckets queue and properly passing them into the second queue.
Ports https://github.com/ss220-space/Paradise/pull/578
The timer subsystem mainly uses two concepts, buckets, and second queue
Buckets is a fixed-length list of linked lists, where each "bucket" contains timers scheduled to run on the same tick 
The second queue is a simple list containing sorted timers that scheduled …

Fix: Avoid timer scheduling too far events into short queue

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
_maps/map_files/LV624/LV624.dmm
_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm

In Big Red, there are big red signs to tell engineers where to put barricades. I put some in Prison Station, Ice Colony, and LV-624.
If you don't see hazard sign, it probably means you don't need to cade that reinforced wall.
Consistency between map is good. Helps with ensuring that one good map practice transfers between other maps.
:cl:
add: hazard signs to help FOB engineers
/:cl:

hazard signs to help FOB engineers

---

_maps/map_files/Sulaco/Sulaco.dmm

Title. Soda dispenser is now actually in Sulaco.
Other shipside maps have this, but not Sulaco. It's time to change that.
:cl:
add: Sulaco medbay now has a break room with access to a soda dispenser. Yeah, you go get that tomato juice and soon to be milk.
balance: Access to soda dispenser, which contains tomato juice and soon to be milk
/:cl:

Sulaco Medbay's Break room

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/revolvers.dm

revolver changes
Readds knockback to revolver, makes akimbo have the same firerate as before so no change. And readds knockback to the bullet.
Everyone has cooled off about revolver. Let it have SOME gimmick.
This should give it a neat gimmick without making it top tier overpowered.
:cl:
balance: Revolver fires at 0.15 when non akimboed, and has knockback again.
/:cl:

revolver changes- non akimbo firerate buff, and knockback readded

---

code/modules/shuttle/marine_dropship.dm

- The option to hijack the alamo to go shipside now has a yes/no prompt so you don't fat finger it.
- Locking the alamo by clicking the console as a hive ruler now actually gives out a line in chat so you know you actually did it
Mmm how is it not?
:cl:
add: Added a yes/no prompt for hijacking the alamo
add: Hijacking the alamo by clicking the console as a hive ruler now gives out a line in chat so you can be sure you actually did it
/:cl:

Adds a confirmation to hijacking the alamo, adds a line when you lock the alamo as xeno by clicking the console

---

code/controllers/subsystem/mapping.dm
code/controllers/subsystem/persistence.dm
code/modules/mapping/modular_mapping.dm
tools/requirements.txt

I've been needing to do this for a bit, essentially allows for mappers to define min and max player values needed for a modular mapping insert to be in "rotation" for a given map.
E.g I could define a LV dome to only show up with a population of between 50 and 100. 
This sort of thing has been needed for quite a while and the potential is fairly limitless. We could theoretically define places in big maps like Chigusa and Magmoor that shrink on lower pop and grow at higher pop, allowing for much more flexible maps.
:cl:
code: Added population dependent mapping insert support.
/:cl:

Adds population dependent modular map support

---

code/modules/projectiles/gun_attachables.dm

The turn_off var was assuming that the object was already zoomed. And activate is called every time an attachment gets detached. Add both together and you zoom in whenever you detach a scope. 
Closes #9289
No more free zooming without a railscope.
:cl:
fix: Scopes should no longer attempt to zoom you in when being detached. 
/:cl:

Fixes rail scopes zooming in when detached

---

code/modules/clothing/suits/marine_armor.dm

Title. It's a fix. This PR #8723 removed armor from uniforms, but forgot to change combat robot armor to reflect the changes so combat robots have been suffering with inferior armor for (time) now.
Consistency.
:cl:
fix: combat robot armor now has the same armor values as marine armor
/:cl:

Adjust combat robot armor values

---

_maps/map_files/Theseus/TGS_Theseus.dmm

Apparently Theseus lacked a button to disengage the roundstart privacy shutters for the CL office. I've fixed this by adding two CL shutter buttons to CIC and also added a photocopier.
One of our few CL mains has been asking for a fix for a week now, and it's about time it gets done so CL players can do their job.
:cl:
fix: Added two CL shutter override buttons in Theseus CIC.
fix: Added a photocopier to Theseus CL office.
/:cl:

Fixes some small issues with Theseus CL office

---

code/game/objects/items/weapons/blades.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/living_defense.dm

https://www.youtube.com/watch?v=DwhcaMFB-UQ
No more ancient Crushers and Queens dying in 0.5 seconds from funny throwing knifes. "Only a few people use throwing knifes" is not an argument, buff their damage instead if needed.
:cl:
code: thrown items respect mob armor
balance: throwing knifes throwforce changed from 35 to 45
/:cl:

Thrown items respect mob armor

---

_maps/map_files/LV624/LV624.dmm

BEFORE:
AFTER:
you can go through this area of the vents now without being forced out
:cl:
qol: Fixed vent overlap in LV624 Fitness Dome
/:cl:

fixes the dumb overlapping vent on lv fitness dome

---

code/game/objects/items/storage/large_holster.dm

Stops the shotgun holsters and SMG holsters from showing an error sprite or just plain vanishing.
Closes #9096
For that rare specimen of a PO who uses their MR25 holster.
:cl:
fix: The sprites for the MR25 holster should work now. What, you didn't know we still had those?
/:cl:

Attempts to fix the holsters no one uses (again)

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm

If a Defender is fortified and has 100+ bullet armor, bullets will reflect off of it.
This only counts for projectiles that do brute damage.
Defender is still hit by the projectiles so sunder and ap will still be applied.
Sadar shots de-fortify on hit and thus cannot be reflected.
This can only be achieved through ancient defender with very strong warding pheros.
I figure this will be a funny interaction that will not cause too much problems balance wise.
:cl:
add: If a Defender is fortified and has 100+ bullet armor, bullets will reflect off of it.
/:cl:

Defenders that are fortified with 100+ bullet armor will have rounds bounce off of them.

---

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm

Title
All 4 gases are now non-transparent, transvitox and hemodile bonus radius was removed
:cl:
balance: transvitox and hemodile bonus spread radius was removed
/:cl:

Defiler gas now has equal spread radius

---

_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
code/game/objects/machinery/vending/new_marine_vendors.dm

No more free plasma cutter in req. You either get it as a synthetic or as an engineer.
I'm sorry, engineer players. This is to make it easier on you when MJP's engineers rework come in.
Marines can clear resin walls with grenades, plasma cutter, melee weapons, mortar, CAS, and railgun. The last three are null when marines push caves, so this leaves grenades, plasma cutter, and melee weapons as the best option to clear resin walls.
Maybe I can give CSE plasma cutter while we are at it. CSE is practically SL of engineers.
I will make concessions in light of this PR. If maintainers allow, I can make plasma cutters cheap.
:cl:
del: Remove free plasma cutters from req in preparation of MJP's rework; it must be done so that engineer players can adapt NOW than later.
add: Synthetic has plasma …

Plasma Cutter Balance: Synthetic Edition

---

code/game/objects/items/tools/research_tools.dm

Removes hard skill lock from xenomorph analyzer, enabling everyone to use them with a 15 second fumble dependent on your medical skill. No change to excavations.
Hard locks against TGMC ethos, allows a variation of playstyles if nobody's playing researcher. Dying as xenos now has a much higher risk.
:cl:
balance: Xenomorph analyzer is now useable by all, with a delay to reflect lack of skill.
/:cl:

Removes hard skill lock from research xenomorph analyzer

---

code/game/objects/effects/effect_system/smoke.dm

Fixes the sentry sightline issue in new opaque gasses #9394 
Bugfixes are always good, and continuing the trend of making the gasses function similarly (I.E. #9407) is also good
:cl:
fix: Hemodile and Transvitox now block sentry line of sight like other defiler gases
/:cl:

Fixes sentries los not being blocked by now opaque hemodile and transvitox

---

code/game/turfs/walls/resin.dm

Grenades deal 50 less overall damage to walls.
Fire got a 10 point per tick buff. 
Fire probably got massively overnerfed in the Wall rework PR, and grenades and other light explosions deal too much damage to resin walls.
:cl:
balance: Fire deals more damage to walls, light explosions deal a decent bit less now.
/:cl:

Fire deals more damage to walls, light explosions deal less

---

code/modules/projectiles/ammo_datums.dm

Per title.
Stats have been changed as follows;
- Penetration reduced from 45 > 30. Seriously.
- Stagger and knockback removed.
- Shots will now pierce through targets.
TX-8 impact ammo has been really dumb for too long. Stagger, slowdown, and knockback on a gun with 25 damage, 45 penetration, and 5 sunder per bullet.
:cl: Lewdcifer
balance: TX-8 impact ammo; 45 > 30 pen, stagger and knockback removed, shots pierce through targets.
/:cl:

TX-8 Scout Rifle impact ammo rebalance

---

code/datums/status_effects/xeno_buffs.dm

Before, the Gorger's Psychic Link would cancel itself if the target xeno left the link's range.
With these changes, the Psychic Link will only toggle itself off if the target isn't within range, and automatically toggle on if the target reenters range.
Quality of Life changes that should make Psychic Link much more easier to use.
also slotbot told me to say that gorger is a great xeno
gorger is a great xeno
:cl: Lewdcifer
qol: Psychic Link will not cancel itself due to distance, instead toggles on/off
/:cl:

Gorger's Psychic Link QoL change

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm
tgui/packages/tgui/interfaces/BlessingMenu.tsx

You can click on buttons now
There was no way of distinguishing visually disabled button from working one, so this information was useless. Plus, when a button is disabled, clicking on it didn't tell you why. This is now fixed and you have the error message (not enough points for exemple)
:cl:
qol: Buy upgrade button in hive blessing menu no longer disabled
/:cl:

Buy upgrade button in hive blessing menu no longer disabled

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Fixes an exploit that allowed you to stack empower by punching someone's missing limb.
closes #8863
:cl:
qol: Warrior : punching someone missing a limb will default to hitting them in the chest instead of entirely failing.
fix: Warrior : Warrior's primordial can no longer be stacked by repeatedly punching someone's missing limb.
/:cl:

Fixes warrior's primordial

---

code/__DEFINES/dcs/signals.dm
code/datums/keybinding/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm

Forgot to allow players to bind acid dash to a key in prae's primo PR
Can't do cool stuff without that
:cl:
fix: Praetorian's primordial : Acid dash can now be bound to a key.
/:cl:

Fixes missing keybind for Praetorian's primo

---

code/game/objects/machinery/vending/marine_vending.dm

Title.
During #9385, I did not notice that Vahalla's TerraGovTech Requisition Vendor use the same icon_state path as synthetic vendor does.
Consistency and attention to detail be like.
:cl:
fix: Fix Vahalla's TerraGovTech Requisition Vendor sprites
/:cl:

Fix Vahalla's TerraGovTech Requisition Vendor sprites

---

_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm

Mapping QoL. Become better at QoL than CM.
New players doing a new job may not know where their vendors are unless they point and right click on doors to positive identify their location. Also, veteran players may sometime not know where other prep are when going to a new job.
This helps to deal with that. If marines are still lost, skill issue, not map issue.
:cl:
qol: Prep signs for marine role in shipside. Now you can stumble to your leader, smartgunner, corpsman, or engineer job easier; thanks to RipGrayson for making these due to Vahalla!
/:cl:

Prep signs for marine role in shipside

---

_maps/map_files/Sulaco/Sulaco.dmm

Title.
When #5809 was made, they added free additional tricord pill bottles. They didn't know that tricord pill bottles will get added in MarineMed, so Sulaco had it.
Either all ships get it, or no ships get it.
:cl:
del: No more free additional tricord pill bottles in Sulaco
/:cl:

No free additional tricord pill bottles in Sulaco

---

code/modules/projectiles/guns/rifles.dm

Title
It's a gun that has a quick burst that essentially devolves into spamclicking compared to guns like T12 or T18 with a lengthier burst that still have BA. Turns into arthritis simulator quickly enough. Gun can't attach a bfa anyway so it shouldn't be an issue compared to the aforementioned ones. Also """standardizes""" burst performance for everyone by just having everyone able to hold click rather than whoever clicks faster being stronger.
:cl:
qol: Tx11 now has burst auto, less spamclicking needed for the same thing burst offers
/:cl:

Gives Tx11 autoburst mode

---

code/modules/surgery/necrosis.dm

Surgery to remove necrosis will sterilize the limb it's performed on.
If you're in surgery you can do this anyway by opening and closing an incision, this just skips the knowledge check to have to do so first.
:cl:
add: Necrosis removal surgery clears germs on its own
/:cl:

Necrosis removal surgery clears germs

---

code/modules/projectiles/guns/energy.dm

Cleaned up duplicate lines of code for energy weapons
Some duplicate lines of code snuck into marine energy guns for unwielded scatter.
Edit: energy pistol now correctly has 4 scatter. Previously it was using 0 so was more accurate in one hand than wielded.
Extra code is bad.
:cl:
code: removed unneeded code
fix: Energy pistol is no longer more accurate one handed than wielded
/:cl:

Removed duplicate code from energy weapons

---

code/modules/projectiles/guns/specialist.dm

Allows the T-26 to load flak and incend ammo when badmins spawn it for you
For some reason the T-26 cannot actually load its own flak and incend mags.
Fixes this, although I don't think they're normally available in game.
Gun not load intended ammo bad.
:cl:
fix: T-26 can actually use all 3 ammo types now
/:cl:

T-26 can actually use its alt ammo types

---

code/game/objects/structures/xeno.dm

Xeno doors are no longer opaque when opened
You can now click a door as a xeno to open it (it was opening then immediatly closing)
:cl:
fix: Xeno doors are no longer opaque when opened
fix: You can now click a door as a xeno to open it (it was opening then immediatly closing)
/:cl:

Xeno resin door fixes

---

code/game/data_huds.dm

When ungas go DNR, they currently still show as defibbable on the minimap until their defib timer runs out.
I am a brainlet coder, but this seems to work and it's been an annoying bug forever.
Marines seethe when they risk their lives to try save a dead guy, only to find out when they reach them that they're actually DNR.
:cl:
fix: DNR's no longer show as revivable on the minimap
/:cl:

DNRs no longer show up as defibbable on the minimap

---

code/game/objects/items/storage/belt.dm

Title. tgmc.dme screwed up #9517, so #9519 is the result.
Fix bug. Also, not going to do /obj/item/reagent_containers/hypospray/autoinjector in can_hold in case if people REALLY want to put other things beside the 5 specific autoinjector. Maintainers will correct me or not.
:cl:
fix: Fix hypospray belt not accepting specific autoinjectors
/:cl:

Fix hypospray belt not accepting five specific autoinjectors

---

code/game/objects/machinery/vending/marine_vending.dm
code/game/objects/machinery/vending/vending_types.dm

Title.
Also move /obj/machinery/vending/cigarette/nopower and /obj/machinery/vending/engivend/nopower to their respective location just to make it easier to see child.
Have you ever wonder why when you want to save a crowbar in your loadout (except in engineering belt and tool pouch), crowbar doesn't appear in loadout?
Just me? Okay.
I give you a reason why. Loadout checks marine_vending.dm but not vending_type.dm. I don't know the magic behind this, but it works. It's why MarineMed slowly loses pill bottles over the round.
Yes, I really want to keep a crowbar on person at all time, and I'm too lazy to go to vendor to get one myself. It's why I have loadout. Also, I find this a weird oversight of not being able to save tools beside in engineering belt and tool pouch. We have infinite …

Moving YouTool code to marine_vending.dm

---

code/game/objects/items/reagent_containers/hypospray.dm

Title.
It's kinda wack that hypospray, for all its advancement, doesn't have a 30u option. Also, adjust the set transfer menu on hypospray to make it a LOT easier to choose 30u.
:cl:
add: Hypospray has 30u and 20u for set transfer reagent
qol: amount per transfer in hypospray menu
/:cl:

Hypospray has 30u & 20u mode and QoL with amount per transfer menu

---

code/game/objects/machinery/mortar.dm

Makes flare shells decent again, and more in-line with their clone, the CAS illumination flares.
-Adds a light_power of 8 (same as CAS flares) to flare shells. This does **NOT** change their actual light range of 9, but it does provide the actual light. Basically, fixes flares so they actually produce light.
-Gives flare shells the same light as CAS flares. They work similarly, last for the same amount of time, and have near the same range. They are literally clones of each other.
-Removes the 'flicker' effect from flare shells. CAS flares don't have it, it looks very jumpy with a larger light radius, and it limits light range. It just doesn't fit as it is now.
Before:
After:
Makes mortar flare actually useful. Judging by the light_range of 9, but the lack of actual light produced, this …

Fixes mortar flares

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm

Adds heat absorbent coif crates to each LZ on ice colony.
This has not been tested on a local build but given that it builds without error and that it's a really simple map edit i feel it should cause no major issue.
As i said in my icy caves PR (#9484)
> Heat absorbent coif crates on both landing pads!
> You didn't forget your heat absorbent coif, did you?
> (i'll add these to ice colony once this PR is merged, gotta atomize y'know? Though if it doesn't get merged i'll just make it a separate thing for both maps.)
So now i'm doing that
Eitherway this is just good for any marine that either hasn't realized it's ice colony or forgot to put one on before launching groundside.
:cl: Vondiech
add: added heat absorbent coif crates to each LZ of ice colony.
/:cl:

Adds the heat absorbent coifs crates to ice colony.

---

code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/rifles.dm
code/modules/projectiles/guns/specialist.dm

Recent scatter changes made some guns unviable or even unusable. This PR attempts to make those guns usable again.
balance is good
:cl:
balance: T-60, T-18, TX-11, Minigun, Laser Machinegun recieved new scatter values
/:cl:

Scatter balance pass

---

code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/species.dm

They were not metabolising it, yet it was on accumulating there.
The main advantage is that spitter or defiler will no longer have the toxin indicator on robots, which was confusing
:cl:
qol: Robots no longer have chem in their bodies
/:cl:

Robots no longer have chem in their body

---

code/modules/mob/living/living.dm

You could shuffle someone when moving diagonnaly, even when that mob was not on your destination tile. This is fixed, but you can of course still shuffle diagonnaly 
:cl:
fix: No more weird shuffle when moving diagonaly
/:cl:

No more weird shuffle when moving diagonaly

---

code/__DEFINES/is_helpers.dm
code/game/objects/structures/cas_plane_parts.dm
code/game/turfs/closed.dm
code/game/turfs/walls/wall_types.dm
code/game/turfs/walls/walls.dm

Refactors plasmacutter behavior when used on walls, fixing a number of bugs (see changelog for details) and making the code more concise. Also addresses and fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/9468.
Bugs are bad, fixes good.
:cl:
balance: Plasmacutters will now cut down walls without leaving a girder
fix: Plasmacutters now respect resistance flags and cannot destroy turfs that have RESIST_ALL or PLASMACUTTER_IMMUNE. 
fix: Plasmacutters no longer spam "can't cut through this" messages when destroying some closed turfs.
fix: Fixes a rare situation where plasmacutters would take multiple charges to cut down some ship walls.
refactor: Refactored plasmacutter behavior for closed turfs.
/:cl:

Refactors some plasmacutter behavior, squashes a number of plasmacutter bugs

---

code/modules/projectiles/guns/rifles.dm
code/modules/projectiles/guns/shotguns.dm

Title
The recent change to the bipod a 50% aim mode delay removal makes the attachment a good complement to these long-range sniper guns. Now you can truly feel like a sniper.
:cl:
balance: you can attach bipod to tl127 and mosin
/:cl:

Allow TL127 and Mosin to take bipod attachment

---

code/modules/mob/dead/observer/observer.dm

Title
It is always ready, it's not an information 
:cl:
del: Remove useless xeno respawn timer stat information
/:cl:

Remove useless xeno respawn timer stat information

---

code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
code/modules/xenomorph/xeno_structures.dm

Buffs primordial drone.
Cooldown 60 seconds -> 45 seconds
Plasma cost 500 -> 200
Night shade 
Passive cloaking range 5 tiles -> 7 tiles
Maturation time 5 minutes -> 4 minutes
The plasma price was way too high and forced drones to choose between planting or building.
Night Shade took way too long to grow for what it offered 
:cl:
balance: Primordial drone : Reduced plasma cost and cooldown, night shade takes less time to grow and has greater range.
/:cl:

Primordial drone buff

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/projectiles/magazines/energy.dm
code/modules/reqs/supplypacks.dm

Fixes #9575 by doing the exact opposite of what the author wants, removing any mention of /obj/item/cell/lasgun/tesla .
When I made the tesla gun free, I was told to make it take in the same mag as the energy weapons, the Terra Experimental standard battery. Due to that, the /obj/item/cell/lasgun/tesla kinda existed in supply pack and in code without any use whatsoever. It even showed in Vahalla!
:cl:
del: Remove any mention of /obj/item/cell/lasgun/tesla
/:cl:

Remove any mention of /obj/item/cell/lasgun/tesla

---

code/modules/projectiles/gun_system.dm
code/modules/projectiles/guns/rifles.dm
code/modules/projectiles/guns/smgs.dm

When firing guns akimbo, there is an extra fire delay associated with it that means you shoot a bit slower. Currently this only applies to semi auto firing, not to full auto.
Makes autofire actually respect the akimbo_additional_delay var.
Also reduced the extra delay value for all SMGs to 0.2 from 0.5. This means guns that fire at 0.15 will fire at 0.2 akimbo.
Rifles reduced to 0 as they're terrible at akimbo, and don't need to be even worse.
Akimbo additional delay now actually works with autofiring. This has balance implications for guns that are used akimbo with autofire :^)
:cl:
fix: Autofiring while akimbo now actually shoots slower like semi auto
balance: Reduced akimbo additional delay for SMG's and rifles to compensate
/:cl:

Akimbo delay applies to autofire

---

code/modules/projectiles/sentries.dm

Sentries currently runtime when losing their target due to LOS aswell as hav weird firing behavior at the edge of their range. This fixes both of these issues.
Atomized out of another PR at bravemole's request.
Fix man good.
:cl:
fix: Sentries should no longer runtime when losing their target nor show weird behavior at the edge of their range.
/:cl:

Fixes some incorrect sentry behavior

---

code/modules/factory/outputter.dm
code/modules/reqs/supplypacks.dm

Reqtorio was too unbalanced in profit per different refills, this PR makes them more in line with each other. Also removed some duplicate code.
Before:
After:
Reqtorio is good again.
:cl:
balance: Reqtorio cost balance. Grenades and smart ammo are now more profitable.
/:cl:

Reqtorio cost balance (again)

---

code/game/objects/structures/razorwire.dm

Prevents razor wires from slowing you down twice when you managed to get on top of them and attempted to resist out.
Crushers no longer turn into snails the moment they touch the apex predator.
closes #9418
:cl:
fix: Razorwires no longer apply their slowdown twice when resisted out of (notabily by Crushers).
/:cl:

Razorwire fix

---

code/datums/elements/deployable_item.dm

Fixes #9612
Stops the marine from deleting the deployable
:cl:
fix: You can no longer send deployables into nullspace by deploying it to your hand.
/:cl:

Deployables can no longer be deployed into nullspace

---

code/modules/shuttle/escape_pod.dm

Removes max capacity requirement. Any number of marines can now evac.
@Walarks 
With #9227 Marines can now evac after 10 minutes to try and prevent a Xeno major. More than 50% of marines
alive have to evac to attain this round end conclusion but it's harder to do so on some shipmaps like Minerva or on higher pops. This removes the evac capacity limit and fixes a few checks (Tested and seems to work so far).
:cl:
del: Removes evac max capacity.
fix: Fixed an apparent infinite loop check.
/:cl:

Fixes Evac

---

code/modules/atmospherics/machinery/components/components_base.dm
code/modules/atmospherics/machinery/components/unary_devices/cryo.dm

Fixes #9597
tbh I'm not sure whether I should be changing the call in /obj/machinery/atmospherics/components/update_icon() instead, in the off chance that I break something, or if I should be using the same signal code present in atom/proc/update_icon() to check for updates instead, but hey bandaid fix, maintainers asleep, wooooo
Fixes buggy sprite
:cl:
fix: Cryotube should now update it's icon properly
/:cl:

Fixes cryo icon not updating

---

code/game/objects/structures/teleporter.dm

teleporter is no longer immune to beno.
Zack cannot into git. I assume he tested this though.
Allows xenos to damage teleporters
Invulnerable shit is bad.
:cl:
balance: teleporters are no longer invulnerable to xenos
/:cl:

Bluespace teleporters can be damaged by xenos

---

code/modules/projectiles/ammo_datums.dm
code/modules/reqs/supplypacks.dm

Makes the incendiary and flak ammo for the AMR actually available in game, and tweaked the prices of all three ammo types to be more in line with the superior T-81.
Standard   3 points from 5 (same as T-81)
Flak           4 points
Incendiary 5 points
Also increases flak's airburst multiplier to 0.2, as currently it does nothing of value.
I would drop the AMR cost itself, but there's already a PR for that.
Gives the AMR something to distinguish it from the cheaper, more powerful NV T-81.
:cl:
add: Add T-26 incendiary and flak ammo to req
balance: Decreased the cost of basic T-26 ammo to be in line with T-81 ammo
balance: Increased the AOE damage of flak ammo slightly
/:cl:

T-26 Alt ammo buff and available from req

---

code/__DEFINES/loadout.dm

Title. For 4 points since that's the same points you would spend if you were to convert bought metal into miner modules back when they were in the autolathe. 
Removing them from the autolathe is good since it prevents printing infinite miner modules with enough patience, but removing an engineer's ability to acquire them outside of req stomps on any mining plans an engineer might have for the round. This returns miner control to the role that is responsible for repairing them.
:cl:
balance: miner upgrades in engineer point vendor for 4 points (does not include autominer)
/:cl:

Miner upgrades in engineer point vendor

---

code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm

Halves the build time for xeno turrets. If its balance or QoL I dont mind either. 15s to build something is too much.
When prepping as a hive leader be either low pop or normal pop the 15s timer for a turret that will start with 300 hp feels like a punishment. Even if your being pushed hard by marines, 15s to make a defense structure is too much when you will be mostly needed at the front.
:cl:
balance: Build time from 15s to 10s.
/:cl:

Xeno's turret deploy time reduced to 10s.

---

code/modules/projectiles/ammunition.dm

Fixes #9651. I'm not sure this is the best way to go around this, but I can't think of another way.
Stops marines from making infinite ammo.
:cl:
fix: Marines can no longer create 0 handfuls and shoot phantom ammo.
/:cl:

Fixes zero stacks of handfuls

---

code/__HELPERS/announce.dm

Lets deaf, crit, or dead humans hear all announcements, like in CM.
Currently, TGMC is extremely momentum based. If you start losing, it can be hard to stop it. Part of this problem is how common deafness is. 
When someone is deaf, they cannot hear anything, sometimes for an extended period of time. You get absolutely NO information, except what is _visible_ on your screen, and that's absolutely crushing. ESPECIALLY when some things deafen you for _half a fucking hour at times_. Deafness is an **incredibly** strong debuff.
But this PR doesn't change that, and that's why I think it's balanced. The only thing this allows command to do, is _ensure_ that everybody heard something. Nothing else really fills that role currently, and from how organised CM is at times, I think it's something …

Makes announcement hearable even if deaf

---

code/modules/clothing/head/head.dm

title says it all
Adds 2 lines just to give headbands armor and make them not able to be decapped
Berets have decapitation protection. I think headbands should be the same.
:cl:
balance: Headbands are no longer able to be decapitated
/:cl:

No decap on headbands; Same Armor as berets

---

code/modules/projectiles/guns/pistols.dm

This doesn't stop the plasma pistol from normally shooting in it's unattached version. I also stole this code from #9316 thanks to Notamaniac for making this.
https://user-images.githubusercontent.com/24631139/154784939-9b6d6ea2-b345-4728-a9c4-67ff3579ef27.mp4
(tested the code anyway so I don't perish)
A less nuclear option than #9664 as shotguns aren't really the main problem here, it's mostly underattachments as a whole not having a clear indication that the gun possesses them, blindsiding xenos with surprise ugl impacts or ubf/masterkey, but the big difference between these under attachments and plasmapistol is that they need to be fully wielded to actually start shooting, giving xenos that are more hit and run a moment to leave. (runners, hunters etc.) Most stuns are only for 2 …

Makes plasma pistol attachment shoot only while wielded

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm

Attempts to find a good price for Acid well so it doesn't cost an arm and a leg to make or fill up whilst also making sure its not super spammed
Acid well's are a defensive & utility structurefor xenomorphs, but they use up a LOT of plasma 500 to make and 200 to build, when creating a maze or base xenos wont be able to spare the plasma, Lowered Acid Well cost will allow xenos to better hold defensive lines rather then falling victim to marine pushes hat cant be stopped.
When retreating Marines will often follow xenos into weeded areas, but I believe with the reduced cost for acid wells they will think twice.
:cl:
balance: Acidwell now 400 down from 500
balance: Filling an acidwell is now 150 down from 200
/:cl:

Reduces Acid well Cost.

---

code/game/objects/items/tools/maintenance_tools.dm

Fixes #9643
Re adds the left click code again. I dunno if I should go and move the code into a proc or not so yeah.
Apparently this was messing with people's muscle memory. Also those who have not embraced the light of right click should not be discriminated against.
:cl:
qol: Left click takes cells out of handheld chargers again
/:cl:

Left click takes cells out of handheld chargers again

---

code/game/objects/items/radio/detpack.dm

Fixes a couple of detpack bugs:
- Fixes detpacks breaking when taken off a surface, and put on another
^ This might also have happened when 'Send signal' was spammed, and if it did, that's fixed too
- Detpacks are now immune to explosions, including explosions from _other detpacks too close_ and friendly grenades/OBs
- Detpacks now delete properly when destroyed
This should fix #9544  and might fix #9543 (I'm pretty sure 9543 was caused by explosions (like from an OB or other detpacks) fucking things up, not walls being deleted under the detpacks)
Detpack is regarded as one of the worst ways to take down a wall at the minute, and the thing itself, from whenever I've used it, isn't so bad. What IS bad, however, is the fact that half the time it doesn't bloody work. Hopefully by making it …

Detpack fixes

---

code/modules/projectiles/guns/pistols.dm

Apparently the flag for firing a gun while wielded only cares if it's in a wielded state, not if you're currently wielded or not. There's a specific flag for stable wielded firing which only allows shooting once you're finished wielding. This fixes my pr which used the wrong flag.
https://user-images.githubusercontent.com/24631139/155063629-fd5dc38a-e190-4885-8c1f-5b9b3d21669f.mp4
bugfix
https://user-images.githubusercontent.com/24631139/155063653-aa160a4c-c9be-4fe6-9835-4cd97527506f.mp4
:cl:
fix: Plasma pistol actually only works when fully wielded while attached to a gun.
/:cl:

Fixing my own pr (Plasma pistol can only fire while wielded)

---

code/controllers/subsystem/persistence.dm

The 3rd rifle seasonal set (ALF machine carbine and Type 71 rifle) was missing from rotation. Not sure if this was intentional or it just got left out by accident. So let me know if that's the case.
ALF game stronk.
:cl:
config: Made the ALF and type 71 seasonal actually be in rotation
/:cl:

Add missing rifle seasonal to rotation

---

code/modules/projectiles/ammo_datums.dm

Currently the bouncy revolver 'bounce' shots don't come from the turf they hit, they come from the firer themselves. I'm not entirely sure how long this has been the case...
Fixes this so that bonus projectiles are fired from the location of the original projectile when the proc is called.
This also makes the proc more flexible for other uses, without breaking buckshot and the like. Not sure if I should make the origin point an arg instead, to allow for even more options. Maintainers let me know what you think.
Also if anyone can explain how pixel location magic works, it would be great to use the exact pixel location of the origin projectile instead of just the turf location.
Bouncing bullets now actually work.
:cl:
fix: Bouncy revolver bullets now actually bounce from what they hit …

Fixes the bouncy revolver

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Warrior punch no longer knocks down sentries, instead doing X4 its damage like it does on regular machinery.
Defender charge no longer knocks down sentries either.
Sentries have it a bit hard and warriors aren't supposed to shine during sieges but in 1 on 1 combat.
Defender is a T1 and already very good at crowd control, that's too much utility.
:cl:
balance: Warrior : punch no longer knocks down sentries
balance: Defender : forward charge no longer knocks down sentries
/:cl:

Punch and Forward charge no longer knock down sentries

---

code/__DEFINES/conflict.dm
code/modules/projectiles/ammo_datums.dm

Gives an overall buff to the underused, Anti-mat T-26 sniper rifle.
From 80 damage to 90, 60 to 80 pen, and removed all sundering.
Additionally, the Laser was made to have a 1.7 across the board buff from a 1.5 in damage and pen.
An underused sniper rifle, overshadowed by the new "Auto-Sniper", and considered a waste of points by some, gives it an edge over the weapons, making people consider using it more. And as a general note, I make it embrace its AP heritage, removing the Sunder from it, making it pure damage inflicting weapon for late-game Ancient/Primordial xenos, and setting the stage for Marines to chase the said Xeno down.
:cl:
balance: rebalanced the T-26 sniper rifle to have an additional 10 damage per bullet, with the addition of the lase now being 1.7 instead of a 1.5 damage …

Anti-Mat sniper buff.

---

code/modules/projectiles/guns/pistols.dm

How am I supposed to know wielded_fire flag doesn't care about guns that are mid-wielding, and how am I supposed to know stable_wielded_fire flag doesn't care if a gun is onehanded and lets it shoot anyway. I am literally at my limit and about to cry, I've added BOTH flags into the plasma pistol while attached now. 
https://user-images.githubusercontent.com/24631139/156093114-ec151343-6ec6-40ec-9f20-d2220ecdd232.mp4
Fixes my broken pr twice
:cl:
fix: Plasma pistol actually doesn't shoot onehanded or while wielding while attached to a gun
/:cl:

Actually fixes my pr that's only a one line change for the 2nd time (Plasma pistol only shoots while fully wielded bugfix)

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm

Apparently command can look through cameras located in the underground complex and see what the xenos are up to. 
Since the xenos never base anywhere but SE complex, command can essentially tell hive composition, resin silo location etc from the safety of their ship without even dropping shutters.
This isn't intended behavior, marines shouldn't be able to peep on xenos half a map away in an underground silo within 30 seconds of mission start.
:cl:
balance: Marines can no longer spy on xenomorph activity in Big Red's underground complex.
/:cl:

Removes ship cameras from Big Red underground complex

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Turns out the turf one gets sent to if banished is turf/closed/whatever, which means that it is in fact neccessary for recall to be usable on closed turfs. I do not see anything bad able to happen from that either, so this should be fine.
Fix man good.
:cl:
fix: Wraiths are once again able to recall themselves due to brazil-space being a closed turf.
/:cl:

Fixes recall not working if banishing oneself

---

code/datums/components/footstep.dm

When you walk you're supposed to hear footsteps as a marine (or monkey) but it's currently broken so you don't hear anything. This PR corrects the error so you can hear footsteps like you're supposed to.
Fixes good, also I was asked to fix this error so there's *somebody* out there who wants to hear the sounds of feet slapping the ground.
:cl:
fix: You can now make footsteps again as a marine.
/:cl:

Fixes footsteps

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/sentries.dm
code/modules/projectiles/magazines/sentries.dm

571
Damage 50-> 25
pen 5->20
Halved falloff (0.25)
Ammo Capacity 50->500 (300 might be better, will talk about)
Fire delay 0.6->0.25
Deploy shortened.
580
Damage 25 -> 20
Pen 5->20
FD 0.3 -> 0.2
Ammo Cap 100->300
Makes sentries good at point defense rather than being this weird thing that is a sniper more than a point defense. I can readd the sniper turret gimmick in another PR, probably.
:cl:
balance: Sentry rebalance, 571s have much higher capacity and fire much faster, aswell as deploy faster. 580s have a bit less damage, higher pen and higher fire delay, and more capacity.
/:cl:

sentry rework

---

code/game/objects/items/stacks/snow.dm
code/game/objects/items/tools/shovel_tools.dm
code/game/objects/structures/barricade.dm

Right now every other diggable tile in game can give you an infinite amount of dirt to fill your sandbags with. However on the ice planets you have to dig 5 snow layers to make one sandbag cade (and often times most snow is shallow). This makes it easier and less annoying to fill sandbags on ice planets while making sure there aren't any snow duplication silliness. Snow cades now also require 5 snow as part of this.
Right now every other diggable tile in game can give you an infinite amount of dirt to fill your sandbags with. However on the ice planets you have to dig 5 snow layers to make one sandbag cade (and often times most snow is shallow). This makes it easier and less annoying to fill sandbags on ice planets while making sure there aren't any snow duplication silliness. Snow cades …

Better snow digging

---

code/modules/clothing/modular_armor/attachments/modules.dm

Right now the SL helmet uses the Jaeger sprite for helmet modules. This PR fixes that, using Xenonauten sprites.
Current(Left) Fixed(Right)
Bug fixes good.
:cl:
fix: Squad Leader helmets now use the proper Xenonauten sprites.
/:cl:
**Pro tip: don't forget to atomize**

Fixes the SL Xenonauten helmet using the Jaeger sprite

---

code/__DEFINES/loadout.dm

https://github.com/tgstation/TerraGov-Marine-Corps/pull/9684 removes squad leader radio from vendor but not essentials. Elsa's reasoning is that no one uses it, therefore I trust that removing it from the essential is also wise (I have also not seen anyone use it, if you have please tell me). However the main point of this PR is giving the SL a compass as part of their essentials. Yes compasses are free but by making it part of the essentials it will be brought more to their attention.
The compass gives coordinates (the type you use for a drop pod) and is a mostly unused item. Putting it directly in the hands of  SLs makes it a more known tool and allows SLs to easily give coordinates to those wishing to drop pod right into combat.
:cl:
balance: replaces SL essentials kit radio with a …

Gives the SL the compass

---

_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm

All shipside maps have three bluespace beakers.
Move bluespace beaker to spawn on top of chem master.
All shipside maps have two chem dispensers and chem masters next to each other for marines to use and a dedicated chem lab for researcher.
Some maps, like Sulaco and PoS, did not have all the standardization of chem labs that are across other shipside maps. It's time to fix that.
:cl:
qol: All shipside maps have two chem dispensers and chem masters next to each other for marines to use and a dedicated chem lab for researcher.
qol: Move bluespace beaker to spawn on top of chem master.
balance: All shipside maps have three bluespace beakers.
/:cl:

Chem Lab QoL and Standardization

---

_maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm

Title.
Tivi orders Shiryu to do this else map gets remove from rotation, and Shiryu hasn't respond yet, so I'm doing the initative to do this ahead of him.
While I'm on it, no free plasma cutters. That's all.
:cl:
del: acid gas landmark in Barrenquilla
del: free plasma cutters in Barrenquilla
/:cl:

Remove acid gas and plasma cutters in Barrenquilla

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/rifles.dm

Made it a uniquely good weapon at medium to long range since autoburst delay and extra delay are shorter.
Autoburst gets to be equal to burst, you shouldn't need to be a good CS:GO player to use the Battle Rifle.
~~Scatter forces you to use a recoil compensator or a vertical grip while making long range shots more difficult, therefore you are more likely to miss, but you have better punch ESPECIALLY AT CLOSE RANGE.~~ Only low scatter (from burst multiplier) makes it a weapon of choice for ranged, ~~plus the accuracy multiplier of 1.25,~~  this is magnified by the bullet changes, but then we remove plasma pistol, UBF and masterkey. 
Last change I made was the accuracy and fine tune balance change.
:cl:
balance: Light marksman bullet gets 5 AP, 2.5 damage and 0.25 sunder.
balance: The T-64 …

Make the T-64 Great Again

---

code/modules/projectiles/ammo_datums.dm

The change to the base sniper bullet used by the anti-mat rifle inadvertently effected some other sniper bullets that used the old inherited values.
Adds those old values to the child bullets where they were missing.
Fix accidental changes.
David pls.
:cl:
fix: M42C and SVD have their correct pen and sunder values again
/:cl:

Fix sniper ammo with inherited pen/sunder

---

code/modules/projectiles/guns/rifles.dm

The ALF is currently firing faster on autoburst compared to normal burst fire (0.4 instead of 0.7), due to it's unusually high extra delay and how autoburst delay is calculated.
Sets autoburst delay to 0.7 so it's the same as normal burst fire. Dunno if that makes it terrible but this is a bug fix not a balance change so eh.
Gun shooting considerably faster than it should do is not fun for beno.
:cl:
fix: The ALF machinecarbine no longer shoots abnormally fast on autoburst.
/:cl:

Fixed ALF autoburst delay

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm

Changes the progress icon for forward charge to danger.
Changes the progress icon for forward charge to danger.
Consistency. Acid spray, scatter spit, rocket launchers, and minigun use BUSY_ICON_DANGER. You should be given a proper alert that a defender is about to use their 4 second charge stun, especially when much of the aforementioned abilities have a similar windup time. 
:cl:
balance: Forward charge now uses BUSY_ICON_DANGER instead of BUSY_ICON_GENERIC.
/:cl:

Forward Charge Now Uses A Danger Icon

---

code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/guns/mounted.dm

Reduce max_integrity from 800 to 500.
Aim mode takes 6 seconds to do. 
Scope now takes 2 seconds to use.
Scope now 7 tiles instead of 11 tiles that it inherits.
Remove AT gun having IFF. Sleep deprivation is dangerous. Don't do it. Have 7+ hours.
The nerfs that xenomorph players have been waiting for.
It was either this PR or removing it from armament vendor since David asked me to remove it, but MJP and I got a plan.
Decrease range so that boiler can shoot it with ease, making AT gun less of SADAR lite with sniper scope. MJP agrees to reduce range since it has a sniper scope on it; 11 tiles, holy smokes. Due to a decreased timer on activating AT gun scope, it makes sense to decrease it range.
Now AT gun is weaker and susceptible to CQC. Slash it enough, and MAYBE you can break it!
I …

AT gun nerf and removes IFF on it

---

code/__DEFINES/loadout.dm
code/game/objects/machinery/vending/new_marine_vendors.dm

Allows SLs to save and get the leader class helmet from the loadout vendor.
Also removing the enclosed Xenonauten helmet from essentials kits and giving the leader armor essentials kit a description.
When you try to save a loadout with a leader helmet it will not give you the helmet, this fixes that.
The "Heavy" helmet is just a different sprite and just serves as clutter in the essentials kit (Don't worry you can still get it from surplus)
The description for leader armor sets just keeps it up to par with other armor essential sets.
:cl:
qol: Leader armor essential sets have have their own description now.
del: The enclosed helmet no longer comes with the Xenonauten essentials kit (check your surplus vendor to find it)
fix: SLs can now save their leader helmets in their loadouts
/:cl:

Helmet QOL, specifically leader helmets.

---

code/__DEFINES/loadout.dm
code/game/objects/machinery/vending/new_marine_vendors.dm

Gives the FC an essentials kit specifically for jaeger and removes the useless motion detector from FC and SL essentials kits.
Also renamed the jaeger essentials paths since jaeger is no longer the only modular suit.
Less clutter in the FC's office if they don't want to use Jaeger, and considering that motion detectors are a free and infinite gun attachment that people barely ever use in hand anymore (let alone actually call out the xeno about to ambush everyone) so having it in an essentials kit is somewhat silly.
And having the typepath be named basicmodular is an outdated way since the majority of marine armor is modular these days (also smushing words together makes me sad).
:cl:
add: FC now has a specific essentials kit for jaeger
del: SL and FC no longer start with an extra motion …

Updates leader essentials kits, FC has specific Jaeger kit.

---

_maps/shuttles/minidropship.dmm

There is a way to lockdown tadpole and NOT let anyone bring up the shutters again unless you shoot your way through.
Seen it happen, and it's weird that marines have to shoot it down. Also, prevent griefing the tadpole.
:cl:
add: Give a button outside of Tadpole when someone lockdowns tadpole from inside so that you can open tadpole's shutters from the outside.
/:cl:

Give a button outside of Tadpole when someone lockdowns tadpole from inside

---

code/game/objects/machinery/vending/vending_types.dm

The Flight surgeron medical equipment dispenser is stock of reagent bottles and autoinjectors like its previous dispenser, the NanotrasenMed Plus.
Also, you can refill autoinjectors and reagent bottles. It does not need to be 0 to refill as my video demostrates.
This brings back the medbus to fully operational again. Good players that use medbus should not be punish for the sharable NanotrasenMed Plus that hinder the glory that is the medbus.
Previously, medbus players bring the NanotrasenMed Plus for surgery and healing. Many, if not all, the chems are used to help wounded marines. Since #9533, they can no longer do that. #9561 attempts to fix that, but it is not enough.
This is not going to buff marines any way, it is just bringing back to a tadpole's state for the better.
:cl:
add: …

Tadpole Part 2: Bring Back Medbus

---

code/game/objects/structures/teleporter.dm

Title.
Teleporter inherits max_integrity from objs.dm for a max_integrity of 500 (thank you, @Lumipharon). This is okay if it is in limited supply, but engineers can grab this for free in their engineer vendor AND get a plasma cutter. The current backpack selections that engineers can choose are a radiopack, a welderpack, and pair of teleporters.
Teleporter is reshaping TGMC's meta really fast, and letting teleporter have 500 max_integrity is too much for xenomorphs to deal with if their mission is to destroy the teleporter.
:cl: novaepee and Lumipharon
balance: Engineer's teleporter has health of 250, half of what it used to have
/:cl:

Teleporter has max_integrity of 250, half of its health

---

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm

Savage gets a quarter shaved off its max damage multiplier. It will, however use less plasma because of this.
Runner has absurd damage for a fast caste, and savage is fine. Evasions longterm effects have shown the caste is tanky in direct combat now. So it doesn't deserve absurdly high damage.
:cl:
balance: Savage mulitpliters 1/4th'ed, less max damage. But it will use less plasma because of this.
/:cl:

Runner savage damage bonus max, 1/4th

---

code/modules/clothing/modular_armor/attachments/storage.dm

Jaeger storage modules are normal sized items. General storage modules can carry 2 normal sized items. This creates PROBLEMS.
Also having like 7 modules in a bag is pretty meme as well.
So increases the size of storage modules to bulky, so no more storing them in other things.
Recursive storage is bad.
:cl:
fix: Jaeger storage modules are bulky, and no longer fit in other jaeger storage modules.
/:cl:

Fix recursive storage exploit

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/modularmaps/big_red/bigredatmosvar3.dmm
_maps/modularmaps/big_red/bigredcheckpointsouthvar1.dmm
_maps/modularmaps/big_red/bigredcheckpointsouthvar3.dmm
_maps/modularmaps/big_red/bigredofficevar2.dmm
code/game/objects/effects/landmarks/corpsespawner.dm

Apparently an area on Big Red has an incorrect area assignment causing wonky visual effects when it comes to weather.
This PR removes that and makes yet more changes to the Crashedbury variation of offices, namely making it so the walls aren't indestructible and adding marine corpses inside instead of security.
Just some more minor tweaks requested on Discord, I live to make tiny changes.
:cl:
add: New marine corpse spawners for use by mappers.
balance: The crashed Canterbury variation in Big Red no longer has indestructible walls.
fix: Fixed an incorrect area in Big Red causing weather to look weird.
/:cl:

Patches an area of incorrect weather on Big Red, plus minor tweaks

---

_maps/shuttles/alamo.dmm

Alamo has four fire-safety lockers, or essentially fire extinguishers, so that marines are safe and secured knowing that hopefully someone will extinguish fire really fast.
Fire bad, Alamo safe, Alamo good. I'm surprised that the fire-safety lockers don't get used as much despite being super useful. It's neat have around and shouldn't be limited to Magmoor.
:cl:
add: Add fire extinguishers in Alamo
/:cl:

Add fire extinguishers in Alamo

---

code/modules/projectiles/guns/rifles.dm

Do what #9699 couldn't.
Make burst fire tuned.
:cl: 
balance: T18, T12, and Tx11 burst firerates have all been nerfed with burst fire delay of 0.05 seconds. Don't worry, slap on BFA, and you're good. MJP will balance BFA to make sure you have your funny brr
/:cl:

Burst fire balance 2.0

---

code/modules/projectiles/ammo_datums.dm

Primo isn't supposed to scale stats, however boiler gas clouds scale with maturity, leading to monstrously huge clouds when Primo. Fixes this, seriously, ancient clouds are already massive.
Big stinky cloud go home.
:cl:
fix: Boiler gas cloud no longer scales in size past Ancient
/:cl:

Boiler cloud radius no longer scales past Ancient

---

code/controllers/subsystem/monitor.dm
code/datums/gamemodes/nuclear_war.dm

Small nerf (from 3x to 2.5) for silos.
And set spawner output to be the same as in distress
3 times is a bit too strong, 2.5 should be more balanced while still being a challenge for marines. Minions spam is boring to play, and far too strong
:cl:
balance; Silos in nuclear war only have a 2.5 spawn multiplicator, rather than 3
balance; Minions output in Nuclear War is now the same thing as in Distress

Nerf silos in nuclear war 

---

code/modules/mob/living/carbon/xenomorph/embryo.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Larval huggers where having a hard time being a half combat hugger, as they had quite big leap cooldown bt also overwhelming stam damage but for last and not less important a unholy burst time.
Larval huggers are more of a niche thing now, used less in combat with its stam damage being halved now they will give marines long term problems with the burst time being reduced to 7 or 8 minutes.
:cl:
balance: Larval Hugger burst time from 13 minutes to 7/8
balance: Larval hugger stam damage from 100% marine stam to 50%
/:cl:

Larval hugger rebalance

---

code/modules/power/groundmap_geothermal.dm

Currently, the way the check is setup, if corruption activates and not enough marines are on ground, it gets to the PROCESS_KILL bit and stops its processing, which does not restart unless recorrupted or fixed. This was triggered by the tad taking off for example, as this triggers gen corruption to activate and start processing, causes it to not see any marines on ground, and cancels processing due to that.
This PR makes it return whether or not there are enough marines on ground, preventing the PROCESS_KILL bit from being reached provided it is corrupted and has its corruption activated, which should avoid said issue. (Of course, it still checks for the required amount for providing the actual points.)
Fixes #9308 
Fix man good.
:cl:
fix: Groundside corrupted gens should not have their …

Fixes gens sometimes just not working and needing to be recorrupted.

---

code/game/objects/machinery/sleeper.dm
code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
code/modules/reagents/holder.dm
code/modules/reagents/machinery/chem_dispenser.dm
code/modules/reagents/machinery/chem_master.dm
code/modules/reagents/reagents.dm
code/modules/reagents/reagents/toxin.dm

Acts as an alternative to https://github.com/tgstation/TerraGov-Marine-Corps/pull/9820
You had to know this was coming.
Right now the game suffers from a small group of players who have figured out how to duplicate razorburn and then microdose it. 
This PR patches the current methods being used and adds some future protections against this sort of thing.
To start off, reagents no longer transfer to dead mobs, this was being used to gas large groups of dead monkeys with nanites.
Sleepers no longer perform dialysis on monkeys at all, this was being used to transfer the nanite reagent to beakers.
I'm going to answer some questions here to save time.
Q. But what if they just start gassing live humans to extract nanite reagent?
A. Sleepers now purge any chemicals instead of removing them to a …

Fixes razorwire duplication exploit, adds ability to blacklist medical chems

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/projectile.dm

Basically, the way explosive (rocket) ammo works is that on_turf_hit, it explodes, which generally works all fine since a rocket doesn't tend to pass through walls. Hoowever, when there is say, a shell that passes through walls and is explosive, said code causes issues, namely exploding on every closed turf (mainly walls) and stacking explosions, amping its lethality to questionable levels. ~~This resolves this problem via only calling on_turf_hit()'s drop_nade() if said turf is the original intended target, as that is the only situation where it *should* explode on hitting a turf (since hitting xenos or whatever else is handled in the other on_hit procs and it doesn't pass through mobs / simillar anymore)~~
Instead of what I did before, I instead resorted to having ammo not do …

Fixes AT gun APHE chain explosions

---

_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

FCDR now has loadout vendors in all shipside maps except Sulaco. Waiting on you, Derrick, for the Sulaco map change.
In PoS, I change up his bunk to ensure that he has armament vendor, clothing vendor, armor vendor, and loadout vendor.
In Minerva, due to constraints, I have to change up SO, captain, and FC's bunk to give room for FC's loadout vendor and a clothing vendor.
For posters, I change some poster's positions in both maps for aesthetics and visual reasons.
I overheard that FCDR has a loadout vendor in his bunk. I had to check all the shipside maps, which wasn't too hard, to see which map, and surely enough, it was Theseus that had loadout vendor. Of all the shipside maps, Theseus has FCDR not running to marine prep like a peasant.
As par usual of me, I ensure that all shipside …

Tweak Minerva and PoS for FCDR to have loadout vendor and change poster's positions

---

code/__DEFINES/combat.dm
code/modules/mob/living/carbon/xenomorph/damage_procs.dm

Code for xeno handle of explosions was strange, and unconcise at times. This PR makes it more standardized, and very slightly nerfs explosions in one particular case.
It is now easier to change explosion behavior. 
It is also easier to understand how explosions work.
Finally, slightly nerfs light explosions on benos with no bomb resistance (most benos actually) so that they are in line with other cases in terms of stagger and slowdown.
:cl:
refactor: Refactored xeno explosion damage procs
balance: Slowdown from light explosions on weak benos reduced from 4 to 3 to be in line with other cases
balance: Stagger is now always 2 less than slowdown with xeno explosions
/:cl:

Xeno ex act refactor

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm

Crusher Advance in its current form is near useless because it does not "ram" things in its immediate path or put crusher in a full charge state during or after.
This PR seeks to remedy that. For a separate PR I am also debating lowering the very high plasma cost in light of the fact each tile covered by the ability now also depletes plasma as if you were full speed charging and stacking the costs. Perhaps keep the cost as is but leverage `agile_charge` to allow fun diagonal ramming just for the Advance path.
Here you can see it won't even touch a wooden table currently:
`We skid to a halt.`
I added a readout for `valid_steps_taken` to visualize what was happening to the counter. As you can see currently it is way lower than it should be:
Here is the result of the fix:
`We crush wooden …

Fix crusher primo advance

---

.github/CONTRIBUTING.md
_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm

All shipsides shall spawn with the following:
6 30mm ammo crates
2 banshees
2 keepers
2 widowmakers
4 mini rockets
2 GAU-21 30 mm cannons
2 rocket pods
2 minirocket pods
Update map contribution to ensure that other contributors can read good practices on map PRs.
Theseus is the only shipside map that has the most CAS ammo compare to all shipside maps. It is the most beloved of all the CAS PO since they can boom boom more. This ensures that all CAS PO have the same ammo across shipside maps.
Long time ago, Theseus was made for high pop (whatever that meant). Only Big Bury is the dedicated high pop shipside, and even then Crash game mode doesn't exist after 30+ pop.
Theseus has
6 30mm ammo crates
2 banshees
2 keepers
4 widowmakers
6 mini rockets
2 GAU-21 30 mm cannons
2 rocket pods
2 …

Standardization of Round Start CAS ammo

---

code/modules/mob/living/simple_animal/friendly/cat.dm

Gives cat hats half the armor of FC beret and decap immunity.
The brave companions that oversee marines from above now get to join the fight themselves. This tactically vital improvement will both boost the morale of troops and utilization of our limited yet considerable feline forces. As a side effect this might also cause marines to protect cats harder and in the future may even inspire other quad-pedal companions to get inspired to be on the frontlines themselves.
:cl:
add: Cat as helmets now provide decap immunity and half the protection of FC beret
/:cl:

Jones Gets Sturdy

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm

Crusher was the only xenos to have unique explosion handler, which overrides default behavior with 0 damage from light or heavy explosions, but doubled damage from devastating ones. This PR removes this handler. This code is likely a remainder from CM, since it wasn't ever changed by anybody.
Makes game more intuitive - game plays as you expect it to play. Crusher now can be damaged by nades, but is very resistant to them, as he still has tier 3 armor. He can also be damaged by all CAS weapons. For info - CAS machinegun and nades will deal 30 damage on average. 
:cl:
code: Removed ex act from crushher.dm
balance: crusher is no longer immune to some explosions
balance: crusher gets less damage from biggest explosions
/:cl:

Crusher unique explosion handler removal

---

code/modules/mob/living/carbon/xenomorph/damage_procs.dm

When it comes to explosion severity lower number = more severe.
```
#define EXPLODE_NONE 0
#define EXPLODE_DEVASTATE 1
#define EXPLODE_HEAVY 2
#define EXPLODE_LIGHT 3
```
Calling this a hack due to the tech debt accrued by assuming the defines will not go above 3.
Fix good.
:cl:
fix: Fixed xeno ex_act severity math.
/:cl:

Fix xeno ex_act severity math hack

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm

Someone *cough* in their last PR didn't account for direction needing recalculation each step which is required to advance to all the red arrow destinations:
Fix.
:cl:
fix: Fixed Crusher Rapid Advance forcing 8 directions only.
/:cl:

Fix crusher rapid advance forcing 8 directions

---

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Displays the overheal amount next to health like `Health: 100 + 200/200` if you have an active overheal.
Knowing exact values is good.
:cl:
add: Added xeno overheal amount to the status panel.
/:cl:

Add xeno overheal amount to the status panel

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm

Gives mature+ Crusher bomb resist 4 to restore previous ex_act override functionality through the use of numbers.
Tivi's suggestion fulfilled (for maintenance purposes).
> people can feel free to buff it with numbers
Unfortunately the snowflake devastation effects are lost, but keeping them would require a snowflake type check in ex_act or bringing back the override.
:cl:
balance: Mature+ Crusher now has bomb resist 4.
/:cl:

Undo Crusher bomb immunity removal with numbers

---

_maps/map_files/icy_caves/icy_caves.dmm

removes some stuff and fixes some stuff
Red disk was more or less a free disk for marines, so added a silo and fog area west of it in the miner building behind the icy walls to prevent undefendable camping meaning xenos only got a few fog spots to shoot from giving marines a chance.
green disk had marines hard camping it so fixes that by extending the fog  upward rather then closer to the disk giving xenos a place to attack from two areas.
blue disk well a bit tricky i think its more or less an issue of skill and its already pretty far so i aint touching it
there was also that silo south of dorms which had no fog and stuff so i deleted that
:cl:
balance: fog and silo changes
/:cl:

Icy caves crash fixes & adjustments

---

code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/living.dm

Offset is now reset on reset_perspective(), and ghosting triggers reset_perspective() like it should.
Previously dying or ghosting or whatever while scoped/zoomed/whatever just straight up wouldn't reset it.
Not only is there no way to remove this (annoying) if you go into another body you keep the zoom and can move and shoot around with it. Sniper scope SADAR bad!!!!
:cl:
fix: Zoomed vision + offset now resets properly when ghosting/on death
/:cl:

Scope vision + offset now resets properly when ghosting/on death

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/mounted.dm

You can anchor the TAT.
APCR Changes.
100 pen down to 40.
damage upped to 160.
Sunder from 55 to 65
Rebalances APCR to deal less damage against higher tier beans, sunder upped. I might reduce the pen further.
Anchorability on the TAT is a no brainer.
:cl:
qol: You can anchor the TAT-36 as a marine.
balance: APCR changes, 40 pen from 100, damage upped to 160, sunder upped to 65.
/:cl:

APCR changes, and AT Gun anchorablity

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Alternative to or to be merged with https://github.com/tgstation/TerraGov-Marine-Corps/pull/9904
Wraith can still blink in phase shift, it just won't apply the debuff on anything
Unkillable + no counter + actually pretty severe debuffs, even with eyeblur removal
Blink debuffs probably wouldn't be that strong without phase shift (you can't apply them on standing targets since debuffs are only applied on same tile as wraith now, instead of 3x3), but do whatever
:cl:
balance: Blink debuff no longer applies while the wraith is in phase shift
/:cl:

Removes blink debuff when wraith is in phase shift

---

code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm

Centrifugal Force and Regenerate Skin are both on-click trigger abilities that can never be selected. This makes them not /activable (the type for selectable abilities) and with that fixes the keybinds for both of them not working (alternatively could have been resolved via modifying what the keybinds do, but since they're not actually selectable this is a moot point.)
Additionally, allows Centrifugal force to actually be interrupted via retriggering, sometimes (this change just allows it to reach the check that can abort it which wasn't accounted for before, however the timer may not be existing at specific timings and therefore not interrupt it, which still leaves this somewhat inconsistant at times, but better than before)
Fix man good, probably.
:cl:
fix: The keybinds for Centrifugal …

Resolves some Defender action issues

---

code/modules/mob/living/blood.dm

Limbs skip bleeding if they aren't bleeding normally. Missing limbs are special cased instead of bleeding normally, so that check needs to go first.
bugfix
:cl:
fix: Removed limbs bleed properly
/:cl:

Makes missing limbs bleed

---

code/game/objects/items/storage/pouch.dm

Mini pepperball mags are, as the name suggests, pretty mini, have low ammo and therefore run out of ammo quickly with it's mediocre fire rate. When I made the mini pepperball I did not consider how you store these mags. Since the mini pepperball is already pretty weak compared to other attachment options, ammo for it should at least be easy to carry around.
Note this does not allow regular pepperball to fit in pistol pouches.
Plasmapistol OP, ammo fits in pistol pouch.
Mini Pepperball weak, ammo does not fit in pistol pouch.
Curious.
:cl:
balance: mini pepperball magazines now fit in pistol pouches
/:cl:

mini pepperball magazines should fit in pistol pouches the second

---

code/datums/beam.dm
code/datums/status_effects/debuffs.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/energy.dm

About The Pull Request
Tesla gun is a rarely used weapon, highly underestimated by marines. But in fact when it is used, it can have unexpectedly high impact. Current effects are:
- Skill block for xenos for LONG time
- Strong plasma drain with effect lasting for 10 seconds, draining 60% of your max plasma
- Slowdown, which usually makes difference between whether you are faster than marine or not
- All this with abysmally large effect range
- But also slow speed and firerate
This PR is trying to make tesla gun less painful for xenos and more fun for marines.
Before, one pew pew from marine could break Queen Screech assault by blocking skills of every xenos in large radius. Even more painful, it made possible to hunt xeno by having few marines by your side when you shoot the tesla to …

Tesla gun rebalance

---

code/datums/elements/deployable_item.dm
code/game/objects/items.dm
code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/mounted.dm

the TL102 miniscope now rezooms in when you rotate.
I removed the spam delay on scopes for ease of use when rotating the deployable weapons.
deployables no longer check direction after deployment, brave broke this earlier
Fixes up some things.
:cl:
qol: The TL102 miniscope now rezooms in when you rotate.
fix: Deployables no longer check direction after deployment, but before.
/:cl:

Some deployable weapon updates

---

_maps/map_files/desertdam/desertdam.dmm

Preweeds Chigusa, makes some minor balance changes and consistency changes which I'll list here
-To compensate for lack of deep caves, NE xeno territory now comes pre-fortified.
-Replaces stairs with a newer version I made for LV.
-Makes some cosmetic adjustments to NE temple area.
-Moves blue disk generator farther east after complaints from xeno mains about how close together the disks were.
-Makes the SW merchant ship not completely invulnerable.
-Fixes some improperly mounted fire extinguisher cabinets.
-Fixes some improperly rotated shutters.
-Preweeds 90% of Chigusa, with greater density in the eastern side.
Fixes good, people have been bugging me to preweed for a while now and currently we have the pop where Chigusa is relevant enough that it needs adjusted.
:cl:
balance: Chigusa …

Preweeds Chigusa + minor changes and fixes

---

code/game/objects/structures/teleporter.dm

Buff teleporter from 20 sec cooldown to 2 secs
It is easy rn to bypass the cooldown by stacking on teleporter, which is honestly janky.
Two solutions: 
- One object teleported at once, which is a major nerf to teleporter
- Cooldown being almost irrelevant. That's a buff, but also a QOL. 
I'd rather take the second option, teleporter is a strong tool for engineers and nerfing them like this would make it irrelevant.
Also, make the cooldown shared between the two teleporters, so you're not instantly teleported back by mistake
:cl:
balance: Teleporter cooldown severly reduced to 2 secs (rather than 20 secs)
/:cl:

Teleporter buff cooldown

---

code/game/objects/items.dm
code/modules/mob/inventory.dm

Title.
TG has simple little animations for picking up items and dropping them, this PR ports them.
It looks fancy and lets you see who's picking up what.
:cl:
add: Ported TG's animation effects for dropping and picking up items.
/:cl:

Ports TG's drop and pickup animations

---

code/modules/projectiles/guns/energy.dm

If you change from one firemode with a lower charge/shot to a firemode with a higher charge/shot, you lose some charge = to the difference between the two. If you switch back you regain this charge, but it means you will only get 19 overcharge shots on a laser rifle etc if you change firemode with a cell in, and stay in that firemode.
This was added to fix some other funky energy gun bugs which no longer exist, so is now safe to remove.
Losing one shot because you changed firemode with a loaded gun is sad times.
:cl:
fix: Changing firemode with a loaded energy weapon no longer tweaks the cell charge
/:cl:

Fix TE power cell drain bug

---

code/modules/projectiles/guns/mounted.dm

Changed MG and TL102 integrity to 200 in line with T27.
Currently the T27 has 200 integrity, while the MG has 150, and the TL102 has 125. Also normal guns have 250, if you put them on a BAS.
It doesn't make sense to me that the guns that are bigger and heavier have less hp then the guns that can actually be fired when not deployed, as currently thy can be destroyed literally in a couple of seconds worth of acid spit, as they have zero acid (and melee) armour.
consistent integrity, heavy gun doesn't get deleted in 4 shots.
:cl:
balance: MG and TL-102 have 200 integrity like the T27
/:cl:

Make mounted gun integrity consistent

---

code/__DEFINES/conflict.dm
code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
code/modules/mob/living/carbon/xenomorph/damage_procs.dm

Xeno bomb armor is now a usual armor. Before it was essentially hard armor. No magic and noob coders who waste time on something like explosions. 
Raw numbers for bigger ex adjusted so that total damage in line with old damage. Slowdown, stagger and sunder have same effects as before. gib range is same.
**Before:**
Common case, Nade or CAS machinegun (light ex): 
100dmg on armor 0, 70 dmg on armor 3
Rare case, Mortar HE direct hit or CAS rocket direct hit (devastating ex): 
gib armor 0, 170 dmg on armor 1, 150 dmg on armor 3
**After:**
Common case, Nade or CAS machinegun (light ex): 
100dmg on armor 0, 70 dmg on armor 3
Rare case, Mortar HE direct hit or CAS rocket direct hit (devastating ex): 
gib armor 0, 180 dmg on armor 1, 140 dmg on armor 3
- Correct armor values in game codex.
- …

Change xeno bomb armor to usual soft armor

---

code/game/objects/items/stacks/medical.dm

3->10 for bandage/ointment, +3 for ATK and ABK.
1->1.5 seconds use time.
Makes bandages and ointment actually useful and useable rather than utter garbage, and I think the slight use time increase won't be too bad.
:cl:
balance: bandages and ointment heal 10 brute/burn, and ATKs heal 3 more damage up to 15. Use time increased by .5 seconds.
/:cl:

bandages heal more, but take longer to use

---

_maps/modularmaps/lv624/medbaytwo.dmm

It swaps out the 2 Marine meds in this variant for Nanotransen+ units.
I don't think the shared shipside pill vendor being groundside was intentional, so this update swaps them out with the usual NT+ vendor....And well, there's not much else I can say about that
:cl:
fix: Swapped out the Marine Meds on a certain LV variant for the usual NT+.
/:cl:

Updates LV medbay variant 2.

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm

Title.
The hivemind is one of the premiere support roles in the hive. It provides healing, building, and weeding against all odds from marines' superior firepower. It's the drone that keeps on supporting.
Weirdly, even though it can heal, it cannot give plasma to other xenomorphs. This can be an alternative to #9911 , but it depends on the maintainers. I'm giving it the drone plasma transfer since ~~hivelord has a lot more compared to drone, I'm giving hivemind a stronger plasma transfer, between drone and hivelord, just to make it more viable for a drone caste player to go hivemind, and it makes sense that~~ hivemind is drone that saw the weakness of fresh and embrace the resin.
:cl:
add: Give Hivemind Transfer Plasma
balance: Provide Hivemind plasma transfer so it can support xenos; it …

Give Hivemind Transfer Plasma

---

code/modules/projectiles/magazines/misc.dm

Title.
/datum/ammo/bullet/smartmachinegun is not the same as /datum/ammo/bullet/smartgun. MJP deleted /datum/ammo/bullet/smartgun/rifle to make T-25 use /datum/ammo/bullet/smartmachinegun but not changing the T-25 packet.
Quick fix, please merge under 24 hours.
:cl:
fix: Fix t-25 ammo packet not working
/:cl:

Fix t-25 ammo packet not working

---

code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/living.dm

Makes night vision scopes actually offset their vision when you scope in.
#9894 changed reset_perspective which uh, is called more than just when you die. Added a check to see if the mob is kill, before resetting their vision.
Nightvision scopes actually working is good.
:cl:
fix: Night vision scopes work properly when activated.
/:cl:

Fix night vision scope offset

---

_maps/map_files/Icarus_Military_Port/icarus_military_port.dmm

Removes hostile crate mimics from Icarus.
This shouldn't be in the game, simple mobs are broken anyway and spam runtimes when active. 
:cl:
balance: Removed crate mimics from Icarus.
/:cl:

Removes hostile mobs from Icarus

---

_maps/map_files/Minerva/TGS_Minerva.dmm

One picture is worth a thousand words.
Two pictures are worth twice the thousand words
Minerva is known for its symmetry. I didn't follow that philosophy when I changed its req, so here we go.
To deal with the empty space from the symmetry adjustment, I had to add a briefing area. You're welcome, RPers.
Also, CAS armament area is more pretty.
:cl:
add: Minerva's req has been change to make req conveyor belt symmetrical in respect to req
add: briefing area in Minerva
add: Minerva's CAS armament area is now prettier
/:cl:

Change Minerva's Req, CAS armament area, and add Briefing Area

---

code/game/objects/structures/window.dm
code/modules/projectiles/guns/flamer.dm

Stops flamethrowers from going through windows, and allows them to go through vehicles and deployables.
Turns out flamers use throwpass for these checks, so the coverage change effected these objects.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/9898
:cl:
fix: Flamers will no longer go through windows
fix: Flamers can go through vehicles and deployables again
/:cl:

Flamethrower fixes

---

code/game/objects/machinery/vending/marine_vending.dm
code/game/objects/machinery/vending/vending_types.dm

Self-explanatory title.
They're just splints.
:cl:
balance: The NanoTrasenMed Plus and MarineMed now have unlimited splints.
/:cl:

Makes the shipside NanoTrasenMed and MarineMed have unlimited splints

---

code/__DEFINES/traits.dm
code/modules/projectiles/mounted.dm

There is a bug, where you and your metafriend can simultaneously reload a deployed weapon, which allows it to have more ammo inside. Allows funny TAT things.
Bugfix good
:cl:
fix: fixed deployables being able to take several reloads at once
/:cl:

Simultaneous deployable reload fix

---

_maps/map_files/Minerva/TGS_Minerva.dmm

Title.
Also, add some 2x1 maint doors.
It's weird that Minerva is the only shipside map that has one landing zone for ERT. Time to fix that. It's going to be a bit cramp during spawn, but no one bothers. 
:cl:
add: Add Minerva's starboard ERT shuttle landing zone
balance: Add Minerva's starboard ERT shuttle landing zone
/:cl:

Add Minerva's starboard ERT shuttle landing zone

---

code/game/objects/items/reagent_containers/glass/bottle.dm

Title.
The basic med reagent bottles, bica, kelo, and tri, have 60u whereby the tramadol reagent bottle has 20u. Heck, even meralyne and dermaline have 60u. It's time to fix that.
:cl:
balance: change Tramadol reagent bottle from 20u to 60u
/:cl:

change Tramadol reagent bottle from 20u to 60u

---

code/game/objects/machinery/vending/new_marine_vendors.dm

Title.  #10030 removed use_points from the gear vendor parent type, making all specialized vendors not require points. Thank you very cool. This readds the use_points = TRUE to it and thereby resolves that issue.
Fixes #10041 
Fix man good.
:cl:
fix: Gear vendors use points again.
/:cl:

Fixes equipment vendors no longer requiring points

---

code/modules/projectiles/gun_attachables.dm

https://user-images.githubusercontent.com/46353991/164780296-59647659-facc-42d3-987c-e57d724f0a79.mp4
https://streamable.com/lm0fyv
you should really, not be able to move while using this thing
:cl:
balance: T-26 antimat's scope can no longer be used on the move
/:cl:

makes the AMRs scope unuseable on the move

---

code/__DEFINES/mobs.dm

The order in which equipped items are rendered on mobs is a little bit funky. Suit slot items and back items are currently rendered underneath everything head related. So if you have a large gun or backpack on, it appears underneath your hair or large helmet.
This PR means you get this:
Instead of this:
The system isn't perfect either way, as you still get issues with large guns (like the above RR) combined with large helmets like the jaeger causing clipping when facing downwards but in my opinion this is the lesser of two evils, as it results in significantly less clipping over all.
Also Jaeger helmets are bizarrely huge.
The ideal solution would be to have render order based on direction faced, or to have over/underlays that can apply to other item layers, but that's not something I …

Adjust layer order for mob item rendering

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/projectile.dm

Changes the behavior of TAT ammo.
APCR no longer causes an explosion, just a 1 tile flash (same as AP rockets). This was causing it to do around 240-260 damage instead of 160. Instead, it will do a short (0.5) stagger, slow and 2 tile knockback. **Direct damage has been buffed to 200 as well.** So a net 40-60 (depending on armour) damage nerf, as well as no AOE.
Additionally, for both APCR and APHE, their piercing behavior has been changed so that every time they pierce something, their max range is reduced. This stops the silliness of projectiles blasting into the distance and possibly killing benos through like 20 tiles of solid rock by fluke.
For APHE this is 10 tiles per pierce,
For APCR this is 5 tiles per pierce.
So for example, you shoot through a 2 tile deep resin wall that is 7 …

TAT tweaks

---

code/game/objects/items/defibrillator.dm

Fixed defib fumble time for unskilled mobs.
So it turns out that fumble time for defibbing someone was written... poorly.
If you have medical skill of 2 or above (corpman) you ignore fumble time entirely. If you're below 2 however, you have a fumble time of three seconds for medical skill 1 (SL's), or ONE SECOND for medical skill 0 (ungas).
I have no idea why it was like this, it's the only fumble check written in this way and it's written correctly in the same file by the same PR... but it's been like this for 2 years.
Literal greyshirts knowing how to use defibs better than people with basic medical training is bad.
:cl:
fix: Mobs with 0 medical skill will no longer know how to operate defibs better than those with basic medical training.
/:cl:

fix defib fumble time

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

PoS has additional changes. Mapper self wants to continue to improve map.
PoS is symmetrical in profile.
PoS's req has been flip. This is so that belt is closer to Alamo if anyone running req wants to deliver it to Alamo.
PoS' bar increases. Also, boxing ring is near bar in case if anyone wants to fight the old fashion way.
Radically change medbay to integrate bar better. Also, two cryotubes.
PoS's Condor landing zone has hazard tiles to indicate where it lands.
PoS now has 2x1 maint doors.
PoS has maint in its bow.
PoS has more generators.
For req, it makes it easier to move stuff to Alamo.
For medbay, it is to make traffic easier and fix the issues with current medbay.
For bar and boxing, they exist for RP purposes.
For Condor landing zone, I have done it for Alamo, so why not for …

Expansion of PoS: Req change 2.0, Bigger Bar, 2x1 maint doors, medbay remap, maint hall in bow, and Condor's hazard signs

---

code/modules/surgery/headreattach.dm

Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/8774
:cl:
fix: robot heads can be reattached as intended
/:cl:

Fixes robo heads not being reattachable

---

code/game/objects/structures/door_assembly.dm

Added
`resistance_flags = XENO_DAMAGEABLE`
`throwpass = FALSE`
`max_integrity = 50`
to door_assembly vars
All this = you can't shoot through door assemblies and xenos can slash through door assemblies like cheesecake.
Door assemblies cost the same amount as barricades but are quicker, cannot be damaged by xenos, and can be shot through. This essentially creates a stupid yet powerful use of door assemblies as better barricades.
This PR remedies that problem by making marines not able to shoot through them, making xenos able to slash them, and making the structure extremely fragile, thereby rendering it useless for a combat situation.
:cl: Vondiech
balance: Marines can no longer shoot through door assemblies. …

Nerfs door assemblies into unusable for combat situations

---

code/__DEFINES/mobs.dm

An alternative to #10110 
Makes the bio printer print limbs almost instantly.
As of now limbs take quite a while to print, and patients will often find themselves tossed into the autodoc for limb replacement surgery instead of being tended to manually.
This is a problem because manual surgery is supposed to be faster than the autodoc, and waiting so long for limbs to print is boring for the marine and doctor.
compared to #10110  It is much more sensible to speed up the bio printer itself for a variety of reasons: 
* People are already aware that the bioprinter makes limbs, 
* It doesn't further clutter medbay with another locker, 
* The bioprinter buff is given to all ships at the same time instead of being beholden to map conflicts or being forgotten in medbay reworks
* Print time is …

Bioprinter now prints limbs almost instantly

---

_maps/map_files/LV624/LV624.dmm

Title.
Green is in hydro, red is in bar dome, nuke generator itself has been moved into caves.
Currently both Green and Red disk are free disks for marines since they weren't balanced with the idea of LZs being used, this PR fixes that and also moves the nuke generator into xeno held territory like the other maps.
:cl:
balance: Shuffled the locations of nuke disk generators on LV624 to be less biased.
fix: Removed some duplicate LZ shutters from corporate dome
/:cl:

Shuffles LV-624 nuke disk generators, removes a shutter

---

_maps/map_files/generic/Admin_Level.dmm

Removed the two unmanned vehicles from Valhalla.
Valhalla has two unmanned vehicles in its cargo section as decoration, the problem is that these are on the AI's connection list. Now the AI can't actually do or see anything while using them, but they are still visible to the AI and make the list longer and more annoying to deal with.
:cl:
qol: Removed the unmanned vehicles from Valhalla.
/:cl:

Removes unmanned vehicles from Valhalla

---

_maps/map_files/LV624/LV624.dmm

Apparently I overlooked that the nuke I moved in this https://github.com/tgstation/TerraGov-Marine-Corps/pull/10109 PR has been accidentally relocated inside silo fog. While this isn't a huge issue during Nuclear War it keep marines from getting it during Crash.
I have moved it to the crashed ship, which is not covered by fog.
It's nice for marines to actually complete their objectives during Crash,
:cl:
fix: The nuke generator on LV is no longer inside silo fog
/:cl:

Moves nuke out of silo fog

---

code/controllers/subsystem/ticker.dm
code/modules/mob/living/living.dm
code/modules/mob/mob.dm

Moves the see invisible code to `/mob/living/` so it does not override observers toggle and calls it when the round ends so it actually works.
Fix good.
:cl:
fix: Fixed and improved end of round ghost reveal code.
/:cl:

Fix and improve end of round ghosts reveal

---

code/game/objects/machinery/squad_supply/supply_pads.dm

The issue: 
In SDMM: 
#10121 edited sprite name, and supply drop hatching becomes invisible. One line fix.
:cl:
fix: Supply Drop Hatching Being Invisible
/:cl:

Fix Supply Drop Hatching Being Invisible

---

code/modules/mob/living/carbon/human/death.dm

When you die it always plays a generic death message. Now you can enjoy the sweet custom text as you murder monkeys and bay furries.
Code actually doing something is good.
:cl:
fix: Species specific death messages actually work.
/:cl:

Fix species specific death messages

---

code/game/objects/items/defibrillator.dm
code/modules/mob/inventory.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/organs/limb_objects.dm
code/modules/organs/limbs.dm
code/modules/surgery/headreattach.dm

Synthetics no longer have organs.
Head reattach surgery works on combat robots now.
You can now see all three robotic species (Combat Robot, Synth, Early Synth) head items when they've been decapitated.
Fixes are good.
:cl:
fix: Synths no longer have organs that they cannot fix
fix: Combat robots can now have their heads reattached.
fix: You can now actually see synthetic/robotic heads on the ground for retrieval.
fix: Head reattachment surgery no longer makes you bald.
/:cl:

Robotic surgery fixes.

---

code/game/objects/effects/spawners/random.dm

For mapper use only.
Adds some spawners that randomly spawns a gun from a list, along with it's associated ammo. This should allow mappers to have random spawns without the issue of the gun not matching the ammo due to being two separate spawners.
mismatched items is pain.
:cl:
add: Add some spawners for mapper use for random guns to spawn with ammo they actually use.
/:cl:

Random weapon set spawners for mapping

---

code/datums/jobs/job/shipside.dm
code/game/objects/items/reagent_containers/glass/bottle.dm
code/modules/reqs/supplypacks.dm

Lemoline cheapened to 5 points for 10 units from 30 for 10 units, mera/derma have had changes since I made it all that time ago, and this is fine in my opinion.
Doctors/CMO get a 30 unit bottle, RSR and Synth do not get a set because they are not truly dedicated doctors.
Makes Lemoline buyable, and gives a reason to actually pick MD over RSR or Synth.
:cl:
balance: Lemoline is considerably cheaper, and doctors get a 30 unit bottle in their bag.
/:cl:

CMO and Doctors get 30 units of lemoline on spawn, cheapens Lemoline considerably.

---

_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm

Title.
I'm doing it on behalf of Loy who does botany when playing CL. Apparently only Sulaco has a seed extractor and it's this is a problem for all wannabe botanists.
Aspiring botanists need seed extractors to actually do Botany.
:cl:
add: Added seed extractors to PoS, Theseus, and Minerva.
/:cl:

Adds botanical seed extractors to a number of ships

---

code/__DEFINES/skills.dm
code/datums/skills.dm
code/game/objects/machinery/vending/new_marine_vendors.dm
code/modules/mob/living/carbon/human/species.dm

EARLY SYNTH CAHNGES
MAX HP 120->200
BRUTE/BURN MOD->.6
SURGERY/MED SKILL->3
CONSTRUCTION/ENGINEERING->5
Synths no longer get an essential PC.
Differentiates early/late synth. Variety.
PC should go, its absurd.
:cl:
balance: Essential PC removed, early synth now builds faster but is worse at medical than late synth.
/:cl:

Synth changes, early synth differentiated, given unique skills and nerfs, and deletes PC from synth

---

code/datums/elements/deployable_item.dm
code/game/atoms_movable.dm

Title. We're seeing an immense rise of people trying to do wacky stuff with deployables, mainly sentries, via using them in conjunction with objects that can vary their density and as such do not initially block placement, but can be used as cover afterwards via using whichever toggle said objects have. This removes this vector of wackyness and disallows deployables from being placed on tiles with any other structure or machinery present.
Additionally, improves the check during deployment to properly reflect the state after the do_after aswell, due to the possibility of people moving things onto the tile after starting deployment and the previous iteration only checking before the do_after.
Less cheese tends to be good for the game. Except if you are a mouse.
:cl:
balance: Any machinery / …

Deployables cannot be deployed on a tile with any structures or machinery, as opposed to only dense ones

---

code/game/objects/items/stacks/medical.dm

After being applied to a treatable limb, health kits (gauze/ointment/advanced) will then cycle through all the other patient's limbs with a delay on each treatable one. They'll only use one unit of the stack for this entire cycle.
Alternative to #9968 
Helps with a primary complaint of basic kits, which is that if you apply them regularly you'll burn through them super fast.
Might be excessive with regard to advanced kits, in which case their max stack could be reduced to five or so.
:cl:
add: After applying a health kit to one limb, you'll start applying it to all other damaged ones without using additional stacks.
/:cl:

Health kits chain apply

---

code/game/objects/machinery/vending/marine_vending.dm

Moves the typepaths for TAT and the Non-IFF hmg (including it's ammo) from weapon vendor to engineer vendor, 
The reason why I'm moving them is because due to the fact that they're available normally in the weapons vendor it can be achieved in crash, TAT doesn't get additonal ammo aside from the shells it gets roundstart, nor does HMG get any extra ammo due to the lack of req, but it doesn't matter when TAT & HMG are only pulled out when marines finally get the nuke and double down their defenses with both of these tools. 
Marines already get a ton of sentries ontop of engineers being able to vend a teleporter for A BACKPACK EQUIPMENT SLOT, not even spending any points to actually affect the amount of materials or sentries they can get, which I will address in another pr
:cl:
balance: …

Moving TAT and Mobile HMG (Non-IFF hmg) From weapons vendor to Engineering Vendor

---

code/__DEFINES/conflict.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/projectile.dm

Reduces damage from 153 to around 120 when lased, massively reduces pen overall.
Damge stays at 90, pen reduced to 50 compared to pre change AMR, so armor actually matters in some cases.
Reduces damage/pen to old values, before david changes.
Adds back the 15 sunder and slowdown on hit.
Moves the AMR back to being a long range support tool rather than a big dick killing machine, overall.
Changes compared to pre nerf/buff AMR is because I personally believe scope movement should stay gone, and I think it needs minor compensation with slightly more damage overall, and the pen nerf compared to old one is nearly non-noticeable overall IMO, I think defoonders and crushers should feel the difference. Otherwise, I think this PR is better than alternatives.
:cl:
balance: AMR mostly reverted to …

Mostly reverts AMR state to pre nerf/buffs, with minor changes.

---

code/game/objects/machinery/deployable.dm

Fixes https://github.com/tgstation/TerraGov-Marine-Corps/issues/9366
disclaimer did not test
:cl:
fix: vision will no longer be bugged when a deployable item is undeployed while being used
/:cl:

Fix deployables not unzooming when picked up

---

code/datums/elements/deployable_item.dm
code/game/atoms_movable.dm

Reverts tgstation/TerraGov-Marine-Corps#10152
Causes a whole bunch of issues. #10165
Makes a significant percentage of turfs invalid for deployables, due to things like patches of grass, pipes, wires, light fixtures etc.
This needs to be done differently to work.

Revert "Deployables cannot be deployed on a tile with any structures or machinery, as opposed to only dense ones"

---

code/datums/gamemodes/game_mode.dm

Title.
Possibly makes the explicit client checks in the conditional redundant.
- Momentary network lapses that boot all clients will no longer cause premature round ends.
- Could drag out normal round ends when the last members of a team decide to give up and go SSD without explicitly ghosting, requiring additional admin intervention to avoid the delay.
:cl:
code: SSD mobs with a grace timer are now included in count_humans_and_xenos(count_flags = COUNT_IGNORE_ALIVE_SSD) results.
/:cl:

Include SSD mobs with grace timer in count_humans_and_xenos()

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm

Cancels xeno stealth when the owning mob loses the action.
bugfix
:cl:
fix: Hunters advancing to primordial while stealthed won't stay translucent
/:cl:

Cancel stealth on losing stealth action

---

code/modules/clothing/head/hardhat.dm

Title. At this time only includes hardhats.
Do feel free to point out other instances of this kind of exploitative light based tomfoolery, and if possible I will add them to this PR.
Consistency good. 
:cl:
fix: Fixed hardhats not turning off on xeno slash like flashlights.
/:cl:

Fix some throwable togglable light sources being unslashable

---

code/__DEFINES/mobs.dm
code/game/objects/items/scanners.dm
code/game/objects/items/stacks/medical.dm
code/game/objects/machinery.dm
code/game/objects/machinery/autodoc.dm
code/modules/mob/living/blood.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/human_damage.dm
code/modules/mob/living/carbon/human/life/handle_organs.dm
code/modules/mob/living/carbon/xenomorph/embryo.dm
code/modules/mob/living/living_health_procs.dm
code/modules/organs/limbs.dm
code/modules/organs/wound.dm
code/modules/reagents/reagents/medical.dm
code/modules/surgery/implant.dm
code/modules/surgery/internal_bleeding.dm

Wounds exist as a whole thing on top of limbs, tracking their individual damage and description and treatedness. The only gain from this is that if you examine someone you get to see what their wounds look like. This pr kills wounds as a datum with the exception of internal bleeding, which is refactored to process itself instead of being handled by the limb. Everything should work the same, with the sole exception of internal bleeding not contributing directly to the limb's brute loss.
Removes a level of abstraction which generally isn't thought about ingame and only really offers flavor (individual wound descs) as a benefit.
:cl:
refactor: Limbs have damage themselves instead of separating it into wounds
refactor: Internal bleeding doesn't count directly as damage on a limb.
/:cl:

Removes external wounds

---

_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
code/game/objects/machinery/vending/marine_vending.dm

All sentries shall spawn inside TerraGovTech Engineer System Vendor; to do that, I remove the sentry kit near FOB drone and just add an additional sentry kit in the TerraGovTech Engineer System Vendor.
Made some PoS' prep QoL by adding green facepaint near vendors since people would want to use it for coloring.
Remove 5 stacks of metal and 3 stacks of  plasteel near Theseus' FOB drone.
Remove extra crowbars and screwdrivers in all prep if needed since we don't need it to dissemable Jaegar.
The sentry kit next to FOB drone is a relic of an old time, so it makes senes to consolidate all the sentry kits into one place.
PoS' prep got an additional change since I saw Minerva has green facepaint for marines to use and PoS has none, so I added that. Also, deleted the vendors that lurk outside of …

Remove sentry kit near FOB drone and additional map stuff

---

code/datums/components/attachment_handler.dm

Guns spawn their attachments into nullspace. If a gun spawns into nullspace, it doesn't generate attachments. So, make them spawn their attachments inside the gun instead.
Closes #10135 
Bugfix
:cl:
fix: Default attachments which have their own attachments (miniflamer's the most common you'd notice) now spawn those attachments correctly
/:cl:

Fixes attachments not spawning with their own attachments

---

code/modules/organs/organ_internal.dm

Apparently bruised lungs just caused way more losebreath than broken lungs and will just kill you if you don't have exceptional luck. Reverses that.
worse wounds are worse than less worse wounds
:cl:
fix: Broken lungs are worse than bruised lungs now.
/:cl:

Makes broken lungs worse than bruised ones

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm

Title.
Retains hunter rendering layer (i.e. MOB_LAYER) across appearances to prevent practical invisibility when disguising as an object that renders below weeds.
No more invisibility for Primo Hunter.
Fixes #10167.
:cl:
fix: Disguised Hunter now appears above objects (e.g. weeds) regardless of what it is disguised as.
/:cl:

Fixes Hunter disguise rendering under weeds

---

code/modules/projectiles/guns/sentries.dm

What it says on the tin. You can no longer cheese 4+ free turrets by stealing them from the dropship modules.
You get your forward facing turrets only and you'll like it.
shitloads of free turrets are bad.
:cl:
fix: Turrets can no longer be removed from dropship turret modules
/:cl:

Dropship turrets can no longer be removed from their mounting

---

code/modules/xenomorph/xeno_structures.dm

Doing a pass through Xeno Structures and replacing some of the to_chat messages with (arguably) better looking balloon alert messages.
Does not remove nor replaces all to_chat messages.
Atomized by file for easier review. I am going line by line control-f to_chat so this is gonna be a long WIP.
> On the aesthetic side it actually looks really cool to see overhead notifications like "Franklin Ramis fixes the internal wiring of platinum …

Adds and Replaces To_Chat() With Balloon_Alerts() in Xeno Structures

---

code/modules/requisitions/fulton.dm

Another file pass with most to_chat() replaced with balloon_alert().
I'm doing these by complete random order.
> So by implementing this not only do we look fancy, but it also enhances team cooperation because …

Adds and Replaces To_Chat() With Balloon_Alerts() in Fulton Actions

---

code/_onclick/xeno.dm
code/datums/actions/xeno_action.dm

A few more Balloon Alerts, this time in xeno actions handing checks if an ability can be used.
Balloon alerts are weird. The font should really be more aliased and of smaller size (according to my testing). In it's current form, anything longer than 5 words is difficult to read.
> On the aesthetic side it actually looks really cool to see overhead notifications like "Franklin Ramis fixes the internal wiring of platinum miner" or "Queen …

Adds and Replaces To_Chat() With Balloon_Alerts() in Xeno Actions

---

code/modules/mob/living/carbon/xenomorph/xenomorph.dm

Fixes xenos not having weeds set when they spawn (e.g. from evo) on weeds and do not move.
Fix bug
:cl:
fix: fixes xeno not having weeds when spawned/evo on weeds and not move
/:cl:

Fix xeno not having weeds when spawned on weeds

---

code/modules/mob/dead/observer/observer.dm

Since `attempt_to_join_as_larva()` acts like a toggle now if you are already in the queue when you click the link in chat to Join as a Larva the result will be you get booted as if you clicked the regular button.
This adds a check to prevent that from happening.
Fixes: #10063
Fix good.
:cl:
fix: Fixed call of the burrowed unintentional larva queue leaves.
/:cl:

Fix call of the burrowed unintentional larva queue leaves

---

code/game/objects/items/tools/soldering_tool.dm
code/modules/organs/limbs.dm
code/modules/surgery/generic.dm

Missed adjusting a bit of bleeding code during the wounds removal, oops.
Closes #10178 , which was a combination of this bug and soldering code not checking a bitflag correctly.
Also removes wound clamping on surgery finish, since otherwise that hung around forever.
bugfix
:cl:
fix: Robotic limbs are firmly incapable of bleeding.
/:cl:

Fixes bleeding prosthetics

---

code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm

Simply includes the ability to command minions to a specific location that all queens up to Primo Queen has.
Imagine my disappointment when I purchase Primo Tier 4 and suddenly I lose the ability to command my 60 minion strong swarm to attack the FOB.
Well no longer. Now I can command my minions to die for me. 
Yes numbered Crusher, charge that razorwire. Trust me, nothing bad will happen.
:cl:
fix: Queen now retains the ability to command minions after maturing to Primo status.
/:cl:

Restores Command Minions Ability to Primo Queen

---

code/modules/mob/living/carbon/human/examine.dm

Pre-wound removal you could see if someone was bleeding through clothing on examine but I forgot to include that in the overhaul oops.
h
:cl:
fix: You can see bleeding on human examine again.
/:cl:

Return bleeding visibility on examine

---

code/modules/mob/living/carbon/human/human_defense.dm
code/modules/power/cable.dm

Robot repair with cable coil and welder automatically selects next damaged limb.
Also kind of normalizes some of the repair code.
Less monotonous clicking.
:cl:
qol: robot repair automatically starts repairing the next damaged limb
/:cl:

Makes robot repair automatically select next damaged limb

---

_maps/map_files/LV624/LV624.dmm
code/game/area/lv624.dm

Title.
Just looking at it you would expect the crashed ship near LV caves to at least be safe from acid rain, but it isn't. This wasn't a huge issue until I moved the nuke generator into the crashed ship, but now a badly timed rain can ruin the marine's round.
As amusing as it is, this should probably not be happening.
:cl:
balance: The crashed ship area in LV is now weatherproof and underground
/:cl:

Changes LV crashed ship to be underground

---

code/modules/mob/living/carbon/human/life/handle_organs.dm
code/modules/organs/limbs.dm

Since wounds don't exist any more we can be more discerning about whether a limb needs kit treatment, beyond just whether it's bandaged or not. Don't bother bandaging if there's no brute damage, don't bother salving if there's no burns, and don't bother disinfecting if there's no chance to gain germs from current damage.
Also fixes movement germs being applied in a couple incorrect cases.
Helps avoid confusion and slowdown from kitting healthy limbs, both from direct apply and from cycling.
:cl:
fix: You can't kit undamaged limbs
/:cl:

Prevents kitting undamaged limbs

---

code/game/objects/machinery/vending/vending.dm
code/modules/projectiles/ammunition.dm
code/modules/projectiles/gun_system.dm

The signal for a gun to disconnect from a worn mag only fires when the mag is moved from the mob to another location, so since restocking vending leaves it in the mob and qdels it wasn't disconnecting properly. Makes restocking move the item into the vendor first to fix that. Also moved the signal register into reload itself so that it's included in a tactical reload, and adds code to handle nulls in list when retrieving handfuls eg from revolvers.
Fixes #10201 
Fixes #10104 
Fixes #9231 
:cl:
fix: Restocking a back-mounted ammo (power packs, fuel tanks) will now properly disconnect them from any loaded weapons.
fix: Flamers won't stay connected to fuel tanks across time and space after you do a tactical reload.
fix: Revolvers won't sometimes jam after firing the first few bullets and …

Three minor gun fixes

---

code/datums/components/attachment_handler.dm

Per title. Previously, the old attachment would be dropped on the floor.
Mainly just QOL; having to pick up some very small icons from under you each time you swap an attachment can get really tedious when trying out builds or whatever. Also sucks for flamers. I've wanted this for quite a while, and it's a oneline change, so
:cl:
qol: When swapping an attachment, the old attachment now goes into your hand instead of on the floor
/:cl:

Swapping attachments keeps the old attachment in-hand

---

code/modules/mob/living/carbon/xenomorph/attack_alien.dm

Removes ancient ability of xenos that allowed them to instantly extinguish human marines with a single click of the help intent.
Xeno extinguishing marines is one of the last remaining relics of the capture days. Back when marines would instead flame themselves and thus kill themselves to avoid capture.
Now, it's just a bald (e.g., me) xeno misclick if accidently on help intent and giving marines a free instant fire extinguish.
Xenos should not be helping marines by reducing damage on them. If a marine is on fire, let them burn.
This will not effect xenos helping other xenos to extinguish their flames. Only between xenos and animals.
:cl:
balance: Xenos on help intent no longer extinguish their sworn enemies and instead watches them burn.
/:cl:

Removes Xeno Ability to Instantly Extinguish On Fire Humans With Help Intent

---

code/game/objects/machinery/miner.dm

Permanently disables phoron miners on global hijack signal.
Fix good. Seems like a bug when there is no possible way for xenos to prevent tad from fixing miners even if they were to go around and disable them all before hijacking (that is if the dropship locking window even allows).
:cl:
fix: Fixed phoron miners continuing to function after hijack.
/:cl:

Disable phoron miners on hijack

---

code/datums/elements/deployable_item.dm

Title. Simply makes sure that deployables check whether their tile is blocked after the do_after is finished as trusting conditions to remain the same is usually a bad idea. Thats it.
Fix man good.
:cl:
fix: Deployables should be less likely to have issues with turf blocking conditions changing during deployment.
/:cl:

Deployables check whether their turf is blocked more reliably

---

code/game/objects/items/explosives/grenades/marines.dm

See changelog.
This is just silly:
I used a modified Flare Gun here, but it should be easy to imagine Ocelot spam from a backpack full of this tiny item just as I have witnessed and experienced in-game. You know who you are 🧂.
Even with this change the time to kill is only like 2.5 times longer, but imo is much closer to balanced if someone wants to run this loadout.
:cl:
balance: Flares only deal extra burn damage to things not already on fire. Normal throw impact damage and fire stacks are unchanged.
/:cl:

Nerf flare gun spam

---

code/game/objects/items/tools/mining_tools.dm

A few more balloon alerts for plasmacutter actions. I prefer to keep to_chats with messages particularly flavorful.
> So by implementing this not only do we look fancy, but it also enhances team cooperation because …

Adds and Replaces To_Chat() With Balloon_Alerts() in Plasmacutter Interactions

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

RipGrayson's mapper QoL got merged, so I shall fix my mistakes.
The existence of 2 wide maint halls exist near high conflict area so that in hijack xenomorphs don't body block each other in a single tile while also preventing marines / ERT getting body slammed by crushers / bulls. The intention of 1 wide maint hall is to prevent xenomorphs from the "fade in fade out routine that xenos accel in", though often than not xenomorphs bait marines into tight corridors and end marines if xenomorph players are robust enough.
:cl:
fix: camera position in PoS
add: two tile wide maint halls around PoS
add: better hijack position when xenomorphs crash Alamo into PoS
/:cl:

PoS's ADDITIONAL changes: camera orientation and 2 wide maint halls

---

code/datums/components/harvester.dm

Fixes harvester storing 60 instead of 30 units of a reagent, along with some text prompts.
Updates text prompts from chat messages to runechat.
More clarity and fixes unintentional buff.
:cl:
balance: fixes harvester storing 60 instead of 30 of each reagent
qol: updates harvester messages to runechat instead of chat
fix: select reagent button icon no longer disappears sometimes when re-equipping the weapon
/:cl:

Harvester fixes and qol

---

code/game/objects/structures/dropship_equipment.dm

Fixes a bug where you can pick up a turret module with the ripley while the turret is deployed, and the turret stays where it is. This allows you to attach more sentry modules and stack multiple turrets.
Thankfully this isn't exploitable since turrets get undeployed back to their module when the tad takes off, but still a bug to be fixed.
Also fixes a bug where you can destroy the module for the MG, but the MG itself remains, allowing for stacking shenanigans.
Bugfix good
:cl:
fix: Fixed a couple of bugs that could let you stack turrets or MG's
/:cl:

deployable module bugfixes

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/specialist.dm
code/modules/projectiles/magazines/specialist.dm
code/modules/vehicles/multitile/hardpoints.dm

1. SG minigun firerate from .1 -> .15
2. SG minigun windup delay from .75 -> .4
3. SG minigun damage multiplier from .8 -> 1
4. SG minigun damage per bullet from 10 -> 15
5. Removed smartgun type bullet and the tank weapon that used it (Both were unused)
1. Right now the minigun is a bit too fast
2. Windup delay was a copy paste from MJP's original minigun I forget to change (shouldn't affect too much)
3. The SG minigun has its own bullet type and doesn't need a damage multiplier (Another copy paste forget)
4. Less firerate means more damager per bullet to maintain a DPS similar to the SG-29
5. Unused, removed to reduce confusion between actual SG weapon ammo
:cl:
balance: SG minigun fires slower and does more damage
fix: SG minigun is now consumer safe and no longer bullies low end …

SG Minigun balance

---

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm

Some more balloon alerts. A large part of these now originate above the target of the ability so hopefully these will work.
> So by implementing this not only do we look fancy, but it also enhances team cooperation …

Adds and Replaces To_Chat() With Balloon_Alerts() in Defiler Abilities

---

code/__DEFINES/dcs/signals.dm
code/__DEFINES/xeno.dm
code/datums/keybinding/xeno.dm
code/game/objects/structures/xeno.dm
code/game/turfs/walls/resin.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm

In line with my previous PRs modernizing the xeno interface, resin construction selection for all xenos are now done through a radial menu.
Resin construction selection is in the odd position where it is the only action that is cycled through by clicking it multiple times.
While in its current state, it is quite simple to cycle through constructions by clicking the action icon the required amount of times (and a bit more if the player miss-clicked too many times), it is the only one to do so.
For uniformity, I believe changing the selection to radial menu and bringing it in line with weed selection, drone plant selection, and (proposed) pheromones selection will be easiest for everyone to understand.
Note, there are requests that I close this PR as they prefer the old click to cycle …

Resin Constructions Now Can Be Radial Selected

---

code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
code/modules/screen_alert/_screen_alert.dm

Marine command orders have now been added to the Queen's hive message action.
Note, the current in-chat announcement of word of queen still occurs in order to allow xenos to reread what was announced in case they missed it or need to copy paste in a translator (for english playing on soviet servers or vice versa).
Looks a lot more modern. Kinda. Trust me, this looks a lot better with less buttons taking up the padding space around the message but that's something only the queen suffers though.
:cl:
add: Queen hive message now displays on game map.
/:cl:

Queen Hive Message Is Now Displayed and Animated

---

code/game/objects/machinery/doors/multi_tile.dm

There exists a green 2x1 airlock called Squad Preparation, and apparently the CO, MD, researcher, and CMO can't get through funny door.
Captain should walk anywhere he desires.
For MD, researcher, and CMO, often they load up and head out to help with surgery planetside or research, and weirdly enough they don't have a medical armory. Maybe we should change that.
:cl:
fix:  issue of anyone w/o ACCESS_MARINE_PREP can't get through 2x1 door
/:cl:

Fix issue of anyone w/o ACCESS_MARINE_PREP can't get through 2x1 door

---

code/modules/mob/living/living_defense.dm

Removes unnecessary and broken armor check that skipped the damage application. Also simplified damage calculation. It apparently as applying armor block twice in the same calculation. One at proc call and another within the proc itself.
Throwing knives now do damage. Hurray.
:cl:
fix: Throwing knives (and all other things thrown) now do damage!
/:cl:

Fixes Broken Throwing Armor Check

---

code/__DEFINES/xeno.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm

Just a small code relocation of the icon used in automatic weeding's radial menu selection.
From the current manual addition of the icon to the radial menu every time automatic weeding is selected to baked in at start time.
Weed radial menu is also a little bit tighter. From a radius of 48 to 35.
OLD:
NEW:
Just more uniformity in the code logic.
:cl:
qol: Xeno weed type radial menu made smaller.
/:cl:

Weeds Radial Menu Refactor and Slightly Compressed

---

code/datums/actions/xeno_action.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm

Due to a previous exploit with hiveminds, should show xeno action proc was used as a easy override check to ensure a hivemind that is not corporal could not use specific abilities.
This however broke hidden keybind only buttons I intended on implementing with my pheromone wheel of fortune #10240.
Instead, the could use check has been properly relocated to can_use_action.
Required fixes to allow for hidden keybind only buttons to be functional.
:cl:
qol: The actions that hiveminds can use while manifested no longer disappear but instead are disabled.
/:cl:

Refactors Hivemind Ability Checks to Not Use should_show()

---

code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm

Some more balloon alerts. This time for drones, and their fatter cousins.
With all these balloon alerts, we'll need to see if any accidentally conflict and overlap.
> So by implementing this not only do we look fancy, …

Adds and Replaces To_Chat() With Balloon_Alerts() in Drone, Hivelord, and Queen Abilities

---

code/datums/weather/weather_types/acid_rain.dm
code/game/objects/effects/aliens.dm
code/game/objects/items.dm
code/game/objects/items/explosives/grenades/marines.dm
code/game/objects/items/reagent_containers/food/drinks/bottle.dm
code/game/objects/items/reagent_containers/syringes.dm
code/game/objects/structures/razorwire.dm
code/game/objects/structures/stool_bed_chair_nest/chairs.dm
code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
code/game/turfs/open.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/mob/living/carbon/human/human_damage.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/xenomorph/attack_alien.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/mob/living/carbon/xenomorph/charge_crush.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
code/modules/mob/living/living_defense.dm
code/modules/mob/living/living_health_procs.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/projectile.dm
code/modules/xenomorph/xeno_structures.dm

All armor checks now execute through proper soft armor checks instead of ancient CM armor checks.
How ancient you say?
--------
**Why this new PR? Because fuck Git. I broke the last PR trying to resolve a merge conflict. This now has all changes manually copied over. Line by line via the coder's favorite keyboard combination: Control - C Control - V.**
Pain.
All armor interactions now execute through TGMC armor checks and returning TGMC values.
That means yes, Xeno armor now mean something.
Previously, xeno armor was infact returning 0 (as in no armor for anything) for numerous interactions. This was legacy code from Apop himself in the initial commit of open source CM.
Several ancient interactions such as acid rain were in fact doing 100% of damage to xenos regardless of armor due to …

Armor Check Refactor (Now With Manual Merge Conflict Resolution)

---

code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm

Runner abilities now have balloon alerts.
> So by implementing this not only do we look fancy, but it also enhances team cooperation because xenos/marines can see what their teammates are doing while being focused on …

Adds and Replaces To_Chat() With Balloon_Alerts() in Runner Abilities

---

code/__DEFINES/dcs/signals.dm
code/datums/keybinding/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm
code/modules/mob/living/carbon/xenomorph/say.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

All main caste xenos (not minions) and larva now have the ability to overwatch other xenos through chat (F) button.
However, only the queen is able to arbitrarily select a xeno from the hive to overwatch without seeing their voice in the chat (simply to prevent increasing the number of buttons).
Now larva and young runners can rest inside the safety of the silo and grab popcorn to watch the rest of the hive get railed at the front line without having to actually risk their own lives to see how it is going.
The drone is the player in this image and can now "overwatch" the queen via the (F) button in the chat. However, only the queen's overwatch will result in the eye appearing on the xeno HUD overlay.
Requires #10250 to be merged in order to function for all xenos other than the queen. …

All Xenos Now Have Overwatch Ability Through Chat

---

code/game/data_huds.dm

Adds a stat DEAD check to the fire stacks hud code.
Fix.
:cl:
fix: Fixed xeno hud perma fire stacks on dead.
/:cl:

Fix xeno hud perma fire stacks on dead

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm

the weed check for plasma regenning causes the signal handle_stealth was registered to not trigger, this fixes that by making it use process instead.
Fixes: #9620
:cl:
fix: fixed a bug that caused the hunter invisibility ability not get to standing still invisibility level due to it only attempting to do so when plasma was regenerated.
/:cl:

Fixes hunter not getting more invisible when standing still

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm

Due to the special case of hiveminds being purely base upgrade tier caste, setting the caste datum was crashing when trying to get a normal (e.g., young) upgrade since it does not exist.
This fixes that issue by forcing the upgrade to only look for base upgrade type since that is the only one that exists.
One less runtime. Might prevent the MC from self destructing mid-game????
:cl:
fix: Fixed an error appearing when a drone evolves to hivemind.
/:cl:

Fix Hivemind Runtime Upon Evolution

---

code/__DEFINES/mobs.dm
code/game/objects/structures/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm

Added balloon alerts to resin interaction and resin jelly application.
Also fixed multiple people using the same resin jelly and halved application time if resin jelly was in hand.
Balloon alerts and fixes good.
:cl:
qol: Resin jelly now has balloon alerts for application.
fix: Resin jelly can no longer be used by multiple xenos at once.
fix: Resin jelly is no longer applied twice as fast to self while in hand.
fix: Resin jelly can no longer be applied to fireproof xenos.
/:cl:

Added Balloon Alerts and Fixes For Resin Jelly

---

code/modules/mob/living/carbon/xenomorph/say.dm

Makes the parenthesis part of the clickable text.
Arguably looks better in both light and dark mode.
Is consistent with how the `FOLLOW_LINK` macro renders them.
:cl:
qol: Xeno hivemind chat follow links are easier to click.
/:cl:

Tweak xeno hive chat follow link, less click accuracy needed

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/energy.dm

Before anyone says anything about Elsa's PR #10229
I've had this idea and been working on it for longer so this isn't some kneejerk reaction.
Changes the sniper rifles main fire mode to have the IFF tag (Does not affect heat shot)
This IFF mode loses damage logarithmically for each friendly target it passes through.
Changes its sunder to 4 -> 1 
Increases the damage from 60 -> 85
Laser sniper can no longer take magnetic harness (it has an unremovable scope so you shouldn't be able to put it on in the first place but oh well)
Laser sniper can no longer take under barrels
Laser sniper can now take the bipod 
##I would like to stress that none of these variables are permanent and are all open to discussion
Everyone knows that the laser sniper rifle is bad in its current form, it has quite …

Laser sniper changes (IFF mode)

---

tgui/packages/tgui/interfaces/BlessingMenu.tsx
tgui/packages/tgui/interfaces/HiveEvolveScreen.js

I **strongly disagree** with the design choices in the xeno theme but I have atomized the improvements to blessings menu and conversion of evo screen to xeno theme into a separate PR.
:cl:
qol: Xeno Evolution UI now has the same theme as Hive Blessings.
qol: Minor improvements to spacing and color in the Hive Blessings UI.
qol: Hive upgrade button is now disabled if the hive has insufficient number of points to purchase it.
/:cl:

Unifies Xeno TGUI Windows to Xeno Theme

---

code/__DEFINES/dcs/signals.dm
code/_onclick/click.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
code/modules/mob/living/carbon/xenomorph/say.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Deletes control middle click overwatch selection for overwatch.
Overwatch now cancels if the watcher is damaged.
Removes code bloat. Also prevents xenos from being surprise killed when they're watching someone else.
:cl:
add: Overwatch is now canceled if the watcher is damaged.
refactor: Overwatch from chat now uses target reference instead of trying to match nicknames. This should mean it should no longer fail to work if xeno names are identical.
del: Queen can no longer select xenos to overwatch using control middle click.
/:cl:

Removes Largely Unused Overwatch Keybind (Ctrl-Middle Click) and OW Changes

---

code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

Larva, in their conversion to using standard evolution logic, can now no longer evolve if there is no shrike or queen. Such as round start.
This fixes that.
Once #10275 is merged, this will instead be converted to a xeno caste flag check so it's not larva snowflake code.
Larva can now evolve round start without having to ask admins.
:cl:
fix: Larva now no longer need a hive ruler to evolve.
/:cl:

Larva Can Now Evolve Without Hive Ruler

---

code/modules/clothing/modular_armor/attachments/modules.dm

Arrowhead modules were simultaneously tracking their own cooldown and using a callback to trigger the after-damage recharge start, and the two would desync. This changes it into only relying on a timer callback, plus a couple of misc cleanups.
Fixes #10236 
:cl:
fix: Arrowhead starts recharging again after taking damage
/:cl:

Fixes arrowhead module restarts

---

code/modules/mob/living/carbon/xenomorph/evolution.dm
code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Hive status and actual evolution checks use two, possibly different, mathematical formulas to calculate the limit of xenos for tiers two and three.
One key difference is that hive status / datum did **NOT** take into account burrowed larvas counting towards tier zero counts whereas evolution checks **DID** take them into account. Which was why in rare occasions even if the slots were completely full in tier 2 according to the hive status page, tier one xenos could still evolve to tier two.
I have now removed the evolution check's limit calculation in favor of hive datum's **AND** changed hive datum's calculation to now take into account burrowed larva.
Hive status page no longer lies when it says no more slots when there really is. And future c*ders wanting to balance xeno caste …

Unifies Evolution Limit Calculation to Those Defined in Hive Datum

---

code/game/objects/structures/barricade.dm

Since MJP isn't finishing this.
Closes #10232 
Improves one cade upgrade, which are generally agreed upon as pretty not worth right now. Requires more dedication for marines than just making sandbags unmeltable.
:cl:
add: Metal cades upgraded with caustic armor can't have xeno acid applied.
/:cl:

Caustic upgraded cades can't be melted

---

code/modules/clothing/suits/labcoat.dm

Put medical stuff on your labcoat! (most importantly, a med scanner for quick equipping)
I used to always gun for the labcoat as a doctor, either by asking CMO for one out of their locker (if they weren't anywhere else on the ship map) or by ACCIDENTALLY stumbling into their window with a machete, repeatedly, then ACCIDENTALLY hitting their locker until it disappeared (if they weren't anywhere else on the ship map). Why? because DRIP! no not really, its because the only equipment storage items that have quick equip are pouches, belts, back storage, _**and the place where you put your gun when playing marine.**_ Surgical aprons didn't allow you to put medscanner on your quick equip suit slot, but labcoats did. 
And they don't anymore. Why? well, they got updated to have 5 slot …

Makes doctoring instruments of medicine fit on labcoat

---

code/game/objects/items/scanners.dm
tgui/packages/tgui/interfaces/MedScanner.js

As title. Only shows whether any exist, nothing about types/volume.
It was a feature on the old health scanner but didn't get carried over yet.
:cl:
add: New health scanner shows an alert if the patient has unscannable reagents in them.
/:cl:

New healthscanner displays unknown chemicals

---

code/game/objects/machinery/floodlight.dm

This PR modifies the lighting values of floodlights to produce more "circular" lighting rather than the current blocky lit tile appearance. 
However, this can be considered a balance change as it does kinda improve the range of colony floodlights, barely, and nerfs armored floodlights to be less laser beam from god.
* Requires #10302 for floodlights to function.
:cl:
balance: LZ, Colony, and Armored Floodlights have had their lighting power (inverse dropoff) reduced. This means less lighting around the edges of floodlights but will now appear more circular in lit area.
balance: LZ and Colony Floodlights have had their lighting range improved to compensate for increased dropoff in light.
/:cl:

Floodlight Light Decay Changes

---

code/datums/gamemodes/nuclear_war.dm

Probably a good idea as a banaid fix while people rack their heads around how to better design this mode, in my opinion.
Might be better to make this map based to be honest, but in most maps xenos don't really need the incredibly high scaling, and death should atleast have some meaning in nuclear war.
:cl:
balance: silo scaling is 2 from 2.5
/:cl:

Drops nuclear war silo scaling from 2.5 to 2.

---

code/game/atoms.dm
code/game/objects/effects/decals/Cleanable/fuel.dm
code/game/objects/items/bodybag.dm
code/game/objects/items/explosives/grenades/grenade.dm
code/game/objects/items/explosives/grenades/marines.dm
code/game/objects/items/explosives/mine.dm
code/game/objects/structures/flora.dm
code/game/objects/structures/plants.dm
code/game/objects/structures/reagent_dispensers.dm
code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
code/game/objects/structures/xeno.dm
code/game/turfs/snow.dm
code/game/turfs/walls/resin.dm
code/modules/hydroponics/vines.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
code/modules/mob/living/carbon/xenomorph/egg.dm
code/modules/mob/living/carbon/xenomorph/facehuggers.dm
code/modules/projectiles/ammunition.dm
code/modules/projectiles/guns/flamer.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm
code/modules/xenomorph/xeno_structures.dm

All of the flamer_fire_act calls already used this argument, it just was ignored by most of the proc defs. Also adds one missing span call.
Buffs flamers against resin walls. One flame duration will always destroy a resin wall, taking ~15 seconds to do so. Miniflamers are nerfed by roughly an equivalent amount, so they're the same against mazes and weaker against mobs. They won't take a fully matured wall down in one shot, but will kill fresh ones.
Alternative to #10311 
Lets different flamers/ammo more uniformly burn stuff at different rates.
Improves flamers at one of their dedicated roles, area clearing.
Nerfs miniflamers, which're apparently still overperforming.
:cl:
code: flamer_fire_act gets a new argument that, among other things, means x-fuel is better than default at burning …

Adds an argument to flamer_fire_act, buffs flamer against resin

---

code/modules/surgery/amputation.dm
code/modules/surgery/bones.dm
code/modules/surgery/brainrepair.dm
code/modules/surgery/encased.dm
code/modules/surgery/eye.dm
code/modules/surgery/face.dm
code/modules/surgery/generic.dm
code/modules/surgery/headreattach.dm
code/modules/surgery/implant.dm
code/modules/surgery/internal_bleeding.dm
code/modules/surgery/necrosis.dm
code/modules/surgery/organs_internal.dm
code/modules/surgery/robolimbs.dm
code/modules/surgery/surgery.dm

Adds balloon alerts to surgery steps.
Makes surgery much easier for new docs, prettier, and makes it easier to see if you failed a step among the flood in chatboxes.
I have wanted this every single time I've done groundside surgery as rsr
:cl:
qol: Balloon alerts to surgery actions
/:cl:

Adds balloon alerts to surgery actions

---

code/game/objects/items.dm
code/modules/projectiles/gun_helpers.dm
code/modules/projectiles/gun_system.dm

You were supposed to be able to click the revolver with your empty hand to open/close the chamber, but an argument wasn't being passed properly through do_unique_action.
bugfix
:cl:
fix: You can open and close m44 revolvers.
/:cl:

Fixes being unable to open SA revolvers

---

code/game/objects/structures/barricade.dm

Fixes metal cades being upgraded with nothing when moving away from them while selecting an upgrade
Fixes good
:cl:
fix: Fixes metal cades being upgraded with nothing
/:cl:

Metal upgrades fix

---

code/game/objects/machinery/computer/intel_computer.dm
code/game/objects/machinery/computer/nuke_disk_generator.dm
code/game/objects/machinery/nuclearbomb.dm

Disables: Nuke disk gens, intel computers, and the nuke itself.
Fix good.
:cl:
fix: Fixed some groundside machinery not deactivating on hijack (like the nuke)
/:cl:

Disable more groundside stuff on hijack

---

tgui/packages/tgui/interfaces/MarineCasship.tsx

Keys 1, 2, 3, 4, 5 select weapons
6 deselects weapon
South and East keybindings were the wrong way around, swaps them round to be correct
(so before down would = east, right would = south - that's swapped)
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/10060 along with the lighting fix
You still need to focus on the window for keybindings (good), but firing a weapon un-focuses the weapon. I don't know how to fix that, so you'll still have to click on the window every time you fire a weapon. If there's a way to fix that please ping
More QoL good
Bugfixes good
This has been wanted for a while now
:cl:
qol: 123456 keybind weapon swapping for CAS
fix: Swaps south/east keybinds for CAS to where they should be
/:cl:

More hotkeys for CAS

---

code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/guns/flamer.dm
code/modules/projectiles/guns/grenade_launchers.dm
code/modules/projectiles/guns/pistols.dm
code/modules/projectiles/guns/shotguns.dm
code/modules/projectiles/guns/specialist.dm

This PR adds wield time and wielded movement speed maluses to underbarrel weapon attachments.
Underbarrel weapons provide marines huge damage and/or utility buffs with literally zero downside.
This is in comparison with most other attachments that have some sort of downsides for the benefits they provide.
The changes are pretty mild. All 5 underbarrels now add 0.2 second of wield time.
Make underbarrel weapons slightly more reasonable
:cl:
balance: Underbarrel weapons now slightly impact wield times for their parent guns.
/:cl:

Underbarrel weapon rebalance

---

code/game/objects/machinery/OpTable.dm

As title. You still need an anesthetic tank in the table, it just doesn't do anything. Instead the knocked out trait is applied to the mob after a delay, and removed after a delay following unbuckling. No behavior change gameside.
Supplement to #10313 , removing atmos remnants. 
:cl:
code: Operating tables don't use their anesthetic tank for internals any more. They still need one though.
/:cl:

Operating tables apply a trait instead of using internals

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/energy.dm

Reverts tgstation/TerraGov-Marine-Corps#10230, which gave in built IFF to the laser sniper.
The las sniper is vastly outperforming every other sniper by virtue of being an IFF hitscan sniper.
Mole prefers this, I don't mind.
:cl: Lewdcifer
balance: Laser sniper IFF reverted.
/:cl:

Revert "Laser sniper changes (IFF mode)"

---

code/modules/projectiles/ammo_datums.dm

Per title. Sundering value reduced from 2 > 1.
SG Miniguns are sundering really quickly, faster than Hivelords can treat entire hives worth of sunder.
:cl: Lewdcifer
balance: SG minigun sunder 2 > 1.
/:cl:

Nerfs SG minigun sunder

---

code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/coffin.dm
code/game/objects/structures/crates_lockers/largecrate.dm
code/game/objects/structures/janicart.dm
code/game/objects/structures/misc.dm
code/game/objects/structures/reagent_dispensers.dm
code/modules/hydroponics/hydro_tray.dm
code/modules/mining/satchel_ore_boxdm.dm
code/modules/paperwork/filingcabinet.dm
code/modules/recycling/sortingmachinery.dm
code/modules/vehicles/train.dm

See changelog.
Part 1 of X.
Closets (including coffins and toggleable crates) probably should not be immune from slash destruction, and opening one should not trigger attack cooldown.
Wooden crates, barrels, cases, plastic flaps, beer kegs, ore boxes hydro trays etc.. take a long time to destroy especially with acid which is even slower than slashing which the majority of overlooked movement blocking objects lack the resistance flag for.
:cl:
balance: Reduced the max_integrity of: coffins, large crates (the kind that must be broken or opened with a crowbar), cases, barrels, ore boxes, plastic flaps, hydro trays, mop buckets, janitorial carts, filing cabinets, and reagent dispensers.
fix: Added the xeno damageable flag to: janitorial carts, filing cabinets and reagent dispensers (beer keg, …

Allow many non-combat essential objects to be slashed at all or faster by xenos

---

code/__DEFINES/conflict.dm

As title. No functional changes.
So people mucking with guns don't have to go code diving to figure out what each flag actually does.
Is this one of those cases where it's worse because it means changes need to be made in two places and probably one of them will be missed?
:cl:
code: Ammo flag comments expanded
/:cl:

Adds explanatory comments to ammo flags

---

code/modules/projectiles/guns/specialist.dm
code/modules/projectiles/magazines/misc.dm
code/modules/projectiles/magazines/specialist.dm

This PR  brings back down the smart-minigun to a tolerable ammo count and ROF.
This was discussed in the balance channel on discord prior to making it. The numbers are chosen based on what a few people there said.
They keep the 1k magazines they get so it can be fully reloaded instead of having to use 3 magazines.
This makes it so the smartminigun isn't as oppressive as it currently is, alongside the sunder nerf it's getting in the other PR.
:cl:
balance: Smartminigun ammo count reduced to 1,000 and mag box down to 500.
/:cl:

Nerfs smartgunner minigun ammo count and magazine boxes

---

code/modules/projectiles/guns/specialist.dm

Per title. SADAR can no longer be fired until wielded.
People are insta PBing out of knockdown/stuns with SADAR AP. Yet another example of rocket tag gameplay with no viable or enjoyable response.
:cl: Lewdcifer
balance: SADAR is unable to fire until wielded.
/:cl:

Disables SADAR from firing until wielded

---

code/game/objects/structures/teleporter.dm

Undeployed teleporters are no longer able to resist the wrath of a thousand boilers
An item that should be taken advantage of when undeployed should be able to get melted when undeployed.
:cl:
fix: Removed the ability for an undeployed teleporter to not get melted.
/:cl:

Makes undeployed teleporters meltable

---

code/modules/surgery/generic.dm

Doesn't actually matter for functionality since the only thing that corpse health is important for is defibing and that updates health manually, but this clears up a weird display thing on health scanners.
bugfix
:cl:
fix: Suture surgery updates patient health for scanners.
/:cl:

Mob health updates on suturing

---

code/modules/mob/living/carbon/human/human_attackhand.dm

They've been inverted for weeks. Why does nobody report these things?
bugfix
:cl:
fix: Self-examine correctly shows whether limbs are treated
/:cl:

Fixes self-examine kit messages

---

_maps/map_files/LV624/LV624.dmm
code/game/area/lv624.dm

This chokepoint is the bane of marines and xenomorphs. Marines can't push else they get screw over by stun castes and xenomorphs can't push else they eat lead. Fundamentally, this chokepoint is the hallmark of a map design that mappers must keep in mind: avoid 1-tile entry in large traffic else you create chokepoints.
In Distress, it is pain.
In Nuclear War, it is less pain unless marines choose to push silo.
Also, add crowbar just to let anyone with incentive to break open boxes and connect plasteel.
Also, saw RipGrayson saying to make sand temple underground, so one line add.
:cl:
del: A memorable chokepoint in LV-624 cave
add: sand temple in LV-624 is now underground
add: crowbar in LV-624 LZ
/:cl:

LV-624 changes: Remove chokepoint in cave, add crowbars in LZ, and make Sand Temple underground

---

code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Xeno flag revamp moved the relevant flag into a different var but forgot to update what the facehugger actually checked.
Bugfix
:cl:
fix: Carriers and other appropriate xenos can pick up facehuggers again
/:cl:

Fixes carriers not carrying huggers

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/flamer.dm
code/modules/projectiles/projectile.dm

Previously all of the damage was dealt through igniting the mob's turf, which led to certain weirdness like not actually damaging moving mobs and AMMO_INCENDIARY code not triggering. This shouldn't change the effective damage in any way, just clean out niche bugs.
Adds an incendiary_strength var to ammo datums to adjust how hard AMMO_INCENDIARY actually ignites stuff.
Also fixes projectile flamer not being able to clear out vines or snow.
Bugfixes
:cl:
balance: Flamer's extended nozzle can remove vines and snow, along with other sources of ground fire.
fix: Flamer projectiles should more reliably ignite on hit.
/:cl:

Shifts projectile flamer to deal damage on hit

---

code/modules/mob/living/carbon/xenomorph/evolution.dm

Just a missing return.
Fixes #10405 
:cl:
fix: Moving early cancels xeno evolution properly
/:cl:

Fixes moving not canceling evolution

---

code/modules/projectiles/gun_system.dm

Fixed #10364
It turns out modifiers to projectile speed does fucking nothing, because the proc that adds it just gets, gets overridden by the proc that calls it in the first place.
Barrel charger projectiles are a bit funny because you can barely see them they move so fast, but eh, bugfix.
Bugfix good.
:cl:
fix: Projectile speed modifiers now actually work
/:cl:

Fixes projectile speed modifiers

---

code/modules/mob/living/carbon/human/life/handle_organs.dm
code/modules/organs/limbs.dm

Any two legs/feet that were missing or broken were supposed to cause an occasional knockout but this usually didn't happen because missing limbs don't process. Fixes that, and also reduces the knockout from a 20 second unconscious to a 3 second knockdown. It was a little overkill.
Also fixes amputated limbs not being amputated.
Bugfixes, and a random 20 second unconscious is not necessary.
:cl:
fix: When you have two broken or missing legs or feet, you'll now fall down once or twice a minute.
fix: Amputated limbs are amputated.
/:cl:

Fixes failing legs code

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Full white screen (aka:flash/flashbang effect) is kinda eh.
Changes to blind, which means you can see just a tiny circle around your turf, and a bit of eye blur.
Full white screen isn't great when it's 3 seconds long.
:cl:
balance: Empowered jab now actually blinds instead of flashing
/:cl:

Empowered jab tweak

---

code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/mob/living/carbon/xenomorph/xenoprocs.dm

As title. Right now, if a xeno is at low health while at high balance buff and then the buff drops a ways, it can just die immediately. Which's funny and usually won't happen since that requires a fairly drastic shift, but still. With this, if you're at 50% health before adjustment, you'll be at 50% after too.
Smooths out strong scalar adjustments.
Also fixes modified max health not showing up in the game status window.
:cl:
balance: Xenos keep current percent health when a balance scalar is applied.
fix: Game status window properly shows current max health when a balance scalar is active.
/:cl:

Xenos keep health percent through balance buff

---

code/__HELPERS/unsorted.dm

turns THIS
into THIS
removes 4 duplicate if's, removes a bunch of else-if's, turns this into a switch.
This code is used fairly oftenly for someone seeing someone else get shot, also getting used for the stethoscope... So it probably would be better if this was turned into a switch since a long line of else-if's like this is not really efficient.
:cl: Vondiech
code: Turns long line of else-if's in parse_zone into a switch. Also removes 4 duplicate if's for the hands and feet
/:cl:

Turns long line of parse_zone else-if's into a switch

---

code/game/objects/items.dm
code/modules/mob/living/carbon/human/inventory.dm

Over time the procs that are used to equip items to mobs (via stuff like quick equip etc) stopped working correctly due to refactors to how item storage worked for various things.
I fixed some of these for quick equip but didn't realise the issue was bigger than just effecting quick equip.
This should make the procs work for storing any ALL storage types regardless of slot now, so there may be some minor fixes for quick equip, but I mainly did this as a coder QOL as it makes fucking OUTFIT datums 200% easier to do, since postequip actually works, rather than having to make loaded storage items and all the pain that's involved with that.
If I've missed some storage items/types, please let me know.
Bug fix good
Outfits not being as suffering to make is gooder (also avoids bloat from loads …

Some fixes to equip procs

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm

Adds hivemind caste can_flags override to differ from the default of `CASTE_CAN_VENT_CRAWL|CASTE_CAN_BE_QUEEN_HEALED|CASTE_CAN_BE_LEADER`
Fix good.
:cl:
fix: Fixed missing hivemind can_flags.
/:cl:

Fix missing hivemind can_flags

---

code/modules/projectiles/ammo_datums.dm

Praetorian has a weird problem with it's neurotoxin spit. Young has a transfer rate of 9.5, then it gets nerfed to 9 on Mature, and then regains to 9.5 on Elder. This makes absolutely no sense, so I am reducing young transfer rate to 8.5 that way it doesn't nerf itself.
It fixes a oversight for Praetorian that nerfs itself half way through the maturation process.
:cl:
fix: Fixes unintended Praetorian Neurotoxin nerf at Young to Mature.
/:cl:

Fixes unintended Praetorian Neurotoxin nerf at Young to Mature.

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
_maps/map_files/LV624/LV624.dmm
_maps/modularmaps/big_red/bigredcargoareavar1.dmm
_maps/modularmaps/big_red/bigredcargoareavar2.dmm
_maps/modularmaps/big_red/bigredcargoareavar3.dmm
_maps/modularmaps/big_red/bigredcargoareavar4.dmm
_maps/modularmaps/big_red/bigredcargoareavar5.dmm
_maps/modularmaps/big_red/bigredcargoareavar6.dmm
_maps/modularmaps/big_red/bigredcargoareavar7.dmm
_maps/modularmaps/big_red/bigredcargoareavar8.dmm

Title.
It's time to remove easy miners next to FOB.
Ice Colony has this issue for a long time. Both LZ literally have marines walking toward miners. Splinter once said that it was easy to just flank miners near FOB, but the autism fort from these miners can be extensive and continue to run the show.
Big Red has a miner next door to LZ1 that is practically protected by walls, though to be honest, if xenomorphs push here and marines are weak, they will lose miner. That said, if marines are strong, this places holds too well until marines drop the ball, which will take a long time.
LV-624 has a similar case. LZ2 has two miners next door to the point that one can snip from FOB to one of the miners. This makes LZ2 a meta pick for miner and engineers who just so happen to practically dictate …

Remove miners near LZ

---

code/modules/projectiles/guns/rifles.dm
code/modules/projectiles/guns/shotguns.dm
code/modules/projectiles/guns/smgs.dm

Someone ded, plsnerf.
**shotguns**
For some reason shotguns had the default akimbo scatter values (so an extra 2-4 scatter for going akimbo).
Changed this to the rifle values of 3 and 5 (so between 6 and 10 extra scatter for akimbo), as it is presumably quite hard to akimbo two shotguns.
This should make akimbo combat shotguns still deadly at pb range, but medium/longer range slug spam will be considerably less reliable.
The only other shotgun you can actually do this with is the sawn off.
**Rifles**
Also changed rifles to have the standard akimbo firedelay debuff. It was removed when akimbo was made to actually effect autofire and I thought it was a bad idea at the time. Most notably it makes akimbo AR11 really gross at close range.
**SMG90**
Increased akimbo scatter for the SMG90 from …

Akimbo nerfs

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/reqs/supplypacks.dm

Some items have been moved away from reqs and its operational vendor. To compensate, some of these items have had their supply in normal vendors increased, or have been otherwise added to normal vendors.
List of changes:
- **CAS flares** can no longer be purchased from reqs. These were already available in the weapons vendor. To compensate, its supply has been increased from 30 to 50.
- **Normal binoculars** can no longer be purchased from reqs. Weapon vendors have these in infinite supply.
- **Normal flares** can no longer be purchased from reqs. Weapon vendors have 200 of these.
- **Tarps** can no longer be purchased from reqs. These were already in the reqs vendor. To compensate, its supply has been increased from 2 to 10.
Part of an effort to reduce content bloat in requisitions. With …

Moves some items away from reqs

---

code/game/turfs/walls/resin.dm

The strength of fire against resin walls specifically has been reduced from 1.5 to 1.25, as per Tivi's request.
Fire is too good at clearing walls. This should make it a tad bit more bearable.
:cl: Lewdcifer
balance: Fire strength against resin walls reduced from 1.5 to 1.25.
/:cl:

Nerfs fire strength against resin walls

---

code/game/objects/structures/barricade.dm
code/game/objects/structures/platforms.dm

Removes the dexterity requirement to interact with all barricades and platforms.
Xenos do not have the dexterous flag, which means they can't interact with any object that requires dexterity. This is every item in the game by default, and climbing counts as interacting.
This doesn't let them open plasteel cades or anything, so there shouldn't be any issues. But please let me know if there is some kind of weird interaction this could let them do that they shouldn't be able to.
Getting stuck behind a knee high rail as a 3 meter tall alien is stinky.
:cl:
fix: Xenos have been sent to climbing school, and can now climb platforms and (unwired) barricades of all kinds.
/:cl:

Xenos are no longer cucked by a knee high railing

---

CONTRIBUTING.md

PL is not a role anymore and won't come back.
contributing.md is now front page, as it's something that new coders should read yet they usually don't notice it

Remove project leader role from contributing.md, move that file to root folder

---

code/modules/projectiles/guns/rifles.dm
code/modules/projectiles/magazines/rifles.dm

gives the BR a 36 round mag instead of a 35 round one
magazine sizes that don't fit bursts give me minor, but stacking, aneurysms
:cl:
balance: the BR-64 battle rifle now has one extra round per magazine, raising it to 36 rounds instead of 35, with a new theoretical max of 36+1 rounds in the gun
/:cl:

gives the BR-64 one (1) extra round per magazine

---

code/game/objects/machinery/mortar.dm

As of right now, you need to use wrench to move mortar. Relic of CM.
This PR removes that. Just drag the mortar's sprite your mob's sprites like other deployable objects, and you're good.
Deployable weapons are easy to move with the sheer and weird exception of mortar. 11C Indirect Fire Infantryman in the Army or 0341 Mortarman in the Marine Corps don't need to use a wrench to move mortar. My hypothesis is that no one has updated mortar to the new deployable code, therefore I'm doing the favor for all indirect fire marines.
:cl:
add: Mortar's description now tells players how to deploy and undeploy
qol: Remove wrench from moving mortar; drag the mortar's sprite your mob's sprites like other deployable objects
balance: Makes it easier for mortar marines for tactical and superior position …

Remove using wrench to undeploy mortar

---

code/game/objects/items/scanners.dm
code/modules/organs/limbs.dm

I was completely convinced this code already existed, which's why I opened #10394 . It's even part of the why section. But, uh, it didn't actually exist. Adds it.
Turns out germs were in fact the only way necrosis hurt organs. Oops. Without this, necrosis on head/chest/gut doesn't really do anything.
Also cleans some carryover medscanner stuff from wound removal.
:cl:
add: Necrosis causes organ damage over time. Accidentally removed this when I killed organ germs.
/:cl:

Necrotic limbs applies organ damage over time

---

code/modules/projectiles/ammo_datums.dm

As title, 0 falloff for boiler shots. Applies to both globs and lances.
Featuring some minor suffering due to a diverged master.
Dedicated artillery caste doing higher damage from point blank is silly.
:cl:
balance: Boiler projectiles have 0 damage falloff.
/:cl:

Removes damage falloff from boiler projectiles

---

code/__DEFINES/dcs/signals.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/mob/living/status_procs.dm
code/modules/organs/organ_internal.dm
code/modules/reagents/holder.dm
code/modules/reagents/reagents/drink.dm
html/changelogs/AutoChangeLog-pr-10326.yml

Kidneys now moderate the total number of medicines you can have in you at a time. 5 while healthy, decreasing while damaged. If you exceed this number you'll get an overlay and periodic confusion, the later scaling in frequency and strength with both organ damage and excess count.
Liver stuff is mostly cleaning up the current functionality. Only significant change is a chance to vomit if it's at least bruised.
Also fixes humans generating their reagent container twice, once in human/set_species and once in species/on_species_gain.
Provides a bit of reason not to just stuff yourself with one of every pill. Drawbacks are fairly minor without organ damage.
DD nerf is just there so having an extra healing chem in you doesn't make you able to run every single other chem with no drawbacks. It …

Adds new effects to kidneys, cleans up liver

---

code/modules/clothing/glasses/glasses.dm

Title.
A marine ballistic goggle takes two storage in helmet, and I do know marines that like the aesthetics of having goggles on helmet. This lets it that having ballistic goggle in helmet allow you to have another tiny item, say cigerettes or autoinjectors.
Can be balance issue.
:cl:
expansion: Marine ballistic goggles are now tiny, letting you fit goggle and another tiny object in helmet
balance: Marine ballistic goggles are now tiny, letting you fit goggle and another tiny object in helmet
/:cl:

Marine ballistic goggles are now tiny, letting you fit goggles and another object

---

code/__HELPERS/icons.dm
code/datums/components/attachment_handler.dm
code/game/objects/items.dm
code/game/objects/items/jetpack.dm
code/modules/clothing/clothing.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/modular_armor/modular.dm
code/modules/clothing/suits/marine_armor.dm
code/modules/mob/living/carbon/human/update_icons.dm

This adds the possibility of using bigger icons for any worn or inhand item without them being limited to the leftmost pixel of the tile and autocenters, also adds a offset that can be applied on both worn and inhand icons for stuff that doens't need to be bigger but needs to be more distant from the mob sprite.
Example:
We can have bigger stuff now!!!11!1!!!
:cl:
code: changed human item rendering code so it can support bigger icons with centralization.
/:cl:

Support for bigger worn and inhand icons and change some images to mutable appearances

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
code/game/area/icecolony.dm

Changes Ice Colony LZ1 to not be perma unpowered, removes a duplicate APC, changes Ice Colony LZ2 to have an APC and be powerable.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/10508
People have been asking for this for a bit, I promised Zack that I would fix LZ1 today, and I have.
:cl:
balance: Ice Colony LZ2 now has an APC.
fix: Ice Colony LZ1 now can be powered like any other LZ.
fix: Removed a duplicate APC from Ice Colony LZ1.
/:cl:

Fixes Ice Colony LZ1, adds APC to LZ2

---

code/game/objects/machinery/vending/marine_vending.dm

Operational supplies vendor in req now has a free pinpointer.
Lack of people playing command roles for whatever reason can have a tremendous impact. This should alleviate the hit and encourage people to actively ask for aSL and lead other players should they find out there's no SLs, as well as not punish req by forcing a 20 point purchase for 1 single pinpointer over people not picking a role.
~~Should be good for two squads, but not for 3 or 4.~~ After some more thinking, I realized that if CIC is staffed to make someone aSL, it's also staffed to merge all squads into 1 if there's no SLs at all. That nobody actually brought this up on discord and had to figure it out on my own a day later only tells me nobody even plays command that often lmao.
TL;DR encouraging teamwork is good.
:cl: …

Adds a pinpointer to op vendor

---

code/datums/components/harvester.dm
code/game/objects/machinery/autodoc.dm
code/modules/mob/living/carbon/human/human_damage.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/living_health_procs.dm
code/modules/reagents/reagents/medical.dm

Adds a robo_repair arg to human's heal_limb_damage and heal_overall_damage to enable use of these procs to heal robot limbs.
Removes human's getexternalBruteLoss since internal brute damage got removed.
Fixes #10423 , enables options for future.
:cl:
code: Added routing to enable robot healing on two function calls.
/:cl:

Adds routing for robot heals in two human procs

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

Effects by default have INDESTRUCTIBLE as part of theirs resistance flags, which prevents turf explosions (e.g. grenades) from affecting them. This removes that flag from their resistances, as they're not targettable regardless. Also adds crusher_immune and banish_immune because banish checks for indestructible or banish_immune and being able to banish portals would be wacky.
Fixes #10532 
Fix man good.
:cl:
fix: All explosions should now affect wraith portals, not just CAS GAU ones.
/:cl:

Fixes wraith portals being unaffected by most explosions

---

code/modules/mob/living/carbon/carbon_helpers.dm
code/modules/reagents/reagents/medical.dm

1 cloneloss per 3 organ damage. A bruised organ will be about as much as an old shot, a broken one will be more. Zero cloneloss if you don't have organ damage, of course.
On-field repair cost should scale with damage. Off field, you aren't using peri+.
:cl:
balance: Peridaxon Plus cloneloss scales with the organ damage it heals
/:cl:

Peri+ clone loss scales with organ damage healed

---

code/modules/mob/living/living.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/living_health_procs.dm
code/modules/organs/organ_internal.dm
code/modules/reagents/reagents/medical.dm

Right now dylovene has the drawback of dealing stamina damage (and thus stopping stam regen entirely) above 10u. This changes that to a 50% regen reduction that activates at any volume.
Changes stamina regen multiplier to be dynamically calculated from a modifier list, similar to movespeed. Can't go below zero for now.
Removes the necessity to use a split dose for a basic healing chem in order to avoid drawbacks. You'll still want to mix it with other tox chems if you want a higher heal rate.
:cl:
balance: Dylovene reduces stamina regen by half instead of preventing it entirely, but does so at any volume.
/:cl:

Dylovene reduces stamina regen with any volume

---

code/game/objects/items/reagent_containers/hypospray.dm
code/game/objects/items/reagent_containers/pill.dm

Pills weren't doing it at all, hypos were reacting with the proper amount.
Basically zero gameside changes, almost no reagents have reaction_mob implemented and any that do don't belong in pills.
Code cleanup. Might allow future differentiation between pills and injectors.
:cl:
code: Pills and hypos call a proc they were missing. No gameplay change.
/:cl:

Pills and hypos call reaction_mob properly

---

code/__DEFINES/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
code/modules/reagents/reagents/toxin.dm

Makes all xeno toxins actually work in the defiler abilities, as intended, and as in ability description. 
Improves code as well.
- Sanguinal is also counted as xeno tox, even though you are unlikely to get the synergy.
- Transvitox accounts for ozy as well.
- Sanguinal has its effects **unchanged** in PR, as if ozy was not a thing.
Fix good. Code improve good.
:cl:
fix: Fixed defiler toxins sometimes not counting in synergies
refactor: Refactored xeno toxins code
/:cl:

Defiler fixes

---

_maps/shuttles/tgs_bigbury.dmm
_maps/shuttles/tgs_canterbury.dmm

Title.
Apparently you can't get Lemoline without grinders, which Cant and Bigbury currently don't have.
:cl:
balance: The Canterbury and its larger cousin now have reagent grinders.
/:cl:

Adds reagent grinders to Canterbury and Bigbury

---

code/modules/reqs/supplypacks.dm

Title.
When Bravemole merged my PR making autominer cost 5 points, both of us never knew the existence of an autominer that cost 15 points. Such autominer was made by MJP in #7125, and Spooky approved. It was a forgotten piece of code that ought to be removed.
:cl:
del: Removed more expensive autominer
/:cl:

Remove 15 req point autominer from req

---

code/game/objects/items/reagent_containers/reagent_container.dm
code/game/objects/machinery/vending/vending.dm

The frame from #7814 , but purely as an option. No gameplay changes, the var enabling it isn't active on anything.
Lets rarer chems be available in vendors in a limited amount, rather than forcing them to either be absent or infinite.
:cl:
code: Reagent containers can be set to not allow restocking after use.
/:cl:

Adds code to enable preventing reagent container refills

---

code/__DEFINES/status_effects.dm
code/datums/status_effects/debuffs.dm
code/modules/mob/living/status_procs.dm
code/modules/organs/organ_internal.dm

Kidneys are a little more aggressive in counting: they'll include any medicines that got added since the last life tick, but not any that've been removed.
This catches any chems that were added with a volume below their metabolism rate, since otherwise you can microdose infinite chems without care.
Also fixes an issue where confuse status effects weren't properly being created with a duration, leaving them to do nothing forever.
Bugfix, remove a way to ignore organ drawbacks.
:cl:
fix: Kidneys count microdosed chems against their limit
fix: Confuse effects won't be created with infinite duration and zero function.
/:cl:

Kidneys catch microdoses, confuse fix

---

code/game/objects/items/marine_gear.dm

Click thing with compass, get coordinates. It does work through cameras, which isn't strictly intended, but that seems alright.
Saves basic math trying to get a location nearby. Potentially enables squad officer nonsense?
:cl:
add: Clicking on stuff when you're carrying a compass will tell you that stuff's coordinates.
/:cl:

Compasses can get target coordinates

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
code/modules/projectiles/projectile.dm

Adds a `loc_override` arg to `fire_at()` which gets around the only reason the `shooter` needed to change in the first place to teleport projectiles.
Unbuckles any humans before crossing.
Fixes #10494
Fixes #10495
Fixes #10510
:cl:
fix: Fixed wraith portal changing projectile's shooter and breaking things like boiler glob size, and teleporting buckled humans.
/:cl:

Fix some wraith portal issues

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm

Fixes disguise using plasma while standing still
Fixes hunter not regening plasma on weeds while standing still.
Fixes #10578 
:cl:
fix: If you stand still as a disguised hunter, you won't use any plasma.
fix: Hunters with stealth active get half plasma regen while still and zero while moving, instead of the opposite.
/:cl:

Hunter stealth plasma fixes

---

code/modules/projectiles/guns/shotguns.dm

I almost ded, pls nerf.
Previous nerf to akimbo scatter for the combat shotgun isn't sufficient, due to the rate of fire allowing for almost perma slow to be applied. Increases akimbo additional delay to 0.9 from 0.5. In practice this may not actually make enough of a difference, but I don't want to sledgehammer it.
Akimbo shotgun is gross, previous minor nerf was insufficient.
:cl:
balance: SH39 akimbo additional delay changed to 0.9 from 0.5.
/:cl:

Combat shotgun akimbo tweak - again

---

code/modules/projectiles/ammo_datums.dm

Some changes to the staggerstun proc used by projectiles.
**Fixes staggerstun max range**
Staggerstun now respects the max_range var.
Currently due to reasons lost to time and/or shitcode, the max range for projectile staggerstun is ONLY checked if the staggerstun also causes screenshake. (It also wouldn't apply if it caused shake + the target was lying down... fuck knows why, stunlock checks exist later in the proc)
For example, this meant you could knockback and slow a xeno from 10+ tiles away with incendiary slugs, but not with normal slugs (which do cause shake), despite both having a max range of 5.
**Refactors**
Minor refactor to how the proc applies the hard_size_threshold and queen stagger immunity... it was extremely specific for some reason.
:cl:
fix: Fixed projectile …

Staggerstun bug fix and cleanup

---

code/modules/mob/living/carbon/human/life/handle_status_effects.dm

As QV pointed out, currently orders just apply to all humans in range... even hostile ones.
Makes it so that orders only apply to those within your own faction. So you won't buff SOM by accident, but also can't buff free lancers for example.
If people like being able to order friendly factions, maybe someone can code that in the future, but currently factions are only designated friendly/neutral/hostile, but this is fixed, and not relative to other specific factions.
HvH will be a bit silly when you're buffing your enemies.
:cl:
fix: Orders no longer apply to humans in factions other than your own
/:cl:

You can no longer give orders to other factions

---

code/modules/projectiles/magazines/energy.dm

Currently you can only tactical reload a culverin by dragging the powerpack to the gun (which is kinda funny since if you get brain damage now, you can no longer operate it).
The same also applies to the caliver if used with a powerpack of course.
Added attackby code to the culverin so you can now normal reload it (click on the powerpack with the gun).
I also moved cell charging from click drag to power pack to just clicking the powerpack with the cell.
Braindamaged ungas should be able to use their guns
bugfix good
:cl:
fix: Volkite culverins and calivers can now be normally reloaded by clicking the powerpack with the gun, instead of only being tac reloadable
add: Volkite powerpacks now recharge cells by clicking the powerpack with the cell instead of click dragging
/:cl:

Volkite powerpack fix

---

code/modules/organs/limbs.dm

Being able to hear your splint break is a super useful addition to the game, but currently the sound has a theoretical max range of 100 tiles, which effectively means you'll hear everyone's splints breaking which is uh, not ideal since you can't tell if it's yours or not.
Makes the sound effect have a range of 1, so you'll only hear other people's splints break if you're right next to them (So xenos still get to hear that juicy pop when they melee someone's splints off).
Hearing everyones splints breaking across the map is funny but not useful.
:cl:
fix: Splint break sounds no longer carry over large distances
/:cl:

Splint break sound range limit

---

code/game/objects/items/explosives/plastique.dm

The previous supplier of C4 has been given the boot due to their excessively smokey explosions.
C4 now has a 1 tile smoke cloud on detonation, and only very a very short duration.
Currently it lasts for a very long time, making it impossible to use with any sort of aggression, as you'd have to push through the smoke blind or wait forever for it to clear.
Makes C4 a tiny bit more useful, mainly for HvH
:cl:
balance: C4 causes less smoke for a much shorter duration on detonation
/:cl:

C4 smoke reduction

---

code/game/objects/items/tools/maintenance_tools.dm
code/game/objects/machinery/doors/airlock_types.dm
code/game/objects/machinery/doors/multi_tile.dm

refactors this yandere dev style istype and else if chain
less spagehetti
:cl: Stan_Albatross
refactor: refactored the application and removal of welding torch overlays so that they do not use istype() procs excessively
/:cl:

refactor of welding overlay code

---

code/modules/lighting/lighting_mask/lighting_mask.dm

Light masks were made hidden because??? Now they are not hidden. Mortar flare shells and mech lights worked during testing. Wraith portal seems fine during testing as well.
So mortar flares can be useful again.
:cl:
fix: Make hybrid lights visible again
/:cl:

Make light masks visible again

---

code/__DEFINES/objects.dm
code/game/objects/structures/razorwire.dm

Untangle via resist no longer applies a "big slowdown" making pixel hunt slashing the wire only better for destroying the wire faster and not a requirement for survival.
Crusher Time To Kill has been on a steady decline ever since razorburn got buffed to be full health and with each new sunder hose (mini-SG) and accuracy change (no miss on big mobs) introduced.
:cl:
balance: Untangle from razorwire via resist no longer applies a slowdown.
/:cl:

Remove untangle's 10 slowdown

---

code/modules/clothing/modular_armor/attachments/modules.dm

It could activate without properly activating and get stuck in a mixed state.
fixes #10615 
:cl:
fix: You won't get sent to zoom hell for zooming while you zoom.
/:cl:

Fixes bino module desyncing

---

code/__DEFINES/is_helpers.dm
code/__DEFINES/vending.dm
code/game/objects/machinery/vending/marine_vending.dm
code/game/objects/machinery/vending/vending.dm
tgmc.dme
tgui/packages/tgui/interfaces/Vending.tsx

This PR changes the restocking behavior of the vending machines somewhat.
Firstly, added a button that sucks up all items on the same tile as the vending machine back into the vendor:
I intend this to be for people who want to clean up after themselves when filling ammo boxes. Latejoins no longer have to pixelhunt/ alt-click around the 30 stacked mags left on the vendor so they can make their own ammo boxes in peace now.
Vending machine cleans itself up 2.5 minutes after the last vended item.
Secondly, replaced the reject messages as to why you can't restock an item with shorter balloon alerts.
Thirdly, loosened up some of the restrictions on restocking things, especially in correlation with infinite items.
You no longer need to refill a magazine, charge a cell or refill reagent bottles …

Vending restock changes

---

code/modules/mob/living/carbon/xenomorph/castes/spitter/spitter.dm

Code was adjusted for when spitter had 48x48 sprites, not 2x2 sprites. This changes that.
:cl:
fix: Fix off-set of spitter sprites
/:cl:

Fix off-set of spitter sprites

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/magazines/energy.dm

Some further tweaks to volkite weaponry, mainly aimmed at making them a bit less oppressive at longer range.
- Volkite projectiles are less accurate (5 bonus accuracy instead of 15 like lasers)
- Volkite projectiles do less deflagrate damage (25% less for the charger, 20% less for the others)
- Increased the damage falloff on the Serpenta, Caliver and Culverin (as well as less damage at range, this also reduces the chance of deflagrate triggering).
- Reduced the caliver magazine capacity to 40 shots from 50 (backpack is unchanged)
- Reduced the accurate range of the Caliver and Culverin
:cl:
balance: Slightly reduced the accuracy of volkite projectiles, and decreased the damage of deflagration
balance: Volkite weapons have higher damage falloff
balance: Reduced the accurate range of the …

More volkite tweaks

---

code/__DEFINES/dcs/signals.dm
code/datums/actions/order_action.dm
code/datums/keybinding/human.dm
code/game/objects/machinery/overwatch.dm
code/modules/screen_alert/command_alert.dm

Title. Pretty simple, and thank god we have quality code to add these things easily.
Just QoL stuff.
Some gamer leadership want to not click on action button on UI so that they can be a high speed leader buffing and rallying marines as fast as the speed of caffine induced mania that is TGMC. This continues the marine design philosophy of leaving mouse cursor for SHOOTING XENOMORPHS & getting stuff from inventory and keyboard for everything else.
:cl:
qol: Keybind for Move, Focus, Hold, Send, and Rally Order
/:cl:

Keybind for Move, Focus, Hold, Send, and Rally Order

---

code/datums/gamemodes/crash.dm

Overwrites the job larva worth proc so that dead marines will not reduce total number of xenos to spawn.
Also 1 minut interval between larval checks
Its tad difficult to test this properly, it does compile atleast. Could this be TM'ed atleast once to see if it works properly?
This avoids annoying situation on crash where a few marines die killing xenos, reducing the xeno pop to a point they cannot really fight them(1 of any cast cannot solo all the marines behind cades)
The latter change because same one pinged me about it
:cl:
balance: Dead marines will not cap the xeno pop for crash
balance: Xeno larva check will proc every 1 minut instead of 2 minuts for crash
/:cl:

Dead marines do not reduce number of xenos for crash

---

code/game/objects/machinery/vending/marine_vending.dm

This Pull request add normal smoke grenades that produces thick smoke that hides terrain, xenos and marines.
They definitely have some uses because they allow to hide objects such as other grenades, tarps, mines, dropped guns. 
:cl:
add: Adds back good old smoke grenades
/:cl:

Adds normal smoke grenades

---

code/modules/mob/dead/observer/observer.dm

found a long chain of else-if's that could be turned into a switch so i did that
heres part of the old code before i switch'd it up
and heres afterwards i switch'd it up
Makes code look less weird and more efficient, helps if you have a bunch of ghosts using this in a long high-pop round.
:cl: Vondiech
code: turned long chain of else-if's in /mob/dead/observer/Topic(href, href_list) into a switch
/:cl:

Turns lengthy else-if chain in /mob/dead/observer/Topic(href, href_list) into a switch

---

code/datums/components/largeobjecttransparency.dm

Was wondering why my skinny street lamp was taking up 3 tiles worth of clicking space. Turns out when the transparency wears off, the mouse opacity becomes "opaque", which means any sprite will take up the entire tiles of space it occupies when you hover over the tiles with your cursor. Nothing in the game currently uses the large object transparency component except trees but this one line change will make trees and any future large objects work correctly.
Fixes large objects with transparency. If you had trouble with trees, not anymore.
:cl:
fix: Large object transparency no longer makes all tiles a multitile object occupies the only thing clickable.
/:cl:

Fix large object transparency opacity issue

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10658
:cl:
fix: Fix wraith unable to time shift self again after entering and existing crit whilst under the effect of time shift
/:cl:

Fix wraith unable to time shift self again after entering and existing crit whilst under the effect of time shift

---

code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
code/modules/mob/living/carbon/xenomorph/update_icons.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9734
:cl:
fix: Fix disguised hunter still having wound overlay
/:cl:

Fix disguised hunter still having wound overlay

---

code/game/objects/structures/xeno.dm
code/modules/mob/living/carbon/xenomorph/egg.dm

Cleans up a few parts of xeno eggs.
Removes all obj/alien registering to atom_entered, since it was only used by multitile tanks and didn't apply to most of the things that inherit from obj/alien anyway. Also it was runtiming when eggs set up detection.
Eggs more properly break in response to damage, exploding instead of just hatching.
Gas eggs break a lot easier.
fixes #10712 
:cl:
fix: Eggs work a little more the way they ought. Flaming them won't make the hugger hatch, for instance.
/:cl:

More egg cleanup

---

code/modules/reqs/supplypacks.dm

Increases the lemoline provided in the orderable crate, from 10u to 30u
Increased price of lemoline crate from 5 points to 8.
The ability to acquire larval jelly is largely dependent on the existence of carriers. From my experience playing xeno in the course of the past two months, it is not uncommon to play entire rounds, and not have a single carrier, at any point. Larval jelly is currently the only means of acquiring more reasonable amounts of lemoline. This aims to help alleviate that.
Now that a large number of chemicals are gatekept by lemoline, it should only be natural that the ability to acquire it should be less limited, and also less dependent on Xeno caste choices.
Also capture gameplay is dead.
I tried buffing carriers in a previous PR to fix this issue. I'm now doing a more …

Lemoline Crate Buff

---

code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm

Increasing  sunder recovery during Gorger drain ability on dead bodies by five times
Srry for bad English :3
The initial 0.5 adjust during the drain ability is absolutely useless.
Gorger recovers his health very quickly (but not sunder) and he is quickly ready to fight again, because of this, sunder does not have time to recover at least partially. How much sunder will be restored depends on the duration of drain ability. So, at low hp, 
sunder is restored by ~10% by long drain . This is a very small percentage that is destroyed in the next battle. And it turns out that Gorger plays the whole round with ~0-15% of his already small armor against bullets and bombs.
PR increases sunder's recovery to about ~25% at long drain, which allows Gorger to restore his armor. 
:cl:
balance: Increasing …

Increasing sunder recovery during Gorger drain ability

---

code/modules/shuttle/cas_plane.dm

You cannot resist out of the condor in Reserved Z Levels so you dont kill yourself
Setting forced to TRUE still ejects in reserved space
Fixes #10729
Killing yourself and getting deleted in addition is bad, also a bug
:cl:
fix: You can no longer get out of the condor while it is flying so you dont kill yourself
/:cl:

Fix getting out of the Condor in Reserved Z

---

code/modules/mob/living/carbon/human/species.dm

Synthetics can no longer have hair.
Hair is an expensive thing, and a military synth probably shouldn't have neon colored hair, and I believe would enhance the roles authenticity towards being towards being a better defined and shown role ingame.
:cl:
tweak: For lore purposes, synths can no longer have lore.
/:cl:

Synths no longer can have hair

---

code/datums/components/chem_booster.dm

Changes the wording in multiple balloon messages, for example replacing "resource" with "green blood" since that's what the suit description says.
Oh, I also removed a redundant check for the volume amount since the checks happen on the same frame regardless of whether or not it's at the end of the checks or at the beginning. (Perhaps someone forgot to remove it?)
The pull request was, at first, aimed to fix a bug regarding the degeneration overlay, but somehow a person had fixed it in the time span of me discovering the bug a day earlier and then trying to fix it like, yesterday. So uh, yeah, the change I THOUGHT had fixed it has been reverted. (Tested in-game on dream daemon, bug was still gone even after moving it back.)
Having better wording on messages is good for obvious reasons and …

Vali Tweaks

---

code/modules/mob/living/carbon/xenomorph/update_icons.dm
code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/9351
:cl:
fix: Fix xeno fire overlay not changing dir when the xeno is turning
/:cl:

Fix xeno fire overlay not changing dir when the xeno is turning

---

code/datums/gamemodes/combat_patrol.dm

Two minor stat fixes.
Survival rate shows correctly when no revives were performed
SOM correctly show their overall accuracy stat.
Stat work gud
:cl:
fix: Fix some Combat Patrol end of round stats
/:cl:

End of round stat fix for Combat Patrol

---

code/datums/wires/_wires.dm

Have you ever hacked a door, a vendor or even something weird like a radio and seen that little 'Attach' button in the wiring menu?
Yeah, putting stuff on it hasn't worked for about a year or two. I've been meaning to squash this bug for a while.
Fixes good. This is a really really really cool feature.
Could create balance issues with possible traps, but if the door is powered enough for these assemblies to work, it'd take 5+ seconds for a xeno to slowwwly pry open when it's closed anyway. Shuttertraps are still far superior and AI can no longer close doors behind xenos groundside
:cl:
fix: Attaching stuff like signalers, voice sensors and the like to wires will now actually pulse them instead of runtiming
balance: Possible engi heaven
/:cl:

Assemblies now pulse wires they're attached to again

---

code/game/objects/items/radio/detpack.dm

Detpacks now check for the Z level of whoever's hand they're in, instead of only their own Z level. This broke detpacks because, when an object is on a person or inside of a storage unit, the object's z level is always set to 0. This caused issues with https://github.com/tgstation/TerraGov-Marine-Corps/pull/10703
Fixes good, I like using my funny detpacks :)
:cl:
fix: Detpacks now work when a signaler is in your hand again, instead of only working on the floor
/:cl:

Fixes detpacks

---

code/datums/actions/order_action.dm
code/modules/mob/living/carbon/human/human.dm

https://github.com/tgstation/TerraGov-Marine-Corps/pull/10648 completely broke CIC markers. Going into overwatch just creates two sets of the personal marker abilities now. This separates the overwatch markers and personal markers so that CIC can actually use their overwatch markers (without removing the personal markers). Elsa is busy with real life stuff so I'm making this PR because grr let me use the epic MARKERS.
I think some other stuff might have broken in CIC markers, so please make an issue report for anything you notice, but for now making them actually functional is priority.
Fixes good, this was completely unintentional & markers are actually pretty useful for CIC
:cl:
fix: Overwatch markers now work again
/:cl:

CIC markers now work as they used to (fix)

---

code/modules/reqs/supplypacks.dm

When you order tactical binocs, you now get one key for CAS radio.
There is pretty much no way for a regular marine to get access to fire support channels if they didn't grab the mortar crate at round start. This PR changes that. 
:cl:
add: Added one CAS radio key to the tactical binoculars crate. 
/:cl:

Add CAS radio key to the tactical binocs crate.

---

code/modules/surgery/surgery.dm

Radial limb selection only runs once when trying to do surgery instead of once for every possible surgery step available. Didn't test the last batch on radial oops.
bugfix
:cl:
fix: Radial medical will only need to choose limb once for surgery
/:cl:

Surgery single limb selection

---

code/datums/components/shield.dm
code/modules/mob/living/living_defense.dm
code/modules/projectiles/projectile.dm

Hard armor on shields had two issues: if it was more than the damage taken the shield didn't absorb anything at all, and if it wasn't then it still increased the damage the mob took.
Bullet pen didn't apply to shields at all. With this it'll increase the damage the shield itself takes (mob damage is unaffected) for absorption shields like riot and reduce block chance for binary shields like eswords. 
Bugfixes
:cl:
add: High-pen bullets deal more damage to shields
fix: Shield hard armor reduces damage instead of increasing it
/:cl:

Shield hard armor works, bullet pen applies

---

code/game/objects/structures/teleporter.dm

The bluespace teleporter's description now tells you how to remove the cell.
If you're trying to remove the Squad Engineer's bluespace teleporter's power cell to put it in a recharger, there's no indicator on how to do so. So, I put it in the description.
:cl:
fix: The bluespace teleporter's description now tells you how to remove the cell.
/:cl:

Teleporter kit's description tells you how to remove the power cell

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/Sulaco.dmm

title
Let roomba do its job. The r windows in prep block roomba since its AI is not that good.
:cl:
del: remove reinforced windows in prep to free roomba
/:cl:

remove r windows in prep to free roomba

---

_maps/shuttles/supply.dmm

Adds retractable railing to the Elevator to prevent crates getting spaced in transit
Crates getting spaced is very bad for the RO and whoever wants contents of said crates
:cl:
add: Added another set of railing to the ASRS so crates dont get spaced
/:cl:

Add yet another set of railing to the ASRS Elevator to prevent crate spacing

---

code/controllers/subsystem/modularmapping.dm
code/datums/gamemodes/combat_patrol.dm

Fixes #10659  
Fixes light levels not being correctly assigned to modular map areas in Combat Patrol and Civil War.
Also fixes a few related bugs, such as these areas not being available to jump to for ghosts/admins, or for admin supply pods etc.
Modular map areas were being added to the game after a proc had run to add all areas in the world to a list of areas. Now that proc runs against after modular map inserts are loaded.
Maybe I should have had this as a separate PR, but I forgot to make a new PR when making the bug fix above, oh well.
Also increases the light levels of deep caves in Combat Patrol to 50 from 25. It'll still be dark, but it shouldn't be this aylmao squintfest.
Seeing is good.
Modular map areas being in the list of areas is very good.
Bugfixes doubleplus good.
:cl: …

Lighting and bugfix

---

code/game/objects/items/storage/belt.dm

Fixes #10786 
Qwerty did a funny and copy pasted the loaded belt code twice when adding smart pistol.
Bug fix good.
:cl:
fix: fixed SO's spawning with belts loaded twice
/:cl:

Fix SO belts being double loaded

---

code/__DEFINES/dcs/signals.dm
code/datums/actions/order_action.dm
code/datums/keybinding/human.dm

Title
Let the most robust SL or FC have keybinds to coordinate marines
:cl:
add: Keybinds for Attack, Defend, and Retreat orders
qol: easier to coordinate as FC or SL
/:cl:

Keybinds for Attack, Defend, and Retreat orders

---

code/controllers/subsystem/vote.dm

I have no idea how this wasn't picked up, I think some shitcode meant this issue wasn't always actually triggering...
Fixed voting so you can't vote shipmap if the upcoming round is combat patrol.
Fucking vote codesdfshdfisdhf
:cl:
fix: Voting a different shipmap during Combat Patrol is correctly disabled
/:cl:

Fix Combat Patrol groundmap votes

---

code/modules/projectiles/gun_system.dm

Fixes #10765 
Some guns were getting cycled on spawn when they shouldn't be, namely anything that takes handfuls but doesn't open.
Bugfix good.
:cl:
fix: Certain guns will no longer spawn with a missing round
/:cl:

Fix some guns spawning with a missing round

---

code/datums/looping_sounds/_looping_sound.dm
code/datums/looping_sounds/machinery_sounds.dm
code/game/objects/structures/patrol_points.dm

Reduces volume and/or increases falloff rate for combat base radio chatter, and rappel/hovering tad sounds.
They were really loud, with low falloff, so they stayed very loud even at a very high distance.
Also cleaned up/added autodoc to a couple of vars for looping sounds.
Less ear damaging
:cl:
qol: Made radio chatter and rappeling quieter in Combat Patrol
/:cl:

Combat Patrol sound tweaks

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

It started with a little fix for those markings, and then I realized that some things just didn't make sense area wise, so i fixed them. I also added more firelocks, so those are consistent, fire alarms in rooms missing them, and most importantly, turned a bunch of them around, so they look niiiiice. Symmetrically is cool. 
Fixes are good. 
:cl:
fix: fixed more weird ground markings, lights, cameras & firelocks.
/:cl:

Fix some more markings, lights, cameras and areas on POS

---

code/modules/mob/living/silicon/ai/say.dm

This PR changes the AI voice from a cooldown of 60 seconds to 40 seconds. (Assuming no lag)
The AI voice is nice, but it is not as good as announcement.
Making it slightly more frequent could help it to be leaned on more by AI players as a command tool.
:cl:
balance: Lowered vox cooldown from 60s to 40s
/:cl:

Slightly reduce vox cooldown for the AI

---

code/game/objects/items/binoculars.dm
code/game/objects/machinery/mortar.dm

The binocs argument is used nowhere, so lets toss it.
Please merge this before #10834 or it will break it. 
No useless arguments = better codebase health
:cl:
code: removed an useless argument in mortar/binocs code
/:cl:

Remove an useless argument in a mortar/binocs proc 

---

code/modules/projectiles/mounted.dm
code/modules/projectiles/sentries.dm

Sets the layer of deployable weapons (mainly turrets) to 4.2 instead of 4.1.
This fixes them in certain instances being under objects like cades, making them invisible.
Invis turret bad.
:cl:
fix: It is no longer possible to hide turrets under barricades
/:cl:

Fixes deployed gun layer

---

code/game/objects/effects/misc.dm

What it says on the tin. Crash fog, forcefields (but not 'normal' decorative fog) can no longer be fired through.
Bug fix good
:cl:
fix: fixed projectiles going through fog
/:cl:

Fix projectiles being able to bypass fog

---

code/modules/mob/living/status_procs.dm

Title. Currently, it only prevents adding stagger if the thing being hit is already staggered due to the check checking the wrong thing. Now it properly prevents stagger from being increased.
Note: Stagger already present still affects the target and has to be set to 0 seperately, which appears to be intentional given the only use case able to be used while staggered (Rav Endure) manually sets it.
Fix man good.
:cl:
fix: The stagger immunity trait should now work properly.
/:cl:

Fixes the stagger immunity trait

---

code/controllers/subsystem/vote.dm

Turns out I was checking current mode via master_mode when I should have been checking the next mode via the txt file.
You will now actually be able to select a shipmap when voting out of Combat Patrol.
Bug fix good
:cl:
fix: fixed a vote bug when changing gamemode from Combat Patrol
/:cl:

Vote fix: For real edition

---

code/__DEFINES/dcs/signals.dm
code/datums/keybinding/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm

Instead of Hunter Mirage and Swap being two different abilities, Swap is triggered by reactivating Mirage while illusions are active.
Simplifies the control scheme for this caste. Since the two abilities can only ever be used one after the other, they can be on the same hotkey instead of having two separate hotkeys.
:cl:
qol: Hunter's Swap is no longer activated with a separate ability, reactivate Mirage to trigger it.
/:cl:

Hunter Swap control simplification

---

code/modules/mob/living/carbon/human/species.dm

Fixes #10843 and is actually good
bugs bad!
:cl: 
fix: TGMC's Diversity-IT joint team has fixed something: Combat robots who are non-binary or do not care about genders can now scream and shout inspirational cries AND BE HEARD!
/:cl:

It just works - fixes non-binary and object robots not being able to scream or warcry

---

code/_onclick/ai.dm

Clicking Ctrl click on a turf you can see will now print the coordinates in your chat. 
I'd have liked to have it copy into your clipboard, but I'm not sure byond can do that. 
This would allow the AI to more easily provide drop pod coordinates, and targeting information for artillery pieces. 
I think this is a buff for the role, but nothing you couldn't do with a (working) webmap before. 
:cl:
add: Gave the AI the ability to Ctrl-click turfs to get their coordinates. 
/:cl:

Allows the AI to grab coordinates with ctrl click

---

code/modules/mob/living/carbon/human/life/handle_organs.dm

Currently, having a broken leg does precisely fuck all.
You cannot fall over unless you have 2 broken limbs (including legs and feet) or more, while having one shatter leg is totally fine.
Changes this so having a single broken leg/foot can cause the stun. The calculation for probability is unchanged, the more broken bones you have the more likely you are to fall over, it just couldn't happen at all with one (so having 2 broken legs will have the same probability as previously).
Also reduced the stun time from a meaty 3 seconds to 1 second, since you're just falling over, and a hard stun is a really big debuff (and is far more likely to actually occur in game now).
Running on a broken leg has actual consequences
Falling over is no longer a death sentence
:cl:
balance: Having a single …

Leg breaks adjustment

---

code/modules/projectiles/guns/shotguns.dm

This PR re-adds the requirement to start wielding the SH39 before being able to fire it.
It was removed as apart of [https://github.com/tgstation/TerraGov-Marine-Corps/pull/7142](7142)
Currently one handing the SH39 allows you to juggle up to three shotguns effectively. More so when combined with a shield.
This change is to mitigate some of the oppressiveness of three SH39 being rapid-fire on xenos.
:cl:
add: You are required to start wielding the SH39 before being able to fire it again.
/:cl:

Two Handing added to SH39

---

code/modules/projectiles/gun_system.dm
code/modules/projectiles/projectile.dm

Some minor tweaks to how accuracy and hits are calculated.
Moved the pain and focus order checks to when the bullet is fired instead of at hit. Because this was previously checked only when hitting mobs, this PR means pain and focus orders now actually impact your ability to shoot past cover.
Pain now correctly uses shock_stage instead of traumatic_shock.
Objects being unanchored no longer reduces their coverage by half.
Tweaked the order different affects are calculated when checking to hit. You're unlikely to notice much difference in game other than large xenos won't be so easily hit way off screen anymore.
Improve and clean up accuracy/hit code slightly, certain buffs and maluses working better is good.
bug fix good.
:cl:
code: Some tweaks to projectile accuracy and hit code
/:cl:

Accuracy system tweaks

---

code/game/objects/structures/crates_lockers/largecrate.dm
code/modules/hydroponics/hydro_tray.dm
code/modules/mining/satchel_ore_boxdm.dm
code/modules/paperwork/filingcabinet.dm

Adds soft armour for bullet, laser and energy to certain objects and structures.
A previous PR heavily reduced the HP of these objects and structures, to make it easier for xenos to clear junk out.
This was a sensible QOL change, but in HvH guns simply output far more dps, so these structures are functionally useless for cover, which isn't ideal.
This PR means they are still easily destroyed by melee or acid, but are a bit more survivable when shot by guns
Also slightly increases the coverage for hydrotrays, since I made them lower back when they had a load of HP.
Cover not disintegrating after 2 bullets is good.
:cl:
balance: Increased the durability of some map objects and structures against guns
balance: Hydro trays provide slightly better cover
/:cl:

Increases the survivability of certain objects and structures

---

_maps/map_files/LV624/LV624.dmm
_maps/modularmaps/big_red/bigredlzvar2.dmm
_maps/modularmaps/big_red/bigredlzvar3.dmm
_maps/modularmaps/big_red/bigredlzvar8.dmm

https://user-images.githubusercontent.com/6610922/188245762-5a45593e-3935-4e26-9dc3-84e3c4e8ea38.mp4
https://user-images.githubusercontent.com/6610922/188245766-8caf2500-d4ff-4a95-892e-15a8cdce6ec0.mp4
Anyone using the FOB drone can assure you that this single girder screws up with making FOB. I'm removing this single girder just to help with any marines.
Also, move a crate in LV624's LZ2 because said crate does the same thing.
:cl:
qol: delete a girder in Big Red LZ1 and move crate in LV624 to let marines using FOB drone not suffer
/:cl:

Remove girder in Big Red LZ1 and move crate in LV624

---

code/modules/clothing/gloves/marine_gloves.dm
code/modules/clothing/modular_armor/modular.dm
code/modules/clothing/shoes/marine_shoes.dm

Some number tweaks to make things more consistant.
**Marines**
Marine helmets now have the same armour values as heavy armour across the board. Previously they have notably lower bullet, laser, energy and acid armour.
MX11 helmets are now just 5 more armour across the board (except for melee which was already higher).
**SOM**
SOM shoes and gloves now have the same armour as marine versions, except veteran gloves which have 5 higher on bullet, laser and energy.
Some consistancy changes for SOM armour:
5 higher acid armour on medium and heavy armour (still lower than marine versions however).
5 lower bomb armour on heavy and Gorgon armour
5 lower fire armour on Gorgon armour
SOM helmets adjusted so that the standard helmet is equal armour values to **medium** armour and veteran helmets are …

Marine and SOM armour rebalancing

---

code/__DEFINES/traits.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm

Defenders that use crest-defense are now immune to staggers
Very few castes can effectively counter shotgun users , considering that defenders have the tail swipe and the ability to fortify , they should be the best caste to handle shotgun spam, especially when they receive slowdown that lets marine run away.
:cl:
balance: Defender crest-defense now provides stagger immunity while active.
/:cl:

Defender crest-defense now provides stagger immunity

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

The disposals on POS are broken in medbay, also the shutters for hangar lockdown are nonfunctional, this PR fixes them.
Bugs bad, fixes good.
:cl:
fix: The hangar lockdown in PoS now works again
fix: Medbay disposals on PoS should function properly now without spitting objects out mid-transit.
/:cl:

Fixes POS disposals and shutters

---

code/modules/mob/living/silicon/ai/say.dm

I took a look at the Bioscan code and orders code under advice, and copied it for the AI.
It now sends the VOX voice to all living humans, observers, and synths.
I tested it by putting a synth on the ground and on the ship. It heard the message. I tried it with a bean, didn't hear anything.
Currently, Vox only works ship side, which is not obvious. This basically makes it only useful at the start, and if the xenos board the ship. Now, it can be used to give advice to ground side teams. 
:cl:
expansion: Extend AI vox to all Z levels
fix: Prevent xenos from hearing Vox on shipside
/:cl:

AI vox reaches all Z levels & all humans

---

code/datums/gamemodes/game_mode.dm

- Basically the title, you couldn't respawn into EORD if you didn't have the pref for it due to only being attributed the verb if you changed mob *after* it started. This resulted in you not being able to join if you were dead and had the pref off when it begun.
- Also sanitises so we don't get duplicate verbs, just in case
Sometimes you're in the mood to go into EORG, sometimes you aren't. It's nice to have the option to join in if you feel like it. This essentially makes the pref just a "force pull me into EORG roundend" pref.
:cl:
qol: You can now respawn into EORD no matter your pref for it
/:cl:

You can now respawn into EORD no matter your pref for it

---

code/modules/mob/living/silicon/ai/ai.dm

The AI can now use command orders like squad leaders or CIC staff.
It only reaches all marines, given they do not have an assigned squad.
I've had to copy all of the code, because it features a bunch of references to /living/human, and the Ai is not that sort of thing.
More communication good.
:cl:
expansion: Gave the AI similar command orders to CIC staff
/:cl:

The AI now has access Command Orders

---

code/controllers/subsystem/persistence.dm
code/game/objects/machinery/vending/marine_vending.dm

Very simply, condenses the seasonals to that they have 4 guns each, in order to both increase player choice during a single seasonal, since they can play with four toys, and make seasonals cycle a bit faster, since you cant always play TGMC all-day every day and missing that one seasonal you like sucks. Then again, the SOM seasonals have 4 guns which gave me the idea.
Not just that, but this PR adds the SO seasonals to the Valhalla seasonal vendor, and the old V10 shotgun to the shotgun seasonal. huzzah
Just a simple change to grant more choice per seasonal and faster rotation. Descriptions changed to match the new contents.
:cl:
qol: SOM seasonals are now in the seasonal vendor
qol: seasonals condensed into 4 guns for more choice and faster rotation
add: the old V10 shotgun made his way …

Condensing seasonals

---

code/modules/projectiles/ammo_datums.dm

- Increased the soft CC (stagger/slow) of airburst, incend and cluster micro grenades. 
- Minor tweak to airburst and incend accuracy variance
- Increased the radius and damage of cluster bomblets (15 damage after armour instead of 10, wew)
I balanced micro grenades very conservatively to begin with, but this doesn't seem to be a problem, and looking at regular grenades (40-50 damage + 1.5 slow/stagger AFTER armour) it makes sense.
Normal grenade will continue to be superior at generally messing someone up, but this PR should help improve the micro grenades in their intended function of AOE crowd control.
More useful microgrenades in comparison to the vanilla attachment weapons.
:cl:
balance: Increased the stagger and slow of V-31 microgrenades slightly, and improved the damage and radius …

V-31 tweaks

---

code/modules/projectiles/guns/smgs.dm

Increases burst scatter (so only effects the higher rate of fire mode), and decreases wielded accuracy.
The V-21 has worse accuracy and scatter on fuller auto, but it was still a bit too effective, especially at longer range. It will still be extremely effective, you just won't be able to stand near the edge of the screen and still land almost everything.
Balance the bullet hose
:cl:
balance: V-21 wielded accuracy reduced slightly, and fuller auto scatter increased
/:cl:

V-21 tweak

---

code/game/objects/items/tools/mining_tools.dm

This PR reduces the damage from a whooping 100 to 75
Plasma cutters are a tool, and a very useful one at that. Their ability to deal with maze, walls and other structures is very useful and why they are carried by most people who can take one.
When used against xenomorphs, it also drains 1/5th of the target plasma per hit.
Why it has more damage than **any** other melee weapon in the game, outside of the energy axe, is byond me. 
Bringing the damage closer to the machete and spears seems more reasonable to me. Still absolutely capable of killing, but less of an outlier. 
:cl:
balance: Lowered Plasma cutter damage
/:cl:

Reduce plasma cutter to be closer to other melee

---

code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm

So for a while, wraith couldn't banish weeds/resin because the ability checked if something was an obj/effect to see if it was immune to banish. #10626 repathed a bunch of stuff out of obj/effect, which made weeds viable target. This fixes that with a check for /obj/alien.
Included in this are weeds+nodes, resin, eggs, and hivemind cores. 
Fixes burning your ability on the ground by accident.
:cl:
fix: Wraith can't banish weeds/resin
/:cl:

Wraith can't banish weeds

---

code/modules/organs/limbs.dm

Just about the same brute damage as before on all limbs, but limbs can hold more damage than before so you need 20-30 burn damage to become immune to amputations instead of any at all.
Solves tactical 1 burn damage with minimal potential for increasing burn damage potency on the whole.
:cl:
balance: You need 20-30 burn damage on a limb in order for it to be immune to getting chopped off, instead of any at all.
/:cl:

Adds a buffer between a limb's max damage and the brute required to sever

---

code/modules/projectiles/magazines/unmanned_vehicle.dm
code/modules/reqs/supplypacks.dm
code/modules/vehicles/unmanned/unmanned_droid.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm

This PR aims to make it clearer which ammo UV's use, how much they have left, and to make ordering easier.
It also changes the logic of the ammo system, so you can't try to reload a full UV anymore, or lose 149 bullets when you only reload 1. 
I also corrected 2 typos regarding the ammo magazines.
I also added some quick little descriptions about which ammo types the turrets use. It should make it easier for players to maintain things. I couldn't manage to make the system automatic, but it isn't likely to change anytime soon. 
Clarity = Good
Using roughly the same logic as any other ammo for UV's = good
:cl:
qol: Improved Droids and UV's examine to show more accurate ammo counts
qol: improved UV's crates names to make their names more useful
qol: Added caliber information to UV's, …

Improve UV ammo logic & descriptions

---

code/game/objects/items/binoculars.dm

Tac/Rangefinder binoculars can now link to multiple mortars
Using binoculars on a mortar adds or removes them from the list
Using the binoculars to set target sets target on the selected linked mortar
Alt-click changes selected mortar, Unique Action now the only way to change modes, still has a verb for it i think
Its faster than getting a target, unlinking your mortar and then linking another target, then getting yet another mortar
Still needs teamwork or really,really quick hands to pull off firing the linked mortars in a speedy manner
:cl:
add: Rangefinder/Tactical Binoculars can now link to multiple mortars
/:cl:

Make Tac/Rangefinder binoculars able to link to multiple mortars

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

The AI gets a slightly better room, which can't be cheesed by melting one wall.
Also looks a little less like a storage closet.
:cl:
qol: Swapped the AI and Synth rooms on POS
/:cl:

Swap the AI and Synth rooms on POS

---

code/controllers/configuration/entries/game_options.dm
code/modules/organs/limbs.dm

organ_health_multiplier, removed by request and since it didn't have a proper server config anyway, and organ_regeneration_multiplier since it was never used.
cleanup
:cl:
config: Removed config numbers organ_health_multiplier and organ_regeneration_multiplier
/:cl:

Removes two unused config vars

---

code/datums/gamemodes/game_mode.dm
code/datums/round_statistics.dm
code/game/objects/machinery/miner.dm

I copied points_from_research and shoved it into the mining stuff.
I did not test this, but it should be fine, right?
Stats good. 
:cl:
add: Add req points from mining to round end stats
/:cl:

Add mining to round end stats

---

code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/organs/limb_objects.dm
code/modules/organs/limbs.dm

Enables reattaching synth/robbit heads
Fixes heads turning invisible on removal
bugfix
:cl:
fix: Synth heads can be reattached
fix: Heads have their proper hair and name and aren't invisible sometimes
/:cl:

Beheading fixes

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Title.
Said APC is draining power from CIC, which is weird. Also, this unwired APC powers CIC. ghost wire
:cl:
del: Remove unused APC in synth room that drain CIC of its power
/:cl:

Remove unused and extra APC in synth room

---

code/modules/vehicles/unmanned/unmanned_vehicle.dm

Reloading didn't update the visible ammo count. Now it does.
Clearer.
:cl:
fix: fix unmanned droids not having their ammo counter update until they were fired.
/:cl:

Add an update_icon() to the UV's

---

code/modules/projectiles/magazines/flamer.dm

You can no longer refill X fuel using regular fuel tanks, for infinite X fuel.
Also if you try fill a full tank, it now says it's full, instead of saying it was refilled and making the refuel sound, because that was annoying.
Exploit bad.
:cl:
fix: X fuel tanks no longer convert ordinary fuel to X fuel
/:cl:

X fuel exploit fix

---

_maps/map_files/desertdam/desertdam.dmm

It's time for Chigusa's yearly patch.
Here's a list of what's been changed/fixed.
-platforms have now proper junctions so they don't intersect awkwardly 
-fixed blue disk generator having a duplicate
-fixed xenos being able to build literally right next to LZ1
-gave xenos some more prebuilt resin structures
-adjusted shutters so marines can more easily fortify both LZs
Fixes good, bugs bad. Maybe the extra resin will help xenos survive for 5 minutes longer.
:cl:
balance: Chigusa now has some more prebuilt resin structures on Chigusa
balance: Chigusa LZs are slightly bigger so marines can build fortifications more easily.
fix: Chigusa LZ1 now has a proper building exclusion zone again.
fix: Removed the duplicate blue disk generator in Chigusa.
/:cl:

Fixes some minor issues with chigusa

---

code/game/objects/machinery/squad_supply/supply_console.dm

Fixes the supply drop console delay message, which will now notify players that they will have a new drop available in _30_ seconds, not _300_.
Polishing.
:cl:
fix: Fixes supply drop console delay message.
/:cl:

Fixes supply drop console delay message

---

code/game/objects/machinery/vending/marine_vending.dm

Moves the V1 Thermal Dampening Tarp out of the requisitions operations vendor, and into the Marine Armaments Vendor, Specialized tab.
Hardly anyone uses the V1 Tarp. Given this, whenever someone DOES wish to use one, they have to go out of their way to ask the RO to vend one of their _ten_ free tarps from the access-locked operations vendor.
Given the lack of usage, alongside the face that the tarp isn't overpowered or anything of that sort in practice, I don't see any reason that acquiring one should require two-factor RO verification.
:cl:
qol: Moves the V1 Thermal Dampening Tarp to the Marine Armaments Vendor, Specialized tab.
/:cl:

Moves Thermal Dampening Tarp to Specialized Tab

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

The POS AI core door is now a opaque.
This stops the AI from hearing the vending machines ads. 
Ads spam bad.
:cl:
qol: Made the AI unable to hear vending ads. 
/:cl:

Replace POS AI Door with an opaque one

---

code/modules/projectiles/guns/specialist.dm
code/modules/projectiles/magazines/specialist.dm
code/modules/reqs/supplypacks.dm

The req minigun is called Vindicator MIC-A7, but it is MG-100 in the box. 
This PR merges the 2 names, giving us the MG-100 Vindicator. This will allow old RO's to find it, while preserving the new name.
I took MG-100 as the line history shows it was the latest set name. 
Consistent weapons names are good.
:cl:
qol: Rename minigun to MG-100 Vindicator, a conflation of MG 100 and MIC-A7 Vindicator 
/:cl:

Clarify the minigun names

---

code/game/objects/machinery/squad_supply/supply_beacon.dm

It makes it clearer for people to say which beacon they should send things to.
:cl:
qol: Added name & area to supply beacons
/:cl:

Add name and area to planted supply beacon

---

code/datums/jobs/job/marines.dm
code/datums/jobs/job/sonsofmars.dm

Eliminates the random hunger system from marine spawning, starting marines and SOM at full nutrition levels.
I don't believe that anyone actually likes dealing with decreased spawning nutrition. It's a hinderance for exactly 20 seconds until you can make it to the marine food vendor and eat two nutrition bars, which is already an obstruction to round-start procedure - something you'll have to do, every single round, adding nothing but tedium.
Low starting nutrition is only noticeable if you _forget_ to manage it, and potentially debilitating if you do. Personally, I don't believe that possibility adds anything positive to the gameplay experience.
:cl:
qol: Marines and SOM no longer have randomized hunger on spawn
/:cl:

Removes randomized starting nutrition for Marines/SOM

---

code/game/objects/items/explosives/mine.dm

Any mob thats dead can no longer trigger landmines
The amount of times i've seen people blow themselves trying to sell dead xenos and walking through a mind-field is unreal.
I don't see why we should keep this either , it only serves to make landmines even worse(like they aren't already quite niche and weak)
:cl:
balance: Anti-personnel landmines no longer get triggered by dead mobs
/:cl:

Anti-personnel landmines no longer trigger on dead mobs

---

code/modules/projectiles/ammo_datums.dm

Reduces the flash range of the following rockets
Default rocket subtype , from 5 to 2
recoilless rockets default subtype , from 5 to 2 
light recoiless rocket , from 5 to 1
recoilless low impact from 3 to 2
The RR launcher has been seeing no use, we have already added a lot of telegraphing whenever a marine fires a rocket , so i believe it is fair to let marines actually see the xeno they want to kill.
This makes it so getting hit by an RR  while fighting close-up marines is far more deadly, and far more of a risk.
(And actually lets marines score a kill whenever they do manage to hit a xeno)
:cl:
balance: Reduced the default rocket subtype flash range from 5 to 2
balance: Reduced RR rocket flash range from 5 to 2
balance: Reduced the LRR rocket flash range from 5 to 1
balance:Reduced the …

Reduces the flash range of rockets and RR rockets.

---

code/controllers/subsystem/persistence.dm

Per title. Reverts the addition of SoM guns to seasonals in #10810.
These guns are very much NOT balanced for normal HvX gameplay.
The SoM rifle's underbarrel attachie is overpowered when used against xenos, dealing too much damage _and_ staggering for a decent duration. The damage per bullet is likewise a bit too good.
The other guns display similar issues with damage balancing; especially the SMG, which can be dual wielded for crazy DPS up close.
:cl: Lewdcifer
del: Removed SoM seasonals.
/:cl:

Reverts the addition of SoM guns to seasonals

---

code/__DEFINES/dcs/signals.dm
code/datums/components/autofire.dm
code/modules/projectiles/gun_helpers.dm
code/modules/projectiles/gun_system.dm

Autoburst will now respect akimbo additional delay (looking at you, V-21).
Fixed a bug where the a firing gun could not trigger reset_fire() when it should in specific circumstances, leading to buggy behavior.
Bug fixes good.
:cl:
fix: Autoburst now respects akimbo extra fire delay modifiers
fix: Fixed a bug that could cause guns to retain akimbo modifiers when no longer akimbo in specific cirumstances
/:cl:

Akimbo bug fixes

---

code/modules/projectiles/ammo_datums.dm

Fixes some exploits and unintended behavior.
Smoke and cluster micronades no longer penetrate solid turfs/fog.
:cl:
fix: Cluster and smoke cluster micronades can no longer hit things past solid objects
/:cl:

Micronade fixes

---

code/game/objects/items/storage/firstaid.dm

fix: https://github.com/tgstation/TerraGov-Marine-Corps/issues/10824
:cl:
fix: Fix letter overlay on medical items bug out in storage slots
/:cl:

Fix letter overlay on medical items bug out in storage slots

---

code/modules/mob/living/silicon/ai/ai.dm

This PR gives the AI more stuff in their game tab.
Dropship points are something you might want to know, and they are basically the same as supply points.
Living marines count is quite useful. The code was stolen from the communications console. 
More tools for command to use.
:cl:
add: AI knows dropship points & number of living marines
/:cl:

AI knows dropship points & nb of live marines

---

_maps/map_files/gelida_iv/gelida_iv.dmm
code/game/objects/structures/platforms.dm
code/game/objects/structures/prop.dm

Fixes some common complaints about Gelida.
I'm going to list the changes out so people can easily read them without having to examine a map.
-Platforms are now 99% percent cosmetic and *shouldn't* block projectiles or require climbing
-A small fraction of platforms are still tangible, but the health has been reduced even further.
-Caves has been slightly expanded south.
-Caves now has even more entrances and exits due to complaints about how easy it is to bottle xenos up.
-Most windows are now regular windows instead of reinforced.
-A number of rock formations that could potentially obstruct crusher lanes have been removed.
-Some platforms have been slightly rearranged to be less obstructive.
-The vehicle roadblocks that covered a large number of routes are now slashable.
-The lockdown …

Gelida balance changes

---

code/game/objects/items/storage/boxes.dm
code/modules/projectiles/gun_system.dm

Rotating a gun like HSG or MG-08 takes right click, but it isn't clear how you do it in game.
This PR adds a little description on examine. 
Better description good.
:cl:
qol: Better description for Mounted guns. 
/:cl:

Add mounted gun rotation info

---

code/modules/mob/living/carbon/xenomorph/abilities.dm

Per title. These two stats been brought in line with resin wall stats.
Resin doors got smacked really bad between durability nerfs and building costs.
This PR aims to amend that by reducing the building costs, since the durability nerfs were already enough.
:cl: Lewdcifer
balance: Resin door build time and plasma costs reduced (same as resin walls).
/:cl:

Resin door build time and plasma costs reduced

---

code/game/objects/structures/dropship_ammo.dm
code/game/objects/structures/dropship_equipment.dm

Examining CAS ammo gives you only the description that they need a powerlifter.
On top of that, once loaded, they did not properly give a description of how full they are. Something which would really be obvious to anyone taking a close look.
This PR fixes both of those issues. The chosen solution is the same as is used for CAS guns, so this also standardizes the code a bit. 
Broken descriptions are bad. 
:cl:
fix: fixes broken CAS ammo descriptions. 
/:cl:

Correct dropship ammo description

---

code/datums/components/autofire.dm
code/modules/projectiles/gun_system.dm

Makes ALL autoburst guns respect akimbo extra delay.
So the previous PR worked, but due to the quirky way in which autoburst delays are calculated in the first place, guns that didn't have a specific autoburst delay just default to double the firerate delay - but this is done on the autofire end, not on the gun itself.
This meant altering the autofire delay was trying to multiply the value of zero.
Changed it so guns now simply set their autoburst delay to fire_delay + extra_delay (i.e. the actual delay when manual bursting) if a specific amount is not specified.
Technically this is a balance change I guess, but I mean autoburst was shit on any gun that didn't have a specific autoburst delay specified. To this day I still don't know why autoburst delay was originally THREE TIMES …

Autoburst akimbo fixes round 2

---

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm

Carrier panic drop can now only be used when at 25% of health or under.
Currently panic drop is without question the most powerful ability in the game, and is just used as an insta kill ability, not an 'oh shit' panic ability as intended.
This PR retains its potency, but means you can't be as hilariously aggressive with it.
ggnore button is bad
:cl:
balance: Carrier panic drop can only be used at 25% health or less
/:cl:

Carrier panic drop change

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Evo towers now count as a xeno for T3 and T2 slot calculations
Evo towers are made to boost evo-speed, yet xenos can never get enough larva generation to justify having these. So making them also permit more slots for T3 and T2 is more than fair , it makes them more viable at all population counts.
:cl:
balance: Evolution towers now multiply xeno count by 20% for each tower, increasing T3 and T2 slots.
/:cl:

Evolution towers now count for T3 and T2 xeno slot calculations

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm

Warrior punch will now properly go on cooldown when punching unmanned vehicles such as droids or RC's. Currently you can just infinitely punch them to insta kill them.
Also made the base proc return true, so if anyone forgets to add a punch_act it will still go onto cooldown (the check for a valid target is done before this)
Bug fix good
:cl:
fix: Warriors can no longer infinitely punch unmanned vehicles
/:cl:

Fix warrior punch exploit

---

code/modules/mob/living/living_defense.dm
code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/projectile.dm

Incendiary ammo and volkite weapons were applying fire armour to the amount of fire stacks being passed for adjust_fire_stacks(), when the proc already does this internally.
Also cleaned up the incendiary ammo code more generally, as ignite() also checks for fire immunity, so that didn't need to be done in projectile code either.
The last notable change is that you will now scream every time anything successfully ignites you, regardless of whether you're already on fire.
Currently this is inconsistant, incendiary projectiles will always trigger a scream, but walking through fire for example will only trigger it if you weren't already on fire.
This means standing in fire/running through a flaming corridor will trigger screams periodically instead of just once.
Bug fixes good
:cl:
fix: Fire …

fire stack proc fix and cleanup

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Engineering on POS has 1 APC with no wire underneath it. This PR fixes this issue. 
Fix good.
:cl:
fix: fixed a missing wire on POS
/:cl:

Fix 1 engineering APC having a missing wire

---

code/game/buckling.dm

So you don't get stuff like strapping a crit marine to a roller bed and yakkety saxing.
Xenos can still strap people in for mr bones wild ride if they're awake.
Avoid a corpsedrag bypass.
:cl:
balance: Xenos can't buckle other people to stuff if they aren't conscious.
/:cl:

Prevents xenos from buckling dead people to things

---

code/modules/projectiles/guns/smgs.dm

Muh akimbo.
This PR is dependant on #11012 
Increased akimbo penalty for the MP-19, so that the delay between bursts in 0.25 when akimbo'd. Still likely to be deadly as all fuck, but a little bit less rediculous.
:cl:
balance: Increased MP-19 akimbo penalties
/:cl:

MP-19 akimbo tweak

---

code/modules/mining/remote_fob/remote_fob_actions_misc.dm

Fixes plasteel cades not being wired by the FOB drone when it has do_wiring 
its a fix
:cl:
fix: Fixed plasteel cades not being wired by LZ drones.
/:cl:

Fixes plasteel cades not wiring with the FOB drone

---

code/modules/reqs/supplypacks.dm

Increases the shell price for Howitzer shells.
The Howie is great at holding a siege and with a steady income, makes sieges almost endless.
The value it provides far outweighs the price it can be obtained for.
Shells can still be spammed granted marines are still selling corpses or have a miner.
This just slightly slows down it's capability if marines are struggling for points.
:cl:
balance: Increased Howie HE and Incen shell prices to 4
balance: Increased Howie Tfoot and WP shell prices to 6
/:cl:

Howie Shell cost increased

---

code/_onclick/ai.dm
code/modules/mob/living/silicon/ai/ai.dm

This is a code improvement PR : 
- The AI did not unregister the shuttle takeoff signal. 
- Added and removed a couple spaces in the Ai code.
- Add middle mouse support for the AI. It is not currently used by anything, but it works. Same function as AiCtrlClick.
Code improvements are good.
:cl:
code: Clarified AI code
code: Added middle mouse click support for the AI
code: Unregistered a signal which wasn't before on the AI 
/:cl:

Add AI middle click code, clarify some AI code, unregister signal

---

code/__DEFINES/dcs/signals.dm
code/datums/keybinding/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm

This PR lets primordial hunters have disguise as well as stealth instead of primo hunter sending the stealth ability to brazil.
In addition to that, I have also made it so disguise and stealth cannot stack so we dont get funny stun/damage stacking.
I think this should be balanced?????????????????? (maybe???????)
(locally tested, should behave as intended)
i hate disguise i hate disguise I HATE DISGUISE
WHY THE FUCK DOES DISGUISE REPLACE STEALTH WHILST BOTH ARE DIFFERENT ABILITIES??? YOU DONT GO AND GIVE BOILER ACID/NEURO LANCE JUST TO TAKE HIS NORMAL GLOBS AWAY NOW DO YOU???
:cl:
add: Primo hunters get to use stealth again, but not at the same time as disguise.
qol: added seperate keybinds for disguise and stealth
/:cl:

Lets primordial hunters have stealth as well as disguise (again) but they cant be active at the same time

---

_maps/map_files/Minerva/TGS_Minerva.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/map_files/Sulaco/Sulaco.dmm
_maps/map_files/Theseus/TGS_Theseus.dmm
code/game/objects/machinery/door_control.dm
code/game/objects/machinery/doors/poddoor.dm
code/game/objects/machinery/doors/shutters.dm
code/game/objects/machinery/telecomms/computers/logbrowser.dm
code/game/objects/machinery/telecomms/computers/telemonitor.dm

This is a fat PR, because splitting changes is an horrible pain, and this took me hours.
Changes contained : 
- Telecoms rooms have 2 computers used to monitor them. They are not set to "Tcommsat" by default, which makes them useless for the layman.  This PR changes that by creating 2 subtypes and replacing all the consoles.
- Theseus Power monitors lacked cables underneath, rendering them useless. 
- Theseus telecoms room lacked cameras. 
- Some pod doors were called poddooor, which was obviously a typo.
- Fixed the POS not having working hangar shutters. The issue was that they were firelocks, and not proper shutters. 
- Fixed the POS having medical shutters, but no button to activate them. I've given the CIC and CMO a button for it. 
That was really painful.
For telecoms, it makes …

Telecom fixes & Marine ships fixes. 

---

code/modules/clothing/modular_armor/attachments/storage.dm

Engie storage for armor can now take filled sandbags
With all the other great storage modules, it was an annoying handicap not being able to carry filled sandbags in it. Grenade and injector modules are great choices, and engie module does the same thing as a webbing (which also fits empty sandbags and tools), so I feel like this is a fair compromise for what are seldom use barricades.
:cl:
balance: engineering storage module can fit filled sandbags
/:cl:

Makes engineering storage module fit filled sandbags

---

code/controllers/subsystem/aura.dm
code/game/objects/machinery/overwatch.dm
code/modules/mob/living/carbon/human/life/handle_status_effects.dm
code/modules/mob/living/carbon/xenomorph/life.dm
code/modules/mob/living/living.dm

Basically, the problem with the aura subsystem at the moment is that it "pulses" mobs on SSaura, but "finishes" cycles (clears phero received while applying effects for what pulsed it, etc.) on Life which is on SSmobs. This means that when SSaura and SSmobs get sufficiently delayed or desynced relative to eachother (high TD tends to cause this), mobs will begin to have cycles they did not receive a pulse from SSauras, leading to mobs not gaining aura effects despite being supposed to.
This addresses said issue by also moving the call of the finishing proc into SSauras, iterating through all humans and xenos to do so. It seemed like the easiest solution to achieve consistancy with only having to iterate through those mobs once per cycle and other possible options to combat the issue that I …

Refactors SSauras to be more consistant and to respect MC_CHECK_TICK

---

_maps/map_files/BigRed_v2/BigRed_v2.dmm
_maps/map_files/LV624/LV624.dmm
_maps/map_files/Vapor_Processing/Vapor_Processing.dmm
_maps/map_files/desertdam/desertdam.dmm
_maps/map_files/icy_caves/icy_caves.dmm
_maps/modularmaps/big_red/bigredsecornervar3.dmm
_maps/modularmaps/big_red/bigredsecornervar6.dmm
_maps/modularmaps/lv624/cargo_bay.dmm
code/game/objects/machinery/vending/vending_types.dm
code/game/objects/structures/crates_lockers/closets/secure/security.dm

Per title. SoM flashbangs should remain unaffected.
Thanks, Rio!
Flashbangs have no place in normal gameplay. They've only been used to grief, and with the recent addition of pulling objects (#11011), xenos can pull flashbangs into fire and force them to trigger. These things can stun for up to **20 seconds.**
:cl: Lewdcifer
del: Flashbangs no longer spawn naturally.
/:cl:

Flashbangs no longer spawn naturally

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
_maps/map_files/Research_Outpost/Research_Outpost.dmm
_maps/map_files/icy_caves/icy_caves.dmm
code/game/objects/effects/spawners/random.dm
code/modules/projectiles/guns/shotguns.dm

Replaces map spawned slugs with buckshot, and makes the tx11 and mosin scopeless.
These are problematic for HvH as they're unbalanced, and are basically decorative for HvX.
No more cheesy map spawn items, better HvH balance
:cl:
balance: Groundside will no longer have shotgun slugs or scoped weapons as part of random spawns
/:cl:

Cleans up some map spawned gear

---

code/game/objects/items/explosives/grenades/flashbang.dm

Fixes flashbangs not actually making a sound if it doesn't successfully flash anyone.
Currently the flashbang sound is triggered when someone is actually flashbanged... this is also triggered for EVERY person that is flashbanged (i.e. flash 5 people, play the sound 5 times).
Hearing when your flashbang goes off so you don't run out and stun yourself is good.
:cl:
fix: Flashbangs go bang regardless of  whether someone actually gets flashed
/:cl:

Flashbang sound fix

---

code/__HELPERS/unsorted.dm

Adding a generic proc to draw a path between two atoms and check to see if anything is blocking that path, with a few args to tweak it's behavior.
This is useful because procs like get_hear() ignore transparent objects like windows or machinery, and is blocked by opaque atoms like smoke.
I made this for widow, but there's other things it can be used for, so PR'ing it on it's own for now, but let me know if that's not OK.
Useful proc good
:cl:
code: Added a check_path proc to see if a path between atoms is blocked
/:cl:

check path proc

---

code/datums/elements/deployable_item.dm

What it says on the tin. Provided that the border object isn't facing you (and so blocking your access) you can deploy items like teleporters/sentries etc onto turfs with barricades or other border objects.
More of a QOL change than anything.
Being able to deploy things on a turf you can walk through is good.
QOL
:cl:
qol: Deployable objects can be deployed on turfs with border objects such as barricades, that aren't obstructing your access
/:cl:

Deployable items can be deployed on turfs with dense border objects.

---

code/game/atoms_movable.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm

Per title. One of Tivi's wishlist items.
Allows xenomorphs to pull objects again. All objects have a pull wind-up of 1.5 seconds; the pull will fail if they are somehow interrupted.
Further encourages xenomorphs to interact with the environment, which leads to a less restrictive gameplay experience.
Bear in mind this implies many other concerns will be enabled, but it is preferable to tackle them rather than take the easy way out.
:cl: Lewdcifer
add: Xenomorphs can now pull objects (again).
/:cl:

Xenomorphs can pull objects again

---

_maps/map_files/LV624/LV624.dmm
_maps/modularmaps/lv624/auxbotany.dmm
_maps/modularmaps/lv624/lvhydrobridge1.dmm
_maps/modularmaps/lv624/lvhydrobridge2.dmm
_maps/modularmaps/lv624/lvhydrobridge3.dmm
_maps/modularmaps/lv624/lvhydrobridge4.dmm
code/game/area/lv624.dm
code/modules/mapping/modular_mapping.dm

Before:
After:
I think the current LV is not as good as the other maps on offer. The first goal of this PR is to make the whole general western area of the map more playable for both the xenos and marines, as currently it's just a lot of grass, water and a huge cliffside on both sides of the river, hard to approach for both xenos and marines. To address this, I opened up the southwestern exit out of the LZ and added a dome and paths around it for easier navigation. The cliffside north of the river has been cut open a tablefort area has been added. This area has a miner, so marines have a reason to go for it. It also has a bridge to get to it across the river, xenos no longer have to suffer over the tiny 2 tile bridge to attack the red disk, they have more options and I think that's good. …

LV 2022 Rework

---

code/datums/gamemodes/combat_patrol.dm

What is says on the tin. 3 minutes instead of 5. Prep takes 5 seconds, the time is really just there to ensure everyone can spawn in before the game starts.
Less waiting good
:cl:
qol: Shutters drop after 3 minutes in Combat Patrol instead of 5
/:cl:

Reduces shutter drop time in combat patrol to 3 minutes

---

code/modules/instruments/songs/play_synthesized.dm

currently synthesized instruments tend to bug out if the sound they try to play is too long.
turns out this is because the arguments in a proc call were putting the channel number into is_global and setting the actual channel to null resulting in the sounds getting assigned a random channel, meaning that the instrument will try to update the wrong channels
this just sets is_global to false and replaces null with channel
also would love if anyone could double check this, I am confident this should work but second opinions are nice.
not having synthesized instruments bug out is nice
:cl:
fix: fixed synthesized instruments
/:cl:

fix synthesized instruments

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Big bundled box of little changes. As usual, you gotta pack things together
- Fixed a bunch of cameras on firelocks or glass.
- Made the CL room a little nicer
- Added some markings to engineering to make it look better
- Changed the Synth door from a door labelled 'AI core' to a CIC door
- Added a second fuel cycler to POS
- Added a lil button for the umbilical, besides the OB room. It doesn't let you go to space
- The FCDR office had 2 doors. Removed one
- The FCDR office had 3 firealarms. Left one
- Added Ian back to the CIC
- Brought back the pod shutters
- Brought back the medbay shutters button in the CMO office
- Gave the CPT and FCDR soap in their showers
- Fixed weird mirrors in the hangar bathroom
- Fixed the wrong type of glass in the memorial
- Moved the researcher consoles …

Various improvements on Pillar of Spring 

---

code/modules/vehicles/unmanned/unmanned_droid.dm

- Fixes unmanned droids not deleting properly
Things failing to delete because of a funny runtime is not good.
Closes #11025.
:cl:
fix: Fixes unmanned droids not deleting properly
/:cl:

Fixes unmanned droids not deleting properly

---

code/modules/projectiles/guns/rifles.dm

Increases extra delay from 0.05 to 0.1 seconds.
The AR-11 has the highest dps in the game by a significant margin. The autoburst fix didn't change this, but it did serve to highlight it by removing the need to turbo clickspam.
This is a tiny nerf, but I'd rather make small changes, and make more changes in the future, instead of large ones.
Slightly tweak the brrt spam of AR-11 for the better
:cl:
balance: Very slightly increased burst extra delay on the AR-11
/:cl:

Minor AR11 nerf

---

code/_onclick/hud/hud.dm
code/_onclick/hud/screen_objects/screen_objects.dm
code/modules/projectiles/ammunition.dm
code/modules/projectiles/gun_system.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/flamer.dm
code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm
code/modules/vehicles/mecha/mecha_mob_interaction.dm

1) No more user passing
2)autodoc
3)Can be given to any datum
4) no longer creates and deletes ammo objects constantly
5) no more spawn
6) other misc cleanups
I folded in mech ammo but I can split it out if you want
:cl:
fix: Ammo HUDs will now always blink when you are out of ammo instead of only the bottommost one
/:cl:

Ammo hud refactor and gives ammo counter to mechs

---

code/modules/projectiles/ammo_datums.dm

Fixes lmg not dealing damage and nerfs the light cannon.
LMG working good, light cannon not critting crushers in 3 hits also good (it crits them in 5 hits instead now)
:cl:
balance: mech light cannon's main projectile and spread projectiles deal less damage
fix: fixed the mech lmg not dealing damage
/:cl:

LMG fix and light cannon nerf

---

code/modules/clothing/head/helmet.dm
code/modules/clothing/masks/gasmask.dm
code/modules/clothing/suits/marine_armor.dm
code/modules/clothing/under/jobs/civilian.dm
code/modules/clothing/under/jobs/engineering.dm
code/modules/clothing/under/jobs/medsci.dm
code/modules/clothing/under/jobs/security.dm
code/modules/clothing/under/marine_uniform.dm
code/modules/clothing/under/syndicate.dm

Edit: This PR now removes the armour values from hopefully all non admeme uniforms and powergamable masks.
Removes the armour from PMC uniforms and balaclavas and put it into their helmets and armour.
No change for PMC, but prevent marine cheese when they get their hands on it on certain maps.
Super high melee resist cheese bad
:cl:
balance: Removed armour from PMC masks and uniforms, and increased their helmet and suit armour accordingly
balance: Removed armour from non admin uniforms
/:cl:

Removes most uniform and mask armor values

---

code/modules/events/intel_computer.dm

This event does nothing in these modes, so disabling it like it is in crash.
Pointless thing be pointless
:cl:
fix: The intel event will no longer trigger in Combat Patrol or Sensor capture
/:cl:

Disabled intel events for Combat Patrol and sensor capture

---

code/modules/projectiles/ammo_datums.dm

Reduced the bomblet damage of cluster grenades from 30 back to 20.
When I increased the blast radius, it made it a lot easier to stack many/all the bomblet blasts on a single person, and it was never intended to be a burst damage weapon, or atleast reliably so.
Big funny burst damage bad.
:cl:
balance: Cluster grenade bomblets do 20 damage instead of 30
/:cl:

Cluster grenade tweak

---

code/modules/reagents/reagents/medical.dm
code/modules/reagents/reagents/toxin.dm

If you have 75 damage on chest and 75 on a robot arm, inaprovaline will see that you have 150 damage and heal 50 of it. This makes ina/rr/neuro only consider damage on limbs it can heal.
Also applies the same restriction to transvit scaling.
Chems are for flesh automatons.
:cl:
fix: Emergency chem heals only scale on fleshy damage.
fix: Transvit doesn't try to convert burn from robot limbs
/:cl:

Emergency chems ignore robotics for heal amount calculation

---

code/modules/events/ion_storm.dm
tgmc.dme

It's a new event, Tivi wants more of them and I sat down and made some.
Ion storm is a low probability event that temporarily knocks comms offline for a period of between 1-4 minutes. It's basically TG's comms blackout, but it doesn't use emp_act() so we have more control over the duration.
More events good.
:cl:
add: Added a new event, ion storm
/:cl:

Adds an new event, ion storm

---

code/controllers/subsystem/greyscale.dm
code/datums/loadout/item_representation/_item_representation.dm

Caches hyperscaled attachments.
Allows loadout icons to be displayed correctly in case of greyscale_colors being set and not greyscale_config
fixes
:cl:
fix: Caches hyperscaled attachments.
fix: Allows loadout icons to be displayed correctly in case of greyscale_colors being set and not greyscale_config.
/:cl:

Some misc fixes for the hyperscale guns

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
_maps/map_files/LV624/LV624.dmm
_maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
_maps/map_files/gelida_iv/gelida_iv.dmm
_maps/map_files/icy_caves/icy_caves.dmm
code/game/objects/structures/sensor_tower.dm

tgmc can now only activate 1 sensor tower and cannot activate another until that sensor tower is activated or stopped
adjusted extra time when sensor tower is activated to +7 minutes from 10 minutes
time to activate sensor tower is now 250 seconds
todo: review map sensor towers placement
you can now win as som, encourages more team play rather than individual players running off to activate all the sensor towers in the map making som have to play whack a mole
:cl:
balance: tgmc can now only activate 1 sensor tower and cannot activate another until that sensor tower is activated or stopped
balance: adjusted extra time when sensor tower is activated to +7 minutes from 10 minutes
balance: time to activate sensor tower is now 250 seconds
/:cl:

sensor capture balance

---

code/modules/projectiles/guns/flamer.dm

Prevents normal muzzle from penetrating further than 3* tiles into resin walls
Prevents spray muzzle from penetrating as much
Currently spray nozzles are dominating xeno mazes, the justification that I recieved was that flamers need to clear mazes effectively.
This allows you to still clear mazes without the insane spread of fire behind 5 layers of mazes.
:cl:
balance: nerfed standard and wide flamer nozzle
code: Made it possible to set flamer penetration on resin walls
/:cl:

Flamer nerf

---

tgui/packages/tgui/interfaces/PlayerPreferences/GearCustomisation.tsx

I'm a little too new to the game to fully know what you're expecting out of these screens, but I assume that you probably don't want a bluescreen that prevents you from using it at all.
In my opinion, selecting a robo species should display a robo and possibly disable gear that they can't wear, but I'm not knowledgeable enough to know which yet.
fixes #10796
:cl:
fix: Fixes a bluescreen at the gear customization screen for combat robos.
/:cl:

Prevents a ui bluescreen at gear customization

---

code/modules/projectiles/ammo_datums.dm

Flechette is now 7+5+5 sunder, which is 17.
Slugs of both kinds have halved sunder to 7.5.
12 Gauge Slug sunder is probably overall too high, perhaps 10 is better if it underperforms in the future.
Flechette sunder is too low right now, and I feel the ammo type is underperforming, If it does too much I'll nerf it down to like, 12.
:cl:
balance: 12 Gauge Slugs (Both Incend/Normal) sunder halved to 7.5, flechette upped to 17 max sunder on hit from 8.
/:cl:

Nerfs 12 Gauge Slug sunder, gives flechette higher sunder.

---

code/modules/projectiles/guns/rifles.dm

Title
Trade extended barrel's accuracy bonus for more bullet speed and an accuracy malus. DMR already can fit it while having the same range, nobody seems to complain.
:cl:
balance: SR-127 can now fit barrel charger
/:cl:

Lets SR-127 fit barrel charger

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/specialist.dm

SG-85 changes
Armor Penetration
15->25
Damage Falloff
.5->.1
Changed falloff from the gun to the ammo considering nothing else uses it.
SG Minigun is currently a pretty big noobtrap nobody uses considering you give up the ability to carry another primary to use it for a grand total of basically no gain considering t-29 is basically the same and is much more rewarding to use in most of the same scenarios.
Higher pen and less falloff should allow it to deal okay damage at range, and penetrate armor so it can touch tougher castes and suppress them, while still mainly being poor at dealing any actual damage.
:cl:
balance: SG-85 has less falloff (.5 per tile to .1 per tile) and higher Armor Penetration. (15->25 Pen)
/:cl:

SG Minigun buffs, has higher penetration and less falloff.

---

code/datums/elements/deployable_item.dm
code/modules/projectiles/mounted.dm

you can no longer be moved while using mounted guns (only applies to marines xenos can still push and shuffle you) also removes being able to deploy deployables diagonally because you cannot get on the gun even if your behind it you have to click it diagonally, breaks aiming, and it breaks turning
pvt pisser shitter can no longer stop you from getting the epic frag by pushing you
:cl:
qol: can no longer be moved while manning mounted gun
fix: can no longer deploy mounted gun diagonally since it breaks stuff
/:cl:

you can no longer be moved when manning mounted guns by humans and a fix

---

_maps/map_files/gelida_iv/gelida_iv.dmm

Apparently some varedits slipped past me while porting Gelida, and people didn't like the bolts/welds. This PR removes them.
If you ask people what they hate about Gelida, usually they'll bring up bolted doors. Removing them should be a positive.
:cl:
balance: Gelida no longer has bolted or welded doors at roundstart.
/:cl:

Removes some bolted/welded varedits on Gelida

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

Per title.
Fix good. Ravager being FOB destroyer 9000 bad.
:cl: Lewdcifer
fix: Ravager's Ravage will no longer push anchored atoms.
/:cl:

Fixes Ravage pushing anchored atoms

---

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm

Fixes an issue where being staggered or stunned during Emit Gas would make you emit particles forever.
Fix good. Eternally stinky Defiler bad.
:cl: Lewdcifer
fix: Defiler particles are cleared correctly when staggered or stunned during Emit Gas.
/:cl:

Defiler particles are cleared when staggered or stunned during Emit Gas

---

code/game/objects/items/storage/backpack.dm
code/game/objects/items/tools/maintenance_tools.dm

So refuel code is pretty spaghetti, welder kits, welder packs, and welding tanks all run their refuel code in different places, adds the missing checks to the two bags, although long term they could probably use a refactor to just be generally less jank.
Also added a missing check welder kits so they don't appear to refuel full tanks.
Exploits bad.
:cl:
fix: fixed both kinds of welder bag still refilling xfuel tanks
/:cl:

Fixed welderpack/kit still refueling xfuel tanks

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/reqs/supplypacks.dm

Adds X fuel large tanks to req for 30 points.
Removes incinerator tanks from req and replaces them with the regular large tanks for double the cost (3>6).
Amount of large flamethrower tanks in vendors reduced from 30 to 16.
X fuel is only available in the form of a back tank. This adds the regular X fuel tanks to req for half the price of a back fuel tank.
There's never a reason to order incinerator tank with the lesser fuel it provides and tanks being refillable to an infinite amount and its greater versions being available roundstart.
The amount of initial large tanks available have been reduced now that they're orderable in req.
:cl:
add: Added X tank to requisitions for 30 points.
balance: Replaced incinerator tanks with large flame tank for higher cost (6 points).
balance: Reduced …

Adds X fuel tank to req. Replaces incinerator tanks in req with large tanks.

---

code/__DEFINES/loadout.dm

The AI targeting module was intended to be 10 in req and in the engineering vendor. 
I forgot it during the PR which introduced it. 
It was the intended price. 
Also, 40 is very expensive when you could invest in a lot of mines, razorburn, turrets, UV or whatever else. 
:cl:
balance: Set the AI artillery aiming module to 10 in engineering vendor also
/:cl:

Set the price of the AI targeter in engineer vendor to 10 as well.

---

code/modules/reagents/reagents/toxin.dm

Title.
Closes https://github.com/tgstation/TerraGov-Marine-Corps/issues/11244.
There's a mixup in the beer datum with beer2, causing a check to fail and the beer to not be dispensed. Because beer2 is a toxic knockout drink that has no place in TGMC I removed it entirely.
Bugs bad fixes good.
:cl:
fix: The booze dispenser can dispense beer again.
/:cl:

Fixes beer not being dispensable

---

code/modules/mob/living/living_defense.dm

stop drop and rolling now makes you get stunned for 5 seconds from 10 seconds
fire damage does allot of pain and stop drop and rolling doesn't remove all the fire stacks so 10 seconds of being stunned and the fire still being there because you didn't bring an extinguisher is not fun
:cl:
balance: stop drop and roll only takes 5 seconds now
/:cl:

stop drop and roll no longer stuns you for 10 seconds

---

code/__DEFINES/conflict.dm
code/datums/components/autofire.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/projectiles/gun_system.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm

:cl:
code: Redid how autofire decided to continue firing a little
/:cl:

Mech autofire will no longer use ammo outside cone

---

code/modules/projectiles/ammunition.dm

Title
This seems to have been there since before ammo packets were a thing. They're inferior now since a backpack can fit 150x8 rounds for a total of 1200 rounds, or 5 boxes for 750 and have space left for anything else.
Since the big ammo box takes up the backpack slot that you can't change on the fly by, say, dumping a few ammo packets to make space for something else, it should probably have been buffed since the introduction of packets. Count increased to 2400 as per MJP's suggestion so as to make it 2x the amount of rounds you'd be able to fit in a full backpack of equivalent ammo packets.
:cl:
balance: Big 10x24 ammo box now fits 2400 rounds from 800
/:cl:

Increases ammo count of big 10x24 ammo box

---

code/game/atoms_movable.dm
code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
code/modules/mob/living/carbon/xenomorph/xenomorph.dm
code/modules/mob/mob.dm

code is comparable to how tg does it
:cl:
fix: things that have high move resistance such as mechs can no longer be pulled by things with low move resistance
/:cl:

Fixes mechs being pullable

---

code/game/objects/machinery/vending/marine_vending.dm
code/modules/projectiles/ammunition.dm

Title
Same rationale as #11248. Found it while editing that one, figured it'd be neat to have in actual rounds. Backpack count full of ammo boxes is 12x150 leading to 2250, that x2 would be 4500. Given how fast you'd go through mags in a fight you'd sooner lose them anyway.
:cl:
add: There's now a Big Ammo Box for 10x20mm SMG caliber. 4500 rounds.
/:cl:

Increases count of big 10x20 ammo box

---

code/modules/projectiles/ammo_datums.dm

Set the barricade clear distance for bullets, energy projectiles and rockets (i.e. no xeno projectiles) to 2 instead of 1.
This means you can safely shoot past any object 2 tiles away instead of having to be right next to it.
This should have minimal if any impact on HvX, and is mainly aimed at HvH modes.
This should make using cover a lot easier in practice when you're active moving around, or shooting at diagonals (like shooting out of a 2-3 tile wide window). 
It also means you can take advantage of layers of cover, for example many maps have 2x2 areas of crates and other objects, which previously would always atleast partially block your bullets.
:cl:
balance: guns can now shoot past obstacles up to 2 tiles away instead of 1
/:cl:

Coverage change - HvH mainly

---

code/modules/reqs/supplypacks.dm

Big ammo boxes of both 10x20mm and 10x24mm are now orderable for 5 points each.
So far most ammunition from the op vendor was either craftable (cardboard) or had an equivalent (normal ammo boxes for mags, ammo packets, or shotgun boxes). This was the only thing that was in the op vendor for ammo but obtainable nowhere else, making it a once in a round thing for something that hardly had a reason to be like that. 5 points seems reasonable given the surplus supply crate costs 20.
:cl:
add: Big ammo boxes (10x20mm and 10x24mm) can be ordered from req for 5 points each.
/:cl:

You can now order big ammo boxes from req

---

code/modules/projectiles/guns/mounted.dm

Both guns get TAT level of armor, the other limited fixed gun, *without* an increase in integrity.
Got the go ahead from Tivi, but she simply said "idk" on exactly what armor to give so no doubt this PR needs discussion.
These two fixed guns are essentially forced into an aggressive, frontline role considering the very short scope, and the MG08 even more due to total lack of IFF. they had 0 armor except bullet, so I gave them the armor TAT has (plus 40 acid since the TAT has 0) but did not touch the 200 integrity (vs TAT 500). So they wont be nuked as easily even through cades with scatter spit, particualrly the 08.
I know the armor might seem like removing all the counter play, but I personally did not see complaints specifically about the TAT tankiness, and considering the machineguns …

Gives armor to the HSG102 and MG08

---

code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm

it uses the same as for big mobs

Crest toss will now toss much less on mechs

---

code/datums/jobs/job/special_forces.dm
code/modules/projectiles/guns/pistols.dm
code/modules/projectiles/guns/smgs.dm

- Replace their baclava with SWAT masks
- Gave them mag harnesses
- Gave them pistol laces where applicable.
SAS ERT has not kept up with other ERT's
Their armor is really weak right now, and the guns are pretty unwieldly without any mag harness. This PR should make them survive longer than a single stun, defiler, or other sources of gas. 
:cl:
balance: Gave SAS ERT Mag Harness
balance: Gave SAS ERT Pistol Lace for breacher
balance: Gave SAS ERT Gas masks instead of baclavas
/:cl:

Update the SAS ERT Gear

---

_maps/map_files/Theseus/TGS_Theseus.dmm

The SD doors on Theseus aren't accessible to everyone, unlike every other ship we have. This PR corrects that oversight.
It's apparently difficult for marines to hold SD when they can't even filter in and out of the doors, ERT can't invade either apparently.
:cl:
fix: The Theseus' SD doors are now accessible to everyone once the shutters are lifted.
/:cl:

Fixes Theseus SD doors

---

_maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm

Areas all over Ice Colony have multiple APCs per area which can cause problems. This rectifies that issue.
This has been a problem for a while now, this fixes that problem.
:cl:
fix: Removes multiple APCs from areas such as Medbay, Admin, and Aerodome Security
fix: Cleans up some useless cables
/:cl:

Removes multi-APCs on Ice

---

code/__DEFINES/loadout.dm
code/game/objects/machinery/vending/vending_types.dm

Did a PR awhile a go where I made an isotonic pill bottle you could buy from the loadout vendor, realized why should you pay for it, moved it to the NTMed
nuff said, why pay for something that shouldnt really be paid for
:cl:
qol: moved isotonic pills from the corpsman loadout vendor to the medical vending machine
/:cl:

moves isotonic pills to the pill bottle vendor

---

code/datums/components/chem_booster.dm

Currently Vali alerts to impending after 12 secs, giving necro hud and periodic text warnings. Changes to two step warning, with text warning only at 10 secs onwards, and necro hud appearing at <s>17</s> 15 secs onwards. This translates to text warning appearing at 10 seconds left and necro hud appearing at 3 seconds left. Values still undecided until tested.
Current vali warning is imprecise and misleading imo. The margin of 8 seconds on the warning is too wide and defeats the purpose of the warning. Also the text alerts are inconsistent and don't happen at consistent intervals, so you can't rely on them that well. Splitting the warning into text and hud at different intervals would be better I think. Text warning will be there to let you know that necro is approaching and allow you to …

Vali Necro Warning Adjustment

---

code/modules/mob/living/carbon/human/human_attackhand.dm

Clicking on human with empty hand will now start removing hugger from their face if they have one. This has lower priority than putting out fire so hilarity ensues.
Removing huggers is a pain in ass. You need to drag victim's sprite onto yourself then click the corresponding item slot and THEN you start removing it. I do not consider it to be a balance change for two main reasons
1. Removing huggers with hands is a noob trap that puts two marines out of combat for at least 4 seconds and will not work out if anybody shuffles them. Removing huggers with fire is the most reliable option to deal with them.
2. Abilities should not be balanced by janky, user unfriendly interfaces. Hugger removal time can be increased if needed, but not the complexity of controls.
:cl:
qol: huggers can now be …

Help intent clicking starts removing huggers 

---

code/game/objects/items/explosives/plastique.dm

I was waiting for someone to answer my mails, so I did this in the meantime.
This PR adds a little beeping noise before the C4 blows up. 
It also adds explosion noises, which weren't present. It picks randomly from 3 different ones. 
I tested it, but I forgot to test the longer cooldowns. I don't think this should be an issue.
C4 was kind of underwhelming before. This gives it a bit more fluff, and hopefully makes people more interested in using it.
:cl:
soundadd: Add a beeping noise to C4
soundadd: Add an explosion noise to C4
/:cl:

Add beeping & explosion noises to C4

---

code/modules/projectiles/ammunition.dm

Big Ammo Box (10x20mm) couldn't actually refill mags because it still inherited the parent caliber of rifle ammo. Apparently nobody uses big ammo boxes to realize they could be using the 4500 round box to refill 10x24mm rifle mags.
Bugs bad
:cl:
fix: Big Ammo Box (10x20mm) will actually fill mags of its caliber now.
/:cl:

Fixes 10x20mm ammo box not working

---

code/game/objects/structures/barricade.dm

all metal cade tool interactions no longer block you from interacting with other cades
Makes engi less of a hassle + actually brings it up to par with plasteel, which even had this info in a comment
:cl:
balance: all metal cade tool interactions no longer block you from interacting with other cades
/:cl:

Barricades do_after interaction expansion

---

code/modules/mob/living/carbon/carbon_defense.dm

- Fixes ozelomelyn defiler smoke not doing anything if you have a gas mask, I have no idea how nobody has noticed this for so long
I'm pretty sure making using ozy in smoke should not be a noob trap. Bringing it up to the same level as the others should do us good.
:cl:
fix: Fixes ozelomelyn defiler smoke not doing anything if you have a gas mask
/:cl:

Fixes ozelomelyn defiler smoke not doing anything if you have a gas mask

---

code/game/objects/items/explosives/plastique.dm

I didn't notice the sound_range was the same as volume by default. 
Thanks, @Lumipharon, for the callout. 
It just makes sense to not hear it so far.
:cl:
fix: fixed C4 being hearable way too far.
/:cl:

Reduce C4 boom volume & range

---

code/datums/jobs/job/xenomorph.dm

Crash xeno to marine ratios feel weird and I think its because xenos have to pay back for free slots, this PR should hopefully make those free slots, actually free.
Low-pop should be fun for both sides too, this should hopefully even out the playing field.
:cl:
balance: xenos dont pay back for roundstart slots
/:cl:

xenos no longer pay back for free slots on crash

---

code/modules/projectiles/guns/smgs.dm

Per title. Akimbo delay increased from 0.5 to 1.3.
Funny double MP-19 man shouldn't be almost instantly shredding through xeno health like a HOT (thank you mr. @revelation-8468) knife through butter.
:cl: Lewdcifer
balance: MP-19 akimbo delay 0.5 > 1.3.
/:cl:

Nerfs MP-19 akimbo delay

---

_maps/map_files/Theseus/TGS_Theseus.dmm

Title.
CLs were getting locked out of their office roundstart, in an earlier PR I gave an extra button to the CL in the CIC as an override, but the button isn't noticeable and the area near the CL office is cluttered so there's no easy place to relocate the button.
I've opted to just start the doors open at roundstart, if the CL needs to close the shutters he has a button inside his quarters.
It should lead to less locked out CLs.
:cl:
balance: The CL office on Theseus now starts open on roundstart.
/:cl:

CL shutters now start open on Theseus

---

code/modules/projectiles/guns/rifles.dm

Identical to the T-12 (.1 extra fire delay and 2 aim speed modifier)
Its a T-12 sidegrade in design and there's absolutely no reason it should have worse aim stats than its Assault Rifle cousin.
:cl:
balance: LMG now has identical aim mode stats to the AR, which ends up as a buff, aim mode fire rate stat buffed from .2 to .1, and aim slowdown from 5 to 2. Tottaling to .3 fire delay and 2.85 aim slowdown in total.
/:cl:

LMG now has better aim mode stats.

---

code/modules/vehicles/unmanned/unmanned_vehicle.dm

Per title. Fixes #11211, even though it's not strictly a fix and also a balance change.
Allows these specific castes to contest UAVs instead of being screwed over.
:cl: Lewdcifer
balance: Xenos such as the Runner and the Spiderling will now bump into UAVs instead of going over them.
/:cl:

Runners and Spiderlings will now bump UAVs instead of going over them

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Warrior's punch ability is currently hardcoded to break your splint no matter what, which is super cringe.
Even without this it's still likely to break your splint, just not 100% guaranteed.
autobreak is cringe.
:cl:
balance: Warrior punch is no longer 100% guaranteed to always break splints
/:cl:

Remove autosplint break from warrior punch

---

code/game/objects/effects/temporary_visuals/miscellaneous.dm

The explosion visual and lighting effect are now both correctly centered on where the explosion occured.
The cool new explosion animation and lighting effect had an offset problem, where the explosion was centered but the light was not.
This is because the light source is based off where the icon is, which is offset due to being 64x64.
Making the explosion an overlay fixed this, as that can be offset separately. I also gave it a rotate, so while barely noticable, it means when you have 10 explosion go off on screen at once, they won't all be perfectly identical, which I think is visually nice.
bug fix good.
:cl:
fix: fixed explosion lights not being correctly centered
/:cl:

Explosion light fix

---

code/modules/projectiles/ammo_datums.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm

Final balance adjustments before release:
-All laser guns nerfed, they were too strong considering they didn't have to worry about ammo at all, and mech ammo logistics is painful, with that in mind~
-Most weapons max ammo count, and magazine count, got buffed, majority of these weapons had pitiful ammounts of ammo and reloading a mech is absolute hell, and that's even if marines actually bother carrying your ammo crate for you, this should give them more staying power and make them more desirable when compared to energy weapons.
-Mech medium and heavy head did not have a light range var so they were stuck with shitty lights, now they do.
Walance
:cl:
balance: Lasers nerfed, ammo count on most guns buffed, medium and heavy head have better lights
/:cl:

Mech Balance changes 2.0

---

code/modules/projectiles/guns/specialist.dm

Fixes an issue where the SADAR had two lines defining gun flags each, which means that SADAR has always been able to fire without full wielding. This was my mistake. Hee hoo.
Bug fix good. Bug-free game good. Bug bad. Squash bug.
:cl: Lewdcifer
fix: Fixes an issue where SADAR gun flags were defined twice.
/:cl:

Fixes SADAR gun flags being defined twice

---

code/modules/projectiles/magazines/misc.dm

SG-85 ammo bin now states 500 rounds instead of the incorrect 1000.
:cl:
spellcheck: SG-85 Ammo Bin now shows correct number of rounds.
/:cl:

SG-85 Magazine Typo Fix

---

code/game/objects/machinery/computer/camera_advanced.dm

Fixes issue #11067 caused by bug introduced in #11002. Tad now lands in the direction expected.
Funny tad spin is not a feature and I don't like it.
:cl:
fix: Tadpole now lands in the correct direction.
/:cl:

Tadpole Rotation Bugfix

---

_maps/map_files/Sulaco/TGS_Sulaco.dmm
code/game/objects/items/frames/table_rack.dm
code/game/objects/items/stacks/rods.dm
code/game/objects/structures/tables_racks.dm

Apparently I missed this map when doing https://github.com/tgstation/TerraGov-Marine-Corps/pull/10248, while I was fixing that oversight I also changed tables so you can't game them by deconstructing them into parts and then turning the parts into metal.
I also removed a random check that existed to prevent building in a hangar.
Oversights bad, it needs done because apparently it's becoming an issue again.
:cl:
balance: You can no longer deconstruct Sulaco's tables and chairs for metal.
fix: Fixed an oversight where you could deconstruct tables for parts, then parts for metal.
/:cl:

Corrects Sulaco having regular tables/chairs

---

code/game/objects/items/weapons/shields.dm

Reduced the damage absorbtion (not armour) of shields for bullet, laser, energy and fire.
Minimal if any impact on HvX, but should tone down a bit the durability of shield loadouts in HvH.
Make shield chads slightly easier to deal with in HvH
:cl:
balance: Reduced the damage absorbtion of shields for bullet, laser, energy and fire
/:cl:

reduce projectile and flame absorb of shields

---

code/game/objects/items/storage/dispenser.dm
code/game/objects/structures/teleporter.dm

Adds the XENO_DAMAGEABLE flag to the dispenser so xenos can actually hurt it, also set its max integrity to 200, same as the teleporter.
Also fixes an exploit that allowed you to draw items from a dispenser when not deployed.
Oh and a couple of desc fixes.
Incidentally, updated a var on the teleporter that was misleading, since max integrity is actually inherited from the item it deploys from, but left it in on both items for clarity.
Marine structures hittable is good
misleading var bad
Being able to carry and wield 9 guns is bad
:cl:
balance: Reduced dispenser integrity to 200. Can also now be hit by xenos
fix: Fixed an exploit that allowed for items to be drawn from a dispenser when not deployed
/:cl:

Dispenser tweaks

---

code/game/blood.dm
code/game/objects/items/tools/cleaning_tools.dm
code/game/objects/structures/watercloset.dm
code/game/turfs/open_ground.dm
code/game/turfs/turf.dm

Soap REFACTORED
Showers REFACTORED
Rivers FRESH
Server CLEANER THAN EVER
Adds a clean_mob() and clean_turf() proc to mobs and turfs respectively. Maybe I should have just added this at the atom level but eh.
Made shower code a little bit less guh, and means RIP's rain pr can just reference this proc instead of copy pasting shower code, like I've done with river code.
Soap can now actually target a turf to clean all the crap off it instead of targeting one decal at a time.
Fixes a pretty funny bug where showers can be used to qdel ANY effect/overlay, for example OB/CAS laser indicators, certain effects like timestop and gib animations. Also palmtrees.
Also stops showers from runtiming constantly as they clean decals in the most bizarre way possible.
Cleaner cleaning code
bugfix good.
:cl: …

Cleans the server

---

code/modules/reqs/supplypacks.dm

req currently can only order detpacks in a set of 2 with a signaler for a cost of 15, this changes it so reqcan order 1 detpack at a time with no signaler for 5 points.
being able to order a precise amount of detpacks is nice and is more inline with c4 and other req orders, also there is no reason for it to include a signaler since you can just get it from the utility section in the weapons vendor for free.
as for the price i set it to 5 since it is more expensive then c4 which is 3 and having it cost somewhere around 7 seems a bit much.
:cl:
balance: detpacks can now be ordered individually and cost 5 points, no signaler included
/:cl:

detpacks are no longer sold in pairs, cost reduced to 5, no longer comes with signaler

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Per title. Meant to go together with the Lunge range nerf PR here: #11387.
It is published separately since maintainers don't like unatomized nerfs.
**If a choice must be made between either, prioritize this one.**
Punch's base damage is equal to the Warrior's **slash damage**. At Ancient, this is **23** damage.
Primordial's **Empower bonus** to Punch is **x1.5**, applied **BEFORE** the Lunge into Punch bonus.
23 x 1.5 = **34.5** damage.
The **Lunge into Punch bonus** is **x2.0**.
23 x 2.0 = **46** damage.
Including the **Empower bonus**, 34.5 x 2.0 = **69** damage.
Base damage remains untouched. This is **23** damage.
Primordial's **Empower bonus** untouched.
23 x 1.5 = **34.5** damage.
Lunge into Punch bonus **decreased** to **x1.5**.
23 x 1.5 = **34.5** damage.
Including the **Empower …

Nerfs Warrior Lunge bonus modifier for Punch from x2.0 to x1.5

---

code/modules/mob/living/carbon/life.dm
code/modules/projectiles/ammo_datums.dm

Hey! You! Yes, you. Come on over, let me show you something really funny...
So I noticed that Boiler globs have a var called `hit_drowsyness`, which is the amount of drowsiness stacks applied on a direct hit. A normal acid glob applied one stack of drowsiness. A lance acid glob, applied 18. A neuro lance glob applied 2.
So what does drowsiness do, you wonder? I am so glad you asked...
Every tick, if you have a stack of drowsiness, it'll blur your eyes and you'll lose a stack. However, _**it also has a 5% chance to make you fall asleep and unconscious**_. This was taken from `/mob/living/carbon/handle_status_effects()`:
What does this mean for a poor, poor marine? After being hit directly by a Boiler glob, there's a 5% chance they'll just fall asleep and unconscious as long as they have …

Drowsiness sleep chance changed to only activate after a certain stack threshold

---

code/game/objects/machinery/mortar.dm
code/modules/projectiles/ammo_datums.dm

Replaces several instances of get_dist() with get_dist_euclide() in artillery code.
Get_dist() has a cap of 127 tiles (thanks BYOND) which meant artillery shots had an effective range of 127 tiles (~63 on diagonals). Lest we forget the many pushes decimated by BYOND's cruel gaze.
Previously, the max_range on the shell datum didn't actually affect the range of the shot. It now does. The default for all shells has been set to 1000 so this doesn't actually change gameplay currently, but the code's ready if you want to.
Also alters the screenshake check to use cheap_get_humans_near/cheap_get_xenos_near instead of checking if every single mob is next to the mortar or not, which SHOULD be slightly more efficient.
Fixes good
:cl:
fix: Artillery shots no longer have a pitiful range of 127, …

Arty range fix

---

code/game/objects/items/stacks/sheets/sheet_types.dm

Removes bypassing grenade balance via unchecked reagent reaction mechanics. (e.g. Multi-fire tile effect napalm grenades, multi-explosion instakill mixes.)
Possibly more to remove to purge chemnades but starting here for now.
:cl:
You can no longer craft grenade casings
/:cl:

Removes chemisty grenade crafting recipe

---

_maps/map_files/Minerva/TGS_Minerva.dmm

Implements Azon's PR here, https://github.com/tgstation/TerraGov-Marine-Corps/pull/11215. I have permission to do this.
EDIT: I've given this the high priority label due to the fact that Tivi's mechs won't work on Minerva without the PR being merged.
With https://github.com/tgstation/TerraGov-Marine-Corps/pull/11393 live only Minerva lacks an MP bay, without one mechs and pilots cannot spawn in normal gameplay.
:cl:
add: Added a mechbay and MP spawners to Minerva.
/:cl:

Adds MP bay to Minerva

---

code/datums/elements/shrapnel_removal.dm

This PR adds support to the corpsman's medical tweezers for the same radial menu that medkits and surgery use. This PR also makes it so you will continue attempting to remove shrapnel as long as your patient has any in them.
Makes using the tweezers slightly less inconvenient. Also it was weird that virtually every other limb-based medical thing supported the radial menu setting but the tweezers didn't.
:cl:
qol: The corpsman's medical tweezers now support radial menus and will continue attempting to remove shrapnel if the patient still has any.
/:cl:

Adds radial menu support to medical tweezers, chain-tweezing.

---

_maps/modularmaps/big_red/bigredatmosvar1.dmm
_maps/modularmaps/big_red/bigredatmosvar3.dmm
_maps/modularmaps/big_red/bigredatmosvar4.dmm
_maps/modularmaps/big_red/bigredatmosvar6.dmm

You can pod into the tank on BR if you're insane enough, the walls are invincible so nobody can get at you. It wasn't really a consideration because you're intentionally locking yourself out of the game and most people don't want to do that, but Franklin Ramis isn't most people apparently and I have to do something about it.
Bugs bad, fixes good. Also it keeps wind from affecting the interior of the tank area.
:cl:
fix: You can no longer pod inside of the water tanks in BR.
/:cl:

Fixes being able to pod into BR containment tanks

---

code/modules/clothing/suits/marine_armor.dm

Mech Pilot armor sprite now properly shows (it has been set to no map variants)
This is not good for the game and will actively make the experience worse.
:cl:
fix: Mech Pilot armor sprite fixed.
/:cl:

MP Armor Fix

---

code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm

Tittle
Efficiency module is way too good, this should put it in line with the other two energy modules
:cl:
balance: mecha energy efficiency module drain reduction reduced from 75% to 50%
/:cl:

Nerfs mecha efficiency module from 75% energy reduction to 50%

---

code/datums/weather/weather_types/acid_rain.dm

Title.
I had a check to prevent this in an earlier version, forgot to re-implement it once the shower refactor was in. 
Oops.
As amusing as it is to hear the game refer to the xenos nonexistent clothing getting waterlogged, it should probably be fixed.
:cl:
fix: Rain no longer affects xenomorphs' nonexistent clothing.
/:cl:

Fixes rain giving xenos wet messages

---

code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm

Energy sword now uses mech energy when swinging, you have 8 slashes give or take before running out and having to go take a break in a corner
Infinite dashing with mech is fun, for the mech, actualy having to deal with it isn't very fun, this puts a max ammount to the number  of dashes you can do with it so it still retains mobility without making mechs barry alen
:cl:
balance: mech energy sword now uses energy to swing
/:cl:

Nerfs laser sword energy usage and increase cooldown between uses

---

code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm

Nerfs overall mech health, buffs heavy mech chest slowdown slightly (so slightly it probably doesn't even make a difference but the numbers not being symetrical were bothering me)
Stats (taking into account a full set instead of mixed parts)
Light: 1500 hp >> 1300hp
Medium: 2750 hp >> 2200hp
Heavy: 4000hp >> 3200hp
Less tanky mechs, considering how easy they are to repair they shouldn't be this tanky
:cl:
balance: Mech overall health reduced
/:cl:

Mech health nerfed

---

code/game/objects/machinery/vending/marine_vending.dm

This PR adds mech ammo to the Operational Supply Vendor in requisitions, in its own tab.
To my knowledge, requisitions currently has no way of sending down refills for mech guns on its own. MPs can already vend unlimited amounts of the stuff, this just makes the process of getting more ammo for your mech less of a pain in the ass.
:cl:
qol: The Operational Supply Vendor in requisitions now carries ammo for mechs.
/:cl:

Lets requisitions vend mech ammo

---

code/game/turfs/turf.dm

Title.
The new smoothing system doesn't really understand the concept of ChangeTurf() that well and so you get ugly black voids or weird missing walls if you plasma cut a wall.
This PR fixes that by integrating a smoothing check into ChangeTurf itself so the walls behave properly.
I have really needed to do this for a while, it's a small consistency fix that makes mining more bearable.
:cl:
fix: Walls will now properly smooth when destroyed via plasma cutter.
/:cl:

Fixes smoothing when mining turfs

---

code/modules/requisitions/supply_export.dm

Quick fix to prevent selling marines in hvx by putting them on the cargo elevator after you've started lowering it.
bugfix
:cl:
fix: Trying to sell humans you shouldn't be able to sell will not let you collect 200 dollars
/:cl:

Ally export prevention

---

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm

Per title.
Currently, the Defiler's Tentacle ability will meet many weird scenarios where it will fail the grab, causing the ability to go on cooldown and effectively wasting its use. This PR aims to amend that.
:cl: Lewdcifer
balance: Defiler ability will no longer go on cooldown if it fails to grab in some scenarios.
/:cl:

Defiler's Tentacle ability will no longer go on cooldown if it fails

---

code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm

When maturing pheromone strength changes are applied without having to turn them off and on again.
Tested it, both auras of single xenos and leader auras from queen both update properly.
It's how people expect it to work considering the ammount of poor clueless benos running around with unupdated pheromones
:cl:
fix: Xenomorph pheromones update when maturing.
/:cl:

Xenomorph pheromones update when maturing

---

code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm

Per title. This PR is meant to go together with the Lunge Punch damage modifier nerf PR here: #11386.
It is published separately since maintainers don't like unatomized nerfs.
**If a choice must be made between either, prioritize #11386 before this one.**
https://user-images.githubusercontent.com/59634950/198903302-02540db4-a6d8-4822-9a36-aea107d0c060.mp4
https://user-images.githubusercontent.com/59634950/198903315-16079228-2fd4-4c1b-972b-5eee9843eeaa.mp4
Effective range:
Lunge having 6 tiles of range has contributed to the current issue of Warriors being too good at what they do, not to mention being able to easily punish from considerable distances. This PR aims to amend that.
:cl: Lewdcifer
balance: Warrior Lunge range reduced from 6 to 4 tiles.
/:cl:

Nerfs Warrior Lunge range from 6 to 4 tiles

---

code/game/objects/items/bodybag.dm

Per title. Tarps have had their inventory size reduced, allowing more storage options to carry them.
This thing is so underwhelming nowadays, since xenos have a lot of tools to catch people in tarps.
Tarps would see more use if more inventory storages could hold them, and would also put them in line with other similar options, such as rollerbeds.
:cl: Lewdcifer
balance: Thermal dampening tarp inventory size reduced. More inventory storage options can hold them now.
/:cl:

Lowers the inventory size of thermal dampening tarps

---

code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm

Defiler now consumes plasma after noxius gas has been channeled instead of before/during
Defiler still gets its plasma consumed if stunned during channel
Noxius gas most of the time gets cancelled due to server ticks, ping or other lag issues, having it get canceled on the final tick and consuming plasma is very obnoxious and just makes the defiler more annoying and harder to play than it already is. 
:cl:
balance: defiler now consumes plasma after noxius gas has channeled
/:cl:

Defiler now consumes plasma after noxius gas has channeled

---

code/modules/reqs/supplypacks.dm

refill used to give 20 mag for 50 points. Now Buying 20 mag  is now cheaper than refilling.
Fix: cost before 5 points per magazine( if you buy 20 mag separately for 100 points) refill gives 20 mag for half the price (50 points for 20 mag)
Before: 5x20=100 (100\2=50)
Now: 2x20=40 (40\2 = 20 - refill price)
:cl:
fix: Reqtorio refill Cost for scout  rifle decreased to reasonable levels
/:cl:

BR-8 scout rifle magazine assembly refill Cost Fix

---

code/modules/mob/living/carbon/xenomorph/facehuggers.dm

facehuggers no longer disable your lights and headset cam when you are hugged
removes a cap gameplay relic
less overwatch screaming at marines to reboot their headsets and marines having to turn their lights back on
:cl:
del: facehuggers no longer disable your lights and headset cam when you are hugged
/:cl:

facehuggers no longer disable lights and headset

---

code/game/turfs/turf.dm

Fixes an issue where he recent fix for turfs not properly smoothing when a turf is destroyed was causing a metric gorillion runtimes at init for any map that uses modular map areas.
Runtime spam bad.
:cl:
fix: fixed some mapload runtimes
/:cl:

Turf smoothing runtime fix

---

code/modules/projectiles/gun_system.dm

Would you like to update the icon of your gun 40 times per second?
Would you like to update it 4 times just to reload once?
Well uh, I don't.
Small refactor of gun code so update_icon isn't spammed a gorillion times.
Basically cycle and update_ammo_count are called very often and update icon themselves, even though almost every proc that calls them updates icon anyway. So just changed it so ALL those calling procs call update_icon, and cycle/update_ammo_count do not.
Spamming icon updates is probably bad. Maybe some perf improvements, I unno.
:cl:
refactor: Guns should spam update_icon less
/:cl:

Gun icon update refactor

---

code/modules/mob/living/carbon/xenomorph/facehuggers.dm

Impregnate timer shortened to 10 seconds from 12.
As it stands, with the facehugger being easier to remove with just help intent, marines can reliably have the hugger removed as long as they are in a group. This change should not change that dynamic, just adjusts the window of time the marine has to take into account the ease of removal. This does not affect gestation period, only how long until an infection begins.
:cl:
balance: Hugger impregnate timer shortened from 12 seconds to 10.
/:cl:

Facehugger Impregnates Faster

---

code/game/objects/machinery/computer/nuke_disk_generator.dm

Stop the minimap icon blinking when the console shuts down from power loss or hijack.
Fix good.
:cl:
fix: Fixed the Nuke Disk Gen minimap icon blinking forever in some cases.
/:cl:

Nuke Disk Gen minimap icon fix

---

code/modules/projectiles/guns/flamer.dm

https://user-images.githubusercontent.com/57223640/200179538-42cf0f28-7ca2-41e0-a72c-d740137e8ebd.mp4
Blue fire is now dark blue instead of orange
:cl:
qol: flamer particles are now colored for blue/green fire
/:cl:

Flamer particle colors

---

code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/drone/drone.dm

`enhancement_action.end_ability()` was causing a runtime as drones will always lack that ability unless primordial.
Replaced `remove_status_effect` with `QDEL_NULL` accomplishes the same thing but faster, no reason not to use it as we are already storing a reference to it in the action.
closes #11332
Things should work as they are supposed to, drone link not being removed on death was also causing issue
:cl:
fix: Drone link is now removed on death
fix: Drone link removal by alt-use of the link ability now works
/:cl:

Drones can now cancel essence links properly, essence link automatically removed on death.

---

_maps/shuttles/tgs_bigbury.dmm
_maps/shuttles/tgs_canterbury.dmm

removes the 3 extra sentries and hsg in crash
3 sentries and a hsg is a bit much to deal with especially in lowpop xeno
:cl:
balance: remove the extra sentries and hsg in crash
/:cl:

remove the 3 extra sentries and hsg marines get in crash

---

code/modules/reagents/reagents/medical.dm

Paracetamol will no longer purge Tricordrazine.
The implications of this change are as follows;
- Allows players to have a viable alternative to the usual bica/kelo/tram trinity, in the form of paracetamol / oxycodone / tricordrazine, since the latter chem can counteract oxycodone's tox loss. Dylovene cannot do this since it purges paracetamol.
- Actually enables very niche builds such as Vali paracetamol builds, by allowing them to counteract oxycodone's consequence via tricordrazine.
- Adds more variety to chem gameplay by giving players viable alternatives to the usual everyday chems.
- Enables niche Vali builds based on paracetamol, which in turn means more variety for Vali players.
- Paracetamol gains more relevance, instead of being a forgotten and unused chem that nobody cares …

Paracetamol no longer purges Tricordrazine

---

code/game/objects/items/reagent_containers/autoinjectors.dm
code/game/objects/items/reagent_containers/hypospray.dm

Limits that behavior to regular hyposprays. Use one of those or eat the pill normally.
Standardizes all hypos/autos to lowercase names
bugfix
:cl:
fix: Autoinjectors can't absorb pills
spellcheck: Lowercased autoinjectors/hypos
/:cl:

Autoinjectors can't absorb pills, grammar

---

code/game/objects/structures/bookcase.dm

Title.
QOL.
Continuing on my last object update PRs to fix the overwhelming amount of objects that can only be destroyed by crusher or acid.
:cl:
qol: Xenos can now destroy bookshelves by slashing.
/:cl:

Make bookcases slashable by xenos

---

code/modules/mob/living/carbon/xenomorph/xenomorph.dm

minor irritation
:cl:
fix: fixed extra space in minion names
/:cl:

Fix extra space in minion names

---

code/modules/mob/living/carbon/xenomorph/charge_crush.dm

Title.
Currently it takes ~50 full speed charges to take down a 2500 HP mecha.
Crusher can delete rwalls in a single charge, yes there is some rng, but currently only does like 2 slashes worth of damage to a mech.
:cl:
balance: Mechs take the same damage from crusher charge as anchored objects.
/:cl:

Mechs take the same damage from crusher charge as anchored objects

---

code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
code/modules/vehicles/mecha/mecha_defense.dm

Title, oversight
:cl:
fix: Fixes mech arm weapons not taking damage from xeno slashes when targetted and fixes their integrity being set to 400 regardless of intended HP(usually 300 or lower)
/:cl:

Fixes mech component damage and weapon integrity

---

code/game/objects/structures/prop.dm

Have you ever tried to walk past an APC prop only to reee in agony as you get blocked by an invisible wall?
No more.
Changed the position of the sprite and its hit box to actually reflect the amount of space it visually takes up.
Invisible walls obstructing movement when they don't appear like they should is bad.
:cl:
qol: Changed APC prop hitboxes to accurate reflect the amount of space they visually take up.
/:cl:

APC prop QOL change

---

code/__HELPERS/game.dm
code/game/atoms_movable.dm
code/game/objects/items.dm

believe it or not, using GLOB.clients in a for loop for something that absolutely does not need it scales horribly

Flick overlay view/item pickup/drop animation optimization

---

code/datums/weather/weather_types/ash_storm.dm

Masks no longer protect against inclement weather, meaning marines outside are at risk.
Anyone with more than two minutes of playtime will wear a mask as there is no downside to doing so, and therefore this mechanic only negatively impacts one side whilst letting the other roam free. This will hopefully force both sides into more close encounters within buildings while taking shelter from storms, whilst at the same time not removing the ability for both to quickly dart in and out of the weather outside or shore up defences with haste.
:cl:
balance: Masks no longer make marines immune to inclement weather.
/:cl:

Marine masks no longer protect against ash/sandstorms

---

code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm

Rebalances the phoron and fusion engine
Makes the engines actually balanced and MPs actually have to consider which one is better for their build now, with phoron being better for lighter mechs but having less recharge rate and less capacity, and fusion being better for heavy builds but having more slowdown, also reduces max fuel capacity overall so MPs can't run around with infinite energy memes
:cl:
balance: Mech phoron and fusion engine have been rebalanced
/:cl:

Mech engine rebalance

---

code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm

Carrier can switch type of hugger to use while resting
Quality of life, shouldn't affect any balance, just allows the carrier to change the hugger type they want while resting.
:cl:
qol: Carrier can switch hugger type while resting
/:cl:

Carrier can switch huggers while resting

---

code/game/objects/effects/landmarks/landmarks.dm

Title.
While https://github.com/tgstation/TerraGov-Marine-Corps/pull/11496 was a fantastic PR, it also broke the weed landmark icon so if you open up a map you'll see endless fields of this
As one of my guiding principles as map maintainer has been clear readability when it comes to mapping, they need to be fixed so as to be instantly understandable by mappers both new and old.
:cl:
fix: Fixed the weed landmark icon to properly display while mapping
/:cl:

Fixes weed landmark icon

---

code/game/turfs/open.dm

Title.
Mechs now take damage from standing in or entering lava. The exact damage numbers are up to change if maintainers think they're too strong/weak. The intent is just to discourage mechs sitting in lava more or less invulnerable to counter attack, not make mechs unable to cross a lava river.
Currently mechs can just sit in the middle of a lava pool indefinitely, as long as team xeno doesn't have an acid based caste there's nothing that can be really done about it. For that matter, even if team xeno does have an acid based caste, there's a number of alcoves in the rock surrounding lava that the mech can just hide in and pop out to snipe boilers aiming at them.
This PR imposes a marginal penalty for just sitting in the middle of a lava pool, they can potentially do it for quite some …

Makes mechs take damage from lava

---

code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm

Allows the tank to live up to their name and continue fighting and soaking damage for their fellow xenos
I believe that a caste which is supposed to soak damage should be able to do so properly
:cl:
balance: made it possible for gorger to activate feast or rejuvenete while staggered
/:cl:

Makes rejuvenate and feast work even if staggered

---

code/modules/reagents/reagents/medical.dm

OD ticks for paracetamol, peri+, and arithrazine actually trigger
bugfix
:cl:
fix: ODs for para, arith, and peri+ work
/:cl:

Fixes mispathed overdoses

---

code/modules/events/hive_threat.dm
code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm

Mature/elder/etc xenos have the correct stocked age when created by spawning directly. No gameplay changes
can be worked around by varediting/xeno panel but easier to not bother
:cl:
fix: Spawning in aged xenos via admin tools will give them the proper upgrade_stored for their maturity level
fix: Draining the hive threat target give you the necessary stored age for ancient instead of setting you ancient and leaving it too low
/:cl:

Spawned in xenos have correct age

---

code/game/objects/items/storage/dispenser.dm

Dispenser storage size 63->48.
Backpacks are 24, you're telling me dispenser is about 2.3 times as big as a normal backpack, fits bulky items and fits on your back?
Thats absurd considering the only trade off is that you have to buy and deploy it to me. Should be more balanced being twice as big as a backpack overall.
:cl:
balance: Dispenser storage amount nerfed from being about two and a half times bigger than a normal backpack to only being twice as big as a backpack in storage amount.
/:cl:

Dispenser nerfed to 48 max storage size from 63.

---

code/modules/projectiles/gun_attachables.dm
code/modules/projectiles/guns/revolvers.dm

Removes snubnose Mateba, it literally doesn't matter considering longbarrel hasn't worked for probably like half a year?
Moves all the Longbarrel stats to the default Mateba.
Scatter buff. 0 scatter wielded, 7 unwielded.
Basically just reverts Mateba to the pre-snubnose nerf with some minor buffs., it was unnecessary for it to get nerfed in the first place in my opinion and this should make it more appealing to order and get.
:cl:
balance: Mateba buffs, now has long barrel stats, removes snubnose and just makes the longbarrel form the default with the snubnose storage size.
/:cl:

Mateba changes, removes snubnose, and some minor scatter buffs.

---

code/game/objects/machinery/mortar.dm
code/modules/reqs/supplypacks.dm

TA-40L (MLRS) rocket boxes now carry 16 rockets instead of 8, req orders adjusted to balance for this
Just a QoL thing, instead of having to ask for 2 boxes for every 'volley', it is just a 1 box per volley.
:cl:
qol: TA-40L Rocket Boxes now carry 16 rockets instead of 8. Requisition adjusted to compensate.
/:cl:

Rocket Storage Box QoL

---

code/game/objects/structures/dropship_equipment.dm

Yo can no longer deploy a mounted gun on top of other dense atoms, i.e. howies or sentries.
Exploit bad.
:cl:
fix: Tadpole weapons can no longer be deployed on top of other dense objects
/:cl:

Tad weaponpoint fix

---

code/game/objects/machinery/telecomms/machine_interactions.dm

Copypaste fix from TG that should fix linking telecomms machinery resulting in UI errors and runtimes.
Tested locally and didn't have issues with it, no clue why it works though, perhaps something about removing laziness.
Should have someone who can understand it take a look and ensure this doesn't harm anything though.
Credit to KacperRaid for digging up this code from TG.
Because telecomms shouldn't become a game of "How long does it take multiple admins and Pit Boss to fix" or "How one AI stole the airwaves."
:cl:
Linking telecomms machinery together should now function properly
/:cl:

Runtime fix when linking telecomms machinery

---

code/__DEFINES/dcs/signals.dm
code/datums/keybinding/xeno.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm

Adds a hotkey for "Place acid well" - xeno 's ability
Easy access to the use of the ability 
Improving the quality of the game
:cl:
add: Xenomorphs can quickly build acid wells, as well as collapse the top panel with abilities (since all abilities can be used using keyboard shortcuts).
/:cl:

Adds a hotkey for place acid well

---

code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm

leash ball hp 25->75
Currently leash ball is very situational, you need other xenos to be occupying marines so that the leash ball can do its job.
This should hopefully still make the leash ball easy to destroy for marines but also not vanish from getting hit once.
:cl:
balance: leash ball hp 25->75
/:cl:

increase widow leash ball hp

---

code/game/objects/machinery/miner.dm

Miners now render above mobs, changing from this:
To this:
This kinda bugged me, just a minor visual thing.
Magic man floating over miners bad.
:cl:
fix: Mobs no longer render over miners
/:cl:

Miner layer fix

---

_maps/map_files/LV624/LV624.dmm
_maps/map_files/desertdam/desertdam.dmm
_maps/map_files/gelida_iv/gelida_iv.dmm
_maps/modularmaps/big_red/operation.dmm
code/modules/economy/ATM.dm

Cleans up the last remaining few references to Weyland Yutani, replaces them with NanoTrasen.
Also removes all var edited ATMs and slightly changes ATM name to better standardize.
References to Weyland Yutani are bad for lore and legal. Cleaning up the last few remnants that were missed is good. Removing var edits on ATMs and standardizing their name is also good.
:cl:
fix: Weyland Yutani references removed
fix: ATM var edits removed
/:cl:

Weyland Yutani Removal

---

code/game/objects/structures/xeno.dm

Doors have custom ex_acts now. 2 light explosions to kill them, anything heavier qdel's them.
Resin doors are supposed to be fragile, they have low health on purpose to make them worse than walls at defending a position but allow  for better xeno mobility. Them not dying to explosions properly is an oversight to me. But it is a change of balance compared to how it previously was.
:cl:
balance: Resin Doors have proper custom Ex_Acts now, and die to 2 light explosions, heavy and devastation explosions delete them off the face of the universe.
/:cl:

Resin Doors have custom ex_acts now

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm

Title.
Prevents Hivemind shuffle cheese.
Hivemind can now pass through Xenos as well, preventing shuffling of castes (that can result in death occasionally <s>skill issues</s>) and can also heal more easily as hivemind itself cannot be shuffled.
Yes it can stand on a mob to block bullets or stand on marines, but hivemind has negligible HP and its rarely worth it if it actually wants to contribute to the hive.
:cl:
balance: Hivemind can pass through all mobs.
/:cl:

Hivemind now passes through all mobs.

---

code/game/smoothwall.dm
code/game/turfs/closed.dm
code/modules/shuttle/shuttle_rotate.dm

Makes smoothing work for shuttles. This will specifically be effecting the large escape shuttles, but it means it can be extended out to any shuttle including the Alamo etc if desired.
Notably the two shuttles are smoothing together. That's because they're actually two copies of the same shuttle, and so share a smoothing group.
Ideally a second identical shuttle should be made using a new smoothing group to resolve that, but that's a mapping change and I don't feeling like dying right now.
Makes shuttle look less jank.
:cl:
fix: fixed turf smoothing not working for shuttles
/:cl:

Turf smoothing for shuttles

---

code/game/objects/machinery/doors/railing.dm

In some req areas, we get ugly smoothing like this:
Removes this.
Uggo smoothing be gone.
:cl:
fix: Req railing will not longer smooth with walls nearby
/:cl:

Railing smoothing removal

---

code/game/objects/machinery/vending/marine_vending.dm

Title.
Less bloat.
:cl:
del: Removed dupe of TGMC uniform.
/:cl:

Removes dupe TGMC uniform from Clothing vendor

---

code/game/objects/machinery/cic_maptable.dm

Registers an `on_move` signal for observers.
This allows us to close the map when they move too far away.
Fixes broken observer gameplay
:cl:
fix: maptable closes when observers move away.
/:cl:

fix: maptable for observers

---

code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm

Closes #11537
Clean up `handle_living_health_updates` proc.
Add a weed check when the manifestation ends.
Stops hiveminds being able to stay "behind enemy lines"
:cl:
balance: hivemind is shunted back to core when the manifestation dies without weeds nearby
/:cl:

fix: fix hivemind manifestation not returning to weeds

---

code/modules/screen_alert/command_alert.dm

Just replaces the input with a TGUI input, if the player has them enabled.
It allows for the player to preformat their text a little with line breaks making for nicer orders.
https://user-images.githubusercontent.com/1134201/204362870-798e3456-0f82-40af-b545-6612db47da87.mp4
:cl:
code: send order now uses a TGUI input if the player has them enabled
/:cl:

feat: replace send order with TGUI window

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Tier 2 slots will now be calculated correctly.
It was adding the existing t2 xenos to the calculation, so you'd never run out.
Bug fix good.
:cl:
fix: T2 xeno slots being calculated incorrectly
/:cl:

Fixes tier 2 xeno calculation

---

code/modules/projectiles/ammo_datums.dm

Buff mech minigun damage, nerfs AP
I might have made the minigun just straight up worse than the LMG in the last nerf pr, oops
:cl:
balance: Mech minigun damage buffed to 30, AP nerfed to 10
/:cl:

Mech minigun buff

---

code/game/objects/items/reagent_containers/food/drinks.dm

Combat canteen has more possible transfer amounts from inheriting /obj/item/reagent_containers/food/drinks .
Sometimes, marines want to have more measured transfer amount when drinking out of their canteen. possible_transfer_amounts is the same as /obj/item/reagent_containers/glass, which is what beaker inherits from. I would not be surprised if marines make some cocktail of a canteen with this PR.
:cl:
add: Combat canteen has more possible transfer amounts
balance: More options on transfer amounts for combat canteen will inevitably change how marine consume from combat canteen
/:cl:

Combat canteen has more possible transfer amounts

---

code/modules/client/client_procs.dm

So importing a sound as a admin does an admin permission check that didn't actually work.
Changed it to how TG does it, which appears to work fine although I'm too smoothbrain to actually figure out how to turn admeme sounds on in local to actually hear them play.
Probably isn't, but bug fix gud
:cl:
admin: Fixed importing sounds
/:cl:

Fixes imported sounds

---

code/game/objects/items/storage/storage.dm

Alt -right-clicking a storage item will open the menu, just like if you clicked it with the item in hand or drag-and-dropped it to your sprite.
Unfortunately does not work if you have right click context menu enabled, but that does not seem to be the standard here. Just something to note.
Incredibly useful QoL addition. Instantly open any storage item on or around you.
:cl:
qol: Alt-right-click storage items to open them. Does not work if right click opens context menu.
/:cl:

Alt right click opens storage

---

_maps/map_files/LV624/LV624.dmm
_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
_maps/shuttles/tgs_bigbury.dmm
_maps/shuttles/tgs_canterbury.dmm

Patches a handful of known problems, mostly with the Canterbury and its crash locations.
Bugs bad.
:cl:
fix: Adjusted a crash location on LV624 that could crush the green disk generator
fix: Adjusted a crash location on the Pillar of Spring that could destroy the hull of the ship and lead to space.
fix: Changed the button locations on both Canterbury variations so they can't be melted from the outside.
/:cl:

Minor mapping bugfixes

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/rifles.dm

Very minor tweaks I forgot to do ages ago.
Slight reduction on V-31 accuracy, and slight decrease in AP for AP rifle ammo. I guess this also effects PMC SL but they can cope, they still have mega dps due to their damage multiplier.
Reducing the AP as the actual % damage reduction is lower on rifles compared to AP smg ammo, but with the same AP gain.
Also removed an uneeded var.
More comparable scaling for rifle AP ammo.
:cl:
balance: Slight reduction in V-31 base accuracy
balance: Reduced AP rifle ammo AP to 25 from 30
/:cl:

Minor V-31/AP tweak

---

code/modules/mob/living/carbon/xenomorph/hive_datum.dm

Initially in my september PR , a maintainer has raised concerns when using quantitized quantities instead of multipliers on total xeno pop
After a few months of gameplay , the evo tower is still not a good choice , even with big hives they were not used due to the buff being simply too small (20% of 15-20 xenos was still not enough)
I believe not using multipliers is  a better choice , as multipliers can easily get out of control at high-population ,  but remain nigh useless at low-pop
This change aims to make them decent at any pop .
:cl:
balance: Evotowers no longer provide 20% more slots , and instead provide 1 T3 slot and 2 T2 slots for each.
/:cl:

Evo towers now provide 1 T3 slot and 2 T2 slots

---

code/game/objects/machinery/deployable.dm

Deployables objects (telepads, dispensers, etc) can no longer be picked up/undeployed if they're covered in acid.
Fixes oversight where deployables covered in acid can be picked up and redeployed to remove the acid on them.
:cl:
fix: Deployables covered in acid can no longer be picked up
/:cl:

Can no longer pack up deployables covered in acid

---

_maps/map_files/LV624/LV624.dmm

before
after
I've seen many players WASD into this weird chokepoint, look at it, then waggle their way out (me included). It's such a weird chokepoint that I think deserve to be open up. Yes, it is a one tile chokepoint, but now the flow is better.
:cl:
del: Remove a tree south of LV-624 hydro bridge
/:cl:

Remove a tree south of LV-624 hydro bridge

---

code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/mob/living/carbon/xenomorph/attack_alien.dm

Marine item attack uses the final target zone for armor calculation instead of the starting zone
Species apply_damage properly handles being sent a limb datum instead of a zone define
Doesn't really matter in the standard usecase since humans don't actually have random limb miss chance but prevents issues in a nonstandard but possible situation (null defzone).
Stops runtiming when species tries to check armor with a zone that isn't actually a zone
:cl:
fix: Marine on marine violence more fully uses the correct armor
/:cl:

Minor fix to the damage refactor fix

---

_maps/map_files/gelida_iv/gelida_iv.dmm

I cope hard as a mapper and marine player.
before
after
Having walls that force a 1-tile choke which can only be destroyed by plasma cutters and C4 is not good map practice. Since these chokepoints are in the direction of the map (marines push from south to north), these chokepoints are contested very often.
Also, I'm coping hard.
:cl:
del: Remove multiple 1 tile chokepoints in Gelida
/:cl:

Remove multiple 1-tile chokepoints in Gelida

---

code/game/objects/items/robot/robot_parts.dm
code/modules/surgery/robolimbs.dm

Currently, the limb replacement surgery does not work with radial - you need to both select the right part on the radial AND select the right part on the targeting doll with the prosthetic. This corrects that, you now only need to select the correct radial part if using radial.
:cl:
fix: Limb replacement surgery's attach prosthetic step now works with the radial menu.
/:cl:

Makes limb replacement surgery respect radial choice

---

code/game/objects/items/scanners.dm
tgui/packages/tgui/interfaces/MedScanner.js

This PR makes changes to the GUI for healthanalyzer, to correct the following usability issues.
1. If any limb was infected, every limb was labelled as infected. Now, only the specific limb is is labelled.
2. Limbs who where infected or necrotizing were not marked as such unless they had another condition. Now, they are labelled.
3. If a limb has necrosis, it suppressed the limb being labelled with infected. Now, they are separate (This is important because limbs can have necrosis while not being infected).
Due to the above oddities with the GUI, infections seemed to exhibit strange behavior. This should make it more clear to the user what is happening. 
:cl:
fix: Heath analyzers are now more clear about what limbs have infections and necrosis.
/:cl:

GUI Fix for medical analyzer's display of infections/necrosis

---

code/modules/mob/living/silicon/ai/ai_verbs.dm

The AI has a shutdown systems verb, which is just a fancy ghost button. I don't know why that thing exists, but I improved it a little. 
This PR : 
- Added another confirm to prevent accidental ghosting
- Added icon reset for core, so you go back to default AI looks
- Added Announcement for whenever that happens, so people know you shutdown for some reason
- Added Admin message, so they know the AI ghosted. 
I tested the PR and had no significant issues.
Just makes the game plain better.
:cl:
qol: made AI ghosting harder to do accidentally, look better, and notify marines of the fact
admin: made AI ghosting notify admins
/:cl:

Improve AI shutdown verb

---

code/game/objects/items/circuitboards/computer.dm
code/game/objects/machinery/overwatch.dm
code/game/objects/machinery/squad_supply/supply_console.dm
code/modules/reqs/supply.dm

All req computers were given circuit boards so they can be rebuilt if an unga ever blows them up. This is not a balance change since xenos cannot use grenades. Slashes can already be repaired with a blowtorch.
Split from #11729
I don't want to ask admins to fix the req computers whenever they are hit by a grenade.
:cl:
add: Req consoles can be repaired after friendly fire.
/:cl:

req consoles can be rebuilt

---

code/__DEFINES/cooldowns.dm
code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
tgui/packages/tgui/interfaces/MechVendor/MechAssembly.tsx
tgui/packages/tgui/interfaces/MechVendor/data.ts

Increase cooldown on crafting mechs to 1 minute each.
Additionally updates the display to show when its busy.
There is currently no limit to how many you can spam.
No external resources used or anything.
This will slow the spam of mechs, until a proper solution can be implemented.
:cl:
balance: mechs now take a minute to build
/:cl:

balance: increase cooldown on mech computer

---

code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm

title
WARLOCK'S BRAIN IS SO BIG HE CAN TELEPATHICALLY TALK TO MARINES AND TELL THEM, "COPE AND SEETH!" WHEN WARLOCK BLASTS THEM WITH ITS MIND! BEAT MARINES WITH PSYCHIC POWER?! MORE LIKE CRUSH MARINES THROUGH PSYCHOLOGICAL OPERATION!!
Due to how psychic whisper bypasses admin's oversight, I gave admins the ability to see what kind of message the xenomorph is sending to a marine.
:cl:
add: Give Warlock psychic whisper
add: admins can now read psychic whisper
/:cl:

Give Warlock psychic whisper

---

code/modules/client/client_defines.dm
code/modules/client/preferences_ui.dm
code/modules/tgui_input/say_modal/modal.dm
code/modules/tgui_input/say_modal/speech.dm
code/modules/tgui_input/say_modal/typing.dm

Title.
Currently, typing indicators will always show up, regardless of preference settings, due to client having a var that determines whether they show up, but this var having nothing hooked into it to change it regardless of the pref existing. This removes that redundant var and hooks the checks back into preferences directly (since clients should always have preferences attached).
Preferences actually doing what they say they do tends to be a good thing.
:cl:
fix: The 'show typing indicator' pref should be functioning properly once again.
/:cl:

Fixes the "show typing indicator" pref

---

code/modules/mob/living/carbon/human/human_defense.dm

Queen screech gives stagger
The ability is better used against larger groups of marines , by providing them with the damage debuff , instead of it currently being used on solo marines to secure easy kills.
:cl:
balance: Queen screech now gives a maximum of 15 stagger , adjusted based on distance , with the minimum being 3.
/:cl:

Queen screech now gives stagger

---

code/modules/projectiles/ammo_datums.dm

Fixes Bonus projectiles incorrectly applying gun bonuses, leading to situations like masterkey buckshot getting its damage reduced twice.
Sidenote: I don't want to feature creep the PR, but masterkey falloff is completely wack. Buckshot specifically loses 8 damage per tile. Which means even if you PB a xeno, you've already lost a THIRD of your damage, while at 3 tiles away you do literally no damage at all.
Bug fix good.
:cl:
fix: fixed bonus projectiles stacking gun bonuses incorrectly
/:cl:

Fixes for bonus projectiles

---

code/modules/projectiles/ammo_datums.dm

The sadar pr changed the max range for the base rocket ammo, leading to some ammo types (notably AT ammo) getting their range inadvertently cut in half.
Bug fix good.
:cl:
fix: fixed some rockets having far lower range than they should
/:cl:

range fix for some rockets

---

code/modules/vehicles/mecha/mecha_defense.dm

There's code in place to prevent repairing mechs more than once at a time by any given person but it doesn't work if you trigger a skill delay. Fixes that
bug bad
:cl:
fix: You can only repair mechs one attempt at a time per person
/:cl:

Fixes mech repair spam

---

code/modules/vehicles/mecha/equipment/weapons/weapons.dm

mech reload via UI now takes 2 seconds just like normal autoreload
Reloading weapons via UI is easily abusable and should take time just like normal autoreload.
:cl:
balance: mech UI reload now takes time
/:cl:

mech UI reload takes time

---

code/modules/mob/living/carbon/human/species.dm

title
that ain't it, chief
:cl:
add: update death message and pray you have your head on when you died
fix: update death message to reflect that you can survive a chestburst
/:cl:

update death message to reflect that you can survive a chestburst

---

code/modules/projectiles/ammo_datums.dm

Entirely removes the shake effect from ammo code. No ingame impact.
The shake effect of certain projectiles was made entirely nonfunctional a while ago, but some of the associated code was never removed.
Also removes the masterkey buckshot from the code, which hasn't been used for a very long time.
Clean code good.
:cl:
code: Cleaned up some unused code for ammo
/:cl:

ammo code cleanup

---

code/game/objects/items/explosives/grenades/marines.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm

Adds duration as a var to smoke nades, instead of being hardcoded to 11 seconds.
Reduced Sentinel nade duration to 5 seconds (it was supposed to be set at 2 seconds)
Magic number bad.
Bug fix good
:cl:
fix: fixed sentinel gas grenades lasting longer than they should
/:cl:

Smoke nade duration var and sentinel primo fix

---

code/game/objects/effects/temporary_visuals/miscellaneous.dm

CAS GAU now uses flick for it's animation. This means that the animation will actually start when that particular tile is hit, rather than them all being confusingly in sync even though they are hit at different times.
Clearer visuals
:cl:
add: CAS GAU animation behaves more sensibly
/:cl:

CAS visual fix

---

code/datums/status_effects/xeno_buffs.dm
code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm

Reduces Drone, Queen and Hivelord sunder heal from abilities.
Drone and Queen 10 > 5
Hivelord 1.8 > 1.5 per tick.
I was a bit too generous with sunder heals in my initial PR. Queen and Drone gets their sunder heal reduced because their abilities have only 5 second cooldown. Hivelord infusion reduced slightly because it has been buffed over years. Shrike and Hivemind heal stays same at 10 sunder because their abilities have a 60 second cooldown.
:cl:
balance: reduced sunder heal for drone, queen and hivelord abilities.
/:cl:

sunder heal nerf

---

code/game/objects/items/tools/soldering_tool.dm

Soldering tool now works like welder and cable coil where it'll repair the next damaged limb until it's done
I'm lazy
:cl:
qol: soldering tool repairs the next damaged limb
/:cl:

Soldering tool repairs the next damaged limb

---

code/modules/client/client_procs.dm

What it says on the tin. They were configured incorrectly after the tgui say port.
Bind work good
:cl:
fix: fixed XOOC and MOOC binds incorrectly opening LOOC
/:cl:

Fix MOOC and XOOC binds

---

code/game/objects/items/storage/pill_packets.dm

Changes the capacity of the tricordazine and dylovene pill packets from 6 to 8.
Standardizes these two meds to the 8 capacity all of the other pill packets have. Tricord and Dylo are not game-breaking chems and shouldn't have reason to have less capacity then the other meds.
:cl:
balance: Tricordazine and Dylovene pill packet capacity changed from 6->8
/:cl:

Tricord/Dylo pill packet capacity 6 -> 8

---

code/datums/actions/xeno_action.dm
code/modules/codex/entries/mobs_codex.dm
code/modules/mob/living/carbon/xenomorph/abilities.dm
code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
code/modules/mob/living/carbon/xenomorph/charge_crush.dm
code/modules/mob/living/carbon/xenomorph/evo_datum.dm

Adds descriptions to buttons of xeno abilities, makes codex use _desc_ variable rather then _mechanics_text_, and removes _mechanics_text_ variable.
Makes more easy for new players to understand what abilities do
:cl:
qol: Adds descriptions for buttons used by xeno abilities
/:cl:

Adds descriptions to xeno ability tooltips

---

code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm

Minor QOL for some hotkeys to ensure they update immediately, useful if you're unfamiliar that crush and shield have follow up activations.
Clearer buttons good.
:cl:
qol: Warlock action buttons should reliably update immediately on state change
/:cl:

Warlock QOL changes

---

code/game/objects/structures/teleporter.dm

Improved the engineer teleporter's description
Fixed some 'The the' issues
Made it possible to link 2 teleporters.
QoL and better info. 
Paving the way for buying single teleporters.
:cl:
qol: Created the possibility to link 2 engineer teleporters
qol: Removed 'The the' issues on engineer teleporters
qol: Made examining engineer teleporters with no cell tell you that fact
qol: Engineer teleporters now have unique #123 names. 
fix: Made engineer teleporters properly unlink when one is destroyed
/:cl:

Improves engi teleporters slightly

---

code/modules/mob/living/carbon/xenomorph/update_icons.dm

Instead of using a signal to set the dir of the wounds overlay, we can just use the vis_flags of inherit dir from parent.
Additionally using the vis_hide flag for wounds when they have nothing to show.
This helps remove them from the right click menu (but they will return when xenos are hurt).
Just a cleanup
:cl:
code: removed an extraneous signal
refactor: hide xeno wounds when they have nothing to show
/:cl:

feat: use vis flag to determine direction

---

code/game/objects/items/tools/soldering_tool.dm
code/modules/power/cable.dm

1. A solder or cable coil B
2. B move away from A
3. A is still soldering/cabling
What should happen is A should stop like with Blowtorch.
Honestly, I didn't even know you can do that with cables.
:cl:
fix: long range solder and cable
/:cl:

Fix long range soldering and cabling

---

code/game/objects/items/storage/storage.dm

Unequipping storage into a full hand would remove it from any of your inventory slots but keep it inside the mob, where it was more or less stuck.
Fixes #11839 
:cl:
fix: Dragging equipped storage into an occupied hand won't leave the storage stuck unavailable
/:cl:

Fixes storage getting stuck in mobs

---

code/modules/reagents/reagents/medical.dm

Reduces cryo fracture healing from one bone every 2 seconds to one every 10 on average. 'On average' because it runs on a prob(20). The fix is guaranteed if the limb has enough brute damage to just break again, because crunchtube is important.
>Why not just count ticks and fix it after a specific amount?
The way cryo injects reagents over time means that bhj isn't guaranteed to be in the body every tick. It'll run out after a bit and you'll get another dose a little later, so if healing duration was tracked on the chem it'd frequently reset without doing anything.
>What about tracking it on the limb then?
That builds complications into the question of 'is a limb broken', which is honestly annoying enough to answer as is, and sticks a system on them which is used entirely for one chem.
Not …

Slows down cryo fracture healing

---

code/modules/mob/living/living_defense.dm

You now spin while stop drop rolling. 3 seconds of duration, same as paralyze, 1.5 abstract time value for time between direction spins.
Presumably this should pop an error out considering it's a signal handler and there's sleeps in spin(), but there weren't any so who knows. I'll invoke_async if told to.
:cl:
add: You now spin while stop drop rolling.
/:cl:

You now spin while stop drop rolling.

---

code/modules/vehicles/mecha/equipment/mecha_equipment.dm
code/modules/vehicles/mecha/equipment/weapons/weapons.dm
code/modules/vehicles/mecha/mecha_defense.dm

Now mech weapons keep 1 integrity on destruction like they were intended to.
Mech weapons dont detach from taking damage.
Fixed few related runtime errors.
Fix good
:cl:
fix: mech weapons dont detach from taking damage. fixed a few related runtime errors.
/:cl:

Mech weapons dont detach on destruction

---

code/game/objects/structures/patrol_points.dm

Adds spawn protection when you deploy to the ground in Combat Patrol and Sensor Capture. For 10 seconds you have godmode. This may need to be tweaked if you can sprint to anything important in that time.
I got tired of watching ungas mindlessly deploying 1 by 1 into a Denholm spawn camp they know about, rather than using their brain (and map table) and just deploying to the 2nd spawn point.
As I can't cure ungabrain, I'll have to settle with this.
Removes some salt from people being dumb.
Also spawn camping is cringe.
:cl:
balance: HvH: You have 10 seconds of spawn protection when deploying groundside
/:cl:

HvH spawn protection

---

code/game/objects/items/explosives/grenades/grenade.dm
code/game/objects/items/explosives/grenades/marines.dm
code/modules/projectiles/guns/grenade_launchers.dm

Adjusted sticky nade det time when fired from a GL from 1 second to 3-5 seconds.
Currently, all nades fired from a GL have their det time hard set to 1 second, giving a (very) small window to try avoid the blast.
Stickies are a bit difficult because they, well, stick, making them a guaranteed wombo combo tool.
This makes more of a trade off between normal grenades with a larger radius and shorter det time for that immediate staggerslow, and stickies with their guaranteed hit (if you hit initially) but longer det time.
This can also be used to individually tweak det times for specific grenades, if required.
Make stickies a bit less unpleasant to deal with.
:cl:
balance: Sticky grenades detonate after four seconds instead of one second, when fired from a grenade launcher
/:cl:

Grenade launcher tweak

---

code/datums/quick_load_outfits.dm
code/modules/clothing/modular_armor/attachments/modules.dm
code/modules/clothing/modular_armor/modular.dm

Bit of an experiment to see how it changes the game.
Adds eshields to all default loadouts (i.e. loadouts that don't already have another module), excluding engies and medics.
This should add a level of survivability, and especially help against plinking hits/surprise attacks.
Also removes the weird -5 bullet armour. There was no negative for any other human specific armour types so it never really worked, and 'you get FF'd worse' is a pretty meme idea anyway.
More survivability in HvH
:cl:
balance: eshields no longer have -5 bullet armour
balance: HvH: eshields added as default modules for roles other than engie and medic, where another module is not present
/:cl:

HvH E-shields

---

code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm

Reduces radius from 4 to 3, and duration from 5 to 4.
Currently the radius is the same as an ancient boiler, but bypasses barricades because it's thrown.
This makes it rather good at providing a smokescreen for xenos that apply guaranteed staggerslow to anyone that goes into it, while it's very safe to use due to it's radius and instant cast.
Slightly less oppressive stagger smoke.
:cl:
balance: Reduced sentinel grenade radius and duration by 1 tile and 1 second respectively
/:cl:

Sentinel nade tweak

---

code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm

Fixed a bug where vampirism would separetely heal both brute and burn for 25% of total health lost, effectively meaning the heal could be 200+ health.
Reduced the heal amount to 12.5% from 25%.
25% heal every 2 seconds is simply not balanced, even without the bug, especially taking into account endure and (super) rage.
I'm not entirely happy with the vampirism mechanic because it's essentially passive, but the previous one was trash.
Bug fix good.
Having a queen healing you every 2 seconds bad.
:cl:
balance: Reduced Ravager vampirism healing by 50%.
fix: fixed Ravager vampirism healing more than it should
/:cl:

Primo rav fix and adjustment

---

code/__DEFINES/objects.dm
code/game/objects/items/tools/maintenance_tools.dm
code/game/objects/items/weapons/shields.dm
code/game/objects/machinery/deployable.dm
code/game/objects/objs.dm
code/game/objects/structures/barricade.dm
code/modules/vehicles/atv.dm
code/modules/vehicles/mecha/mecha_defense.dm
code/modules/vehicles/motorbike.dm
code/modules/vehicles/unmanned/unmanned_vehicle.dm

Probs TM first.
Repairing anything object with a welding tool will now chain repair until you run out of fuel or it is fully repaired.
Refactored object repair to use a single proc, instead of the same thing being done is 10 slightly different, inconsistant ways.
Fixes some repairs not actually causing eye damage, and a few other minor bugs.
There may be a couple of minor fumble time changes as part of making everything consistent.
Also fixed plasteel cade code to use tool act procs instead of attack by.
Less duplicate code, code actually checking everything it should.
:cl:
balance: Repairs with a welder will now chain repair, fumble is only done once per chain
refactor: refactored welding repair code
refactor: refactored plasteel tool interactions
/:cl:

Repair refactor/QOL

---

code/game/objects/items/reagent_containers/autoinjectors.dm

Combat injectors now come with 5u of tricordrazine instead of 5u of dylovene.
Alternative to #11830 so as to make combat injectors not chop stamina regen by half due to the dylov in it. Would make dylovene its own toxin-dedicated med.
:cl:
balance: Combat injectors now have tricordrazine in replacement of dylovene.
/:cl:

Changes dylovene to tricordrazine in combat injector

---

code/game/objects/items/scanners.dm

Per title, lowered from PRACTICED to NOVICE.
Primarily aimed at making SL's able to use medscanner without fumble. SL is given med skill to use defibs, but surprisingly isn't able to use scanner in lieu of this. SL is a supportive role that can dabble in the basic aspects of the other jobs in order to fill needed roles. I'd argue that being able to use medscanner is a basic skill that SL should have to assist in healing, especially given they are vended a free medhud and have medical access for meds.
As to the other jobs affected, I am pretty sure they are all not in the game so it shouldn't affect anyone except SL. However the datums are hard to read since the skill ratings are numerical, so let me know if anything else is affected.
:cl:
balance: SL able to use medscanner without …

Medscanner skill threshold lowered to novice. Allows SL to use medscanner without fumble.

---

code/_onclick/hud/ghost.dm

Adds a confirmation for returning to your corpse if you are in the larva queue, so you wouldn't accidentally go out of it. It appears only if you are in the larva queue, and if you are not it works as before.
People wouldn't accidentally loose their position in the queue if they unintentionally click on the corpse returning button or due to not knowing that returning to their corpse will make them out of it.
:cl:
qol: Returning to your corpse while being in larva queue will require a confirmation, so you wouldn't accidentally loose your place.
/:cl:

Confirmation for return to corpse if you are in larva queue

---

code/game/objects/machinery/kitchen/smartfridge.dm
tgui/packages/tgui/interfaces/SmartVend.js

Fridges now generate/alter their storage lists when something is added or removed instead of every time the ui updates
Fridges clean names to prevent weirdness with "\improper Thing" and "Thing" being equal some times and not other times
Minor opt, fixes #11893 
:cl:
fix: Vended reagent bottles can be taken back out of the chem smartfridge
/:cl:

Small chemfridge refactor

---

code/modules/requisitions/supply_export.dm

Inflation adjustment for selling shrike.
I observed that when I sold shrike, its price was 50 req points, meaning that the shrike cost the same as a single smartgunner T-29 drum. MJP did not know that there was a dedicated code that shrike sold separately than what is usually sold as a T4. A shrike is a T4 and yet is sold as a T3.
:cl:
fix: Shrike req points 50->500
balance: Shrike req points 50->500
/:cl:

Balance Fix: Shrike req points 50->500

---

code/game/objects/items.dm
code/game/objects/items/marine_gear.dm
code/game/objects/items/radio/headset.dm
code/game/objects/items/storage/backpack.dm
code/game/objects/items/storage/belt.dm
code/game/objects/items/storage/holsters.dm
code/game/objects/items/storage/pouch.dm
code/game/objects/machinery/vending/new_marine_vendors.dm
code/game/objects/machinery/vending/vending.dm
code/modules/clothing/clothing.dm
code/modules/clothing/modular_armor/attachments.dm
code/modules/clothing/modular_armor/modular.dm

Vendors will now try to insert spawned items into the player's currently opened container, before trying to put them into their hand.
For instance, you can open your ammo belt, vend 6 mags, and they will be auto-inserted into the belt, without you having to manually click them each in.
Does not affect the auto-closet, which still attempts to auto-equip relevant items.
Reduces repetitive clicking to fill storages during prep.
:cl:
qol: Vendors will try to insert vended items into the player's currently opened storage. Does not affect Automated Closet.
/:cl:

Vendor QOL #2

---

code/modules/vehicles/mecha/mecha_mob_interaction.dm

Mech pilot now cant enter the mech while wearing jetpack. Also pilot will drop items in hands to prevent cheese.
Mech pilots can escape easily on mech destruction, which encourages reckless pushes with little to no risk of being killed. Inability to wear a jetpack makes pushes actually dangerous and punishable.
:cl:
balance: mech pilot cant enter the mech while wearing jetpack, and will drop items in hands on entering the mech.
/:cl:

MP cant enter the mech with jetpack of his back

---

code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
code/modules/mob/living/carbon/xenomorph/damage_procs.dm
code/modules/projectiles/ammo_datums.dm

Minor buff to primo spitter to give it a bit more area control/flavour.
Primo spitter's autofire spit now leaves acid pools on hit (like prae already does), and primo spitter now has acid blood, which is more flavour than anything, but reinforces the 'acid guy' theme.
Autospit now has the explosive flag like most spits (i.e. lands where you click).
Reduced damage fall off from 1 to 0.3 since it has almost the worst falloff in the game considering its base damage.
Also fixed a bug where acid pools on hit will bypass obstacles like cades, or entirely solid ones like glass panes etc.
And fixed a bug and reworked acid blood. Currently there is a splatter chance that... does nothing. And the splatter itself didn't respect acid armour either.
More interesting spitter primo than "shoots fast". …

Primo spitter tweaks

---

_maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm

Add more soul to medbay break room.
Allow chemists to reach to fridge.
Remove funny dropship landing on medbay that allow xenomorphs to fling marines to space.
Add back the crew monitoring computer back.
Sometimes, mappers didn't see mistakes, and players give feedback to improve map.
:cl:
add: more soul to POS medbay break room.
fix: Allow POS chemists to reach to fridge.
del: Remove funny dropship landing on POS medbay that allow xenomorphs to fling marines to space.
fix: Add back the crew monitoring computer back in PoS
/:cl:

PoS Medbay Fixes

---

code/modules/projectiles/guns/revolvers.dm

SAA has a bit higher damage (10% more damage) than normal revolvers.
Mateba and revolvers in geneal have significantly less screen recoil, and recoil.
Revolver scatter in general normalized to TP-44 levels (15), revolvers with revolver/small bullets normalized to 12 (CMB and Nagant Revolver)
Mateba has better gun accuracy stats.
Mateba and SAA are pretty much worse than normal revolver due to poor handling stats, and revolvers in general no longer should have as much screenshake considering the stat has been entirely reworked compared to the last time the stat was set.
:cl:
balance:Revolvers in general have less screenshake, and scatter. mateba has better accuracy. SAA has a bit of extra damage compared to stock revolvers.
/:cl:

Mateba, General revolver changes and SAA buff.

---

code/datums/loadout/item_representation/gun_representation.dm

Fixes loadout vendors not vending guns with starting attachments unavailable in the weapon vendor separately.
i.e. GL-54 scope, AR-11 scope etc.
Fixes #11837
Fixes #11776 
Fixes #10365
Fixes #8335
Note:
I've seen some people have an issue with stocks not spawning on their guns. I have no idea if that is related as I can't replicate it, but just noting that this isn't regarding that particular issue.
Bug fix good.
:cl:
fix: fixed loadout vendors not vending weapons with certain default attachments
/:cl:

Loadout attachment fix

---

code/_globalvars/lists/flavor_misc.dm

Fixed warlock having no icons in some places, like lower hive status panel or observe panel.
Before: 
After:
Fix good.
:cl:
fix: fixed warlock having no icon in some interfaces
/:cl:

Warlock observe hud fix

---

code/modules/projectiles/ammo_datums.dm
code/modules/projectiles/guns/shotguns.dm
code/modules/projectiles/magazines/rifles.dm

Removes some unused or redundant code that annoys me every time I see it.
Also makes a few consistancy changes, like additional flech having different falloff and pen values from the base ammo for no apparent reason, something which doesn't occur for other types of flech.
Lastly removed the double falloff multiplier from the masterkey. Because falloff is linear, masterkey having a large damage reduction meant the increased falloff reached rediculous levels, such that buckshot will stun someone at 3 tiles away, but do ZERO damage.
code cleanup good.
Funny buckshot doing zero damage bad.
Consistant ammo behavior good.
:cl:
code: Some minor ammo code cleanup
balance: Standard flechette now has consistant AP and falloff between the main and addition flechette projectiles
balance: Masterkey no …

Minor ammo cleanup and walance changes

---

_maps/map_files/generic/Admin_Level.dmm
code/game/objects/machinery/vending/marine_vending.dm
code/modules/clothing/glasses/glasses.dm
code/modules/clothing/glasses/night.dm
code/modules/reqs/supplypacks.dm

Per title. Removes Optical Imager Goggles entirely from the code, removing them from the game by extension.
My argument for this one will be a little weak since it is maintainers that have come to dislike imagers, but I will go ahead and say that imagers are in a difficult spot at the moment. They are incredibly sought after in requisitions, and prove to be one of the most common purchases; there's certainly an issue when any given marine refuses to deploy without their funny vision enhancer.
This PR is open at the same time that #11888 is; both were meant to be in the same PR, but I found it a more sensible choice to separate these into two PRs, so as to give maintainers options to choose from.
:cl: Lewdcifer
del: Removed Optical Imager Goggles from the code and the game.
/:cl:

Removes Optical Imager Goggles from the game

---

code/modules/projectiles/guns/energy.dm

Per title. Laser Pistol's wielded slowdown has been reduced from 0.75 to 0.
Someone probably overlooked the parent's slowdown when doing this.
Why in tarnation does a sidearm have the equivalent wielded slowdown of a laser rifle? In fact, why does a sidearm even have slowdown in the first place?
:cl: Lewdcifer
balance: Laser Pistol wielded slowdown reduced from 0.75 to 0.
/:cl:

Laser Pistol no longer has wielded slowdown

---

code/modules/shuttle/cas_plane.dm

Per title.
I am getting so tired of the classic PO griefing the round for whatever reason.
:cl: Lewdcifer
fix: CAS is no longer usable before shutters open, or before Tadpole launches.
/:cl:

CAS can no longer be launched before shutters open, or before Tadpole launches

---

code/game/objects/items/explosives/grenades/marines.dm
code/game/objects/items/flashlight.dm
code/game/objects/items/storage/boxes.dm
code/game/objects/items/storage/pouch.dm
code/modules/projectiles/guns/grenade_launchers.dm

Sponsored by the cabal.
Have you ever wanted to obliterate xenos?
Have you ever wanted to farm salt off of xenos?
Seek no further. The cabal provides.
The following changes have been made:
- Flare packs (including CAS flares) have had their inventory size reduced.
- Flare packs can now hold a maximum of 14 flares.
- All flares have had their inventory size reduced.
- Flare pouches can now hold a maximum of 28 items.
- Flare guns can now be tactically reloaded with a flare pouch by right clicking it.
- Flare guns have had their inventory size increased, but it still fits in flare pouches.
Flares have sucked for the longest time, and this feels like a neat way to enhance marine visibility.
As discussed with @TiviPlus in the Discord, flares should be very spammable but easily dealt with. …

Buffs M40 FLDP grenades and their related storage options

---

code/modules/reagents/reagents/toxin.dm

Per title. I forgot to remove this when I was debugging. Whoops.
Admemes do not get spammed with debugging messages they don't care about.
:cl: Lewdcifer
fix: Removed a stray admin message, left there by Sentinel debugging.
/:cl:

Removes a stray admin message from Sentinel debugging

---

code/__DEFINES/mode.dm
code/datums/gamemodes/sensor_capture.dm
code/game/objects/structures/sensor_tower.dm

The Game timer is now paused when a tower is activating, and restarts when the tower fully activates or is disabled.
This makes it much easier for marines to actually try and win, without getting fucked on by the timer.
The additional time granted by capping a tower has been reduced to 5 minutes. I'll like tweak this timer and/or the capture times themselves in the future however.
Less frustrating losses when winning the game, more enjoyable rounds for both teams.
:cl:
balance: Sensor Capture: the game timer pauses while towers are being activated
Balance: Sensor Capture: reduced the additional game time for activating a timer to 3 minutes
/:cl:

Sensor cap timer change
